### ISSUE TITLE
In the Solution Explorer, right-click on the project > Add > New Scaffolded Item, menu item is missing.

### ISSUE THREAD

**Issue by dumaisf** [aspnet/AspNetCore.Docs#10024]
I'm using:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.1
ASP.NET Core 3.0 Preview 1 (SDK 3.0.100-preview-009812)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try the released version the tutorial suggests.

**Comment by dumaisf** [comment]
Where is the link?

**Comment by dumaisf** [comment]
Scaffolding does not work with ASP.NET Core 3.0 preview 1, I went back to ASP.NET Core 2.2

**Comment by kofifus** [comment]
Why us this closed ? is there any update on scaffolding in ASP.NET Core 3.0 ?

**Comment by Zero2Cool** [comment]
![image](https://user-images.githubusercontent.com/5612416/61341101-a6051100-a80a-11e9-8d86-331c5f0092c8.png)

VS2019 Enterprise 2019 16.1.6  
ASP.NET Core 3 Preview 6

**Comment by Rick-Anderson** [comment]
This is a know problem in the current preview. I'm not sure it's fixed in the next.

**Comment by Rick-Anderson** [comment]
Fixed in GA version
