### ISSUE TITLE
Add content for migrating app to ASP.NET Core piecemeal

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore.Docs#10033]
A common pattern we've seen when migrating your app from ASP.NET to ASP.NET Core is to create an IIS sub-application and only move certain routes from ASP.NET to ASP.NET Core while preserving the URL structure of your application.

We should update this doc to mention this pattern and how to accomplish it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@shirhatti 	can you provide a first draft? We don't have anyone with the expertise for this task.

**Comment by shirhatti** [comment]
Relevant section from applicationHost.config

```xml
<sites>
    <site name="Default Web Site" id="1" serverAutoStart="true">
        <application path="/">
            <virtualDirectory path="/" physicalPath="D:\sites\MainSite\" />
        </application>
        <application path="/api" applicationPool="DefaultAppPool">
            <virtualDirectory path="/" physicalPath="D:\sites\netcoreapi" />
        </application>
        <bindings>
            <binding protocol="http" bindingInformation="*:80:" />
            <binding protocol="https" bindingInformation="*:443:" sslFlags="0" />
        </bindings>
    </site>
	...
</sites>
```

Directory structure on disk 
```
.
├── MainSite
│   ├── ...
│   └── Web.config
└── NetCoreApi
    ├── ...
    └── web.config

**Comment by pandagopal** [comment]
My Web Application uses ADO.Net heavily, and Each Stored Proc sends either 3 more Result sets. The problem is there is no such equivalent in .Net Core. For everything we cant go on making class and properties .
