### ISSUE TITLE
Please include details to use Identity for WebApis

### ISSUE THREAD

**Issue by Praveen-Rai** [aspnet/AspNetCore.Docs#10064]
Presently, the samples and instructions for using Identity services are focused on MVC apps. Few question remains un-answered. Can Identity services be used with webApis ? If yes, a sample would be much appreciated.

I've searched else where and almost all of them use third party tool/library to secure webApis such as IdentityServer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Praveen-Rai** [comment]
@Rick-Anderson Thanks for pointing to original Issue. I just read through and here too it seems like that ASP.Net Core Identity is applicable to MVC only, for WebApi's we need third party schemes. If that's correct can we please update this information to the page ?

**Comment by Rick-Anderson** [comment]
Per `@HaoK`
There's a bit of conflation here, and there are two parts of identity, users/roles and that stuff is applicable everywhere, identity by default uses cookies to store that info, so its that piece that is not applicable to WebAPI, so they would have to do the work to use identity to login/etc, and then typically generate a bearer token (which is why IdentityServer/OpenIdict is used there).  

We are also integrating identity server with identity:
https://github.com/aspnet/AspNetCore/issues/5833

**Comment by Praveen-Rai** [comment]
@Rick-Anderson Thanks for the clarification. I think this piece of information is important and the scope of Identity needs to be explicitly mentioned.  I would request  a simple sample too on how to integrate any Token Provider / Validator can be combined with Identity. If not sample may be just a bit of overview of the integration of the two systems.

**Comment by Praveen-Rai** [comment]
As we are already working on integrating IdentityServer and Identity i hope we are going to have a good details after work is finished. So, may be for now we can have a sort of quick fix on the existing articles to make the scope of Identity clear and redirect WebApi creators to IdentityServer.

Your thoughts ??

**Comment by Rick-Anderson** [comment]
Ping me early next year and I'll see what I can do.

**Comment by Praveen-Rai** [comment]
@Rick-Anderson, greetings and wishes for the new year !!

Can we update the doc to explicit mention that Asp.Net Core WebAPI projects needs to have bearer token generation Server, along with a sample ?

**Comment by Rick-Anderson** [comment]
@danroth27 - @blowdart We've lost @CamSoper so we need someone from the PU to write the draft and sample code. Can you schedule this? See also #4556

**Comment by blowdart** [comment]
Well it's still not available so it's low on my concern list until we have a beta

**Comment by Praveen-Rai** [comment]
@blowdart That's why we must atleast mention that third-party providers are required for WebApis, along with a few suggested providers. Just the way we did in [logging section ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#third-party-logging-providers)

**Comment by Praveen-Rai** [comment]
@Rick-Anderson I found [this blog post](https://blogs.msdn.microsoft.com/webdev/2017/01/23/asp-net-core-authentication-with-identityserver4/), in which the author demonstrates ASP.Net core Authentication using IdentityServer4. @blowdart , in this blog-post the author mentions about connecting ASP.Net Core Authentication with IdentityServer4. Is this something different from what you've been referring to ?

For your reference here's another post [Asp.Net Authentication using OpenIddict](https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/)

**Comment by Praveen-Rai** [comment]
@Rick-Anderson @blowdart Any updates ? I couldn't find any related changes in .Net Core 3.0 Preview 3.

**Comment by wewald** [comment]
@Rick-Anderson I see you wanted to wait until the beginning of 2019 to address how to connect a Web API to the .net Identity Framework.   Can you point us to some help for this?

**Comment by Rick-Anderson** [comment]
It will be announced here. @blowdart owns it.

**Comment by wewald** [comment]
@blowdart I'm hoping you can identify where we are on this.  It would seem to me that passing the U&P through the header in a TSL protected HTTPS post would have the same security as any other web request so no 3rd party is needed.  We just need to know how to connect from the api to dotnet Identity Framework so we can authenticate and authorize users who are already in our database (i.e., we already use Identity Framework for our website so we have users but now we want to add an api in dotnet core).

**Comment by wewald** [comment]
@blowdart It would be great if you could provide direction on how to do this with the latest version of dotnet core on Azure which I believe is 3.0 (including what package versions to have installed).

**Comment by blowdart** [comment]
Even the real answer in 3.0 is "Use identity server, and here, we put it in the box for you". I'm not about to comment on the validity of any other approach.

As the template in 3.0 is currently very early alpha and looking for feedback, documentation is somewhat down the list of things to do.

**Comment by wewald** [comment]
With .net Core 3.0 in very early alpha, can we get a working version of a connection from an Azure API to authenticate and authorize users via .net Identity Framework in the last version of .net Core which is at this point "mature"?

**Comment by blowdart** [comment]
I don't believe the docs repo is the right place to ask about features. Frankly I'm unsure what you're asking for here. There's no .NET Identity Framework, an Azure API isn't something we have templates for (and I can't tell if you mean an API that azure offers, or an API you host on azure).

If this is not, as I suspect, a docs issue, then the [aspnet repo](https://github.com/aspnet/AspNetCore/issues) would be a better place to ask feature questions.

**Comment by mkArtakMSFT** [comment]
Closing this as there is no more action pending here from us.
