### ISSUE TITLE
Add VS and CLI tabs for migrations

### ISSUE THREAD

**Issue by rcroeder** [aspnet/AspNetCore.Docs#10142]
This page uses 
dotnet ef migrations add RowVersion
dotnet ef database update

However the second line failed. When using the same format from the Migrations section it worked well. Below worked. 

Add-Migration RowVersion
Update-Database

From hunting around, additional tools need to be installed before dotnet ef will work. This article describes issue.

http://errummwelluhh.blogspot.com/2017/01/no-executable-found-matching-command.html#!/2017/01/no-executable-found-matching-command.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The following are CLI commands run from the command line:
```
dotnet ef migrations add RowVersion
dotnet ef database update
```

You run the following from the PMC
```
Add-Migration RowVersion
Update-Database
```
