### ISSUE TITLE
HTTP/2 enabled by default in 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10141]
Also for:

* Kestrel
* Host and deploy: IIS Overview
* Performance Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@Tratcher @halter73 Reviewed our current HTTP/2 coverage. If the following remarks are good, then we can close this issue.

1. In `fundamentals/servers/index` and `fundamentals/servers/kestrel` under **Kestrel**:

   > HTTP/2 will be supported on macOS in a future release.

   **Still true in 3.0?**

1. In `fundamentals/servers/index` under **IIS (out-of-process)**:

   > Public-facing edge server connections use HTTP/2, but the reverse proxy connection to Kestrel uses HTTP/1.1.

   **Still true in 3.0?**

1. In a NOTE in `security/authentication/windowsauth`:

   > Windows Authentication isn't supported with HTTP/2. Authentication challenges can be sent on HTTP/2 responses, but the client must downgrade to HTTP/1.1 before authenticating.

   **Still true in 3.0?**

**Comment by Tratcher** [comment]
Yes, all still true.
