### ISSUE TITLE
Update Scaffold Identity to 3.1

### ISSUE THREAD

**Issue by DragonMastery** [aspnet/AspNetCore.Docs#10159]
18.6 K PV/month

Hey Rick,
Lets try this again. 
Please follow the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#update-compatibility-version): 
To up-date the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#create-full-identity-ui-source): 
The docs should all be referencing ASP.NET Core version 2.2 now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#create-full-identity-ui-source)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hongzewangpa  wrote:

I found if I move the services.Addxxx out of IdentityHostingStartupinto startup.cs, it is working.

```
//code piece moved:
                services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    context.Configuration.GetConnectionString("DefaultConnection")));

                services.AddDefaultIdentity<IdentityUser>()
                    .AddEntityFrameworkStores<ApplicationDbContext>();
```

**Comment by Rick-Anderson** [comment]
See  #12857

**Comment by vthe** [comment]
![image](https://user-images.githubusercontent.com/10944353/60787321-fc7bab00-a18b-11e9-9727-f79cf053b529.png)

**Comment by uzochiapa** [comment]
options.AllowAreas = true; 
this code doesn't work in ASP.NET Core 3.0
Any work around for this ?

**Comment by Rick-Anderson** [comment]
`AllowAreas` is a compatibility switch. With 3.0 being a breaking change, Areas are "allowed" out of the box, so `options.AllowAreas = true;` can be dropped.

https://github.com/aspnet/AspNetCore.Docs/issues/14357#issuecomment-532385914

**Comment by gopala000** [comment]
Documentation is not updated for .Net Core 3.0. I tried the section "Create full identity UI source". I had to add below line for services.AddIdentityServer() to work (ApplicationUser is my IdentityUser):
           services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>,UserClaimsPrincipalFactory<ApplicationUser>();
