### ISSUE TITLE
Test, debug, and troubleshoot enhancements

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10150]
* In the *Test, debug, and troubleshoot* node, the *Troubleshoot* topic can be recast into an *Overview* topic and include subtopic links for the rest of the topics in this node.
* We probably need to do a better job of cross-linking from this node to existing diagnostics topics in other doc sets and existing sections of our own docs. We've made some improvements in cross-linking  (e.g., *Host and deploy* troubleshooting topics), but there's more that can be done. Currently, we don't cross-link to the EventSource Logging Provider from anything in the *Test, debug, and troubleshoot* node :cry:, and PerfView is only mentioned in that EventSource Logging Provider section of the *Logging* topic. We don't link to any of the Windows ETW docs, etc. This could all be resolved with a *Overview* for this node.
* ~Move the TOC entry for [MVC controllers testing doc](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) into the *Test, debug, and troubleshoot* node. https://github.com/aspnet/AspNetCore.Docs/issues/12528#issuecomment-495913155~ **Already there. Didn't :eye: it earlier.**

@anurse @vancem Various remarks suggest that EventPipe has been available as far back as 2.1, but it looks like the Core CLI tooling was pushed off to 3.0. Is that correct? Whatever the case with that, is there a plan for where/when it will be documented (here or over in dotnet/docs)? If we're going to do something here and given that we have a 3.0 preview moniker now, we could engage this topic early if the bits have stabilized enough to do so.

EventPipe/Core CLI tooling cross-ref:

* https://github.com/dotnet/docs/issues/4954
* https://github.com/aspnet/KestrelHttpServer/issues/2937
* https://youtu.be/zKmjFWYN-PI?t=2029

**Comment by anurse** [comment]
> Various remarks suggest that EventPipe has been available as far back as 2.1, but it looks like the Core CLI tooling was pushed off to 3.0. Is that correct?

EventPipe has existed in some form for a while. In 2.2 we added support for out-of-process collection functionality and in the 3.0 *timeline* we're working on tools to take advantage of that functionality. Those tools should work fine on 2.2 apps though, it's just that we haven't built them yet, so they'll be coming in as part of the 3.0 "wave".

cc @pakrym and @davidfowl for more recent developments there as I'm on leave right now so things may have changed :P

**Comment by tdykstra** [comment]
@guardrex 

>recast into an Overview topic and include subtopic links for the rest of the topics in this node.

We're trying to avoid the pattern of duplicating a list of TOC links in an article.

>We probably need to do a better job of cross-linking from this node to existing diagnostics topics in other doc sets and existing sections of our own docs.

Agreed. When everyone's back from vacation we need to decide if we're going to more freely link to the same doc from different parts of the TOC, and once we've made that choice we'll be in a better position to know what the Overview doc needs to look like. Meanwhile feel free to add cross-linking in the docs you mention and anywhere else you think it would be helpful.

**Comment by guardrex** [comment]
> We're trying to avoid the pattern of duplicating a list of TOC links in an article.

I meant to imply 'where appropriate' in that regard. A section that goes into any detail in the *Overview* would link down to the full topic for more details (i.e., 'for more information, see ...' lines).

I'll stand-by until you determine what you'd like to do, if anything.

**Comment by guardrex** [comment]
@tdykstra Just took a closer look ... seems good actually. An "overview" doesn't make sense here given that this is a loose collection of topics. Perhaps one day, there would be sub-nodes to group topics (or this node would be broken up into root nodes for each area) ... but not today ... it doesn't seem like there are enough topics in each of these areas to sweat it.

WRT EventPipe ... let's wait until engineering provides guidance on a new issue that pertains to that tech.

Mov'in on ..............
