### ISSUE TITLE
context.Database.EnsureCreated(); will never execute

### ISSUE THREAD

**Issue by cbeamond** [aspnet/AspNetCore.Docs#10182]
After adding ContosoUniversity.Models.DbInitializer.Initialize(SchoolContext context) to Program.Main(), context.Database.EnsureCreated() will never be called. This is because the function is removed from Program.Main() and while it is included in DbInitializer.Initialize, it is actually commented out.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-au/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
>while it is included in DbInitializer.Initialize, it is actually commented out.

That comes from a later stage of the tutorial.  In the pre-migrations tutorials, EnsureCreated is used; after the migrations tutorial, it's commented out.
