### ISSUE TITLE
mvc/views/tag-helpers/intro"Introduction to Tag Helpers"

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#1025]
Link to corresponding sections in scenario based docs.
Add links to built-in TH

**Comment by danroth27** [comment]
This should just be a table of built-in tag helpers with links to the docs that cover them.

**Comment by Rick-Anderson** [comment]
Fixed by  #2785

**Comment by tdykstra** [comment]
@Rick-Anderson If this was fixed by #2785, is there a reason it wasn't closed?  I need to either use this for another TH Intro doc change or create a new issue-- it says you need to install a specific package for TH intellisense but that's not the case in 2.0 .

**Comment by Rick-Anderson** [comment]
> it says you need to install a specific package for TH intellisense but that's not the case in 2.0 .

That was fixed in the last VS release and doesn't apply to 2.0.
Feel free to add to this issue or create a new one. It wasn't totally fixed, so I updated the comment.

**Comment by Rick-Anderson** [comment]
Make https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/ an include and add it to the intro doc.

**Comment by Rick-Anderson** [comment]
Moved to #7998
