### ISSUE TITLE
Use scaffolder to generate Web API code

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10274]
Use scaffolder to generate Web API code.

Currently we use a cook book approach and have them copy/paste each method. It might be better to use the scaffold to generate the code, then have a discussion of each generated method. That's what we do in the RP and intro to MVC series.

I propose for the 3.0 version we use the scaffolder. The 2.2 version will keep the copy/paste approach. We can compare CSAT between the two versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danroth27 	please review. This is marked P2 because it's automatic done as part of the 3.0 doc updates. cc @tdykstra 	@scottaddie

**Comment by xtianus79** [comment]
What would the scaffolding method and is there documentation regarding scaffolding methodology?

**Comment by danroth27** [comment]
@glennc are you in favor of updating the basic Web API tutorials to use scaffolding?

**Comment by glennc** [comment]
Would you leave both options or switch it over to only show scaffolding? I don't have an objection to showing them scaffolding, especially if what we are showing them to write is no different to what you'd get from the scaffolder.

**Comment by Rick-Anderson** [comment]
Currently we have

* Add `Get` methods - copy/paste the following code
* Add a `Create` method copy/paste the following code
* Add a `PutTodoItem` method copy/paste the following code
* Add a DeleteTodoItem method copy/paste the following code

That would be changed to

* Run the scaffolder
* Examine the generated `Get` methods - we'd go into more detail on the generated code. Test the `Get` methods
* Examine the `xyz` method - explain it,  test it, etc.

I could add a note saying you don't need to run the scaffolder, just copy/paste the methods you're interested in.

The code we're using now is the same as the scaffolder generates.

**Comment by jamesdickpro** [comment]
While running through the tutorial using VS 2019, .Net Core 2.2, and generating the code with API Controller with actions, using Entity Framework, I noticed the generated code does not match the code in the tutorial.  Specifically,

Post Method
Generated code: return CreatedAtAction("GetTodoItem", new { id = todoItem.Id }, todoItem);
Tutorial code: return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);

Delete Method
Generated code: return todoItem;
Tutorial code: return NoContent();

Put Method
Generated code:

try
{
	await _context.SaveChangesAsync();
}
catch (DbUpdateConcurrencyException)
{
	if (!TodoItemExists(id))
	{
		return NotFound();
	}
	else
	{
		throw;
	}
}

Tutorial code: await _context.SaveChangesAsync();

Generated code has the TodoItemExists method, but the tutorial does not.

private bool TodoItemExists(long id)
{
	return _context.TodoItems.Any(e => e.Id == id);
}

**Comment by Rick-Anderson** [comment]
To do:

Delete Method
Generated code: `return todoItem;`
Tutorial code: `return NoContent();`

Verify with the scaffolding folks.

**Comment by cremor** [comment]
> Delete Method
> Generated code: `return todoItem;`
> Tutorial code: `return NoContent();`
> 
> Verify with the scaffolding folks.

Related:
aspnet/Scaffolding#983
aspnet/AspNetCore#8855

**Comment by Goldenstarc** [comment]
and services.AddControllers(); for new version

**Comment by Rick-Anderson** [comment]
This was complete last version.
