### ISSUE TITLE
Add missing metadata

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#10291]
The following docsets are missing the required metadata:
https://github.com/aspnet/ApiDocs/blob/master/aspnet-webpages/docfx.json
https://github.com/aspnet/ApiDocs/blob/master/aspnet-mvc/docfx.json

We need to do something similar to what was done in https://github.com/aspnet/ApiDocs/blob/master/aspnet-core/docfx.json#L49

**Comment by mairaw** [comment]
Other pages being reported for bad metadata. Please validate. Probably a bad combo of ms.prod and ms.technology values:
https://docs.microsoft.com/en-us/aspnet/api-ref
https://docs.microsoft.com/en-us/aspnet/config-builder
https://docs.microsoft.com/en-us/aspnet/entity-framework
https://docs.microsoft.com/en-us/aspnet/overview
https://docs.microsoft.com/en-us/aspnet/tutorials

**Comment by tdykstra** [comment]
Moved the items reported by @mairaw to #11946 

For the items this issue was created for, I had to submit requests for two new ms.prod values.  When those are put into effect I'll update the docfx.json files.
