### ISSUE TITLE
run in CLI, the fetchData.js give error Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Ping-GAO** [aspnet/AspNetCore.Docs#10303]
the app work fine in visual studio, but when i test it use cli, it give Unexpected token &lt; in JSON at position 0 error, and i test the sampledata api, dont work, it give me a html instead of jason, and that is what trigger the error,  in the html, it says that i dont enable javascript, and i check chrome find out i have that enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by foezahmed** [comment]
Manually starting the npm server on ClientApp (along with VS debugging process) seems to solve the problem. But from my understanding, it should start the server automatically on the background as an alternative manual process is mentioned explicitly on the documentation.
Still looking for a better solution...

**Comment by kidchenko** [comment]
Same issue here... :c

**Comment by salvoravida** [comment]
you have to use https://localhost:5001 or https://localhost:5000 that are served from webServer .netCore

not the one used just for hot relaod react 54445 ....  (in that webServer /api/ is not routed server side...)

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
