### ISSUE TITLE
Example for reverse proxy

### ISSUE THREAD

**Issue by pregress** [aspnet/AspNetCore.Docs#10337]
When using asp.net core with a reverse proxy and path prefixing (like Traefik) you need to update the config to look like this:

```C#
app.UseSwagger(c =>
{
	c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/prefix");
});
app.UseSwaggerUI(c =>
{
	// no forward / to use relative path
	c.SwaggerEndpoint("v1/swagger.json", "My API V1");
});
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS 	please review.

**Comment by SteveSandersonMS** [comment]
@Rick-Anderson I'm not the best person to review this, as I'm not familiar with the `UseSwagger` middleware` - sorry!

**Comment by Rick-Anderson** [comment]
@Tratcher 	please suggest a reviewer.

**Comment by dougbu** [comment]
@Tratcher `swaggerDoc.BasePath` is helpful when using CLI tools to interrogate a project or application for its Open API or Swagger documentation. I don't remember if Swashbuckle pays attention to `request.BasePath` when the document is retrieved from the app's Swagger endpoint or when the user heads to the UI endpoint.

**Comment by dougbu** [comment]
@domaindrivendev could you please fill in my gap:
>  don't remember if Swashbuckle pays attention to `request.BasePath` when the document is retrieved from the app's Swagger endpoint or when the user heads to the UI endpoint.

That is, does Swashbuckle use information from the request when serializing Swagger or Open API documents (in the non-CLI case)? If yes, does request information _override_ settings such as `swaggerDoc.BasePath`?

**Comment by valuator18** [comment]
Doing this will produce a working SwaggerUI, but the link to the swagger.json file will be broken. Changing the swagger endpoint to "../prefix/v1/swagger.json" fixes it.

**Comment by gonzaloluna** [comment]
pregress example worked for me.

**Comment by Rick-Anderson** [comment]
Moved to #16195
