### ISSUE TITLE
Update documentation and mention that "grant_type=authorization_code" is possible as well (see description)

### ISSUE THREAD

**Issue by becke-ch-s0-v1** [aspnet/AspNetCore.Docs#10336]
Can you pls update the postman documentation and mention that it is possible to use both "grant_type=implicit" (as already documented) and as well "grant_type=authorization_code".
Grant type implicit has according to MS doc security concerns see: https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow
I got the quick-start/tutorial (https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-quickstarts-web-app) and its code (https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/archive/master.zip) working using either one of the grant_type.
The only differences between "grant_type=implicit" and "grant_type=authorization_code" are that "grant_type=authorization_code" needs some more parameters as follows:
a) Access Token (access token request) URL: https://login.microsoftonline.com/&lt;tenant-name&gt;.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1_&lt;name-of-your-signup-signin-flow&gt;
b) client_secret: generate a key for you application: Azure Portal -&gt; Azure AD B2C -&gt; Applications -&gt; &lt;your-application&gt; -&gt; Keys -&gt; Generate Key
Thank you Raoul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2#use-postman-to-get-a-token-and-test-the-api)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
Moved to #16186
