### ISSUE TITLE
Document using IPolicyEvaluator in 2.0 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10384]
Moved from #4748

Add a section to the [Resource-based authorization](https://docs.microsoft.com/aspnet/core/security/authorization/resourcebased) doc explaining when and how to use `IPolicyEvaluator` in 2.0 apps. The doc currently assumes authentication has run and set the `User` property. `IPolicyEvaluator` should be used instead of `IAuthorizationService` when doing authentication in those samples.

Related issues:
- https://github.com/aspnet/Security/issues/1343
- https://github.com/aspnet/Security/issues/1348
- https://github.com/blowdart/AspNetAuthorizationWorkshop/issues/23

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5234edfa-92bb-a0a4-c523-ad2d7823e865
* Version Independent ID: 89c82c33-8e4f-93dc-af2f-492350557a4b
* Content: [Resource-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/resourcebased.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/resourcebased.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@HaoK 	@andrewlock could one of you do this?

**Comment by HaoK** [comment]
I looked through all the issues and I think our current docs for resource based auth look about like what our suggested code is:

```
        var document = _documentRepository.Get(id);

        var authenticateResult = await context.AuthenticateAsync("YourAuthScheme");
        if (authenticateResult != null && authenticateResult.Succeeded) {
           var authorizationResult = await _authorizationService.AuthorizeAsync(authenticateResult.User, document, new EditRequirement());
            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            return new ForbidResult("YourAuthScheme");     
        }
        return new ChallengeResult("YourAuthScheme");
```

Looks pretty similar to what's in the imperative authorization code snippet:

```
public async Task<IActionResult> OnGetAsync(Guid documentId)
{
    Document = _documentRepository.Find(documentId);

    if (Document == null)
    {
        return new NotFoundResult();
    }

    var authorizationResult = await _authorizationService
            .AuthorizeAsync(User, Document, "EditPolicy");

    if (authorizationResult.Succeeded)
    {
        return Page();
    }
    else if (User.Identity.IsAuthenticated)
    {
        return new ForbidResult();
    }
    else
    {
        return new ChallengeResult();
    }
}
```

The `IPolicyEvaluator` was not really designed to be used as a public imperative API, but rather a shared implementation that SignalR/MVC authZ logic could use.  I don't think its really something we should be calling out and directing people to be us in the documentation. 

@blowdart @davidfowl thoughts?

**Comment by blowdart** [comment]
Sure, call it out as "Don't use this". Do we have examples of what people want it for that they can't do with the authorization service?

**Comment by HaoK** [comment]
This exists since we wanted to have MVC and SignalR share the same code, there's nothing they can't do with the underlying APIs that they couldn't do anyways, this is basically an artifact of our framework's implementations as opposed to something that's generally useful

**Comment by Rick-Anderson** [comment]
Per @HaoK  closing this as won't doc. This issue is discoverable and  containss @HaoK  notes.
