### ISSUE TITLE
Document how to customize the view component search path

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10385]
Moved from #7667

We have already documented where ASP.NET Core searches for views:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1#view-search-path

We need to add how to customize that search path.

`@pranavkm` wrote:

There was an issue filed to allow further customization here - aspnet/Mvc#6426, although it looks like it was closed by the author. It did seem like triage wanted to consider it for a future release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1#view-search-path)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 are you interested in this? No hurry. One option is to just point to this issue, I could do that.

**Comment by serpent5** [comment]
Sure. I’ll add it to my list. I’ve got a fair bit of free time next week so I plan to spend some time on said list then.
