### ISSUE TITLE
For consistency: add-migration after applying validation rules

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10436]
Copy from @shadinamrouti #10429 since this is updated first.

Mainly, the following two attributes affect the schema:
- `[Required]` will alter the relevant column and make it not null
- `[StringLength(60)]` will alter the type of the column and make it `nvarchar(60)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra  this seems like a good idea. However, you don't get an error if you don't create the migration.

**Comment by tdykstra** [comment]
@Rick-Anderson As suggested, it would be good to mention this but I don't think you have to write detailed instructions for creating and applying a migration.  Migrations is covered more thoroughly in the two EF series.
