### ISSUE TITLE
Recommend: update this tutorial with a "OfficeAssignment model attribute check" sentence

### ISSUE THREAD

**Issue by Toby9876** [aspnet/AspNetCore.Docs#10449]
I ran into a problem following this tutorial on this page which took me some time to figure out. 

Firstly I can concur with the #8049 issue "Code bug with model validation fails" in that when validation fails, an exception occurs in the looping of the Model.AssignedCourseDataList in the edit razor page since it has not been filled. I ran into this problem due to the below bug (of mine):

The view model validation problem I ran into was that I had not removed the [Required] attribute on the Instructor property on the OfficeAssignment class resulting in an invalid model resulting in an page exception (due to #8049). In a previous tutorial, it was stated that the Required attribute was not really necessary since the InstructorID is the PK and FK in the Instructor table. Unfortunately I let the attribute remain because of this when I was working through that tutorial.

I would recommend simply updating the tutorial here with a sentence in the "Instructors Edit page model" section wit han advice to simply to make sure the Required attribute is not set on the Instructor property in the OfficeAssignment class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by STINGREO** [comment]
Unbelievable!  I could not find this with a debugger.  What would I have had to do to find this myself?

**Comment by peterof63** [comment]
I ran into the same problem. Luckily Toby9876 found the culprit.
