### ISSUE TITLE
Update Get Started tutorial for 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#10479]
Update the tutorial for ASP.NET Core 3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows#next-steps)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
remove `Click Accept to accept the privacy and cookie policy. This app doesn't keep personal information.`

**Comment by Rick-Anderson** [comment]
@wadepickett  can you fix this today?

**Comment by wadepickett** [comment]
@Rick-Anderson, sorry I missed this.  I didn't see it was re-opened.  Getting it now...

**Comment by wadepickett** [comment]
Fixed with PR #14748
