### ISSUE TITLE
Update Web API tutorial for 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#10480]
Update the tutorial for ASP.NET Core 3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1&tabs=visual-studio#next-steps)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by nexthazard** [comment]
Followed the Tut, very fun sadly i think im missing something in the HTML/JS Sections as my To-do List does not show in the Table.

**Comment by tdykstra** [comment]
@nexthazard The first link under [Additional resources](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1&tabs=visual-studio#additional-resources) goes to the completed sample application -- you can view or download that and compare it to what you have to see what's different between that and what you created by following the tutorial.

**Comment by nexthazard** [comment]
THx

**Comment by teracomp** [comment]
Unable to post todo using Postman. Status: 415 Unsupported Media Type.
Copied / pasted code 3 times. Stopped. Restarted. Done everything but reboot.

I'm on a Mac (latest version) if that makes any difference.
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "0HLM50UMQCPN2:00000002"
}

**Comment by teracomp** [comment]
never mind that last comment. I'm new to Postman. I didn't see the pulldown for JSON. My mistake.

**Comment by Rick-Anderson** [comment]
@tdykstra  this issue is not showing up on the doc page because we changed the title. Moved to #13373
