### ISSUE TITLE
Update EF RP for 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#10486]
Update the tutorial for ASP.NET Core 3.0.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3964cdf7-752f-9b95-4e9f-06ee6315cba9
* Version Independent ID: 0a2bc801-fe4a-05a8-a409-324dc1f2720b
* Content: [ASP.NET Core Razor Pages with EF Core - tutorial series](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra  I moved this issue to #13304
Can we delete this index page?
