### ISSUE TITLE
Update RP Intro tutorial for 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#10482]
Update the tutorial for ASP.NET Core 3.0.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Tutorial: Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by MrEmanuel** [comment]
In the meantime, the "Introduction to Razor Pages" for more experienced developers that is mentioned in this intro is updated after the 3.0 preview release (04/06/2019).
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index?view=aspnetcore-3.0

**Comment by Rick-Anderson** [comment]
Closed as dup of https://github.com/aspnet/AspNetCore.Docs/issues/10482
