### ISSUE TITLE
`KeyboardEvent.keyCode` has been deprecated perhaps update to `KeyboardEvent.code`

### ISSUE THREAD

**Issue by noobling** [aspnet/AspNetCore.Docs#10506]
Please see this article for further details: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* GitHub Login: @ssougnez
* Microsoft Alias: **scaddie**

**Comment by wadepickett** [comment]
Fixed with PR #16835
