### ISSUE TITLE
Model binding doc updates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10502]
Moved from #1080 by `@danroth27`
 	
Something like "Model state is a record of what data was bound to your model and any errors with the bound data". Include a link to the validation doc.

- [ ] eliminate MVC-controller-views-specific language (include Razor Pages)
- [ ] explain [ bind] attribute
- [ ] Model binding doc should define what model state is
- [ ] Example of when binding fails - and how to fix it (pass a subset of model, and post back)
- [ ] UE edit - remove market speak (vast majority, works great)
- [ ] Provide a simple sample where it fails and show how to create a simple binder. For example if you post a subset of a model it won't create a model.

From #1680 

It would be nice to table out the list of formats that we support in model binding. For example, for `Dictionary<string, string>` following formats work which is kind of difficult for an end user to figure out:

_Model_: `Dictionary<string, string> states`
1. states[wa]=washington&states[va]=virginia&states[mi]=michigan
2. states[0].Key=wa&states[0].Value=washington&states[1].Key=va&states[1].Value=virginia

 `@danroth27` wrote:
@dougbu is our model binding expert. He did the reviews on the [model binding doc](https://docs.asp.net/en/latest/mvc/models/model-binding.html) that is currently published. It might be enough just to get some time with him to get his thoughts on the specific issues this bug is tracking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by dougbu** [comment]
@Rick-Anderson what's the best way to convert the page to a Word doc?

And, is there a rush on this? (I still haven't got back to #9238 🙁)

I bet @danroth27 is correct those tick boxes can't be checked off. (Even if he's incorrect in only listing two of the three supported formats for dictionary values. 😈) However I may not catch all of the "market speak" @danroth27 mentioned.
