### ISSUE TITLE
Introduction to ASP.NET Core clean up

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10559]
Moved from #1367
- [x] Add link to "Side-by-side app versioning when targeting .NET Core."
- [x] The hosting doc goes into detail on content root and web root. Point to them for details.

per `@danroth27`
By default the content root will be the location where your app dll is loaded from, which ~~during development~~ [edit insert] { in test/production}  is the bin directory. The content directory is used to determine the location of things like your views and your web root ( _wwwroot_  folder). However, during development your views and web root are not in the bin folder. They are a couple of directories up where your project is located. To fix that we setup the project to use the current directory where you are running “dotnet myapp.dll” from, which is during development is typically the root directory of your project.

Can you reword "To fix that setup"? Should it be something like "To set the content root for development"? 

Seems like it's much simpler to define content root as the parent of web root ( _wwwroot_ )

~~It is based on a set of granular and well factored NuGet packages.This allows you to optimize your app to include just the NuGet packages you need.~~ replace with something like

It is based on a set of well factored NuGet packages, you include only the packages you need.

The following is fixed
The content root is the base path to any content used by the app, such as its views and web content. By default the content root is the same as application base path for the executable hosting the app; an alternative location can be specified with WebHostBuilder.

What does web content mean?  @danroth27  asks fowler " how to describe the content root for an ASP.NET Core app?" Fowler responds:
- Any non code files that need to be read from the project. Config files, data files (like a database file), etc. it's also the base path for the webroot folder 

-- end of fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mishakapoor** [comment]
great blog !!
great bulk information available in this blog
this blog are very helpful for Dot net freshers like me,
thank you
https://www.exltech.in/dot-net-training.html

**Comment by tdykstra** [comment]
@wadepickett Regarding your #3 above, the sxs description in the doc isn't nearly as good as David Fowler's in the issue.  I still think the issue info should be integrated into the doc.  I'd make a new issue for this work.

**Comment by wadepickett** [comment]
Since we decided to move the expanded info on content root out to the .NET Generic Host topic and link to that instead I moved that work item out to a new issue and assigned to myself. (see note above)  https://github.com/aspnet/AspNetCore.Docs/issues/14165
