### ISSUE TITLE
describe what the arguments here do

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10565]
Feedback from @dc995 in internal email thread : **Subject**: RE: health checks and db

 I would put a diagram in for the flow of data (creating events and publishing events) reflect that to the calls.   

The biggest thing was understanding the arguments here (both what the defaults do (where you verify the json endpoint and what this call does to change where it looks).  

I would show a separate container or separate project that consumes data from the most basic web app that utilizes a database – creating another sample.

It would be great to know where aspnet core starts and stops and what is OSS code.  Others have asked how to modify the UI itself (maybe adding their company name or change the colors to match their company)

I would also describe what is liveliness vs readiness that would be consumed by k8s.  Does it just need to see a response “Healthy” vs “Not Healthy”.

What are the nugets required for basic health producing?  I’d want to call that out.  I mean, what is the recipe to accomplish this.   What additions are available for say Entity Framework context OR that list of OSS ones where you put in something like a SQL query.  I’d describe what each one would tell you… e.g. I can reach the server but not the database.

However, if I could only update one thing – it would be describing what the arguments here do (and what the app.json requires and why).  I found that I spent a lot of time trying to figure out if I could override what’s in the config here (I don’t want to use a file for config with containers)

 `app.UseHealthChecksUI(setup => { setup.ApiPath = "/health-ui-api"; setup.UIPath = "/healthcheckui";});`

and it wasn’t clear where in this json file and what was absolutely required to work…   I started with a database connection string.  While it’s fake (I have 3 tiers – secrets then app json then environment variables as order for my config.   As such… it wasn’t clear the shape the json needed to be. 
```
{
  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "GRN Publisher",
        "Uri": "https://localhost:44364/hc"
      }
    ],
 
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "FujiDB": "Data Source=tcp:127.0.0.1,1401;Initial Catalog=fujidb;User Id=sa;Password=BogusExamplePass;TrustServerCertificate=False;Connection Timeout=30;"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@glennc please triage and indicate what updates we should make.

**Comment by guardrex** [comment]
@Rick-Anderson AFAIK from my discussion with engineering (mostly Ryan) on the issue, BeatPulse documents their own liveness libraries and their UI, not us. If that's correct (and maybe its not going to be the case going forward), most of the questions asked should be directed to the [BeatPulse repo issues](https://github.com/Xabaril/BeatPulse/issues). My understanding (*was anyway*) from Ryan that the ASP.NET Core docs will doc Health Checks primarily as namespaces, classes, and methods (sort of like *health check API primitives for building health check libs) and that readers are recommended to use BeatPulse for all (or most) of their health check probes. For example, Ryan's remark at https://github.com/aspnet/Docs/pull/8959#issuecomment-431606705 ...

> I think in general our guidance would be to use these checks for things that they [BeatPulse] support. I think that's what most users would prefer anyway

**Comment by Rick-Anderson** [comment]
@glennc 	please triage, set priority and indicate what we should change.
