### ISSUE TITLE
Doc missing Tag Helpers

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10593]
Moved from @simonech #2256
See #2256 for details. Summary here

Missing:
- [x] FormActionTagHelper
- [ ] LinkTagHelper #12167
- [x] ~OptionTagHelper~ - This works in conjunction with the SelectTagHelper and has no value on its own.
- [x] ~RenderAtEndOfFormTagHelper~ - This works in conjunction with other inner-form TagHelpers such as `input`. Not intended to be used directly.
- [ ] ScriptTagHelper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1692705d-02cc-f371-bae5-580380d2e877
* Version Independent ID: ec9bb36b-d744-5c66-8d60-b55ee2c7007a
* Content: [ASP.NET Core built-in Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/index.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by NTaylorMullen** [comment]
Took care of the `FormActionTagHelper` and wrote off doing the `Option`/`RenderAtEndOfForm` TagHelpers. Will leave it to some other brave soul to do link and script.
