### ISSUE TITLE
Update migration docs for .NET Core 3.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#10618]
Tracking issue for updates to the [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio) doc.

@natemcmaster Could you please provide details on what should be updated?/

**Comment by natemcmaster** [comment]
The current doc would still be accurate for preview 2, so no new details are necessary, per se.

That said, it's probably worth fleshing out the document a little more. All it currently says is "Some assemblies were removed from Microsoft.AspNetCore.App between 2.x and 3.0.  You may need to add `<PackageReference>` items". It would be good to show people how to migrate their code to react to:

* The removal of Json.Net support in MVC (add a call to `.AddNewtonsoftJson()`)
* The removal of runtime compilation - requires a new package (not sure on details, cc @pranavkm )
* The removal of EF Core

**Comment by danroth27** [comment]
Runtime compilation was removed in Preview 2, but we don't yet have a package for adding it back. The package for adding back runtime compilation should be available for Preview 3. For now, I think we can leave out any mention of the runtime compilation situation from this doc.

**Comment by danroth27** [comment]
Some proposed text for the Json.NET removal:

### Adding back Json.NET support

As part of the work to [clean up the ASP.NET Core shared framework](https://blogs.msdn.microsoft.com/webdev/2018/10/29/a-first-look-at-changes-coming-in-asp-net-core-3-0/), Json.NET has been removed from the ASP.NET Core shared framework and now needs to be added as a package. 

To add back Json.NET support to an ASP.NET Core 3.0 project:
- Add a package reference to [Microsoft.AspNetCore.Mvc.NewtonsoftJson](https://nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson)
- Update your `ConfigureServices` method to include a call to `AddNewtonsoftJson()`.

    ```csharp
    services.AddMvc()
        .AddNewtonsoftJson();
    ```

**Comment by Tratcher** [comment]
New topic: Generic host.

The templates have changed from using WebHostBuilder to using HostBuilder. WebHostBuilder will remain for compat purposes. The biggest gotcha for apps on the new HostBuilder is that due to changes in the DI setup, Startup's constructor can only inject IConfiguration and IHostingEnvironment. This is so we only have to build the DI container once and avoids several DI issues.

**Comment by Rick-Anderson** [comment]
@Tratcher 	I'll copy that section from the [ASP.NET Core 3/preview2 blog](https://blogs.msdn.microsoft.com/webdev/2019/01/29/aspnet-core-3-preview-2/)

**Comment by mkArtakMSFT** [comment]
Folks, is there anything else pending here?

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT Given that `@natemcmaster` is no longer here, can you assign someone to review this super important doc. It will get massive traffic once 3.0 GA's.

**Comment by danroth27** [comment]
@Pilchie @glennc We should make doing an update pass on this migration doc a priority before we ship 3.0.

**Comment by Pilchie** [comment]
Strong +1.

Also tagging @davidfowl as we had another thread about this today.

**Comment by mkArtakMSFT** [comment]
@pranavkm, @rynowak can you folks please review the doc and propse any changes, if necessary?
@Tratcher, @JamesNK

**Comment by davidfowl** [comment]
Have we documented all announcements?

**Comment by pranavkm** [comment]
I'll do a pass over the 3.0 breaking changes announcements and see what's missing. I know things like pubinternal changes + stuff that got removed from the shared runtime aren't covered in the migration notes.

**Comment by rynowak** [comment]
Some updates from me here: https://github.com/aspnet/AspNetCore.Docs/pull/14442

**Comment by mkArtakMSFT** [comment]
Closing as there is no more pending action left here.

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson feel free to reopen, if you still need this to track some work on your end.
