### ISSUE TITLE
Samples for Linux and Mac users with SQLServer

### ISSUE THREAD

**Issue by JulioJu** [aspnet/AspNetCore.Docs#10635]
@Rick-Anderson 

Here, I answer to your question from https://github.com/aspnet/Docs/issues/9863#issuecomment-456608855

Actually, all examples at https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples and  https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples can't work on Linux because they use MS-SQL LocalDB, and MS-SQL LocalDB is not implemented on Linux (see https://stackoverflow.com/questions/45860851/localdb-is-not-supported-on-this-platform )

For Linux Users maybe you could advise to change the ConnectionStrings 

* for  https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples to : 

```json
  "ConnectionStrings": {
    "RazorPagesMovieContext": "Server=localhost; Database=RazorPageMovie; user id=SA; password=YOUR_SQL_PASSWORD"
  }
```

* for https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples to

```json   
 "ConnectionStrings": {
    "DefaultConnection":"Server=localhost; Database=sampleMSUniversity; user id=SA; password=YOUR_SQL_PASSWORD"
    }
```

and give a link to https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-2017 

For Mac users, maybe you could give a link to https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017 (as MS-SQL is not implemented on Mac). 

Simply, under https://docs.microsoft.com/en-us/aspnet/core/index?view=aspnetcore-2.2#how-to-download-a-sample you could add a new section named `How to install, configure and start for Linux and Mac Users` with some steps and links to the official doc quoted above. 

What do you think about that? 

Below an example: 

#### How to install and configure tool needed

1. Install dotnet: see https://dotnet.microsoft.com/download/archives . Do not forget to export variables as explained under this link. 

2. Install, configure ans start MS-SQL Server. 
  * For Linux users see https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-2017 . 
   * For Mac users, see https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017

3. Install `dotnet ef` thanks : ` dotnet tool install --global dotnet-ef`

#### How to configure the sample
You must change the [ConnectionStrings](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings) as [LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-2016-express-localdb?view=sql-server-2017) is not implemented under Linux. 

* For  https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.2 sample, change the file appsettings.json to: 

```json
  "ConnectionStrings": {
    "RazorPagesMovieContext": "Server=localhost; Database=RazorPageMovie; user id=SA; password=YOUR_SQL_PASSWORD"
  }
```

* For [Contoso University samples](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.2) , change the file appsettings.json to

```json   
 "ConnectionStrings": {
    "DefaultConnection":"Server=localhost; Database=sampleMSUniversity; user id=SA; password=YOUR_SQL_PASSWORD"
 }
```

* Change the string `YOUR_SQL_PASSWORD` by your password of your MS-SQL Server, for the user `SA`. 

#### How to start the sample 

1. Do not forget to export variables as explained under https://dotnet.microsoft.com/download/archives .  

2. Do not forget to start MS-SQL Server

3. `export PATH="$HOME/.dotnet/tools:$PATH" ` (see also https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)

4. Change directory to the root folder of the sample downloaded: `cd PATH_OF_SAMPLE_DOWLOADED`

5. If not already generated, generate the Database: `dotnet ef database update`. If the Database was generated but the Schema is not correct, you could drop the database, then generate again the Database:  `dotnet ef database drop && dotnet ef database update`

6. Start the app: `dotnet run`

7. Tip: when a file change you could automatically trigger compilation, test execution, or deployment. Run `dotnet watch run` (before you must install it thanks `dotnet tool install --global dotnet-watch`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/index?view=aspnetcore-2.2#how-to-download-a-sample)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**5

**Comment by Rick-Anderson** [comment]
```json
  "ConnectionStrings": {
    "RazorPagesMovieContext": "Server=localhost; Database=RazorPageMovie; user id=SA; password=YOUR_SQL_PASSWORD"
  }
```

Can't put password in clear like that.

**Comment by JulioJu** [comment]
Ok, therfore I close this.

**Comment by Rick-Anderson** [comment]
@JulioJu 	this is good information for those who want to use SQL Server on Mac or Linux. They can use the [Secret Manager](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows#secret-manager) to store password.

**Comment by JulioJu** [comment]
Ok so cool, therfore I must update this tips with [Secret Manager](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows#secret-manager) 
? 

The tips above could be cool for Linux or Mac Users, because simply try to test https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples for a Newbie is actually a little bit hard as this sample mainly use SqlServer ;-). And if the Linux User want to try samples without change the c# code and without switch to SQLite, it could be cool to say how ;-).

**Comment by Rick-Anderson** [comment]
@JulioJu 	yes, update these instructions to use Secret Manager.

**Comment by guardrex** [comment]
@Rick-Anderson I was locking resolved issues, but this one is still open ... close and lock it?
