### ISSUE TITLE
lose key codes when add ForeignKey without drop database,

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#10638]
3K PV, 90% CSAT

Copy from https://github.com/aspnet/Docs.zh-cn/issues/109

i have some trouble at the end of the tutoral <
[Fix the ForeignKey constrants](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=netcore-cli#fix-the-foreign-key-constraints) lose key codes when add ForeignKey without drop database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=netcore-cli#applyexisting)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@lawushanshan The best way to troubleshoot is to download the completed project and compare that code with what you have in your project to see if you missed a step or missed something when copying and pasting code.
