### ISSUE TITLE
The goal or practical applications of this type of caching

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore.Docs#10644]
I think the intro of this article needs addition of practical applications, examples or situations why to use this type of caching.

**A note on terminology:** 
It seems the term "distributed cache" is misleading - in Wikipedia, the term is used to describe a cache memory solution that spans multiple servers. See: [Distributed Cache](https://en.wikipedia.org/wiki/Distributed_cache). 
May be this type of caching acts as the middle-tier data source mentioned in an article about [Database Caching](https://en.wikipedia.org/wiki/Database_caching) which is implemented for the sake of scalability, flexibility, availability and performance. 
If it's possible, I suggest to rename the tag helper as ```<database-cache>``` to avoid misunderstanding - I know it's a tough change request, but the opinion is worth mentioning 😊

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937e7280-ac1c-936c-6650-20557da31a8c
* Version Independent ID: d81e3546-e3db-2851-2f61-71f01404057f
* Content: [Distributed Cache Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This deals specifically with the Tag Helper. It's cross-linked to our main topic on distributed caching: https://docs.microsoft.com/aspnet/core/performance/caching/distributed

When the distributed caching implementation takes advantage of a multi-server data store (e.g., Azure Redis) behind the Tag Helper, it matches the definition that they provide. I don't see a problem thus far between what they describe and what distributed caching does in ASP.NET Core in some scenarios; and of course, a dev is completely free to create their own distributing caching implementation hooked up to anything they want.

WRT the naming, we can't address that here on the docs repo. That feedback would need to go to engineering.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
