### ISSUE TITLE
LF line ending for all  files except .sln files

### ISSUE THREAD

**Issue by JulioJu** [aspnet/AspNetCore.Docs#10641]
Hi!

* Actually .gitattribute is:
```sh
# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.cs text
*.cshtml text
```
See [preceding lines](https://github.com/aspnet/Docs/blob/master/.gitattributes#L6-L9) in GitHub

and not:
```sh
# Declare files that will always have LF line endings on checkout.
* text eol=lf

# Declare files that will always have CRLF line endings on checkout.
*.sln text eol=crlf
```

* With the command
```sh
$ while IFS= read -d '' -r i
do
    fileCommandOutput=$(file -b "${i}")
    if [[ "${fileCommandOutput}" == *CRLF* ]]
    then
        file "${i}"
    fi
done < <(find ! -name "*.sln" -type f -print0)
```
we could see than actually all files has LF line ending (except sln files but it's normal), and not CRLF line ending,  except ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml

When we try to make a Pull Request, for a Linux User (and probably a Mac OS X user), each time we work with git it changes this file to match the native line ending of the OS: LF (it's annoying).

Therefore If you want I could make a PR to change all line endings of ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml and change the .gitattribute to define LF line ending for all text files, except .sln files (see above). 

What do you think about that ?

**Comment by JulioJu** [comment]
After some tests thanks https://help.github.com/articles/dealing-with-line-endings/

maybe we could also add
```sh
*.PNG  binary
*.pdf  binary
*.ttf  binary
*.eot  binary
*.woff binary
*.wmv  binary
*.zip  binary
*.exe  binary
*.db   binary
```

If you are not ok, at least we could correct  ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml

**Comment by Rick-Anderson** [comment]
@spottedmahn @cillroy please review suggested changes to `.gitattributes` file.

**Comment by spottedmahn** [comment]
I'm honored but I have no clue.  I just reported the issue: when submitting [PRs via GitHub.com](https://github.com/aspnet/Docs/issues/7485) they are producing "fake" changes.

Based upon [this comment](https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-400456925), seems like @cillroy might know though.

**Comment by cillroy** [comment]
@herohua let us review this

**Comment by JulioJu** [comment]
Contrary to what I've said in https://github.com/aspnet/Docs/pull/10679#issuecomment-459486769 `.gitattribute` file has priority upon global config `git config core.autolf false`  (see https://help.github.com/articles/dealing-with-line-endings/ ) . That's add an argument to correct the .gitattributes

As I've said at, manually correct line ending of a file already merged seem cause  lot of problems (see  https://github.com/aspnet/Docs/pull/10679#issuecomment-459358774 and https://github.com/aspnet/Docs/issues/10735). Improve .gitattributes to not let CRLF come back could be I believe a cool idea.

**Comment by Rick-Anderson** [comment]
@JulioJu  if you want to pursue this, open it in https://github.com/MicrosoftDocs/feedback/issues
