### ISSUE TITLE
Delete Page Route Template Incorrect

### ISSUE THREAD

**Issue by Justin-Lloyd** [aspnet/AspNetCore.Docs#10696]
Following these changes, the @page directive need to be altered for the Delete page to update the route template, such as:
@page "{id:int}/{saveChangesError:bool?}"

Without it, any calls to the page following a failed DB update would fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Justin-Lloyd 	thanks for the report. We'll investigate in our next doc sweep.

**Comment by tdykstra** [comment]
@Justin-Lloyd You can test this in the concurrency tutorial by causing a concurrency error. That test indicates the route template update isn't required.  Without it, the error flag appears as a query string parameter -- Departments/Delete/6?concurrencyError=True
If I'm missing something please send repro steps that produce the error you refer to.
