### ISSUE TITLE
Request for expansion on TempData

### ISSUE THREAD

**Issue by jagerschmidt** [aspnet/AspNetCore.Docs#10704]
hi guys, i'm wondering if we could get a more dedicated section on TempData; what is here is scant and i couldn't find another MS ref resource (if there is one please let me know). TempData seems extremely useful, but is non-intuitive to understand its mechanics.  consequently, i built a 'test lab' proj to study how TempData works. i thought i'd post my notes, which might assist others & perhaps have errors i've made exposed. sorry if the format's bad, as i'm c/p-ing from OneNote. it would be great to have a section like this here, but written by the MS oracles. thanks!

TEMPDATA NOTATIONS:
KEY CONCEPT: TempData persists until certain events or an explicit command mark it for deletion (from the next outgoing Response).

BASIC USAGE: 1] in an Action, add a value to TD;   2] TD cookie goes out w/Response;   3] read TD cookie on the next Request.
 eg:  1] TempData.Add("keyname", value);   --&gt;  2] then send the Response:  return Redirect("/targetpage");
         [UA renders the Response; then submits the subsequent Request, with the TD cookie now attached]
      3] if (TempData.Count == 1 & TempData.ContainsKey("keyname")) {      4]     string s = TempData.Peek("keyname").ToString(); &lt;---calling Peek() does not mark the TD for deletion from the next Response.      4]     OR: int i = (int)TempData["keyname"];           &lt;---same: does not delete TD.      5]     TempData.Clear(); } &lt;---CRIT: this explicitly deletes the TempData object and removes it from the next Response.
"HARD" READING TEMPDATA VALUE: you can explicitly access the value using TryGetValue():
  1] object o;  then: TempData.TryGetValue("keyname", out o);            [you must use a generic object to extract TD values]
  2] string extractedValue = o.ToString();                               [you now have the keyname's value]     NOTE: this does not mark the TD for deletion from the next Response.

BEWARE! TD PERSISTS UNTIL YOU EXPLICITLY CLEAR IT, OR UNTIL IT'S READ INSIDE AN OUTGOING VIEW PAGE.

TO READ A TD VALUE INSIDE A VIEW code inline: @TempData["keyname"]     [can use the same inside an Action, but w/o the "@"]

TempData["key"];   VS   TempData.TryGetValue("key", out o);   VS   Tempdata.Peek("key");
the difference between these methods occurs if they are called INSIDE A VIEW:
  TempData["key"] & TempData.TryGetValue(): read the value and then delete TempData from the outgoing Response.
  TempData.Peek("key"):                     reads the value and does not delete TempData from the outgoing Response.
  NOTE: using any of these methods inside a Controller Action does NOT DELETE TD from the outgoing Response.

NOTES:
 -CRITICAL: you must ensure you CLEAR TempData after retrieving values! otherwise you'll have a 'zombie cookie' stuck to your page cycling.
 -CRITICAL: clear TempData before adding initial values: remember, if a user bugs out and does not complete the next Request (that would
  read the TempData), the TD cookie remains in their UA.  if they return to the original 'starting' TD page, the remnant cookie will crash
  the app when it tries to set that original TD key again, but it already exists in the remnant cookie.
 -if you do not read nor delete a TempData object on the second Request, it continues persisting & rides out on the next Response.
 -TempData is designed for 300-series Redirects, so use it for Redirects and little else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#tempdata)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @jagerschmidt ... great notes. We'll get it on the next update to the topic unless the community steps in to help before then.

**Comment by Rick-Anderson** [comment]
#14127 added more tempdata details
