### ISSUE TITLE
Show accessing the IStatusCodeReExecuteFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore.Docs#10706]
This can be used to get the original request fields in the error handler endpoint.
https://github.com/aspnet/AspNetCore/blob/28157e62597bf0e043bc7e937e44c5ec81946b83/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesExtensions.cs#L184-L189

Similar to the IStatusCodePagesFeature example shown above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@tdykstra I've been working this topic lately. Would u like me to do this one? If so, assign to me.
