### ISSUE TITLE
Generic Host promotion

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10714]
> The templates have changed from using WebHostBuilder to using HostBuilder. WebHostBuilder will remain for compat purposes. The biggest gotcha for apps on the new HostBuilder is that due to changes in the DI setup, Startup's constructor can only inject IConfiguration and IHostingEnvironment. This is so we only have to build the DI container once and avoids several DI issues.

Rotate the emphasis on Web Host to the Generic Host. Recommend that we make the *Fundamentals* topic a single topic (not a node) from the Generic Host topic and move the Web Host topic elsewhere.

cc/ @Tratcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@tdykstra For 3.0 if we go with a single *Fundamentals* > *Host* topic in the TOC (not a node; only covering the Generic Host), where can we place the current Web Host topic (legacy; we don't want to kill it; just want to get it out of *Fundamentals* and de-emphasize it)? Should I place it in *Advanced* and add a NOTE to the top saying that the Generic Host is recommended 3.0+?

**Comment by tdykstra** [comment]
The problem with that is that Web host remains a fundamental for 2.2.  My plan after reviewing the options for the TOC/content model project is to keep both as they are now but have moniker blocks at the top of each explaining what they are for.  If you don't mind and have other things to work on, I can take the 3.0 updates for these docs.

**Comment by guardrex** [comment]
My read of the remarks from engineering (e.g., @Tratcher in issues and @shirhatti at the conference) is that Web Host isn't recommended from 3.0 RTM forward and should be somewhat actively dissuaded post 3.0 RTM. If that's the correct interpretation, then it doesn't seem like it's "fundamental" any longer (i.e., that's too much visibility for adopters for something that we don't want them doing).

I'm just making the observations from assorted convos that:

* The Web Host topic can remain (elsewhere) and be linked from the Generic Host topic.
* The Generic Host topic can be **_the_** *Host* topic (no node).

I might not have received a full or clear understanding of their guidance.

WRT the updates for this issue, sure, if you want to do it. However if you/they decide to leave these SxS, then you may as well just close this issue. There's nothing to do WRT the TOC. If this issue is worked, it should be worked at (or very quickly after) 3.0 RTM.

Conceptual content updates will be worked on #11969 and can take place a lot sooner ... well ... *now, actually!* :smile: lol Those updates are managed via versioning, and I have the green light from engineering to perform the updates whenever I want. The only reason that I haven't already done them is that Blazor is keep'in me fairly 🏃😅 at the moment.

**Comment by tdykstra** [comment]
> if you/they decide to leave these SxS, then you may as well just close this issue.

I'll close this and add some details to #11969
