### ISSUE TITLE
Blazor Topic Reviews

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10717]
| Pre2 | Pre3 | Pre4 | Pre5 | Pre6 | Pre7 | Topic |
| :---: | :---: | :---: | :---: | :---: | :---: | --- |
| #10800 | #11388 | #12106 | &mdash; | #13070 |  | Overview |
| :x: | :x: | :x: | &mdash; |  #13070 |  | Supported platforms |
| #10873 | &mdash; | #12111 | #12289 | #13070 |  | Get started |
| &mdash; | #11721 | #12165 | &mdash; | #13070 |  | Hosting models |
| #10789 | #11390 | #12112 | &mdash; | #13070 |  | Tutorials: Build your first app |
| #10934 | #11391 | #12114 | &mdash; | #13075 |  | Components |
| :x: | :x: | :x: | &mdash; | #13083 |  | Forms and validation |
| #10971 | #11394 | #12132 | #12289 | #13083 |  | Component libraries |
| #10971 | #11395 | #12149 | &mdash; | #13083 |  | Layouts |
| #11012 | &mdash; | #12149 | &mdash; | #13083 |  | Dependency injection |
| #11012 | #11396 | #12149 | #12289 | #13083 |  | Routing |
| &mdash; | #11314<br>#11675 | #12165 | &mdash; | #13083 |  | JavaScript interop |
| :x: | :x: | :x: | :x: | &mdash; |  | Security: Security and Identity |
| :x: | :x: | :x: | :x: | :x: | :x: | Handle errors |
| :x: | :x: | :x: | :x: | :x: | :x: | State management |
| #11329 | &mdash; | &mdash; | &mdash; | &mdash; |  | Debug |
| :x: | :x: | :x: | :x: | &mdash; |  | Call a web API |
| &mdash; | #11723 | #12149 | &mdash; | &mdash; |  | Host/deploy: Overview |
| :x: | :x: | &mdash; | &mdash; | #13083 |  | Host/deploy: Client-side |
| :x: | :x: | #12149 | &mdash; | &mdash; |  | Host/deploy: Server-side |
| &mdash; | #11367 | #12149 | &mdash; | #13083 |  | Host/deploy: Configure the Linker |

**Comment by guardrex** [comment]
@danroth27 I'm moving to the Components (_razor-components/components.md_) topic this afternoon. To confirm our game plan for this one:

* Keep the current Blazor sample app.
* Create a new RC sample app.
* Link both samples on the 'download sample code' line.
* Reference code from the RC sample throughout the Components topic.

I'm fairly certain that I'll have this up later today for a look. :eyes: First, I'm going to perform the last of the 2.2 updates (API Browser links mostly) on https://github.com/aspnet/Docs/issues/8518 and then get right on this.

**Comment by danroth27** [comment]
@guardrex Given that the component code will be the same and the only difference is the hosting model, I'm not sure it's really necessary to create two versions of this sample app. It's pretty easy to switch between Razor Components and Blazor and we expect to make it easier. I think I wouldn't bother with this one.

**Comment by guardrex** [comment]
The sample app is Blazor tho. I thought you wanted this to be RC ... and then since we have a Blazor sample not to throw it away.

**Comment by guardrex** [comment]
Nevermind ... I hear u.

I'll run down the topic just to make sure everything else is ok.

**Comment by guardrex** [comment]
@danroth27 I've reached the *Hosting models* topic ...

https://docs.microsoft.com/aspnet/core/razor-components/hosting-models?view=aspnetcore-3.0

It's linked in the TOC both under *Blazor* and *Razor Components*.

Which way do you want to go with it? ...

* Leave it as a common topic and update in place.
* Split it into a Blazor version for the Blazor area and a RC version for the RC area. Cross-link the two topics.

**Comment by guardrex** [comment]
@danroth27 I just looked :eyes: and see that there are quite a few Preview3 updates to RC. A couple of options:

* Continue with the migration updates shown in the table (first column) :point_up: and then make another pass for Preview3 (next column).
* Skip the rest of the migration updates for the last three, start the Preview3 updates now, catch those last three at the end.

If we're going to continue where we left off, I need guidance for my [last comment](https://github.com/aspnet/Docs/issues/10717#issuecomment-466094404) wrt the *Hosting models* topic.

**Comment by guardrex** [comment]
I'm going to retire this now. It's outlived its usefulness. @rynowak has an issue (https://github.com/aspnet/AspNetCore.Docs/issues/13787) to look everything over ... all topics + the common sample app ... at or just after Pre9 to see where anything has gone off the rails.

The Blazor.Docs project is still working well, so let's keep going with that. I'll keep that up-to-date as we go.

https://github.com/aspnet/AspNetCore.Docs/projects/35
