### ISSUE TITLE
Sending current user to service layer - aka 'Passed in from caller' via IOC.

### ISSUE THREAD

**Issue by dalibor-sanzeru** [aspnet/AspNetCore.Docs#10738]
If you dont wan't to mess your (service layer) method parameters with ClaimsPrincipal use this approach:
1) Create class which provides (get/set) Request Specific data (like ClaimsPrincipal) and via constructor injection on controller-lower levels inject it (e. g. into services). 
2) Create + register ActionFilter which is setting Request Specific data.
3) On service layer provide Class and read ClaimPrincipal where needed.
4) Security extension is to provide only read  (get) interface on controller-lower layers and set Interface only in Action Filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@mjrousos please review.

**Comment by Tratcher** [comment]
How is this an improvement over IHttpContextAccessor?

**Comment by dalibor-sanzeru** [comment]
IHttpContextAccessor::HttpContext from namespace: Microsoft.AspNetCore.Http

In case you would like to have HTTP-agnostic user data in lower layers: 
1) service layer
2) repository layer

IHttpContextAccessor is not "abstract" enought and has direct reference to Http namespace.

E.g. I need only current user data e.g.

is this feasible enought or am I missing anything?

Thx .

You would provide

**Comment by Tratcher** [comment]
If you want to avoid the Http reference then You could provide some ICurrentPrincipal service, but the simplest way to implement that would still be a wrapper around IHttpContextAccessor. Creating an  ActionFilter is not a broadly applicable solution.

**Comment by dalibor-sanzeru** [comment]
I agree with you about 'ICurrentPrincipal' service, that was i was talking about.

Based on reading of documentation there is impression, that only 2 valid solutions are 
a) provide method parameter. 
b) use IHttpContextAccessor interface. 

And b) solution is described somehow as temp 'lets-migrate-it' solution.
So cleaner solution with technology agnostic would be this proposed, or?

Btw. Why is creating Actionfilter not broadly applicable solution? I dont get it.

e.g:

`    public class RequestMetadataFilterAttribute : IActionFilter
    {
        private readonly IRequestMetadata requestMetadata;

        public RequestMetadataFilterAttribute(IRequestMetadata requestMetadata)
        {
            this.requestMetadata = requestMetadata;
        }

        public void OnActionExecuted(ActionExecutedContext context)
        {
            // TODO: No Op.
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            this.requestMetadata.CurrentUser = context.HttpContext.User;
        }
    }`

**Comment by Tratcher** [comment]
ActionFilter assumes you're using MVC, it wouldn't help middleware components or SignalR for example.

**Comment by dalibor-sanzeru** [comment]
That's clear and correct. 

E.g. for WCF, SignalR... I would use another way of  'IRequestMetadata' Interception mechanism -> IOC Unity interceptions e.g... This is of course technology-specific interception and decision.

But result of proposed abstraction (not use IHttpContectAccesssor) is still the same:

I have service injected in lower layers of my application (even in database repository layer) which provides me access e.g. to current user identifier without touching higher levels of architecture... what HTTP metadata of course are. 

Aaand.. I dont need to pass parameter into each method requiring user id and I dont want to use IHttpContect accessor in lower levels of course. What is also my choise? I suppose this one left.

**Comment by dalibor-sanzeru** [comment]
I dont see any valid reason why this option couldn't be mentioned in documentation. (At least if this is not against some OOP - architecture principles what I dont see now).

I had faced same problem and my service layer calls are now without reference to HTTP-interface and without custom user principal id in method calls. 

Please,
Feel free to close this.
 
If anybody will face this in real situation, I hope this thread this will be helpful for him/her.

**Comment by Tratcher** [comment]
RequestMetadataFilterAttribute is redundant with this code in the [HttpContextFactory](https://github.com/aspnet/AspNetCore/blob/9f202feafc335dd70ae640f2053b465be3879e82/src/Http/Http/src/HttpContextFactory.cs#L58-L61) that sets up per-request state for the whole pipeline. You only need the IRequestMetadata implementation that wraps IHttpContextAccessor, not the ActionFilter, and this works for non-MVC AspNet scenarios.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
