### ISSUE TITLE
Add warning regarding SQLite and migrations

### ISSUE THREAD

**Issue by robertmarriott** [aspnet/AspNetCore.Docs#10758]
Hi,

Could you please add a note to the "Add a model to a Razor Pages app in ASP.NET Core" page to inform users the migration used at the end of the tutorial to add a rating to the Movie table won't work with SQLite and that they should probably add the Rating field to the initial model here (or use a different RDBMS).

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's the wrong approach. App development involves adding new fields. We're addressing SQLite migrations when they're required.
