### ISSUE TITLE
Asynchronously initialize state required by child components

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10770]
From `danroth27` at https://github.com/aspnet/Blazor.Docs/issues/240 ...

You can use `OnInitAsync` to asynchronously initialize some state needed by child components (ex retrieve a JWT needed for HTTP requests), but it takes some work and coordination. We should document how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11a64802-62dc-40e0-034f-fcee55f31d4e
* Version Independent ID: 038d7f90-aa71-a35c-cee9-c8543403cfd7
* Content: [Create and use Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-components/components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/components.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 This one is coming up soon for work.

> retrieve a JWT needed for HTTP requests

If this would make a good example, what's supplying the JWT?

**Comment by guardrex** [comment]
@danroth27 Pardon my earlier *stupid question* (I ask one occasionally ... or *daily* :smile: ... around here) ... do you intend to have tokens issued/validated by Identity Server for this? Generally, can you describe the authn flow a bit more (and address client-side vs. server-side deltas)?

Alternatively, is this issue a *wait-'n-see* for how auth will be designed for Blazor ... i.e., let's put this issue on hold for now until [Implement: Authentication and authorization for Blazor (aspnet/AspNetCore #4048)](https://github.com/aspnet/AspNetCore/issues/4048) is handled by engineering.

**_I don't really recommend this,_** but is the write-up for this best for the PU to address? If so, I can ride shotgun on the new topic with grammar and style assistance. If so, I'll mark this for the PU.

**Comment by guardrex** [comment]
@danroth27 Mark for the PU? I'll work this if I can, but I need more guidance ... details. Alternatively, we can mark this for the PU, and they can guide it with my immulagrammatical&dagger; support.

&dagger;**_immulagrammatical_:tm:** &ndash; Get the Urban Dictionary online!!! ... I have a winner here! :smile:

**Comment by guardrex** [comment]
Marking for the PU to address.

**Comment by danroth27** [comment]
I think that the only thing that really needs to be documented here is to note that for all of the async component lifecycle events any async actions performed in those event may not have completed before the component is rendered. So you need to make sure your rendering logic accounts for that (ex values still being retrieved may still be null or not defined yet). Typically this means writing some if statements in your rendering logic to check if things haven't been initialized yet and then render some placeholder UI ("Loading..." or whatever). You can see an example of this in the FetchData component in our templates. After the task returned by an async lifecycle event completes the component will be rendered again with the updated state.

**Comment by guardrex** [comment]
**Note to PU**: I can write this based on the guidance :point_up:. If you'd prefer to pass it to me, drop the PU label and assign it to me.

**Comment by danroth27** [comment]
@guardrex it's all yours :smiley:
