### ISSUE TITLE
Azure Storage/CDN hosting

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#10774]
From @guardrex at https://github.com/aspnet/Blazor.Docs/issues/37 ...

Note: FWIW, this is my **_favorite_** theoretical deployment strategy for Blazor: **_Azure CDN_**. It's not a priority of management, but I hope it will make the cut for a section in the topic at some point.

See https://github.com/aspnet/Blazor/issues/413#issuecomment-379435380.

This is blocked until either of the following occur:

* It can be determined if a completely flat directory structure for published assets will be instituted *in any way*, including creating a tool to do it. Without a flat directory structure, a Blazor deployment can't sit in the `$root` container of Azure Storage (`/` path delimiters aren't allowed in the `$root` container). The issue that I opened on the old Blazor repo was closed as a `wontfix`, but it might be reconsidered if enough devs ask for it later.
* We decide to go forward with an Azure Storage/CDN deployment approach outside of the `$root` container.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df31b39a-669b-f6a1-4385-04bd39e921f9
* Version Independent ID: 19409cdc-3ec8-cacb-d21f-6dd90e29f291
* Content: [Host and deploy Razor Components](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/razor-components/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
oooooooooooooooo @danroth27 I'm lick'in my chops on this one. *I know ... I know* ... but everyone was say'in **_Just Do It!_**:tm: at the conference. Let's see what the crazy green dinosaur 🐲 comes up with. Conceptually, this is my personal favorite Blazor client-side deployment strategy.

... and I confidently guess that Azure :cat2: :cat2: will be happy if we work this out and get it into the coverage.

**Comment by danroth27** [comment]
@jeffhollan did a really great talk about hosting client-side Blazor as an Azure Static Site with Azure CDN and Azure Functions all done from a Mac in VSCode: [Serverless web apps with Blazor, Azure Functions, and Azure Storage](https://mybuild.techcommunity.microsoft.com/sessions/77336).

**Comment by guardrex** [comment]
@danroth27 Let's go with **_@jeffhollan_** for our docs here and get some coverage for this scenario.

After the 👽 take over, *we want to be able to say that we're on their side!!!!!*

**Comment by jeffhollan** [comment]
This is a great pattern to doc. I'd love to see our CDN support get even better and happy to help however I can as well. I'm seeing a crazy amount of interest for Blazor + static website + serverless

**Comment by guardrex** [comment]
@jeffhollan **_Great talk! Loved it!_**

I think you resolved an issue/question that I hit earlier. I was trying to use the `$root` container to avoid a URI segment for a container. Turns out that `$root` can't have pseudo folder paths (forward slashes), which is bad for Blazor (more on this in a sec). I see that you used `$web` and that took care of it ... at least insofar as the storage account is concerned.

I still have a question WRT the Azure CDN. You said prefix `azurecdn` to the storage account name for CDN caching functionality. Is that the full blown CDN tho? I get the impression that that's not the same thing as adding CDN endpoint to a storage account. Don't answer tho ... I can research this easily enough on my own.

The goal in my mind for the *ultimate serverless Blazor app* is to fully leverage the CDN for it. I'll see how `$web` plays with that (if it does).

What we can't do from speaking with Steve Sanderson is ever have a fully flat `dist` publish for Blazor (all files just dumped into a single root folder with all file cross-links working within that one folder). If we had a completely flat `dist`, the `$root` container should work because the app wouldn't have forward slashes (pseudo paths) in its files' names.

Anyway, it seems that `$web` is the way to go.

Also, there could be some redirection challenges for SPA fallback routing for non-file assets ... IIRC a solution there might have been to host all static resources on the CDN; consequently, there would be no need for fallback routing. I'll need to take another look at what I was playing with several months ago and refresh my memory on that point.

**Comment by guardrex** [comment]
@danroth27 This coverage ...

https://docs.microsoft.com/azure/storage/blobs/storage-blob-static-website

... is so 👏 **_GrEaT!_** :clap: that I don't think we need a topic for this. I recommend that we have a new section in the *Host and deploy Blazor* overview topic to surface the content (+ have a cross-link to @jeffhollan's //Build talk). AFAICT, *that'll lick it.* :cow2: 🔔

I'll perform some testing on this scenario. If I hit a snag (e.g., the SPA fallback scenario), I'll ping back for discussion.

**Comment by jeffhollan** [comment]
Yes and as per the routing to SPA pages, the workaround I used (which is a bit hacky for now) is to set the error page to index.html as well.  That way when I do www.mysite.com/someBlazorPage, it "errors" on a 404 and hits index.html which routes someBlazorPage correctly.

**Comment by guardrex** [comment]
Ah ... perfect. Thanks. I'll make sure we cover it what way with some lingo to that effect (*hack* lol but without using that word. lol).

**Comment by guardrex** [comment]
## :tada: **_SWEET!_** :tada:

<img width="440" alt="Capture" src="https://user-images.githubusercontent.com/1622880/58267423-34986d00-7d49-11e9-8e1b-076e024bfbb3.PNG">

... and given the routing scenario for SPA fallback here, the backend handling isn't evident to the client. **_Lov'in IT!_**

<img width="493" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/58267489-5bef3a00-7d49-11e9-8ff2-7be217ecc310.PNG">

Will ping u cats on the PR shortly.
