### ISSUE TITLE
@aspnet/signalr TypeScript Client missing keepAliveInterval

### ISSUE THREAD

**Issue by JohnnyDevNull** [aspnet/AspNetCore.Docs#10783]
The https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-timeout-and-keep-alive-options section should be extended with the keepAliveIntervalInMilliseconds setting, which can be set through the client.

The setting is actually in version 1.1.0 not set automatically to half of the serverTimeoutInMilliseconds as described in other signalR Topics. This setting have to be set manually if the serverTimeoutInMilliseconds changed or the serverside KeepAliveInterval is changed.

So this point is missing KeepAliveInterval (.NET Option) -&gt; keepAliveIntervalInMilliseconds (JavaScript Option)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by mikaelm12** [comment]
Good catch. Looks like the KeepAliveInterval setting is missing for both the .NET and the JavaScript clients.
