### ISSUE TITLE
It should not have been necessary for me to go to the GitHub project to make this work

### ISSUE THREAD

**Issue by ortund** [aspnet/AspNetCore.Docs#10796]
I got tripped up around the issue of initializing the database with test data because the code sample provided on this tutorial doesn't include all of the necessary code. It calls BuildWebHost(args) but never indicates any necessity that this function should be added to the Program.cs file. I'm glad there was the GitHub project I could look at to find out how to write this function otherwise I'd have been completely stumped with no way to actually proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.0#add-code-to-initialize-the-database-with-test-data)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
It's there:

```
public static void Main(string[] args)
{
    var host = BuildWebHost(args);

    using (var scope = host.Services.CreateScope())
    {
        var services = scope.ServiceProvider;
        try
        {
            var context = services.GetRequiredService<SchoolContext>();
            DbInitializer.Initialize(context);
        }
        catch (Exception ex)
        {
            var logger = services.GetRequiredService<ILogger<Program>>();
            logger.LogError(ex, "An error occurred while seeding the database.");
        }
    }

    host.Run();
}
```

BTW, what version of the SDK are you using? This tutorial is currently being updated for 2.2
The Razor Pages version is up to date if you're open to RP.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
