### ISSUE TITLE
gulp-uglify does not support ES6

### ISSUE THREAD

**Issue by vikriu** [aspnet/AspNetCore.Docs#10798]
gulp-uglify does not support ES6, should be replaced by something else (e.g. Terser)

@Rick-Anderson 	edit: 4.7 KPV, 100% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb34beb-733d-ad1e-37a7-cbe045ee9f15
* Version Independent ID: 02319a95-6eb9-59cd-f5fc-747c61e90123
* Content: [Use Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.2)
* Content Source: [aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-gulp.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danroth27  can we retire this doc?

**Comment by danroth27** [comment]
Yes, I think so.
