### ISSUE TITLE
IAuthorizationPolicyProvider implementation out of date and does not work

### ISSUE THREAD

**Issue by jbeanky** [aspnet/AspNetCore.Docs#10824]
The sample implemenation of IAuthorizationPolicyProvider does not work with the current .NET Core framework.  It is missing the use of a fallback policy provider.  It needs to match the example code available in the AuthSamples repository.  Following the example included in the documentation can lead to some weird errors when combined with other policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by mjrousos** [comment]
Thanks for reporting this, @jbeanky. I'll take a look and get things updated.
