### ISSUE TITLE
(Manage Bower Packages) is no longer available

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore.Docs#10832]
(Manage client-side libraries) is the new command according to the announcement:
https://blogs.msdn.microsoft.com/webdev/2018/08/31/library-manager-release-in-15-8/
The suggestion is to remove this article because there is already an article about LibMan and also many resources are talking about bower as _officially_ dead or _is dying_ since 2016. It even has no Wikipedia page except in German 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd636ce2-7f47-77e4-e12c-461bd6951c65
* Version Independent ID: 86160014-970f-5662-a446-308fd4c1b331
* Content: [Manage client-side packages with Bower in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.2)
* Content Source: [aspnetcore/client-side/bower.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bower.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@madskristensen @raquelsa can I delete [Manage client-side packages with Bower in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.2)
