### ISSUE TITLE
Do you have an example of the absolute expiration time. 

### ISSUE THREAD

**Issue by MNF** [aspnet/AspNetCore.Docs#10858]
The article said:“The following sample: Sets the absolute expiration time.”
But I only found sliding expiration examples.
Please add the example or , if I missed it, highlight it by comment.

Ref:  https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.set?view=aspnetcore-2.2#Microsoft_Extensions_Caching_Memory_CacheExtensions_Set__1_Microsoft_Extensions_Caching_Memory_IMemoryCache_System_Object___0_System_TimeSpan_

@Rick-Anderson 	 edit:
16K PV, 83% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`                .SetAbsoluteExpiration(DateTime.Now.AddSeconds(30))`

Or via prop:

```
cacheEntryOptions.AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(30);
cacheEntryOptions.AbsoluteExpiration = DateTime.Now.AddSeconds(30);
```
