### ISSUE TITLE
Changing to Microsoft.AspNetCore.App from Microsoft.AspNetCore.All is not straightforward.

### ISSUE THREAD

**Issue by MNF** [aspnet/AspNetCore.Docs#10860]
“Replace the package reference for Microsoft.AspNetCore.All with a package reference for Microsoft.AspNetCore.App. You may need to add dependencies that were removed from Microsoft.AspNetCore.All.”
	1.  it is recommended, but not mandatory to change .All to .App, as .All is still supported. Can you clarify it in the article?
	2. In my experience, adding  dependencies explicitly is the most time consuming and annoying step in the migration from 2.0. Can you highlight in the article that it may be not straightforward and add the direct reference to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#migrating-from-microsoftaspnetcoreall-to-microsoftaspnetcoreapp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> add the direct reference to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#migrating-from-microsoftaspnetcoreall-to-microsoftaspnetcoreapp

It does have a direct ref to that.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by michael-freidgeim-webjet** [comment]
Sorry, but I don't agree that you answered to my suggestions to change the document.
1.The phrase "Replace the package reference for Microsoft.AspNetCore.All with a package reference for Microsoft.AspNetCore.App" still sound as a mandatory step of migration when it is only recommended,

2. Phrase "You may need to add dependencies that were removed from Microsoft.AspNetCore.All." doesn't describe how to add the dependencies. This is  why I suggest to add the direct reference to section "Migrating from Microsoft.AspNetCore.All to Microsoft.AspNetCore.App" https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#migrating-from-microsoftaspnetcoreall-to-microsoftaspnetcoreapp .

 Subsequent links "For more information" describe the packages Microsoft.AspNetCore.All to Microsoft.AspNetCore.App for reference, but link to section "Migrating from Microsoft.AspNetCore.All to Microsoft.AspNetCore.App" is more useful in step-by-step instructions "Update the project file to use 2.1 versions".

**Comment by GitHubSlob** [comment]
What a mess! The right arm is not talking to the left. NuGet was supposed to solve reference and package problems. Now it is all over the place and tightly coupled with what version of Core SDK and .NET and Visual Studio. Entropy has set in. It is impossible to create a simple web application anymore. Pretty sure not many startups are using .NET these days.

**Comment by GitHubSlob** [comment]
I just totally hosed a project I was working on when a Scaffolding error told me that I should update to 2.1. I hope my saved copy will get me back to where I was.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
