### ISSUE TITLE
Split into two docs: using options and implementing the options pattern

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#10946]
Using options will stay in the Fundamentals TOC node, and implementing the options pattern will go into the Advanced TOC node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#additional-resources)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This one wasn't addressed by https://github.com/aspnet/AspNetCore.Docs/pull/10929, but that's cool ... let me take a look in January on issues such as https://github.com/aspnet/AspNetCore.Docs/issues/15987 and at least one other one that I need to track down. This is cross-linked to that issue now, so I'll put an :eye: on this for Options topic updates when I get get to it. 🏃😅
