### ISSUE TITLE
"OnInit" called after the component has received parameters from its parent

### ISSUE THREAD

**Issue by rpc-scandinavia** [aspnet/AspNetCore.Docs#10984]
Quote: "OnInitAsync and OnInit execute code after the component has been initialized. To perform an asynchronous operation, use OnInitAsync and use the await keyword".

Quote: "OnParametersSetAsync and OnParametersSet are called when a component has received parameters from its parent and the values are assigned to properties. These methods are executed after OnInit during component initialization".

In reality, the "OnInit" is called after the component has received its parameters from its parent.
Perhaps I misunderstood, but I read your documentation like "OnInit" is called before ANY parameters are set, more like a constructor - perhaps you miss a life cycle method like "OnConstructor" (OnCreate would use a good name for component developers).

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 11a64802-62dc-40e0-034f-fcee55f31d4e
* Version Independent ID: 038d7f90-aa71-a35c-cee9-c8543403cfd7
* Content: [Create and use Razor Components](https://docs.microsoft.com/nb-no/aspnet/core/razor-components/components?view=aspnetcore-3.0#lifecycle-methods)
* Content Source: [aspnetcore/razor-components/components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/components.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 

https://docs.microsoft.com/aspnet/core/razor-components/components?view=aspnetcore-3.0#lifecycle-methods

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
