### ISSUE TITLE
Suggestion to start with a simpler introductory example

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore.Docs#10985]
I suggest to start the article with a simpler introductory example:

**Read a value from appsettings.json directly into a view**

_appsettings.json_
 ```csharp
 {
  "root": {
    "parent": {
      "child": "myvalue"
    }
  }
```

_A View_
```csharp
@inject Microsoft.Extensions.Configuration.IConfiguration configuration
@{
     string myValue = configuration["root:parent:child"];
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Dependency injection into views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Just a quick note in case this becomes an actionable issue: It's fine to provide a different or new example anywhere, but let's (mostly) stick with gender-neutral examples. It would be sad to see things go back to the way that they were. https://github.com/aspnet/Docs/pull/2314

**Comment by shadinamrouti** [comment]
Good point @guardrex
