### ISSUE TITLE
Content model - security tasks

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#11015]
* Add TOC link to https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DotNet_Security_Cheat_Sheet.md

* Find a place to explain how to get security advisories -- subscribe to https://github.com/aspnet/Announcements / [search open issues](https://github.com/aspnet/Announcements/issues?q=is%3Aissue+is%3Aopen+label%3ASecurity+sort%3Aupdated-desc)

**Comment by wadepickett** [comment]
Proposed changes to OWASP folks to see if they are OK with me adding a new Security Announcements" section to the DotNet_Security_Cheat_Sheet.  https://github.com/OWASP/CheatSheetSeries/issues/59 . Thought it best to ask if that was the proper place before submitting a PR.

**Comment by wadepickett** [comment]
Related OWASP resulting PR: https://github.com/OWASP/CheatSheetSeries/pull/73.  Will close this issue once that PR on their repo is accepted.
