### ISSUE TITLE
Adding Xml support

### ISSUE THREAD

**Issue by kingmotley** [aspnet/AspNetCore.Docs#11026]
Currently, the alternative way of adding XML support as suggested https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#adding-xml-format-support, will cause the ProblemDetails and ValidationProblemDetails to be serialized incorrectly because they are only wrapped correctly when you call .AddXmlSerializerFormatters(); as I found out when I reported the issue as a bug https://github.com/aspnet/AspNetCore/issues/7715

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#adding-xml-format-support)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kingmotley 	thanks for reporting this. Would you be able to provide the first draft of updating this doc?

@pranavkm 	do you agree we should update this doc with the instructions you provided in https://github.com/aspnet/AspNetCore/issues/7715?

**Comment by pranavkm** [comment]
Yeah. Removing the alternatives would be the way to go.

**Comment by sumon19** [comment]
nice

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/56453902-aa419100-62e4-11e9-9538-9f336b260d9d.png)
