### ISSUE TITLE
Create a DI in Razor Pages doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#11032]
Create a DI in Razor Pages doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d2cf2e-55fb-33a4-b1d4-c97b2d531741
* Version Independent ID: f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf
* Content: [Dependency injection into controllers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu  @danroth27  should we create a DI for RP like this DI for controllers/views?

**Comment by dougbu** [comment]
What is a "DI"?

**Comment by pranavkm** [comment]
@Rick-Anderson that seems reasonable. I'd focus it on PageModel and not on injecting things in to the Razor Page.
