### ISSUE TITLE
Sharing layout in areas with _ViewStart.cshtml 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#11030]
For areas, *_ViewStart.cshtml* should be copied  to the root folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ccit-spence** [comment]
How does this impact __ViewImports_?

**Comment by Rick-Anderson** [comment]
Sorry, that should be copied.

**Comment by ccit-spence** [comment]
So, to clarify.  The __ViewImports_ should be copied into each `View` folder within an Area.

I did notice in `3.0.100-preview5-011568` that is the only way I could get it to work.

**Comment by Rick-Anderson** [comment]
MOved to #11720
