### ISSUE TITLE
Localization of the DefaultUI

### ISSUE THREAD

**Issue by fjallemark** [aspnet/AspNetCore.Docs#11038]
How do I add localization to the DefaultUI? It seems a huge overkill to override DefaultUI by scaffolding all pages just to be able to add other languages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by fjallemark** [comment]
I have now scaffolded all pages and found a sloppy implementation with hardcoded English strings. I assume that the DefaultUI is the same code made to a component. There is only one long tedious process to scaffold the whole thing and replace 100's of strings in cshtml and cs files.

**Comment by Rick-Anderson** [comment]
Thanks for bringing this to our attention.
@HaoK 	should I open an issue "Make Identity source UI localizabale"?

@ryanbrandenburg @hishamco can you outline an approach to localized the Identity UI.

@fjallemark it sounds like you're not doing localization (supporting multiple languages), but translating the English UI into another language. Is that correct?

**Comment by HaoK** [comment]
Identity already has an issue https://github.com/aspnet/AspNetCore/issues/5778 in the backlog

**Comment by hishamco** [comment]
@damienbod can you participate on creating docs for  `Localizing Identity UI` I knew you did a great job in this before .. hopefully I can participate on this after I'm finishing the docs that I have

**Comment by dev4y0u** [comment]
I would like to know if changes will be patched into a newer version of the .net core 2.2 fw, or if the localization of the default identity UI is only available from .net core 3.x?
Is there a planned release date for this change?

**Comment by fjallemark** [comment]
@Rick-Anderson: This is what I do: 
- Step 1 is to replace all hardcoded strings in the scaffolded GUI and place them in a default langauage RESX file. 
- Step 2+ I add more languages to my GUI like German, Swedish and so on. 
So if the scaffolder could do Step 1, my job will be to add other languages simply by copying the default RESX and make the translations. I think its good practise to make it easy to add languages to and application. We are a whole world developers using .NET for localized apps!

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson: This is what I do: 
- Step 1 is to replace all hardcoded strings in the scaffolded GUI and place them in a default langauage RESX file. 
- Step 2+ I add more languages to my GUI like German, Swedish and so on.  **So if the scaffolder could do Step 1,** my job will be to add other languages simply by copying the default RESX and make the translations. I think its good practise to make it easy to add languages to and application. We are a whole world developers using .NET for localized apps!

@DamianEdwards @vijayrkn @mkArtakMSFT @ryanbrandenburg  can we get the scaffolder to do that?

**Comment by mkArtakMSFT** [comment]
We have no immediate plans to add localization support to the default IdentityUI. This can be done currently by scaffolding all the identity pages and doing that yourself.
As was pointed out by @HaoK , there is a separate issue in the backlog tracking the localization support.
