### ISSUE TITLE
Consider renaming this repo to AspNetCore.Docs or similar 

### ISSUE THREAD

**Issue by divega** [aspnet/AspNetCore.Docs#11049]
Now that a main repo exists for the ASP.NET Core codebase, and it is called AspNetCore, it seems to make more sense for the ASP.NET Core documentation to be in AspNetCore.Docs. 

It would help clarify the scope, given that in the same aspnet GitHub org there are other codebases with their own documentation repos.

I understand that the ASP.NET Core docs also cover the code in the Extensions repository, but I think a small inconsistency like that is fine. 
 
I also understand this may require some work than it is worth doing now, but if at some point we decide to move all the repos to some other GitHub org like 'dotnet', we will probably have to do it anyway. 

Also, keep in mind that GitHub handles redirects automatically for any links to the current name.

**Comment by Rick-Anderson** [comment]
Perfect timing. We are in the process of splitting the repo in two (aspnet framework and aspnetcore). The aspnet framework has been moved to https://github.com/aspnet/AspNetDocs

@cillroy 	@Eilon 	@JasonCard

**Comment by Eilon** [comment]
I'm fine renaming these. @Rick-Anderson - in general, GitHub will auto-redirect just about everything from the old name to the new name. But if we want to do this rename, who should be made aware of the rename?

Also cc @danroth27 @DamianEdwards @bradygaster who love Docs things.

**Comment by bradygaster** [comment]
Doesn't the repo also have non-Core docs in it? I agree with @divega, but I also don't think we should rush into this and break things in the docs system. Are we confident we won't break anything? Does anyone have issues with the fact that some Classic ASP.NET content will remain in this repository?

**Comment by Rick-Anderson** [comment]
> Doesn't the repo also have non-Core docs in it?

Per my comments above:
>Perfect timing. We are in the process of splitting the repo in two (aspnet framework and aspnetcore). The aspnet framework has been moved to [aspnet/AspNetDocs](https://github.com/aspnet/AspNetDocs)

Once the split is complete, I'll have a discussion alias on the rewriting history (to remove the massive history from the non-core repo). Once the split/rewrite is complete, the core docs repo will be much smaller ( a big customer request).

**Comment by bradygaster** [comment]
AH. I see that now, @Rick-Anderson - then i'm good with this change provided we don't break anything in OPS.

**Comment by Rick-Anderson** [comment]
Per https://github.com/aspnet/Announcements/issues/350
@Eilon can we get @NTaylorMullen or another Git converstant dev to do the following?

* Rename https://github.com/aspnet/Docs to https://github.com/aspnet/AspNetCore.Docs
* Remove all history.

We need to remove all history to reduce the repo size by more than 70%. Currently history has all the [ASP.NET Framework repo](https://github.com/aspnet/AspNetDocs) assets (which is much larger than the Core assets)

**Comment by Eilon** [comment]
But this repo's name *is* `AspNetCore.Docs` 😏 😏 😏 😏 😏 😏

Are you sure you want to remove all the history? That's of course a permanent change. I recommend you consult with other stakeholders of the repo. I think it's fairly trivial if you want to delete *all* history. Just `squash` all the Git commits in the entire repo into 1 (might have to do it per-branch, or delete other branches).

**Comment by guardrex** [comment]
@Eilon Does clearing the history kill the contributions counters on the *Contributors* page?

https://github.com/aspnet/AspNetCore.Docs/graphs/contributors

**Comment by Eilon** [comment]
It probably would because it'll all be 1 huge commit from 1 person. Unless GitHub does some magic to track historical data that is now gone.

**Comment by guardrex** [comment]
Aquent @guardrex (~75% of my commits) has no concerns ... that's fine. Community contributor @guardrex (~25% of my commits) **_strongly discourages killing the contribution history_** ... not cool ... definitely not a friendly move to the community who worked very hard on many of those commits (whole topics for example).

**Comment by Rick-Anderson** [comment]
@guardrex  your commit history was duplicated and retained in https://github.com/aspnet/AspNetDocs/graphs/contributors

**Comment by guardrex** [comment]
Just concerned about the "Remove all history" part. *Sounds scary!* 🎃

**Comment by Rick-Anderson** [comment]
The `#1` customer request to to reduce the repo size. The history has the entire https://github.com/aspnet/AspNetDocs (which was recently moved to its own repo).  @danroth27  please comment.

**Comment by guardrex** [comment]
> The #1 customer request to to reduce the repo size.

Because they want to download single samples ... a situation that apparently will be addressed.

https://github.com/aspnet/AspNetCore.Docs/issues/6991#issuecomment-398104010

... but "near-term" perhaps means that they ran into some trouble implementing their plan

**Comment by Rick-Anderson** [comment]
@guardrex  - per @danroth27  check out  **Removing a File from Every Commit** at https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

We can use that to remove all the ASP.NET Framework files and reduce the repo size, and retain history.

**Comment by guardrex** [comment]
I just downloaded the aspnet/AspNetCore.Docs ZIP ... 57 MB ... and that's going to get a lot smaller as we continue to drop the static assets from samples.

Are you saying that when you fork and clone that it's a lot more data and still takes a long time (the clone step)?

But even if so, that should be rare approach for the sample downloaders out there. We tell them to take the ZIP in the guidance.

**Comment by danroth27** [comment]
I thought one of the goals was to reduce the size of the repo. If we only care about the download size for getting the sample code, then we should probably just leave the repo as is. Since you guys are the ones that work in this repo the most often I'll leave it to you to decide if rewriting the git history is worth it. If you need help from the engineering team on this, we can look at making this a work item for our next doc-a-thon.

**Comment by Rick-Anderson** [comment]
Remaining work moved to Remove all ASP.NET Framework Files from Every Commit #11917
