### ISSUE TITLE
Show how to use a different connection string based on MVC route

### ISSUE THREAD

**Issue by ardalis** [aspnet/AspNetCore.Docs#11048]
I need to be able to specify which database will be used as part of the URL/route in a controller. How can I configure the database name part of the connection string in a controller either after the DbContext instance has been loaded or by injecting a factory or similar that can do it for me?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
