### ISSUE TITLE
Does this issue also apply to ASP.Net?

### ISSUE THREAD

**Issue by hoyle1977** [aspnet/AspNetCore.Docs#11066]
I see similar issue in ASP.Net.WebApi.Core 5.2.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by mjrousos** [comment]
@hoyle1977, this should only apply to ASP.NET Core. Can you provide more details on the ASP.NET problem you're seeing? If ClaimsPrincipal.Current isn't populated, it's possible that authentication isn't setup properly or that there's a bug in recent [ASP.NET](https://github.com/aspnet/AspNetWebStack) builds.
