### ISSUE TITLE
Retire WIP app in favor of draft PRs

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#11063]
Investigate whether draft PRs are a suitable replacement for the WIP GitHub Marketplace app installed in the aspnet/Docs repo. Uninstall the app if draft PRs are sufficient.

**Comment by Rick-Anderson** [comment]
They are. Much better, except you have to create the PR as a draft PR. Once you remove draft, you can't go back. I think we can live with those limitations.

**Comment by Rick-Anderson** [comment]
Lets hold off on this for another month. WIP was convenient for a customer PR where they hadn't signed off.

**Comment by Rick-Anderson** [comment]
@scottaddie  lets keep this as it solves problems draft doesn't

**Comment by scottaddie** [comment]
Removed the app and branch protection rule on _master_ from our repo. Let's use Draft PRs, when possible, from this point forward.
