### ISSUE TITLE
Does not work with ECMAScript 6

### ISSUE THREAD

**Issue by JasperKent** [aspnet/AspNetCore.Docs#11084]
The minifier does not work on ECMAScript 6. It falls over with an unhelpful error message on the first use of 'let'.

This may be a fault in the product, but it should be made clear upfront in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by ryanbrandenburg** [comment]
Could you be more specific? There's no "let" keyword in the version of gulpfile.js we have listed on the docs page, so I'm not sure where it's coming from in your case. Could you include the error message and whatever was generated to produce this error?

**Comment by JasperKent** [comment]
I’m not using gulp. I’m following the instructions on the Microsoft documentation site for Bundling and Minification (https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio) up to but not incuding the section ‘Consume bundleconfig.json from Gulp’.

The ‘let’ in question is in one of my own .js files, which I have referenced in bundleconfig.json.
