### ISSUE TITLE
Continuous deployment via the Deployment Center isn't working

### ISSUE THREAD

**Issue by JamesBateson** [aspnet/AspNetCore.Docs#11085]
I can publish the React project template to Azure using Publish in Visual Studio. However, when I set up continuous deployment from GitHub if fails (presumably when it runs npm start) with the error: 

&gt; react-scripts build  
  'react-scripts' is not recognized as an internal or external command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by danroth27** [comment]
@JamesBateson You probably need to customize the deployment. See https://github.com/projectkudu/kudu/wiki/Customizing-deployments for details on how to do this. Since customizing deployments to Azure is not an ASP.NET Core specific issue I don't think there is anything for us to add here.
