### ISSUE TITLE
Automatic Reconnect Article

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore.Docs#11093]
See https://github.com/aspnet/AspNetCore/issues/5282#issuecomment-360935433

Doc article summarizing how the automatic reconnect functionality being added to SignalR functions. Should include the following:

* [x] How to opt in
* [x] How to configure the reconnect timeout
* [x] What events are raised when the client succeeds or fails to reconnect automatically
* [x] Best practice for handling reconnecting event (e.g. disable client UI and/or queue server hub method invocations)
* [x] Description of exponential backoff process

**Comment by mikaelm12** [comment]
Done in https://github.com/aspnet/AspNetCore.Docs/pull/11951
