### ISSUE TITLE
Document unobtrusive validation

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#1111]
We should have API refs and conceptual content for the JavaScript libraries we ship for MVC.

1. [S.O answer by @poke ](https://stackoverflow.com/a/50148838/3365147)
2. [S.O answer by João Pereira](https://stackoverflow.com/a/35362280/3365147)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by os1r1s110** [comment]
I'm not sure if this is still active at all, but here are two stackoverflow links that might provide some help for those searching for documentation while waiting for official docs. 
1. [S.O answer by @poke ](https://stackoverflow.com/a/50148838/3365147)
2. [S.O answer by João Pereira](https://stackoverflow.com/a/35362280/3365147)

**Comment by danroth27** [comment]
@os1r1s110 Thanks for the useful pointers! The lack of docs for this library came up again recently and this is something that we want to address.
