### ISSUE TITLE
MemoryCache behavior when there is no SizeLimit

### ISSUE THREAD

**Issue by mikernet** [aspnet/AspNetCore.Docs#11216]
I can't find any documentation on how this cache behaves when no size limit has been specified. Does it start ejecting items when memory pressure reaches a certain point? Is this a suitable way to use the cache if you want it to use all available system memory or does it just grow without bounds?

---
#### Document Details

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
There is no set size. See https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#use-setsize-size-and-sizelimit-to-limit-cache-size
Yes
Yes

**Comment by mikernet** [comment]
I know there isn't a set size, but the docs aren't clear as to whether or not items start to get ejected when there is *memory pressure*. No set size doesn't necessarily mean it grows without bounds and starts to get paged out.

**Comment by mikernet** [comment]
@Rick-Anderson Also note that this indicates that this enum references "memory pressure triggered cleanup", furthering the ambiguity as to the behavior of the cache: 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheitempriority?view=aspnetcore-2.2

**Comment by mikernet** [comment]
@Rick-Anderson I appreciate your answers but this is an issue opened about the docs, i.e. a suggestion that they be clarified as I don't see these rather critical details documented anywhere.

**Comment by Rick-Anderson** [comment]
@JunTaoLuo please respond to cache limits.

**Comment by JunTaoLuo** [comment]
If no size is set, the cache will grow without bound. We do not evict on memory pressure.

**Comment by mikernet** [comment]
There are some other places that should have docs updated as well then, i.e  the cache entry priority enum if I recall, as it talks about it being entry priority during memory pressure compaction.

**Comment by JunTaoLuo** [comment]
It is still used. Though we do not trigger compaction, the user can still compact the cache with `MemoryCache.Compact(double percentage)`. When that is called, compaction will consider priority when evicting cache entries.

**Comment by mikernet** [comment]
I understand that now, but the inclusion of the “memory pressure” bit in the docs is confusing in 2 ways to readers like myself: 1) is it only used during memory pressure compaction or also during manual compaction, and 2) so is the cache capable of memory pressure compaction? If not then why is it mentioned?

**Comment by JunTaoLuo** [comment]
We no longer have automatic memory pressure compaction though we did have it at one point. The recommendation now is for users to create their own mechanism to determine when caches should be compacted and trigger compaction manually.

**Comment by Rick-Anderson** [comment]
@JunTaoLuo I'll add that to the docs.
Should I write, when memory is exhausted, behavior is indeterminate.
