### ISSUE TITLE
Add  API tests to Integration tests 

### ISSUE THREAD

**Issue by AnthonyMastrean** [aspnet/AspNetCore.Docs#11283]
It's not obvious from the content, but it seems like this only work with MVC projects? What about API projects (that is, projects using ApiController and ControllerBase and only returning like JSON responses, not views).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
AFAIK, the approaches work with web API. Of course, your tests will be a bit different given that the current topic sample uses AngleSharp to dig into view/page responses.

I'll mark this for the Integration Testing project. Engineering will decide what they would like to do at some point. They may want a separate topic for web API testing or perhaps just a separate sample attached to this topic.

**Comment by Lechus** [comment]
Def need separate topic for API testing.

**Comment by Rick-Anderson** [comment]
Moved to #16341: Integration tests MASTER issue
