### ISSUE TITLE
The first example under "Customize the model" breaks my ASP.NET core web app.

### ISSUE THREAD

**Issue by TheMadStrater** [aspnet/AspNetCore.Docs#11300]
After making the changes outlined I get the following error:  InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.

After a lot of research I finally discovered that the injections in _LoginPartial.cshtml need to be updated to use the new ApplicationUser.  does anyone actually try this stuff before publishing it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/55923110-c7b58300-5b9f-11e9-93ce-cb6c758e5a5d.png)

**Comment by Rick-Anderson** [comment]
@TheMadStrater  what portion did you encounter that problem? You must have been using old template generated code. The pre 2.0 templates used `ApplicationUser`, since 2.0 they've used `IdentityUser`. If you add user data, the default is 
```
public class MyUser : IdentityUser
    {
    }
```

**Comment by cremor** [comment]
@Rick-Anderson This still happens with templates from ASP.NET Core 2.2.4.

Repro:

1. `dotnet new mvc --auth Individual`
2. Modify the project as described in the section "Custom user data" [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#custom-user-data)
3. `dotnet run`
4. Exception is thrown: `InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager``1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.`

**Comment by Rick-Anderson** [comment]
@cremor at what step?

**Comment by cremor** [comment]
@Rick-Anderson What do you mean with "step"? Which part of the documentation I followed? If yes, just as I wrote, I did the whole "Custom user data" section. So I added an `ApplicationUser`, changed the base class of `ApplicationDbContext` and changed the `Startup.ConfigureServices` method.
