### ISSUE TITLE
Update Add, download, and delete custom user data to Identity to 2.2

### ISSUE THREAD

**Issue by azazael13** [aspnet/AspNetCore.Docs#11313]
There seem to be a lot of steps missing.  When I followed them I ended up with a good number of errors.  After looking at the sample code there is a lot missing.  Will the example above be updated to match what is in the sample code? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@azazael13 this is not a beginning tutorial.

**Comment by azazael13** [comment]
Is this not a tutorial for 'Adding custom user data to Identity'?  I have an app that I used the scaffold feature to add Identity into.  That worked no problem.  I wanted to add 3 custom fields to the Identity data.  After following this I received a bunch of errors.  If this isn't the tutorial for adding Custom user data, can you direct me where that one is?

**Comment by Rick-Anderson** [comment]
If you're having problems, don't start with you app. Start from scratch and follow the instructions.

**Comment by azazael13** [comment]
Even if I started from scratch there are still steps missing.

For example in the section: Update the Account/Manage/Index.cshtml page

You don't the following change highlighted
private readonly UserManager<WebApp1User> _userManager;

The change from IdentityUser to WebApp1User isn't covered anywhere.  Little things like that could leave someone very confused as to why they are having so many complications.

Other changes like changing the changes to the _LoginPartial aren't covered anywhere in this.

**Comment by rohankleem** [comment]
Yes, as it has me. Complete changes required to startup.cs, and as you I add this to a base application with identity setup and it screwed the whole thing.

**Comment by Rick-Anderson** [comment]
I'll try to get it updated this month.
