### ISSUE TITLE
Document how to add TypeScript support for .NET Core 2.0 + React Template

### ISSUE THREAD

**Issue by Weffe** [aspnet/AspNetCore.Docs#11326]
Currently, there is documentation on how to generate the .NET Core + React Template project that uses `create-react-app@1.1.5` which only supports JavaScript. As of `create-react-app@2.1.0` and above, it now [supports TypeScript](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#210-october-29-2018).

It would be nice if there could be some documentation on how to provide TypeScript support. Whether that's simply emptying out the `ClientApp` folder and running `npx create-react-app project-name --typescript`. Or, info on how to [bolt on TypeScript support](https://facebook.github.io/create-react-app/docs/adding-typescript) after the project files are generated.

Having this documented for usage of React + TS in .NET Core 2.0 would be great until the template gets updated in v3.0.0 release -- https://github.com/aspnet/AspNetCore/issues/5446

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16209
