### ISSUE TITLE
Clarify cascade delete

### ISSUE THREAD

**Issue by jacksos101** [aspnet/AspNetCore.Docs#11399]
In the note just above the "Modify Enrollment entity" heading, you state "if you didn't define the Department.InstructorID property as nullable, EF would configure a cascade delete rule to delete the instructor when you delete the department".

Isn't this meant to be the other way around, i.e. when you delete the instructor, the department is deleted by the cascade rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [Tutorial: Create a complex data model - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
I think the article is correct. cc @tdykstra

**Comment by Rick-Anderson** [comment]
I think the article is correct. cc @tdykstra

**Comment by tdykstra** [comment]
@jacksos101 is correct. If you delete the instructor, Department.InstructorId would have to be set to null, but since it can't be if it's nonnullable, the only way to maintain referential integrity is to delete the department entity.  I'll change the wording in the tutorials.

**Comment by tdykstra** [comment]
@jacksos101 Thanks for pointing that out!
