### ISSUE TITLE
Add Programatic Routing with IUriHelper

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore.Docs#11397]
I know it exists but currently it's not documented how to navigate programatically (IUriHelper) If im not mistaken this used to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7d0b96-7f5c-7330-f111-6e3f8fb94766
* Version Independent ID: 14285806-d00d-d7d9-594c-91f35e2912a0
* Content: [Razor Components routing](https://docs.microsoft.com/en-us/aspnet/core/razor-components/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/razor-components/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/routing.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by lanto3000** [comment]
See "https://chrissainty.com/blazor-bites-routing/" for using UriHelper.NavigateTo("/home");
