### ISSUE TITLE
Per-Application Isolation - app's configuration path

### ISSUE THREAD

**Issue by DavidDeSloovere** [aspnet/AspNetCore.Docs#11401]
Bullet 1 under "Per-Application Isolation" lists: "If the app is hosted in IIS, the unique identifier is the app's configuration path."

It's unclear what the "app's configuration path" exactly is. 
I assume it's not the "physical path of the app", as listed in bullet 2.
Is it the config path of the app in IIS? Which might just be the physical path of the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#setapplicationname)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I would've checked here, but the ANCM broke on the last preview release, and I'm waiting for a new one to come down. I would need to rollback my broken one, and I'm 🏃 out the door in a few minutes.

You can inject this somewhere (`Startup.Configure` for example) ...

```csharp
IOptionsMonitor<DataProtectionOptions> dpo
```

... and read the [ApplicationDiscriminator property](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionoptions.applicationdiscriminator?view=aspnetcore-2.2) from `dbo` ... that should tell you what it used.

**Comment by DavidDeSloovere** [comment]
Finally got back to this.
In Startup.Configure, the ApplicationDiscriminator still empty.
But when injecting DataProtectionOptions into a controller, I was able to see what the discriminator is:
It's the file path where the application is in. So not an IIS path, but an actual folder.
I'm getting this for both the InProcess and OutOfProcess hosting model.
Should docs be clarified?

**Comment by DavidDeSloovere** [comment]
My apologies. Docs have been updated already.
Well done. 👍
