### ISSUE TITLE
No XHTML self-closing style required

### ISSUE THREAD

**Issue by ygoe** [aspnet/AspNetCore.Docs#11404]
[EDIT by @guardrex to fix the HTML-encoding.]

Instead of `<partial name="..." />` it's also possible to write more HTML-like `<partial name="...">`.

Sources:
* https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/authoring
* https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.TagHelpers/PartialTagHelper.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [Partial Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by ygoe** [comment]
Oops, this form seems to have a bug. HTML-encoding wasn't requested here, yet it happened.

**Comment by guardrex** [comment]
> HTML-encoding wasn't requested here, yet it happened.

The **Content feedback** form does it. It's normal.

WRT closing tags, see :point_right: https://github.com/aspnet/Razor/issues/393#issuecomment-102735952

**Comment by ygoe** [comment]
I'm not having that issue from 2015. The code works perfectly without the `/>` style. The next issue referenced by you in the linked issue confirms that.

The documentation just doesn't mention it. I thought it would be helpful if everybody could read up in the documentation that it isn't necessary to write that XML-style markup but plain HTML style is fine.

**Comment by guardrex** [comment]
Oh, yeah. I forgot about that. I remembered the first remark but not the work/info that Taylor provided.

Cross-ref: https://github.com/aspnet/Mvc/pull/2956
