### ISSUE TITLE
LocalDB is Windows-Only

### ISSUE THREAD

**Issue by mrlife** [aspnet/AspNetCore.Docs#11419]
It should be communicated up front that SQL Server Express LocalDB is required in this tutorial (prerequisite that the tutorial and sample project will run on Windows only).

It would be useful to provide a few steps Linux and macOS users could take to use SQLite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=netcore-cli)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by amitpatelupw** [comment]
Gggjvsgb

**Comment by RanteCorp** [comment]
ghgftt
