### ISSUE TITLE
"...search the dependency tree and find controllers (even in other assemblies)"

### ISSUE THREAD

**Issue by LasseNisted** [aspnet/AspNetCore.Docs#11429]
The docs state that "By default MVC will search the dependency tree and find controllers (even in other assemblies).". This seems to not be the case for .NET Core. See https://stackoverflow.com/questions/37725934/asp-net-core-mvc-controllers-in-separate-assembly . My own example has one assembly with controller that references other assembly with Startup code. This does not resolve the controller. Can you elaborate on what is meant by "the dependency tree" and possibly state new behavior for .NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 please review

**Comment by serpent5** [comment]
@Rick-Anderson The setup sounds a little different here in that I _think_ @LasseNisted is suggesting that the `Startup` class assembly is a dependency of the controller's class assembly rather than the more typical other way around. I'll investigate.
