### ISSUE TITLE
How is this horrible document still not updated?

### ISSUE THREAD

**Issue by drullo** [aspnet/AspNetCore.Docs#11431]
After spending a lot of time trying to make this work and chasing down undocumented dependencies, I see that others commented on this frustrating problem last year.  And the response was a reference to an issue from February 2018 stating that this document was due for an update.  How is it now March 2019 and this hasn't been addressed and this document still exists as official public Microsoft documentation?

Also, I saw somebody comment about how frustrating it is to not have using statements included.  The response was that they are omitted for advanced users.  Well... I've been a developer since the mid 90s and I consider myself to be somewhat advanced.  And I can tell you that it is terribly frustrating to not have using statements included.  And how do you know if the consumer of the document will be "advanced"?  When I post articles, I always include all dependencies and assume nothing about the reader.

With that being said... where are User() and UploadData() defined??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by emhomm4** [comment]
Viewing the whole sample project on GitHub was essential for me to make any progress on this. It's linked at the top.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
