### ISSUE TITLE
The requirements of the class to create a custom middleware are not well documented

### ISSUE THREAD

**Issue by meziantou** [aspnet/AspNetCore.Docs#11443]
What are the exact requirements for writing a custom middleware as a class?

- A constructor with a single parameter of type `RequestDelegate`
- A method named `Invoke` or `InvokeAsync`
  - must return a `Task`?
  - must have a parameter of type `HttpContext`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I agree. That should be explained in the first section.

**Comment by APIWT** [comment]
This brings up an interesting point: Should there be an interface for implementing middleware?

**Comment by meziantou** [comment]
There is already the interface `IMiddleware`. But you are not required to use it.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.2

**Comment by AgentFire** [comment]
I've created a request for it: https://github.com/dotnet/AspNetCore.Docs/issues/34730

You **should** be inclined to use the interface, im my opinion. The old way should start to be getting deprecated.
