### ISSUE TITLE
Need   <FrameworkReference Include="Microsoft.AspNetCore.App" /> ?

### ISSUE THREAD

**Issue by niltor** [aspnet/AspNetCore.Docs#11488]
If I don't replace the &lt;PackageReference&gt; with a &lt;FrameworkReference&gt;,there are  some runtime errors .
When I change cshtml files,there will be error like  " Cannot find reference assembly XXX".
So，If it's necessary replace the &lt;PackageReference&gt; with a &lt;FrameworkReference&gt;,I think it should be clear in the documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#update-the-project-file)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
What version of the the SDK do you have installed, and does your project file start with
```
<Project Sdk="Microsoft.NET.Sdk.Web">
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
