### ISSUE TITLE
Streaming to a target .net client

### ISSUE THREAD

**Issue by hodgezappa** [aspnet/AspNetCore.Docs#11539]
Is there a way to allow the server to target a particular client when streaming, in the same way we can with non streamable messaging?
I can do this on the server:
await _hubContext.Clients.Client(idOfTheClientConnectionIWant).SendAsync("foobar");
but when streaming the example talks about the threading channel reader and writer, how do i link this to my hubContext so i can specify my clientId?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by calhamdower** [comment]
Is there any way to do this yet?
At the moment I assume the client will still need to request the stream from the server which can construct a new stream... 
but this scenario is probably pretty desirable:
ClientA = Stream => Server = stream => ClientB

At the moment it would need to be
ClientA = Stream => Server (server stores data)
ClientA = notify of available stream => Server (however you want to do this... maybe not even needed) => Client B Notified of available stream
ClientB = request stream => Server (creates new stream) = stream = > Client B

Its a bit verbose compared to the scenario @hodgezappa was after

**Comment by BrennanConroy** [comment]
This is not possible today. Closing in favor of issue https://github.com/aspnet/AspNetCore/issues/10151 filed on the product repo.
