### ISSUE TITLE
Activation from a runtime store-deployed assembly

### ISSUE THREAD

**Issue by a14907** [aspnet/AspNetCore.Docs#11575]
It is realy hard to follow in this section! what stop 1 and step 2 mean!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Use hosting startup assemblies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @a14907 ... Sorry for the delay getting back to you. I'm away at a conference, so communication is slow until I get back on Saturday.

Thanks for letting me know about that broken step. We made BIG changes to the demonstration with the sample about a week ago, and we failed to update this step (Step 2).

Until I get a chance to fix it ...

1. Execute the build.ps1 script in the RuntimeStore folder.
1. Run the deploy.ps1 script in the 'deployment' folder.

Fortunately, Pavel included code comments in the scripts to explain what's happening, and it matches what the topic describes earlier. 

I'll probably put in a quick PR today to patch that step, but I'd also like to put in a PR when I get back that explains those script comments in the doc. Doc content is localized, but code comments aren't.
