### ISSUE TITLE
Building the config in a configuration callback can cause repeated network calls

### ISSUE THREAD

**Issue by VladCananau** [aspnet/AspNetCore.Docs#11616]
Calling `var builtConfig = config.Build();` within the callback passed to `ConfigureAppConfiguration` seems like a bad practice because it causes the configuration to be built multiple times at application startup. Consider, for example, that `config.AddAzureKeyVault` itself sets up a network call for the next time (and actually all the subsequent times) that `config.Build()` is called. It is easy to imagine how a number of N extensions methods that follow this pattern of "build the config that we have so far, get a setting from it, then add a callback of my own" can set up `1 + 2 +3 + ... + N` network calls out of which `1 + 2 + .. + N-1` are redundant and duplicated. Those extension methods could come from libraries, with no way for the user code to guard against the effect. Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @VladCananau ... Thanks for commenting. We only handle doc issues on this repo. Provide that feedback at :point_down:

https://github.com/aspnet/AspNetCore/issues

**Comment by VladCananau** [comment]
>  We only handle doc issues on this repo. Provide that feedback at 👇
> 
> https://github.com/aspnet/AspNetCore/issues

I'm indeed reporting it as a doc issue. That's to say the article is proposing to the reader to use a potentially bad practice without warning of the possible side-effects. This is indeed a doc issue.

**Comment by guardrex** [comment]
The doc is describing the practices and recommendations provided by engineering. We usually have engineering issues/questions go to the aspnet/AspNetCore repo issues and then if the engineers determine that a doc update is required we take it from there. This is fine to discuss here if you prefer. I'll tag it for triage here. Standby for a bit tho ... The MVP Summit is this week, so we might not hear back until next week (or the week  after : 🏃:sweat_smile:).

**Comment by VladCananau** [comment]
> Standby for a bit tho ... 
Fair enough, cheers!
