### ISSUE TITLE
Update twitter external login

### ISSUE THREAD

**Issue by PieterjanDeClippel** [aspnet/AspNetCore.Docs#11642]
Twitter has modified this procedure. Update of docs may be required
![image](https://user-images.githubusercontent.com/3605364/57482750-2292d680-7241-11e9-8c02-2e3049dd80f0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@01binary are you familiar with the new twitter developer account and procedure?  I've applied for a developer account.
