### ISSUE TITLE
docker support uses old registry for aspnetcore-runtime (2.2)

### ISSUE THREAD

**Issue by arigelni** [aspnet/AspNetCore.Docs#11678]
still the "old" images from the docker-hub registry is taken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Remove images when this is updated. Doc's other than onboarding need an exception approval to have images.

**Comment by Rick-Anderson** [comment]
Moved to #16250
