### ISSUE TITLE
Examples on how to affect the Layout rendering from Body component

### ISSUE THREAD

**Issue by RichiCoder1** [aspnet/AspNetCore.Docs#11682]
It's not clear if it's possible to pass data from the wrapped component to the Layout ala https://docs.microsoft.com/en-us/aspnet/web-pages/overview/ui-layouts-and-themes/3-creating-a-consistent-look#passing-data-to-layout-pages, and if so how. Clarification would be great

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce76032-e7b4-d168-6e24-c2cb88ae7e44
* Version Independent ID: f3ecd255-c3ce-9162-ddf1-67b35aeffc11
* Content: [Razor Components layouts](https://docs.microsoft.com/en-us/aspnet/core/razor-components/layouts?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/razor-components/layouts.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/layouts.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Might be a dup or related to https://github.com/aspnet/Docs/issues/11243.

**Comment by guardrex** [comment]
I'll be working on #11243 tomorrow (Wednesday, 4/3). @RichiCoder1, I'm going to move this to a comment on that issue as a reminder to test the `EventCallback` bits with a layout to confirm it works. Even if it doesn't work as expected (and I doubt that will be the case), I'll note that it doesn't work with layouts in the PR tomorrow. Thanks for opening this ... you can track it on #11243.

**Comment by guardrex** [comment]
We discussed this: We have coverage enhancements to make for this scenario: A useful approach is using a service (DI) to communicate across the component-layer barrier. We'll document that approach.

**Comment by guardrex** [comment]
@RichiCoder1 Engineering is going to address it formally. https://github.com/aspnet/AspNetCore/issues/10131

**Comment by RichiCoder1** [comment]
Sounds good! The referenced issue is basically exactly what I was looking for.

**Comment by guardrex** [comment]
@RichiCoder1 *Yes*, was happy to hear from DR that they're working on a framework scenario for it. At least in the short-term until they get there (this preview) , the approach offered by @sven5 is pretty sweet. That should at least tide everyone over. We'll get the bits that they build into the docs ASAP after release.
