### ISSUE TITLE
Model Binding does not work on a complex type with both [FromBody] and [FromHeader]

### ISSUE THREAD

**Issue by markpritchett** [aspnet/AspNetCore.Docs#11699]
Version: ASP.NET Core 2.2

Trying to bind to a type that has both `[FromBody]` and `[FromHeader]` attributes doesn't work.

Given the following class:

``` CSharp
public class Mixed
{
    [FromBody]
    public string BodyName { get; set; }
    [FromHeader]
    public string HeaderName { get; set; }
}
```

And the following controller endpoint:

``` CSharp
[HttpPost("single-complex-type-body-and-header")]
public ActionResult SingleMixedComplexType(Mixed mixed)
{
    return Ok(mixed);
}
```

Only the `BodyName` property is set; The `HeaderName` is null.

The only way I can get `[FromHeader]` to work on a complex type is to define it as a separate type, for example:

``` CSharp
public class BodyOnly
{
    public string BodyName { get; set; }
}

public class HeaderOnly
{
    [FromHeader]
    public string HeaderName { get; set; }
}
```

And controller endpoint:

``` CSharp
public ActionResult SeparateComplexTypes(BodyOnly bodyOnly, [FromHeader]HeaderOnly headerOnly)
{
    return Ok(new SeparateTypesResponse
    {
        BodyOnly = bodyOnly,
        HeaderOnly = headerOnly
    });
}
```

I've got a basic repository to demonstrate the issue - if you have a look at [these tests](https://github.com/markpritchett/AspNetCoreApiModelBindingFromHeaders/blob/master/AspNetCoreApiModelBindingFromHeaders.Tests/ExampleTests.cs) (the first test fails for the single mixed type, the second test passes for two separate types).

Is this an issue or by design?  If it's by design, is it worth explaining [in the docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2)?

**Comment by Rick-Anderson** [comment]
@dougbu please review.

**Comment by dougbu** [comment]
Not sure if this is worth explaining in the docs. That depends on the exact issue. If for example, there were a header named `Mixed.HeaderName` in the request, `mixed.HeaderName` will not be bound. However headers named `HeaderName` in the first case and `HeaderOnly` in the second should bind correctly (and case-insensitively).

@markpritchett please describe what's submitted when model binding does not work as you expect.

**Comment by markpritchett** [comment]
@dougbu model binding doesn't work as I expect when I call my `SingleMixedComplexType` method where I'm trying to bind from both the request body and headers into the method's `Mixed` type argument. 

 Having a single type argument and having the properties bound from different parts of the request seems like it should work but it doesn't.  It feels cleaner to me to have a single complex type as a argument instead of having to have two separate complex types (like I did in the second example - `SeparateComplexTypes`)

In my example [repository](https://github.com/markpritchett/AspNetCoreApiModelBindingFromHeaders/tree/master), my first test `SingleMixedComplexType_Maps_From_Header_And_Body` fails as `result.HeaderName` is null.  Here's the test for ease of reference:

``` CSharp
[Fact]
public async Task SingleMixedComplexType_Maps_From_Header_And_Body()
{
    _client.DefaultRequestHeaders.Add("HeaderName", "HeaderValue");

    var request = new { bodyName = "BodyValue" };

    var responseMessage = await _client.PostAsJsonAsync("api/example/single-complex-type-body-and-header", request);
    var result = await responseMessage.Content.ReadAsAsync<Mixed>();

    Assert.Equal("HeaderValue", result.HeaderName);
    Assert.Equal("BodyValue", result.BodyName);
}
```

So I'm wanting clarification on whether:

(a) I'm doing something wrong / missing something to get the first case working correctly;
(b) It's not meant to function in that way.  If this is the case, does this need explaining in the docs?
(c) It's an issue

**Comment by Rick-Anderson** [comment]
@dougbu  please respond

**Comment by dougbu** [comment]
> I'm doing something wrong

I haven't read through everything but this is my suspicion. The body you're sending in the test is a JSON object and not a string. Assigning that to a C# `string` property shouldn't work.

**Comment by zackshine** [comment]
Please refer to https://stackoverflow.com/questions/58038884/fromheaderattribute-doesnt-work-for-properties

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
