### ISSUE TITLE
An error occured when adding Blazor template.

### ISSUE THREAD

**Issue by ThinhVu** [aspnet/AspNetCore.Docs#11703]
An error occurred when I running "dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.9.0-preview3-19154-02" command. The reason is a folder named "NuGetPackages" doesn't exist in "C:\Program Files (x86)\Microsoft SDKs".
Solution for this problem is create new folder NuGetPackages then run above command again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by danroth27** [comment]
This appears to be a framework issue, not a doc issue. If you are are still seeing this issue please create a new issue in the https://github.com/aspnet/aspnetcore repo.
