### ISSUE TITLE
Multiple razor pages with the same name in multiple projects, which takes priority, and can the priority be overridden?

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore.Docs#11700]
If there are multiple razor pages with the same name in multiple projects, which takes priority, and can the priority be overridden?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Matthew-Bonner** [comment]
The reference to "project" relates to Razor class libraries specifically where there is no razor page in the web project itself.

/web
  /pages
    /foo.cshtml

/rcl1
  /pages
    /index.cshtml

/rcl2
  /pages
    /index.cshtml

web inherits both rcl1 and rcl2

the build order is rcl1, rcl2 then web

rcl1 index.cshtml is the page that loads when developers may have expected this to be the index.cshtml in rcl2.

I think this should be clarified in the docs.

**Comment by Matthew-Bonner** [comment]
Is the order based on alphanumeric order?

As it doesn't seem to matter what build order I use, or which projects reference which, so I'm also inclined to raise a feature request to allow a degree of control over which razor page takes priority, if a feature request doesn't already exist.

**Comment by Matthew-Bonner** [comment]
I also noticed on another page, "The order of the entries in the ApplicationParts collection isn't important." is specified, but this is untrue, as the order does matter if you have multiple projects. The order appears to be alphanumeric.

The quote came from the following page:
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts

**Comment by Rick-Anderson** [comment]
If you want to use multiple pages with the same name, use [Areas](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.2)

**Comment by Matthew-Bonner** [comment]
Hi Rick

Sorry maybe I wasn’t being clear enough, I’m not wanting to use the same page name in different areas, I’m wanting to have one project inherit multiple projects whereby the structure of the frontend is built up from a series of projects, so if the page doesn’t exist in the overriding project it falls back to the page in the base project.

Please could you reopen this.

Thanks
Matt

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by bamdad-b** [comment]
This feature is really needed for our product. Consider how one could expand this feature for complex scenarios. I think one of the main options in having a multi-part web solution is to be able to prioritize the parts. Get another 👍 from me, thanks.
