### ISSUE TITLE
Rewrite and adapt ASP.NET Core Docker article from .NET Core repo

### ISSUE THREAD

**Issue by Thraka** [aspnet/AspNetCore.Docs#11705]
There is an article in the .NET Core repo that talks about creating an ASP.NET Core Docker image and container that is more suited to live in this doc set. 

https://github.com/dotnet/docs/blob/ea80a5bdcfc37d09204643aa50a7bae52410261f/docs/core/docker/building-net-docker-images.md

I'm going to delete that article as I publish updates to the Docker area of .NET Core. Please let me know when you get this article rewritten and published and I will link back and provide a redirect from the old page to the new one.

@scottaddie

**Comment by tdykstra** [comment]
> let me know when you get this article rewritten and published and I will link back and provide a redirect from the old page to the new one.

@Thraka You can redirect to https://docs.microsoft.com/aspnet/core/host-and-deploy/docker/building-net-docker-images

**Comment by Thraka** [comment]
Thanks. I filed https://github.com/dotnet/docs/pull/11933
