### ISSUE TITLE
Split Host and Deploy RC/Blazor content

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11714]
@tdykstra We need to split the RC and Blazor *Host and deploy* content.

Two possible approaches leap to mind ...

## 1

~An overview for each hosting model can hold the common content using an INCLUDE. The *Overview* topics can then cover each hosting model.~

[EDIT] **NOT USING :point_down: :-1:**

```
Host and deploy (*host-and-deploy* folder)
    ... other nodes ...

    Blazor node (*blazor* folder)
        Overview (*index.md*) - INCLUDE for common content followed by Blazor-specific content.
        Configure the Linker topic (*configure-linker.md*)
        
    Razor components node (*razor-components* folder)
        Overview (*index.md*) - INCLUDE for common content followed by RC-specific content.

    ... host and deploy topics ...
```

[EDIT] **WILL USE :point_down: :+1:**

## 2

Here's an alternative that uses a common node (`Razor Components/Blazor`) ...

```
Host and deploy (*host-and-deploy* folder)
    ... other nodes ...

    Razor Components/Blazor node (*razor-components-blazor* folder)
        Overview (*index.md*) - Contains the common content.
        Blazor (*blazor.md*) - Blazor-specific host and deploy content.
            Configure the Linker topic (*configure-linker.md*)
        Razor Components (*razor-components.md*) - RC-specific host and deploy content.

    ... host and deploy topics ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df31b39a-669b-f6a1-4385-04bd39e921f9
* Version Independent ID: 19409cdc-3ec8-cacb-d21f-6dd90e29f291
* Content: [Host and deploy Razor Components](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/razor-components/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@guardrex I'm not familiar enough with the documentation to make a strong recommendation either way.  I incline toward #2 but if you prefer #1, I'd say try it and see how it works.

**Comment by guardrex** [comment]
I agree. When linking to this content in a general way ('For more info, see ...') ...

* Option #2 allows us to link to **_one_** *Overview* topic. The reader can pursue the additional content in either or both hosting model topics. The TOC is already set up this way, so I just need to change the node text and add the two hosting model topics. *Easy Squeezie!* :+1: 
* If we went with #1, we'd always be picking one *Overview* or the other in each linking case (bit of a pain for us). If a reader reads both, they're faced with having to bypass the duplicated common content in the second hosting model topic that they read. :-1:

Let's go with #2. Looks a lot better.
