### ISSUE TITLE
MySQL dsitributed Caching

### ISSUE THREAD

**Issue by ChaosEngine** [aspnet/AspNetCore.Docs#11730]
There is also MySQL variant alternative to distributed cache.
It is handled by PomeloFoundation (https://github.com/PomeloFoundation/Caching-MySQL)
If you like I could extend the docs and write up something about this variant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hold off until management can take a look. They may decide that it's too risky for us to include/link.

**Comment by danroth27** [comment]
Typically we link to related third party projects that implement our core abstractions from our readme files on GitHub. I would recommend sending a PR to add a link to this project to the caching readme in the extensions repo: https://github.com/aspnet/Extensions/blob/master/src/Caching/README.md
