### ISSUE TITLE
Postman Callback Url has been changed

### ISSUE THREAD

**Issue by piotrzuzak** [aspnet/AspNetCore.Docs#11750]
Hi,

Postman has changed callback url. Please update documentation. New link is =&gt; https://www.getpostman.com/oauth2/callback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by aszalacinski** [comment]
Sooooo is this need an update or not?

**Comment by Rick-Anderson** [comment]
Moved to #16186
