### ISSUE TITLE
Pitfalls writing scalable services in ASP.NET Core

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11754]
I recommend making the *ASP.NET Core Guidance* for *Common Pitfalls writing scalable services in ASP.NET Core* part of the official docs (cc: @davidfowl):

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md

* The content can appear in an *Advanced* node topic.
* Most of the sections should be linked from appropriate areas elsewhere and not duplicated.
  * The [Access HttpContext topic](https://docs.microsoft.com/aspnet/core/fundamentals/http-context) already covers *HttpContext access from a background thread*, but there are several other scenarios in the *Common Pitfalls* content for HttpContext not covered by the *Access HttpContext* topic.
  * The DI topic covers scopes for calling services from main but doesn't mention the controller scenario.
  * There's no coverage on some of them: For example, there's no coverage on *Prefer using HttpRequest.ReadAsFormAsync() over HttpRequest.For*.

If we do this, there are two sections without content. We might need to wait for content on these two before proceeding:

* Use buffering and synchronous reads and writes as an alternative to asynchronous reading and writing
* Avoid reading the entire request body or response body into memory

I'll tentatively take this on for post 3.0 RTM if you want to proceed with it.

**Comment by Rick-Anderson** [comment]
@guardrex  see #14734
