### ISSUE TITLE
Application Profile Example

### ISSUE THREAD

**Issue by alexandercarls** [aspnet/AspNetCore.Docs#11760]
I would love to see an example of a typical microservice architecture utilizing this tooling with the following services:
* A standalone IdentityServer (this is not mentioned in the profile section, not sure if this is part of it)
* "SPA" - standalone SPA, communicates with IdentityServer and the API.
* "API" - standalone API, communicates with IdentityServer

A sample solution with a link in the docs is enough, this should set the user up for success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by mdmoura** [comment]
Can someone, please, confirm if as of Preview 7 is it possible to have the Auth, SPA and API in different applications?

**Comment by javiercn** [comment]
This is not something we are targetting in this release. For 3.0 all the components live on the same application. Yo are free to follow any of the many IdentityServer tutorials that explain how to achieve this scenario.

**Comment by mdmoura** [comment]
@javiercn I thought it would be possible even if not in the template because [Application profiles](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#application-profiles) section in the Docs.

Wouldn't SPA and API profiles be exactly that?

**Comment by javiercn** [comment]
It is possible, but we are unlikely to produce such a sample as is not a core target for this release.

The main difference is that you need to specify the client redirect url explicitly, the API explicitly and configure the JWT bearer handler in the API.

**Comment by nkaenzig** [comment]
https://fullstackmark.com/post/21/user-authentication-and-identity-with-angular-aspnet-core-and-identityserver
