### ISSUE TITLE
Odata Documentation

### ISSUE THREAD

**Issue by FIVIL** [aspnet/AspNetCore.Docs#11770]
I want to add a few articles (and code examples as well) about Odata support in ASP.net core so as required in CONTRIBUTING.md file for complex submissions i opened this issue to get approval for them.
what i have in mind is a simple example of adding odata capabilities on top of existing API and also some tips for scenarios which include  starting a new API project  with odata support from scratch.
also i come across this (https://github.com/aspnet/Docs/issues/9740) open issue about odata so i was wondering should i do it or wait for odata official team.
also i think it worth to mention that im having 1.5+ years experience with ASP.net core and 3+ years experience with C# and ASP.net mvc (.net framework) and also good understanding of odata.

@Rick-Anderson  edit:

Reopen this and PR #12108 When https://github.com/MicrosoftDocs/OData-docs/pull/74 is merged. Look for closed issues with ODATA `in:title`

**Comment by Rick-Anderson** [comment]
@FIVIL thanks for checking first. @blowdart and @HaoK will make that decision. They'll probably want an outline before you start.

**Comment by blowdart** [comment]
As long as the security implications and mitigations are covered I have no problems.

**Comment by Rick-Anderson** [comment]
@FIVIL  can you post an outline here?

**Comment by FIVIL** [comment]
@Rick-Anderson  Sure.
as i mentioned earlier what i have in mind contains two separated parts which are 
1. Adding OData support to a existing REST API 
1. Creating a new REST API with OData support

for the first one i do not intend going into details so ill make a single article .
in this single article i will explain how you can add OData support to your existing API with as less modification as possible in your codebase without breaking the existing API routes with backward compatibilities.
in this article i will expand [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) already existing project in docs, though i might change the model class for better demonstration of OData capabilities by adding some new properties
the outline will look like this:

1. Overview 
-what we are going to build-
1. Prerequisites 
-VS 2017+ and .ner core SDK 2+-
1. Introduction
-what is OData-
1. Loading the project
-which as i mentioned in this step i will show how you can load the existing project in VS-
1. Adding Nuget Packages
-i will use [this](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/) official package from MS-
1. Updating Model Class
-adding some new properties to use OData capabilities-
1. Adding migratings
1. Registering required services in DI container
1. Configuring middlewares
-i will show how you can add OData route and also how you can expand your existing API routes using ` routeBuilder.EnableDependencyInjection();`-
1. Changes in Controllers
1. some example 
-how to invoke new api methods using OData queries-
1. Security concerns
-how you can prevent or add some OData features-
1. Additional resources
ill try to make this article as short and as simple as possible

also i will add some code examples and i might include some screenshots from postman to showing the result of invoking the API

for the second part i intend to make a couple of articles and in them i will go further into details and internals of OData
Outline:
article number 1 -> Overview : what the end result would look like and link to other articles in this series
article number 2 -> complete introduction to OData, explaining that how OData is actually a open specification and .net core libraries, also i will dive into query language and functionalities of OData
article number 3 -> Getting Started
1. Prerequisites 
1. Creating The Project
1. Adding Nuget Packages
1. Running the Project to make sure everything is fine

article number 4 -> adding model classes:
in this step i will use the contos university example which is a well understood example from MS
article number 5 -> Configuring Database:
1. Adding database context class
1. Adding migrations

article number 6 -> Configurations of the project:
1. Adding Services in DI container
1. Adding middlewares with much more details

article number 7 -> Scaffolding
1. Scaffolding the Controllers
1. Applying required changes to the controllers

article number 8 -> Pushing some data into API
article number 9 -> Examples:
1. querying data
1. querying a single record
1. filters
1. querying  relational data
1. invoking functions

article number 10 -> Security concerns


so im expecting to do this in at least 3 RRs one for article number 1, one for series of articles in 2nd part and one last PR for the code examples

**Comment by Rick-Anderson** [comment]
Looks good to me.
 @blowdart and @HaoK  any comments on the outline?

**Comment by Rick-Anderson** [comment]
@FIVIL would you be interested in helping @guardrex  with #5106?

**Comment by FIVIL** [comment]
@Rick-Anderson Sure, honestly im having some spare time within next few month and i want to get best out of it by contributing to aspnet repos, so im open to help with any task that can be done by community.
also im waiting for @blowdart  and @HaoK  approval for OData doc outline so i can get started on them as well.

**Comment by guardrex** [comment]
I think #5106 provides what I need to perform the update. Within `Tratcher`'s remarks, I see about three aspects missing from the topic. @FIVIL, I'll ping u on the PR to review it if you have time.

**Comment by FIVIL** [comment]
@guardrex  sounds great to me, so im waiting to hear from you.

**Comment by Rick-Anderson** [comment]
@FIVIL ping me next week if @blowdart  doesn't approve your outline. @scottaddie / @danroth27  please review outline.

**Comment by blowdart** [comment]
Harsh but fair @Rick-Anderson.

Security to 10 maybe? My concern here is, for example, someone reads enough to expose their data because that's what they want to do, without understanding they now have a DoS vector or Information Leak via joins. 

Notes in each section to the security section would work though.

**Comment by FIVIL** [comment]
@blowdart sure, ill keep your notes in mind.

**Comment by FIVIL** [comment]
so im trying to deliver first draft as soon as possible.

**Comment by FIVIL** [comment]
@Rick-Anderson 
I'm done with the first set of tutorials, however, I will cover more materials in the next set of articles.
you can check out the sample files in:
https://github.com/FIVIL/AspNetCore.Docs/tree/OData/aspnetcore/tutorials/first-odata-api/samples/2.2/TodoApi
and markdown file in:
https://github.com/FIVIL/AspNetCore.Docs/blob/OData/aspnetcore/tutorials/first-odata-api.md
and tell me if they are Ok, so i can send a PR, or if they need any changes

TNX

**Comment by Rick-Anderson** [comment]
@FIVIL  looks great. Create a PR then I'll submit some commits to your branch for minor edits.

**Comment by Rick-Anderson** [comment]
@FIVIL when you submit the PR, `@mention me only` so I have a chance to make some edits, then we can mention `@blowdart`

**Comment by Rick-Anderson** [comment]
@FIVIL  I moved two of them over - see https://docs.microsoft.com/en-us/odata/webapi/odata-expand
The last one is in PR at https://github.com/MicrosoftDocs/OData-docs/pull/83
