### ISSUE TITLE
Where and how does the BooksData folder get used 

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#11785]
In Step 1, we create a BooksData directory on the local machine to store data. However, after completing all the listed steps to get Web API project running, the data directory remains empty. 
So how and when does the data directory get filled? If those steps are not part of the project, then why is it needed to be created in the first place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Build web APIs with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio#next-steps)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
@krchome  In step 2, you set the directory we created in step 1 as the default directory for your data.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
