### ISSUE TITLE
Examples aren't clear on where the code go

### ISSUE THREAD

**Issue by Panzerbjrn** [aspnet/AspNetCore.Docs#11789]
While the code samples are fine, there is no information on where they go.
By this I mean, which file(s) are meant to contain the various code samples.

**Comment by guardrex** [comment]
Hello @Panzerbjrn ... Close this issue and open the issue from the page you're looking at using the *Send feedback about:* **This page** button at the bottom of the topic. It tags the issue with metadata that helps us track the issue. If there are multiple pages, you can list them in a comment here.
