### ISSUE TITLE
Surface 3.0 Windows service project template in WS topic

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#11791]
[.NET Core Workers as Windows Services](https://devblogs.microsoft.com/aspnet/net-core-workers-as-windows-services/)

**Comment by guardrex** [comment]
If the current WS topic is used for guidance in constructing this tutorial, I recommend holding off for a bit. I'll be working the WS topic for 3.0 when Preview 4 releases (sometime between P4 and P5). The updated guidance should help on this one if this issue goes forward.

**Comment by guardrex** [comment]
[Windows Service topic+sample update for 3.0 (aspnet/AspNetCore.Docs #12449)](https://github.com/aspnet/AspNetCore.Docs/pull/12449) just merged. It includes usage of the Generic Host for 3.0.

If you decide against a tutorial, I can surface the template in the current WS topic. Assign me.
