### ISSUE TITLE
HttpPost requires `[FromBody]`

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11790]
[Moved from https://github.com/aspnet/Docs/issues/11787.]

@Jaygem asks ...

# Issue
In [this page](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio) at the HttpPost section there's a missing `[FromBody]` attribute : 

original : 
```csharp
// POST: api/Todo
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem item)
{
    _context.TodoItems.Add(item);
    await _context.SaveChangesAsync();

    return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);
}
```

Working solution for me : 

```csharp
// POST: api/Todo
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem([FromBody] TodoItem item)
{
    _context.TodoItems.Add(item);
    await _context.SaveChangesAsync();

    return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2):
`[FromBody]` is inferred for complex type parameters .

**Comment by Rick-Anderson** [comment]
I think we're using the same code as the scaffolder. We should verify that and use the same code.

**Comment by Rick-Anderson** [comment]
if you're using ASP.NET Core 2.1+, you can also use the `[ApiController]` attribute to automatically infer the `[FromBody]` binding source for your complex acti

**Comment by Jaygem** [comment]
I tried it and it worked, thank you for your time!
