### ISSUE TITLE
[Preview 4] Blazor configurable initialization

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11795]
https://github.com/aspnet/AspNetCore/pull/8901

This issue will be worked when Preview 4 is released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8227c67e-83bb-dee3-e31c-73097df59614
* Version Independent ID: e7b564a3-b078-c390-15ba-b5044bd4edec
* Content: [Get started with Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-components/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorcomponents**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
Additional information, we want to link to the docs for troubleshooting SignalR connectivity. This came up because we had a bunch of users in the last preview who couldn't diagnose SignalR connection issues. So the idea that you collect diagnostics this way should be front and center.

**Comment by guardrex** [comment]
This was mostly resolved by https://github.com/aspnet/AspNetCore.Docs/pull/12048, but I'm going to attempt a cross-link to SignalR troubleshooting on https://github.com/aspnet/AspNetCore.Docs/pull/12061.
