### ISSUE TITLE
Update source MVC/EF in next doc sweep

### ISSUE THREAD

**Issue by jwhitener6** [aspnet/AspNetCore.Docs#11805]
the source code does not work for me, neither the starter or the final. It just fails missing a viewmodel or data not transferred in the migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [Tutorial: Update related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
2.2K PV
@jwhitener6  what migration? We have lots of customers reporting success on this.

**Comment by jwhitener6** [comment]
It was the InitialCreateDB I gather. the migration appears to work but testing gives error for a missing person table for me. This is for final/completed sample.

On Apr 3, 2019 1:03 PM, Rick Anderson <notifications@github.com> wrote:

2.2K PV
@jwhitener6<https://github.com/jwhitener6> what migration? We have lots of customers reporting success on this.

**Comment by Rick-Anderson** [comment]
Tested, works fine.
