### ISSUE TITLE
1.0.0 Not released on Maven

### ISSUE THREAD

**Issue by freeknortier** [aspnet/AspNetCore.Docs#11804]
The latest version in Maven is '0.1.0-preview2-35174' and not '1.0.0' as stated above. This is for an Android client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e954a77-daa3-980c-0a0b-c4e7dabc8ed0
* Version Independent ID: 09e7b88b-8373-89d4-7360-d71370c095da
* Content: [ASP.NET Core SignalR Java client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/java-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/java-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @mikaelm12
* Microsoft Alias: **mimengis**

**Comment by freeknortier** [comment]
Here is a link to the Maven page : https://mvnrepository.com/artifact/com.microsoft.aspnet/signalr

**Comment by BrennanConroy** [comment]
We point to com.microsoft.signalr/signalr in the doc. You're using the wrong package.

https://mvnrepository.com/artifact/com.microsoft.signalr/signalr

**Comment by mikaelm12** [comment]
Specifically we changed the package name from _com.microsoft.aspnet_ to _com.microsoft.**signalr**_
The artifact ID is still _signalr_ though.

**Comment by freeknortier** [comment]
@mikaelm12 @BrennanConroy Thanks for your replies. com.microsoft.signalr is not compatible as a drop in replacement for com.microsoft.aspnet.signalr. Is there any documentation/wizards for migration to com.microsoft.signalr?

**Comment by mikaelm12** [comment]
These were both preview releases of the first version of the SignalR java client so we weren't tracking breaking changes yet. What issues are you seeing?

**Comment by mikaelm12** [comment]
Closing this as we haven't heard from you in a little while. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
