### ISSUE TITLE
IdentityServer4 specific example? Should this not be generic

### ISSUE THREAD

**Issue by vurso** [aspnet/AspNetCore.Docs#11806]
Is this guide specifically for IdentityServer4 because the following code block is specific to IDS4:

services.AddDefaultIdentity<IdentityUser>(config =>
    {
        config.SignIn.RequireConfirmedEmail = true;
    })

I am trying to avoid using and 3rd party modules and only using what comes with dotnet core 2.2 etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This works with ASP.NET Core.

**Comment by vurso** [comment]
Didn't for me I am on the latest SDK for 2.2 in VS2017 my service collection doesn't have an AddDefaultIdentity method (did I forget to install something)?

Appreciate the help cheers.

**Comment by vurso** [comment]
@Rick-Anderson not going to open another issue unless you need me to but the page needs some clarification specifically it assumes people will be using a Web Application project and not a Web API project.

In my case the Microsoft.AspNetCore.Identity.UI library was missing for obvious reasons as its a headless project and therefore does not have a UI (or requires one being an API).

Thanks.
