### ISSUE TITLE
summary and response details only included in swagger if XML documentation is read

### ISSUE THREAD

**Issue by hf-kklein** [aspnet/AspNetCore.Docs#11809]
To improve the documentation I'd suggest to add a sentence similar to the following:

Some swagger feature do work without the use of a XML file based documentation, e.g. the scheme for a request body or the possible response codes (if specified in attributes). To make use of the &lt;summary&gt; or &lt;response code="..."&gt; tags the use of the XML based documentation file is mandatory, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@hf-kklein would you be interested in creating a PR to address this issue? cc @scottaddie
