### ISSUE TITLE
Need a pure HTML5 front end (no Razor, or other backend dependency) for File Upload solution

### ISSUE THREAD

**Issue by davidekarasek** [aspnet/AspNetCore.Docs#11807]
I need a pure HTML5 front end (no Razor, or other backend dependency) for File Upload solution. ASP.Net Core used only for the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't have the resources to write such a sample that not directly related to ASP.NET Core.
