### ISSUE TITLE
Tick "XML Documentation File" checkbox in project properties->Build to generate XML documentation

### ISSUE THREAD

**Issue by hf-kklein** [aspnet/AspNetCore.Docs#11808]
The command `var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";` fails with a FileNotFoundException if no XML documentation file created during the build. It's nearly trivial but half a sentence would be fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Related to #11809
Would you be interested in PRing this too?
