### ISSUE TITLE
Hot code paths link broken

### ISSUE THREAD

**Issue by larry-hengen** [aspnet/AspNetCore.Docs#11812]
hot code paths is linked several times, but doesn't go anywhere.  Would be useful to have a definition of what the author considers a hot code path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in the intro, and the links work
In this document, a hot code path is defined as a code path that is frequently called and where much of the execution time occurs. Hot code paths typically limit app scale-out and performance.
