### ISSUE TITLE
Update Microsoft Account external login setup

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#11828]
See internal mail by Kevin.Yam with subject "[Action required] Important update regarding Application Registration Portal (apps.dev.microsoft.com)" 
Sent: Wednesday, April 3, 2019 6:15 PM
For details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by kjyam98** [comment]
@Rick-Anderson please update the app registrations steps since we will be replacing apps.dev.microsoft.com soon.
