### ISSUE TITLE
Incomplete example with no namespaces needed

### ISSUE THREAD

**Issue by davidekarasek** [aspnet/AspNetCore.Docs#11822]
This is not followable due to confusion in namespaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
21.5K PV, 16 ratings, 50% CSAT

What namespace confusion?

**Comment by Rick-Anderson** [comment]
@davidekarasek  have you looked at the download file?

**Comment by guardrex** [comment]
This has been addressed on the topic+sample overhaul. I've marked this issue on the tracking issue: https://github.com/aspnet/AspNetCore.Docs/issues/10214 ... closing it here.
