### ISSUE TITLE
Need more detail on using TypeConverters in ASP.NET Core

### ISSUE THREAD

**Issue by davisnw** [aspnet/AspNetCore.Docs#11820]
No examples are given on how to create a TypeConverter, and it is unclear how to write the TypeConverter to give an informative message when binding fails.  E,g., if I had a custom "Date" type, and the provided value is "Bob", how should that be communicated from the TypeConverter implementation?  In the custom modelbinder, you have access to ModelState, but not so in the TypeConverter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by TjeuKayim** [comment]
Can dependency injection be used to register a `TypeConverter`, instead of the static `TypeDescriptor.AddAttributes()`?

https://stackoverflow.com/q/43378709

**Comment by Rick-Anderson** [comment]
Moved to #16319

**Comment by Rick-Anderson** [comment]
Moved to  Master issue #16319
