### ISSUE TITLE
[Preview 5] Prerendering with reconnect

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#11836]
We should add docs for the prerendering + reconnect feature.
* Describe how it works.
* Define the limitations.
* Talk about scale-out.

**Comment by guardrex** [comment]
"Component" ... Is this similar to and possibly can be worked with https://github.com/aspnet/AspNetCore.Docs/issues/11366?

**Comment by javiercn** [comment]
No. This is server-side

**Comment by guardrex** [comment]
Thanks ... but Razor Components? (without context, e.g., an engineering issue or comment, idk what it is). I'll fix the labels ... we have a workflow going over here:

* No "area-mvc" label. We don't use that label anyway, but we also don't consider RC/Blazor to be MVC for tracking.
* RC/Blazor issues to be triaged by DR and to receive the "DR" label, except bug fixes that I work immediately.
* No "3.0" label for RC/Blazor topics. They're being filtered differently ...
* We're using the "Razor Components" label instead.
* No "ASP.NET Core 3.0" project for these. They will be tracked by ...
* ["Razor Components" project](https://github.com/aspnet/AspNetCore.Docs/projects/35)
* Milestone is ok I suppose, but "3.0.0-preview4" hasn't been approved by the docs management. They'll advise if they have a problem with it.

No worries tho for you ... I'll adjust the labels as the issues come in.

cc: @ajaybhargavb ... I updated the labels on the issue that you opened.

**Comment by mkArtakMSFT** [comment]
@guardrex `area-mvc` label is used to identify issues owned by my team. Please leave it as my team owns multiple areas and that way I can query them all.

**Comment by guardrex** [comment]
@mkArtakMSFT I see. I was given different direction by my superiors over here. I'll leave them be ... let me know if any of the others (ours) cause a problem.

**Comment by guardrex** [comment]
@javiercn Physical file location changes will be occurring soon. Best to hold off for a sec if you were planning to do this one on Monday/Tuesday (4/15-4/16) until the dust settles. 🚧👷

I'll ping back here when everything is 👍.

**Comment by mkArtakMSFT** [comment]
@guardrex is there still a blocker here?

**Comment by guardrex** [comment]
No blockers WRT topic locations ... all topics have moved to their good upcoming Pre4 locations.

However, there are a *TON* of Pre4 updates going on a branch now across the doc set. Is the plan to work this issue before the Pre4 release?

**Comment by mkArtakMSFT** [comment]
I've moved it to `preview5` milestone already, but wanted to make sure that this is not going stale. If not right now, we should make sure this will be done early during `preview5`

**Comment by guardrex** [comment]
Perfect ... I have a *half-a-gazillion* updates for Pre4. Touching almost anything before merging the upcoming docs PR will almost certainly result in a :boom: .... even if only on my branch. :smile: lol ... no worries. If it happens, I'll just deal with it. :+1:

**Comment by guardrex** [comment]
@danroth27 Has this issue been mostly or completely resolved by the Pre4 blog post additions to the *Hosting Models* topic? If so, it's closed by the work on https://github.com/aspnet/AspNetCore.Docs/pull/12048.

There might be more to say tho ...

* Describe how it works. :+1: *Seems ok.*
* Define the limitations. :question: *If the limitation is state still exists ... it's the only one we describe.*
* Talk about scale-out. :-1: **Not really AFAICT.**

**Comment by danroth27** [comment]
I'm not sure - let's wait till @javiercn is back and see what he thinks.

**Comment by guardrex** [comment]
@danroth27 Not much action for ~6 weeks on this one. I think this was covered with the updates on #12048.

We could close this and continue to wait-'n-see if devs hit prerendering and reconnect problems (i.e., due to a lack of coverage).

**Comment by javiercn** [comment]
I do have the content for this, I just need to complete some discussions on how to frame it. We haven't seen people run into issues in this area, but I want us to have content in this. It simply needs to have broader scope and we are going through discussions about this.
