### ISSUE TITLE
[Preview 4] Razor components renaming

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11837]
**For Preview 4 RTM**

https://github.com/aspnet/AspNetCore/issues/8931

Because sample and code example updates are concurrent with the naming changes, this should be worked the day that Preview 4 releases.

Details:

- [x] Rename the Razor Components template in .NET Core 3.0 back to “Blazor (server-side)”.
- [x] Rename the Blazor template to "Blazor (client-side)" for full clarity.
- [x] Rename `services.AddRazorComponents()` -> `services.AddServerSideBlazor()`
- [x] Rename `routes.MapComponentHub<TComponent>()` -> `routes.MapBlazorHub<TComponent>()`
- [x] Rename `components.server.js` back to `blazor.server.js` and `components.webassembly.js` back to `blazor.webassembly.js`.
- [x] Blazor on WebAssembly will no longer be experimental: Remove INCLUDE.
- [x] Get Started: One topic
  * Install SDK + templates
  * Tooling tabs: VS2019+VSIX; VSC+C# extension (**https://github.com/aspnet/AspNetCore.Docs/issues/11971#issuecomment-483620553**); check for other VSC
  * Template choice for desired experience
- [x] All *.razor* and all components in *Pages*.
- [x] Host & Deploy: Place the four topics under one node/folder.
- [x] Tutorial: Already a single topic: Clean it up for *.razor*, *Pages* folder, and tooling instructions.
- [ ] Common sample to P4 bits. **REGRESSION REPAIRS**
- [x] Remove the Razor Components (Blazor server-side) common sample.
- [x] "Razor components" app model language changed to "Blazor."
- [x] Recombine *Overviews* into one topic.
- [x] TOC work
- [x] Components in pages+views are interactive.
- [x] Blazor client-side get prerendering support for Preview 5. Update the language to reflect the push back to Pre5 for this scenario.
- [x] Update topic dates.
- [x] Mirror additional updates from the blog post in the docs.
- [x] *_Imports.razor*
- [ ] *Spit-'n-polish* ... it's the **spit** that really makes the docs shine. 🌞

Additional Info:

> We will still refer to the component model as Razor components (i.e. a .razor file will still be a Razor component), but when talking about the application model we are finding it very cumbersome to have different names.

> We're planning to keep the .razor extension for components. Components are based on Razor syntax, but components are handled differently by the Razor compiler, so they need a different file extension.

> What about the blazor hosted template? Answer: It stays as is. So there will be three Blazor templates: standalone client-side, ASP.NET Core hosted, and server-side

Convo on this issue resolves to ...

## Physical folder layout

* aspnetcore
  * blazor

`client-side` > `spa` > `blazor` 👋 *Bye!* 👋

## TOC

* Web apps
  * Blazor (after MVC)
  * Client-side development (after Blazor)

Client-side Development > SPA > Blazor 👋 *Bye!* 👋

**Comment by guardrex** [comment]
@tdykstra and I discussed this over a dozen virtual :beer: and came up with ...

## Physical folder layout

Either ...

* aspnetcore
  * client-side
    * blazor
      * client-side
      * server-side

... or (root-based) ...

* aspnetcore
  * blazor
    * client-side
    * server-side

No consensus reached at this point.

## TOC

* Client-side development
  * Blazor
    * Client-side hosting
    * Server-side hosting

## Notes

Consensus thus far is that it's best to keep client-side and server-side in the same folder/under the same TOC entry as opposed to splitting Blazor client-side to **client-side** > **spa** and Blazor server-side to **client-side**. Current spit-ball'in yields links like :+1: ...

* `aspnet/core/client-side/blazor/client-side/XXXXXXXX`
* `aspnet/core/client-side/blazor/server-side/XXXXXXXX`

... which seems better than :-1: ...

* `aspnet/core/client-side/spa/blazor-client-side/XXXXXXXX`
* `aspnet/core/client-side/blazor-server-side/XXXXXXXX` (*ugh ... plz NO!*)

cc: @danroth27, @scottaddie, @Rick-Anderson, and @wadepickett

**Comment by danroth27** [comment]
I don't think we want to have a top level fork between server-side and client-side Blazor. Blazor is one app model with multiple hosting models. Most of what you do with Blazor is *the same* regardless of whether you host client-side or server-side: you write components, add routes, inject services, etc. The only place where client-side vs server-side should come up is when your talking about different hosting. We want one doc TOC for Blazor, not two.

**Comment by danroth27** [comment]
I would rename the razor-components folder to blazor. The razor components tutorial should become the new Get Started with Blazor tutorial, which shows getting started with the server side model since that's what's shipping first. I think we will then need to add some content to this tutorial that highlights where you need to do something different if you want to run on WebAssembly instead.

**Comment by guardrex** [comment]
Similar then to what we originally had on blazor.net.

## Physical folder layout

Either ...

* aspnetcore
  * client-side
    * blazor

... or (root-based) ...

* aspnetcore
  * blazor

@tdykstra's call on that. My recommendation is that with a *client-side* folder it seems logical to it to go there, not be root based.

## TOC

* Client-side development
  * Blazor

**Comment by guardrex** [comment]
> highlights where you need to do something different if you want to run on WebAssembly instead

Easy if/when ...

* All components go to `.razor` extension.
* Layout of folders (location of components) is similar across hosting model.

Otherwise, it gets dicey ... e.g. https://github.com/aspnet/AspNetCore.Docs/issues/11953 ... but not necessarily super bad. Just need to be careful.

**Comment by tdykstra** [comment]
> My recommendation is that with a client-side folder it seems logical to it to go there, not be root based.

Sounds good, let's go with that.

**Comment by danroth27** [comment]
Hold on :smile:

Note that we already have an [aspnetcore/razor-components](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/razor-components) folder with all of the relevant Blazor content. It seems logical to rename that folder to blazor. There is also a blazor folder under client-side/spa. Anything important from that folder should be somehow merged into the top level blazor folder.

**Comment by guardrex** [comment]
Yes ... but it will be a rename and move. "razor-components" is currently at the root of the repo.

**Comment by guardrex** [comment]
btw - We aren't messing with redirects during preview. (*I knew this was going to happen*, so I said to the team, "Let's **not** bother with that until RTM.")

**Comment by tdykstra** [comment]
It could go either way -- we have MVC and Razor Pages at top level in the folder structure but under Web apps in the ToC, so Blazor could go top level in the folder structure and under client side in the ToC

**Comment by guardrex** [comment]
Not a fan ... but not my call. I just need marching orders. 🖖

**Comment by guardrex** [comment]
@tdykstra Per offline chat with @danroth27 ... latest i-dears:

**TOC**

Place the Blazor node directly under Web Apps (not under Client-side Development). Client-side Development > SPA > Blazor is going 👋 adios 👋. Place the Client-side Development node directly under Web Apps (i.e., it won't be on the root of the TOC).

**Physical**

Leave the `blazor` folder under the root (as planned; just renaming *razor-components* to *blazor*). Leave the `client-side` folder under root (as exists today).

If you and DR proceed with the TOC updates, let me know if you want me to take care of both. I'll get the Blazor stuff; do you want me to also take care of the Client-side update at the same time if that turns out to be the direction?

Next, I'm going to update the opening post of this issue with the latest. It will include the other details on the topic work for Blazor P4.

**Comment by tdykstra** [comment]
> * Blazor node directly under Web Apps 
> * Client-side Development node directly under Web Apps
> * Leave the blazor folder under the root
> * Leave the client-side folder under root

These all make sense to me, as does including them in your PR. Web apps node will have a long list, we'll have to give some thought to the right order.

**Comment by guardrex** [comment]
@tdykstra When you determine the order, I recommending updating the OP on this issue. I intend to work from the OP when the time comes, so I've been keeping it updated with latest guidance.

**Comment by tdykstra** [comment]
OP?

**Comment by guardrex** [comment]
original post ...... aka first comment

Where did I get that from? ... AOL??!! 🙈

**Comment by tdykstra** [comment]
Ok I added placement suggestions in the main comment box.
