### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by screig** [aspnet/AspNetCore.Docs#11833]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)	WebApplication1	

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-gb/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @screig ...

Enable Visual Studio to use preview SDKs (and you'll need the latest .NET Core 3.0 Preview 3 installed on the machine):
1. Open **Tools** > **Options** in the menu bar.
1. Open the **Projects and Solutions** node. Open the **.NET Core** tab.
1. Check the box for **Use previews of the .NET Core SDK**. Select **OK**.

I put a PR in yesterday to update the guidance: https://github.com/aspnet/AspNetCore.Docs/pull/11818
