### ISSUE TITLE
Limit compression based on the message size

### ISSUE THREAD

**Issue by francisminu** [aspnet/AspNetCore.Docs#11846]
Hi,
It would be really helpful if there could be an option to add the size feature into the compressor.
In other words, lets say if the message size if 8bytes, no compression.
Something similar to what happens in this library:
https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression

Would be really appreciated if you could look into this being added as an option for the GzipCompressionProviderOptions object.

Thanks,
Minu Francis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi ... did the form open two of these?

Open product feedback over at https://github.com/aspnet/AspNetCore/issues.

**Comment by francisminu** [comment]
Yes, it did... I will open a new one.
