### ISSUE TITLE
Update doc to show new docker image names

### ISSUE THREAD

**Issue by antonioortizpola** [aspnet/AspNetCore.Docs#11840]
In the docker part, it says to use

```
microsoft/dotnet:2.2-aspnetcore-runtime
microsoft/dotnet:2.2-sdk
```

However, searching in docker hub, this images are no longer the supported, now it gets redirected to the new repo where the images names has changed to

`mcr.microsoft.com/dotnet/core/sdk:2.2`

and

```
mcr.microsoft.com/dotnet/core/runtime:2.2
mcr.microsoft.com/dotnet/core/aspnet:2.2

```

Also, what are the implications? it will load the same image in with both names (microsoft or mcr.microsoft.com/dotnet)?

Also, now you need the aspnet image if you are using aspnet core mvc, this was not necessary with the previous repo, could the documentation reflect this new change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
From https://hub.docker.com/_/microsoft-dotnet-core-aspnet/  and https://hub.docker.com/_/microsoft-dotnet-core-sdk/ it looks like it should be:

`mcr.microsoft.com/dotnet/core/sdk:2.2` and 
`mcr.microsoft.com/dotnet/core/aspnet:2.2`

**Comment by Rick-Anderson** [comment]
@antonioortizpola 
I don't see `mcr.microsoft.com/dotnet/core/runtime:2.2` so I used `mcr.microsoft.com/dotnet/core/aspnet:2.2`. See #12047

> Also, now you need the aspnet image if you are using aspnet core mvc, this was not necessary with the previous repo, could the documentation reflect this new change?

Are you saying you need both if you're using ASP.NET Core?

**Comment by antonioortizpola** [comment]
@Rick-Anderson that is exactly what I like to be clear in the docs.

There are more docker images in the [net core registry](https://hub.docker.com/_/microsoft-dotnet-core).

![image](https://user-images.githubusercontent.com/11655127/56523583-4b129500-650d-11e9-9f00-a2af69786e58.png)

From what I understand, you should be fine using `aspnet`, since it will include the runtime and all the aspnet core dependencies, where the `runtime` will only include the core libraries (nothing about aspnet), but I think the great majority will just change to aspnet, since almost all projects use some feature of asptnet.

Remember that `net core` is just the runtime to run C# code, and `asp net core` is a set of libraries on top of `net core` to help create web applications

**Comment by JohnnyFun** [comment]
Changing to in-process causes web.config to be changed locally to include some environment variables. If those get deployed to production they can change things...

I suggest adding a comment about that here and suggesting a web.config transform perhaps to remove those environment vars for Release builds: https://github.com/aspnet/websdk/issues/564
