### ISSUE TITLE
Deriving from ControllerBase vs Annotation

### ISSUE THREAD

**Issue by williamTri** [aspnet/AspNetCore.Docs#11849]
This article leaves us in more darkness about the pros and cons associated with the use of one or the other method than before we read it. Thanks.
Now, the questions are: Why there are two methods; what are their advantages and disadvantages; which method will be supported longer in the future, etc, etc, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
32.4K PV, 34 ratings, 62% CSAT.
@williamTri  thanks for bringing this to our attention, I agree with you.

Article needs to be rewritten and replace all the repository stuff with the `ValuesController` generated by the templates, or better yet, a subset of it.

The imperative **Derive class from ControllerBase** is unclear - why are you doing that. It should be something like, Historically, web API controllers derived from  `ControllerBase` - 
Actually the templates still do.

Then in the sample they decorate with `[ApiController]` but keep `ControllerBase`
It never really tells what that attribute does.

Article needs a scrub.
