### ISSUE TITLE
Small wording mistake

### ISSUE THREAD

**Issue by emilborowiec** [aspnet/AspNetCore.Docs#11864]
In the paragraph starting with 'The preceding code looks a lot like a Razor view file. ' I think it was meant to be HTML and not 'Razor view' file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@emilborowiec  actually it's correct. It looks like a Razor view file used by MVC controllers. That sentence was written from the perspective of someone coming from MVC with controllers and views, not someone new to ASP.NET Core.  So it's ambiguous. I'll clean it up.

**Comment by emilborowiec** [comment]
Right, makes sense. I'm coming back to asp.net after years in java backend
+ javascript frontend, hence the confusion.
Take care!

pt., 5 kwi 2019, 20:57 użytkownik Rick Anderson <notifications@github.com>
napisał:
