### ISSUE TITLE
IISExpress vs IIS

### ISSUE THREAD

**Issue by dyardyGIT** [aspnet/AspNetCore.Docs#11867]
During development is there any advantages to use IIS vs IISExpress? (I have been using IIS for years however as I could just point IIS as my web directory).

It seems that this is now possible again with .net core.  This is correct?  

I was able to follow the instructions in the documentation.  However VS.NET 2019 has some **new** screen shots and additional options i..e Hosting Model, App URL

Can you update docs to include screen shots and explanations for the new fields?

**Comment by guardrex** [comment]
Hello @dyardyGIT 

> advantages

There are advantages that pertain to capabilities. For example, bindings. IIS Express works with localhost ... so if you want to test other bindings, you have to jump through some hoops (not recommended I think by the IIS cats! lol). Whereas with IIS, you can configure bindings normally. I think protocols are another thing ... IIS Express works great with HTTP/HTTPS ... but I think that's it. If you need to work with other protocols, then you probably need to go to IIS. Modules can be a sticking point with IIS Express ... I don't think that they're all supported. Then, there's just the IIS Manager UI ... point and click goodness is fast, and IIS Express doesn't have a UI like that. Search over in the the IIS docs. They have some docs that explain the differences between IIS and Express and the limitations of IIS Express.

> is now possible again with .net core

Correct ... with the [dev-time support for IIS in VS](https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/development-time-iis-support), it's easy to set up and use IIS. 

> update docs to include screen shots and explanations for the new fields

We can't maintain screenshots. There's too much churn in the UI of VS to do it. We tried! lol ... We were burned many times trying to do that, so we had to stop.

We do have quite a bit on VS if you look down in the Host and Deploy section of the TOC in the docs.

WRT "new fields" ... VS2019 just landed, so as I sweep through the deployment topics, yes, I'll make a point to see what I can do regarding the fields. We don't need to keep this open for that. All of these docs are going to get a big sweep and set of updates for 3.0.

I'll close as answered, but we can re-open if you want to discuss further.
