### ISSUE TITLE
Update dev-time IIS support in VS topic

### ISSUE THREAD

**Issue by dyardyGIT** [aspnet/AspNetCore.Docs#11868]
I found that the instructions did not work when url was http (vs.net 2019 said that it was unable to start the application pool, even if i manually started the application pool, vs.net 2019 when trying to debug F5 it would stop it..then vs.net would just hang.

After I made it https it all worked.  Is this by design?

**Comment by guardrex** [comment]
I take it that you're referring to dev-time support for IIS in VS? https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/development-time-iis-support

btw --- Use the feedback feature at the bottom of the topic when opening an issue. It will tag the issue with metadata that helps our tracking.

<img width="423" alt="Capture" src="https://user-images.githubusercontent.com/1622880/55657367-96177300-57bf-11e9-8a14-cc613f8b95c4.PNG">

**Comment by guardrex** [comment]
oh ... and a clarification on the screenshot situation. We use them for a number of tutorials. However even in tutorials, they're difficult to maintain, so we try to back off using them when possible.

If you are referring to the dev-time support topic, your timing with this issue is great. Like you, I just installed VS2019 here, and I need to walk the issue. I'll try to use text to explain the screen selections. I'll update for some of the differences that you may have seen between the VS2017-era text and the VS2019 UI.

**Comment by guardrex** [comment]
@dyardyGIT ok ... I have the scoop on this now. Yes, it will work with HTTP, but there's a catch: It can't work with both HTTP and HTTPS.

In the following screenshots, you can see that my app is set up to be reached at `/testFDD` on `localhost`. It's one of my framework-dependent deployment test apps.

App Pool:

<img width="223" alt="apppool" src="https://user-images.githubusercontent.com/1622880/55669871-504fbe80-5842-11e9-90d2-22740fd66295.PNG">

# HTTP

IIS website binding:

<img width="389" alt="binding_80" src="https://user-images.githubusercontent.com/1622880/55669877-5cd41700-5842-11e9-9228-9d26965d8595.PNG">

<img width="479" alt="binding_80_2" src="https://user-images.githubusercontent.com/1622880/55669981-da4c5700-5843-11e9-8499-25c3a82ba077.PNG">

VS2019 profile:

<img width="524" alt="profile_80" src="https://user-images.githubusercontent.com/1622880/55669880-62c9f800-5842-11e9-9842-e12fd1356b9c.PNG">

# HTTPS

IIS website binding:

<img width="390" alt="binding_443" src="https://user-images.githubusercontent.com/1622880/55669890-707f7d80-5842-11e9-8fad-52917c9721cc.PNG">

<img width="478" alt="binding_443_2" src="https://user-images.githubusercontent.com/1622880/55669983-dfa9a180-5843-11e9-9e35-4923809fac51.PNG">

VS2019 profile:

<img width="515" alt="profile_443" src="https://user-images.githubusercontent.com/1622880/55669899-79704f00-5842-11e9-8c0e-60045cc9e65a.PNG">

# Hosting Model

You can leave **Hosting Model** set to Default. The behavior is that if you have ...

```xml
<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
```

... in the project file, it will use in-process as the default. If you don't have the property in 2.2, the default is out-of-process. If you don't have the property and you want in-process in 2.2, then you should change the profile's **Hosting Model** to `In Process`.

As for 3.0 coming out later, the default will switch over to in-process. At that point, it wouldn't matter if one had the property for in-process in the project file or not.

# Caveat for HTTP/HTTPS

Like I mentioned, either set the whole thing up HTTP or set it up HTTPS. You just want **one binding** for the website in IIS.

I see several things that I'd like to update in the topic, so I'm going to work on it this afternoon (Saturday). I'll ping u on the PR.
