### ISSUE TITLE
Fix ToC handling of monikerRange metadata

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#11863]
The ToC is confusing at times because you can accidentally have version switched to 1.0 or 1.1 without noticing it, and the ToC doesn’t even display many of the nodes then, even if you know what to look for or filter for. Two proposed solutions:
* Keep 1.0/1.1/2.0 from ever being the default version.
* Disable/gray-out the ToC nodes for non-selected versions instead of omitting them altogether.

**Comment by guardrex** [comment]
I could see readers getting a bit upset with the first one when working in a supported version and looking at doc after doc.

The 2nd idea is **_solid gold_** imo.

**Comment by tdykstra** [comment]
The OPS team is aware of this issue -- it's in [the ToC roadmap doc](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft-my.sharepoint.com%2F%3Aw%3A%2Fp%2Fshgoldb%2FEYIo9XbKjINPrno3elooJFQBrz361PrBRwyl7rZnd843NA%3Fe%3Dx66fve&data=02%7C01%7Ctdykstra%40microsoft.com%7C4d2d688377a84a866f7d08d6978d30cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636863030007280143&sdata=5t4YdHPrr96yyTVmNgDA4LYMYA66s5SbF5yrq0SVNf4%3D&reserved=0), but it's not one of the issues currently scheduled to work on in the next 3 years.

I'm going to close this as communicated to OPS team, so we've done as much as we can and it doesn't make sense to hold it open for (possibly) years.
