### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by miroslavp** [aspnet/AspNetCore.Docs#11877]
# Before you open an issue

If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page.

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description
I wonder how this example of yours works at all. You declare a static class and put a constructor in it (class name and constructor name does not match by the way). Furthermore, if you can't have a constructor in a static class, how will you inject the IJSRuntime object.

        using Microsoft.AspNetCore.Components;
        using Microsoft.JSInterop;
        using System.Threading.Tasks;

        namespace MyLib
        {
               public static class MyLibElementRefExtensions
               {
                      private readonly IJSRuntime _jsRuntime;
                      public MyJsInterop(IJSRuntime jsRuntime)
                      {
                             _jsRuntime = jsRuntime;
                      }

                     public static Task Focus(this ElementRef elementRef)
                     {
                            return _jsRuntime.InvokeAsync<object>(
                                    "myLib.focusElement", elementRef);
                     }
               }
         }
# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by guardrex** [comment]
Hello @miroslavp ... The updates to the topic for Preview 3 are covered by https://github.com/aspnet/AspNetCore.Docs/pull/11675, which are awaiting review by engineering. We'll merge the updates asap.
