### ISSUE TITLE
dotnet watch run doesn't work with relative paths with the --project or -p option

### ISSUE THREAD

**Issue by abjbhat** [aspnet/AspNetCore.Docs#11873]
Unless I'm in the actual directory itself, dotnet watch run --profile relative/path/to/project.csproj doesn't work. The error message that no msbuild project was found keeps getting displayed. You have to navigate to the folder under which the csproj file is located. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3163f-1903-f2c7-8909-d34f917944bf
* Version Independent ID: 55aae418-9d32-5b2b-1df7-5e4e76313ec4
* Content: [Develop ASP.NET Core apps using a file watcher](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/dotnet-watch.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's how it works. Feel free to open a product bug if you think it should support relative paths.

**Comment by serpent5** [comment]
This works if you attach the `--project` switch to `watch` rather than to `run`:

    dotnet watch --project relative/path/to/project.csproj run

**Comment by Rick-Anderson** [comment]
@serpent5 that sounds like great info to add to the article. Are you interested in PRing it?

**Comment by serpent5** [comment]
Yeah, of course, I'll do that. :)
