### ISSUE TITLE
no primary key

### ISSUE THREAD

**Issue by minde123222** [aspnet/AspNetCore.Docs#11876]
hello i just finished this part but at appsettings at the ConnectionStrings i used not local db but my own witch i created at sql management studio and every thing mostly works except creating new movie they show that
 SqlException: Cannot insert the value NULL into column 'ID', table 'statybos.dbo.movie'; column does not allow nulls. INSERT fails. 
and
DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
CreateModel.OnPostAsync() in Create.cshtml.cs
-
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _context.Klientas.Add(Klientas);
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }
    }
}

are where is an easy way how to fix it if i dont want to use local server ?

---
#### Išsami dokumento informacija

⚠ *Neredaguokite šio skyriaus. To reikia docs.microsoft.com ➟ „GitHub“ problemoms sieti.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/lt-lt/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a great error message. Error has nothing to do with SQL Server. Test this with localDB and you'll get the same error.

**Comment by minde123222** [comment]
no then i tested with my local db with in my computer is (localdb)\Mindaugas every thing was ok but i wanted connect to sql that i could create movie examples more easier and this problem started

**Comment by minde123222** [comment]
now i created this code
 <div class="form-group">
                <input asp-for="movie.ID" type="hidden" class="text-danger" />
            </div>
and error message has disappear but then i press save nothing happens it does not save the new movie

**Comment by minde123222** [comment]
the code  
<div class="form-group">
                <input asp-for="Klientas.ID" type="hidden" class="text-danger" />
            </div>

**Comment by minde123222** [comment]
<div class="form-group">
                <input asp-for="Klientas.ID" type="hidden" class="text-danger" />
            </div>

**Comment by minde123222** [comment]
<input asp-for="Klientas.ID" type="hidden" class="text-danger" />
