### ISSUE TITLE
Server-side hosting model Startup class

### ISSUE THREAD

**Issue by MartiusBr** [aspnet/AspNetCore.Docs#11871]
Please update the startup class   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aab7db7-b198-86c3-75bb-3b2c0cbe302a
* Version Independent ID: 7c1e5736-37b7-4135-944a-d4b517db8207
* Content: [Razor Components hosting models](https://docs.microsoft.com/en-us/aspnet/core/razor-components/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-components/hosting-models.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorcomponents**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The PR is in ... Waiting on engineering review.
