### ISSUE TITLE
VS2019 Core 2.2 Authentication with /sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo

### ISSUE THREAD

**Issue by SeanGahan** [aspnet/AspNetCore.Docs#11895]
Using VS2019 Core2.2 I was able to compile and run this example: https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo 
The issue I have is with the authentication; You can register a new user and it is stored in [dbo].[AspNetUsers], but after you complete the login process, you’re not authenticated.  In the Account Controller - > Login, the _signInManager.PasswordSignInAsync returns true and you are redirected to the Home/Index page, but not authenticated.  After spending some time on this, I then tried the sln using VS2017 and everything worked as expected.  Here is some output from the Immediate Window:
VS2019
?User.Identity
{System.Security.Claims.ClaimsIdentity}
    Actor: null
    AuthenticationType: null
    BootstrapContext: null
    Claims: Count = 0
    CustomSerializationData: null
    IsAuthenticated: false
    Label: null
    Name: null
    NameClaimType: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    RoleClaimType: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"	

VS2017
?User.Identity
{System.Security.Claims.ClaimsIdentity}
    Actor: null
    AuthenticationType: "Identity.Application"
    BootstrapContext: null
    Claims: Count = 4
    CustomSerializationData: null
    IsAuthenticated: true
    Label: null
    Name: "sean@email.com"
    NameClaimType: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    RoleClaimType: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

Output from VS2019
1) Start website
2) Register - redirected to home page
3) Login - redirected to home page

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\sean\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo
Now listening on: http://localhost:55928
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.HomeController.Index (IdentityDemo) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.HomeController.Index (IdentityDemo) in 5264.2645ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6020.7326ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/css/site.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/images/banner1.svg
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/images/banner2.svg
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/images/banner2.svg'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\images\banner2.svg'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/images/banner1.svg'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\images\banner1.svg'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/site.css'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\css\site.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery/dist/jquery.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 51.9471ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 86.6746ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/css/bootstrap.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 185.3848ms 200 image/svg+xml
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 162.526ms 200 image/svg+xml
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 187.1716ms 200 text/css
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/js/site.js'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\js\site.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 39.5018ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/images/banner3.svg
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 150.9153ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/images/banner4.svg
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/images/banner3.svg'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\images\banner3.svg'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/images/banner4.svg'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\images\banner4.svg'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 180.6044ms 200 image/svg+xml
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 185.203ms 200 image/svg+xml
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 48.9978ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/favicon.ico
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: 'C:\Users\sean\Desktop\ASPNETCore-IdentityDemoComplete\IdentityDemo\wwwroot\favicon.ico'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 15.7869ms 200 image/x-icon
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/Account/Register
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.AccountController.Register (IdentityDemo) with arguments () - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Account/Register.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.AccountController.Register (IdentityDemo) in 1090.6084ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1154.0231ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/css/bootstrap.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery/dist/jquery.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation/dist/jquery.validate.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 16.2919ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 39.436ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 66.7713ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 70.1904ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 73.5663ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 36.0933ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation/dist/jquery.validate.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 9.3487ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7.5655ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:55928/Account/Register application/x-www-form-urlencoded 251
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.AccountController.Register (IdentityDemo) with arguments (IdentityDemo.Models.AccountViewModels.RegisterViewModel, ) - ModelState is Valid
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.3-rtm-10026 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (99ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
      FROM [AspNetUsers] AS [u]
      WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[@__normalizedEmail_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
      FROM [AspNetUsers] AS [u]
      WHERE [u].[NormalizedEmail] = @__normalizedEmail_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[@p0='?' (Size = 450), @p1='?', @p2='?' (Size = 4000), @p3='?' (Size = 256), @p4='?', @p5='?', @p6='?', @p7='?' (Size = 256), @p8='?' (Size = 256), @p9='?' (Size = 4000), @p10='?' (Size = 4000), @p11='?', @p12='?' (Size = 4000), @p13='?', @p14='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [AspNetUsers] ([Id], [AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [LockoutEnabled], [LockoutEnd], [NormalizedEmail], [NormalizedUserName], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [TwoFactorEnabled], [UserName])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
info: IdentityDemo.Controllers.AccountController[0]
      User created a new account with password.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[@__user_Id_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
      SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
      FROM [AspNetUserClaims] AS [uc]
      WHERE [uc].[UserId] = @__user_Id_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[@__userId_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
      SELECT [role].[Name]
      FROM [AspNetUserRoles] AS [userRole]
      INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
      WHERE [userRole].[UserId] = @__userId_0
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: Identity.Application signed in.
info: IdentityDemo.Controllers.AccountController[0]
      User created a new account with password.
info: Microsoft.AspNetCore.Mvc.RedirectToActionResult[1]
      Executing RedirectResult, redirecting to /.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.AccountController.Register (IdentityDemo) in 1256.6846ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1294.3358ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.HomeController.Index (IdentityDemo) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.HomeController.Index (IdentityDemo) in 16.9698ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 32.6735ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/css/bootstrap.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 14.4269ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery/dist/jquery.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 45.6779ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 42.7083ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 12.294ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/Account/Login
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.AccountController.Login (IdentityDemo) with arguments () - ModelState is Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Account/Login.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.AccountController.Login (IdentityDemo) in 629.9845ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 659.2463ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/css/bootstrap.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation/dist/jquery.validate.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery/dist/jquery.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 13.8122ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 27.7554ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 60.923ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 59.1458ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 70.4409ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 11.4789ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation/dist/jquery.validate.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7.3856ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7.2528ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:55928/Account/Login application/x-www-form-urlencoded 240
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.AccountController.Login (IdentityDemo) with arguments (IdentityDemo.Models.AccountViewModels.LoginViewModel, ) - ModelState is Valid
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.3-rtm-10026 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
      FROM [AspNetUsers] AS [u]
      WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@__user_Id_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
      SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
      FROM [AspNetUserClaims] AS [uc]
      WHERE [uc].[UserId] = @__user_Id_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@__userId_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
      SELECT [role].[Name]
      FROM [AspNetUserRoles] AS [userRole]
      INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
      WHERE [userRole].[UserId] = @__userId_0
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: Identity.Application signed in.
info: IdentityDemo.Controllers.AccountController[0]
      User logged in.
info: Microsoft.AspNetCore.Mvc.RedirectToActionResult[1]
      Executing RedirectResult, redirecting to /.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.AccountController.Login (IdentityDemo) in 138.2533ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 163.1983ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityDemo.Controllers.HomeController.Index (IdentityDemo) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityDemo.Controllers.HomeController.Index (IdentityDemo) in 19.478ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 37.7278ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/css/bootstrap.css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/jquery/dist/jquery.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 16.5198ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 21.6183ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 53.4864ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55928/lib/bootstrap/dist/js/bootstrap.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 8.5586ms 404

**Comment by Rick-Anderson** [comment]
> but after you complete the login process, you’re not authenticated. I
How did you verify you're not authenticated?

**Comment by SeanGahan** [comment]
Hey Rick, after rebooting my system, all seems to be working with the Identity example.  Sorry to have wasted your time.
