### ISSUE TITLE
Conflict with the docs?

### ISSUE THREAD

**Issue by AndrewRRMoser** [aspnet/AspNetCore.Docs#11896]
https://github.com/aspnet/AspNetCore.Docs/issues/9901

Should this page replace UseKestrel with ConfigureKestrel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AndrewRRMoser ... IIRC that problem with `UseKestrel` was when it was re-added by the dev after `CreateDefaultBuilder` was also called. According engineering if the app doesn't call `CreateDefaultBuilder`, `UseKestrel` is called ... then if additional config is required, call `ConfigureKestrel`.

Here's what they approved ...

https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#how-to-use-kestrel-in-aspnet-core-apps

... and repeated in the migration topic ...

https://docs.microsoft.com/aspnet/core/migration/21-to-22#update-kestrel-configuration

I think we're ok here, so I'll close as answered. Thanks for asking tho ... this is how we find the little 🐞 in the docs. :+1: We can re-open to discuss further if needed.
