### ISSUE TITLE
Unable to get rid rid of querystring in the searchfunctionality even after using it with @page directive

### ISSUE THREAD

**Issue by pratishthap** [aspnet/AspNetCore.Docs#11909]
Hello,
I have been trying it replicate Search on get based on value supplied in the input field.
I have also used as you mentioned @page "{searchstring?}" .But the url still show /..SearchUsers?searchstring=abc

Please suggest what could be done. Also i have used [BindProperty(SupportsGet =true)].But still not getting the desired url

**Comment by guardrex** [comment]
Which topic @pratishthap? ... It's best to use the feedback button at the bottom of the topic to open the issue. It tags the issue with metadata that helps us track the work.

**Comment by pratishthap** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2.If this helps

**Comment by pratishthap** [comment]
I have submitted the feedback via the specified page

**Comment by guardrex** [comment]
Thanks ... no worries, I'll move it over.

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/11910.

**Comment by pratishthap** [comment]
I have been struggling to get rid of querystring but not happening with the @page directive
