### ISSUE TITLE
Introduce BackgroundService class in IApplicationLifetime Interface section

### ISSUE THREAD

**Issue by RickyLin** [aspnet/AspNetCore.Docs#11906]
I wonder if we can introduce `Microsoft.Extensions.Hosting.BackgroundService` class in  IApplicationLifetime interface section? I think readers are good to know `BackgroundService` class can simplify the application lifetime management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#iapplicationlifetime-interface)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RickyLin ... We usually resist that type of general cross-linking unless there's a compelling reason. Otherwise, we'd end up with a large number of cross-links with dubious relationships. If we did something like this, then I think we'd need to know what you mean in detail, probably with sample code,  by ...

> class can simplify the application lifetime management

**Comment by RickyLin** [comment]
Hi @guardrex,
Thanks for your explanation. Now I don't think my request is necessary.
