### ISSUE TITLE
Update 3.0 preview INCLUDE for VS2019 RTM

### ISSUE THREAD

**Issue by chrisw000** [aspnet/AspNetCore.Docs#11925]
Using the final release of VS2019 (not preview as per docs) I get this:

rzc generate exited with code -2147450730 in :

file: C:\Program Files (x86)\dotnet\sdk\3.0.100-preview3-010431\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets
	
line :93	

The error code lead me to an old (semi-unrelated) github issue which mentioned installing x86 onto x64 box - and swapping to x64 sdk fixing...

I had unintentionally installed the x86 .net core preview 3.x - so took that off, installed the x64 SDK, reboot etc... created brand new project - still get the same error:

rzc generate exited with code -2147450730

cannot proceed... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by chrisw000** [comment]
edit to above...  after posting that I double checked and had accidentally re-installed the x86 core preview 3 a second time.... after installing the x64 preview - this now compiles and works.

So.... rzc generate exited with code -2147450730 for me was fixed by uninstalling the x86 SDK and installing the x64 SDK

**Comment by guardrex** [comment]
> not preview as per docs

btw - Thanks for letting me know about that. I'll patch it up.

> rzc generate exited with code -2147450730

See :point_right: https://github.com/aspnet/AspNetCore/issues/8755

Don't close this tho ... It will auto-close when I update the "preview" language in the topic on the PR.

**Comment by guardrex** [comment]
Cool ... glad it had a happy ending.

Leave this open ... it will auto-close shortly.
