### ISSUE TITLE
web.config doesn't override ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by TadeuTorres** [aspnet/AspNetCore.Docs#11928]
This sentence is wrong: "When the ASPNETCORE_ENVIRONMENT environment variable is set with web.config, its value overrides a setting at the system level."
In .net core 2.2 this doesn`t happen. The new value is appended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @TadeuTorres ... It was updated in one spot :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#setting-environment-variables ... but not here. I'll update it now. Thanks for reporting this.

Cross-ref: https://github.com/aspnet/AspNetCore/issues/6140
