### ISSUE TITLE
Environment name "missing" in the Background tasks with hosted services example

### ISSUE THREAD

**Issue by haakoo** [aspnet/AspNetCore.Docs#11935]
I've been setting up a new project in .Net Core and are following the "best practices" of using _IHostedService_ and _Options Pattern_. When I tried to run the example for [Background tasks with hosted services](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-GenericHost) the `appsettings.Development.json` file is not read, `appsettings.Production.json` is read instead. I'm running this from Visual Studio 2019.1 and in _Debug_-mode.

If I put a breakpoint in my `.ConfigureAppConfiguration(..)` I can see that `hostContext.HostingEnvironment.EnvironmentName` is set to `Production` and not `Development` as I would expect.

Testing this using the `dotnet` cli seems to result in the same, only reading the default `appsettings.json` and not the development or production files.

I assume there is an idea about how to do this, unfortunately it's not easy (enough) to find.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by haakoo** [comment]
After reading quite a bit more, I'd figure this should be in the `launchSettings.json` file under `Properties`. Maybe add that to this (and other) examples?

**Comment by guardrex** [comment]
Hello @haakoo ... We can't provide cross-links in that fashion. We'd end up with (at least) a dozen dubious cross-links on every topic to the *Fundamentals* node topics. The environment that the app assumes is a separate matter from the hosted service (as is the options pattern). One has to do exactly what you did: Find out that the environment isn't as expected and then access the [Multiple environments topic: Development section](https://docs.microsoft.com/aspnet/core/fundamentals/environments#development).

> is set to Production and not Development as I would expect.

By-design ... it's a security specification for apps. They want the default to be Production to help prevent an app from leaking sensitive data (e.g., the Developer Exception Page).

> Maybe add that to this (and other) examples?

Also, by-design. The file is specific to certain scenarios: VS and `dotnet run`. With VSC, that approach wouldn't work. IIRC, the file should've been auto-generated for you by VS.

**Comment by guardrex** [comment]
I'm going to close as answered, but we can re-open to discuss further if needed.

**Comment by haakoo** [comment]
Fair enough. So what you're saying is I might have found a VS bug, since VS doesn't create a `Properties\launchSettings.json` file automatically?

**Comment by guardrex** [comment]
@haakoo ... Yes ... it seems strange to me. Let's ask around here if anyone on the docs team knows more about the behavior to just answer the question.

@Rick-Anderson @tdykstra @scottaddie @wadepickett TL;DR ... Do you know: Why wouldn't VS auto-magicially create the *launchSettings.json* file when it doesn't find it in the project. AFAIK, it always does (for me).

If nobody knows for sure, I recommend digging into VS docs on the file. If nothing turns up there, I recommend opening a "Report a problem..." issue from within VS.

**Comment by sebastienricher** [comment]
How does this play with IIS when hosted in process in relation to idle timeout. Does activity by hosted services refresh the idle timeout? I'm seeing IIS go Idle after 20 minutes even though I have a timed process at 15 minutes. Issue in my code?

**Comment by guardrex** [comment]
@haakoo Did you ever find out why VS wasn't creating the *launchSettings.json* file? If that's working ok now (perhaps with an updated VS), then we can close this.

**Comment by haakoo** [comment]
No, don't know why. Doesn't look like VS generates this file now either. Trying VS 16.0.2 and the latest 16.1 preview version.

**Comment by guardrex** [comment]
I see. Sorry to hear that it isn't just working. Most posts around the Net are devs complaining about the file ... they wish they had a way to tell VS to *stop creating it automatically*.

Anyway, it isn't something we can address here in the docs repo. It's a Visual Studio scenario, so they'll need to take a look at why you aren't getting the file. If you submitted a problem report to them using the **Report a Problem** process in VS, then they do have your problem report.

You're already aware of the workaround: Add the folder+file to any project.
