### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ibmorgan** [aspnet/AspNetCore.Docs#11939]
Broken link on the Application Insights -&gt; Metrics blade in Application Insights portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90384677-5801-05d3-3f16-78392fc3ffea
* Version Independent ID: 7ecc5731-9d3c-1f7a-9920-3ce2a37434d1
* Content: [Performance Diagnostics Tools](https://docs.microsoft.com/en-us/aspnet/core/performance/diagnostic-tools?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/diagnostic-tools.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/diagnostic-tools.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ibmorgan ... I'll patch that up right now.
