### ISSUE TITLE
Cookie IsEssential 

### ISSUE THREAD

**Issue by Yavari** [aspnet/AspNetCore.Docs#11938]
I had to add IsEssential = true to the CookieOptions in order to get all browsers to use the cookie.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That applies to ASP.NET Core 2.1 templates
