### ISSUE TITLE
Page is not loading when host ASP.NET Core in a Windows Service

### ISSUE THREAD

**Issue by kudlatiger** [aspnet/AspNetCore.Docs#11936]
Here is the launchSettings.json

 ```
{
 "iisSettings": {
 "windowsAuthentication": false, 
 "anonymousAuthentication": true, 
 "iisExpress": {
  "applicationUrl": "http://localhost:17562",
  "sslPort": 44338
 }
},
"profiles": {
 "IIS Express": {
  "commandName": "IISExpress",
  "launchBrowser": true,
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
  }
 },
 "My.Service": {
  "commandName": "Project",
  "launchBrowser": true,
  "applicationUrl": "https://localhost:5001;http://localhost:5000",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
   }
  }
 }
}
```
Service is running successfully in services.msc but when I browse https://localhost:5001 it is not opening any page

Note:

Page opens successfully when I run the application using Visual Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @kudlatiger ...

* Does it respond at `http://localhost:5000`?
* If you're trying to reach it at the secure endpoint, did you configure the app for HTTPS per the [Configure HTTPS section](https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service#configure-https) of the topic? The engineers recommend that you use the *appsettings.json* approach for HTTPS endpoint+certificate config. There are examples down in [Kestrel: Endpoint configuration](https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#endpoint-configuration).

**Comment by kudlatiger** [comment]
It's working. It was typo error!
