### ISSUE TITLE
Keyvault permissions required

### ISSUE THREAD

**Issue by brobichaud** [aspnet/AspNetCore.Docs#11941]
There is no documentation on what keyvault permissions are needed with ProtectKeysWithAzureKeyVault(). It should note which specific access policy permissions are required for use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @brobichaud ... Yep ... good :eye:. It should say (IIRC) "List" and "Get" permissions. We have some language in another topic (KV config provider) that I should be able to mirror over here. I'll do that now. Thanks for commenting on this.

**Comment by brobichaud** [comment]
Actually I found different. It seems ProtectKeysWithAzureKeyVault() actually needs the "Unwrap Key" permission in the Cryptographic Operations section of Key permissions.

**Comment by guardrex** [comment]
I see. So much for my *assumption*. I'll open an issue to investigate ... I found the Azure docs (and blog posts) somewhat *cryptic* on the point.
