### ISSUE TITLE
Code is not updated

### ISSUE THREAD

**Issue by jeanmarc3** [aspnet/AspNetCore.Docs#11949]
Default ASP.NET CORE projects use Bootstrap, not Angular so why is the example app use Angular?  One more thing to figure out (pass the form fields to the Ajax Upload() function in the controller, similar to app.js?)...
Also the example app is not updated for .NET CORE 2.2 .  Some APIs have newer prototypes (in MultipartRequestHelper)...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jeanmarc3 ... There's a tracking issue to address the topic+sample: https://github.com/aspnet/AspNetCore.Docs/issues/10214

I'll take a look when I get to it. It's coming up for work soon. Don't worry about my closing this. I've cross-linked this issue on the tracking issue.
