### ISSUE TITLE
Really poorly written page

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/AspNetCore.Docs#11953]
This page is quite confusing!
You guys are jumping between the Blazor and RazorComponent projects, which is not obvious in the beginning and it's confusing. Why don't you stick to one project (either Blazor or RazorComponent) and explain that throughout. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9063eb3-fb65-45ed-2e3d-a7cf1354d523
* Version Independent ID: 84390f51-2206-8269-221b-5a20726dab76
* Content: [Build your first Razor Components app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-razor-components-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-razor-components-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/build-your-first-razor-components-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I disagree with the strong sentiment; however, I don't like it either. We don't wish to have a lot of duplicated text, and I personally don't care for INCLUDES all that much when only dealing with two topics (if we split this).

The other thing to consider is that for the upcoming Preview 4 things should improve. `.razor` will be for Blazor, too, AFAIK. I think the folder structure is going to align better between the two hosting models, which will also help. The little mess here should get better for Preview 4.

@danroth27 Will things align better (`.razor` and folder layout of the projects) for Preview 4?

If not, then I agree with @MohammadMQ, and I think we should split this topic.

**Comment by danroth27** [comment]
> @danroth27 Will things align better (.razor and folder layout of the projects) for Preview 4?

This will be fixed for Preview4 - the folder layouts for the client-side and server-side Blazor projects will be pretty close to the same.

**Comment by danroth27** [comment]
We are going to address this as part of #11837

**Comment by MohammadMQ** [comment]
Sorry for the strong language. However I've really been waiting a long time for this kind of technology and finally its here. I would like you guys to put extra effort into showcasing this groundbreaking technology buy writing articles where you don't mix up different approaches to develop interactive web pages.
