### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/AspNetCore.Docs#11956]
You need to supply with much more information about Blazor, especially in regards to CRUD operations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1db781bc-cad1-7146-5c1a-b507a0bbf1c8
* Version Independent ID: ffe6fe92-284c-96c5-de3b-ec253a8470f8
* Content: [Host and deploy Razor Components](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components-blazor/razor-components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/razor-components-blazor/razor-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components-blazor/razor-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the Blazor section of the TOC (under Client-side Development > SPA > Blazor) ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/razor-components-blazor/blazor?view=aspnetcore-3.0

We're going to be making **_BIG_** changes to the Blazor/Razor Components (soon to be just called Blazor client-side and Blazor server-side) for Preview 4. The naming changes will permit us to do a much better job with the TOC. The work is going to be tracked by https://github.com/aspnet/AspNetCore.Docs/issues/11837.
