### ISSUE TITLE
 Generate Exe without adding a RuntimeIdentifier

### ISSUE THREAD

**Issue by AksharX** [aspnet/AspNetCore.Docs#11958]
A third party library our project heavily relies on seems to incorporate a bug where if a RuntimeIdentifier such as win-7x64 is set that library does not behave correctly. Is it possible to have a FDD deployment as a windows service without incorporating this step, or generate an exe a different way. I am able to use dotnet MyProject.dll to run the application however the docs say that it shouldn't be used for production. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
IIRC *Yes!* It can be done. Let me go see if I can track that down. The critical thing is registering the service so that `dotnet XXXX.dll` is called instead of an `.exe`. Stand-by for a bit.

**Comment by guardrex** [comment]
AFAICT from a scan of https://github.com/aspnet/AspNetCore.Docs/issues/10114 ... If you produce an FDD (drop the RID from the project file and publish), you'll only get a .DLL out (you won't see an EXE in the *publish* folder).

Don't use the PowerShell script from the topic to register the service tho ... use the `sc.exe` tool to do the service registration step using *dotnet.exe* and the DLL. You might have to tweak it a bit, but it should go something like ...

```
sc create MyService binPath= "'c:\Program Files\dotnet\dotnet.exe' c:\svc\SampleApp.dll" obj= "{DOMAIN}\ServiceUser" password= "{PASSWORD}"
```

If you want to go the PowerShell way, that's fine, but you'll need to reprogram the script to make it work. The PS script is set up to receive an executable (the FDE). https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service/scripts/2.x/RegisterService.ps1

>  the docs say that it shouldn't be used for production

Does it say that? Where? I didn't see it on a quick scan. It should be ok to use an FDD. However, I can't say that it's officially supported. What the topic shows is **officially supported**. We have engineering approval.

**Comment by AksharX** [comment]
Thank you! This is so helpful. Will give this a try. Also I was confusing the command dotnet run for just dotnet app.dll.

**Comment by guardrex** [comment]
Sure thing. We won't be documenting that approach unless more devs call for it. 

I'm going to close as answered. We can re-open if further discussion is required.

If you end up with notes on how to make it work that differ from what I posted (for example, if the command syntax ends up being a little different), please leave a note back on this issue. If we ever did add a purely FDD approach to the topic, any notes that you provide will come in handy.
