### ISSUE TITLE
Mention Endpoint routing in 2.2-to-3.0 migration doc

### ISSUE THREAD

**Issue by virshu** [aspnet/AspNetCore.Docs#11962]
One of the problems we encountered migrating from Core 2.2 to Core 3.0-preview3 is introducing Endpoint Routing, as discussed here: https://devblogs.microsoft.com/aspnet/aspnet-core-3-preview-2/ We have CORS and Authroization in both middleware and MVC. Specifically, 
`
services.Configure<MvcOptions>(options => {
                options.Filters.Add(new CorsAuthorizationFilterFactory("AllowAnyOrigin"));
            });
`
is now throwing an error. 
Yes, the way we have it in 2.2 has a smell, and it's great to have a cleaner way - but some guidance as to how to implement the new way would be very helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mkArtakMSFT** [comment]
We will try to update CORS documentation to reflect on the ER changes.
