### ISSUE TITLE
Browser Link doesn't work with ASP.NET Core

### ISSUE THREAD

**Issue by AhmedHemdan21** [aspnet/AspNetCore.Docs#11963]
Browser Link never worked for me with ASP.NET Core, 
this is my 3rd laptop and i have tried with VS17, and currently using VS19 with fresh Win 10, still getting no current connections 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.2#)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use the Visual Studio feedback menu item to leave feedback.  Help >  Send Feedback
