### ISSUE TITLE
Link Mismatch

### ISSUE THREAD

**Issue by dersanli** [aspnet/AspNetCore.Docs#11977]
The link format used in this page (example "http://localhost:5000/Movies/Edit/2") does not work in my tutorial implementation. I use "http://localhost:5000/Movies/Edit?id=2" notation instead.

Perhaps it will be OK to fix this in this page or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You missed 
Update the Edit, Details, and Delete Razor Pages to use the "{id:int}" route template.
