### ISSUE TITLE
Update Provider Aliases section

### ISSUE THREAD

**Issue by rychuhardy** [aspnet/AspNetCore.Docs#11978]
- Console
- Debug
- EventLog
- AzureAppServices
- TraceSource
- EventSource

There is no "AzureAppServices" provider alias. Instead "AzureAppServicesFile" and "AzureAppServicesBlob" should be listed. The correct list would be
- Console
- Debug
- EventLog
- AzureAppServicesFile
- AzureAppServicesBlob
- TraceSource
- EventSource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x&view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@rychuhardy Thanks for reporting that!
