### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by dawidgrey** [aspnet/AspNetCore.Docs#11976]
Before creating a new Visual Studio project, Preview version of the SDK need to be enabled in Visual Studio.
Tools -&gt; Options and search for .NET Core you'll see a checkbox that says "Use previews of the .NET Core SDK".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's Step 2 in the list.

<img width="438" alt="Capture" src="https://user-images.githubusercontent.com/1622880/56128474-554cf600-5f45-11e9-8d1b-0fba5a419954.PNG">
