### ISSUE TITLE
New Blazor App Throws Many Problems in VS Code

### ISSUE THREAD

**Issue by PirasannaRavi** [aspnet/AspNetCore.Docs#11971]
When I just follow the instructions to create a new default Blazor App using .Net Core CLI (.Net Core SDK 3.0 Preview) using VS Code, the app build and runs but throws so many problems in the PROBLEMS tab such as the below 
1. Ambiguity between 'Template.__o' and 'Template.__o' [WebApplication1]
2. The name 'page' does not exist in the current context [WebApplication1]

How to Solve this issue?

**Comment by guardrex** [comment]
Hello @PirasannaRavi ... VS Code tooling will be supported with Blazor for the upcoming Preview 4 release. Until then, use the command line to run the app (`dotnet run` from the project's folder).

**Comment by PirasannaRavi** [comment]
Thanks Luke.

**Comment by PirasannaRavi** [comment]
I was able to get rid of the error messages installing the new C# extensions using the VSIX in VS Code. I followed the following link [https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/](url) 

> A new preview C# extension update is available for VS Code that includes the latest C# compiler (aligned with .NET Core Preview 3 and Visual Studio 2019 Preview 4), which is required to use new C# 8.0 syntax. You need to download the extension and then install it as a VSIX in VS Code (VSIX install is in Extensions settings).

**Comment by guardrex** [comment]
Thanks for mentioning that ... it's on my list of things to do for the upcoming Preview 4 release to make sure that it's noted. I'm going to cross-link your remark to the tracking issue.
