### ISSUE TITLE
Should placing app_offline.htm in application directory stop application pool?

### ISSUE THREAD

**Issue by bondido** [aspnet/AspNetCore.Docs#11980]
According to the comment in the powershell code, placing app_offline.htm in application directory stops apppool.
But it doesn't behave like this in my environment (.NETCore 2.2 application hosted on Windows 2012R2)
Requests to the pplication return http 503 but application pool remains started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bondido ... We only deal with doc issues here. Search the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for "app_offline" ... I think you'll see a few issues there, especially dealing with file locks. If the issues that you find don't seem to fit the behavior that you're seeing, you can open a new issue there for the engineers. If we ultimately do need to make a doc change, we can re-open this issue to address it.
