### ISSUE TITLE
Blazor getting starded error

### ISSUE THREAD

**Issue by brunopbarrote** [aspnet/AspNetCore.Docs#11998]
# Issue description

Blazor gettind startd page gives 404. above error:

"404 - Page not found
Hmm, we couldn't find this link, but here are some related search results that may be helpful."

**Comment by guardrex** [comment]
The docs have moved on the repo. We probably won't provide redirects for them given that they're in preview.

https://docs.microsoft.com/aspnet/core/blazor/?view=aspnetcore-3.0
