### ISSUE TITLE
Text/link mistake

### ISSUE THREAD

**Issue by cremor** [aspnet/AspNetCore.Docs#11994]
In the section [HTTP/2 support](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#http2-support) it says

> For more information on the in-process and out-of-process hosting models, see the [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2) topic and the [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2).

Both links are the same. If those should have been different links, one should be changed. Otherwise one can be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @cremor ... They probably were different at some point and then things went sideways on an update.

Do you want to submit a PR to fix it, or shall I patch it?

**Comment by guardrex** [comment]
If you want to set up the PR, do it like this ...

> For more information on the in-process and out-of-process hosting models, see \<xref:host-and-deploy/aspnet-core-module>.

... and update the date in the metadata at the top of the topic.

**Comment by cremor** [comment]
I've never changed MS documentation before, so I think you'll be faster. Feel free to do it if that's ok for you :smile:

**Comment by guardrex** [comment]
sure ... np. I'll take care of it. Thanks for reporting it.
