### ISSUE TITLE
Whether ADFS token encryption has been supported or not？

### ISSUE THREAD

**Issue by victarary** [aspnet/AspNetCore.Docs#11999]
I want to ask if ADFS token encryption has been supported or not? Do you have plan to support it in the futrue if it has not been supported yet?

I saw a property "TokenDecryptionKey" in options.TokenValidationParameters, whether this is the right place to assign the private key to decrypt ADFS token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: WS-Federation #16508

**Comment by blowdart** [comment]
That'd be a question for @Tratcher

**Comment by Tratcher** [comment]
Not that I know of, but TokenValidationParamters is maintained by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet so you should ask there.
