### ISSUE TITLE
Provide guidance for publishing .NET Core Web App to an Azure App Service from Visual Studio code

### ISSUE THREAD

**Issue by ricardoserradas** [aspnet/AspNetCore.Docs#11997]
Visual Studio code is one of the favorite IDE recently. ASP.Net Core as a framework as well.

It would be nice to have guidance on how to do that to reach those people who has this preference combination.

I'll working on creating something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ricardoserradas  I agree. I'll try to get this fixed this month.

**Comment by Rick-Anderson** [comment]
@vijayrkn please comment

**Comment by vijayrkn** [comment]
The commandline documentations listed here should work for VS code - https://github.com/aspnet/websdk#folder-publish

We dont have any specific publish support for App Services from VS code. 

@Andrew-MSFT & @AngelosP to comment on plans for VS code publish support.

**Comment by AngelosP** [comment]
I cannot comment on plans related to Visual Studio Code, my area of responsibility if Visual Studio on Windows.

**Comment by ricardoserradas** [comment]
Hello.

I've created some guidance and added it to a Pull Request, which is related to this issue.

Thanks.
Ricardo Serradas

**Comment by ricardoserradas** [comment]
> The commandline documentations listed here should work for VS code - https://github.com/aspnet/websdk#folder-publish
> 
> We dont have any specific publish support for App Services from VS code.
> 
> @Andrew-MSFT & @AngelosP to comment on plans for VS code publish support.

Oh I understand. What I meant is that we could have a richer guidance, leveraging on either command line and the [Azure App Service Extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureappservice) for Visual Studio Code.

And that's what I've produced and is already available as a PR for you.

**Comment by Andrew-MSFT** [comment]
Adding @metoly who is looking at our VS Code experience

**Comment by metoly** [comment]
Thanks @ricardoserradas !
It looks great. I added a few comments to a PR review to eliminate ambiguity regarding downloading the SDK and making sure that the user is aware of having to install the C# extension.

**Comment by ricardoserradas** [comment]
> Thanks @ricardoserradas !
> It looks great. I added a few comments to a PR review to eliminate ambiguity regarding downloading the SDK and making sure that the user is aware of having to install the C# extension.

Thanks, @metoly. Happy to help! 

The comments make total sense, thanks for the review.

I changed according to your observations already.

**Comment by metoly** [comment]
> Thanks, @metoly. Happy to help!
> The comments make total sense, thanks for the review.
> I changed according to your observations already.

Thanks a lot @ricardoserradas .
I just approved the PR.
