### ISSUE TITLE
Missing documentation regarding .NET Framework

### ISSUE THREAD

**Issue by lafe** [aspnet/AspNetCore.Docs#12009]
The documentation does not mention how to configure the out of process hosting, if the ASP.net Core application does not use .NET Core but .NET Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It shows both configurations in the [Hosting models section](https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#hosting-models) at the top, and it includes the following line in the In-process section:

> The in-process hosting model isn't supported for ASP.NET Core apps that target the .NET Framework.

The [Out-of-process section](https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#out-of-process-hosting-model) has the following:

> If the `<AspNetCoreHostingModel>` property isn't present in the file, the default value is `OutOfProcess`.
>
> Set the value of the `<AspNetCoreHostingModel>` property to `OutOfProcess` ...

**Comment by guardrex** [comment]
I think we're ok .... let me know if you would like to discuss this further, and we can re-open this issue.
