### ISSUE TITLE
How to use the Analyzers?

### ISSUE THREAD

**Issue by gzinger** [aspnet/AspNetCore.Docs#12003]
[EDIT by @guardrex to put the code block in place.]

I do see Analyzers in my newly created ASP.NET Core 2.2 Visual Studio Project. However, I don't understand how to use them.

I changed one of the methods in values controller to the following code:

```csharp
// GET api/values/5
[HttpGet("{id}")]
[ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
public ActionResult<string> Get(int id)
{
    if (id < 1) return NotFound();
    return "value";
}
```

It still compiles without a single error or warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **pranavkm**

**Comment by Rick-Anderson** [comment]
Changed from what? What were you expecting?

**Comment by lonix1** [comment]
@gzinger I also see no change. Did you get it to work?

**Comment by MarcioArakaki** [comment]
When I build my project severeal warnings are present in the terminal, but in my class there are no warnings nor the option to fix the method.

**Comment by jasperdunn** [comment]
Still not getting any intellisense in vscode for this.
