### ISSUE TITLE
RIP G+ icon

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore.Docs#12001]
A suggestion to replace the G+ icon at the top of this page with Google icon instead because Google plus is officially dead as from April 1st, 2019.

The image I'm talking about: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index/_static/social.png?view=aspnetcore-2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Fixed with #15245 .   I removed the outdated and misleading G+ icon rather than replace it since the graphic was not essential.
