### ISSUE TITLE
may Blazor be blessed ,and JavaScript die!

### ISSUE THREAD

**Issue by EKanadily** [aspnet/AspNetCore.Docs#12010]
welll , i can't be thankful enough for Blazor.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @EKanadily! :rocket:
