### ISSUE TITLE
Not an ASP.NET Core example

### ISSUE THREAD

**Issue by ProfBird** [aspnet/AspNetCore.Docs#12024]
This example has a target framework version of 4.5.2
Please give us an example using ASP.NET Core!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ProfBird It's coming up for work soon on https://github.com/aspnet/AspNetCore.Docs/issues/10214. I should be able to get to that within a week. 🤞🍀

**Comment by xcaptain** [comment]
IFormFile binding doesn't work for rest api, I have a simple example:
```
public ActionResult<string> Upload()
        {
            var file = Request.Form.Files[0];

            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(stream);
            }
            return filePath;
        }
```
then using `curl localhost:5000/api/upload -F file1=@/tmp/imgs/test2.png` to test this upload api.

**Comment by guardrex** [comment]
@xcaptain We don't work closed issues. Please open a new issue using the **This Page** feedback button at the bottom of the topic. I'll add your new issue to the tracking issue for the topic. I should be getting to it soon ... I hope in just a few days. 🏃😅

**Comment by xcaptain** [comment]
@guardrex Thank you for the reply, I opened a new issue at #12130
