### ISSUE TITLE
Google+ shutdown warning is outdated

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#12021]
The opening paragraph needs updating now that February/March has passed and the Google+ updates have been made to the relevant packages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  Thanks for bringing this to our attention. I had forgotten about it.
