### ISSUE TITLE
Blazor docs that need redirect

### ISSUE THREAD

**Issue by wadepickett** [aspnet/AspNetCore.Docs#12032]
These 2 topics rank number 5 and 6 on a google search for "ASP.NET Core" + "Blazor"

- https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/
- https://docs.microsoft.com/en-us/aspnet/core/razor-components/

However they both currently return a 404 so we are losing some traffic and we may want to consider a redirect to the new locoation for Blazor docs here:  https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0.

**Comment by guardrex** [comment]
It's under discussion offline. I'm awaiting orders on rolling with https://github.com/aspnet/AspNetCore.Docs/pull/11992.

**Comment by Rick-Anderson** [comment]
We don't redirect preview docs.
