### ISSUE TITLE
New Server Side Blazor App Throws Error while Debugging using VS Code Debugger

### ISSUE THREAD

**Issue by PirasannaRavi** [aspnet/AspNetCore.Docs#12056]
I just followed the steps from [https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio-code](url) to install the required DotNet Core Version and Blazor Components and created new Server Side Blazor App.

Installed the Required Asset as well. Tried to Run the app using the VS Code Debugger.
Encountered the below error at 

`
public static void Main(string[] args)
{
    CreateHostBuilder(args).Build().Run();
}
`
-----------
<img width="864" alt="Screen Shot 2019-04-19 at 7 24 26 AM" src="https://user-images.githubusercontent.com/49619395/56422623-6d3eb580-6276-11e9-9411-695e00f74dde.png">
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'Microsoft.AspNetCore.Components.Server'.'
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestParser.Parse(Assembly assembly, String name)
   at Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider..ctor(Assembly assembly)
   at Microsoft.AspNetCore.Components.Server.ConfigureStaticFilesOptions.PostConfigure(String name, StaticFileOptions options)

**Comment by guardrex** [comment]
Hello @PirasannaRavi ... I don't repro that here. Do you have the latest C# Extension (mine is 1.19.0). My VSC is 1.33.1. Although, I do need to manually open a browser and navigate to the site (my VSC doesn't do that for me for some reason).

You could also try deleting the package cache on the machine just to make sure that that's not a problem: `dotnet nuget locals all --clear` from a command shell.

**Comment by guardrex** [comment]
btw - "I just followed the steps ..." Please use the feedback button for **This Page** at the bottom of the topic. It tags the issue with metadata that helps us track work here.

**Comment by guardrex** [comment]
Take a look at ... https://github.com/aspnet/AspNetCore/issues/9402 ... does that match your setup? Are you on macOS?

**Comment by guardrex** [comment]
@danroth27 I'm going to add a note to the VSC section of *Get Started* to cover this on my update PR today.

**Comment by danroth27** [comment]
@guardrex ok
