### ISSUE TITLE
Intellisense errors anytime a .razor file is open using blazorhosted project template

### ISSUE THREAD

**Issue by jehk32** [aspnet/AspNetCore.Docs#12059]
CS0234 The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)	Testing.Client	C:\Users\Username\Testing\Testing.Client\_Imports.razor

I get about 10 or so lines of errors like that.

I also see
CS0115 '__Imports_razor.ExecuteAsync()': no suitable method found to override	Testing.Client	C:\Users\Username\Projects\Testing\Testing.Client\_Imports.razor

I followed the instructions on the "Getting started with Blazor" page. I had no preview version of visual studio installed.

**Comment by guardrex** [comment]
Hello @jehk32 ... I checked the engineering issues, and I don't see one for that. Open this over on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for the engineers to see.

If you find out from them over there that we need to surface something about it in the doc, ping me back over here, and we'll re-open and work this for docs.

**Comment by guardrex** [comment]
oh ... and btw --- use the **This Page** feedback button at the bottoms of our topics to open an issue. It tags the issue with metadata that helps us track our work.
