### ISSUE TITLE
Add check if code is running on server side (prerendering) or client side

### ISSUE THREAD

**Issue by smartprogrammer93** [aspnet/AspNetCore.Docs#12057]
Add check if code is running on server side (prerendering) or client side

JsInterop can only be invoked when running on webassembly. so if we have prerending, you need meake sure the invoke happens only on client side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'll cross-ref the content that we added to the *Hosting models* topic in the JSInterop topic.

https://docs.microsoft.com/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#detect-when-the-app-is-prerendering
