### ISSUE TITLE
"RazorGenerate" task was not found

### ISSUE THREAD

**Issue by Chris55** [aspnet/AspNetCore.Docs#12053]
Just teste this, but got this error duing build process:

Error MSB4036	
The "RazorGenerate" task was not found. Check the following: 
1.) The name of the task in the project file is the same as the name of the task class. 
2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 
3.) The task is correctly declared with &lt;UsingTask&gt; in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin" directory.	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't repro that here, and I don't see that reported in the engineering repo.

What versions are you using? Make sure that your SDK is up-to-date (3.0.100-preview4-011223) and VS2019 is 16.0.2 (or later if you're using VS2019 preview). Confirm that your Blazor Extension is up-to-date (v.16.0.19216.3).

**Comment by guardrex** [comment]
@Chris55 I'm going to have you move this over to the engineering repo: Open it at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for the engineers to take a look.

If you find out that we need to surface something in the docs, ping me back over here, and I'll re-open this to work it.
