### ISSUE TITLE
Important: Disable error handler

### ISSUE THREAD

**Issue by bluebaroncanada** [aspnet/AspNetCore.Docs#12050]
[EDIT by @guardrex to fix the code blocks.]

Please update this page to include this little bit.  You can get errors in the console, instead of having to print out the contents of the response. At minimum you should add:

```
builder.ConfigureServices(services => { //Already in the doc
    services.AddMvc(); //Add this line
}).Configure(app => { app.UseMvc(); }); //This is the important line.
```

This will prevent your `Startup.Configure` method from running.  The MVC template includes a `Startup.Configure` method with the following line:

```csharp
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage(); //This is the source of the problem
```

That causes errors not to be caught by xunit.  My method prevents that line from being called, thus, disabling any error handlers and allowing the error message to drop back to xunit which prints it out to the `ITestOutputHelper`.  That way you get beautiful text errors with hyperlinks you can click that bring you right to the error.

I'll bet most people don't even know this is possible.  Please fix!

Here's my question on StackOverflow https://stackoverflow.com/questions/55738128/how-do-you-see-errors-from-the-controller-in-xunit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @bluebaroncanada ... I'll mark this for a look by engineering when they do their engineering doc sweep.

**Comment by bluebaroncanada** [comment]
It actually turns out that this is more important than I once thought. If you don't do this properly, you won't get proper errors from Continuous Integration.

**Comment by Rick-Anderson** [comment]
Moved to #16341: Integration tests MASTER issue
