### ISSUE TITLE
Spelling error in Blazor main page

### ISSUE THREAD

**Issue by Szmiglo** [aspnet/AspNetCore.Docs#12078]
Hi!
I'm not sure if it's right place to report this but I haven't found better place. Looks like there is quite irritating spelling mistage on front page of Blazor https://dotnet.microsoft.com/apps/aspnet/web-apps/client

![image](https://user-images.githubusercontent.com/1494905/56456377-a278ff80-636b-11e9-9e15-5ea75956916b.png)

> Your

 
instead of 

> You're

**Comment by guardrex** [comment]
Thanks @Szmiglo ... Good :eye: ... I opened it over on the repo where that lives. It will be tracked/merged over there. Thanks for letting us know.
