### ISSUE TITLE
Missing details of how to use NSwag with Redoc

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore.Docs#12082]
Page mentions that NSwag can be used as an alternative, and that it also generates/supports Redoc.

But there is no explanation how to do that (i.e. use redoc).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by StanislavPrusac** [comment]
Hi lonix1:
1. You can find about "AspNetCore Middleware" and how add ReDoc:
https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

2. Best example is here:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs

**Comment by RicoSuter** [comment]
Or just add `app.UseReDoc()` and access via `/redoc`

**Comment by Legends** [comment]
Most simple setup for a .net core 3.0 web api project:

```
     public void ConfigureServices(IServiceCollection services)
        {          
            services.AddControllers();
            services.AddSwaggerDocument(config =>
            {
                config.PostProcess = document =>
                {
                    document.Info.Version = "v1";
                    document.Info.Title = "ToDo API";
                    document.Info.Description = "A simple ASP.NET Core web API";
                    document.Info.TermsOfService = "None";
                    document.Info.Contact = new NSwag.OpenApiContact
                    {
                        Name = "YourName",
                        Email = string.Empty,
                        Url = "https://twitter.com/YourName"
                    };
                    document.Info.License = new NSwag.OpenApiLicense
                    {
                        Name = "Use under LICX",
                        Url = "https://example.com/license"
                    };
                };
            });
        }

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            #region swagger

            // URLs: 
            // - http://localhost:65384/swagger/v1/swagger.json
            // - http://localhost:65384/swagger
            // - http://localhost:65384/redoc
            // - http://localhost:65384/openapi
            // - http://localhost:65384/openapi_redoc

            //app.UseOpenApi();
            app.UseSwaggerUi3();
            //app.UseReDoc();

            #endregion//// Add OpenAPI and Swagger middlewares to serve documents and web UIs
...
..
.
```


Only the following urls do not work:
 // URLs:   
            // - http://localhost:xxxx/redoc  --> This localhost page can’t be found
            // - http://localhost:xxxx/openapi  --> This localhost page can’t be found
            // - http://localhost:xxxx/openapi_redoc  --> This localhost page can’t be found

**Comment by robv8r** [comment]
To my knowledge, only `app.UseSwaggerUI3()` and `app.UseReDoc()` offer a web based user interface.  For ReDoc, you'll need to configure the end-point.  

Please see https://github.com/RicoSuter/NSwag/blob/ca33499f4d5c8b90423778d14b1dfa936d251ac7/src/NSwag.Sample.NETCore22/Startup.cs.

**Comment by RicoSuter** [comment]
Maybe the default route of UseReDoc is also /swagger?

**Comment by Legends** [comment]
Installing `Swahbuckle.AspNetCore.Redoc` helps regarding `Redoc`. The `Openapi` urls still don't work.
Adapted my code to look like the above.

**Comment by robv8r** [comment]
In order to create an endpoint for Redoc, you'll need to configure it in your Startup.cs.  For example:

````
app.UseReDoc(config =>
{
    config.Path = "/redoc";
    config.DocumentPath = "/swagger/v1/swagger.json";
});
````

Reference: https://github.com/RicoSuter/NSwag/blob/ca33499f4d5c8b90423778d14b1dfa936d251ac7/src/NSwag.Sample.NETCore22/Startup.cs#L54

**Comment by Rick-Anderson** [comment]
Moved to Master issue, check here first. #16879
