### ISSUE TITLE
Improvements for code understanding

### ISSUE THREAD

**Issue by Mikelsoft99** [aspnet/AspNetCore.Docs#12089]
for the counter component there should be the full code displayed. With the render template, not only the @functions section. 
It could help to understand how this all works together.
best regards
mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Mikelsoft99 ... I'm going to close this and add a link to it from the reviews tracking issue. These topics will *all* receive an edit pass this week. I'll take a look at this when I hit the *Get started* topic again ... actually, it should happen tomorrow (Monday).

**Comment by Mikelsoft99** [comment]
Perfekt, thanks
Mike

Luke Latham <notifications@github.com> schrieb am So., 21. Apr. 2019, 17:51:

**Comment by guardrex** [comment]
I agree here ... I'll add this as a "fixes" to the PR along with the other updates. There are a couple of these that I'll roll into a single update on the Pre4 sweep today.
