### ISSUE TITLE
Deprecated "plus.login" Scope

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#12084]
The `https://www.googleapis.com/auth/plus.login` scope has been deprecated and so the examples should be probably be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-2.2#establish-the-authentication-scope)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thx @serpent5 ... I just changed it on the existing PR.
