### ISSUE TITLE
typo in Event handling

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#12092]
Probably doesn't matter... but.. for completeness sake

message = $"You selected Button #{buttonNumber} at " +
            "mouse position: {e.ClientX} X {e.ClientY}.";

should have $ in front of "mouse position: {e.ClientX} X {e.ClientY}.";

like:

message = $"You selected Button #{buttonNumber} at " +
            $"mouse position: {e.ClientX} X {e.ClientY}.";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#import-components)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, thanks @Alienroid ... I probably broke the line because it was too long (we keep them somewhat short to avoid horizontal scrollbars in the docs) and didn't get the $ in there. I'll patch it up.

**Comment by Alienroid** [comment]
:) that's efficient
