### ISSUE TITLE
Unable to run in Windows PC

### ISSUE THREAD

**Issue by VRKarthik** [aspnet/AspNetCore.Docs#12096]
I am getting the following error while trying to run blazor client app in windows pc, I am using vs code.

> C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\NuGet.targets(121,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [E:\Blazor\webApplication1\webApplication1.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\NuGet.targets(121,5): error :   A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [E:\Blazor\webApplication1\webApplication1.csproj]

Tried restoring nuget packages, getting the same response.

**Comment by guardrex** [comment]
Hello @VRKarthik ... Ask about that over on the NuGet repo. Search first tho ... there seem to be existing similar issues. For example: https://github.com/NuGet/Home/issues/5358

**Comment by guardrex** [comment]
One more thing ... make sure that your VS Code is the latest version. I think 1.33.1 is the latest.
