### ISSUE TITLE
It's not easy to understand for beginners

### ISSUE THREAD

**Issue by imranshams** [aspnet/AspNetCore.Docs#12098]
The information is fairly good, but I looking for a step by step project sample. Who can help me find a beginner tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be127bb-755c-98ab-d7fb-b3f50687857f
* Version Independent ID: 9562d8c0-563d-21ca-e802-80f9b99689ff
* Content: [Host ASP.NET Core in a web farm](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/web-farm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/web-farm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't have a good tutorial link handy. You'll need to search and ask devs on a support forum or chat. There are only a relatively small number of people reading and responding to these issues, so ask on a larger forum. I'm sure you'll get some good tutorial suggestions.

**Comment by guardrex** [comment]
Oh ... Should add that you can try the IIS doc set, too. They might have one or a few good tutorials over there 

https://www.iis.net

**Comment by guardrex** [comment]
... along the lines of ...

https://docs.microsoft.com/iis/web-hosting/scenario-build-a-web-farm-with-iis-servers/overview-build-a-web-farm-with-iis-servers

There are also probably similar docs in the Azure doc set if you want to host on Azure.

**Comment by imranshams** [comment]
> ... along the lines of ...
> 
> https://docs.microsoft.com/iis/web-hosting/scenario-build-a-web-farm-with-iis-servers/overview-build-a-web-farm-with-iis-servers
> 
> There are also probably similar docs in the Azure doc set if you want to host on Azure.

Thank you so much
