### ISSUE TITLE
Info is not part of Swashbuckle.AspNetCore.Swagger in latest version?

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore.Docs#12103]
Not able to follow the instructions on this page with the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by VR-Architect** [comment]
Sorry, I meant version 5.0.0-rc2

**Comment by VR-Architect** [comment]
The new usings is Microsoft.OpenApi.Models.OpenApiInfo

**Comment by spboyer** [comment]
`OpenAPIInfo` is now updated in version 2.2 of the [doc here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware).
