### ISSUE TITLE
Not able to use ConfigureKestrel 

### ISSUE THREAD

**Issue by DMehro** [aspnet/AspNetCore.Docs#12101]
I am not finding option to configure kestrel properties, I have imported Microsoft.AspNetCore.Hosting namespace and .net core 2.1 version on VS 17. What else is missing (its very basic web api project created by Visual studio via scaffolding ) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Did you compare your namespaces against the sample app? ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel/samples/2.x/KestrelSample/Program.cs

Do you have `Microsoft.AspNetCore.Server.Kestrel.Core`?

**Comment by guardrex** [comment]
The `ConfigureKestrel` is in Hosting, but those options are in the other package ...

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.server.kestrel.core?view=aspnetcore-2.2

**Comment by guardrex** [comment]
@DMehro Leave this issue **open**. We have an ongoing effort to improve namespace visibility in the topics, and this is a good candidate. Where the topic talks about the options, it doesn't say explicitly the namespace that they live in. It forces the dev to go to the API browser unnecessarily. I'll make some improvements here shortly. Thanks for asking about this.
