### ISSUE TITLE
Surface Blazor/SignalR WSS guidance

### ISSUE THREAD

**Issue by agc-software** [aspnet/AspNetCore.Docs#12107]
[EDIT by guardrex to update the topic metadata: This work will be for the Blazor Server host and deploy topic]

When hosting a server-side Blazor application the following headers should be added in NGINX proxy config or other preferred config to avoid WSS errors under chrome.

proxy_pass http://hellomvc/;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eddf2de-7e50-5680-ff2d-a4307f26b5c0
* Version Independent ID: 673f220c-ad49-bd27-5d74-3a9c44747cba
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.0#signalr-configuration)
* Content Source: [aspnetcore/host-and-deploy/blazor/server.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by guardrex** [comment]
@shirhatti That's close to what we have at https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx#configure-nginx ...

```
proxy_pass         http://localhost:5000;
proxy_http_version 1.1;
proxy_set_header   Upgrade $http_upgrade;
proxy_set_header   Connection keep-alive;
proxy_set_header   Host $host;
proxy_cache_bypass $http_upgrade;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto $scheme;
```

Can u verify that the delta on ...

```
proxy_set_header Connection "upgrade";
```

... is correct?

If so, I'll move this issue over to the Blazor server-side hosting topic and get it listed for triage by DR.

**Comment by mikes-gh** [comment]
I just discovered this too,

`proxy_set_header   Connection keep-alive;`

Doesnt work with serverside blazor due to the SignalR websockets requirement.

Had to use

`proxy_set_header   Connection $http_connection;`
