### ISSUE TITLE
Incorrect file name in documentation

### ISSUE THREAD

**Issue by crbeckman** [aspnet/AspNetCore.Docs#12119]
for the "Change the site name in the QR Code", the file is listed as "/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml".  Obviously it needs the .cs suffix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie I've got this.

**Comment by scottaddie** [comment]
@Rick-Anderson Already have the PR ready to go.

**Comment by Rick-Anderson** [comment]
OK
