### ISSUE TITLE
Ratings Validation excludes ratings that include numerical values and the character "-"

### ISSUE THREAD

**Issue by Courtland9777** [aspnet/AspNetCore.Docs#12118]
"The RegularExpression attribute is used to limit what characters can be input. In the code above, Genre and Rating must use only letters (First letter uppercase, white space, numbers and special characters are not allowed)."
The validation for ratings as stated above excludes the ratings, "PG-13" and "NC-17". The description should be modified to state the character "-" followed by two numeric characters is acceptable for ratings. The Regex pattern already allows for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This tutorial is not about regEx. Feel free to PR the doc and improve the RegEx.

**Comment by Courtland9777** [comment]
The regex patterns are fine the way they are. They are two different
patterns though. It is the quote I sent explaining the validation that
needs to be corrected to state that ratings are not limited to only
characters but can be numbers as well, like PG-13.
I am very grateful for all the work put in to these tutorials. They have
been extremely helpful. I'd be willing to to submit a rewrite of the quoted
documentation. I just didn't want to step on any toes. Thank you again all
your hard work.

**Comment by Rick-Anderson** [comment]
A PR would be most welcome.

**Comment by Courtland9777** [comment]
Below is the current Regex patterns for "Genre" and "Rating". They are both
correct and working as intended but the patterns are not identical.

[image: Validation.PNG]

Below is the validation documentation describing the RegularExpression
attribute. It describes "Genre" and "Rating" as though they have identical
Regex patterns which is not the case.

[image: RegexBlurb.PNG]

The above bullet point should be modified to reflect the difference in the
two patterns. An example of this modification would be:


   - The "RegularExpression" attribute is used to limit what characters can
   be input. In the code above, "Genre" must only use letters and the first
   letter is required to be uppercase (white space, numbers and special
   characters are not allowed). "Rating" also requires that the first
   character be an uppercase letter but does allow special characters and
   numbers in  subsequent spaces. So, "PG-13" would be accepted as a rating
   but as a "Genre" an error message would appear.


[image: MovieMVCExample.PNG]
  The above photo is directly from the Movie App. I hope it is a good
illustration of what I am trying to say.

I would like to thank you again for all the work you have put into this
project. It has been a wealth of knowledge and a tremendous aid to me. I'm
grateful for the opportunity to help contribute, even if it is something
this small. The time you have taken to correspond with me is appreciated as
well. If I can be of any other assistance or you would like me to clarify
anything I have written, please feel free to reach out.

Best,

Courtland Hacker
