### ISSUE TITLE
Create an ODATA security doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#12115]
Create an ODATA security doc
Port over [Security Guidance for ASP.NET Web API 2 OData](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-security-guidance)

**Comment by Rick-Anderson** [comment]
@FIVIL is there anything like The `[Queryable]` attribute for ASP.NET COre?
See [Query Validation](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options#query-validation)

**Comment by Rick-Anderson** [comment]
@FIVIL   `        [EnableQuery(PageSize =10)]` works

**Comment by Rick-Anderson** [comment]
@FIVIL See [Query Validation](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options#query-validation)

Can you create a sample using   `MyQueryableAttribute ` for ASP.NET Core?

**Comment by FIVIL** [comment]
@Rick-Anderson 
`[EnableQuery]` seems to be Successor od `[Queryable]` in OData v4. so I think generally speaking `[Queryable]` is not a case with asp.net core and works for MVC and legacy versions.
but overriding `EnableQueryAttribute` and query validations is possible with ASP.net core.

**Comment by FIVIL** [comment]
@Rick-Anderson 
sure. I will add an example of Query Validation
just to be sure may i add new examples to existing tutorials, or should i create a new MD file. like the documentation of ASP.NET MVC

**Comment by Rick-Anderson** [comment]
@FIVIL  just create the sample for now. Create a PR with the sample in `AspNetCore.Docs\aspnetcore\web-api\advanced\odata-security\samples`

**Comment by FIVIL** [comment]
@Rick-Anderson 
Sure, I'll try to submit the pull request ASAP (within a day)

**Comment by FIVIL** [comment]
@Rick-Anderson 
under which branch should i search for `AspNetCore.Docs\aspnetcore\web-api\advanced\odata-security\sample` ?

**Comment by FIVIL** [comment]
@Rick-Anderson 
well, I thought you already added a folder at that path. but now I realized that's not the case.
ill add it under my own branch (`OData`)

**Comment by Rick-Anderson** [comment]
@FIVIL  sorry, yes.. Just create it in your PR.

**Comment by FIVIL** [comment]
@Rick-Anderson 
i couldn't add new commits to my other PR. so i created a new PR https://github.com/aspnet/AspNetCore.Docs/pull/12137
