### ISSUE TITLE
Are sessions blocking in ASP.NET Core?

### ISSUE THREAD

**Issue by mirsaeedi** [aspnet/AspNetCore.Docs#12110]
In ASP.NET sessions were blocking which means concurrent requests of a session were queued and ran serially. Do we still have this behavior in ASP.NET Core? If it doesn't stand true, can we mention this fundamental difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by zdarovka** [comment]
From my testing I would say that in ASP .NET Core sessions are not blocking in the same way as in the MVC5, but let me know if you find any real answer in this

**Comment by Rick-Anderson** [comment]
Sessions are not blocking in ASP.NET Core.
