### ISSUE TITLE
HttpsInlineCertStore "Store" field do not default to "My"

### ISSUE THREAD

**Issue by natenho** [aspnet/AspNetCore.Docs#12113]
When following the instructions using certificate from cert store:

```json
"HttpsInlineCertStore": {
      "Url": "https://localhost:5002",
      "Certificate": {
        "Subject": "<subject; required>",
        "Store": "<certificate store; defaults to My>",
        "Location": "<location; defaults to CurrentUser>",
        "AllowInvalid": "<true or false; defaults to false>"
      }
```

If you omit the "Store" field, the application throws Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The parameter is incorrect'

So it should be documented as a required field instead of "certificate store; defaults to My".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @natenho ... I'll get on this asap.
