### ISSUE TITLE
Do you miss [FromBody] for post sample. otherwise it can not accept json body.

### ISSUE THREAD

**Issue by qitia** [aspnet/AspNetCore.Docs#12123]
post sample does not accept json body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@qitia This particular controller is annotated with the `[ApiController]` attribute that was introduced in ASP.NET Core 2.1. Consequently, [binding source inference](https://docs.microsoft.com/aspnet/core/web-api/?view=aspnetcore-2.2#binding-source-parameter-inference) is in play. The binding source inference feature assumes the parameter will be found in the request body, therefore making the application of the `[FromBody]` unnecessary.
