### ISSUE TITLE
node js is required?

### ISSUE THREAD

**Issue by s-trooper** [aspnet/AspNetCore.Docs#12124]
i got "'npm' is not recognized as an internal or external command", is node js a requirement? if so it should be mentioned in Prerequisites. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by scottaddie** [comment]
@s-trooper Thank you for reporting this issue. Visual Studio ships with Node.js and npm. VS Code, on the other hand, does not ship with these products. I'll get the tutorial updated.

**Comment by s-trooper** [comment]
i just installed "node.js development" for my VS 2019, "asp.net web development" was already there. i got no nodejs installed, i suppose i have to install nodejs from web but such things should be realy mentioned.

**Comment by scottaddie** [comment]
@s-trooper I've explicitly listed Node.js and npm as prereqs (with links to their appropriate download locations).
