### ISSUE TITLE
life cycle in  signalR java client

### ISSUE THREAD

**Issue by ahmadhamzavi** [aspnet/AspNetCore.Docs#12122]
how to identify when java client connected successfully to SignalR. where is onConnect life cycle .

i want to do something when hubConnection connected to server.

hubConnection have onClose method for subscribing callback method that run when connection is closed or disconnected.

**Comment by BrennanConroy** [comment]
When `start` returns then you know the connection was successful.

For example you could do:
```java
hubConnection.start().doOnComplete(() -> logger.info("Client connected successfully."));
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
