### ISSUE TITLE
Error Displayed Viewing Counter Source

### ISSUE THREAD

**Issue by bytemon** [aspnet/AspNetCore.Docs#12125]
Followed instructions creating Blazor client project.  Get a red squiggly under "IncrementCount" on the Counter page with following error:
    cannot convert method group to non-delegate type object
If I click on the entire solution error circle I get:
     CS0234 C# The type or namespace name 'Mvc' does not exist in the namespace (are you missing an assembly reference?)

The Counter page, however, does compile and run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bytemon ... AFAIK, these are point-in-time IntelliSense problems that will be corrected as the tooling advances. I can't provide an ETA on the next VS release, but I think you'll find that when it comes out that at least some of these rough spots will be fixed. I suspect that by the time we get to the 3.0 RTM release (hopefully later this year according to the roadmap), the tooling will have come a long way by then, too, and most of these types of problems will be resolved.
