### ISSUE TITLE
AddStackExchangeRedisCache in 2.2 version

### ISSUE THREAD

**Issue by freerider7777** [aspnet/AspNetCore.Docs#12127]
Hi,

I select 2.2 version (in the dropdown) and the page shows AddStackExchangeRedisCache for Redis cache, though AddStackExchangeRedisCache seems to be included only in version 3.

(In 2.2 still AddDistributedRedisCache)

BTW what's the need to rename?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @freerider7777 ... It's for 2.2. Example: https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.stackexchangerediscacheservicecollectionextensions.addstackexchangerediscache?view=aspnetcore-2.2 ... see the **Applies to** at the bottom.

Cross-ref: It was worked on:

* https://github.com/aspnet/AspNetCore.Docs/issues/11118
* https://github.com/aspnet/AspNetCore.Docs/pull/11158

**Comment by guardrex** [comment]
I'm going to close as answered, but we can re-open this if you'd like to discuss it further.

**Comment by freerider7777** [comment]
Why close? I open documentation for 2.2 and it shows methods from 3.

**Comment by guardrex** [comment]
No ... the method is for >=2.2 ... both 2.2 and 3.0+.

Why do you think that `AddStackExchangeRedisCache` isn't available for 2.2?

**Comment by guardrex** [comment]
Do u have the wrong package reference ... 

Did you go with [Microsoft.Extensions.Caching.StackExchangeRedis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis)?

**Comment by guardrex** [comment]
Topic looks like it has a bad reference tho further down on Line 42. I'll take a look shortly ... I'm 🏃 at the moment.

**Comment by guardrex** [comment]
ok ... just looked. It's good. The reference that I referred to is inside a 2.1 versioning block, so the topic seems ok.

**Comment by freerider7777** [comment]
New project -> Web API 2.2, 
add nuget package microsoft.extensions.caching.redis
AddDistributedRedisCache available, AddStackExchangeRedisCache NOT available

**Comment by guardrex** [comment]
That's the old package. Don't use `Microsoft.Extensions.Caching.Redis`. Use .........

```console
add nuget package Microsoft.Extensions.Caching.StackExchangeRedis
```

**Comment by guardrex** [comment]
I think we're ok here. Looks like you just need to change the package reference. The topic seems ok ......

For the 2.1 version of the topic, it shows `Microsoft.Extensions.Caching.Redis`.

For the >=2.2 version, it shows `Microsoft.Extensions.Caching.StackExchangeRedis`.

I'm not sure why they changed the package name, namespaces, methods, etc. We'd need to ask the engineers over on the aspnet/Extensions repo, but I doubt that it's worth the trouble. Whatever the reason(s), this is what they want everyone to use now.

**Comment by freerider7777** [comment]
Thanks for clarification! :)
I didn't notice the package change.
Really strange why everything changed so much...

**Comment by TangMonk** [comment]
Microsoft.Extensions.Caching.StackExchangeRedis not work on 3.0
