### ISSUE TITLE
This upload example doesn't work for dotnet core 2.2

### ISSUE THREAD

**Issue by xcaptain** [aspnet/AspNetCore.Docs#12130]
I tried to run this upload example but failed, error message is `Null Reference Exception with IFormFile`. I changed to below example and it works.
```csharp
[HttpPost("upload")]
public ActionResult<string> Upload()
{
    var file = Request.Form.Files[0];

    // full path to file in temp location
    var filePath = Path.GetTempFileName();

    using (var stream = new FileStream(filePath, FileMode.Create))
    {
        file.CopyTo(stream);
    }
    return filePath;
}
```
Test command is `curl localhost:5000/api/upload -F file1=@/tmp/imgs/test2.png`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @xcaptain ... I'll add this to the tracking issue. I hope to get to that issue by the end of the week. 🤞

**Comment by guardrex** [comment]
This is addressed and tracked by the master tracking issue. I'm going to close here and only attach the master tracking issue to the PR.
