### ISSUE TITLE
Inconsistency in "Use dynamic LINQ to simplify code" section

### ISSUE THREAD

**Issue by aws5295** [aspnet/AspNetCore.Docs#12133]
The example in "Use dynamic LINQ to simplify code" section shows the Index() method accepting an int? called "page".
However in the previous tutorial article on "Sort, filter, page, and group", the parameter  was called "pageNumber" and the view was set up to bind the value to a variable called "pageNumber".

Also, it looks like "page" is a reserved name and can't be used as a route parameter: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#reserved-routing-names

Great tutorial otherwise - very useful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@aws5295 thanks for the feedback. We'll get this fixed in the next doc sweep.
