### ISSUE TITLE
Update sample code to adapt to Blazor's current requirements

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore.Docs#12139]
- Decorate all parameters with `[Parameter]`
- Make parameters `private`
- Change `Action` type to `EventCallback`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Already done ... we haven't merged it to live yet.

**Comment by guardrex** [comment]
I'll do that now. https://github.com/aspnet/AspNetCore.Docs/pull/12141

**Comment by Andrzej-W** [comment]
@guardrex Component parameters are still `public`and they should be `private` (eventually `protected`). Look here https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#component-parameters
First sentence is:
> Components can have component parameters, which are defined using non-public properties on the component class decorated with [Parameter].

**Comment by guardrex** [comment]
> Component parameters are still public

Where? I trying to get these updated on this round (Preview 4) of doc updates.

**Comment by guardrex** [comment]
oh ... sorry. Yes ... I see them. ok ... I'll get 'um.

**Comment by guardrex** [comment]
ei ei ei ... and I just spotted another one elsewhere.

We'll just need to spot and update these as we go. There were a bunch of them that came from engineering samples back in the Blazor.Docs days. The only way to get them out is to manually catch them on doc updates. :eyes:

**Comment by guardrex** [comment]
Here's what I'll do ... I have a couple of open Blazor PRs right now touching several topics. I'm going to let those merge first. I've made a note to sweep the doc set again for these.

**Comment by Andrzej-W** [comment]
@geardrex Be careful with automatic `public => private` conversion for parameters. Here https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#tabset-example in `Tab component` source code you will find this line:
```c#
[Parameter]
public RenderFragment ChildContent { get; private set; }
```
It have to be public because it is used from `TabSet` component.

**Comment by guardrex** [comment]
@Andrzej-W I'll ping you on the PR. Let's put them in separately so that anything I :boom: *break* :boom: 🙈 is easy to spot.
