### ISSUE TITLE
How external logins (Google etc.) work with this SPA setup?

### ISSUE THREAD

**Issue by lertoo** [aspnet/AspNetCore.Docs#12138]
Please provide external logins exmaple for "Identity with SPA".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
This is no different from configuring identity to use an external provider.

https://docs.microsoft.com/es-es/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2

**Comment by lertoo** [comment]
Thanks you. It's great. 
Previously I got some errors. With lastest updates (3.0 preview 4 & VS16.0.2) all are working fine now - except Providers are now in separate NuGet packages: Microsoft.AspNetCore.Authentication.xxxx
