### ISSUE TITLE
React to back-end changes & ReplacePrincipal

### ISSUE THREAD

**Issue by chickenpotpie** [aspnet/AspNetCore.Docs#12147]
I was having an issue where after using `ReplacePrincipal` to update my principal, antiforgery token validation would fail. After looking around in the default antiforgery validation code I found that I needed to include a `NameIdentifier `or `Upn `claim to be able to update claims and have my antiforgery tokens still work.

https://github.com/aspnet/AspNetCore/blob/4a5f2d16bbeab0e16f3786d5058872c013c686f9/src/Antiforgery/src/Internal/DefaultClaimUidExtractor.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm can I close this issue and let the issue document

>I was having an issue where after using `ReplacePrincipal` to update my principal, antiforgery token validation would fail. After looking around in the default antiforgery validation code I found that I needed to include a `NameIdentifier `or `Upn `claim to be able to update claims and have my antiforgery tokens still work.

https://github.com/aspnet/AspNetCore/blob/4a5f2d16bbeab0e16f3786d5058872c013c686f9/src/Antiforgery/src/Internal/DefaultClaimUidExtractor.cs

**Comment by pranavkm** [comment]
> can I close this issue and let the issue document

Sure
