### ISSUE TITLE
404 on Github reference

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#12145]
This link gives a 404: https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/logging/loggermessage/samples/2.x/LoggerMessageSamples/

I'd love to see the sample :) can you provide a new URL please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e02614-5cdd-0c85-3193-75a2325326b4
* Version Independent ID: fca176e2-c56e-0f17-de1b-e60912091e4b
* Content: [High-performance logging with LoggerMessage in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/logging/loggermessage.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/loggermessage.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sorry about that @jasonshave ... the 🧀 must have moved.

Here's the sample :point_right: https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/logging/loggermessage/samples/2.x/LoggerMessageSample

I'll get this patched today. Thanks for letting us know!

**Comment by jasonshave** [comment]
Thank you 👍

**Comment by guardrex** [comment]
Sure thing ... no need to close. This will auto-close when the PR merges.
