### ISSUE TITLE
No mention of RazorLangVersion on this page even though warnings point to this page about it

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore.Docs#12142]
I'm building a project that uses .razor files for the purpose of #blazing and I got this warning:

Warning RAZORSDK1005 One or more Razor component files (.razor) were found, but the project is not configured to compile Razor Components. Configure the project by targeting RazorLangVersion 3.0 or newer. For more information, see https://go.microsoft.com/fwlink/?linkid=868374

If you go to https://go.microsoft.com/fwlink/?linkid=868374, it takes you to this doc (https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2), which doesn't mention RazorLangVersion at all.

It would be nice to have a mention of it, and showing where/how to put it in the CSPROJ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson Let me know if you want it documented here (Razor SDK) or in the Blazor docs. If here, then you may decide to handle this. If in the Blazor docs and you want me to keep it and move it to the Blazor project, then that fwlink should point to a new location. The only problem with taking it to Blazor is that we don't have a great spot for it at the moment. I'll have to confer with DR to determine the best spot if we're going to get into project file details for Blazor (we just don't cover any of it at the moment).

**Comment by Eilon** [comment]
@danroth27 - this is the issue I was talking to you about.

**Comment by hannespreishuber** [comment]
same issue here
trying to build a component library

Compiles, but can not be used by reference in Visual Studio Solution with both Projects.

Component builds, the dll is there, but is the .Razor included?
