### ISSUE TITLE
Blazor (Client Side)

### ISSUE THREAD

**Issue by smjltd** [aspnet/AspNetCore.Docs#12140]
There is not enough documentation for Blazor (Client Side) for example creating using command line dotnet new blazor -o proj creates server side hosted blzaor not webassembly one please show us how to create Blazor (Client Side)!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> using command line dotnet new blazor -o proj creates server side hosted blzaor not webassembly one

That shouldn't be possible. The server-side template is called `blazorserverside`. If you're using `blazor` and getting a server-side app, then you should open that on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for the engineers to address.

I agree with you that the *Hosting models* topic should have a cross-link to the *Get started* topic to make sure that the reader can find the instructions for creating either of the app types. I'll cross-link them. Leave this issue open ... it will auto-close when the PR merges. Thanks for the feedback.
