### ISSUE TITLE
VS2019 Pre2 loads a blank solution for a Blazor hosted project

### ISSUE THREAD

**Issue by stephenmroe** [aspnet/AspNetCore.Docs#12159]
I've followed these steps, and when I open the solution, it's empty.  The Solution Explorer shows: "Solution 'BlazorDemo' (0 of 0 projects)".  When I browse to the file system manually it appears the project template did in fact create all the intended artifacts, including 'BlazorDemo.Client', 'BlazorDemo.Server', and 'BlazorDemo.Shared' folders, along with the 'BlazorDemo.sln' file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't repro that here, but I'm not on the preview release. I'm on VS2019 v16.0.2.

<img width="230" alt="Capture" src="https://user-images.githubusercontent.com/1622880/56733404-ab7c1f00-6725-11e9-9c1a-7c2ca3102766.PNG">

You may have run into a point-in-time problem with the preview release of VS. The best way to provide feedback about it is by using the **Help** > **Send Feedback** > **Report a Problem** process from within Visual Studio ... that feedback goes directly to the engineering team that handles Visual Studio.

As a temporary workaround, you could open the client project (via its project file), add the server and shared projects (via their project files), and then create the solution that way.

cc: @danroth27

**Comment by danroth27** [comment]
Closing since this appears to be a product issue, not an issue with the documentation.
