### ISSUE TITLE
ElasticCache

### ISSUE THREAD

**Issue by tellybrown** [aspnet/AspNetCore.Docs#12163]
I have implemented this interface for ElasticSearch.  It also has the ability to compress larger cached objects.

https://github.com/tellybrown/ElasticCache
https://www.nuget.org/packages/ElasticCache/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tellybrown ... I guess you're asking to have it mentioned+linked in the topic? The product unit will need to look and decide if they'd like to do that. I've marked this issue for their review.

**Comment by tellybrown** [comment]
Sorry.  I was expecting the comments to behave like they did before the github integration.  I was just commenting on the page.
