### ISSUE TITLE
Reload applies to more than file providers

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore.Docs#12161]
Under "Conventions" it says "File Configuration Providers have the ability to reload configuration when an underlying settings file is changed after app startup. The File Configuration Provider is described later in this topic."

However, change detection is not exclusive to file providers, any provider could implement this. This support was recently added to the KeyVault provider for example. https://github.com/aspnet/Extensions/pull/1054.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#conventions)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> any provider could implement this

... but not all of them. Seems like we should call out which ones do it ... perhaps in the table in the *Providers* section.

https://docs.microsoft.com/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#providers
