### ISSUE TITLE
Pages 1 through 5 do not show any content

### ISSUE THREAD

**Issue by Ace07** [aspnet/AspNetCore.Docs#12176]
Tutorial Pages 1 through 5 do not show any content, just the header and Feedback sections. Pages 6 on seem fine. I've tried Edge and Chrome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ace07 ... It's a versioning issue. The topic probably just needs the 2.1+ moniker at the top. If you flip the version up to 2.1 in the sidebar, you'll get the content.
