### ISSUE TITLE
Need to add ASP NET Core 3.0 runtime extension to Azure app service to avoid an error

### ISSUE THREAD

**Issue by patrickjlee** [aspnet/AspNetCore.Docs#12179]
At present (26 Apr 2019) one gets an error message when deploying to Azure, because preview versions of ASP NET Core are not installed by default. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-3.0#deploy-aspnet-core-preview-release-to-azure-app-service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042b0c63-cbb8-0347-97f2-11e935aae405
* Version Independent ID: 064606f3-3a82-1493-768a-41e056eb92de
* Content: [Host and deploy Blazor server-side](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server-side?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/host-and-deploy/blazor/server-side.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/blazor/server-side.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @patrickjlee I'll cross-link the coverage for that.

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2#deploy-aspnet-core-preview-release-to-azure-app-service
