### ISSUE TITLE
Should the sample projects be moved to aspnet/samples?

### ISSUE THREAD

**Issue by nschonni** [aspnet/AspNetCore.Docs#12175]
Seems like the dotnet/docs moved theirs to dotnet/samples and the build pulls in pieces as needed

**Comment by guardrex** [comment]
There was going to be a solution for all repos ... https://github.com/aspnet/AspNetCore.Docs/issues/6991#issuecomment-398104010 ... but "near-term" doesn't look like it worked out. There may have been technical problems.

@scottaddie Are there any updates?

**Comment by Rick-Anderson** [comment]
@rpetrusha can you advice us how to migrate our samples? How do we get a samples repo? 

I've referenced sample code in another repo before, it's not that much more work. Do you have a doc you could point to we could use as an example?

**Comment by Rick-Anderson** [comment]
cc @tdykstra

**Comment by Rick-Anderson** [comment]
If that works out for them we'll consider it.

**Comment by nschonni** [comment]
I believe they're also looking at https://github.com/dotnet/try for some of the examples too

**Comment by rpetrusha** [comment]
I'm not sure that there's a document available about it, but the migration should be straightforward -- just create a samples repo; code references should work either unchanged or when the path starts with ~/samples. 

There's a second issue here as well -- downloading small amounts of code without having to get the entire repo. You can create .zip files and, when they're placed in a repo, become downloadable. We had started to do that for some high page view topics, but the results haven't really justified the effort involved. For example, String.Format has 30,000+ page views per month, but fewer than 100 combined downloads (for both the C# and VB examples) per month.
