### ISSUE TITLE
docker run : linux on 5000 not working

### ISSUE THREAD

**Issue by amitdixit** [aspnet/AspNetCore.Docs#12187]
After 
--&gt; docker run -it --rm -p 5000:80 --name aspnetcore_sample aspnetapp
--&gt;http://localhost:5000 does not work.

To make it work had to perform below steps:
-&gt; Get the container IP using --&gt; docker inspect [container id]
-&gt; In my case http://172.17.0.2/ --&gt;Done

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@amitdixit I tried it with Ubuntu 18.04 and can't replicate the error.  What distro/version are you using?

**Comment by tdykstra** [comment]
Closing the issue for now. Will reopen when information is available that makes it possible to repro the error.
