### ISSUE TITLE
Poor Example

### ISSUE THREAD

**Issue by jwhitener6** [aspnet/AspNetCore.Docs#12189]
I appreciate the work that goes into this sample and I've found it helpful in other tutorials. However I think it poorly demonstrates Updating related data. You have only one example of updating one to many related data (CourseAssignments) which works by passing a string array parameter that you have to break down once it is brought into the function and updated separate from the primary model (instructor). It seems inefficient and more importantly it doesn't address real world examples where a related model may have more than 1 property. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [Tutorial: Update related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@jwhitener6  thanks for your comment. This tutorial isn't meant to cover more advanced scenarios.
