### ISSUE TITLE
Builder pattern link

### ISSUE THREAD

**Issue by andynewcomb** [aspnet/AspNetCore.Docs#12209]
The link to the builder pattern goes to a wiki page that describes the GOF builder pattern... but I believe the builder pattern being used for the CreateDefaultBuilder is a modified version of Joshua Bloch's version of builder pattern from "effective java". Can that be confirmed and clarified? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&tabs=windows#feedback)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The topic doesn't use the phrase "GOF builder pattern." The Wikipedia topic doesn't describe the pattern that way either. It just says that the builder pattern is one of the GoF patterns.

A more specific possibility (without linking the book), which is linked in the Wikipedia topic is ...

http://www.drdobbs.com/jvm/creating-and-destroying-java-objects-par/208403883?pgno=2

* Is it clearer? (probably yes imo)
* Is it more authoritative than Wikipedia? (probably yes imo)

**Comment by andynewcomb** [comment]
Yes! The link you mention is more like the "builder pattern" that WebHostBuilder and other builder-like classes in Asp.Net are emulating. The Wikipedia article on the other hand is describing a different pattern (unfortunately it is named the same). The Wikipedia article is definitely referring to a specific builder pattern that was authored by the gang of 4... In the "overview" on Wikipedia it states "The Builder design pattern is one of the twenty-three well-known GoF design patterns[1"

It then goes on to show a uml diagram showing the pattern, which is exactly the one used by the gang of 4 and completely different from the "builder pattern" used by Asp.Net.  

The two patterns are often confused because they have the same name and solve similar problems. Even Wikipedia got confused and linked to Joshua Blachs implementation.

**Comment by tdykstra** [comment]
@andynewcomb Thanks for pointing this out.  I agree that the link @guardrex provides is much better than the Wikipedia link. But rather than change the link, I'm editing out the reference to builder pattern. On reviewing the text and keeping in mind that the article is a high-level overview, it seemed better to make the Host section more concise and avoid getting into a topic outside the scope of the article.
