### ISSUE TITLE
Not able to view counter component in "index.razor"

### ISSUE THREAD

**Issue by jsowndarrajan** [aspnet/AspNetCore.Docs#12207]
I followed the getting started tutorial and added the counter component `<Couter />` tag inside the `index.razor` page but I am not able to see the Counter component in the browser.

Do I need to do any changes in the default web app template that is created by Blazor template extension in the VS2019? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jsowndarrajan ... Check your spelling ... it should be ...

```cshtml
<Counter />
```
