### ISSUE TITLE
Processing a file after uploading

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore.Docs#12204]
I suggest to include in the code samples a simple processing step after uploading. 
For example, how to copy a file from the temporary path to a required path with a sample filename and the correct extension. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @shadinamrouti ... I've added this to the tracking issue. Thanks for commenting.

**Comment by shadinamrouti** [comment]
Thanks @guardrex and @Rick-Anderson for your quick response as usual.

I will leave here my code which may help someone if _she_/he needs to copy an uploaded file to a location inside www root:

```csharp
   var file = Request.Form.Files[0];
   var filePath = Path.GetTempFileName();
  ...
   //processing
   var fileExt = System.IO.Path.GetExtension(file.FileName); 
   var newFileName = Guid.NewGuid() + fileExt;
   var newFilePath = HostingEnvironment.WebRootPath + $@"\images\{newFileName}";
   System.IO.File.Copy(filePath, newFilePath, true);
```
