### ISSUE TITLE
Not available for 2.0

### ISSUE THREAD

**Issue by JohnCOsborne** [aspnet/AspNetCore.Docs#12200]
The requested page is not available for 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-2.0#exception-handler-lambda)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Correct

**Comment by JohnCOsborne** [comment]
My apologies -- Figured it should of been since I can use the exception handler lambda in my 2.0 project.
