### ISSUE TITLE
Possible correction

### ISSUE THREAD

**Issue by funcubes** [aspnet/AspNetCore.Docs#12214]
"Blazor implements .NET Standard 2.0. APIs that aren't applicable inside a web browser..." 
I am not a native English speaker but don't you think that line is misleading ? shouldn't it be 
"Blazor implements .NET Standard 2.0. APIs, except that aren't applicable inside a web browser" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/index?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> APIs that aren't applicable inside a web browser (for example, accessing the file system, opening a socket, and threading) throw a `PlatformNotSupportedException`.

Hello @funcubes ... The text is correct. "misleading" ... why do you think so?

**Comment by guardrex** [comment]
What I'd like to do here is break the paragraph. It shifts focus when it stops describing the .NET Standard and starts describing APIs that aren't going to work client-side. That will fix this confusing language.
