### ISSUE TITLE
Link wrong to ASP.NET Core SignalR

### ISSUE THREAD

**Issue by dodegaard** [aspnet/AspNetCore.Docs#12215]
The link in the initial section points to legacy SignalR in the href but the link text says ASP.NET Core SignalR.  Here is the test to note... 
For more information, see #ASP.NET Core SignalR#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfda216b-81ea-485b-9b8e-1f8d747e000a
* Version Independent ID: 81b63785-aab6-b4d9-0e7b-c2c6c6ce3829
* Content: [What's new in ASP.NET Core 2.1](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.1?view=aspnetcore-2.2)
* Content Source: [aspnetcore/release-notes/aspnetcore-2.1.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-2.1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @isaac2004
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @dodegaard ... I'll get that patched.
