### ISSUE TITLE
What if the array of objects on the backend change?

### ISSUE THREAD

**Issue by GSUFan513** [aspnet/AspNetCore.Docs#12213]
For instance if I have an endpoint where I'm patching a list of customers where the subset array of object changes relatively often, how do I know that the patch is on the correct array of objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@GSUFan513 Thanks for the question. You'll probably get a faster answer on a support forum, such as StackOverflow, or a support chat, such as Slack or Gitter. If you post the question elsewhere, please update this issue with the link.
