### ISSUE TITLE
WebApplicationFactory - Shadow Copying

### ISSUE THREAD

**Issue by andrefilipegsilva** [aspnet/AspNetCore.Docs#12212]
# Issue description

I'm currently trying to launch a `TestServer` using the `WebApplicationFactory`. I followed the [docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) but in the end I end up with the error:

> Can't find 'C:\Repos\{production-net-core-app-assembly}.deps.json'. This file is required for functional tests to run properly. There should be a copy of the file on your source project bin folder. If that is not the case, make sure that the property PreserveCompilationContext is set to true on your project file. E.g '<PreserveCompilationContext>true</PreserveCompilationContext>'. For functional tests to work they need to either run from the build output folder or the {production-net-core-app-assembly}.deps.json file from your application's output directory must be copied to the folder where the tests are running on. A common cause for this error is having shadow copying enabled when the tests run.

I have extended the `WebApplicationFactory` and overridden `ConfigureWebHost ` only to set the Environment name before calling `base` (i.e., `builder.UseEnvironment(IntegrationTestEnvironmentName);`). The error occurrs at this line:

```csharp
var httpClient = webApplicationFactory.CreateClient(new WebApplicationFactoryClientOptions
{
     AllowAutoRedirect = false
});
```

I have the `xunit.runner.json` file at the root of the test project and is being always copied to the `bin/` folder. The startup class is from another assembly (the production-net-core-app-assembly}. I have also tried to set the `<PreserveCompilationContext>` property to true in all referenced projects.

However, if I configure the `TestServer` instance myself with a custom `IWebHostBuilder` without using the `WebApplicationFactory` class, it runs smoothly.

Any ideas?

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @andrefilipegsilva ... Is the goal just to set the environment that the app is running under when the tests are run? What are you trying to do?
