### ISSUE TITLE
Don't bundle tutorial sample code in AspNetCore.Docs repo

### ISSUE THREAD

**Issue by apulliam** [aspnet/AspNetCore.Docs#12227]
Since there is no way to clone a directory in a repo, I have to download all the docs and then sort through to find sample code.  Please keep code samples (including tutorial code) in separate repos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @apulliam ... it's a known issue and remarked upon many times. Management is aware of the problem. They were planning something to address it, but there's no word back on implementation yet. For now, devs do need to fork and clone the repo or take the ZIP down.

In the meantime while they work on a permanent solution, we are actively dropping the JS/Bootstrap assets from as many samples as we can. This is having an excellent impact on overall repo size. We also recently split out the ASP.NET docs from the ASP.NET Core docs ... that helped a lot, too.
