### ISSUE TITLE
Describe the difference between AddCheck and AddTypeActivatedCheck

### ISSUE THREAD

**Issue by schummbo** [aspnet/AspNetCore.Docs#12229]
I can't seem to determine the difference between these two methods for adding health checks. I also can't seem to find any other documentation on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @schummbo ... Correct, we don't use or document it at the moment (... and I haven't used it personally). I'll mark this issue for the PU to take a look and decide if they would like coverage for it. Until then, there's the API Browser ...

https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.healthchecksbuilderaddcheckextensions.addtypeactivatedcheck

Check out what they have in the engineering repo at https://github.com/aspnet/Extensions/search?q=addtypeactivatedcheck&unscoped_q=addtypeactivatedcheck ... it looks like they have one or more notes in the code that might be helpful.

We'll see later if they would like to cover it ... and if so, what they would like to say in the docs.

**Comment by guardrex** [comment]
Looks like the difference is the ability to pass args. Check out that test code ...

* https://github.com/aspnet/Extensions/blob/112c1a8ae1c0a921eae4490abd4ccdfcdb899574/src/HealthChecks/HealthChecks/test/DependencyInjection/HealthChecksBuilderTest.cs#L92
* https://github.com/aspnet/Extensions/blob/112c1a8ae1c0a921eae4490abd4ccdfcdb899574/src/HealthChecks/HealthChecks/test/DependencyInjection/HealthChecksBuilderTest.cs#L239

**Comment by guardrex** [comment]
Note to `rynowak` when you look at this: If the purpose is to be able to pass args, I can handle the update here and include this in the sample app. Otherwise if more complicated and you/PU want to take it, then swap me from the assignment.

@schummbo I'll leave this on the backlog until I hear back from them. They'll look at the "PU" issues at some point and let us know how they would like to proceed.
