### ISSUE TITLE
Unexpected behavior of Url.Action() 

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/AspNetCore.Docs#12221]
According to the [docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#areas):
```csharp
    app.UseMvc(routes =>
    {
        routes.MapAreaRoute("duck_route", "Duck",
            "Manage/{controller}/{action}/{id?}");
        routes.MapRoute("default", "Manage/{controller=Home}/{action=Index}/{id?}");
    });

    [Area("Duck")]
    public class UsersController : Controller
    {
        public IActionResult GenerateURLInArea()
        {
            // Uses the 'ambient' value of area
            var url = Url.Action("Index", "Home"); 
            // returns /Manage
            return Content(url);
        }

        public IActionResult GenerateURLOutsideOfArea()
        {
            // Uses the empty value for area
            var url = Url.Action("Index", "Home", new { area = "" }); 
            // returns /Manage/Home/Index
            return Content(url);
        }
    }
```
The `GenerateURLInArea()` will return `/Manage` and `GenerateURLOutsideOfArea()` will return `/Manage/Home/Index`.

However, when I follow the example and create a demo with ASP.NET Core 2.2,   the response of following URL:
```
GET https://localhost:5001/Manage/users/GenerateURLInArea
```
is : `/Manage/Home/Index`  intead of `/Manage`

And if I send a GET request to  `GenerateURLOutsideOfArea()`  :
GET https://localhost:5001/Manage/users/GenerateURLOutsideOfArea

The actual result is not ` /Manage/Home/Index`  but  `/Manage` .

```
&gt; dotnet --version
2.2.100
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#areas)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #13871
