### ISSUE TITLE
Doesn't need "ASP.NET Core"

### ISSUE THREAD

**Issue by glittle** [aspnet/AspNetCore.Docs#12220]
The LibMan is a part of VS 2019 and can be used for the older ASP.NET MVC type sites too. This is not only for "Core" projects.  Please remove reference to "Core" from this page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e74f29a-f2db-3910-a368-d832c0efd54a
* Version Independent ID: 08df0875-304c-bca1-3b83-6e636f910bc0
* Content: [Client-side library acquisition in ASP.NET Core with LibMan](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/index?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/client-side/libman/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/libman/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @glittle ... The topic doesn't say that ASP.NET Core is required. This repo is dedicated to ASP.NET Core framework coverage, so it's ok for our docs to make remarks that indicate that the tech works with ASP.NET Core and not cover other frameworks (e.g., .NET Framework). LibMan might get coverage for .NET Framework over in https://github.com/aspnet/AspNetCore ... if that's needed, please do open an issue on that repo for .NET Framework coverage.
