### ISSUE TITLE
IIS Idle Timeout

### ISSUE THREAD

**Issue by sebastienricher** [aspnet/AspNetCore.Docs#12232]
I have hosted services running in process on IIS, do these refresh the IIS idle timeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, @sebastienricher ... for the most recent 👊 *bar brawl* 👊 convo, see https://github.com/aspnet/AspNetCore/issues/3849 ....... it's a *knife* 🔪 *fight* in there :smile:, so be ready. Do feel free to add your own feedback. The engineers do take your feedback into consideration as they design and implement scenarios for the framework.

* Use the Application Initialization Module (but that's just to get the app started after an app pool recycle/server start).
* Always running + idle timeout set to 0 (zero) + preload enabled. Engineering says '*it works*' with 2.2 or later.
* Use an external ping service to hit the app periodically (inside the idle timeout) to keep it *warm*.
* Move the scenario to a Windows Service.
* I think someone said this works ... try the [Health Check Publisher](https://docs.microsoft.com/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#health-check-publisher) ... but note that there's a small issue with it until 3.0 (there's a note in the topic to explain the problem).
* I see a PS script thingy that someone did on that engineering issue, too.

Leave this open @sebastienricher ... I'd like to add a section that lays out the options or goes with whatever the engineers prefer that devs use. There will be a delta (probably) for in-process vs. out-of-process (i.e., out-of-process probably works with the external ping the best), and I'd like to get that difference covered, too.

**Comment by sebastienricher** [comment]
Sounds good, I can chime in with the final selection when I have it. One thing that might be to consider also is the Application Pool's .NET CLR Version, in the current tests I'm running, I have it set to No Managed Code.

**Comment by guardrex** [comment]
That's correct ... the CoreCLR is is booted to host the app in the worker process. You should be able to leave that set just like you have it and the methods that I listed *should* work. 🤞🍀 ... don't forget to sacrifice a Microsoft mouse to the 🙏 *server gods* 🙏. :smile: ... it couldn't hurt. :smile:

When I get to this issue, I'll see about clarifying the app pool **.NET CLR version** setting in one or two other spots. Right now, it's only directly covered in the IIS set up instructions (and it doesn't say why one is setting it that way) ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#create-the-iis-site

Of course, it doesn't matter (much) if it's set. There might be a very *VERY* tiny penalty of like microseconds on server start/app pool recycle to have it set AFAIK from talking to the engineers, but I think the language could use a tiny touch of work to clarify it.

**Comment by sebastienricher** [comment]
Good news, I tried "Always running + idle timeout set to 0 (zero) + preload enabled.", initial tests are positive! I'll drill it some more but both my site seems to be staying warm and the hosted services keep running every 15 minutes. Thanks for pointing me in the good direction!

**Comment by guardrex** [comment]
Cool ... did you test an app pool recycle, too? Also ... and similar to a recycle, did you test a total server restart? Does the app get up and running without intervention? The **Application Initialization Module** might be required to get an app started in some scenarios.

**Comment by sebastienricher** [comment]
You're right, that's what I'm seeing now. Once the Application is actually started it does not go to sleep as wanted, but when there is a recycle, it does not come back up on it's own.

I'll look into the initialization module, it seems to be the reliable way to go about this from both your indications and related posts.

**Comment by guardrex** [comment]
Check and confirm that the server role feature for **Application Initialization Module** is enabled.

I have a sneaky impression that the "always running" and "preload" are there but the module doesn't have to be installed for those settings to be available.

**Comment by guardrex** [comment]
I'm going to take **another look** :eyes: at https://docs.microsoft.com/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization

**Comment by guardrex** [comment]
According to IIS's docs, it should ✨ *Just Work*:tm: ✨. I need to dig into the subject a bit more and perform some testing here, too. I'm buried in file upload code at the moment, but I should be free (*free-ish* 🏃😅) within two weeks to take a deeper look.

My impression of the most reliable way to keep an IIS-based ASP.NET Core app started and warm is .... *drum roll plz* .... 🥁🥁🥁🥁🥁 .... **_external service pings_**. ei ei ei ... I know ... I know. That's **_not good_**. I just say that because I've seen this come up over-and-over for two years now and the devs who say that they use an external service to ping their apps seem to live with the least stress in their lives.

**Comment by guardrex** [comment]
..... well .... I'll add this to that .... the devs who moved their always-running service things to a Windows Service also seem very happy. Consider that option, too. Get your always-must-run-ALWAYS! stuff **_off of IIS_**. That's a good option, too.

**Comment by sebastienricher** [comment]
Yeah I need IIS for internal certificate and infrastructure reasons, but it is a viable last recourse.

I'm all setup with application initialization, but I'm still not getting warmed up.

Added this to web.config:

      <applicationInitialization doAppInitAfterRestart="true">
        <add initializationPage="/api/bfm/healthcheck/" />
      </applicationInitialization>

**Comment by guardrex** [comment]
I'm surprised that the preload setting doesn't do it.

> Setting preloadEnabled to "true" tells IIS 8.0 that it sends a "fake" request to the application when the associated application pool starts up.

I'll mark this issue with the PU label, but I might get to it before engineering takes a look. In that case, I'll do the best I can (and do my own testing here as you're doing there). If the PR goes in before they look at this issue, then they'll be pinged to review the PR, and that should lead to final answers on guidance. They might get to looking at "PU"-labelled issues soon now that Preview 4 is out.

**Comment by sebastienricher** [comment]
As a reference, I'm running on HTTPS, so I am looking here for part of the solution also: https://support.microsoft.com/en-ca/help/2843964/application-initialization-module-fails-when-web-site-requires-ssl

**Comment by sebastienricher** [comment]
> "fake" request

Do we know what URL is used for that? This would be subject to the site's bindings?

**Comment by guardrex** [comment]
Good question ... we need PU (product unit) support. Now that I've marked this issue, engineering (`shiratti`) will see it and respond. Alternatively, I'll work the issue and get a PR up. He'll review and help at that point. We're a bit limited on pinging him here because he's quite 🏃😅 busy most of the time. I'll get back to this asap. It's a top item for May, so I think I'll get to it next week.

**Comment by guardrex** [comment]
@sebastienricher It looks like the answer is *yes* to your suggestion on the binding port ... and it goes to `/`.

> The applicationInitialization element tells IIS that it should issue a request to the application's root Url ("/" in this example) in order to initialize the application.

I'll be working this one very soon, including some local testing to see what's what with my own :eyes:. I'll ping u on the PR when it goes up.
