### ISSUE TITLE
What is app's auth scheme?

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore.Docs#12236]
&gt; The app's authentication scheme is different from the app's cookie authentication scheme.

I always thought that the whole purpose of configuring authentication is defining various auth options for app. But from the sentence above it follows that there is a standalone term `app's authentication scheme`. What is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  can you answer quick question?

> The app's authentication scheme is different from the app's cookie authentication scheme.

I always thought that the whole purpose of configuring authentication is defining various auth options for app. But from the sentence above it follows that there is a standalone term `app's authentication scheme`. What is it?

**Comment by Rick-Anderson** [comment]
@HaoK  does this answer the question?

[Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1)

**Comment by HaoK** [comment]
Generally the 'app' authentication scheme is the default scheme or default authentication scheme, which is what the auth middleware will use and set on the HttpContext
