### ISSUE TITLE
Is the project created in Asp.Net core 2.1 or 2.2?

### ISSUE THREAD

**Issue by LouBH** [aspnet/AspNetCore.Docs#12231]
I am using 2.1 and cannot get the project to accept UIFramework (does not exist in the current context).  I tried adding the Microsoft.AspNetCore.Identity.UI namespace but that did not help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`UIFramework` was added in 2.2

**Comment by Rick-Anderson** [comment]
You don't need `UIFramework`  for the sample
