### ISSUE TITLE
About page doesn't work with VS 2019

### ISSUE THREAD

**Issue by kmcbarne** [aspnet/AspNetCore.Docs#12244]
If you follow this tutorial explicitly, only making the changes that are highlighted in green, the About page above doesn't load, either by clicking the menu button or by entering `https:\\localhost:xxxxx\About` in the URL bar.  In order to make this work, you need to add an additional change to the _Layout.cshtml file:
1. Open _Layout.cshtml.
2. Locate the About nav-link line, &lt;a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About"&gt;About&lt;/a&gt;.
3. Modify this line so that the asp-controller value is "Home" instead of "About".
4. Build and run the application, you can now navigate to the About page.

The reason behind this is that when VS 2019 creates the _Layout.cshtml file, it sets up the Home and About pages to use different controllers, rather than both using the same Home controller.  By changing the controller to Home, you redirect the About page to be run by the Home controller, as the tutorial expects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@kmcbarne  you're right. I outlined the steps in  #12245
