### ISSUE TITLE
Markup Issus For Dialog.razor

### ISSUE THREAD

**Issue by stevenfowler16** [aspnet/AspNetCore.Docs#12242]
In the markup for the documentation the section explaining Dialog.razor seems to have an issue with quotation marks around an attribute. 
```
&lt;div&gt;
    &lt;h1&gt;@Title&lt;/h1&gt;

    @ChildContent

    &lt;button onclick="@OnYes"&gt;Yes!&lt;/button&gt;
&lt;/div&gt;
```

The onclick attribute for the button seems to render the rest of the html as a string

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @stevenfowler16 ... I'll take a look.

**Comment by stevenfowler16** [comment]
Sorry for the terrible markup on the issue @guardrex. 

Thanks!

**Comment by guardrex** [comment]
No worries ... it always encodes for a paste into the feedback form on the topics.

The code block is correct in the topic, so this is a styles/rendering problem.

@scottaddie ... does this styles/rendering issue go to our build system folks or over to the DocFX folks?

<img width="258" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57084737-74c37d00-6cc0-11e9-8c27-976abf8d4e09.PNG">

**Comment by scottaddie** [comment]
@guardrex Send this one over to the DocFX team.

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/docfx/issues/4472. Thanks for reporting @stevenfowler16! 🏎
