### ISSUE TITLE
The property 'Department.Budget' could not be mapped ? 

### ISSUE THREAD

**Issue by JackLovel** [aspnet/AspNetCore.Docs#12259]
## system environment
```
os: deepin linux 
ide: vscode 
netcore version: 2.2.203

database: mysql  server 
database version: Ver 14.14 Distrib 5.7.21, for Linux (x86_64) 
mysql drive: MySql.Data.EntityFrameworkCore/8.0.16
```
## error 
When I learn [ASP.NET Core MVC with EF Core - tutorial series](https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/?view=aspnetcore-2.2),  Then run the following command：
 
```
dotnet ef migrations add md2
```
<img src="https://raw.githubusercontent.com/JackLovel/excuise-/master/office_csharp_code/img/ContosoUniversityError1.png"  />
<img src="https://raw.githubusercontent.com/JackLovel/excuise-/master/office_csharp_code/img/ContosoUniversityError2.png"  />

## attempt
```
The addition of the [NotMapped] attribute to Budget 
in the Department.cs file was successful, 
but the Department table in the database had no Budget field.
```

**Comment by Rick-Anderson** [comment]
Per @tdykstra 
a note about MySQL in the tutorial at the point the attributes are added, with no change to the sample app would be best.

**Comment by JackLovel** [comment]
> Per @tdykstra
> a note about MySQL in the tutorial at the point the attributes are added, with no change to the sample app would be best.

thank reply me
