### ISSUE TITLE
Strongly recommend providing a link to documentation for MvcJsonOptions.AllowInputFormatterExceptionMessages

### ISSUE THREAD

**Issue by APIWT** [aspnet/AspNetCore.Docs#12267]
I think it would be extremely beneficial to provide a link to the following page in this article: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcjsonoptions.allowinputformatterexceptionmessages?view=aspnetcore-2.2

My team and I are currently working on a project that was flagged during a security scan for a potential XSS vulnerability in our Web API. This was due to the exception messages that are generated by Newtonsoft during the model binding pipeline. In our case, the field that was raising the flag was a DateTimeOffset. Our security testing team had posted a script tag into the field and the response from the server contained the following message:
```
{
    "errors": {
        "datetime": [
            "Could not convert string to DateTimeOffset: <script>hey!</script>. Path 'datetime', line 1, position 47."
        ]
    },
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "0HLMF4A7SK4GI:00000001"
}
```

After several days of searching, we were able to suppress this message by adding the following to `ConfigureServices`:
```
services
    .AddMvc()
    .AddJsonOptions(options => options.AllowInputFormatterExceptionMessages = false)
```

I hope this helps someone in the future reading this page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by APIWT** [comment]
@Rick-Anderson Have you had a chance to look at this? Thanks!

**Comment by Rick-Anderson** [comment]
@JamesNK is this an urgent security issue or can it wait for your teams next docathon?

**Comment by JamesNK** [comment]
I don't know. Returning a script tag in JSON doesn't seem insecure to me, since it should be encoded before it is set to any HTML. Check with @blowdart

**Comment by APIWT** [comment]
It is insecure as a default behavior in my opinion. I realize that the client should encode it before rendering but this seems like it could be opt-out rather than opt-in to make it more secure for the majority of use cases.

**Comment by blowdart** [comment]
I agree with both of you, the returning view/service should be encoding, but developers may not think to encode by default. If the mime type is correct though, i.e. the json mime type then there's nothing for us to do here, as the mime type would prevent XSS.

**Comment by APIWT** [comment]
I'm torn @blowdart and @JamesNK 
I understand both your perspectives since JSON is simply designed to serialize data. There is no responsibility for the server to automatically encode anything inside the JSON so I think we 100% agree on this point.
What I don't like is the fact that the default for `AllowInputFormatterExceptionMessages` is true in the current version (and presumably future versions) of .NET core. At the very least, I think it would be beneficial to the community to put something on the XSS article about this option. Even with a mime type of `application/json`, security scans pick up on this type of false positive all the time. In fact, we run two different pen testing tools and both caught this "potential vulnerability". Originally, I went the route of explaining to the security team that these were in-fact false positives. I've gone through the same headache twice now with separate issues since pen testing tools raise many false positives through a sort of narrow approach at detecting issues (don't get me wrong, they can also catch real issues but they often detect stuff that is perfectly safe).

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
