### ISSUE TITLE
Invalid instruction

### ISSUE THREAD

**Issue by axa88** [aspnet/AspNetCore.Docs#12268]
Item 3.3 seems invalid.
There no longer seems to be a check box to use previews of the .NET Core SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @axa88 ...

<img width="451" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57158501-35249000-6da9-11e9-905c-99aa588bc352.PNG">

Are you using the preview version of VS? If so, that would explain it because the preview version of VS always uses preview SDKs by default.

**Comment by guardrex** [comment]
I'm going to make that say that if a non-preview version is in use to enable the setting.
