### ISSUE TITLE
AddDefaultIdentity configuration

### ISSUE THREAD

**Issue by omrumbakitemiz** [aspnet/AspNetCore.Docs#12264]
Seems like services.AddDefaultIdentity() extension method was removed from api. When i try to use AddIdentity() method, it wants me TUser and TRole types. I don't know which method is right to use. There may be some more documentation about the identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
`dotnet --list-sdks`
`3.0.100-preview5-011568`

Create a web app with Individual user accounts and it works and uses `AddDefaultIdentity`

**Comment by Rick-Anderson** [comment]
```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        // This lambda determines whether user consent for non-essential cookies 
        // is needed for a given request.
        options.CheckConsentNeeded = context => true;
    });

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>()
        .AddEntityFrameworkStores<ApplicationDbContext>();

    services.AddRazorPages()
        .AddNewtonsoftJson();
}
```

**Comment by omrumbakitemiz** [comment]
I created a new project with new preview sdk in visual studio, i choose individual authentication. Visual Studio added  `"Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview5-19227-01"` dependency to csproj file. I added same dependency to my main project and I think it will solve my problem. Thank you  😇

**Comment by Rick-Anderson** [comment]
@omrumbakitemiz  you don't need to add `Microsoft.AspNetCore.Identity.UI`

**Comment by Rick-Anderson** [comment]
```
dotnet new webapp -o aspnetcoreapp -au Individual  -uld
cd aspnetcoreapp 
dotnet run
```

**Comment by omrumbakitemiz** [comment]
I think i am missing something. When i remove the dependency from csproj file i am getting error.
By the way my project is a web api. I don't have any ui. 

<img width="326" alt="Screen Shot 2019-05-10 at 15 12 42" src="https://user-images.githubusercontent.com/12871066/57526430-13da1b80-7336-11e9-9290-84e34eb484b7.png">
