### ISSUE TITLE
Missing step under 'Changes to Razor Pages projects Razor files'

### ISSUE THREAD

**Issue by mcalasa** [aspnet/AspNetCore.Docs#12280]
It may be helpful for other people migrating their projects to add this step 
'Add In Areas/Identity/Pages/_ViewStart.cshtml change Layout = "/Pages/_Layout.cshtml"; to Layout = "/Pages/Shared/_Layout.cshtml";'  after this line ''Move Pages/_Layout.cshtml to Pages/Shared/_Layout.cshtml'

I ran into an issue in that if you forget to change the layout path in _ViewStart.cshtml you will get a 404 error when trying to navigate to a page that uses the [Authorize] attribute and the user has not entered in their user credentials.  By adding the correct path, the user will be presented with the login page.

I can create a PR if needed.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mcalasa thanks. I'll create the PR and have you review it.

**Comment by mcalasa** [comment]
@Rick-Anderson Excellent, I'll keep an eye out for it.

**Comment by Rick-Anderson** [comment]
@mcalasa  can you create the PR? I uninstalled the 2.0 SDK and it's no longer available to download.

**Comment by mcalasa** [comment]
@Rick-Anderson Sure, just to be sure we are on the same page, I will create a PR of this article.  Is that correct?

**Comment by Rick-Anderson** [comment]
@mcalasa  correct.

**Comment by Rick-Anderson** [comment]
@mcalasa need any help creating the PR? 
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
