### ISSUE TITLE
SignalR Samples hubcontext _ missing SignalR JS-Library

### ISSUE THREAD

**Issue by Mikelsoft99** [aspnet/AspNetCore.Docs#12281]
In the samples: SignalR/Hubcontext

In the **Views/Home/Notify.cshtml** there is the **/lib/signalr/signalr.js** included.
But in the sample this file is missing.

Couldn't not create a pull request.

Thanks Mike

**Comment by scottaddie** [comment]
@Mikelsoft99 The sample currently relies on the npm registry for retrieval of *signalr.js*. You'd have to run `npm i` in the project root to get the file. This, of course, assumes you have both Node.js and npm installed.

@bradygaster Do we want to adopt LibMan and/or cdnjs to remove the Node & npm requirement in SignalR sample apps?

**Comment by Mikelsoft99** [comment]
Hey @scottaddie , thanks for your answer. But this doesn't work either I think. In the View file you are referencing the wwwroot-Folder. If I run the npm i everything goes to the node_modules folder - so the script referencing in the view-file is still missing.

I think this example won't work written like this.

Thanks Mike

**Comment by scottaddie** [comment]
@Mikelsoft99 There's a custom MSBuild target in the *.csproj file that copies from *node_modules* to *wwwroot*. You have to build the project to trigger that task.

```xml
  <Target Name="CopySignalR" BeforeTargets="AfterBuild">
    <ItemGroup>
      <SignalRJSClientFiles Include="$(MSBuildThisFileDirectory)node_modules\@aspnet\signalr\dist\browser\*" />
    </ItemGroup>
    <Copy SourceFiles="@(SignalRJSClientFiles)" DestinationFolder="$(MSBuildThisFileDirectory)wwwroot\lib\signalr" />
  </Target>
```

**Comment by bradygaster** [comment]
We like the idea of using the cdnjs option here. cc @scottaddie
