### ISSUE TITLE
Requires database

### ISSUE THREAD

**Issue by elvan11** [aspnet/AspNetCore.Docs#12293]
It does not say anything about a required database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by losmac** [comment]
It can be any database... For example: Azure, SQL Server, PostgreSQL, MySQL, Oracle, etc.
For further details, please, see: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-2.2)

**Comment by APIWT** [comment]
If I understand correctly, @elvan11 is simply pointing out that it would be good to mention that it requires _some_ database (not a specific database).

**Comment by guardrex** [comment]
In addition to the topic that @losmac linked, there's a sample app with https://docs.microsoft.com/aspnet/core/security/authentication/social/additional-claims that uses Google and stores additional claims from Google for users. That sample uses an in-memory database, which can be swapped out for a real one. **NOTE**: We just made major updates to that tho. They're on a PR at https://github.com/aspnet/AspNetCore.Docs/pull/11950 ... either look at the PR or wait for us to merge it. If you decide to wait until the updates go live: The current date on the live topic is 11/10/2018. After the updates on the PR go live, the date will be 4/21/2019 (or later if I submit more commits to that PR).

Note on the tabs at https://docs.microsoft.com/aspnet/core/security/authentication/social/#create-a-new-aspnet-core-project ... The VS tab has the app with Individual User Accounts, but the VSC and VS4Mac CLI commands don't have the `--auth Individual` option.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
