### ISSUE TITLE
Remove RuntimeFrameworkVersion to fix "You must add a reference to assembly netstandard, Version=2.0.0.0"

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore.Docs#12294]
Hello - I'm trying to upgrade a project from 1.1 to 2.0 and I'm getting:

> You must add a reference to assembly netstandard, Version=2.0.0.0

Through some googling [I found this](https://github.com/dotnet/core/issues/860#issuecomment-323242286): 

> I have a similar problem, and I remove the RuntimeFrameworkVersion, and the problem was fixed.

And that seems to have fixed it for me.  Should this be in this guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c61fe9-3c62-e4fe-6883-feb0b2f6eb10
* Version Independent ID: c1e227c3-2c14-be3e-21de-af93aacfb002
* Content: [Migrate from ASP.NET Core 1.x to 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/1x-to-2x/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/1x-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
You're saying
```
<TargetFramework>netcoreapp2.0</TargetFramework>
```

doesn't work?

**Comment by spottedmahn** [comment]
Hi Rick - no, I'm saying the 'red box' has to be removed:

![image](https://user-images.githubusercontent.com/14079228/57324387-b5166700-70d5-11e9-9e7f-37d31aecc1d0.png)

Changing the 'purple box' as described in the guide works just fine.

**Comment by Rick-Anderson** [comment]
@spottedmahn  see #12320
