### ISSUE TITLE
Missing tooling instructions

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12290]
There are some missing tooling instructions when VSC/macOS tabs are selected. https://docs.microsoft.com/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#initial-migration

<img width="370" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57195224-c57fe380-6f15-11e9-9b49-3c1c9898f04b.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  nothing is missing. I could add 
"this is blank because this only applies to VS".
