### ISSUE TITLE
Automatic paramters added in Swagger produced documentation.

### ISSUE THREAD

**Issue by zefirin** [aspnet/AspNetCore.Docs#12304]
Hello,

I followed this Swashbuckle and ASP.NET Core tutorial and my automated doc is working to a charm.
The only issue I found is that for any API controller routes that includes at least two parameters with the attribute [FromRoute], the according swagger entry generated will have all the same unwanted parameters flagged as required:

Timestamp *
integer($int32)
(path)	

Machine *
integer($int32)
(path)	

Pid *
integer($int32)
(path)	

Increment *
integer($int32)
(path)	

CreationTime *
string($date-time)
(path)

I have searched for a way to prevent their presence in the doc but I can't find anything in the Swagger settings.

Jonthan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16195
