### ISSUE TITLE
directory was wrong in the launch.json file

### ISSUE THREAD

**Issue by gitSushi** [aspnet/AspNetCore.Docs#12312]
using VSC, at the 'run without the debugger' step, my RazorPagesMovie.dll file was saved in the "program": "${workspaceFolder}/bin/MCD/Debug/netcoreapp2.2/RazorPagesMovie.dll" directory.
But in the launch.json file it was looking for it in the "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/RazorPagesMovie.dll"
I thought I should share it if others were facing the same problem because the alert window will say it is missing the .dll file which is slightly incorrect, it is only 'misplaced'. :)

**Dup** of #12136

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@gitSushi Can you please provide the following pieces of info to aid in troubleshooting?

1. Which version of the C# extension are you using in VS Code?
2. What do you see when you run `dotnet --version` in this project's directory?
