### ISSUE TITLE
MetadataReferenceFeature is obsolete: (https://aka.ms/AA1x4gg)

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#12316]
Hi team,
I'm moving this from here: https://github.com/aspnet/AspNetCore.Docs.de-de/issues/38
The user is reporting obsolete content in the code box.

@cyberh0me commented:
please could you update the FeaturesController sample accordingly

See https://github.com/aspnet/Announcements/issues/312

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/Announcements/issues/312

**Comment by Rick-Anderson** [comment]
@serpent5 this looks like an easy one.

**Comment by serpent5** [comment]
@Rick-Anderson Removing the code references looks simple enough, but the sample and corresponding code snippets are all ASP.NET Core 2.0 and the screenshot would also need to be updated (or dropped?). What would you like me to do?

**Comment by Rick-Anderson** [comment]
Delete the screen shot.
