### ISSUE TITLE
Globalization and localization doc not friendly to Visual Studio Code, VS Mac, or linux

### ISSUE THREAD

**Issue by 1arrywei** [aspnet/AspNetCore.Docs#12310]
It's not friendly to Visual Studio Code, It seems difficult to use resx file in the VSCode, and I don't know what to do when I want to make a .net core mvc project Globalization and localization in ubuntu use VSCode, a  extension is necessary maybe, is there anyone in the same boat as me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DamianEdwards  do we have plans to support localization in VS Code and VS Mac?

**Comment by hishamco** [comment]
@Rick-Anderson this is a duplicate for #2501
