### ISSUE TITLE
Usage of lambda symbol in the "RequestSetOptionsStartupFilter" class

### ISSUE THREAD

**Issue by eJamesLee** [aspnet/AspNetCore.Docs#12328]
This appears to be an expression bodied method given the usage of the lambda symbol, where an expression would return the method's expected return type, which in this case would be a IApplicationBuilder.  Assuming this is the correct intention, the potential issue is that expression bodied methods are limited to one expression, with no 'return' statement.  Can you please clarify?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@eJamesLee Why is that an issue?

**Comment by eJamesLee** [comment]
Hi @tdykstra.  So according to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members#methods, the supported usage would be more like:  public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next) => builder.UseMiddleware<RequestSetOptionsMiddleware>();  But instead, there is a also a return statement, along with another statement (next(builder)) in the body.  Is this also supported as well?

**Comment by tdykstra** [comment]
The method as it stands is not an expression-bodied method; it returns a lambda, an `Action<IApplicationBuilder>`, that contains two statements:

```
builder.UseMiddleware<RequestSetOptionsMiddleware>();
next(builder);
```

It could be written as an expression bodied member that returns the lambda:

```
public class RequestSetOptionsStartupFilter : IStartupFilter
{
    public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
        => builder =>
        {
            builder.UseMiddleware<RequestSetOptionsMiddleware>();
            next(builder);
        };
}
```
That would work, but to me the original looks better / is easier to understand.

**Comment by eJamesLee** [comment]
Thank you for the thorough response Tom.  I quickly realized how I over-thought this, but also to become aware of what is allowable (e.g. expression body then with a lambda) but is not preferable.  Appreciate the complete answer, and agree with your conclusion.
