### ISSUE TITLE
Alternative for setting request timeouts for in-process hosting

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12330]
From @effyteva on #5449 ...

> As "ANCM: RequestTimeout doesn't apply to inProcess aspnet/IISIntegration#555",

> What's the recommended alternative for setting request timeouts when using in process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#attributes-of-the-aspnetcore-element)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by effyteva** [comment]
Thank you @guardrex guardrex
I've actually kept digging, and figured out it's even a bit worse than I expected.
I tried switching to OutOfProcess, in which this parameter partially works - the request is aborted and the client gets a error page ("The specified CGI application encountered an error and the server terminated the process.")
However, the server keeps processing infinitely.

Re-producing is very easy, I created a view, with a "while (true) { }" loop in it.
I couldn't get it to abort after any kind of timeout setting.

**Comment by guardrex** [comment]
Yes, and your experience matches what engineering said on that issue ...

> The in-proc corollary is waiting for the application to process the request.

Since any app can *just swallow the request* and we don't address that scenario anywhere in the docs as far as I know, you ask a great question. What we need to do on this issue is mark it for the Product Unit ("PU" label) so that they can tell us what they think about an alternative.

Now that Preview4 is out, I think (*hope*) that they'll look at this soon. I'll take their guidance and enhance that remark in the topic. We should at the very least say what engineering said: The app is left to process the request without a timeout by IIS/ANCM.

**Comment by effyteva** [comment]
Thanks, I highly appreciate your quick and detailed responses.
Let's see what the Product Units team comes up with, hopefully there's a simple and effective way to abort these abandons requests.

**Comment by guardrex** [comment]
This is *old* but interesting ... might lead to some newer info or an approach.

https://github.com/aspnet/KestrelHttpServer/issues/611

**Comment by effyteva** [comment]
> This is _old_ but interesting ... might lead to some newer info or an approach.
> 
> [aspnet/KestrelHttpServer#611](https://github.com/aspnet/KestrelHttpServer/issues/611)

Sadly it's related to ASP.NET and not ASP.NET Core.
The Server property doesn't exist anymore.

**Comment by guardrex** [comment]
Kestrel is the server in that scenario, so they're discussing how it would work with Core.

**Comment by guardrex** [comment]
Ben has an "execution timeout" ... I'll track that down and see if it went in.

**Comment by guardrex** [comment]
Doesn't look like it ... https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits

**Comment by guardrex** [comment]
... and here's why ... https://github.com/aspnet/KestrelHttpServer/pull/485#discussion_r55264843

**Comment by guardrex** [comment]
Closing. See: https://github.com/aspnet/AspNetCore/issues/10079
