### ISSUE TITLE
Unable to install Prerequisites mentioned in the NOTE OS before Win10

### ISSUE THREAD

**Issue by scottluskcis** [aspnet/AspNetCore.Docs#12332]
# Issue description

Unable to install Prerequisites mentioned in the NOTE in the [Host ASP.NET Core in a Windows Service - Prerequisites](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#prerequisites)  

In the NOTE it says anything before Windows 10 that the [Microsoft.PowerShell.LocalAccounts](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/?view=powershell-5.1) must be installed. 

I open a PowerShell window as administrator and try the following commands as noted on the doc page

```powershell
Install-Module WindowsCompatibility -Scope CurrentUser
Import-WinModule Microsoft.PowerShell.LocalAccounts
```

The first command succeeds but the `Import-WinModule` command fails with this error

```powershell
PS C:\Users\MyUser> Import-WinModule Microsoft.PowerShell.LocalAccounts
New-PSSession : [localhost] Connecting to remote server localhost failed with th
e following error message : The client cannot connect to the destination specifi
ed in the request. Verify that the service on the destination is running and is
accepting requests. Consult the logs and documentation for the WS-Management ser
vice running on the destination, most commonly IIS or WinRM. If the destination
is the WinRM service, run the following command on the destination to analyze an
d configure the WinRM service: "winrm quickconfig". For more information, see th
e about_Remote_Troubleshooting Help topic.
At C:\Users\MyUser\Documents\PowerShell\Modules\WindowsCompatibility\1.0.0\Wi
ndowsCompatibility.psm1:232 char:20
+         $session = New-PSSession @newPSSessionParameters | Select-Obj ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Management.A\u2026tion.RemoteRunspa
ce:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : CannotConnect,PSSessionOpenFailed

```

I am trying this on Windows 8.1 Enterprise for example. Are there any additional steps that need to be mentioned in the NOTE? 

I have been able to follow everything on the doc successfully on Windows 10 and I was successful using the older version of the doc before the `New-LocalUser` approach was added. Thanks for any input regarding this. 

# Software versions

PowerShell 6.2
Windows 8.1 Enterprise

**Comment by guardrex** [comment]
@scottluskcis Sorry you hit that.

@rjmholt You helped me with that on ...

https://github.com/aspnet/AspNetCore.Docs/pull/11839#discussion_r272353519

As I reread your remarks, I think you're saying that I shouldn't have ...

```powershell
Import-WinModule Microsoft.PowerShell.LocalAccounts
```

... in the note. You remarked ...

> No note needed for PowerShell versions, but older Windows versions have a Microsoft.PowerShell.LocalAccounts version that's not compatible with PowerShell Core.
>
> Instead you need to use the WindowsCompatibility module (or just use Windows PowerShell)


The note is at ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service#prerequisites

**Comment by guardrex** [comment]
@scottluskcis Is the `New-LocalUser` command available on that Win8 machine now? If so, it implies that I'll just need to remove that 2nd line from the NOTE.

**Comment by scottluskcis** [comment]
@guardrex it seems it is NOT available. Calling `New-LocalUser -Name Foo` for example just gives the message `New-LocalUser : The term 'New-LocalUser' is not recognized as the name of a cmdlet, function, script file, or operable program.` message

**Comment by guardrex** [comment]
Ok ... thx. Robert will explain what I missed when he comes on. The update was a little bit 😵 on that point with the PS and Windows version combinations. Although ... I looked a little further down that PR, and he did see the NOTE and suggest a change ...

https://github.com/aspnet/AspNetCore.Docs/pull/11839#discussion_r272356227

Anywho ... *Stand-By* ... we'll get it sorted out asap for you.

**Comment by scottluskcis** [comment]
Thanks for the support @guardrex, much appreciated!

**Comment by rjmholt** [comment]
I think it's better just to do this:

```powershell
powershell -Command "New-LocalUser -Name $UserName"
```

---

### Warning: Unnecessary details follow

The reason is that the `Microsoft.PowerShell.LocalAccounts` comes with **Windows** and isn't part of PowerShell 6.2. On versions of Windows before the 2018 October Update, that module isn't compatible with PowerShell 6.2. So PowerShell 6.2 won't be able to load it directly.

Instead the approach in the docs here recommends the [WindowsCompatibility module](https://github.com/PowerShell/WindowsCompatibility) to use Windows PowerShell to load the module (this uses PowerShell remoting under the hood, which is why the error message refers to "localhost" and WinRM).

I think instead it's easier to just say `powershell -Command "New-LocalUser -Name $UserName"`.

On Windows 10 2018 October Update and later, `Microsoft.PowerShell.LocalAccounts` is compatible, so you don't need to do this, just `New-LocalUser -Name $UserName` in PowerShell 6.2.

**Comment by guardrex** [comment]
Thanks @rjmholt .... so go with .....

* Drop the NOTE completely.

* Go with something like ...

Create a user account for the service using the \[New-LocalUser](/powershell/module/microsoft.powershell.localaccounts/new-localuser) cmdlet from an administrative PowerShell 6 command shell.

On Windows OS earlier than the Windows 10 October 2018 Update (version 1809/build 10.0.17763):

\`\`\`console
powershell -Command "New-LocalUser -Name {NAME}"
\`\`\`

On Windows 10 October 2018 Update (version 1809/build 10.0.17763) or later:

\`\`\`PowerShell
New-LocalUser -Name {NAME}
\`\`\`

Provide a \[strong password](/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements) when prompted.

For the sample app, create a user account with the name ServiceUser.

On Windows OS earlier than the Windows 10 October 2018 Update (version 1809/build 10.0.17763):

\`\`\`console
powershell -Command "New-LocalUser -Name ServiceUser"
\`\`\`

On Windows 10 October 2018 Update (version 1809/build 10.0.17763) or later:

\`\`\`PowerShell
New-LocalUser -Name ServiceUser
\`\`\`

**Comment by scottluskcis** [comment]
@rjmholt @guardrex just tried this on the Windows 8.1 machine still with no luck. I opened just a command prompt and tried 

```console
powershell -Command "New-LocalUser -Name MyTestUser"
```

I still get an error about New-LocalUser is missing though. Perhaps I'm still missing something? This is on a VM, I've tried it on a few different machines other than just mine with the same results for Windows 8.1. 

On a separate note, I have a single PowerShell (ps1) script that I wrote that combined all the steps from the doc. There's no way to run a command in PowerShell?

**Comment by rjmholt** [comment]
Yeah I think that's the best way

**Comment by rjmholt** [comment]
@scottluskcis In Windows PowerShell can you please report the output of the following:

```powershell
$PSVersionTable

gmo -list Microsoft.PowerShell.*

gcm New-LocalUser
```

**Comment by rjmholt** [comment]
> On a separate note, I have a single PowerShell (ps1) script that I wrote that combined all the steps from the doc. There's no way to run a command in PowerShell?

What do you mean by `command` here?

**Comment by scottluskcis** [comment]
> 
> 
> @scottluskcis In Windows PowerShell can you please report the output of the following:
> 
> ```powershell
> $PSVersionTable
> 
> gmo -list Microsoft.PowerShell.*
> 
> gcm New-LocalUser
> ```

@rjmholt here is the output from the above

```powershell
PowerShell 6.2.0

Copyright (c) Microsoft Corporation. All rights reserved.


 


https://aka.ms/pscore6-docs

Type 'help' to get help.


 


PS C:\Users\MyUser> $PSVersionTable

>>

>> gmo -list Microsoft.PowerShell.*

>>

>> gcm New-LocalUser


 


Name                           Value

----                           -----

PSVersion                      6.2.0

PSEdition                      Core

GitCommitId                    6.2.0

OS                             Microsoft Windows 6.3.9600

Platform                       Win32NT

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1

WSManStackVersion              3.0


 


Name              : Microsoft.PowerShell.Archive

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Archive\Microsoft.PowerShell.Archive.psd1

Description       : PowerShell module for working with ZIP archives.

Guid              : eb74e8da-9ae2-482a-a648-e96550fb8733

Version           : 1.2.2.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Archive

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {}

ExportedCmdlets   : {}

ExportedFunctions : {[Compress-Archive, Compress-Archive], [Expand-Archive,

                    Expand-Archive]}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.Archive}


 




Name              : Microsoft.PowerShell.Diagnostics

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Diagnostics\Microsoft.PowerShell.Diagnostics.psd1

Description       :

Guid              : ca046f10-ca64-4740-8ff9-2565dba61a4f

Version           : 6.1.0.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Diagnostics

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {}

ExportedCmdlets   : {[Get-WinEvent, Get-WinEvent], [New-WinEvent,

                    New-WinEvent]}

ExportedFunctions : {}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.Commands.Diagnostics}


 




Name              : Microsoft.PowerShell.Host

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Host\Microsoft.PowerShell.Host.psd1

Description       :

Guid              : 56d66100-99a0-4ffc-a12d-eee9a6718aef

Version           : 6.1.0.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Host

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {}

ExportedCmdlets   : {[Start-Transcript, Start-Transcript], [Stop-Transcript,

                    Stop-Transcript]}

ExportedFunctions : {}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.ConsoleHost}


 




Name              : Microsoft.PowerShell.Management

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Management\Microsoft.PowerShell.Management.psd1

Description       :

Guid              : eefcb906-b326-4e99-9f54-8b4bb6ef3c6d

Version           : 6.1.0.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Management

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {[gin, gin], [gtz, gtz], [stz, stz]}

ExportedCmdlets   : {[Add-Content, Add-Content], [Clear-Content,

                    Clear-Content], [Clear-ItemProperty, Clear-ItemProperty],

                    [Join-Path, Join-Path].}

ExportedFunctions : {}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.Commands.Management}


 




Name              : Microsoft.PowerShell.Security

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Security\Microsoft.PowerShell.Security.psd1

Description       :

Guid              : a94c8c7e-9810-47c0-b8af-65089c13a35a

Version           : 6.1.0.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Security

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {}

ExportedCmdlets   : {[Get-Acl, Get-Acl], [Set-Acl, Set-Acl],

                    [Get-PfxCertificate, Get-PfxCertificate], [Get-Credential,

                    Get-Credential].}

ExportedFunctions : {}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.Security}


 




Name              : Microsoft.PowerShell.Utility

Path              : C:\program files\powershell\6\Modules\Microsoft.PowerShell.

                    Utility\Microsoft.PowerShell.Utility.psd1

Description       :

Guid              : 1da87e53-152b-403e-98dc-74d7b4d63d59

Version           : 6.1.0.0

ModuleBase        : C:\program

                    files\powershell\6\Modules\Microsoft.PowerShell.Utility

ModuleType        : Manifest

PrivateData       :

AccessMode        : ReadWrite

ExportedAliases   : {[fhx, fhx]}

ExportedCmdlets   : {[Export-Alias, Export-Alias], [Get-Alias, Get-Alias],

                    [Import-Alias, Import-Alias], [New-Alias, New-Alias].}

ExportedFunctions : {}

ExportedVariables : {}

NestedModules     : {Microsoft.PowerShell.Commands.Utility}


 


gcm : The term 'New-LocalUser' is not recognized as the name of a cmdlet, functi

on, script file, or operable program.

Check the spelling of the name, or if a path was included, verify that the path

is correct and try again.

At line:5 char:1

+ gcm New-LocalUser

+ ~~~~~~~~~~~~~~~~~

+ CategoryInfo          : ObjectNotFound: (New-LocalUser:String) [Get-Command],

CommandNotFoundException

+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands

.GetCommandCommand


 




PS C:\Users\MyUser>
```

**Comment by rjmholt** [comment]
@scottluskcis can you get that output in Windows PowerShell, the `powershell.exe` on your machine (not sure if it's 5.1, 4 or 3)

**Comment by rjmholt** [comment]
Looking at [the documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/?view=powershell-5.1&viewFallbackFrom=powershell-4.0)

The Microsoft.PowerShell.LocalAccounts module may not exist before Windows 10.

In that case, I think the `net user` command is best

**Comment by guardrex** [comment]
Looks like I should put the `net user` command there for versions prior to Win10 that you called out and delete the NOTE.

**Comment by scottluskcis** [comment]
@rjmholt , regards to this

> What do you mean by `command` here? Things like `Get-Module` and `New-LocalUser` are commands, as is `net user bryan password /add`

The [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2) doc walks through running the commands individually (Create a user account, Set permission, Create the service, etc). I created a script and when deploying have instructions to just run the script. My comment was I'm trying to run a PowerShell script that does all steps instead of one at a time like the doc does a great job of walking thru

**Comment by scottluskcis** [comment]
@rjmholt @guardrex, so since I have the need to run this on older OS than Win10 the recommendation is I should switch back to using `net user` for the user creation part instead of `New-LocalUser`? Appreciate all of the feedback here

**Comment by rjmholt** [comment]
@guardrex 
> Looks like I should put the net user command there for versions prior to Win10 that you called out and delete the NOTE.

Yeah I think that's the way to go. The current docs depend on Windows PowerShell 5.1 being installed alongside PowerShell 6.2. We can ignore the Windows version entirely with `net user`. Otherwise it gets complicated due to Windows PowerShell compatibility. Is there a compelling reason to want to use `New-LocalUser`?

**Comment by guardrex** [comment]
Only that readers have asked multiple times (for whatever reason) to make the entire process as PowerShell-y as possible. Since I'll only be saying to use `net user` prior to Windows 10 October 2018 Update (version 1809/build 10.0.17763), we should be ok.

I'll ping both of you on the PR .... probably get to it tommorrow (Thursday) ..... *maybe* 🤞🍀

**Comment by scottluskcis** [comment]
@rjmholt That's the same reason I've seen from those I've spoken to as well, the request to be more "PowerShell-y" as possible :). I'm good with going with `net user` I had that approach prior and noticed the updates to the doc and thought someone had a compelling reason for it and I liked being able to use the module. If I only had to support Win10 I would stick with it but I have the need for Win7 and Win8. 

@guardrex Appreciate the update to the docs, I've shared the doc with several clients and colleagues and linking to it in a Medium article I'm working on as well.

**Comment by rjmholt** [comment]
Speaking to @SteveL-MSFT, `net user` is going to work in all cases -- I think trying to use `New-LocalUser` complicates things a lot while Win 7 and Win 8.1 need to be considered. PowerShell is a shell after all; `net user ...` is still PowerShell-y.

**Comment by guardrex** [comment]
Sounds good.

FYI, too ...... an issue coming up *very soon* for me is to refactor the topic + sample to use the [Generic Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host), which will be recommended for 3.0+. Keep an :eye: on the live topic .... say .... er .... a month or two down the road. The docs version drop down will still default to 2.2 until 3.0 reaches RTM (later this year), but when you set the drop down to "3.0 Preview," you'll get this updated doc that will go with the Generic Host. I'll get on that asap ... I think within May ... but for sure by the end of June.

**Comment by rjmholt** [comment]
Also @scottluskcis creating a script for this makes perfect sense to me. Maybe something like this:

```powershell
#requires -Version 6.2
#requires -RunAsAdministrator

param(
    [Parameter(Mandatory)]
    [string]
    $ServiceName,

    [Parameter(Mandatory)]
    [string]
    $PublishPath,

    [Parameter(Mandatory)]
    [string]
    $ExePath,

    [Parameter(Mandatory)]
    [string]
    $ServiceUserName,

    [Parameter(Mandatory)]
    [string]
    $ServiceUserDomain,

    [Parameter(Mandatory)]
    [string]
    $ServiceUserPassword,

    [Parameter()]
    [string]
    $DisplayName = $Name,

    [Parameter()]
    [string]
    $Description = '',

    [Parameter()]
    [string]
    $AppSrcPath = (Get-Location),

    [Parameter()]
    [ValidateSet('W','R','X','F','M')]
    [string[]]
    $ServicePermissions = 'R'
)

function Exec
{
    param([Parameter(Position=0)][scriptblock]$Invocation)

    & $Invocation

    # note, if $Invocation doesn't have a native invocation, $LASTEXITCODE will
    # point to the obsolete value
    if ($LASTEXITCODE -ne 0)
    {
        # Get caller location for easier debugging
        $caller = Get-PSCallStack -ErrorAction SilentlyContinue
        if($caller)
        {
            $callerLocationParts = $caller[1].Location -split ":\s*line\s*"
            $callerFile = $callerLocationParts[0]
            $callerLine = $callerLocationParts[1]

            $errorMessage = "Execution of {$sb} by ${callerFile}: line $callerLine failed with exit code $LASTEXITCODE"
            throw $errorMessage
        }
        throw "Execution of {$sb} failed with exit code $LASTEXITCODE"
    }
}

function Register-Service
{
    param(
        [Parameter(mandatory=$true)]
        [string]
        $ServiceName,
        [Parameter(mandatory=$true)]
        [string]
        $DisplayName,
        [Parameter(mandatory=$true)]
        [string]
        $Description,
        [Parameter(mandatory=$true)]
        [System.IO.FileInfo]
        $Exe,
        [Parameter(mandatory=$true)]
        [string]
        $User
    )

    $acl = Get-Acl $($Exe.DirectoryName)
    $aclRuleArgs = $User, "Read,Write,ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow"
    $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($aclRuleArgs)
    $acl.SetAccessRule($accessRule)
    $acl | Set-Acl $($Exe.DirectoryName)

    New-Service -Name $ServiceName -BinaryPathName $($Exe.FullName) -Credential $User -Description $Description -DisplayName $DisplayName -StartupType Automatic
}

$ErrorActionPreference = 'Stop'

# Publish app
Push-Location $AppSrcPath
try
{
    Exec { dotnet publish --configuration Release --output $PublishPath }
}
finally
{
    Pop-Location
}

# Create a service user
Exec { net user $ServiceUserName $ServiceUserPassword /add }

# Set the permissions
$perms = $ServicePermissions -join ''
Exec { icacls $PublishPath /grant "${ServiceUserName}:(OI)(CI)$perms" /t }

# Create the service
$serviceParams = @{
    ServiceName = $ServiceName
    DisplayName = $DisplayName
    Description = $Description
    Exe = (Join-Path $PublishPath $ExePath)
    User = "$ServiceUserDomain\$ServiceUserName"
}
Register-Service @serviceParams

# Start the service
Start-Service -Name $ServiceName

```

(Haven't tried it)

**Comment by scottluskcis** [comment]
@rjmholt , thanks for sharing, yes that is very similar to the script I put together. I like your approach, I'll have to revisit mine to see if I need to tweak anything a bit. Thanks again for sharing this
