### ISSUE TITLE
Incorrect line highlight for PreserveCompilationReferences

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#12331]
`PreserveCompilationReferences` should be highlighted, rather than `TargetFramework`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Let me know if you want me to PR this one.

**Comment by guardrex** [comment]
Yes, please do @serpent5 ... we're always 🏃🏃🏃🏃😅 and *greatly appreciate your help!* :rocket:

... and you can put a colon (`:`) at the end of the sentence that leads into that code example.
