### ISSUE TITLE
Blazor Javascript Files

### ISSUE THREAD

**Issue by mike1o1** [aspnet/AspNetCore.Docs#12358]
The documentation states that for server-side Blazor, the javascript files will be located in "bin/{Debug|Release}/{TARGET FRAMEWORK}/publish/{APPLICATION NAME}.App/dist/_framework" however that doesn't seem to be correct as I don't see the files there.

It would be great if this file can be published on npm so that it can be included with a webpack build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mike1o1 ... The 🧀 moved on that back for Preview 2, but we didn't get it into the docs. Thanks for letting me know. I'll take care of it.

> We no longer need to load `blazor.server.js` from the client app project, because it's now served directly from an embedded resource in `.Components.Server` middleware.

https://github.com/aspnet/AspNetCore/pull/6562

**Comment by guardrex** [comment]
@mike1o1 WRT ...

> It would be great if this file can be published on npm so that it can be included with a webpack build.

That's engineering feedback, so you should open that suggestion over on the [aspnet.AspNetCore repo issues](https://github.com/aspnet/AspNetCore/issues) where the engineers will see it.
