### ISSUE TITLE
Fresh install won't start

### ISSUE THREAD

**Issue by andrewleith** [aspnet/AspNetCore.Docs#12351]
I created a brand new project and it won't start.  My VS details:

Microsoft Visual Studio Enterprise 2017
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.03056

When the page loads (IIS express seems to die and the IDE doesn't stay in debug mode) it displays:
HTTP Error 502.5 - Process Failure

Any help would be appreciated.

Thanks,
Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Update to VS 19
Try `dotnet run`
