### ISSUE TITLE
[Request] Official template for JWT auth

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore.Docs#12365]
The current authentication+authorisation template, which uses Identity, is great - but it's for cookies.

Many of us are using Angular/React/Vue. For us, setting up auth is **hard** - not because it can't be done, but because there are no docs, and the cookie docs are completely irrelevant.

There is also repeated advice (everywhere from here to StackOverflow to blogs) to use IdentityServer. That is completely unnecessary. It is not needed for cookies, it is not needed for JWT. *It is overkill for most projects.*

It took me a week to set up auth using JWT, mostly through trial-and-error. It should have taken 10 minutes (that is how long it takes for cookies, because there is a great template for that scenario).

*What is needed is an official example so we can get going quickly without reinventing the wheel.*

---
This is how projects are broken down:
- hobby/simple projects: excellent support for Identity+cookies, lots of templates and examples
- middle-tier projects: no support
- enterprise projects: support via Identity+IdentityServer

I assume most businesses are in the middle. And we shouldn't have to deploy IdentityServer just for auth support.

**Comment by guardrex** [comment]
Hello @lonix1 ... If you're asking for a `dotnet new` template, close here and re-open over on the engineering repo, since we only handle docs on this repo. [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues). The engineers and managers are :ear: listening :ear: over there.

**Comment by lonix1** [comment]
I'm not sure what is best? Right now there's not much at all.

Maybe basic docs would be good (would have helped me), but later a full template would be considered.

I hoped @RickAndMSFT would say whether this could be "backlogged".

**Comment by guardrex** [comment]
Sure ... I wasn't sure what you were asking for. An ask for a template would to to the product unit. An ask for docs does go here.

**Comment by lonix1** [comment]
I'm also not sure what I'm asking for... :stuck_out_tongue:

Maybe both. But lets start with docs, because an official template could thereafter be built on that.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
