### ISSUE TITLE
"Use Gulp" hyperlink issue

### ISSUE THREAD

**Issue by BraveThrasher** [aspnet/AspNetCore.Docs#12364]
The URL for the "Use Gulp" hyperlinks in the first paragraph and the Additional resources section differs from the one for this page but the URL for those hyperlinks gets redirected to this page ("Use Grunt in ASP.NET Core").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3b23da-ff3d-daf6-c56a-2b8ddf79f805
* Version Independent ID: 5ea39e72-fcfc-ddbe-2f4d-f4166dfbe5a8
* Content: [Use Grunt in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/client-side/using-grunt.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/using-grunt.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BraveThrasher ... The topic was just removed on https://github.com/aspnet/AspNetCore.Docs/pull/12360. There are 11 links sprinkled around the docs ... I'll make a pass and get them out. Thanks for letting us know.
