### ISSUE TITLE
Microsoft.AspNet.WebApi.Client package removed from shared framework

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#12370]
Document the impact and update code as necessary. Docs affected:

- [x] [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
- [x] [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2)
- [ ] [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)

**Comment by mkArtakMSFT** [comment]
@scottaddie is anything else left here?

**Comment by scottaddie** [comment]
The remaining work is being tracked in https://github.com/aspnet/AspNetCore.Docs/issues/13353.
