### ISSUE TITLE
What part does index.html play in the layout workflow?

### ISSUE THREAD

**Issue by itanex** [aspnet/AspNetCore.Docs#12379]
I was looking for details about the index.html file which appears to be the root layout file similar to the _layout.cshtml in MVC projects. Does this file behave similarly? How would I go about adding meta tags to the header filled with data from a service.

Scenario:

request &gt; querydb for metadata &gt; add data to viewbag &gt; in _layout.cshtml access viewbag fields &gt; add data to metatags from viewbag

While this scenario is specific to a translation I am working on right now, I do know I have other similar scenarios where I need to modify the _layout.cshtml file based on this same principal. Any details towards the accepted practice would be wonderful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @itanex ... Are you on an older Blazor preview? You want to use the *_Host.cshtml* for that. Here's an example using configuration and injecting `IConfiguration` into the Razor file (you can inject any service and use it, including a dbContext) ...

I'll add a key-value for "Author" to the *appsettings.json* file ...

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Author": "DJ RexALot"
}
```

I'll add a `using` and `inject` for configuration + I'll ask the service to give me the "Author" configuration value ...

```cshtml
@page "/"
@namespace blazorpre5client.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration  

<!DOCTYPE html>
<html>
<head>
    <!-- OTHER HEAD TAG CONTENT -->
    <meta name="author" content="@Configuration["Author"]">
</head>
```

... and there you have it :tada: ...

<img width="352" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57562826-f15af900-735b-11e9-9aa4-3f8128ca1885.PNG">

You can also have an `@functions` block ... use methods and properties normally. For example ...

In the `<head>` ...

```cshtml
<meta name="something_else" content="@PropertyValue">
```

At the bottom of the *_Host.cshtml* file ...

```cshtml
@functions {
    private string PropertyValue { get; set; } = "property value here";
}
```

Renders in the browser as ...

```
<meta name="something_else" content="property value here">
```

There's an existing issue to address the lack of coverage, and I'll be getting to that **_very soon_**, possibly even this weekend. I'm going to close this as a dup of https://github.com/aspnet/AspNetCore.Docs/issues/12188, but we can re-open if you want to discuss further ... or just add remarks to that issue, which is probably best.

**Comment by itanex** [comment]
Blazor Template Version: `Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01`
DotNetCore: `3.0.100-preview5-011568`

I reinstalled them today and created a new project today. There is still an `index.html` file in the project.

![image](https://user-images.githubusercontent.com/430586/57733409-4d6f9700-7654-11e9-98a9-e5c1f2cfa8f5.png)

Your response is informative, however, it doesn't explain the relation of the files as I was trying to understand. So far I have updated the `index.html` file and I can see that reflected in the render of the page. So correct me where I am confused. Also where in the templated project files are you putting the injection code?

When the initial project is created, built and ran, the index page is rendered as such.

1) Router: - find Page for route "/"
2) Page found: `Pages/Index.razor` declares `@page "/"`
 * Brings a reference for `Shared/SurveyPrompt.razor`
3) `Pages/Index.razor` does not declare a parent container/directive, uses `Pages/_Imports.razor`
 * Brings a reference for `Shared/MainLayout.razor`
 * Brings a reference for `Shared/NavMenu.razor` via `Shared/MainLayout.razor`
4) `Pages/_Imports.razor` does not declare a parent container/directive, uses `_Imports.razor`

This is then all assembled into the directive `App` and injected into the `wwwroot/index.html` file.

Do I have this understood correctly? If not could you please point me towards the proper documentation?

**Comment by guardrex** [comment]
Yes, @itanex ... Blazor client-side uses the *wwwroot/index.htm*. Blazor server-side uses the *\_Host.cshtml* file. I incorrectly assumed that you were using **server-side**. I just put a PR in to clear this up. See :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/12392.

Yes, I think you mostly have it well understood.

> Brings a reference for Shared/SurveyPrompt.razor

It's a component. The Survey Prompt component is a child of the Index component. But, yes, you could say "brings a reference for" to describe that relationship.

*Yes* (mostly) on the rest. I think you have a clear idea of the composition.

> and injected into the wwwroot/index.html file.

I wouldn't say "injected" there. I'd say "composed" or "assembled." But yes, I think you have it right.

I'll think about the coverage more in this regard as we proceed through the previews. This is *always* a bit confusing, and we have the same issues trying to describe how pages/views and other compositional units go together (e.g., view components, partial views, layouts).

Ping me back later as we go with preview docs updates if this is still a problem. I'm glad we have a little time to iron out the problems before RTM.

**Comment by itanex** [comment]
That is great! Ok now down to brass tax here. Since the "composition" uses the `wwwroot/index.html` file at the end. Where in this file structure would one put code that will "compose" values into the `<head>` element?

My goal is to take what is there

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>BlazorClient1</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app>Loading...</app>

    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```

and have some new `<meta/>` tags added to the `<head>` section like this

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <meta property="og:type" content="...">
    <meta property="og:title" content="...">
    <meta name="description" property="og:description" content="...">
    <meta property="og:image" content="...">
    <meta property="og:url" content="...">
    <meta property="og:site_name" content="...">

    <meta property="twitter:card" content="...">
    <meta property="twitter:image:alt" content="...">

    <title>BlazorClient1</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app>Loading...</app>

    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```

I would imagine there would be something like the razor section declarations that are used in classic MVC Razor views.

```
@section Header
{
/// HTML Content and C# code
}
```

**Comment by guardrex** [comment]
*Yes! Indeed!* @itanex ... AFAIK, they're working on exactly that. See https://github.com/aspnet/AspNetCore/issues/10131, and they're 👂 *listening* 👂 on that issue for feedback, so feel free to comment and ask questions there. You'll be chatting directly with management and engineering on that issue.

**Comment by guardrex** [comment]
... but I'm aware that "header" is being used loosely. A "header" section of the page isn't often the `<head>` element. Perhaps, it would be best if you open a **_new issue_** with engineering on that.

Open a new issue at 👉 https://github.com/aspnet/AspNetCore/issues

... and perhaps cross-link the issue that I mentioned asking 'is this part of that issue?'

**Comment by guardrex** [comment]
The more I think about it, the more I think you need a new issue. The only way that I can grok that you'd be able to do that with the *wwwroot/index.html* would be perhaps via JavaScript interop. If you were working with server-side Blazor, you could inject any service ... thus provide a custom service to the *\_Host.cshtml* component to modify the `<head>` element `<meta>` tags. With client-side Blazor tho ... *nope!* ... that isn't going to fly.

Open a new issue and ask if JS interop would be the only way to address that scenario.

Add me "cc: @guardrex" so I can track on your issue.

**Comment by itanex** [comment]
> ... but I'm aware that "header" is being used loosely. A "header" section of the page isn't often the `<head>` element. Perhaps, it would be best if you open a **_new issue_** with engineering on that.
> 
> Open a new issue at 👉 https://github.com/aspnet/AspNetCore/issues
> 
> ... and perhaps cross-link the issue that I mentioned asking 'is this part of that issue?'

That was supposed to be Head not Header. 

Also, if the only way is JavaScript InterOp, than Blazor sites may not be friendly enough for SEO solutions, `<meta>` tags are just one of the items I have to deal with when it comes to that. Static Pages, sure that's one thing, the tags don't change dynamically. I am looking through the AspNetCore issue list for the correct approach.

**Comment by guardrex** [comment]
Excellent feedback ... I look forward to hearing their answer to your question.
