### ISSUE TITLE
If you are using a custom IWebHostBuilder implementation...

### ISSUE THREAD

**Issue by chaim1221** [aspnet/AspNetCore.Docs#12383]
... because you have to make modifications to the defaults, then it _must_ be called CreateWebHostBuilder for Entity Framework migrations to work.

https://stackoverflow.com/a/54222348/2496266

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @chaim1221 ... Yes, we can improve coverage on it, but not in the migrations topic. Migrations is only for version diffs. I'll work it into the overview and host topics.

**Comment by chaim1221** [comment]
Thanks!
