### ISSUE TITLE
Surface Awesome Blazor in Blazor Introduction topic

### ISSUE THREAD

**Issue by fernandreu** [aspnet/AspNetCore.Docs#12387]
Hi, just in case it might be useful for somebody else, I made a [client-side Blazor project on GitHub](https://github.com/fernandreu/blazor-pages) which automatically deploys to GitHub Pages. This is done via Azure Pipelines, using the community approach described in this page. Keep the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db3c04b-4e0e-73a6-80a8-e3df4ee64e89
* Version Independent ID: b514cd67-3e1d-d326-9b87-b70269729a0a
* Content: [Host and deploy Blazor client-side](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/client-side?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/blazor/client-side.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/client-side.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fernandreu ... *Nice one!* We used to keep a Community page of projects, but now we recommend that you open an issue for Adrien Torris's *Awesome Blazor* GH repo at https://github.com/AdrienTorris/awesome-blazor/issues.

I wonder if we should cross-link that as an additional resource on the Blazor docs *Introduction* page.

**Leave this issue open, and we'll see.**

**Comment by fernandreu** [comment]
No problem @guardrex, I went a bit further and created a pull request in the *Awesome Blazor* repo to include my project as a sample one. Thanks for the feedback!

**Comment by guardrex** [comment]
I sent in a patch PR on the line endings. That will speed us up over here on docs. I always stop and add them as I go with a new sample. https://github.com/aspnet/AspNetCore/pull/10192

**Comment by ken-carrier** [comment]
Since you have to "Rewrite URLs for correct routing" does that mean that the server app code and the client app code are no longer interchangeable?

**Comment by guardrex** [comment]
I'm going to put this one up for review. I'll cross-link *Awesome Blazor* from our docs. If engineering doesn't want it, they can just kill the PR.
