### ISSUE TITLE
.net 3 preview 5 Cannot run on VS Code

### ISSUE THREAD

**Issue by mammadkoma** [aspnet/AspNetCore.Docs#12390]
Blazor and other template (MVC & WebApp) in .net 3 preview 5 not work and start (F5) with microsoft VS Code!
We want to create launcher and start (F5) like flutter framework.
![image](https://user-images.githubusercontent.com/17564001/57586310-6d467400-7509-11e9-8ea3-735ae404288f.png)
![image](https://user-images.githubusercontent.com/17564001/57586316-78999f80-7509-11e9-8c9b-add93362e160.png)
![image](https://user-images.githubusercontent.com/17564001/57586319-82230780-7509-11e9-8d7a-dae22a66c874.png)
Boom and Start with F5.

**Comment by guardrex** [comment]
Hello @mammadkoma ... this looks more like product feedback than docs feedback. Open it over on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for managers and engineering to see :eyes:.

**Comment by guardrex** [comment]
btw @mammadkoma ... any problems launching apps with an ASP.NET Core Preview in VS Code are probably point-in-time problems during the preview (and sometimes until the next update to the tooling is made after an RTM of the framework). The tooling and framework always work well by the time they get to RTM.
