### ISSUE TITLE
Sample Client for strongly typed hubs

### ISSUE THREAD

**Issue by crazyfx1** [aspnet/AspNetCore.Docs#12398]
Is there a sample for a .NET client using a strongly typed hub? 
Let's say I want to implement a .NET client using the IChatClient interface described in https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#strongly-typed-hubs

I would expect to pass an implementation of IChatClient to the HubConnection, but I don't see how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Take a look at the code samples in the article on using [SignalR with Background Services](https://docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-2.2#call-a-signalr-hub-from-a-background-service) as it demonstrates this. If you feel this doc would benefit from having something more explicit called out, please let me know and I'll see to it. Thanks!

**Comment by crazyfx1** [comment]
Thank you very much.

This confirms that there is no real type safety as I still need magic strings to wire up the connection. Maybe that's why the implementation is "hidden" in the docs ;)

**Comment by mphealy** [comment]
This thread is a little old but found this link
https://github.com/mehmetakbulut/SignalR.Strong
At the bottom of a similar thread: 
https://github.com/dotnet/aspnetcore/issues/15198

**Comment by BenjaminCharlton** [comment]
This recent blog post looks like a nice implementation of a strongly typed SignalR client. I'm going to try it today.

https://blog.hagoodit.com/2021/08/28/strongly-typed-signal-r-client-and-server/

**Comment by jsauve** [comment]
> This recent blog post looks like a nice implementation of a strongly typed SignalR client. I'm going to try it today.
> 
> https://blog.hagoodit.com/2021/08/28/strongly-typed-signal-r-client-and-server/

That example is outstanding. I ran across it independently. I had already been using SignalR to live push config to my Xamarin app from Azure App Service (via my AS.NET Core API), but now I've adapted it to this strongly-typed implementation. I love it.

The only things that I would change are here:
https://blog.hagoodit.com/2021/08/28/strongly-typed-signal-r-client-and-server/#c8vpo1zg9y

Change...
```cs
endpoints.MapHub<CounterHub>("/CounterHub");
```
to...
```cs
endpoints.MapHub<CounterHub>($"/{nameof(CounterHub)}");
```

...and here:
https://blog.hagoodit.com/2021/08/28/strongly-typed-signal-r-client-and-server/#8rnq36en6lc

Change...
```cs
public CounterSignalRClient(NavigationManager navigationManager)
    : base(navigationManager, "/CounterHub") 
    {
    }
```
to...
```cs
public CounterSignalRClient(NavigationManager navigationManager)
    : base(navigationManager, $"/{nameof(CounterHub)}") 
    {
    }
```

...just to get rid of all manually defined strings.
