### ISSUE TITLE
Add using for app to imports file

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12404]
From @Saik19922 on https://github.com/aspnet/AspNetCore.Docs.de-de/issues/39.

Thanks @Saik19922 ... I think that's a change from prior versions, where they used to have an import for the app's namespace. I just looked and noticed that the template doesn't do that any longer.

I'll update the doc and have the reader add it to the *\_Imports.razor* file. Thanks for letting us know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hi @guardrex 
I'm moving this from here https://github.com/aspnet/AspNetCore.Docs.de-de/issues/39 as per your request:
@Saik19922 commented 36 minutes ago

> At step 5 where TodoItem.cs is created and the TodoItem class is declared, todo.razor will also need a @using <Name of your App> directive to make the TodoItem class available.

**Comment by guardrex** [comment]
@CeciAc Is it better for me to always let you move them? I certainly can do so. I go a little *too fast* 🏃 *sometimes!*

**Comment by guardrex** [comment]
@CeciAc I should just *hold my horses* a bit. I tend to respond super fast on pings ... like *60 seconds*. lol

I'll just wait. I know ur going to take care of it.

Thanks @Saik19922 ... I'll get this updated today.

**Comment by Saik19922** [comment]
Thanks for taking care so fast! Keep up the good work.
