### ISSUE TITLE
Overwhelming

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore.Docs#12408]
I think this page contains **tons** of great information but IMHO it is overwhelming to the beginner and for the basics.  In comparison, [this site helps](https://thomasardal.com/appsettings-in-asp-net-core/) a user do the basics with appSettings.json

Perhaps there is a way to break this up a little? 🤔 

Thoughts? 💭

Edit:

![image](https://user-images.githubusercontent.com/3605364/57719047-8b4fc980-761a-11e9-8210-47e2951ab0ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @spottedmahn It's possible. This is a known issue ... and not just for this topic. We have a few that due to framework scenario growth became looooong topics. Same can be said for the IIS Overview, and I discussed that with Sourabh recently. We're talk'in about it for sure.

@Rick-Anderson @tdykstra If you want to proceed on this issue ... at least consider how this might go, you can assign me if you want, and I'll have time in June to look. I propose to discuss it here on the issue first. If we find an opportunity/approach that you like, we can take it from there.

**Comment by Rick-Anderson** [comment]
@spottedmahn  thanks for the suggestion. This is an advanced topic and we don't have the resources to rewrite this.

**Comment by spottedmahn** [comment]
@Rick-Anderson fair enough 👍

I'm curious, what's stats screenshot you put in opening entry?

**Comment by guardrex** [comment]
It's a proprietary web analytics system. I think it's a MS thing. I searched and didn't see a public site/repo for it. Of course, the stats displayed by the system aren't available to the public.

**Comment by Rick-Anderson** [comment]
Internal tracking stats.
It's a good suggestion, we're just overwhelmed with more pressing issues (over 400).

**Comment by spottedmahn** [comment]
Hi @Rick-Anderson
>Internal tracking stats.

I see, interesting, thanks!

>It's a good suggestion, we're just overwhelmed with more pressing issues (over 400).

Np, I understand.

---

What I was really looking for I found today: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2) 🎉.

**Comment by mxa0079** [comment]
How is poorly written documentation not a pressing issue? This is the entry point to new developers and a driver for adoption (just look at Vue). What is the value of a full-featured, efficient, and modern framework if the entry cost is too high and people wont use it?

**Comment by EternalDeiwos** [comment]
This please... Between the new SPA templates (for which Vue is notably lacking) total obfuscation and trying to figure out what the configurable options are for IdentityServer, I'm just about ready to give up completely. I've been fighting with this documentation for a week now to deploy an application that is freshly generated from the template.

Its just one problem after the next and eventually finding some flag that needs to be set before finding the next non-obvious problem that requires an arcane work around.
