### ISSUE TITLE
unable to use useState hook with .net core project template

### ISSUE THREAD

**Issue by mookhoo** [aspnet/AspNetCore.Docs#12405]
I am trying to create a new page that utilizes useState hook in the project created by [this template](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio), I have been unsuccessful. I have tried several ways, creating a function, and I end up getting error. Do you have an example on how to create a new page in this template and utilize "useState" hook? Thanks!

**Comment by guardrex** [comment]
Hi @mookhoo ... I'm going to move this over to an issue opened via the **This Page** feedback button at the bottom of the topic. It will tag the issue with metadata that will ping the author of that topic. Stand-by ... you'll get a ping when I move it.
