### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by Anarkin** [aspnet/AspNetCore.Docs#12402]
Hi,

Unless it's generally accepted at this point, I think we should consider rephrasing "from DI" in the following occurrences:
- "Get an ILogger&lt;TCategoryName&gt; object from DI."
- "To write logs in the Program class, get an ILogger instance from DI:"

My thought process is that DI can either be the pattern, or the MS.Ext.DI libs. Even in the case where the provided example code explicitly resolves an instance, it might be confusing.

What do you think?

Regards,
Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Anarkin Thanks for the question.  I've never seen any indication that "from DI" in contexts like these has been misunderstood, and we use the phrase throughout our docs.  The acronym DI should only appear in an article after being introduced earlier in the same article as "dependency injection (DI)", with either a short explanation or a link to the DI article. Either way, "DI" should be understood as the DI system used by ASP.NET Core, and "from DI" as shorthand for "from the DI container".
