### ISSUE TITLE
Anything about query parameters? Like ?x=a&y=b ,etc? 

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore.Docs#12425]
Or is this on another page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wrkettlitz ... Only Route Parameters (described in the [Components topic](https://docs.microsoft.com/aspnet/core/blazor/components?view=aspnetcore-3.0#route-parameters)) are supported at this time. 

Query string scenarios are on the roadmap and should appear in a future preview. See the remarks at :point_right: https://github.com/aspnet/AspNetCore/issues/5489, where catch-all segments and querystring/hash values are mentioned.

If you have questions or comments, chat directly with the engineers and management on that engineering issue.
