### ISSUE TITLE
Docs for new Negotiate auth handler

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore.Docs#12420]
Docs for https://github.com/aspnet/AspNetCore/pull/9831

This may be an addition to or spinoff from https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio

This is a new authentication handler for Kerberos and NTLM and is intended for cross platform use.

WARNING: This component can persist credentials across requests on a given connection and MUST NOT be used with proxies unless they maintain a 1:1 connection affinity. This means it must not be used with Kestrel behind IIS (ANCM) out-of-proc.

Configuration:
- The code and options are quite minimal, but configuring your environment can be very complicated, especially for Kerbers, Linux, etc.. That's out of scope for this doc but we should link to some guides on environment setup.
- This only works with Kestrel.
- It is supported on Windows, Mac, and Linux
- We expect the primary usage to be Windows clients connecting to Linux servers that are part of the same Windows domain.
- HTTP/2 is not supported, but most clients automatically downgrade to HTTP/1.1 when challenged.

Results:
- On Windows this produces a WindowsPrincipal and WindowsIdentity.
- On Unix this produces a ClaimsIdentity with the name of the user (user@example.com). (No roles, etc.)

**Comment by Tratcher** [comment]
Usage sample:
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization(options =>
            {
                // Require all requests to be authenticated unless an endpoint is marked as AllowAnonymous
                options.FallbackPolicy = options.DefaultPolicy;
            });
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseDeveloperExceptionPage();
            app.UseAuthentication();
            app.UseAuthorization();
            app.Run(HandleRequest);
        }
```

**Comment by Tratcher** [comment]
Setup doc:
https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller
(TODO: Confirm these work)

**Comment by blacksnake-rus** [comment]
> Environment setup:
> Additional steps:

If my app is deployed in docker, then i must to follow all these instructions inside the container?

**Comment by Tratcher** [comment]
I haven't tried that yet. Note keytab files can be re-used so you should be able to do this setup once and then copy it into the container. Let me know how that goes.
