### ISSUE TITLE
Sending message to specific User

### ISSUE THREAD

**Issue by garfbradaz** [aspnet/AspNetCore.Docs#12427]
Hey guys, how to do you send a specific message to a user/client from a Controller outside the hub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by serpent5** [comment]
Take the example from the page:

    await _hubContext.Clients.All.SendAsync("Notify", $"Home page loaded at: {DateTime.Now}");

To send to a specific user/client, use the relevant method:

    await _hubContext.Clients.Client("clientId").SendAsync("Notify", $"Home page loaded at: {DateTime.Now}");
    await _hubContext.Clients.User("userId").SendAsync("Notify", $"Home page loaded at: {DateTime.Now}");

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
