### ISSUE TITLE
The Visual Studio tool guidance, step #8 is incorrect

### ISSUE THREAD

**Issue by bleachlizard** [aspnet/AspNetCore.Docs#12435]
8. For a Blazor client-side experience, choose the Blazor (client-side) template. For a Blazor server-side experience, choose the Blazor (server-side) template....

Should be:
8. For a Blazor client-side experience, choose the Blazor (client-side) template. For a fully self-contained Blazor experience, choose the Blazor (ASP.NET Core hosted) template....

It doesn't appear that the server-side template is there if the prior instructions are followed precisely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bleachlizard ... It's not showing ...

<img width="603" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57814362-132bf580-7739-11e9-80a3-4c929d17ee6d.PNG">

**Comment by bleachlizard** [comment]
Interesting. I’m on the latest version of 16.0, but not 16.1, so maybe that’s the difference?

**Comment by guardrex** [comment]
I'm using 16.0.2, and I have it.

What does a `dotnet --info` show ... do you have the Preview 5 SDK?

**Comment by bleachlizard** [comment]
Thanks for responding, @guardrex . The 'Use preview SDKs' is indeed checked, but my preview SDK version is different -- I have the Preview 3. I'm actually surprised that Step 2 didn't fail then, as I did tell it to use 3.0.0-preview5-19227-01 per the instructions. I don't know enough about the dotnet command, so I presume it used the min of that version and my local version. I'm testing that theory now (installing Preview 5).

**Comment by guardrex** [comment]
> I have the Preview 3.

Ah, yes. I think you'll find that that's the problem. 🤞

As for step 2 ...I guess it installs the templates without regard to the SDK installed as you found out. I've never tried running that command first, before the SDK preview install step.

**Comment by bleachlizard** [comment]
Yep, that was it! Thanks for the help, @guardrex .

In summary, you need at least the Preview 5 SDK, regardless of what version(s) you already have installed. Lesson learned :D
