### ISSUE TITLE
Is policy always required when specifying authentication schemes?

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore.Docs#12438]
As far as I understand, default policy only requires that user is authenticated. And I assume that if attribute is used like that (without specifying policy)
```CSharp
[Authorize(AuthenticationSchemes = AuthSchemes.Cookies)]
```
Default policy will be used. If so, I cannot understand why authorization fails for the razor page to which user is redirected after signing in.
When I specify policy:
```CSharp
[Authorize(Policy=Policies.ManagesProducts, AuthenticationSchemes = AuthSchemes.Cookies)]
```
everything works fine.

```CSharp
services.AddAuthorization(opt =>
{
    opt.AddPolicy(Policies.ManagesProducts, _ =>
    {
        _.Requirements.Add(
            new ClaimsAuthorizationRequirement(ClaimTypes.Role, new[] { "ConnectDeviceAdmin" }));
    });
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x#use-multiple-authentication-schemes)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for: Authorize with a specific scheme #16190

**Comment by HaoK** [comment]
You policy doesn't require the user to be authenticated, try adding RequireAuthenticatedUser to your policy and it should fail as well

**Comment by HaoK** [comment]
The issue is maybe that you didn't specify an authenticationType in your identity, so even though you have a principal, its not considered authenticated

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
