### ISSUE TITLE
Implementing Asp.Net Core 2.2 Identity for Angular SPA

### ISSUE THREAD

**Issue by niranjan17892** [aspnet/AspNetCore.Docs#12439]
I have an existing application with ASP.Net Core 2.2 and Angular 7 SPA. I want to implement Identity Authentication to it. Is there any way to achieve it ? Or is JWT is the only way to do so ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
Authentication and Authorization for SPAs is a 3.0 only feature. That said, it should be possible to reuse the pieces already available to some extent to create your own implementation. For authenticating and authorizing SPA applications JWT is the way to go.

**Comment by niranjan17892** [comment]
Thank you!

**Comment by Svetomechc** [comment]
@niranjan17892 https://gitlab.com/Svetomechc/angularidentityserver
