### ISSUE TITLE
Confusion about "Use a common user database" for ASP.NET Core + ASP.NET 4.x case

### ISSUE THREAD

**Issue by CallStackRunner** [aspnet/AspNetCore.Docs#12432]
Hello! Thanks for the great article.
There's "Confirm that the identity system for each app is pointed at the same user database." proposal at the bottom. 
I'd want to confirm that this is not the case when one app is ASP.Net Core and another one is ASP.NET 4.x because Identity v3 and v2 use different database schemas.
If this is correct then I'd like to propose to mention this in article explicitly because it causes some confusion: first we're telling how to configure 4.x and Core to work with same cookie simultaneously and then we're telling that apps can use same database (which is, according from my understanding, is not true for 4.x + Core case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share cookies among apps with ASP.NET and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by natiki** [comment]
Hi,

Just to add to @CallStackRunner I am also confused by this. There appears to be no way to allow a WebForms .NET 4.61 application using using `Microsoft.AspNet.Identity` to use Microsoft.AspNet**Core**.Identity and hence have the WebForms application and the .NET Core application use ASP.NET Identity Core common database.

What am I missing here? I need exactly what this post promises but cannot get WebForms and .NET Core to use the same user database.
