### ISSUE TITLE
Implement Asp.Net Core 2.2 Identity with Angular SPA

### ISSUE THREAD

**Issue by niranjan17892** [aspnet/AspNetCore.Docs#12440]
Hi,

I have an existing application with .Net Core 2.2 and Angular 7 SPA. I wanted to implement Authentication using .Net Core Identity, is there any sample or documentation which I could use or refer to ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guyng** [comment]
Microsoft has published a angular 7 & identity server template for .Net Core 3.0 (preview 5).
You can either upgrade to preview and try it out or wait a few months untill they'll release
.Net Core 3.0.
For my understanding they mentioned in one of their streams that it will most likely be released on third quarter of 2019(probably around august/sept).

**Comment by OzBob** [comment]
install aspnetcore 3 preview 5 and
dotnet new angular --auth Individual

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
