### ISSUE TITLE
Just had my mind blown. 

### ISSUE THREAD

**Issue by stewa11** [aspnet/AspNetCore.Docs#12442]
.Net Core looks sooo good, but it's difficult to absorb all in one go.
Thank you for making the EF lightweight. 

Just installed VS2019 and created my first .Net Core project. What a clean, professional it looks too. It all looks so impressive.

I am not a great fan of HTML tag-based 'generators' like Razor. I prefer to work in JavaScript. On the other hand I am looking for productivity and flexibility when defining SPAs with complex logic. I am almost certain this is a new journey.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment.
