### ISSUE TITLE
Redis on Windows in 2019?

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/AspNetCore.Docs#12448]
Is it a best practice from Microsoft - "Use redis for windows"?
Redis for windows not supported by Microsoft for a 3 years already. disro on git marked as archived and no longer maintained. 
Maybe installation via Chocolatey on Windows should be dropped and replaces with for example- Redis hosted on Linux Subsystem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-memory-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SychevIgor ... I'll mark this for the Product Unit to take a look at on the next doc review. Thanks for asking ... they'll let us know when they see this.

**Comment by guardrex** [comment]
I just took a closer look ... the sample app and text were already updated for `StackExchangeRedis`, and engineering is supporting it. https://github.com/aspnet/Extensions/tree/master/src/Caching/StackExchangeRedis

It's actively maintained ...

* https://www.nuget.org/packages/StackExchange.Redis/
* https://github.com/StackExchange/StackExchange.Redis/

I think we're good here, but we can re-open if there's something that I missed.

**Comment by SychevIgor** [comment]
@guardrex looks like you don't understand me.
Redis it self - is a cool key-value data storage and it's working well on LINUX. What you give my- are provider(connector- it's not a database it's a way to access database) to Redis datastore.
But Microsoft do not support Redis database on WINDOWS.  WHat Microsoft did already in archive https://github.com/microsoftarchive/redis

**Comment by guardrex** [comment]
Ah ... I see ... that's a product issue. Open it over for the engineers and managers to see.

Open it here :point_right: https://github.com/aspnet/AspNetCore/issues

**Comment by SychevIgor** [comment]
@guardrex looks like I didn't understand the problem again.

It's not a bug in a asp.net core! We may use Redis using Redis client from StackExchange.Redis if Redis was installed on Linux.
Problem is in a documentation. Developers using documentation as official guides and set of best practices, and it's wring to have an instruction "how to install redis on windows", when redis on windows is not supported by microsoft.

Section about Redis installation on windows should be deleted from the documentation or updated with a guide how to run it in a container or on Linux.

**Comment by guardrex** [comment]
Ok ... thanks for explaining it out. I'll mark this for the product unit to take a look at.

**Comment by collinstevens** [comment]
@guardrex maybe the docs should reference https://redislabs.com/blog/redis-on-windows-10/ because the version of Redis which is ported to Windows is outdated and not receiving further updates. 

You can use the official build of Redis on Windows by using WSL with no issues.

**Comment by guardrex** [comment]
@collinstevens Until engineering has time to take a look at this and decide what they'd like to do (including even dropping that *"To install Redis on your local machine"* bit), this issue will be visible to readers. Hopefully, they'll find your remark ☝️ and have good results with it.
