### ISSUE TITLE
No info on how to do Blazor server side with Azure SignalR service

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore.Docs#12445]
This page is pretty low on info in general. It would be great to have info here on the changes I need to make for my server side Blazor app to run on Azure (or another host). In particular, I want my app to work 100% locally when I do dev, and use Azure SignalR when I deploy to SignalR. This includes doing secure credential storage and all the best practices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042b0c63-cbb8-0347-97f2-11e935aae405
* Version Independent ID: 064606f3-3a82-1493-768a-41e056eb92de
* Content: [Host and deploy Blazor server-side](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server-side?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/blazor/server-side.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/server-side.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Eilon** [comment]
@danroth27

**Comment by guardrex** [comment]
@danroth27 Doesn't it just fall in with our existing *Host and Deploy* coverage, which this topic already links to? It's low on info because we cover all of the concepts in existing topics.

**Comment by Eilon** [comment]
If the info is elsewhere, I think linking is fine.

**Comment by guardrex** [comment]
It currently cross-links to ...

* \<xref:signalr/introduction>
* \<xref:host-and-deploy/index>
* \<xref:tutorials/publish-to-azure-webapp-using-vs>
* \[Deploy ASP.NET Core preview release to Azure App Service](xref:host-and-deploy/azure-apps/index#deploy-aspnet-core-preview-release-to-azure-app-service)

*BUT* ... I just discovered that I left a few markup notes in the doc for possible expansion ...

1. **Concerns are the same as publishing an ASP.NET Core SignalR app** &ndash; I believe this is meant to be a general remark + link over to the SignalR docs that pertain to publishing SignalR apps.
1. **Content on the Azure SignalR Service** &ndash; I need to research this further.
1. **Manually turn on WebSockets support** &ndash; I need to research this further.

I'll see if I can address these.

**Comment by danroth27** [comment]
If you're using the Azure SignalR Service I believe you don't need to turn on WebSockets support in the app.

Here's the quickstart for getting started with the Azure SignalR Service and ASP.NET Core (should also apply to server-side Blazor): https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core

**Comment by danroth27** [comment]
@bradygaster Are there other docs for using the Azure SignalR Service with ASP.NET Core SignalR that we should be referencing?

**Comment by bradygaster** [comment]
Here are a few that are definitely worth of linking-to:

* https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core
* https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-overview?toc=%2Faspnet%2Fcore%2Ftoc.json&bc=%2Faspnet%2Fcore%2Fbreadcrumb%2Ftoc.json&view=aspnetcore-2.2
* https://docs.microsoft.com/en-us/azure/azure-signalr/ (intro)

If we should create anything more specific let me know, I'd be happy to help near the end of next week once DEVIntersection wraps up. Or I could serve as a reviewer if @guardrex had some time to work on something.
