### ISSUE TITLE
"Rating" column not being added when running: dotnet ef database update

### ISSUE THREAD

**Issue by AskYous** [aspnet/AspNetCore.Docs#12441]
Note: I use a Mac.

1. I edited the Movies.cs file to include a new `Rating` field. 
2. I deleted `MvcMovie.db`. 
3. I ran `dotnet ef database update`.
4. The same schema is made as before. No `Rating` column.

I even tried adding 5 more fields just to test it. It seems to completely ignore my `Movies.cs` file.

* Here is a video of me trying to add the field: https://youtu.be/zgqLaseEK5Y
* Here is my current code: https://github.com/AskYous/razor-movie-add-field-glitch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by AskYous** [comment]
I noticed that when I attempted to add the column manually using a database client app, it gave the error:

> [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)

I don't know if this is related.

**Comment by AskYous** [comment]
For now, I solved my problem by deleting the migrations folder and running
```
dotnet ef migrations add InitialCreate
dotnet ef database update
```

**Comment by Rick-Anderson** [comment]
That works. In the next sweep we'll have SQLite instructions.
Covered in #10758

**Comment by anangaur** [comment]
@Rick-Anderson Whats the resolution of this issue? Should the instructions mentioned by @AskYous be added to the docs? Is there a PR for it?

**Comment by Rick-Anderson** [comment]
Delete the migrations folder.
