### ISSUE TITLE
Serverside javascript references in component

### ISSUE THREAD

**Issue by Simon-Miller** [aspnet/AspNetCore.Docs#12459]
Here's my scenario:  Opened the default template for a serverside razor project.  Works great, can add a breakpoint in c# code, and see the debugger in visual studio.  LOVE IT!!  So, I desire visual studio code debugging - thus avoiding Chrome's debugger tools.  Now, I want to add interaction with javascript.  The Canvas to be precise.  But I don't want to just download a working component, or else I would not learn anything.  
So I dotnet new blazorlib -o BlazorLib1, and out pops a project.  The "prompt" interaction.  Great!  So, add a project reference to it in Visual Studio, and it's happy for me to add code in a click handler such as :

async Task Interact()
    {
        response = await ExampleJsInterop.Prompt(this.JSRuntime, "Hello from C#!");
    }

Which works in the sense that the click is wired up, and the interop must be called, because the error refers to not being able to find "window.exampleInterop" function.  Something like that.  Basically, it suggests that the javascript code has not been pulled into the client side.  No script reference?
So, how is the script "registered"?  Is there a step missing in the explanations above?  I can't for the life of me find a way to get this working, and I would like to think I'm not alone in this - and this is the perfect page to find such information!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [Blazor JavaScript interop](https://docs.microsoft.com/en-gb/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Simon-Miller ... A bit of what you're asking about is on a PR that merged to `master` a couple of days ago, but we haven't merged to `live` yet. I'll do that now, and the updates should appear shortly.

The gist of it is that in server-side Blazor, the JavaScript `<script>` reference for the *exampleJsInterop.js* file goes into the `<head>` of the *Pages/\_Host.csthml* file.

In a client-side Blazor app, it goes into the `<head>` of the *wwwroot/index.html* file.

You can either look at the PR or wait for the updates to go live within an hour or two.

The PR :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/12392

Regarding the Blazor lib scenario: For the current preview, a Blazor server-side app can't consume static assets from a component library (either a Razor Class Lib or a Blazor lib). There's a 3rd party package that might be able to help. See :point_right: https://docs.microsoft.com/aspnet/core/blazor/class-libraries#static-assets-not-supported-for-server-side-apps. This is a point-in-time problem, and a solution will arrive from engineering in an upcoming preview. I'm aware that our coverage is a little light on **_exactly how_** static asset (e.g., JS files, stylesheets) injection into a Blazor client-side app works. For example, we don't currently cover how stylesheets go into a `_content` folder with a reference in *wwwroot/index.html*. I'm planning on addressing the whole subject on a future issue when engineering has resolved the Blazor server-side scenario.

WRT additional debugging features for VSCode ... AFAIK, that's still on the roadmap. If you look down on the backlog of the roadmap, there's a mention of it ... see if that issue addresses it. Try searching the engineering repo for "vscode" or "vs code" after filtering the issues on the `area-blazor` label. There might be other VSC issues in the engineering repo that aren't linked in the roadmap issue.

* [Blazor Roadmap](https://github.com/aspnet/AspNetCore/issues/8177)
* [aspnet/AspNetCore engineering repo](https://github.com/aspnet/AspNetCore/issues) (filter on `area-blazor`)

I don't think I have anything at the moment to document here. Follow-up on my links. If you have additional docs notes or questions, add them to this issue. I'll re-open, and we can discuss it further. If you have product feedback on Blazor, open an issue on the engineering repo for the engineers and managers to see. Thanks for commenting here.

**Comment by guardrex** [comment]
Unfortunately, I can't merge to `live` at this time. There's a PR with an unusual title marking that  management will need to take a look at before we take #12392 live. You can access that PR directly to see the updates.

**Comment by Simon-Miller** [comment]
That's ok.  For your information, or anyone else that might be trying the same, you need to know that https://www.nuget.org/packages/BlazorEmbedLibrary/# works!
You were right - I'm very humbled by Microsoft, and the Blazor community.

So I'm seeing the default template project that is a javascript interop of the "prompt" command - working in Blazor (server side).

This extension does indeed recognise the component lib, and adds brings the javascript interop code to the client-side, so when you make a call to it from the c# side, - everything works as you'd expect.  It's a dream come true!
