### ISSUE TITLE
The problem with Data Integrity rules being hard-coded....

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#12465]
Here's 290 Movies that can no longer be included in our Database:
https://www.imdb.com/search/keyword?keywords=one-letter-title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
So change the rules.

**Comment by boomalator** [comment]
Lol... well, yes... but...

That means spinning up a development project to change something that had no business being hard-coded; including gaining management approval, budget, and time to do so, and tracking it through a change management system, and then doing unit and acceptance testing, right?

As a tutorial, I think it's good to model the best practices, and a developer hard-coding an arbitrary limit leads to things like:
- People named Ng not having their names accepted (too short)
- People named O'Toole and O'Connor not having their names accepted
- People not being able to enter their non-10-digit phone number 
- People not being able to enter non-US postal codes (Not being able to use a Non-US credit card at a gas pump because of it)
- Being forced to use insecure passwords (refusing characters like spaces, etc., or require "old-style" security)

For example, it's also been decided in development that "19th Century Film" is an invalid Genre.... Why? (That's rhetorical.) More importantly, why would it be a developper decision? I suppose if you have a functional spec that defines these things, then the developer is jut implementing, but I don't think nearly enough thought is put into how such limits are determined.

Thank you for the quick response.
