### ISSUE TITLE
CSS doesn't support the background highlighting (in 2.2?)

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#12468]
This is listed as a 2.2 tutorial. However, the 2.2 new project template doesn't seem to include a "success" CSS class. ("Added code that dynamically adds class="success" to the tr element of the selected instructor. This sets a background color for the selected row using a Bootstrap class.")  I think I've heard of bootstrap, but it wasn't listed as a dependency. (I see no mention of it in "Get Started".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's for your feedback. We'll look at this in the 3.0 sweep.
