### ISSUE TITLE
Should HTTPS redirection occur earlier in the pipeline?

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12461]
Might be an ID-10T error on my part, but I'm working up a Blazor sample for web API and using the sample app here as a basis. With the sample app's pipeline order of ...

```csharp
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseHttpsRedirection();
app.UseMvc();
```

... the *Index.html* page loads (handled by Static File Middleware prior to the HTTPS Redirection Middleware), but the GET (and any other method, POST, etc.) throws a CORS violation (browser) and a 'method not supported' exception from endpoint middleware (app) due to (*I think*) the redirect working on the subsequent requests (handled by MVC after HTTPS Redirection Middleware) ... thus a protocol change on the AJAX requests.

Whether that's a correct interpretation or not ... If the order is changed for a redirect to the secure protocol on the initial *index.html* page request, then subsequent requests to GET, POST, etc. work fine (protocol is the same). Should the order in the pipeline be? ...

```csharp
app.UseHttpsRedirection();
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseMvc();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I dunno if it's helpful to mention here, but `dotnet new webapp` sets up something that corroborates your suggestion:

```cs
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseCookiePolicy();
app.UseMvc();
```

**Comment by Rick-Anderson** [comment]
We should do what the templates do. Not sure how they got out of order.

**Comment by guardrex** [comment]
I'll patch it on the new Blazor topic PR that I'll be putting in shortly. The topic points to this topic+sample as a web API example for its demo.
