### ISSUE TITLE
Errors In namespaces. Doesn't seem to have been tested. Isn't 2.2 despite listed as such.

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#12467]
There are several places where the Namespace in the provided code is wrong. Despite this being listed as a 2.2 tutorial, it does not match 2.2 and appears to be based on 2.1 or earlier. It doesn't appear that anyone went through and keystroke-tested this before publishing it (at least not as a 2.2 tutorial).

This statement "The preceding code handles office assignment changes." appears in the section "Add Course assignments to the instructor edit page", where it does not correctly apply. (Seems to be a cut-and-paste that got missed.)

Comments indicate that some issues will be addressed, but it's been ten months and #7745 is simply closed. 

The section at the top includes a link "If you run into problems you can't solve, download or view the completed app. Download instructions", which leads to a mish-mash of badly-labelled folders. Is this cu20? cu21? I dunno? Or maybe this is a stage snapshot? It doesn't not seem clear to me which of this working folders is actually for this tutorial, or which may have been for core 1 or 2.1 instead of 2.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The code works in 2.2.
We'll review this in the 3.0 sweep.

**Comment by boomalator** [comment]
> The code works in 2.2.
> We'll review this in the 3.0 sweep.

The code works if one makes undocumented edits. Which is kinda like "not working". It does NOT work as posted.
