### ISSUE TITLE
Possible missing feature in default project set up Visual Studio Preview 2019 .NET Core 2.2

### ISSUE THREAD

**Issue by Kool-Koder** [aspnet/AspNetCore.Docs#12463]
Hi, I am setting up a new project using Visual Studio Preview 2019 with .NET Core 2.2.

I'm not too sure if it affects, but I used to have another project which has a dynamic 'active' navbar when that particular view is chosen.

I have been searching for the code that was controlling the dynamic navbar in the old project and likewise in the new project but I can't seem to find any settings for it. Could you please point me to the right direction? Thank you!

**Comment by guardrex** [comment]
The ASP.NET Core templates can be found here ...

https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates

If you want to see the code for an older template, set the branch to an older release. It defaults to `master` which is where the engineers are doing work currently for the upcoming release.
