### ISSUE TITLE
Update Commands need more detail 

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#12469]
By "A command Window", I assumed that one would use the Visual Studio Ctrl-Alt-A Command Windows. However, that returns  "Command "dotnet" is not valid.".   So, it must be a "Windows Command Window" (elevated? Not elevated?), Which informs me that "No project was found. Change the current working directory or use the --project option."  This is supposed to be a Tutorial. Providing guidance and instructions that lead to the right place would be beneficial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is the last portion of an advanced tutorial. YOu have to be in the project directory.
