### ISSUE TITLE
Problems on Mac

### ISSUE THREAD

**Issue by daveyostcom** [aspnet/AspNetCore.Docs#12478]
1. I downloaded the Blazor extension, then in Extension Manager, I clicked Install from File..., selected the extension, and clicked Open. Then nothing apparently happened. I don't see anything like a Blazor extension anywhere in the Installed section of the Extension Manager.
2. There is no Tools &gt; Options on Mac. I went to Preferences... and couldn't find anything like Projects and Solutions or "use preview SDKs".
That's as far as I could get. Please correct this page for Mac VS. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @daveyostcom ... VS4Mac bits aren't quite ready yet. Last I heard, they were working on it. You'll need to use VS Code on the Mac at this time.

Note that "Visual Studio" in doc contexts only refers to VS on Windows. There will be a new tab here when VS4Mac is ready, and that will have VS4Mac-specific instructions.
