### ISSUE TITLE
Remove namespace from snippets

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#12471]
As in the last part, the namespace is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What namespace is wrong? Where?

**Comment by Rick-Anderson** [comment]
Namespace should be removed from displayed snippet.

**Comment by boomalator** [comment]
If one follows your instructions in https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio, namely:

"In the Data context class row, select the + (plus) sign and change the generated name to ContosoUniversity.Models.SchoolContext."

Then, the code on this page, which includes:
private readonly ContosoUniversity.Data.SchoolContext _context;

Will not compile, because the namespace is wrong.

This a simple fix, that convinces me that this tutorial was not tested end-to-end, "advanced" or not.

**Comment by Rick-Anderson** [comment]
That's a helpful comment. The scaffolder changed between versions and we missed that change. We'll get it fixed in the next update. This is a high traffic document and folks are able to figure that out.

**Comment by boomalator** [comment]
The veiled insult to a customer is not necessary. I was, in fact, able to "figure it out". The fact that dozens or millions of other customers also "figured it out" does not make it less of an error.

The POINT of documentation is to learn about the project, like maybe that "the scaffolder changed".

**Comment by Rick-Anderson** [comment]
I apologize, I did not intend to insult you. I knew you figured it out and the last comment was helpful in figuring out what went wrong.

**Comment by Rick-Anderson** [comment]
Advanced tutorials shouldn't include the namespace.

**Comment by Rick-Anderson** [comment]
Moved to #12475 so we can see comment at the start of the series.
Thanks for bringing this to our attention.
