### ISSUE TITLE
Blazor (client-side) template is missing

### ISSUE THREAD

**Issue by daveyostcom** [aspnet/AspNetCore.Docs#12479]
Where it says:
8. For a Blazor client-side experience, choose the Blazor (client-side) template.
Blazor (server-side) is in the list, but not client-side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you run the command? ...

```console
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01
```

**Comment by guardrex** [comment]
I thought you said that you were on a Mac (VS4Mac)?

**Comment by daveyostcom** [comment]
I switched to Windows 10 (in VMware Fusion, latest), following the instructions there. I ran the command (otherwise how would "Blazor (server-side)" be in the list? :)

Another thing: where it says to click Create, then it says to type F5. That seems a nonsequitur and does nothing.

**Comment by guardrex** [comment]
> otherwise how would "Blazor (server-side)" be in the list?

Because the behavior on Mac is still in flux ... I thought that perhaps some progress had been made by that team such that the VS4Mac preview would at least show them.

Do a `dotnet new --help` and see if they're listed there. Also, you're saying now that you're using VSforWin on that VM?

> where it says to click Create

Are you using VS preview? If ur trying to use a non-preview VS, it might either have unusual behavior or just flat-out not run Blazor apps properly. Also, the dialogs changed. The topic describes the latest experience with VS preview (*I think* lol ... even I'm still running 16.0.2 here).

**Comment by daveyostcom** [comment]
I'm following the instructions using VS preview on Windows. And I was able to run the server-side app. (My F5 problem probably has to do with VMware.)

`blazorserverside` is the only blazor thing in the list when I run `dotnet new --help`.

**Comment by guardrex** [comment]
hum ..... interesting. Well, it's more of a product unit problem on the MIA Blazor client-side template. If you have the Preview 5 SDK installed, it should work.

Ask the engineers/managers on the engineering repo about it. The topic shows the latest guidance that we have from them. You might want to search open **and closed** issues first tho ... someone else may have hit the same problem.

https://github.com/aspnet/AspNetCore/issues

I'll close here because we don't have an actionable doc issue yet, but please do ping back here if you find out what the problem is and feel that we should address it.

**Comment by daveyostcom** [comment]
[This page](https://devblogs.microsoft.com/dotnet/net-core-tooling-update-for-visual-studio-2017-version-15-9/) says I should be seeing the option to use previews of the .NET Core SDK, but I'm not seeing that option.
![](https://devblogs.microsoft.com/wp-content/uploads/sites/10/2019/02/derp.png)

**Comment by guardrex** [comment]
Correct ... VS preview always uses preview SDKs automatically. Therefore, they don't show that checkbox in VS preview.

**Comment by daveyostcom** [comment]
Ah. Then the right thing is for the URI to show that fact, grayed out.

**Comment by guardrex** [comment]
I see what you mean ... that makes sense. Open that for the VS team using the **Help** > **Send Feedback** > **Report a Problem** process. It goes directly to the VS team.

**Comment by ppatel514** [comment]
Blazor (Client-Side) Template is missing in visual studio even after following steps 1,2 & 3 on link below.

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

However, I am able to create new Blazor (Client-Side) project using .Net Core CLI.

Please let me know if any additional details are needed. Any help much appreciated.

**Comment by guardrex** [comment]
The name changed a couple of days ago. Use the Blazor WebAssembly App template. We already have a change in for the doc that will go live on Monday.

**Comment by ppatel514** [comment]
Thank you for quick response.

any reason I am seeing "Blazor WebAssembly App" template twice in list when creating new project?

**Comment by guardrex** [comment]
It's a known issue. They should have it fixed soon.

**Comment by ppatel514** [comment]
Thank you. Will below link be updated with new instructions along with other issues?

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by guardrex** [comment]
*Yes*, but there aren't any new instructions. It was just the name of the templates that changed. They changed mid-stream from the framework (in between Pre6 and the upcoming Pre7 releases), so that's why they were put in off of the normal preview release schedule.

**Comment by AqlaSolutions** [comment]
Having the same issue with the latest preview

**Comment by guardrex** [comment]
@AqlaSolutions ... There are no changes as far as I know from engineering. You can either use the **Report a Problem** process (under **Help**) from within Visual Studio Preview to report it (btw - make sure that you're using [16.3 Preview 3](https://docs.microsoft.com/visualstudio/releases/2019/release-notes-preview)), or you can open an issue for engineering.

**Comment by AqlaSolutions** [comment]
@guardrex , already found the cause - I've run `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19424.4` under administrator command prompt but VS is run under normal user.

**Comment by guardrex** [comment]
I would open a new issue, except that this is a point-in-time problem. *Soon!* there will be no need to run the separate command to install the templates. The VS installer will take care of it. That line in the topic that has that `dotnet` command **_should_** 🤞 go away ....... if the :pray: *sever gods* :pray: bless us with good tooling at 3.0 GA. :smile:

**Comment by ahmediddma** [comment]
install it from here https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates/

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio
