### ISSUE TITLE
Found a malformed 'input' tag helper. Tag helpers must have a start and end tag or be self closing	

### ISSUE THREAD

**Issue by karthickthangasamy** [aspnet/AspNetCore.Docs#12481]
The input tags must be self-closed

&lt;input bind="@StartDate" format-value="yyyy-MM-dd" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-in/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @karthickthangasamy. I'll patch it. This is unfortunate because progress had been made with Razor ... the engineers fixed an earlier issue in Razor syntax where void elements didn't require self-closing. We've moved back to having to close them now ... at least for the time being.

**Comment by guardrex** [comment]
@karthickthangasamy ... here's the engineering PR where they did the work :point_right: https://github.com/aspnet/Mvc/pull/2956

**Comment by guardrex** [comment]
ok ... that should fix them. I ask DR on the PR if this is just a point-in-time problem. I hope so ... I'm a big fan of **_not closing_** when using HTML5. Although, I admit that the spec is ok with it. I think W3C should have said that they have to be *unclosed*.
