### ISSUE TITLE
ApplicationName

### ISSUE THREAD

**Issue by joacar** [aspnet/AspNetCore.Docs#12482]
Hi,

The section describing [ApplicationName](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#application-key-name) doesn't mention that the setting is **not** overridable from environment specific configurations files, example `appsettings.Staging.json`. Does that differ should be documented explicitly that the behavior isn't available.

So, to the question: Should the documentation be updated or is this not the intended behavior (i.e bug)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#application-key-name)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@joacar It should be ... did you try setting it directly from an argument (i.e., in `args`)? You could also do it this way :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#override-configuration with a `ConfigurationBuilder`.

`

**Comment by guardrex** [comment]
AFAIK, the key name is still `applicationName`; so if you set that into the *appsettings.Staging.json* config file, you should be able to get that host config with ...

```csharp
var config = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.Staging.json", optional: true)
    .AddCommandLine(args)
    .Build();

return WebHost.CreateDefaultBuilder(args)
    .UseConfiguration(config)
```

... and the command-line should work, too ...

```console
dotnet run --applicationName MYAPP
```

**Comment by joacar** [comment]
@guardrex Thanks for quick reply! My applications is using the generic host and code looks like

```c#
var builder = new HostBuilder()
                .ConfigureHostConfiguration(ConfigureHostConfiguration)
                .ConfigureAppConfiguration(ConfigureAppConfiguration)
                .UseSerilog(ConfigureSerilogInternal);
            return builder;
```
In the method `ConfigureSerilogInternal` I use **ApplicationName** to configure the source that entries in Windows Event Log should be written to. Now the value remains the same as in **appsetings.json** and `null` if I remove it.

The extensions method `UseConfiguration` I guess is in the `Micorosft.AspNetCore.Extensions` namespace and assembly and as of 2.2 not compatible with generic host `IHostBuilder`

**Comment by joacar** [comment]
Made a small application to show case the issue

```c#
var host = new HostBuilder()
	.ConfigureHostConfiguration(builder =>
	{
		builder.AddJsonFile("appsettings.json");
		// While this works, how do I get access to EnvironmentName?
		//.AddJsonFile("appsettings.Production.json");
	})
	.ConfigureAppConfiguration((context, configuration) =>
	{
		// No affect on ApplicationName
		configuration.AddJsonFile("appsettings.Production.json");
	})
	.Build();
var hostingEnvironment = host.Services.GetRequiredService<IHostingEnvironment>();
// Prints Production
Console.WriteLine("EnvironmentName = {0}", hostingEnvironment.EnvironmentName);
// Prints appsettings.json
Console.WriteLine("ApplicationName = {0}", hostingEnvironment.ApplicationName);
Console.ReadKey();
```

And the configuration files

```json
/* Default */
{
  "ApplicationName": "appsettings.json" 
}
/* Production */
{
  "ApplicationName": "appsettings.Production.json" 
}
```

How do I get the **EnvironmentName** during the call to `ConfigureHostConfiguration(IConfigurationBuilder)` to load the correct configuration file?

[AspnetCore.Docs-Issue12482.zip](https://github.com/aspnet/AspNetCore.Docs/files/3206596/AspnetCore.Docs-Issue12482.zip)

**Comment by guardrex** [comment]
Build the configuration and then you can get values from it. You'll need to use a provider, of course, and the env var provider and command line provider would automatically be there if you called `CreateDeafultBuilder`. Since you're not calling `CreateDeafultBuilder` in your example code and just going right off of a new `HostBuilder`, then you'll need to supply the environment using at least one provider ... any of them ... whatever makes sense for you. In the following example, I'll use another settings file (*hosting.json*). However, it could be any of them ... env vars, command line, etc.

*hosting.json*:

```json
{
  "environment": "MyCoolEnvironment"
}
```

```csharp
.ConfigureHostConfiguration(configHost =>
{
    // Set up at least one provider here that will supply the environment.
    // I'll use that hosting.json file.
    configHost.SetBasePath(System.IO.Directory.GetCurrentDirectory());
    configHost.AddJsonFile("hosting.json");
    var builtConfig = configHost.Build();
    configHost.AddJsonFile($"hostSettings.{builtConfig["environment"]}.json");
})
```

It will go looking for a *hostSettings.MyCoolEnvironment.json* file to load config.

Engineering seems to prefer that devs keep their hosting confg and app config separate. It's true that settings from a file called "appsettings" here in `ConfigureHostConfiguration` will flow to the app, but I'm just say'in that you don't see that set up in engineering samples. In the example above, I go for more of a clean separation of host config (e.g., *hostSettings.ENVIRONMENT.json*) for that. I'd then read my *appsettings.json*/*appsettings.ENVIRONMENT.json* down in `ConfigureAppConfiguration`. On the other hand tho, I'm sure that you're aware of the need for flexibility, and they've given that to everyone with these cool toys.

**Comment by joacar** [comment]
Once the host is built it is closed for registration of services so I can't call `Build()` that early since I need to configure application services. That is only available on the `IHostBuilder`. Recall that I use `Microsoft.Extensions.Hosting.IHostBuilder` where there is no default factory method.

Should we conclude that **ApplicationName** is a host configuration and can't be override by application configuration?

**Comment by guardrex** [comment]
What I showed isn't building the host ... it's just building it's configuration providers.

> ApplicationName is a host configuration and can't be override by application configuration?

AFAIK, yes.

**Comment by joacar** [comment]
Thanks for taking the time @guardrex to explain clear my confusion. I've changed to a custom section for this specific purpose.
