### ISSUE TITLE
Document Browser support matrix for Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#12480]

**Comment by guardrex** [comment]
We don't have a formal *Prerequisites* section any longer. If you let me know where you'd like this, I can take care of it.

**Comment by danroth27** [comment]
SignalR has a [Supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms) doc that has their browser support matrix. How about we add a similar doc for Blazor?
