### ISSUE TITLE
Update intro to RP for VS19

### ISSUE THREAD

**Issue by shanecossey** [aspnet/AspNetCore.Docs#12497]
Why does the prerequisite list include Visual Studio 2019 and then show the New Project creation in another version of VS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We haven't updated all the doc.

**Comment by Rick-Anderson** [comment]
VS 19 is correct.

**Comment by shanecossey** [comment]
Yes, got it going. It just doesn't instill much confidence in a tutorial when the step-by-step guide shows steps which don't look like your screen does. Apart from that, good tutorial.
