### ISSUE TITLE
Areas in .net core 3 which is using endpoints

### ISSUE THREAD

**Issue by koppular** [aspnet/AspNetCore.Docs#12493]
In .net core 3, endpoints are used to for routing. Could you update the docs.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
