### ISSUE TITLE
AspNetCore.App now has to be referenced in .csproj of dependent projects

### ISSUE THREAD

**Issue by lccarvalho** [aspnet/AspNetCore.Docs#12491]
I have a solution previously converted to aspnetcore 2.1 in which some projects depend on others. In this configuration I did not have to reference Microsoft.AspNetCore.App on dependent projects, only in the referenced one. Migrating to 2.2 I had to reference the metapackage in all projects. Noting that in docs could save people some time and trouble.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Microsoft.AspNetCore.App metapackage for ASP.NET Core 2.1 or later](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@lccarvalho  thanks for reporting this.. Hopefully the information will help someone. We'll be looking for feedback.
