### ISSUE TITLE
AddOpenIdConnect.Options.PostLogoutRedirectUri Renamed

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore.Docs#12499]
`PostLogoutRedirectUri` was renamed to `SignedOutRedirectUri`

I'm happy to submit a PR but I'm not 100% where it should do in this guide.  Thoughts? 💭

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by spottedmahn** [comment]
`Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions`

**Comment by scottaddie** [comment]
@spottedmahn Thank you for the offer to submit a PR. This would fit well in the following section, below the code snippet showing the `AddOpenIdConnect` call:

https://docs.microsoft.com/aspnet/core/migration/1x-to-2x/identity-2x#openid-connect-oidc-authentication
