### ISSUE TITLE
OmniSharp can't load Microsoft.NET.Sdk.Web if Visual Studio 2017 is installed

### ISSUE THREAD

**Issue by ChronosWS** [aspnet/AspNetCore.Docs#12495]
The initial application creation and loading steps above will fail in VSCode if Visual Studio 2017 is installed as well because OmniSharp will find the MSBuild version from that install before the .NET Core SDK version.  The older version of MSBuild will not resolve the web SDK correctly.  I worked around this by simply relocating the old MSBuild version so OmniSharp would no longer find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Closing as a duplicate. This issue is engineering-related and is being tracked in the extension's repo at https://github.com/OmniSharp/omnisharp-vscode/issues/3074. Please track progress over there.
