### ISSUE TITLE
Building the solution has a missing assembly reference for Microsoft.AspNetCore

### ISSUE THREAD

**Issue by pipe2path** [aspnet/AspNetCore.Docs#12509]
After following instructions on the "Getting Started" section and creating a new Asp.Net Core Web Application project, the solution does not build. Here is the error:  Error CS0234 The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pipe2path VS preview + the Preview 5 SDK is required. That seems to fix this situation for most users. See the engineering issue for more info :point_right: https://github.com/aspnet/AspNetCore/issues/9851#issuecomment-494126720
