### ISSUE TITLE
User secrets in shared hosting (Plesk)

### ISSUE THREAD

**Issue by neman** [aspnet/AspNetCore.Docs#12510]
Is it possible to use this feature within shared hosting environment, where we do not have options to use `dotnet` command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows#feedback)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
No, this is intended for client side dev, not a shared host.
