### ISSUE TITLE
Revert void element tag closure in Blazor topics

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12518]
Revert: https://github.com/aspnet/AspNetCore.Docs/pull/12484

https://github.com/aspnet/AspNetCore/issues/10498

**Comment by guardrex** [comment]
@danroth27 How you want void element closure handled?

* Leave them closed as they sit today ... and we can close this issue.
* Don't close void elements ... and put in an engineering PR for the templates to do the same.

**Comment by guardrex** [comment]
Ping @danroth27 ... :point_up: for guidance which way to go.

**Comment by danroth27** [comment]
I'm finding the VS really wants my void tags to be closed, so I think we should stick with closed void tags.
