### ISSUE TITLE
Why build project inside image rather than copy the publish/* into image like normal .netcore app ?

### ISSUE THREAD

**Issue by GreatFireWall** [aspnet/AspNetCore.Docs#12519]
From here [Tutorial: Containerize a .NET Core app](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container).

It's very simple:

```
FROM mcr.microsoft.com/dotnet/core/runtime:2.2

COPY app/bin/Release/netcoreapp2.2/publish/ app/

ENTRYPOINT ["dotnet", "app/myapp.dll"]
```

I don't know why asp.net core app need to copy the source code into image then build it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by spboyer** [comment]
In this example, the base container is the `runtime` and does not have the necessary items to build the application. 

As an alternative, we could have a multi-stage Docker file and build the application within the container and produce the final build assets. Such as

```docker
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build-env
WORKDIR /app

COPY myapp/*.csproj ./
RUN dotnet restore

COPY ./myapp ./
RUN dotnet publish -c Release -o out

# FINAL IMAGE
FROM mcr.microsoft.com/dotnet/core/runtime:2.2
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "app/myapp.dll"]
```

Practice would be to build the application in the same OS that you'd use the runtime in unless you were producing multiple outputs. i.e. for Linux, Windows and other variations of an OS.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by GreatFireWall** [comment]
@spboyer Thanks your answer. 
I have another question:
After image build, I run `docker exec -it ...` enter the container, I can see current working dir is `/app`, that's good. But under `/app`, there're all source code files of my project like this:

![image](https://user-images.githubusercontent.com/4510984/58304969-04c09680-7e29-11e9-8b72-1f190ea41c00.png)
-------------------------

The publish folder location as the follow image, I don't know how can the `ENTRYPOINT ["dotnet", "myproject.dll"]` find the correct `myproject.dll` path ?

![image](https://user-images.githubusercontent.com/4510984/58305177-bb247b80-7e29-11e9-85a9-ad42371b129b.png)

**Comment by GreatFireWall** [comment]
I found that it was caused by the debug version. In the release version, the files is positioned as expected.

**Comment by StingyJack** [comment]
I dont believe that the question was answered, only more explanations about possibilities. The OP asked why are you running the build from inside the docker container instead of in VS or a devops pipeline? 

Its really strange to see and there isnt a great explanation of why one would choose a far more complex approach.

**Comment by AIZ-THerring** [comment]
I'm still curious about this myself.  If I already have a built copy of the application (part of a solution with multiple other non-containerized apps, and the whole solution is built together), then why do I need to build it AGAIN inside Docker instead of just dumping the application files into a docker image with the proper runtime?
