### ISSUE TITLE
Create advanced Blazor tutorial

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12516]
Create an advanced tutorial based on the Blazing Pizzas workshop+app. 

https://github.com/aspnet/AspNetCore.Docs/issues/10773#issuecomment-494923781

**Comment by danroth27** [comment]
@guardrex I think we should close this one. We are already invested in maintaining the Blazor workshop. I don't think we want to duplicate the content elsewhere that we then need to keep in sync.
