### ISSUE TITLE
What will happen is I not use `IFormFile` and also not disable `FormValueProviderFactory`?

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore.Docs#12511]
> Files uploaded using the `IFormFile` technique are buffered in memory or on disk on the web server before being processed.

what cause it ? Model binding  or any related to `IFormFile` like the `Requst.Form.Files`  ?  and why remove `FormValueProviderFactory` and `JQueryFormValueProviderFactory` make a difference?

and may be not related to this page, but I think the Stream upload code is too complex, and we can create a new public  class to make this step simple.
```c#
public class MultipartRequestHandle
{
    public MultipartRequestHandle(Func<IFileContentDisposition,Stream,Task> fileContenthandle){};
    public ValueTask<IFormCollection> HandleAsync(){} // this will return the FormCollection ,but the FormCollection.File.Body will be null, 
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @John0King ... AFAICT, that's actually just the way the framework handles requests. It seems to be the case for *any* request, but you'd need to research it more ... perhaps consult with engineers who know that code base much better than I.

https://github.com/aspnet/AspNetCore/blob/093df67c06297c20edb422fe6d3a555008e152a9/src/Http/WebUtilities/src/FileBufferingReadStream.cs

... so (if that's correct) I doubt that `FormValueProviderFactory`/`JQueryFormValueProviderFactory` affects the scenario.

> Stream upload code is too complex

You'd have to take that up with engineering.

Note that we have a big update going in on https://github.com/aspnet/AspNetCore.Docs/pull/12344. It's in review now.

**Comment by guardrex** [comment]
@John0King See remark at :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/12344#issuecomment-495290221

**Comment by John0King** [comment]
@guardrex Ok
