### ISSUE TITLE
How to test with DI'd HttpClients?

### ISSUE THREAD

**Issue by DavidPx** [aspnet/AspNetCore.Docs#12528]
Is there a chance we could get a section on how to write tests against this?  Typically I run the "real" Startup class in order to get the real DI container and then swap in external services like HTTP and AWS with mocks.  HttpClient is not mockable so I'm currently riding the struggle bus on how to get a mock HttpMessageHandler into the mix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
If we do something specific, it would probably be better in either the unit testing or integration testing topics.

* https://docs.microsoft.com/aspnet/core/mvc/controllers/testing
* https://docs.microsoft.com/aspnet/core/test/integration-tests
* ... note that we don't maintain the unit testing topic in the *Test, Debug, Troubleshoot* area. That one is maintained in .NET Core docs.

I'll mark this for the Integration Testing project so the product unit can decide if they want us to pursue it.

**Comment by stevejgordon** [comment]
I have a partially completed, long overdue post on testing with HttpClient and HttpClientFactory. I'll try to pick that up again after my upcoming vacation and share the link. Happy to help distil some of that into a doc afterwards if appropriate.

**Comment by guardrex** [comment]
cc: @tdykstra @Rick-Anderson ... :point_up:

**Comment by guardrex** [comment]
> some of that into a doc afterwards if appropriate.

If it boils down to just mocking a few objects correctly, I wonder if it can be covered with an added section (possibly with a sample app example).

btw @tdykstra Would the [MVC controllers testing doc](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) be better off in the *Test, debug, and troubleshoot* node with the rest of the testing docs? If so, I could move that TOC entry when I work on [Test, debug, and troubleshoot enhancements (aspnet/AspNetCore.Docs #10150)](https://github.com/aspnet/AspNetCore.Docs/issues/10150), which is coming up quick for work.

**Comment by tdykstra** [comment]
> Would the MVC controllers testing doc be better off in the Test, debug, and troubleshoot node with the rest of the testing docs?

Yes that makes sense.

**Comment by guardrex** [comment]
Moved to the tracking issue for this topic: **Integration tests MASTER issue** #16341
