### ISSUE TITLE
Unable to start Kestrel

### ISSUE THREAD

**Issue by davidRsully** [aspnet/AspNetCore.Docs#12525]
I followed instructions on this page and ran the CLI, but get this error. Please advise.

~/Projects $dotnet new blazor -o WebApplication1
The template "Blazor (client-side)" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on WebApplication1/WebApplication1.csproj...
  Restore completed in 715.65 ms for ~/Projects/WebApplication1/WebApplication1.csproj.

Restore succeeded.

~/Projects $cd  WebApplication1
~/Projects/WebApplication1 $dotnet run
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.

If I run the Visual Studio Mac, I get an error with the following: 
NullableContextOptions="$(NullableContextOptions)"        
/usr/local/share/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(10,10): Error MSB4064: The "NullableContextOptions" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. (MSB4064) (BlazorSample)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @davidRsully ... search the engineering issues (open & **closed**). If you don't see a similar issue with an answer from engineering, then open a new issue with that info. If you open a new issue, give them your `dotnet --info` output and tell them what platform and OS version that you're using.

https://github.com/aspnet/AspNetCore/issues

**Comment by guardrex** [comment]
This might be similar ... I see it says "NullableContextOptions" in its error message.

https://github.com/aspnet/AspNetCore/issues/10218
