### ISSUE TITLE
[5.0] IE11 support for server-side Blazor

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12520]
HOLD for engineering work on: https://github.com/aspnet/AspNetCore/issues/9436

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
We should just add a sentence somewhere "to user Blazor Server with older browsers like IE11 we recommend using the community maintained [Blazor Polyfills](https://github.com/Daddoon/Blazor.Polyfill)".

This can potentially go into the Browser Support Matrix article.

**Comment by guardrex** [comment]
It's already there. :+1:

**Comment by guardrex** [comment]
Since https://github.com/dotnet/aspnetcore/issues/9436 was closed as a won't fix (or won't fix further, i.e., polyfills work) and the supported versions topic already has a statement about using polyfills, we can close this.
