### ISSUE TITLE
Sample code for ManifestEmbeddedFileProvider needs to be modified

### ISSUE THREAD

**Issue by chrisdpratt** [aspnet/AspNetCore.Docs#12527]
In the sample code for `ManifestEmbeddedFileProvider`, it's created via:

    var manifestEmbeddedProvider = 
        new ManifestEmbeddedFileProvider(Assembly.GetEntryAssembly());

That works fine as long as the startup code is being run directly by the app, but in situations where the it's being run by proxy, such as via the `dotnet ef` CLI tool, then the "entry assembly" is actually `ef` in that case, not your app. It would be better to use:

    var manifestEmbeddedProvider = 
        new ManifestEmbeddedFileProvider(typeof(Program).Assembly);

As this will remain constant, despite the usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.2#file-provider-implementations)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @chrisdpratt ... I'll schedule this for the PU to take a look at. Once we have their approval, I'll put a PR in to fix it.
