### ISSUE TITLE
No such package for 3.0 preview

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore.Docs#12536]
Add XML format support
To add XML formatting support, install the Microsoft.AspNetCore.Mvc.Formatters.Xml NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@pranavkm Any ideas?

**Comment by pranavkm** [comment]
The binary is part of the shared framework in 3.0 and consequently a package is no longer produced. https://github.com/aspnet/Announcements/issues/325 has an announcement detailing what's being done and https://github.com/aspnet/AspNetCore/issues/3756 has a list of the packages that are no longer being published.

**Comment by scottaddie** [comment]
Reopening to adjust doc based on Pranav's response above.
