### ISSUE TITLE
NavLink li active?

### ISSUE THREAD

**Issue by Aurora7Sys** [aspnet/AspNetCore.Docs#12535]
Is there a way to have the NavLink Component render the li as active instead of the a / anchor? That would be handy in cases where a .css has already been setup for that scenario. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
No ... not OOB. The behavior of the NavLink is set by the framework. You could, of course, open an engineering request for that ...

https://github.com/aspnet/AspNetCore/issues
