### ISSUE TITLE
Invoking "void" methods

### ISSUE THREAD

**Issue by fleed** [aspnet/AspNetCore.Docs#12545]
[EDIT by @guardrex to fix the HTML-encoded C# from the feedback form.]

How do I Invoke JavaScript methods that don't return anything ("void" methods)?

**IJSRuntime** only exposes `Task<T> InvokeAsync<T>(string identifier, params object[] args);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
void functions return `undefined`, so I whipped up a test with the sample app ...

```javascript
window.exampleJsFunctions = {
    testVoid: function () {
        console.log('testVoid called!');
        return undefined;
        // or ... return void(0);
        // or ... return void 0;
    }
}
```

```csharp
var returnValue = _jsRuntime.InvokeAsync<object>("exampleJsFunctions.testVoid", null);
```

The FN is called and `returnValue` is `null`, which seems fine.

Should we have a few lines to cover this scenario? I think it would just need to say that:

* The FN returns `undefined` (`void(0)` or `void 0`)
* `T` is `object` in this scenario.
* Expect `null` to come back after the FN executes.

Stand-by @fleed ... DR will let us know what to do.

**Comment by danroth27** [comment]
Yup, we should doc this as proposed.
