### ISSUE TITLE
`OpenRegion`/`CloseRegion` are internal

### ISSUE THREAD

**Issue by limefrogyank** [aspnet/AspNetCore.Docs#12544]
I couldn't find the `OpenRegion` and `CloseRegion` methods on `RenderTreeBuilder` and after examining the source code, I discovered they were internal.  So these are not available to the public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/RenderTree/RenderTreeBuilder.cs#L537-L552

I see ... that came from the Gist on the subject (3rd Q&A) ...

https://gist.github.com/SteveSandersonMS/ec232992c2446ab9a0059dd0fbc5d0c3#questions

I'll remove the remark. Thanks @limefrogyank!

**Comment by danroth27** [comment]
@SteveSandersonMS Should the OpenRegion and CloseRegion methods on RenderTreeBuilder be public? Currently they are internal.

**Comment by SteveSandersonMS** [comment]
I don't know of any reason to make them public. The builder uses them internally when people add `RenderFragment` content. What scenarios do you have in mind for using them separately from this?

**Comment by guardrex** [comment]
@SteveSandersonMS It's one of your answers in the Gist Q&A, which was taken for the doc text (but docs PR #12546 removed it) ...

> Q: I find it impractical to hard-code sequence numbers in really long blocks of manually-implemented RenderTreeBuilder logic. What should I do?
>
> A: Don't write really long blocks of manually-implemented RenderTreeBuilder logic. Preferably use `.razor` files and let the compiler deal with this for you, or if you can't, split up your code into smaller pieces wrapped in `OpenRegion`/`CloseRegion` calls. Each region has its own separate space of sequence numbers, so you can restart from zero (or any other arbitrary number) inside each region if you want.

https://gist.github.com/SteveSandersonMS/ec232992c2446ab9a0059dd0fbc5d0c3#questions

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying. Yes, makes sense.

I'm pretty neutral about this. We can do it, but it's super low priority compared with the large number of mainstream-scenario-critical work items that remain ahead of 3.0. We might do this eventually but certainly not before 3.0.

**Comment by limefrogyank** [comment]
I was trying to use the `OpenRegion` and `CloseRegion` to create list items in a ListView type of control.  I don't remember exactly why it was necessary, but I was using RenderTreeBuilder so I could insert a virtualized spacer in front and at the end of the list with specific heights.  It was rather difficult to do this without using a loop.  Also, there was some difficulty doing it with razor files, too.  But, there's no rush.

**Comment by arivoir** [comment]
> I don't know of any reason to make them public. The builder uses them internally when people add RenderFragment content. What scenarios do you have in mind for using them separately from this?

I have a scenario where the content of a component is dynamic (A data grid), so I need to pass the RenderTreeBuilder to the rows and these pass it to the columns, any of these can modify this method to customize the content of the cells. In order to allow the columns and rows to have "secure" sequence numbers I need the Open/CloseRegion to be public.

I also considered using razor components inside the cells but it's terrible slow. In my opinion this is a major performance problem of the platform https://github.com/aspnet/AspNetCore/issues/10563

**Comment by guardrex** [comment]
May I recommend taking the discussion to a new issue in engineering? We don't work on or discuss things on closed issues. Besides, this isn't currently a docs issue ... it's more of an engineering consideration at this point.
