### ISSUE TITLE
This article promotes C#/dotnet for the server-side but ignores C# client-side

### ISSUE THREAD

**Issue by wolfch** [aspnet/AspNetCore.Docs#12543]
I only care about using C#/dotnet-core for _consuming_ REST but this article focuses on the server-side and leaves out that client detail and only mentions jQuery and the Postman tool.  Not good.  

I have found numerous examples that suggest using `HttpClient` then programmatically performing deserialization on a per-object basis.  Very primitive.  In Java we have Spring-Boot and Python offers `requests` both of which do transparent  deserialization.   The closest I found in the dotnet space is:

https://github.com/dotnetcore/WebApiClient

this project seems like an excellent REST client along the lines of https://github.com/OpenFeign/feign  
but code comments and `README.md` are in Chinese.  I am very surprised that dotnet is so limited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The article is not about consuming, it's about producing. ASP.NET Core is a server technology, not a client side.

**Comment by wolfch** [comment]
Ok, but upon closing, you couldn't give me a clue if dotnet has a client-side?

**Comment by Rick-Anderson** [comment]
Yes, but that's not my area. This is a server article. Google it.
