### ISSUE TITLE
Visual Studio setup #3

### ISSUE THREAD

**Issue by jhvanderven** [aspnet/AspNetCore.Docs#12549]
In my version of Visual Studio 2019 Community this checkbox is under Environment|Preview features. If you do not enable it, you get an error about App not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jhvanderven ... I'm going to remove that note. The engineers are saying now that unless one uses a preview release that apps either won't run or the IDE doesn't function properly. I'm still hanging on barely with 16.0.2 (for other reasons ... I'm out of HD space here 🙈), but I do have a lot of tooling bugs.

Try the preview release. There's no 'use preview SDK' checkbox in VS preview releases ... preview VS always uses preview SDKs by default.
