### ISSUE TITLE
Latest VS 2019 update moved the preview option

### ISSUE THREAD

**Issue by bleachlizard** [aspnet/AspNetCore.Docs#12555]
In Step #3 of the "Visual Studio" section, as of the latest VS 2019 update (16.1.1+28922.388), it appears that the "Use previews of the .NET Core SDK" option has moved to Environment &gt; Preview Features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bleachlizard ... It's been addressed and the change will go live shortly. https://github.com/aspnet/AspNetCore.Docs/pull/12550
