### ISSUE TITLE
How to extend the user registration UI?

### ISSUE THREAD

**Issue by joarb** [aspnet/AspNetCore.Docs#12552]
I would love to see a small section regarding how to extend the user registration UI once one has scaffolded a ASP.NET Core 3.0 SPA Identity-backed project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by joshpearce** [comment]
I'm assuming the scaffolding explained here does not work https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli

**Comment by joshpearce** [comment]
I haven't tried the IdentityServer's UI scaffolding. I'm not sure if it would work.

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

**Comment by Svetomechc** [comment]
Can I extend the UI with anything other than Razor pages (Angular, for example)?

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406
