### ISSUE TITLE
Make it easier to find ConfigureTestServices

### ISSUE THREAD

**Issue by omerlh** [aspnet/AspNetCore.Docs#12551]
I tried to copy the sample above, but VS for mac (not vscode!) is not that good in detecting the extension method. It couldn't find `ConfigureTestServices` until I manually added the relevant namespace `Microsoft.AspNetCore.TestHost`. It required some Googling to find the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.webhostbuilderextensions.configuretestservices?view=aspnetcore-2.2) of this method - and from there to learn which namespace I should add. 
Maybe worth adding a note "don't forget to add `using Microsoft.AspNetCore.TestHost`"? I know this is a VS bug, but I don't know when or if this will be fixed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#inject-mock-services)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omerlh ... The guidance from engineering is to use the `Microsoft.AspNetCore.Mvc.Testing` package, which has a dependency on `Microsoft.AspNetCore.TestHost`. `Microsoft.AspNetCore.Mvc.Testing` is called out early in the topic. 

Also, every member that we link via the API Browser, provides the namespace and the assembly.

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.testhost.webhostbuilderextensions.configuretestservices

<img width="593" alt="Capture" src="https://user-images.githubusercontent.com/1622880/58414852-41b3a580-8042-11e9-98fd-288231af5c52.PNG">
