### ISSUE TITLE
RegisterService.ps1 link is dead

### ISSUE THREAD

**Issue by sattha** [aspnet/AspNetCore.Docs#12561]
When clicking to the sccipt it redirects to 404 Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @sattha ... We just made a large round of updates to the topic, and the changes haven't gone live yet.

https://github.com/aspnet/AspNetCore.Docs/pull/12449

I'll merge our updates to the `live` branch now, so the updated topic should appear within an hour or two.

**Comment by DerHulk** [comment]
Hello @guardrex it looks like the link is once again/still broken.
[https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2](url) or [https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/host-and-deploy/windows-service/scripts](url). Plz can you fix it, thx.

**Comment by guardrex** [comment]
That script was removed from the topic. The localized version of the topic will take a little bit longer to update. We only merged that PR a few days ago. I'm not sure how long it will take to update.

Let's give it another couple of days. Ping me back if it doesn't update, and I'll ask internally how long it takes for the localized version to update.

**Comment by DerHulk** [comment]
Hello @guardrex , docu is up to date now, thx.
