### ISSUE TITLE
Linked GitHub Repo is archived

### ISSUE THREAD

**Issue by XmlmXmlmX** [aspnet/AspNetCore.Docs#12562]
The linked GitHub Repository for JavaScriptServices was marked as "archived".
https://github.com/aspnet/JavaScriptServices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScriptServices to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @XmlmXmlmX ... I'll patch that up.

The new location is :point_right: https://github.com/aspnet/AspNetCore/tree/release/2.2/src/Middleware/SpaServices

**Comment by guardrex** [comment]
I'll fix up shortly ... it's a slightly more complicated fix given that the naming has shifted in engineering. "JavaScript Services" isn't really *a thing* any longer ... it's all called "SPA Services" now. However, the topic, which was written back in the "JavaScript Services" days, follows the old naming convention and splits the tech description into two categories. I'll fix it up when I get back. Thanks @XmlmXmlmX for calling this out.

**Comment by guardrex** [comment]
@natemcmaster When the "JavaScript Services" repo moved, it looks like the naming was dropped. The topic currently describes it this way (in its own section) ...

> JavaScriptServices is a collection of client-side technologies for ASP.NET Core. Its goal is to position ASP.NET Core as developers' preferred server-side platform for building SPAs.
>
> JavaScriptServices consists of three distinct NuGet packages:
>
> * Microsoft.AspNetCore.NodeServices (NodeServices)
> * Microsoft.AspNetCore.SpaServices (SpaServices)
> * Microsoft.AspNetCore.SpaTemplates (SpaTemplates)

Keeping in mind that the [SPA templates went away (aspnet/Announcements #289)](https://github.com/aspnet/Announcements/issues/289) and should be dropped here.

... while "SPA Services" are described as (in a separate section) ...

> SpaServices was created to position ASP.NET Core as developers' preferred server-side platform for building SPAs. SpaServices isn't required to develop SPAs with ASP.NET Core, and it doesn't lock you into a particular client framework.
>
> SpaServices provides useful infrastructure such as:
>
> * Server-side prerendering
> * Webpack Dev Middleware
> * Hot Module Replacement
> * Routing helpers

... so there's a *client-side and specific-to-Core* versus *server-side and generic to SPA framework* distinction there.

Has the naming "JavaScript Services" gone away and the client-side bits are just generally lumped under the naming "SPA Services" now?

If so, I need to roll that content together (carefully keeping the distinction that exists).

If not, I need to drop the explicit "JavaScript Services" proper noun naming. Perhaps, we'd just go with something along the lines of ...

* JavaScript services
* JavaScript services provided by ASP.NET Core
* ASP.NET Core JavaScript services

**Comment by natemcmaster** [comment]
I think the naming "JavaScript services" is relevant. There are still several packages built and supported by the AspNetCore team.

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/NodeServices/README.md
https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/SpaServices/README.md
https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/SpaServices.Extensions

The movement of the source code from a dedicated repo to a shared one wasn't meant to signal any changes in the product. It was done to simplify our engineering.

**Comment by guardrex** [comment]
@natemcmaster Thanks ... I'll make the update on that basis and preserve everything just about the way that it is.

I think we only need to lose the proper noun. It flowed from the name of the dedicated repo ("JavaScriptServices"). Now, it can just be "JavaScript services."
