### ISSUE TITLE
Support for dependency injection

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/AspNetCore.Docs#12563]
Hi,

Please enable 'registering' routes, maps, and constraints, so that they're resolved on demand with the DI container.

See https://github.com/aspnet/AspNetCore/issues/10574.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?highlight=routing&view=aspnetcore-2.2#route-constraint-reference)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @weitzhandler ... You opened that in the right spot for engineering. We only handle the documentation aspects over here, so we'll react after they make a move.
