### ISSUE TITLE
Latest VS template and documentation not matching

### ISSUE THREAD

**Issue by sowsan** [aspnet/AspNetCore.Docs#12567]
Going through the doc and testing the blazor serverside app in VS 2019. The startup.cs file created by default has a different code compared to the documentation here. Can you update the same here?

 public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton&lt;WeatherForecastService&gt;();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();

            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =&gt;
            {
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#server-side)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Indeed, it does ... the doc is showing Preview 4. I'll update it ... *_BUT_* ... it's a bad idea given the churn to show code at this time. *That's just bitten us here!* I'll remove the code and leave the description. It will harden the topic for future previews/RC/RTM/future versions. Thanks @sowsan! :rocket:

**Comment by sowsan** [comment]
Awesome. It make totally sense :)

**Comment by guardrex** [comment]
Yep ..... I have a sneaky feel'in ..... it's going to change again ..... *and again* .... maybe even one more time after that. :smile: lol

**Comment by sowsan** [comment]
Lol :)
