### ISSUE TITLE
How to add page route templates AFTER the app has been initialized

### ISSUE THREAD

**Issue by spacecat** [aspnet/AspNetCore.Docs#12576]
If you want to create a custom page route model convention you do it by implementing IPageRouteModelConvention and then you pass it to options in Startup.cs.

Let's say I add new templates for each of the Razor Pages I have in my project in the custom page route model conventions Apply method.

This works fine and the new route templates will be available to my app.

But what about new routes that I might add later on, when the app is already up and running, e.g. if I want to register additional route templates based on page content created in a CMS, how would I dynamically register these new ones? Or you can only add new route templates during app startup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c32c8-ec27-1771-bb62-71d6aa55b1d6
* Version Independent ID: 99dc76fb-8762-20a6-d7b1-df3ce6e6fc4d
* Content: [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.2#model-conventions)
* Content Source: [aspnetcore/razor-pages/razor-pages-conventions.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @spacecat ... It wasn't a scenario discussed when we wrote the topic (or in the Routing topic AFAIK).

Ask on the engineering repo. If they provide guidance that seems like it should go into the topic (or in the Routing topic), then ping me back over here and we can work it.

https://github.com/aspnet/AspNetCore/issues

**Comment by spacecat** [comment]
@guardrex Thanks.
