### ISSUE TITLE
Need an article on authentication and authorization

### ISSUE THREAD

**Issue by sbsw** [aspnet/AspNetCore.Docs#12579]
I had hoped to find information about securing my API (implementing authentication and authorization). From what little I've gleaned from reading about the general subject, I would expect to find info about the proper way to pass around JWTs and the proper way to authenticate when the caller and the API are all hosted within Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#additional-resources)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Dup of #4556
