### ISSUE TITLE
Add a hosting startup loading assemblies scenario for 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12574]
> Use another environment variable to specify a startup hook (which can be a path) which is a bootstrapper assembly that can load assemblies before Main runs. There you can hook up an assembly resolver to load whatever you need to before Main. 

**Email convo**: Context will be provided shortly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Use hosting startup assemblies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@guardrex The description box had a quotation with no context -- why is that formatted as a quote / where is the quote from?

**Comment by guardrex** [comment]
Let me get back to you on that ... big 🏃😅 *Blazor day*. :smile: lol

**Comment by guardrex** [comment]
@tdykstra *I'm back!* 🏃😅 This is from an email convo between engineering and a user. It pertains to loading hosting startup assemblies (or any assemblies apparently) before `Main` runs. I intend to work it ... unless u had another plan for this issue.

**Comment by tdykstra** [comment]
Sounds like this issue is more focused than 3.0 in general, so my suggestion is to change the title to reflect what it's actually about, link to the conversation the quote came from to provide more context, and create a separate 3.0 issue for Web Host/Generic Host plus any other 3.0 changes.

**Comment by guardrex** [comment]
Depends ... Do you (or someone else) want to work the Generic Host side? If so, *yes* ... I'll split it. I'll keep and work this issue and leave the new issue for Generic Host unassigned. If no tho, then *no* ... let's not split. Loading the assembly as described is *new for 3.0*. The title is accurate for both updates. I'm 🏃😅 most of the time and don't want to come back. *LazyRex*:tm: :smile:

WRT more context on the remark: There's no additional context at this time. It wasn't much more than a passing remark. I'll hunt it down in the engineering repo and either cross-link that in here or just work it and reference it on the PR. I'll try to do that asap, but I'm 🏃🏃🏃😅 at the moment.

**Comment by tdykstra** [comment]
You can take the Generic Host changes in this doc, but they'll be dependent on my 3.0 updates to the Generic Host doc, so you'd have to wait.  With separate issues you could go ahead with the work originally planned for this issue. If you're OK with waiting, leave it as one issue.

**Comment by guardrex** [comment]
I see. That makes sense. I thought we'd only need a link (or a couple) to existing headings. I'll split now. I have this one coming up soon.
