### ISSUE TITLE
70-486

### ISSUE THREAD

**Issue by jerimy386** [aspnet/AspNetCore.Docs#12575]
Hello Guys,

I had a question regarding the prioritization in the transport, I saw 4 types which 3 are in this page

WebSockets
Server-Sent Events
Long Polling

How do I know exactly which one came first? are they in order? It is supposed to be a 4th one, related to ajax I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
They are listed in the order they are prioritized.

The fourth transport does not exist in ASP.NET Core SignalR, you're thinking of ASP.NET SignalR, see https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr#transports-and-fallbacks

**Comment by hanhnguyen1421998** [comment]
sds
