### ISSUE TITLE
Counter page does not work.  The counter value does not increment.  

### ISSUE THREAD

**Issue by mjhillman** [aspnet/AspNetCore.Docs#12587]
Using VS2019 Preview and Core 3.0 Preview 5, I find that the Counter page does not work.  The counter value does not increment.  Seems that the event wire-up does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mjhillman ... must be an edge case scenario. There have been a couple I think (e.g., OS-related). Open it with engineering for further investigation. Be sure to give them your full particulars ... OS and OS version ... output of `dotnet --info` ... how you created the project.

https://github.com/aspnet/AspNetCore/issues
