### ISSUE TITLE
hostingModel="InProcess"  is giving me multiple Environments

### ISSUE THREAD

**Issue by dcumin39** [aspnet/AspNetCore.Docs#12596]
When i turn on logging it tells me that is is starting with Environment= Staging;Debug

I want it to use the Environment I set in the web.config.  How do I go about doing this.  Why would I ever want multiple environments like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dcumin39 ... That's a bad value. It's probably appending the value from *web.config* to a system env var for environment. See the *Warning* at :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#setting-environment-variables. If you find a system-level env var setting it to `Staging`, remove that env var.

**Comment by guardrex** [comment]
I'm going to close as answered. The behavior is by-design, and the warning should cover it.
