### ISSUE TITLE
FileUploadSample build errors on  VS 2017 Error CS1061

### ISSUE THREAD

**Issue by wadepickett** [aspnet/AspNetCore.Docs#12591]
FileUploadSample application requires an update for VS 2017 in order to build and run.  

Topic that refers to uploading the example:
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md

Location of the example FileUploadSample.sln
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/

Recreate issue with these steps:
Download and open the FileUploadSample project from its .sln in VS 2017.
Dialog asks to migrate.
Allow migration.
Build.  -- Results:  Following errors:

1>Filters\DisableFormValueModelBindingAttribute.cs(14,23,14,59): error CS1061: 'IList<IValueProviderFactory>' does not contain a definition for 'RemoveType' and no accessible extension method 'RemoveType' accepting a first argument of type 'IList<IValueProviderFactory>' could be found (are you missing a using directive or an assembly reference?)
1>Filters\DisableFormValueModelBindingAttribute.cs(15,23,15,65): error CS1061: 'IList<IValueProviderFactory>' does not contain a definition for 'RemoveType' and no accessible extension method 'RemoveType' accepting a first argument of type 'IList<IValueProviderFactory>' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "FileUploadSample.csproj" -- FAILED.

Note, the example already has an update entered for  "using Microsoft.AspNetCore.Mvc.ModelBinding;" on DisableFormValueModelBindingAttribute.cs.  

Tested on VS 2017 15.9.12

**Comment by guardrex** [comment]
There's a major sample overhaul on this topic in review at https://github.com/aspnet/AspNetCore.Docs/pull/12344. I recommend testing against that sample (in my repo) to see if this problem goes away with those updates.
