### ISSUE TITLE
Please expand on how Client-side Blazor can support offline scenarios

### ISSUE THREAD

**Issue by gojanpaolo** [aspnet/AspNetCore.Docs#12599]
Hello, it would be really helpful if you could please expand on how Client-side Blazor can support offline scenarios. Adding some links or additional resources would be greatly appreciated. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gojanpaolo ...

Thus far, we have a topic coming on calling web APIs: https://github.com/aspnet/AspNetCore.Docs/issues/10743. Authn and authz are in design and in development: https://github.com/aspnet/AspNetCore/issues/4048.

What other offline scenarios would you like to see covered?

**Comment by gojanpaolo** [comment]
@guardrex I'm not sure I understand how those topics are related to offline scenarios (maybe I'm just inexperienced with web development).
Any examples or additional resource regarding offline scenarios will help. I don't have anything specific in mind. :)

**Comment by guardrex** [comment]
A **client-side** Blazor app *is offline* in all respects. It's running out there in the browser all by itself. After it's served, there's no request-response model (unless the app is programmed to do it; e.g., web API calls).

In contrast, a **server-side** Blazor app does run on the server and SignalR provides communication between the browser and server.

I'm sure that there will be additional client-side offline scenarios, but they'll come along as devs hit a need. Those two that I mentioned are *BIG ONES* ...

* A client-side app does need to hit web APIs to get data and do things on servers. Thus far (as you can see on that PR), the `HttpClient` there is working great. Server-side Blazor is still in-design. That's also mentioned in that comment that I left on the PR.
* These apps also need authz and authn support, and that likely/usually involves interacting with identity servers. The engineering team is working on that.

... and ... another one is interacting with the browser via JavaScript interop. That's covered fairly well at this point. https://docs.microsoft.com/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0

> Any examples or additional resource regarding offline scenarios will help.

Everything we plan to have right now is either already there, in a docs PR, or in-design in engineering.

If you don't have a specific offline scenario now, then we'll keep an :ear: open as you work with the tech and see what sort of scenarios that you run into with client-side Blazor. Feel free to open an issue to ask about coverage for something.

**Comment by gojanpaolo** [comment]
@guardrex Thanks for the explanation! I'll keep reading and will start developing with Blazor. :)
