### ISSUE TITLE
Highlighted code is not actually highlighted

### ISSUE THREAD

**Issue by Omortis** [aspnet/AspNetCore.Docs#12598]
Several times in this page "highlighted code" is mentioned, but no code is highlighted that I can see (in Firefox or Chrome).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&tabs=windows#feedback)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you provide examples? I don't see any missing.

**Comment by Omortis** [comment]
I posted a screenshot [here](https://imgur.com/UYRyQdo). I don't see any lines highlighted?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/58659505-cf9bc480-82be-11e9-94f2-80aa6fceea71.png)

**Comment by Rick-Anderson** [comment]
FF
![image](https://user-images.githubusercontent.com/3605364/58659563-fa861880-82be-11e9-8a02-aca66ec72db3.png)

**Comment by Omortis** [comment]
Interesting. Looks correct at home, but neither the syntax highlighting nor the yellow-ish line highlighting display correctly at my day job.  Sorry for the static.
