### ISSUE TITLE
Cannot find the sample

### ISSUE THREAD

**Issue by ThatMouse** [aspnet/AspNetCore.Docs#12602]
The github link does not give you the download link and finally clicking on the tab gives me the master which is a LOT of projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's for different stage of the tutorial.
Why do you need the completed sample?

**Comment by ThatMouse** [comment]
The tutorial here:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio

Links to sample code to here:
https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start

But there does not appear to be a way to download just one project.

**Comment by Rick-Anderson** [comment]
By Rick Anderson

View or download sample code (**how to download**).
