### ISSUE TITLE
Why is a `private` property with `Parameter` attribute accessible outside of the component itself?

### ISSUE THREAD

**Issue by gojanpaolo** [aspnet/AspNetCore.Docs#12600]
In the example
`Counter.razor` has the following property:
```c#
[Parameter]
private int IncrementAmount { get; set; } = 1;
```

and then accessed by `Index.razor`
```c#
&lt;Counter IncrementAmount="10" /&gt;
```

This feels weird to me since `IncrementAmount` is `private`. What's the point of marking a member `private` if it can be accessed  outside of where it was defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
In this scenario where the attribute of the `<Counter>` element is setting it, it isn't "outside" of the component. Think of like "_it's setting it **on itself**_." In other scenarios, the component parameters are `public`. For an example, see the [TabSet example in the Components topic](https://docs.microsoft.com/aspnet/core/blazor/components?view=aspnetcore-3.0#tabset-example), where the child content (Tab component) needs access to the `ActiveTab` of the TabSet component.
