### ISSUE TITLE
Flow of the document could be improved

### ISSUE THREAD

**Issue by bawkee** [aspnet/AspNetCore.Docs#12609]
I just wasted almost two hours wondering why does my authorisation not work, it turns out I completely missed the critical step - having an `[Authorize]` attribute on top of the `Hub`. The document is excellent but it would be very nice if there was a bullet-list on top showing all the critical must-haves in order for the authorisation to work - there's currently too much optional stuff in-between. Maybe it'd be nice just putting a note section telling the reader that authorization *won't work by default* and that you have to decorate hubs. For Asp.net vets this is obvious but newcomers don't expect it. Other than that excellent doc, this is just a suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
>  it turns out I completely missed the critical step 

I'm sorry you missed that step, but the step is there.
