### ISSUE TITLE
Apache mod_rewrite query string matches from RewriteCond not available in RewriteRule substitution when QSD flag used

### ISSUE THREAD

**Issue by mikevh** [aspnet/AspNetCore.Docs#12613]
Using the rewrite rule below, read in from the mod_rewrites.txt. The resulting redirect does not have the report id value as expected at the end of the url. The %1 should have the value matched from the backreference to the RewriteCond line.  This rule works as I expect on Apache

```
using (var sr = File.OpenText("mod_rewrites.txt")) {
    var rwo = new RewriteOptions().AddApacheModRewrite(sr);
    app.UseRewriter(rwo);
}
```

RewriteCond %{REQUEST_URI} /home
RewriteCond %{QUERY_STRING} report_id=(.+)
RewriteRule (.*) http://localhost:64782/home/report/%1 [R=301,L,QSD]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f7c61-a9fa-bd34-001d-217477874bb6
* Version Independent ID: 9c48da92-af90-3fc1-fde0-c3f74fa88510
* Content: [URL Rewriting Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/url-rewriting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/url-rewriting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mikevh ... I'll see if I can repro here. If so, this can go to engineering for a look. I should be free later this afternoon (Friday) or certainly tomorrow (Saturday). I'll get back to u shortly.

**Comment by guardrex** [comment]
Yep ...... 😵 *brain-fried myself* 😵 today. You can 👃 the *roasting brain* over here! ... ugh.

I'll take a look at this over the weekend and get back to you.

**Comment by guardrex** [comment]
@mikevh I think you've hit a bug in the framework. Although it does seem to detect the condition, I agree that it isn't getting the captured value (if it is captured at all) into the rewrite. I went to look for some querystring tests to see how they have the rules for querystrings set up, but I don't see any for mod_rewrite: https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Rewrite/test/ApacheModRewrite/ModRewriteMiddlewareTest.cs

Open this over on the engineering repo for them to take a look at.

https://github.com/aspnet/AspNetCore/issues

If there is something special that we need to document, including anything that you find out about query string flags (I recommend that you ask them about QSA/QSD/QSL on the issue), ping me back over here and we'll re-open this issue and work on the doc.
