### ISSUE TITLE
Please describe how to bind submit button disabled state to validation IsValid

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#12617]
Given a /Page with an EditForm as shown in these docs, how would one bind the submit button's "disabled" attribute to the current validation status of the form?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dazinator ... Check over in engineering. For example, I spotted this one ...

https://github.com/aspnet/Blazor/issues/624

Let's leave this open for triage. It might be something that DR wants this topic to show.

**Comment by dazinator** [comment]
Thanks. I did have a search but I'll keep hunting and experimenting in the meantime ;-)

**Comment by PeterHimschoot** [comment]
I hope this helps...

https://blogs.u2u.be/peter/post/disabling-the-submit-button-in-blazor-with-validation

**Comment by dazinator** [comment]
I couldn't resist commenting on this:

> this is an advanced scenario

This is truly a very basic and common scenario!
It's such a simple and common requirement that it definitely should be included in the docs. Scouts honour.

I mean - have you ever seen a form on the interwebs that wont let you click the submit button until all the input is valid? If you haven't I'd be very surprised. If Microsofts cutting edge, premier, shiny new UI framework is truly the stuff of legend it will have a way to cater for this - fairly easily no doubt. I can't see it anywhere though.

**Comment by guardrex** [comment]
Some of that is engineering feedback, and I can't remark on it.

As for the rest, it was triaged, so there's no need to push the issue with so much effort. It will be worked, perhaps even this weekend. :rocket:

@mkArtakMSFT You didn't say which way to go with it ...

* Cross-link to @PeterHimschoot's topic in the Additional resources section.
* Incorporate something along the lines of @PeterHimschoot "Attempt 2" into the topic.

... or if it's TBD, no worries. I have a nice little pile of issues to work now, so I'm good.

**Comment by mkArtakMSFT** [comment]
@javiercn can you recommend the best option here?

**Comment by guardrex** [comment]
@javiercn I'm up to working this. Just need to know if the topic should incorporate something along the lines of @PeterHimschoot "Attempt 2" into the topic to resolve this issue ...

https://blogs.u2u.be/peter/post/disabling-the-submit-button-in-blazor-with-validation

... or do you just want me to cross-link his whole blog post in the *Additional Resources* section of the topic?

**Comment by javiercn** [comment]
@SteveSandersonMS Is probably a better person to recommend an option in this area.

**Comment by guardrex** [comment]
@SteveSandersonMS Quick ? for this issue that I hope to resolve today ...

For enabling/disabling the submit button based on validation, do you find something similar to @PeterHimschoot's *Attempt 2* ([blog post](https://blogs.u2u.be/peter/post/disabling-the-submit-button-in-blazor-with-validation)) acceptable for the *Forms and Validation* topic?
