### ISSUE TITLE
Blazor Client Side InputNumber Visual Studio syntax error

### ISSUE THREAD

**Issue by zzhang2001** [aspnet/AspNetCore.Docs#12616]
In a Blazor Client Side project, the InputNumber tag causes Visual Studio to show an error.

`            <InputNumber id="todoPriorityNumber" bind-value="@newTodo.PriorityNumber" class="form-control" />
`

This is the error message.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'TypeInference.CreateInputNumber_0<T>(RenderTreeBuilder, int, int, string, int, string, int, object, int, object)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	BlazorClient1	C:\Users\vmtest\source\repos\BlazorClient1\BlazorClient1\Pages\Todo.razor	1	Active

However, the project can be compiled without error.

Changing bind-value to bind-Value (uppercase V) seems make the error going away. However, the bind attribute should not be case sensitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zzhang2001 ... Open this over in the engineering issues for them to take a look at.

https://github.com/aspnet/AspNetCore/issues
