### ISSUE TITLE
Configuration in Blazor/.NET Core 3.0

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#12614]
Noticed the Startup.cs is very "clean" and doesn't implement IConfiguration. I'd like to make a connection to Key Vault and CosmosDB using my own interfaces/services implementation. Is it safe to assume I can add the `Microsoft.Extensions.Configuration` package and inject IConfiguration in Startup.cs like a .NET Core 2.x project or is it done differently in 3.0/Blazor? 

Also, can I create my own `appsettings.json' and `appsettings.Development.json' files with the expectation they'll be picked up by IConfiguration in Startup.cs as usual? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jasonshave ... The short answer is "kind'a yes" ... like if you were working with a console app. You can do something like this (**Warning:** *RexHacks*:tm: 🙈 *follow!*) ...

```xml
<PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0-preview6.19222.10" />
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.0.0-preview6.19222.10" />
```

```csharp
// Bring in the namespace: using Microsoft.Extensions.Configuration;

public void ConfigureServices(IServiceCollection services)
{
    var config = new ConfigurationBuilder()
        .AddInMemoryCollection(new System.Collections.Generic.Dictionary<string, string> { { "key", "value" } })
        .Build();
    services.AddSingleton(config);
}
```

Component:

```cshtml
@using Microsoft.Extensions.Configuration
@inject IConfigurationRoot Configuration

@Configuration["key"]
```

**_BUT_** ... the real answer is that this is in-design :point_right: https://github.com/aspnet/AspNetCore/issues/5531

I'll close as answered. Feel free to discuss your needs/scenarios on that engineering issue. We'll document the bits when they become available.

**Comment by jasonshave** [comment]
Of course! This makes perfect sense. I'm still wrestling with .NET as a SPA. Cheers.
