### ISSUE TITLE
Disposal of objects does not state what happens for HttpReponseMessage objects

### ISSUE THREAD

**Issue by ggirard07** [aspnet/AspNetCore.Docs#12621]
The section about [object disposal](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#disposal-of-objects) clearly indicates what will happen on test completion for the `WebApplicationFactory` and its servers and clients, all will be disposed by xUnit while disposing the `IClassFixture`.

But what about the `HttpReponseMessage` returned by the clients? Will there be disposed too?
Because sample code provided here clearly don't handle this, and according to disposal section xUnit/WebApplicationFactory won't too...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#disposal-of-objects)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ggirard07 ... AFAIK, the answer is *Yes*, but I'll mark your question for the Product Unit ("PU") to address.

Cross-ref: https://github.com/aspnet/AspNetCore.Docs/issues/6292

**Comment by guardrex** [comment]
I'm walking the Testing project issues and trying to resolve what I can today. AFAIK, anything that disposes on its own *will do so*, and anything that a dev needs to dispose on their own *they must manage*. That's true anywhere in the framework. We can't call out every object that might require it here. We do need to address the `IClassFixture`. Beyond that tho, we just can't call out every possible object that might require explicit disposal.
