### ISSUE TITLE
PWA's ?

### ISSUE THREAD

**Issue by SogoGolf** [aspnet/AspNetCore.Docs#12627]
We're new to PWA's (vs. native mobile app dev) and are interested in knowing whether we can use C#, .Net Core & Blazor to build PWA's. Could you add a topic about that on this page ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-NV60elOCB10BOp2dM808Nw&epi=je6NUbpObpQ-NV60elOCB10BOp2dM808Nw&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir__al22klrnk0kfrmes0h0nh3m2kv2xmdfx0ynnf66600)(7593)(1243925)(je6NUbpObpQ-NV60elOCB10BOp2dM808Nw)()&irclickid=_al22klrnk0kfrmes0h0nh3m2kv2xmdfx0ynnf66600&view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is under discussion and in-design in the following engineering issues ...

* https://github.com/aspnet/AspNetCore/issues/5479
* https://github.com/aspnet/AspNetCore/issues/5475

Additional community remarks ...

* https://github.com/aspnet/AspNetCore/issues/9938#issuecomment-489599368
* https://github.com/aspnet/AspNetCore/issues/5465#issuecomment-418459302

We'll have an issue for this when it becomes a supported scenario.
