### ISSUE TITLE
Missing step in getting started for Visual Studio

### ISSUE THREAD

**Issue by Jacob-McKay** [aspnet/AspNetCore.Docs#12624]
Just followed steps in the getting started section for Visual Studio 2019.  There was no mention of telling Visual Studio to use preview versions of .NET Core but until I did that I got build errors in the template solution.  This issue helped me figure it out: https://github.com/aspnet/AspNetCore/issues/8074#issuecomment-496594135

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Jacob-McKay ... VS release versions aren't supported. Only VS preview is supported, which uses preview SDKs by default.
