### ISSUE TITLE
Why RegisterPostEvictionCallback is not invoked, when cache is expited

### ISSUE THREAD

**Issue by MNF** [aspnet/AspNetCore.Docs#12634]
It will be good to add clarification on this page, why RegisterPostEvictionCallback is not invoked, when cache is expited 
It is explainined on https://github.com/aspnet/Caching/issues/248#issuecomment-258571802 Expiration almost never happens on it's own in the background #248
, but it’s useful enough to be included in documentation, as well as workaround:

Rather than using SetAbsoluteExpiration(TimeSpan.FromHours(1)) you could instead use CancellationTokenSource.CancelAfter(TimeSpan.FromHours(1)) for the token you're already registering. When this token fires it will remove the entry immediately and fire the eviction callbacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MNF  thanks for bringing this to our attention. #13812 fixes this and should be published in a few days.
