### ISSUE TITLE
Reload an aseembly in a blazor client app.

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#12638]
I'd like to know whether it is possible, for a running blazor client app, and within the browser:

1. Stop the application
2. Reload only particular assemblies from the server that it is known have changed 
3. Restart the application

My scenario is that I have my own javascript library on the page that receives notifications from the server when dll's there are changed relating to the running blazor client app. When these events occur I'd like to perform the above cycle using javascript - I.e stop the blazor client app, reload preferably only the modified dll's, and then restart the blazor app. I'd like to avoid a full page reload if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@dazinator Ask in engineering ...

https://github.com/aspnet/AspNetCore/issues
