### ISSUE TITLE
Visual Studio preview should change to Visual Studio 2019

### ISSUE THREAD

**Issue by OnurGumus** [aspnet/AspNetCore.Docs#12630]
The first step says:
1. Install the latest Visual Studio preview with the ASP.NET and web development workload.

I guess that's no longer valid. It should say Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @OnurGumus ... The document's text is correct. Engineering only recommends VS 2019 **preview** for Blazor development. One can use VS 2019, but it's rough ... lots of rough edges and quirky IDE behavior. I know because I'm using 16.0.2 right now with it (I can't install preview ... I'm running out of HD space 🙈).

**Comment by OnurGumus** [comment]
@guardrex, but 16.1 is out already?

**Comment by guardrex** [comment]
Correct, but engineering says that the preview release should always be used during Blazor preview, which is at 16.2 Preview 1 ...

https://docs.microsoft.com/visualstudio/releases/2019/release-notes-preview
