### ISSUE TITLE
Bad redirect in gRPC tutorials

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#12633]
Visiting https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-client?view=aspnetcore-3.0&tabs=visual-studio will redirect to a 404.

Likely cause: https://github.com/aspnet/AspNetCore.Docs/pull/12522/files

The ideal redirect for the old grpc-client tutorial is https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start#create-the-grpc-client-in-a-net-console-app

**Comment by Rick-Anderson** [comment]
@JamesNK  it's redirecting correctly now. Thanks for the heads up.
