### ISSUE TITLE
How to access a net instance from a javascript event?

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore.Docs#12649]
I created a component whose BuildRenderTree method emits a "div" element. I need that div "onscroll" event to execute some JavaScript and call to the component after it. How can I achieve that?
Notice the given sample in the documentation doesn't show how to access the component from an event. It passes the reference from the server, but this is not applicable in my case, and probably in most cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@arivoir Clarify it a bit more ...

> Notice the given sample in the documentation doesn't show how to access the component from an event.

It shows calling from JavaScript. If the event can call JS, it *should be able to* 🤞 call a component method (*in theory* :smile:). Are you saying that this is specific to the `BuildRenderTree` scenario? Are you saying that it works with an `onscroll` present and wired up in the component's markup but not when created using `BuildRenderTree`?

> It passes the reference from the server, but this is not applicable in my case, and probably in most cases.

"and probably in most cases." ... you mean specifically in most cases when using `BuildRenderTree`?

**Comment by arivoir** [comment]
Hi @guardrex 
Let me clarify.

In order to call a method of the component from JavaScript it is necessary to have a reference

> Pass the .NET instance to JavaScript by wrapping it in a DotNetObjectRef instance. The .NET instance is passed by reference to JavaScript.

In the sample shown it passes the reference from the server

```
    public Task CallHelloHelperSayHello(string name)
    {
        // sayHello is implemented in wwwroot/exampleJsInterop.js
        return _jsRuntime.InvokeAsync<object>(
            "exampleJsFunctions.sayHello",
            new DotNetObjectRef(new HelloHelper(name)));
    }
```

But in my case, I need the call to the component to be invoked directly from JavaScript (specifically from a function called onscroll event of div)

So I'm wondering whether there is a way to get the dotnet component reference from JavaScript? 

Maybe I could pass the reference on the OnAfterRenderAsync method on the component and save it somewhere so when the onscroll event is raised I can use it, but this will need a separate call from server to the client every time the component is rendered. I bet this will be bad design. If I could somehow pass the reference in the BuildRenderTree, that would avoid the extra call.

Do you see my point?

**Comment by guardrex** [comment]
I see. In the instance method scenario, I don't know. I was hoping to hear that perhaps you figured out a workaround for your scenario that uses the static method call approach. Anyway ..... it's definitely best for you to ask engineering ... open an issue for them at :point_right: https://github.com/aspnet/AspNetCore/issues.

I'll close here. If you get a good approach from them that you feel we should call out in the doc, ping me back over here on this issue, and I'll re-open it for triage. Just cross-link the engineering issue and solution/workaround into your comment here, and we'll use the referenced engineering issue for the docs work.
