### ISSUE TITLE
YouTube tutorial on DI 

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#12648]
A youtube tutorial on dependency injection is available at https://www.youtube.com/watch?v=ZFeyrXQpuoA
If you like please put your likes and share it with others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d2cf2e-55fb-33a4-b1d4-c97b2d531741
* Version Independent ID: f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf
* Content: [Dependency injection into controllers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@krchome  thanks!
