### ISSUE TITLE
SignalR sample launch in Visual Studio Code on Linux

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#12644]
[EDIT by @guardrex to remove issue template boilerplate.]

How to launch the SignalR sample from Visual Studio Code on Linux? It doesn't work as http://localhost:5000/index.html is not found.

```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.204/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.204 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by guardrex** [comment]
Helllo @khteh ... Which topic are you looking at? Note that it's best to open an issue using the **This Page** feedback button at the bottom of the topic (if possible). It adds metadata to the issue to help us track the source (in this case the sample) that might require work.

**Comment by khteh** [comment]
I am referring to this one: https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/signalr/sample and there is no "This Page"

**Comment by guardrex** [comment]
I see ... it goes with this topic :point_right: https://docs.microsoft.com/aspnet/core/tutorials/signalr

**Comment by guardrex** [comment]
Thanks @khteh ... see how it has the author's GH mention? ... we get auto-pings, too, when they go in that way. It isn't always possible to do it, but it helps.

This issue moved to :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/12651
