### ISSUE TITLE
Listing of Return Types

### ISSUE THREAD

**Issue by jkrollin** [aspnet/AspNetCore.Docs#12650]
Just wondered where is a list of ALL ActionResult Return Types? Just think it might be an idea as the title of this doc makes it sound like you list them all here but instead presented with many words and confusing examples, just a simple one line example showing usage and a list of them would be great 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hit **More ...** under **Derived** here :point_right: https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.iactionresult

Since they're subject to change, I wonder if the link to the API Browser is enough? ... but perhaps with an explicit instruction on how to get to them there.

**Comment by douglasg14b** [comment]
Similarly having a clear list of all the controller helper methods like `OK`, `BadRequest`, `NotFound`...etc would be very helpful as this seems particularly hard to find...
