### ISSUE TITLE
expired session does not get recreated

### ISSUE THREAD

**Issue by rtbsoft** [aspnet/AspNetCore.Docs#12655]
the docs above say:

If a cookie is received for an expired session, a new session is created that uses the same session cookie.

However, I'm getting this repeatedly in my logs:

[Microsoft.AspNetCore.Session.DistributedSession]	[2]	Accessing expired session, Key:5d353988-4d84-f1b9-3f94-03aa05b07cbd

the client is polling every 5 seconds, and it complains with the same key every time.

I'm using this setup:

            services.AddDistributedMemoryCache();
            services.AddSession(options =&gt;
            {
                options.IdleTimeout = TimeSpan.FromMinutes(20); //default session timeout
                options.Cookie.HttpOnly = true;
            });

and it happens after the webserver spontaneously restarted (1 second after a poll from client) and this:

[Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager]	[0]	User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-2448291975-4234089047-1793108301-2903605371-3779044736\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.

appeared in the log.

I suspect that the in memory session cache was lost and recreated. I can live with that, but why does it insist on letting the client keep trying with the same invalid session key? Browser is Chrome, if that helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> but why does it insist on letting the client keep trying with the same invalid session key?

It can't force the client into not using an invalid session key. You're right, once the server restarts, all of session is lost unless you're using a persistent session provider.
