### ISSUE TITLE
launch in Visual Studio Code on Linux fails with index.html not found

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#12651]
How to launch the SignalR sample from Visual Studio Code on Linux? It doesn't work as it opens up browser pointing to http://localhost:5000/index.html not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
thanks for the report @khteh - could you let us know which distro of linux you're using?

**Comment by khteh** [comment]
https://github.com/aspnet/AspNetCore/issues/10873

**Comment by khteh** [comment]
Switch to use `IPAddress.Any` works.
