### ISSUE TITLE
Update Web API tutorial for VS19

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#12675]
Update Web API tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett can you update this for VS19? See the RP and MVC versions.

**Comment by wadepickett** [comment]
@Rick-Anderson, yes, thank you!

**Comment by guardrex** [comment]
Side note on the updates: This topic is used as a basis for the Blazor 'call a web API' topic. If the endpoints of the sample app are changed, plz ping me. The Blazor app hits the endpoints of this sample app for data. If the endpoints change here, I'll mirror those changes over on that PR.

https://github.com/aspnet/AspNetCore.Docs/pull/12477

**Comment by wadepickett** [comment]
@guardrex, thanks for the heads up!  I will avoid changing the endpoints, but if I have to change them for some reason I will loop you in.

**Comment by wadepickett** [comment]
In this topic now finally, updating screenshots and verifying instructions against VS19.  I see a few minor changes have hit it the last few days and have synced, thanks.

**Comment by wadepickett** [comment]
PR for this was merged successfully 6/24/19 for VS for Windows updates:
PR #12989

**Comment by Rick-Anderson** [comment]
@wadepickett  you need to put `Fixes #12675` in the PR, not `Fixes # 12675`  - that way the issue is closed automatically.

**Comment by wadepickett** [comment]
Understood.  Thanks for the help Rick.
