### ISSUE TITLE
ConfigureKestrel IPAddress.Loopback does NOT work

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#12671]
I use ConfigureKestrel in order to enable protocol HTTP1.x and HTTP2. However, using IPAddress.Loopback does not work! The browser opens up 127.0.0.1/index.html and show "Page not found"! Modify the URL at the browser address bar to "localhost" works!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
I've not seen that behavior when configuring a listen address with `IPAddress.Loopback`. When I use it, it always gives me an `127.0.0.1` endpoint here, which is what the API doc states will be used.

You can ask the engineers about it, but be sure to give them full info: They'll need to know your platform/OS version, SDK/runtimes installed (the output of `dotnet --info`), and at least the `ConfigureKestrel` code block with `Listen` configuration that you're using ... they might even want to see a minimal repro app put up on GH that produces the behavior.

https://github.com/aspnet/AspNetCore/issues

I'll close here; but if you discover something undocumented that we need to surface, please do ping me back on this issue. Link the engineering issue here, and we'll take a look.

**Comment by khteh** [comment]
```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.204/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.204 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
https://github.com/khteh/AspNetCoreApiStarter

**Comment by guardrex** [comment]
Open a new issue at :point_right: https://github.com/aspnet/AspNetCore/issues
