### ISSUE TITLE
Move Blazor Circuit Handler content

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#12687]
We need to create docs for `CircuitHandler`. This is a server-side blazor feature that lets users register a *lifecycle filter* for a server-side blazor hive of components

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/Circuits/CircuitHandler.cs

**Comment by nagytam** [comment]
An example project to demonstrate the CircuitHandler is available at GitHub: https://github.com/nagytam/BlazorCircuitHandler.

**Comment by mkArtakMSFT** [comment]
This has been done by @pranavkm: https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#blazor-server-circuit-handlers

@guardrex let's move this out from the `Error handling` section. It should be some root-level item under hosting model. Also, this can go into (as a link) under the advanced topics for Blazor.

**Comment by guardrex** [comment]
Sure thing ..  an existing PR does a lot of other work here, so I'll take care of this right after that work merges.
