### ISSUE TITLE
Mention LinkGenerator as an alternative to IUrlHelper.

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore.Docs#12682]
To generate URL's `LinkGenerator` class also can be used, and some of its methods do not require any context contrary to `IUrlHelper` which [won't be resolved by default](https://stackoverflow.com/questions/37322076/injection-of-iurlhelper-in-asp-net-core).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#url-generation)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson It's covered in the Routing topic, and `IUrlHelper` uses the Link Generator under-the-covers. Since the context is available in a controller and the Routing topic is already cross-linked here, I don't think this is actionable.

https://docs.microsoft.com/aspnet/core/fundamentals/routing#url-generation

**Comment by voroninp** [comment]
@guardrex  So docs contain 2 sections about URL generation. It would be nice to crosslink them at least. 

Google shows me  this [one](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#url-generation) first for search query `asp.net core url generation`.

And when I have two options with titles:
**Routing to controller actions in ASP.NET Core | Microsoft Docs** and **Routing in ASP.NET Core | Microsoft Docs** I will obviously select the former one, because that's exactly what I am interested in: _I am trying to find out how to generate absolute url outside controller for hitting particular action._

**Comment by guardrex** [comment]
They are cross-linked. First paragraph in the controllers topic's *URL generation* section, *Routing* is linked over ...

> See Routing for a detailed description of URL generation.

It's also linked in the introduction (*Routing* is linked) ...

> This document will explain the interactions between MVC and routing, and how typical MVC apps make use of routing features. See Routing for details on advanced routing.

In the Routing topic, *Action Results* is linked over ...

> The API can be used outside of the context of an executing request. MVC's IUrlHelper and scenarios that rely on IUrlHelper, such as Tag Helpers, HTML Helpers, and Action Results, use the link generator to provide link generating capabilities.

WRT the rest, you didn't explain that when you opened the issue. Your request is clear now. At first, it just sounded like you were asking for cross-linking, which is already present.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
