### ISSUE TITLE
dotnet new blazor supposed to be client side model?

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#12684]
I just tried `dotnet new blazor` as mentioned in this article, and it created a project that runs server side blazor, not client side. Can this be clarified? I'm trying to create a pure client side blazor project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#client-side)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ask in engineering because that sounds like a real bug. If you get an answer that we need to surface, ping me back on this issue to re-open and address the engineering remarks to the readers.

https://github.com/aspnet/AspNetCore/issues

**Comment by guardrex** [comment]
... BUT ... make sure that you installed the templates.

```console
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01
```
