### ISSUE TITLE
Need to execute `StateHasChanged()` after submit

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#12683]
Please review: https://stackoverflow.com/questions/56436577/blazor-form-submit-needs-two-clicks-to-refresh-view/56438679#56438679

Should we mention this method call is required if a component is updated on a form `submit`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Wondering if databinding that weather object would have resulted in a re-render without calling `StateHasChanged`. I'll label this for DR to take a look.

Our `StateHasChanged` coverage is light in the sense that it's not specific about the scenarios where it must be called. DR ... Can you give me the list of cases where it must be called? I'll place the scenarios where we first talk about `StateHasChanged` in the *Components* topic. If it should be surfaced here in the forms validation doc, I'll cross-link it here.

**Comment by jasonshave** [comment]
I'm happy to give it a quick test. In what way would you suggest the data binding to happen? Are you suggesting binding it to a form element in some way?

**Comment by guardrex** [comment]
Strike that ... I don't see why `StateHasChanged` is required in that scenario, and the SO answer (the reasoning) doesn't sound correct (or at least complete). We need engineering to take a look.

**Comment by endstreet** [comment]
There are many instances where state has changed. of the submitted for updated the record ofn the page it is reguired.
very common if you have a modal form editing a record. thes tatehaschanged is required to close the modal after a succesfull submit.
I cant even imagine there is a test case where you do not want to update the client on the success of the submit.

**Comment by mkArtakMSFT** [comment]
I've posted a correct explanation to the issue in the StackOverflow. And we already cover this (when to call `StateHasChanged`) in our docs: https://docs.microsoft.com/aspnet/core/blazor/components
