### ISSUE TITLE
Inconformity in MvcMovieContext.cs Location

### ISSUE THREAD

**Issue by GRXself** [aspnet/AspNetCore.Docs#12680]
This article first said:  `Add the following MvcMovieContext class to the Models folder:`
So, the MvcMovieContext.cs should be placed in Models folder.
But later in `Initial migration` chapter,  it said `The database schema is based on the model specified in the MvcMovieContext class (in the Data/MvcMovieContext.cs file). `
So, this time, the MvcMovieContext.cs should be placed in Data folder.
Please solve this problem ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio-code#initial-migration)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It doesn't matter where you put it. The VS scaffolder puts it in Models folder with Data in the namespace. I'll make sure the next version is consistent..

**Comment by Rick-Anderson** [comment]
BTW, I've removed 
The database schema is based on the model ~(in the Data/MvcMovieContext.cs file)~
