### ISSUE TITLE
There should be a section about certificates etc.

### ISSUE THREAD

**Issue by christiansparre** [aspnet/AspNetCore.Docs#12697]
The gRPC features are very exciting, but I hit a snag immediately using the templates. When the ASP.NET Core gRPC service was not setup using TLS/HTTPS, I changed that immediately by reflex, TLS all the things :)

But when using the client you can either have it use SslCredentials.Insecure (now goes against every fiber of my being, hehe) or manage certificates and keys manually which is a pain I think.

I'm not sure why you manually have to handle that, I was looking at the new managed client using HttpClient, but that is the same deal I think. I don't know enough about gRPC, TCP, HTTP/2 and TLS to understand why :)

So a section in the docs explaining why that is and best practices for managing certificates etc. would be a good idea if we, for some reason, are not able to just let HttpClient handle it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JamesNK** [comment]
In preview 7 the docs will recommend using HTTPS everywhere via the new HttpClient driven gRPC client

Related PR: https://github.com/aspnet/AspNetCore.Docs/pull/13051

**Comment by scottaddie** [comment]
Fixed in https://github.com/aspnet/AspNetCore.Docs/pull/13051
