### ISSUE TITLE
Provide guidance on where to keep non-page components

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12690]
> Instead of creating a new Components folder, consider putting PlanetDetails.razor under Shared.

https://github.com/aspnet/AspNetCore.Docs/pull/12623#issuecomment-498690449

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 What's your advice for *where* non-page components should be placed between *Components* and *Shared* folders? ... or should they always go with the *Shared* folder?

**Comment by danroth27** [comment]
Components are just classes. They really can go anywhere you want. I just figured we already had one random folder in the template for non-page components that there was no reason to create another one for this tutorial.
