### ISSUE TITLE
Call out package for Redis cache

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [aspnet/AspNetCore.Docs#12693]
My code in `ConfigureServices()`:
            
```cs
            Microsoft.Extensions.DependencyInjection.RedisCacheServiceCollectionExtentions x; // Just test if the class exists.
            services.AddStackExchangeRedisCache(options =>
            {
                options.InstanceName = Configuration["Redis:InstanceName"];
                options.Configuration = Configuration["Redis:Configuration"];
            });
```

My .csproj includes:
```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.AspNetCore.DataProtection.Kms" Version="1.0.0-alpha02" />
    <PackageReference Include="Google.Cloud.AspNetCore.DataProtection.Storage" Version="1.0.0-alpha02" />
    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="3.0.0-beta13" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="StackExchange.Redis" Version="2.0.601" />
  </ItemGroup>
```

The error messages I see:
```
Startup.cs(40,54): error CS0234: The type or namespace name 'RedisCacheServiceCollectionExtentions' does
not exist in the namespace 'Microsoft.Extensions.DependencyInjection' (are you missing an assembly reference?) [C:\Users\rennie\gitrepos\getting-started-dotnet\Sessions\Sessions.csproj]
Startup.cs(41,22): error CS1061: 'IServiceCollection' does not contain a definition for 'AddStackExchangeRedisCache' and no accessible extension method 'AddStackExchangeRedisCache' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [C:\Users\rennie\gitrepos\getting-started-dotnet\Sessions\Sessions.csproj]
```
Full code lives here: https://github.com/SurferJeffAtGoogle/getting-started-dotnet/tree/Sessions/Sessions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @SurferJeffAtGoogle ... The fact that the package isn't called out is probably leftover from the days when the Redis package was included in the `Microsoft.AspNetCore.All` package. Now that we're using the `Microsoft.AspNetCore.App` package, it doesn't come in unless you add it. I'll add the NuGet package to the coverage there.

You'll need to add a package reference for it to your project file ...

Latest stable version of the package for .NET Core 2.2:

https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis/2.2.5

```xml
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="2.2.5" />
```

Here's the 3.0 preview package if your app is targeting 3.0 Preview 5:

https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis/3.0.0-preview5.19227.9

```xml
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="3.0.0-preview5.19227.9" />
```

You can leave this issue open. It will automatically close when the PR merges.

**Comment by guardrex** [comment]
... and I just spotted ...

```xml
<PackageReference Include="StackExchange.Redis" Version="2.0.601" />
```

... in your code. Swap the 2.2.5 one that I provided for that one. :point_up:

**Comment by guardrex** [comment]
... and some good news. This is already covered in the topic in the Prereqs section ...

https://docs.microsoft.com/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#prerequisites
