### ISSUE TITLE
Privacy link doesn't redirect to the log in page

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#12698]
When the app is running and in the Log out state, privacy link doesn't redirect to the log in page even when the [Authorize] attribute to the Privacy page is in place. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#scaffold-register-login-and-logout)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I can't reproduce the problem.

**Comment by krchome** [comment]
I followed your tutorial step by step and created the app, Scaffolded the Register, Login, Logout pages. Then as per the Test Identity section wrote as follows: 

Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
When the app was run and I navigated to the Privacy link it didn't require login .

If you wish I could share the code as a GitHub link

**Comment by krchome** [comment]
I am using Visual Studio 2017 where putting [Authorize] as an attribute on the Privacy page is showing a compile-time green squiggly "AuthorizeAttribute cannot be applied to Razor Pages handler methods....."
Probably I shall need to upgrade to VS2019 to get it going.

**Comment by Rick-Anderson** [comment]
Apply it to the class.

**Comment by Rick-Anderson** [comment]
Per the article
```
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
```
