### ISSUE TITLE
Move "SignalR connection lifetime handling" section to the SignalR docs

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#12716]
The section about Improved [SignalR connection lifetime handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#improved-signalr-connection-lifetime-handling) doesn't belong in this doc (my bad!) and should move to the SignalR docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
oops ... https://github.com/aspnet/AspNetCore.Docs/issues/12715

Beat you by 10 seconds. 🏃

I'll close that.

**Comment by guardrex** [comment]
Looks like we only need to delete it in Blazor ...

https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#automatically-reconnect
