### ISSUE TITLE
What are the changes required for a Razor library?

### ISSUE THREAD

**Issue by fleed** [aspnet/AspNetCore.Docs#12711]
I'm referencing the `Microsoft.NET.Sdk.Razor` Sdk for a Razor library.
When trying to target .net core 3.0 I get the following warning:

```
/usr/local/share/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets(803,5): warning RAZORSDK1004: One or more Razor view or page files were found, but the project is not configured to add Razor support for MVC. The MSBuild property 'AddRazorSupportForMvc' must be set to correctly compile Razor files that target MVC. For more information, see https://go.microsoft.com/fwlink/?linkid=868374.
```

and some additional errors, but I think that they are all related to the warning above.

PS: I'm adding a `FrameworkReference` to `Microsoft.AspNetCore.App` in the project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
See the following section for instructions: https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#razor-class-library.
