### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by Svetomechc** [aspnet/AspNetCore.Docs#12727]
Is it possible to configure? No mention on the docs page.

I have some unwanted behaviour: my frontend shows you are logged in whereas in fact the token is already expired and backend sends 401 Unauthorized.

See example (upper left corner - credentials and logout button):

![image](https://user-images.githubusercontent.com/36156020/59050353-d31ce600-8892-11e9-84c5-7f49881c3632.png)

This seems like a strange behaviour, if not a bug.

P.S. I used command `dotnet new angular -o <output_directory_name> -au Individual` from [this ASP.NET Core version](https://github.com/aspnet/AspNetCore/tree/v3.0.0-preview5-19227-01).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Svetomechc** [comment]
Related question: is it possible to use refresh tokens here?

**Comment by Svetomechc** [comment]
@javiercn, sorry to bother, but could you please share your thoughts?

**Comment by javiercn** [comment]
This should work, if not. Its either something is not configured right on the templates or the underlying library has a bug. As far as I understand the library is properly configured.

**Comment by Svetomechc** [comment]
@javiercn here's a more appropriate example:

![image](https://user-images.githubusercontent.com/36156020/59276992-06cb8780-8c68-11e9-8e12-a15f80512a85.png)

Steps to reproduce:
1. Register and login via Identity Server
2. Wait some time
3. Try to access data from **[Authorize]** controller

**Comment by marno11** [comment]
Has this issue been resolved in preview7?

...I am unable to recreate this issue in this preview...

**Comment by Michaelwan777** [comment]
@Svetomechc  It seems that the app fails to renew the token as you mentioned.

**Comment by Svetomechc** [comment]
@Michaelwan777 indeed it does! Hope this gets resolved before ASP.NET Core 3.0 stable release.

**Comment by asad-c** [comment]
Has anyone figured out a work around for this?

**Comment by Svetomechc** [comment]
@asad-c, nope, I just redirect to login page if that happens.

**Comment by caihongxu** [comment]
I encountered the same issue and would like to see if someone could look into this issue. Thanks.

**Comment by asad-c** [comment]
I couldn't wait for this to get resolved so had to create the individual projects myself (Angular client, API and IdentityServer) and it's working as expected.

**Comment by caihongxu** [comment]
Care to share any details/pointers how you resolved this?

**Comment by asad-c** [comment]
> Care to share any details/pointers how you resolved this?

For me to get this to work was a combination of the IdentityServer quickstart tutorials:
https://identityserver4.readthedocs.io/en/latest/quickstarts/0_overview.html

And the following Pluralsight course:
https://app.pluralsight.com/library/courses/openid-and-oauth2-securing-angular-apps/table-of-contents

The IdentityServer docs give an example of a vanilla JavaScript client, but the Pluralsight course shows how to implement an Angular client.

**Comment by Svetomechc** [comment]
@asad-c a bit tiresome if you ask me, compared to `dotnet new angular -o <output_directory_name> -au Individual`. Also, I thought they'd change _Implicit Flow_ to _Authentication Code Flow_ with 3.0 release, but they haven't. Oh well, I guess this template is deserted.

**Comment by javiercn** [comment]
@Svetomechc The template uses authorization code + pkce

**Comment by Svetomechc** [comment]
@javiercn [you're right](https://github.com/aspnet/AspNetCore/commit/7bf660947baf8966cd65ae6a3708cf283576dc25), I looked at the wrong place - forgot that the authorization code was in **Microsoft.AspNetCore.ApiAuthorization.IdentityServer** package, not in the template itself. 
Still, the problem in this issue stands.

**Comment by berik** [comment]
@Svetomechc does this happen in production as well?

**Comment by Svetomechc** [comment]
@berik, no, it currently doesn't happen in production for me. But it's been popping out **iframe**s like crazy, some 20-ish of them.

**Comment by caihongxu** [comment]
It does happen in production to me. Svetomechc, how did you configure your production differently other than setting the environment to production?

**Comment by Svetomechc** [comment]
@caihongxu there are a lot of modifications to my production code (for example I use MongoDB for storing users), so I can't list them all, especially because I have no idea what worked around* token expiration.

*though I'm still waiting for the fix proper, as 20+ iframes for authorization slows down my application at startup pretty heavily

**Comment by yakeer** [comment]
In fact, it happens to me as well,
After I deploy a new version, and I relogin, I get 401 error for every request I send using the new token.

For a strange reason, it happens only on production, and not in development mode.
If anyone has succeeded to figure this out, I would really appreciate his help.

**Comment by Svetomechc** [comment]
@yakeer this happens to me to, by the way, and I haven't found a solution. But I've found a workaround:

![image](https://user-images.githubusercontent.com/36156020/69791096-d99e7180-11d4-11ea-8d02-9609e1a80816.png)

**authorize.interceptor.ts**
```ts
import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler, HttpEvent, HttpErrorResponse } from '@angular/common/http';
import { Router, ActivatedRoute } from '@angular/router';
import { Observable, throwError } from 'rxjs';
import { mergeMap, catchError } from 'rxjs/operators';
import { AuthorizeService } from './authorize.service';
import { AppRoutes } from '../app-routes';

@Injectable({
  providedIn: 'root'
})
export class AuthorizeInterceptor implements HttpInterceptor {
  constructor(private authorize: AuthorizeService, private router: Router, private activatedRoute: ActivatedRoute) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return this.authorize.getAccessToken()
      .pipe(mergeMap(token => this.processRequestWithToken(token, req, next)));
  }

  // Checks if there is an access_token available in the authorize service
  // and adds it to the request in case it's targeted at the same origin as the
  // single page application.
  private processRequestWithToken(token: string, req: HttpRequest<any>, next: HttpHandler) {
    if (!!token && this.isSameOriginUrl(req)) {
      req = req.clone({
        setHeaders: {
          Authorization: `Bearer ${token}`
        }
      });
    }
    const pathname = window.location.pathname;
    return next.handle(req).pipe(catchError(err => {
      if (err instanceof HttpErrorResponse) {
        if (err.url.includes('Identity/Account/Login') && !pathname.includes(AppRoutes.authorizationLogin)) {
          this.router.navigate([AppRoutes.authorizationLogin], { queryParams: { ReturnUrl: pathname } });
        }
      }
      return throwError(err);
    }));
  }

  private isSameOriginUrl(req: any) {
    // It's an absolute url with the same origin.
    if (req.url.startsWith(`${window.location.origin}/`)) {
      return true;
    }

    // It's a protocol relative url with the same origin.
    // For example: //www.example.com/api/Products
    if (req.url.startsWith(`//${window.location.host}/`)) {
      return true;
    }

    // It's a relative url like /api/Products
    if (/^\/[^\/].*/.test(req.url)) {
      return true;
    }

    // It's an absolute or protocol relative url that
    // doesn't have the same origin.
    return false;
  }
}
```

**Comment by joshpearce** [comment]
For refresh token not working, are you using a persistent store for Identity Server's operational data? If not, then it's just the in-memory store, which means the refresh tokens would disappear when the process restarts.

https://identityserver4.readthedocs.io/en/latest/reference/ef.html#operational-store-support-for-authorization-grants-consents-and-tokens-refresh-and-reference

**Comment by Svetomechc** [comment]
@joshpearce of course I am. [https://github.com/matteofabbri/AspNetCore.Identity.Mongo](AspNetCore.Identity.Mongo) in particular. The issue is not specific to the store, though. It remains if I switch over to EF Core and SQLite / SQL Server.

**Comment by berik** [comment]
@joshpearce thank you. This solved my issue.
I've added 
```
.AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly("Infrastructure"));
                     // Change "Infrastructure" to "typeof(Startup).GetTypeInfo().Assembly.GetName().Name;"
                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30; // interval in seconds
                })
```

And whole picture

```
public void ConfigureServices(IServiceCollection services)
        {            
            var connectionString = Configuration.GetConnectionString("DefaultConnection");
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(connectionString));
            services.AddDefaultIdentity<ApplicationUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
            
            services.AddIdentityServer()
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly("Infrastructure"));
                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30; // interval in seconds
                })
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

            services.AddAuthentication()
                .AddIdentityServerJwt();

            services.AddControllersWithViews();
            services.AddRazorPages();
            services.AddSpaStaticFiles(configuration => { configuration.RootPath = "ClientApp/build"; });
        }

**Comment by Svetomechc** [comment]
@berik are you sure the problem has disappeared after that?

**Comment by berik** [comment]
@Svetomechc for the first time, i've left running localhost for overnight and next morning it was working. Today I've repeated same action, but it started not working. So it didn't solve the issue :(

**Comment by Svetomechc** [comment]
@berik that's what I suspected :c

**Comment by joshpearce** [comment]
I have great respect for the work done in this project template, but I feel like anyone considering oidc-client instead of just old fashion session cookies for a web app, even an SPA, needs to think long and hard about whether they really need it. The surface area for subtle auth failure bugs is greatly increased by adding all the client-side logic, and I've never understood the benefits.

Here we're talking about leaving a browser open for hours. You've got background tabs going to sleep and OS's going into power save state working against your auth logic. The user doesn't care about any of this. They just want to either be logged in or out, not partially logged in, wondering how to get the app back working. 

Auth is a mess right now. Logging into the Azure Portal sometimes involved four seconds straight of redirects. Then when you log out, they tell you you're probably logged out, but it's best to close the browser to make sure

We write web apps for Radiology, and availability is the number one requirement. I would not introduce oidc-client to our apps.

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406

**Comment by caihongxu** [comment]
Update: I think I addressed this by adding the following line in `Startup.cs`:
`
            services.Configure<JwtBearerOptions>(
                IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
                options =>
                {
                    options.TokenValidationParameters.ValidateIssuer = false;
                    options.TokenValidationParameters.ValidateLifetime = false;
                });
`
Specifically the `ValidateLifetime = false` line. My token hasn't expired since then.
