### ISSUE TITLE
Update Scaffold Identity to 3.0

### ISSUE THREAD

**Issue by hongzewangpa** [aspnet/AspNetCore.Docs#12723]
I am using VS 2019 v16.0.4

If we create a web app and selecting Individual User authentication, it works well. However, if we add Identity scaffording to an existing asp.net mvc core 3 app. The app simply return 404 blank page after all changes made in this article.

Thanks,
Hz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
ASP.NET Core 3.0 probably needs more work.

**Comment by hongzewangpa** [comment]
Hi Rick,
Is there an estimate time of update to this?
Thanks,
Hz

**Comment by hongzewangpa** [comment]
I found if I move the services.Addxxx out of IdentityHostingStartupinto startup.cs, it is working.

//code piece moved:
                services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    context.Configuration.GetConnectionString("DefaultConnection")));

                services.AddDefaultIdentity<IdentityUser>()
                    .AddEntityFrameworkStores<ApplicationDbContext>();

**Comment by Rick-Anderson** [comment]
Dup of  #10159
