### ISSUE TITLE
Cookie Consent removed from Template in 3.0

### ISSUE THREAD

**Issue by isaac2004** [aspnet/AspNetCore.Docs#12720]
Per https://github.com/aspnet/AspNetCore/issues/10346 the Cookie Consent section will be removed in ASP.NET Core 3.0. This doc will need to be updated to mention this and note how to add necessary bits. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@isaac2004 Please let Rick know if you'll be submitting a PR. I'd hate to have him spend time on it if you're already working on it.

**Comment by isaac2004** [comment]
@Rick-Anderson PR already submitted
