### ISSUE TITLE
What's new in ASP.NET Core 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#12729]
New article.

**Comment by natemcmaster** [comment]
Oh yeah, forgot I had started drafting that. I made an initial start on it and got sidetracked by more pressing matters. @scottaddie let's sync up sometime soon, if you're free. I'll be going on paternity leave a week from today, so I'm unlikely to finish up the work I started in https://github.com/aspnet/AspNetCore.Docs/commit/22e6ed8b58988717ec0acb8ec2d4429a1d921776

**Comment by mkArtakMSFT** [comment]
@danroth27 who will be handling this?

**Comment by scottaddie** [comment]
Closing, as this doc already exists.
