### ISSUE TITLE
Revert remark on container images in proxy/LB topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12737]
Revert remark ...

> Until new container images are provided in Azure, you must create an app setting (environment variable) for `ASPNETCORE_FORWARDEDHEADERS_ENABLED` set to `true`. For more information, see [Templates do not work in Antares Linux due to missing scheme forwarders (aspnet/AspNetCore #4135)](https://github.com/aspnet/AspNetCore/issues/4135).

... when new container images land in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher

For the section that we added to the proxy/LB topic, *Forward the scheme for Linux and non-IIS reverse proxies*, I'm aware that the new container images will address the need for the dev to set the `ASPNETCORE_FORWARDEDHEADERS_ENABLED` env var, so we can drop that remark for >=3.0.

However, we have the entire section versioned for 2.x only, not 3.0. That includes the code block shown. Is an in-box solution on the way such that we should leave this versioned the way that it is? Otherwise, I take it that we need to **_keep the section and code visible for >=3.0 going forward_**.

If we are going to version for 2.1+ (to include 3.0) for the lead-in paragraph and code, I'll adjust the lingo on `UseHttpsRedirection` and `UseHsts` given that those are dropping out of the template.

**Comment by Tratcher** [comment]
@bradygaster The ASPNETCORE_FORWARDEDHEADERS_ENABLED variable added to the containers wasn't version specific, right? E.g. it's present for 2.x and 3.x apps?

**Comment by guardrex** [comment]
Let's continue the discussion on the PR :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/13251
