### ISSUE TITLE
error in startup at beginning

### ISSUE THREAD

**Issue by Lokesh-Eisen** [aspnet/AspNetCore.Docs#12748]
additional things to add for clarity.

right after the require authenticate users heading
 config.Filters.Add(new AuthorizeFilter(policy));

 in create starter app mention the fact that you have to create authentication folder with the necesarry
code here:

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data/samples/starter2.1/Authorization/ContactOperations.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2#secure-user-data)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Lokesh-Eisen** [comment]
problem fixed could you highlight this line of code as well to reduce confusion
services.AddMvc(config =>
    {

**Comment by Rick-Anderson** [comment]
@Lokesh-Eisen  this is an advanced tutorial.
