### ISSUE TITLE
Confusing between UseAuthentication and UseAuthorization.

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#12747]
> We recommend placing the authorization middleware (`UseAuthentication`) immediately before `UseAuthorization`.

Should this read?:

> We recommend placing the authorization middleware (**`UseAuthorization`**) immediately **after** `UseAuthentication`.

The authorization middleware being `UseAuthorization` rather than `UseAuthentication`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Noting in passing that the named middlewares are proper nouns in case this goes forward (e.g., "Authorization Middleware").

**Comment by serpent5** [comment]
Apologies. I referenced this issue from the wrong issue. I deleted the comment but the first, erroneous reference above remains. 😦

**Comment by serpent5** [comment]
If this change is desired, I can create a PR.

**Comment by guardrex** [comment]
Sounds good to me. Capitalize the middleware as a proper noun. "Authorization Middleware"
