### ISSUE TITLE
works in an unintened way when not signed in.

### ISSUE THREAD

**Issue by Lokesh-Eisen** [aspnet/AspNetCore.Docs#12754]
so If hit allow anonymous  the unloggedin user should be able to view the content  as long as items are approved and the edit and delete buttons should not be displayed. 

This works propperly for a user who is signed in with no role, but works improperly for a nonregistered user. Any idea why this might be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2#test-the-completed-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Lokesh-Eisen** [comment]
like when I go to the webpage I see this right now: 
https://imgur.com/gallery/3cSETC7

**Comment by Lokesh-Eisen** [comment]
if (currentUserId == null) {
                contacts = contacts.Where(c => c.Status == ContactStatus.Approved);
            }

fixxed that with a simple^ but I can still try to click on the edit links before it prompts me to log in?

**Comment by Lokesh-Eisen** [comment]
should I ideally have another operation handler for when not signed in?

**Comment by Rick-Anderson** [comment]
There might be some imperfections in the app. 
Can you tell me exactly what's wrong with the sample download?

**Comment by Lokesh-Eisen** [comment]
no nevermind feel free to close this. this was a problem with my own code not the document/sample was looking for help debugging.
