### ISSUE TITLE
Small typo under 'Create Razor Pages Web App' heading

### ISSUE THREAD

**Issue by banta-isaiah** [aspnet/AspNetCore.Docs#12751]
"Name the project RazorPagesMovie. It's important to name the project RazorPagesMovie so the namespaces will match when you copy and paste code code."

The word 'code' is displayed twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by zo0o0ot** [comment]
This issue is still listed as open on the documentation web page, having merged content that appears to fix the issue.

Presumably, it should be closed, since the page has been updated?

![image](https://user-images.githubusercontent.com/876146/60746050-7caed000-9f42-11e9-9807-bc33e9336ca0.png)

**Comment by Rick-Anderson** [comment]
Thanks @zo0o0ot

**Comment by zo0o0ot** [comment]
👍
