### ISSUE TITLE
Clarify lifecycle events

### ISSUE THREAD

**Issue by joshlang** [aspnet/AspNetCore.Docs#12769]
In the docs here: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods … 3 lifecycle methods are covered.

Because of the way it's written, I was confused and thought the lifecycle events are called in order... `OnInit` (once), then `OnParametersSet` (often), then `OnAfterRender` …

I was also confused because some examples used Parameters in OnInit() and I wondered if it was safe - so I was using OnParametersSet instead.

But the intellisense docs for OnInit() state: `Method invoked when the component is ready to start, having received its initial parameters from its parent in the render tree.`

Now things are clear.

Could I suggest adding the content from the intellisense docs into these blazor docs, and to clarify the order in which lifecycle events occur?

Thanks to the folks on blazor Gitter chat for this one :)

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/12773.

Thanks for opening @joshlang . FYI for future issues: If they're opened from the **This Page** feedback button at the bottom of the topic, it tags the issue with metadata that helps us track the work.
