### ISSUE TITLE
Step 3 Visual Studio Default Project Does Not Compile

### ISSUE THREAD

**Issue by vthokie93** [aspnet/AspNetCore.Docs#12767]
Followed instructions through step 3 using Visual Studio, but the project does not compile.  Fails with error "The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)" in Startup.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vthokie93 ... You must use the latest release of VS Preview available at: https://visualstudio.microsoft.com/vs/preview/
