### ISSUE TITLE
[Preview 7] Blazor directive updates

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12766]
* Drop '@' from values. https://github.com/aspnet/AspNetCore.Docs/pull/12756#discussion_r291826971 and https://github.com/aspnet/AspNetCore/issues/10909
* Drop `@(...)` syntax. https://github.com/aspnet/AspNetCore.Docs/pull/12756#discussion_r291826921

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb should this be closed?

**Comment by guardrex** [comment]
This is done ... came to find out that even if the issue is marked "fixes" and goes from the staging branch to `master` that these issues must be manually closed. Not sure what GH was thinking on this behavior.
