### ISSUE TITLE
Lazy initialisation with built-in DI.

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#12768]
> Func&lt;T&gt; support for lazy initialization

The above is listed as one of the features not supported by the built-in container, but the built-in `AddXXX` methods all have overloads that can take a `Func<IServiceProvider, T>`, which I believe is initialised lazily. e.g. [`AddSingleton`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton?view=aspnetcore-2.2#Microsoft_Extensions_DependencyInjection_ServiceCollectionServiceExtensions_AddSingleton__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Func_System_IServiceProvider___0__).

I realise that initialisation and instantiation are different things and that the line I referenced might be referring to something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#default-service-container-replacement)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @serpent5 ... I'll mark this for the Product Unit to address.

**Comment by guardrex** [comment]
@serpent5 My understanding is that engineering will be pinged on these at some point. If it's still an open question, you could leave this open to see if that happens.

**Comment by serpent5** [comment]
@guardrex Thanks. I closed this for another couple of reasons:

1. It's not had any :+1:s so it's not something of interest to others.
2. I concluded that it likely means the ability to delay creation of a service until it's _used_, rather than what I described where it's done before construction of the dependent component.
