### ISSUE TITLE
Clarify lifecycle events

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12773]
*From @joshlang on https://github.com/aspnet/AspNetCore.Docs/issues/12769* ...

> In the docs here: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods … 3 lifecycle methods are covered.
>
> Because of the way it's written, I was confused and thought the lifecycle events are called in order... `OnInit` (once), then `OnParametersSet` (often), then `OnAfterRender` …
>
> I was also confused because some examples used Parameters in OnInit() and I wondered if it was safe - so I was using OnParametersSet instead.
>
> But the intellisense docs for OnInit() state: `Method invoked when the component is ready to start, having received its initial parameters from its parent in the render tree.`
>
> Now things are clear.
>
> Could I suggest adding the content from the intellisense docs into these blazor docs, and to clarify the order in which lifecycle events occur?
>
> Thanks to the folks on blazor Gitter chat for this one :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by eyal7773** [comment]
Fix the methods name on Lifecycle part to OnInit instead of OnInitialized (and async also)

**Comment by guardrex** [comment]
This content is now cross-linked and will be considered/worked on #14353. Please track it on that issue.
