### ISSUE TITLE
No backwards compatibility with default overload of Html.BeginForm(no params)

### ISSUE THREAD

**Issue by timmi4sa** [aspnet/AspNetCore.Docs#12783]
This Core thing is annoying, the fact that we DID'T need to specify action name when using the default Html.BeginForm() helper method breaks a lot of things for us. Example: what if we need to rename some action, do we need to find all Views that contain that action's asp-action attribute?? Or worse, we use Create/Edit views a lot to avoid duplication of Razor logic, so now we have to indicate Action name????? Please do something about this, give us a magic value (asp-action="request-source") or something...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-action)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @timmi4sa ... Your feedback is better for the product unit to see than for us. We just handle documentation issues here. Open your feedback at ...

https://github.com/aspnet/AspNetCore/issues
