### ISSUE TITLE
Build Action set to Content

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#12798]
For some reason if I create a file with extention .razor, BuildAction always defaults to None. Good to note to others (maybe in the ToDo section) to make sure the file Build Action is set to 'Content'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Alienroid "Create a file" ... a C# class file that you rename?? ... I can't explain the Build Action behavior if that's what your IDE is doing. Anyway, Razor components files (*.razor*) will be a file type offered in VS shortly, so this is a point-in-time issue.

**Comment by Xyncgas** [comment]
I created .razor file and it was displaying my component as its name as html tag in dom, I noticed my previous existing component had built action set to content, it caused a lot trouble for me to debug this
