### ISSUE TITLE
@namespace not covered in Razor syntax doc

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#12795]
The @namespace Razor directive is missing from the Razor Syntax doc. It's covered in the Razor Pages doc (https://docs.microsoft.com/aspnet/core/razor-pages), but it should also be covered here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're adding it on https://github.com/aspnet/AspNetCore.Docs/pull/12762.

https://github.com/aspnet/AspNetCore.Docs/pull/12762/files#diff-1e5e737d1940c4e0e1456cab8f97f03fR582

**Comment by guardrex** [comment]
**Update**: It was added by the engineers on #12762 and is live now ...

https://docs.microsoft.com/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#section-7
