### ISSUE TITLE
Confusing or perhaps incorrect text with reference to the  built-in helper method Json()

### ISSUE THREAD

**Issue by carlosthehyena** [aspnet/AspNetCore.Docs#12809]
Document mentions "To return data in a specific format from a controller that inherits from the Controller base class, use the built-in helper method Json to return JSON".
In my default ASPNet 2.2 API solution created in Studio 2017, the controller inherits from "ControllerBase" class, which is different to the "Controller" base class. The "ControllerBase" class in my solution does not have this helper.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
Correct. That method is on Controller, not ControllerBase. ControllerBase has a smaller amount of functionality and is the recommended base class to use for API controllers. Which should typically return ActionResult or IActionResult rather than Json(). This lets them use content negotiation and return other results like BadRequest and NotFound which returning Json() (as the method return type) would not support. And if you just return Ok(object) it will by default serialize the object to Json.

**Comment by carlosthehyena** [comment]
OK thanks. I'm proposing this part to be changed for a number of reasons: Firstly, out of the box, the ASPNET Rest API scaffold uses controllerbase and as you say, is the recommended base class to use - the document "Create web APIs with ASP.NET Core" (https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2) confirms that (A web API has one or more controller classes that derive from ControllerBase. ) . So while I understand that the paragraph in question refers to  Controller Base class, giving the example code with the json function as a primary example doesn't make sense in the context of ASP.net Core APIs. Secondly, there is a very slight ambiguity between the phrase " inherits from the Controller base class" (in the documentation) and " inherits from the ControllerBase class" - very easy to misread, especially within the conteext of the default scaffold aforementioned. 

In addition, there is no reference to the fact that Ok(object) serializes the object to Json by default.

I suggest that the first paragraph should not be "Format-Specific Action Results", but rather "Default Format for WebAPIs ", with text referring to the recommended ControllerBase and  referring to your json and/or OK(json)  explanation. This should be followed by another paragraph ..."Format-Specific Action Results WebAPI (controllerbase)"; and then finally "Format-Specific Action Results - other controllers", which is the parapraph in question,  and which stresses the difference between controllerbase class and "controller base class" .

**Comment by Rick-Anderson** [comment]
Fixed in #12077
