### ISSUE TITLE
Input Password generation

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#12803]
InputText shows open text. Is there an input component for password? Also, how to add placeholder to Input components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Alienroid** [comment]
Oops, I think #12660 answered this

**Comment by guardrex** [comment]
*Yes* ... these *should* work with Pre6. 🤞 If the framework is missing a scenario after Pre6 comes out, open an engineering issue at https://github.com/aspnet/AspNetCore with the request.
