### ISSUE TITLE
Compiler error, withurl missing?

### ISSUE THREAD

**Issue by AnR62** [aspnet/AspNetCore.Docs#12804]
This doesn't work, produces a compile error "Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'HubConnectionBuilder' does not contain a definition for 'WithUrl' and no accessible extension method 'WithUrl' accepting a first argument of type 'HubConnectionBuilder' could be found (are you missing a using directive or an assembly reference?)	ConsoleApp.ConnectToHub	C:\Users\anders.rydell\Desktop\Spikes\ConsoleApp.ConnectToHub\Program.cs	16	Active
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @AnR62 ... See https://github.com/aspnet/AspNetCore/issues/9827.

**Comment by guardrex** [comment]
And I see one more over there. Check this one, too :point_right: https://github.com/aspnet/AspNetCore/issues/5137#issuecomment-496001119
