### ISSUE TITLE
Small typo under 'Consuming these interfaces' heading

### ISSUE THREAD

**Issue by zakaria-dz** [aspnet/AspNetCore.Docs#12802]
"the component take an IDataProtectionProvider" should be "the component takes an IDataProtectionProvider."
The "s" is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23af4f99-387c-b2f5-3d5b-3d98cfac247c
* Version Independent ID: 0d95b7b7-5e46-5718-ca09-bdae43c86963
* Content: [Consumer APIs overview for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/overview?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/overview.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/consumer-apis/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @zakaria-dz ... I'll patch it.
