### ISSUE TITLE
Does it mean after 3.0, the javascript client will reconnect automatically?

### ISSUE THREAD

**Issue by virtualbiz** [aspnet/AspNetCore.Docs#12814]
If so, what's the details of this auto-reconnect mechanism? How does it happen? Is it configurable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
If you view the 3.0-preview version of the docs you'll see we already have documentation on it!
https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#reconnect-clients

**Comment by guardrex** [comment]
Closing as answered. @virtualbiz, let's re-open if the preview content doesn't address your questions. Ping us back here on this issue if that's the case.
