### ISSUE TITLE
Startup Project different from Data Context project

### ISSUE THREAD

**Issue by Serjster** [aspnet/AspNetCore.Docs#12815]
I would expect Microsoft to provide how to handle the very common scenario where the DataContext is in a class library, or otherwise different from the Startup project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. That's probably more appropriate for https://docs.microsoft.com/en-us/ef/core/
