### ISSUE TITLE
Scaffolding Angular template

### ISSUE THREAD

**Issue by manu-mishra** [aspnet/AspNetCore.Docs#12827]
How can we scaffold the new Angular template with external users enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by manu-mishra** [comment]
I understand Angular template is new, if you can please point me to the repo which has that code, i can try to check files manually. Thanks. The new angular identity template is awesome.

**Comment by Rick-Anderson** [comment]
@scottaddie which repo has the angular template?

**Comment by scottaddie** [comment]
The Angular project template is in https://github.com/aspnet/AspNetCore. Specifically, see https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
