### ISSUE TITLE
Adding Client-side library doesn't work in Visual Studio 2019 - no autocomplete displayed

### ISSUE THREAD

**Issue by timavaza** [aspnet/AspNetCore.Docs#12821]
This documentation says an autocomplete of available client-side javascript libraries will be displayed. But it doesn't work. So its not possible to see what javascript signalr client versions are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Changed title because your version is a **little ways out**. 👍 

Any chance you could provide a screen shot of what you're seeing? It would help understand the scenario somewhat.

**Comment by ctyar** [comment]
I can reproduce this
![Annotation 2019-07-01 132549](https://user-images.githubusercontent.com/1432648/60423589-c7a7ab00-9c03-11e9-9a86-f9be98e601ec.png)

**Comment by xyz92** [comment]
+1

**Comment by bradygaster** [comment]
Thanks for the screen shots. Investigating this ATM.

**Comment by bradygaster** [comment]
Adding @jodavis to the discussion.

**Comment by jodavis** [comment]
This is a bug in Library Manager. It should work as documented. The issue is under investigation, tracked here: https://github.com/aspnet/LibraryManager/issues/352

**Comment by valuator18** [comment]
Came here to report the same issue. Wow. Seems like nothing ever works in Visual Studio anymore. Every new release is a regression.

**Comment by JasOcher** [comment]
Several months later and this still doesn't work.

**Comment by timavaza** [comment]
Such a bad developer onboarding experience. Gave up on Signalr Core at this
point. #roadblocked

**Comment by jodavis** [comment]
I apologize for the delay. This should be working better in the latest preview of Visual Studio 2019 that was released this week.

**Comment by bradygaster** [comment]
Good to hear this, @jodavis. @timavaza  - this isn't a SignalR-specific issue, but I understand your frustration and apologize for it. You could use the CDNJS-hosted packages, or you could use the libman CLI or even the NPM CLI to install the package, as well. I know that's not as efficient or elegant, but I wanted you and others to know there are options to acquire SignalR and other packages with the "@".

**Comment by timavaza** [comment]
I don't think users should be expected to know how to do those things..
Surely the documented steps on the Signalr getting started site (including
any workarounds) are Signalr responsibility.
New users will get stuck when the steps don't work & it doesn't inspire
confidence in the maturity of the platform.

**Comment by bradygaster** [comment]
@timavaza have you tried this with the new bits as @jodavis has reported the update has been shipped.

**Comment by bradygaster** [comment]
Note to @timavaza - I've also facilitated a pull request with the CDNJS folks, as that's where we'll be maintaining this moving forward. See [this PR](https://github.com/cdnjs/cdnjs/pull/13438) for details. Once the nice folks at CDNJS merge this, I'll update the doc to reflect the change. Between the package update on CDNJS, the VS update @jodavis  mentioned, and the new library location, I think you and other customers will be much happier. 

Thanks for persisting on this.
