### ISSUE TITLE
PasswordHasherOptions

### ISSUE THREAD

**Issue by OzBob** [aspnet/AspNetCore.Docs#12824]
How to provide an override of the default PasswordHasherOptions for V3, so that it uses PasswordHasherOptions V2?
https://github.com/aspnet/AspNetCore/blob/2b2aeee9f869ec43f65c188a66d9285858823628/src/Identity/Extensions.Core/src/PasswordHasher.cs#L42
has IOptions&lt;PasswordHasherOptions&gt; , but what is the syntax to provide custome PasswordHasherOptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcab4fd-00de-6e6f-0552-30c07ffc4086
* Version Independent ID: 5c2b0d48-ef1a-5875-35d1-865cb022fa71
* Content: [Dependency injection in requirement handlers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/dependencyinjection?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/dependencyinjection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/dependencyinjection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This is documented in [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.2), under [Password Hasher options](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.2#password-hasher-options). There's a code snippet that shows how to set `IterationCount`, but you can change that to set `CompatibilityMode` accordingly.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
