### ISSUE TITLE
Clustering clarification

### ISSUE THREAD

**Issue by yahorsi** [aspnet/AspNetCore.Docs#12830]
Hi,

In the "Clustering" section did you really mean Reddis Clustering? It is a bit misleading.
Please clarify, as well as "Clustering isn't officially supported, but it might work."
Does that mean again Reddis Clustering? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Sure we can update the text to be more clear.

Just curious, what other clustering could we be referring to here?

**Comment by yahorsi** [comment]
Potentially Azure App Service clustering (scale out)
