### ISSUE TITLE
Sql ca Redis pers, Sql In memory OLTP?

### ISSUE THREAD

**Issue by yahorsi** [aspnet/AspNetCore.Docs#12832]
The article does not state anything about Sql Server cache speed. And, once Sql Server now supports in memory OLTP it looks like perfect match, so, please state if/how to use Sql Server based caching with In Memory OLTP.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @yahorsi ... WRT speed, we won't be able to address that (we almost never do). The environment (server, network, app, etc.) plays a large role in perf. We recommend benchmarking the options under your local conditions to aid in making a choice.

WRT Sql Server and In Memory OLTP ... there's an existing engineering issue for that. Add your feedback or ask them about it on that issue :point_right: https://github.com/aspnet/Extensions/issues/741
