### ISSUE TITLE
Update IIS doc for 3.1 (Generic Host)

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#12844]
Web Host --&gt; Generic Host -- there's a link to a Web Host H2 that doesn't exist in the Generic Host doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  unassign yourself if you don't have time.

**Comment by guardrex** [comment]
Sure thing ... I'll take care of it right now. I'm at a good *Blazor Break Point*:tm:.

**Comment by guardrex** [comment]
@Rick-Anderson ... looks like this was resolved on an earlier PR at some point. There are only two Web Host topic links, and they're both in versioned content <3.0.
