### ISSUE TITLE
mention Microsoft.AspNetCore.WebSockets package needed

### ISSUE THREAD

**Issue by pablocar80** [aspnet/AspNetCore.Docs#12856]
The documentation could mention that in order to be able to call UseWebSockets, we need to install the package Microsoft.AspNetCore.WebSockets.

**Comment by scottaddie** [comment]
@pablocar80 Can you please provide a link to the doc you're referring to?

**Comment by pablocar80** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
@pablocar80  that's an advanced topic and we don't list every include needed. At least in Visual Studio, that's trivial to add.

**Comment by pablocar80** [comment]
@Rick-Anderson pages often include the namespace that is needed to add, and this one doesn't. It's trivial to add a reference only after you know which reference you need to add. Visual Studio 2019 won't automatically resolve the reference for UseWebSocket() in NET Standard projects.

Here is an example of a help page that includes the namespace at the top:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.isession?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
That's an API page - a reference doc, different type of doc.
Can you PR and add that?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
