### ISSUE TITLE
Prerendering with reconnect

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12854]
https://github.com/aspnet/AspNetCore.Docs/pull/12872#issuecomment-505565330

Content from closed (unmerged) PR is here :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/12776/files

DR will provide the content here on the issue ...

> I'd like to create two new completely new top level topics:
>
> * Prerendering
> * Using components with Pages and Views
>
> The content in this PR would then be covered in those new topics, but in the context of those specific scenarios and without new jargon.

Note to self ...

> ... cross-links for the current prerendering content. There's such content in the Hosting Models and JS Interop topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 I'll assign to you for now and then switch the assignment back to me after you've pasted the content in here.

(Let me know if this issue has become more of a *HOLD-for-now* thing. If so, I'll move this from the P1 column to the *HOLD* column for the time being.)

**Comment by danroth27** [comment]
@guardrex I don't expect to get to this for a while, so it's definitely in a holding state.

**Comment by mkArtakMSFT** [comment]
These are now documented.
