### ISSUE TITLE
3 AddAreas missing

### ISSUE THREAD

**Issue by OzBob** [aspnet/AspNetCore.Docs#12857]
using the latest aspdotnetcore3 preview 5 

The UseIdentityServer option (https://github.com/aspnet/AspNetCore/blob/18a230737a3ebf02b44db2c24a14399f41eadc4d/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs#L47) is used
1. Is there an equivalent scaffolding override for core3?

2. When trying to configure 'UseAreas' in MVC as per instructions (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio#create-full-identity-ui-source) the AllowAreas has gone from Microsoft.AspNetCore.Mvc.RazorPages.RazorPageOptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Tracking in #10159
