### ISSUE TITLE
Add Blazor First App tutorial to Tutorials TOC node

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#12866]
Add a duplicate TOC node for this tutorial under **Tutorials &gt; Web apps** following MVC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#publish-and-deploy-the-app)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Could be a note on https://github.com/aspnet/AspNetCore.Docs/pull/12623 to do this ... I think we'll be moving back to working on that early next week.
