### ISSUE TITLE
This documentation is only for < ES6

### ISSUE THREAD

**Issue by Xarkam** [aspnet/AspNetCore.Docs#12861]
Hello,

It would be useful to put an information for the developers who want to minify code javascript ES6 and higher.
Just use gulp-terser instead of gulp-uglify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@Xarkam  any chance you could PR that?

**Comment by Xarkam** [comment]
Hello @Rick-Anderson,

I am going to do a PR but I am not very hot when I see that the issue ( 5028  ) that my wife opened in 2017 is tagged help wanted.

I will read the contributing page for this PR.
