### ISSUE TITLE
Build error when compiling the client project

### ISSUE THREAD

**Issue by buzzfrog** [aspnet/AspNetCore.Docs#12860]
Maybe something has changed in the gRPC Server template?
In that template the greet.proto set the namespace to option csharp_namespace = "GrpcGreeter";
But in the code that should be pasted into program.cs in the client project, the namespace is "Greet". This will not build. 
Solution change Greet to GrpcGreeter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by buzzfrog** [comment]
BTW: I use preview 6 of .NET Core 3

**Comment by tdykstra** [comment]
@buzzfrog Thanks for reporting that!  I'm fixing that plus some other issues I noticed while reviewing the tutorial.
