### ISSUE TITLE
Minor confusion with attributes on docs.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/AspNetCore.Docs#12867]
When Conditional attributes section starts, the previous line talk about C# attributes, but this explain html tag attributes.
It makes a minor confusion for a split second to switch between contexts. Maybe it's good idea to implicit call for html tag attributes and/or c# attributes and distinguish one from the other (?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Bartmax (and good to hear from you). I'll mark this for review/triage.
