### ISSUE TITLE
FirstOrDefaultAsync vs. SingleOrDefaultAsync

### ISSUE THREAD

**Issue by ChiefInnovator** [aspnet/AspNetCore.Docs#12885]
I find this advice to be bad.  If you expect a single entity, you should always use Single or SingleOrDefault semantics.  The performance gain of First is negligible if you have an EF query that is correct to begin with.  However, the benefits of code quality with the use of Single is much better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That section was written by the EF team and is the expert consensus.
