### ISSUE TITLE
[3.1] Supply content to a Blazor layout from a component

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#12889]
[Blazor Layouts with several placeholders (Header/Footer/etc) like MVC Sections/WebForms aspnet/AspNetCore \#10131](https://github.com/aspnet/AspNetCore/issues/10131)

The original community-submitted issue :point_up: was closed in favor of :point_right: https://github.com/aspnet/AspNetCore/issues/10452.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@guardrex this shuold be closed, as we don't have proper support for `Sections`.

**Comment by guardrex** [comment]
@mkArtakMSFT Should it cover https://github.com/aspnet/AspNetCore/issues/10450?

**Comment by guardrex** [comment]
Perhaps, 5.0 is so far in the future tho that it isn't worth having this lying around.
