### ISSUE TITLE
Is it possiable to use more than one parameter in an action method with Json Post

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore.Docs#12890]
&gt; Don't apply `[FromBody]` to more than one parameter per action method

some json input are too simple and can not to reuse further. Create a class for each request is a big challenge for naming the class.

I wonder is there a way I can use the parameters like the Form Post Input

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by jez9999** [comment]
I'm not sure if the above post is saying what I think it is, but if it is, I have the same issue.

Given a JSON POST to ASP.NET Core where the body payload is:

```
{
    foo: 1,
    bar: "two",
    baz: true
}
```

... I should be able to declare an ASP.NET Core action method like so, and have the values be bound correctly:

```
[HttpPost]
[Route("api/buckets/{id}")]
public async Task PostEvent(int id, int foo, string bar, bool baz) {
    [...]
}
```

Right now it seems I have to declare a class with `foo`, `bar`, and `baz` in and bind them with the `FromBodyAttribute` which seems a bit like overkill for a few primitive data type values.

**Comment by John0King** [comment]
@jez9999 yes, this is exactly what I'm asking about.

**Comment by Rick-Anderson** [comment]
Moved to Model Binding master issue #16316

**Comment by Rick-Anderson** [comment]
See #16316

The topic states explicitly that only one parameter can be decorated with `[FromBody]` and the startup logic for MVC enforces this. Any attempt at a workaround would be much more involved than just creating a wrapper class.
