### ISSUE TITLE
Please add a complete example of a simple .net core app with responsecompression enabled that works published in IIS without losing the compression in the response

### ISSUE THREAD

**Issue by techaimail** [aspnet/AspNetCore.Docs#12898]
Using your basic information about responsecompression when the app is runing in console mode (iisexpress or kestrel) compression works, but when run in IIS (in or out of process) the response has no compression.

**Comment by guardrex** [comment]
Hello @techaimail ... If you verified that the [conditions for response compression](https://docs.microsoft.com/aspnet/core/performance/response-compression#troubleshooting) are met but compressed responses aren't produced, please open an issue for engineering ...

https://github.com/aspnet/AspNetCore/issues

btw- When you open a documentation issue, please use the **This Page** feedback button at the bottom of the topic to tag the issue with metadata.
