### ISSUE TITLE
The FTP publish method does not publish any files

### ISSUE THREAD

**Issue by techaimail** [aspnet/AspNetCore.Docs#12897]
Using the deployment profile downloaded from azure (checked ok that credentials direct via FTPS) the publish command delete the existent files but dont publish the files.

**Comment by guardrex** [comment]
Hello again ... We only handle documentation on this repo. To report a problem with VS, use the **Report a Problem** process in VS ...

**Help** (menu item) > **Send Feedback** > **Report a Problem**

It opens an internal issue for the team that handles Visual Studio.
