### ISSUE TITLE
How to configure flags for Debug and EventSource logger

### ISSUE THREAD

**Issue by lafe** [aspnet/AspNetCore.Docs#12891]
The page describes what the example configuration does, however, it is not clear how to configure other logging targets (e.g. EventSource or Debug). So more examples or a in-depth explanation would be awesome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-level)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
The first code sample shows how to do that:

```
public static void Main(string[] args)
{
    var webHost = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            var env = hostingContext.HostingEnvironment;
            config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                  .AddJsonFile($"appsettings.{env.EnvironmentName}.json", 
                      optional: true, reloadOnChange: true);
            config.AddEnvironmentVariables();
        })
        .ConfigureLogging((hostingContext, logging) =>
        {
            logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
            logging.AddConsole();
            logging.AddDebug();
            logging.AddEventSourceLogger();
        })
        .UseStartup<Startup>()
        .Build();

    webHost.Run();
}
```

**Comment by lafe** [comment]
Thanks for your quick feedback. Maybe, I did not explain myself clearly. The examples show how to hook up configuration that is located elsewhere (appsettings.json or environment variables) and also show an example of the appsettings configuration, but it does not show which flags can be set in those configuration files and which are available in general. This was something which I expected from the [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#configuration) chapter but which was not available there.

**Comment by guardrex** [comment]
We often list/explain options (usually mirrored content from the API docs), but we'd be hard pressed to doc all of the options for every framework feature. Also, there's generally 🏃 *a lot of engineering churn* 🏃 with options.

One way to handle this is to link to the options in the API browser. Today, it's often a reader-unfriendly process to get to them. For example, take the Console Provider ...

* In the  reference source: The *Console provider* section links to the NuGet package. The package links to the source repo. Then ... **src** > **Logging** > **Logging.Console** > **src** > **ConsoleLoggerOptions.cs** to see them.
* In the API docs: The reader is probably 😵 trying to guess the namespace to search.

In the *Console provider* case, we could link https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions. The reader can select their version. We wouldn't need to list/explain every one. Engineering can modify them each release with reduced doc churn.

**Comment by guardrex** [comment]
@lefe For the two that you asked about IIRC, I don't think there are options to configure (but you should look to make sure). For the rest of the providers, I'll link their options API docs.
