### ISSUE TITLE
Wrong documentation for OnParametersSetAsync/OnParametersSet lifecycle methods

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore.Docs#12896]
[EDIT by guardrex to remind myself to add the no-loc metadata: `no-loc: [Blazor]`]

In current doc here https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods we have:

`OnParametersSetAsync` and `OnParametersSet` are called when a component has received parameters from its parent and the values are assigned to properties. These methods are executed after component initialization and each time the component is rendered:

It should be something similar to this:

`OnParametersSetAsync` and `OnParametersSet` are called when a component has received parameters from its parent and the values are assigned to properties. *This happens each time parent component is rendered.* These methods are executed after component initialization ~~and each time the component is rendered~~:

The problem was discovered here: https://github.com/aspnet/AspNetCore/issues/11248
In my opinion Blazor works as expected but not as documented. `OnParametersSet` methods are not called when component is rendered as a result of handling some event. They are called only when parent component is rendered. Those conclusions are based on experiments. I have not analysed source code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Note to self: Add the no-loc metadata.
