### ISSUE TITLE
Potential issue with SetApplicationName when using Docker

### ISSUE THREAD

**Issue by spacecat** [aspnet/AspNetCore.Docs#12905]
When Docker is enabled for a Razor Pages web app the auto-generated Dockerfile looks like the following:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["mywebapp01/mywebapp01.csproj", "mywebapp01/"]
RUN dotnet restore "mywebapp01/mywebapp01.csproj"
COPY . .
WORKDIR "/src/mywebapp01"
RUN dotnet build "mywebapp01.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "mywebapp01.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "mywebapp01.dll"]
```

Notice the last `WORKDIR `command `WORKDIR /app`

Now, I create a second Razor Pages web app with Docker enabled and I get the following auto-generated Dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["mywebapp02/mywebapp02.csproj", "mywebapp02/"]
RUN dotnet restore "mywebapp02/mywebapp02.csproj"
COPY . .
WORKDIR "/src/mywebapp02"
RUN dotnet build "mywebapp02.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "mywebapp02.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "mywebapp02.dll"]
```

Notice that the last `WORKDIR `command is identical to the one from app mywebapp01.

Next, I publish both my apps to Docker Hub.

Then I create two services in AKS, both under the same domain, e.g. example.com. 

mywebapp01 has one `POST `operation and mywebapp02 has another.

Now, if I `POST `my forms with antiforgery enabled for mywebapp01 and then `POST `again but this time from mywebapp02  I will have a conflict.

```
Antiforgery token validation failed. The antiforgery token could not be decrypted.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---&gt; System.Security.Cryptography.CryptographicException: The key {6a48a446-462e-4238-a4af-5a6751ae81cc} was not found in the key ring.
```

Both `.AspNetCore.Antiforgery.xxx` keys will be identical. The values will vary.

So when I try to `POST `the second time I will get a `Antiforgery token validation failed. The antiforgery token could not be decrypted.`

The docs state that:

> By default, the Data Protection system isolates apps from one another based on their content root paths, even if they're sharing the same physical key repository. This prevents the apps from understanding each other's protected payloads.

In my scenario both apps will have the same Content root path and this will lead to the apps not being isolated and they will therefore try to share each others payloads - in this case the antiforgery token.

Content root path for mywebapp01:

```
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

Content root path for mywebapp02:

```
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

Notice that the Content root path is the same for both apps.

I changed the `WORKDIR `command in the Dockerfiles and this will dictate what the Content root path will be.

mywebapp01 Dockerfile:
```
.
.
.
FROM base AS final
WORKDIR /mywebapp01
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "mywebapp01.dll"]
```

mywebapp02 Dockerfile:
```
.
.
.
FROM base AS final
WORKDIR /mywebapp02
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "mywebapp02.dll"]
```

And now I will not get the error: `Antiforgery token validation failed. The antiforgery token could not be decrypted.
`
And the Content root path will look like this:

Content root path for mywebapp01:

```
Hosting environment: Production
Content root path: /mywebapp01
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

Content root path for mywebapp02:

```
Hosting environment: Production
Content root path: /mywebapp02
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

So the question is:

The auto-generated Dockerfile - shouldn't this variable be unique for every newly created project in Visual Studio instead of `/app`?

Maybe this is more of a tooling issue but I think they're connected and this section of the docs is where I think it's make most sense to bring it up.

Also, maybe just adding a paragraph about `WORKDIR `in the Visual Studio auto-generated Dockerfile in the SetApplicationName docs section could suffice.

It would be great if you guys could confirm this because even though I *think* I've figured this out I'm still a bit unsure if I got it all right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#setapplicationname)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This appears to be a docker issue and not an issue with this doc.
