### ISSUE TITLE
Change title to "Tutorial: Create a web API with ASP.NET Core"

### ISSUE THREAD

**Issue by Ljupco7** [aspnet/AspNetCore.Docs#12902]
Please update the title as this tutorial doesn't contain instructions on building asp.net core MVC project with the Web API project, which is the only one explained in this tutorial. The current title is misleading. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#add-a-puttodoitem-method)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Web API is part of MVC, but I see your point
