### ISSUE TITLE
Updates within PrefixKeyVaultSecretManager

### ISSUE THREAD

**Issue by michaelmairegger** [aspnet/AspNetCore.Docs#12900]
In the doc page https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#use-a-key-name-prefix improve sample for `PrefixKeyVaultSecretManager` and inherit from `DefaultKeyVaultSecretManager` and use the predefined methods

    public class PrefixKeyVaultSecretManager : DefaultKeyVaultSecretManager
    {
        private readonly string _prefix;

        public PrefixKeyVaultSecretManager(string prefix)
        {
            _prefix = $"{prefix}-";
        }

        public override bool Load(SecretItem secret)
        {
            return secret.Identifier.Name.StartsWith(_prefix);
        }

        public override string GetKey(SecretBundle secret)
        {
            return base.GetKey(secret).Substring(_prefix.Length);
        }
    }
```

**Comment by guardrex** [comment]
btw -- There's a **This Page** feedback button and form at the bottom of every topic. When the issue is opened using that approach, the issue is tagged with metadata that helps us track. Just mentioning this in passing in case you need to open future doc issues.

**Comment by guardrex** [comment]
Closing per https://github.com/aspnet/AspNetCore.Docs/pull/12901#issuecomment-502724661.

**Comment by michaelmairegger** [comment]
> btw -- There's a **This Page** feedback button and form at the bottom of every topic. When the issue is opened using that approach, the issue is tagged with metadata that helps us track. Just mentioning this in passing in case you need to open future doc issues.

Ok, thanks for pointing that out
