### ISSUE TITLE
This information should be represented as a warning in documentation .

### ISSUE THREAD

**Issue by gurmeetsinghdke** [aspnet/AspNetCore.Docs#12904]
In current documentation of session and app state here - [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#session-state).

There are few session state exhibits and last one is the following:

_Session state cookies aren't marked essential by default, so session state isn't functional unless tracking is permitted by the site visitor. For more information, see General Data Protection Regulation (GDPR) support in ASP.NET Core._

This information is very critical for developers and they should be aware that their session state in .net core 2.1 onward will not work, so this information should be represented as warning instead of an information only.

**Comment by guardrex** [comment]
Thanks @gurmeetsinghdke ... This isn't going to be as much of an issue as of 3.0 Preview 8. They're going to remove GDPR from the templates. See: https://github.com/aspnet/AspNetCore/issues/10346

The GDPR doc speaks to this scenario at the top. https://docs.microsoft.com/aspnet/core/security/gdpr

btw -- There's a **This page** feedback button at the bottom of the topic that tags issues with metadata. Just noting it for future issues that you might need to open. It helps us track work on these issues.

**Comment by gurmeetsinghdke** [comment]
> Thanks @gurmeetsinghdke ... This isn't going to be as much of an issue as of 3.0 Preview 8. They're going to remove GDPR from the templates. See: [aspnet/AspNetCore#10346](https://github.com/aspnet/AspNetCore/issues/10346)
> 
> The GDPR doc speaks to this scenario at the top. https://docs.microsoft.com/aspnet/core/security/gdpr
> 
> btw -- There's a **This page** feedback button at the bottom of the topic that tags issues with metadata. Just noting it for future issues that you might need to open. It helps us track work on these issues.

@guardrex Thanks for providing the information about elimination of GDPR from template. 
Should it not be there for documentation pertaining to .Net Core 2.1+ and <3.0? Please suggest.

**Comment by guardrex** [comment]
When the topic author returns, he'll take a look.

**Comment by Rick-Anderson** [comment]
@gurmeetsinghdke  I'm closing this for now given GDPR is going away in 3.0. If we get more complaints, I'll reconsider.
