### ISSUE TITLE
Should we resolve typed clients through IHttpClientFactory

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/AspNetCore.Docs#12917]
In the "Named clients" section, the example resolves the "github client" with `IHttpClientFactory`:

```csharp
    public NamedClientModel(IHttpClientFactory clientFactory)
    {
        _clientFactory = clientFactory;
    }

    public async Task OnGet()
    {
        var client = _clientFactory.CreateClient("github");
    }
```

But in the "Typed clients" section, the example resolves the "github client" with the typed class and does not make direct use of `IHttpClientFactory`.

```csharp
    public TypedClientModel(GitHubService gitHubService)
    {
        _gitHubService = gitHubService;
    }
```

The documentation also states "IHttpClientFactory tracks and disposes resources used by HttpClient instances"?

So even though the typed client example doesn't make direct use of `IHttpClientFactory`, can we safely assume that `IHttpClientFactory` is being used to inject `HttpClient` into `GitHubService` so that we are still getting the benefits of `IHttpClientFactory`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by stevejgordon** [comment]
Hi @MisinformedDNA,

The short answer is that you can safely assume that IHttpClientFactory is managing the HttpClient (and under handlers/connections) for the typed clients as well as named clients.

The named client approach is a little simpler to follow as we can see that we're directly using the factory. In the case of typed clients, there's more abstraction involved. Your typed client accepts HttpClient in the constructor (along with any other dependencies you have). By registering your typed client using the AddHttpClient<TClient, TImplementation> or AddHttpClient<TClient> methods, it is now created using DI and HttpClientFactory. 

Both are valid approaches and ensure that the IHttpClientFactory feature is doing the heavy lifting. I personally prefer typed clients.

I hope that helps clear things up a little?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Rick-Anderson** [comment]
Thanks @stevejgordon !
