### ISSUE TITLE
Router FallBackComponent gone in preview 6

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#12928]
Looks like this is now not a thing anymore. You may wish to remove it from this document as it will confuse people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Strange ... virtually no mention of the drop in the engineering repo.

@ajaybhargavb Can you confirm the 🔪 *Kill Order* 🔪 on `FallbackComponent`?

**Comment by ajaybhargavb** [comment]
I'm not aware of this either. @pranavkm is this no longer a thing?

**Comment by guardrex** [comment]
The only mention is on [Router displays NotFoundContent without any layout (aspnet/AspNetCore \#10445)](https://github.com/aspnet/AspNetCore/issues/10445), where Steve says ...

> We add an extra DefaultLayout property to Router (of type System.Type, just like we used to for FallbackComponent).

"**_just like we used to for_**" ... makes it seems gone. However, I can't find an issue/PR where it was removed.

**Comment by pranavkm** [comment]
`FallbackComponent` was replaced by `NotFoundContent` which lets you specify the content to display inline when no component matches a route.

**Comment by guardrex** [comment]
@pranavkm Thx ... I'll take care of it. 🔪

**Comment by guardrex** [comment]
So the idea would be that the dev places another component inside of `NotFoundContent`. We doc that separately on another PR, so I can just kill it here. :+1:
