### ISSUE TITLE
Upgrade guide doesn't talk about the changes needing to configure kestrel.

### ISSUE THREAD

**Issue by niemyjski** [aspnet/AspNetCore.Docs#12923]
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

                .ConfigureKestrel(c =&gt; {
                    c.AddServerHeader = false;
                    //c.AllowSynchronousIO = false; // TODO: Investigate issue with JSON Serialization.
                })

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by niemyjski** [comment]
This doesn't cover other web things you might be doing like health checks outside of a startup class.

**Comment by niemyjski** [comment]
It also doesn't cover the following:

`app.Use((context, func) => context.Response.WriteAsync($"Running Job: {jobOptions.JobName}"));`

```
Error | CS7036 | There is no argument given that corresponds to the required formal parameter 'configure' of 'EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder, Action<IEndpointRouteBuilder>)' | Exceptionless.Web | C:\Code\Exceptionless\src\Exceptionless.Web\Startup.cs | 197 | Active

```

**Comment by guardrex** [comment]
I'll take care of this one right after I hear back from engineering on the Kestrel-to-3.0 updates. https://github.com/aspnet/AspNetCore.Docs/pull/13775

**Comment by guardrex** [comment]
*Note to self:* https://github.com/aspnet/AspNetCore.Docs/pull/14190#issuecomment-529011785
