### ISSUE TITLE
Document enabling sticky sessions when using Blazor server apps with Azure SignalR service

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#12949]
[EDIT by guardrex to coalesce content from #15392 into this issue]
[EDIT by guardrex to add the topic metadata]
[EDIT by guardrex to remind myself to add the no-loc metadata: `no-loc: [Blazor]`]

Typically server-side Blazor apps will prerender in response to the first request which will setup the UI state on that server. When the client tries to then setup the SignalR connection for that app and is redirected through the SignalR service, we need the client to end back up on the same server. There is an option in the Azure SignalR SDK to support this scenario by enabling sticky sessions. You can turn it on by setting the "Azure:SignalR:StickyServerMode" config value to "Required".

[EDIT ... the following is from #15392 ...]

* Include a sample on how to configure it on Kubernetes as per https://github.com/aspnet/AspNetCore/issues/16645#issuecomment-547962457
* A sample on how to configure in App Service
This is done in the portal in Application Settings
* A sample on how to configure it in IIS
https://docs.microsoft.com/en-us/iis/extensions/configuring-application-request-routing-arr/http-load-balancing-using-application-request-routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by danroth27** [comment]
Eventually, Visual Studio will just do this for you (in 16.3), but for now you need to enable in manually.

**Comment by guardrex** [comment]
A P1 issue? I can work it PDQ.

Looks like this is for the *Hosting Models* topic: https://docs.microsoft.com/aspnet/core/blazor/hosting-models

**Comment by guardrex** [comment]
This is related to #15392.

Recommend moving remarks from here to there or from there to here and closing this or closing that one ........ *if that makes sense!* :smile: lol

**Comment by mkArtakMSFT** [comment]
@guardrex I agree these two are essentially the same. Feel free to use the details in either one of these and close the other one.
