### ISSUE TITLE
Error CS 1601

### ISSUE THREAD

**Issue by LouBH** [aspnet/AspNetCore.Docs#12948]
I have downloaded the starter project from GitHub as directed.  When I add to ConfigureServices I get various errors, mostly CS 1601.             services.Configure&lt;CookiePolicyOptions&gt;(options =&gt;
            {
                options.CheckConsentNeeded = context =&gt; true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddDbContext&lt;ApplicationDbContext&gt;(options =&gt;
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddDefaultIdentity&lt;IdentityUser&gt;().AddRoles&lt;IdentityRole&gt;()
               .AddEntityFrameworkStores&lt;ApplicationDbContext&gt;()
                .AddDefaultTokenProviders();

            services.AddMvc(config =&gt;
            {
                // using Microsoft.AspNetCore.Mvc.Authorization;
                // using Microsoft.AspNetCore.Authorization;
                var policy = new AuthorizationPolicyBuilder()
                                 .RequireAuthenticatedUser()
                                 .Build();
                config.Filters.Add(new AuthorizeFilter(policy));
            })
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            // Register no-op EmailSender used by account confirmation and password reset during development
            // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=532713
            services.AddSingleton&lt;IEmailSender, EmailSender&gt;();
        }

I am not having any success in figuring how to resolve all these errors.  Do you have any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Let us know when you figure it out.

**Comment by LouBH** [comment]
Not helpful, Rick.  I downloaded YOUR starter project and faithfully and carefully followed YOUR directions.  I started encountering problems immediately.  Have been able to fix some, but now I am getting more confused instead of advancing my understanding.  I am abandoning this tutorial.  I am sure there is a simpler way to do what I need to do.

**Comment by Rick-Anderson** [comment]
Can you post incorrect code?

**Comment by Rick-Anderson** [comment]
This is not a beginning tutorial. We have about 16K/month view, many reporting success.

**Comment by LouBH** [comment]
Sorry, have been out sick for a week.  Incorrect code is posted above.  Here are the errors I am getting:

Error	CS1061	'CookiePolicyOptions' does not contain a definition for 'CheckConsentNeeded' and no accessible extension method 'CheckConsentNeeded' accepting a first argument of type 'CookiePolicyOptions' could be found (are you missing a using directive or an assembly reference?)	

Error	CS0103	The name 'SameSiteMode' does not exist in the current context	ContactManager	

Error	CS1061	'IServiceCollection' does not contain a definition for 'AddDefaultIdentity' and no accessible extension method 'AddDefaultIdentity' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	ContactManager	

I have the correct namespaces.  Here is the csproj file.  (I deleted two items from the bottom itemgroup in response to error messages that they were obsolete.  I tried updating the packages but then I got a bazillion error messages about duplicate references:)
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-ContactManager-0DAD76F8-C053-4971-A8DF-4C55A4FF198B</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>
</Project>

**Comment by Rick-Anderson** [comment]
I think this requires 2.1 or higher.

**Comment by LouBH** [comment]
I thought so too, but then how did I end up with a project file that uses older versions?  I don’t have a good enough understanding of how to identify and attach the right package, if that is the correct term, to my project.  I have 2.2 on my machine.  When I tried to use Package Manager to upgrade one package a little bit, instead it upgraded all of them to the latest version and I got  lots more! errors.  If you could point me in the direction of a tutorial that would help me with these basic skills, I would really appreciate it.

**Comment by Rick-Anderson** [comment]
Install the 2.2 SDK. All packages come from the SDK now, not NuGet.  Upgrade your project to 2.2
