### ISSUE TITLE
"Unclosed tag" error in Todo.razor template code

### ISSUE THREAD

**Issue by katiep23** [aspnet/AspNetCore.Docs#12944]
Receiving "Unclosed tag 'TodoItem' with no matching end tag" error with the Todo.Razor code provided on this page.  Is this a bug?  My repo: https://github.com/katiep23/BlazorTest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by katiep23** [comment]
It occurs twice with this statement: "private IList<TodoItem> todos = new List<TodoItem>();"

And once here (in FetchData.razor): "forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");"

Looks to be an issue with the < & > inside the @code block?

**Comment by guardrex** [comment]
Are you on Preview 6?

**Comment by guardrex** [comment]
I see your project ... that's Preview 5, so you'll need to go to Preview 6 for the updates.

https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by DanTsion** [comment]
Excuse me, but i am in preview 6 and i had the same error, 

I created a new project for test some Component like InputData(who doesn't work) and i got this error...

**Comment by guardrex** [comment]
@DanTsion Put up a repro project on GitHub that demonstrates the error. Use the **This Page** feedback button at the bottom of the topic to open a new issue and provide a link to the project. I'll pull it down and take a look.
