### ISSUE TITLE
Update Introduction to ASP.NET Core for 3.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#12958]
Update for 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson Can I help with this? If yes, what needs doing. I see the following possibilities:

- Mention and link to gRPC
- Add Blazor and gRPC to the learning path options under "Follow a tutorial..."
- Update the sample snippet under "Regions in sample code" to either:
 - Use `Host`.
 - Be simpler

**Comment by Rick-Anderson** [comment]
@serpent5  I like your outline. That would be great if you could PR this.
