### ISSUE TITLE
Mac Instructions

### ISSUE THREAD

**Issue by angie-garciapaz** [aspnet/AspNetCore.Docs#12960]
The instructions for a mac user are incomplete for many of the pages. Many of the steps assume the user has completed certain steps that aren't mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you be specific? What steps are missing?

**Comment by angie-garciapaz** [comment]
Page: Get Started
-The user should be given the choice to use the GUI to make the project and not just the terminal.

-Unless the user has f1, f2, etc as the standard function keys, cmd-opt-f5 won't work so it would be command-option-enter to run without the debugger.

Page: Add a model
- It's assumed that we've added the Data folder without being told
- I think it should be explained why we're using Models in the RazorPagesMovieContext instead of Data in the namespace

Page: Add a new field
-Mac users can delete the database by right-clicking the database and then running  "dotnet ef database update"

**Comment by Rick-Anderson** [comment]
@angie-garciapaz  thanks for the specific information. We'll get this addressed in the next update.

**Comment by dbrtly** [comment]
I'm also getting errors on a Mac.

An unhandled exception occurred while processing the request.

PlatformNotSupportedException: LocalDB is not supported on this platform.
System.Data.SqlClient.SNI.LocalDB.GetLocalDBConnectionString(string localDbInstance)

**Comment by jlee-vi** [comment]
Would it be possible to have someone complete the steps using a Mac - should be clear pretty quickly just how much of the instructions are incomplete.

**Comment by angie-garciapaz** [comment]
@jlee-vi
The tutorial is complete for Mac users. The errors I found was more to do with the verbiage of the tutorial. The only thing that didn't work for me as it should've was the search. The search will only work if it is capitalized like the book. For example, "searchString=ghost" will not work but "searchString=Ghost" will work and the results are the same if I use the search box.

@dbrtly
What part of the tutorial are you getting this error?

**Comment by Rick-Anderson** [comment]
Per the search article:

Note: The Contains method is run on the database, not in the C# code. The case sensitivity on the query depends on the database and the collation. On SQL Server, Contains maps to SQL LIKE, which is case insensitive. **In SQLite, with the default collation, it's case sensitive.**

**Comment by jamoore5** [comment]
> Per the search article:
> 
> Note: The Contains method is run on the database, not in the C# code. The case sensitivity on the query depends on the database and the collation. On SQL Server, Contains maps to SQL LIKE, which is case insensitive. **In SQLite, with the default collation, it's case sensitive.**

Thanks this helped solve my confusion from the document.

The screenshot from the browser using the form used lowercase "ghost" and I could not figure out why that did not work for me on a mac.
