### ISSUE TITLE
Can we get a list of breaking changes to EditForm please for the latest Blazor release?  Is there a place where there is a list of the multitude of breaking changes for each blazor release.  This last one was super bad (.NET Core 3.0.0-preview6).  It's almost unusable, it's super unstable.

### ISSUE THREAD

**Issue by longhornleads** [aspnet/AspNetCore.Docs#12988]
# Before you open an issue

If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page.

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

{ description here }

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by guardrex** [comment]
Hello @longhornleads ... A couple of approaches:

* The blog posts generally list the major changes (*but not the smaller updates* ... there's a lot of churn during previews and a *TON* of small fixes and updates ... too many to list out in the blog post). https://devblogs.microsoft.com/aspnet/?s=blazor&submit=%EE%9C%A1
* The engineering repo:
  * Release Notes (but not super helpful given that it's a high level release overview): https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview6.md
  * Bug Fixes: https://github.com/aspnet/AspNetCore/issues?q=is%3Aissue+milestone%3A3.0.0-preview6+label%3ADone+label%3Abug
  * Remove the `bug` label and filter on `milestone:3.0.0-preview6`, and you can really see what they worked on :point_right: https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A3.0.0-preview6 :point_left: sub-search for "validation" or "EditForm" and you might find the issues that pertain to those.

Eventually (after 3.0 RTM), breaking changes for Blazor will be covered in our regular migration topic set along with the rest of the ASP.NET Core changes.
