### ISSUE TITLE
Missed part how to enable UserSecrets

### ISSUE THREAD

**Issue by Andrey-Pavlov** [aspnet/AspNetCore.Docs#12987]
if (env.IsDevelopment())
			{
				builder.AddUserSecrets&lt;Startup&gt;();
			}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not required.
