### ISSUE TITLE
How to verify the automatically-bound property in Get?

### ISSUE THREAD

**Issue by sadqiang** [aspnet/AspNetCore.Docs#12985]
The warning box says:

> For security reasons, you must opt in to binding GET request data to page model properties. Verify user input before mapping it to properties. Opting in to GET binding is useful when addressing scenarios which rely on query string or route values.
> 
> To bind a property on GET requests, set the [BindProperty] attribute's SupportsGet property to true: [BindProperty(SupportsGet = true)]

My question:
As binding is done automatically by the framework, how can I verify the property?
Is using ModelState.IsValid the verification method you meant? 

Please give me an example. My code below always rejects the incoming Get because 
the Name property is always invalid. I think I am wrong  in interpreting  "Verify user input before mapping it to properties." in the warning box above.

    public class EditModel : PageModel
    {
        private readonly AppDbContext _db;
        public EditModel(AppDbContext db) => _db = db;

        [BindProperty(SupportsGet = true)]
        public Customer Customer { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            Customer = await _db.Customers.FindAsync(Customer.Id);
            if (Customer == null)
                return NotFound();

            return Page();
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Verify it's not dangerous, for example JavaScript or SQL injection.
