### ISSUE TITLE
KeyVault with Core 3.0 Preview?

### ISSUE THREAD

**Issue by katiep23** [aspnet/AspNetCore.Docs#12991]
Any examples on how to implement KeyVault with IHostBuilder instead of IWebHostBuilder in Program.cs for 3.0 Preview? Would be greatly appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.0#secret-storage-in-the-production-environment-with-azure-key-vault)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @katiep23 ... Usually, we wait until the Release Candidate because there's so much churn in engineering that we'd find ourselves returning to update topics a second time if we work them this early. They haven't announced dates yet, but they've said publicly that there will be several more rapid preview releases before the framework reaches RC. Keep an eye out for their remarks on 3.0 RC ... that's when we'll really dig-in on these 3.0 topic+sample updates.

**Comment by katiep23** [comment]
I wanted to provide the following code I used in 3.0 in case anyone else is interested.

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();

                }).ConfigureAppConfiguration((ctx, builder) =>
                {
                    var azureServiceTokenProvider = new AzureServiceTokenProvider();
                    var keyVaultClient = new KeyVaultClient(
                    new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback));
                    builder.AddAzureKeyVault("myendpoint", keyVaultClient, new DefaultKeyVaultSecretManager());
                });
    }
```
