### ISSUE TITLE
The Images in the Create a web API with ASP.NET page are for Visual studio 2017

### ISSUE THREAD

**Issue by mzkev** [aspnet/AspNetCore.Docs#12998]
A proposal to update the images in the Create a web API with ASP.NET page with Visual studio 2019. 

I noticed it states Visual studio 2019 in the prerequisites and the images are for Visual studio 2017. 

If my proposal gets accepted i will make sure i compress the images with TinyPNG and also follow the contribute guide.

**Comment by guardrex** [comment]
Hello @mzkev ... I think the updates just went in on https://github.com/aspnet/AspNetCore.Docs/pull/12989. Those updates will probably go live today. Check back this evening. If you detect an issue with the topic, use the **This Page** feedback button at the bottom of the topic to open an issue (it will tag your issue with metadata that helps us track the work).
