### ISSUE TITLE
OAuth/OpenID Connect Scopes in the Authorization?

### ISSUE THREAD

**Issue by tinod** [aspnet/AspNetCore.Docs#12999]
Is there an easy way to deal with OAuth/OpenID Connect Scopes in the Authorization?
So far, it appears that you will have to create a handler and a requirement that get the http://schemas.microsoft.com/identity/claims/scope claim (which isn't even a named claim in the System.Security.Claims.Claim enum), split it (with a space as the separator) and then check whether there is a value that matches the [Authorize] attribute on the method.
I would 'think' there should be an 'easier' and 'more convenient' way to handle Scopes, since this should be the primary way to deal with authorizations in an API using OAuth/OpenID Connect...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #16191
