### ISSUE TITLE
Can not create User Class

### ISSUE THREAD

**Issue by ravick4u** [aspnet/AspNetCore.Docs#13002]
I have created my project with following instructions

- From the Visual Studio File menu, select New &gt; Project. Name the project WebApp1
- Select ASP.NET Core Web Application &gt; OK
- Select ASP.NET Core 2.2 in the dropdown
- Click on change authentication and select individual user account and click ok

Next I would like to add scaffolding so followed below step

- From Solution Explorer, right-click on the project &gt; Add &gt; New Scaffolded Item.
- From the left pane of the Add Scaffold dialog, select Identity &gt; ADD

On this screen I am unable to select/create user class. Would like to see what I am doing wrong here

Currently I am using VS2017 15.9.13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ravick4u** [comment]
![UserClass option is disabled](https://user-images.githubusercontent.com/11890407/60122391-190ef080-9753-11e9-9e8b-2340cb8ece63.png)

**Comment by Rick-Anderson** [comment]
Per the instructions, you can't use an existing DB context

To create a new user context and possibly create a custom user class for Identity:
Select the + button to create a new Data context class.
Select ADD.
