### ISSUE TITLE
Is dotnet new blazorhosted meant to be dotnetnew

### ISSUE THREAD

**Issue by voltagex** [aspnet/AspNetCore.Docs#13009]
```
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf
```
`&gt;dotnet new blazorhosted`
`No templates matched the input template name: blazorhosted.`

The template seems to be called blazorserverside now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @voltagex ... Those are two different templates.

Make sure you've installed the Preview 6 templates ...

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2
```

... and you should see them all when you execute `dotnet new --help` ...

<img width="476" alt="Capture" src="https://user-images.githubusercontent.com/1622880/60175123-481b7580-97d8-11e9-8f6a-d36e18e3229d.PNG">

**Comment by voltagex** [comment]
That makes sense but is a bit confusing when starting out with blazor.
Thanks.

**Comment by guardrex** [comment]
It's in the Get Started topic. We assume a reader will see it there first, but sometimes things don't work out that way. 

Step 2 of https://docs.microsoft.com/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by guardrex** [comment]
I'm about to do a doc sweep on these for the Preview 6 release on https://github.com/aspnet/AspNetCore.Docs/issues/10717. I'll take another look at how we describe the templates and how we cross-link. Thanks for letting me know that you hit this issue.
