### ISSUE TITLE
Will this wok on a Web API?

### ISSUE THREAD

**Issue by gojanpaolo** [aspnet/AspNetCore.Docs#13004]
Seeing that this is under `Web apps`, will this work on a `Web API` (at least adding Controllers from a separate class library)?
Thank you! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
Yes. Web APIs are Web Apps as far as ASP.NET Core is concerned.

**Comment by gojanpaolo** [comment]
@ardalis I see. Thank you!
