### ISSUE TITLE
Improve Code Examples for "gRPC services with ASP.NET Core"

### ISSUE THREAD

**Issue by MDendura** [aspnet/AspNetCore.Docs#13037]
* The first and second code blocks are identical. It may be more useful to show just the `ConfigureServices` method in the first block and just the `Configure` method in the second to better highlight the point of interest.

* The text above the last code block talks about getting access to the `HttpContext` but the code itself does not show this and is instead a duplicate of the previous block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JamesNK** [comment]
Thanks for reporting this. It is a mistake. A PR fixing it here - https://github.com/aspnet/AspNetCore.Docs/pull/13051

**Comment by Rick-Anderson** [comment]
@JamesNK I don't think it's a mistake -  but it's OK just to show the `ConfigureServices` in the first and `Configure` in the 2nd. The code is highlighted correctly and shows the entire *Startup.cs* file.

@MDendura  wrote:
> The text above the last code block talks about getting access to the `HttpContext` but the code itself does not show this

That's boiler plate code generated by the templates.

**Comment by JamesNK** [comment]
The last code block not showing how to use GetHttpContext was a mistake.

**Comment by scottaddie** [comment]
Fixed in https://github.com/aspnet/AspNetCore.Docs/pull/13051, which will be published when the Preview 7 release ships.
