### ISSUE TITLE
Static Assets in Reusable Razor class libraries 

### ISSUE THREAD

**Issue by nacoleman** [aspnet/AspNetCore.Docs#13038]
"When the app is published, the companion assets from all referenced projects and packages are copied into the wwwroot folder of the published app under _content/{LIBRARY NAME}/."

I think The static assets should be part of the demo app... It doesn't seem to work at all. I have followed the steps and get nothing published into wwwroot folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio#create-an-rcl-with-static-assets)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  didn't you just test this?

**Comment by nacoleman** [comment]
@Rick-Anderson thx - I am using .net core 2.2 web app to consume the RCL. The RCL is very basic with one View in it and one css file in the wwwroot directory. The view works fine and is used in the consuming app but the css doesn't.

based on the comments on this issue: https://github.com/aspnet/AspNetCore.Docs/issues/7662 it seems like a lot more work is required than this help section suggests. They may be outdated comments though or perhaps I am just doing something very hastily on a friday afternoon!

**Comment by guardrex** [comment]
@nacoleman You need to be on 3.0 Preview 6. It won't work on 2.2.

I'll check the versioning in the topic to see if we have it set up correctly.

**Comment by guardrex** [comment]
It's versioning. I'll fix it. Thanks for reporting this @nacoleman. Sorry for the error.

**Comment by nacoleman** [comment]
@guardrex Ah ok that explains everything! Thanks for getting back to me so fast. Spent a few hours trying to figure it out but learnt a few things in the process so no harm done.

**Comment by guardrex** [comment]
Sorry about that. We were a bit up in the air on how to host the content because static assets apply to both RCL **with** and **without Blazor**. We figured out that we wanted to put the content here and then link to it from the Blazor topic on *Razor component class libraries*. Getting that all figured out, we didn't get the correct versioning tags on the content. It's a simple fix (#13039). Thanks again for reporting it.

**Comment by MylesRip** [comment]
I'm a Blazor newbie and I might be missing something, but this appears to be broken again as far as I can tell. The styles.css file located in wwwroot of a referenced razor component does not get picked up by the consuming Blazor app. I'm using ASP.NET Core 3.0 and the razor component is targeting .NET Standard 2.1.
