### ISSUE TITLE
Migrate Hosting ASP.NET Core Images with Docker over HTTPS from GitHub to docs

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13045]
Migrate [Hosting ASP.NET Core Images with Docker over HTTPS](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md) to our docs repo.

**Comment by spboyer** [comment]
These two documents should be included in this issue. All 3 can be summarized as a single document. 

https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md 

https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-windows.md
