### ISSUE TITLE
Vertical Scroll On All Pages In Default Razor Project Using .Net Core 2.2

### ISSUE THREAD

**Issue by satbirbaidwan** [aspnet/AspNetCore.Docs#13047]
Hi,
I just noticed that there is a vertical scroll (shown on the right side) on all pages. I checked this on another machine and new project thinking i may have changed something and it still shows on project created using Core 2.2.

To confirm i created a another project on first machine this time using Core 2.1 and it does not shows the vertical scroll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by satbirbaidwan** [comment]
![VscrollIssue](https://user-images.githubusercontent.com/24276254/60367339-32aa7500-99ab-11e9-8b91-04f1c7eb6db0.PNG)

**Comment by Rick-Anderson** [comment]
The CSS has changed.

**Comment by satbirbaidwan** [comment]
Hey Rick, 
I don't think its changed on my side as i tested on new projects as well ?
