### ISSUE TITLE
Tutorial - $PATH update for using scaffolding tool is missing

### ISSUE THREAD

**Issue by bashdx** [aspnet/AspNetCore.Docs#13049]
When going through this tutorial you should mention in the scaffolding section to update the $PATH environment variable (at least on Linux) so `dotnet tool aspnet-codegenerator` works.

`export PATH=$HOME/.dotnet/tools:$PATH`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bashdx  thanks, we'll get this updated in the next sweep.

**Comment by bashdx** [comment]
Awesome, thank you!
