### ISSUE TITLE
Possible mistake in content root path setting example

### ISSUE THREAD

**Issue by Sequenta** [aspnet/AspNetCore.Docs#13057]
If we use code sample from example, line ``builder.UseSolutionRelativeContentRoot("<SOLUTION-RELATIVE-PATH>");`` won't be called:
```
public class CustomWebApplicationFactory<TStartup>
     : WebApplicationFactory<RazorPagesProject.Startup>
{
     protected override void ConfigureWebHost(IWebHostBuilder builder)
     {
         builder.ConfigureServices(services =>
         {
             //This code is not called
             builder.UseSolutionRelativeContentRoot("<SOLUTION-RELATIVE-PATH>");
             ...
         });
     }
}
```
But if we write this line directly in overriden method, this will override content root path correctly:

```
public class CustomWebApplicationFactory<TStartup>
     : WebApplicationFactory<RazorPagesProject.Startup>
{
     protected override void ConfigureWebHost(IWebHostBuilder builder)
     {
        //Now this works
        builder.UseSolutionRelativeContentRoot("<SOLUTION-RELATIVE-PATH>");
     }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#how-the-test-infrastructure-infers-the-app-content-root-path)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sequenta ... I can't find an engineering example, but that seems correct; and if it's going to show `ConfigureServices`, it probably should be `ConfigureTestServices` (but I'll remove that for the update).

I'll make the change and engineering will review to confirm. Thanks for opening this issue.
