### ISSUE TITLE
protobuf syntax highlighting

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#13053]
There is no syntax highlighting of protobuf code on docs.microsoft.com

Example: https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.0#proto-file

VS 16.1 added syntax highlighting in the editor. It would be nice if it could be highlighted on the docs website.

Syntax file: https://github.com/michaeledgar/protobuf-tmbundle/blob/master/Protocol%20Buffers.tmbundle/Syntaxes/Protocol%20Buffer.tmLanguage

@shirhatti @JunTaoLuo

**Comment by scottaddie** [comment]
A new dev lang needs to be created to support this. [Engineering request #102367](https://ceapex.visualstudio.com/Engineering/_workitems/edit/102367) has been opened for creation of the dev lang.
