### ISSUE TITLE
Shared Layout

### ISSUE THREAD

**Issue by danobri** [aspnet/AspNetCore.Docs#13062]
From what I can tell, it is not possible for Blazor Pages (.razor) and Razor Pages (.cshtml) to share a single layout file.  Is that correct?  Whether it is or is not, I think it should be called out in this documentation, as it seems like a common case.  For instance, if you create a new Blazor application and include authorization, you are now in a hybrid environment where the Identity pages are all .cshtml, and have a separate layout from the Blazor pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by jhubsharp** [comment]
In this case, wouldn't you code your authentication pages in Razor pages? https://chrissainty.com/securing-your-blazor-apps-authentication-with-clientside-blazor-using-webapi-aspnet-core-identity/

**Comment by mikoskinen** [comment]
Here's an article which shows one way of sharing a layout between a Razor Page and a Blazor Page: https://mikaelkoskinen.net/post/combining-razor-blazor-pages-single-asp-net-core-3-application

Disclaimer: The article was written by yours truly.

**Comment by guardrex** [comment]
Note to self: https://github.com/aspnet/AspNetCore/issues/10883

**Comment by jvallejoa** [comment]
**Here,my Upvote to migrate all obsolete Identity razor pages to blazor components.**
