### ISSUE TITLE
Unable to call AddConfiguration from ILoggingBuilder as explained here

### ISSUE THREAD

**Issue by theswanand** [aspnet/AspNetCore.Docs#13060]
'ILoggingBuilder' does not contain a definition for 'AddConfiguration' and the best extension method overload 'ChainedBuilderExtensions.AddConfiguration(IConfigurationBuilder, IConfiguration)' requires a receiver of type 'IConfigurationBuilder'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Make sure your Program.cs file has a using statement for Microsoft.Extensions.Logging.

**Comment by theswanand** [comment]
Thanks, it worked. Can you please add that in tutorial as well. Visual Studio is also not helping a lot.
