### ISSUE TITLE
Can this be used with Blazor client side apps?

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#13079]
Can this package be used within blazor client side applications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
AFAIK, the answer is *yes* because the text of the [hosting models topic](https://docs.microsoft.com/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#client-side) included a remark that Blazor client-side using the hosted template [**Blazor (ASP.NET Core Hosted)** (`dotnet new blazorhosted`)]  can communicate with the back-end server using SignalR. Engineering has stuck by that remark over successive preview releases. If you try it and it doesn't work, open an engineering issue to inquire further.

**Comment by dazinator** [comment]
@guardrex I tried it and it doesnt work in blazor client side apps. It works in blazor apps that are actually run server side - but I'm talking about pure client side blazor apps. I have seen some issues on engineering that say they need to take a later version of mono with web socket support before signalr client will work in a blazor client application.. but took me a fair bit of digging to find that information and investigation to discover the issue - might be good to add a note about blazor to usage to this doc perhaps?

**Comment by guardrex** [comment]
I'll set this issue up for triage. We only have that one *very brief passing remark* that makes it seem like it would work. We should at least clarify what is meant by the "or SignalR" part of ...

> Blazor (ASP.NET Core Hosted) (dotnet new blazorhosted) – Hosted by an ASP.NET Core server. The ASP.NET Core app serves the Blazor app to clients. The Blazor client-side app can interact with the server over the network using web API calls **or SignalR.**

(emphasis added)

**Comment by dazinator** [comment]
And here is the related issue I found: https://github.com/aspnet/AspNetCore/issues/10489

**Comment by mkArtakMSFT** [comment]
There is currently no SignalR client for Blazor, other than the external community project.
