### ISSUE TITLE
Test the Web API Id Issue

### ISSUE THREAD

**Issue by timthayne** [aspnet/AspNetCore.Docs#13073]
In step 3 of the "Test the web API" section, the hardcoded Id should not be used (it will be unique for every user).

Instead, the Id of one of two records returned from the previous call ( `http://localhost<port>/api/books`) should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@timthayne  apparently most folks no that. It's not just on step 3, it's everywhere in the article. See #13118
