### ISSUE TITLE
Instruction missing

### ISSUE THREAD

**Issue by arcotek-ltd** [aspnet/AspNetCore.Docs#13080]
Where does the very last code segment go?
```
app.UseMvc(routes =&gt;
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by portlandtom** [comment]
This is just a copy of the code that deals with the URL, it is highlighting how the information you pass it is processed also know as the "URL Routing Logic", more info regarding this on this very page if you scroll up a bit. You can find the code mentioned in the Startup.cs of the solution, at the bottom.
