### ISSUE TITLE
What are some examples of authentication resource?

### ISSUE THREAD

**Issue by EKanadily** [aspnet/AspNetCore.Docs#13082]
"credentials that are then compared to those stored in an operating system, database, app or resource"
what are some examples of a "resource"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
ASP.NET Core Identity
