### ISSUE TITLE
Please revise this entire document. 

### ISSUE THREAD

**Issue by nezoic** [aspnet/AspNetCore.Docs#13094]
Everything in here, including the many, many comments on how poor this documentation is, is very confusing. I've spent days trying to get a simple post to work, reading through all the feedback / complaints here and still I cannot figure out what is wrong. So please, either remove this documentation all together or completely update it with the latest and greatest information that is tested and works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
Moved to #16186
