### ISSUE TITLE
Blazor Client Side (Preview 6)

### ISSUE THREAD

**Issue by smjltd** [aspnet/AspNetCore.Docs#13096]
Unable to run it on iOS Safari getting the following error
Unhandled Promise Rejection: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context. (mono.js:239229)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @smjltd ... Open that on the engineering repo for the engineers to take a look at.

https://github.com/aspnet/AspNetCore/issues
