### ISSUE TITLE
HTML Helpers

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#131]
ASP.NET MVC -> Views -> HTML Helpers
- What are HTML helpers?
- Built-in HTML helpers
- Writing custom HTML helpers
- #2009 special-case an entry named "htmlAttributes" in the ViewDataDictionary (optionally augmented using additionalViewData parameters) when executing their default templates. 
- #2008 Improve "expression name" documentation -- describe supported syntax #2008

**Comment by robbert229** [comment]
@danroth27, Is it okay If I write this?

**Comment by duncanawoods** [comment]
> If you would like to review early drafts and outlines of this topic, please leave a note with your contact information in the issue

I would be interested to read a draft please. duncan@tangle.ai

**Comment by jairp8** [comment]
I would like to read a draft too: jairp8@gmail.com

**Comment by Rick-Anderson** [comment]
@robbert229  are you still interested in writing this?

**Comment by Rick-Anderson** [comment]
Fixed in #3762 and #3762
