### ISSUE TITLE
Outdated example (strongly-typed HubContext)

### ISSUE THREAD

**Issue by AzizAK** [aspnet/AspNetCore.Docs#13119]
Hey,

it seems the example of strongly-typed HubContext outdated, Please have look at SendMessage function.

```csharp
public async Task SendMessage(string message)
{
    await _strongChatHubContext.Clients.All.ReceiveMessage(message);
}
```

I think it has to be something like this

```csharp
public async Task SendMessage(string message)
{
    await _strongChatHubContext.Clients.All.SendAsync("ReceiveMessage", message);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
The main point of strongly-typed `HubContext` is that you can invoke methods with the type information present (via the interface) and not have to write strings and pass generic objects.

Why do you think this is wrong? Did you try it out and hit an issue?

**Comment by AzizAK** [comment]
Sorry misunderstood. Thank you.
