### ISSUE TITLE
not seeing  identity pages/razorpage library when  following example nor in github source

### ISSUE THREAD

**Issue by calebwidmer** [aspnet/AspNetCore.Docs#13123]
inside Create a Web app with authentication:
Not seeing any of this when following the directions, nor in github...:
* not a RCL
* none of the referenced Identity/Account areas are created
* not  seeing it in github either
thanks a bunch:

The generated project provides ASP.NET Core Identity as a Razor Class Library. The Identity Razor Class Library exposes endpoints with the Identity area. For example:

/Identity/Account/Login
/Identity/Account/Logout
/Identity/Account/Manage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What version?  `dotnet --version`
Take a closer look.

*he Identity Razor Class Library exposes endpoints with the Identity area. For example:*

Those are endpoints, not files.

**Comment by Rick-Anderson** [comment]
examine the files created with `dotnet new webapp --auth Individual -o WebApp1`

**Comment by calebwidmer** [comment]
thanks for the quick response, I was looking for physical files like a Razor page library project and related /Identity/Account/ files and not a reference as the page infers. I tried to look into the link provided for "ASP.NET Core Identity" for more details , but it is linked to this specific page (circular).  
FYI, Totally liking the idea of not having to create identity UI, TYVM!
 "AddDefaultUI" nice...
