### ISSUE TITLE
GrPC invalid http/2 connection preface

### ISSUE THREAD

**Issue by hooseinsaid** [aspnet/AspNetCore.Docs#13120]
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722806": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence1& buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync() at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication1 application)
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722807": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence1& buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync() at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication1 application)
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722808": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence1& buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync() at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication1 application)
Microsoft.Hosting.Lifetime: Information: Application is shutting down...
EventSource Error: ERROR: Exception during construction of EventSource Microsoft-System-Net-Primitives: Incorrect function.
The program '[15348] GrPC.exe: Program Trace' has exited with code 0 (0x0).
The program '[15348] GrPC.exe' has exited with code -1073741510 (0xc000013a).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
`dotnet --version` ?

**Comment by hooseinsaid** [comment]
it is 3.0
  ```
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
```

**Comment by iulianaciura** [comment]
I bumped into the same issue with the Greeter sample and the fallback was to bypass Grpc.Net.Client and use just Grpc.Core.
Hope this helps!

**Comment by fabio770** [comment]
I am facing the exact same situation

**Comment by zxyao145** [comment]
> I bumped into the same issue with the Greeter sample and the fallback was to bypass Grpc.Net.Client and use just Grpc.Core.
> Hope this helps!

Thanks a lot, I solved the problem in this way.

**Comment by mustakimali** [comment]
> I bumped into the same issue with the Greeter sample and the fallback was to bypass Grpc.Net.Client and use just Grpc.Core.
Hope this helps!

It helped. Thanks.

This is an issue with preview7 as well. Any plan to fix this in final release?

**Comment by fabio770** [comment]
> I bumped into the same issue with the Greeter sample and the fallback was to bypass Grpc.Net.Client and use just Grpc.Core.
> Hope this helps!

Thank you! This solved my problem

**Comment by tehstun** [comment]
> I bumped into the same issue with the Greeter sample and the fallback was to bypass Grpc.Net.Client and use just Grpc.Core.
> Hope this helps!

@iulianaciura  could you add more context for how you used core to get around this? Maybe a example? Thanks.

**Comment by JamesNK** [comment]
Hi everyone

I think the issue here is a mis-match between the server and the client over whether to use HTTPS.

Grpc.Net.Client by default will use HTTPS:

```cs
   var httpClient = new HttpClient();
    // The port number(5001) must match the port of the gRPC server.
    httpClient.BaseAddress = new Uri("https://localhost:5001");
    var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);
```

To use Grpc.Net.Client without TLS you must set an app context switch and change the base address to start with http:

```cs
    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
    var httpClient = new HttpClient();
    // The port number(5001) must match the port of the gRPC server.
    httpClient.BaseAddress = new Uri("http://localhost:5001");
    var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);
```

**Comment by JamesNK** [comment]
When you run the gRPC server, what is the console output when it starts?

For example:

```
C:\Development\Source\AspNetCore.Docs\aspnetcore\tutorials\grpc\grpc-start\sample\GrpcGreeter [jamesnk/grpc-sample-fix ≡]> dotnet run
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\Source\AspNetCore.Docs\aspnetcore\tutorials\grpc\grpc-start\sample\GrpcGreeter
```

`Now listening on: https://localhost:5001` indicates that you want to use HTTPS to call the server.

**Comment by tehstun** [comment]
> Hi everyone
> 
> I think the issue here is a mis-match between the server and the client over whether to use HTTPS.
> 
> Grpc.Net.Client by default will use HTTPS:
> 
> ```cs
>     var httpClient = new HttpClient();
>     // The port number(5001) must match the port of the gRPC server.
>     httpClient.BaseAddress = new Uri("https://localhost:5001");
>     var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);
> ```
> 
> To use Grpc.Net.Client **without** TLS you must set an app context switch and change the base address to start with http:
> 
> ```cs
>     AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
>     var httpClient = new HttpClient();
>     // The port number(5001) must match the port of the gRPC server.
>     httpClient.BaseAddress = new Uri("http://localhost:5001");
>     var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);
> ```

This worked great for me @JamesNK  thank you. Is this expected to be a flag later on or are we expected to be adjusting the context in the future if we require http?

Thanks.

**Comment by JamesNK** [comment]
I don't know of plans to make HTTP/2 without TLS officially supported.

Disclaimer that you should only use HTTP in development. Always use HTTPS for real data over the internet.

**Comment by blowdart** [comment]
As no browser supports HTTP/2 without TLS encryption is defacto mandatory. You're in uncharted and unsupported scenarios. This will not be exposed as a flag, and will remain only available as an AppContext switch which we will remove at some point.

**Comment by JamesNK** [comment]
Documentation on common TLS errors has been added here - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0

**Comment by tarockx** [comment]
Just wanted to report that this problem also affects the sample that uses gRPC as a local inter-process communication mechanism, described here:
https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-5.0
With the code in that sample, I got the error mentioned in the OP. 
To fix it, I had to replace:
`options.ListenUnixSocket(SocketPath);`
with
```
options.ListenUnixSocket(socketPath, s => {
    s.UseHttps();
});
```
on the server's Program.cs
and I also had to replace:
`return GrpcChannel.ForAddress("http://localhost", new GrpcChannelOptions`
with
`return GrpcChannel.ForAddress("https://localhost", new GrpcChannelOptions`
in the client's `CreateChannel()` method.

**Comment by Leonardo-Ferreira** [comment]
im having the same issue, but im trying to use postman as the client... i'm using .net 10, latest version of Grpc.AspNetCore. Perhaps its worth mentioning that im on a MAC, not windows or linux
