### ISSUE TITLE
Multiple ToC links for Logging

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#13121]
This page lives under both "Fundamentals" and "Test, debug and troubleshoot" in the ToC. Is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hi @serpent5 ... Yes, it was intentional.

https://github.com/aspnet/AspNetCore.Docs/commit/96759e7db2353ebf9cec7ff4927ec21076a6bc77

**Comment by serpent5** [comment]
Thanks @guardrex (and thanks for the commit reference). It confused me a little as I was going through the Testing section, so I figured it wouldn't hurt to ask. :)
