### ISSUE TITLE
Highlighted code missing

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13143]
see first block featuring `services.Configure`

Turns out this is an [internal bug](https://icm.ad.msft.net/imp/v3/incidents/details/131591244/home)

# This impacts all of the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
I was going through the docs having the same issue. Parts of all highlighted codes are missing.
![Capture](https://user-images.githubusercontent.com/6568968/60755813-13e55780-a017-11e9-8152-bb314bb68db0.PNG)

**Comment by abarrak** [comment]
Me too in all docs.

**Comment by Rick-Anderson** [comment]
Fixed
