### ISSUE TITLE
Core 3, Angular Auth Template Route Errors

### ISSUE THREAD

**Issue by gavdraper** [aspnet/AspNetCore.Docs#13149]
I've just created an angular app with auth by using the commands at the top of this page. It seems to build fine on the latest version core 3 at this time but when I run the app I get route errors when I try to access register or login screens...

"Cannot match any routes. URL Segment: 'Identity/Account/Register'"

I've made no changes to the template, not sure if I have missed a step? Does Identity Server need to be manually setup? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
> It seems to build fine on the latest version core 3

Can you open an issue at https://github.com/aspnet/aspnetcore and give details of your environment so that we can investigate?

**Comment by Rick-Anderson** [comment]
@gavdraper and list the  https://github.com/aspnet/aspnetcore here.

**Comment by codingcronus** [comment]
Why is this issue closed? I am having the same issue with the latest dotnet 3.0 preview SDK.

I btw. also had to configure CORS in order to run the Angular with authentication sample, otherwise the _configuration/{clientId} endpoint would return 404.
