### ISSUE TITLE
After adding the "SeedData" class, things started to break

### ISSUE THREAD

**Issue by mayee007** [aspnet/AspNetCore.Docs#13146]
Till "SeedData.cs" file was added, everything was working fine. Added class  "SeedData.cs", updated "Program.cs", also deleted all tables from database. Restarted the application and now getting this error. 
 
ArgumentNullException: Value cannot be null.
 Parameter name: connectionString
Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(string value, string parameterName)
Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, string connectionString, Action&lt;SqlServerDbContextOptionsBuilder&gt; sqlServerOptionsAction)
MvcMovie.Startup.&lt;ConfigureServices&gt;b__4_1(DbContextOptionsBuilder options) in Startup.cs
+
                options.UseSqlServer(Configuration.GetConnectionString("MvcMovieContext")));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@mayee007 The stack trace you've provided indicates that the database connection string can't be found. Confirm that your *appsettings.json* file contains the following property:

```json
  "ConnectionStrings": {
    "MvcMovieContext": "Server=(localdb)\\mssqllocaldb;Database=MvcMovieContext-1;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
```

The `ConfigureServices` method of the *Startup.cs* file looks for that specific property:

```csharp
services.AddDbContext<MvcMovieContext>(options =>
       options.UseSqlServer(Configuration.GetConnectionString("MvcMovieContext")));
```

**Comment by esmhos** [comment]
why i should use "Seed the database" did i will use it in real app ?
