### ISSUE TITLE
Cookie Consent removed from Template in 3.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13141]
See https://github.com/aspnet/AspNetCore/issues/10346

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
# GDPR 3.0 update outline

* Keep the 2.2 version
* The 3.0 version will be only one paragraph, which follows:

The ASP.NET Core 3.0 templates provide a stubbed out privacy page that you can replace with your privacy and cookie use policy.

To enable the cookie consent feature found in the ASP.NET Core 2.2 templates, see the **enable cookie consent in 3.0** section. View the 2.2 version of this document for an explanation of the ASP.NET Core 2.2  GDPR support.

**Comment by Rick-Anderson** [comment]
@blowdart  can your review my outline proposal to update the GDRP doc for 3.0?

**Comment by blowdart** [comment]
Aye, fine.

**Comment by Scobiform** [comment]
Context is out of the box error - so please update
