### ISSUE TITLE
Incorrect Statement ?

### ISSUE THREAD

**Issue by AdimUser** [aspnet/AspNetCore.Docs#13148]
There is a sentence in this document like "Don't create a web API controller by deriving from the Controller base class", But I guess It should be "Don't create a web API controller by deriving from the Controller class" , The word 'base' should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
It's correct, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller

**Comment by scottaddie** [comment]
@AdimUser I see where the confusion is coming from. I'll update the doc accordingly. It is indeed the `Controller` class that we discourage inheriting from in a web API controller.

**Comment by Rick-Anderson** [comment]
`Controller` class is the base class.
`A base class for an MVC controller with view support.`

**Comment by scottaddie** [comment]
@Rick-Anderson Yes, but it's confusing (at least to me and the author of the issue) to have a class named `ControllerBase` and text like "`Controller` base". The two are too easily confused.

**Comment by AdimUser** [comment]
@scottaddie  Thanks for understanding end user perspectively.  Beginners can easily get confused.
Like me :) 💯 👍 🥇 
@Rick-Anderson  : Thank you

**Comment by scottaddie** [comment]
@AdimUser Thank you for bringing it to our attention.
