### ISSUE TITLE
Part of the code block is hidden 

### ISSUE THREAD

**Issue by biju-ps** [aspnet/AspNetCore.Docs#13153]
part of the code block is hidden for the below link 
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2

Please have a look at the attached screenshot
![image](https://user-images.githubusercontent.com/2868701/60756316-b56da880-a019-11e9-9a91-9934847c0e8e.png)

**Comment by Rick-Anderson** [comment]
dup of #13143
