### ISSUE TITLE
Code not rendered correctly 

### ISSUE THREAD

**Issue by MythreyaK** [aspnet/AspNetCore.Docs#13154]
Some code in the section [Registering Database Context](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#register-the-database-context) is highlighted but doesn't show up, as shown below. 

![image](https://user-images.githubusercontent.com/26112391/60756385-4a70a180-a01a-11e9-885c-f46923a94c83.png)

I could try a pull request, but wasn't sure of the error in the Markdown. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
dup of #13143
