### ISSUE TITLE
Sample code partially invisible in Google Chrome

### ISSUE THREAD

**Issue by Pethical** [aspnet/AspNetCore.Docs#13159]
Some code is invisible in Google Chrome, because the .line-highlight div is covering it.

![image](https://user-images.githubusercontent.com/10383468/60759584-da691800-a027-11e9-8a28-5ca77a493ada.png)
![image](https://user-images.githubusercontent.com/10383468/60759591-fa004080-a027-11e9-8ac4-fe0344951b34.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is a system wide problem. that's tracked in #13143
