### ISSUE TITLE
Unreadable examples due to syntax highlightning?

### ISSUE THREAD

**Issue by tabrath** [aspnet/AspNetCore.Docs#13158]
![image](https://user-images.githubusercontent.com/568083/60759366-7729b680-a024-11e9-930c-ef9371817910.png)

The text is there as it works by copying, but as seen in the screenshot, it's unreadable as the text and background color is the same. This is the dark theme, but it's the same for light mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f06ca2b-9d96-9979-46a8-d09900af0653
* Version Independent ID: 0f0d321d-46ed-25cb-6bb4-e4611343b131
* Content: [SignalR API design considerations](https://docs.microsoft.com/en-us/aspnet/core/signalr/api-design?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/signalr/api-design.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/api-design.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @anurse
* Microsoft Alias: **anurse**

**Comment by guardrex** [comment]
Hi @tabrath ... It's a known issue. We have an internal issue open with the doc engineers to address it.
