### ISSUE TITLE
Content of highlighted code not showing

### ISSUE THREAD

**Issue by paul000** [aspnet/AspNetCore.Docs#13168]
For some reason, anytime the tutorial shows highlighted code (code inside the yellow boxes), most of the content does not appear. On this page the highlighted code in the sample 
"public void ConfigureServices(IServiceCollection services)", only the word "SchoolContext" is showing, no other code in the highlighted yellow box. Every subsequent tutorial page has the same problem. 

At first I thought it was a monitor setting, but I am using 3 monitors, all having the same issue. I'm using Edge so I tried in Chrome and Firefox and had the same problem. I booted another desktop with a separate monitor, same problem. I even went to the page on my smart phone and had the same problem. I changed versions from 2.2 to 2.1, no luck.

I've been using this tutorial for a couple of years and never had this problem, is there a website issue or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio#set-up-the-site-style)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is a system wide problem. that's tracked in #13143

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in #13143

**Comment by paul000** [comment]
Thanks!

Paul
