### ISSUE TITLE
Shouldn't ResourceType property be mentioned as a localization option?

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore.Docs#13162]
Old way of localizing data annotations is with `ResourceType`-like properties.
This approach may be useful when models reside in separate class library. Shouldn't this option be mentioned in `DataAnnatations localization` section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#dataannotations-localization)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco  please comment.

**Comment by hishamco** [comment]
AFAIK there's `ResourceLocationAttribute` but I'm not sure if it is used in data annotations, so let me check

Meanwhile you can check the docs https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#dataannotations-localization

**Comment by hishamco** [comment]
I quote from ASP.NET Core team https://github.com/aspnet/AspNetCore/issues/4870#issuecomment-382831955

> but we don't generally recommend `ResourceTypes` anymore

**Comment by hishamco** [comment]
@voroninp hope that answered your question

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
