### ISSUE TITLE
Some code is not displayed in code samples

### ISSUE THREAD

**Issue by dmitry-pavlov** [aspnet/AspNetCore.Docs#13164]
The code sample blocks on this page do not display part of the code. Instead of that I see yellow areas, where only primitive type values, some keywords are rendered, but no methods and variables. Looks like a rendering issue for code blocks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by dmitry-pavlov** [comment]
![13164](https://user-images.githubusercontent.com/1560778/60768627-dd6b1380-a0ce-11e9-92af-718be729a378.png)

**Comment by guardrex** [comment]
We have an internal issue open to address the problem. https://github.com/aspnet/AspNetCore.Docs/issues/13143

**Comment by dmitry-pavlov** [comment]
Ok, great!
