### ISSUE TITLE
Highlighted code is inconsistent with sample code on GitHub

### ISSUE THREAD

**Issue by shoko93** [aspnet/AspNetCore.Docs#13161]
I think code for database connection string and Startup.ConfigureServices for visual studio code section is incorrect . I understand I can look at the sample code on GitHub, but I think it is much easier to follow the tutorial if the code on tutorial page is updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We have an internal issue open to address the problem. https://github.com/aspnet/AspNetCore.Docs/issues/13143
