### ISSUE TITLE
CSS / Code View

### ISSUE THREAD

**Issue by jrzabott** [aspnet/AspNetCore.Docs#13160]
Please, check the CSS for marked code. There is something wrong and very disturbing for tutorial seekers.  Of course, with a little mind stretch you can find things, however not always straight forward.

See the image here: https://i.imgur.com/JHyzWOD.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jrzabott** [comment]
just saw the dup report, sorry

**Comment by Rick-Anderson** [comment]
No problem. Sorry for this mess.
This is a system wide problem. that's tracked in #13143
