### ISSUE TITLE
Code Examples displaying incorrectly

### ISSUE THREAD

**Issue by CoenraadS** [aspnet/AspNetCore.Docs#13167]
Code examples (in yellow) are broken and half of the text does not get displayed.

![image](https://user-images.githubusercontent.com/5593825/60772169-c3dbc300-a0f2-11e9-9004-8b5f7d45bd53.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address it. #13143
