### ISSUE TITLE
Some code is unreadable in the dark mode

### ISSUE THREAD

**Issue by roa-nyx** [aspnet/AspNetCore.Docs#13177]
# Issue description

Code is sometimes unreadable, see screenshot:

![image](https://user-images.githubusercontent.com/8572438/60795353-864e5880-a139-11e9-8fcf-736db2927f07.png)

Above screenshot is from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2 but I imagine that it is similar on other pages

# Software versions

Chrome (latest), Windows 10 Pro

**Comment by daihongbin** [comment]
Not just the dark mode, all the theme modes can't read the code. You can't see the code on both the iPad and the phone, and this problem usually occurs in the section that highlights the code.

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143

**Comment by daihongbin** [comment]
> Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143

The problem has been solved, thank you
