### ISSUE TITLE
Q: Using Newtonsoft.Json with Endpoint routing

### ISSUE THREAD

**Issue by shatl** [aspnet/AspNetCore.Docs#13171]
In https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#jsonnet-support
Samples cover only case when `services.AddMvc()` is used. However new MVC and WebAPi templates based on Endpoint Routing does not use AddMvc. 

`AddNewtonsoftJson` internally calls `AddServicesCore()` but is is internal method.

How to add Newtonsoft.Json in this case? Please add an example or make `AddServicesCore` public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by JamesNK** [comment]
> However new MVC and WebAPi templates based on Endpoint Routing does not use AddMvc.

Are you referring to them using AddControllers/AddRazorPages? They return the same builder as AddMvc:

```cs
services.AddControllers().AddNewtonsoftJson();
```

**Comment by shatl** [comment]
Thanks a lot @JamesNK !
