### ISSUE TITLE
Page layout is broken

### ISSUE THREAD

**Issue by Paxxi** [aspnet/AspNetCore.Docs#13174]
The sample code displays green blocks where I assume the relevant parts of the example should be.
I've tested this in safari iOS 12.3.1 and latest ms edge canary on windows 10 with identical results

![A4BA0894-5F04-42A1-9F9D-46004AE45DC8](https://user-images.githubusercontent.com/874927/60785676-126d7980-a154-11e9-8694-a0744920926b.jpeg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address it. #13143
