### ISSUE TITLE
Partial green (added) code text is not appearing

### ISSUE THREAD

**Issue by wooden-utensil** [aspnet/AspNetCore.Docs#13178]
Hi. Some of the green (added) code text isn't appearing.

When I look at it, some parts are missing:

![Missing parts of code](https://user-images.githubusercontent.com/48314599/60808978-e2ae8800-a1cc-11e9-8d90-e0acbe963cb7.PNG)

But when I copy and paste it, those missing lines appear:

```services.AddMvc()
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
    .ConfigureApiBehaviorOptions(options =>
    {
        options.SuppressConsumesConstraintForFormFileParameters = true;
        options.SuppressInferBindingSourcesForParameters = true;
        options.SuppressModelStateInvalidFilter = true;
        options.SuppressMapClientErrors = true;
        options.SuppressUseValidationProblemDetailsForInvalidModelStateResponses = true;
        options.ClientErrorMapping[404].Link =
            "https://httpstatuses.com/404";
    });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143
