### ISSUE TITLE
Instructions to enable client-side validation

### ISSUE THREAD

**Issue by codenjs** [aspnet/AspNetCore.Docs#13172]
This article could be improved if it showed how to enable client-side validation. It mentions the _ValidationScriptsPartial view a couple times, but doesn't actually show how to use it. I couldn't get the client-side validation to work until I did some additional web searching to find examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#client-side-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
client side validation is enabled by default.

**Comment by codenjs** [comment]
I'm not sure about your workflow, so I don't know what "enabled by default" means in your comment. I created views using the "Add MVC View" dialog in Visual Studio Community 2017. Right-click in Solution Explorer > Add > View

The "Reference script libraries" option is not always checked. When the option is unchecked, the view is created without any reference to the _ValidationScriptsPartial view, which means client-side validation is not enabled. This article would be more helpful if it showed how to enable it.
