### ISSUE TITLE
Possible bug with documentation/VS2019 preview

### ISSUE THREAD

**Issue by Kool-Koder** [aspnet/AspNetCore.Docs#13188]
Hi, this is the section being affected. In Visual Studio 2017, the documentation works fine, however in VS 2019 Preview 3, the option "MVC controller with views, using Entity Framework." does not appear at all. Not sure if this is a bug or a missing documentation. Thank you.

https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#create-controller-and-views

VS 2017
![Github](https://user-images.githubusercontent.com/39305371/60824026-75562380-a1db-11e9-94f4-68990b696206.png)

VS 2019
![Github 2](https://user-images.githubusercontent.com/39305371/60824028-76875080-a1db-11e9-8ec3-21a3d0996bcc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Install the latest SDK and VS 19

**Comment by Kool-Koder** [comment]
I just installed the latest version of VS 19 and the SDK is the latest version as well. I still don't see this option "MVC controller with views, using Entity Framework" when trying to scaffold.

**Comment by Rick-Anderson** [comment]
Try the command line. You may need to reinstall.

**Comment by Kool-Koder** [comment]
Just reinstalled the SDK as well. Option is still unavailable.

**Comment by Rick-Anderson** [comment]
Use the Visual Studio feedback menu item to leave feedback.  Help >  Send Feedback
