### ISSUE TITLE
CSS background-color is hiding code snippets

### ISSUE THREAD

**Issue by KeeganFargher** [aspnet/AspNetCore.Docs#13180]
#### When trying to view code snippets it is being hidden by a css class called `.line-highlight`.

With the background color visible:

![wrong](https://user-images.githubusercontent.com/28064609/60813437-0b665b80-a194-11e9-84dd-c9890ba32869.png)

With the background color hidden:

![correct](https://user-images.githubusercontent.com/28064609/60813538-449ecb80-a194-11e9-913e-09e1dfc2e9e4.png)

#### Tested with:

- Microsoft Edge 42.17134.1.0
- Google Chrome Version 76.0.3809.46

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143
