### ISSUE TITLE
Configure SignalR section has missed code

### ISSUE THREAD

**Issue by StasBalia** [aspnet/AspNetCore.Docs#13184]
In Configure SignalR section I can only view underlined lines without any code. I mean I can see only yellowed lines in using statement and inside ConfigureServices and Configure methods, looks like code has same color as underlined strings.
[https://ibb.co/10cWnVY](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143

**Comment by jhensley707** [comment]
@guardrex Although Rick-Anderson claimed this was fixed in https://github.com/aspnet/AspNetCore.Docs/issues/13143 and it appears correctly when then Version is ASP.NET Core 3.0, it is still broken in ASP.NET Core 2.2.

**Comment by jhensley707** [comment]
Nevermind. Flipping back and forth between the versions caused the missing highlighted text to finally show up. Definitely different from the 3.0 version so I'm glad it appeared.
