### ISSUE TITLE
Scripts Look Very Strange

### ISSUE THREAD

**Issue by asapostolov** [aspnet/AspNetCore.Docs#13183]
It looks like the scripts view is a bit broken. Everything that is in yellow does not make much sense.

![image](https://user-images.githubusercontent.com/1162471/60820157-88e89680-a1a9-11e9-9ce8-3c2229496616.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in https://github.com/aspnet/AspNetCore.Docs/issues/13143.
