### ISSUE TITLE
Add coverage of Azure App Configuration provider

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#13182]
See 
* https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app
* https://devblogs.microsoft.com/aspnet/configuring-a-server-side-blazor-app-with-azure-app-configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?tabs=basicconfiguration&view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We have it here :point_right: https://docs.microsoft.com/aspnet/core/security/key-vault-configuration

... and listed in the [Providers section of the Configuration topic](https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#providers).

**Comment by tdykstra** [comment]
@guardrex I don't see it in the list of providers.  This is not Key Vault.
