### ISSUE TITLE
Code showing error

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#13186]
@MyOnAsSalat commented on [Sat Jul 06 2019](https://github.com/aspnet/AspNetCore.Docs.ru-ru/issues/50)

Code in code block are covered by yellow lines, it make some lines of code on this page invisible.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Внедрение зависимостей в представления в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/mvc/views/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hi team, 
this issue is present in several of the code boxes
![imagen](https://user-images.githubusercontent.com/26746247/60821542-1ca26e80-a17a-11e9-8ce0-e6ffeffef253.png)

**Comment by guardrex** [comment]
Hey @CeciAc ... There's an internal issue open with the docs engineers to address it. #13143
