### ISSUE TITLE
Code Highlighting Broken

### ISSUE THREAD

**Issue by kylejrp** [aspnet/AspNetCore.Docs#13191]
The green background of highlighted code fails to show the white text. I've tried a few different pages, but the issue is only appearing on this page. The issue appears on both the light and dark theme.

I'm using Google Chrome 75.0.3770.90. The issue still persists in a new incognito window. It's also appearing in Firefox 67.0.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by kylejrp** [comment]
![image](https://user-images.githubusercontent.com/6742479/60829652-39cf4100-a16a-11e9-94cc-7144645ed9d0.png)

Text with syntax highlighting appears, but the normal white text does not.

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143
