### ISSUE TITLE
Issue when "Register the database context" section

### ISSUE THREAD

**Issue by raydlevel5** [aspnet/AspNetCore.Docs#13196]
Discovered while manually typing code (I'm not copy + pasting).

Location:  The picture under the instructions "Update Startup.cs with the following highlighted code:"

Problem:  The highlighted sections are not opaque, and the text underneath is hidden.  Essentially, you can't see what's under the highlight.  You have to copy and paste to see the code.  I'm trying to type it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi ... We have an open issue with the docs engineers to address the broken code blocks. #13143
