### ISSUE TITLE
RequireConfirmedAccount",vs "RequireConfirmedEmail"

### ISSUE THREAD

**Issue by danobri** [aspnet/AspNetCore.Docs#13206]
It appears there is a new configuration setting in 3.0 called "RequiredConfirmedAccount" that is replacing "RequireConfirmedEmail".  Is that correct?  When I scaffold the Register page, that is the property it checks before deciding whether to login a user upon registration.  Oddly, I don't find a reference to "RequireConfirmedAccount" anywhere in the ASP.NET Core 3.0 documentation, and "RequireConfirmedEmail" is still a valid setting (not marked as obsolete).  Unless I am missing something, I believe the 3.0 version of this doc needs to be updated to use the new property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'll be working on this next week. Follow #12990 to get your questions answered.

**Comment by flatproject** [comment]
I don't think #12990 answers the question. Is there maybe a different place where the question is answered? I can't understand or find any relevant documentation on what is the purpose of "RequireConfirmedAccount", how it is used and how it differs from "RequireConfirmedEmail"

**Comment by HaoK** [comment]
RequireConfirmedAccount is a new higher level option that if set will use the IUserConfirmation service https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/IUserConfirmation.cs to determine if a user is confirmed and hence allowed to logged in.  The default implementation of this, just uses RequireConfirmedEmail, but the idea is this is the new extensibility point for developers to whether a user is considered confirmed and able to log in.

**Comment by willemserruys** [comment]
When I set RequireConfirmedAccount to True, no mail is being sent if I'm authenticating via an external login provider. When it is set to False, a confirmation mail is being sent, but I can already sign in without confirming. Could this be a bug or am I missing something?

**Comment by DoyleJOfTexas** [comment]
It would be helpful if this page mentioned the need to remove the code block identified by the comment in RegisterConfirmation.cshtml.cs after the email sender is operational or did I miss that.

**Comment by gp2-gp2** [comment]
> When I set RequireConfirmedAccount to True, no mail is being sent if I'm authenticating via an external login provider. When it is set to False, a confirmation mail is being sent, but I can already sign in without confirming. Could this be a bug or am I missing something?

Is there any solution available for this issue?

**Comment by zoran-petrovic-87** [comment]
@gp2-gp2 
> When I set RequireConfirmedAccount to True, no mail is being sent if I'm authenticating via an external login provider. When it is set to False, a confirmation mail is being sent, but I can already sign in without confirming. Could this be a bug or am I missing something?
> 
> Is there any solution available for this issue?

I had the same issue. It looks like you must add role in order to make it work:
`.AddRoles<IdentityRole>()`

For example:
```
services.AddDefaultIdentity<IdentityUser>(
	options => {
		options.SignIn.RequireConfirmedAccount = false;
		options.SignIn.RequireConfirmedEmail = true; 
	})
	.AddRoles<IdentityRole>()
	.AddEntityFrameworkStores<ApplicationDbContext>();
```

**Comment by TecVector** [comment]
Found the solution on StackOverflow for me:  I needed to change RequireConfirmedAccount to false, but then set RequireConfirmedEmail to true.  Here's the code fix, and a link to the SO article:

services.AddDefaultIdentity<IdentityUser>(options => 
        {
            options.SignIn.RequireConfirmedAccount = false;
            options.SignIn.RequireConfirmedEmail = true;
        })
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();

https://stackoverflow.com/questions/58824729/problems-with-using-external-login-and-sending-confirmation-mail-in-asp-net-core

**Comment by HaoK** [comment]
Yeah there's a bug in the flow here, the product bug will be tracked via https://github.com/aspnet/AspNetCore/issues/18140
