### ISSUE TITLE
http://contoso.com/api/pets/2?DogsOnly=true  cannot linkaction GetbyID()!!

### ISSUE THREAD

**Issue by lichasu** [aspnet/AspNetCore.Docs#13207]
@tahen2 commented on [Mon Jul 08 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/140)

在文章开头第一个例子中，http://contoso.com/api/pets/2?DogsOnly=true   这个路由无法查找 GetByID 的第一个参数，该参数是一个名为 id 的整数。至少路由的动作方法时pets怎么会查找getbyid方法呢？是不是有错误？
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的模型绑定](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by lichasu** [comment]
Hi team, please check this issue created by the user. Rough translation:

> In the first example at the beginning of the article, http://contoso.com/api/pets/2?DogsOnly=true This route cannot find the first argument to GetByID, which is an integer named id. How does pets look for getbyid methods when at least routing action methods? Is there an error?

**Comment by tdykstra** [comment]
The `id` is in the route as `{id}` and in the URL following `pets` as `/2`

**Comment by Rick-Anderson** [comment]
Recommend you close this issue.
