### ISSUE TITLE
Package: "Microsoft.Extensions.Http.Polly"

### ISSUE THREAD

**Issue by seanalford** [aspnet/AspNetCore.Docs#13208]
It would be nice if all docs included the required package at the top. i.e. "Microsoft.Extensions.Http.Polly"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Covered in the topic here :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0#use-polly-based-handlers

**Comment by Rick-Anderson** [comment]
Per the doc:
Can be used after installing the Microsoft.Extensions.Http.Polly NuGet package. The package isn't included in the ASP.NET Core shared framework.
