### ISSUE TITLE
[Preview 8] Update documentation to reflect new Blazor template names

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore.Docs#13200]
**Issue description**
The following docs need to be updated to reflect [the rename of the Blazor templates](https://github.com/aspnet/AspNetCore/pull/11550).

- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/client-side?view=aspnetcore-3.0
- https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0
- https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio
- https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio

**Comment by isaac2004** [comment]
I can probably do this one, since I did the work on the other side.

**Comment by guardrex** [comment]
@isaac2004 If engineering approves your working the issue, shoot them into the `3.0-preview7` branch (not `master`).

**Comment by isaac2004** [comment]
@guardrex this got merged, we good to start?

**Comment by guardrex** [comment]
@isaac2004 Can you point me to the engineering issue? Ryan marked this for Pre8.

**Comment by isaac2004** [comment]
Here it is, with linked PR

https://github.com/aspnet/AspNetCore/issues/10348

**Comment by guardrex** [comment]
Thanks.

@danroth27 The engineering PR merged to master, but the label on the engineering issue (and here on the docs issue) is set to Preview 8. Which release should take these doc updates, and is @isaac2004 :+1: to do the work once the timing is determined?

**Comment by danroth27** [comment]
These template changes are shipping with .NET Core 3.0 Preview 8.

@isaac2004 if you want to help out with contributing the doc updates, that's fine. It's also fine to have @guardrex take care of this if you'd rather focus on something else.

**Comment by guardrex** [comment]
@isaac2004 If you want to proceed, hold off for a bit. We'll create a `release/3.0.0-preview8` branch later. I'll ping u back here when the branch is up and ready to receive PRs.

**Comment by guardrex** [comment]
@isaac2004 Do you still want to proceed with this? If so, create a new branch from `release/3.0-preview8` and then submit the work back to that same branch. If not, no worries. I'll take care of this issue.

**Comment by isaac2004** [comment]
@guardrex I can take this. Will have @danroth27 review

**Comment by guardrex** [comment]
Resolved by #13536
