### ISSUE TITLE
Auto

### ISSUE THREAD

**Issue by Infraton11** [aspnet/AspNetCore.Docs#13214]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

- Explain why this topic is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

**Comment by scottaddie** [comment]
Closing, as there's nothing actionable provided in this issue.
