### ISSUE TITLE
Messed up string interpolation

### ISSUE THREAD

**Issue by Joelius300** [aspnet/AspNetCore.Docs#13218]
In the part [Customize WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#customize-webapplicationfactory) there is the following code snippet.  

```
logger.LogError(ex, $"An error occurred seeding the " +
     "database with test messages. Error: {ex.Message}");
```
Notice that the first string has the $ sign but the second doesn't and the second is the only one that uses the string interpolation. I think this should be:
```
logger.LogError(ex, "An error occurred seeding the " +
    $"database with test messages. Error: {ex.Message}");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Joelius300 ... due to a recent update to shorten the line. I'll patch it shortly.
