### ISSUE TITLE
Dictionary<string,string> or Dictionary<int,string>

### ISSUE THREAD

**Issue by cysun** [aspnet/AspNetCore.Docs#13211]
In the Dictionary example, it says "Suppose the target parameter is a Dictionary&lt;string, string&gt; named selectedCourses", and then the C# code shows a "Dictionary&lt;int, string&gt; selectedCourses".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2#dictionaries)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@cysun  thanks for bringing this to our attention
