### ISSUE TITLE
the preceding example，the Dictionary's Type isnot same.  the Dictionary<int ,string>should be wrong,should the same with the first Line.

### ISSUE THREAD

**Issue by lichasu** [aspnet/AspNetCore.Docs#13229]
@tahen2 commented on [Tue Jul 09 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/142)

假设目标参数是名为 selectedCourses 的 Dictionary<string, string>：
C#
public IActionResult OnPost(int? id, Dictionary<int, string> selectedCourses)

the preceding example，the Dictionary's Type isnot same.  the Dictionary<int ,string>should be wrong,should the same with the first Line.

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的模型绑定](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by lichasu** [comment]
Hi Team, please check the issue above.

Thanks!

**Comment by Rick-Anderson** [comment]
This has been fixed.
