### ISSUE TITLE
doc redirects to fontawesome.com

### ISSUE THREAD

**Issue by jaoord** [aspnet/AspNetCore.Docs#13221]
# Issue description

[This](https://stackoverflow.com/a/48097019/106866) StackOverflow answer links to the following doc: https://docs.microsoft.com/en-us/aspnet/core/client-side/less-sass-fa. However, following that link results in a redirect to https://fontawesome.com/

**Comment by scottaddie** [comment]
@jaoord This is the intended behavior. The team made a decision to retire that doc. It's not our product, and there are better docs available elsewhere on that same topic.

**Comment by jaoord** [comment]
Isn't that confusing? Because there seems to be a default 404 page for the docs site: https://docs.microsoft.com/en-us/aspnet/core/client-side/less-sass
