### ISSUE TITLE
Javascript Services Endpoint Routing in .NET core 3

### ISSUE THREAD

**Issue by oguduvictor** [aspnet/AspNetCore.Docs#13226]
How do i use endpoint routing with Javascript Services.

At the moment the docs gives this example:
```
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");

    routes.MapSpaFallbackRoute(
        name: "spa-fallback",
        defaults: new { controller = "Home", action = "Index" });
});
```

Meanwhile .NET core 3 uses
`app.UseEndpointRouting(options => ....)`

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
