### ISSUE TITLE
Update to 3.1 Facebook, Google, and external provider authentication

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13234]
Facebook, Google, and external provider authentication
![image](https://user-images.githubusercontent.com/3605364/61007853-28816280-a32b-11e9-9377-35ed52deca9d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by datvm** [comment]
Can we have a brief mention on how to call the methods to enable Google/Facebook now? Thanks.

**Comment by Rick-Anderson** [comment]
Moved to #16210
