### ISSUE TITLE
Update to 3.0 FB auth

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13236]
FB
![image](https://user-images.githubusercontent.com/3605364/61009321-89ab3500-a32f-11e9-96c0-06915fda32c4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Related to now closed https://github.com/dotnet/docs/issues/14959 .  Currently also changing code example to address this...

**Comment by wadepickett** [comment]
Fixed with PR #15838
