### ISSUE TITLE
3.0 update: Javascript Services middleware & Endpoint Routing for .NET core 3+

### ISSUE THREAD

**Issue by oguduvictor** [aspnet/AspNetCore.Docs#13245]
How is the Javascript Services middleware used in the new endpoint routing

At the moment the docs gives this example:
```
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");

    routes.MapSpaFallbackRoute(
        name: "spa-fallback",
        defaults: new { controller = "Home", action = "Index" });
});
```
Meanwhile .NET core 3 routing uses
`app.UseEndpointRouting(options => ...)`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/client-side/spa-services?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by ryanbrandenburg** [comment]
@SteveSandersonMS it's not clear to me that there's a way to get the same behavior as MapSpaFallbackRoute within `Spa.Services.Extensions` Am I maybe missing or not understanding something?

**Comment by Rick-Anderson** [comment]
Per doc:

> [!WARNING]
> The features described in this article are obsolete as of ASP.NET Core 3.0. A simpler SPA frameworks integration mechanism is available in the [Microsoft.AspNetCore.SpaServices.Extensions](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions) NuGet package. For more information, see [[Announcement] Obsoleting Microsoft.AspNetCore.SpaServices and Microsoft.AspNetCore.NodeServices](https://github.com/aspnet/AspNetCore/issues/12890).

**Comment by rjgotten** [comment]
@ryanbrandenburg 

You're not missing anything.
Either you have something that exactly fits the Microsoft-determined React or Angular mold, or your scenario is no longer supported and Microsoft is selling you what is essentially a PR-friendly wrapping around a brusque "it's been great, now fuck off."

The reason for it is laughable as well; citing a high cost of maintenance to keep the parts that interface with Node.js working. Interesting fact; most of the TypeScript files that form the Node.js gluecode haven't been touched in literal years, indicating that 'high cost' to have **actually** been near-zero for the last years.
