### ISSUE TITLE
Is it possible to use a simple flag with the Command-line Configuration Provider?

### ISSUE THREAD

**Issue by phil-harmoniq** [aspnet/AspNetCore.Docs#13247]
[Command-line Configuration Provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#command-line-configuration-provider) lets you map properties, but it's unclear if I can just have a true/false switch that can be triggered by just using that flag and not explicitly declaring a property as true. For example:

`cli-app --EnableSomething`

instead of

`cli-app --EnableSomething=true`

**Comment by guardrex** [comment]
Hello @phil-harmoniq ... They must be key-value pairs.

https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#arguments

**Comment by guardrex** [comment]
You could suggest that to the engineers/management. You can open an issue with them at :point_right: https://github.com/aspnet/AspNetCore/issues
