### ISSUE TITLE
SignalR tutorial with JavaScript is displaying content for the wrong version

### ISSUE THREAD

**Issue by Oxyrus** [aspnet/AspNetCore.Docs#13256]
Currently the page is displaying instructions for the usage of SignalR with ASP.NET Core 3.0, even though the version selected in the sidebar is ASP.NET Core 2.2.

![Imgur](https://i.imgur.com/25IFdvx.png)

![Imgur](https://i.imgur.com/fKmbzUV.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
cc @tdykstra - was this a recent change in which some new pictures slipped in?

**Comment by Rick-Anderson** [comment]
@Oxyrus @bradygaster  we'll get this fixed.
