### ISSUE TITLE
Extra NuGet packages and Postman alternative

### ISSUE THREAD

**Issue by p33t** [aspnet/AspNetCore.Docs#13267]
I found I needed these additional NuGet packages when editing Startup.cs:
Microsoft.EntityFrameworkCore.InMemory
Microsoft.AspNetCore.StaticFiles

Also, Postman didn't play nice with my corporate proxy.  Insomnia worked fine (and didn't require an account  setup).  Perhaps add a note about an alternative option would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Those packages come from the SDK, not NuGet. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app

Proxy shouldn't matter with localhost.
