### ISSUE TITLE
Wrong using: OpenApi

### ISSUE THREAD

**Issue by lichasu** [aspnet/AspNetCore.Docs#13266]
Hi team, please check this issue that was created in the it-it repo [here](https://github.com/aspnet/AspNetCore.Docs.it-it/issues/35):

@MarGraz
> Hi,
> 
> I'm trying to following this guide, but at this point: https://docs.microsoft.com/it-it/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware you suggest to add a reference to "OpenApi", but isn't possible, because "Swashbuckle" doesn't use "OpenApi".
> The correct using is: "Swashbuckle.AspNetCore.Swagger.Info".
> 
> Thank you,
> Marco

Thanks!

**Comment by Rick-Anderson** [comment]
Moved to #13273
