### ISSUE TITLE
ViewComponent

### ISSUE THREAD

**Issue by rcroeder** [aspnet/AspNetCore.Docs#13268]
Is there any plans to add ViewComponent as an options for Add New like class, view, controller,....

**Comment by guardrex** [comment]
Hello @rcroeder ... We only handle ASP.NET Core documentation on this repo. We can't take feedback for Visual Studio. Use the **Help** > **Send Feedback** > **Suggest a Feature** process in Visual Studio. That will send your feedback directly to that team.
