### ISSUE TITLE
"Swashbuckle" doesn't use "OpenApi".

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13273]
Original issue https://github.com/aspnet/AspNetCore.Docs.it-it/issues/35

Hi,

I'm trying to following this guide, but at this point: https://docs.microsoft.com/it-it/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware you suggest to add a reference to "OpenApi", but isn't possible, because "Swashbuckle" doesn't use "OpenApi".
The correct using is: "Swashbuckle.AspNetCore.Swagger.Info".

Thank you,
Marco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by fsadamw** [comment]
The latest stable version 4.0.1 did no work for me, so I needed to install via Package Manager Console to get the Prerelease version '5.0.0-rc2' which worked for me. I am using .net core 2.1.

**Comment by elizabethconnolly** [comment]
For .net core 2.2 here is what worked for me: 
- install pre-release 5.0.0-rc2 as specified above
- no using statement required
- syntax for c.SwaggerDoc : c.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo {

**Comment by Ben67366** [comment]
I had the same problem. But after use 5.0.0-rc2 it resloved.

![image](https://user-images.githubusercontent.com/25456777/62753841-3d772000-baa8-11e9-870b-e857fb3d5f5b.png)

**Comment by spboyer** [comment]
Version 2.2 of the docs and ASP.NET Core 2.2 and above reference `Swashbuckle.AspNetCore Version 5.0.0-rc2`. Closing as resolved.
