### ISSUE TITLE
Server created by VScode doesn't open in chrome due to HTTPs

### ISSUE THREAD

**Issue by ltlombardi** [aspnet/AspNetCore.Docs#13276]
when I type http://localhost:5000 it gets redirected to https://localhost:5001/ and it doesn't load giving this error:
```
This site can’t be reached The webpage at https://localhost:5001/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY
```

This tutorial should not let this happen. If open in old IE, the server loads.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by ltlombardi** [comment]
This happens in my Windows 8.1 single language, .NET core SDK 3.0.100-preview6-012264

Extension version: 1.20.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.3.9600

**Comment by ltlombardi** [comment]
Going to Startup.cs, and removing the bellow line, was a workaround.

app.UseHttpsRedirection();

**Comment by guardrex** [comment]
Hello @ltlombardi ... Check these related engineering issues to see if you can sort out what's happening.

https://github.com/aspnet/AspNetCore/search?q=ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY&type=Issues

If those don't clarify what's going on, open an issue for the engineers on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues). Provide them that version info that you just stated :point_up:. If you/they discover something that we do need to surface in the docs, ping me back over here.

**Comment by guardrex** [comment]
@ltlombardi I noted a **Tip** that calls that error out. See and try ...

https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio#run-the-app

... look at the 2nd bullet point in the **Tip** box of that section.

Let me know if that works.

**Comment by SaadZahoor70** [comment]
> Going to Startup.cs, and removing the bellow line, was a workaround.
> 
> app.UseHttpsRedirection();

Best Solution.
