### ISSUE TITLE
Subject index

### ISSUE THREAD

**Issue by KenyaLS** [aspnet/AspNetCore.Docs#13272]
> Предметный указатель — вспомпомогательный указатель, в заголовках рубрик которого названы предметы, сведения о них содержатся в тексте издания и могут быть потенциальным объектом поиска.

**Subject index** — an auxiliary index, in the headings of the headings of which the objects are named, information about them is contained in the text of the publication and can be a potential search object.
About(Keywords) - 

1. O - OpenApi  page in the book 26
2. @ - @page page in the book 26
3. @ - @model page in the book 56
4. @ - @Html.DisplayFor page in the book 56
5. @ - @RenderBody page in the book 57

And so like that

**Comment by KenyaLS** [comment]
the main words in the book it will be quicker to remember the command on the eye when you know the documentation

**Comment by KenyaLS** [comment]
About -
![image](https://user-images.githubusercontent.com/20774076/61162440-04d43d00-a522-11e9-9ed7-e1ca01ff5039.png)

**Comment by guardrex** [comment]
Hello @KenyaLS ... Good idea, but we can't process your feedback here. We just work on ASP.NET Core documentation issues on this repository.

Open an issue on the Microsoft.Docs repository at ...

https://github.com/MicrosoftDocs/feedback
