### ISSUE TITLE
Update Logging doc for 3.0 (Generic Host)

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#13278]
Update the doc to use Generic Host + any other 3.0 changes that affect it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
From @EdiWang (https://github.com/aspnet/AspNetCore.Docs/issues/13469) ...

```
public Startup(IConfiguration configuration, ILogger&lt;Startup&gt; logger)
```

> This code no longer works. Same issue as aspnet/Extensions#1096

> Per Andrew Stanton-Nurse's comment under that issue. aspnet/Extensions#1096 (comment)

> This document needs update.
