### ISSUE TITLE
Must remove .AddMVC if...

### ISSUE THREAD

**Issue by ghhv** [aspnet/AspNetCore.Docs#13289]
I spent a mind numbing day or more trying to resolve why an app I was migrating from 2.2 to 3.0 preview 5 kept failing with the error `Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: Identity.Application was not authenticated. Failure message: Unprotect ticket failed` message on startup. 
In Startup, I had updated as advised from above to add
` services.AddControllers();
  services.AddRazorPages();`
in place of 
` services.AddMvc();`
but I also had an IdentityHostingStartup in a previously scaffolded Identity which still had an extra `AddMvc()` as well. 
This combination causes that obscure error above for which no other available suggestions could fix. 
SO I guess the feedback is, if you use `AddControllers` and `AddRazorPages`,  ensure you have removed `AddMvc` as well. 
Maybe there should be another warning in case this 'conflict' occurs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by ghhv** [comment]
And if you're wondering why I had the extra `AddMvc()` it was to add this - I don't even know why anymore.. 
`.AddRazorPagesOptions(options =>
                     {
                         // options.AllowAreas = true; not working in Core 3
                         options.Conventions.AuthorizeAreaFolder("Identity", "/Account/Manage");
                         options.Conventions.AuthorizeAreaPage("Identity", "/Account/Logout");
                     });`

**Comment by ghhv** [comment]
Woops.. sorry. Maybe delete or close this feedback. Turns out the error is still happening but removing the AddMvc no longer creates an exception. Back to the drawing board.

**Comment by Rick-Anderson** [comment]
Take a look at https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0 and if that doesn't solve the problem let me know.
