### ISSUE TITLE
Missing instructions on how to setup development IIS express host with Visual Studio Code

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore.Docs#13280]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0

- [x] .NET Core 3.0
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @wrkettlitz ... btw -- Please use the **This Page** feedback button at the bottom of any topic. It helps us track work on the repo.

That's not a supported scenario for VSC. VSC uses [Omnisharp](https://github.com/OmniSharp/omnisharp-vscode) for debugging.

I think you probably can find some resources out around the Net (at your own risk in some cases). For example, you'll probably find some cats explaining how to [use IIS Express from the command line](https://docs.microsoft.com/en-us/iis/extensions/using-iis-express/running-iis-express-from-the-command-line) and then making that a task in VSC. There is also at least [one 3rd party extension that will do it](https://marketplace.visualstudio.com/items?itemName=warren-buckley.iis-express). You could try some kind of 🙉 **_HACK!_** 🙈 that might work (for example, [see this](https://github.com/OmniSharp/omnisharp-vscode/issues/2223#issuecomment-418039057)), *but I don't recommend it*. Outside of IIS Express from the CLI, these approaches **_are NOT supported by Microsoft!_** If while using an unsupported approach, your hard drive gets erased, you get a $500 speeding ticket, or your cat dies, *it's on you!* :smile: lol

Of course, I'm sure you know that publishing locally will allow you to use IIS locally. Unfortunately, our local dev with IIS scenario is VS-only at this time ... covered in [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/development-time-iis-support).

To request a scenario like that for VSC, open an issue with the Omnisharp folks at https://github.com/OmniSharp/omnisharp-vscode/issues. They might be open to mirroring the kind of scenario you see in that VSC extension in their feature set OOB.
