### ISSUE TITLE
Anchor element update

### ISSUE THREAD

**Issue by m-whe** [aspnet/AspNetCore.Docs#13281]
"Find the following anchor element in the Pages/Shared/_Layout.cshtml file.
&lt;a class="navbar-brand" asp-area="" asp-page="/Index"&gt;RazorPagesMovie&lt;/a&gt;"

should read
&lt;a asp-page="/Index" class="navbar-brand"&gt;RazorPagesMovie&lt;/a&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The templates generate `asp-area=""`

**Comment by drofnasb** [comment]
asp-area="" was not generated for me. I have the same <a asp-page="/Index" class="navbar-brand">RazorPagesMovie</a> as the above comment mentioned. Would I update that with <a asp-page="/Movies/Index" class="navbar-brand">Movie</a>?

**Comment by Rick-Anderson** [comment]
Update your SDK version.
