### ISSUE TITLE
Update to 3.0: Microsoft Account external login setup

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13299]
Microsoft Account external login setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ShinraCorpMixer** [comment]
Any update as to when it will be updated for .NET Core 3.0

**Comment by supersamamor** [comment]
Is it available on .NET Core 3.0?

**Comment by ShinraCorpMixer** [comment]
Got it to work on .NET Core 3.0, I just followed the Google authentication document but replace the method, with the Microsoft Account one (and also registering the app via Azure instead of Google of course.). So it should look something like this in the startup.cs class.

  services.AddAuthentication()
        .AddMicrosoftAccount(options =>
        {
            IConfigurationSection microsoftAuthNSection =
                Configuration.GetSection("Authentication:Microsoft");

            options.ClientId = microsoftAuthNSection["ClientId"];
            options.ClientSecret = microsoftAuthNSection["ClientSecret"];
        });

**Comment by wadepickett** [comment]
@ShinraCorpMixer, Sorry for the horrible delay, I had to complete other work as a priority before going on vacation.   I apologize for missing your question here.   Yes, the Google OAuth and Facebook OAuth topics I updated use the same code as for this situation.  Working on this topic now today.

**Comment by wadepickett** [comment]
@ShinraCorpMixer, fixed and closed with pr #15985 , thanks again for your feedback.
