### ISSUE TITLE
Document explaining how to use SignalR with Xamarin Forms

### ISSUE THREAD

**Issue by dinobu** [aspnet/AspNetCore.Docs#13292]
I would like to suggest to add a document like this one but to provide steps and instructions explaining how to add and use SignalR with Xamarin.Forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
There is a great doc on using the Azure SignalR Service with Xamarin [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr). Also, @scottaddie is working on a new mobile section in the SignalR docs, which will land sometime very soon. It will have a link to the Xamarin article above, as well as one on the Java client for building native Android applications and a mobile overview doc of the things you need to be aware of when building real-time apps for mobile devices and scenarios.

**Comment by bradygaster** [comment]
@dinobu - if this is a good collection of mobile-related and Xamarin-related articles, please close this issue. If not, please let us know how the existing article is lacking so we can improve upon it.

**Comment by dinobu** [comment]
> @dinobu - if this is a good collection of mobile-related and Xamarin-related articles, please close this issue. If not, please let us know how the existing article is lacking so we can improve upon it.

Looks like this is supported only on VS2019?  I dont have problem with that just asking if that is true and recommended?  Thanks for quick reply

**Comment by profexorgeek** [comment]
Hi @dinobu - I created the doc and sample that Brady linked above. We definitely _recommend_ using Visual Studio 2019 since it's the latest version. I created and tested the sample using Visual Studio 2019.

That being said, I did run some quick tests and it looks like everything should work in Visual Studio 2017 too. I tested building the UWP project, running the chat server locally, and made sure the "deploy to Azure" dialog functioned the same. The screenshots may vary slightly but you should be able to test in VS2017.

**Comment by dinobu** [comment]
Much appreciated @bradygaster @profexorgeek
