### ISSUE TITLE
@Code, @Key :  new 3.0 feature, add to Razor Syntax

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13301]
See [ASP.NET Core and Blazor updates in .NET Core 3.0 Preview 6](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#section-7)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  shouldn't `@code` be in this doc too?

**Comment by guardrex** [comment]
Yes ... indeed so if it didn't make it on those Pre6 updates.

IIRC I think that `@page` is under-represented (or not covered) here. IIRC, I couldn't cross-link it on a Blazor PR a little while ago, and it slipped off my radar with all the churn at the time.

**Comment by Rick-Anderson** [comment]
Per [https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/)

New Razor features: `@attribute, @code, @key, @namespace`, markup in `@functions`

All that needs to be covered in this doc.

**Comment by guardrex** [comment]
AFAIK, they're good on the Blazor side sans cross-links. I can open an issue for the cross-links or they can be worked with this. Problem with adding the cross-links to this work is that the staging branch is already going to be ripe for :boom: *merge conflicts* :boom: as it is. Loading more and more churn on it could lead to a doc author 😵 *schizoid embolism* 😵 followed by ⚰️ *funeral services ... RIP!* ⚰️.

Let me know if you want a separate issue for cross-links. I'll self-assign and work it after the staging branch merges to `master`.

**Comment by Rick-Anderson** [comment]
@guardrex I thought `@danroth27` said content that's common to both this Razor Syntax page and [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0) should be in this Razor Syntax page. The Razor Components doc can have links to sections in this doc.

Is the `@code, @key` the same here? Can we move it over here?

**Comment by guardrex** [comment]
> should be in this Razor Syntax page

> Can we move it over here?

These are more like passing mentions that pertain directly to Blazor. They aren't formally, fully covered in those instances.

**Comment by guardrex** [comment]
Might be best tho given the churn and 🏃 that this topic get full, formal coverage now but wait to address those Blazor cases (and cross-links) until after Pre7. I have a :boom: feel'in com'in on here trying to do too much too fast. However, let me know if you need me to do anything ... take any particular process over there.

At the moment, those Blazor topics could be addressed for this on my upcoming **_Preview 7 Sweep_**:tm:.

**Comment by Rick-Anderson** [comment]
@guardrex 
The new `@code` directive is used in  *.razor* files (not supported in *.cshtml* files)

**Comment by guardrex** [comment]
These updates are in review now on https://github.com/aspnet/AspNetCore.Docs/pull/13524.

Yes on the ❓ ... all directive attributes are for RC (.razor) only. That PR :point_up: has all the content on it for these updates.

Do you want me to put put a "fixes" line on the PR, or do you want to close this as a duplicate?

**Comment by guardrex** [comment]
Sorry about not signaling this sooner. I **_WAS_** going to only concentrate on the Blazor side of things over there, but I quickly found out that cross-links would be needed between the two topics and it made more sense to address everything at once on one PR.
