### ISSUE TITLE
Update to 3.0: Twitter auth

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13300]
Update to 3.0: Twitter auth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external sign-in setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Fixed with PR #16057
