### ISSUE TITLE
Order of code blocks

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13314]
From @llPRANAVll ...

"Review the contact operations requirements class"
should come before the other code in section
"Create owner, manager, and administrator authorization handlers"
So reader can understand where the Constants came from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by llPRANAVll** [comment]
correction:
looks like I provided wrong link last time
content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2)

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13320.
