### ISSUE TITLE
Order of code blocks

### ISSUE THREAD

**Issue by llPRANAVll** [aspnet/AspNetCore.Docs#13313]
"Review the contact operations requirements class"
should come before the other code in section
"Create owner, manager, and administrator authorization handlers"
So reader can understand where the Constants came from.
Content source : [https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2)

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13314.

Please use the **This Page** feedback form at the bottom of the topic. It adds the topic metadata to help us track the work.
