### ISSUE TITLE
Highlighted code missing

### ISSUE THREAD

**Issue by krhirst** [aspnet/AspNetCore.Docs#13317]
Some of the highlighted code is missing. I see there was an issue opened about this (#13143) that says it was fixed but there is still code missing on this page and almost all the other pages in this tutorial ([Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.2)) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @krhirst ... I don't see missing code here. Can you post a screenshot here for the topic author to see?

**Comment by krhirst** [comment]
The problem seems intermittent. 

[Change the title, footer, and menu link in the layout file](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio#change-the-title-footer-and-menu-link-in-the-layout-file)

![AddViewPageScreenshot](https://user-images.githubusercontent.com/44347950/61307737-7deac300-a7b4-11e9-981d-6d18b4cc193d.PNG)

The code appears after refreshing or zooming in/out:
![AddViewPageScreenshot2](https://user-images.githubusercontent.com/44347950/61307935-cefab700-a7b4-11e9-8c8d-7ce11c91a008.PNG)

I am using Microsoft Edge. I just checked the page using Chrome and it worked fine.

**Comment by guardrex** [comment]
Interesting ... cc: @scottaddie and @tdykstra to :eyes: this, too. This might be an Edge issue for the Edge team to investigate.

**Comment by Rick-Anderson** [comment]
@krhirst  I think the CSS caching is the problem.
