### ISSUE TITLE
Order of code blocks

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13320]
From @llPRANAVll ...

"Review the contact operations requirements class"
should come before the other code in section
"Create owner, manager, and administrator authorization handlers"
So reader can understand where the Constants came from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is not a beginning tutorial. Not every step is layed out.
