### ISSUE TITLE
Startup update to 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13337]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@tdykstra  can you outline what needs to be done?

**Comment by guardrex** [comment]
I can tell ya ... I looked yesterday ...

* Coverage for Generic Host >=3.0
* `IHostingEnvironment` to `IHostEnvironment`
* Template changes (`Configure` method; in particular, drop HTTPS bits).

Fortunately, this is one where there are just snapshots and no sample app.

This one where I only took it because I worked on it for 2.2. @wadepickett, you can hit me up if you need more info.

**Comment by Rick-Anderson** [comment]
Fixed in #13606
