### ISSUE TITLE
MVC Test Controller Logic update to 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13343]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ParthiKarnan** [comment]
Is there any specific documentation available for an ASP.NET Core Web API Test controller logic?

**Comment by guardrex** [comment]
@ParthiKarnan No, there isn't at this time. Readers have asked for coverage for web API in integration testing on https://github.com/aspnet/AspNetCore.Docs/issues/11283 but not for unit testing. This issue doesn't cover the request. This one is just to update the topic+sample for 3.0.

You can open a new issue for this topic asking for more or new coverage for web API controller testing, and I'll mark it for the product unit to take a look and consider the request. If you want to open an issue, use the **This Page** feedback button at the bottom of https://docs.microsoft.com/aspnet/core/mvc/controllers/testing.

**Comment by ParthiKarnan** [comment]
Thanks for your response and I have raised a ticket in github regarding my question. Kindly find the below link. 
https://github.com/aspnet/AspNetCore.Docs/issues/13575

**Comment by guardrex** [comment]
@Gosha24 reported on https://github.com/aspnet/AspNetCore.Docs/issues/14253 ...

I downloaded and run sample AspNetCore.Docs\aspnetcore\mvc\controllers\testing\samples\2.x\TestingControllersSample
I got exception

```
An error occurred while starting the application.
InvalidOperationException: Cannot resolve scoped service 'TestingControllersSample.Core.Interfaces.IBrainstormSessionRepository' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)

InvalidOperationException: Cannot resolve scoped service 'TestingControllersSample.Core.Interfaces.IBrainstormSessionRepository' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService(IServiceProvider provider)
TestingControllersSample.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
var repository = app.ApplicationServices.GetService();
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
