### ISSUE TITLE
Health Checks update to 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13340]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@rynowak WRT health checks composition for 3.0 ...

Switch to `UseEndpoints` and drop `UseHealthChecks`? If keeping both, which one configures the options? Both of the following seem valid (in terms of IntelliSense not freak'in out about the code). Seems redundant to specify the path twice.

```csharp
app.UseHealthChecks("/health", new HealthCheckOptions()
{
    ResponseWriter = WriteResponse
});

app.UseEndpoints(endpoints =>
{
    endpoints.MapHealthChecks("/health", new HealthCheckOptions()
    {
        ResponseWriter = WriteResponse
    });
});
```

What about setting the port? ... I can't set the port with `MapHealthChecks`, so it seems like I have to use `UseHealthChecks` ...

```csharp
app.UseHealthChecks("/health", port: Configuration["ManagementPort"]);

app.UseEndpoints(endpoints =>
{
    endpoints.MapHealthChecks("/health");
});
```

**Comment by rynowak** [comment]
> Switch to UseEndpoints and drop UseHealthChecks?

We'd show `UseEndpoints` + `MapHealthChecks` as the hero sample. However the old style is not wrong.

> If keeping both, which one configures the options? 

We should discourage showing both. If you do both then they are separate, but there's no reason to mix styles. In your example where they use the same path, the router will never run because the request won't reach it (handled by the health checks middleware).

> What about setting the port? ... I can't set the port with MapHealthChecks

You can with `MapHealthChecks("/health").RequireHost("*:5000")`

Routing has a **much** more powerful set of things to apply here. You can also do things like specify auth policies.

**Comment by guardrex** [comment]
> the request won't reach it (handled by the health checks middleware).

I see. Makes sense.

> You can with MapHealthChecks("/health").RequireHost("*:5000")

Gotcha. Thx.

I think I can get the PR done now. I'll ping u on the PR, but there's no giant rush on review given that it's for 3.0.

**Comment by rynowak** [comment]
Thanks @guardrex !
