### ISSUE TITLE
3.0 update:  Format response data in ASP.NET Core Web API

### ISSUE THREAD

**Issue by filipbekic01** [aspnet/AspNetCore.Docs#13359]
Web API do not extend Controller, it extends ControllerBase class. Therefore, methods like Json() and other are not available but still you're using it in documentation (it's confusing for newbies). I see you have "NOTE" at the top but still, page is incorrect for Controller class. Maybe keep Controller only methods here and still have link to "Web apps" for ControllerBase oriented methods. Keep it simple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by filipbekic01** [comment]
I see many people complain about same thing, that's a sign you should do something about it.

**Comment by ardalis** [comment]
When written the sample's controllers did just inherit from `Controller`, not `ControllerBase`. It might be worth revisiting that in light of current recommendations for API controllers.

**Comment by ruaanviljoen** [comment]
Yes super confusing. Direct contradiction to https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2 (https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md) and the example referenced also contradicts the recommendation and shows no valid way to return values with the new recommendation (https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting/sample/Controllers/Api/AuthorsController.cs). I'm guessing one of the status code name matching return helpers such as Ok,NotFound should be used.

**Comment by Rick-Anderson** [comment]
Fixed in #12077
