### ISSUE TITLE
Try this tutorial and it doesn't work - needs update to access token Auth URL

### ISSUE THREAD

**Issue by madtownchris** [aspnet/AspNetCore.Docs#13363]
Same general comments as others: you need to keep pages like this maintained otherwise people spend hours trying to understand this stuff. In any case, the Auth URL format you describe here seems to be the wrong format - could not get it tow work. After screwing around and then trying Fiddler, I tried this and it works:

https://{tenant name}.b2clogin.com/{tenant domain name}/{name of sign-up / sign-in workflow}/oauth2/v2.0/authorize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by daveduvarney** [comment]
Thanks for posting.

**Comment by fabio770** [comment]
Thank you.

**Comment by Rick-Anderson** [comment]
Moved to #16186
