### ISSUE TITLE
Tip for "asp-all-route-data"

### ISSUE THREAD

**Issue by contact4manoj** [aspnet/AspNetCore.Docs#13365]
Tip: 

Adopt the approach offered by the `Microsoft.AspNetCore.Mvc.TagHelpers` for route parameters.

Instead of using the `asp-all-route-data`, where the parameters have to be defined as a dictionary and initialized before hand, before using the same as part of the `<a>` anchor tag, it is more effective to adopt the `asp-route-<paramName>=<paramValue>` approach.

For example, for the above shown CSHTML code, we could write it as:

```<a asp-route="speakerevalscurrent"
   asp-route-speakerId="11"
   asp-route-currentYear="true">Speaker Evaluations</a>
```

Advantage:
In a Listing page, for example, we would be iterating using the "item" member of the Model in the foreach loop.  Accessing the ID parameter, for example of the "item" would become cumbersome, as the initialization of the dictionary would have to be achieved inside the foreach loop to adopt the approach as shown in the asp-all-route-data example above.  

Adopting the refined approach would look like:
```
<a asp-action="Details" 
   asp-controller="Manage" 
   asp-area="Admin" 
   asp-route-id="@item.ID" 
   asp-route-param2="@item.CategoryName">
   	View Details
</a>
```

The preceding code will generate the following HTML:
```
<a href="/Admin/Manage/Details?ID=15&param2=DemoCategory">
   View Details
</a>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@NTaylorMullen please review suggestion.

**Comment by Rick-Anderson** [comment]
@contact4manoj  I added `code` and removed the HTML encoding. Can you review my updates to your issue?

**Comment by contact4manoj** [comment]
Thank you very much @Rick-Anderson.  I noticed I had made a small textual mistake, which I have corrected now.  It looks great.

And if you find everything fine, kindly submit the same for approvals.

**Comment by contact4manoj** [comment]
Sorry.  I noticed that I had mistakenly closed the issue.

**Comment by NTaylorMullen** [comment]
I'm a bit confused, on what's this is adding. We have an [`asp-all-route-data` section](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-all-route-data) and an [`asp-route-*` section](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-route-value). It's up to the user to determine which approach benefits them.

@contact4manoj could you clarify what you're suggesting to add/update in the docs?

**Comment by contact4manoj** [comment]
Hi @NTaylorMullen,

I agree that my request is an implementation of [asp-route-*](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-route-value).  The idea is to help the developer referring to the document to understand how to innovatively adopt this approach, instead of the elaborate approach recommended by  [asp-all-route-data](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-all-route-data).

That said, if you think that it is something that the existing documentation doen't need this, then please inform, so that I shall close this request accordingly.

**Comment by NTaylorMullen** [comment]
> That said, if you think that it is something that the existing documentation doen't need this, then please inform, so that I shall close this request accordingly.

Ya I think the existing docs cover it sufficiently for now. Thanks for looking out for us though! Always good to have extra eyes on our docs 😄
