### ISSUE TITLE
Requires update for Core 2.2 MVC project

### ISSUE THREAD

**Issue by aveer28** [aspnet/AspNetCore.Docs#13379]
When scaffolding an MVC project with auth (dotnet new mvc -o &lt;name&gt; --auth Individual), Identity defaults to using internal razor pages for Register, Login etc. The tutorial needs to be updated to reflect that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll do that soon as part of the 3.0 sweep.
#13233
