### ISSUE TITLE
Logger - Does it logs client ip address, when hosted in ELB or LB ?

### ISSUE THREAD

**Issue by srganeshram** [aspnet/AspNetCore.Docs#13382]
**Logger - Does it logs client IP address, when hosted in ELB or LB ?**

Hi Damien/Tom,

I was excited about this article when it stated that logging client IP address. This looks very useful for me to understand who is logging in to my website.
I need some clarification from your end. 

> "Say when my application is hosted on Load balance or ELB or Azure LB, will it track the client IP address ?"

because usually when we log for client IP Address, we usually end up with getting ELB IP address or LB IP address.

Please clarify.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @srganeshram ... Please see the proxy/LB topic, which will explain how to use Forwarded Headers Middleware to get the original client IP address in proxy/LB scenarios ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
