### ISSUE TITLE
Custom model binder for methods with more than one parameter are not documented well enough.

### ISSUE THREAD

**Issue by arieradle** [aspnet/AspNetCore.Docs#13386]
# Issue description

Custom model binder for methods with more than one parameter are not documented well enough.
Please refer this question: 
https://stackoverflow.com/questions/56883548/custom-model-binder-for-a-webapi-method-with-more-than-one-parameter

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x ] .NET Framework - 462

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13387.

Please use the **This Page** feedback form at the bottom of any topic. It tags the issue with metadata that helps us track the work.
