### ISSUE TITLE
Custom model binder for methods with more than one parameter are not documented well enough

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13387]
From @arieradle ...

# Issue description

Custom model binder for methods with more than one parameter are not documented well enough.
Please refer this question: 
https://stackoverflow.com/questions/56883548/custom-model-binder-for-a-webapi-method-with-more-than-one-parameter

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x ] .NET Framework - 462

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  It looks like I just need to add your SO answer to this doc.

**Comment by serpent5** [comment]
Oh yeah. I guess it could go in the "Implementing a ModelBinderProvider" and be a lot less wordy than my answer. :smile:

**Comment by serpent5** [comment]
@Rick-Anderson Would you like me to take a stab at this?

**Comment by Rick-Anderson** [comment]
@serpent5  yes!

**Comment by serpent5** [comment]
@Rick-Anderson Just as a heads-up: this article is *really old* and the sample app targets 1.0 :scream:, which means it doesn't have any of the more recent API conventions (`[ApiController]`, `ControllerBase`, etc). Do you know if there's an issue for getting this all updated? The question I answered was very specific to having the `[ApiController]` attribute in place, but the solution might be the same for controllers without this so I'm just going to check that first.

**Comment by guardrex** [comment]
@serpent5 The sample tracking issue is at https://github.com/aspnet/AspNetCore.Docs/issues/5495. Brace yourself before you :eyes: that issue ... this ain't the only one. :smile: *Aye captain! I'm giv'in er all she's got!* - Chief Engineer Montgomery Scott

If you work this with sample updates (**_IF_** the sample survives), then *in theory* we'd have a 2.x (2.2) and 3.x (3.0) sample created from what's there now. It does feel good that ..........

> sample apps are generally being dropped

We've dropped a few already in favor of snapshot files. This topic seems like a good candidate for that treatment. If you get approval to do that, I'll remove this one from the sample tracking issue :tada:.

Layout the snapshot files the same way as a sample app ...

If there are no differences between 2.x and 3.x, versioning isn't required ...

```
custom-model-binding/samples_snapshot/CustomModelBindingSample/file.xxx
```

If there are differences in one or more files between 2.x and 3.x, use `2.x` and `3.x` folders (but you only a 2.x file if a 3.x file would be identical to it).

```
custom-model-binding/samples_snapshot/2.x/CustomModelBindingSample/file.xxx
custom-model-binding/samples_snapshot/3.x/CustomModelBindingSample/file.xxx
```

**Comment by Rick-Anderson** [comment]
Upgrading to 2.2 and 3.0 would be ideal

**Comment by Rick-Anderson** [comment]
See #13529

**Comment by Rick-Anderson** [comment]
Moved to #16319
