### ISSUE TITLE
3.0 update: delete Index page

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13389]
Should we delete this page as part of the 3.0 sweep, including the 2.2 version? Does this add any value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Tutorial: Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra do you think we should delete this?

**Comment by tdykstra** [comment]
Yes but put a summary list of tutorials in the first tutorial.
