### ISSUE TITLE
Explanation for copy steps in Dockerfile template 

### ISSUE THREAD

**Issue by AbdoHassanUMG** [aspnet/AspNetCore.Docs#13381]
[EDIT by @guardrex to remove issue boilerplate]

Why the project file is copied individually before dotnet restore then a "COPY . . " statement is execute later ? 

What's the benefit of doing a csproj copy instead of doing a "COPY . ." before the dotnet restore?

**Comment by AbdoHassanUMG** [comment]
Docs tag 5847cdf8-1823-7740-6e43-030902b26ad8

**Comment by AbdoHassanUMG** [comment]
@usmanmohammad

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13388.

Please use the **This Page** feedback form at the bottom of the topic. It tags the issue with metadata that helps us track the issue.
