### ISSUE TITLE
Step 3 doesn't work for VS Mac

### ISSUE THREAD

**Issue by niktek** [aspnet/AspNetCore.Docs#13380]
Can get preview version installed, and the DNC 3 SDK reports version correctly from terminal.  Extension download does not work on Mac and then steps to create project do not match with UI options.

You have to:
 'File-&gt;New Solution'
Select Other-&gt;Miscellaneous-&gt;Blank Solution

Go to the terminal and inside the folder of the newly created solution:
mkdir shared server client
cd shared
dotnet new blazorlib
cd ../server
dotnet new blazorserverside
cd ../client
dotnet new blazor

Now you can go to the Solution in VS and add the three existing projects to your solution, set the server project as your Startup Project, build all and then run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @niktek ... Blazor isn't supported in VS4Mac yet. I don't have an ETA, but engineering will let us know when to provide the instructions.
