### ISSUE TITLE
3.0 update: XSRF doc

### ISSUE THREAD

**Issue by nathans1309** [aspnet/AspNetCore.Docs#13394]
I wasn't able to get antiforgery headers working while placing the code `app.Use(next => context =>` as the first piece of middleware.  It worked after placing just before `app.UseMvc(...`

Edit: Add RP samples
![image](https://user-images.githubusercontent.com/3605364/69367232-f8808f00-0c3b-11ea-875c-a3a4c1597eff.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@nathans1309  see [Middleware order](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#middleware-order)
