### ISSUE TITLE
How To "Download or view the completed application."

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/AspNetCore.Docs#13403]
thanks for taking the time …
each chapter has a 'link' saying:

"Download or view the completed application."

when clicking I get to github. Yes I see the github files BUT I can't 'download' (NO 'clone and Download' button).
VIEW: does this just mean to view the github files!?

HOW do I view the App !?
What I'm doing wrong NOT to see the 'Clone or Download' button ?
thanks ek
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @edikaufmann ... Follow the guidance at :point_right: https://docs.microsoft.com/aspnet/core/index#how-to-download-a-sample
