### ISSUE TITLE
Blazor (client-side) template missing - Suggest rename in docs

### ISSUE THREAD

**Issue by mike-01** [aspnet/AspNetCore.Docs#13402]
I have the latest VS 2019 Preview and Blazor template, 3.0.0-preview6.19307.2.

I think you need to update the documentation at https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

I believe it should read "Blazor WebAssembly App" and not "Blazor (client-side)".

It's confusing for people getting started with Blazor.

**Comment by guardrex** [comment]
Hello @mike-01 ... quick side note: Please use the **This Page** feedback button at the bottom of any topic. It adds metadata to the issue to help us track the work.

VS engineering did make some changes. We corrected one on an earlier PR. I'm not on Preview here (for unrelated reasons). Can you supply a screenshot here for me to take a look at what you're seeing in the VS Preview UI?

**Comment by guardrex** [comment]
@mike-01 Here's the PR that we recently did for the server-side naming ...

https://github.com/aspnet/AspNetCore.Docs/pull/13274

Note in his screenshot that the client-side template hadn't changed names at that time. He posted this UI image ...

![Capture](https://user-images.githubusercontent.com/1622880/61546164-9ce49180-aa0e-11e9-979c-1cde8e2a6f99.PNG)

**Comment by guardrex** [comment]
@scottaddie @tdykstra Are either of you on the latest VS 2019 Preview, which is 16.2 Preview 4? If so, do you have a sec to screenshot the new web app dialog? I can't install Preview here ... no HD space left on these drives. :weary: [*Next year, I'm building a new desktop or getting a new laptop.*]

**Comment by mike-01** [comment]
![Blazor](https://user-images.githubusercontent.com/6891486/61557151-800d8580-aa31-11e9-8913-4098f9dff37b.PNG)

**Comment by guardrex** [comment]
Thanks @mike-01 ... Tom showed that to me. I presume that the double entry there is already fixed (or will be soon).

**Comment by mike-01** [comment]
![VS Info](https://user-images.githubusercontent.com/6891486/61557300-df6b9580-aa31-11e9-8e04-fbfc9d5ba23e.PNG)
