### ISSUE TITLE
Configuring the SendGridUser and SendGridKey.

### ISSUE THREAD

**Issue by Vihang030** [aspnet/AspNetCore.Docs#13411]
Is the SendGridUser and SendGridKey username and password of SendGrid account? or a API name and API key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=visual-studio&view=aspnetcore-2.2#configure-sendgrid-user-secrets-1)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It uses the API key. Here's their example :point_right: https://github.com/sendgrid/sendgrid-csharp/blob/master/ExampleCoreProject/Example.cs

I'm not sure what the `SendGridUser` is used for.

**Comment by Rick-Anderson** [comment]
`SendGridUser` is used in the 3.0 version. It's not required.
