### ISSUE TITLE
Please Add RenderAction and RenderAction Partial Again

### ISSUE THREAD

**Issue by iamjassiesandhu** [aspnet/AspNetCore.Docs#13413]
Hi,

I think removing RenderAction and RenderActionParital is not a good idea, these ViewConponents require whole new coding files and very irritating, request you please keep RenderAction again.

**Comment by guardrex** [comment]
Hello @iamjassiesandhu ... This is product unit feedback, and I think they decided that they aren't going to do that. See ...

* https://github.com/aspnet/AspNetCore/issues/329
* https://github.com/aspnet/AspNetCore/issues/1919
