### ISSUE TITLE
Working with real Db (I have Views, etc) - where do I delete Database?

### ISSUE THREAD

**Issue by alvipeo** [aspnet/AspNetCore.Docs#13426]
I added Db migration into builder.ConfigureServices. So the db gets created and migrations are applied for every test. But I can't figure out where should I put the code to drop database (after each test).

(Yes, I need it and it's fast in case you're wondering ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by alvipeo** [comment]
ok, I figured that out - this has nothing to do with WebApplicationFactory. That code should be placed into TestBase class which should implement IDisposable.

**Comment by RandyDaddis** [comment]
I wonder if utilizing [ReSpawn](https://github.com/jbogard/respawn) to reset the Db instead of delete/create/migrate would improve integration test performance? Jimmy Bogard provides a [sample implementation](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity.IntegrationTests/SliceFixture.cs).

**Comment by alvipeo** [comment]
I'll give it a try, thank you! Never heard of it before.
