### ISSUE TITLE
Command doesn't generate identity for this command.

### ISSUE THREAD

**Issue by mitulsuthar** [aspnet/AspNetCore.Docs#13438]
I am using asp.net core 2.2 and this command doesn't generate identity related stuff. This needs correction.
dotnet new webapi -au Individual

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-2.2#reconfigure-app-to-use-a-new-storage-provider)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@mitulsuthar Identity isn't currently supported in web API projects. You may have also noticed that it isn't possible to add via Visual Studio. I've removed this invalid command from the doc. Thank you for bringing it to our attention.
