### ISSUE TITLE
Dfifferent approach with AppContext for DAL and PageModel

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/AspNetCore.Docs#13439]
I am confused:. The author wrote for DAL tests' description: "The problem with this approach is that each test receives the database in whatever state the previous test left it", so for DAL tests is used the dedicated function (TestDbContextOptions), but not for PageModel tests. Where is a difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gjaryczewski ... The reason is the last sentence of the following paragraph in the [Unit tests of the page model methods](https://docs.microsoft.com/aspnet/core/test/razor-pages-tests#unit-tests-of-the-page-model-methods) section (emphasis added) ...

> This group of tests often mock the methods of the DAL to produce expected data for the Act step where a page model method is executed. For example, the `GetMessagesAsync` method of the `AppDbContext` is mocked to produce output. When a page model method executes this method, the mock returns the result. The data doesn't come from the database. **This creates predictable, reliable test conditions for using the DAL in the page model tests.**

This is just *one way* that you can go. If you don't want to use mocks, that's up to you.
