### ISSUE TITLE
Short syntax for data binding to parameters and events

### ISSUE THREAD

**Issue by SNathani** [aspnet/AspNetCore.Docs#13433]
It would be more fluent if we could have short notations for binding to parameters and events.

In the above example, the binding @data-year="ParentYear" can be shortened to @year="ParentYear"
and event can be shortened from @data-year:event ="YearChanged" to :year="YearChanged"

Please note that, in the real world scenarios, we often use several few parameters and having to type @data-Param attribute repeatedly  makes code look ugly and verbose.

Having short syntax will reduce typing and saves few bits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @SNathani ... We only handle documentation feedback here. Open feedback and product feedback with the engineers and management at https://github.com/aspnet/AspNetCore/issues.
