### ISSUE TITLE
[Preview 8] Blazor globalization

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#13435]
# Summary

Blazor's binding support (`@bind`) for `<input>` elements is culture-aware. This means that values will be formatted for display and parsed using the current culture's rules. You can access the value of the current culture from the `System.Globalization.CultureInfo.CurrentCulture` property. This means that `@bind` will work correctly when the user's desired culture has been set as the current culture - see the article on localization for information on setting the culture. (https://github.com/aspnet/AspNetCore.Docs/issues/13436)

As an exception to this, `<input type="number" />`  and `<input type="date" />` will use `CultureInfo.InvariantCulture` and the formatting rules appropriate for these field types in the browser. These field types cannot contain free-form text and have a look and feel that is controller by the browser. 

Other field types with specific formatting requirements include `datetime-local`, `month`, and `week` - these field types are not supported by Blazor at the time of writing because they are not supported by all major browsers.

## Specifying the format for a binding

`@bind` supports the `@bind:format` parameter to control the formatting and parsing of date types. You can use the `@bind:format` to specify a format string when using a .NET date type with an `<input type="text" />` field. Specifying a format is not recommended when using `<input type="date" />` as the this field type has built-in support in Blazor that provides the required format.

`@bind:format` is supported for binding the following .NET types:
- `DateTime`
- `DateTime?`
- `DateTimeOffset`
- `DateTimeOffset?`

## Specifying the culture for a binding

`@bind` supports the `@bind:culture` parameter to provide a `System.Globalization.CultureInfo` to be used in parsing and formatting. Specifying a culture is not recommended when using `<input type="date" />`, or `<input type="number" />` as these this field type has built-in support in Blazor that provides the required culture.

**Comment by rynowak** [comment]
@guardrex - updated the main post with the information that seems relevant. This should get folded into existing topics rather than a new one.

**Comment by guardrex** [comment]
Resolved by #13696
