### ISSUE TITLE
the code in OnStopping() & OnStopped() cannot be executed in LifetimeEventsHostedService 

### ISSUE THREAD

**Issue by zhaobingwang** [aspnet/AspNetCore.Docs#13443]
in [.NET Generic Host](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#iapplicationlifetime-interface) ,the code of class `LifetimeEventsHostedService` in `OnStopping()` & `OnStopped()` cannot be executed  when i publish to docker run as  an container,any idea?

**Comment by zhaobingwang** [comment]
i debug the code `OnStopping()` & `OnStopped()` on windows, it's work fine(press `ctrl+c` finish the process and the code be excuted). but in docker,the code can't be excuted when i use the command `docker stop container`

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13446.
