### ISSUE TITLE
Usage of options.CurrentValue

### ISSUE THREAD

**Issue by moikot** [aspnet/AspNetCore.Docs#13450]
If in the example about avoiding service locator pattern MyClass is registered as a singleton, the CurrentValue returned in the constructor will stale as soon as the options monitor updates options. In order to avoid that you need to retrieve CurrentValue in the method where options are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by moikot** [comment]
I think I was mistaken

**Comment by guardrex** [comment]
@moikot Not so fast. Yes, `MyClass` isn't registered in the container, but I kind'a like you idea better. Let's give that a shot and see how engineering likes it. However, standby for a bit. We're crazy busy 🏃🏃🏃🏃😅 at the moment. I'll get back to u within ... say ... er ... 70.5 hours! :smile: lol
