### ISSUE TITLE
when running on linux with cli: No templates matched the input template name: grpc.

### ISSUE THREAD

**Issue by ptsneves** [aspnet/AspNetCore.Docs#13458]
When trying to create the grpc server with the presented dotnet new command i get:
No templates matched the input template name: grpc.

It seems I do not have the grpc template although i have dotnet 2.2.300. I am running in Linux.
If I manually create for example an mvc application and then manually add the package for grpc  it seems i can progress, although not completely in line with the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
@ptsneves IIRC, gRPC is a 3.0 thing. Get the 3.0 preview (Preview 7 just came out today :tada:), and you should get the template.

https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by ptsneves** [comment]
You are right. The docs were for 3.0. I am working for a professional deployment so developing with non stable releases is a bit out of my scope for now. Thanks for the clarification.
In the mean time i got the gRPC official project C# implementation working with core.
