### ISSUE TITLE
Blazor App not appearing as option when creating new project.

### ISSUE THREAD

**Issue by Izelude** [aspnet/AspNetCore.Docs#13472]
Hi, 
I just installed Visual Studio Enterprise 2019 Preview Version 16.2.0 Preview 4.0 
and 
dotnet core sdk 3.0.100 preview7.
I ran the shell command as described and it finished without any error.
When i create a new project i do not get the "Blazor App" option. If i type in "blazor" in the search i get offered 2 different (but same in appearance) ASP.NET Core Web Application options.
I also have Visual Studio 2017 Enterprise installed on my machine (not sure if that might cause an issue with Template surfacing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 This is what happened to me yesterday when I tried on an Azure VM (WS 2019). I received 16.2 P4, not 16.3 from the Preview installer (Community Ed.).

**Comment by danroth27** [comment]
[Visual Studio 16.3 Preview 1 is now available](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-2-generally-available-and-16-3-preview-1/) and should resolve these issues. Sorry about the delay!

**Comment by TJSoftware** [comment]
Hi, my issue felt like it was related to this so I did not think I should open another item.

I could not see in Community or Enterprise preview 16.3 preview 1. I tried to use `ASP.NET Core Web Application` from the create project page, then the next seletion I used `Blazor (client-side)`. This allowed me to be able to complete the rest of the steps on the page.
