### ISSUE TITLE
how to use te override OnInitializedAsync on my pages

### ISSUE THREAD

**Issue by MarvynHarry** [aspnet/AspNetCore.Docs#13474]
What do I have to do to be able to use these methods since in my project it says "no suitable method found to override"
![image](https://user-images.githubusercontent.com/44927942/61802895-9d629b00-ae07-11e9-8792-5ad2d17a8342.png)

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
