### ISSUE TITLE
Disabling the ANCM start-up error page and configuring IIS custom error pages

### ISSUE THREAD

**Issue by mattbrooks2010** [aspnet/AspNetCore.Docs#13479]
Under the [Start-up error page](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#start-up-error-page) heading, it is stated:

> To suppress this page and revert to the default IIS 5xx status code page, use the disableStartUpErrorPage attribute. For more information on configuring custom error messages, see HTTP Errors &lt;httpErrors&gt;.

However, this doesn't appear to work. Is it [incorrect](https://github.com/aspnet/AspNetCoreModule/issues/31)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#start-up-error-page)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mattbrooks2010 ... This was seen by engineering when some work on the topic was performed in November on https://github.com/aspnet/AspNetCore.Docs/pull/9452. That guidance was preexisting to that PR, but engineering looked right at it when that paragraph was moved (*guessing*).

Let's ask @jkotalik to :eyes: and confirm ...

> To suppress this page and revert to the default IIS 5xx status code page, use the disableStartUpErrorPage attribute. For more information on configuring custom error messages, see HTTP Errors `<httpErrors>`.

**Comment by jkotalik** [comment]
disableStartupErrorPage should work. @mattbrooks2010 that issue was 3 years old and I believe it has been resolved. Are you observing different behavior?

**Comment by mattbrooks2010** [comment]
Thank you both for your responses. I have revisited my setup and can confirm I now have it working.

It turns out I didn't have the correct IIS feature installed locally, and my IIS `<httpErrors>` configuration wasn't causing an error — it was just being ignored. I didn't troubleshoot further than this when I saw [this issue](https://github.com/aspnet/AspNetCoreModule/issues/31).

```
<httpErrors errorMode="Custom" defaultResponseMode="File">
  <remove statusCode="500" />
  <error statusCode="500" path="500.htm" />
</httpErrors>
```

![image](https://user-images.githubusercontent.com/2045274/61810341-f990e380-ae36-11e9-8add-00f144078fd4.png)

**Comment by guardrex** [comment]
Thanks @mattbrooks2010 ... I think that's the default for both a WS and Win10 install of IIS. If so, I'll sacrifice a Microsoft Ergonomic Keyboard to the :pray:  *server gods* :pray: in hopes that we'll be ok with the current coverage. I'll keep and :eye: and :ear: out tho for anyone else hitting this going forward.
