### ISSUE TITLE
additional info

### ISSUE THREAD

**Issue by tet-web-dev** [aspnet/AspNetCore.Docs#13488]
Considering this is one of the top 3 results when searching "adding validation to asp core razor pages" It may be helpful to mention jquery.validate and jquery.validation.unobtrusive need to be added to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The templates add them.

**Comment by Rick-Anderson** [comment]
@tet-web-dev  this tutorial is about using the template/scaffold generated code. That info should be in [Model validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2)
