### ISSUE TITLE
What are fragments in Blazor?

### ISSUE THREAD

**Issue by ArvindRSingh** [aspnet/AspNetCore.Docs#13486]
> Render fragments can be defined using Razor template syntax. 

What are fragments? The concept of fragements is not clear on the page or need some reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ArvindRSingh ... I agree. Later, we have ...

> A render fragment represents a segment of UI that is rendered by the component.

"Later" doesn't do us much good, does it? :smile: lol

I'll get this fixed. Thanks again.
