### ISSUE TITLE
[Preview 8] Blazor @key is now stricter

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#13489]
Currently, the docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#use--to-control-the-preservation-of-elements-and-components say:

> Avoid supplying a value that can clash unexpectedly. If @key="@someObject.GetHashCode()" is supplied, unexpected clashes may occur because the hash codes of unrelated objects can be the same. If clashing @key values are requested within the same parent, the @key values won't be honored.

This is no longer accurate. As of preview 8, `@key` is becoming stricter. It *only* allows distinct keys. If the renderer finds two identical keys within the same parent element, it will throw an exception. So I'd suggest rephrasing as:

> Be careful to ensure that values used for `@key` do not clash. If clashing values are detected within the same immediate parent element, Blazor will throw an exception, because it could not deterministically map old elements or components to new ones. So, you should only use values that are sure to be distinct, such as object instances or primary key values.

**Comment by guardrex** [comment]
@mkArtakMSFT This is straight-forward enough that a *silly green dinosaur* can probably cover it. Assign me if you want to (I'll update the labels accordingly.)

**Comment by mkArtakMSFT** [comment]
@guardrex all yours to tackle!

**Comment by guardrex** [comment]
Resolved by #13504

@Rick-Anderson @scottaddie @wadepickett It's *very annoying* 😠 that when we merge a release staging branch into `master` that these "fixed" issues don't automatically close. I'll research it and see if there's anything we can do about it.
