### ISSUE TITLE
Disable client-side validation not working for Razor Pages

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13490]
See [Disable client-side validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#disable-client-side-validation)

```
services.Configure<HtmlHelperOptions>(o => o.ClientValidationEnabled = false);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#disable-client-side-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu  `services.Configure<HtmlHelperOptions>(o => o.ClientValidationEnabled = false);` doesn't disable  client side validations.

**Comment by dougbu** [comment]
@Rick-Anderson which versions are affected and exactly how are they affected? From everything I can see in the source, the option should control MVC HTML and tag helpers wherever they're used.

@rynowak is this a known issue w/ Razor pages?

**Comment by Rick-Anderson** [comment]
@dougbu  see https://github.com/aspnet/AspNetCore/issues/7576
I'm using dotnet --version
3.0.100-preview7-012821
cc @javiercn

**Comment by Rick-Anderson** [comment]
@Ponant I have the following code:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();

    services.Configure<HtmlHelperOptions>(o => o.ClientValidationEnabled = false);

    services.AddDbContext<RazorPagesMovieContext>(options =>
      options.UseSqlServer(Configuration.GetConnectionString("RazorPagesMovieContext")));
}
```
But that's not disabling client side validation.

**Comment by dougbu** [comment]
Ah, I see. A problem @javiercn fixed in 3.0 Preview 5.

@javiercn did you confirm whether both 2.1 and 2.2 applications experience the bug?

**Comment by Rick-Anderson** [comment]
@dougbu I'm using dotnet --version
3.0.100-preview7-012821
and it's not working. See my code above.

**Comment by Rick-Anderson** [comment]
The following code works
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages().AddViewOptions(o =>
        o.HtmlHelperOptions.ClientValidationEnabled = false);

    services.AddDbContext<RazorPagesMovieContext>(options =>
       options.UseSqlServer(Configuration.GetConnectionString("RazorPagesMovieContext")));
}
```

**Comment by Rick-Anderson** [comment]
@Ponant  what are the two steps mentioned in aspnet/AspNetCore#7576 to get it working with RP in 2.x?

**Comment by Rick-Anderson** [comment]
`services.Configure<HtmlHelperOptions>(o => o.ClientValidationEnabled = false);` works in 2.2
