### ISSUE TITLE
dev-certs for other URLs

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/AspNetCore.Docs#13496]
`dev-cert` appears to only create certificates for `localhost`. Can we have specify other URLs to it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`localhost` is a hardcoded constant ...

https://github.com/aspnet/AspNetCore/blob/master/src/Shared/CertificateGeneration/CertificateManager.cs#L25

https://github.com/aspnet/AspNetCore/blob/master/src/Shared/CertificateGeneration/CertificateManager.cs#L181

... and there's no provision in the `dotnet dev-certs` command options to override it.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by weitzhandler** [comment]
I the future, it would have been nice if dev-certs has an additional parameter that allows creating certificates with other URLs.
For the reference, I did the following:

1. Create a certificate using the following PowerShell command:
```ps1
New-SelfSignedCertificate -Subject *.aqounts.com -DnsName mysite.com, *.mysite.com
    -CertStoreLocation Cert:\CurrentUser\My -NotAfter (Get-Date).AddYears(10)
```

The modified _Program.cs_ to like like the following:
```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
  WebHost
    .CreateDefaultBuilder(args)
    .UseStartup<Startup>()
    .ConfigureKestrel(options =>
    {
      // listen for HTTP
      options.ListenLocalhost(80);

      // retrieve certificate from store
      using (var store = new X509Store(StoreName.My))
      {
        store.Open(OpenFlags.ReadOnly);

        var certs = store.Certificates.Find(X509FindType.FindBySubjectName, "*.mysite.com", false);
        if (certs.Count == 1)
          // listen for HTTPS    
          options.ListenLocalhost(443, listenOptions =>
              listenOptions.UseHttps(certs[0]));
        else
          throw new InvalidOperationException("No matching certificate found.");
      }
    })
    .UseUrls($"https://*.{Consts.MainAddress}");
```

**Comment by weitzhandler** [comment]
I the future, it would have been nice if dev-certs has an additional parameter that allows creating certificates with other URLs.
For the reference, I did the following:

1. Create a certificate using the following PowerShell command:
```ps1
New-SelfSignedCertificate -Subject *.mysite.com -DnsName mysite.com, *.mysite.com
    -CertStoreLocation Cert:\CurrentUser\My -NotAfter (Get-Date).AddYears(10)
```

The modified _Program.cs_ to like like the following:
```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
  WebHost
    .CreateDefaultBuilder(args)
    .UseStartup<Startup>()
    .ConfigureKestrel(options =>
    {
      // listen for HTTP
      options.ListenLocalhost(80);

      // retrieve certificate from store
      using (var store = new X509Store(StoreName.My))
      {
        store.Open(OpenFlags.ReadOnly);

        var certs = store.Certificates
            .Find(X509FindType.FindBySubjectName, "*.mysite.com", false);
        if (certs.Count == 1)
          // listen for HTTPS    
          options.ListenLocalhost(443, listenOptions =>
              listenOptions.UseHttps(certs[0]));
        else
          throw new InvalidOperationException("No matching certificate found.");
      }
    })
    .UseUrls($"https://*.{Consts.MainAddress}");
```
