### ISSUE TITLE
Incorrect syntax in tutorial

### ISSUE THREAD

**Issue by rhoddog77** [aspnet/AspNetCore.Docs#13491]
To get my button onclick event to work I had to change the syntax to:
&lt;button @onclick="@AddTodo"&gt;Add todo&lt;/button&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @rhoddog77 ... Sounds like you're a version behind. Get the Pre7 SDK at ... https://dotnet.microsoft.com/download/dotnet-core/3.0.

**Comment by rhoddog77** [comment]
ah, sorry. I downgraded because I could not get the Blazor WebAssembly App to build in v7

**Comment by guardrex** [comment]
If you hit anything that looks like a 🐞, the engineers take bug reports on their repo :point_right: https://github.com/aspnet/AspNetCore/issues
