### ISSUE TITLE
3.0 update: Disable model validation

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13507]
See #13490

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#disable-client-side-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by regisbsb** [comment]
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages().AddViewOptions(o =>
        o.HtmlHelperOptions.ClientValidationEnabled = false);
}
```

can we add this to the 3.0 documentation then? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@regisbsb  have you tested that? Great idea, I'll get it added.

**Comment by Rick-Anderson** [comment]
@serpent5  here's an easy one. Let me know if you're interested.

**Comment by regisbsb** [comment]
I've tested and following the thread form the previous  one https://github.com/aspnet/AspNetCore.Docs/issues/13490
it's the only way on 3.0

**Comment by serpent5** [comment]
> Let me know if you're interested.

Yeah, sure. I’ll do it.

**Comment by serpent5** [comment]
@Rick-Anderson Did you want me to create the 3.0 sample for this too? With the typical copy/paste md for >= 3.0 and update approach?

**Comment by Rick-Anderson** [comment]
Give me a few minutes  - I'll create the 3.0 section.

**Comment by Rick-Anderson** [comment]
Ready anytime now. via  #15647
