### ISSUE TITLE
Final Step [Apply Migrations] for Mac Instructions missing

### ISSUE THREAD

**Issue by D-BowdreyR** [aspnet/AspNetCore.Docs#13506]
The final step in this tutorial [Apply Migrations] says that migrations are not required for SQLite, but this just seems more lazy than true. I looked at the database with DB Browser for SQLite and it showed that the **Title** and **Rating** column did not have 'Not Null' constraint against them.

So I rebuilt the database with the following commands:

1. dotnet ef database drop
2. dotnet ef migrations remove
3. dotnet ef migrations add initial
4. dotnet ef database update

Afterwards the DB Browser for SQLite showed all the constraints/validation in this part of the tutorial.

This should be added to the VS code VS for Mac Tab to complete the tutorial.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@D-BowdreyR  thanks. I'll get this updated.

If you have more than one migration you'll need to delete the migrations folder.

**Comment by Rick-Anderson** [comment]
@tdykstra  I like the  `dotnet ef migrations remove` step. We could add, if you have two migrations, run `dotnet ef migrations remove` twice. Alternatively, delete the migrations folder.

**Comment by Rick-Anderson** [comment]
> Afterwards the DB Browser for SQLite showed all the constraints/validation in this part of the tutorial.

@D-BowdreyR  was there any change in the char length like SQL?

**Comment by tdykstra** [comment]
@Rick-Anderson I haven't seen multiple remove commands in a row work, have you?  Deleting the Migrations folder always works.

**Comment by Rick-Anderson** [comment]
Looks like this was fixed.
