### ISSUE TITLE
Documentation conflict

### ISSUE THREAD

**Issue by patHyatt** [aspnet/AspNetCore.Docs#13519]
In the section https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#reserved-routing-names an example is provided using a regex constraint against a parameter named `action`.

However, in the section https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#reserved-routing-names parameters named `action`  are prohibited as it violates reserved keywords.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The paragraph in question:

To constrain a parameter to a known set of possible values, use a regular expression. For example, `{action:regex(^(list|get|create)$)}` only matches the `action` route value to `list`, `get`, or `create`. If passed into the constraints dictionary, the string `^(list|get|create)$` is equivalent.

**Comment by Rick-Anderson** [comment]
@patHyatt  it's not a parameter.

```
app.UseMvc(routes =>
{
    routes.MapRoute(
    name: "regexConstraint",
    template: "{controller:regex(^H.*)=Home}/{action:regex(^Index$|^About$)=Index}/{id?}");
});
```
The preceding won't match Privacy. The following will

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                name: "regexConstraint",
                template: "{controller:regex(^H.*)=Home}/{action:regex(^Index$|^Privacy)=Index}/{id?}");
            });
```

**Comment by patHyatt** [comment]
@Rick-Anderson 
Thanks for the response.

I still think there is something off here, and I did not explain well what I think is off. Specifically this surrounds attribute routing and using the example regex provided in the docs.

The doc [Specifying attribute route optional parameters, default values, and constraints](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#specifying-attribute-route-optional-parameters-default-values-and-constraints) links to the [Route Template Reference](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#route-template-reference), provides the example (`{action:regex(^(list|get|create)$)}`) listed in my original attempt at explaining this.

Creating a route with the attribute provided in that example throws a `RouteCreationException`.

```csharp
        [HttpGet("test/{action:regex(^(list|get|create)$)}")]
        public IActionResult Test(string action)
        {
            return Ok(action);
        }
```

**Comment by Rick-Anderson** [comment]
I don't think you'd ever use an action constraint like that on an action.

**Comment by patHyatt** [comment]
As a result of the documentation, I did just that.
