### ISSUE TITLE
Application restores with project file  in .NET Core 3.0 SDK 

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#13515]
Hi there,

The documentation shows 
Prerequisites
.NET Core 2.2 SDK or later

I created the web app following the command line scripts in "Create a web app and scaffold Identity" section. When the application was restored and I viewed the project file it shows (in part)
&lt;ItemGroup&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0-preview7.19365.7" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview7.19365.7" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview7.19365.7" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview7.19362.6" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview7.19362.6" /&gt;
    &lt;PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" /&gt;
  &lt;/ItemGroup&gt;
After some trial and error, I could successfully load and build the solution in Visual Studio 2019 (preview). Earlier I have failed to build it in Visual Studio 2017  
The issue here is the improper labelling ".NET Core 2.2 SDK or later" as users may think that they can build the solution with SDK 2.2 as well (in VS 2017) which is not the case. The label should read .NET Core 3.0 
Kaushik 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio#enable-account-confirmation-after-a-site-has-users-1)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you've installed 3.0 preview, you need to select the [3.0 version of the doc](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.0&tabs=visual-studio#enable-account-confirmation-after-a-site-has-users-1)

**Comment by krchome** [comment]
Ok that's good to know Rick-Anderson. 
However let me clarify that I don't have 3.0 preview SDK but have Visual Studio 2019 preview . I have just the SDK 2.2 installed and I selected this 2.2 version command script in this document. However the restoration still targetted as if 3.0 preview is installed and created a project file as I mentioned above . 
Could it be that irrespective of the preview installed, it targets the highest Visual Studio version installed and then restores the project file that is compatible with the preview for that version, in this case Visual Studio 2019 preview ?

**Comment by Rick-Anderson** [comment]
VS19 previews go with .NET Core 3 previews.

**Comment by krchome** [comment]
Thanks for letting me know. 
One thing still lingers on, is that the  console command for this document (2.2) worked fine with VS 2019 (and 3.0 preview) as well (although the command is different for 3.0 preview. 
Please clarify this as I am going to make a YouTube video on this document too. 
Cheers
