### ISSUE TITLE
Blazor client template is not installed.

### ISSUE THREAD

**Issue by marqdouj** [aspnet/AspNetCore.Docs#13531]
Today I download and installed VS2019 Preview and .NET Core SDK 3 Preview, as directed in this article.
According to para 3.5 there should be 2 blazor templates. I am only able to select Blazor Service App; there is not option for a blazor client.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-ca/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
What version of VS did you get from the VS installer? You need 16.3 Preview 1 or later, which should be available by now :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/13472#issuecomment-514774210

You must also run the template install command ...

```console
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7
```

**Comment by marqdouj** [comment]
This was the very first time I installed any of the previews (I have VS2017/VS2019 already installed); the VS Installer says I'm up to date. 

VS2019 Preview Help About:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.3.0 Preview 1.0
VisualStudio.16.Preview/16.3.0-pre.1.0+29123.89
Microsoft .NET Framework
Version 4.7.03190

dotnet --info:

Microsoft Windows [Version 10.0.17763.615]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\dougm>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by guardrex** [comment]
If you ran the template install command, that all looks good from here.

Did you try to get to *Blazor (client-side)* by going through *ASP.NET Core Web Application* first (i.e., **not** selecting **Blazor App** from the top-level offerings)? I wonder if that template is still only available by going through *ASP.NET Core Web Application*, while the **Blazor Server App** (Blazor server-side) is available from *Blazor App* at the top level.

One of the problems that I had last week was that either the installer didn't work properly or wasn't updated. I need to spin up a new VM and check our instructions. Sorry for the trouble, but *this is preview!* :smile: lol .... things can break ........ and they will. :cry:

**Comment by marqdouj** [comment]
I ran the install again: dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7 

The templates now show up as follows:
1. Select Blazor from the filter:
  a. Blazor Server App
2. Select Web App:
  a. Blazor Server App
  b. Blazor Client (ASP.NET Core hosted)
  c. Blazor (client-side)

Looks like I should be gtg for now, thanks.

**Comment by guardrex** [comment]
Ok ... that's what another reader said on the issue.

I'll take a look at this shortly. Leave this issue open.

Thanks for commenting on it.

**Comment by guardrex** [comment]
Confirmed on an Azure VM. The current instructions for 16.3 P1 are correct.

**Comment by ChrisMyrick** [comment]
I ran into the same issue and re-ran the dotnet new command. I now see the three template types (Server, Core Hosted, and Client Side), but the high level project template should not display "Server App".

**Comment by Lurs** [comment]
I ran into the same issue but re-running the dotnet new command didn't help me on Windows 7 and VS Community 2019 Preview. I only see the server-side template.
VS2019 Preview Help About:
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 1.0
VisualStudio.16.Preview/16.3.0-pre.1.0+29123.89
Microsoft .NET Framework
Version 4.7.03062

dotnet --info:
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\share
d\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\
Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\
shared\Microsoft.WindowsDesktop.App]

**Comment by guardrex** [comment]
@Lurs Re-execute that template install command in the *Get Started* topic and then restart VS and see if it picks them up.

**Comment by Manikandarajan-Jegadeshwaran** [comment]
First time I cant able to see any client side template while creating new project from IDE. I tried from console, by using 
'dotnet new'  and 'dotnet new blazor' . 

Its worked.

**Comment by Lurs** [comment]
@guardrex the output on my host PC is the following:
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\NuGet.targets(123,5): error
: Der Dienstindex für die Quelle "https://api.nuget.org/v3/index.json" konnte ni
cht geladen werden. [d:\Users\werdesl\.templateengine\dotnetcli\v3.0.100-preview
7-012821\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\NuGet.targets(123,5): error
:   Response status code does not indicate success: 407 (Proxy Authorization Req
uired). [d:\Users\werdesl\.templateengine\dotnetcli\v3.0.100-preview7-012821\scr
atch\restore.csproj]

The proxy seems to be the problem. I wonder why it works with the server-side template. How can I tell dotnet my proxy credentials?

**Comment by guardrex** [comment]
@Lurs I only see one report that didn't receive further discussion: https://github.com/dotnet/core/issues/2507

Ask on the dotnet/cli repo :point_right: https://github.com/dotnet/cli/issues

**Comment by joslat** [comment]
Still happening, got everything following the official get started, https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio, which matches the VS and SDK version. No client side blazor can be seen on the designer.
But, on the command line "dotnet new blazor" works like a charm.

Is there any way to get this resolved? :)

**Comment by guardrex** [comment]
@joslat ... You tried one more template install just to make sure?

1. Close VS.
1. Execute :point_right: `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7`
1. Re-open VS. 🤞

If you have VS Preview latest, the correct (Pre7) SDK, and these instructions don't work, open an issue for engineering. https://github.com/aspnet/AspNetCore/issues

**Comment by joslat** [comment]
Hi Guardrex, yes, read the comments and tried even three installations... and a last fourth one after your message.
My VS 2019 preview is freshly installed,
![image](https://user-images.githubusercontent.com/9831011/62836987-149e8880-bc6a-11e9-9f25-311616abf816.png)

Also the SDK seems to be on check:
C:\Users\joslat\blazor\bl01>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

So, do I create a new issue? :)

**Comment by guardrex** [comment]
@joslat That looks correct. If you don't see **Blazor App** anywhere in the VS new project UI, then yes, go ahead and open an engineering issue. If you want to add a "cc: @guardrex" at the bottom, I'll see what they say. There might be a special instruction or troubleshooting step that the doc should cover.

**Comment by joslat** [comment]
went there and checked. It seems that everything comes from an identified issue and there is a workaround...
main issue is here (closed): https://github.com/aspnet/AspNetCore/issues/11706
and the root cause (with hints to the workaround): https://github.com/aspnet/AspNetCore/pull/11707
"We worked with the web tools folks on a resolution and the recommended workaround for this issue is to remove the package GUIDs from the VS host files for these templates. This will cause the localized content in VS to not be used for these templates and instead the strings from the templates will be used. "
Now any hint on how to remove the package GUIDS from the VS host files for the concrete templates? a bit lost there.. ;)

cc @danroth27

Just not to bother @guardrex I will follow the topic on https://github.com/aspnet/AspNetCore/pull/11707
