### ISSUE TITLE
Add docs for gRPC over h2c

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore.Docs#13544]
Our templates default to using gRPC over TLS. On platforms where server-side ALPN is not available (MacOS, Windows < 8.1, Linux distros with OpenSSL < 1.0.2g), our templates will fail to run.

We should add instructions on how fallback to using gRPC over h2C over these platforms.

**Comment by shirhatti** [comment]
Reported in https://github.com/grpc/grpc-dotnet/issues/416

**Comment by Rick-Anderson** [comment]
cc @JunTaoLuo @JamesNK
