### ISSUE TITLE
Using Razor Components in Razor Pages and MVC projects

### ISSUE THREAD

**Issue by smadgerano** [aspnet/AspNetCore.Docs#13546]
The docs say that you can integrate server-side Razor Components with existing Razor Page project, but information is very limited and some elements are missing. It says that components must be wrapped in a div...

&lt;div id="counter"&gt;
    @(await Html.RenderComponentAsync&lt;Web.Components.Counter&gt;(new { }))
&lt;/div&gt;

...but this alone will not work. I found a reference on the page  https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0 that the following script tag needs to be added...

&lt;script src="_framework/blazor.server.js"&gt;&lt;/script&gt;

...which I had to place in my Pages/Shared/_Layout.cshtml and then I also had to add the following into my Startup.cs...

services.AddServerSideBlazor();
endpoints.MapBlazorHub();

This worked, but only for components on the index page, on all other routes and pages the HTML is rendered but the dynamic content does not. The missing part that I could not find documented anywhere is that you also need to place the following in the HEAD tag on your _Layout.cshtml

&lt;base href="~/" /&gt;

After this all server-side dynamic content can be rendered on any page or route of the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Additional from @smadgerano on https://github.com/aspnet/AspNetCore.Docs/issues/15759 pertaining to [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0) ...

> The section in your docs suggest that all you need to do is use "await Html.RenderComponentAsync...." tags.
>
> In reality you also need to add extra using statements into your _Imports.razor file (that are only apparent after going through the downloadable samples), an extra tag into the Head of the page, extra extra endpoints and services in to your Startup.cs (which to be fair I did pick up from other parts of the doc).
>
> I've been using components in this way for the last 6 months in various preview versions, and having to put "extra" using statements in the _Imports.razor file was the last thing I thought of - taken me 2 hours to work this out, could have taken 5 minutes if there was a proper document for this hybrid style of usage rather than a single paragraph that was mixed up in the middle of the other two hosting scenarios.
