### ISSUE TITLE
For my understanding

### ISSUE THREAD

**Issue by WellspringCS** [aspnet/AspNetCore.Docs#13554]
Url.Action(new { category = "admin/products" })…

Shouldn't that be...

Url.Action(new { page = "admin/products" })…

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by WellspringCS** [comment]
less than trivial, but while I'm here: "These are called a catch-all parameters."

Grammar check that one! :)

**Comment by Rick-Anderson** [comment]
`Url.Action(new { category = "admin/products" })` is correct.

**Comment by WellspringCS** [comment]
> `Url.Action(new { category = "admin/products" })` is correct.

Then I'm still confused about something -- my apologies and I'll dig in to see what I'm not understanding.

**Comment by WellspringCS** [comment]
elsewhere in the same page it says...

var link = Url.Action("ReadPost", "Blog", new { id = 17, });

The implication being that the { id } provision fills the expected route parameter id.

Then again later, this...

```
routes.MapRoute(
    name: "blog",
    template: "Blog/{**article}",
    defaults: new { controller = "Blog", action = "ReadArticle" });
```
And text below it talks about extracting article value of  All-About-Routing/Introduction from /Blog/All-About-Routing/Introduction ...

The above examples guiding me, I would have *guessed* that Url.Action(new { page = "admin/products" })…
fulfills a route defined as `/search/{**page}` by providing a value for **page

What am I missing? the word category appears in this document exactly once, where I would have thought `page` is the word I'd see. I don't know what "category" is... ??
