### ISSUE TITLE
Blazor template names out of date

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore.Docs#13557]
The getting started doc shows
`dotnet new blazor -o WebApplication1`

`dotnet new blazorserverside -o WebApplication1`

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio-code

dotnet new shows

```
Blazor Server App                                 blazorserver             [C#]              Web/Blazor
Blazor WebAssembly App                            blazorwasm               [C#]              Web/Blazor/WebAssembly
```

**Comment by guardrex** [comment]
Updates are on https://github.com/aspnet/AspNetCore.Docs/pull/13536 and awaiting review.

The updates are slated for the `release/3.0-preview8` branch for Pre8.

**Comment by mikaelm12** [comment]
Ah, great
