### ISSUE TITLE
Need clarification on Parent/Child component bindings

### ISSUE THREAD

**Issue by JeroMiya** [aspnet/AspNetCore.Docs#13578]
There's a section on data binding showing the `@bind-PropertyName` syntax, along with the `EventCallback<T> PropertyNameChanged` convention, but it doesn't show a complete sample with two-way binding from parent to child and back. Modifying the one-way sample provided to add an `<input @bind=... >` element to the child component, bound to the bindable property resulted in a one-way bind-once binding from parent to child, with data flowing to child once on initial render but not back to the parent when the child value changed. I'm assuming either I did something wrong, or the child component has to explicitly invoke the `PropertyNameChanged` event callback on property change (which incidentally seems like a lot of extra boilerplate for something that should just work with cascading `@binds`), but if so, it's not clear from the current documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JeroMiya ... We're discussing this, specifically with regard to `<input>` value binding across components, on https://github.com/aspnet/AspNetCore.Docs/issues/13539. Thus far, a cascading parameter allows a child to interact with a parent property which is set by a callback (i.e., matches your *seems like a lot of extra boilerplate* remark). I show that approach in the issue. It might be more of a *hack* tho. I'm waiting to hear back from engineering on a better alternative.

I'm going to move your remark here over to that issue, and we'll work it all together.
