### ISSUE TITLE
Let us download code samples.

### ISSUE THREAD

**Issue by JawadJaber** [aspnet/AspNetCore.Docs#13573]
Code samples is effective channel to understand the concepts. I advise you add the samples for all this and other Blazor topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JawadJaber ... The sample app does demo what the topic shows.

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/JSInterop.razor

I'll get the sample app link into the topic. Thanks for calling this out.
