### ISSUE TITLE
Need documentation on custom events 

### ISSUE THREAD

**Issue by harleydk** [aspnet/AspNetCore.Docs#13572]
I hard a hard time finding info on custom events. Did find what I was looking for at https://github.com/aspnet/Blazor/issues/236#issuecomment-372240986, you would perhaps consider incorporating this in this page? 

Thank you for your consideration.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/da-dk/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I like it ... thanks @harleydk. We'll get this scheduled.

**Comment by VR-Architect** [comment]
Not sure this is a custom event or not but I can't figure how to refresh the parent state from a complex child. For example, the child is a collection html controls with local onchange events in the child. But once the child event has fired, it needs to invoke the child component's onchange to send a notification to the parent so it can refresh state.

Parent
    <MyChild onchange="callMeBack">

MyChild
    <input type="text1" onchange="MylocalText1Changed"/>
    <input type="text2" onchange="MylocalText2Changed"/>

When MylocalText1Changed is called, how do we invoke a call back to the parent at the component level?

**Comment by guardrex** [comment]
@VR-Architect We've been discussing that a bit on https://github.com/aspnet/AspNetCore.Docs/issues/13539. Follow along and chat with the devs on that issue for now. I'm still groking the cross-component event binding myself, but I'm hampered a bit by 🏃 *lots of unrelated work* 🏃 at the moment. I hope to be able to spend some time with those concepts within a week and see what can be done on that issue with the docs to clarify things further.

**Comment by VR-Architect** [comment]
Thanks @guardex I think I solved my issue with this request to add an example to this doc to you. I provided an example. Please feel free to use and enhance :)

https://github.com/aspnet/AspNetCore.Docs/issues/13651

**Comment by guardrex** [comment]
Back to the original ask: This seems to be a point-in-time problem when this was opened. Doesn't `EventCallback` cover this?

**Comment by harleydk** [comment]
Probably does. I haven't had time to experiment with Blazor since August, likely won't for some time to come. Might as well close this one up, unless you'd like to keep it open?

**Comment by guardrex** [comment]
Let’s close for now. If the latest docs still pose a problem, open a new issue later using the This Page feedback form/button at the bottom of the topic.
