### ISSUE TITLE
How to display related table in blazor using entity frame work

### ISSUE THREAD

**Issue by novfal** [aspnet/AspNetCore.Docs#13576]
If using the include to join the table table vales are not displaying in blazor view

**Comment by guardrex** [comment]
Hello @novfal ... We only handle documentation issues here. If you think that you found a bug, open an issue with the engineers.

https://github.com/aspnet/AspNetCore/issues

Provide more information than this tho ... show your component code in the issue, and they might ask you to put up a repro project on GitHub for them to pull down and take a look at.
