### ISSUE TITLE
No previously created "Data" folder

### ISSUE THREAD

**Issue by mattielee** [aspnet/AspNetCore.Docs#13586]
There is no previously created "Data" folder. [Add a database context class](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac#add-a-database-context-class)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you also fix the 3.0 version while you're at it?
/cc: @anangaur

**Comment by Rick-Anderson** [comment]
Sometimes the content is in an include that doesn't change between 2.2 and 3.0 - in that case there is only one fix.

**Comment by mattielee** [comment]
Okay, I will look into it.
