### ISSUE TITLE
Project Naming Guidelines

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [aspnet/AspNetCore.Docs#13582]
I am not sure, if there is a documentation already available from Microsoft for this. Watch the below video to understand the issue better.

[Video](https://youtu.be/KM5o9M4cuQA)

**Comment by PradeepSinghMakwana** [comment]
I mean we can have, project structure and naming guidelines. So that it is easier to create and scale projects. I recently faced problems in naming and structuring my own projects.

**Comment by Rick-Anderson** [comment]
@PradeepSinghMakwana can you open that issue in the .NET repo?

**Comment by PradeepSinghMakwana** [comment]
> @PradeepSinghMakwana can you open that issue in the .NET repo?

@Rick-Anderson  Do you mean microsoft/dotnet or aspnet/AspNet. I have opened the issue in both and then closed it in aspnet/AspNet as I think you didn't really mean that.

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/docs

**Comment by Rick-Anderson** [comment]
You'll have to write up exactly what's needed and not cite a video.
