### ISSUE TITLE
Question about disabled keys in Key Vault

### ISSUE THREAD

**Issue by ps-tb** [aspnet/AspNetCore.Docs#13608]
Having the Key Vault provider has turned out to be a great improvement to our apps. I had a question though regarding disabled secrets because the exception they caused was a problem we experienced when first starting. The documentation states the following:
> Disabled and expired secrets throw a KeyVaultClientException. To prevent your app from throwing, replace your app or update the disabled/expired secret.

Can you explain what is meant by "replace your app"? Does it that mean rewrite the app to not use the provider or is there something else that can be done to avoid the exception that is thrown? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes ... it's a blown update that we and engineering didn't catch from ancient times of ASP.NET Core ... **_2017!_** :smile:

Original remark ...

> Disabled and expired secrets throw a `KeyVaultClientException` at runtime. Therefore, it's important that you update your application or replace or update a disabled or expried secret in the key vault before the provider attempts to load or reload a disabled or expired secret.

"update your application" ... 🤔 ... even that's confusing.

I'm going to make it say the following and then we can see if engineering wants to modify it further ...

> Disabled and expired secrets throw a `KeyVaultClientException` at runtime. To prevent your app from throwing, provide the configuration using a different provider or update the disabled or expired secret.

Thanks for opening this @ps-tb.

**Comment by ps-tb** [comment]
@guardrex Ah yes, the dark days of 2017. Glad to help.
