### ISSUE TITLE
Error if using the "copy" function for the code under heading "Add validation rules to the movie model"

### ISSUE THREAD

**Issue by WinterDragon76** [aspnet/AspNetCore.Docs#13612]
public int ID { get; set; }

should be 

public int Id { get; set; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We consistently use upper case `ID`
