### ISSUE TITLE
Links to UIEventArgs are broken

### ISSUE THREAD

**Issue by Lurs** [aspnet/AspNetCore.Docs#13613]
On https://docs.microsoft.com/de-de/aspnet/core/blazor/components?view=aspnetcore-3.0 both links to [UIEventArgs](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/UIEventArgs.cs) are broken. Maybe the file was moved?

---
#### Dokumentdetails

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/de-de/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the heads-up @Lurs ... *Yes!* ... there have been updates just within the last few days ...

https://github.com/aspnet/AspNetCore/pull/12660

I'll get this sorted out today. Thanks again.

**Comment by guardrex** [comment]
@scottaddie Note that the `Blazor` label seems to have had a regression. This is I think the 2nd or 3rd issue that I've seen without any labels added.

**Comment by guardrex** [comment]
Nevermind @scottaddie ... I think this happened merely because the issues in question were opened from the non en-US docs pages.
