### ISSUE TITLE
Indicate minimum versions

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore.Docs#13614]
It would be much more useful to document the _minimum_ required versions. In locked-down corporate environments, it's pretty common to be stranded on older versions until gatekeepers decide to push an upgrade. I've seen some places running versions that are as much as full a year behind. "Current" doesn't tell us anything more than a list of checkmarks would. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MV10 ... AFAIK, this is only because Blazor is in preview. I'll tag this for RTM, and we'll get firm versions there for 3.0 RTM.

**Comment by guardrex** [comment]
@danroth27 The ask is for ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms

The topic states "Current" for versions of browsers that Blazor supports. Can we say explicitly what version for each of these we support?

**Comment by guardrex** [comment]
@MV10 ... see #14842 for discussion on this one. We're going to leave it at "Current."

**Comment by MV10** [comment]
@guardrex thanks for the follow-up. Disappointing. Does "Current" mean Microsoft is committed to automatically guaranteeing full-support the moment a new browser version drops? The decision makes zero sense to me, the page is pretty much worthless this way. Oh well.

**Comment by guardrex** [comment]
> guaranteeing full-support the moment a new browser version drops?

Yes ... in the sense that if you hit a 🐞 with a new browser release, they *should*&dagger; assist/advise/fix/workaround the scenario.

&dagger;I'm a contractor, so I can't speak for MS directly. This is my assessment based on their remarks.

**Comment by danroth27** [comment]
> Does "Current" mean Microsoft is committed to automatically guaranteeing full-support the moment a new browser version drops?

Yes. If you come to us with a bug that only happens in the latest version of one of these browsers then we will support you. If you ask for support for an issue that is specific to an older browser version we will still consider the impact, but we will likely ask you to update your browser.
