### ISSUE TITLE
[Preview 9] Update EventArgs

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13618]
React to https://github.com/aspnet/AspNetCore/pull/12660.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mv10-work** [comment]
I assume this is why the link "EventArgs classes in the reference source" now 404s?

**Comment by guardrex** [comment]
@mv10-work Just a month ago I fixed that on https://github.com/aspnet/AspNetCore.Docs/pull/13617 ... you can see how long that lasted! :smile: I'll update the link again now. Thanks for letting me know.
