### ISSUE TITLE
Blazor Server App Short Name Changed in 3.0.0-preview7.19365.7

### ISSUE THREAD

**Issue by Just2Sour** [aspnet/AspNetCore.Docs#13610]
Getting Started step #3 uses the command dotnet new blazorserverside -o WebApplication1 for .NET Core CLI; however, the short name in this preview version is blazorserver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Just2Sour ... That will be for Pre8. We have it on https://github.com/aspnet/AspNetCore.Docs/pull/13536.
