### ISSUE TITLE
Add DOM events to Event Arg Types table

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13619]
From https://github.com/aspnet/AspNetCore/issues/5521#issuecomment-486321803 ...

> onkeydown and onkeyup don't actually provide the value, so the behavior described is expected. ... We should document this better. 

Cross-ref to the original work that was done by engineering to address that issue: https://github.com/aspnet/AspNetCore.Docs/pull/11152

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by honkmother** [comment]
I would have saved an hour of headbanging if the onkeyup event said "HEY YOU MIGHT WANT TO CHECK OUT oninput INSTEAD".

**Comment by guardrex** [comment]
@danroth27 @mkArtakMSFT 

**FYI:** I'm running down the Blazor.Docs triage issues today (Thursday). These 46 issues generally fall into these categories:

* Not sure if the issue should be worked at all (some may require transfer to engineering). If we are to work the issue, it requires a priority. Add the label, and I'll take care of moving it to the correct Blazor.Docs column, or just drag the issue to the correct priority column ... I'll fix the labels.
* The issue requires engineering guidance to proceed, possibly as far as supplying content (I'll use the new PU content label if that's the case). Typically, they also require a priority assignment.

I'll add notes/questions to them today. I won't ping u on these as I go. My goal is just to call out what each issue requires from you.

**This specific issue**, which doesn't require PU content, requires guidance ...

Devs aren't (apparently) picking up on which C# event class to use with which DOM event. It's obvious when the connection is made between `onkeyup`/`onkeydown` and `KeyboardEventArgs` that one isn't going to get an element "value" out of that other than something about keys ... i.e. ... **_the key is "the value" in this scenario._**

```cshtml
<p>
    <input @onkeyup="@WhatKey" placeholder="Show me the keys!" />
</p>

<p>
    @_keyMessage
</p>

@code {
    private string _keyMessage = string.Empty;

    private void WhatKey(KeyboardEventArgs e)
    {
        _keyMessage = $"The key up key is '{e.Key}'.";
    }
}
```

Options:

* Add a column to our table at https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-argument-types with the applicable DOM events.
* Do nothing (close the issue) ... go forward assuming it's somewhat obvious from the C# class names.

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex.
Let's go with option No: 1 above:
> Add a column to our table at https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-argument-types with the applicable DOM events.

**Comment by guardrex** [comment]
Will do. :+1:
