### ISSUE TITLE
'ID/Id' identifier name inconsistent in tutorial.

### ISSUE THREAD

**Issue by alexsaalberg049** [aspnet/AspNetCore.Docs#13624]
The rest of this tutorial (starting [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visual-studio)) uses `Id` for the 'Id' of `Movie.cs`

This page of the tutorial uses `ID` instead.

I copy-pasted the new `Movie` class in order to add the validation rules and it resulted in build errors due to the `Id` being referenced in other parts of the application.

I believe it would make sense to change `ID` to `Id` on this page. (As I did manually in my own project)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in #13612
