### ISSUE TITLE
CheckChanged event example

### ISSUE THREAD

**Issue by jetedrow** [aspnet/AspNetCore.Docs#13623]
The example provided is syntactically incorrect:
&lt;input type="checkbox" class="form-check-input" @onchange="CheckboxChanged" /&gt;
@code {
    private void CheckChanged()
 ...
The method CheckboxChanged is being called, however the @code section calls this CheckChanged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @jetedrow ... we missed a spot on the Pre7 update. I'll take care of that right now.
