### ISSUE TITLE
No selection code is incorrect

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13625]
[No selection](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.2&branch=pr-en-us-13615#no-selection)
Complete with sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.2&branch=pr-en-us-13615)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson What needs doing here? I see a merged PR but no real information about what's still left to do.

**Comment by Rick-Anderson** [comment]
@serpent5  looks like it's showing code for `<option value="">--none--</option>`
