### ISSUE TITLE
What about Singleton per client/session

### ISSUE THREAD

**Issue by PerseusTheGreat** [aspnet/AspNetCore.Docs#13633]
How can devs implement Singleton object per client or session.
Is there any registration method or technic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#lifetime-and-registration-options)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @PerseusTheGreat ... For the default container, you only get the lifetime options that you see in the topic: transient, scoped, and singleton (whole app instance). You might be able to get per-client/per-session using a 3rd party container. You can discuss this further with the engineers on the engineering repo ... for example if you would like to make a feature request.

https://github.com/aspnet/AspNetCore/issues
