### ISSUE TITLE
Razor Page Test Sample Missing

### ISSUE THREAD

**Issue by ryanmajidi** [aspnet/AspNetCore.Docs#13631]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1788) by @kylejrp** 

Hey there,

The samples announcement article mentioned to create an issue for any missing samples. It looks like the Razor Pages samples are missing, or at least I can't search for them.

Link to article:
Here's an example article that references the samples src/RazorPagesTestSample and tests/RazorPagesTestSample.Tests:
https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2

Problem:
I don't seem to be able to find these samples:
https://docs.microsoft.com/en-us/samples/browse/?term=razor%20pages

I would expect that there would be more samples for Razor Pages, so it's strange that there's no results.

**Comment by Rick-Anderson** [comment]
We don't have ASP.NET Core samples in the new samples repo.

cc @tdykstra @scottaddie

**Comment by Rick-Anderson** [comment]
Use the following query for ASP.NET Core samples
https://docs.microsoft.com/en-us/samples/browse/?products=aspnet-core
