### ISSUE TITLE
Binding with Parent-Child not working per this doc

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore.Docs#13634]
Getting an error on this code above. Did something change in the last preview release?:

The attribute names could not be inferred from bind attribute 'bind-Year'. Bind attributes should be of the form 'bind' or 'bind-value' along with their corresponding optional parameters like 'bind-value:event', 'bind:format' etc.		
    
[Parameter]
    private int ParentYear { get; set; } = 1978;

    private void ChangeTheYear()
    {
        ParentYear = 1986;
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It should work. Check your component naming (casing in particular) :point_right: https://github.com/aspnet/AspNetCore/issues/9786

**Comment by guardrex** [comment]
Wait ... hold on a sec. I was reminded of that error when the naming is wrong.

**Comment by guardrex** [comment]
Yeah ... so what's often happening when the name of the child component **_is correct_**, is that the child component (as that issue calls out) **_just isn't found_**. Place your child component in the *Pages* folder to have it discovered .... or put non-page components in one of the *Shared* folders. If you need to make a component available in the app from someplace else, then you must add an explicit `@using` to bring it in where it will be used. We have this covered in the following section :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#component-classes

**Comment by VR-Architect** [comment]
The issue was my file name was Test1 and I forgot to change the component name on the parent; however, I would have expected VS to catch this as an error during build. Code in document works fine. My bad.

**Comment by VR-Architect** [comment]
^ my "child" file name was Test1

**Comment by guardrex** [comment]
No worries. Yes, indeed ... engineering has already made some improvements that will help: Coming up for Pre8, a warning is generated if an element in the markup starts with an uppercase letter but the name doesn't match the name of a component in the app. We have that doc update on the staging branch, so the text will go live when Pre8 releases.

**Comment by Legends** [comment]
@guardrex

Don't want to open a new thread, but... having this event callback property in the `ChildComponent.razor` is somewhat not intuitive:

` [Parameter]
    public EventCallback<int> YearChanged { get; set; }`

Because it's not used directly anywhere, only under the hood.
IMO this should be made differently.

**Comment by Legends** [comment]
It's sitting in the ChildComponent like a lost dog...

**Comment by guardrex** [comment]
It's one of those "by-convention" things, but that's really a product feedback issue ... we can't address that from the docs team. We just write about the bits.

Open product feedback on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues

**Comment by Legends** [comment]
Yes, I know, sorry for bothering you here.

**Comment by guardrex** [comment]
No worries. Not too busy ... just working up some Blazor security content.
