### ISSUE TITLE
Provide complete Startup filter sample

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13637]
ASP.NET Core 3.0 only.
Provide the complete project for [Extend Startup with startup filters](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#extend-startup-with-startup-filters)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 can you provide this sample? You can use MVC or RP.

**Comment by Rick-Anderson** [comment]
```
public class Program
{

    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
           .ConfigureAppConfiguration((hostingContext, config) =>
           {
           })
        .ConfigureServices(services =>
        {
            services.AddTransient<IStartupFilter,
                      RequestSetOptionsStartupFilter>();

        });
}
```

**Comment by Rick-Anderson** [comment]
@serpent5 I got it working. I'll have you review the code.

**Comment by serpent5** [comment]
The referenced section is in a different topic to the one this was opened against. Is that intentional? A startup filter is a different concept to an MVC filter, even though "filter" is used in both cases. You could use a startup filter without using MVC, for example.

**Comment by serpent5** [comment]
Hmm, your latest comment popped up after I just posted mine. I’ll be glad to help with reviewing.

**Comment by Legends** [comment]
Is the sample code still valid? It uses .net core 1.0
