### ISSUE TITLE
There is no way of detaching a callback from HubConnection.onclose

### ISSUE THREAD

**Issue by kirill-chilingarashvili** [aspnet/AspNetCore.Docs#13630]
# Issue description

There is no way of detaching a callback from connection.onclose(callback)
I believe there should be a method connection.offclose(callback) allowing to detach a callback from this event, otherwise there is no way of disposing a connection (it will hold a reference to a callback)

**Comment by guardrex** [comment]
Hello @kirill-chilingarashvili ... Would you mind re-opening this issue from the **This Page** feedback button at the bottom of the topic where it applies. Several authors are involved in that area of the docs, and the system will ping the correct author if you open the issue that way.
