### ISSUE TITLE
Entity Framework Core Tools for the .NET CLI installation

### ISSUE THREAD

**Issue by Enver-Yilmaz** [aspnet/AspNetCore.Docs#13649]
The tutorial assumes Entity Framework Core Tools for the .NET CLI is already installed. If it is not then installation command is;
 dotnet tool install --global dotnet-ef --version 3.0.0-*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Enver-Yilmaz  thanks again!
