### ISSUE TITLE
Cannot Modify Styling of Account Pages

### ISSUE THREAD

**Issue by MarkMurphy37** [aspnet/AspNetCore.Docs#13655]
Given the following boilerplate: dotnet new react -o &lt;output_directory_name&gt; -au Individual

Is there a way to modify the styling of the account pages? (such as login or register)
For example: https://localhost:5001/Identity/Account/Register?returnUrl=/authentication/login

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#authenticate-api-requests-react)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
You can follow the steps in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio to modify the look and feel of the included Identity UI

**Comment by guardrex** [comment]
Hi @MarkMurphy37 ... Looks like your question has been answered. I'll close now.

**Comment by mmurphyalo** [comment]
Thanks! I'll give this a shot. For reference, I'm running .net core 3.0 preview with React SPA auth. May be worth including a link on this page: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0 because it's not apparent after spinning up the project that you can alter those pages.

**Comment by MarkMurphy37** [comment]
Thanks! I'll give this a shot. For reference, I'm running .net core 3.0 preview with React SPA auth. 

It may be worth including a link on this page: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0 because it's not apparent after spinning up the project that you can alter those pages.

**Comment by guardrex** [comment]
Yes, great idea. I'll do that right now.
