### ISSUE TITLE
Identity vs IdentityServer

### ISSUE THREAD

**Issue by JimbobTheSailor** [aspnet/AspNetCore.Docs#13659]
What makes the page, and many pages on this Authentication subject really difficult to understand (for a newcomer) is the terms 'Identity' ' Microsoft Identity' and 'IdentityServer'.  These three seemingly similar terms refer to three profoundly different things. It is taken me a week of heavy reading to grasp all this for the first time. A new paged just describing these terms, what they are, their relationship would be very helpful. They are just used everwhere without first establishing their complete meaning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
See [this SO answer](https://stackoverflow.com/a/48367152/502537) to your question. That info should probably be in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity

**Comment by Rick-Anderson** [comment]
MOVED to #13697
