### ISSUE TITLE
Method UseCors() has invalid position

### ISSUE THREAD

**Issue by filipbekic01** [aspnet/AspNetCore.Docs#13660]
If you put UseCors() method after UseAuthentication() and UseAuthorization(), everytime auth fails, CORS error will appear in browser too because web app never when through UseCors() method. I think UseCors() method should be called first. Correct me if i'm wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @filipbekic01 .... *Yes* ... you are correct. CORS Middleware must be placed before any middleware that uses CORS. I'll move it up a line. Thanks for pinging us on it.
