### ISSUE TITLE
HttpRepl against Azure 

### ISSUE THREAD

**Issue by zivraf** [aspnet/AspNetCore.Docs#13678]
It would be great if you could add a section for using HttpRepl with Azure management endpoint (covering authN) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16842b60-b268-a322-8078-c0b27c57fa7d
* Version Independent ID: d63c12f3-220e-9067-ead5-90e644c06591
* Content: [Test web APIs with the HTTP REPL](https://docs.microsoft.com/en-us/aspnet/core/web-api/http-repl?tabs=windows&view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/http-repl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/http-repl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by dkmiller** [comment]
Seconding this! Not just Azure management, but any endpoint requiring authentication via bearer token.

**Comment by scottaddie** [comment]
This is an unsupported scenario today. I recommend opening an issue in the [aspnet/HttpRepl](https://github.com/dotnet/HttpRepl) repo for the feature request.
