### ISSUE TITLE
Clarify async use in gRPC services with C# page

### ISSUE THREAD

**Issue by Kryptos-FR** [aspnet/AspNetCore.Docs#13680]
I believe the description and the code samples are confusing. In the text, the remote method is referred as `SayHello` but the code sample uses `SayHelloAsync`.

According to https://grpc.io/docs/tutorials/basic/csharp/#calling-service-methods, the generator is smart and does generate both a sync `SayHello` and an async `SayHelloAsync` versions.

That said, for a first reader (like myself) that hasn't use gRPC yet, it was slightly confusing and I couldn't determine if it was a typo or not. At least not before double-checking with the official tutorial.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7223e694-85ba-4b95-96c8-68ae14753e7c
* Version Independent ID: 28ec8399-ba0e-c995-3ac2-b1f28e93331b
* Content: [gRPC services with C#](https://docs.microsoft.com/en-gb/aspnet/core/grpc/basics?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/basics.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/basics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JamesNK** [comment]
Fixed here - https://github.com/aspnet/AspNetCore.Docs/pull/13699

Expanded docs on using the gRPC client is coming soon that discusses the difference between the async and block methods. In-progress PR here https://github.com/aspnet/AspNetCore.Docs/pull/13684

**Comment by Kryptos-FR** [comment]
Thanks for the quick and for the update. I'll follow the progress of that PR.
