### ISSUE TITLE
AddSingleton link points to incorrect article

### ISSUE THREAD

**Issue by MarkSFrancis** [aspnet/AspNetCore.Docs#13683]
The article's `AddSingleton` link (within https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#service-lifetimes) points to: 
https://docs.microsoft.com/dotnet/api/microsoft.aspnet.odata.builder.odatamodelbuilder.addsingleton
But it should point to:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#service-lifetimes)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... it looks like a cut-'n-paste error from a tool that we use to get the API links. I'll fix that right now.
