### ISSUE TITLE
Up method in the Migrations/<time-stamp>_InitialCreate.cs

### ISSUE THREAD

**Issue by arseyam** [aspnet/AspNetCore.Docs#13686]
Maybe it's not an issue or it's least priority but when I came to the section where it says there's an Up method in the Migrations/<time-stamp>_InitialCreate.cs I found that the file created in my project Migrations folder has the suffix name **_Initial.cs** not **_InitialCreate.cs** so I thought of reporting it for consistency although maybe I'm having an issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@arseyam  it's worth reporting. See my PR changes https://github.com/aspnet/AspNetCore.Docs/pull/13687/files

**Comment by Rick-Anderson** [comment]
@arseyam thanks for bringing this to our attention.
