### ISSUE TITLE
No mention of GrpcClient class

### ISSUE THREAD

**Issue by cristicatalan** [aspnet/AspNetCore.Docs#13681]
The code snippet for the client uses the GrpcClient type:
`var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);`<br/>
`GrpcClient` is not available by referencing the package in the client project via `<PackageReference Include="Grpc.Tools" Version="1.22.0-pre1" PrivateAssets="All" />`.<br/>
This page makes no reference to it, and there is no link to a sample application, so can't create a building project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7223e694-85ba-4b95-96c8-68ae14753e7c
* Version Independent ID: 28ec8399-ba0e-c995-3ac2-b1f28e93331b
* Content: [gRPC services with C#](https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/basics.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/basics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
Into states
This document outlines the concepts needed to write gRPC apps in C#.
This is not meant to be a code tutorial. See the **Additional resources** at the end, which point to the tutorial this references.

Create a .NET Core gRPC client and server in ASP.NET Core

**Comment by cristicatalan** [comment]
I thought this page documents  how to use gRPC in C# for project types other than ASP.NET. Thanks for the clarification. Indeed `GrpcTools` package can be used with .NET Core versions before 3.0.0.
