### ISSUE TITLE
Creating a Custom View Engine

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#137]
ASP.NET MVC -> Views -> Creating a Custom View Engine

[Edit Tom Dykstra] [commit with deleted article stub](https://github.com/aspnet/Docs/commit/e4940fb39e40b4af7973e0709c004c6a6cc62f21)

**Comment by rroyter** [comment]
I would like to know if there are any drafts on the topic. Anyone I can talk to?

**Comment by danroth27** [comment]
No drafts available yet. This item is still on our backlog. Updated accordingly.

**Comment by auzmartist** [comment]
Any update here? Our team has just run up against a (not-urgent) desire to do this but would like to wait for some documentation before proceeding.

**Comment by danroth27** [comment]
@auzmartist Can you tell us more about your scenario? Maybe there is an easier way to accomplish what you want to do.

**Comment by forsyth** [comment]
I've implemented a special template language, completely distinct from Razor, which was working happily in the custom ViewEngine environment in old System.Web.Mvc at 5.2.3.0. It added an instance of my ViewEngine (derived from IViewEngine) to the system using

ViewEngines.Engines.Clear(); ViewEngines.Engines.Add(new MyViewEngine(stuff)));

MyViewEngine derives directly from IViewEngine and shares nothing with Razor.

Having converted the application across to ASP.NET Core, sitting for compatibility reasons on Net.Framework 4.6.1, using Microsoft.AspNetCore.Mvc (v1.1.0-preview1-final), and having spent some time following the apparent method used by Razor to configure RazorViewEngine, I cannot get the custom engine configured (ie, added into the MvcViewOptions.ViewEngines list).

One problem with a Dependency Injection approach to nearly everything is that if nothing happens, it's not easy to work out what's missing. Is there a straightforward way to trace it?

**Comment by forsyth** [comment]
Perhaps a more specific question might help me.

I looked to see where the Razor engine was added. As far as I could tell, the only non-testing instance was in https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/MvcRazorMvcViewOptionsSetup.cs 
and then in MvcRazorMvcCoreBuilderExtensions.cs AddRazorViewEngineServices has

            services.TryAddEnumerable(
                ServiceDescriptor.Transient<IConfigureOptions<MvcViewOptions>, MvcRazorMvcViewOptionsSetup>());

and a bit later
            services.TryAddSingleton<IRazorViewEngine, RazorViewEngine>();

and all that seems to that put the Razor engine into the view engine list.

Sadly, doing something similar in my app's Startup.cs, but with my view engine's class type used instead (still derived from IViewEngine), doesn't seem to work. My equivalent of MvcRazorMvcViewOptionsSetup is never invoked.
Something else is obviously needed, but what? What am I missing?
Have I completely misunderstood how the linkage works?

**Comment by auzmartist** [comment]
@danroth27 I have a situation where I'd like to share a common template (defined in the _Layout.cshtml file) across all my pages except for one MVC route which would be composed within a different template file - _Layout2.cshtml for example. It would be possible to have a single template and then conditionally include partials to produce different html responses based on request url. This seems like it could grow messy. At first glance, a custom view engine seemed a bit more maintainable.

**Comment by scottaddie** [comment]
@NTaylorMullen Any thoughts on an initial outline for this doc?

@dpaquette Are you interested in writing this doc? I know you worked with @NTaylorMullen to create [Pugzor](https://davepaquette.com/archive/2016/11/22/creating-a-new-view-engine-in-asp-net-core.aspx).

**Comment by danroth27** [comment]
> I have a situation where I'd like to share a common template (defined in the _Layout.cshtml file) across all my pages except for one MVC route which would be composed within a different template file - _Layout2.cshtml for example.

Would it be easier to have a specific folder hierarchy with a different _ViewStart.cshtml that specifies the alternative layout?

**Comment by dpaquette** [comment]
@scottaddie I would like to help but I don't have many spare cycles at the moment.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Any thoughts on an initial outline for this doc?

@pranavkm would be a better SME for this article 😄. He's responsible for many of the ViewEngine related features MVC offers.

**Comment by forsyth** [comment]
I'd forgotten about this thread until it became active again recently. As a follow-up to my messages posted above almost a year ago, I should note that a month or two later my Custom ViewEngine started working with no change on my side, so whatever was stopping it had gone. It works very well.

**Comment by scottaddie** [comment]
@dpaquette No problem. We'll request your review upon completion of the doc.

**Comment by dpaquette** [comment]
@scottaddie Sounds good. I am happy to review

**Comment by Rick-Anderson** [comment]
@forsyth can we point to your view engine?

**Comment by Rick-Anderson** [comment]
@pranavkm  @danroth27  closing given we'll never have the cycles to write this.

**Comment by forsyth** [comment]
sorry, I forgot to reply. Unfortunately the view engine I wrote was done as part of a contract for someone else, so it's not mine to make visible.

**Comment by Rick-Anderson** [comment]
@forsyth  thanks for the response. Can you share general reasons they needed a custom view engine?

**Comment by forsyth** [comment]
It's a radically different language: it has two levels. There is an applicative level that defines or generates trees with rules of the form
Top = Head(head_title); AppleTouch; Meta; Analytics(ua_code, gtm_code); attached("stylesheets");
	Body;
		Tagstuff(gtm_code);
		header.template@(header...),
		Main("homepage-main", Content(content));
		footer.template@(footer...),
		attached("scripts");
	End

Content(list) = {l: list -> l.template@(l...)}   # for each l in list, apply the tree function named by l.template to the components of l as named parameters.

where the result of evaluating "Top" would be a tree of string template applications. There's a library of components, and a level of indirection (eg, l.template@ above). The notation is more compact than Razor, and strictly separates the business logic from the presentation (similar to the argument in a StringTemplate paper). There are no mutable values. Values come either from JSON or a database.

The templates are a simple string substitution in the style of StringTemplate (but these templates are not recursive, all the recursion is done in the tree notation). For example:

out Head(title) = <<
<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<meta charset="utf-8" />
		<title>
			$title
		</title>
>>

out Body = <<
	</head>
	<body>
>>

out Main(class, ...) = <<
	<main role="main" id="main" class="$class">
		$...
	</main>
>>

out End = "</body>\n</html>\n"

**Comment by forsyth** [comment]
I'm not sure why I did a whole View Engine for it at the time, instead of just producing the HTML as a string, and handing that to the ASP.NET stack to send out.
