### ISSUE TITLE
RazorPagesMovieContext created manually and through scaffolding?

### ISSUE THREAD

**Issue by j0057** [aspnet/AspNetCore.Docs#13709]
In the 'Add a data model' section (#add-a-database-context-class), the class RazorPagesMovieContext is added manually.

In the 'Scaffold the movie model' section, it says that the RazorPagesMovieContext is added, which is only true if it didn't yet exist, which it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#scaffold-the-movie-model-1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Version 2.2 - with VSC tab. Fix for 3.0
