### ISSUE TITLE
Calling UseAuthorization gives rise to InvalidOperationException. Considerably more details are needed in this article.

### ISSUE THREAD

**Issue by Dave-Lowndes** [aspnet/AspNetCore.Docs#13705]
An exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Authorization.Policy.dll but was not handled in user code
Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddAuthorization' inside the call to 'ConfigureServices(...)' in the application startup code.

This article fails to mention using AddAuthorization, but even adding the simple call to that only leads to another exception:

System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider' while attempting to activate 'Microsoft.AspNetCore.Authentication.AuthenticationMiddleware'.

So presumably there's more information needed in this article?
If the reference in the article to  "JWT Bearer middleware" is the missing link, it's far from illuminating to the uninitiated.
I see in the linked code that it does use JWT Bearer - presumably this is the Microsoft.AspNetCore.Authentication.JwtBearer NuGet package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 363b40bb-4e20-e4b3-4456-5eb8fe6b30fb
* Version Independent ID: 8a7e85b0-5c1c-969d-9748-5e5e2dc45cce
* Content: [Authentication and authorization in gRPC for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by darshana2000** [comment]
I got the same issue. I think error message is misleading.
