### ISSUE TITLE
Incorporation of CREATE and PUT methods

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#13700]
Hi team, 
I'm moving this from here: https://github.com/aspnet/AspNetCore.Docs.es-es/issues/36
the contributor is making a suggestion on the original documentation

@vpj-mati commented 3 hours ago

In the example on the page it shows that to create a CREATE method we need the following method
[HttpPost]
public async Task &lt;ActionResult &lt;TodoItem&gt;&gt; PostTodoItem (TodoItem item)

But in my case when trying to execute the item parameter it always came in with null data. The problem is solved by adding the [FromBody] attribute as a copy below.
[HttpPost]
public async Task &lt;ActionResult &lt;TodoItem&gt;&gt; PostTodoItem ([FromBody] TodoItem item)

The same happened with the example of the PUT method
[HttpPut ("{id}")]
public async Task &lt;IActionResult&gt; PutTodoItem (long id, [FromBody] TodoItem item)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#add-a-create-method)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@vpj-mati  ` [FromBody]` is not required in ASP.NET Core 2.1 and later. This tutorial assumes 2.2 or later.
