### ISSUE TITLE
EditForm InputSelect does not binding with Model int property

### ISSUE THREAD

**Issue by hTopology** [aspnet/AspNetCore.Docs#13713]
I try to bind EditForm InputSelect with model int property but the binding does not work.

**Comment by guardrex** [comment]
Hello @hTopology ... that's possibly/probably a product unit issue (at least at this point). Open with the product unit here :point_right: https://github.com/aspnet/AspNetCore/issues, but you'll need to supply more info. They'll need to know what version you're using, code example of what you're doing, and possibly a GitHub repro project. If you find something inaccurate in the doc or something new to cover, ping me here, and I'll re-open this issue.

Also note for the future, please use the **This Page** feedback button at the bottom of any topic. It tags your issue with metadata that helps us work the issue.
