### ISSUE TITLE
[Preview 9] Confirm/update prerendering disable remark

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13719]
Line 216 ... Confirm/update for Preview 9 ...

> To disable prerendering, open the *Pages/_Host.cshtml* file and remove the call to `Html.RenderComponentAsync`.

https://github.com/aspnet/AspNetCore.Docs/pull/13364#discussion_r310330025

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 You said regarding this remark :point_up: ...

> This text will likely need to be modified for Preview 8 / 9.

Do I need to react for Pre8, or should I mark this issue for Pre9?

**Comment by danroth27** [comment]
Probably best to just wait for Preview 9 on this one.

**Comment by guardrex** [comment]
@SteveSandersonMS 

For the remark in the state management topic ...

> To disable prerendering, open the Pages/_Host.cshtml file and remove the call to Html.RenderComponentAsync.

Does this guidance change for Pre9? If yes, how can I change the remark? If no, I can close this issue.

**Comment by guardrex** [comment]
The full text is ...

> To disable prerendering:
> 
> 1. Open the *Pages/_Host.cshtml* file and remove the call to `Html.RenderComponentAsync`.
> 1. Open the `Startup.cs` file and replace the call to `endpoints.MapBlazorHub()` with `endpoints.MapBlazorHub<App>("app")`. `App` is the type of the root component. `"app"` is a CSS selector specifying the location for the root component.

According to another issue, overloads of `MapBlazorHub` are removed. What's the full replacement instruction for Pre9 to disable prerendering?

**Comment by guardrex** [comment]
```cshtml
<app>
    @(await Html.RenderComponentAsync<App>(RenderMode.Server))
</app>
```

**Comment by danroth27** [comment]
@guardrex Close?

**Comment by guardrex** [comment]
I think these auto-close when the staging branch goes to master.

**Comment by guardrex** [comment]
Scott said he'll be merging staging to master shortly ... and then master to live immediately thereafter.

**Comment by guardrex** [comment]
@danroth27 😮 The issues *didn't close* auto-magically. IMO, it's a fault in GH philosophy. If a PR "fixes" an issue on a branch merged to `master`, imo it should close the issue when the changes reach `master`. Anywho ... I'm closing them manually now.
