### ISSUE TITLE
UseInMemoryDatabase

### ISSUE THREAD

**Issue by Genysis78** [aspnet/AspNetCore.Docs#13718]
The tutorial isn't clear that unless you use 'using Microsoft.EntityFrameworkCore.InMemory;' the UseInMemoryDatabase is red and scaffolding fails. Whilst fixing the issue was a great learning point to hunt around for a solution it might put some people off using the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I take it you're using ASP.NET Core Preview 7.
`using Microsoft.EntityFrameworkCore.InMemory;` is not required.

**Comment by psijkof** [comment]
I am seeing the same error in prev. 8 and no way to resolve?!

**Comment by psijkof** [comment]
Found that you need to add another NuGet package:
Microsoft.EntityFrameworkCore.InMemory

**Comment by Rick-Anderson** [comment]
@psijkof  you missed the step where you're supposed to add `Microsoft.EntityFrameworkCore.InMemory`
