### ISSUE TITLE
Is this really good way to deal with localization?

### ISSUE THREAD

**Issue by voloda** [aspnet/AspNetCore.Docs#13717]
To me this whole thing seems to be step back.

Using the original approach had several benefits - having strong typed manager give's you sanity check. Also it forces you to maintain single source of truth if you want to have something translated.

Having this approach used on project running several years will lead to huge mess in .resx files - obsolete messages, missing messages since somebody forgot to add it to 10 .resx files etc.

Another thing is that the .NET Core itself seems to be rather using original approach too + custom build task to generate .xliff files for translators. 

Is this still recommended way or the shift towards the .xliff and step back to TranslationManager is the better way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is the recommended approach.
