### ISSUE TITLE
How to log automatic 400 responses on model validation errors with model/request data

### ISSUE THREAD

**Issue by MontyGvMC** [aspnet/AspNetCore.Docs#13720]
**Help us make content visible**

- Tell us what docs you found that didn't address your concern.

I came accross the issue [How to log automatic 400 responses on model validation errors](https://github.com/aspnet/AspNetCore.Docs/issues/12157). Unfortunatly it is already closed and I can not post this there. One of the comments on [StackOverflow ](https://stackoverflow.com/questions/57390378/net-core-access-request-data-on-bad-request-when-apicontroller-shortcuts-the-p/57406286?noredirect=1#comment101307160_57406286 )pointed me here.

The issue describes how to do the logging of the model state when [ApiController] automatically returns the Bad Request result.

**Describe the new topic**

Now this is some addition to the problem because the original problem was just focusing on the logging of the model state but not the data causing the invalid model state.

- Explain why this topic is needed.

Sometimes there is also the need to log the model bound data (or the plain request data) in addition to the model state. This is of interest during early development when server and client are not stable. Then the client developer can start arguing with the server developer that the data sent was correct and the Bad Request is a bug.
So the only thing to figure out the source of the bad request is to provide logs with the data received and/or the data being bound.

So how could we access the request data when utilizing the InvalidModelStateResponseFactory apporach?

For me there seems to be no possibility to access the model bound data anywhere.

In the [Scenario2 directory of this repository](https://github.com/MontyGvMC/dot-net-core-logging-demo-api) I created a place for my own approaches. If someone needs a download and start project for testing.

- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

I have no suggestions for this.

**Comment by Rick-Anderson** [comment]
[How to log automatic 400 responses on model validation errors](https://github.com/aspnet/AspNetCore.Docs/issues/12157) is not logged, you can add that information there.

Unfortunately we don't have the resources to write this article.

**Comment by idbates** [comment]
> **Help us make content visible**
> 
> * Tell us what docs you found that didn't address your concern.
> 
> I came accross the issue [How to log automatic 400 responses on model validation errors](https://github.com/aspnet/AspNetCore.Docs/issues/12157). Unfortunatly it is already closed and I can not post this there. One of the comments on [StackOverflow ](https://stackoverflow.com/questions/57390378/net-core-access-request-data-on-bad-request-when-apicontroller-shortcuts-the-p/57406286?noredirect=1#comment101307160_57406286)pointed me here.
> 
> The issue describes how to do the logging of the model state when [ApiController] automatically returns the Bad Request result.
> 
> **Describe the new topic**
> 
> Now this is some addition to the problem because the original problem was just focusing on the logging of the model state but not the data causing the invalid model state.
> 
> * Explain why this topic is needed.
> 
> Sometimes there is also the need to log the model bound data (or the plain request data) in addition to the model state. This is of interest during early development when server and client are not stable. Then the client developer can start arguing with the server developer that the data sent was correct and the Bad Request is a bug.
> So the only thing to figure out the source of the bad request is to provide logs with the data received and/or the data being bound.
> 
> So how could we access the request data when utilizing the InvalidModelStateResponseFactory apporach?
> 
> For me there seems to be no possibility to access the model bound data anywhere.
> 
> In the [Scenario2 directory of this repository](https://github.com/MontyGvMC/dot-net-core-logging-demo-api) I created a place for my own approaches. If someone needs a download and start project for testing.
> 
> * Suggest a location in the Table of Contents.
> * Write an abstract. In one **short** paragraph, describe what this topic will cover.
> * Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
> 
> I have no suggestions for this.

I can access the bound data here:

options.InvalidModelStateResponseFactory = context =>
                {
                    // Get an instance of ILogger (see below) and log accordingly.
                    var loggerFactory = context.HttpContext.RequestServices.GetRequiredService<ILoggerFactory>();
                    var logger = loggerFactory.CreateLogger(context.ActionDescriptor.DisplayName);

                    if (context is Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext)
                    {
                        var ctxt = context as Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext;
                        logger.LogError($"Invalid API response {JsonConvert.SerializeObject(ctxt.ActionArguments.FirstOrDefault(), Formatting.Indented)}");
                    }
                    return new BadRequestObjectResult(context.ModelState);
                };

**Comment by Rick-Anderson** [comment]
@idbates  thanks for your input.
