### ISSUE TITLE
Spelling Error 

### ISSUE THREAD

**Issue by eman365** [aspnet/AspNetCore.Docs#13729]
Update the Delete view

In Views/Student/Delete.cshtml, add an error message between the h2 heading and the h3 heading, as shown in the following example:

I believe it should read "between the h1 heading and the h3 heading,"  as can be seen in Delete.cshtml:

&lt;h1&gt;Delete&lt;/h1&gt;

&lt;h3&gt;Are you sure you want to delete this?&lt;/h3&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
It's `<h2>` in the code shown
![image](https://user-images.githubusercontent.com/3605364/62738313-0f3e0580-ba00-11e9-93f6-1076f515adc5.png)

**Comment by eman365** [comment]
Mine says <h1>. I guess I guess it created it different here...

![image](https://user-images.githubusercontent.com/12814751/62753815-264e1900-ba3b-11e9-91a8-a70113fb0a9a.png)
