### ISSUE TITLE
Downloading and Deleting PersonalData in classes that use the IndentityUser Id as a Foreign Key

### ISSUE THREAD

**Issue by JNickVA1** [aspnet/AspNetCore.Docs#13733]
I have several "add-on" classes for use by the IdentityUser object with each having the IdentityUser Id as a ForeignKey when instantiated. Will the properties marked with the PersonalData attribute in these classes be included in the personal data download or do I have to take a different approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think so. Try it and let me know.

**Comment by iofluxdev1** [comment]
Not sure if I am doing something wrong, but I could not get any navigational properties marked with the attribute on the navigational property on the user entity, nor on any navigational entity properties marked as such.

**Comment by Rick-Anderson** [comment]
@iofluxdev1 `dotnet --version` ?

**Comment by iofluxdev1** [comment]
@Rick-Anderson 2.2.401
