### ISSUE TITLE
AspNetCore.Docs-Master missing pages ef-rp cu21

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/AspNetCore.Docs#13739]
after downloading AspNetCore.Docs-master(download July 2019) and loading ef-rp/cu21.
I CANNOT find Pages Courses/Instructors/Departements as used in Shared/Layout.cshtml (see below)

What am I missing ?

Do I need to download a newer AspNetCore.Docs-Master ?

&lt;ul class="nav navbar-nav"&gt;
                    &lt;li&gt;&lt;a asp-page="/Index"&gt;Home&lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a asp-page="/About"&gt;About&lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a asp-page="/Students/Index"&gt;Students&lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a asp-page="/Courses/Index"&gt;Courses&lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a asp-page="/Instructors/Index"&gt;Instructors&lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a asp-page="/Departments/Index"&gt;Departments&lt;/a&gt;&lt;/li&gt;
                &lt;/ul&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Look in https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu30snapshots
that code will be the same
cc @tdykstra

**Comment by edikaufmann** [comment]
I downloaded AspNetCore.Docs-Master and find 
CU, CU21, CU21snapshots --> neither has the Course, departments and instructor pages
copying the appr pages from CU didn't work (Build error)
thanks for clarifying, ed

CU30, CU30 snapshots --> I do Not yet use Core 3.0

**Comment by Rick-Anderson** [comment]
>  I do Not yet use Core 3.0

The code you're looking for is the same.

**Comment by edikaufmann** [comment]
couple weeks ago I got the suggestion to download https://github.com/aspnet/...../ef-rp/intro/samples/cu30snapshots
to find the completed APP.

whether cu30snapshots nor CU30 etc contains a complete version (at least I can't find it). I.e. ONLY Page/students is there (no course, instructor etc)
Therefore I started to create the app again (with success, thanks good tutorial).

However there is only one thing I miss "Add Course assignments to the Student Create/Edit page".
OR, at least, I can't find these pages having these function. I guess it would work appropriately to
 "Add Course assignments to the Instructor Create/Edit page".

To quickly test I added this info directly on the DB "dbo.Enrollement"; all ok!
PS: I don't want to run DBinitializer anymore!

 ? do I just not see/find this function OR is the idea to challenge the ''students'' and do it myself! ?  

thanks, ed

**Comment by tdykstra** [comment]
The completed version of the app is in cu30, and cu30snapshots only has files that are different at earlier stages of the tutorial.  Where in the tutorial do you see "Add Course assignments to the Student Create/Edit page"?  The sample app only has what the tutorial has.

**Comment by edikaufmann** [comment]
that clarifies it, thanks
