### ISSUE TITLE
How to use ProtectedPersonalData

### ISSUE THREAD

**Issue by JNickVA1** [aspnet/AspNetCore.Docs#13731]
I found the attribute class, ProtectedPersonalData, but I can't seem to find any documentation on how to use it. Please point me to information or provide some examples please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Marking your EF model for encryption](https://github.com/blowdart/AspNetCoreIdentityEncryption#marking-your-ef-model-for-encryption)
To have Identity encrypt your custom IdentityUser model, annotate your model fields with `[ProtectedPersonalData]`
