### ISSUE TITLE
Error on Update-Database

### ISSUE THREAD

**Issue by Cyberance** [aspnet/AspNetCore.Docs#13736]
I get the following error when I'm trying to update the database

The entity type 'OfficeAssignment' requires a primary key to be defined.

As someone suggested I added the [Key] for the OfficeAssignment class. When I do that database is updated, but the seeding database step does not populate the OfficeAssignements table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm  not sure what you've done wrong, but the code does work. You might try the sample download.
