### ISSUE TITLE
<_RazorComponentInclude>Pages\**\*.cshtml</_RazorComponentInclude>

### ISSUE THREAD

**Issue by endstreet** [aspnet/AspNetCore.Docs#13740]
Components can be authored using the .cshtml file extension as long as the files are identified as Razor component files using the _RazorComponentInclude MSBuild property. For example, an app that specifies that all .cshtml files under the Pages folder should be treated as Razor components files: refers..

1. Where in the project xml does this go?
2. When added to the project xml .razor pages fail to compile...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @endstreet ...

1. MSBuild properties go into the project file into a `<PropertyGroup>`. I'll make a modification to that example to include those tags.
1. I can't repro that here. Open an issue with engineering to report a possible bug to them :point_right:  https://github.com/aspnet/AspNetCore/issues

**Comment by guardrex** [comment]
Note that if you mean using the example that that is expected behavior ... it isn't a bug. If the property tells the compiler that all *.cshtml* pages are components, then it will treat them all as components. If you want specific files to be components files in that folder, then list them explicitly in the property value.
