### ISSUE TITLE
The "Register a Component" feels odd being in middle of this page

### ISSUE THREAD

**Issue by pkellner** [aspnet/AspNetCore.Docs#13746]
It seems odd that their is a TOC element in the middle of this article that refers to sections above the TOC. I'm use to seeing indexes like that always above the content. It initially confused me because I'm thinking "didn't I just read about that?", yet I'm running into the TOC section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d627ece-78c4-d244-63a8-d43556ca1653
* Version Independent ID: 069ef9fd-61c2-2c65-d0fe-60d272723f03
* Content: [Tag Helper Components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/th-components?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/th-components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/th-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@pkellner  it looks like a copy/paste error. Should it be:

There are three ways to add to the collection:

    * [Registration via services container](#registration-via-services-container)
    * [Registration via Razor file](#registration-via-razor-file)
    * [Registration via Page Model or controller](#registration-via-page-model-or-controller)

**Comment by pkellner** [comment]
Yes @Rick-Anderson I think you are right. I just figured I did not understand what was going on.

**Comment by pkellner** [comment]
Hey @RickAndMSFT , I’m need to figure out tag helper components right away for my phone lursight course update I’m wrapping.  If you can help me understand the built in head and body tag helper built in components, I’ll do the docs for them.  I’m totally confused and Damien has given up on me.  :).   https://twitter.com/pkellner/status/1161416157758312448?s=21

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  can you help out?

**Comment by NTaylorMullen** [comment]
I'm not quite sure what else to say differently than what the doc says to be honest. If you could be more specific on what's confusing maybe that will help. Also maybe looking at the head/body TagHelper implementations which enable TagHelperComponents may shed some light. i.e. here's the head one: https://github.com/aspnet/AspNetCore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/Mvc/Mvc.Razor/src/TagHelpers/HeadTagHelper.cs
