### ISSUE TITLE
New Blazor Templates for Client Side are Unclear

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore.Docs#13747]
When following this guide, in the latest Preview 7, you get the following options: 
-Blazor Server App
-Blazor (ASP.NET Core Hosted): A project template for creating a Blazor app that runs on WebAssembly. This template can be used for web apps with rich dynamic user interfaces (UIs).
-Blazor (client side): A project template for creating a Blazor app that runs on WebAssembly. This template can be used for web apps with rich dynamic user interfaces (UIs).

In Visual Studio, those last two are identical in descriptions. Here in the documentation, it isn't much better. 
- Blazor (client-side) (dotnet new blazor) – Deployed as a set of static files.
- Blazor (ASP.NET Core Hosted) (dotnet new blazorhosted) – Hosted by an ASP.NET Core server. The ASP.NET Core app serves the Blazor app to clients. The Blazor client-side app can interact with the server over the network using web API calls or SignalR.

If I understand it correctly, the Blazor (client-side) is meant to only have static pages, and therefore would either work if you are connecting to another Web API and merely want blazor as a Front-End Technology?

Whereas Blazor (ASP.NET Core Hosted) is if you're building out a full-stack solution and need to have control of a front and backend (so designing a web app and creating the APIs, database connection, etc?)

If so, would the staff give a bit more information here in the documentation with examples like I mentioned and also update the descriptions in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@kevingates I've marked this for management to triage. For the VS template description, you could try sending that in to that team via VS's **Report a Problem** process built into VS. However, I'm fairly certain that they're already aware of that. The **Hosted** description is missing a bit about **_how_** it's hosted ... i.e., by an ASP.NET Core app.

WRT to the descriptions in the doc, management will provide further guidance to us on how to address it. Thanks for opening this issue.

**Comment by guardrex** [comment]
This was a point-in-time issue AFAIK. If you're still confused on the template descriptions based on what you see in VS, open an issue on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues

If there's a doc issue for the latest descriptions, open a new docs issue using the **This page** feedback button/form at the bottom of the topic.
