### ISSUE TITLE
Link to ASP.NET Core Module does not contain information about activating claims transformations when hosting in-process.

### ISSUE THREAD

**Issue by vbdoug** [aspnet/AspNetCore.Docs#13753]
Please update to link to the correct url/location.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vbdoug ... *Ah!* I see what happened ... the content is there ... you're looking at the wrong version of the topic to see it. Switch your doc version selector over to 2.2.

<img width="515" alt="Capture" src="https://user-images.githubusercontent.com/1622880/62804203-2d643e00-bab2-11e9-8555-20df8e28172c.PNG">
