### ISSUE TITLE
AuthorizeService.js could not load settings

### ISSUE THREAD

**Issue by AIRyndon** [aspnet/AspNetCore.Docs#13769]
Hello Everyone

I'm stuck on how to get Identity to work correctly on Azure App Service.
I'm trying out the asp.net core 3 create-react-app template. I've followed the instructions on setting up IdentityServer and now I'm stuck. It is all working fine on a dev machine, the issue comes up once the application is deployed to Azure - if it means anything, the app is deployed using Azure pipelines.

Here is the error I get in the browser from AuthorizeService.js:
```
async ensureUserManagerInitialized() {
        if (this.userManager !== undefined) {
            return;
        }

        let response = await fetch(ApplicationPaths.ApiAuthorizationClientConfigurationUrl);
        if (!response.ok) {
            throw new Error(`Could not load settings for '${ApplicationName}'`);
        }
```
I followed the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#example-deploy-to-azure-websites) and [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-ssl-cert-load#make-the-certificate-accessible).

I did not load the cert from code because I don't know if I need to do that too. I only uploaded it to Azure App Service and made it accessible like in the instructions. I also thought we don't need to load the cert from code because of this line from the instructions:

> While these steps mention SSL, there's a Private certificates section on the portal where you can upload the provisioned certificate to use with the app.

If we need to load the cert from code, how do we use it from the webapp? Sorry for being a noob. 

Thank you in advance for all the help :)

**Comment by AIRyndon** [comment]
I tried to debug it and found out that in Azure App service it can't find the configuration:
https://localhost:<port>/_configuration/<app_name> - this one returns 200 in localhost
https://<website_name>.azurewebsites.net/_configuration/<app_name> - this one returns 404

I don't know where to check, as to why that config is missing once the app is published to Azure, I tried running a release build from a dev machine and it works fine. Or maybe I should publish it locally and check from there.

**Comment by AIRyndon** [comment]
Okay I was able to debug it..this [issue](https://github.com/aspnet/AspNetCore/issues/10628) helped me out a lot. The issue is the application root in Azure App service confuses the webapp.

**Comment by lucabriguglia** [comment]
@AIRyndon what did you do exactly to fix the issue?

**Comment by AIRyndon** [comment]
@lucabriguglia sorry I forgot what I did exactly, as its been a long time since I made the fix :(

**Comment by lucabriguglia** [comment]
@AIRyndon no problem, I managed to fix it :-)

**Comment by albertosubero** [comment]
@lucabriguglia  what did you do exactly to fix the issue?

**Comment by vohoanvu** [comment]
how did this problem get fixed?
