### ISSUE TITLE
Authentication overview

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#13764]
There is no article that gives an overview of authentication in ASP.NET Core.

The article should talk about:
- What authentication is
- What authentication options there are
- An introduction to setting up authentication

It should be located at: Security and Identity -> Authentication -> Overview

Equivalent page for authorization: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction

**Comment by Rick-Anderson** [comment]
Dup of #4055
