### ISSUE TITLE
Prerequisites could be improved

### ISSUE THREAD

**Issue by HarleyPebley** [aspnet/AspNetCore.Docs#13762]
There's not much description of the code that's presented in this tutorial. It assumes a lot of prior knowledge. Prerequisites I lacked included understanding of DOM and JS. (E.g. in "Get a list of to-do items," three sentences describe 30 lines of code. There's a lot of things going on in those 30 lines that aren't described by the text that I had to infer.)

It would be nice to have mentioned in the prerequisites the level of code knowledge that's expected for C#, CSS, HTML, JS, DOM, jQuery with pointers for more details on each one of these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HarleyPebley  thanks for this. See #13763
