### ISSUE TITLE
`AddEnvironmentVariables` is used to load environment variables prefixed with `DOTNET_` 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13779]
Previously used `ASPNETCORE_`
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-3.0&branch=pr-en-us-13670

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@guardrex  anything else I'm missing from your config update?

**Comment by guardrex** [comment]
@Rick-Anderson I think that's it.

**Comment by tdykstra** [comment]
Per the Generic Host doc,

>The environment variable provider with prefix DOTNET_ and command line args are included by CreateDefaultBuilder. For web apps, the environment variable provider with prefix ASPNETCORE_ is added. 

So it seems that no migration change is needed because everything is still accessible via ASPNETCORE_.
