### ISSUE TITLE
Add a note regarding setting size limit on shared caches

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore.Docs#13778]
The docs references a "shared" memory cache in DI early on and this leads to a pitfall when users try to set a size limit on the shared instance later on. When a size limit is imposed on a cache, all entries must specify a size when being added. This can lead to issues since the users may not have full control on what uses the shared cache. For example, EFCore will use the shared cache and does not specify a size, and the application will throw InvalidOperationException if a size limit is imposed on the shared cache. We should add a note early in the documentation so that it's clear we recommend against setting a size limit on a shared memory cache and instead tell users to create a private instance for caches with a size limit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#using-imemorycache)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JunTaoLuo  do you have an issue this came from?

**Comment by JunTaoLuo** [comment]
@mmitche and I was looking at a bug he ran into and it turned out to be that a size limit was set on the shared instance breaking other components that used it.

**Comment by Rick-Anderson** [comment]
@JunTaoLuo  and @mmitche
> The docs references a "shared" memory cache in DI early on 

What doc?

**Comment by JunTaoLuo** [comment]
Specifically https://github.com/aspnet/AspNetCore.Docs/blame/master/aspnetcore/performance/caching/memory.md#L54
