### ISSUE TITLE
[HTTPS] Can we change the doc here to indicate that --trust is not supported on Linux

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#13774]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio-code

Can we change the docs to provide proper instructions on Linux? (Indicate there is no support for doing trust through the tool) and to simply either go through the untrusted cert prompt once or give instructions for setting up the cert as trusted on ubuntu/debian or any other popular distro. (Disclaimer, I don't have any idea how to do that)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It already cross-links to the *Enforce SSL* topic, but it doesn't cross-link specifically to ...

https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#trust-https-certificate-from-windows-subsystem-for-linux

**Comment by Rick-Anderson** [comment]
@javiercn  I'd rather  not  provide the instructions. I we provide instruction that will create support issues and need updates. I'd rather tell them they need to set up a cert. Aren't there instructions for the popular distro's? cc @scottaddie

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

**Comment by Rick-Anderson** [comment]
@javiercn  I created the integrated issue at #13781

**Comment by Rick-Anderson** [comment]
Fixed in #13782
