### ISSUE TITLE
ASP.NET service providers

### ISSUE THREAD

**Issue by ohault** [aspnet/AspNetCore.Docs#13772]
I would be interresting to extend "Publish to" an eco-systeme of ASP.NET (core) service providers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb594f-04bf-c4d7-c94b-6cd6d8b12d75
* Version Independent ID: 64e973ac-838d-4459-06b0-4e943bff936e
* Content: [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ohault ... Do you mean 3rd party hosters? If so, we can't cover it. That type of content would be impossible for us to maintain.

**Comment by ohault** [comment]
Hello,

There is already a pre-list on https://dotnet.microsoft.com/apps/aspnet/hosting

Just imagine a "Publish to" (in VS code) that will list ASP.NET cloud service providers registered.

This could create a wonderful abstraction to whatever hosting env for ASP.NET (container, native, Azure App Services, ...)

I have added Scott Gurie in cc:

Olivier

________________________________
De : Luke Latham <notifications@github.com>
Envoyé : lundi 12 août 2019 14:34
À : aspnet/AspNetCore.Docs <AspNetCore.Docs@noreply.github.com>
Cc : Olivier Hault (Level IT) <olivier.hault@level-it.be>; Mention <mention@noreply.github.com>
Objet : Re: [aspnet/AspNetCore.Docs] ASP.NET service providers (#13772)


Hello @ohault<https://github.com/ohault> ... Do you mean 3rd party hosters? If so, we can't cover it. That type of content would be impossible for us to maintain.

**Comment by guardrex** [comment]
We only handle ASP.NET Core documentation on this repo.

To provide feedback on VS Code, they take feature requests on their repo at https://github.com/Microsoft/vscode/issues.

**Comment by ohault** [comment]
Perhaps adding a simple hyperlink to  https://dotnet.microsoft.com/apps/aspnet/hosting will already provide a first answer.

With the recent support of many new types of deployments (I mean Containers, K8s, ...) this section "Host and Deploy" section would also require some re-organizations and a more structured table of contents. I can think of grouping deployments into several distinct categories.

**Comment by guardrex** [comment]
I'll mark this for management to triage.
