### ISSUE TITLE
Password reset with SendGrid ( IEMailSender) not working

### ISSUE THREAD

**Issue by foconnor-DS** [aspnet/AspNetCore.Docs#13789]
Followed the article, and New Registration successfully sends an e-mail. But when attempting Password Reset using a React SPA with Authentication (dotnet new react -au Individual) on 3.0.100-preview7-012821, the IEmailSender interface is never called.

Again, it works for new user registration, I get the e-mail, and break points on SendEmailAsync are reached. But on "Password Reset", the interface methods are never called.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I you think it's a bug with the VS generated templates, Use the Visual Studio feedback menu item to leave feedback.  Help >  Send Feedback.

Have you compared your code to the Razor Pages version?

**Comment by foconnor-DS** [comment]
I can confirm this was a Preview7 bug. It works in Preview8. Also, in Preview7, after logging in the first time, it didn't take you to the RegisterConfirmation page. It took you back to the Home page, and you were fully logged in.

In Preview8, it follows the docs.

**Comment by Rick-Anderson** [comment]
Thanks for the update.
