### ISSUE TITLE
HTTPS feature not working in project.

### ISSUE THREAD

**Issue by smiller7812** [aspnet/AspNetCore.Docs#13794]
I had "configure for HTTPS" checked on project creation.  But I did not get the Trust SSL dialogue poping up and my project URL runs starting with localhost and hot https://localhost.  Could tthere something be missing from my project setup that is not allowing https to work properly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>  "configure for HTTPS" checked on project creation

That has nothing to do with the cert, that adds the HTTPS calls like the following `            app.UseHttpsRedirection();`

**Comment by smiller7812** [comment]
Ok, So still  wondering why mine did not run as https and come up as in the tutorial.  No biggie. But I think I have had this issue in past versions of the tutorial as well.
