### ISSUE TITLE
Code sample above has an invalid reference

### ISSUE THREAD

**Issue by jaimeboyaca** [aspnet/AspNetCore.Docs#13795]
in: dotnet user-secrets set Authentication:Twitter:ConsumerAPISecret &lt;Secret&gt;

The ConsumerAPISecret above it being referenced as ConsumerSecret in the sample C# code causing an error from a straight copy and paste:

twitterOptions.ConsumerSecret = Configuration["Authentication:Twitter:ConsumerSecret"];

should be:

twitterOptions.ConsumerSecret = Configuration["Authentication:Twitter:ConsumerAPISecret"];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external sign-in setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jaimeboyaca  check out the fix in #13798

**Comment by jaimeboyaca** [comment]
Looks good! Thanks for the quick fix.

**Comment by Rick-Anderson** [comment]
@jaimeboyaca  thanks for bringing this to our attention.
