### ISSUE TITLE
Examples use undefined `ReadAsAsync` extension method

### ISSUE THREAD

**Issue by cornem** [aspnet/AspNetCore.Docs#13790]
Two examples on this page use an extension method `ReadAsAsync<T>` on `HttpContent`. However, this method itself is actually not defined in the examples or available by default from any of the referenced libraries.

For clarity, this extension method should either be provided, or not used at all.

Sample implementation that could be included:

```
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;

public static class HttpContentExtensions
{
    public static async Task<T> ReadAsAsync<T>(this HttpContent content)
    {
        string stringContent = await content.ReadAsStringAsync();
        return JsonConvert.DeserializeObject<T>(stringContent);
    }
}
```

Or using `System.Text.Json` instead:

```
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

public static class HttpContentExtensions
{
    public static async Task<T> ReadAsAsync<T>(this HttpContent content)
    {
        string stringContent = await content.ReadAsStringAsync();
        return JsonSerializer.Deserialize<T>(stringContent);
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@cornem I saw a post online that the `System.Net.Http.Formatting` package is now `Microsoft.AspNet.WebApi.Client`. That package has been added to the 3.x sample's package references. I wonder if you drop your `bin` and `obj` folders from the app and then nuke your package cache (`dotnet nuget locals --clear all`) if you will get the newer assembly into the app.

**Comment by guardrex** [comment]
Here's where it is ...

https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpContentExtensions.cs

... so give that package cache a clean and restore. I *think* that you'll get `Microsoft.AspNet.WebApi.Client` with the bits.

**Comment by guardrex** [comment]
I'm going to close because I think this is a package issue. We see this from time-to-time when cached packages or incompatible packages end up in projects. I think 🤞 things will work out for your app after following my suggestion. If not, let me know. I'll re-open this issue and check from here to see if I can repro your behavior.
