### ISSUE TITLE
"Project Root" is not sufficiently clear

### ISSUE THREAD

**Issue by t-eckert** [aspnet/AspNetCore.Docs#13817]
Step 4 of "Configure the ASP.NET Core app" could be clearer. Because the user has created other items at the dir above `SignalRWebPack`, they may consider that to be the root, but it would be more idiomatic in C# for the root in question to be the `SignalRWebPack` directory. This is probably what was meant by "project root". I would suggest changing the text to

Create a new directory, called Hubs, in the `SignalRWebPack` directory. Its purpose is to store the SignalR hub, which is created in the next step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by t-eckert** [comment]
Update to this, I was just confused where "project root" was. It might be better to have an explicit step to `cd` into the `SignalRWebPack` dir. I realize now what my mistake is by looking at the sample code, but from following the directions, I created this structure where `SignalRWebPack` is a subdirectory of the root.

![image](https://user-images.githubusercontent.com/29112081/62983462-3c196080-bde4-11e9-8399-eefa25103041.png)

**Comment by AaronLS** [comment]
In VS2019 Package Manager Console commands have a bug that cause them default to the solution root instead of the project root.  This causes commands like npm init to create the package.json file in the wrong directory.  It's important that instructions explicitely state to check pwd and direct the user to cd to the correct folder.

**Comment by wadepickett** [comment]
In addition: 
For VS Code users there should have been an added command  `code -r SignalRWebPack` after creating the new project.  That way the project opens up in VS Code and you automatically get a cd  to the new project directory that was created.

**Comment by wadepickett** [comment]
Fixed with PR #16835
