### ISSUE TITLE
Wrong case used in code

### ISSUE THREAD

**Issue by ShayonX** [aspnet/AspNetCore.Docs#13815]
Under "Add validation rules to the movie model"

The movie class has the following code:

```
public class Movie
{
    public int Id { get; set; }
```

To make it consistent with the previous parts of the tutorial it should be

```
public class Movie
{
    public int ID { get; set; }
```

Otherwise it leads to the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Movie' does not contain a definition for 'ID' and no accessible extension method 'ID' accepting a first argument of type 'Movie' could be found (are you missing a using directive or an assembly reference?)	RazorPagesMovie	E:\Code\Tutorials\C#\RazorPagesMovie\RazorPagesMovie\Pages\Movies\Details.cshtml	47	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ShayonX  thanks for reporting this.
