### ISSUE TITLE
CSS slightly buggy

### ISSUE THREAD

**Issue by MythreyaK** [aspnet/AspNetCore.Docs#13828]
Not much of an issue, but a small glitch near feedback section of the page. 

![image](https://user-images.githubusercontent.com/26112391/63034880-ba0a6400-bed7-11e9-9ef1-d44735bad923.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MythreyaK ... We only work on content here. Open this over on the Microsoft.Docs repo :point_right: https://github.com/MicrosoftDocs/feedback

**Comment by MythreyaK** [comment]
My apologies!

**Comment by guardrex** [comment]
No worries. Thanks for commenting. They should be able to handle it or direct it internally from there.
