### ISSUE TITLE
Compile issue on preview8

### ISSUE THREAD

**Issue by brightertools** [aspnet/AspNetCore.Docs#13820]
I have installed preview8 and created the react project.
The project would not compile with an error:
MSB4064	The "Nullable" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.

in 

C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Compilation.targets	156	

The line content is: 

Nullable="$(Nullable)"

If I remove this, its then compiles.

Will removing this have any adverse effects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@brightertools Are you on v16.3 Preview 2 ... that's required for .NET Core Preview 8.

**Comment by javiercn** [comment]
@pranavkm @NTaylorMullen Is this any of you?

**Comment by javiercn** [comment]
Closing as this is likely not applicable anymore. Will re-open on asp.net core if it happens
