### ISSUE TITLE
Missing section to deploy manually built app to docker

### ISSUE THREAD

**Issue by skloibhofer** [aspnet/AspNetCore.Docs#13824]
The Build and deploy manually section misses a final paragraph/subsection to discuss how the already built app is deployed to docker. As this needs a different Dockerfile this is valuable information in my opinion. I will share how I would do this here, but as I am applying my first docker application at the moment, this may have quite some flaws. So I would be happy, if somebody can review and add that.

In *dotnet-docker/samples/aspnetapp/aspnetapp* create a Dockerfile with the content:

    FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
    WORKDIR /app
    COPY . .
    ENTRYPOINT ["dotnet", "aspnetapp.dll"]

Then, in the same folder run 

    docker build -t aspnet_prebuilt -f Dockerfile published\
    docker run -it --rm -p 5000:80 --name aspnetcore_sample aspnet_prebuilt

Here I use `-f` to specify the Dockerfile directly and then the published folder, to only copy the necessary files to docker (keeps it small). This may or may not be good practice in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by spboyer** [comment]
@skloibhofer the section **Build and deploy manually** describes how to create the `aspnetapp.dll` file manually that is created for you using the multi-stage Dockerfile displayed in the following section.

There is no missing steps here, just note that a multistage Dockerfile is not required as you the developer have done the build stage locally.

Creating a Dockerfile as follows and running `docker build .` would accomplish the task.

```docker
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY published/aspnetapp.dll ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```
