### ISSUE TITLE
[Preview 8] Blazor (Server Side) overriding identity via scaffolding throws error

### ISSUE THREAD

**Issue by hasmMarques** [aspnet/AspNetCore.Docs#13821]
dotnet 3.0.100-preview8-013656

1. Upgrade to .net core 3.0.100-preview8-013656
2. Create a new asp.net core web application project, select server side blazor.
3. Change Identity to individual user account
4. After project creation right click Areas/Identity folder, Add New Scaffold Item, Override all files throws error.

![image](https://user-images.githubusercontent.com/16259170/63013488-3d01cf00-be84-11e9-9877-ae4ba0263b02.png)

**Comment by guardrex** [comment]
Hello @hasmMarques ... open this on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues
