### ISSUE TITLE
 Microsoft.AspNetCore.Identity.EntityFramework Does not seem to exist

### ISSUE THREAD

**Issue by jeanpoelie** [aspnet/AspNetCore.Docs#13822]
I believe  Microsoft.AspNetCore.Identity.EntityFramework has changed into  Microsoft.AspNetCore.Identity.EntityFrameworkCore or it has been a typo in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6772c4-1017-5e86-8045-8849b5dd1ad7
* Version Independent ID: bcb8d6b2-f38a-ac10-d3f2-69d4223bfd72
* Content: [Migrate Authentication and Identity to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/migration/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jeanpoelie  thanks for letting us know.
