### ISSUE TITLE
Doc how proxies work

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13847]
See https://github.com/aspnet/AspNetCore/issues/13160 by @igor-tk 

@blowdart writes:
If you put a proxy in the way of what is essentially a connection based authentication mechanism then the proxy has to do the authentication, then pass on the information in a way the final service understands. It's the same with certificates.

@Rick-Anderson can we get the docs updated to indicate no proxies for both Kerberos/Negotiate and also Certificate auth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#kestrel)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
Also flag that kerberos auth isn't for the internet. It's for machines within your intranet.
