### ISSUE TITLE
SSO requires setting cookie path

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13846]
See #13823 by  @noctwolf 

The instantiated here is the RequestPathBaseCookieBuilder class.
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L15
Changed Path in the Build method of the RequestPathBaseCookieBuilder class
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Core/src/RequestPathBaseCookieBuilder.cs#L21-L35

`@Tratcher `
Ah, I forgot about those custom builders. Yes, this is a scenario that we should discuss and document but changing it in just this code sample isn't going to help. Please file a doc bug so we can make sure the SSO scenario is covered.

@guardrex 

Cookie options are first discussed here ...

https://docs.microsoft.com/aspnet/core/security/authentication/identity-configuration#cookie-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by noctwolf** [comment]
@Rick-Anderson Thanks, get new skills

**Comment by Rick-Anderson** [comment]
@noctwolf  can you create a PR to address this? I'll edit it for you.

**Comment by HaoK** [comment]
Looks fine to me, @Tratcher should take a look too
