### ISSUE TITLE
Typo: The section Areas with Razor Pages uses text 'require and' instead of 'require an'

### ISSUE THREAD

**Issue by ColinPM** [aspnet/AspNetCore.Docs#13857]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.2#areas-with-razor-pages)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ColinPM ... I'll patch that.
