### ISSUE TITLE
Document how to use static web assets feature in all environments

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#13864]
see: https://github.com/aspnet/AspNetCore/issues/13190

We should make sure the docs include the difference between how this feature behaves in production vs development, and how to override this.

**Comment by javiercn** [comment]
We simply need to add a line to the docs that says

_Static web assets are enabled by default during `Development`. If you want to explicitly support static web assets in other environments you can do so by calling_
`webHostBuilder.UseStaticWebAssets()`

(`Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStaticWebAssets(this IWebHostBuilder builder)`)

**Comment by javiercn** [comment]
@guardrex Is this something we can get added to the RCL docs?

**Comment by akorchev** [comment]
Static web assets seem to work fine in production without explicitly invoking `UseStaticWebAssets`. Tested by running `dotnet publish -c Release` and then running the app itself via `dotnet app.dll`.

**Comment by javiercn** [comment]
@akorchev 

The helper methods described above are only used when running the app from the build output (dotnet run) when the app gets published we simply copy the assets to their final destination and there is no additional runtime code required to make it work.

**Comment by javiercn** [comment]
@guardrex Can you also indicate that this is only required for non-published apps and that at publish time the assets are simply in their final locations?

**Comment by guardrex** [comment]
@javiercn Already done on the PR.

**Comment by javiercn** [comment]
Thanks! That was quick!

**Comment by Nairda015** [comment]
Hey can you add to the docs information that using ENV as Local or anything non standard will also require to add manual registration for web assets?

**Comment by guardrex** [comment]
@Nairda015 ... Note in passing that the product unit only works from *open* issues/PRs, so you usually won't get a response when commenting on a closed issue/PR. Also, docs are on a different repo, so this wouldn't be the best place to ask that question. Take a look at the coverage ...

https://learn.microsoft.com/aspnet/core/fundamentals/static-files#static-files-in-non-development-environments

... and then if you want to discuss that section (or any others there), use the "**Open a documentation issue**" link at the bottom of the article. The metadata of the opened issue will automatically ping the article's author. The author will respond, usually within a day or two.
