### ISSUE TITLE
Is "var context = services.GetRequiredService<RazorPagesMovieContext>();" necessary?

### ISSUE THREAD

**Issue by BobLLTB** [aspnet/AspNetCore.Docs#13863]
Is var context = services.GetRequiredService&lt;RazorPagesMovieContext&gt;(); necessary?

After re-creating the db and commenting that line it the db did get seeded.

I also noticed 
                  //  webBuilder.UseStartup&lt;Startup&gt;();
                    webBuilder.UseStartup&lt;StartupVal&gt;();

Tried using &lt;StartupVal&gt; and it didn't work. Worked fine using &lt;Startup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BobLLTB  good catch. #13866 will fix this.
