### ISSUE TITLE
3.0 update: Create web APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#13873]
@anurse  can you assign someone to outline what needs to be updated for 3.0 (besides the obvious changes in `StartUp`)?

cc @tdykstra 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson there were no major changes post 2.2. The only notable changes are in the routing area, which are covered as part of other docs articles.

**Comment by Rick-Anderson** [comment]
>  no major changes post 2.2. The only notable changes are in the routing area, which are covered as part of other docs articles.

@scottaddie  @guardrex  do you have a link to **changes are in the routing area, which are covered as part of other docs articles.** so I can point to that?

**Comment by guardrex** [comment]
I'm not directly aware ... Scott will know ... but *endpoint routing* concepts generally apply, so the Routing topic as a whole can be referenced in the *Additional Resources* section (it's not currently listed).

> \* \<xref:fundamentals/routing>

**Comment by scottaddie** [comment]
@Rick-Anderson I see several minor changes that we should make in the doc for 3.0. Feel free to assign to me.
