### ISSUE TITLE
IHostingEnvironment is obsolete

### ISSUE THREAD

**Issue by spboyer** [aspnet/AspNetCore.Docs#13886]
Migration missing for IHostingEnvironment

Replace `IHostingEnvironment` with `Microsoft.AspNetCore.Hosting.IWebHostEnvironment`

```csharp
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
For this section ...

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#migrate-startupconfigure

**Comment by spboyer** [comment]
IWebHostEnvironment is not mentioned there.

**Comment by guardrex** [comment]
Yes ... I'm just calling out the section.
