### ISSUE TITLE
Provide upperbound on topic versioning

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13887]
We've had a problem signaling to readers that a topic hasn't been updated for the latest version, including for preview releases.

Discussing this offline, there's been some agreement that it would be nice if we could upperbound the version of the topic in metadata and thus activate the 'The requested page is not available for ...' message for topics that haven't been updated for the latest release or prerelease of the framework.

**_Exciting News!_**

![Tattoo1](https://user-images.githubusercontent.com/1622880/63215494-e0edb380-c0ec-11e9-85db-6c31b5fa2a0a.jpg)

**_ZE PLANE! ZE PLANE!_** &mdash; Tattoo ([Hervé Villechaize](https://www.imdb.com/name/nm0898199/)), *Fantasy Island* &copy;1977-1984 [Sony Pictures Television](https://www.sonypicturestelevision.com/)

For a markdown file with the following metadata ...

```
monikerRange: '>= aspnetcore-2.0 <= aspnetcore-2.1'
```

... we get that exact behavior. As a test page, see ...

https://docs.microsoft.com/aspnet/core/version-test

[I'll revert *version-test.md* from the repo after you've had a look.]

Note the following behaviors:

* It loads at 2.1, which is the upperbound.
* Drop it to 1.1 (https://docs.microsoft.com/aspnet/core/version-test?view=aspnetcore-1.1) ... 2.1 is loaded, and the 'The requested page is not available' message is shown.
* Take it up to 2.2 (https://docs.microsoft.com/aspnet/core/version-test?view=aspnetcore-2.2) ... 2.1 is loaded, and the 'The requested page is not available' message is shown.
* It further works at 3.0 Preview: https://docs.microsoft.com/aspnet/core/version-test?view=aspnetcore-3.0

**_Tip of my_** 🎩 **_to docs engineering and @dend!_**

I'd like to get permission to update our docs to take advantage of this feature. I'll knock it out with one of my 😵 *Mad RexScripts*:tm: 😵 ... Wat da ya tinks? :ear:

@danroth27 @Rick-Anderson @scottaddie @tdykstra @wadepickett

**Comment by Rick-Anderson** [comment]
Seems like a good idea to me.

**Comment by tdykstra** [comment]
Ditto

**Comment by danroth27** [comment]
I'm concerned about applying the version cap in a cross cutting manner. I'd like to avoid returning 404s for content that is for the most part correct. Instead of a 404 wouldn't a warning banner be more appropriate to indicate that a topic is stale and might not be fully accurate?

**Comment by guardrex** [comment]
There's no 404 ... it only provides the 'This topic isn't available for the selected version' message both above and below the specified range.

**Comment by guardrex** [comment]
Try the example page at https://docs.microsoft.com/aspnet/core/version-test ... it sets the version for 2.0/2.1 and yields the message <2.0 and >2.1.

**Comment by danroth27** [comment]
Ah! My bad 😝. OK, this sounds pretty reasonable to me, especially while we are in preview.

**Comment by guardrex** [comment]
I'll put my 😵 *Mad RexScripts*:tm: 😵 on it. I'll see if I can hit the edge cases successfully (e.g., based on the sample app versions present and a pre-existing `monikerRange` metadata entry).

**Comment by scottaddie** [comment]
@guardrex I'm okay with this approach too. Thank you for digging into it.

**Comment by guardrex** [comment]
Decided internally that this will be applied on a topic-by-topic basis.
