### ISSUE TITLE
services.AddMvc().AddJsonOptions(options => options.UseMemberCasing())

### ISSUE THREAD

**Issue by ashok-login** [aspnet/AspNetCore.Docs#13896]
# Issue description

Unable to find support for changing the property names to Pascal casing of the CLR object's property names.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [3.0 Preview ] .NET Core

**Comment by guardrex** [comment]
Hello @ashok-login ... At the moment, I think that's over in the migration topic in the last paragraph and example of the *Json.NET support* section: https://docs.microsoft.com/aspnet/core/migration/22-to-30#jsonnet-support

You may need to look up the options ... IntelliSense should be helpful there. If not, try the reference source on the engineering repo.

If it should be elsewhere in the normal reference docs, I'm sure that the docs team member of the given topic will get the updates into it for 3.0. We're trying to get as many done before 3.0 reaches RTM. Even if it isn't addressed before that, I assume that it will be addressed asap after release.

**Comment by guardrex** [comment]
I just saw this related issue, too, to address JSON for 3.0.

https://github.com/aspnet/AspNetCore.Docs/issues/13227
