### ISSUE TITLE
Ite template?

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/AspNetCore.Docs#13890]
How do you create a view component, is there an item template for that?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
No template. You'll have to follow the guidance in the topic ...

https://docs.microsoft.com/aspnet/core/mvc/views/view-components#creating-a-view-component
