### ISSUE TITLE
Statement about View compilation is not correct

### ISSUE THREAD

**Issue by sujayvsarma** [aspnet/AspNetCore.Docs#13895]
(Section: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.0#area-folder-structure)

The document says: "For example, the Controllers and Models folder are not required. The content of Controllers and Models is code which gets compiled into a .dll. **The content of the Views isn't compiled until a request to that view has been made.** " 

The second part of the statement about Views is wrong. When deploying, Views are compiled into a file with name `[projectname].Views.dll`. This is true at least for Core 3.0 Preview (I have not used MVC before that).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Correct. See [Razor file compilation](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation)

Thanks for bringing this to our attention. cc @serpent5

**Comment by serpent5** [comment]
I'll take a look at this one this week. I'd like to investigate exactly what happens between 2.2 and 3.0.

**Comment by Rick-Anderson** [comment]
@serpent5  I don't think the document is correct for 2.2.   

`The content of the Views isn't compiled until a request to that view has been made. "`
Doesn't that just apply to local development?

**Comment by serpent5** [comment]
@Rick-Anderson

> I don't think the document is correct for 2.2.

I agree. The statement in question is incorrect for both versions. I just want to take a quick look at how it works in 3.0 now that runtime compilation is opt-in. I'm not sure exactly *when* the compilation actually occurs in that scenario, but it'll be easy enough to figure out.

**Comment by serpent5** [comment]
@Rick-Anderson I've just been working on rewording this a bit, but I'm wondering now whether the paragraph in question could just be dropped. The preceding paragraph is:

> While the preceding layout is typical when using Areas, only the view files are required to use this folder structure. View discovery searches for a matching area view file in the following order:
>
> [list of view locations]

The paragraph in question mostly just restates that only the views folders matter. I don't think it needs to mention compilation, etc - that's covered in the article you've linked and is imho secondary to what's being described in this page.

What do you think?

**Comment by Rick-Anderson** [comment]
> What do you think?

I agree.
