### ISSUE TITLE
Commented code

### ISSUE THREAD

**Issue by HarleyPebley** [aspnet/AspNetCore.Docs#13902]
Is the context.Database.EnsureCreated() supposed to be commented out in the DbInitializer class?

The text description below the code indicates it shouldn't be. Either the code or text should probably be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@HarleyPebley Thanks for pointing that out!  It was fixed in the 3.0 version but hadn't yet been fixed in the 2.1 version.
