### ISSUE TITLE
No mention of the FileExtensions attribute

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/AspNetCore.Docs#13905]
The article does not mention the `FileExtensions` attribute which can be used in the view model to restrict what files can be uploaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vanillajonathan ... We have a PR in for updates to the topic at https://github.com/aspnet/AspNetCore.Docs/pull/12344. Your recommendation isn't covered on those updates. We have a separate tracking issue for further updates to the topic. I'll add your suggestion there. Thanks for commenting on the topic.
