### ISSUE TITLE
SignalR C# client has ZERO documentation, Release notes impossible to find

### ISSUE THREAD

**Issue by cbordeman** [aspnet/AspNetCore.Docs#13907]
[EDIT by @guardrex for content]

SignalR C# client has ZERO documentation, Release notes impossible to find.  I just saw a StackOverflow issue on this.  No one, including me, can seem to find release notes or even a modern [REMOVED] example on how to use SignalR Core on a C# client.  The one from April 2019 is out of date and doesn't work on SignalR CORE 1.1.  Release notes are utterly impossible to find.

**Comment by guardrex** [comment]
@cbordeman Please don't use language like that here. We can have a civil discussion of what's here and what's missing.

Stand-by ... one of the authors or engineers will respond to your question/remarks.

**Comment by guardrex** [comment]
I'll note in passing in case you didn't see it, the SignalR coverage starts here :point_right: https://docs.microsoft.com/aspnet/core/signalr/introduction

However if by "1.1" you mean "ASP.NET Core 1.1," that version (and 2.0) is no longer supported. Our supported coverage (and the framework itself) is for >=2.1.

**Comment by guardrex** [comment]
There is additional info on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/tree/master/src/SignalR

Release notes go by framework version. You can find the release notes links on the engineering repo *Releases* :point_right: https://github.com/aspnet/AspNetCore/releases

**Comment by guardrex** [comment]
Official blog posts :point_right: https://devblogs.microsoft.com/aspnet/?s=signalr&submit=%EE%9C%A1

(Looking at the titles, it looks like you meant SignalR 1.1 ... my bad.)

@bradygaster Did I cover all of the resources?

**Comment by cbordeman** [comment]
> @cbordeman Please don't use language like that here. We can have a civil discussion of what's here and what's missing.
> 
> Stand-by ... one of the authors or engineers will respond to your question/remarks.

Sorry for the language.  I'm literally in severe chronic pain and it got the best of me.

**Comment by guardrex** [comment]
No worries. I understand. Brady will come on and provide additional info. This isn't really one of my main areas of focus. I'm sure he'll be happy to help and hear your feedback.

**Comment by cbordeman** [comment]
> I'll note in passing in case you didn't see it, the SignalR coverage starts here 👉 https://docs.microsoft.com/aspnet/core/signalr/introduction
> 
> However if by "1.1" you mean "ASP.NET Core 1.1," that version (and 2.0) is no longer supported. Our supported coverage (and the framework itself) is for >=2.1.

That page leads to a super limited "documenatation" page that has no section nor link to a Real-time section.

**Comment by guardrex** [comment]
Is the table of contents in the sidebar on the left helpful? Everything that we currently have for SignalR Core is under that node. We usually rely on that to show the topics under a section along with a handful links at the end of each topic in an *Additional Resources* section.

**Comment by cbordeman** [comment]
The main problem is the sample for .NEt client is seems to be wrong.  I brought in the nuget package indicated, both version 1.0 and 1.1 and I get errors:

        HubConnection connection;
        public ServicesProxy()
        {
            var connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:53353/ChatHub")
                .Build();

            connection.Closed += async (error) =>
            {
                await Task.Delay(new Random().Next(0, 5) * 1000);
                await connection.StartAsync();
            };
        }

HubConnection doesn't exist, nor does HubConnectionBuilder (I haven't checked asp.net core 3.0 yet).  At first I thought it was out of date so I was looking for release notes for SignalR Core, which I still don't see.

I apologize, with my bad eyes I was zoomed way in and so I didn't see the contents on the left.  It's a bit of a nit, but the samples organization is a bit wonkey, right?  Shouldn't the JS/TS/C#/Java samples and tutorials all be under one heading?  No biggy.

**Comment by guardrex** [comment]
Do you have the namespace for those?

```csharp
using Microsoft.AspNetCore.SignalR.Client;
```

* https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilder
* https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnection

I'm not sure on the organization in this TOC node (samples or otherwise). I defer to the team and engineering on the finer points. They'll have more info on those subjects than I.

**Comment by cbordeman** [comment]
I am so sorry, I shouldn't code when I'm in such pain.  Now that it's subsided, I notice I included the wrong package.

**Comment by bradygaster** [comment]
@cbordeman let us know if you need additional support or guidance after figuring out the right NuGet package to pull in. My apologies for there being a few NuGet packages out there - it is the price we've paid for maintaining both the original framework SignalR and pushing the innovations into the new Core package. Please - if you're getting started - make use of the Core packages, as that's where our investment will continue moving forward.
