### ISSUE TITLE
Where is the ValidateDataAnnotations method defined?

### ISSUE THREAD

**Issue by NenoLoje** [aspnet/AspNetCore.Docs#13901]
The code sample mentions a ValidateDataAnnotations method, but it cannot be found (I'm running ASP .NET 2.2, where the Microsoft.Extensions.Options.DataAnnotations package is automatically included).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#options-validation)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the `Microsoft.Extensions.DependencyInjection` namespace. I'll update the doc with the API reference link ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsbuilderdataannotationsextensions.validatedataannotations?view=aspnetcore-2.2#Microsoft_Extensions_DependencyInjection_OptionsBuilderDataAnnotationsExtensions_ValidateDataAnnotations__1_Microsoft_Extensions_Options_OptionsBuilder___0__

**Comment by guardrex** [comment]
I'll work this together with the Options 3.0 update on https://github.com/aspnet/AspNetCore.Docs/issues/13330.

Thanks for asking @NenoLoje! :rocket:
