### ISSUE TITLE
Update screenshot(s) and code in SignalR tutorial to use Visual Studio 2019

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13919]
@donhuvy ...

&gt; Need update screenshot SignalR tutorial use Visual Studio 2019

@BrennanConroy ...

&gt; If you select 3.0-preview you'll see updated docs with VS 2019.
&gt;
&gt; I'm not sure what the policy is for updating previous docs with new VS. We probably are going to keep 2.2 as-is, otherwise every new tooling will need a ton of updates to docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#create-a-web-project)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
@BrennanConroy Yes, indeed. Given that this is a tutorial, it will need that work. For non-tutorials, we're trying not to use images ... especially of IDEs and Azure portal UIs. 🙈 

We're about to provide upperbounds on topic versions. At least that way when the version selector is set to a higher version than the topic actually supports, the reader will get the 'This topic isn't available' for your selected version message. https://github.com/aspnet/AspNetCore.Docs/issues/13887

**Comment by Rick-Anderson** [comment]
@wadepickett  can you do this?

**Comment by wadepickett** [comment]
@Rick-Anderson, on it, thanks!

**Comment by wadepickett** [comment]
@Rick-Anderson, what prioirty is this one?

**Comment by wadepickett** [comment]
Code also needs to updated, not just the screenshots.  On that as well.

**Comment by bradygaster** [comment]
I also just submitted #14764 but have 1-2 more tweaks to make.

**Comment by wadepickett** [comment]
@bradygaster , I have the updated screenshots for the new project dialog, f12 dev tools, libman using "@latest" and update startup.cs using the 3.0 template.  Are you still updating for this tutorial, or can I work off of master as the lastet and add these items in a new PR without danger of duplicating work?  (I will put you on the review.)

**Comment by bradygaster** [comment]
@wadepickett - apologies if my edits caused frustration or confusion. I will stay out of this one until you let me know you're all good and then I will get back in. Apologies again - I will shift focus on another article I've been wanting to update unrelated to SignalR.

**Comment by wadepickett** [comment]
@bradygaster ,  no worries.  Its all good, and thanks for your help.  I am no longer in this tutorial.  Everything updated that I came to do.
