### ISSUE TITLE
Need update screenshot SignalR tutorial use Visual Studio 2019

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore.Docs#13917]
Content https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#create-a-web-project

Need update screenshot SignalR tutorial use Visual Studio 2019

**Comment by BrennanConroy** [comment]
If you select 3.0-preview you'll see updated docs with VS 2019.

I'm not sure what the policy is for updating previous docs with new VS. We probably are going to keep 2.2 as-is, otherwise every new tooling will need a ton of updates to docs.

cc @guardrex

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13919.

**Comment by guardrex** [comment]
@donhuvy Just a quick FYI: If you use the feedback form at the bottom of the topic, it opens the issue with our metadata, which helps us work it. I moved this over to #13919 using that approach ... you can see how it has this nice side-effect of automatically pinging the topic author.
