### ISSUE TITLE
Options pattern in ASP.NET Core - is not easy to read

### ISSUE THREAD

**Issue by jeswin** [aspnet/AspNetCore.Docs#13910]
The link https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2 is the first result on Google for "IOptions asp.net core".  However the text is very difficult to follow for someone looking to accomplish the simple task of attaching Options to an Asp.Net Core Web Application. Perhaps a more task-oriented writing style could be more helpful.

This following is quite subjective, so feel free to ignore some/all of these:
- Address the most common usecases first, with code examples. (Such as config via appsettings.json and Env variables)
- Leave out things like  Interface Segregation Principles. Not relevant or necessary. Btw, if the intent is to target a technically proficient audience, then the "How to dowload this sample" link seems silly.
- The first paragraph (a fairly good sized one) deals with Options interfaces. Again, not very useful since I don't even know how to use this yet. IOptionsMonitorCache<TOptions> is certainly an advanced configuration feature;  I quickly skip the entire paragraph since it makes no sense to me yet.
- "General options configuration is demonstrated as Example #1 in the sample app." Opening the sample along with this article is a distraction. Give us a quick, simple How-To first.
- Next is a reference to Constructor Depdency Injection pattern. Most people who are on the IOptions page already know this. For the rest, it is just a distracting link. We're trying to get something done quickly.
- One large section of code about IndexModel. No idea what this is.
- Next: Configure Options with a Delegate?  Is that the most basic way to get things done.  I'm still looking for how to load stuff from appsettings and env variables.
- "Suboptions configuration is demonstrated as Example #3 in the sample app.". Again, difficult style.

I could go on but stopping here. IMHO, the article needs to be rewritten to address the actual needs of developers. 

Sorry for being a little harsh.

**Comment by guardrex** [comment]
Thanks for the feedback @jeswin!

@HaoK, it's been a while since we've worked on and taken an overall look at this topic. However, I can't get to this issue/topic with my current priority list of issues until we get past 3.0 RTM. 🏃🏃😅 I'll mark this for the backlog for now, and we can take a look when the schedule opens up a bit.

**Comment by tseward** [comment]
Agree on this, the article is near impossible to read. The [sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/configuration/options/samples/3.x) isn't any better using multiple different approaches within the same sample. The sample needs to be split to a per-approach basis.

**Comment by guardrex** [comment]
We aren't receiving negative feedback to that degree. Although opportunities for improvement are always likely, I have several counterpoints and disagreements with @jeswin's remarks. I'll answer the points individually by the end of the year. We're 🏃 on high priority doc issues at the moment, so those issues must take priority at the moment.

**Comment by Rick-Anderson** [comment]
This is an advanced topic. We'll review this issue next time we update the doc.
