### ISSUE TITLE
Need update tutorial ASP.NET Core MVC with Entity Framework use Visual Studio 2019

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore.Docs#13918]
Content https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#create-web-app

Need update tutorial ASP.NET Core MVC with Entity Framework use Visual Studio 2019

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13920.

Use the feedback form at the bottom of any topic. I sent a note on the other issue ... you probably just haven't seen it yet.
