### ISSUE TITLE
Cant run on windows container

### ISSUE THREAD

**Issue by kmukul123** [aspnet/AspNetCore.Docs#13925]
Sending build context to Docker daemon  4.791MB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
2.2: Pulling from dotnet/core/sdk
no matching manifest for windows/amd64 10.0.16299 in the manifest list entries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
cc @spboyer

**Comment by spboyer** [comment]
@kmukul123 - I was able to pull the image direct. 
```console
> docker pull mcr.microsoft.com/dotnet/core/sdk:2.2                                                                    
Pulling from dotnet/core/sdk
e46172273a4e: Downloading [>
```

Try running the `docker pull` command and/or restarting docker. (right click the whale in the task tray).

`docker pull mcr.microsoft.com/dotnet/core/sdk:2.2 `

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
