### ISSUE TITLE
[Https] Add FAQ for troubleshooting

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#13928]
From @javiercn ...

Can we add to the doc an FAQ to troubleshoot what's happening when the certificate appears to not be trusted by the browser despite running the tool? This would be per platform:

**All cases**
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust`.
* Close any open browser instance you have opened. (Cert trust is cached by the browser).

**Docker**
* If you are using docker and remove the `C:\Users\{USER}\AppData\Roaming\ASP.NET\Https` folder if you are using docker. 
* Clean your solution completely (get rid of any bin, obj folders).
* Restart visual studio/VS Code/VS Mac.

If that doesn't fix it.

**Windows**
* Check the certificates in the certificate store. There should be a `localhost` certificate with the `ASP.NET Core HTTPS development certificate` friendly name both under `Current User > Personal > Certificates` and `Current User > Trusted root certification authorities > Certificates`
* Remove all the found certificates from both Personal and Trusted root certification authorities. (Be careful not to remove the IIS Express localhost certificate)
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust` and open your app in a new browser instance.

**OS X**
* Open KeyChain Access
* Select the System keychain
* Check for the presence of a localhost certificate
* Check that it contains a `+` symbol on the icon to indicate its trusted for all users.
* Remove the certificate from the system keychain.
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust` and open your app in a new browser instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@javiercn   suppose you run

 ```
dotnet devcerts https --clean
dotnet devcerts https --trust
```

And that fails. Any advantage to next trying:

```
dotnet tool uninstall --global dotnet-dev-certs
dotnet tool install --global dotnet-dev-certs
dotnet dev-certs https --trust
```

Or is that the same thing?
