### ISSUE TITLE
Visual studio 2019, choose .NET Core, choose 3.0 , don't see web application project template

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore.Docs#13929]
(show image in new tab for bigger)

![image](https://user-images.githubusercontent.com/1328316/63364533-f9d1bf80-c39f-11e9-82dd-70cb0fcbdef2.png)

At this content 

https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio#create-the-web-app-project

If I Select .NET Core and ASP.NET Core 3.0 in the dropdowns, I cannot see web-app option (only show Blazor web application project template).

**Comment by guardrex** [comment]
Hi @donhuvy ... 

Did you select the **ASP.NET and web development** workload when you installed VS?

btw -- Please open a new issue from the feedback form at the bottom of the topic. It will automatically ping the author of the topic and provide metadata to help us work the issue. It's not a biggie, but it's a little bit helpful ...... and probably gets you a faster response from the author.

**Comment by donhuvy** [comment]
Please help me delete this issue. It should be a comment.

**Comment by donhuvy** [comment]
I curious, what is "P4"?

**Comment by guardrex** [comment]
P4 = "Priority 4" ... We usually mark a new issue with this priority level because we think that the problem isn't related to a doc fix that we'll be taking action on. If it turns out that the issue does become a work item for docs, we then elevate the priority up to one of the higher levels.
