### ISSUE TITLE
Deprecate TestServer

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore.Docs#13926]
The "Integration tests" page and [this issue](https://github.com/aspnet/AspNetCore.Docs/issues/7825) both state that `WebApplicationFactory` is the recommended way to perform integration testing. [To quote @javiercn](https://github.com/aspnet/AspNetCore.Docs/issues/7825#issuecomment-408460561):

> WebApplicationFactory is the recommended approach and that's what we want people using. TestServer is just an infrastructure concept at this point, it lacks the setup that WebApplicationFactory does for your tests to behave in a way similar to your app environment.

However, from a dev's viewpoint, it is far simpler and less code to just call

```csharp
var server = new TestServer(new WebHostBuilder())
    .UseStartup<TStartup>();

var client = server.CreateClient();
```

as opposed having to create an entire subclass of `WebApplicationFactory<TStartup>` and new that up. That means that currently, there's little incentive for a dev to use the recommended approach.

IMO `TestServer` should be marked as deprecated to guide devs to using the correct pattern. The simplest way to do this would be placing an `ObsoleteAttribute` on `TestServer` with text that refers devs to `WebApplicationFactory`.

It would probably also make sense to remove any references to `TestServer` from the "Integration tests" document too.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for your feedback @IanKemp ...

`WebApplicationFactory` uses `TestServer`, and it's an integral component of how integration testing works, so it can't be marked depreciated/obsolete. `TestServer` is only lightly mentioned in the topic where appropriate. Engineering has approved the coverage, so we'll go with what we have unless they change their mind.
