### ISSUE TITLE
[Https] Add FAQ for troubleshooting

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#13927]
Can we add to the doc an FAQ to troubleshoot what's happening when the certificate appears to not be trusted by the browser despite running the tool? This would be per platform:

**All cases**
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust`.
* Close any open browser instance you have opened. (Cert trust is cached by the browser).

**Docker**
* If you are using docker and remove the `C:\Users\<user>\AppData\Roaming\ASP.NET\Https` folder if you are using docker. 
* Clean your solution completely (get rid of any bin, obj folders).
* Restart visual studio/VS Code/VS Mac.

If that doesn't fix it.

**Windows**
* Check the certificates in the certificate store. There should be a `localhost` certificate with the `ASP.NET Core HTTPS development certificate` friendly name both under `Current User -> Personal -> Certificates` and `Current User -> Trusted root certification authorities -> Certificates`
* Remove all the found certificates from both Personal and Trusted root certification authorities. (Be careful not to remove the IIS Express localhost certificate)
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust` and open your app in a new browser instance.

**OS X**
* Open KeyCain Access
* Select the System keychain
* Check for the presence of a localhost certificate
* Check that it contains a `+` symbol on the icon to indicate its trusted for all users.
* Remove the certificate from the system keychain.
* run `dotnet devcerts https --clean` and `dotnet devcerts https --trust` and open your app in a new browser instance.

**Comment by guardrex** [comment]
This is for https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl, correct?

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13928.
