### ISSUE TITLE
gRPC Service is now a primary template

### ISSUE THREAD

**Issue by tg73** [aspnet/AspNetCore.Docs#13937]
The instructions for creating the GrpcGreeter project from VS are incorrect when using VS2019 16.3 Preview 2.0. `gRPC Service` is now it's own template, it's no longer an option under the `ASP.NET Core Web Application` template.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
@JamesNK   @JunTaoLuo would you like me to PR this today?

**Comment by JamesNK** [comment]
Go ahead
