### ISSUE TITLE
[Preview 9] Add docs for using SVGs with Blazor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore.Docs#13931]
SVGs are problematic and we need some guidance for users when using these with Blazor. Need some info we can point users to.

**Comment by SteveSandersonMS** [comment]
I don't know there's much we can say except "we don't have full support for embedding SVGs in `.razor` files". See the list of issues here: https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+svg+label%3Aarea-blazor - it's a whole bunch of stuff. If we're going to support embedded SVGs, it will require a nontrivial pass through all these scenarios, which I expect is in 5.0-timeframe thing (cc @danroth27).

External SVGs loaded via `<img src="something.svg">` should work fine.

@guardrex Where's a good place in the docs to note that we recommend the use of external SVGs, not inline ones?

**Comment by guardrex** [comment]
@SteveSandersonMS The *Components* topic is probably the best spot ... perhaps in a new section at the very bottom of it.

**Comment by SteveSandersonMS** [comment]
PR at https://github.com/aspnet/AspNetCore.Docs/pull/14115

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/AspNetCore.Docs/pull/14115.
