### ISSUE TITLE
@bind-Value is not permitted

### ISSUE THREAD

**Issue by nkritikos** [aspnet/AspNetCore.Docs#13938]
When im trying to use @bind-value,  compiler throws error:
error CS0131: The left-hand side of an assignment must be a variable, property or indexer

dotnet build version :
Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core

**Comment by guardrex** [comment]
@nkritikos Not enough to go on there. Please show:

* The full component.
* Your SDK version (`dotnet --version`).
* VS version (**Help** > **About Microsoft Visual Studio** > **Version** line).

**Comment by nkritikos** [comment]
```
<div>
    @if (uiElement==null)
        {
        <p><em>Loading...</em></p>
        }
        else
        {
                @switch (uiElement.UIElementType)              
                {
                    case UIBuilder.UIElementTypeEnum.Editor:
                    <div>                   
                     <label>@uiElement.Caption</label>                     
                     <InputText id=@GetInputControlID(uiElement) type=@GetInputType(uiElement) @bind-Value="@GetDataBind(uiElement)"/>
                     </div>
                    break;
                    default:
                    break;
                }
        }
</div>

@code {    
    [Parameter]
    public UIBuilder.UIElement uiElement  { get; set; }

    [CascadingParameter(Name="modelBaseTable")]
    public System.Data.DataTable modelBaseTable   { get; set; }


    System.Data.DataRow modelBaseRow;

    private string GetInputType(UIBuilder.UIElement uiElement){
       return uiElement.InputType();
    }

    private string GetInputControlID(UIBuilder.UIElement uiElement){
       return uiElement.Key();
    }  

    private string GetDataBind(UIBuilder.UIElement uiElement) {
        modelBaseRow = modelBaseTable.Rows[0];
        return "@modelBaseTable" + "." + uiElement.RelatedField.FieldName ;
    }

}

```




$ dotnet --version
3.0.100-preview8-013656

Visual Studio Core
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by guardrex** [comment]
I'm not aware that you can assign anything other than a property for binding. I'm also not aware that the `InputText` component can be used outside of an `EditForm`.

Recommend that you open an engineering issue showing that code and asking how it might be composed. https://github.com/aspnet/AspNetCore/issues
