### ISSUE TITLE
Comma on last line of enrollments array

### ISSUE THREAD

**Issue by aprykhus** [aspnet/AspNetCore.Docs#13948]
There's a comma on the last line of the enrollments array in DbInitializer.cs code, line 65.

It's
new Enrollment{StudentID=7,CourseID=3141,Grade=Grade.A},
The comma shouldn't be there, just like the students and courses arrays:
new Enrollment{StudentID=7,CourseID=3141,Grade=Grade.A}

The comma causes the Enrollments table to be blank on starting the app. I had to delete all rows in Students and Courses tables in LocalDB and RESEED the identity column on the Students table to get it to work after removing the comma at the end of line 65.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Trailing comma's don't impact the code. We should probably remove it anyway.
Some folks like them, especially in seed code. It make it easier to copy/paste/edit rows.

cc @tdykstra

**Comment by Rick-Anderson** [comment]
We'll fix this in the next doc sweep. Since it's a style issue, closing.
