### ISSUE TITLE
ASP.Net Core  sample doesnt work on Learn site

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore.Docs#13947]
_From @kumarmohe on Sunday, August 18, 2019 5:17:05 PM_

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

ValuesContoller is not created, instead it creates WeatherForecastController.cs. So "dotnet run" command fails.

Thanks,
Mohan

_Copied from original issue: dotnet/core#3210_

**Comment by scalablecory** [comment]
_From @leecow on Wednesday, August 21, 2019 4:25:21 PM_

It looks like an update to the sample application was introduced in the 3.0 preview templates. `dotnet run` should still work but you'll need to enter `http://localhost:5000/WeatherForecast` into the browser to see output from the service.

@bradygaster and @rowanmiller to decide on how to update the sample.

**Comment by scalablecory** [comment]
_From @rowanmiller on Wednesday, August 21, 2019 5:42:45 PM_

The tutorial is written for the latest stable release of .NET Core (currently 2.2). We'll upgrade it to 3.0 once we reach stable release of 3.0.

**Comment by scalablecory** [comment]
_From @kumarmohe on Wednesday, August 21, 2019 6:23:00 PM_

> It looks like an update to the sample application was introduced in the 3.0 preview templates. `dotnet run` should still work but you'll need to enter `http://localhost:5000/WeatherForecast` into the browser to see output from the service.
> 
> @bradygaster and @rowanmiller to decide on how to update the sample.

Yeah. Instead of adding a new controller, the old ValuesContoller.cs is good enough.

**Comment by rowanmiller** [comment]
I don't think there is any work to do here. The tutorial is intentionally designed to work with the current stable SDK. We're in the unfortunate situation where that means it doesn't work with 3.0 previews, but we don't want to update it to be based on 3.0 until that has reached stable release.

**Comment by Rick-Anderson** [comment]
cc @scottaddie

**Comment by bradygaster** [comment]
agreed with @rowanmiller but i **do** think that, once the 3.0 stuff GA's, we should update this learn thread to reflect the new template structure. What say you, @scottaddie and @CamSoper?

**Comment by scottaddie** [comment]
I chatted with Rowan about this earlier in the week. The agreement is that the tutorial will be retired in favor of an MS Learn module. The following issue was created to track that work: https://github.com/aspnet/AspNetCore.Docs/issues/13934. The current thinking is that we'll start work on that issue shortly after 3.0 ships.

**Comment by rowanmiller** [comment]
Prior to retiring any tutorials, we will upgrade them all to 3.0 once it reaches stable release

**Comment by Rick-Anderson** [comment]
@wadepickett  is this something you could do?

**Comment by rowanmiller** [comment]
I can take care of this. I'll get it updated later today.

**Comment by rowanmiller** [comment]
The changes are a little more complicated than I had hoped, so I will finish making them tomorrow.

**Comment by rowanmiller** [comment]
Just confirming that the tutorial has been updated

**Comment by wadepickett** [comment]
@rowanmiller , should I close this one?  It sounded like yo updated the tutorial and this is now resolved?

**Comment by rowanmiller** [comment]
Yep agreed 👍
