### ISSUE TITLE
Authorize OAuth2 Token is completely Missing

### ISSUE THREAD

**Issue by kambleaa007** [aspnet/AspNetCore.Docs#13950]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

- Explain why this topic is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

services.AddSwaggerGen(c =>
            {c.AddSecurityDefinition("oauth2", new OAuth2Scheme
                {}
             });

is missing completely

**Comment by guardrex** [comment]
Hello @kambleaa007 ... There is a feedback form at the bottom of every topic. Could you please close this and re-open using the form on the topic? It will add metadata to the issue, and it will also automatically ping the author of the topic to take a look at your issue.

**Comment by kambleaa007** [comment]
I think, i have to discus this issue with internal network, to get swagger enabled token, if still issue persists i will reopen or close the same,
@guardrex  Thanks buddy
