### ISSUE TITLE
Add warning to use dotnet pack instead of nuget pack

### ISSUE THREAD

**Issue by mcm-ham** [aspnet/AspNetCore.Docs#13951]
It could be helpful to add a warning on this page that you need to use `dotnet pack` instead of `nuget pack`. If you do the later views within package do not work and took me awhile to figure out my mistake. Seems like confusion other developers experienced https://stackoverflow.com/q/52451475/222748

Because `dotnet nuget pack` didn't work and `dotnet nuget --help` gave no information pack existed I then downloaded the latest nuget.exe from https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>You need to use `dotnet pack` instead of `nuget pack`.

@pranavkm should I add this to the article?

**Comment by zbecknell** [comment]
I was chasing my tail trying to find this solution. Thank you mcm-ham!

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Create reusable UI using the RCL project #16639

**Comment by MackinnonBuck** [comment]
This was done in https://github.com/dotnet/AspNetCore.Docs/pull/16414
