### ISSUE TITLE
[Razor class libraries] Add section about typescript integration with razor class libraries

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#13969]
We have users asking how to do this.
The recommendation is:
* Put your ts files outside of the wwwroot folder (inside a `Client` folder for example).
* Configure the typescript build output to go to wwwroot. (Can be done with `<TypescriptOutDir>wwwroot</TypescriptOutDir>`)
* Include the TypeScript target as a dependency of the ResolveCurrentProjectStaticWebAssets target by adding this inside a `PropertyGroup` in your project
```
    <ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
      TypeScriptCompile;
      $(ResolveCurrentProjectStaticWebAssetsInputs)
    </ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
```

@guardrex

**Comment by springy76** [comment]
According to https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets I added `<ResolveCurrentProjectStaticWebAssetsInputsDependsOn>TypeScriptCompile;$(ResolveCurrentProjectStaticWebAssetsInputs)</ResolveCurrentProjectStaticWebAssetsInputsDependsOn>` but only get:

C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(266,61): error MSB4057: The target "TypeScriptCompile" does not exist in the project.

**Comment by guardrex** [comment]
@springy76 ... Open a new issue using the feedback form at the bottom of the topic.

**Comment by javiercn** [comment]
@springy76 You need to have the typescript compiler package installed.

**Comment by guardrex** [comment]
Discussion moved to #14633.
