### ISSUE TITLE
This only seems to work in a Web project

### ISSUE THREAD

**Issue by Sodoshi** [aspnet/AspNetCore.Docs#13964]
If I set Project Sdk="Microsoft.NET.Sdk.WindowsDesktop" and use the latest packages (including prerelease) on dotnetcore 3.0, then .ConfigureWebHostDefaults is unavailable. WebHost.CreateDefaultBuilder still works, but this appears to be being deprecated. Advise? (No aspnetcore3.0 for WindowsDesktop?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sodoshi ... That's a beyond the scope of this doc set (we're web app :cat2: over here :smile:). Recommend that you ask that on the dotnet/SDK repo :point_right: https://github.com/dotnet/sdk/issues

Search first (including the closed issues there) because someone may have already asked about it.

**Comment by Sodoshi** [comment]
Heh, thanks. May as well give up on Project Bedrock if you're not going to play nice together :)
