### ISSUE TITLE
No details about from where external auth buttons appear

### ISSUE THREAD

**Issue by daviatorstorm** [aspnet/AspNetCore.Docs#13960]
Tried to find where the google button came from. This details weren't specified in documentation. Then I found the source code of project that already have this button. And only then I got where the external authentication buttons coming from. https://github.com/AnkitSharma-007/ASPCore.GoogleAuth

```
@{
                var loginProviders = (await SignInManager.GetExternalAuthenticationSchemesAsync()).ToList();
                if (loginProviders.Count == 0)
                {
                    <div>
                        <p>
                            There are no external authentication services configured. See <a href="https://go.microsoft.com/fwlink/?LinkID=532715">this article</a>
                            for details on setting up this ASP.NET application to support logging in via external services.
                        </p>
                    </div>
                }
                else
                {
                    <form asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                        <div>
                            <p>
                                @foreach (var provider in loginProviders)
                                {
                                    <button type="submit" class="btn btn-default" name="provider" value="@provider.Name" title="Log in using your @provider.DisplayName account">@provider.Name</button>
                                }
                            </p>
                        </div>
                    </form>
                }
            }
```

Please, add this detail to documentation.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by lzinga** [comment]
I just dealt with this myself, it looks like they moved the entirety of the account login code into its own package/library. You can get your project to scaffold it by executing the following - 
`dotnet tool install --global dotnet-aspnet-codegenerator`
`dotnet aspnet-codegenerator identity -dc WebApplication1.Data.ApplicationDbContext`
 and you change the namespace location to where your DbContext is.

I believe one or both of these nuget packages is required as well. `Microsoft.VisualStudio.Web.CodeGeneration.Utils` and `Microsoft.VisualStudio.Web.CodeGeneration.Design`

You can read more about it here - https://devblogs.microsoft.com/aspnet/aspnetcore-2-1-identity-ui/. Not sure if this is exactly what you were asking but I stumbled a bit with it myself.
