### ISSUE TITLE
Document enhancement request

### ISSUE THREAD

**Issue by RandyDaddis** [aspnet/AspNetCore.Docs#13979]
[Disable shadow copying](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#disable-shadow-copying)
does not mention changing properties to enable copying xunit.runner.json to the bin folder where xUnit.net runners can find it.
cref:
[Configuring xUnit.net with JSON](https://xunit.net/docs/configuring-with-json.html)
Step 2. change setting for Copy to Output directory to Copy if newer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @RandyDaddis ... It's in the sample app but not in the topic, so I'll add a bit on that.

```xml
<ItemGroup>
  <Content Update="xunit.runner.json">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
</ItemGroup>
```
