### ISSUE TITLE
"WebSockets without SignalR" Incorrect link 

### ISSUE THREAD

**Issue by mtttcgcg** [aspnet/AspNetCore.Docs#13977]
The ""WebSockets without SignalR" sidebar link links to this article instead of the desired article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
That's the correct article. But I do agree it's confusing to have a big heading with "SignalR"
