### ISSUE TITLE
Final version of the sample  not working 

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#13978]
I downloaded and extracted the latest version of the samples from Github. While attempting to run the completed app with different versions of the final, it didn't work as per the following observations (using Visual Studio Community 2019 preview for running all the versions (16.3.0 Preview 2) :

Final - Tried to register a new user. It takes forever so waited for a few minutes before giving up. (Created a user secret and also commented out SeedData when update-database failed)
Final 2 -    Runtime error while trying to run with details as System.AggregateException (Created the user secrets for this project too)
  HResult=0x80131500
  Message=One or more errors occurred. (Value cannot be null.
Arg_ParamName_Name)
  Source=ContactManager
  StackTrace:
   at ContactManager.Program.Main(String[] args) in G:\ASP.NetCore\AspNetCore.Docs-master\aspnetcore\security\authorization\secure-data\samples\final2\Program.cs:line 40

Inner Exception 1:
ArgumentNullException: Value cannot be null.
Arg_ParamName_Name
            
Final 2.1 - Login and new Regsitration seem to be taking forever although there is no runtime error while running the solution. After a couple of minutes Login and Registration still not complete, so closed the app.

Final 3 - New Regsitration seems to be taking forever although there is no runtime error while running the solution. After a couple of minutes, Registration still not complete, so closed the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#create-the-starter-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authorization/secure-data/samples/final3 requires ASP.NET Core 3.

**Comment by Rick-Anderson** [comment]
Use the debugger to figure out what's going on,

**Comment by krchome** [comment]
As I wrote above, I tried with Visual Studio Preview 2019 for running all the versions where I have 16.3.0 Preview 2 that has ASP.NET Core 3 

Quoting yourself "Use the debugger to figure out what's going on," please let me know how could one use the debugger if there are apparently no errors at runtime (in debug mode)?
