### ISSUE TITLE
Ajax Post Clearing all Properties of the Page

### ISSUE THREAD

**Issue by krishnamohan1990** [aspnet/AspNetCore.Docs#13987]
[EDIT by @guardrex to code fence the markup for display.]

When we do form Ajax-POST in a .net core 2.2 Page like below
`<form asp-page-handler="Search" data-ajax="true" data-ajax-method="POST">` 
it is hitting the correct handler and clearing all the other properties which were not set in POST handler. I think its better to update the Page partially i.e. only changed properties and other properties should remain as it is. (after post returning to the same Razor Page)

**Comment by guardrex** [comment]
The behavior is by-design. There's a note on it in the *Model Binding* topic (*[Bind] attribute* section) ...

https://docs.microsoft.com/aspnet/core/mvc/models/model-binding#bind-attribute

We only handle docs here, so we can't address engineering design considerations on the repo. You would need to take this up further with engineering.
