### ISSUE TITLE
Depreciated (documentation)

### ISSUE THREAD

**Issue by thurfir** [aspnet/AspNetCore.Docs#13981]
The NodeServices and SpaServices are being depreciated: https://github.com/aspnet/AspNetCore/issues/12890

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by pkellner** [comment]
When I look at the preview docs for asp.net core 3, this shows up and looks like a first class citizen to the docs. They date of 2019 adds to the confusion. Seems to me that if it is going to stay there should be a big red paragraph on the top that says ‘DO NOT USE FOR NEW PROJECTS’
