### ISSUE TITLE
Issue with `User` declaration in systemctl service file

### ISSUE THREAD

**Issue by itanex** [aspnet/AspNetCore.Docs#13997]
I kept having issues getting the service started after using this pages definition file. I kept getting a 217/USER error and I could not determine why. 

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
```

I finally decided to try without a User declaration since my searches kept returning details about EL7 having issues with this declaration. This solved my problem. Why?

It would be helpful to provide more details about the user entry in this file. Providing a how/why/where and pointing out to external resources that are beyond the scope (like creating, managing users) that directly relate to this hosting solution would be beneficial for all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#monitor-the-app)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @itanex 

> having issues getting the service started after using this pages definition file

@shirhatti, do you want to address that here or on an engineering issue?

> provide more details about the user entry in this file

We might be able to cross-link to an external resource. All we currently have is ...

> ... user defined here must be created first and given proper ownership for files.

@shirhatti, do you want to cross-link to anything or expand on that remark? If you're not sure what we could link to, I'll see what I can find.

**Comment by itanex** [comment]
@shirhatti Is there any details you could provide?

**Comment by guardrex** [comment]
@shirhatti Is this actionable at all? If not, we can close.

**Comment by itanex** [comment]
@guardrex there has not been any contact from him.

**Comment by guardrex** [comment]
He was OOF for bit 🏖, but he'll respond. They're always 🏃😅.

**Comment by guardrex** [comment]
@shirhatti Should we keep this open?

**Comment by shirhatti** [comment]
IMO the document already attempts to address this issue. We should maybe clean up the verbiage a little bit and draw more attention to it.

> If the user www-data isn't used by the configuration, the user defined here must be created first and given proper ownership for files.

The cause for failure as described by @itanex is because the `www-data` user doesn't exist already.

**Comment by guardrex** [comment]
Ok, thanks. I'll give that go and ping u on the PR.
