### ISSUE TITLE
How to host and serve wwwroot from CDN?

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#13998]
How to host and serve wwwroot from CDN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @khteh ... Static File Middleware doesn't offer any scenario for CDNs, and it would defeat the purpose of using a CDN to do so. Use direct links to the content on the CDN and move the static assets to the CDN storage manually or using a bundle+minify workflow. For example, I used to use a gulp.js plugin to automatically move the static assets up to Azure Storage (linked to an Azure CDN).
