### ISSUE TITLE
Unit Test Tutorial For Razor Page TryUpdateModelAsync

### ISSUE THREAD

**Issue by Hugozys** [aspnet/AspNetCore.Docs#14009]
#### Search Effort I made
- Google: Unit Test TryUpdateModelAsync
- Found solution on stackoverflow
- Found this solution only fits to MVC instead of Razor Page

#### What it is about
 Razor Page is the latest technology Microsoft introduced for ASP.NET Core users. There is already tutorial introducing to new users how to do unit test when using Razor Page to develop Web APP. However, I think the tutorial doesn't cover some of the most important for `CU` portion of CRUD operations.

 In ASP.NET Core Web App tutorial, Microsoft recommends using `TryUpdateModelAsync` method to perform Create and Update operation. However, unit-testing action that involves TryUpdateModelAsync in Razor Page seems difficult and cumbersome since `TryUpdateModelAsync` is implemented in such way that requires many internal dependencies. Trying to find all these relationships and mock them is very time-consuming and needs to have a deep understanding on the source code, which seems not very user friendly.

On stackoverflow there is a great solution for unit testing `TryUpdateModelAsync` when using MVC instead of Razor Page:  https://stackoverflow.com/questions/39259025/asp-net-core-mvc-controller-unit-testing-when-using-tryupdatemodel.
However, this doesn't work for Razor Page because the method with the same name is an internal protected method which makes it inaccessible from outside world while it's a public method in MVC, making it adaptable. It would be really helpful if the tutorial could include the idea of unit testing for this part. 

A simple example will be the following:
```c#
 public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (await TryUpdateModelAsync<Post>(Post, "Post", p => p.Title, p => p.SubTitle, p => p.Author, p => p.Content, p => p.CategoryID)){
                if (Post.CategoryID == null){
                    Post.Category = null;
                }
                //more logic elided
                return RedirectToPage("./Index");
            }
           //more logic elided
            return Page();
```
Without proper dependencies setup, code flow can never pass through `TryUpdateModelAsync` method (exception) when doing unit testing. And it is difficult for starters to figure out the dependency setup.
#### Location
It could be put under `ASP.NET Core 2.2/Test, Debug, Troubleshoot/Razor Pages Unit Test`

#### Abstract
I think that this topic just extends the Razor Page Unit Test tutorial, making it complete.

#### Outline
- Unit Test in Razor Page
   - Test DAL
   - Test Page Model Method
          - Test OnGetAsync
          - Test OnPostAsync
                  - Test simple OnPostAsync
                  - Test complex OnpostAsync (involves TryUpdateModelAsync)

**Comment by guardrex** [comment]
Moved to the tracking issue for this topic: **Integration tests MASTER issue** #16341
