### ISSUE TITLE
Production code clarification

### ISSUE THREAD

**Issue by HarleyPebley** [aspnet/AspNetCore.Docs#14008]
In the "Apply the migration to the existing database" section, in the discussion about what a production app would do, is it correct to assume the Down method should also be modified? Perhaps an explicit statement re: the Down method would be good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you need a down method in production.
