### ISSUE TITLE
OnModelCreating code formatting

### ISSUE THREAD

**Issue by HarleyPebley** [aspnet/AspNetCore.Docs#14006]
In the "Update DB Context" section, the entire OnModelCreating method is new but only some of it is highlighted. Also, the new .Entity&lt;&gt;.ToTable() calls aren't needed as correctly mentioned in the following "Fluent API alternative to attributes" section. As I understand it, the only thing that's really needed is the "HasKey" statement at the end. I'd recommending either highlighting the entire method or only have the last statement in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in the 3.0 version.
