### ISSUE TITLE
Table name is 'dbo.Student', not 'Student'

### ISSUE THREAD

**Issue by tg73** [aspnet/AspNetCore.Docs#14019]
A minor issue: in section `view-the-database`, the table name displayed in SSOX is `dbo.Student`, not `Student`.

Using VS 2019 16.3.0 Preview 2.0 with .NET Core 3.0 Preview 8.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
But in other DB's, it's Student. That shouldn't confuse anyone.
