### ISSUE TITLE
Is the route parameter case-insensitive?

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/AspNetCore.Docs#14017]
The [Razor component](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#route-parameters) allows us to pass parameter by routes:

> Components can receive route parameters from the route template provided in the @page directive. The router uses route parameters to populate the corresponding component parameters.

```cshtml
@page "/RouteParameter"
@page "/RouteParameter/{text}"

<h1>Blazor is @Text!</h1>

@code {
    [Parameter]
    public string Text { get; set; }

    protected override void OnInitialized()
    {
        Text = Text ?? "fantastic";
    }
}
```

If I change the `@page "/RouteParameter/{text}"` to `@page "/RouteParameter/{TeXt}"`, it also works. Does that mean the route parameter is case-insensitive? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-handling)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by newbienewbie** [comment]
Ok, it seems that all the component parameter names are case-insensitive?

https://github.com/aspnet/AspNetCore/blob/460f9b63e9db9f4a3a542fcdc4204e29ca90f123/src/Components/Components/src/Reflection/ComponentProperties.cs#L80:

```csharp
if (string.Equals(parameterName, writers.CaptureUnmatchedValuesPropertyName, StringComparison.OrdinalIgnoreCase))
```

**Comment by guardrex** [comment]
Correct. It's covered in the ASP.NET Core *Routing* topic and the Blazor *Routing* topic ...

* https://docs.microsoft.com/aspnet/core/fundamentals/routing#route-template-reference
* https://docs.microsoft.com/aspnet/core/blazor/routing#route-parameters
