### ISSUE TITLE
Data migration issue

### ISSUE THREAD

**Issue by HarleyPebley** [aspnet/AspNetCore.Docs#14012]
I followed the data migration path rather than the drop database/create database path. When I went on to the next section of the tutorial (6 of 8) and tried to see the newly created Courses page, I got "SqlException: Invalid object name 'Departments'. Looking at the DB in SSOX, I only see dbo.Course, dbo.Enrollment and dbo.Student. I interpret this to mean that the database hasn't been migrated. I put a breakpoint in ComplexDataModel.Up and it never gets hit. I don't know enough about the internal structures to be able to diagnose it any more at this point so I followed the Drop/Recreate path and it worked as expected.  So it seems there's some problem somewhere in the migration, but it's not clear where. If there's someplace that talks about how to diagnose EF issues or goes into the structure of EF DBs, perhaps a link to that might be useful for when the happy path fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HarleyPebley  you did the right thing. I think we should delete the `migration path` and just outline what you should do. cc @tdykstra
