### ISSUE TITLE
Link to 'Reading related data' should be 'Read related data'

### ISSUE THREAD

**Issue by tg73** [aspnet/AspNetCore.Docs#14020]
In the `update-the-details-page` section, the link to `Reading related data` actually links to an article named `Read related data`.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.0)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Links frequently don't have the same title.
