### ISSUE TITLE
Move cert instructions to an include

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14040]
Everything between `## Run the app` and `## Examine the project file` should be an include.

Once you have the include, use it in this tutorial, the MVC tutorial, and everywhere else we have these instructions.

cc @scottaddie  - shouldn't this be an include. I think that's why it was missed in #13552

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio#run-the-app)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
ping @wadepickett

**Comment by wadepickett** [comment]
Thanks @Rick-Anderson, what priority label should I set for this one?
