### ISSUE TITLE
3.0.0-rc1 ActionFilter issue

### ISSUE THREAD

**Issue by phillipbritain** [aspnet/AspNetCore.Docs#14050]
I can't get a custom ActionFilter to fire off it's OnActionExecuting method.

Here is my custom ActionFilter:

```
public class ValidateModelActionFilter : IActionFilter
{
	public void OnActionExecuting(ActionExecutingContext context)
	{
		if (!context.ModelState.IsValid)
		{
			context.Result = new BadRequestObjectResult(context.ModelState);
		}
	}

	public void OnActionExecuted(ActionExecutedContext context)
	{
		// Do something after the action executes.
	}
}
```

And here is where I call it in Startup.cs ConfigureServices:

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddControllers(x => x.Filters.Add(typeof(ValidateModelActionFilter)));
    ...
}
```

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

That doc hasn't been updated for 3.0 yet.
