### ISSUE TITLE
Needs pipeline graphic for ApiController

### ISSUE THREAD

**Issue by douglasg14b** [aspnet/AspNetCore.Docs#14051]
Similar to the Filters one here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters/_static/filter-pipeline-1.png?view=aspnetcore-2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#binding-source-parameter-inference)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by pranavkm** [comment]
@douglasg14b API controllers are just regular controllers with some opinionated behavior. The filter pipeline is the same.

**Comment by douglasg14b** [comment]
I mean the specific opinionated behaviors of the API Controller. Correct me if I'm wrong, but some of those behaviors are part of the filter pipeline? It would be nice to see in what order those are executed.

**Comment by pranavkm** [comment]
> I mean the specific opinionated behaviors of the API Controller

Most if not all of the actual behavior should be documented here: https://docs.microsoft.com/en-us/aspnet/core/web-api/index. 

Some of these are implemented as filters, but they're just regular action or result filters:

* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ModelStateInvalidFilter.cs
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ClientErrorResultFilter.cs

There's really nothing special except that they are on by default when MVC configures a controller with `ApiControllerAttribute`.

**Comment by douglasg14b** [comment]
Ah! Gotcha.

**Comment by scottaddie** [comment]
I'll add some clarification to the doc based on Pranav's response above.
