### ISSUE TITLE
How to automatic save "swagger.json" to folder when debug on web API ? 

### ISSUE THREAD

**Issue by uthens** [aspnet/AspNetCore.Docs#14055]
Hi All,
Now i started to used Swagger and Docfx for generate on REST API document.

To related on this issue : 
&gt;&gt; https://github.com/dotnet/docfx/issues/5012
&gt;&gt; https://dotnet.github.io/docfx/

How to automatic save swagger.json file to folder for support with Docfx, when i run debug on web APIs project ? 
My project to used .NET Core 2.2 on vs 2019

Thanks you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16195
