### ISSUE TITLE
Document RenderFragment ChildContent property name restriction

### ISSUE THREAD

**Issue by mv10-work** [aspnet/AspNetCore.Docs#14076]
Apparently (and bizarrely) a `[Parameter] RenderFragment` property must always be named `ChildContent`. It seems this was documented on the old Blazor site, but isn't mentioned here. The link [here](https://github.com/aspnet/Blazor/issues/1378#issuecomment-417904030) redirects to a missing #child-content anchor by way of explanation of this limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to Blazor in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mv10-work ... It's in the NOTE box at :point_right: https://docs.microsoft.com/aspnet/core/blazor/components#child-content
