### ISSUE TITLE
Change Article Reference from Degraded Status to Unhealthy Status

### ISSUE THREAD

**Issue by bdschaap** [aspnet/AspNetCore.Docs#14078]
This section of the article states that it's returning a degraded status.  It's actually returning an unhealthy status which has a different meaning than degraded per the failure status values.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#metric-based-probe-with-a-custom-response-writer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#customize-the-http-status-code)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @bdschaap ... there were changes along the way to how degraded and unhealthy were handled, and I think that inconsistency slipped by one of our topic updates that responded to the changes. I'll fix it now. Thanks for calling it out.
