### ISSUE TITLE
The package.json in the ASP.Core React template is outdated, how to update?

### ISSUE THREAD

**Issue by idevtech** [aspnet/AspNetCore.Docs#14073]
The ASP.Core React project template for VS2019 is outdated. The react packages are not current. Despite multiple tries I can not update the packages correctly due to dependency issues. Is there a more updated version of this template?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@idevtech The most recent template's *package.json* file can be found at https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/ClientApp/package.json. For issues with the templates, please open an issue in the aspnet/AspNetCore repo.
