### ISSUE TITLE
Reactjs.net application is not running in aps.net core 3.0.100-preview8-013656

### ISSUE THREAD

**Issue by MohamedSahir** [aspnet/AspNetCore.Docs#14075]
I have downloaded a guided project from the Reactjs.net and followed the recommended steps and install the dependencies and while build the application , get a below error.

project Url :
https://github.com/reactjs/React.NET/tree/master/tutorial-code

Dotnet Sdk Version :

<img width="260" alt="dotnet sdk" src="https://user-images.githubusercontent.com/20682302/63931796-9583bf80-ca73-11e9-98d3-e76de7f09cfb.PNG">

Compiler Error on build
<img width="921" alt="compiler error" src="https://user-images.githubusercontent.com/20682302/63931813-9caacd80-ca73-11e9-8b07-94418f1a3bdd.PNG">

Is .net core 3 support reactjs.net , if it support kindly guide me

**Comment by guardrex** [comment]
@MohamedSahir Your VS must be VS Preview to use the 3.0 Preview8 SDK. You can get it here: https://visualstudio.microsoft.com/vs/preview/
