### ISSUE TITLE
Section Set indentation size is duplicated

### ISSUE THREAD

**Issue by GoHajime** [aspnet/AspNetCore.Docs#14077]
The section Set indentation size appears twice on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16842b60-b268-a322-8078-c0b27c57fa7d
* Version Independent ID: d63c12f3-220e-9067-ead5-90e644c06591
* Content: [Test web APIs with the HTTP REPL](https://docs.microsoft.com/en-us/aspnet/core/web-api/http-repl?view=aspnetcore-2.2&tabs=windows#feedback)
* Content Source: [aspnetcore/web-api/http-repl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/http-repl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @GoHajime ... The examples are correct: The first one shows 2-space indent, and the second example shows the JSON with the 4-space indent after changing `formatting.json.indentSize` to `4`.

**Comment by GoHajime** [comment]
Sorry for not being any clearer, but the I see the section "Set indentation size" repeated. I have attached a screenshot.

![SetIndentationSize](https://user-images.githubusercontent.com/36074739/63945907-c7624980-caa6-11e9-96eb-d60935e9e1b3.png)

**Comment by guardrex** [comment]
Oh ... The whole section! Sorry ... Another cup of coffee perhaps would have helped me out there.
