### ISSUE TITLE
Document new host matching in routing for 3.0

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#14070]
#### Explain why this topic is needed.

3.0 added a new `[Host]` attribute that can be used to match routes to the host name. This makes it easier for a single ASP.NET Core to provide content for multiple domains.

* [HostAttribute](https://github.com/aspnet/AspNetCore/blob/bcdc9b08dfbb79ca6b8780e9ef5f9cabba67f71d/src/Http/Routing/src/HostAttribute.cs)
* [Sample](https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/domain) (this sample is from 2.2 and uses a predecessor to the final version that was renamed to HostMatching and shipped in 3.0)

#### Suggest a location in the Table of Contents.

It could be added to https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.0

#### Write an abstract. In one **short** paragraph, describe what this topic will cover.

The `[Host]` attribute can be used to match routes using the host name from a request. You can use host name matching to map controllers and actions from an ASP.NET Core app to multiple domains.

**Comment by mkArtakMSFT** [comment]
@JamesNK will you be handling this? we plan to spend about a week on paying off some dept in Docs before 3.1.

**Comment by JamesNK** [comment]
I'll do it

**Comment by JamesNK** [comment]
Fixed with https://github.com/aspnet/AspNetCore.Docs/pull/15291
