### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by jesslilly** [aspnet/AspNetCore.Docs#14089]
Why is there no documentation about downloading files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There's a PR with **_many_** updates for this topic. You'll have to look at the PR to see it (the internal review topic is only available to MS workers). However, it should help. Engineering should 🤞 be reviewing it by the end of the year, possibly after 3.0 is released.

https://github.com/aspnet/AspNetCore.Docs/pull/12344
