### ISSUE TITLE
Maximumum Age of Cache

### ISSUE THREAD

**Issue by garfbradaz** [aspnet/AspNetCore.Docs#14088]
If I have a Web API that lives in Kubernetes, outside of cache expiration settings, in what scenarios is the `MemoryCache` cleared down?

If I have a JSON Payload I want to cache (key is the QueryString) for data that doesnt change regulary (or at all), if I set the cache expiration to 2 weeks, is there any other scenario the cache is cleared down?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#caching-basics-1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
When the app restarts. Per the article, never depend on the cache.
