### ISSUE TITLE
Docs page render issue

### ISSUE THREAD

**Issue by JVimes** [aspnet/AspNetCore.Docs#14092]
Sorry, I can't figure out where else to report this. The [Kestrel page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2) has certain lines of code highlighted. The highlight is off-set from the code when Chrome is zoomed in.

I'll move this issue if someone can tell me the right place to report it. Thanks!

Example:

![2019-08-30_13h35_16](https://user-images.githubusercontent.com/6148201/64047538-4a79b300-cb2c-11e9-99f2-895df48f88c8.png)

**Comment by guardrex** [comment]
Hello @JVimes ... Report that here :point_right: https://github.com/MicrosoftDocs/feedback

**Comment by JVimes** [comment]
Thanks. Reported [here](https://github.com/MicrosoftDocs/feedback/issues/1887).
