### ISSUE TITLE
HTTPS vs TLS

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#14095]
The gRPC document switches between talking about HTTPS and TLS. I think it is confusing for readers.

ASP.NET documentation mostly uses HTTPS:
* https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0
* https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0

I'd like to understand when TLS should be used vs HTTPS, and then update the gRPC documentation to be more consistent.

**Comment by JamesNK** [comment]
// @shirhatti @blowdart

**Comment by blowdart** [comment]
If it's using the HTTP protocol then it's HTTPS
If it's not, then TLS

SSL is never used.

**Comment by JamesNK** [comment]
Was fixed with https://github.com/aspnet/AspNetCore.Docs/pull/14523
