### ISSUE TITLE
How to delete a todo item from the list

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14090]
[Enter feedback here]

Can you extend the sample with "How to delete a todo item from the list"?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Legends ... That's a great idea, but we won't only because we're going to completely replace this experience with a new one. If you look at the issue for the tutorial replacement, you'll see a link to my repo sample for *Galactic Flight Finder* in the last comment. Pull that down and see how it's done there. I'm not saying that we'll use that for sure; but whatever we put up, will probably be at least similar to that sample.

https://github.com/aspnet/AspNetCore.Docs/issues/10773

**Comment by guardrex** [comment]
Oh ... one more note about that. That sample is a Pre6. There were a lot of updates between then and Preview 8. If you want to actually run that, you would need to migrate it to Pre8. Without going to all of that trouble, you can look at the code in it and see how it composes tho.

**Comment by Legends** [comment]
Thanks a lot! I found the helping piece of code instantly.

Blazor looks to me similar to React. Will there be a more detailed documentation about components and life cycle with the release of .net core 3.0?

**Comment by guardrex** [comment]
Not sure ... management probably will go over everything **_after_** 3.0 releases and figure out what else they'd like to cover.

We have a **Blazor.Docs** project that holds the issues for Blazor docs. Things that you see in the **Triage** column haven't been fully assessed by management.

https://github.com/aspnet/AspNetCore.Docs/projects/35

Right now, the engineering team and the docs team are mostly working to get everything into place for 3.0, so I don't think that there will be a lot of new coverage (e.g., new topics, new tutorials, expanded coverage) until after 3.0 ... which probably means not until 2020.

**Comment by Legends** [comment]
Thanks for the link.

But 2020??? Wasn't 3.0 planned for September 2019?

**Comment by guardrex** [comment]
Yes ... according the roadmap, that's the plan. However, there will be lingering 3.0 work on docs going out a month or two beyond the release. Then, holidays land. 🎁 I don't think major new doc work will slide in before year's end, but I'm *just guessing* based on our current workload, staffing, and past year-end/major release patterns.
