### ISSUE TITLE
Please explain how and if this works on a Mac

### ISSUE THREAD

**Issue by AskYous** [aspnet/AspNetCore.Docs#14107]
Since this is called "Windows Authentication," I would assume that this doesn't work on a mac. However, I'm not certain so it would be very good to have some documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=netcore-cli)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Correct, it's a Windows thing, and the first line calls out specific Windows-only hosting scenarios (IIS and HTTP.sys) ...

> can be configured for ASP.NET Core apps hosted with IIS or HTTP.sys.

**Comment by guardrex** [comment]
Actually ... *not so fast!* Client-wise, I see macOS users connecting. Let's ask @Tratcher ... What, if anything, would be said about macOS clients in these contexts?

**Comment by AskYous** [comment]
Our developers use Windows Authentication a lot. When I visit websites using my mac, I am able to authenticate with this pop-up which is pretty nice:

![image](https://user-images.githubusercontent.com/791996/64127636-4c7b8600-cd67-11e9-9c76-d46c2c1c5553.png)

Though when I run the app on my machine, it doesn't work (probably because my machine is not Windows). It would just be nice to have this in the documentation.

**Comment by guardrex** [comment]
As a client, yes, I don't have any info on it not working. I would think (based on what I just saw in search results) that *yes* ... it should work. Stand-by ... we'll get word back from engineering shortly if there are any caveats and perhaps if we need to address this scenario in the topic if there are any caveats (or perhaps to say that it isn't supported if that turns out to be the case).

**Comment by AskYous** [comment]
Apologies. My intention have documentation on *hosting* a Windows-authentication website on mac (for localhost testing). Not if mac users can access the site.

**Comment by guardrex** [comment]
You are correct ... you can't **_host_**.

However, let's leave this issue open until we hear back on the other point: I'm curious to know if macOS clients will work seamlessly with this scenario.

**Comment by Tratcher** [comment]
The linux hosting instructions *should* also allow you to host on macOS, but I don't know of anybody that's tried it yet.

Also, kerberos doesn't support localhost, it falls back to NTLM. Getting localhost NTLM working on a mac would be a whole different task.

**Comment by guardrex** [comment]
> The linux hosting instructions should also allow you to host on macOS

The topic doesn't address it. Given that the topic calls out 'HTTP.sys and IIS only,' it led me to believe that it wasn't even possible. How do u want to proceed?

1. Close this (e.g., lack of staffing, edge case, untested).
1. Mod the topic to add that this is possible. If so, should it say that it's supported or that it's unsupported/experimental?
1. Put this on the backlog for a look later.

**Comment by Tratcher** [comment]
@guardrex ? We already added 3.0 docs here for Kestrel + Linux (&mac?)

**Comment by guardrex** [comment]
No, we haven't ... it's not an open issue. We can use this issue if you like ... I can re-title it and put the 3.0 labels on it.

**Comment by Tratcher** [comment]
? It's right here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#kestrel

**Comment by guardrex** [comment]
Ah ... added by your PR back on June 12. I forgot about it and didn't check the 3.0 preview version (obviously). It's a tiny bit *Web Host-y*, right? `app.UseMvc();`

**Comment by guardrex** [comment]
@AskYous Flip the topic's version selector (upper-left of docs UI) to **ASP.NET Core 3.0 Preview** to see the topic that includes the content that we're discussing.

<img width="306" alt="Capture" src="https://user-images.githubusercontent.com/1622880/64191655-8bc8d600-ce3e-11e9-86fc-cd59d1c44975.PNG">

**Comment by AskYous** [comment]
@guardrex Ah! Thank you!

**Comment by guardrex** [comment]
@AskYous Yes ... I totally forgot about that PR ... probably because I was just a reviewer on it. I have a better memory for things that I wrote. You'll see a *very brief* mention of `app.UseMvc()` for `Startup.Configure` there in the 3.0 content, but that will go like this for the Generic Host (see the [migration topic](https://docs.microsoft.com/aspnet/core/migration/22-to-30) for details) ...

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapDefaultControllerRoute();
});
```

The Kestrel topic updates for 3.0 are in review. They should go in ... er ... um ... *maybe* by the end of the week, but sometime next week at the latest. There's a follow-up issue to add 3.0 content for Kestrel to the migration topic immediately after the Kestrel updates go in.

**Comment by Tratcher** [comment]
Ah, yes, UseMvc isn't in the 3.0 templates anymore. (that's not a generic host difference, just a 3.0 difference).

**Comment by guardrex** [comment]
I'll patch it by merely removing that line from that example.

@AskYous ... if you hit an engineering problem with the new bits under 3.0, you can open an engineering issue. If you hit a docs issue, open a new issue from the feedback form at the bottom of the topic.

**Comment by PouryaMontakhab** [comment]
Ah, Didn't anybody find the solution? How we can authenticate on mac machine finally?
