### ISSUE TITLE
2 Blazor WebAssembly App templates

### ISSUE THREAD

**Issue by pappasa** [aspnet/AspNetCore.Docs#14104]
When I create a Blazor App, it prompts me to choose the template, but it shows me 2 "Blazor WebAssembly App" templates as shown in the screenshot https://snipboard.io/TmdtZk.jpg . None of them works. How can I delete them, and install the latest template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pappasa ... Search the engineering issues to see if anyone has already asked about that. If not, open a new issue there and show them your screenshot. Explain to them exactly what you mean by 'None of them works.'

https://github.com/aspnet/AspNetCore/issues
