### ISSUE TITLE
Blazor signalr doesn't call OnDisconnectedAsync on custom hub

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#14100]
Not sure if I should post here or Blazor section. 

Closing browser or terminate component that contains the connection doesn't call OnDisconnectedAsync on the hub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
This feels more like a Blazor issue than a SignalR issue, though, if it is something SignalR team should be aware of that doesn't work as expected for Blazor customers, I'm all in for making the behavior consistent. Are you actually hooking into a Blazor Hub? That seems unconventional. Adding @danroth27 and @rynowak FYI

**Comment by rynowak** [comment]
> Are you actually hooking into a Blazor Hub? That seems unconventional.

Please don't do this. The Blazor Hub is internal because it's an implementation detail. We can and will make changes to the hub in the future without notice.

**Comment by Alienroid** [comment]
No, Blazor serverside uses Blazor Hub. I created a separate SignalR Core Hub because I created an app to host multiplayer games.

**Comment by Alienroid** [comment]
Actually, please close this issue. It was opened for preview 7 or 8 and in latest 3.0 release (maybe as early as preview 9), this already been resolved.
