### ISSUE TITLE
routes in response format url mappings

### ISSUE THREAD

**Issue by abhishekdixitnagarro** [aspnet/AspNetCore.Docs#14109]
route declaration is not following best practices. Please correct it or at least put a note that look into this for best practices.
This confuses the developers who are new to .net core API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@abhishekdixitnagarro  where in the doc? What do you suggest we change?

**Comment by abhishekdixitnagarro** [comment]
for example in /products/GetById/5, this is not the best practice
It should HTTP GET with url  /products/5.
If you can put saying these are not best practices will help readers.

**Comment by Rick-Anderson** [comment]
@pranavkm  30 second review.
