### ISSUE TITLE
Custom Login/Register Pages

### ISSUE THREAD

**Issue by nkaenzig** [aspnet/AspNetCore.Docs#14105]
The Login and Register forms in the template seem to come completely pre-made from IdentityServer. The html for the angular login and logout components consist entirely of one line: “{{ message | async }}”.

Is there a way to change these forms (add more fields, change design) or to use my own login page in Angular?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
You can customize them through identity
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio

**Comment by nkaenzig** [comment]
Not quite sure how to do that. Adding an example to the doc would be quite useful.

**Comment by Rick-Anderson** [comment]
@nkaenzig  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio has examples.
