### ISSUE TITLE
Add more info about the X-Original-* headers

### ISSUE THREAD

**Issue by luisabreu** [aspnet/AspNetCore.Docs#14110]
It would be useful to give more info about the X-Original-* headers. Something along the lines of this stackoverflow [answer](https://stackoverflow.com/questions/57759419/x-original-for-header-whats-its-purpose/57764700#57764700) would really clear everything up.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
