### ISSUE TITLE
Confusing Variable Names for

### ISSUE THREAD

**Issue by IainCoSource** [aspnet/AspNetCore.Docs#14114]
````html
<partial name="Shared/_ProductPartial.cshtml" for="Product">
````

It is unclear if you are passing 
````csharp
public Product Product { get; set; }
````  
or the class 
```` csharp
class Product 
````
would suggest renaming it to 

````csharp
public Product NewProduct { get; set; }
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [Partial Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@scottaddie  this is low pri. I agree it's confusing until you get used to it, but it's how the PU typically writes code. I don't think we should necessarily follow. We can think about changing this on the next doc sweep.
