### ISSUE TITLE
RequireAuthorization() on endpoints.MapControllerRoute() not working using Cookie Authentication

### ISSUE THREAD

**Issue by Stephen-Gibson** [aspnet/AspNetCore.Docs#14113]
Following the example, I attempted to set up authorization as required in MapControllerRoutes (as I'm using convention based routing) as such:
```
                app.
                .UseAuthentication()
                .UseAuthorization()
                .UseRouting()
                .UseEndpoints(endpoints =>
                {
                    endpoints.MapControllerRoute(
                        "default", "{controller=Landing}/{action=Index}/{id?}").RequireAuthorization(new AuthorizeAttribute());
                });
```
Which after applying should mean that user must be authorized before loading page; however, all requests get through.

Full startup.cs is below: 

```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddRazorPages();

            services.AddAuthentication(options =>
                {
                    options.DefaultChallengeScheme    = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultScheme             = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddCookie(options =>
                {
                    options.AccessDeniedPath   = "/Error/Unauthorised";
                    options.Cookie.Name        = ".ADAuthCookie";
                    options.ExpireTimeSpan     = TimeSpan.FromMinutes(30);
                    options.LoginPath          = "/Account/Login";
                    options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                    options.SlidingExpiration  = true;
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                //app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }
            app.UseStaticFiles()
                .UseHttpsRedirection()
                .UseCookiePolicy(new CookiePolicyOptions
                {
                    MinimumSameSitePolicy = SameSiteMode.Strict,
                })
                .UseAuthentication()
                .UseAuthorization()
                .UseRouting()
                .UseEndpoints(endpoints =>
                {
                    endpoints.MapControllerRoute(
                        "default", "{controller=Home}/{action=Index}/{id?}").RequireAuthorization(new AuthorizeAttribute());
                });
        }
    }

```
The only alternative I had found that correctly applies the authorize attribute to all is to chain `.AddMvcOptions(opt => opt.Filters.Add(new AuthorizeFilter()))` on to the end of either the `services.AddRazorPages()` call or `services.AddControllers()`, which I don't think is the correct way of doing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Stephen-Gibson** [comment]
Unable to edit initial post, but for clarity anywhere in code that "=&gt;" appears should read "=>"

**Comment by Tratcher** [comment]
The migration guide gives the order as
```
    app.UseRouting();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
```

Authorization needs the route to be resolved first to decide which authorization policy applies.

**Comment by Stephen-Gibson** [comment]
Thank you! I was just being an idiot that was it - when configuring it I was paying attention to make sure that .UseAuthentication(), .UserAuthorization() and .UseEndpoints() were in the right order, but seems .UseRouting() slipped by :( 
I was migrating from .NET Framework so had a lot of changes to keep track of!
