### ISSUE TITLE
'EntityFrameworkCore' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by pappasa** [aspnet/AspNetCore.Docs#14129]
In VS2019, I created TodoContext.cs as described above, but I get the error:

https://snipboard.io/38bGEn.jpg

1&gt;Models\TodoContext.cs(1,17,1,36): error CS0234: The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by pappasa** [comment]
When registering TodoContext in Startup.cs, I get the error:

Startup.cs(31,21,31,40): error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase' and no accessible extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by pappasa** [comment]
Why is the statement

services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

need in ConfigureServices?

**Comment by pappasa** [comment]
The API template has in the ConfigureServices method the following statement:

services.AddControllers();

Should this be removed?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
