### ISSUE TITLE
'DbSet<TodoItem>' does not contain a definition for 'ToListAsync' 

### ISSUE THREAD

**Issue by pappasa** [aspnet/AspNetCore.Docs#14132]
After creating the method

// GET: api/Todo/5
[HttpGet("{id}")]
public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; GetTodoItem(long id)
{
    var todoItem = await _context.TodoItems.FindAsync(id);

    if (todoItem == null)
    {
        return NotFound();
    }

    return todoItem;
}

I get the following compiler error:

1&gt;Controllers\TodoController.cs(35,45,35,56): error CS1061: 'DbSet&lt;TodoItem&gt;' does not contain a definition for 'ToListAsync' and no accessible extension method 'ToListAsync' accepting a first argument of type 'DbSet&lt;TodoItem&gt;' could be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of all your other issues.
