### ISSUE TITLE
Issue with GrpcClient.Create

### ISSUE THREAD

**Issue by RobinKetting** [aspnet/AspNetCore.Docs#14136]
When following the instructions, I get an error on GrpcClient.Create. "GrpcClient" name does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by RobinKetting** [comment]
Installed NuGet package is Grpc.Net.Client 0.2.23-pre1.
In the sample folder  I see that Grpc.Net.Client 0.1.22-pre2 is used
( xx\AspNetCore.Docs-master\AspNetCore.Docs-master\aspnetcore\tutorials\grpc\grpc-start\sample\GrpcGreeterClient ).
When downgrading to that version, the issue is solved

**Comment by npuc85** [comment]
Grpc.Net.Client is no longer a pre-release. The GrpcClient type still does not exist, and none of the documentation has been updated to remove that and replace it with whatever it is you're supposed to do now.

**Comment by ddobric** [comment]
I have the same issue.
GreeterClient does not exist ?!

This line does not compile:

 var client = new Greeter.GreeterClient(channel);

**Comment by damonpkuml** [comment]
+1, I have the same issue.

**Comment by JamesNK** [comment]
`GrpcClient.Create` has been removed in the latest version of `Grpc.Net.Client`. Use the client constructor with `GrpcChannel`.

**Comment by jongalloway** [comment]
I don't think this issue should have been closed, as the tutorial still said to call `GrpcClient.Create`. Sent pull request to fix.
