### ISSUE TITLE
Add sample showing "chained bind"

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#14144]
This is a small code sample that shows a solution to cases like this: https://github.com/aspnet/AspNetCore/issues/13408

The typical use case for this is when you want to write a component that represents an input element, but adds some additional functionality like styling, or processing the values that come out of it.

We call this *chained-bind* because there are multiple levels of `@bind` happening:
- Your component binds to an `<input>` element
- Another component binds to your component

Here's a working sample:

```razor
@* Index.razor *@
<PasswordField bind-Value="@password" />
@code {
    string password;
}
```

```razor
@* PasswordField.razor
<input
       type="@(ShowPassword ? "text" : "password")"
       required
       value="@Password"
       @oninput="@OnPasswordChanged" />
<a @onclick="ToggleShowPassword">
    Show password
</a>

@code {
    private string password;

    [Parameter]
    public string Password
    {
        get
        {
            return this.password ?? "";
        }
        set
        {
            if (this.password != value)
            {
                this.password = value;
            }
        }
    }

    [Parameter]
    public EventCallback<string> PasswordChanged { get; set; }

    bool ShowPassword { get; set; }

    private void ToggleShowPassword()
    {
        this.ShowPassword = !this.ShowPassword;
    }

    private Task OnPasswordChanged(ChangeEventArgs e)
    {
        Password = (string)e.Value;
        return PasswordChanged.InvokeAsync(Password);
    }
}
```

**Comment by rynowak** [comment]
@guardrex

**Comment by enetstudio** [comment]
I just can't get this; why the bind-Value="@password" in <PasswordField bind-Value="@password" />
and  not <PasswordField bind-password="@password" />
Are we not suppose to use the name of a parameter property after the hyphen; in that case password ?
As far as I understand, when you use Html input tag, and use @bind="@SomeProperty", the default attribute is value. This is as though we used this syntax instead: @bind-value="@SomeProperty", but  here we speak of one component binding to another component. I guess that no default attribute can be determined. Why value and not password ? And if both cab be used, I still want to understand why value can be used.

Thanks...

**Comment by enetstudio** [comment]
I just can't get this; why the bind-Value="@password" in `<PasswordField bind-Value="@password" />`
and not  `<PasswordField bind-password="@password" />`
Are we not suppose to use the name of a parameter property after the hyphen; in that case password ?
As far as I understand, when you use Html input tag, and use @Bind="@SomeProperty", the default attribute is value. This is as though we used this syntax instead: @bind-value="@SomeProperty", but here we speak of one component binding to another component. I guess that no default attribute can be determined. Why value and not password ? And if both cab be used, I still want to understand why value can be used.

Thanks...

**Comment by guardrex** [comment]
@enetstudio Moved that to https://github.com/aspnet/AspNetCore.Docs/issues/14409.

Please use the feedback form at the bottoms of the topics. It adds metadata for working issues and automatically pings the author. No worries on this one ... let's pick up the discussion over there.
