### ISSUE TITLE
Named options are case sensitive

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/AspNetCore.Docs#14158]
Not sure if it's intended, but it looks like Named options are case sensitive. If that's intentional, I think there should be a note in that section of the docs letting people know that it's case sensitive in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@HaoK, I can't repro this behavior with the sample app. Changing the named options name on either end (`Configure` or `Get`) draws the same values.

**Comment by HaoK** [comment]
Configuration isn't case sensitive, but named options themselves are, I added a test in this PR to demonstrate https://github.com/aspnet/Extensions/pull/2829/files

**Comment by guardrex** [comment]
Thanks ... I found the error here. I can repro the behavior now. I'll get the PR in tomorrow.
