### ISSUE TITLE
Add more details to security warning.

### ISSUE THREAD

**Issue by Vinigas** [aspnet/AspNetCore.Docs#14150]
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.0&tabs=visual-studio#write-a-basic-form
contains security warning ("For security reasons, you must opt in to binding GET request data...") which could be explained more detailed with example, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.0&tabs=visual-studio#write-a-basic-form)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Cross-referencing the original discussion :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/5658

**Comment by Rick-Anderson** [comment]
Binding on GET can make it **NOT** [safe](https://developer.mozilla.org/en-US/docs/Glossary/safe)

See https://www.youtube.com/watch?v=p7iHB9V-KVU&feature=youtu.be&t=54m27s
