### ISSUE TITLE
Certificate Need on Azure App Service

### ISSUE THREAD

**Issue by alaskanrogue** [aspnet/AspNetCore.Docs#14163]
Does the "listenOptions.UseHttps" function need to implemented where the deployment is a Azure App Service which already has a SSL/TSL binding implemented? If so, does it need a different PFX certificate? If not, what should the parameters, e.g. path/file/password, be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by shirhatti** [comment]
gRPC is currently not supported in Azure App Service. The only supported server for gRPC in 3.0 is Kestrel. Hosting on Windows in IIS (and in Azure App Service) will require kernel changes and IIS changes in Windows which we are currently investigating.

**Comment by alaskanrogue** [comment]
Interesting. I subsequently after filing this issue found I had to abandon gRPC because it is not yet fully implemented for Xamarin.
