### ISSUE TITLE
Confusing project name

### ISSUE THREAD

**Issue by Basyras** [aspnet/AspNetCore.Docs#14167]
Many people (including me) got confused when project was called "AuthoringTagHelpers" which sound like namespace. Of course later i found out that in article is stated this:"Create a new ASP.NET Core project called AuthoringTagHelpers" but still i think the project name should be change to something more "correct" as ASPdemo or something that doesn't look like namespace later in article.

For reference that i'am not alone:
https://stackoverflow.com/questions/48271514/custom-tag-helper-not-working

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Autor pomocných rutin značek v ASP.NET Core](https://docs.microsoft.com/cs-cz/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/AspNetCore.Docs.cs-cz/blob/live/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
