### ISSUE TITLE
.NET Generic Host topic needs expanded content root explanation

### ISSUE THREAD

**Issue by wadepickett** [aspnet/AspNetCore.Docs#14165]
- [ ] Need to add expanded explanatory comments about the content root setting to topic .NET Generic Host: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#contentrootpath

This issue was moved here from: https://github.com/aspnet/AspNetCore.Docs/issues/10559

Here is a discussion about the needed content root changes:

The hosting doc goes into detail on content root and web root. Point to them for details.
per @danroth27:

By default the content root will be the location where your app dll is loaded from, which ~during development~ `[edit insert] { in test/production}` is the bin directory. The content directory is used to determine the location of things like your views and your web root ( wwwroot folder). However, during development your views and web root are not in the bin folder. They are a couple of directories up where your project is located. To fix that we setup the project to use the current directory where you are running “dotnet myapp.dll” from, which is during development is typically the root directory of your project.
Can you reword "To fix that setup"? Should it be something like "To set the content root for development"?
Seems like it's much simpler to define content root as the parent of web root ( wwwroot )
It is based on a set of granular and well factored NuGet packages.This allows you to optimize your app to include just the NuGet packages you need. replace with something like
It is based on a set of well factored NuGet packages, you include only the packages you need.
The following is fixed
The content root is the base path to any content used by the app, such as its views and web content. By default the content root is the same as application base path for the executable hosting the app; an alternative location can be specified with WebHostBuilder.
What does web content mean? @danroth27 asks fowler " how to describe the content root for an ASP.NET Core app?" Fowler responds:
Any non code files that need to be read from the project. Config files, data files (like a database file), etc. it's also the base path for the webroot folder "

**Comment by guardrex** [comment]
Just want to mention in passing that we've traditionally covered these concepts in the Fundamentals Overview and linked external mentions to these sections ...

* https://docs.microsoft.com/aspnet/core/fundamentals/#content-root
* https://docs.microsoft.com/aspnet/core/fundamentals/#web-root

**Comment by wadepickett** [comment]
@guardrex , thanks for pointing that out and for the help.  Just to make sure  I'm on the same page, the thinking is that I should fill in a more detailed explanation for these two items right in the fundamentals overview rather than relying on a link to the generic host doc for a more detailed explanation.  Correct?   The current proposal was to still keep the short mention of them in the fundamentals, that wasn't going anywhere,  but add a longer explanation in the generic host.  
@tdyksra you also good with expanding in the fundamentals doc itself?  I think you originally suggested providing that in the generic host doc as an option, but maybe there was no strong preference.  Not a biggie, just didn't want to put aside your previous input.

**Comment by guardrex** [comment]
> a more detailed explanation for these two items right in the fundamentals overview rather than relying on a link to the generic host doc for a more detailed explanation. Correct?

Maybe ... depends I suppose on how specific the new content is to these concepts. If it *only* applies to the host(s), sure thing ... host topic(s) only. If the adds or mods are universally relevant, then *yes* ... other docs link to these and will probably benefit by whatever is added or modified.

> rather than relying on a link to the generic host doc

Not exactly ... I meant that you can cross-link to those two sections from both of the host topics. AFAICT now, there *are missing cross-link opportunities*.

To Fundamentals > Overview > Web Root here, for example, ...

* https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#web-root
* https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host#webroot

Just examples for both of these. There might be more spots.

Content Root could probably use links, too (the last two have in-text references that would take an inline link nicely) ...

* https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#content-root
* https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#set-up-a-host
* https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host#default-builder-settings

Again, just examples from a quick :eyes:.

In passing @tdykstra ... Content Root didn't make the Generic Host updates? ... Perhaps, they said not to show it?

https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.hostinghostbuilderextensions.usecontentroot

**Comment by tdykstra** [comment]
The Fundamentals overview is meant to be a quick read identifying fundamental concepts in ASP.NET Core and linking to the detailed exposition of each of them.  This is not the place for detailed exposition, and arguably content root and web root don't even belong here at all.

By the same token, there should be no need to link back from the host doc to the overview doc, because by its nature an overview is a subset of the detailed exposition.

Content root in generic-host.md is in the [Settings for all app types](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#settings-for-all-app-types) h2 section. The h3 is ContentRootPath, adopting the name from IHostEnvironment.  We could change the h3 to Content root.

**Comment by guardrex** [comment]
> detailed exposition of each of them

What else is there to say on those? If nothing (or little more), then cross-linking still makes sense imo.

> Content root

:smile: *Search Foo* failed me ... I searched for "Content Root." lol
