### ISSUE TITLE
Unclear dependency in ConfigureServices and relation to Azure AD

### ISSUE THREAD

**Issue by MikaelUmaN** [aspnet/AspNetCore.Docs#14173]
Trying to follow this tutorial I am stopped at:

services.AddDbContext&lt;ApplicationDbContext&gt;(options =&gt;
        options.UseSqlite(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity&lt;IdentityUser&gt;()
        .AddDefaultUI(UIFramework.Bootstrap4)
        .AddEntityFrameworkStores&lt;ApplicationDbContext&gt;();

These give read squigglies in Visual Studio and I'm prompted to install some packages.

I don't really want to but I guess I have to? I don't know what IdentityUser and ApplicationDbContext refer to. Is that something I have to create myself? What's stored in the sqlite db in that case ?

And how does this compare to Azure Active Directory? When would I want to use the one or the other ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Start with some tutorials that explain these

- https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio
