### ISSUE TITLE
Implying that Blazor is better than JavaScript is going to be hard to prove.

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/AspNetCore.Docs#14174]
While i agree Blazor is AWESOME.  This statement really isn't nice and I think the it will be hard for you to realistically prove that Blazor is **"Better"** than JavaScript.

>normally requires writing JavaScript, but Blazor provides a better approach using C#.

How about rewording it to 

>normally requires writing JavaScript, but Blazor provides another approach using C#.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LindaLawton ...

It's doesn't mean to say that Blazor is better than JS ... it's saying that the **_approach_** is better.

It's been engineering's opinion from the start that developing server- and client-side in one language is better. It's been common, explicitly stated or implied, in blog posts and in conference talks given by the team.

I'll mark this issue for engineering so that they can reconsider.

*Note to self:* This remark is made in at least one other spot; so if we change it, search and destroy any instances (at least two).

**Comment by Legends** [comment]
it means: one DSL fewer

**Comment by LindaLawton** [comment]
Well from someone who does not use English as primary language it sounds "wrong".    There may be a better way to word it so that its more clear exactly what you mean. 

Thank you for your consideration

**Comment by guardrex** [comment]
It could be written out ...

> Incrementing a counter in a webpage normally requires writing code in two languages: JavaScript is used client-side to increment the counter in the rendered page, and C# is used server-side as the language of the ASP.NET Core app. Blazor provides a better approach because only one language, C#, is used client- and server-side.

... or shorter ...

> Incrementing a counter in a webpage normally requires writing code in two languages, JavaScript and C#. Blazor provides a better approach because only one language, C#, is used client- and server-side.

Thanks @LindaLawton for opening. We don't generally use marketing language, and it's not clear (specific) in the current text what they mean.

**Comment by samridhis1980** [comment]
Blazor is boon to hard core .net specialist who have vast amount of experience in C# and Asp.net MVC Razor pages. They need not get expertise in Javascript to continue with developing web apps

**Comment by kulashaker30** [comment]
The statement "better than javascript" targeted .net developers not php, java developers etc. Because .net devs will save a lot of time developing web apps using their primary programming language.

**Comment by LucidObscurity** [comment]
I think some are missing the high level perspective here. W3C created the WebAssembly spec for a reason (https://www.w3.org/TR/wasm-core-1/)...how much time between ecmascript version releases? How long between releases of your favorite language and how does that language's features compare with ecmascript 6? WebAssembly abstracts the execution from the compilation. In other words, if C# can be compiled to WebAssembly, [insert your favorite language] can also. If Blazor proves to be a success, [insert your favorite language] will have a compiler for WebAssembly as well. MS is being a pioneer here and, like all others pioneering in this field, it's for the benefit of all software engineering.

**Comment by guardrex** [comment]
Thanks everyone. We have enough here to work the issue, and we'll see if management would like to proceed. I made some suggestions at https://github.com/aspnet/AspNetCore.Docs/issues/14174#issuecomment-528843319 that they might agree to implement ... or something else. They'll get to this as soon as they can.
