### ISSUE TITLE
ServerPrerendered, Server, Static

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14171]
Especially the first two modes are irritating. I originally come from web forms, changed to asp.net mvc and now I am having a look on Blazor. I asked on Gitter what are the differences between all three and I got this answer (can you confirm it?):

> @Joe4evr That's not quite true - it (ServerPrerender) is used to PreRender a site for SEO purposes (or even just to present a better experience for the user)
> 
> My understanding (which could be wrong) is:
> 
> Server = the index is sent to the client, then the SignalR connection is made, and when the connection becomes active, the components are rendered and sent to the client (the user sees and can interact with your components)
> 
> ServerPrerendered is for mainly, but not exclusively for SEO - the current layout is rendered server side and sent to the client in the initial Response - it is "Static" content - the user does not yet have a connection to the "Blazor" server - there is no SignalR connection yet, but there will be one soon. Once the connection is Active, the client is updated with a new render of the components which is interactive.
> 
> Static - A bit like PreRendered, but there will be no SignalR connection ever for this component - more like a traditional ASP.NET site, but not really

<hr/>

My questions to this answer:

1. **Server**: What is meant with Index? So on first request nothing comes down, but the index? Layout, pages, components are rendered, when the connection (circuit?) is made?

2.) **ServerPrerendered**: Everything (layout, pages, components) comes down, but static? After connection is made, the code logic gets downloaded and the app is interactive?

3.) **Static**: Pure HTML, nothing else?

So it would be nice to know for each `mode` what exactly is going on...what comes down when, when is the connection established.
What does **prerender** actually mean? Because from my point of view, you can render things on the server or on the client or both.
But as I am using Blazor serverside I thought everything gets rendered on the server.

Confused....
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This text was addressed **_after_** your issue was opened. If the new lingo is still problematic, please open a new issue from the **This page** feedback button/form on the topic.

https://github.com/aspnet/AspNetCore.Docs/pull/14281

**Comment by guardrex** [comment]
ooops ... that was just a minor update. I'll look again.

**Comment by guardrex** [comment]
I don't think what we have is confusing *to me*, but I'll leave this open for engineering to take a look.

**Comment by guardrex** [comment]
There's been churn (hopefully improvements 🤞) on this one since this issue was opened, and engineering has looked at what we're saying and hasn't 😵 *freaked out* 😵 over the coverage. Let's keep an :ear: open for additional feedback and close this for now.
