### ISSUE TITLE
jQuery style guide adherence

### ISSUE THREAD

**Issue by C-F-K** [aspnet/AspNetCore.Docs#14175]
Chaining .accept() calls is a sensible way to reduce overhead; however, the absolute mess of brackets/braces/parens in the getData() function is confusing and nigh-unreadable, especially if one is taking advantage of one's working memory and typing the code out rather than copy-pasting it.

What follows is how it looked after I made sense of it; this is not to suggest it's the only way, but it is certainly more in line with [the jQuery code style guide on chained method calls](https://contribute.jquery.org/style-guide/js/#chained-method-calls). As you can see, I have each call to .append() on its own line, increasing indentation when the context moves down a level.

```javascript
function getData() {
    $.ajax({
        type: 'GET',
        url: uri,
        cache: false,
        success: function (data) {
            const tBody = $('#todos');

            $(tBody).empty();

            getCount(data.length);

            $.each(data, function (key, item) {
                const tr = $("<tr/>")
                    .append($("<td/>")
                        .append($("<input/>", {
                            type: 'checkbox',
                            disabled: true,
                            checked: item.isComplete
                        }))
                    ).append($("<td/>")
                        .text(item.name)
                    ).append($("<td/>")
                        .append($("<button>Edit</button>").on('click', function () {
                            editItem(item.id);
                        }))
                    ).append($("<td/>")
                        .append($("<button>Delete</button>").on('click', function () {
                            deleteItem(item.id);
                        }))
                    )
                ;

                tr.appendTo(tBody);
            });

            todos = data;
        }
    });
}
```

n.b. The way I eventually made sense of it was to write the code out one level of nesting at a time. So, first:

```javascript
function getData() {}
```

Then:

```javascript
function getData() {
    $.ajax({});
}
```

Then: 

```javascript
function getData() {
    $.ajax({
        type: 'GET',
        url: uri,
        cache: false,
        success: function (data) {}
    });
}
```

Et cetera. I include this information as a comparison case for the logic behind the way the tutorial is currently written, in case it helps decide what to do with this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-3.0

**Comment by Rick-Anderson** [comment]
cc @scottaddie

**Comment by scottaddie** [comment]
Per our engineering team's recommendation, we're adopting the Fetch API in our docs moving forward. The 3.0 version of the tutorial already uses it instead of jQuery.
