### ISSUE TITLE
PublishProfile option not taken into account with dotnet publish CLI

### ISSUE THREAD

**Issue by Aszan** [aspnet/AspNetCore.Docs#14178]
```
dotnet publish WebApplication.csproj /p:PublishProfile=&lt;FolderProfileName&gt;
```
does not work. Default publish option is used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson I'll take a look at this and report back.

**Comment by guardrex** [comment]
@Rick-Anderson Yep ... it's a reported issue under investigation by engineering. I'll keep tabs on it and take care of this one.
