### ISSUE TITLE
Documentation on Token Based Authorization using IdentityServer with Blazor

### ISSUE THREAD

**Issue by noufionline** [aspnet/AspNetCore.Docs#14181]
Kindly provide a working sample or comprehensive documentation on how to use Token based authorization using IdentityServer and how to store Access Token and Refresh Token on the client side?

**Comment by guardrex** [comment]
@noufionline There's a feedback form at the bottom of the topics that helps us work these. It adds metadata and automatically pings the author.

No worries tho ..... I just moved this over to https://github.com/aspnet/AspNetCore.Docs/issues/14191.

**Comment by noufionline** [comment]
@guardrex Thanks a Ton :) Really appreciate you gesture.
