### ISSUE TITLE
port configuration

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#14193]
Hi team, 
I moved this from here: https://github.com/aspnet/AspNetCore.Docs.de-de/issues/51
The contributor is making a suggestion to the original documentation

@taori commented 10 hours ago
In case someone hosts a windows application it would probably be best if this sample also contained the necessary snippets to configure that so the service which is running can be navigated to through a browser.

adding the following to appsettings.Production.json to this made it work:

```
"Kestrel": {
	"EndPoints": {
		"Http": {
			"Url": "http://localhost:4300"
		}
	}
},


```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @taori (👋 @CeciAc) ...

The default port is the same as for any template-based ASP.NET Core app.

Access the app in a browser at ...

```
http://localhost:5000/
```

I'll add a note to the *README.me* files.
