### ISSUE TITLE
Great intro!

### ISSUE THREAD

**Issue by johnababb** [aspnet/AspNetCore.Docs#14203]
Very clearly written. My compliments to the author(s)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks! And remember to use the helpful voting system.
![image](https://user-images.githubusercontent.com/3605364/64464966-056ef700-d0bf-11e9-9206-3fceb116994a.png)
