### ISSUE TITLE
Unclear statement - Creating a new circuit containing all of the prerendered components

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14202]
`Creating a new circuit containing all of the prerendered components that are part of the same page`

How can a circuit contain prerendered components? As I understood, a circuit is a websocket connection, it is a mode of transportation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.0#places-where-errors-may-occur)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Full passage ...

> Blazor components can be prerendered using `Html.RenderComponentAsync` so that their rendered HTML markup is returned as part of the user's initial HTTP request. This works by:

> * Creating a new circuit containing all of the prerendered components that are part of the same page.
> * Generating the initial HTML.
> * Treating the circuit as disconnected until the user's browser establishes a SignalR connection back to the same server to resume interactivity on the circuit.

I'm going to make a minor language change here to move away from "containing."
