### ISSUE TITLE
How do I create a new Application User Programmatically?

### ISSUE THREAD

**Issue by iHamzaKhanzada** [aspnet/AspNetCore.Docs#14217]
I have used this template and setup the project. Its working fine, Now I have to populate users from c#, I have 100 users which I want to create programatically. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
@haok @blowdart

**Comment by iHamzaKhanzada** [comment]
I am waiting for response @javiercn  @HaoK  @blowdart

**Comment by HaoK** [comment]
You can try something like this https://stackoverflow.com/questions/52708439/how-do-i-seed-user-roles-in-identity-asp-net-core-2-1-identity-scaffolded where you basically modify your app to seed your users once

**Comment by Rick-Anderson** [comment]
[Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#add-or-remove-a-user-to-a-role-1) seed's the DB.

This is really a DB question and not a web app UI question. Production apps would work directly with the DB using scripts or another mechanism.
