### ISSUE TITLE
Configure with MySQL

### ISSUE THREAD

**Issue by iHamzaKhanzada** [aspnet/AspNetCore.Docs#14214]
How can I use Entity Framework core 3.0 and Dotnet core 3.0 with a MySQL database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @iHamzaKhanzada ... EF Core docs link to ...

* [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql)
* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/README.md

https://docs.microsoft.com/ef/core/providers/

**Comment by iHamzaKhanzada** [comment]
@guardrex , Pomelo.EntityFrameworkCore.Mysql doesn't support Entityframeworkcore 3.0 and mysql.data.entityframeworkcore also doesn't support entity framework core 3.0

**Comment by guardrex** [comment]
@iHamzaKhanzada I see. Ask them on that repo ... they'll know ... but search both open **and closed** issues there first. Someone may have already asked.

https://github.com/aspnet/EntityFramework.Docs/issues

**Comment by guardrex** [comment]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/797

**Comment by guardrex** [comment]
Ah ... here it is ... they're getting close ...

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/818
