### ISSUE TITLE
Typescript samples are incomplete

### ISSUE THREAD

**Issue by AaronLS** [aspnet/AspNetCore.Docs#14213]
Neither of these contain a wwwroot, so when run they fail to load:

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/signalr-typescript-webpack/sample

I download and open the SignalRWebPack.csproj in VS2019 community, and attempted to run the project, and since there's nothing in wwwroot it cannot connect to the site.

These are linked from: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio

I've spent a couple weeks trying to get through this tutorial, and it's frustrating that you don't even have a valid working sample project.

**Comment by Rick-Anderson** [comment]
Our *.gitignore* removes *wwwroot* to prevent bloat. The samples are primarily to document the code. They sometimes need a little work to run.

> I've spent a couple weeks trying to get through this tutorial

Were you unable to follow the instruction at 
[Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio)
 
If so, Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

**Comment by Rick-Anderson** [comment]
Per comment hub:

Can we get a less complicated startup that doesn't use webpack and libman? The article should explain how to setup typescript without these complexities, and leave them for a separate article.

npm init -y doesnot create any package.jkson

cc @scottaddie 

![image](https://user-images.githubusercontent.com/3605364/64646358-ca750800-d3cb-11e9-9f6d-1973f60200f1.png)
