### ISSUE TITLE
Update for 3.0

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#14211]
Introduce version moniker ranges to toggle between 2.x and 3.x versions of the doc. Some things to address:

- @microsoft/signalr instead of @aspnet/signalr
- auto-reconnect support
- replace `UseSignalR` call with `UseEndpoints`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2#feature-differences)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Note per [this conversation with cdnjs](https://github.com/cdnjs/cdnjs/pull/13319) - it looks like folks who use cdnjs won't have to change things, as they can't currently rename packages in cdnjs. so folks will continue to use the aspnet-signalr item until such time as cdnjs can change our package to microsoft-signalr.

**Comment by scottaddie** [comment]
Closing, since this was addressed in https://github.com/aspnet/AspNetCore.Docs/pull/15685/
