### ISSUE TITLE
CascadingValue

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14218]
Found in another blog post:
The important thing to understand is that updates only cascade down you can't update a value from a descendant.

Could you please add this to the docs, it's an important thing, but not mentioned. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Legends ... It just so happens that we're working on improving *chained bind* concepts right now. This just went up this morning. Please feel free to comment on it ...

https://github.com/aspnet/AspNetCore.Docs/pull/14215

... and although I don't show it there, you can set that `password` field in the parent, and it will update down in the `PasswordField` child component, including the UI that the child puts up.

I think what we're doing now on #14215 starts to improve the coverage, but there's more work to do.  I think that the `EventCallback` section needs more work. We might do that on the same PR or a different PR ... probably a different one. I have another priority issue that I need to work first. We plan to review everything and make additional enhancements over the next couple of weeks.

**Comment by Legends** [comment]
It's internal, I don't have access to it...

**Comment by guardrex** [comment]
Look at the diff on the PR.
