### ISSUE TITLE
3.0 update: Globalization and localization

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14225]
Ryan to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
@Rick-Anderson can I participate on this while I added almost the localization features if not all in 3.0.0 :)

**Comment by Rick-Anderson** [comment]
@hishamco Can you provide a PR with the 3.0 updates? You might want to duplicate the entire document like this:

::: moniker range=">= aspnetcore-3.0"
copy of existing doc which you update for 3.0
::: moniker-end

::: moniker range="< aspnetcore-3.0"

original document
::: moniker-end

**Comment by hishamco** [comment]
> ::: moniker range=">= aspnetcore-3.0"
copy of existing doc which you update for 3.0
::: moniker-end

Sure, I already know the monikers stuff :)

**Comment by hishamco** [comment]
FYI: I wrote a related blog post http://hishambinateya.com/what-is-new-in-localization-in-asp.net-core-3.0

**Comment by cesee** [comment]
This guide is great for application localization.

Is there any build-in way to localize a razor component library as stand alone ? (i.e. all the resx files should be inside the library itself, etc...). 

I read a few guides already and they all target only localization an application.

**Comment by hishamco** [comment]
There's a built in support for that with the help of `ResourcesLocationAttribute`

**Comment by cesee** [comment]
Thanks. I'll look into that.
Do you know of any guides/example that can help with this specific scenario ?

The desired result is to have built-in resx files for the library for common languages, and still allowing to override specific values/add new languages by the consumer of the library also through localization.

**Comment by hishamco** [comment]
The current docs mentioning that also you can check aspnet/entropy repo

**Comment by hishamco** [comment]
@casee these are examples from the source

https://github.com/aspnet/Extensions/tree/master/src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests

https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/Localization/testassets

They are absolutely will help you

**Comment by hishamco** [comment]
I think it's the time to start on this one

@Rick-Anderson shall I start with modifying the current code to target 3.0, after that we can write about the new stuff that have been added

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson shall I start with modifying the current code to target 3.0,

Sure. Just remember 

::: moniker range=">= aspnetcore-3.0"
copy of existing doc which you update for 3.0
::: moniker-end

::: moniker range="< aspnetcore-3.0"

original document
::: moniker-end

**Comment by hishamco** [comment]
Don't worry about the monikers, I already worked with them before :)

the PR is coming 🚀 🚀 🚀

**Comment by hishamco** [comment]
@Rick-Anderson I will create another PR to talk about the `Content-Language` header, one more thing there's a minor change in `LogLevel` when the culture is unsupported shall we point to this?

**Comment by Rick-Anderson** [comment]
> there's a minor change in `LogLevel` when the culture is unsupported shall we point to this?

Sure

**Comment by hishamco** [comment]
Ok, I will did that in my 2nd PR
