### ISSUE TITLE
QueueBackgroundWorkItem built-in in 3.0?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/AspNetCore.Docs#14223]
This page says:

&gt; A background task queue is based on the .NET 4.x QueueBackgroundWorkItem (tentatively scheduled to be built-in for ASP.NET Core 3.0)

Is the last part still true? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Daniel15 ... I won't know until I take a look for the work on https://github.com/aspnet/AspNetCore.Docs/issues/12841 (ETA is unknown at this time 🏃😅). Until then, you'd need to go look in the reference source or ask on a support forum or chat.
