### ISSUE TITLE
Should the authentication token be stored in the browser's local storage?

### ISSUE THREAD

**Issue by MNF** [aspnet/AspNetCore.Docs#14224]
“To send the token on subsequent requests, store the token in the browser's local storage. “
Does it contradicts  to OWASP recommendations  “it's recommended not to store any sensitive information in local storage.” (From https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md#local-storage)?

Additionally the page https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage is very detailed reasons

> Stormpath recommends that you store your JWT in cookies for web applications, because of the additional security they provide, and the simplicity of protecting against CSRF with modern web frameworks. HTML5 Web Storage is vulnerable to XSS, has a larger attack surface area, and can impact all application users on a successful attack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart should I change this from ` store the token in the browser's local storage. ` to   store the token in the web app ?

**Comment by blowdart** [comment]
I'm kinda meh about this, because anyone that can access your local storage can access your login cookie and then they're you anyway. Saying it's vulnerable to XSS isn't a reason, so are cookies (although HTTP only provides some mitigation) unless you carefully implement CSRF protection.

Maybe demonstrate both and link to the OWASP page?

**Comment by Rick-Anderson** [comment]
@MNF Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by MNF** [comment]
Sorry, @Rick-Anderson, I am learning the topic myself. I feel that https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage and https://stackoverflow.com/questions/27067251/where-to-store-jwt-in-browser-how-to-protect-against-csrf/37396572#37396572 are reasonable ways to use HttpOnly Secure cookies and protect against CSRF, but not confident enough to write PR.
