### ISSUE TITLE
Provide implementatoin for GetFallbackPolicyAsync to match the 2.2 behavior

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore.Docs#14232]
Following up on https://github.com/aspnet/AspNetCore/issues/13762
GetFallbackPolicyAsync is new in 3.0. It'd be nice to have in the docs a default implementation that mimics the 2.2 behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by mrgleba** [comment]
After some research the simplest code to mimic the 2.2 behavior is:
```cs
public Task<AuthorizationPolicy> GetFallbackPolicyAsync() => Task.FromResult<AuthorizationPolicy>(null);
```

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/AspNetCore.Docs/pull/14717
