### ISSUE TITLE
cannot authorize with custom scheme

### ISSUE THREAD

**Issue by yohsii** [aspnet/AspNetCore.Docs#14233]
I'm using:
```
services.AddAuthentication().AddCookie("custom", options=> {
                options.LoginPath = "/admin/in";
                options.LogoutPath = "/admin/out";
            });
```
to register the scheme "custom" but when i try and authorize on the controller doing this:
```
[Authorize(Roles = "admin", AuthenticationSchemes = "custom")]
        public ActionResult Index()
        {
            return View();
        }
```
it doesn't authorize the user and redirects to login page even though the user is logged in and is in the correct role.

if, however, i try this:
```
[Authorize(Roles = "admin", AuthenticationSchemes = "Identity.Application")]
        public ActionResult Index()
        {
            return View();
        }
```
the same user will happily authorize and i can get through to the page.

so my question is - how can i get my "custom" authentication scheme to work like "Identity.Application". is there additional configuration required to get the custom authentication scheme to work correctly?

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by yohsii** [comment]
it appears that setting `options.ForwardAuthenticate = "Identity.Application";` solves this problem:

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication().AddCookie("custom", options=> {
                options.LoginPath = "/admin/in";
                options.LogoutPath = "/admin/out";
                options.AccessDeniedPath= "/admin/in";
                options.ForwardAuthenticate = "Identity.Application";
            });
            
        }
```

this should really be documented

**Comment by Rick-Anderson** [comment]
@blowdart  quick review of good stuff to add to this doc.

**Comment by cosmoscowboy** [comment]
@yohsii

I had a similar problem when using a "custom" scheme with the call 'AddCookie'. My solution was to add the same scheme name in the call to "AddAuthentication". For instance:

.AddAuthentication(AuthenticationSettings.AuthenticationSchemeSharedCookie)
.AddCookie(AuthenticationSettings.AuthenticationSchemeSharedCookie, cookieAuthenticationOptions =>

Where 'AuthenticationSettings.AuthenticationSchemeSharedCookie' defines the 'custom' name.

In fact, if you are only defining one type of authentication scheme, in this case cookies, there is no need to supply the 'custom' scheme name to both calls. The extension calls to 'AddAuthentication' and 'AddCookie' use the default identity values. I hope this helps. :thumbsup

For more information see: https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Core/src/IdentityConstants.cs
https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/Authentication/Core/src/AuthenticationServiceCollectionExtensions.cs

**Comment by yohsii** [comment]
thanks @cosmoscowboy 
i actually needed two schemes, the default one and a custom one.

regarding `AddAuthentication`, how does it know how to perform the custom authentication when all you're passing in is the name of the scheme?

cheers

**Comment by Frankofoedu** [comment]
> it appears that setting `options.ForwardAuthenticate = "Identity.Application";` solves this problem:
> 
> ```
> public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddAuthentication().AddCookie("custom", options=> {
>                 options.LoginPath = "/admin/in";
>                 options.LogoutPath = "/admin/out";
>                 options.AccessDeniedPath= "/admin/in";
>                 options.ForwardAuthenticate = "Identity.Application";
>             });
>             
>         }
> ```
> 
> this should really be documented

Thanks for this.

Please could you shed more light on why this works?

**Comment by blowdart** [comment]
Please don't create product bugs or queries under docs. Create them in the [product repo.](https://github.com/aspnet/AspNetCore/issues)

**Comment by blowdart** [comment]
(Unfortunately we can't move this)

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/70647957-2da25080-1bee-11ea-9f76-1d179202539a.png)

**Comment by blowdart** [comment]
I don't have permissions :)
