### ISSUE TITLE
Polymorphic model binding via subclassing ComplexObjectModelBinder

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14237]
Per [this comment](https://github.com/aspnet/AspNetCore.Docs/pull/14122#pullrequestreview-283300604)

This part of the design really doesn't seem too scalable. I think most users would look at this sample and say "I don't want to write that code". I think we've done this in the past by subclassing `ComplexObjectModelBinder` right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 are you able to do this?

**Comment by serpent5** [comment]
I’ll give it a go.

**Comment by Rick-Anderson** [comment]
@serpent5  ping `@pranavkm` if you have any questions.

**Comment by Rick-Anderson** [comment]
@rynowak do you have a suggestion on implementing your suggestion subclassing `ComplexObjectModelBinder` ?

**Comment by pranavkm** [comment]
I can have a look at this next week. Like I said, it's a bit gross to set up.

**Comment by serpent5** [comment]
@pranavkm Do you have any quick pointers re whether it's option 1 or 2 that I need to be looking into, or at least just whether I'm way off and should stop trying to go down the path I'm on?

**Comment by Rick-Anderson** [comment]
@serpent5  this is very low priority with the pending 3.0 release. Let's pick this up in a month. I'll find some good programming issues for you in the mean time :)

**Comment by serpent5** [comment]
@Rick-Anderson Understood. I 100% get that. Sorry. :)
