### ISSUE TITLE
constructing AuthorizationPolicyBuilder without parameters leads to exceptions

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore.Docs#14231]
Following up on https://github.com/aspnet/AspNetCore/issues/13764
if you create a AuthorizationPolicyBuilder without providing an authentication scheme name then if it fails an exception would be raised. AuthorizationPolicyBuilder should either have authentication schemes or always succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mrgleba 
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
I can clean up and help.

**Comment by mrgleba** [comment]
Done :)
