### ISSUE TITLE
How to create a library targeting ASP.NET Core 3.0

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore.Docs#14245]
**Help us make content visible**

- How to build a library targeting ASP.NET Core

**Describe the new topic**

Since the WebSDK has an implicit framework reference to AspNetCore, most folks don't see `<FrameworkReferences>` at all. We need some guidance for library authors on how to target ASP.NET. We probably need to include guidance on when to multi-target as well.

**Comment by shirhatti** [comment]
See https://github.com/aspnet/AspNetCore/issues/13541 as an example of a customer reported issue

**Comment by Rick-Anderson** [comment]
@shirhatti  I created an integrated issue at  #14309

This is what I tell customers:

Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by shirhatti** [comment]
Huh? This isn't associated with an existing doc? I filed an issue for a new doc
