### ISSUE TITLE
Identity Two-Factor via REST API documentation

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/AspNetCore.Docs#14241]
**Help us make content visible**
- Tell us what search terms you used and how you searched docs.

"ASP.NET Core Identity webapi two factor"
"ASP.NET Core identity webapi 2fa"

- Tell us what docs you found that didn't address your concern.

I've read through the ASP.NET Core Identity documentation pretty extensively and none of it seems to cover this scenario.

**Describe the new topic**

- Explain why this topic is needed.

The method used in all of the samples involves cookies. It seems some information is stored in the cookie when a login is attempted and 2fa is required. And then that information is retrieved and used to complete the 2fa when the user provides the appropriate code.

- Suggest a location in the Table of Contents.

I'm not sure where this would be best placed.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.

The topic should cover 2fa without cookies, specifically. Preferably within the context of a REST API. It appears `UserManager<TUser>.VerifyTwoFactorTokenAsync();` is the appropriate path for this.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

**Comment by Rick-Anderson** [comment]
2FA 
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by tstivers1990** [comment]
> 2FA
> Thanks for contacting us.
> We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough 👍 responses, we’ll reconsider.

I suspect it's going to have a hard time generating any responses while closed.
