### ISSUE TITLE
No "What's new in 3.0" page

### ISSUE THREAD

**Issue by fiksen99** [aspnet/AspNetCore.Docs#14240]
3.0 is in preview, but there's no page indicating what's new to help me decide if I want to upgrade. I think the feature set is now locked for 3.0 and the changes are now focussed on quality, correct? If so, this means we can begin adding documentation for the 3.0 features.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd495160-090c-065e-5b98-53b112db0cea
* Version Independent ID: 46699e55-2685-95f8-4b54-dcb66d630000
* Content: [What's new in ASP.NET Core 2.2](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-3.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-2.2.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-2.2.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danroth27 @scottaddie  I'll start "What's new in 3.0" from https://devblogs.microsoft.com/aspnet/ 
cc @guardrex

**Comment by Rick-Anderson** [comment]
- gRPC
-
