### ISSUE TITLE
Execution Error in AspNetCore.Docs\aspnetcore\mvc\controllers\testing\samples\2.x\TestingControllersSample

### ISSUE THREAD

**Issue by Gosha24** [aspnet/AspNetCore.Docs#14253]
{ description here }

# Software versions

 .NET Core 2.2
I downloaded and run sample AspNetCore.Docs\aspnetcore\mvc\controllers\testing\samples\2.x\TestingControllersSample
I got exception
An error occurred while starting the application.
InvalidOperationException: Cannot resolve scoped service 'TestingControllersSample.Core.Interfaces.IBrainstormSessionRepository' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)

InvalidOperationException: Cannot resolve scoped service 'TestingControllersSample.Core.Interfaces.IBrainstormSessionRepository' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
TestingControllersSample.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
                var repository = app.ApplicationServices.GetService<IBrainstormSessionRepository>();
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by guardrex** [comment]
@Gosha24 ... I moved this to the issue for upgrading the sample to 3.0. I'll check the sample when I get to that issue.

Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13343
