### ISSUE TITLE
Add example for endpoint routing with controller

### ISSUE THREAD

**Issue by omerlh** [aspnet/AspNetCore.Docs#14254]
I tried to migrate an existing app today, and it took me a while to figure what I'm missing until I find [this post](https://andrewlock.net/comparing-startup-between-the-asp-net-core-3-templates/). Can you add something like this example, showing what is required to support controllers routes? 
```
            app.UseEndpoints(endpoints =&gt;
            {
                endpoints.MapControllers();
            });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#update-routing-startup-code)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omerlh ... It's covered in the topic here :point_right: https://docs.microsoft.com/aspnet/core/migration/22-to-30#migrate-mvc-controllers

**Comment by omerlh** [comment]
Thanks! I somehow missed that...
