### ISSUE TITLE
Redirection after SignOutAsync is required, not to be avoided

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#14255]
> Don't redirect after calling `SignOutAsync` or the user will **not** be signed out.

The suggestion here is incorrect. It shouldn't be prefixed with "don't", as redirection is what actually forces the user to be signed out. The code above this line for `LogoutModel` should also be changed to end with `return RedirectToPage()` instead of `return Page()` to match, which is what the current [2.2 version](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Logout.cshtml.cs#L47) of the Identity UI and scaffolding produce.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  I think that was true in the long ago. Do want to PR the fix?

**Comment by serpent5** [comment]
Yeah, will do.
