### ISSUE TITLE
Should add note about SameSite as an alternative and/or complementary approach to prevent CSRF attacks

### ISSUE THREAD

**Issue by cjblomqvist** [aspnet/AspNetCore.Docs#14251]
Since there's now relatively good browser support, for many use cases SameSite=Lax/Strict can be a better (simpler, less risky) approach than having to manage anti-forgery tokens. There should be a note about that here so that only people who need to implement the additional anti-forgery token layer really do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
Given that google has just changed the rules, no, it's not good browser support and probably won't be for months if not another year.

Until such time as browser support will be fully updated any updates we give will break at least one browser. So unassigning myself and leaving it in the backlog to revisit in 6 months.

**Comment by cjblomqvist** [comment]
@blowdart - the chrome change is to set it as default, so I'm not sure how that goes against adding a note about it to the docs and how that changes browser support?

Of course, the note could mention the details about how browsers treat this in detail if you prefer, but at least some general note would be good right?

**Comment by blowdart** [comment]
The chrome changes break safari. So I'm not going to document this until the state of the changes and browser support is clear. If you want to write a PR feel free

**Comment by Yanal-Yves** [comment]
@blowdart, @cjblomqvist - I guess your are talking about [defaulting samesite=lax as default](https://www.chromestatus.com/feature/5088147346030592) starting from Chrome 76. I am not sure how defaulting to samesite=lax for cookies on Chrome could break safari. Are you refering to the [wierd implementation of samesite=lax of Safari](https://news.ycombinator.com/item?id=19855476) ?

I feel this doc lacks a note about the drawbacks of the Synchronizer Token Pattern implemented by asp.net core.

In a situation where I can guarantee my user are on Chrome, [is it safe to disable the anti-request forgery](https://stackoverflow.com/questions/58290308/is-it-safe-to-disable-antiforgery-token-if-samesite-strict-on-authentication-coo) ?

**Comment by cjblomqvist** [comment]
@Yanal-Yves I think @blowdart is referring to the messy situation in Safari when it comes to samesite in general. There are/have been (not sure since Safari 13/latest OSX release?) multiple issues regarding samesite in Safari.

The one I think he especially is referring to is the one discussed here: https://www.chromestatus.com/feature/5088147346030592

Basically, it's impossible to opt-out of samesite Lax/Strict in Safari by having samesite None in version 12 (using OSX 10.14 or lower, or iOS 12 or lower). It's been fixed in the macOS 10.15, iOS 13 and the latest version of Safari 13.

So, the situation is that it's a mess (UA sniffing seems to be the best bet?) to support older versions of Safari/macOS/iOS at the same time as Chrome 80+ (or whenever they actually change their default behavior to Lax rather than None) if you ever want to set SameSite to None for any cookies. So what can you do?

If you want to use Samesite Lax or Strict on your cookies, it doesn't at all. It only affects if you want to opt-out of Samesite restrictions. Thus, if you want to do Samesite Lax, then none of the above issues (which I assume @blowdart is referring to) will affect you.


If we go back to the original issue - is it possible to get rid of the antiforgery token while still staying safe using samesite Lax? In order to answer that question, we first need to understand how samesite Lax is actually supposed to protect you. https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/ has a pretty decent write up of how it's supposed to work.

If you, based on above, realize that your stack is safe using Samesite Lax, what you have to ask yourself is which browsers will be safe (since if the browser doesn't support it properly, then your best bet is going back to antiforgery tokens). A baseline for support can be found at caniuse: https://caniuse.com/#search=samesite

So it actually looks pretty good, except for those few users still on IE11 on old Windowses (for most types of audiences, you should of course check your user base and what browsers/versions they use).

There are some additional cevaets though. Here we come back to Safari, because there are/have been more issues with Safari. More specifically, the issue described here is the one that can really mess with you: https://news.ycombinator.com/item?id=19855476 (you can track the issue here: https://bugs.webkit.org/show_bug.cgi?id=196375)

It's not been updated since March, but should be fixed and is probably shipped with Safari 13. So you're back to having issues with (at least some) Safari version 12 (and possible older versions - possibly including all older versions of the OS'es as well). This however depends on how you (your project/code base) do authentication, and if you're affected or not. It only affects 3rd-party authentication using POST in the return call (which is quite common for 3rd-party auth).

If you don't worry about Safari versions 12 and below OR you don't do 3rd-party auth (using cookies), then you can safely use Samesite Lax for all browsers supporting it as stated by https://caniuse.com/#search=samesite

That's at least what my research have told me. If @blowdart (or anyone else) knows anything else than I'm happy to hear what they have to say.

It's not above situation should block an update to the docs or not, but I wanted to clarify the situation for you and anyone else interested in the situation.

PS. It's kind of false to say that Chrome is breaking Safari. Rather, old Safari versions have bugs which becomes more difficult to handle if Chrome's starts to default Samesite to Lax. People seem to like to blame the chrome team here, and I'm not really sure why that's the case when it's issues with older Safari versions that is the real issue.
