### ISSUE TITLE
What's new in SignalR for 3.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14262]
Please use the issue to supply the MD markup I'll add to

* SignalR client-to-server streaming
* https://github.com/aspnet/AspNetCore/pull/7608

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3ff3cd-e7c3-f5f8-8993-067ca43f4ccc
* Version Independent ID: 8b8283b5-10f0-139d-b069-6ffab0ea4ca1
* Content: [What's new in ASP.NET Core 3.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/release-notes/aspnetcore-3.0.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-3.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by bradygaster** [comment]
not sure i understand. are you suggesting i add the MD markup yo uadded in #14250 to the client-to-server streaming article?

**Comment by Rick-Anderson** [comment]
Provide What's new in SignalR for 3.0

* Add it to this issue
* I will copy/paste that into #14250

**Comment by bradygaster** [comment]
Got it - saw Dan's intro email on the mission. All clear, sir. Thanks!

**Comment by Rick-Anderson** [comment]
Looks like it's updated [SignaR section of what's new in 3.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1#signalr)
