### ISSUE TITLE
Add Java Client to Server Streaming Section to SignalR Streaming Doc

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore.Docs#14261]
We need to add a small section for client to server streaming in Java.

**Comment by Rick-Anderson** [comment]
I created the new integrated issue for your. This is what I sent customers:

Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
