### ISSUE TITLE
3.0 update Worker Service template

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14269]
add info from https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-3/

DI, etc and test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio#worker-service-template)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/AspNetCore.Docs/issues/12841

**Comment by guardrex** [comment]
Worker Service was covered on https://github.com/aspnet/AspNetCore.Docs/pull/12665 ... and not for this topic. It's a Windows Service thing.

**Comment by Rick-Anderson** [comment]
@guardrex  that doesn't tell me anything about what it's used for. See **Worker Service template** in https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-3/

Should I put all that info into one include, or should we have a dedicated Worker Service topic?

**Comment by Rick-Anderson** [comment]
@scottaddie  I think worker service needs a dedicated page.
@guardrex  please suggest where this should go.
See https://www.hanselman.com/blog/dotnetNewWorkerWindowsServicesOrLinuxSystemdServicesInNETCore.aspx

**Comment by Rick-Anderson** [comment]
Actually, it looks like this is the right place. We just need more content here.

**Comment by guardrex** [comment]
More info ... *probably yes*. Not sure why a separate issue here tho ... there's an existing issue for this topic for 3.0 updates at https://github.com/aspnet/AspNetCore.Docs/issues/12841, which I haven't come to yet (*but I hope to reach it soon*).

The wiring for a WS (`UseWindowsService`) is covered in the WS topic. The Linux worker isn't covered, but there's an [existing issue for it](https://github.com/aspnet/AspNetCore.Docs/issues/14139). That could end up as it's own parallel topic to the 'Host in a WS' topic.

**Comment by scottaddie** [comment]
I think there should be a top-level ToC node for Worker Services. I wouldn't know to look here for info on the topic.

**Comment by guardrex** [comment]
Recommend caution on this given that background tasks and Windows Service are different topics that can be built on this template and do the same thing. To me (thus far), the worker service template is a means to an end ... a **template** ... not a separate app concept. However, I could be totally wrong about that. I haven't had time to dig into the `Microsoft.NET.Sdk.Worker` SDK and see what's what. I'd like to look and plan to so, but I'm too 🏃😅 right now. 🏃🏃🏃🏃🏃🏃

**Comment by Rick-Anderson** [comment]
> I think there should be a top-level ToC node for Worker Services. I wouldn't know to look here for info on the topic.

This is niche and google is your friend. I'd rather not pollute the top level TOC. We can review with `@danroth27`

**Comment by RickAndMSFT** [comment]
@scottaddie  the content really belongs in the .NET repo, not here.

**Comment by Rick-Anderson** [comment]
Doced at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#worker-service-template
