### ISSUE TITLE
What's new in 3.0 for Razor Components and Blazor

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14263]
Please use the issue to supply the MD markup I'll add to #14250

**Comment by guardrex** [comment]
@Rick-Anderson Is this a P1 thing (*Thursday-ish*) or more of a P2 thing (*early next week-ish*)?

**Comment by Rick-Anderson** [comment]
Neither, middle to late next week. Does that make it P3? lol

**Comment by guardrex** [comment]
Resolved on https://github.com/aspnet/AspNetCore.Docs/pull/14250.
