### ISSUE TITLE
Couldn't find an installed template that matches the input, searching online for one that does...

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14270]
```
$ dn new grpc -o GrpcGreeter
Getting ready...
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Basic client/server solution for gRPC on RaspberryPi" (gRPCpi) from author "Erik Taylor" in pack grpcpi
    To use this template, run the following command and try again:
        dotnet new -i grpcpi::1.0.2
```
```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet-3.0/sdk/3.0.100-preview9-014004/

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  3.0.100-preview9-014004 [/usr/share/dotnet-3.0/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/usr/share/dotnet-3.0/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/usr/share/dotnet-3.0/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
@JamesNK what's the right repo to open this issue?

**Comment by JamesNK** [comment]
aspnet/aspnetcore

**Comment by Rick-Anderson** [comment]
If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)
