### ISSUE TITLE
Focus is completely wrong

### ISSUE THREAD

**Issue by Nils-Berghs** [aspnet/AspNetCore.Docs#14275]
There is a ton of information about different log levels, filtering and other obvious stuff. 
Far more important things like logging providers are hardly explained (and for azure its totally outdated). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#azure-app-service-provider)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's outdated in [Azure App Service provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#azure-app-service-provider) ? The 3.0 version?
