### ISSUE TITLE
[Url] attribute allows spaces 

### ISSUE THREAD

**Issue by MythreyaK** [aspnet/AspNetCore.Docs#14283]
I am using the `[Url]` attribute to store URLs in a database and was surprised to see that a URL of the form `http://www.exam ple.com` was accepted, and so was `http://example.com/foo bar`! From what I've read around, a URL shouldn't contain a _literal_ space. Am I mistaken or is this the expected behavior?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by MythreyaK** [comment]
> Select Product feedback, not This Page

It wasn't there, so I added it in manually. Hope that works!

**Comment by Rick-Anderson** [comment]
This one should be there - that was an old message I sent previously

 Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by MythreyaK** [comment]
Do I still go ahead and do it, since the issue seems to have reached the .NET core team (`pranavkm` opened it on behalf of me)?

**Comment by Rick-Anderson** [comment]
Nope, I was just checking to see that you could do it next time with the updated instructions.

**Comment by MythreyaK** [comment]
Okay, got it! Thanks!

**Comment by Rick-Anderson** [comment]
Closing as tracked in `[Url] attribute allows spaces` https://github.com/dotnet/corefx/issues/41093
