### ISSUE TITLE
Was there supposed to be an Authorization folder from the start?

### ISSUE THREAD

**Issue by AskYous** [aspnet/AspNetCore.Docs#14298]
I'm on the part where it says to make a class inside the authorization folder, but the sentence makes it seem like the authorization folder was there the whole time. Was I supposed to create it before? If I'm supposed to create it now, the documentation should say to create a folder first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2#create-owner-manager-and-administrator-authorization-handlers-1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is an advanced tutorial so you sometimes need to make folders. We'll look at this again in the next doc sweep.

**Comment by AskYous** [comment]
Perhaps just change it from this:
> Create a ContactIsOwnerAuthorizationHandler class in the Authorization folder. 

To this:

> Create a **new** "Authorization" folder and create a ContactIsOwnerAuthorizationHandler class in it.

**Comment by Rick-Anderson** [comment]
Can you fix it. Change it to:

Create an "Authorization" folder and create a ContactIsOwnerAuthorizationHandler class in it.

**Comment by AskYous** [comment]
I never contributed to Microsoft docs before. Hopefully this fixes it: https://github.com/aspnet/AspNetCore.Docs/pull/14310
