### ISSUE TITLE
What is the recommended way of reading the Request Body?

### ISSUE THREAD

**Issue by gojanpaolo** [aspnet/AspNetCore.Docs#14306]
Logging the Request Body would be really helpful when troubleshooting the exception. Could you please include a recommended way of reading that? Thank you! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2#exception-filters)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See the logging articles.
cc @guardrex
