### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Yanal-Yves** [aspnet/AspNetCore.Docs#14300]
Hello,

In the Troubleshooting section of https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.2&tabs=visual-studio, the link "Download the completed app" is broken.
My guess is that it should point to https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu21snapshots/Part-4-Migrations
Could you fix it please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  just fixed this in a PR that should go live today.
