### ISSUE TITLE
ASP.NET Core -Detailed Lifecycle

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14307]
Can we get a **detailed lifecycle description** for asp.net core?
We have detailed one for mvc 5, <a href="https://opdhsblobprod04.blob.core.windows.net/contents/ed5efb1947c04bb29402a0c08d68958e/d0ed2e012c44fea6a368d4591ea14088?sv=2015-04-05&sr=b&sig=CNneagzWl5ZdFYZhNCUdF8KqHjNdhZXoNc%2FCTA8EEZk%3D&st=2019-09-13T20%3A22%3A51Z&se=2019-09-14T20%3A32%3A51Z&sp=r">see here</a>
[d0ed2e012c44fea6a368d4591ea14088[1].pdf](https://github.com/aspnet/AspNetCore.Docs/files/3611748/d0ed2e012c44fea6a368d4591ea14088.1.pdf)

On the first page you have high level and on the second a detailed view of the lifycycle.
I like it very much!
To have something like this for asp.net core 3 would be cool.

**Comment by Rick-Anderson** [comment]
Dup of #3524
Please vote up #3524
