### ISSUE TITLE
How to create a library targeting ASP.NET Core 3.0 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14309]
Copy from #14245 by @shirhatti 

**Help us make content visible**

- How to build a library targeting ASP.NET Core

**Describe the new topic**

Since the WebSDK has an implicit framework reference to AspNetCore, most folks don't see `<FrameworkReferences>` at all. We need some guidance for library authors on how to target ASP.NET. We probably need to include guidance on when to multi-target as well.

Issue came from https://github.com/aspnet/AspNetCore/issues/13541

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kierenj any chance you could provide the first draft PR?

At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by kierenj** [comment]
I'm not sure I'm best placed for that - I have more questions than answers! @JunTaoLuo, @shirhatti and others from https://github.com/aspnet/AspNetCore/issues/13541 seem to work on the team and know what's up?

**Comment by jjxtra** [comment]
Can't use controllers in class libraries anymore...

**Comment by davidfowl** [comment]
Sure you can, just add a FrameworkReference to ASP.NET Core.
