### ISSUE TITLE
"Microsoft.Extensions.Configuration.UserSecrets.targets" and "UserSecretsId" transformation in transitive dependencies

### ISSUE THREAD

**Issue by RamanBut-Husaim** [aspnet/AspNetCore.Docs#14315]
Hello everyone,

From my today's experience it seems that the only way this guide to work is to *explicitly* install `Microsoft.Extensions.Configuration.UserSecrets` as a dependency as it seems that [Microsoft.Extensions.Configuration.UserSecrets.targets](https://github.com/aspnet/Extensions/blob/release/2.2/src/Configuration/Config.UserSecrets/src/build/netstandard2.0/Microsoft.Extensions.Configuration.UserSecrets.targets) file that transforms `UserSecretsId` attribute into the assembly property does not work when the package is a transitive dependency in the project.

Our project setup is the following:

+ we have a so-called "platform" nuget package that represents a basis for our microservices;
+ this nuget package has `Microsoft.AspNetCore.App` as a dependency; it is installed via plain nuget reference mechanism with no additional `*.targets` or `*.props` files included inside;
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.6" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="2.2.1" />
    <PackageReference Include="Autofac" Version="4.9.4" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.4.0" />
    <PackageReference Include="Dapper" Version="1.60.6" />
    <PackageReference Include="Docker.DotNet" Version="3.125.2" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="IdentityModel" Version="3.10.10" />
    ...
</ItemGroup>
```
+ our microservice is using this "platform" package as a dependency as well;
+ we are relying on `CreateDefaultBuilder` method so that user secrets should be applied automatically;

Following the steps in this guide resulted in variables *NOT* being applied from the `secrets.json` file. To be more precise:
+ use "Development" environment; personally I'm using `JetBrains Rider` with proper env variable `ASPNETCORE_ENVIRONMENT=Development`;
+ `UserSecretsId` attribute was added into the `csproj` file;
```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>some-amazing-value</UserSecretsId>
  </PropertyGroup>
```
+ user secrets were added to the `secrets.json` file so that `dotnet user-secrets list` command returned valid results;
+ *NO* nuget package was installed as we are working with dotnet core;

The nuget debug process indicated that the following [line](https://github.com/aspnet/Extensions/blob/release/2.2/src/Configuration/Config.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L95) has not returned any `UserSecretsIdAttribute` and as a result no secrets were applied.

Once I've started to experiment with this I've found the following solutions:
+ remove `UserSecretsId` property from `csproj` file and utilize it directly in the code;
```cs
[assembly: UserSecretsId("some-amazing-value")]
```
+ preserve `UserSecretsId` property and install `Microsoft.Extensions.Configuration.UserSecrets` dependency as part of microservice project explicitly;
```xml
<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.2.0" />
```

Would really glad to get feedback on this and update the documentation accordingly in order to avoid others face the same situation again and spend an hour tracing this piece.

### Environment

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
```

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=linux#feedback)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@dougbu  who's the right contact to review this?

**Comment by dougbu** [comment]
I'm not sure. @anurse @mkArtakMSFT❔

**Comment by anurse** [comment]
Can you post a sample project that reproduces the issue so we can see how it works clearly? The UserSecrets package is almost always referenced transitively (even in a single project situation) via `Microsoft.AspNetCore.App`, so it should work transitively. What may not work is a project-to-project reference like this, where Project A references Project B which then references `Microsoft.AspNetCore.App`.

**Comment by RamanBut-Husaim** [comment]
Hello @anurse,
Thanks for the feedback. I'll try to prepare one and attach here.
Thanks!

**Comment by scottaddie** [comment]
@RamanBut-Husaim This is a friendly reminder to provide a sample project so that our team can investigate further.

**Comment by anurse** [comment]
Perfect timing! I was looking for this bug and couldn't remember where it had been filed.

We got https://github.com/aspnet/Extensions/issues/2743 reported recently which is the same root cause. I managed to repro it and reported https://github.com/dotnet/sdk/issues/4007 to track this.

Since it's not a docs issue, it's a product issue, I think this can be closed.
