### ISSUE TITLE
The instruction to enable Response Caching is wrong or invalid

### ISSUE THREAD

**Issue by minhhieugma** [aspnet/AspNetCore.Docs#14321]
The `app.Use(async (context, next) =>` should be placed before calling app.UseResponseCaching();

`The correct code as below:`
    

```
   app.Use(async (context, next) =>
    {
        context.Response.GetTypedHeaders().CacheControl = 
            new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
            {
                Public = true,
                MaxAge = TimeSpan.FromSeconds(10)
            };
        context.Response.Headers[Microsoft.Net.Http.Headers.HeaderNames.Vary] = 
            new string[] { "Accept-Encoding" };

        await next();
    });

    app.UseResponseCaching();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @minhhieugma ... The headers are added for **_subsequent requests_** and not meant to be processed on the first request to the app. @JunTaoLuo, do you want to stick with the current behavior, which goes back to when we first put this sample up back in 1.1 days 👴😄?
