### ISSUE TITLE
migrations generated are empty

### ISSUE THREAD

**Issue by AmjadKh** [aspnet/AspNetCore.Docs#14329]
when I run this command:
dotnet ef migrations add MaxLengthOnNames
it generates an empty migration (Up and Down functions are exist but nothing inside them)
should I write the migration code for creating the tables? or it will be automatically generated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [Tutorial: Create a complex data model - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I don't see anything in the model changes that would change the schema. Keep working, we'll look at this on the next doc sweep. cc @tdykstra

**Comment by Rick-Anderson** [comment]
If you're using SQLite, there won't be any changes,

**Comment by AmjadKh** [comment]
I found the problem, I did not add the DbSet<ClassName> inside the Context Class, that's why the tool did not recognize the change

**Comment by LayersOfAbstraction** [comment]
Had a problem like that. Decided to look at the completed version of the project which helped. I accidently declared an extra new IWebHost  that didn’t have an name of “host”. 
And because the using statement in the Main() method of my program file was expecting "host" it skipped the using statement that allowed the database to be seeded. Deleted that line.
