### ISSUE TITLE
File permissions on Linux

### ISSUE THREAD

**Issue by davegardner** [aspnet/AspNetCore.Docs#14320]
Using VSCode on Ubuntu 18.04. Following the instructions led to the need to preface shell commands with sudo because file permissions do not allow overwriting. I successfully built the app that way. In an attempt to eliminate the need for sudo I reinstalled NPM. This has not fixed the problem and in fact has made it worse. Some guidance on how to overcome this issue would be appreciated. Elimination of the cause would be wonderful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by anurse** [comment]
> Using VSCode on Ubuntu 18.04. Following the instructions led to the need to preface shell commands with sudo because file permissions do not allow overwriting.

This is definitely strange, you should not need to preface the commands with sudo. It sounds like something is messed up with the file permissions on your project rather than this being an issue with npm or SignalR.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
