### ISSUE TITLE
Update Blazor sample apps to 3.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#14337]
We have a number of official Blazor sample apps that live outside of the docs repo that also need to get updated to 3.0:

- [x] [Blazor FlightFinder](https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder)
- [x] [Blazor Validation](https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/Validation)
- [ ] [Blazor Workshop](https://github.com/dotnet-presentations/blazor-workshop/)

**Comment by danroth27** [comment]
@mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS would be you be able to handle this too?
I talked to @rynowak and the other issue we've discussed doesn't cover updating these samples.

**Comment by SteveSandersonMS** [comment]
Sure. I'll handle FlightFinder/Validation.

For the workshop, @rynowak and I can work out how to split that task, since we're the next ones actually delivering this workshop.

**Comment by SteveSandersonMS** [comment]
Validation/FlightFinder done in https://github.com/aspnet/samples/pull/46
