### ISSUE TITLE
Confusing statements

### ISSUE THREAD

**Issue by timothytrimble** [aspnet/AspNetCore.Docs#14345]
After "You can ignore that warning, it will be fixed in a later tutorial."
"The ef migrations add InitialCreate..." content is very confusing. How does this tie into having the reader execute the two PMC commands? Why is the content leading up to the "The Add-Migration command..." line needed for a new dev stepping through the tutorial? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@timothytrimble  keep reading, it will become clear.
