### ISSUE TITLE
Steps in this tutorial don't correspond to the views I'm presented in VS2017 

### ISSUE THREAD

**Issue by ssbaca** [aspnet/AspNetCore.Docs#14342]
When I go to "Deploy the app to Azure" none of the images corresponded to images to which I was presented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-2.2#deploy-the-app-to-azure)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie  I'd like to retire this doc and redirect to https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet

**Comment by Rick-Anderson** [comment]
@scottaddie  I think https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-01?view=vs-2019 would be better.

**Comment by ssbaca** [comment]
Rick,

Thank you for your timely reply.  You're really pushing me to VS2019!!  I better get going on it before 2019 is over!!!

Thank you for all the wonderful work that you have done over the years and continue to do.

Regards,
Stephen
