### ISSUE TITLE
3.0 Migration Discuss RazorPages AllowAreas option

### ISSUE THREAD

**Issue by ardalis** [aspnet/AspNetCore.Docs#14357]
[EDIT by guardrex to add the metadata for the migration topic]

In the 2.2 -> 3.0 Migration guide, cover what do with this:

```
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AuthorizePage("/Basket/Checkout");
                    options.AllowAreas = true; // THIS LINE
                })
```

The line noted above triggers this error in 3.0 latest preview:

```
Error | CS1061 | 'RazorPagesOptions' does not contain a definition for 'AllowAreas' and no accessible extension method 'AllowAreas' accepting a first argument of type 'RazorPagesOptions' could be found (are you missing a using directive or an assembly reference?)
```

I don't know what nuget package, if any, can be added to fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thus far, I see it was removed here :point_right: https://github.com/aspnet/AspNetCore/commit/f113a20dfd9d0c7c991e425fd8000ed6b64d19a5#diff-5c43af172dc698a7587dca36319961fc

... but is the default for areas to allow them? ... are u saying if you remove that and run it that the areas aren't allowed by default?

**Comment by serpent5** [comment]
`AllowAreas` is a compatibility switch. With 3.0 being a breaking change, Areas are "allowed" out of the box, so `options.AllowAreas = true;` can be dropped.

**Comment by guardrex** [comment]
Nice one @serpent5 ... I saw a passing remark on it but didn't have confirmation from the commit that dropped it.

**Comment by ardalis** [comment]
I'd mention that it can be removed in the migration doc. Otherwise it's going to be a compiler error customers are going to spend time trying to track down (instead of just deleting that line).

**Comment by guardrex** [comment]
@Rick-Anderson should add it.

**Comment by pranavkm** [comment]
@ardalis the feature is on by default (and there isn't a way to disable it). It was added as a compat switch for apps migrating from 2.1 -> 2.2 since it introduced a breaking behavior change. Removing it in 3.0 would be the right thing to do.

**Comment by Rick-Anderson** [comment]
@pranavkm I'll update [Compatibility version](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-3.0) and in the release notes mention the compatibility features have been removed for 3.0

**Comment by ardalis** [comment]
@pranavkm Thanks! I'm fine with removing it of course. My issue was that in the course of upgrading an app from 2.2 to 3.0 I had a bunch of missing references (due mostly to things coming out of Microsoft.AspNetCore.App) and this error blended in with those. So I spent at least 20 minutes trying to figure out which Nuget package I had to add to fix the error. Including a note that it can be removed in the migration guide will hopefully save others (and probably future me) from this frustration.

**Comment by Rick-Anderson** [comment]
`AllowAreas` is listed in [github.com/aspnet/Announcements label:"Breaking change"](https://github.com/aspnet/Announcements/issues?page=2&q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22+label%3A3.0.0) in issue [Breaking API changes in Antiforgery, Cors, Diagnostics, Mvc, and Routing #387](https://github.com/aspnet/Announcements/issues/387)

The migration guide has a link to the breaking issues. I don't want to repeat that info in the migration guide. Folks who hit this google will find this issue. If enough hit it, I'll consider adding it to the migration guide.
