### ISSUE TITLE
services.AddProtectedBrowserStorage(); return error. 

### ISSUE THREAD

**Issue by ahmeddawood88** [aspnet/AspNetCore.Docs#14359]
when i inserted this line of code 

services.AddProtectedBrowserStorage();

into Startup.cs file of my Blazor app, I got this error:
iservicecollection does not contain a definition for addprotectedbrowserstorage. 

I followed exactly what MS document instructed to work on Session management of Blazor App:
https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0

Any help is appreciated 
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you add the package to the project file?

https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-3.0#protected-browser-storage-experimental-package

**Comment by ahmeddawood88** [comment]
> Did you add the package to the project file?
> 
> https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-3.0#protected-browser-storage-experimental-package

@guardrex .. do you mean Microsoft.AspNetCore.ProtectedBrowserStorage.? and yes i did add the package

**Comment by guardrex** [comment]
Yes ... in that case ... open this issue for the engineers at ...

https://github.com/aspnet/AspLabs/issues

... which is the GitHub repo where they maintain that package.

**Comment by ahmeddawood88** [comment]
> Yes ... in that case ... open this issue for the engineers at ...
> 
> https://github.com/aspnet/AspLabs/issues
> 
> ... which is the GitHub repo where they maintain that package.

will do. Thanks a lot
