### ISSUE TITLE
Attribute splatting for components

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14351]
See https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-7/
Components can now capture and render additional attributes in addition to the component’s declared parameters. Additional attributes can be captured in a dictionary and then “splatted” onto an element as part of the component’s rendering using the new @attributes Razor directive. This feature is especially valuable when defining a component that produces a markup element that supports a variety of customizations. For instance if you were defining a component that produces an &lt;input&gt; element, it would be tedious to define all of the attributes &lt;input&gt; supports like maxlength or placeholder as component parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#attribute)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Already handled on https://github.com/aspnet/AspNetCore.Docs/pull/13460 and https://github.com/aspnet/AspNetCore.Docs/pull/13524.

* https://docs.microsoft.com/aspnet/core/mvc/views/razor#attributes
* https://docs.microsoft.com/aspnet/core/blazor/components#attribute-splatting-and-arbitrary-parameters
