### ISSUE TITLE
How to swap dB guidance in Integration Testing topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14354]
React to https://github.com/aspnet/AspNetCore.Docs/pull/14265#issuecomment-532171607

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by stevo-knievo** [comment]
@guardrex Guidance would be fantastic! I hope not just only on swapping the database. I hope also on how to seed the database. Currently, the seeding is happing in the fixture class. Meaning you can't really reuse the fixture class if you would like to seed the database with a different set of data.
