### ISSUE TITLE
Improve Blazor component lifecycle page

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#14353]
[EDIT by guardrex to add DR's notes from the 1st PR to this opening content list]

[EDIT by guardrex to update on work done and check off work items that have been completed since this issue was opened]

[EDIT by guardrex to remove plan to create a new lifecycle topic ... that's done]

This is a suggestion that it's time to address a whole bunch of *"how to do..."* question issues that we've been collecting in response to developers' questions:

 * [13473 - Improve lifecycle docs](https://github.com/aspnet/AspNetCore/issues/13473)
 * [12773 - Clarify lifecycle events](https://github.com/aspnet/AspNetCore.Docs/issues/12773)
 * [12896 - Wrong documentation for OnParametersSetAsync/OnParametersSet lifecycle methods](https://github.com/aspnet/AspNetCore.Docs/issues/12896)
 * [11741 - Ability for services to detect when JSRuntime is available and safe to invoke](https://github.com/aspnet/AspNetCore/issues/11741)
 * [13584 - Document "cancelable background work" pattern for components](https://github.com/aspnet/AspNetCore/issues/13584)
 * [14260 - Provide guidance about how to do async work in Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14260)
 * ... and probably many more. I was just searching for "lifecycle" and "background".

Expand content to include:

 * A detailed description of what happens in what order, including:
    * How async tasks affect this
    * When (re)rendering is interleaved into this
    * How things are ordered among parent/child components
    * What kinds of work you're expected to do in each of the methods
 * Relationship with `Dispose`
    * Example: Pattern for cancelling background work
 * Relationship with JS interop
    * Example: Initializing a JS library by passing an `ElementReference`

### From DR on the PR to create the initial *Lifecycle* topic

Instead of focusing purely on the lifecycle events I think we want this article to explain more broadly how components work, like how and when the render. We should walk the user through a day in the life a component in a Blazor app. The lifecycle events are then just specific points that you can plugin your specific behaviors. 

Things that I think should be covered:
- What happens during the initial render of the app
  - We probably need to address prerendering as part of this
- When components get instantiated
- When services get injected from DI
- What happens when a parent/root component gets rendered
- When do components render after the initial render
  - In response to UI events and explicit calls to StateHasChanged
- How long do components life for? When do they get disposed?

WRT the short *State changes* (`StateHasChanged`) section ...

I think this section would fit in better with a broader description of how and when components get rendered. Right now this section on StateHasChanged feels a bit out of context.

**Comment by SteveSandersonMS** [comment]
cc @mkArtakMSFT @danroth27 @rynowak since we already did the first cut of docs triage yesterday.

**Comment by guardrex** [comment]
> we're going to have to split up the giant "components" doc page into smaller pieces

We had a *Components* node to hold multiple topics because I thought that things would go in this direction. I wasn't allowed to keep that node (https://github.com/aspnet/AspNetCore.Docs/pull/10716#issuecomment-459464236), so it was dropped.

Options ...

1. Would you like to go back to a *Components* node (folder)? The current *Components* topic becomes the *Overview*/index of the node, and we can easily split out content and create new topics as needed.
1. Do you want to stick with what we have? Do you want to split this topic up into several topics that live out in the open *Blazor* node?
1. Have you devised a different TOC for basic and advanced components topics that we can put into place now?

**Comment by SteveSandersonMS** [comment]
By all means let's solve the question of how to manage the rest of the "components" material, but I think it can be independent of this specific work item.

My proposal here is just a first step: to split out the lifecycle topics described here into a separate docs page as a sibling of "components", "component libraries", "routing", "js interop" and so on. There's nothing inconsistent about that, since literally all these pages are about doing stuff with components.

**Comment by guardrex** [comment]
> it can be independent of this specific work item

We're only explicitly allowed to change the **physical** TOC (i.e., physical folders/URLs) and UIDs now ... in preview. After 3.0 GA, it will take an :pray: *act of the server gods* :pray: to change the physical TOC/UIDs. I **_strongly recommend_** doing it now ... like today. :smile: lol

> My proposal here is just a first step: to split out the lifecycle topics described here into a separate docs page as a sibling of "components", "component libraries", "routing", "js interop" and so on. There's nothing inconsistent about that, since literally all these pages are about doing stuff with components.

Some of your phrasing and words are overloaded, so I don't follow. Explain it out in terms of TOC nodes (folders). I'll lay out the options below ... which direction would you like to go?

### Option 1: All components subject matter topics are at the same level in the *Blazor* node (folder).

* Blazor
  * Overview
  * Supported platforms
  * Get started
  * Hosting models
  * Build your first app
  * Components &ndash; The *components.md* topic (file).
  * **_New Components Subject Matter Topic 1_** (same level as current *Components* topic)
  * **_New Components Subject Matter Topic 2_** (same level as current *Components* topic)
  * **Additional new components subject matter topics that will come later.** (same level as current *Components* topic)
  * Forms and validation
  * Component libraries
  * Layouts
  * Dependency injection
  * Routing
  * JavaScript interop
  * Security and Identity &ndash; A node (folder) for ...
    * Overview
    * Blazor Server
  * State management
  * Handle errors
  * Debug
  * Call a web API
  * Hosting and deployment &ndash; A node (folder) for ...
    * Overview
    * Blazor WebAssembly
    * Blazor Server
    * Configure the Linker

### Option 2: Go back to a *Components* node (folder) and put the components subject matter topics in that node (folder) ... BUT ... leave the other 'stuff you do with components' topics where they currently are in the *Blazor* node (folder).

* Blazor
  * Overview
  * Supported platforms
  * Get started
  * Hosting models
  * Build your first app
  * Components &ndash; A node (folder) that holds ...
    * Overview (starts with our current *Components* content today and we refactor what's in the _Overview_ as we go)
    * **New Components Subject Matter Topic 1**
    * **New Components Subject Matter Topic 2**
    * **Additional new components subject matter topics that will come later.**
  * Forms and validation
  * Component libraries
  * Layouts
  * Dependency injection
  * Routing
  * JavaScript interop
  * Security and Identity &ndash; A node (folder) for ...
    * Overview
    * Blazor Server
  * State management
  * Handle errors
  * Debug
  * Call a web API
  * Hosting and deployment &ndash; A node (folder) for ...
    * Overview
    * Blazor WebAssembly
    * Blazor Server
    * Configure the Linker

### Option 3: Go back to a *Components* node (folder) and put the components subject matter topics in that node (folder) ... AND ... move the other 'stuff you do with components' topics into that *Components* node (folder), too.

* Blazor
  * Overview
  * Supported platforms
  * Get started
  * Hosting models
  * Build your first app
  * Components &ndash; A node (folder) that holds ...
    * Overview (starts with our current *Components* content today and we refactor what's in the _Overview_ as we go)
    * Routing
    * Component libraries
    * JavaScript interop
    * **New Components Subject Matter Topic 1**
    * **New Components Subject Matter Topic 2**
    * **Additional new components subject matter topics that will come later.**
  * Forms and validation
  * Layouts
  * Dependency injection
  * Security and Identity &ndash; A node (folder) for ...
    * Overview
    * Blazor Server
  * State management
  * Handle errors
  * Debug
  * Call a web API
  * Hosting and deployment &ndash; A node (folder) for ...
    * Overview
    * Blazor WebAssembly
    * Blazor Server
    * Configure the Linker

### Option 4: Something else

Whatever u decide to do WRT nodes/physical folders for URLs and UIDs ... please let's do it now ... in preview ... **_this week!_** :smile: lol

**Comment by SteveSandersonMS** [comment]
I think option 1 is fine. I don't think there's any real advantage to arguing for an extra level of nesting.  Customers won't see any difference as long as they can find the content they want, plus I don't think these topics are truly nestable in any objective way (e.g, there's *lots* of components-related stuff in the other non-"components" pages already).

**Comment by guardrex** [comment]
Indeed, yes, no changes is the happy path. :smile: I'm just saying that if such changes are desired, let's make them now.

**Comment by guardrex** [comment]
Several of the issues here have been resolved, and we should split the remaining pieces into different work items:

* **Add or improve docs for lifecycle methods** &ndash; Was already opened for a possible diagram. I've made the existing issue mirror the engineering issue. I've added the comments from this issue's opening comment to the issue. See: [Lifecycle diagram and coverage (aspnet/AspNetCore.Docs #16287)](https://github.com/aspnet/AspNetCore.Docs/issues/16287)
* **Document "cancelable background work" pattern for components** &ndash; Created [Document "cancelable background work" pattern for components (aspnet/AspNetCore.Docs #16903)](https://github.com/aspnet/AspNetCore.Docs/issues/16903) to track it.
* WRT splitting the *Components* topic &ndash; Created [Split Razor Components topic (aspnet/AspNetCore.Docs #16904)](https://github.com/aspnet/AspNetCore.Docs/issues/16904) to cover.
