### ISSUE TITLE
Escape sequence not working with  HTTP REPL

### ISSUE THREAD

**Issue by jmezach** [aspnet/AspNetCore.Docs#14356]
I'm trying to run a script with the HTTP REPL as documented on this page, but the script involves performing a POST and I'm trying to define the request body inline using the -c argument, According to this doc I need to use double quotes around the entire request body and then use single quotes within the request body itself. Unfortunately this does not seem to be accepted by the API (that is running on ASP.NET Core 3.0) with the following error:

Request to http://localhost:5000...

POST /api/Customer HTTP/1.1
Content-Length: 51
Content-Type: application/json
User-Agent: HTTP-REPL

{
  'id': 1,
  'firstName': 'Jane',
  'lastName': 'Doe'
}

Response from http://localhost:5000...

HTTP/1.1 400 Bad Request
Content-Type: application/problem+json; charset=utf-8
Date: Tue, 17 Sep 2019 19:19:08 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|a74e9a4b-435227a4c12560a7.",
  "errors": {
    "$": [
      "''' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 2."
    ]
  }
}

I've tried various different combinations of escaping, but none of them seem to work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16842b60-b268-a322-8078-c0b27c57fa7d
* Version Independent ID: d63c12f3-220e-9067-ead5-90e644c06591
* Content: [Test web APIs with the HTTP REPL](https://docs.microsoft.com/en-us/aspnet/core/web-api/http-repl?view=aspnetcore-2.2&tabs=linux#test-http-post-requests)
* Content Source: [aspnetcore/web-api/http-repl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/http-repl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by jmezach** [comment]
After some more experimentation I discovered that using \" works correctly, but that is not the suggested approach in the docs, and arguably not very user friendly ;).

**Comment by anurse** [comment]
I think the doc just needs to be updated here to use the proper escaping so that `"` can be used in the JSON blog. The string `"{ 'id': 2, 'name': 'Cherry' }"` is not valid JSON since JSON *requires* the use of `"` around strings. A single quote (`'`) is not allowed by the spec. Some parsers, like Newtonsoft.Json, are more lenient but in ASP.NET Core 3.0 we use System.Text.Json which is stricter about this.

I don't know what escaping syntax is used by the httprepl. I also don't know who owns the repl now as I don't believe the ASP.NET Core engineering team does.

**Comment by Rick-Anderson** [comment]
@jmezach  can you post the proper escaping - or better yet, PR the doc.
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by scottaddie** [comment]
I'll take care of this issue. I'm already in there making other updates.
