### ISSUE TITLE
A few thoughts on "Migrate from ASP.NET Core 2.2 to 3.0"

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#14362]
Just a few thoughts I had when reading through this:

* The Prerequisites tab for Visual Studio references ".NET Core SDK 3.0 Preview", but the other tabs reference ".NET Core SDK 3.0".
* "Migrate Startup.Configure" states: "for example, place UseCors before UseAuthentication, UseAuthorization, and UseMvc", but I think `UseMvc` should probably be `UseEndpoints`.
* The final link in the document displays as a full URL but would look better as something like "runtime compilation".

Let me know what you think and I'd be happy to PR any changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I just noticed something else:

> The new methods can also be combined. The following example is equivalent to calling `AddMvc` in ASP.NET Core 2.2:
>
>     public void ConfigureServices(IServiceCollection services)
>     {
>         services.AddControllers();
>         services.AddRazorPages();
>     }

In the snippet shown, it should be `AddControllersWithViews()` instead of `AddControllers()`.

**Comment by Rick-Anderson** [comment]
Right again. Can you PR this?

**Comment by serpent5** [comment]
Yeah, certainly. Do you want points 2 and 3 plus the `AddControllersWithViews` suggestion?

**Comment by Rick-Anderson** [comment]
yes everything
