### ISSUE TITLE
Can't create Blazor Client with SDK 3.0.100-rc1-014190

### ISSUE THREAD

**Issue by smjltd** [aspnet/AspNetCore.Docs#14367]
update the command in docs from 
`dotnet new blazorwasm -o WebApplication1`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@smjltd Run the template install command ...

```console
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19457.4
```

It has to be run after the SDK is installed.

**Comment by smjltd** [comment]
you mean 3.0.100-rc1-014190

**Comment by guardrex** [comment]
That's the SDK version ... not the package version that contains the templates.

Execute ...

```console
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19457.4
```

... and try to create the app from the template again. It should work 🤞.

**Comment by smjltd** [comment]
it worked thanks 😘
