### ISSUE TITLE
Missing information about using services.Configure<> to inject configuration into controllers

### ISSUE THREAD

**Issue by mxa0079** [aspnet/AspNetCore.Docs#14379]
This article is missing a very useful and relevant technique to inject a custom configuration using `services.Configure<MyConfigCustomObject>(Configuration.GetSection("MyConfig"))`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mxa0079 ... That's part of the Options API and covered here :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/options#general-options-configuration-1
