### ISSUE TITLE
Can this feature be used in a viewmodel?

### ISSUE THREAD

**Issue by kdawg1406** [aspnet/AspNetCore.Docs#14373]
[EDIT by guardrex to escape the "\<" in the first sentence to get it to show up in the comment.]

To be clear, I'm referring to OwningComponentBase and OwningComponentBase\<T>.

Can this feature be used in a ViewModel or only used in the @code or code-behind file?  If only in @code or code-behind, this would limit the ability to use ViewModels.  

Thanks for your thoughts,

Karl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You can register the ViewModel in the DI as a `scoped` service. Then resolve it from the provided service provider on the OwningComponentBase.
