### ISSUE TITLE
Identity Scaffolding not working VS 2019 version 16.2.5

### ISSUE THREAD

**Issue by Jeevanchathuranga** [aspnet/AspNetCore.Docs#14380]
I add the new scaffold item for the fresh my ASP-NET Core 2.2/2.1 MVC application.

Set up

- ASP.NET Core 2.2.
- Individual authentication.
- Visual Studio 16.2.5

After running the Scaffold command, the code generation log says:
Finding the generator 'identity'...
Running the generator 'identity'...
....and it just waits there forever

**Comment by Rick-Anderson** [comment]
What SDK? Does the command line work?
Use the Visual Studio feedback menu item to leave feedback.  Help >  Send Feedback
