### ISSUE TITLE
Sign Out Doesn't Work

### ISSUE THREAD

**Issue by stalbot123** [aspnet/AspNetCore.Docs#14387]
Following the steps above work great - I'm able to authenticate with Microsoft. The problem is that a user will Log Out of my application, which invalidates my sites tokens/cookies (which is good), but then when another user signs in, the Microsoft Sign In page is shown for a brief moment before signing in with the first user's credentials.
How do I invalidate the first user's token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)

Include steps to reproduce the bug and the version you're using `dotnet --version`

**Comment by stalbot123** [comment]
Not sure that it's a defect; perhaps I don't understand the proper way to logout of the application. This guide doesn't talk about a successful logout though, so I wouldn't know what I'm doing wrong. I can open an issue as you instruct. How do I ensure that it gets tagged to external login appropriately?

**Comment by Rick-Anderson** [comment]
Selecting the sign-out UI should do a correct sign-out. If it doesn't, create the simplest possible sample (from the templates) that reproduces the problem. I think there was a problem with 2.1. What version are you using?

**Comment by timmywiff** [comment]
This is also happening to me using 3.1. I click sign out, which sings me out of the app. Then, clicking Microsoft to sing in, signs in the previous user.

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate).
