### ISSUE TITLE
WebHost in ASP.NET Core 3 startup order (code shows IHostedService tasks before IApplicationStartup notified)

### ISSUE THREAD

**Issue by manigandham** [aspnet/AspNetCore.Docs#14381]
On this page it says: 

> When using the Web Host, StartAsync is called after the server has started and IApplicationLifetime.ApplicationStarted is triggered. When using the Generic Host, StartAsync is called before ApplicationStarted is triggered.

However the code from the latest v3.0.0-preview9 shows that the `StartAsync` for hosted services from `WebHost` is still called before `ApplicationStarted`: https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview9.19424.4/src/Hosting/Hosting/src/Internal/WebHost.cs#L154

This is the better and expected behavior by the way, looks like it's just the documentation that needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher to confirm and then I'll make an update. Thanks for reporting @manigandham.

**Comment by davidfowl** [comment]
Yep we made a change in 3.0 https://github.com/aspnet/AspNetCore/pull/11575
