### ISSUE TITLE
New topic: Secure Web API

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14391]
Currently we support authentication and authorization for APIs with SPA apps. For any other scenario,[ Identity Server](https://identityserver.io/) already has plenty of documentation and samples.

**Comment by anurse** [comment]
What's the request here? A topic about how to build a SPA that calls a Web API with AuthN/AuthZ?

**Comment by Rick-Anderson** [comment]
> What's the request here? A topic about how to build a SPA that calls a Web API with AuthN/AuthZ?

Now, we get lots of customers requests on how to secure Web API. Should I make the following an include and paste it in all the WebAPI topics?

 To secure web APIs and SPAs, use IdentityServer4. IdentityServer4 is an OpenID Connect and OAuth 2.0 framework for ASP.NET Core 3.0. IdentityServer4 enables the following security features:

Authentication as a Service (AaaS)
Single sign-on/off (SSO) over multiple application types
Access control for APIs
Federation Gateway

**Comment by Rick-Anderson** [comment]
It's an include now
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/IdentityServer4.md
I'll paste it in more WebAPI topics and close this issue if that's OK.

**Comment by anurse** [comment]
I don't know if I would go as far as to say "To secure APIs, use IdentityServer". While IdentityServer is a fantastic option, it's not the only one. You could use Azure AD, Azure AD B2C, as well as other services/components.

@blowdart any thoughts here?

**Comment by Rick-Anderson** [comment]
I'll update [the include](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/IdentityServer4.md) to list those options.

**Comment by blowdart** [comment]
Yea, leave it as options, it's a "not our concern" sort of
