### ISSUE TITLE
Where is the example source code ?

### ISSUE THREAD

**Issue by mchudinov** [aspnet/AspNetCore.Docs#14396]
Is example source code available? 
Code in the section "Configure the underlying OpenIdConnectOptions/JwtBearer/Cookie options" is no clear. It is "omitted for brevity" too much. It is absolutely unclear how to setup authentication from B2C based on this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
@mchudinov  there is no sample code with this. Hopefull @CamSoper can provide more details.

**Comment by CamSoper** [comment]
@mchudinov What options do you need to set?

**Comment by mchudinov** [comment]
1. I need to redirect a user to B2C login page when user comes unauthorised.
2. I need to set authentication om some certain controllers, when some other controllers stay anonymous access.
3. I need to add claims to identity principal. E-mail for example.

I see some strange definitions in generated code in _LoginPartial.cshtml
asp-area="AzureADB2C" asp-controller="Account" asp-action="SignIn"
Where these definitions come from?
There are no such areas/controllers in code.

**Comment by CamSoper** [comment]
@mchudinov The areas and controllers are coming from compiled Razor assemblies.

In your *Startup.cs*, you should see something like this somewhere:

```
services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
  .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));
```

That's what wires up ASP.NET Core authentication with B2C. From there, all the other behaviors are the same as any other ASP.NET Core auth. You can decorate controllers with `[AllowAnonymous]` and redirection to the signin URL should happen automatically when they're not authenticated.

**Comment by CamSoper** [comment]
Tagging in @blowdart - Can you recommend someone who has a good grasp of the B2C integration? I haven't done much with it lately.

**Comment by blowdart** [comment]
None of this is specific to B2C except the email claim, which is in their configuration in azure. The rest is "Make B2C your only auth" and "Use authorize"

**Comment by CamSoper** [comment]
Stale conversation. @mchudino if you're still looking for help on this please let me know and I'll reopen.
