### ISSUE TITLE
Seeing Different Results btw VS and CL when Trying to Include Files Using DotNetPublishFiles in csproj File

### ISSUE THREAD

**Issue by ashish4915** [aspnet/AspNetCore.Docs#14390]
# Issue description

We need to copy files from another location into a location in our publish destination.

We added the following to the csproj file:

```
<ItemGroup>
<_EdrResponseFetcherFiles Include="..\TechShare.EdrGateway.EdrResponseFetcher\bin\Release\netcoreapp2.1\**" />
<DotNetPublishFiles Include="@(_EdrResponseFetcherFiles)">
  <DestinationRelativePath>App_Data\jobs\continuous\EdrResponseFetcher\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
</DotNetPublishFiles>
</ItemGroup>
```

The files move correctly when publishing through VS 2017 but it does not work from the command line. We are using the following command: 

`dotnet  publish src\TechShare.EdrGateway.UI --configuration Release --output c:/publish/p1 --framework netcoreapp2.1`

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong>
</summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
Open an issue in https://github.com/dotnet/cli and  include `dotnet --info` output.
