### ISSUE TITLE
Component binding: 'bind-value' and 'bind-property' syntax confusing

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14409]
From @enetstudio at https://github.com/aspnet/AspNetCore.Docs/issues/14144#issuecomment-533101340 ...

> I just can't get this; why the `bind-Value="@password"` in `<PasswordField bind-Value="@password" />` and not `<PasswordField bind-password="@password" />`
>
> Are we not suppose to use the name of a parameter property after the hyphen; in that case `password` ?
>
> As far as I understand, when you use Html input tag, and use `@Bind="@SomeProperty"`, the default attribute is `value`. This is as though we used this syntax instead: `@bind-value="@SomeProperty"`, but here we speak of one component binding to another component. I guess that no default attribute can be determined. Why `value` and not `password`? And if both can be used, I still want to understand why `value` can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @enetstudio ... Yes, I'm currently aware (and use in the sample code in the *Chained bind* section of this page) **the property** (`<PasswordField @bind-Password="password" />`) and not `bind-value`. `bind-value` is used with `bind-value:{event}`.

We'll wait here for engineering make additional remarks for doc updates. We need a little bit of time tho ... a couple of weeks. We're working hard on the 3.0 doc updates. 🏃😅 *Stand-by* for a bit.

**Comment by enetstudio** [comment]
Thanks for the clarification..
