### ISSUE TITLE
Differences between asp.net middleware and GRPC interceptor

### ISSUE THREAD

**Issue by PawelHaracz** [aspnet/AspNetCore.Docs#14406]
Can you tell more whats differences are between asp.net middleware and GRPC interceptor when I'm using GRPC communication in .net core3.0? is a performance of GRPC interceptor better? or it's almost the same, and there is one difference that GRPC can have access to response/request before and after the route handler is called

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JamesNK please comment.

**Comment by JamesNK** [comment]
1. ASP.NET Core middleware runs before gRPC interceptors.
2. ASP.NET Core middleware gives you access to HttpContext, HttpRequest, HttpResponse.
3. gRPC interceptors give you access to the deserialized message sent to a call, and the message being returned from the call before it is serialized. Middleware can only access bytes from the request and response streams.
