### ISSUE TITLE
How can we implement global exception handling?

### ISSUE THREAD

**Issue by aueda** [aspnet/AspNetCore.Docs#14415]
The section "Places where errors may occur" shows all the places where an exception might be thrown, but the recommended resolution is wrapping the code with local try-catch statements. While we can add local try-catch to all the places, we might miss a few places and an unhandled exception might freeze the application.

Is there a way to implement a global exception handling, so we can catch any unhandled exception, like the ASP.NET custom errors? It would be useful to have a global exception handling so we can cover any unexpected exception while delivering a user-friendly page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.0#manage-unhandled-exceptions-in-developer-code)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by pranavkm** [comment]
@aueda please see the discussion here: https://github.com/aspnet/AspNetCore/issues/13452
