### ISSUE TITLE
Configure services without Startup Example is wrong

### ISSUE THREAD

**Issue by fitdev** [aspnet/AspNetCore.Docs#14420]
[EDIT by guardrex to fix the code block]

As of Asp.Net Core 3 RC1, the example does not work. It took me a while to figure out why. Turns out the 
```
.ConfigureServices(services =>
        {
            services.AddControllersWithViews();

        })
```

parts must be called _after_ `.ConfigureWebHostDefaults( ...` had a chance to run. So, configuration of ASP-specific services (like MVC or Authorization) need to happen within ```
```
.ConfigureWebHostDefaults(webBuilder => {

webBuilder.ConfigureServices(services =>
        {
            services.AddControllersWithViews();
        }
//webBuilder.Configure stuff follows
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
Known issue: https://github.com/aspnet/AspNetCore/issues/13765

**Comment by guardrex** [comment]
Since it's marked for 3.1, shouldn't we go ahead with the PR that I just put up?
