### ISSUE TITLE
 we don't refer to the strings passed into link generation as URIs. 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14428]
See https://github.com/aspnet/AspNetCore.Docs/pull/13993#pullrequestreview-289662320

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 can you suggest better wording in the 3.0 version?

**Comment by Rick-Anderson** [comment]
How about changing 
`is part of the URI to access the ` to
`is part of the Page name to access the`

and
`can be used to generate URIs to the`  to
`can be used to generate the Page name to the`

**Comment by serpent5** [comment]
How about something along the lines of this?:

> The string `./Index` is the page name used to access the preceding page. In this example, the relative page name of _./Index_ resolves as an absolute page name of *Pages/Customers/Index.cshtml*. The call to `RedirectToPage("./Index")` results in a browser redirect to a URL that is generated from this page name.

**Comment by Rick-Anderson** [comment]
Perfect. Do you want to PR this?
