### ISSUE TITLE
HttpRequest.Protocol always / only reports HTTP/1.1

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14434]
"If an HTTP/2 connection is established, HttpRequest.Protocol reports HTTP/2."

That's not true. I have the following setup in Program.cs:
```
`            .ConfigureKestrel((context, options) =&gt;
            {
                options.Listen(IPAddress.Any, 5002, listenOptions =&gt;
                {
                    listenOptions.UseHttps("/tmp/localhost.pfx", "4xLabs.com");
                    listenOptions.UseConnectionLogging();
                    listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                    //listenOptions.UseHttps("testCert.pfx", "testPassword");
                });
            });
```
And I log HttpRequest:
```
            app.Use(async (context, next) =&gt;
            {
                // Request method, scheme, and path
                _logger.LogInformation(JsonConvert.SerializeObject(new RequestLog(context?.Request?.Method, 
                                    context?.Request?.Scheme, 
                                    context?.Request?.PathBase, 
                                    context?.Request?.Path, 
                                    context?.Request?.Host.ToString(), 
                                    context?.Request?.ContentLength, 
                                    context?.Connection?.RemoteIpAddress?.ToString(), 
                                    context?.Request?.QueryString.ToString(), 
                                    context?.Request?.ContentType,
                                    context?.Request?.Protocol,
                                    context?.Request?.Headers
                                    )));
                await next();
            });
```
I use Chrome to browse to my application. Logs are collected by Elasticsearch and shown in Kibana. Application is deployed to Kubernetes on cloud behind Load Balancer which uses HTTPS. Unfortunately ONLY HTTP/1.1 is recorded. There is no other protocols observed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#http2-support-1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @khteh ... please open this for the engineers at https://github.com/aspnet/AspNetCore/issues. If we need to make a docs change after they react to that, then we can re-open over here.
