### ISSUE TITLE
Wrong return type in IActionResult examples?

### ISSUE THREAD

**Issue by dvdgutzmann** [aspnet/AspNetCore.Docs#14432]
Shouldn't the return type in the examples for IActionResult type actually be IActionResult and Task&lt;IActionResult&gt;, respectively?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.2#specific-type)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Yes. Thank you for letting us know.
