### ISSUE TITLE
AzureAD Jwt Bearer Sample

### ISSUE THREAD

**Issue by udlose** [aspnet/AspNetCore.Docs#14437]
Are there any samples on setting up AzureAD authentication with JwtBearer option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82950389-524e-0754-a125-addeccbdb1b3
* Version Independent ID: 80b7f7cf-dc2e-137a-5aa7-fa88da63ac80
* Content: [Authentication samples for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/samples.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Not in this doc set.

**Comment by udlose** [comment]
Why was this closed? Could you at least either provide a link to an example or work on creating one?
