### ISSUE TITLE
How about internationalization (i18n) and translation

### ISSUE THREAD

**Issue by epsitec** [aspnet/AspNetCore.Docs#14433]
Hardcoding the validation messages into C# code attributes is a straightforward solution for simple projects. But how would you integrate this with I18N?

```cs
public class ExampleModel
{
    [Required]
    [StringLength(10, ErrorMessage = "Name is too long.")] // <-- I18N issue
    public string Name { get; set; }
}
```

I feel that as of today, Blazor is not yet ready for real-world scenarios because of this. Living in a multilingual country (Switzerland), where we need to generate UIs at least in German, French and English, and ideally also in Italian (and theoretically even in Romansh).

Did I miss some underlying mechanism which would allow me to replace hardcoded strings with culture dependent content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There are some existing engineering issues. Search over there and see what you can find:

* https://github.com/aspnet/AspNetCore/issues/12158
* https://github.com/aspnet/AspNetCore/issues/12088

**Comment by guardrex** [comment]
Hello @epsitec ... Recommend that you open over on the engineering issue. This probably has to go into design in the framework, not something that docs alone can address. Search open **and closed** issues first; and if you don't find a related issue on globalization/localization that matches your ask, open a new issue ...

https://github.com/aspnet/AspNetCore/issues
