### ISSUE TITLE
Create Microsoft.dotnet-openapi doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14447]
## General
https://docs.microsoft.com/en-ca/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.1 covers the current state of client code generation in ASP.NET Core web sites. However, we're working to give customers simple ways to annotate their project files for automated code generation during every build (as source API descriptions change) and that should also be documented.

Note tooling for the new experience isn't going to happen immediately. The initial documentation should focus on manual edits to .csproj files.

## Issues with Existing Topics
Does not cover work described in aspnet/AspNetCore#4896 and its sub-issues.

**Comment by scottaddie** [comment]
@Rick-Anderson Can this issue be closed now?
