### ISSUE TITLE
Update HTTP REPL installation command for 3.0 RTM

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#14441]
When 3.0 ships next week, the `--version` option should be removed from the installation command.

**Comment by Rick-Anderson** [comment]
@scottaddie  were're tracking these in https://github.com/aspnet/AspNetCore.Docs/projects/47

I set it for you.

**Comment by tlmii** [comment]
@scottaddie The 3.0 nuget package is available so the command without the `--version` option works now.

**Comment by scottaddie** [comment]
This change is live.
