### ISSUE TITLE
Docs are no longer current

### ISSUE THREAD

**Issue by sbsw** [aspnet/AspNetCore.Docs#14453]
The code example at the beginning of this document refers to `services.AddIdentity` and `services.ConfigureApplicationCookie`, but guidance on other Microsoft documentation pages (as well as the code created by the current VS templates) uses `services.AddDefaultIdentity` and `services.Configure<CookiePolicyOptions>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@haok please review

**Comment by HaoK** [comment]
I think the migration docs are fine, as those APIs all still work, they might not be the same APIs that the current templates use, but the document is about migration to 2.0 correct?

**Comment by Rick-Anderson** [comment]
> but the document is about migration to 2.0 correct?

Correct.

@scottaddie  do you want to track this for your migration to 3.0 docs?
