### ISSUE TITLE
How to understand the ReadinessPublisher sample

### ISSUE THREAD

**Issue by ThomasArdal** [aspnet/AspNetCore.Docs#14458]
I'm trying to understand the `ReadinessPublisher` class in the health checks 2.x and 3.x samples. I have two main questions for things that don't make sense. At least not in my head.

### Why is `Entries` there?

There's a list of health results named `Entries`. The publisher keeps pushing to this list:

```csharp
Entries.Add((report, cancellationToken));
```

But the results are new read or logged by anyone. What is the purpose of this list?

### Who sets `Exception`?

There's a property named `Exception` on the publisher. No-one ever sets this property to any value. Is that done automatically somehow? The publisher checks if the exception is not null and then throw it:

```csharp
if (Exception != null)
{
    throw Exception;
}
```

I cannot see when this if will ever be true?

**Comment by guardrex** [comment]
Hello @ThomasArdal ... We recommend using the feedback form at the bottom of the topic to open an issue on the repo. It applies metadata and pings the author. I'll move this over to a new issue.
