### ISSUE TITLE
How to understand the ReadinessPublisher sample

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14459]
From @ThomasArdal on https://github.com/aspnet/AspNetCore.Docs/issues/14458 ...

I'm trying to understand the `ReadinessPublisher` class in the health checks 2.x and 3.x samples. I have two main questions for things that don't make sense. At least not in my head.

### Why is `Entries` there?

There's a list of health results named `Entries`. The publisher keeps pushing to this list:

```csharp
Entries.Add((report, cancellationToken));
```

But the results are new read or logged by anyone. What is the purpose of this list?

### Who sets `Exception`?

There's a property named `Exception` on the publisher. No-one ever sets this property to any value. Is that done automatically somehow? The publisher checks if the exception is not null and then throw it:

```csharp
if (Exception != null)
{
    throw Exception;
}
```

I cannot see when this if will ever be true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`IHealthCheckPublisher` doesn't seem to demand the presence of these. However, they are in the ref source test publisher at https://github.com/aspnet/Extensions/blob/master/src/HealthChecks/HealthChecks/test/HealthCheckPublisherHostedServiceTest.cs#L490-L526. There are also some other members that aren't present in the topic's sample: `Started` and `Wait`.

@rynowak will let us know, and I'll provide more info in the doc:

1. `Entries`
1. `Exception`
1. `Started`: Add to the topic/sample?
1. `Wait`: Add to topic+sample?

@ThomasArdal, note that we might get a response *weeks* out because of the on-going priority 3.0 work right now. 🏃😅 I'll mark this for October on the docs side ... that's the soonest that I'd be able to update the content with *the answers*.

**Comment by ThomasArdal** [comment]
Totally understand the priority vs. 3.0 here.

It makes a lot of sense to extend the test publisher with these properties, since that makes it possible to assert events handled, etc. But for developing a new health publisher, I believe it makes it harder for new people to understand what's required of a publisher. To my understanding, nothing more than the `PublishAsync` method needs to be implemented.

**Comment by guardrex** [comment]
> makes it harder for new people to understand what's required of a publisher

Agree ... and these members should be explained out if they're going to be there. I should've asked when we were working on it 🙈 ... but 🏃 ... and 🏃🏃  ........ and 🏃🏃🏃 ... things get missed when a topic first goes up and we're working so fast. Thanks for opening this issue. :+1:

> To my understanding, nothing more than the `PublishAsync` method needs to be implemented.

Agree ... per the interface, that's true.

**Comment by rynowak** [comment]
Those things are part of a test. How did unit testing code get turned into a sample? 

Here's an example of a real publisher. https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/706fb5b7c1991272ab73aa00a3e868c03589d93f/src/HealthChecks.Publisher.Prometheus/PrometheusGatewayPublisher.cs

I can see how it would be hard to produce a good sample for the docs because 100% of the code will depend on the scenario.

**Comment by guardrex** [comment]
We didn't get reviewed properly due to a push to merge doc content. https://github.com/aspnet/AspNetCore.Docs/pull/10728

We can fix it up now. This is already scheduled for October, so I'll put an :eye: on it soon.

**Comment by rynowak** [comment]
OK, just ping me I guess when you're ready 😁  - a sample for health check publish should be **really** simple, because there's basically nothing to show in the sample.
- The runtime calls you
- You do a thing

**Comment by ThomasArdal** [comment]
I believe the sample using Microsoft.Extensions.Logging is fine as a simple example. It could log either `Error` or `Information` depending on if the checks succeed or not.

**Comment by guardrex** [comment]
> It could log either Error or Information depending on if the checks succeed or not.

I like that idea. Fortunately, what's there now works and is already rolled into the sample. The `Entries` and `Exception` just no-op. I had such a great weekend getting things done, I can take a stab 🔪 at fixing it up right now.
