### ISSUE TITLE
services.AddAuthentication().AddMicrosoftAccount is obsolete

### ISSUE THREAD

**Issue by sbsw** [aspnet/AspNetCore.Docs#14455]
@Rick-Anderson  edit: See [UPDATING MICROSOFT ACCOUNT LOGINS IN ASP.NET CORE WITH OPENID CONNECT AND AZURE ACTIVE DIRECTORY](https://damienbod.com/2019/05/17/updating-microsoft-account-logins-in-asp-net-core-with-openid-connect-and-azure-active-directory/) by @damienbod 

I am just finishing up an incident with Microsoft Tech support regarding the correct way to add Azure AD as an "external login provider". The method described in this document is obsolete:

    services.AddAuthentication()
        .AddMicrosoftAccount` is obsolete.

Other Microsoft documentation describes using

    services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
        .AddAzureAD(options => Configuration.Bind("AzureAd", options));

This logs in with Azure AD, but the login happens automatically (due to the `AzureADDefaults.AuthenticationScheme` argument). Removing that argument, so that Azure AD might function alongside other login providers, does not work.

According to Microsoft Tech Support (who consulted with the developers), in order for Azure AD to function alongside local accounts and other providers such as Facebook, you must call

    services.AddAuthentication()
        .AddOpenIdConnect(options => Configuration.Bind("AzureAd", options))

(where "AzureAd" identifies a set of configuration values, e.g. in appsettings.json) such as:

	"AzureAd": {
		"Instance": "https://login.microsoftonline.com/",
		"Authority": "https://login.microsoftonline.com/{tenant ID}/v2.0/",
		"TenantId": "{tenant ID}",
		"ClientId": "{client ID",
		"CallbackPath": "/signin-oidc"
	}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@sbsw `AddMicrosoftAccount` is used to [Configure Microsoft Account Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.2#configure-microsoft-account-authentication), not Azure AD.

cc @CamSoper @scottaddie

**Comment by lukepuplett** [comment]
Excuse me if I'm way off chipping into this conversation here.

Perhaps another MS team that confusing everything by bringing Microsoft accounts and OpenID into some kind of Microsoft "identity platform" and bringing the AD brand into the fold. I complained recently about all this.

https://github.com/MicrosoftDocs/azure-docs/issues/43056#issuecomment-555506355

**Comment by damienbod** [comment]
here's the ASP.NET Core issue which covers this as well

https://github.com/aspnet/AspNetCore/issues/10037

**Comment by higorbandeira** [comment]
Eu consigo utilizar isso para me conectar a um AD do Windows Server ??

**Comment by higorbandeira** [comment]
Can I use this... to connect in Windows AD ??

**Comment by carolinemilam** [comment]
OMG - I have been trying to get .Net Core 3.1 with Individual Accounts to work with single tenant AD authorization for over a week.

The 2 missing links:  
1.  Confirmation to use OpenIDConnect vs Microsoft Accounts
2.  Clear AzureAD json options (including specification to put the tenant id both as an option by itself AND in the Authority url):
"AzureAd": {
	"Instance": "https://login.microsoftonline.com/",
	"Authority": "https://login.microsoftonline.com/{tenant ID}/v2.0/",
	"TenantId": "{tenant ID}",
	"ClientId": "{client ID",
	"CallbackPath": "/signin-oidc"
}

CAUTION TO THOSE STARTING OUT:  The microsoft doc's and tutorials reference example source in Core 2.x which has completely different syntax and won't work out-of-the-box with individual accounts if you require a single tenant AD authentication.
