### ISSUE TITLE
RCL 3.0 walkthrough

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14463]
A 3.0 RCL experience wasn't added on https://github.com/aspnet/AspNetCore.Docs/pull/14461.

Requires ...

* A complete run-thru for 3.0 (e.g., VS deltas).
* 3.0 samples (project + RCL).
* I (🐲) couldn't run VS Preview at the time of that update.
* Possibly add a tab for VS4Mac? :apple:

Note: Check/update the RCL creation VS tab in the topic for the exact VS UI checkbox for 'page and view' support. There's a remark there, which was one of the main points of #14461, to surface it. The remark just needs to be placed in the step-by-step VS instructions with UI callouts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Create reusable UI using the RCL project #16639
