### ISSUE TITLE
CORS doesn't work.

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14467]
My ASP.Net Core 2.2 is deployed on kubernetes behind load balancer with AWS ALB ingress controller. CORS doesn't work. I have the following code in Startup.cs:
```
services.Configure&lt;ForwardedHeadersOptions&gt;(options =&gt; options.ForwardedHeaders = ForwardedHeaders.All);
app.UseForwardedHeaders();
```
Any advice and insight is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/AspNetCore.Docs/issues/14276 ... please don't open more than one issue for the same scenario.
