### ISSUE TITLE
Migration Failure

### ISSUE THREAD

**Issue by JohnnyB77** [aspnet/AspNetCore.Docs#14460]
Mr. Anderson,
When I use Add-Migration Initial and Update-Database on the PMC I get the following error message.

The specified deps.json [C:\Users\John\Documents\My Web Sites\RazorMovieApp_Tutorial\RazorPagesMovie\RazorPagesMovie.deps.json] does not exist

It appears VS 2019 is looking for a file somewhere where it should have been generated.  I also get the same issue in my attempts to follow the MVC version of the tutorial.  I am running VS Community 2019 Version 16.2.5.  I would love to move forward and keep learning; any assistance is much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#pmc)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use the Visual Studio feedback menu item to leave feedback.  Help >  Send Feedback
