### ISSUE TITLE
Problem() convenience method not exist?

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [aspnet/AspNetCore.Docs#14475]
The examples refer to a convenience method `Problem()`, but that does not appear to exist in `ControllerBase` or `Controller`.  Either need docs updated to reflect where it is, or to use another approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by guardrex** [comment]
@rellis-of-rhindleton Are u using the preview 3.0 framework? It's a 3.0 scenario ...

https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ControllerBase.cs#L1858

**Comment by guardrex** [comment]
We do need to do something about this. The topic is versioned for >=2.1; but since that's a 3.0 thing, it's not clear what to do. Guessing that this one is best for Scott.

**Comment by rellis-of-rhindleton** [comment]
I'm on 2.2.  Wondered if it was 3.0.  Didn't know how to tell though.

**Comment by rellis-of-rhindleton** [comment]
If it saves any time this is a simplified version of what I have in place now. But I imagine someone there has something better.

```csharp
[Route("error")]
public ActionResult Error([FromServices] IHostingEnvironment webHostEnvironment)
{
	var feature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
	var ex = feature?.Error;
	var path = feature?.Path;

	var isDev = webHostEnvironment.IsDevelopment();

	var problemDetails = new ProblemDetails
	{
		Status = 500,
		Instance = path,
		Title = isDev ? $"{ex.GetType().Name}: {ex.Message}" : "An error occurred.",
		Detail = isDev ? ex.StackTrace : null
	};

	return StatusCode(problemDetails.Status.Value, problemDetails);
}
```

Overall the documentation is great, so thanks for that.

**Comment by scottaddie** [comment]
@pranavkm Please advise how to handle in 2.2.

**Comment by pranavkm** [comment]
@rellis-of-rhindleton 's suggestion looks great. We could have it construct a `ProblemDetails` in < 3.0 case.
