### ISSUE TITLE
error: Unable to resolve 'Swashbuckle.AspNetCore (>= 5.0.0-rc2)' for '.NETCoreApp,Version=v2.2'.

### ISSUE THREAD

**Issue by exedor** [aspnet/AspNetCore.Docs#14478]
After using the mentioned command to create the TodoApi project, attempting to install swashbuckle just produces this error:

error: Unable to resolve 'Swashbuckle.AspNetCore (&gt;= 5.0.0-rc2)' for '.NETCoreApp,Version=v2.2'.
error: Package 'Swashbuckle.AspNetCore' is incompatible with 'all' frameworks in project 'TodoApi.csproj'.

EDIT:
OK, found another article with similar problem. the only way I could make this work was to add 

`-s https://api.nuget.org/v3/index.json`

to the end of your dotnet command for adding the package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by exedor** [comment]
OK, found another article with similar problem. the only way I could make this work was to add "-s https://api.nuget.org/v3/index.json" to the end of your dotnet command for adding the package

**Comment by Rick-Anderson** [comment]
Moved to #16195

**Comment by dco1993** [comment]
Thank you
