### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by kdawg1406** [aspnet/AspNetCore.Docs#14497]
This page needs to be updated for .NET Core 3, RTM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Already done. Refresh the page from the server every so often. There is a slight delay between our moving the content to `live` and it building and actually hitting the web servers.

**Comment by guardrex** [comment]
We shot the updates up ~45 minutes ago, so you should see the package updates fairly soon.
