### ISSUE TITLE
dotnet publish (3.0)

### ISSUE THREAD

**Issue by zygimantas** [aspnet/AspNetCore.Docs#14494]
[Enter feedback here]

.NET 3.0 breaking change - I had to change after upgrade from 2.2 to 3.0:

`dotnet publish --configuration=Release --no-restore --output=../../dist src/Website`

to

`dotnet publish --configuration=Release --no-restore --output=dist src/Website`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  who can review `dotnet publish --configuration=Release --no-restore --output=dist src/Website`

**Comment by zygimantas** [comment]
Solution structure is:

```console
/src/Website/Website.csproj
App.sln
```

**Comment by pranavkm** [comment]
This issue was moved to aspnet/AspNetCore#14262
