### ISSUE TITLE
Create 3.0 version of App parts

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14509]
*  Look at sample code. Create new samples with 3.0 templates using same namespace.
*  Copy over supporting code from previous version and test
* Create whole-topic versions - that is

```
::: moniker range=">= aspnetcore-3.0"
Copy paste entire topic here
::: moniker-end
::: moniker range="< aspnetcore-3.0"
Current topic here
::: moniker-end
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2&branch=pr-en-us-14507)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@Rick-Anderson thanks!  What priority should I label this?

**Comment by Legends** [comment]
I get an error when trying to compile sample 2!
After failed compilation I get an error:

Error		XML document must contain a root level element.	Miscellaneous Files	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	166
