### ISSUE TITLE
The Features sample shows Tag Helpers twice instead of those and View Components

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#14506]
In the features sample, the output from the controller shows Tag Helpers twice. The View enumerates `Model.TagHelpers` twice instead of also enumerating `Model.ViewComponents`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I'm working on a PR for this, but once the issue is addressed, the output for the View Components section of the view is empty. There are no VCs in the project or any of its references.

Should I add a dummy View Component to the project or should the example output in the docs page just call out that there aren't any View Components in the sample?

**Comment by Rick-Anderson** [comment]
Add a VC.
