### ISSUE TITLE
Update when available: We hope to have ASP.NET Core 3.0 available on Azure App Service soon.

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14515]
See the [ASP.NET Core on App Service Dashboard](https://aspnetcoreon.azurewebsites.net/) for the version of ASP.NET Core available on Azure App service.

@glennc  let me know when **We hope to have ASP.NET Core 3.0 available on Azure App Service soon.**  is available  so I can update this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-3.0&tabs=visual-studio#deploy-aspnet-core-30-to-azure-app-service)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Houuse** [comment]
Hi,
any update ?

**Comment by humanitycompany** [comment]
yes please - where is it? So this confirms that app will not fire as expected - done that - and has no tweak until sorted in backend? this is terrible as usual if true...

**Comment by guardrex** [comment]
@humanitycompany They're working on it. You can keep an eye on this dashboard that I was just introduced to today to know when it has been rolled out. https://aspnetcoreon.azurewebsites.net/

**Comment by humanitycompany** [comment]
If that helps anyone, great. What are we talking about here? Weeks?

**Comment by guardrex** [comment]
No ... not weeks. They're working on it like **_right now_**, and they know that many devs are waiting to get their hands on it. 🏃

**Comment by humanitycompany** [comment]
Still, after a few hours sleep. I can't belive this was not ready for use.....

**Comment by guardrex** [comment]
All we know is "soon" (which I don't interpret to be weeks) ...

https://twitter.com/AzureSupport/status/1178011240129540097

It's best for you to take it up further with Azure Support. We only handle ASP.NET Core docs here.

**Comment by Houuse** [comment]
well I've just went with SCD hope that don't have any implicit downsides other than package size, take your time ,

**Comment by andrewduffy77** [comment]
I can see ASP.NET Core 3.0 (x86) Runtime available as an extension in Azure App Service, are we saying that is not working?

**Comment by erik-forsmyr-stratsys** [comment]
To use the extension you need to deploy your app service as Self Contained, otherwise it will fail.

**Comment by blogcraft** [comment]
I did a Zip Deploy and the 3.0 extension worked perfectly, i just had to restart the app service once, no need of a self contained.

**Comment by blogcraft** [comment]
My app is Framework-dependent executable (FDE) and the 3.0 extension worked perfectly, no need of Self Contained.

**Comment by guardrex** [comment]
The rollout has begun :tada: ... keep an :eye: on this for your datacenter(s) ...

https://aspnetcoreon.azurewebsites.net/

**Comment by ShinraCorpMixer** [comment]
Hmm SDK is still missing for Canada East and Central. Oh well no rush :)

**Comment by ideoclickVanessa** [comment]
I'm confused.  Does the blue face on the map mean that I should be able to run a .NET Core 3 Rest API or not?
![image](https://user-images.githubusercontent.com/44000426/66783839-a2c30500-ee8d-11e9-9fdd-fc7f65b5a3f5.png)
Seems to imply that I can run it, I just can't build it.  However, I'm getting a silent 500 error whenever I attempt to communicate with the deployed site.

**Comment by farooq41** [comment]
Same here, Does not build even after adding core 3.0 extensions. Do we need to wait for it to Go Green from Blue?

**Comment by allanwei** [comment]
same questions please answer

**Comment by MisinformedDNA** [comment]
Ping.

**Comment by Rick-Anderson** [comment]
@MisinformedDNA  The Azure team controls that. Pinging us doesn't help, it just adds extra work for us.  See the [ASP.NET Core on App Service Dashboard](https://aspnetcoreon.azurewebsites.net/) for the version of ASP.NET Core available on Azure App service.

**Comment by MisinformedDNA** [comment]
The dashboard currently says that it should be available to run in all data centers. Multiple people have stated that the instructions do not actually work. I have tried following the docs and I haven't been able to get a working site.

**Comment by guardrex** [comment]
Azure Apps has the runtime and shared framework. I just worked with a 3.0 Azure Key Vault app a few days ago ... no probs ... other the dog'gone certificates for my AKV app flaking out! :smile:. Anyway ... the dashboard is probably accurate.

We aren't actually getting many pings about Azure and 3.0 at this point.

> I have tried following the docs and I haven't been able to get a working site.

Follow the advice at ... 

https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#troubleshoot-on-azure-app-service

btw @Rick-Anderson ... that preview notice isn't updated for the runtime/shared framework rollout.

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/azure-apps-preview-notice.md
