### ISSUE TITLE
Grpc .net client issue with .NET Core and .NET standard (2.0)

### ISSUE THREAD

**Issue by shyamutty** [aspnet/AspNetCore.Docs#14524]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Grpc.Net.Client 0.2.23-pre1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Grpc.Net.Client 0.2.23-pre1 supports: netstandard2.1 (.NETStandard,Version=v2.1)	GrpcGreeterClient

Grpc.Net.Client 2.23.2 dependency is .NETStandard 2.1

**Comment by shyamutty** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Grpc.Net.Client 2.23.2 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Grpc.Net.Client 2.23.2 supports: netstandard2.1 (.NETStandard,Version=v2.1)	GrpcGreeterClient	1

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
