### ISSUE TITLE
dotnet-aspnet-codegenerator won't be installed, unless specify version

### ISSUE THREAD

**Issue by hatzhang** [aspnet/AspNetCore.Docs#14527]
fixed with adding --version 2.0.0

i am ubuntu, and the following won't work.
`dotnet tool install --global dotnet-aspnet-codegenerator`

> error NU1202: Package dotnet-aspnet-codegenerator 3.0.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any. Package dotnet-aspnet-codegenerator 3.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
The tool package could not be restored.
Tool 'dotnet-aspnet-codegenerator' failed to install. This failure may have been caused by:
>* You are attempting to install a preview release and did not use the --version option to specify the version.
>* A package by this name was found, but it was not a .NET Core tool.
>* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
>* You mistyped the name of the tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hatzhang** [comment]
need specify version

**Comment by Rick-Anderson** [comment]
Not with the GA/RTM version.
