### ISSUE TITLE
Hosting Bundle Installer/ANCM deployment in web farm environments

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14520]
We don't address how to deploy/maintain the hosting bundle/ANCM in web farm environments. The [dotnet-install PS script](https://docs.microsoft.com/dotnet/core/tools/dotnet-install-script) can't help OOB.

* @shirhatti @Tratcher, what do you currently advise?
* Should we provide guidance (or link to something) on the subject in this topic?

cc: @mtirion (asked about this offline)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be127bb-755c-98ab-d7fb-b3f50687857f
* Version Independent ID: 9562d8c0-563d-21ca-e802-80f9b99689ff
* Content: [Host ASP.NET Core in a web farm](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/web-farm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/web-farm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
This would be guidance for a hosting platform? That's a pretty specialized environment, I don't know that there is broad guidance to give. We can describe the different ANCM versions and their compatibility mechanics, but actual deployment would use hoster specific patterns.

Most of our relevant experience is with Azure Web Sites and they deploy ANCM as part of their base image updates. The runtimes are deployed separately.

Is there a more specific question?

**Comment by mtirion** [comment]
We still see a lot of customers not using WebSites but use VM's. They need an automated way to install the hosting bundle. You can do it now, but need to use a direct link to a specific version of the package. The dotnet-install script nicely hides this for the SDK and runtime install, why not for the hosting install? And the other way around, if it isn't important for hosting, why is it important for the runtime and SDK?

**Comment by Tratcher** [comment]
@shirhatti can you redirect for installers?

**Comment by guardrex** [comment]
@shirhatti Is there anything we can say here? *Custom Script Extension* perhaps? ...

https://docs.microsoft.com/azure/virtual-machines/windows/tutorial-automate-vm-deployment

**Comment by shirhatti** [comment]
@guardrex I used to maintain this repo https://github.com/shirhatti/ANCM-ARMTemplate but it's out of date now. It has an ARM template that uses a custom script extension to install ANCM

Perhaps something worth re-using in that?

**Comment by guardrex** [comment]
Wouldn't the template be appropriate when creating *new VM's* ... not so much for distributing a new hosting bundle installer and running it on existing VM's?

Does your script *install-ancm.ps1* mirror what the hosting bundle installer does?

I only briefly looked at their topics, but it seemed like a *Custom Script Extension* run immediately on a resource group of live VM's would immediately download/run the hosting bundle installer. It also seemed like (because they mention ARM templates in passing) that it can be configured to work with ARM templates.
