### ISSUE TITLE
Typo in project sdk xml

### ISSUE THREAD

**Issue by rpbrongers** [aspnet/AspNetCore.Docs#14533]
In my experience, SDK needs to be Sdk in the xml references, otherwise the project will fail to load (VS2019 16.3.0) e.g. &lt;Project SDK="Microsoft.NET.Sdk.Web"&gt; needs to be &lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That does match the templates ... I'll update it. Thanks @rpbrongers!
