### ISSUE TITLE
Show fix for Visual Studio Code

### ISSUE THREAD

**Issue by Gimanua** [aspnet/AspNetCore.Docs#14539]
The instructions for Visual Studio Code seem to be missing some step (at least for me). When I use the command "code -r RazorPagesMovie", it loads for a while and the OmniSharp flame icon turns white instead of green. Then it says it had trouble loading, and if you click show output you can see this:

[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\T4User\Documents\Programmering\RazorPagesMovie\RazorPagesMovie.csproj'.
c:\Users\T4User\Documents\Programmering\RazorPagesMovie\RazorPagesMovie.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\T4User\Documents\Programmering\RazorPagesMovie\RazorPagesMovie.csproj

This seems to make it impossible to actually run the app later, when I try to start with Ctrl + F5 Visual Studio Code shows an error window with the text: Could not find the task 'build'.

I've installed all the prerequisites from the exact links shown in the "Prerequisites" section.
I've tried searching for a solution but haven't found one that actually works.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/sv-se/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you open an issue with the VSC folks? Thanks

**Comment by Gimanua** [comment]
Nevermind, this seems to have been fixed now.
