### ISSUE TITLE
Typo in Migrate Startup.Configure (Routing startup code)

### ISSUE THREAD

**Issue by szilajka** [aspnet/AspNetCore.Docs#14532]
In [General advice list](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-startupconfigure):

Original text:
> Replace IHostingEnvironment with IWebHostEnvironment and add a using statement for the Microsoft.Extensions.Hosting namespace.

Shouldn't it be (replaced `IWebHostEnvironment` with `IHostEnvironment`):
>  Replace IHostingEnvironment with [IHostEnvironment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment?view=aspnetcore-3.0) and add a using statement for the Microsoft.Extensions.Hosting namespace.

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by zygimantas** [comment]
No, Visual Studio suggests IWebHostEnvironment

**Comment by zygimantas** [comment]
If you don't need specific IWebHostEnvironment features, IHostEnvironment is fine, but if you replace IHostingEnvironment with IHostEnvironment, you will not be able to get WebRootPath and WebRootFileProvider.

**Comment by szilajka** [comment]
Thanks for the info. 👍
