### ISSUE TITLE
Shared Framework Change Impact not adequately documented

### ISSUE THREAD

**Issue by jonstelly** [aspnet/AspNetCore.Docs#14538]
## Problem

If I understand what's going on correctly, I think the ASP.NET Core Shared Framework changes for 3.0 are going to cause quite a bit of confusion and needs a big bold **warning** in several different places.

## Scenario

`[Edit]`  I'm using **framework dependent builds and that's the only place where this is an issue**. 
I have a classlib project that references `Microsoft.AspNetCore.Authentication.Google`.  I then have a non-aspnet-core console app (worker service) that references my library and is run in docker.  When targeting `netcoreapp2.2` I am able to run this application in docker using the `mcr.microsoft.com/dotnet/core/runtime` docker image as my base.  If I target `netcoreapp3.0` (and update dependencies to the Microsoft.AspNetCore.* 3.0.0 version) then I get the following error when starting the container:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

If I switch my base image from 
`mcr.microsoft.com/dotnet/core/runtime:3.0-alpine` to 
`mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine`  `    ` then the worker app starts without error.

From a quick sample app, it looks like a project targeting `netcoreapp2.2` with a:

```
<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="2.2.0" />
```

produces a runtimeconfig.json like:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.2",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.2.0"
    }
  }
}
```

but targeting netcoreapp3.0 with a:

```
<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="3.0.0" />
```

produces a runtimeconfig.json like:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.0.0"
    }
  }
}
```

## Suggestions/Thoughts
It's not intuitive or adequately called out in the documentation that my dotnet core project that does not target Microsoft.Net.Sdk.Web via `<Project Sdk="Microsoft.NET.Sdk.Web">` will require the aspnet docker image or shared framework just because I pulled in a nuget reference for something from AspNetCore.

It's further confusing or non-obvious because looking at the [nuget.org page for Microsoft.AspNetCore.Authentication.Google](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Google/) shows that version 3.0 has no dependencies (where [version 2.2.2 shows its dependencies](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Google/2.2.2)).  This shared framework dependency needs to get listed on the nuget page.

Also, I'm assuming that only the libraries on the obsolete package references list [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references) will add this shared framework dependency so from an outsider looking in, I can't easily reason about this behavior to figure out "If I have a nuget reference to any project in the `Microsoft.AspNetCore` namespace, I'm pulling in a dependency on the shared framework".

Like I said above, I think this needs to be called out in the documentation in several places: 2.2 to 3.0 migration, dotnet core docker hub, nuget package page, as well as general (not-upgrade related) aspnet core 3.0 documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by MaximRouiller** [comment]
Thank you @jonstelly for bringing that to our attention! @Rick-Anderson Is the content editor associated with this content. We're going to give him some times to go through all his GitHub notifications. 😄

**Comment by jonstelly** [comment]
Thanks, I'm sure everyone's busy with the release.  I did read through the [deep-dive article](https://natemcmaster.com/blog/2018/08/29/netcore-primitives-2/) linked from the 2.2-3.0 migration page and it covers this.  The deep dive is a really good read and does explain the heart of the issue along with the symptom but I'm guessing I won't be the only one to skip a link titled "deep dive" and run into this problem.

But after reading that deep dive I realized I didn't include some important information, mainly that I'm using framework dependent builds and that's the only place where this is an issue.  I'd guess most people are using framework dependent builds for Docker since it produces a much smaller upper layer in the docker image, speeding up deployments of app upgrades, etc...

**Comment by Rick-Anderson** [comment]
@jonstelly  can you suggest an edit?

If you're using **framework dependent builds**  .. ?

**Comment by jonstelly** [comment]
I don't know if I have anything easy to suggest.  I'm just trying to collect my thoughts below, apologize if this seems like rambling, it just doesn't feel like an easy change.

1) This is only really a breaking or unexpected change if you're building a non-asp.net-core application that depends on a library/nuget-package that depends on the ASP.NET Core shared framework.  Best case, I know to expect or look for this but the only way to see if a nuget package depends on a shared framework is to add the nuget dependency, build, then check the runtimeconfig.json.  Worst case, I don't know to look for this and get the error mentioned above and head to google/stack-overflow.

2) I think nuget should call out shared framework dependencies, but I have a feeling that's going to take some time/effort.

3) The arrangement of all of this makes sense, I wouldn't want to see the aspnet and runtime docker images merged.  The docker images track the [runtime installers](https://dotnet.microsoft.com/download/dotnet-core/3.0), it's great to see the smaller framework dependent builds.

4) Since this information needs to be in several places (IMO), maybe a permanent page for `Shared Frameworks` in the .net core documentation, below [Target Frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) in the index?  That page could include some description of this issue and a link to the deep dive.  Then the link to the deep dive could be replaced in the asp.net core 2.2 -> 3.0 migration document to link to the shared frameworks page.  And in other places the link could be added and called out with as much/little emphasis as needed.  As an aside, I'm really curious about building my own shared frameworks, seems like a mechanism that would work really well with docker images in an enterprise... in the future maybe some documentation explaining the process of creating custom shared frameworks could be added.

5) I don't know what to do about the docker hub pages.  That seems like a key place it needs to be called out but those hub pages are pretty streamlined/spartan.  Looking at the [base dotnet core hub page](https://hub.docker.com/_/microsoft-dotnet-core/), there's a link titled `Building Docker Images for .NET Core Applications` that links to https://docs.microsoft.com/dotnet/core/docker/building-net-docker-images which redirects to https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.0 which is titled `Docker images for ASP.NET Core`.  Note that the link text and target document title disagree a bit between .NET Core vs ASP.NET Core, I think that link would be better if it pointed to the more general https://docs.microsoft.com/en-us/dotnet/core/docker/introduction, but I'm sure there are many more asp.net core docker images out there than plain dotnet core runtime images.  But if that link did go to the more generic `Introduction to .NET and Docker` that page seems like a perfect place to mention shared frameworks and link to the aforementioned Shared Frameworks page

**Comment by Rick-Anderson** [comment]
@jonstelly  thanks, that's helpful.

**Comment by pranavkm** [comment]
@jonstelly as one of the follow ups, I've asked for the framework reference to appear as a prerequisite in the gallery: https://github.com/NuGet/NuGetGallery/issues/7578. More documentation would certainly help here.
