### ISSUE TITLE
Scaffolding failed for  Failed to get Project Context

### ISSUE THREAD

**Issue by hatzhang** [aspnet/AspNetCore.Docs#14530]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Looks like you're mixing 2.2 and 3.0

**Comment by hatzhang** [comment]
> Looks like you're mixing 2.2 and 3.0

But how to check and fix this?

**Comment by Rick-Anderson** [comment]
Start from the beginning and follow https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio

**Comment by hatzhang** [comment]
I was following that tutorial from beginning, works well until Scaffolding. I tried some Mono a few days ago, is there any possibility these two has any conflicts?  i am reading nuget [tutorial](https://docs.microsoft.com/en-us/nuget/api/nuget-protocols) right now.

**Comment by Rick-Anderson** [comment]
somehow you got 2.2 and 3.0 mixed.
I'd install 3.0 and start from the beginning.

**Comment by hatzhang** [comment]
Ok, i will try it that way.

**Comment by hatzhang** [comment]
i worked.
it compiled and runnable. except my Code shows lots of Problems: 
```
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. (CS0012) [RazorPagesMovie]
```
dotnet build showed no warning. must be something wrong with my Code setting?
