### ISSUE TITLE
How to download sample code

### ISSUE THREAD

**Issue by cveld** [aspnet/AspNetCore.Docs#14540]
What is your guidance on downloading the sample code for this tutorial? The only way I see so far is to clone to the complete AspNetCore repo which is 700 MB in total.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're getting them up in a special place now so that they can be downloaded individually.

https://docs.microsoft.com/en-us/samples/browse/

This one hasn't been placed over there yet, so *yes* ... get the zip of the repo and dig it out is the way to go right now.
