### ISSUE TITLE
Configure environment settings

### ISSUE THREAD

**Issue by Vasilut** [aspnet/AspNetCore.Docs#14554]
Hi. I have a .net core api 2.2 app where I configured my nlog (**ConfigureNLog** method) based on my configuration:

                    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.ClearProviders();
                    var logConfig = string.IsNullOrEmpty(Environment.GetEnvironmentVariable("env"))
                        ? "NLog.Development.config"
                        : "NLog.config";
                    **hostingContext.HostingEnvironment.ConfigureNLog(logConfig);**
                })
                .UseNLog()
                .UseStartup<Startup>();
    }
Regarding that some things changed in 3.0, how I can achieve that configuration ? (I searched into the docs but I cannot find anything relevant).
I tried using **logging.ConfigureNLog(logConfig);** (but I got an obsolete warning):

                 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureLogging((hostingContext, logging) =>
                    {
                        logging.ClearProviders();
                        var logConfig = string.IsNullOrEmpty(Environment.GetEnvironmentVariable("env"))
                            ? "NLog.Development.config"
                            : "NLog.config";
                        logging.ConfigureNLog(logConfig);
                        //NLogBuilder.ConfigureNLog(logConfig); -other choice maybe ? 
                    })
                    .UseNLog()
                    .UseStartup<Startup>();
                });

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Have you tried moving to `CreateHostBuilder`?
cc @guardrex

**Comment by Rick-Anderson** [comment]
This is a NLog issue. See https://github.com/NLog/NLog.Web/issues/350

**Comment by snakefoot** [comment]
@Vasilut Alternative you could setup logging before building host:

```c#
var logConfig = string.IsNullOrEmpty(Environment.GetEnvironmentVariable("env"))
                        ? "NLog.Development.config"
                        : "NLog.config";
var logger = NLog.Web.NLogBuilder.ConfigureNLog(logConfig).GetCurrentClassLogger();

CreateWebHostBuilder(args).Build().Run(); 
```

See also [Program.cs example from NLog Wiki](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-2#4-update-programcs)
