### ISSUE TITLE
Easier to understand sorting

### ISSUE THREAD

**Issue by rmissier** [aspnet/AspNetCore.Docs#14558]
This is not really an issue, but IMO it is easier to understand.

We start with sortOrder name_asc, that sets ups the links as on the page as
NameSort = name_desc
DateSort = date_asc

When the data is sorted on LastName, it will sort the data on name_desc and set up the link for sorting on name_asc.
When the data is sorted on EnrollmentDate, it will sort the data on date_asc and set up the link for sorting on date_desc.

```
public async Task OnGetAsync(string sortOrder = "name_asc")
        {
            NameSort = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            DateSort = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            IQueryable<Student> students = _context.Students.Select(s => s);
            students = sortOrder switch
            {
                "date_asc" => students.OrderBy(s => s.EnrollmentDate),
                "date_desc" => students.OrderByDescending(s => s.EnrollmentDate),
                "name_desc" => students.OrderByDescending(s => s.LastName),
                _ => students.OrderBy(s => s.LastName)
            };

            Students = await students.AsNoTracking().ToListAsync();
        }
}
```

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
That code is pretty complicated and we'd welcome a simpler approach.
