### ISSUE TITLE
Please provide guidance on how to use Azure AD together with other social IdPs like facebook, google, etc..

### ISSUE THREAD

**Issue by bachoang** [aspnet/AspNetCore.Docs#14555]
It appears that You can either use social IdPs or Azure AD (.AddAzureAD) by itself.  Customer has the requirement to support multiple social IdPs including Azure AD.  We have no guidance or documentation on how to use AzureAD together with other social IdPs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@CamSoper  can you comment?

**Comment by CamSoper** [comment]
I believe the recommended way to accomplish this is to use Azure AD B2C, which is capable of supporting AAD and Social IdP logins. [See this doc](https://docs.microsoft.com/azure/active-directory-b2c/tutorial-add-identity-providers).

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
