### ISSUE TITLE
No information about authentication provided by integration inclusion of IdentityServer and additional wording feedback

### ISSUE THREAD

**Issue by eriawan** [aspnet/AspNetCore.Docs#14567]
This what's new in ASP.NET Core 3.0 page should include the authentication integration inclusion of Identity Server.
This official ASP.NET blogpost has mention this IdentityServer integration: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0/

Also the section on Request counters should be titled to "New EventCounters on request", because it is not just an actual request counter as is. The blog announcement seems better than this page, because it says "New EventCounters created for requests per second, total requests, current requests, and failed requests."

![image](https://user-images.githubusercontent.com/8773147/65567743-8106ea00-df81-11e9-9be6-c19c90a71a14.png)

Please update this what's new in ASP.NET Core 3.0 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3ff3cd-e7c3-f5f8-8993-067ca43f4ccc
* Version Independent ID: 8b8283b5-10f0-139d-b069-6ffab0ea4ca1
* Content: [What's new in ASP.NET Core 3.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/release-notes/aspnetcore-3.0.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-3.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@eriawan  thanks for this info. I'll get it added tomorrow.

**Comment by Rick-Anderson** [comment]
@eriawan thanks for bringing this to our attention. Very good suggestions.

**Comment by eriawan** [comment]
Thanks! 
LGTM, closing this now 👍
