### ISSUE TITLE
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0

### ISSUE THREAD

**Issue by jeffreyln101** [aspnet/AspNetCore.Docs#14571]
It takes around 48 hours to figure out that IdentityHostingStartup.cs is your problem following this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jeffreyln101** [comment]
You think you need to scaffold the contact class then scaffold Identity. You can't add this to startup .cs 
services.AddDefaultIdentity<IdentityUser>(
        options => options.SignIn.RequireConfirmedAccount = true)
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();
after you scaffold Identity. be more clear.

**Comment by Rick-Anderson** [comment]
Where does it say scaffold identity? Did you compare your code to the download?

**Comment by jeffreyln101** [comment]
It does not, but when your talking about Identity and Scaffolding after the other tutorials you kind of think right off the bat I need to scaffold the contact class and then Identity. The tutorial helped me figure out allot of things, I am not saying it is bad. 

I think maybe adding something under this section 'Add Role services to Identity'  like 'If you did scaffold Identity even though I didn't tell you too look here IdentityHostingStartup.cs' Anyway have a great day!
