### ISSUE TITLE
Update to 3.0

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#14578]
The sample code here is for 2.2, but should be updated to 3.0. I think this just involves replacing `AddMvc` and expanding what was just `UseAuthentication`. We can grab the changes from the *security/authentication/cookie* topic for the `UseAuthentication` stuff and perhaps just drop the call to `AddMvc` as it's secondary to the explanation, and again, that's how the other topic handles it..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9d7ad5-47d6-80bf-88fe-fac3a74151a3
* Version Independent ID: e64816f4-3391-5aab-31c2-ab4f915bc7f6
* Content: [Facebook, Google, and external provider authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/social/social-without-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/social-without-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I can make a PR for this within the next day or two. Let me know if that's _not_ ok.

**Comment by Rick-Anderson** [comment]
When you update, use whole file versioning

```
::: moniker range=">= aspnetcore-3.0"

// 3.0 version

::: moniker-end
::: moniker range="< aspnetcore-3.0"

// Old content

::: moniker-end
```
