### ISSUE TITLE
EventSource logger should be updated with instructions using dotnet trace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore.Docs#14572]
There's a new global tool dotnet-trace that can be used to collect logs using the EventSource logging provider. We should have instructions on how to use this tool with the provider (including how to dial specific categories up or down).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Some notes for myself on the syntax as I've been splunking:

```
dotnet trace collect -p {pid} --providers Microsoft-Extensions-
Logging:4:2:FilterSpecs=Microsoft.AspNetCore.Hosting*:Information
```

The above turns on the EventSource logger for errors, but turning the **Microsoft.AspNetCore.Hosting** category on as **Information**.

**Comment by davidfowl** [comment]
cc @noahfalk @shirhatti

**Comment by Rick-Anderson** [comment]
@guardrex  or @scottaddie  can one take this?

**Comment by guardrex** [comment]
Yes, but in October. I'm 🏃 right now.
