### ISSUE TITLE
Locked Files - how to reference Microsoft.NET.Sdk.Web in the project file?

### ISSUE THREAD

**Issue by rangler2** [aspnet/AspNetCore.Docs#14579]
It says under Locked deployment files, that Publish will use app_offline.htm if you "Use Web Deploy and reference Microsoft.NET.Sdk.Web in the project file"
My csproj already has &lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt; at the top, is this sufficient? I tried adding &lt;PackageReference Include="Microsoft.NET.Sdk.Web" /&gt; but it says this nuget package doesn't exist. However it is not putting an app_offline.htm file in place and fails after 10/10 attempts to replace the locked dll file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.2#locked-deployment-files)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> at the top, is this sufficient

Yes

> adding \<PackageReference Include="Microsoft.NET.Sdk.Web" />

Right ... don't do that.

> it is not putting an app_offline.htm file in place

Open that for the product group. We only handle the docs here. Open it over at :point_right: https://github.com/aspnet/AspNetCore/issues. They'll either help you there or point you to the right spot. Note that the issue of locked files came up in several issues. I recommend before you open a new issue to search those engineering issues (both open **_and closed_**) and see if they've already addressed it. Try this search link (based on a "locked files" search phrase) and see ... https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aissue+locked+files+
