### ISSUE TITLE
dotnet dev-certs https cannot clean and/or install properly, macos

### ISSUE THREAD

**Issue by realdanielbyrne** [aspnet/AspNetCore.Docs#14581]
Launching the netcore debugger give me the following error:

```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run `dotnet dev-certs https`. To trust the certificate (Windows and macOS only) run `dotnet dev-certs https --trust`.
```
However, `dev-certs` seems confused as to the state of the HTTPs certificates on this machine.  `dev-certs` will not create a cert because it thinks one exists.  --Clean will not clean because it thinks it does not exist. IT will not trust because it thinks a cert exists.

```
> :~ daniel$ dotnet dev-certs https 
A valid HTTPS certificate is already present.

>:~ daniel$ dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. This operation might require elevated privileges. If that is the case, a prompt for credentials will be displayed.
HTTPS development certificates successfully removed from the machine.

>:~ daniel$ dotnet dev-certs https 
A valid HTTPS certificate is already present.

>:~ daniel$ dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <<certificate>>'
This command might prompt you for your password to install the certificate on the system keychain.
A valid HTTPS certificate is already present.
```
Im in quandary because I cannot debug nor can I fix the problem with the tools provided.  Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in an ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&branch=pr-en-us-14568&tabs=visual-studio#troubleshoot-certificate-problems)

If that doesn't work, try

```
dotnet tool uninstall --global dotnet-dev-certs
dotnet tool install --global dotnet-dev-certs
dotnet dev-certs https --trust
```

**Comment by Rick-Anderson** [comment]
Closing for lack of response.
