### ISSUE TITLE
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer'

### ISSUE THREAD

**Issue by rarrrrr** [aspnet/AspNetCore.Docs#14589]
Thanks for the guide. I got this error after amending the ConfigureServices method:
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer'
Got around it by installing the Microsoft.EntityFrameworkCore.SqlServer NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The previous page tells you to add that. If you didn't, you'd get the error on the previous tutorial. See #14604
