### ISSUE TITLE
RazorViewEngineOptions FileProviders .net core 3.0

### ISSUE THREAD

**Issue by zhou881117** [aspnet/AspNetCore.Docs#14586]
services.Configure<RazorViewEngineOptions>(options =>
            {
               options.FileProviders.Add(
                 new EmbeddedFileProvider(typeof(MySharedController).GetTypeInfo().Assembly));
            });

.net core 3.0  RazorViewEngineOptions changed.  without FileProviders to locate view

@Rick-Anderson 

tks!

**Comment by guardrex** [comment]
Moved to #14509 

@zhou881117 Using the feedback form at the bottom of the topic tags the issue with metadata and pings the author. No worries ... I moved it. Track it on the new issue.
