### ISSUE TITLE
Why still Blazor WebAssembly in preview

### ISSUE THREAD

**Issue by smjltd** [aspnet/AspNetCore.Docs#14582]
I have a project to ship in production!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @smjltd ... It's not something that we can address here on the docs repo. You can open a product feedback issue in engineering :point_right: https://github.com/aspnet/AspNetCore/issues ... but I know that that's their plan. I doubt that they have a strict ETA, but you can ask them. If they know, they'll tell u over there.
