### ISSUE TITLE
ControllerBase File doesn't specify the stream disposal

### ISSUE THREAD

**Issue by SnakyBeaky** [aspnet/AspNetCore.Docs#14585]
# Issue description

The `ControllerBase.File(Stream)` method and its many overloads don't state anywhere that the provided `Stream` will be disposed after the response is sent.

This can only be seen after decompiling the code and seeing the `using` statement in an underlying method (`WriteFile`...).

Questions about this exact issue in SO:
https://stackoverflow.com/questions/42238826/does-a-stream-get-disposed-when-returning-a-file-from-an-action
https://stackoverflow.com/questions/3084366/how-do-i-dispose-my-filestream-when-implementing-a-file-download-in-asp-net
https://stackoverflow.com/questions/26275764/does-filestreamresult-close-stream

# Software versions
- [x] ASP .NET Core 2.2 (others too)

**Comment by guardrex** [comment]
Probably a candidate for the API remarks, which would automatically cover it for the formal docs.

**Comment by davidfowl** [comment]
Yes the Stream is disposed. We should make sure it's in the API comments as well.
