### ISSUE TITLE
Please fix and integrate the content

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#14599]
Hi team, 
I'm moving this from here: https://github.com/aspnet/AspNetCore.Docs.it-it/issues/38
I'm checking the fist item with the localization team, because it repros just in localized versions, but it's probably also a source issue with a format error that bugs the translation tool.

@unsafecode commented 8 hours ago
I'm currently migrating a large ASP.NET 2.2 app to 3.0, and I was referring to this page for guidance. However, I found lots of important information missing:

-   The collapsible panel under "Remove obsolete package references" hides most of the relevant content. Additionally, the layout of deprecated packages is unreadabl.e
-   There must be a specific section on how to upgrade existing Class Libraries to leverage ASP.NET Core 3.0 (cross-targeting, #ifdef, etc...)
-    Please list all the API breaking changes for ASP.NET Core 3.0. For instance, AllowSynchronousIO is mentioned, but not the fact it breaks Microsoft.AspNetCore.ResponseCaching (just to mention one), and requires it to enable backward compatibility.
-   There must be another section about 3rd party libraries (eg. SwashBuckle.Swagger) that need to be migrated as well (at least add the link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The collapsible panel under "Remove obsolete package references" hides most of the relevant content. Additionally, the layout of deprecated packages is unreadabl.e

@unsafecode  In your version `it-it`, it's not hidden. You just need to click per the instructions.

**Comment by unsafecode** [comment]
@Rick-Anderson Looks like the panel was fixed yesterday, today works fine.

**Comment by unsafecode** [comment]
@Rick-Anderson wrt to System.Text.Json, I'd also point out that this serializer is not yet 100% equivalent to Newtonsoft.Json. For instance, https://github.com/dotnet/corefx/issues/36240

**Comment by Rick-Anderson** [comment]
@unsafecode  we don't say it's equivalent
