### ISSUE TITLE
Missing services.AddApiExplorer()

### ISSUE THREAD

**Issue by JakeWierzba** [aspnet/AspNetCore.Docs#14594]
The instructions are missing: services.AddApiExplorer()
services.AddMvcCore(options =&gt;
            {
                options.EnableEndpointRouting = false;
            })
            .AddApiExplorer()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Sti2nd** [comment]
If you use AddMvc instead of AddMvcCore it will be automatically registered according to the Swashbuckle docs https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckle-apiexplorer-and-routing

**Comment by Rick-Anderson** [comment]
Moved to #16195
