### ISSUE TITLE
Regarding Async code

### ISSUE THREAD

**Issue by DrGriff** [aspnet/AspNetCore.Docs#14597]
Is best practice to use .ConfigureAwait(false) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DrGriff ... We focus our coverage on ASP.NET Core. Try the C# Guide at ....

https://docs.microsoft.com/dotnet/csharp/

... and there are many blog posts out there to address your question.
