### ISSUE TITLE
Migrate AspNetCoreDiagnosticScenarios/AspNetCoreGuidance.md

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14605]
Move 
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md under **Test, debug, and troubleshoot** 
![image](https://user-images.githubusercontent.com/3605364/65630157-8b6cb800-df70-11e9-8161-df6877a110a3.png)

**Comment by Rick-Anderson** [comment]
@wadepickett  can you start on this?
cc @guardrex

**Comment by wadepickett** [comment]
Yes, thanks, just saw this.

**Comment by wadepickett** [comment]
@Rick-Anderson , just to make sure I am on the same page:
1. Only migrate the AspNetCoreGuidance.md file.  We are not migrating AspNetCoreDiagnosticScenarios.
2. Reformat to some sort of template or leave the design as is?

**Comment by Rick-Anderson** [comment]
For now:

* Copy https://raw.githubusercontent.com/davidfowl/AspNetCoreDiagnosticScenarios/master/AspNetCoreGuidance.md
* Create Web API project and move snippets to code.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks!   
1. Should I reformat to a template or leave it as is?
     a. If you want it reformated to a template, publish first as is so it is out quick, then reformat?

Thanks.

**Comment by Rick-Anderson** [comment]
Leave as is for now. Use
#if BAD
        // Bad code here
#else
        // Good code here
#endif

**Comment by wadepickett** [comment]
Got it, thanks!     Not sure what to name this.  "ASP.NET Core Guidance" is too generic.  I'll come up with something more specific.

**Comment by Rick-Anderson** [comment]
Append it to https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices

cc @guardrex @scottaddie

**Comment by Rick-Anderson** [comment]
@mjrousos you ok with adding  `@davidfowl`  https://raw.githubusercontent.com/davidfowl/AspNetCoreDiagnosticScenarios/master/AspNetCoreGuidance.md to your topic?

**Comment by mjrousos** [comment]
Absolutely! There's some overlap in the first couple with my more general guidance to avoid blocking calls, but that's probably ok. No harm in giving general guidance and then pointing out specific cases where it's likely to be an issue.
