### ISSUE TITLE
Clarify the scenario for the template install command

### ISSUE THREAD

**Issue by kdawg1406** [aspnet/AspNetCore.Docs#14600]
Can you please be more specific about the templates and EXACTLY what they are and for what scenarios you need them.   I've read on Twitter that these are client only templates.  Is that true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're cross-linked in each tooling tab (Step 3) ...

> For information on the two Blazor hosting models, Blazor Server and Blazor WebAssembly, see ASP.NET Core Blazor hosting models.

The hosting model topic goes into great detail.

**Comment by kdawg1406** [comment]
This text in the Getting Start Page where I posted this states, "Install the Blazor templates by running the following command in a command shell:"  This is not 100% clear or accurate.  Why not update this one line of text to make it clear to everyone.

**Comment by guardrex** [comment]
What's not accurate or unclear?

**Comment by kdawg1406** [comment]
That you don't need these preview templates except for client development.

**Comment by guardrex** [comment]
I see ur point now. I'm neck-deep in hosting startup code today. 😵:gun:

Yes, indeed. I agree. I'll add a note about that.

**Comment by guardrex** [comment]
I'll get it done by the end of the day. I need to dig myself out of this 🕳 **hosting startup** 🕳 work first. Thanks for calling it out.

**Comment by kdawg1406** [comment]
Maybe @danroth27 can shed some light as well.  

Thank you for your time and consideration.

**Comment by guardrex** [comment]
Not necessary ... he's OOF anyway. I'll have it done by the time he gets back.

**Comment by danroth27** [comment]
Yeah, it should say "Install the Blazor **WebAssembly** template by..."

**Comment by guardrex** [comment]
I was just about to fix it up.

I just got free ....... i.e. ...... **_SURVIVED_** my bout with *hosting startup assemblies* 🥊 .... 1 ... 2 ... 3 .... the ref waves him off! *GuardRex knocks out the challenger!* 🥊
