### ISSUE TITLE
HttpContext.SignInAsync null after migrate to .Net Core 3.0

### ISSUE THREAD

**Issue by kienit** [aspnet/AspNetCore.Docs#14619]
I used exactly the same as above guideline. It works perfectly on .Net core 2.2. However, after I migrate to 3.0 it stop working. Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  3.0 migration question on `HttpContext.SignInAsync` null after migrate to .Net Core 3.0

**Comment by IrakliGabadze** [comment]
Same Problem... 
HttpContext.SignInAsync null after migrate to .Net Core 3.0

**Comment by Rick-Anderson** [comment]
Does the sample app work?

**Comment by kienit** [comment]
Hi guys, I believe this issue related to Visual Studio 2019.
Since my application function normally when published. It creates null only on Development.

I will recreate more case and give final conclusion

**Comment by IrakliGabadze** [comment]
Any solution ??? Anybody ???

**Comment by IrakliGabadze** [comment]
Ok guys... If you have only this   services.AddHttpContextAccessor(); in startup.cs 
you can edditionaly try to add this services.AddScoped<HttpContextAccessor>(); It worked for me. let me know if it is usefull for you too...

**Comment by IrakliGabadze** [comment]
this services.AddScoped<HttpContextAccessor>();

**Comment by IrakliGabadze** [comment]
services.AddScoped < HttpContextAccessor > ();

**Comment by davidfowl** [comment]
Is there a callstack?

**Comment by serpent5** [comment]
@IrakliGabadze It looks like you've taken a dependency on `HttpContextAccessor` somewhere (note that it's not **`I`**`HttpContextAccessor`). It's possible that all you need to do is change that to depend on the interface, which is what gets registered by the call to `AddHttpContextAccessor`.

**Comment by HaoK** [comment]
I'm going to close this for now feel free to reopen/file a new issue if there's still questions

**Comment by wgutierrezr** [comment]
I have the same issue

**Comment by hermanthotan** [comment]
I try to add this line of code in startup it doesn't work
services.AddHttpContextAccessor();
services.AddScoped<HttpContextAccessor>();

Can someone help it, I follow the exact docs

**Comment by davidfowl** [comment]
Can you file a bug with a repro project that shows the issue?

**Comment by Rick-Anderson** [comment]
@hermanthotan 
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
