### ISSUE TITLE
HttpContext.SignInAsync null after migrate .Net Core 3.0

### ISSUE THREAD

**Issue by kienit** [aspnet/AspNetCore.Docs#14613]
# Issue description

After I migrate my current application from .Net core 2.2 to 3.0. The HttpContext.SiginAsync become null, so all of the authorisation stop working because there is no Identity

# Software versions

- NET Core 3.0.100

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
- Create a new web app with auth
- scaffold identity
- test and compare to your code
- report back here.

**Comment by kienit** [comment]
@Rick-Anderson,
I am currently not using Identity. I followed the instruction "Using cookie for Authentication without Identity".

It works before but after migrating it stop

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by wgutierrezr** [comment]
I have the same issue.

**Comment by Rick-Anderson** [comment]
@kienit  @wgutierrezr  we need the simplest possible repo.

1. Create a new ASP.NET Core 2.2 web app.
2. Update the app to 3.0.
3. Show the problem.

**Comment by Rick-Anderson** [comment]
Dup of #14619
