### ISSUE TITLE
using Microsoft.Extensions.Options need to be added

### ISSUE THREAD

**Issue by hatzhang** [aspnet/AspNetCore.Docs#14622]
should add the following to Startup.cs, or it won't compile
`using Microsoft.Extensions.Options`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
This is not a begging tutorial and not all includes are specified.

**Comment by raegar** [comment]
Personally I think it is worth mentioning under Add a Configuration Model step 3. I'm not exactly a novice but it took me a few minutes check and re-read everything as I thought I had missed a step and didn't want to continue until I was sure I hadn't missed something important..
