### ISSUE TITLE
java signalr don't receive message when app is closed

### ISSUE THREAD

**Issue by tahlilgar** [aspnet/AspNetCore.Docs#14629]
hello.I've implemented an Android chat application with Signal R.
 Everything is working fine but the problem is that I don't get a message when the Android app is completely closed. 
I don't close my connection. Do you have a solution to this problem?

I asked this in StackOverflow in this link https://stackoverflow.com/q/57770474/10711373 .Thanks for taking a look at it.

**Comment by guardrex** [comment]
Hello @tahlilgar ... would you mind opening this issue from the feedback form at the bottom of the topic that you're looking at? It will tag the issue with metadata to track it ... but more importantly, it will automatically ping the right doc author to look at this issue. When you've opened the new issue, you can close this one.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
