### ISSUE TITLE
AlwaysRunResultFilters is applied even response is short-circuited

### ISSUE THREAD

**Issue by ZeekoZhu** [aspnet/AspNetCore.Docs#14625]
&gt; The IAlwaysRunResultFilter and IAsyncAlwaysRunResultFilter interfaces declare an IResultFilter implementation that runs for all action results. The filter is applied to all action results unless:
&gt;
&gt;   * An IExceptionFilter or IAuthorizationFilter applies and short-circuits the response.
&gt;   * An exception filter handles an exception by producing an action result.
&gt; Filters other than IExceptionFilter and IAuthorizationFilter don't short-circuit IAlwaysRunResultFilter and IAsyncAlwaysRunResultFilter.

But in the codebase, `ResourceInvoker.InvokeAlwaysRunResultFilters` is always called after short-circuit.

* [AuthorizationShortCircuit](https://github.com/aspnet/AspNetCore/blob/23596349092f69890c3efe5b8b9005856cc83db2/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs#L403)
* [ResourceShortCircuit](https://github.com/aspnet/AspNetCore/blob/23596349092f69890c3efe5b8b9005856cc83db2/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs#L586)
* ...

Did I understand wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.0#result-filters)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@ZeekoZhu You understand correctly. It looks like the explanations of `IResultFilter`/`IAsyncResultFilter` and `IAlwaysRunResultFilter`/`IAsyncAlwaysRunResultFilter` are being mixed up in the page.

@Rick-Anderson Tagging you as I'm not sure whether `@ardalis` is active on these issues. I think this needs to be changed in the docs page accordingly.

**Comment by Rick-Anderson** [comment]
@serpent5  it would be great if you could PR this.

**Comment by serpent5** [comment]
@Rick-Anderson Yeah, of course. I should've said that in the previous comment actually. :)
