### ISSUE TITLE
There is no `--trust` option in the latest dotnet CLI

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14628]
```
$ dn dev-certs https --trust
Specify --help for a list of available options and commands.
$ dn dev-certs https --help


Usage: dotnet dev-certs https [options]

Options:
  -ep|--export-path  Full path to the exported certificate
  -p|--password      Password to use when exporting the certificate with the private key into a pfx file
  -c|--check         Check for the existence of the certificate but do not perform any action
  --clean            Cleans all HTTPS development certificates from the machine.
  -v|--verbose       Display more debug information.
  -q|--quiet         Display warnings and errors only.
  -h|--help          Show help information
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What version? What platform?

**Comment by Rick-Anderson** [comment]
Open an issue in https://github.com/dotnet/cli/issues
Report your platform and version 
`dotnet --version`
Post the issue link here.

**Comment by Rick-Anderson** [comment]
First try

```
dotnet tool uninstall --global dotnet-dev-certs
dotnet tool install --global dotnet-dev-certs
dotnet dev-certs https --trust
```

**Comment by Rick-Anderson** [comment]
Make sure you have the GA (release version) of the .NET SDK installed. You might need to reinstall it.
