### ISSUE TITLE
site.js should be under wwwroot/js folder

### ISSUE THREAD

**Issue by hatzhang** [aspnet/AspNetCore.Docs#14620]
and there is no site.css in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
*site.css* is used for the test page 
Add an HTML file named _index.htm_l to the _wwwroot_ directory. Replace its contents with the following markup:

Putting *site.js* in */js* is a good convention.

**Comment by Physeos-sys** [comment]
Cannot get index.html to load. Deleted launchUrl from Properties\launchSettings.json. Browser is blank and debug log shows a 404 error.

**Comment by Physeos-sys** [comment]
index.html needs to have <script src="js/site.js" changed to "site.js". Instructions above do not say to create a folder named js in wwwroot
