### ISSUE TITLE
what is the point to use Pascal casing in json to match CLR object's property names?

### ISSUE THREAD

**Issue by hatzhang** [aspnet/AspNetCore.Docs#14623]
camel casing is default now, so why change it anyway? 
isn't that the same to dotnet consumers? 
or this is only a demonstration that it can be done?

[link](https://github.com/aspnet/Mvc/issues/4283)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0&tabs=visual-studio-code#configure-json-serialization-options)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by tylerjames** [comment]
I agree with the above commenter. I get that C# still uses PascalCase, but it just seems tacky to push that out through JSON. I suppose it's something that some people might *want* to do, but I wouldn't suggest that it's something that needs to be done.

**Comment by HiltonGiesenow** [comment]
I don't think this is about which one to use, but rather specifically to fix the "BookName" property, which would not match the original schema otherwise - the example is actually illustrating some useful options to separating C# from JSON representations.

**Comment by Rick-Anderson** [comment]
Moved to #16196
