### ISSUE TITLE
Do you need to restart the app to see the change? 

### ISSUE THREAD

**Issue by boomalator** [aspnet/AspNetCore.Docs#14636]
On my laptop, the change does not reflect until you stop and restart the app. If this is intended, the step should be documented.  In either case, how to stop the app should also be mentioned. A bit of explanation about how the app is running would probably also be welcomed as I don't thing most web apps are run (in dev or in production) by leaving a command window open.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.0&tabs=windows#feedback)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You need to refresh.

@wadepickett  update to make sure it mentions refresh.

**Comment by wadepickett** [comment]
Got it.  Thanks!

**Comment by boomalator** [comment]
Well, admittedly, this particular laptop is being a bit flaky :(  But an F5-refresh in Chrome didn't show the update until I stopped and restarted the application (host).  It may well be something on my end.

**Comment by wadepickett** [comment]
Thanks @boomalator, testing through it just in case.  :)

**Comment by serpent5** [comment]
Could this be related to runtime compilation of Razor files being opt-in as of 3.0?

**Comment by Rick-Anderson** [comment]
@serpent5  that's it. I'm using the default template which is **not** calling `  AddRazorRuntimeCompilation();` and I'm getting changes on refresh.

**Comment by wadepickett** [comment]
I as getting some results as boomalator. Maybe a good argument for using "dotnet watch run" by default for these to keep it simple.

**Comment by wadepickett** [comment]
@danroth27 for awareness.

**Comment by Rick-Anderson** [comment]
I was running from VS. Somehow VS debug mode enables runtime compilation.

**Comment by wadepickett** [comment]
PR fix now available for review:  https://github.com/aspnet/AspNetCore.Docs/pull/14644

**Comment by wadepickett** [comment]
PM reviewed and aproved.  Fix merged #14644.  Thanks @boomalator for taking the time to point this out!  Very appreciated!  Thanks @serpent5 for the insight regarding the opt-in for runtime compilation of Razoor files.

**Comment by wadepickett** [comment]
This is somewhat related to a request to use "dotnet watch run" instead of "dotnet run" for VS Code https://github.com/aspnet/AspNetCore.Docs/issues/9488   I will either expand on that for all tutorials for this situation or create a new issue and link to that.  Thanks.
