### ISSUE TITLE
Two problems with Swashbuckle tutorial

### ISSUE THREAD

**Issue by Sti2nd** [aspnet/AspNetCore.Docs#14631]
Following the tutorial I had two problems.

1. In the [XML comments](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#xml-comments) section I think the first XML example is wrong. To generate the XML file I needed to add `<DocumentationFile>TodoApi.XML</DocumentationFile>` inside the property group. The two XML examples in this section are identical, which leads me to believe the first one should be different.
2. Using launch configurations in VS Code and launching with F5 (Debug) or CTRL + F5 doesn't generate the XML, but using `dotnet run` does generate the XML. 

Targetframework netcoreapp2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16195
