### ISSUE TITLE
3.0 worker service documentation - creation steps error

### ISSUE THREAD

**Issue by pwen090** [aspnet/AspNetCore.Docs#14637]
# Issue description

The steps to create a new worker service project are wrong. It seems in the latest version you no longer select an ASP.NET Core Web Application template but rather a Worker Service template at the top level

**Comment by guardrex** [comment]
Hello @pwen090 ... that's correct. This was a recent change to template layout in the recently released VS 16.3. I'll take care of this on Friday morning. Thanks for commenting.

**Comment by guardrex** [comment]
Note to self: The template is in VS4Mac now. If we don't currently show a tab for it in the two or three places that it's described, this is a good time to add a tab for VS4Mac. 🍎
