### ISSUE TITLE
Blazor templates need updating

### ISSUE THREAD

**Issue by dcuccia** [aspnet/AspNetCore.Docs#14639]
Not sure what might have changed with RTM, but the Blazor templates are still listed as Preview 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's correct. It's only for the Blazor WebAssembly template. Blazor WebAssembly is still in preview. After Blazor WebAssembly is released, that step will be dropped.

**Comment by dcuccia** [comment]
Thanks
