### ISSUE TITLE
[HttpPost] Where does it go?

### ISSUE THREAD

**Issue by Topham88** [aspnet/AspNetCore.Docs#14635]
Unable to determine where exactly the below code goes.

[HttpPost]
public string Index(string searchString, bool notUsed)
{
    return "From [HttpPost]Index: filter on " + searchString;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at the download sample

**Comment by SIVMkeyBOardMAN** [comment]
I can't seem to find it there.

**Comment by test6568** [comment]
Hi, anyone able to help. I'm having the same issue.
