### ISSUE TITLE
Documentation is Incorrect about Kestrel

### ISSUE THREAD

**Issue by gravidThoughts** [aspnet/AspNetCore.Docs#14649]
This documentation is confusing. We are using WebHost.CreateDefaultBuilder() with InProcess specified in the web.config, which is not Kestrel.
Is there documentation specifically for InProcess?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Basics (high level overview) is here :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/servers/

Coverage for IIS/ANCM is here :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#hosting-models

Advanced, deeper details are here :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#hosting-models

**Comment by guardrex** [comment]
I'm going to close because we're happy thus far with the overall split. If you have further feedback, feel free to open a new issue using the **This Page** feedback form at the bottom of any topic.
