### ISSUE TITLE
Update node name and remove "Host on/in" language

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14641]
The node name for host and deploy topics per the guidelines should be *Host and Deploy*. Personally, I like the simple verbs better anyway ... more *action-y* :smile:. It was that way earlier and then it was changed to the gerund form, but I recommend changing it back.

Several of the topics under this node start with "Host on/in." I recommend dropping that useless and distracting language. I suggest going from the current TOC (leaving out the nodes/topics that I'm not focusing on here) ...

* Hosting and deployment
  * Host on Azure App Service
  * Host on Windows with IIS
  * Host in a Windows service [sic: that should be "Windows Service"]
  * Host on Linux with Nginx
  * Host on Linux with Apache
  * Host in Docker
  * Host in a web farm

... to ...

* Host and deploy
  * Azure App Service
  * IIS
  * Windows Service
  * Linux with Nginx
  * Linux with Apache
  * Docker
  * Web farm

@Rick-Anderson @scottaddie @danroth27

**Comment by scottaddie** [comment]
:shipit:
