### ISSUE TITLE
Additional information about endpoint-routing

### ISSUE THREAD

**Issue by mbedded** [aspnet/AspNetCore.Docs#14655]
From my point of view this chapter should have additional information about Endpoint-Routing and needed changes. Do i have missed the content somewhere?

Many articles are writing that we have to change the calls to something like
```
app.UseEndpoints(x =>
{
    x.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
});
```
without mentioning that some things are broken like Attribute-Routing. I am unable to access controllers or methods by using `[Route(..)]` nor `[HttpGet(..)]`.
A call of `MapControllers()` (instead of `MapControllerRoute(..)`) didn't fixed the issue either. I hoped there would be some more information about that.

If i understood it correctly the usage of `AddMvc()` should not be used anymore in the future because enpoint routing offers a better performance and more possibilities for middleware.

Unfortunately the page https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0 doesn't provide information about this either.
Unfortunately i am running from one issue into another without getting information how to resolve them.
I even used a plain simple new Asp.Net Core project (created by VS 2019) to avoid any project-specific issues.

EDIT 2019-09-27: Typo fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak can you assign someone to update this routing doc for endpoint-routing?

**Comment by mbedded** [comment]
A short update from my side:
I read the [migration-documentation from 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#mvc-controllers) another time. There it says you have to use 
```
 app.UseEndpoints(endpoints => {
  endpoints.MapControllers();
});
```
to enable Attribute-Routing. It seems that this documentation should be updated as well then (or no one besides me uses attribute routing or found another workaround).

**Comment by boboberg** [comment]
Important info for using attribute routing. Thank you. You must also call services.AddControllersWithViews();
within ConfigureServices()

**Comment by Rick-Anderson** [comment]
Moved to #13871
