### ISSUE TITLE
Indicate Azure SignalR Service availability in the Publish dialog

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#14652]
Azure SignalR Service documentation isn't ready for asp.net core 3.0.

Furthermore, I am developing an webapp with signalr core. I wonder if having my own signalr connection is causing the failures. If I call hConnection.StartAsync(), I'll get 

rror: System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions.
 ---&gt; System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eddf2de-7e50-5680-ff2d-a4307f26b5c0
* Version Independent ID: 673f220c-ad49-bd27-5d74-3a9c44747cba
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/blazor/server.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> isn't ready for asp.net core 3.0

Everything was checked and approved by engineering prior to the docs launch.

Recommend you open that for the engineers to take a look at ...

https://github.com/aspnet/AspNetCore/issues

**Comment by Alienroid** [comment]
You are correct. I just created another blazor server-side project and use azure signalr service (from web deploy). It works! 

The link provided above for Azure SignalR Service is totally misleading for aspnetcore 3.0. The working example, I didn't need to configure anything mentioned from that link. 

Please ignore the errors I posted above, that's something I am still looking into. Thanks again.

**Comment by guardrex** [comment]
Was this the exact remark that you're referring to? ...

> We recommend using the Azure SignalR Service for Blazor Server apps.

If not, what was confusing or misleading?

**Comment by Alienroid** [comment]
Yes, that's what was misleading. Perhaps instead of using that link, just post an image saying use this:
![publish](https://user-images.githubusercontent.com/32919730/65732349-6ebea600-e07e-11e9-940f-e8f03776a8f2.png)

**Comment by guardrex** [comment]
We don't put images into the docs ... too hard to maintain.

Leave this open. We should enhance the text slightly to indicate the availability via the Publish dialog.

This issue will close automatically when the PR merges later.

Thanks for commenting.
