### ISSUE TITLE
Microsoft Support for AspNetCore.Diagnostics.HealthChecks?

### ISSUE THREAD

**Issue by cshell-incomm** [aspnet/AspNetCore.Docs#14662]
This article has a comment saying "AspNetCore.Diagnostics.HealthChecks is a port of BeatPulse and isn't maintained or supported by Microsoft." BeatPulse is no longer maintained on GitHub so who maintains \ supports this library? 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cshell-incomm ... The link changed ... they moved their repo. I'll update the link.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks

**Comment by guardrex** [comment]
Not so much changed ...... they ported that depreciated lib over to the new repo and package. The text was actually correct. However, **_it is a little confusing_**. We can just remove the link and mention, and it will all work out just fine.

**Comment by cshell-incomm** [comment]
Well, the library looks great - before I started adding to too many solutions I wanted to be sure it was not actually unsupported. Thanks for the quick reply.
