### ISSUE TITLE
Scaffold Error

### ISSUE THREAD

**Issue by jacobDinesenWork** [aspnet/AspNetCore.Docs#14661]
Following the tutorial, I run into an error when scaffolding the model.

All the suggestions show up as expacted: "Movie (RazorPagesMovie.Models)" in Model class, and "RazorPagesMovie.Models.RazorPagesMovieContextt" in which I changed ".Models." to ".Data.", but when I press add, VS comes with the following error:

There was an error running the selected code generator: 'Package restore failed. Rolling back package changes for 'RazorPagesMovie'

I'm using VS2019 (16.3.1) .NET core 3.0.1. Everything should be up to date with newest version, and I'm unable to find anyuseful info about this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try creating another project where you don't change the namespace.

**Comment by jacobDinesenWork** [comment]
Thanks for your reply.

Yes. I have tried leaving the namespace as suggested (RazorPagesMovie.Models.RazorPagesMovieContext), but the error remains.

I have deleted the project and tried over several times, following the tutorial closely, but nothing seems to help,

**Comment by Rick-Anderson** [comment]
Try:

* Follow the CLI instructions (command line). If that fails, reinstall .NET Core 3.0
* Create a new project with VS instructions. If that fails
* Follow the CLI instructions (command line). If that fails, report the error to https://github.com/aspnet/Scaffolding/issues/1070

**Comment by irfangazi** [comment]
![Annotation 2019-10-02 205417](https://user-images.githubusercontent.com/56088976/66068767-e137f600-e556-11e9-89b0-f84a96f54b0b.png)
