### ISSUE TITLE
Scaffolder issue in .NET Core 3

### ISSUE THREAD

**Issue by iman5** [aspnet/AspNetCore.Docs#14679]
I've been using the docs to scaffold the full identity but there are many issues.
when i create the scaffold with override all files and choosing the + for a new context class and user class, it generates this in IdentityHostingStartup and vbrings lots of problems with it:
 ```
builder.ConfigureServices((context, services) => {
                services.AddDbContext<EF1Context>(options =>
                    options.UseSqlServer(
                        context.Configuration.GetConnectionString("DefaultConnection")));

                services.AddDefaultIdentity<EF1User>(options => options.SignIn.RequireConfirmedAccount = true)
                    .AddEntityFrameworkStores<EF1Context>();
            });
```
IF i run it immidiately i get System.InvalidOperationException: 'Scheme already exists: Identity.Application'

IF i comment below code as some suggest because of repetition i get InvalidOperationException: unable to resolve service for typeMicrosoft.AspNetCore.Identity.UserManager`1[EF1.Areas.Identity.Data.EF1User]' while attempting to activate 'EF1.Areas.Identity.Pages.Account.RegisterModel'.:
```
services.AddDefaultIdentity<EF1User>(options => options.SignIn.RequireConfirmedAccount = true)
                    .AddEntityFrameworkStores<EF1Context>();
```

IF i change the ConfigureServices to below as the docs suggest   get InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[EF1.Areas.Identity.Data.EF1User]' while attempting to activate 'EF1.Areas.Identity.Pages.Account.RegisterModel'.
Still the EF1 user and context is not recognized.
```

services.AddIdentity<IdentityUser, IdentityRole>()
        // services.AddDefaultIdentity<IdentityUser>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();
```

What to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#create-full-identity-ui-source)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This doc needs updates but I could not reproduce your problem. Following the docs:

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#scaffold-identity-into-a-razor-project-without-existing-authorization

```
set projNam=RPnoAuth
set projType=webapp

dotnet new %projType% -o %projNam%
cd %projNam%
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore
dotnet add package Microsoft.AspNetCore.Identity.UI
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet restore
dotnet aspnet-codegenerator identity --useDefaultUI
dotnet ef migrations add CreateIdentitySchema
dotnet ef database update
``

add login partial
Call UseAuthentication after UseStaticFiles:

And everything works.

**Comment by iman5** [comment]
Hi,
To replicate it, first, choose the identity in the project maker and then when the project comes up, scaffold the full identity. That's it.

**Comment by Rick-Anderson** [comment]
Can you get my approach working?

**Comment by iman5** [comment]
This is cli but I only used the gui. I don't think they are different as they both should work.
Did you try gui?
there is another thing when removing the cascade delete as well. it doesn't work as 2.2 does.

**Comment by Rick-Anderson** [comment]
No repo
