### ISSUE TITLE
2.2 -> 3.0 Migration docs should clearly explain view compilation change

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#14686]
We need to bump up the visibility of the instructions for migrating runtime compilation.

See: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#opt-in-to-runtime-compilation

This is what the text says:

> In 3.0, runtime compilation is an opt-in scenario. To enable runtime compilation, see Razor file compilation in ASP.NET Core.

This isn't a clear explanation - what is runtime compilation? That's a technical term that lots of our users won't understand. This linked doc isn't much clearer on what the impact will be on most users migrating code.

I'm looking for an explanation that is at the level of "In previous releases we would compile your view code while the app is running. Now this **only** happens as part of the build by default. If you want to compile view code - in response to changes while running - or if you want to compile view code that wasn't present during the build - then you need to go follow these instructions ...."

Then we should have a clear before/after of code samples.

I want to be able to answer questions like this: https://github.com/aspnet/AspNetCore/issues/14544 by pointing people at the link, but it's not good enough.

**Comment by Rick-Anderson** [comment]
@serpent5  could you fix this?

**Comment by serpent5** [comment]
@Rick-Anderson Yeah, I can take a look. Do you know what is meant by the following:

> Then we should have a clear before/after of code samples.

Does this mean examples of do-your-own runtime compilation or is it more around how it was just `AddMvc` before but now it's `AddXXX().AddRazorRuntimeCompilation()` etc?

**Comment by Rick-Anderson** [comment]
@serpent5  it's before 3.0 vs. 3.0

**Comment by scottaddie** [comment]
Fixed in https://github.com/aspnet/AspNetCore.Docs/pull/14861
