### ISSUE TITLE
Add Blizzard OAuth instructions

### ISSUE THREAD

**Issue by natrist** [aspnet/AspNetCore.Docs#14680]
Hi,

Would it be possible to add instructions for Blizzard OAuth?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f869636-630e-2542-b029-199154ef70c3
* Version Independent ID: cea7e5a6-383f-aeb5-2476-7c7d0a8bb851
* Content: [External OAuth authentication providers](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/social/other-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/other-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Blazor?

**Comment by guardrex** [comment]
This one ... https://develop.battle.net/documentation/guides/using-oauth

There are things out there for it with ASP.NET Core:

* https://us.battle.net/forums/en/bnet/topic/20743755853 (shows someone using `UseOpenIdConnectAuthentication`)
* Some discussion, link, info here :point_right: https://us.battle.net/forums/en/bnet/topic/14728823854
* *WOOT!* :point_right: https://www.nuget.org/packages/AspNet.Security.OAuth.BattleNet/ with TOP community devs working on that! :+1:

@Rick-Anderson `aspnet-contrib` is already in the topic ... very first paragraph ... links off and lists that package with the rest ...

<img width="416" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65821991-a9514b80-e202-11e9-8bf6-24a0525ccb59.PNG">

... I don't think that there's anything else for this issue.

**Comment by natrist** [comment]
Yes, thank you very much for your replies.
I meant mostly that links should be added on the Blazor tutorials list page.

**Comment by guardrex** [comment]
I don't understand ... that's not a "Blazor tutorials list page." That's the *External OAuth authentication providers* page, and the providers there aren't Blazor-specific.

**Comment by natrist** [comment]
Well, you're right. It's not really relevant but I thought I was still on the Blazor.net website for some reason... Maybe I was, maybe I wasn't. Can't remember much of that night 🤣
