### ISSUE TITLE
Model binding changed from 2.2. to 3.0

### ISSUE THREAD

**Issue by vankampenp** [aspnet/AspNetCore.Docs#14698]
When binding in a Post method, with a [FromBody] attribute, there are differences between the 2.2 and the 3.0 implementation.
* null to int: when binding a null value to an int, in 2.2 the model is still valid. In 3.0 the whole model gets a null value.
* string to int: in 2.2 a string json value binds to an int. (the string is cast to the int).  In 3.0 the model gets a null value
* int to string: in 2.2 an int json value binds to a string. In 3.0 the model gets a null value.
If this is intended behavior, it would be good to document this somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak @pranavkm what model binding changes do we need to document?

**Comment by vankampenp** [comment]
On one of my Api, I use an Enum:
public enum EnumTaal
    {
        Nl,
        En
    }
As example, Swagger shows this
..
 "taal": "nl"
..
And in the model it is shown as:
taal*	string
Enum:
[ nl, en ]
In 2.2 the acceptable values were "nl" and "en" as expected
In 3.0 I get an error:
"$.taal": [
            "The JSON value could not be converted to DTOAPI.Controllers.v2.Models.Ehm.EnumTaal. Path: $.taal | LineNumber: 9 | BytePositionInLine: 14."
        ]

The only acceptable values are now 1 and 2.

Is there an attribute that I can use to force the values back to "nl" and "en'?

**Comment by vankampenp** [comment]
Ah: 
[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
public enum EnumTaal
{
Nl,
En
}
works
