### ISSUE TITLE
RequireScope 

### ISSUE THREAD

**Issue by vankampenp** [aspnet/AspNetCore.Docs#14699]
AuthorizationPolicyBuilder' does not contain a definition for 'RequireScope' and no accessible extension method 'RequireScope' accepting a first argument of type 'AuthorizationPolicyBuilder' could be found (are you missing a using directive or an assembly reference?)	

Besides getting this error on RequireScope, I would welcome some more explanation. What is it doing, and in what scenario should I use the RequireScope?

(Thanks for the excellent document, I migrated a large app in a couple of hours, with this explanation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  can you provide more info on `  .RequireScope("MyScope") `

**Comment by blowdart** [comment]
No, because I don't know where it came from either. 

Unless @javiercn says this is from some spa extension best to check who added that, and ask them

**Comment by Rick-Anderson** [comment]
@HaoK  please review.

**Comment by HaoK** [comment]
There is no such method in our APIs, so we probably should remove that from our migration guide, or at least point out that its specific to identity server so only a specific subset of our templates that are using that, its at the bottom of: (http://docs.identityserver.io/en/latest/topics/apis.html)
