### ISSUE TITLE
` IStartupFilter`

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14694]
` IStartupFilter` still doesn't make sense to me.
You can control the order of middleware execution via registration order and you can position the code to execute before or after the `next` statement.

So why use ` IStartupFilter` at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0#configure-services-without-startup)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
@Legends what you want to inject middleware at the beginning or end of the pipeline without an explicit call to Use* in the pipeline.

**Comment by Legends** [comment]
What's the benefit besides not using `use`?

**Comment by davidfowl** [comment]
It's used commonly by ASP.NET Core itself to add defaults to the beginning of the pipeline without having to make the application author explicitly register pieces of middleware.

> What's the benefit besides not using use?

It's really about having a different component call Use on behalf of the app author.
