### ISSUE TITLE
Confusing reference to adding EF Core support

### ISSUE THREAD

**Issue by sbsw** [aspnet/AspNetCore.Docs#14695]
The section on adding package references for removed assemblies (https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies) mentions Entity Framework Core, but then gives a link to an article about adding support for EF Core providers. This leads readers (like me) to assume that the requirement is to add support for EF Core providers, but not for EF Core itself. Adding the name of the EF Core NuGet package (as you do for all of the other removed assemblies) would resolve this confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#update-the-project-file)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sounds very reasonable.
