### ISSUE TITLE
`[Authorize]` on Hub cause `negotiate`  401 

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore.Docs#14692]
`[Authorize]` on Hub cause `negotiate`  401   in asp.net core 2.2,  and there no way to pass access_token to the negotiate request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by davidfowl** [comment]
Can you elaborate? Do you have an example?

**Comment by John0King** [comment]
just add `[authorize]` on the Hub , then the  `negotiate` request  are also need  authorization .
now I'm move the `[authorize]` to all hub method, now.
but I'm facing a new much odd issue with signalr,
I'm useing IdentityServer4 with beare authentication,   and in signalr  hub it just get empty users (the Context.User property is an blank user, and any call to it will cause an authorization error) .  but  I'm ok with MVC , so I think my authentication party is ok too. 
I'll show more info when I can solve it.

**Comment by davidfowl** [comment]
That's by design, you need to do auth before is all. The article shows how to configure the client and the server JWT bearer middleware to handle this.

**Comment by John0King** [comment]
@davidfowl  
actually I can't,  the negotiate request  doesn't use `accessTokenFactory`  , so It's impossible to do the authentication.

**Comment by davidfowl** [comment]
AFAIK it should. If you have a repro, that would be great.

**Comment by John0King** [comment]
odd , I find where it cause it doesn't work, but I do not know why .
```C#
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(o =>
                {
                    var jwtSection = Configuration.GetSection("Authentication:JwtBearer");
                    o.ApiName = jwtSection.GetValue<string>("ApiName");
                    o.ApiSecret = jwtSection.GetValue<string>("ApiSecret");
                    o.Authority = jwtSection.GetValue<string>("Authority");
                    o.RequireHttpsMetadata = jwtSection.GetValue<bool>("RequireHttps");
                    o.SaveToken = true;
                    //o.JwtBearerEvents.OnMessageReceived = context =>
                    //{
                    //    if (string.IsNullOrEmpty(context.Token))
                    //    {
                    //        var token = context.Request.Query["access_token"].ToString();
                    //        if (!string.IsNullOrEmpty(token))
                    //        {
                    //            context.Token = token;
                    //        }
                    //    }
                    //    return Task.CompletedTask;
                    //};
                    o.TokenRetriever = request =>
                    {
                        var token = TokenRetrieval.FromAuthorizationHeader()(request);
                        if (string.IsNullOrEmpty(token))
                        {
                            token = TokenRetrieval.FromQueryString()(request);
                        }
                        return token;
                    };
                });
```

`OnMessageReceived` doesn't work

**Comment by davidfowl** [comment]
Maybe identity server specific? This might be worth adding to the docs
cc @leastprivilege @brockallen

**Comment by John0King** [comment]
I'm seen the `id4.AccessTokenValidator` souce code ,    I can't find anything wrong in there side.


https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/2b47ee5baba65b8f72f8e4ca4365b09c2b1277c8/src/IdentityServerAuthenticationOptions.cs#L164-L168

**Comment by leastprivilege** [comment]
Try with plain JwtBearer handler first - and see if this makes a difference.

You only need our handler if you need to also support reference tokens.

**Comment by leastprivilege** [comment]
But negotiate sounds like Windows authentication somewhere..
