### ISSUE TITLE
IncrementCount -> IncrementAmount inside onclick

### ISSUE THREAD

**Issue by smilyte** [aspnet/AspNetCore.Docs#14696]
In the example where Pages/Counter.razor is modified to have IncrementCount parameter, onclick still calls IncrementCount. This gives build error, as it should be replaced with IncrementAmount.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @smilyte ... I'll get that patched up.

**Comment by guardrex** [comment]
No, @smilyte ... actually, that's correct. The method is `IncrementCount` there.

**Comment by guardrex** [comment]
Check your spellings in your code. I've seen a spelling mistake cause that sort of error.

**Comment by smilyte** [comment]
Wow, it's been a long day for me. I managed to copy-type this incorrectly :D Sorry, and thanks for quick look!
