### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DaFreeLum** [aspnet/AspNetCore.Docs#14697]
All was going so well untill I added opt.UseInMemoryDatabase("ToDoList"));  and I tried to add the controller - the model and classes are there but the code generator fails 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by DaFreeLum** [comment]
nuget -Install-Package Microsoft.EntityFrameworkCore.InMemory fixed both issues

**Comment by OmarElhenawy** [comment]
> nuget -Install-Package Microsoft.EntityFrameworkCore.InMemory fixed both issues

Thanks it Worked

**Comment by Rick-Anderson** [comment]
That's in the doc

**Comment by westl** [comment]
Just ran through this tutorial, nice work btw! 

I actually missed this part as well. 

If it's not too much, can we get it in **bold** or added to the card's title since it's a crucial step? (Add Microsoft.EntityFrameworkCore.SqlServer & Microsoft.EntityFrameworkCore.InMemory)
