### ISSUE TITLE
ASP.NET Core Identity 2.2 to 3.0 change log

### ISSUE THREAD

**Issue by Eirenarch** [aspnet/AspNetCore.Docs#14707]
I've tried searching around (ASP.NET Core Identity 3.0 breaking changes, Migrating ASP.NET Core Identity 2.2 to 3.0 and some other search terms) and I have failed to find a change log describing the changes in ASP.NET Core Identity 3.0. It would be great if you can provide docs on that

- Does 3.0 include any changes to the database? Do I need to make any changes to the structure of my existing database in order to move to ASP.NET Core 3.0
- What changes to the code are required

Side question - is it possible to use Identity 2.2 with ASP.NET Core 3.0 (I've tried and failed)

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/14708

**Comment by guardrex** [comment]
Hello @Eirenarch ... I moved it using the feedback form at the bottom of the topic. That process adds metadata and pings the author.
