### ISSUE TITLE
Blazor Globalization and localization

### ISSUE THREAD

**Issue by amir6mehrabi** [aspnet/AspNetCore.Docs#14703]
How we can do this for Blazor? Is it possible doing this without controllers in Blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Currently covered here :point_right: https://docs.microsoft.com/aspnet/core/blazor/components#localization and in the following section https://docs.microsoft.com/aspnet/core/blazor/components#provide-ui-to-choose-the-culture

... but we might have more work to do. For example, there's this issue that was opened (but hasn't been triaged yet): https://github.com/aspnet/AspNetCore.Docs/issues/14433

If you don't find the information you need from the current coverage, add your remarks back here, and I'll re-open this issue for engineering to take a look at.
