### ISSUE TITLE
IValueProverFactory missing RemoveType definition

### ISSUE THREAD

**Issue by jwhitener6** [aspnet/AspNetCore.Docs#14701]
I don't think I've ever run a sample from MS and it just work. I spend an hour trying to update different references but almost always end up with only more errors....

It says there is no definition for RemoveType in List&lt;IValueProviderFactory&gt;.  using Microsoft.AspNetCore.Mvc.ModelBinding but it finds nothing. I try to update the AspNetCore.Mvc reference to 2.2.0 but must update other references for compatibility and when I do that it ends up with about 20 different errors, though the RemoveType becomes recognized....

Running VS 2017 (15.9.16)
I am looking to learn how to integrate file uploads into my .net Core 2.2.0 web app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jwhitener6 The topic+sample are very old at this point. We have an overhauled topic+sample in review now on https://github.com/aspnet/AspNetCore.Docs/pull/12344. We're not going to address the current sample further. You can get the new sample from my repo ... I just updated it over at https://github.com/guardrex/FileUploadsSampleApp. If you have comments on the File Uploads PR, put them on #12344 (or if you have comments about 3.0 updates that we should get to this week for that work, put your remarks on https://github.com/aspnet/AspNetCore.Docs/issues/13344).
