### ISSUE TITLE
Little code change

### ISSUE THREAD

**Issue by SndrSchnklshk** [aspnet/AspNetCore.Docs#14704]
You guys might need to add the declaration of the "remoteIp" inside the filter (executing):
var remoteIp = context.HttpContext.Connection.RemoteIpAddress;

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
🙈 *Good idea* @SndrSchnklshk! 🙈

Thanks ... I'll take care of it.
