### ISSUE TITLE
Add URL to instructions for Postman in "Examine the PostTodoItem create method"

### ISSUE THREAD

**Issue by owens2024** [aspnet/AspNetCore.Docs#14710]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#test-posttodoitem-with-postman

In the steps to test the PostTodoItem with Postman, need to add the url (https://localhost:5001/api/TodoItems) to the steps (after the request type set to POST)

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/14711

@owens2024 Please use the feedback form at the bottom of any topic. It will add metadata for issue work and automatically pings the author. No worries tho ... I moved it. Track on the new issue.
