### ISSUE TITLE
Single file deployments aren't supported in AspNetCoreModuleV2 + InProcess

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14714]
https://github.com/aspnet/AspNetCore/issues/14473#issuecomment-536674738

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#in-process-hosting-model)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by jkotalik** [comment]
@guardrex updated the title. This only impacts inprocess deployment due to how we can't start another exe in the same process that is running the exe.
