### ISSUE TITLE
Add URL to instructions for Postman in "Examine the PostTodoItem create method"

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14711]
From @owens2024 ...

> In the steps to test the PostTodoItem with Postman, need to add the url (https://localhost:5001/api/TodoItems) to the steps (after the request type set to POST)

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#examine-the-posttodoitem-create-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#test-posttodoitem-with-postman)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup and moved to  #16901
