### ISSUE TITLE
Link to Azure dashboard

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14725]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-3.0&tabs=visual-studio#deploy-aspnet-core-30-to-azure-app-service)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I had the impression that that's not official. @scottaddie, is that official?

**Comment by Rick-Anderson** [comment]
@glennc  OK to point to https://aspnetcoreon.azurewebsites.net/ ?

**Comment by guardrex** [comment]
I prob made a bad guess ... the privacy policy points to the MS Privacy Policy.

Recommendation tho: Might want to put something on that dashboard UI that it's maintained by MS.
