### ISSUE TITLE
Incorrect example in the Additional Fields section?

### ISSUE THREAD

**Issue by pjdennis** [aspnet/AspNetCore.Docs#14731]
It looks like the first example in the [Additional fields](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0#additional-fields) section is incorrect - shouldn't FirstName reference AdditionalFields = nameof(LastName) and vice versa?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Additional fields](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0#additional-fields)

**Comment by Rick-Anderson** [comment]
@serpent5 please review

**Comment by serpent5** [comment]
Yeah, @pjdennis is correct.

**Comment by serpent5** [comment]
@Rick-Anderson I think this can be closed.

**Comment by Rick-Anderson** [comment]
@serpent5  I thought this was fixed but [GitHub history](https://github.com/aspnet/AspNetCore.Docs/commits/master/aspnetcore/mvc/models/validation.md) doesn't show the PR.

**Comment by serpent5** [comment]
It was just a change to the sample code in https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation/sample/Models/User.cs.

**Comment by Rick-Anderson** [comment]
That's it, thanks!
