### ISSUE TITLE
mplicit Razor expressions start with @ followed by C# code ? ...

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore.Docs#14735]
What about VB code support (or B# as some of us like to call it -- just to be cool like C#)?

No mention is made (at least that I can find) whether or not B# code is supported -- I'll apologize in advance if I missed something earlier that specified that C# is the ONLY language supported by Razor pages.

Having come from the WebForms (.Net Framework environment) -- I have yet to find a simple (and I mean simple) "Hello World" website example for .net core; (please provide info regarding the difference between a "web app" and a "website").  I find MVC overly complex and code heavy.  What would be the absolute minimum to get a simple form (created from code, not markup) up and running; say with two fields, first name and last name and then post back to the same page and display "Hello First Name, Last Name" under .Net core (in under 25,000 lines or less)??!!

ps:  This "new" fangled approach to chaining statements, for example:

```
do_something().then_something().then_call_this_method.AndDoSomethingElse( object =
        {
            another_object.Method();
        });
```

... is really a nightmare way to code -- has anyone read "Steve McConnels" book "Code Complete"???  -- EVERYONE doing any work on documentation should make this required reading; you'll find out very quickly that separate statements (each on their own line) are far easier to read and maintain the densely chained statements littering the documentation.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't support VB. Coming from web forms, we recommend https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start
