### ISSUE TITLE
JSInterop example for Blazor documentation should return a ValueTask<T>

### ISSUE THREAD

**Issue by simonpbond** [aspnet/AspNetCore.Docs#14738]
The JSInterop - Blazor documentation should return a ValueTask<T>?
[Link here.](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#capture-references-to-elements)

> To use an extension method to focus an element, create a static extension method that receives the IJSRuntime instance:
`public static Task Focus(this ElementReference elementRef, IJSRuntime jsRuntime)
{
    return jsRuntime.InvokeAsync<object>(
        "exampleJsFunctions.focusElement", elementRef);
}`

I may be wrong, however I assume it should now be:
`public static ValueTask<T> Focus<T>(this ElementReference elementRef, IJSRuntime jsRuntime)
{
    return jsRuntime.InvokeAsync<T>(
        "exampleJsFunctions.focusElement", elementRef);
}`

**Comment by guardrex** [comment]
@simonpbond Please use the This Page feedback form at the bottom of any topic. It adds metadata for working the issue and pings the author (*ME!* :smile: lol).

No worries ... I just moved it. Track on the new issue.

Moved to https://github.com/aspnet/AspNetCore.Docs/issues/14739

**Comment by simonpbond** [comment]
@guardrex Sorry Luke! Will do in future!
