### ISSUE TITLE
Components Page Way Too Long

### ISSUE THREAD

**Issue by jlinstrum** [aspnet/AspNetCore.Docs#14751]
It seems like more than half of the most useful Blazor information is on this one web page. Fortunately there is an index to the page or it would be unusable, but it would still be hugely helpful to new Blazor developers to reorganize this page into smaller, more cohesive subtopics on separate pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @jlinstrum ... It's under discussion with engineering. See https://github.com/aspnet/AspNetCore.Docs/issues/14353.
