### ISSUE TITLE
IHostingEnvironment is Obsolete

### ISSUE THREAD

**Issue by isaac2004** [aspnet/AspNetCore.Docs#14750]
Starting in 3.0, `IHostingEnvironment` is obsolete and the recommendation  is to use `IWebHostEnvironment`. This will change how lots of people use the injected service to get things like Paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@isaac2004 Yes, but this topic is really more of a 2.2 scenario at this point. Engineering recommends moving to the Generic Host for 3.0, and the change for `IWebHostEnvironment` is covered/demonstrated there.
