### ISSUE TITLE
Uninstalling previous Blazor versions

### ISSUE THREAD

**Issue by 1944GPW** [aspnet/AspNetCore.Docs#14753]
I'm having trouble with the Blazor templates only giving me the Blazor App server-side template, not the Blazor Server/Shared/Client 3-in-1 project template as shown on Tim Corey's Blazor video on Youtube. 
The word 'Blazor' is no longer included in the ASP.NET Core Application template like it is in Tim's video.  
I have VS2019 Preview up-to-date, latest Core 3.0 up-to-date and Blazor template latest Preview 9 up-to-date. 
This is very confusing. 
Also, since you mention uninstalling previous Blazor templates, can you show the uninstall command for this please, or link to it?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
WRT the template for a hosted WebAssembly app ... it's activated by the checkbox on the WebAssembly app template.

<img width="704" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/66028284-645b3c80-e4c2-11e9-9bea-525d8d404186.PNG">

The checkbox is covered in the *Hosting Models* topic under *WebAssembly*. I thought about calling it out more specifically in the *Get Started* topic, but I'd like to see if more readers run into a problem finding it. I'll keep an :ear: out for more questions on this.

WRT "uninstall" ... it's not by command. If you still have the **Blazor** preview extension installed, uninstall it from the Extensions UI in VS: **Extensions** > **Manage Extensions** in the menu bar.

**Comment by mike-01** [comment]
I did this and I still have Blazor as a template. I've uninstalled using Extensions>Manage Extensions and also by using the Visual Studio installer and modifying my installation. Blazor does not go away. When I then install Blazor again I have multiple WebAssembly templates, one of which doesn't contains only client code and doesn't compile, another that has both Server and Client. How can I fully uninstall Blazor?

**Comment by mike-01** [comment]
Also, what does WRT mean?

**Comment by conficient** [comment]
WRT = with respect to  

I think

**Comment by pjjdebruijn** [comment]
asp.net core hosted wont work with the static template preview. so before you start developing your app make sure u get the deployment working, which u wont get working unless u fall for the azure functions vendor lock...
microsoft made sure it works with functions and not with a standard api...

..|..
