### ISSUE TITLE
NS_ERROR_NET_INADEQUATE_SECURITY in Firefox

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14756]
FireFox doesn't support our dev cert - right?
What's the Edge error? Easy to test, run `dotnet dev-certs https --clean` first

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&branch=pr-en-us-14755&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@scottaddie FireFox doesn't support our dev cert - right?

**Comment by scottaddie** [comment]
@Rick-Anderson That appears to be the case. Here's what I see:

![image](https://user-images.githubusercontent.com/10702007/66049350-e1050f80-e4f0-11e9-8f5c-c5cf0629015f.png)
