### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by richards-randall** [aspnet/AspNetCore.Docs#14752]
I have tried to work through this article at least 6 times.  I consider Rick Anderson to be the best writer in the Microsoft group.  It is very well written, but I am having a problem.  After I scaffold and try to run the program, it always gives the HTTP Error 500.30. I upgraded to the latest version of VS last night. I still get the error.  I have gotten the same result when working through programs in every book I purchase on VS.  Can anyone give me some help. THANKS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
what is `dotnet --version`` ?
run it from the command line
`dotnet run`
What's the error?

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#50030-in-process-startup-failure

**Comment by guardrex** [comment]
The code fences goofed ... prob cell ☎️ keyboard. :smile:

> what is `dotnet --version` ?
> run it from the command line
> `dotnet run`
> What's the error?

**Comment by richards-randall** [comment]
The dotnet version is 3.0.100

**Comment by richards-randall** [comment]
Sorry, the SDK version is 3.0.100.  The .NET Core version is 3.0.  When I ran dotnet run, I got many, many screens of errors. The last one was: AppData\Local\Microsoft\VisualStudio\15.0_a875a2b4\VTC\427a3b5200a62594e9d2ec5b8e173f25\~PC\P\CSharp\Cross-Platform\MasterDetail.Azure.PCL.zip\MasterDetail.Android\Resources\Resource.designer.cs(29,102): error CS1056: Unexpected character '$' [C:\Users\Randall\NumbersInCSharp.csproj]
I have to admit that I have no clue what this means.  Should I uninstall all previous versions of VS?

**Comment by Rick-Anderson** [comment]
Follow the CLI instructions. Don't use VS to generate any of the code. You can use VS to edit the code.

**Comment by Rick-Anderson** [comment]
See the [ASP.NET Core on App Service Dashboard](https://aspnetcoreon.azurewebsites.net/) for the version of ASP.NET Core available on Azure App service. and #14515

**Comment by richards-randall** [comment]
Thanks for the help. I haven't gotten to work on this for several days.
Have been traveling and now at my Vietnam reunion. Thank you
