### ISSUE TITLE
Blazor WebAssembly sample references a previous version of the API tutorial

### ISSUE THREAD

**Issue by juandelacruz23** [aspnet/AspNetCore.Docs#14769]
Blazor docs references [this sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/3.x/BlazorSample), and it says it uses the [API](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi) from the WebApi tutorial. I found some problems running them:

- The new api version uses endpoints called api/TodoItems, while the Blazor sample calls api/Todo
- The web api uses the same port than blazor, and trying to run it crashes at first, should changing it be documented? Along with enabling CORS.
- There are some css files missing.
- A file/class was renamed in the web api, but it's references on Program.cs weren't, so it fails to compile.

I almost solved all of it, it's ok to make a pull request? Or would this be solved by another person? 🤔

**Comment by guardrex** [comment]
Hello @juandelacruz23 ... sure thing on the PR. That would be very helpful. We're 🏃😅 and appreciate the help.

First thing tho ..... let me move this issue. Stand-by ....

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/14771.

@juandelacruz23 ... Use the **This Page** feedback form at the bottom of any topic. It adds metadata and pings the author. No worries ... I moved this to #14771. We'll pick up the discussion over there.
