### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by bbarry** [aspnet/AspNetCore.Docs#14761]
The first example on this page returns a `List<Product>`. It should not directly return this type according to framework guidelines , various FxCop/analyzers and numerous online references: see https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1002-do-not-expose-generic-lists?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?wt.mc_id=docsexp4-reddit-marouill&view=aspnetcore-3.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
This rule isn't applicable to controllers. For an explanation, see https://github.com/aspnet/AspNetCore.Docs/pull/16982#issuecomment-585335171.

**Comment by bbarry** [comment]
Someone should tell the analyzer team that. Either the example controller method here should be updated or the documentation for the analyzer should be updated. 

I can explain it to developers but I cannot convince my auditors that I am justifiably ignoring this rule without some documentation to point at.

**Comment by scottaddie** [comment]
@bbarry I think the problem is https://docs.microsoft.com/visualstudio/code-quality/design-warnings?view=vs-2019. The link text (at the top of the doc) should be changed from ".NET Design Guidelines" to ".NET Framework Design Guidelines". I'll submit a PR to address that low-hanging fruit.
