### ISSUE TITLE
3.0 update: ASP.NET Core Middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14774]
Update  samples using 3.0 templates and endpoint routing.

```
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak please assign someone to show 3.0 template based samples of middleware.

**Comment by anurse** [comment]
There's not much to change here, I think. It's already been updated to 3.0 content and the samples are still relevant. The most I'd suggest doing is to consider removing examples of `Run` and linking over to the [Routing docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0) for that.

**Comment by m-pollack** [comment]
Where is the repo we can download to see the actual working project?

**Comment by anurse** [comment]
This doc doesn't have a full sample attached, as far as I'm aware. The doc is quite varied in what it describes so there isn't really a single sample app that would illustrate the concepts.

**Comment by m-pollack** [comment]
It is definitely needed. The internet if full of plagiarized articles on this subject without any downloadable example for the current version of core.  Trying to put all the pieces together to make a working solution is very time consuming.
