### ISSUE TITLE
Incorrect: dotnet --info produces output similar to the following...

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore.Docs#14776]
> The .NET Core SDK includes an HTTPS development certificate. The certificate is installed as part of the first-run experience. For example, dotnet --info produces output similar to the following:

At this link https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

I am using .NET Core 3.0.100 ; I run command `dotnet --info`

the result is
```
C:\Users\donhuvy\Desktop\temp_secu>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\donhuvy\Desktop\temp_secu>
```
The document and the reality are different.

(I think post issue is better than comment directly in Feedback text box, because I have more space, can markup content for more clear)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in an ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You must have installed it already. What does `dotnet dev-certs https -c` show?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by donhuvy** [comment]
Oh, I am misunderstanding
![okk](https://user-images.githubusercontent.com/1328316/66103240-5818d180-e5df-11e9-91e2-dee25d1cf434.png)

**Comment by donhuvy** [comment]
> You must have installed it already. What does dotnet dev-certs https -c show?

This is my result
```
Microsoft Windows [Version 10.0.17134.1006]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\donhuvy>dotnet dev-certs https -c
A valid certificate was found.

C:\Users\donhuvy>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\donhuvy>
```

If you have time, please explain for me.

and more, I read https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#all-platforms---certificate-not-trusted

In my PC

```
C:\Users\donhuvy>dotnet devcerts https --clean
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-devcerts does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
![kk](https://user-images.githubusercontent.com/1328316/66103622-91057600-e5e0-11e9-858d-c2791d28af36.png)

I don't understand why it happen.

**Comment by Rick-Anderson** [comment]
Try
`dotnet tool install --global dotnet-dev-certs`

**Comment by Rick-Anderson** [comment]
@javiercn  I have reproduced this error.

Run `dotnet dev-certs https --clean` - cert is removed.
Run `dotnet dev-certs https --trust`

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-devcerts does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

So I had to do this

```
dotnet tool install --global dotnet-dev-certs
dotnet dev-certs https --trust
```

Should I update the instructions?

**Comment by Rick-Anderson** [comment]
@javiercn in my case I have the 1.1, 2.1, 2.2 and 3.0 SDKs installed. WHen I ran `dotnet tool install --global dotnet-dev-certs`
It reported it installed the 2.2 cert.

**Comment by serpent5** [comment]
@donhuvy In your example screenshots, you've missed the `-` in `dev-certs`. The error you show is because `devcerts` isn't a valid command and therefore cannot be found.

**Comment by donhuvy** [comment]
> @donhuvy In your example screenshots, you've missed the `-` in `dev-certs`. The error you show is because `devcerts` isn't a valid command and therefore cannot be found.

![image](https://user-images.githubusercontent.com/1328316/66114145-6fb08400-e5f8-11e9-8190-5ee172feeb1a.png)

@serpent5  you true.
