### ISSUE TITLE
Blazor WebAssembly sample references a previous version of the API tutorial

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14771]
From @juandelacruz23 ...

Blazor docs references [this sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/3.x/BlazorSample), and it says it uses the [API](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi) from the WebApi tutorial. I found some problems running them:

- The new api version uses endpoints called api/TodoItems, while the Blazor sample calls api/Todo
- The web api uses the same port than blazor, and trying to run it crashes at first, should changing it be documented? Along with enabling CORS.
- There are some css files missing.
- A file/class was renamed in the web api, but it's references on Program.cs weren't, so it fails to compile.

I almost solved all of it, it's ok to make a pull request? Or would this be solved by another person? 🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@juandelacruz23 That tutorial+sample over there was just updated to 3.0 recently. This is a great time to update this side of the equation to match. If you'd like to work on it and update it, then we'll add you to the author byline ... sound good? If not, no worries, I'll take care of it as soon as I can get free ... well ... *free-er-ish*! One is never really "free" around here. lol 😅

> The new api version uses endpoints called api/TodoItems, while the Blazor sample calls api/Todo

Very good. Yes, that should match for the best experience.

> The web api uses the same port than blazor, and trying to run it crashes at first, should changing it be documented? Along with enabling CORS.

*Sort-of, kind-of* ok to address that in that this is an ordinary problem covered elsewhere in CORS docs. However, *yes*, it could at least link out to the CORS doc if not actually address this directly WRT the sample app and the web API sample.

> There are some css files missing.

Like what? We don't want CSS files unless we have to have them ... they bloat the docs repo. Which ones are you referring to?

> A file/class was renamed in the web api, but it's references on Program.cs weren't, so it fails to compile.

What's been renamed? If there's an error over there, use the **This Page** feedback form on that topic to let them know if that sample is :boom:. Best to open the issue first for that author (probably Scott) to confer and see what's going on first before taking any action. It could be fixed on another PR or this PR depending on how it plays out.

> I almost solved all of it, it's ok to make a pull request? Or would this be solved by another person? 🤔

Indeed ... the *"other person"* is 🐲 *me!* 🐲 lol ... If you want to fix everything up, we'd be happy to put you on the author byline, which might be useful to you in professional circles.

**Comment by guardrex** [comment]
WRT to the CORS situation ... yes ... the coverage looks good ...

https://docs.microsoft.com/aspnet/core/blazor/call-web-api#cross-origin-resource-sharing-cors

The guidance in the sample app page should probably just say "Host the web API on a different port than 5000/5001. Should also change the `UseMvc` language, since that's changed to endpoint routing.

```html
<p>The Blazor sample app makes a <a href="https://docs.microsoft.com/aspnet/core/security/cors">cross-origin resource sharing (CORS)</a> request from <code>http://localhost:5000</code> or <code>https://localhost:5001</code> to the web API service app. Add the following CORS middleware configuration to the web API's service's <code>Startup.Configure</code> method before it calls <code>UseMvc</code>:</p>

<pre><code>app.UseCors(policy => 
    policy.WithOrigins("http://localhost:5000", "https://localhost:5001")
    .AllowAnyMethod()
    .WithHeaders(HeaderNames.ContentType));</code></pre>

<p>Adjust the domains and ports of <code>WithOrigins</code> as needed for the Blazor app.</p>
```

Someone did a decent job on that one! :smile:

**Comment by juandelacruz23** [comment]
> Which ones are you referring to?

`bootstrap.min.css` and `open-iconic-bootstrap.min.css`. Could it be worth to use a cdn?

Anyway, I'll work on the rest 💪

Finally, is there a standard for PR? 🤔

**Comment by guardrex** [comment]
No, we don't want those CSS files. If you find an unused style in the common Blazor app, 🔪 it out ... or if something really isn't rendering properly, add the style to the *site.css* file. AFAIK, the app looks fine with the styles in the *site.css* file. I'll take another look at it if you spot something not rendering properly. Let me know :ear: ... but generally ... we'll either cut any unused styles or add a style where needed to the file or to the element.

> standard for PR

First line of the opening comment will just be `Fixes #14771` to link it to this issue (and to close this issue when the PR merges).

We have quite a few 😅 style guidelines (e.g., https://docs.microsoft.com/style-guide/welcome/); but for this PR, I doubt that you'll need to look at that. I don't think that there will be many text changes, and I can edit the PR after you submit it.

**Comment by guardrex** [comment]
oh .,... and if you were calling out earlier that there is really a 🐞 in the web API topic, open an issue for that topic from its feedback form and cross-link the issue here. We should get that fixed at the same time or just before this goes in.

**Comment by juandelacruz23** [comment]
@guardrex Right now the app is calling the https version of the api, which has failed in all the browsers I have tested. It seems it's because they reject by default self signed certificates, so you have to open the url in another tab and accept it (or at least that is what I've had to do).
Do you think others might find the same issue? In that case, wouldn't be easier to make the calls through normal http to skip this problem (this would also require to disable HTTPS Redirection 😪)? Or do you think it's something will only happen to me? 😅
Also, changing the ports of the api is just a matter of adding `webBuilder.UseUrls("https://localhost:10000", "http://localhost:10001");` under `ConfigureWebHostDefaults` in Program.cs.
I could add that as an instruction in the tutorial and documentation as with the cors, if you considere it appropiate.

**Comment by guardrex** [comment]
> self signed certificates

Let's *not* get into that. :smile: This is a reference topic. In a tutorial, we might do something like that. However, add https://docs.microsoft.com/aspnet/core/security/enforcing-ssl to the *Additional resources* section of the topic. Add this to that section ("security/enforcing-ssl" is the topic's UID identifier, and it will create the cross-link with the article's title automatically when the doc is built) ...

```
* <xref:security/enforcing-ssl>
```

> make the calls through normal http

Same deal as above. This isn't a problem that this topic needs to address. However, *yes* on a cross-link. Add the following to the *Additional resources* section (for this cross-link, we'll set the title specifically because we want something more specific than just the article's title + we'll put the *Endpoint configuration* section on there as a link bookmark) ...

```
* [Kestrel HTTPS endpoint configuration](xref:fundamentals/servers/kestrel#endpoint-configuration)
```

The CORS is good in this topic tho. CORS, in my experience, is a real dev pain-point :cry:. We get many issues about configuring CORS. Therefore, let's leave those bits here.
