### ISSUE TITLE
Please stop using double negations

### ISSUE THREAD

**Issue by MrRosendahl** [aspnet/AspNetCore.Docs#14784]
The sentence: "[BindProperty] SHOULD NOT be used on models containing properties that SHOULD NOT be changed by the client...".

Explain How [BindProperty] should be used instead of the opposite!
"[BindProperty] SHOULD BE used on models properties that SHOULD BE changeable by the client...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's a security feature. It's not a double negative.
