### ISSUE TITLE
ProblemDetails & Core 3.0

### ISSUE THREAD

**Issue by AllTaken** [aspnet/AspNetCore.Docs#14789]
Where did the ProblemDetails class go in .net Core 3.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
By "where," do you mean via the API browser? Clarify your ask.

It's still there ...

https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.Core/src/ProblemDetails.cs

They might be working on getting that to show up in the API browser ... there might be a slight delay on that. I think they're working on it based on another issue where some API for hosting was missing.

**Comment by scottaddie** [comment]
If you're asking why it doesn't appear in the API browser, the team is still working on publishing 3.0 APIs. The class still exists.

**Comment by AllTaken** [comment]
Yeah, sorry, I don't know what went wrong in my environment.
