### ISSUE TITLE
Error: another version of this product is already installed when installing Visual C++ redistributable

### ISSUE THREAD

**Issue by jawn** [aspnet/AspNetCore.Docs#14790]
When installing Microsoft Visual C++ 2015 redistributable 64 bit on a Windows Server 2016, I get the error
&gt;Another version of this product is already installed

I notice the following versions of the Visual C++ Redistributable are already intalled:

[Screenshot](https://i.imgur.com/M1KcXlQ.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.0&tabs=visual-studio#install-the-net-core-hosting-bundle)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't think that that's a problem. The only time you need to manually install this is if the machine is offline because the hosting bundle installer will install it if it isn't there when the machine has an Internet connection. Either way if it's already there, then it's all good. 👍

**Comment by jawn** [comment]
Thanks for the quick clarification.

**Comment by guardrex** [comment]
Sure thing ... this text should cover this aspect of the scenario ...

> If the system doesn't have an Internet connection, 

... and then we'll deal with the bitness problem on the other issue when we hear back from engineering.
