### ISSUE TITLE
dev-certs command seems to need some other parameter fields or format

### ISSUE THREAD

**Issue by icelava** [aspnet/AspNetCore.Docs#14797]
Testing this on a Ubuntu server 18.04.3; dotnet complains the command or options are not proper or sufficient.

$ dotnet dev-certs https --trust
Specify --help for a list of available options and commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.2&tabs=windows#feedback)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> dotnet complains

Please paste in the full error message.

**Comment by Rick-Anderson** [comment]
You need to install it first
`dotnet tool install --global dotnet-dev-certs`

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/66156804-1d527180-e5be-11e9-8e28-e9e433c32269.png)

**Comment by guardrex** [comment]
I got a bad feel'in about this ........ Windows subsystem for Linux **is not Linux** ... this what that links to ..........

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux

... and the *Enforce HTTPS* topic doesn't call that out otherwise.

**Comment by icelava** [comment]
Yea I think I was looking at Windows instructions when it should've been Linux (Ubuntu).
