### ISSUE TITLE
TypeScript SignalR tutorial references outdated npm package

### ISSUE THREAD

**Issue by ericl85** [aspnet/AspNetCore.Docs#14794]
Just a heads up that the TypeScript SignalR tutorial still references @aspnet/signalr instead of @microsoft/signalr.

That package still amazingly works with SignalR 3.0, but there are some differences that confused me until I found this:

https://github.com/aspnet/Announcements/issues/372

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
> That package still amazingly works with SignalR 3.0

:+1:
SignalR tries to make the server backwards compatible with older clients while adding new features that new clients can take advantage of.

**Comment by wadepickett** [comment]
fixed with PR #16835
