### ISSUE TITLE
Missing information about dependency

### ISSUE THREAD

**Issue by patrickhacens** [aspnet/AspNetCore.Docs#14792]
There have been a bit of changes on blazor client-side apis and as of 3.0 it seems to be required to include Microsoft.Aspnetcore.Components.Authorization package as a dependency through nuget but it is not clearly defined on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio-code#authentication)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @patrickhacens ... Currently, we only cover it for `[Authorize] attribute`, and I think it's a great idea to go thru the topic and clarify the package requirements in the hosting model scenarios. If Blazor Server gets it, I'll call that out. If Blazor WebAssembly needs it, I'll call that out.
