### ISSUE TITLE
Missing class MultipartRequestHelper

### ISSUE THREAD

**Issue by lichasu** [aspnet/AspNetCore.Docs#14796]
@sergiodesousafilho commented on [Thu Oct 03 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/118)

Hello, the class "MultipartRequestHelper" is not implemented or builtin.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Uploads de arquivos no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Thu Oct 03 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/118#issuecomment-537945387)

Hello, @sergiodesousafilho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.

Thanks!

**Comment by guardrex** [comment]
@lichasu Open these using the feedback form on the English topic :point_right: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads

**Comment by guardrex** [comment]
It is implemented ... see the sample app :point_right: https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Utilities/MultipartRequestHelper.cs

**Comment by guardrex** [comment]
Actually ... *YES!* ... let's call that out in the text. I'll add that to the 3.0 updates on https://github.com/aspnet/AspNetCore.Docs/pull/14770.

**Comment by guardrex** [comment]
Thanks @lichasu and @sergiodesousafilho ... that update will go in when #14770 merges. :rocket:
