### ISSUE TITLE
CSHTML Code snippet

### ISSUE THREAD

**Issue by matfricker** [aspnet/AspNetCore.Docs#14810]
Section I refer too:

- **Replace the content in Pages\Index.cshtml with the following code:**

Second line from bottom script tag pointing to **signalr.js** is incorrect according to **Target Location** set up when **Client-Side Library** was added earlier in tutorial. Should point to: _js/signalr/dist/browser/signalr.js_

Script tag currently points to: 
`<script src="~/lib/signalr/dist/browser/signalr.js"></script>`

Potentially should point to: 
`<script src="~/js/signalr/dist/browser/signalr.js"></script>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@BrennanConroy  @bradygaster  please review
