### ISSUE TITLE
Clearer Instructions for Migrating from .NET Core 2.2 to 3.0 (Contained Within)

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/AspNetCore.Docs#14817]
Please can the instructions for migrating .NET Core 2.2 to 3.0 be made clearer as this article contains a mixture of instructions, release notes and demos. Compared to the migration guide for .NET Core 2.1 > 2.2 it says it takes 4 times as long to read. All this document should contain are the steps required to migrate with the other information contained within other/further information pages.

By comparing a blank .NET Core 2.2 and 3.0 project I was able to work out the migration steps which are below in case anyone else finds them useful:

**1. Copy Existing Project**
Before starting it is best to take a backup of the existing .NET Core 2.2 project as sometimes when switching frameworks this would fail and cause most C# commands not to be recognised so only option was to take another copy and try again.

**2. Delete Existing Published Files**
Navigate to the project directory where the solution file is located and then into the sub-folder containing the project files.
Delete the following folders (renaming does not work as folders are still picked up and still lead to the error):
- bin
- obj

**3. Update the csproj file**
Navigate to the project directory where the solution file is located and then into the sub-folder containing the project files. Edit the .csproj file.

Find the reference to the target framework:
```
<TargetFramework>netcoreapp2.2</TargetFramework>
```

Replace with:
```
<TargetFramework>netcoreapp3.0</TargetFramework>
```

Find the reference to the hosting model. If this is set to InProcess this section can be removed as this is now the default:
```
<PropertyGroup>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
</PropertyGroup>
```

Find and remove this line as this package is now split up into seperate packages to avoid duplication and ensure projects remain lean and efficient:
```
<PackageReference Include="Microsoft.AspNetCore.App" />
```

Also remove references to AspNetCore.Razor.Design:
```
<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
```

Remove any item groups relating to bundleconfig.json as this is no longer used.

Add the following packages so the section should now look like this (aside from any additional packages:
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0" />
</ItemGroup>
```

**4. Update Startup.cs**
Open Startup.cs from within Visual Studio.

Find the Startup function definition at the top:
```
public Startup(IConfiguration configuration, IHostingEnvironment env)
```

Replace it with
```
public Startup(IConfiguration configuration, IWebHostEnvironment env)
```

Below find the following:
```
public IHostingEnvironment HostingEnvironment { get; }
```

Replace with:
```
public IWebHostEnvironment HostingEnvironment { get; }
```

Find the following in the ConfigureServices section:
```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

Replace with (compatibility version is no longer required):
```
services.AddRazorPages();
```

Now move to the Configure section:
Find the function definition:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
```

Replace with:
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
```

Find:
```
app.UseCookiePolicy();
app.UseAuthentication();
app.UseMvc();
```

Replace with:
```
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
});
```

Also ensure the using command has been added at the top for Microsoft.Extensions.Hosting:
```
using Microsoft.Extensions.Hosting;
```

**5. Update Program.cs**
Open Program.cs from within Visual Studio.

Find the following in the Main function at the top:
```
CreateWebHostBuilder(args).Build().Run();
```

Replace with:
```
CreateHostBuilder(args).Build().Run();
```

Find the following in the function below:
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
```

Replace with:
```
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.ConfigureKestrel(serverOptions =>
        {
            // Set properties and call methods on options
        })
```

If present find and remove:
```
.ConfigureKestrel((context, options) =>
{
    // Set properties and call methods on options
});
```

Also ensure the using command has been added at the top for Microsoft.Extensions.Hosting:
```
using Microsoft.Extensions.Hosting;
```

**6. Build, Publish and Deploy**
You should now be able to build, publish and deploy your project. The destination folder does now contain around 26 files whereas with .NET Core 2.2 it was around 9. A new runtimes folder is also now created.
If this fails try opening a CMD window and navigate to the project directory and run:
```
dotnet build
```

If you get the following error:
```
Assets file '...\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. 
Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project.
```

Then go to Project Folder\Properties\PublishProfiles.

Edit `FolderProfile.pubxml` and look for
```
<TargetFramework>netcoreapp2.2</TargetFramework>
```

Replace with:
```
<TargetFramework>netcoreapp3.0</TargetFramework>
```

For me this seems to randomly switch itself back in this file when according to the Publish section in VS it says target framework is netcoreapp3.0 and may have just published minutes earlier.

The project should now work or if not you may need to follow the additional steps below:

**6. Additional Migration Steps Depending on Code**

**JsonIgnore using Newtonsoft.Json**
If you have used `[JsonIgnore]` on any of your class attributes to avoid circular references when generating Json this no longer works and is now has no effect.

The fix is to find instances of this:
```
using Newtonsoft.Json;
```

And replace with:
```
using System.Text.Json;
using System.Text.Json.Serialization;
```

Then it works again

**Stored Procedures**
If you are calling stored procedures or executing SQL statements directly from code then you need to update the function that calls these as the name has changed:

In .NET Core 2.2 this works:
```
var surnameParam = new SqlParameter("@Surname", SqlDbType.NVarChar);
surnameParam.Value = (object)surname ?? DBNull.Value;

ObjectFromDB = await _context.ObjectFromDB 
    .FromSql("EXEC SPR_StoredProcedure @Surname", surnameParam)
    .ToListAsync();
```

In .NET Core 3.0 you must do this instead:
```
ObjectFromDB = await _context.ObjectFromDB
    .FromSqlInterpolated( $"EXEC SPR_StoredProcedure @Surname={surname}")
    .ToListAsync();
```

**EF Core Queries**
EF Core queries are now forced to execute on the server and not the client until after the entries have been converted to objects using `ToListAsync()`. This means anything that would have historically forced client-side execution now generates an error so this is now much more restrictive (in an attempt to always generate efficient SQL). Sometimes this may be a case of removing a `.ToString()` command or other times (for more complex statements) it may be easier to re-write as a stored procedure and execute that instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by StanislavPrusac** [comment]
Than you! <3
