### ISSUE TITLE
PMC not working

### ISSUE THREAD

**Issue by s-fukuzawaa** [aspnet/AspNetCore.Docs#14826]
Hi.
I've gotten to the step of "Add-Migration" in Package Manager Console and I got the following error.

PM&gt; Add-Migration InitialCreate
Add-Migration : The term 'Add-Migration' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Add-Migration InitialCreate
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], Comma 
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

I have followed the exact same steps the tutorial requires, and even checked if I had the required entity framework package.
Here are the packages I have installed.
1. Microsoft.EntityFrameworkCore.SqlServer 3.0.0
2. Microsoft.EntityFrameworkCore.Tools 3.0.0

Are there anymore packages to install?
I have tried reinstalling and it still doesn't work.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try [Add NuGet packages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)

Run the following .NET Core CLI commands:
```
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```

**Comment by s-fukuzawaa** [comment]
Still not working...

PM> Add-Migration InitialCreate
Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Add-Migration InitialCreate
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Rick-Anderson** [comment]
Did you miss the step
`Install-Package Microsoft.EntityFrameworkCore.SqlServer`

**Comment by s-fukuzawaa** [comment]
No I didn't.

**Comment by s-fukuzawaa** [comment]
Is there any other way to do the same step by hardcoding.

**Comment by Rick-Anderson** [comment]
Use the VSC/MAC tab instructions

**Comment by vpoteryaev** [comment]
If I initially didn't place the solution and project in the same directory, I get the same errors.
Seems PMC refers to the solution's directory and can't find the project.
Just launch the CMD and go to the project's directory, then 'dotnet ef migrations add ...' works fine.
Same with adding packages and so on.

**Comment by Kairen-Vaze** [comment]
"Add-Migration InitialCreate" is not enough. You have specify which dbContext you gonna use by using -Context. For ex, my dbContext have 2, 1 from tutorial named MvcContext, 1 from myself is Kairen_MoviesContext. I want to use my Kairen_MoviesContext, so here is the code: 

Add-Migration InitialCreate -Context Kairen_Movies.Data.Kairen_MoviesContext

"Kairen_Movies.Data": is the namespace in your dbContext
"Kairen_MoviesContext": is the name of class of my dbContext

If you want to know more, you can copy your error message to Youtube to know more information :3

**Comment by Rick-Anderson** [comment]
> You have specify which dbContext you gonna use by using 

You should only have one for this tutorial.
