### ISSUE TITLE
Not able to get user information in Api Controller

### ISSUE THREAD

**Issue by caihongxu** [aspnet/AspNetCore.Docs#14827]
Hi I tried to follow this document to create a SPA that talks to server API. In the API controller I try to get the current logged in user information via
var user = await _userManager.GetUserAsync(User);
But I get null with this method. What is the proper way to get the user information from server or is it not part of the bearer token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by caihongxu** [comment]
OK solved this by adding the follow line in Startup.cs

            services.Configure<IdentityOptions>(options =>
            {
                options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier;
            });

I think the identityserver sets UserIdClaimType to "sub" which messed things us. Somewhere in the code base needs to be fixed for this to work automatically.

I will leave this open until someone helps to address this in general so that this hack is no longer needed. Thanks.

**Comment by blowdart** [comment]
Please open an issue in the [aspnet core](https://github.com/aspnet/AspNetCore/issues/) repo for actual code issues.

**Comment by javiercn** [comment]
You can't use the user manager APIs to retrieve user information directly in your APIs. The user you see inside your API is the result of validating and deserializing the access token sent by the SPA to the app, which is different from the user that Identity expects (which is serialized into the Identity cookie).

This is also something that you shouldn't do in your API. The access token is the piece of data that represents the credentials for the call, and you should key your decisions on information that comes from the token, and not try to get to the underlying authentication mechanism.

**Comment by javiercn** [comment]
Closing as this is not something we plan to support.

**Comment by caihongxu** [comment]
Just so to clarify, the user id does exist in the token directly, just identity server override the options.ClaimsIdentity.UserIdClaimType configurations which resulted in that user manager cannot parse and get it correctly. And I still feel getting user id from access token is the proper thing to do. There is no identity cookie involved here as the OIDC protocol we are using is based on authorization header as I understand.

Please advise on other alternatives of getting user identities if any. Thank you.

**Comment by javiercn** [comment]
The Claims principal in the controller action was not produced by Identity and so UserManager does not know how to work with it. You can choose to tweak how the ClaimsPrincipal gets produced to make it work with Identity, but afaik, UserManager only works with ClaimsPrincipal instances produced by Identity and does not guarantee working with other ClaimsPrincipals. Is that fair @blowdart?

@caihongxu Could you provide more detail on what you are trying to do with the user you retrieved? You are coupling your app code to your auth code, which is not something we recommend, as it will prevent you in the future from changing the auth implementation without a high cost.

**Comment by blowdart** [comment]
Again, please open an issue in the core repo for this. It's not a docs issue.
