### ISSUE TITLE
The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/AspNetCore.Docs#14824]
I can't work out how to migrate stored procedure calls in .NET 3.0.

First I need to replace:
```
FromSql(
```
With
```
FromSqlRaw(
```

But then none of the nullable SqlParameters work - e.g.:
```
var reportTypeParam = new SqlParameter("@ReportType", SqlDbType.NVarChar);
reportTypeParam.Value = (object)reportType ?? DBNull.Value;
```

Error is:
```
InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.
```

All the articles I can find about this relate to old versions of the .NET Framework so are not really helping me to work out what to do. It seems to just be an issue with optional parameters but I need to keep them as optional as they do not have to be specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by robinwilson16** [comment]
Ok I have now worked this out but didn't find it documented anywhere

In .NET Core 2.2 this works:
```
var surnameParam = new SqlParameter("@Surname", SqlDbType.NVarChar);
surnameParam.Value = (object)surname ?? DBNull.Value;

ObjectFromDB = await _context.ObjectFromDB 
    .FromSql("EXEC SPR_StoredProcedure @Surname", surnameParam)
    .ToListAsync();
```

In .NET Core 3.0 you must do this instead:
```
ObjectFromDB = await _context.ObjectFromDB
    .FromSqlInterpolated( $"EXEC SPR_StoredProcedure @Surname={surname}")
    .ToListAsync();
```

Now it works in .NET Core 3 without the error and code is simpler.

Robin

**Comment by Rick-Anderson** [comment]
@tdykstra  can you suggest where this info should go?

**Comment by tdykstra** [comment]
In the EF repo, maybe here: https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md
