### ISSUE TITLE
States Visual Studio is available on Linux.

### ISSUE THREAD

**Issue by Romans-I-XVI** [aspnet/AspNetCore.Docs#14820]
Is this a typo and you meant to write Visual Studio Code?
"Stay productive with Visual Studio on Windows, Linux, and macOS"

Or... foreshadowing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
VSC is a flavor of VS and marketed SxS with VS IDE. It's not a typo, and it isn't foreshadowing anything.

https://visualstudio.microsoft.com/
