### ISSUE TITLE
Breaking changes REQUIRE bold text stating that this is a breaking change!

### ISSUE THREAD

**Issue by Kaelum** [aspnet/AspNetCore.Docs#14828]
There are SEVERAL breaking changes with this release, and not 1 of then is labeled as such.  For example, the “AllowSynchronousIO disabled” change with break all existing projects across the board, and should be labeled as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Just mentioning in passing ... not as an answer to your suggestion @Kaelum ... there are **47** announcements. The topic cross-links to them ...

* https://docs.microsoft.com/aspnet/core/migration/22-to-30#breaking-api-changes
* https://github.com/aspnet/Announcements/issues?page=2&q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22+label%3A3.0.0

I think every dev should study them when upgrading to see what applies to their scenarios.

WRT marking them here in some way, I defer to management.

**Comment by Rick-Anderson** [comment]
@Kaelum duplicating information is problematic. #14828 makes breaking changes more obvious.
