### ISSUE TITLE
3.01update:  Filter methods for Razor Pages in ASP.NET Core

### ISSUE THREAD

**Issue by DragonMastery** [aspnet/AspNetCore.Docs#14831]
This convention is outdated

```
services.AddMvc(options =>
{
options.Filters.Add(new SamplePageFilter(_logger));
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by cheesemacfly** [comment]
I think we now have to use `AddControllers` or `AddControllersWithViews` to get the same behavior: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#mvc-service-registration.

So the example becomes:
``` csharp
services.AddControllers(options =>
{
    options.Filters.Add(new SamplePageFilter(_logger));
});
```

**Comment by Rick-Anderson** [comment]
@cheesemacfly  for RP use `AddRazorPages`

**Comment by cheesemacfly** [comment]
I tried and it doesn't work for me. I have a filter like this:

``` csharp
    internal sealed class SecurityHeadersFilter : ResultFilterAttribute
    {
        public override void OnResultExecuting(ResultExecutingContext context)
        {
            // basically adds CSP headers
        }
    }
```

And then in the startup.cs this doesn't work (the filter is never triggered):

``` csharp
            services.AddRazorPages()
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.ConfigureFilter(new SecurityHeadersFilter());
                });
```

but this works:

```csharp
            services.AddControllersWithViews(options =>
            {
                options.Filters.Add(new SecurityHeadersFilter());
            });
```

Am I missing something? I'm using 3.0 not 3.1 if it matters.

**Comment by RichMercer** [comment]
I could do this these docs being updated too. It's not clear to me how we're supposed to pass services into global filters now with the startup changes in 3.0. For example, the _logger passed into the filter can no longer be done in that way.

**Comment by Rick-Anderson** [comment]
@Tratcher  the 2.x sample injects the logger in `Startup`. But showing how to write filters for logging is probably a bad idea  - we should recommend customer use the built in loggers and not write filters that do logging.

For the 3.1 update I plan on removing all the logging and just show RP filters. Please comment.

**Comment by Tratcher** [comment]
The question of how to use services in a filter or convention is legitimate. @rynowak ?

@Rick-Anderson You're right that we need to remove logger from the samples.

**Comment by Rick-Anderson** [comment]
@Tratcher  I believe @rynowak  responded previously See [this comment](https://github.com/aspnet/AspNetCore/issues/17868#issuecomment-565608080)

**Comment by rynowak** [comment]
`TypeFilterAttribute` and `ServiceFilterAttribute` are already docced, but we might want some more pages examples with these.
