### ISSUE TITLE
Why force VSCode users to use SQLite?

### ISSUE THREAD

**Issue by LarnuUK** [aspnet/AspNetCore.Docs#14841]
VSCode is available on Windows, and SQL server runs on Dockers and Linux? Why does the documentation not explain how to connect to a local (or remote) SQL Server instance using VSCode? I don't want to use SQLite, and the documentation here is trying to force me to use something else (which isn't even a MS product). The Visual Studio Documentation is useless for trying to implement to VSCode, meaning I have to figure it out myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@LarnuUK  thanks for the comment. We document ASP.NET Core, not SQL. It's just a matter of changing the connection string.

**Comment by Rick-Anderson** [comment]
If you're on Windows, why not LocalDB?

**Comment by LarnuUK** [comment]
I'm not on Windows, hence my comment about Docker and Linux. I know how to use SQL, but I'm brand new to ASP.Core, and, unfortunately, the document gives me no details on how to connect to SQL Server. That isn't a SQL issue, that's a problem with the Document. I know very well how to use SQL Server; I specifically don't want to learn a different RDBMS and why this document confuses me.
