### ISSUE TITLE
in-process-hosting - ASP.NET Core module

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14846]
The "in-process-hosting" illustration shows the ASP.NET Core Module, but in the explanation below it is missing. 
Better incorporate ASP.NET Core Module in this section: 

       _A request arrives from the web to the kernel-mode HTTP.sys driver...._, 

so we can learn how it interacts with the rest.

Because here : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-3.0, I read:

_HTTP.sys isn't compatible with the ASP.NET Core Module and can't be used with IIS or IIS Express._

How do Http.sys and ASP.NET Core Module cooperate, if at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0#hosting-models)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
Actually only change:

> The module receives the native request and passes it to IIS HTTP Server (IISHttpServer).

to
The **ASP.NET Core module** receives the native request and passes it to IIS HTTP Server (IISHttpServer).

And perhaps a little clarification: Is http.sys is a kernel mode driver and in other places I read it's a webserver. Question: Are both the same or different?

**Comment by guardrex** [comment]
HTTP.sys is both a server implementation in ASP.NET Core ([HttpSysServer](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/HttpSys)) and a kernel-mode driver in Windows that distributes HTTP traffic to processes.

My idea for this coverage is to mention HTTP.sys driver as little as possible in the IIS doc and concentrate the language and the images on ANCM/IIS.

Over in the HTTP.sys topic, you won't see much (probably any really) distinction between HTTP.sys the driver and HTTP.sys the server implementation ([HttpSysServer](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/HttpSys)).

Hopefully, the simplifications aren't confusing. I'll keep an :ear: open on this one for more feedback. If more peeps say that the driver remark is a problem here, then perhaps we can remove/revise it.

For now, I'm going to specify the module in two spots in the topic.
