### ISSUE TITLE
Highlight this section

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14851]
I would put this in an attention box, like "Note":

> This article covers the Web Host, which remains available only for backward compatibility. The Generic Host is recommended for all app types.

like this box, don't know if you use different colors for different attentions:

![image](https://user-images.githubusercontent.com/966368/66261385-99220900-e7cc-11e9-985d-6d1fa3a8f18e.png)

And perhaps tell the user to switch to `GenericHost` section when using ASP.NET Core v3.0 <
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Legends ...

> tell the user to switch to GenericHost section when using ASP.NET Core v3.0

The web host is really *still here*. Even in the new world of the Generic Host, the web host (`IWebHostBuilder`) is built and several aspects of this topic still apply (e.g., web host configuration). I don't agree with the direction that was taken, but I'm just little green dino in a big MS world. :smile: This is the direction that they decided to go.

WRT changing to a NOTE, I don't think that would make a big difference ... and kind'a make things worse given what I was just saying. Devs shouldn't avoid the guidance in this topic today, and it's probably not good to push them away from it any more than it currently does.

**Comment by Legends** [comment]
> which remains available only for backward compatibility.
> The Generic Host is recommended for all app types.

hm, this doesn't sound to me, I should be using it in v3.0 anymore.
If it is not deprecated and it doesn't looks (no comments in code), then I would remove these sentences, imo. It's irritating.

So without reading the "Web Host" section (skipped it, because of this sentences above) are there some infos we cannot find in section "Generic Host", but is included here in "Web Host"?
Of course, if Web Host is still valid, then it doesn't make sense to highlight the sentences above, but rather remove them.

Soemthing doesn't make sense here...

**Comment by guardrex** [comment]
I agree with your confusion ... I find it confusing, too. I'd have gone a different way with it. This is what they wrote/approved, so this is what we have today. They'll keep an :ear: open for additional feedback. If enough devs say that they're confused by the coverage, I suspect they'll make changes.

**Comment by Legends** [comment]
hm, ok. Thanks for your feedback.
