### ISSUE TITLE
NuGet package required for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by wforney** [aspnet/AspNetCore.Docs#14855]
May want to update the docs to include installing the NuGet package for the different providers... It assumes that you had it already and those who don't know where to look will have a hard time if they only land here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by samnaseri** [comment]
Yup, it took me 3 minutes to figure it out that I need to add Microsoft.AspNetCore.Authentication.Google package where as the whole article is supposed to be read in 3 minutes :))

**Comment by Rick-Anderson** [comment]
@samnaseri  sorry about that :)

**Comment by wadepickett** [comment]
Moved this one up to be included in this week's workload.  Thanks @wforney and @samnaseri.  Sorry for the bad experience.

**Comment by wadepickett** [comment]
Updating and testing for 3.0, including overview topic that includes the starter project.
Will keep the 2.2 version in.
