### ISSUE TITLE
Host Configuration example

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14850]
```
Host.CreateDefaultBuilder(args)
    .ConfigureHostConfiguration(configHost =&gt;
    {
        configHost.SetBasePath(Directory.GetCurrentDirectory());
        configHost.AddJsonFile("hostsettings.json", optional: true);
        configHost.AddEnvironmentVariables(prefix: "PREFIX_");
        configHost.AddCommandLine(args);
    });
```

When I access `configHost ` it shows me the following options:

![image](https://user-images.githubusercontent.com/966368/66261008-9ae8ce00-e7c6-11e9-82e0-a75ffac99e97.png)

Where are all these methods from the example like `AddJsonFile` etc. ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#host-configuration)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Add ...

```
using Microsoft.Extensions.Configuration;
```

... I'll put it into the example.
