### ISSUE TITLE
can't find HttpContext.SignInAsync 

### ISSUE THREAD

**Issue by samnaseri** [aspnet/AspNetCore.Docs#14860]
I can't find the method  SignInAsync on HttpContext. Probably it is an extension method. But where that extension method is defined? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's shown in the topic in several spots and in the sample app ...

```csharp
using Microsoft.AspNetCore.Authentication;
```

**Comment by guardrex** [comment]
https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.signinasync

They're still working on the 3.0 API.

**Comment by bdcoder2** [comment]
Same issue here - .Net Core 3.0 project, Error shows:

using Microsoft.AspNetCore.Authentication;

But error displayed is:

'HttpContext' does not contain a definition for 'SignInAsync'

**Comment by Rick-Anderson** [comment]
> -- does this mean "SignInAsync" is unavailable under 3.0?
No, it means https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.signinasync doc pages is not updated for 3.0
