### ISSUE TITLE
ef commands getting "ScriptHalted" error

### ISSUE THREAD

**Issue by marydeshon** [aspnet/AspNetCore.Docs#14863]
When I run Add-Migration InitialCreate I get "ScriptHalted" error in the the PMC.

Tried to find a solution but nothing seems to work.
Any suggestions are welcome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fmir864** [comment]
Same issue occurred on my Win 7 x86 machine running VS 2019 16.3.4 and .NET Core 3 SDK. Following post had the answer;

https://developercommunity.visualstudio.com/content/problem/753703/package-manager-console-scripthalted.html

Bottom line is need to update Powershell to version 5.1 to work with Core 3 Entity Framework.

```
The problem is the version of powershell.

powershell on win7 is 2.0,and PM is base on powershell. So, after I upgrade my powershell version to 5.1 it work out.
```

**Comment by Rick-Anderson** [comment]
@fmir864  thanks for the update. Not many are on Win7. This issue is very discoverable.

**Comment by marydeshon** [comment]
Upgrading to Powershell 5.1 fixed the problem for me as well. Thank you!!
One side note that may help others is that I had Powershell 2.0 and when I tried to install 5.1 the install silently "stalled" around 50%.
I discovered that I needed to update to Powershell 4 and then upgrade to 5.1.
