### ISSUE TITLE
Error in Code Example

### ISSUE THREAD

**Issue by Walad100100** [aspnet/AspNetCore.Docs#14864]
The following code example:

&lt;input value="@CurrentValue"
    @onchange="@((ChangeEventArgs __e) =&gt; CurrentValue = __e.Value)" /&gt;

Generates an error unless I typecast __e.Value by (bool), i.e., 

CurrentValue = (bool) __e.Value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't think that it's an "error" in that sense that it was just an abbreviated example for the `@bind` equivalent **_for a textbox_** shown in the lead-in sentence. It's not meant for you to actually use that code in a component, nor does it currently apply to the checkbox example `italicsCheck`. I think that example should be based on the prior example (`italicsCheck`). Thanks for commenting.
