### ISSUE TITLE
Guidance on how to re-write EF .NET Core Queries

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/AspNetCore.Docs#14862]
Is it possible to get some guidance on how to re-write EF .NET Core Queries as whatever I do I cannot seem to get any that are not just a straigtforward ```.ToListAsync()``` ones to execute.

Here is one that works fine in .NET Core 2.2:
```
AuditTrail = await _context.AuditTrail
                .Include(a => a.ApplicationUserUpdatedBy)
                .Where(a => a.TableName.ToString() == tableName && a.ChangeType == 4 && a.ApplicationUserUpdatedBy.UserName == user)
                .GroupBy(a => a.ObjectID)
                .Select(a => a.FirstOrDefault())
                .OrderByDescending(a => a.UpdatedDate)
                .Take(30)
                .ToListAsync();
```

According to https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/ I must call ```AsEnumerable()``` as only the last part of the query can be executed on the client but I can only get the query above to work by commenting out everything from the Where to the Take command and if I use ```AsEnumerable()``` then I get other errors and ```ToListAsync()``` is then not valid.
The example given on that page does not include an example where ```ToListAsync()``` is used.

Thanks
Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by robinwilson16** [comment]
Ok this sort of works (if I put brackets around the server part) but it is producing the wrong answer presumably because of the order of execution:
```
AuditTrail = (await _context.AuditTrail
                .Include(a => a.ApplicationUserUpdatedBy)
                .Where(a => a.TableName == tableName && a.ChangeType == 4 && a.ApplicationUserUpdatedBy.UserName == user)
                .ToListAsync())
                .GroupBy(a => a.ObjectID)
                .Select(a => a.FirstOrDefault())
                .OrderByDescending(a => a.UpdatedDate)
                .Take(30)
                .ToList();
```

What this does is return the 30 most recent customers the user has amended or viewed.
Whilst this now compiles and runs it is no longer doing this for some reason.

**Comment by Rick-Anderson** [comment]
Can you open an issue in https://github.com/aspnet/EntityFramework.Docs ?

**Comment by robinwilson16** [comment]
Thanks, I have ended up re-writing them all as stored procedures which I think is better for debugging too as lots of them had issues so everything is working now (well aside from some other migration issues I still need to work out resolutions for).
