### ISSUE TITLE
"Roaming" is missing from the Secrets path.

### ISSUE THREAD

**Issue by billgatesfan** [aspnet/AspNetCore.Docs#14877]
I believe there is a very small error in the article : at "https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets#how-the-secret-manager-tool-works",  you said that path is "%APPDATA%\Microsoft\UserSecrets\&lt;user_secrets_id&gt;\secrets.json". 

I believe the Roaming folder is missing, so that would be "AppData\Roaming\Microsoft\UserSecrets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.0&tabs=windows#how-the-secret-manager-tool-works)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
`%APPDATA%` is the variable name for `C:\Users\{USER}\AppData\Roaming`.
