### ISSUE TITLE
Incorrect DbContext initialization syntax

### ISSUE THREAD

**Issue by jamie-tillman** [aspnet/AspNetCore.Docs#14883]
This tutorial dead-ends at the DbContext configuration code.

This line:
```
services.AddDbContext<TodoContext>(opt =>
               opt.UseInMemoryDatabase("TodoList"));
```
Results in this error:
`Cannot convert lambda expression to type 'ServiceLifetime' because it is not a delegate type`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jamie-tillman** [comment]
Nope.  It's there.  If it were missing, the error would be:
```
'dbContextOptionsBuilder' not contain a definition for 'UseInMemoryDatabase'
```

**Comment by guardrex** [comment]
Best bet until Rick can take a look ... compare your app to the sample and see if there's a delta somewhere ...

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi

**Comment by jamie-tillman** [comment]
Coder error.  I had provided the model where the specific context should have been provided instead.

**Comment by thebluess** [comment]
I having the same problem here but cant fix it
