### ISSUE TITLE
fix code

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#14889]
@sercocn commented on [Fri Oct 04 2019](https://github.com/aspnet/AspNetCore.Docs.zh-tw/issues/114)

&lt;input value="@CurrentValue"
    @onchange="@((ChangeEventArgs __e) =&gt; CurrentValue = __e.Value)" /&gt;

not compile success
add "as string" compile success

&lt;input value="@CurrentValue"
    @onchange="@((ChangeEventArgs __e) =&gt; CurrentValue = __e.Value as string)" /&gt;

and 

CurrentValue not defined in this document

@code {
    public string CurrentValue{ get; set; }
}

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [建立和使用 ASP.NET Core Razor 元件](https://docs.microsoft.com/zh-tw/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sat Oct 05 2019](https://github.com/aspnet/AspNetCore.Docs.zh-tw/issues/114#issuecomment-538611777)

Hello, @sercocn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I move this here because the user is making suggestions to the code
best

**Comment by guardrex** [comment]
Hello @CeciAc and @sercocn ...

The updates are already in the works on https://github.com/aspnet/AspNetCore.Docs/pull/14868.

This is a dup of https://github.com/aspnet/AspNetCore.Docs/issues/14864.
