### ISSUE TITLE
This page should be versioned as Certificate Forwarding is new middleware available starting in .net core 3.0

### ISSUE THREAD

**Issue by samf1596** [aspnet/AspNetCore.Docs#14887]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher I didn't get wind of cert forwarding. Can you point me to some engineering details or let me know what I should add?

**Comment by Tratcher** [comment]
It's already in the doc, but it needs to be restricted to the 3.0 version.
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md#certificate-forwarding

**Comment by guardrex** [comment]
Gotcha ... thanks.
