### ISSUE TITLE
Document control of event propagation and default actions

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#14884]
[EDIT by guardrex to add the *Components* topic metadata]

This ships in 3.1 preview 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#cookies)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@SteveSandersonMS @danroth27 Should engineering take this one, or can you point me to an engineering issue that will explain it out such that I can this?

**Comment by danroth27** [comment]
@guardrex See https://github.com/aspnet/AspNetCore/pull/14509

**Comment by guardrex** [comment]
The second link makes a lot more sense to me than the first. I might be able to get that in here. I'll leave it up to you if you want me to give a go. Otherwise, I'll handle the grammar+style bits as usual.

**Comment by danroth27** [comment]
I will also be doing a write up on this for the announcement blog post. If you want you could just wait for that and I can get you an early draft of the content.

**Comment by guardrex** [comment]
In that case, I'll self-assign and stand-by for your post.

**Comment by guardrex** [comment]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-2/
