### ISSUE TITLE
using statements in samples

### ISSUE THREAD

**Issue by steveoh** [aspnet/AspNetCore.Docs#14899]
do you think we could get the using statements required for the samples to run?

I'm not sure what namespace the `ReadAsAsync` extension method is in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@steveoh  have you looked in https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/http-requests/samples/3.x ?
We usually don't add includes in advanced tutorials.
Are you using Visual Studio?

**Comment by scottaddie** [comment]
@steveoh In ASP.NET Core 3.0 projects, you'll need to install the [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/) NuGet package. This assembly was included in the shared framework (`Microsoft.AspNetCore.App`) in 2.x, so there was no need to install it separately.

**Comment by steveoh** [comment]
@Rick-Anderson no I did not see that folder. Is that linked to in the samples or is that something I should be able to find by convention?

I am using vscode right now.

@scottaddie thanks for the nuget package link and explaination.

Do you think it is a good idea to use items outside of the shared framework in the samples? I don't have an opinion really, but I figured it is a good question.

**Comment by scottaddie** [comment]
> Do you think it is a good idea to use items outside of the shared framework in the samples? I don't have an opinion really, but I figured it is a good question.

@steveoh In most apps, you will use components that aren't provided in the ASP.NET Core shared framework. Common examples of such components include Entity Framework Core, Json.NET, and social auth APIs (Twitter, Facebook, etc.).

**Comment by Rick-Anderson** [comment]
@steveoh  see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies
