### ISSUE TITLE
Asp-route parameters in core 3.0 / Razor Pages

### ISSUE THREAD

**Issue by mrAshpool** [aspnet/AspNetCore.Docs#14911]
In 2.2 an anchor would automatically include any route parameters, if the source had that property, and the destination contained the @page "{ParamName}"

i.e.
`<a asp-page="/Test/Index">Test</a>` could be rendered as 
`<a href="xx/Test/Index/ParamValue">Test</a>`
despite not including asp-route-ParamName

After migrating to 3.0 I need to explicitly include any route details in the tag helper

If I disable Endpoint Routing in 3.0, the anchor helper works as it did in 2.2

Is this the intended behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-3.0#)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@rynowak  Do you want a repo of this 3.0 routing problem?

**Comment by Rick-Anderson** [comment]
@mrAshpool  thanks for reporting this. Moved to https://github.com/aspnet/AspNetCore/issues/14869

They might want the simplest possible repo.
