### ISSUE TITLE
Delete response code is not correct

### ISSUE THREAD

**Issue by cremor** [aspnet/AspNetCore.Docs#14914]
The shown `DeleteTodoItem()` method for ASP.NET Core 3.0 returns the deleted entity, but after the code block there is the following text:

> The DeleteTodoItem response is 204 (No Content).

This doesn't match.

For versions other than 3.0 it is correct, but not for the code that is shown if you choose 3.0.

I think returning `NoContent()` is the "better" way, so in theory the shown code should be updated. But since this code has to match the code that is actually created by the scaffoling process, this would also be "wrong".

Related:
https://github.com/aspnet/AspNetCore.Docs/issues/10274#issuecomment-504578212
aspnet/Scaffolding#983
aspnet/AspNetCore#8855

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by RickAndMSFT** [comment]
@Rick-Anderson

**Comment by rajeev26** [comment]
I was confused with the same. Why would the response return the deleted entity if it has been deleted?
