### ISSUE TITLE
Which file to edit?

### ISSUE THREAD

**Issue by Structed** [aspnet/AspNetCore.Docs#14910]
In the section [Out-of-process hosting model|https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#out-of-process-hosting-model], you mention to edit some XML, specifically

```xml
&lt;PropertyGroup&gt;
  &lt;AspNetCoreHostingModel&gt;OutOfProcess&lt;/AspNetCoreHostingModel&gt;
&lt;/PropertyGroup&gt;
```

I assume, this goes to the `csproj` file. However, there is no note on where to do this. This problem occurs on several occasions through the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#out-of-process-hosting-model)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, that's correct ... the project file.

I'll run through it today and make sure that's clear. Thanks for commenting.

**Comment by guardrex** [comment]
Not every instance shown that's in XML goes in the project file. Some of those are for *web.config* and there's one I see for a publish profile.

I'll get them carefully called out sometime today.

**Comment by Structed** [comment]
Thanks for the quick fix!
