### ISSUE TITLE
Incorrect information for  <aspnetcore21

### ISSUE THREAD

**Issue by GeorgeAlexandria** [aspnet/AspNetCore.Docs#14912]
The section #add-a-controller describe how to add a new controller for `<.aspnetcore21` (in the issue scope younger versions are not interested), it just use `ApiControllerAttribute` to decorate controller that allow controller responds to web API requests. Besides, `ApiControllerAttribute` was introduced at `aspnetcore21` (https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.aspnetcore.mvc.apicontrollerattribute?view=aspnetcore-2.2#applies-to) and it cannot be used in [`.aspnetcore10`;`.aspnetcore20`], so this describes is incorrect for `<.aspnetcore21`.

If I miss something, please let me know about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.0&tabs=visual-studio#add-a-controller)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@GeorgeAlexandria  thanks for the feedback. We should probably remove the version selector for 1..0 to 2.0 since we don't support those versions.

cc @scottaddie
