### ISSUE TITLE
Sample app - unnecessary #regions

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14913]
Why use regions for multiple lines or even one line of code?
It decreases readability and makes here no sense anyway.

```
 public static class LoggerExtensions
    {
        #region snippet1
        private static readonly Action&lt;ILogger, Exception&gt; _indexPageRequested;
        #endregion

        #region snippet2
        private static readonly Action&lt;ILogger, string, Exception&gt; _quoteAdded;
        #endregion

        #region snippet3
        private static readonly Action&lt;ILogger, string, int, Exception&gt; _quoteDeleted;
        private static readonly Action&lt;ILogger, int, Exception&gt; _quoteDeleteFailed;
        #endregion

        #region snippet4
        private static Func&lt;ILogger, int, IDisposable&gt; _allQuotesDeletedScope;
        #endregion
...
..
.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e02614-5cdd-0c85-3193-75a2325326b4
* Version Independent ID: fca176e2-c56e-0f17-de1b-e60912091e4b
* Content: [High-performance logging with LoggerMessage in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/logging/loggermessage.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/loggermessage.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
The regions are used by the .md files to pull in code to display in the documentation pages. For example, the following is taken from the page in question:

```
 [!code-csharp[](loggermessage/samples/3.x/LoggerMessageSample/Internal/LoggerExtensions.cs?name=snippet1)]
```

At the end of that line, you'll see a reference to `snippet1`. This allows the .md files to reference a section of code by a name rather than line-numbers, which is a bit more flexible.

**Comment by Legends** [comment]
hm, ok. I will close it, I guess you currently don't have a better solution at hand.
From your point of view it makes sense, actually perfect, but when reading the code from a readers view it's a bit nasty to read.

**Comment by guardrex** [comment]
The way to do it without ranges is to use a query string "range" of code (by line number).

```
[!code-csharp[](path/file.cs?range=10-20)]
```

Downside: If the line numbers change (*and they will*), the code block breaks (shows the wrong lines). This approach requires too much maintenance, so we don't use it very much. It's a bit of a holdover in old docs, and we try to refactor it when an old doc is overhauled.

btw - You may also see those snippets in markup. For example ...

```html
<p>blah</p>
<!-- <snippet_MySnippet> -->
<p>Shown in the doc.</p>
<!-- </snippet_MySnippet> -->
<p>blah</p>
```

```
[!code-csharp[](path/file.html?name=snippet_MySnippet)]
```

**Comment by serpent5** [comment]
FYI, this is described in the docs: https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.0#regions-in-sample-code.

**Comment by guardrex** [comment]
Thanks @serpent5 ... and I'll patch that `WebHost` example for 3.0.

**Comment by guardrex** [comment]
Nevermind ... already scheduled for work. https://github.com/aspnet/AspNetCore.Docs/issues/12958
