### ISSUE TITLE
ASP.NET Core 2.2 version requires the loggerFactory.AddAzureWebAppDiagnostics() in Startup.cs (even though obsolete)

### ISSUE THREAD

**Issue by MHarrison22** [aspnet/AspNetCore.Docs#14924]
Title says it all, I had no luck getting the logging working in the Azure App Service log stream, VS Professional 2019 signals the loggerFactory.AddAzureWebAppDiagnostics(); is obsolete, however I couldn't get it working without adding it, luckily by following this recent S/O post: https://stackoverflow.com/questions/58269169/microsoft-extensions-logging-azureappservices-not-showing-up-in-azure-log-stream

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
ping @glennc

**Comment by Rick-Anderson** [comment]
@MHarrison22  is this still a problem in 3.1?
