### ISSUE TITLE
CreateDefaultBuilder & ConfigureWebHost/ConfigureWebHostDefaults are broken

### ISSUE THREAD

**Issue by Kaelum** [aspnet/AspNetCore.Docs#14928]
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =&gt;
    {
        webBuilder.UseStartup&lt;**Startup**&gt;();
    });

The above code is being using in multiple places, but it fails if the **StartUp** class constructor contains anything other than "IConfiguration configuration".  If you don't use the "Host.CreateDefaultBuilder()", and instead start with a WebHostBuilder object, everything works as expected.  I am using the following constructor:

public Startup(ILogger&lt;Startup&gt; logger, IConfiguration configuration)
{
	Logger = logger;
	Configuration = configuration;
}

Which works perfectly when starting with a WebHostBuilder object, but fails with the following exception when starting with the HostBuilder objects:

System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[Webroot.Bcap.WebApi.Startup]' while attempting to activate 'Webroot.Bcap.WebApi.Startup'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's correct. That's the new 3.0 behavior. See :point_right: https://github.com/aspnet/Announcements/issues/353.

Inject your logger directly into `Startup.Configure` ...

https://docs.microsoft.com/aspnet/core/fundamentals/logging/#create-logs-in-the-startup-class

If you need it in `Startup.ConfigureServices`, call `GetRequiredService` for an instance ...

```csharp
var logger = services.GetRequiredService<ILogger<Program>>();
```

**Comment by Kaelum** [comment]
For those who see this after the issue was closed, here is a link to the thread where they try to defend this change, but fail miserably:

[[Announcement] Generic Host restricts Startup constructor injection](https://github.com/aspnet/AspNetCore/issues/9337)

If you are using NLog, you can use the following line as a work-around for this ridiculous issue:

			Logger = LogManager.GetCurrentClassLogger();
