### ISSUE TITLE
Chinese version copy error

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#14927]
The comment below was machine trasnlated

@yomunsam commented on [Tue Oct 08 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/201)

"The name of the component must begin with an uppercase character. For example, MyCoolComponent is valid and MyCoolComponent is invalid."

The second "MyCoolComponent" in the English version is "myCoolComponent"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [创建和使用 ASP.NET Core Razor 组件](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components?view=aspnetcore-3.0#component-classes)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Tue Oct 08 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/201#issuecomment-539632326)

Hello, @yomunsam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Please, disregard this issue

**Comment by guardrex** [comment]
@CeciAc If there's another way that we can word that to make it translate better (if that's the problem), let me know. I'm not married to that exact expression if it doesn't translate into Chinese well.

**Comment by CeciAc** [comment]
Hi @guardrex 
no problem, I though so at first but it looks like it can easily be fixed at our end
I just sent it to the linguist :)

**Comment by guardrex** [comment]
ok cool ... thx @CeciAc ... hit me up if they suggest a better way to say that.
