### ISSUE TITLE
Duplicate Heading + content

### ISSUE THREAD

**Issue by Tobolov** [aspnet/AspNetCore.Docs#14938]
The heading 'The Dockerfile' along with its content is repeated twice (In succession).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tobolov  thanks for bringing this to our attention. Fix should be  visible in a few minutes.
