### ISSUE TITLE
Provide Blazer tutorial example scenes.

### ISSUE THREAD

**Issue by xCyborg** [aspnet/AspNetCore.Docs#14933]
In this page there are a couple of starter Blazor example but there is no complete file code or the whole example, so this would be a nice addition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It was done on purpose due to high churn in engineering. This whole topic is due for an overhaul, so we won't be providing such a sample at this time.

**Comment by ciphercoder** [comment]
Hi,
Can't we have screenshots of what we are building.. as this would help the prospective user to more actively comprehend what the final product will look like...

**Comment by guardrex** [comment]
@ciphercoder We can't at this time. This tutorial is subject to being completely replaced. Given the workload, there's no way that we can get all of the images into it only having to replace them in a few months. Later tho ... when we get a new tutorial in place ... *Yes!* ... I hope to have screenshots in the new tutorial.
