### ISSUE TITLE
Setting Up SQL Server tables instead of SQLLite for the new .net core SPA Auth example

### ISSUE THREAD

**Issue by owlyowl** [aspnet/AspNetCore.Docs#14941]
**Help us make content visible**
I googled around for .net core react authentication jwt and came across: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback

It's a super handy starter but when actually looking in to implementing and running up the test project I'd love to know if there's a quick way to have the CreateIdentitySchema in Migrations use sql server or examples of boostrapping different databases with aspnet users, roles etc

I think it would be helpful to have more of an explanation of the new security around basic auth roles, users etc

**Comment by Rick-Anderson** [comment]
@owlyowl  Sorry but we don't have such a sample.
