### ISSUE TITLE
No Razor Class Library in Visual Studio

### ISSUE THREAD

**Issue by datvm** [aspnet/AspNetCore.Docs#14946]
I chose "ASP.NET Core Web Application" as project type, named the project but in the list there is no Class Library (ASP.NET Core 3.0 is selected):

![](https://i.imgur.com/EWQhRWZ.png)

There is also a project type named "Razor Class Library" but it creates a Blazor library. I am having latest VS 16.4 Preview 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by datvm** [comment]
I think I have found it. It's hidden here:

![image](https://user-images.githubusercontent.com/6388546/66496388-0b545f80-eae5-11e9-9120-6864a4e1028c.png)

So the content is no longer correct. I needed to pick Razor Class Library project type (not ASP.NET Core Web Application) and need to check the box on the above screenshot.

**Comment by timheuer** [comment]
Good catch -- the actual walk through of this is also here: https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
@wadepickett this should be quick to fix. I put it next in https://github.com/aspnet/AspNetCore.Docs/projects/49?card_filter_query=assignee%3Awadepickett

**Comment by wadepickett** [comment]
Thanks!

**Comment by Rick-Anderson** [comment]
@wadepickett can get to this by tomorrow?

**Comment by wadepickett** [comment]
On this now.  I had to finish other doc work first I had already picked up.  Thanks for assigning to me.
