### ISSUE TITLE
Scaffold Movie Pages

### ISSUE THREAD

**Issue by Energised** [aspnet/AspNetCore.Docs#14947]
Under the code example for Visual Studio Code, the dotnet command is missing a dash. The command should be:

`dotnet-aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not correct. Try
`dotnet aspnet-codegenerator --help`

**Comment by darthestar** [comment]
I had this problem running that command: Scaffolding failed.
Could not find project file in MyFiles/File/ProjectName. Took me hours to get it to work .... 
I am using VS for Mac
what worked for me was added a   -p YourProjectName   right in between codegenerator and controller

**Comment by Aditha-Sansa** [comment]
He's correct. I had an execution error while running:
`dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries` 
I'm using VS for Mac with .net core 3.1.1 and the right way should be:
`dotnet-aspnet-codegenerator` 
and if you installed code generator with `dotnet tool install --global dotnet-aspnet-codegenerator` a guide is shown in terminal saying you can invoke the tool using `dotnet-aspnet-codegenerator`

**Comment by xouaib** [comment]
Please help:
BTW, im using ubuntu 18.04 with .netcore sdk 3.1.302, i always get this error i dont how to deal with it :+1: 

```
dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
A file matching the name MvcControllerWithContext.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.40
```
