### ISSUE TITLE
CertificateAuthenticationDefaults.AuthenticationScheme

### ISSUE THREAD

**Issue by yshahin** [aspnet/AspNetCore.Docs#14949]
I can't find this "CertificateAuthenticationDefaults.AuthenticationScheme" anywhere.
It is not part of Microsoft.AspNetCore.Authentication and there is no reference in the documentation on how to access it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
Like all the other option classes it's in the name space for the auth type;

https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Certificate/src/CertificateAuthenticationOptions.cs

```c#
namespace Microsoft.AspNetCore.Authentication.Certificate
{
    public class CertificateAuthenticationOptions : AuthenticationSchemeOptions
    ....
}
```

**Comment by guardrex** [comment]
@yshahin There's a delay on getting that namespace (a 3.0 scenario) into the [API docs](https://docs.microsoft.com/dotnet/api/). I think that they're working on it, but I haven't heard an ETA.

**Comment by Rick-Anderson** [comment]
If we get more hits on this, we'll add it to the doc. Hopefully it will be easy to figure out once the 3.0 API docs are published.
