### ISSUE TITLE
Add BEFORELocationChanged event to NavigationManager?

### ISSUE THREAD

**Issue by CtrlAltNoot** [aspnet/AspNetCore.Docs#14945]
I would VERY much find it useful to have the ability to catch navigation BEFORE it happens to be able to fire off things like validation. For example, I have a page with over 100 fields, and I want to be able to fire off Service.ChangeTracker.HasChanges() from EF Core, but if I do it in the LocationChanged event nothing actually comes of it since the page changes before that event is fired.

**Comment by Rick-Anderson** [comment]
@CtrlAltNoot  you might want to request that in the EF repo.
