### ISSUE TITLE
This page doesn't render correctly using Microsoft Edge

### ISSUE THREAD

**Issue by wildough57** [aspnet/AspNetCore.Docs#14942]
This page doesn't render correctly using Microsoft Edge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532d66a6-fa01-54d3-1dfa-20d1889668bb
* Version Independent ID: 6489c522-2148-e39a-92cc-6f631c065422
* Content: [Get started with the Data Protection APIs in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/security/data-protection/using-data-protection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/using-data-protection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wildough57 ... open this over at :point_right: https://github.com/MicrosoftDocs/feedback/issues

**Comment by wildough57** [comment]
I took the time to give you the Feedback your organization asked for.  If your webshite routed me to the wrong place, why TF do I need to fix that?On Oct 9, 2019 10:59 AM, Luke Latham <notifications@github.com> wrote:Hello @wildough57 ... open this over at 👉 https://github.com/MicrosoftDocs/feedback/issues

**Comment by guardrex** [comment]
I understand your frustration, but we're very compartmentalized here. That's a whole different group of cats with their own repo. We redirect readers all the time here. Engineering problems go to the engineering repo ... doc build system problems go to the docs engineers ... Azure problems to Azure repo ... you get the picture. We don't work on the build system here ... just the docs content.

Anyway ... I opened the topic in Edge, and I don't see anything wrong ...

<img width="309" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/66498170-4625ab80-ea83-11e9-9a98-9414819c485d.PNG">

What are you seeing there? I'll open the issue over there if you provide a screenshot and/or description of what's breaking.

**Comment by wildough57** [comment]
Hi Luke,
I can see that compartmentalization every day and you do have my sympathy.  If the word "organization" can be applied at all, it is of the Byzantine variety.  I see discussions where the participants are so anxious to point the finger at another group and close the threads that even the internal participants get annoyed.
I clicked the page feedback button.  If that goes to the wrong place I am sorry for you as the person who's getting dumped on . . . but it's also on you guys to fix it.  If the routing is incorrect, fix it.  If there needs to be someone in the organization to triage and redirect the feedback to the appropriate group, sounds like a management issue to me.  Please feel free to forward this to your management. 
When I view that page, there is no text (code) in the areas with the light yellow background.
Attached is a screen capture using Snip.
I'd tell you what version of Edge I'm using but the convention of having Help -> About seems to be outta style.
Do what you will with this information.  
It's time for me to go back to trying to work around the fact that there is ABSOLUTELY zero cohesion among Entity Framework Core, Asp.Net Core and SQL Server when it comes to encryption. 
Cheers,Will
 
    On ‎Wednesday‎, ‎October‎ ‎9‎, ‎2019‎ ‎11‎:‎59‎:‎50‎ ‎AM‎ ‎EDT, Luke Latham <notifications@github.com> wrote:  
 
 
I understand your frustration, but we're very compartmentalized here. That's a whole different group of cats with their own repo. We redirect readers all the time here. Engineering problems go to the engineering repo ... doc build system problems go to the docs engineers ... Azure problems to Azure repo ... you get the picture. We don't work on the build system here ... just the docs content.

Anyway ... I opened the topic in Edge, and I don't see anything wrong ...



What are you seeing there? I'll open the issue over there if you provide a screenshot and/or description of what's breaking.

**Comment by guardrex** [comment]
I didn't get the snip, but no worries ... I'll just open it and tell them that the yellow line highlighting isn't working in Edge and cross-link back to this issue. If they end up requiring a screenshot, they'll ping u here.

........ and yes, indeed on the version ... they may ask you later about your Edge version ... btw ... that's under **Settings** > **General** at the very bottom of the panel.

**Comment by wildough57** [comment]
Sending the screen shot again.  Filename is Capture.PNG (very original).
Also trying simple paste.








    On ‎Wednesday‎, ‎October‎ ‎9‎, ‎2019‎ ‎01‎:‎09‎:‎55‎ ‎PM‎ ‎EDT, Luke Latham <notifications@github.com> wrote:  
 
 
I didn't get the snip, but no worries ... I'll just open it and tell them that the yellow line highlighting isn't working in Edge and cross-link back to this issue. If they end up requiring a screenshot, they'll ping u here.

........ and yes, indeed on the version ... they may ask you later about your Edge version ... btw ... that's under Settings > General at the very bottom of the panel.

**Comment by guardrex** [comment]
Try dragging the image file into the GH comment box.

**Comment by guardrex** [comment]
Opened at https://github.com/MicrosoftDocs/feedback/issues/2016 for investigation.

**Comment by Rick-Anderson** [comment]
@ wildough57  can you supply an image of what's not rendering correctly?

**Comment by Rick-Anderson** [comment]
@wildough57 you can reply from email with a screen shot, you need to select the GitHub link at the bottom of the email and paste the screen shot here.

We've spent alot of time reviewing your complaint be we can't find a problem.

**Comment by mairaw** [comment]
I think you meant they **can't** reply via e-mail with attachments.

**Comment by wildough57** [comment]
Yeah, already tried that several times.  Besides, all that you would see is what I've already described.
Seems that my issue is only when viewing the page remotely using RDP.
It appears to be systemic because I've subsequently experienced the same thing on other pages.
Not an issue with Chrome or IE 11.  Also, sometimes I'll switch to a different window and then come back to Edge and I can see the text.
I'm calling it an Edge problem but maybe you guys should be aware. Sorry for the inconvenience.
Will
    On Wednesday, October 9, 2019, 07:04:21 PM EDT, Rick Anderson <notifications@github.com> wrote:  
 
 
@wildough57 you can reply from email with a screen shot, you need to select the GitHub link at the bottom of the email and paste the screen shot here.

We've spent alot of time reviewing your complaint be we can't find a problem.

**Comment by Rick-Anderson** [comment]
@wildough57  you keep replying by email, you need to post the image here.
