### ISSUE TITLE
gRPC label

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14959]
Do we want a `gPRC` label for issues like we have for `SignalR`?

We could have a bot apply it for all gRPC docs.

cc @scottaddie  @BrennanConroy @JamesNK @JunTaoLuo

**Comment by scottaddie** [comment]
It's really easy. I'll take care of it today.

**Comment by scottaddie** [comment]
All gRPC issues can be found at: https://github.com/aspnet/AspNetCore.Docs/issues?utf8=✓&q=is%3Aissue+sort%3Aupdated-desc+label%3AgRPC+
