### ISSUE TITLE
opt.UseInMemoryDatabase("TodoList") does not exist

### ISSUE THREAD

**Issue by davinakano** [aspnet/AspNetCore.Docs#14952]
Hi there :wave: ! Beginner here, trying to follow the tutorial.

In "Register The Database Context" section, the method "UseInMemoryDatabase" does not seem to exist / can't be resolved. Did the method change, by any chance?

Ref https://docs.microsoft.com/en-ca/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#register-the-database-context

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#register-the-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by kmkivist** [comment]
Addition to Microsoft.EntityFrameworkCore.SqlServer you also need to install Microsoft.EntityFrameworkCore.InMemory Nuget package. It's missing in tutorial.

**Comment by davinakano** [comment]
Thank you so much @kmkivist ! That made the trick. Hopefully that will be added to the tutorial!

**Comment by Rick-Anderson** [comment]
That's in the instructions

Use the preceding instructions to add the `Microsoft.EntityFrameworkCore.InMemory` NuGet package.

**Comment by davinakano** [comment]
@Rick-Anderson 

Thank you for the reply! You are correct, it is in the instructions for Visual Studio Code.

However, it is missing from Visual Studio 2019 instructions. Is the recommended way to use Visual Studio Code instead?

**Comment by Rick-Anderson** [comment]
It's not missing,
Use the preceding instructions to add the `Microsoft.EntityFrameworkCore.InMemory` NuGet package.

**Comment by davinakano** [comment]
Oh, that's correct. My bad, I missed that line. Thank you for taking the care and sorry for that!
