### ISSUE TITLE
The ASP.NET Core Azure API App Service Deployment

### ISSUE THREAD

**Issue by maheshsabnis** [aspnet/AspNetCore.Docs#14968]
I was trying to deploy ASP.NET Core 3.0 Application as Azure API App Service. Surprisingly I faced following error 

---
![ASPNET-Core_30_Publish_Issue](https://user-images.githubusercontent.com/5309850/66540464-83547100-eb49-11e9-94df-2aa774f27ecd.PNG)

Even after trying the extension for ASP.NET Core 3.0, there was no luck. Finally I dockerized it in local environment to demonstration. Hope this will be resolved asap.

Regards
Mahesh Sabnis

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The 3.0 rollout in Azure is in progress. Keep an eye on https://aspnetcoreon.azurewebsites.net/.

**Comment by maheshsabnis** [comment]
Hi,
  I am using VS 2019 with latest update. I am trying to create ASP.NET Core 3.0 API application. Although I am trying to create it and deploy it on Azure API App, but still the VS2019 shown following waring 
![image](https://user-images.githubusercontent.com/5309850/67382889-d8619f80-f5ab-11e9-8245-0206c8b21508.png)

I really do  not understand why is it show where the deployment is successful?
