### ISSUE TITLE
This does not seem to work for my project.

### ISSUE THREAD

**Issue by mikedcooper** [aspnet/AspNetCore.Docs#14960]
I Added
services.AddControllersWithViews().AddRazorRuntimeCompilation();
and added the nuget package.

I am using Core 3.0 in an asp.net mvc application while trialling a Blazor component.
If I change a class on an element in a cshtml file, save and refresh the page in the browser nothing changes.  If I pause the application, make the change, then run the application I see the message applying changes in the lower left... then I get the error box stating that I need to edit or stop the application due to the changes.  A little slow to see minor changes to the view :)  Any help would be great.  Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #14800
