### ISSUE TITLE
Is it possible to push a streaming from server to client through IHubContext?

### ISSUE THREAD

**Issue by ccic** [aspnet/AspNetCore.Docs#14969]
If I want to implement the scenario of sending streaming from one client to another client, how can I do this?

One client sends streaming to server, and server forward the streaming to another client.  Can I use Clients.Client(connectionId).SendAsync(ChannelReader&lt;&gt;); to send the streaming? I found it does not work for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Currently this is possible to handle yourself in a single server scenario. Take a look at [this sample](https://github.com/SignalR/sample-StreamR) to see how we forward streams.

There is an [issue filed](https://github.com/aspnet/AspNetCore/issues/10151) for sending streams to specific clients. Closing this as we have that tracking issue.
