### ISSUE TITLE
How to build / get TestServer from WebApplicationFactory<Startup>?

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14962]
In 2.2, we can construct TestServer from WebApplicationFactory this way:
```
public class CustomWebAppFactory : WebApplicationFactory<Startup>
{
    IWebHostBuilder webHostBuilder = new WebHostBuilder();
    ConfigureWebHost(webHostBuilder);
    TestServer = new TestServer(webHostBuilder);
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    { ... }
}
```
Since WebHostBuilder is going to be deprecated, how to build the TestServer in 3.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@javiercn  please respond

**Comment by javiercn** [comment]
There is a `factory.TestServer` property you can use, that hasn't changed.

**Comment by khteh** [comment]
I mean the services added into the DI for use by the TestServer. I remeber I used the `TestServer` from `WebApplicationFactory` but lack of the services required and that's how I ended up `new TestServer(webHostBuilder)` and used that.

**Comment by javiercn** [comment]
`(TestServer)factory.Services.GetRequiredService<IServer>()`
