### ISSUE TITLE
ReadToEndAsync Snippet is wrong

### ISSUE THREAD

**Issue by eddynaka** [aspnet/AspNetCore.Docs#14979]
The code in snippet 2 is missing a line to read the streamReader

**Comment by guardrex** [comment]
@Rick-Anderson I mapped it to you given that you'll do the approval of the PR.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by guardrex** [comment]
@eddynaka Note that these close automatically when they're linked to the PR with `Fixes {ISSUE NUMBER}` syntax on the PR.
