### ISSUE TITLE
Inaccurate description of GoodStreamReaderController example

### ISSUE THREAD

**Issue by idg10** [aspnet/AspNetCore.Docs#14981]
In the *performance-and-reliability* section, there's an example preceded by this description:

&gt; "The following example uses ReadToEndAsync and does not block the thread while reading."

But the example appears not to do this. In fact it calls `JsonSerializer.DeserializeAsync`. As far as I can tell from the source, it doesn't use `ReadToEndAsync`.

(The warning that it reads the whole request in is true, but it does that by reading it into an object. It doesn't first load it into a string.)

Maybe consider 3 examples? The existing 'bad' example, its exact async equivalent (which would do what the description says - essentially just replace the `ReadToEnd` with `ReadToEndAsync`) and then the example you actually have, which avoids duplicating the data into a string before deserializing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@halter73  @jkotalik please review

**Comment by halter73** [comment]
I don't see what the issue is.

> > "The following example uses ReadToEndAsync and does not block the thread while reading."
> 
> But the example appears not to do this. In fact it calls `JsonSerializer.DeserializeAsync`. As far as I can tell from the source, it doesn't use `ReadToEndAsync`.

I'm pretty sure it does. The sample immediately after the sentence "The following example uses ReadToEndAsync and does not block the thread while reading." does indeed call ReadToEndAsync().

> (The warning that it reads the whole request in is true, but it does that by reading it into an object. It doesn't first load it into a string.)

This statement is accurate, but the doc never says the body is first loaded into a string, so there's no contradiction.

> Maybe consider 3 examples? The existing 'bad' example, its exact async equivalent (which would do what the description says - essentially just replace the `ReadToEnd` with `ReadToEndAsync`) and then the example you actually have, which avoids duplicating the data into a string before deserializing it.

I must be missing something. Isn't this exactly what we have?

**Comment by davidfowl** [comment]
@idg10 we added a 3rd sample so this is now moot. It was fixed earlier today.
