### ISSUE TITLE
no solution file

### ISSUE THREAD

**Issue by daveyostcom** [aspnet/AspNetCore.Docs#14992]
On Mac, following the instructions, I did
```
dotnet new grpc -o GrpcGreeter
cd GrpcGreeter
```
This page then says:
- From Visual Studio, select File &gt; Open, and then select the GrpcGreeter.sln file.

but there is not *.sln file anywhere in the GrpcGreeter folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
It should say to select the project file (.csproj). Thanks for reporting this.
