### ISSUE TITLE
Error on scaffolding API controller: No parameterless constructor defined for type

### ISSUE THREAD

**Issue by Jogge** [aspnet/AspNetCore.Docs#15007]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#scaffold-a-controller

This part does not work. I had to create a parameterless constructor and add this inside the dbContext:

```
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFProviders.InMemory;Trusted_Connection=True;ConnectRetryCount=0");
            }
        }
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#scaffold-a-controller)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Jogge** [comment]
> The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

You're right. The tutorial works. I tried reproduce the error and found that i somehow changed the following code in Program.cs from:
`public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)...`
to
`public static IHostBuilder CreateHostBuilder() => Host.CreateDefaultBuilder()...`
