### ISSUE TITLE
Models/SeedData.cs(13,38): error CS0246: The type or namespace name 'MvcMovieContext' could not be found (are you missing a using directive or an assembly reference?) [/home/peter/Desktop/MvcMovie/MvcMovie.csproj]

### ISSUE THREAD

**Issue by Peter-ComCo** [aspnet/AspNetCore.Docs#15004]
If you are getting this error you need to add using MvcMovie.Data; in SeedData.cs class 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Peter-ComCo  thanks for bringing this to our attention.
