### ISSUE TITLE
app_offline.htm[l]

### ISSUE THREAD

**Issue by spanevin** [aspnet/AspNetCore.Docs#15001]
&gt; Use PowerShell to drop app_offline.html (requires PowerShell 5 or later):

Why do we need to drop app_offline.html when we created app_offline.htm ?

Does it support both app_offline.htm and app_offline.html?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @spanevin ... I think that's just a typo. I'll check and get back to you.

**Comment by guardrex** [comment]
Yep ... just a typo. Thanks for letting us know.

*.htm* = :smile:
*.html* = :cry:
