### ISSUE TITLE
Azure AD Authentication and long requests headers

### ISSUE THREAD

**Issue by MaximeMarck** [aspnet/AspNetCore.Docs#15009]
I experienced an issue on my asp.net core site hosted on Azure App Service when accessed behind an NGinx Proxy. 

I got a 502 Bad Gateway error when trying to authenticate using Azure AD. After a few days of research I opened a ticket on the AspNet Core project (https://github.com/aspnet/AspNetCore/issues/14725) and in the end the issue was that the request headers were > 4Kb and NGINX was rejecting those requests (NGINX Default Config).

I saw there is a section regarding this: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.0#long-request-header-fields but I thought maybe it would be good to mention that this limit can easily be reached when using Azure AD Authentication. In fact I don't embed a lot of claims in the token and I do not include the security groups (which can increase the size of the cookie by a lot), so I guess this is some pretty standard setup.

In my case a note about 502 Bad Gateway errors being related to authentication cookies in Azure AD could have saved me at least a week of debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @MaximeMarck ... That's a great idea.
