### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by DaveEmmerson** [aspnet/AspNetCore.Docs#15008]
"Look for a mistakes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @DaveEmmerson ... I'll fix that right up.
