### ISSUE TITLE
Comment about Server-side Rendering and Left as User Exercise misleading

### ISSUE THREAD

**Issue by pkellner** [aspnet/AspNetCore.Docs#15012]
Since server-side rendering was a part of the previous to asp.net core 3.0 templates, I understand why there is an important mention of it here:

> Server-side rendering" is not a supported feature of this template. Our goal with this template is to meet parity with "create-react-app". As such, scenarios and features not included in a "create-react-app" project (such as SSR) are not supported and are left as an exercise for the user.

However, "left as an exercise for the user" would lead the reader to think they somehow may be able to reasonably modify the template to do server-side rendering.  To convert create-react-app to do server-side rendering is a bad idea and was never expected from the create-react-app creators (so why would we expect readers to be able to do it).

Notes from create-react-app here:  https://github.com/facebook/create-react-app#popular-alternatives

* If you want to do **server rendering** with React and Node.js, check out [Next.js](https://github.com/zeit/next.js/) or [Razzle](https://github.com/jaredpalmer/razzle). Create React App is agnostic of the backend, and only produces static HTML/JS/CSS bundles.

My suggestion is just state the facts and make it clear that these templates are not meant to support server-side rendering and if you want to do that you need to decouple react from core and create a very different solution.  Templates are not for you.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS please review

**Comment by SteveSandersonMS** [comment]
@Rick-Anderson Not 100% sure what you're asking me to review - is there some particular rephrasing you have in mind for the docs?

Overall I do agree with @pkellner's point. It is not realistic to imagine that most developers will find it easy to set up some SSR solution with these templates. It would be better not to talk about it at all than to imply it's something you can do in a straightforward way.
