### ISSUE TITLE
Updated resources needed

### ISSUE THREAD

**Issue by marcslevesque** [aspnet/AspNetCore.Docs#15018]
Your "Additional resources" links point to documents which state they are no longer being updated.  Any documentation about valid transformation syntax I can find does not include "InsertIfMissing", which appears above in an example.  Where can updated information be found which includes seemingly new attributes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c703c55-7ece-6e0d-2518-50786599530a
* Version Independent ID: 7e68f62c-8c84-e7a5-2a74-201fc60b3036
* Content: [Transform web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/transform-webconfig.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/transform-webconfig.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @marcslevesque ... I'll take a look and respond back this weekend.

**Comment by guardrex** [comment]
@vijayrkn I don't see anything else we can link for transform syntax besides what we currently have ...

* [Web.config Transformation Syntax for Web Application Project Deployment](https://go.microsoft.com/fwlink/?LinkId=301874)
* [Web.config Transformation Syntax for Web Project Deployment Using Visual Studio](https://docs.microsoft.com/previous-versions/aspnet/dd465326(v=vs.110))

Leave these? Remove these? Open an issue somewhere (some docs repo) that we need new syntax coverage?

`Insert` is covered in the old docs (and `InsertIfMissing` is fairly obvious from the naming), but I don't see `InsertIfMissing` covered in a spot that we can use here. It appears in ...

* https://devblogs.microsoft.com/nuget/how-to-use-nugets-xdt-feature-examples-and-facts/
* A few examples in unrelated material.
* A few forum comments in unrelated material.

**Comment by guardrex** [comment]
ping @vijayrkn :point_up: I don't think this is actionable because AFAICT there's nothing else that we can link for transformation syntax.

**Comment by guardrex** [comment]
@shirhatti TL;DR the ask is that our transform syntax *web.config* cross-links are to content that isn't maintained any longer. I don't see anything else that we can link to. Our options seem to be ...

* Do nothing. Keep the links.
* Strip the links out and not provide coverage.
* Create new topics somewhere (IIS docs or here) for transform syntax.

How would u like to proceed?

**Comment by vijayrkn** [comment]
I think at this point the best course of action is to do nothing and keep the links. 

(Sorry for my late response.)

**Comment by guardrex** [comment]
Thanks @vijayrkn.

@marcslevesque ... We'll keep the links (at least for now) and keep an :ear: open for more developer concerns about this.

**Comment by marcslevesque** [comment]
Thanks for looking into it.
