### ISSUE TITLE
VSCode and VSMac specific information needs to be separated from VS2019 information 

### ISSUE THREAD

**Issue by c0g1t8** [aspnet/AspNetCore.Docs#15025]
Under https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio#initial-migration, references made to instructions specific to dotnet CLI. 

The text regarding the expected error should be more prominent.

**Comment by Rick-Anderson** [comment]
Mac supports .NET CLI
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by c0g1t8** [comment]
@Rick-Anderson - I didn't realize that was the workflow. I will follow it in the future.

**Comment by Rick-Anderson** [comment]
NP
