### ISSUE TITLE
Kestrel On Azure AppServer

### ISSUE THREAD

**Issue by fahrettinozturk** [aspnet/AspNetCore.Docs#15035]
Is it possible to bypass IIS on Azure App Server to reach directly to the Kestrel from the client? It looks IIS is always acting as a reverse proxy server even if you set-up the Kestrel properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
No there is no way to do that.

**Comment by guardrex** [comment]
For that scenario, try an Azure VM with the required ports open in the NSG and VM firewall.
