### ISSUE TITLE
ReadAsASync

### ISSUE THREAD

**Issue by taylorchasewhite** [aspnet/AspNetCore.Docs#15046]
I don't believe the examples for ReadAsASync anymore? I could be wrong but I'm seeing that HttpContent does not have a ReadAsASync function, only ReadAsStringAsync, ReadAsByteAsync, ReadAsStreamAsync and they aren't generic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
FYI, `ReadAsAsync` is provided by the [`Microsoft.AspNet.WebApi.Client` NuGet package](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/). This was provided by the `Microsoft.AspNetCore.App` metapackage before 3.0, but needs to be added as a `PackageReference` from 3.0 onwards.

**Comment by adisazhar123** [comment]
You can make use of the new json serializer from microsoft. The code using `ReadAsAsync` would then be refactored as:
       ``` 
using (var contentStream = await response.Content.ReadAsStreamAsync())
        {
            PullRequests = await JsonSerializer.DeserializeAsync<IEnumerable<GitHubPullRequest>>(contentStream);
        }
```
https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=netcore-3.0
