### ISSUE TITLE
The "Special case formatters" description looks like something wrong

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs#15045]
https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#special-case-formatters

When removing the `TextOutputFormatter`, it won't return `406 Not Acceptable`. It'll use 
`StringOutputFormatter` instead. I'm using ASP.NET Core 2.2. 

If I remove the `StringOutputFormatter`, it'll use `JsonOutputFormatter` instead.

Would you check the content for this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2#special-case-formatters)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  does that look wrong?

**Comment by serpent5** [comment]
> I wonder if it would be worth running the behaviour of `RemoveType` by someone on the engineering team.

On second thought, I don't think this would be beneficial. Changing the behaviour could be a breaking change for little gain. In all likelihood it's _deliberately_ done this way so there's no need to bother them.
