### ISSUE TITLE
Add Token-based authentication sample

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs#15057]
Is it possible to add new sample for token-based authentication (JWT) in the samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82950389-524e-0754-a125-addeccbdb1b3
* Version Independent ID: 80b7f7cf-dc2e-137a-5aa7-fa88da63ac80
* Content: [Authentication samples for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/samples.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Keep an eye on the repo for new samples. I don't think any are scheduled
https://github.com/aspnet/AspNetCore/tree/v3.1.0-preview1.19508.20/src/Security/samples/ClaimsTransformation
