### ISSUE TITLE
dotnet new angular has no -au parameter!

### ISSUE THREAD

**Issue by dmoibm** [aspnet/AspNetCore.Docs#15058]
dotnet new angular -o &lt;output_directory_name&gt; -au Individual dose not work! The -au parameter dosent exist.
Depnds on version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
I see the option here:

<img width="523" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/66714265-3e635100-ed7a-11e9-848f-dcb6dcde858a.PNG">

What SDK are you on? `dotnet --version`

**Comment by dmoibm** [comment]
Sorry! My fault. Wrong version. I used .NET Core 2.2! At the top of the article it is writen: **USE ASP.NET Core 3.0 or later**
Thanks for all and have a nice day.
