### ISSUE TITLE
Wrong headings used

### ISSUE THREAD

**Issue by matteocontrini** [aspnet/AspNetCore.Docs#15061]
I think there's a problem with headings in this page. Every title after the `asp-all-route-data` section is using an `h3` tag, so in the summary on the right sidebar most sections of the page are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Yep ... something went wrong. :boom: ... I'll fix it up. Thanks for reporting this.
