### ISSUE TITLE
Confusing documentation Http.sys

### ISSUE THREAD

**Issue by SoeTien** [aspnet/AspNetCore.Docs#15076]
I am confused by this part:

MaxConnections | The maximum number of concurrent connections to accept. Use -1 for infinite. Use null to use the registry's machine-wide setting. | null(unlimited)

In the description column, it says -1 for infinite, and null for machine-wide setting, but in the default column it says the default value is null and between parentheses it says unlimited.
So is null unlimited or machine-wide setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-3.0#configure-windows-server)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
From the API comments ...

```csharp
/// <summary>
/// Gets or sets the maximum number of concurrent connections to accept, -1 for infinite, or null to
/// use the machine wide setting from the registry. The default value is null.
/// This settings does not apply when attaching to an existing queue.
/// </summary>
public long? MaxConnections
{
    get => _maxConnections;
    set
    {
        if (value.HasValue && value < -1)
        {
            throw new ArgumentOutOfRangeException(nameof(value), 
                value, "The value must be positive, or -1 for infinite.");
        }

        if (value.HasValue && _urlGroup != null)
        {
            _urlGroup.SetMaxConnections(value.Value);
        }

        _maxConnections = value;
    }
}
```

https://github.com/aspnet/AspNetCore/blob/master/src/Servers/HttpSys/src/HttpSysOptions.cs#L95-L117

... so I'll change that to say that the default is the machine-wide setting.
