### ISSUE TITLE
[MVC] Include a section about discovery in the application part docs

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#15078]
In this doc
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.0

We get a lot of issues regarding 404s when invoking controllers or pages with all of them traced back to the user missing some key piece on the way application parts get discovered and work.

We want to add an additional section on the document above to explain the application part discovery process and mention the requirements for MVC applications to work outside usage patterns.

Specifically:
* The `applicationName` setting needs to be set to the root assembly (normally the entry point assembly) used for discovery.
* The root assembly needs to have a reference to the parts used for discovery (either direct or transitive).
* The root assembly needs to reference the Web SDK.
  * We have custom build logic that stamps attributes into the root assembly that are used for discovery.

@pranavkm Anything missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2&branch=pr-en-us-14507)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
@javiercn  when you create an integrated issue, you don't have to write
In this doc `https://docs.microsoft.com/en-us/aspnet/core/etc`

Please we (and customers) can see all the issues for the doc from the doc page.
