### ISSUE TITLE
ASP.NET Core 2.1 support

### ISSUE THREAD

**Issue by dyslexicanaboko** [aspnet/AspNetCore.Docs#15071]
The instructions on this page are like 99% good enough for ASP.NET Core 2.1 except for one part.

This code doesn't work for 2.1:
```
app.UseEndpoints(endpoints =&gt;
{
	endpoints.MapHub&lt;ChatHub&gt;("/chatHub");
});
```

This is what is required instead:
```
app.UseSignalR(route =&gt;
{
    route.MapHub&lt;ChatHub&gt;("/chathub");
});
```
Got that from here: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1

Basically what I am getting at is there should be 2.1 support for SignalR as well. I was able to get this example to work with 2.1, I am not ready to move to 3.0 yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio&viewFallbackFrom=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
The docs are versioned so you can see what different versions of the libraries might do. As you point out, the aspnetcore-2.1 docs work for you as expected. In 3.0 we're moving to Endpoint Routing so that's what the docs show.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by dyslexicanaboko** [comment]
@BrennanConroy that's my point, when you select 2.1 in the top left, the code does not change, it stays on 3.0 like that's been around all along. I just think it would be fair that if you change the target version the code should reflect that target version like the docs already do in other parts of the site.

**Comment by Rick-Anderson** [comment]
@dyslexicanaboko  you're right. PR #14812 removed the previous version. We'll get that restored ASAP.

**Comment by Rick-Anderson** [comment]
@dyslexicanaboko  thanks for bringing this to our attention and being persistent. The 2.x version should be live in 5 minutes.

**Comment by dyslexicanaboko** [comment]
Thank you for listening, I appreciate it.
