### ISSUE TITLE
Console log redirection needs working example.

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore.Docs#15073]
# Regarding Documentation at:
[https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection)

# Issue description

Under the heading **Enhanced diagnostic logs**, the following configuration is shown:

```
<aspNetCore processPath="dotnet"
    arguments=".\MyApp.dll"
    stdoutLogEnabled="false"
    stdoutLogFile="\\?\%home%\LogFiles\stdout"
    hostingModel="InProcess">
  <handlerSettings>
    <handlerSetting name="debugFile" value=".\logs\aspnetcore-debug.log" />
    <handlerSetting name="debugLevel" value="FILE,TRACE" />
  </handlerSettings>
</aspNetCore>
```

Several questions are raised (by newbies such as myself who are trying to figure out how this all works):

1. Whenever configuration code is supplied in documentation, please provide a link to the the doc(s) that explain the schema of the configuration file.  For example, in this case where do I go to find out the complete schema along with an explanation of every configuration setting within web.config? -- I have yet to find such a document !!

2. The configuration parameter **stdoutLogEnabled** is set to "false", and the **stdoutLogFile** is set to a path - this (to me) indicates that Console output will NOT be redirected to the specified path.  Should **stdoutLogEnabled** be set to "true" (given that the topic is "**log creation and redirection**" )-- setting **stdoutLogEnabled** to false disables redirection, does it not?

3. Can the **stdoutLogFile** contain a physical path such as: "D:\\temp\\website_log" ?  Apparently, it can, as it seems to [almost] work for me (see next point).

4. When **stdoutLogenabled** is set to "true" and **stdoutLogFile** is set to a physical path such as "D:\\temp\\website_log", an output file IS CREATED, of the form:  **D:\temp\website_log_{timestamp}_{pid}.txt** as per the docs, but is always empty!! -- WHY ?? What configuration value or setting is missing or what magic code  is used to have content written to the output file?  

I was under the impression that whenever the following statement was executed in code:

`Console.WriteLine( "this should appear in the log file" ):`

... the Console output would be redirected to the **stdoutLogFile** -- but it obviously does not.  In short, a working example of redirecting console output to a file needs to be included as nothing in the docs provides a working solution.

Finally, how does the **Logging** section within the **launchSettings.json** file fit into all of this?  Several examples are given that show various Logging configuration set-ups, for example:

```
   "Logging": {
      "LogLevel": {
         "Default": "Debug",
         "System": "Information",
         "Microsoft": "Information"
      }
```
Does this file and its Logging settings have anything to do with log redirection?  Again where is the document that shows the complete schema for the configuration settings that are allowed in the **launchSettings.json** file?

Three days of trying to get Console logging redirected to a text file (**still not working)**.  Decent documentation would have allowed me to do it in 3 minutes!  (Or, perhaps it cannot be done without a third party plug-in)?  That too, should be mentioned in the docs !!

# Software versions
 .NET Core version 3.0
Microsoft Visual Studio Community 2019
Version 16.3.4
VisualStudio.16.Release/16.3.4+29409.12
Microsoft .NET Framework
Version 4.8.03752

**Comment by guardrex** [comment]
Please use the **This Page** feedback form at the bottom of the topic, which applies metadata and pings the author (*ME!* :smile: lol). No worries ... I moved this over to  #15080.
