### ISSUE TITLE
Use wrong Storage version for Asp.net core 2.2

### ISSUE THREAD

**Issue by yangzuo0621** [aspnet/AspNetCore.Docs#15075]
# Before you open an issue

If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page.

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

Asp.Net Core 2.2 uses the Microsoft.WindowsAzure.Storage package for management of Azure Storage, and Microsoft.Azure.Storage package is used in Asp.Net Core 3.0 or higher.

So the example of creating StorageCredentials in the doc is for Asp.Net Core 3.0 or higher. And in section Asp.Net Core 2.2, it needs modify.

Is that right?

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

Also, be more specific of what is wrong on the page.
