### ISSUE TITLE
Console log redirection needs working example

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#15080]
From @bdcoder2 ...

# Regarding Documentation at:

[https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection](https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection)

# Issue description

Under the heading **Enhanced diagnostic logs**, the following configuration is shown:

```
<aspNetCore processPath="dotnet"
    arguments=".\MyApp.dll"
    stdoutLogEnabled="false"
    stdoutLogFile="\\?\%home%\LogFiles\stdout"
    hostingModel="InProcess">
  <handlerSettings>
    <handlerSetting name="debugFile" value=".\logs\aspnetcore-debug.log" />
    <handlerSetting name="debugLevel" value="FILE,TRACE" />
  </handlerSettings>
</aspNetCore>
```

Several questions are raised (by newbies such as myself who are trying to figure out how this all works):

1. Whenever configuration code is supplied in documentation, please provide a link to the the doc(s) that explain the schema of the configuration file.  For example, in this case where do I go to find out the complete schema along with an explanation of every configuration setting within web.config? -- I have yet to find such a document !!

2. The configuration parameter **stdoutLogEnabled** is set to "false", and the **stdoutLogFile** is set to a path - this (to me) indicates that Console output will NOT be redirected to the specified path.  Should **stdoutLogEnabled** be set to "true" (given that the topic is "**log creation and redirection**" )-- setting **stdoutLogEnabled** to false disables redirection, does it not?

3. Can the **stdoutLogFile** contain a physical path such as: "D:\\temp\\website_log" ?  Apparently, it can, as it seems to [almost] work for me (see next point).

4. When **stdoutLogenabled** is set to "true" and **stdoutLogFile** is set to a physical path such as "D:\\temp\\website_log", an output file IS CREATED, of the form:  **D:\temp\website_log_{timestamp}_{pid}.txt** as per the docs, but is always empty!! -- WHY ?? What configuration value or setting is missing or what magic code  is used to have content written to the output file?  

I was under the impression that whenever the following statement was executed in code:

`Console.WriteLine( "this should appear in the log file" ):`

... the Console output would be redirected to the **stdoutLogFile** -- but it obviously does not.  In short, a working example of redirecting console output to a file needs to be included as nothing in the docs provides a working solution.

Finally, how does the **Logging** section within the **launchSettings.json** file fit into all of this?  Several examples are given that show various Logging configuration set-ups, for example:

```
"Logging": {
   "LogLevel": {
     "Default": "Debug",
     "System": "Information",
     "Microsoft": "Information"
   }
}
```
Does this file and its Logging settings have anything to do with log redirection?  Again where is the document that shows the complete schema for the configuration settings that are allowed in the **launchSettings.json** file?

Three days of trying to get Console logging redirected to a text file (**still not working)**.  Decent documentation would have allowed me to do it in 3 minutes!  (Or, perhaps it cannot be done without a third party plug-in)?  That too, should be mentioned in the docs !!

# Software versions

 .NET Core version 3.0
Microsoft Visual Studio Community 2019
Version 16.3.4
VisualStudio.16.Release/16.3.4+29409.12
Microsoft .NET Framework
Version 4.8.03752

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@dbcoder ... 

1. At this point, that's a product question given that I agree with you: I can't find one either. I thought it was over at the schemastore.org site, but I may have been mistaken about that (or it used to be there but no more). Open that request with the product team at :point_right: https://github.com/aspnet/AspNetCore/issues to ask them if one is available somewhere or if they would be willing to put one up.

2. The instruction on how to enable the debug log is to ...

   > Add the \<handlerSettings> element to the \<aspNetCore> element in web.config.

   These are two different files controlled in different ways. The stdout log is enabled by `stdoutLogEnabled` (explained in the prior section). The debug file is enabled by the presence of the \<handlerSettings> element (`name="debugFile"`). If you feel that it would be better to have more of a *switch-type* set up for the debug file to match the stdout file configuration, that's good product feedback for the engineers (*and I agree with you* if that's your notion here). Open that with them so that they can consider/react to your feedback :point_right: https://github.com/aspnet/AspNetCore/issues.

3. Yes, and that's shown in other examples in the topic.

4. It *sounds* like you have the right config. I'm wondering if there's a permissions difference between being able to create the file and write to it going on here. Try using a path directly to the folder from which you're running the project in IIS (the "Physical Path" to the app).

5. The schema for that one they do have :point_right: http://json.schemastore.org/launchsettings, but those logging settings aren't in that file. Did you mean to type *appsettings.json*? ... http://json.schemastore.org/appsettings ... but you won't find the log levels element schema there. This is covered (better anyway) in the Logging topic starting at https://docs.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#create-filter-rules-in-configuration and running through the next few sections, which indicate that you just set up a `Console` node with a `Default` log level set to one of the log level values listed at https://docs.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#log-level.

**Comment by guardrex** [comment]
After we've discussed this a bit further, I'll identify what we can do in the doc. For example, we'll cross-link the console logging coverage here.

**Comment by bdcoder2** [comment]
@guardrex - Thanks for the feedback...

**Regarding point 3** - yes, it is shown, but for those who are un-initiated, looking at a line like:

`stdoutLogFile="\\?\%home%\LogFiles\stdout"`

... raises questions such as:

Where in the docs do I find explanations for the various elements shown in the path? For example:

1. \\?\ - What does that resolve to on disk?  (Again, someone with no knowledge wouldn't have a clue). provide a link to: [https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)

2. %home% - What does that resolve to on disk? (No clue for those that are new) - provide a link to where I can find something regarding the (environment variable?) %home%.   (Always assume the reader knows nothing!!!) 

The example in the current doc does not seem to work (at least not for me) -- Just tried this morning and the debug log contained the following entries:

```
[aspnetcorev2.dll] Exception 'create_directories: The system cannot find the path specified.: "\\?\%home%\logs"' caught at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\CommonLib\RedirectionOutput.cpp:66 
[aspnetcorev2.dll] Event Log: 'Could not start stdout file redirection to '\\?\%home%\logs\website3_log' with application base 'D:\vsprojects\netcore3\website3\website3\'. create_directories: The system cannot find the path specified.: "\\?\%home%\logs".' 
End Event Log Message.
```
However, the path D:\vsprojects\netcore3\website3\website3\logs DOES exist -- perhaps %home% refers to some other path?? -- No clue as the error message displayed by RedirectionOutput.cpp does NOT provide the actual (physical) path that could not be found -- which makes the error message, well, basically useless -- unless you are born with the knowledge of where %home% resolves to !

The strange part is, the debug log file is created and written to without issue to D:\temp\ via the web.config settings:

```
    <handlerSetting name="debugFile" value="D:\\temp\\website3_debug_log" />
    <handlerSetting name="debugLevel" value="FILE,TRACE" />
```

However, when (trying) to redirect Console output using:

```
<aspNetCore 
    stdoutLogEnabled="true"
    stdoutLogFile="D:\temp\website3_log"
    hostingModel="InProcess">
```
The log file is created, but is always empty.  Seems strange that the debug file can be written to, but the Console file cannot.  A more consistent approach would be to set handlers for Console logging, something like:
```
    <handlerSetting name="consoleFile" value="D:\\temp\\website3_log" />
    <handlerSetting name="consoleLevel" value="FILE,TRACE" />
```

**Regarding the launchSettings.json config file**

Yes - I am still looking for some schema or definition page that explains the various entries that can exist and what effect they have, what values are valid, etc (all valid questions that should be easily found within the docs).

**Comment by guardrex** [comment]
Yes, I'll put the link pertaining to file paths in the *Additional Resources* section.

`\\?\%home%\LogFiles\stdout` is an Azure App Service path (yes, env var on Azure). There's a sentence in the topic calling it out ...

> When an app is deployed to Azure App Service, the `stdoutLogFile` path is set to `\\?\%home%\LogFiles\stdout`. The path saves stdout logs to the LogFiles folder, which is a location automatically created by the service.

I'll indicate the the path env var for `%home%` is set by the service. I'll see about a cross-link wrt env var path variables and include that in *Additional Resources*, too.

> The log file is created, but is always empty. Seems strange that the debug file can be written to, but the Console file cannot. 

I don't have any further info or advice. Did you try a path to a folder in the IIS physical path to the app as I suggested? ... just to see if this is a write permissions problem? If you can't get it to work at all (including such a test with the IIS physical path), then you can open it with engineering for investigation. Note that they'll probably want to see a repro project, so put one up on GH for your issue over there. Show them the **published** *web.config* file ... the one from your *publish* folder or the one that ends up at your IIS physical path if you're publishing directly there.

>  A more consistent approach would be to ...

That feedback has to go to engineering. We only handle docs here and aren't part of the engineering team. They'll react to your suggestions on their repo.

> all valid questions that should be easily found within the docs

Sure, but I can't link to content that I don't have. The request has to go to the product unit (engineering). We can document it if they'll work it up (feel free to add an "cc: @guardrex" to the bottom of your issue so that I can get a ping on their response to your issue). For now, we have the console logging info in the logging topic to cross-link. I don't have a schema for *web.config*, nor do I have a schema for *appsettings.json* logging section entries; therefore, I don't have anything to link at this time. Do let them know tho ... this is the type of feedback that they would like to hear.

**Comment by bdcoder2** [comment]
@guardrex - Thank-you very much for the response.   I will shoot engineering the questions raised here as per your suggestion.

I did try a path to a folder within my project -- at several levels -- but to date, the console logging file gets created, but is never written to (remains empty) -- I am at a loss.

Good grief, if internally one cannot find docs regarding **web.config** and **launchSettings.json**; how can newbies (such as myself) find answers?  I'll be sure to mention this to engineering as well ! :) 

Again, thanks for the positive responses -- very much appreciated.

**Comment by guardrex** [comment]
> I did try a path to a folder within my project

It occurs to me looking at the discussion: You're trying to run IIS Express/ANCM from VS? Is that correct. I think you should try the https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.0 topic for that scenario. What was confusing me at first was that I thought you were trying to get your console logging output in IIS and confused about the role of *launchsettings.json*, but now I see that I'm the one who is confused about your ask: You are trying to get console logging with IIS Express and VS ... not run a proper site. If you host that site on IIS, the console logging will work as described here.

This opens a larger question tho ... one that we have struggled with in the docs: The IIS Express scenario (and along with VS where IIS Express is a launch profile OOB) aren't covered very well. Part of that is due to our focus on cross-tooling docs. Part of it is that it's the ANCM on IIS that devs need the most info on for production hosting.

Let me come back to those aspects again on this issue shortly ... perhaps next week when I get through some stuff on my plate.

Before you open with engineering tho on the console logging problem, check out the dev-time support topic for IIS. See if taking that approach gets your logging output going.

**Comment by guardrex** [comment]
... and I'll just add one more tidbit here. You're obviously trying to get console logging going with that stdout logging. Engineering really doesn't prefer that you take that approach. They *always* recommend:

* Use a 3rd party logging provider to take your console logging (e.g., Serilog).
* Use this stdout logging with a troublesome app on a server for quick-and-dirty logging to figure out a quick, local issue.

The stdout logging isn't a good choice for any type of logging really: There's no limit on log size, and there's no log rotation. If someone forgets to turn it off, it can take down a whole server! *Yikes!* :smile:

**Comment by bdcoder2** [comment]
@guardrex - Just saw your additional posts (after I posted my issue with engineering) -- and yes, you are correct (I should have been more detailed) -- I am running in DEBUG mode via Visual Studio / IIS Express.  (I would never enable Console logging in a production environment).

As I am new to the .Net Core environment (having spent the last several years in .Net Framework development), I was only wanting to use Console logging for my on sanity while trying to learn how all this works!

Cheers!

**Comment by guardrex** [comment]
I think you're going to have to go with dev-time IIS support in VS to get that console logging output ... guessing a bit since I didn't actually try it myself. It should work tho. 🤞 I've only set up the dev-time support to make sure that our coverage was correct. You *probably* won't get console logging otherwise running IIS Express.

Console logging is rather *very* frowned upon by them for the reasons that I mentioned ... even in any kind of local testing scenario. It's really meant to be a quick-and-dirty logging tool for one-off scenarios ... not for regular logging of any sort ... production, development, or otherwise.

**Comment by bdcoder2** [comment]
@guardrex - Understood -- might be a good idea to mention that in the docs, ie: something along the lines of:

**Console output redirection should not be used when developing / using IIS Express.**

Myself: It took 10 minutes to write my own "custom" logger that dumps to a text file; which is working just fine - I will simply add to my notes never to use Console logging / redirection when using ASP.Net Core.

[end of story]

**Comment by guardrex** [comment]
Yes ... it's already there :point_right: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#log-creation-and-redirection

I'll get on your feedback here soon and ping u on the PR. Thanks for your remarks and discussion.
