### ISSUE TITLE
Fetch

### ISSUE THREAD

**Issue by Taylor365** [aspnet/AspNetCore.Docs#15087]
Fetch is mentioned several times on this page but is not in any of the code snippets.

Solution: Code snippets need to be updated to match what is on github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1&tabs=visual-studio#call-the-web-api-with-javascript-1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie  5 minute fix.

**Comment by scottaddie** [comment]
@Rick-Anderson I'll take a look.
