### ISSUE TITLE
<Dependency injection> section needs updating.

### ISSUE THREAD

**Issue by aminm1364** [aspnet/AspNetCore.Docs#15083]
Hey, I hope this is helpful.

- On the latest version on the Blazor template (Server app), the Services folder has been renamed to Data. so I believe on the Pages/FetchData.razor, there is no "@using ToDoList.App.Services". instead we should have something like "@using ToDoList.App.Data"
- Also, there is no weather.json file anymore to provide data for this page. the data comes from the controller and I think needs to be updated on the documentation. 

best wishes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for that note @aminm1364 ... Indeed, we were 🏃 fast during 3.0 updates, and I didn't have time to walk the whole topic. I'll fix that for the Blazor Server piece today.

The *weather.json* file is still there for the Blazor WebAssembly app. That's called out in the topic. However ...... now that I run an :eye: over that coverage .... I don't like how it's all in the text without clear headings. The text just drifts right from speaking to Blazor Server to Blazor WebAssembly. While I'm fixing up the Blazor Server bits :point_up:, I'll see if I can get some headings in there to distinguish those approaches.
