### ISSUE TITLE
添加数据库上下文类 tag

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15109]
@95 commented on [Tue Oct 15 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/206)

1. 添加到“数据”文件夹 -&gt; 添加到“Data”文件夹
2. namespace RazorPagesMovie.Models -&gt; namespace RazorPagesMovie.Data

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [在 ASP.NET Core 中向 Razor Pages 应用添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Tue Oct 15 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/206#issuecomment-542023448)

Hello, @95
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@Rick-Anderson commented on [Tue Oct 15 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/206#issuecomment-542030804)

Data folder is correct. so `namespace RazorPagesMovie.Data` is correct

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user is making a suggestion on one of the code boxes
(the first item is linguistic which I already forwarded for linguistic assessment

kind regards

**Comment by Rick-Anderson** [comment]
Actually, for the model, model is correct.
