### ISSUE TITLE
Dictionary saved into Data property must be initialized with StringComparer.OrdinalIgnoreCase

### ISSUE THREAD

**Issue by tfabraham** [aspnet/AspNetCore.Docs#15119]
Configuration keys are documented as being case-insensitive.  However, Dictionary&lt;string, string&gt; defaults to a case-sensitive comparer as used in the sample EFConfigurationProvider.  When the config system searches the provider chain for a particular path/key, the search against the dictionary from EFConfigurationProvider is case-sensitive.  If the same path exists in multiple provider dictionaries with different casing, it's possible to get back different values depending on the case of the key passed to GetValue() on IConfiguration.  The Dictionary must be initialized with StringComparer.OrdinalIgnoreCase to preserve the expected case-insensitivity.  After hours of troubleshooting, I finally discovered that by looking through the ASP.NET Core Extensions configuration providers source code on GitHub.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tfabraham ...

> If the same path exists in multiple provider dictionaries with different casing, it's possible to get back different values depending on the case of the key passed to GetValue() on IConfiguration.

What use case leads to that? How do the same keys with different casing get into the dictionary in your scenario?

**Comment by tfabraham** [comment]
All it requires is "MySetting": "abc" in appsettings.json, then (attempting to) override it in the custom provider with "MySETTING" = "def" (in a Dictionary without StringComparer.OrdinalIgnoreCase).  The resulting IConfigurationRoot after Build() will return "abc" from config["MySetting"] and "def" from config["MySETTING"], when both should now return "def" (assuming the custom provider comes last).

**Comment by guardrex** [comment]
I might be able to reach this by the end of the month, but I put it in the November sprint just in case.
