### ISSUE TITLE
Bad cross-refs

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#15112]
I'm going to run thru and fix these up ...

aspnetcore/fundamentals/host/generic-host.md
2  invalid cross reference(s)
\<xref:Microsoft.Extensions.Hosting.Internal.ConsoleLifetime>",  \<xref:Microsoft.Extensions.Hosting.Internal.ApplicationLifetime>

aspnetcore/migration/22-to-30.md
2  invalid cross reference(s)  \<xref:Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.IConnectionAdapter>
\<xref:Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.SchedulingMode>

aspnetcore/performance/caching/response.md
1 invalid cross reference(s)
\<xref:Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter>

aspnetcore/security/authentication/social/additional-claims.md
1  invalid cross reference(s)  \<xref:Microsoft.AspNetCore.Identity.UI.Pages.Account.Internal.ExternalLoginModel.OnPostConfirmationAsync*>

cc: @Rick-Anderson @scottaddie @wadepickett

**Comment by guardrex** [comment]
@scottaddie *Whooops!* :smile: ... There's an API docs bug here.

https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.Extensions.Hosting.Internal.ConsoleLifetime

... is a thing, but the API doc page (first link returned) ends up a 404 :boom: ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.internal.consolelifetime

I suppose you'll want to open an internal issue and then close this.

**Comment by scottaddie** [comment]
This is a result of some API ref changes @mairaw is working on. The Internal namespaces will need to be code-fenced, as they're no longer being published.

**Comment by guardrex** [comment]
Ok ... do you want me to do it? ... or leave it assigned to u?

**Comment by scottaddie** [comment]
I'm wrapping up a few other PRs right now. If you have time, go ahead with it.

**Comment by guardrex** [comment]
ok ... I'll do it. I'm just waiting on the blog post.
