### ISSUE TITLE
API reference missing for 3.0

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore.Docs#15128]
When looking at the [API reference docs for 3.0](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.0), a lot of content appears to be missing, most notably all the MVC namespaces. There are only very few namespaces available when comparing that to [2.2](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.2). This wasn’t as much as an issue during the 3.0 previews but now that 3.0 is out, the docs should really be there.

This issue already existed at MicrosoftDocs/feedback#1521 and aspnet/AspNetDocs#162 but I’m not sure if there was ever a follow up. I couldn’t find an issue in this repo at least.

Any chance we could get the API docs updated soon?

**Comment by guardrex** [comment]
Hello @poke ... it's a known issue. They're working on it. We don't have an ETA.
