### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by CJEdgerton** [aspnet/AspNetCore.Docs#15139]
Azure AD V1 samples -&gt; Integrating Azure AD Into an ASP.NET Core Web App: results in 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdae773-368b-a0c1-64d0-2a7b8c8fb134
* Version Independent ID: 2816eb27-7fc5-19e6-7f79-7e81a388647f
* Content: [Azure Active Directory with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/azure-active-directory/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-active-directory/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @CJEdgerton ... I'll fix that up.

**Comment by fowl2** [comment]
The link now goes to the v2 sample. :(

**Comment by guardrex** [comment]
@fowl ... Open a new issue using the **This Page** feedback button+form at the bottom of the topic and state which link you're referring to and where you think it should go.
