### ISSUE TITLE
ASP.NET Core 2.2 Online Documentation

### ISSUE THREAD

**Issue by jovton** [aspnet/AspNetCore.Docs#15132]
The online documentation for ASP.NET Core 2.2 says: Prerequisites ".NET Core 3.0 SDK or later". Is that really so?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, we don't keep older versions of this tutorial. The instructions should work for 2.1 and 2.2
