### ISSUE TITLE
Just a Heads-up

### ISSUE THREAD

**Issue by henryjones000** [aspnet/AspNetCore.Docs#15138]
In your Create a new ASP.NET Core Web Application section above, the picture below shows ASP.NET Core 2.2. 

It should be 3.0. I think that's what caused the conflict when I tried to install Entity Framework late on. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/66947222-3875a600-efee-11e9-8596-ffe7607681f5.png)

@henryjones000  thanks for reporting this.

@wadepickett  can you get this fixed today?
In the new image, put a red box around ASP.NET Core 3.0

**Comment by wadepickett** [comment]
@Rick-Anderson, yes, hitting this now, thanks!

**Comment by henryjones000** [comment]
LOL. Now the top says "Select Web Application(Model-View-Controller), and then select Create." while the picture below says "Web Application". Please correct.

**Comment by Rick-Anderson** [comment]
@wadepickett  please fix

**Comment by wadepickett** [comment]
Fixed with #15207
