### ISSUE TITLE
JS function for "setElementValue" (on <Detect when a Blazor app is prerendering> section)

### ISSUE THREAD

**Issue by aminm1364** [aspnet/AspNetCore.Docs#15140]
Hey,
I know this is not so tricky ;) but just for the sake of the documentation :), no JavaScript function has provided for "setElementValue" so it leads to "Nothing" on the &lt;Detect when a Blazor app is prerendering&gt; section, and raising an error for the next part.

wish the best.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#detect-when-a-blazor-app-is-prerendering)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @aminm1364 ... Yes because it isn't germane to the concepts discussed in the section. Same deal for `handleTickerChanged` earlier, which also isn't shown. In the `handleTickerChanged` case, however, there's a line to call it out in the code snippet ...

> The handleTickerChanged JavaScript method is implemented in a JavaScript file, such as 'wwwroot/tickerJsInterop.js'.

The same thing should be done here.

**Comment by guardrex** [comment]
You're actually the 2nd dev to ask. @Legends just commented a short time ago on https://github.com/aspnet/AspNetCore.Docs/issues/14131 ...

```
setElementValue: (elem, val) => { elem.value = val; return val;}
```

Perhaps, it should have it. 🤔 It would be better for playing with the bits if *all the bits are there!* :smile:

**Comment by guardrex** [comment]
Yes ... I think this has composed very well with examples. Thanks @aminm1364. I'll ping u and @Legends on the PR, which should be up shortly.

**Comment by aminm1364** [comment]
Thank you @guardrex 🤘. I assume it'd be definitely helpful to follow and understand the different parts of the code. 🙂
