### ISSUE TITLE
How to Access Windows Auth User, when in C# Model?

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore.Docs#15145]
I'm using Asp.Net Core 3.0, Server Side Blazor. The doc does well showing how you can get the Identity name for use within an component. But I have some Models utilized within my components. Namely a "User Activity" model which has 2 properties: UserName and DateTime.

I cannot find in any Blazor documentation how I can access the username within this .cs file. Any guidance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#procedural-logic)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kevingates ... try injecting the `IAuthorizationService` into the class.

https://docs.microsoft.com/aspnet/core/security/blazor/#procedural-logic

Let's leave this open because *you are correct* in that the topic doesn't show such an example. Management/engineering will decide if we should have an example to go along side the Razor component example shown in the *Procedural logic* section.

**Comment by guardrex** [comment]
Did you try injecting `IAuthorizationService` directly into your `UserActivity` class and use it there (i.e., no need to pass it like that from the component).

**Comment by kevingates** [comment]
> Did you try injecting `IAuthorizationService` directly into your `UserActivity` class and use it there (i.e., no need to pass it like that from the component)?

Pardon my ignorance. I'm still relatively new to Dependency Injection. I'm currently scanning microsoft docs, but do you have a pseudo-code (or actual code) example of **how** I would do that directly into the class?

Also, the few times I get the values of AuthorizationService (trying to implement this in different ways), I never actually see anything that would lead me down a User -> Identity -> Name type of path.

Thank you again for all your time and assistance.

**Comment by guardrex** [comment]
Yeah ... I see now that the user is from `AuthenticationStateProvider` in the example that Steve put up. 

Why pass it tho ... can u just assign it directly to the new `UserActivity` .......

```csharp
namespace BlazorAuthTest
{
    public class UserActivity
    {
        public string UserName { get; set; }
        public DateTime DateTime { get; set; }
    }

    public class Vendor
    {
        public string Something { get; set; }
        public UserActivity UserActivity { get; set; }
    }
}
```

```cshtml
@page "/"
@using Microsoft.AspNetCore.Components.Authorization
@inject AuthenticationStateProvider AuthenticationStateProvider

<h1>Hello, world!</h1>

Welcome to your new app.

@code {
    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        var user = authState.User;
        var x = new Vendor() 
        {
            Something = "blah", 
            UserActivity = new UserActivity()
            { 
                DateTime = DateTime.Now,
                UserName = user.Identity.Name
            }
        };
    }
}
```

**Comment by guardrex** [comment]
Cross-linking a few existing topics for authn/authz ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
* [Token Based Authorization using IdentityServer with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14191)
* [Signalr Context.User missing on hub](https://github.com/aspnet/AspNetCore.Docs/issues/14097)
* [Logout Flow](https://github.com/aspnet/AspNetCore.Docs/issues/13316)
* [Blazor auth topic enhancements](https://github.com/aspnet/AspNetCore.Docs/issues/13022)
* [Blazor and multiple auth providers](https://github.com/aspnet/AspNetCore.Docs/issues/15033)
* [How to Access Windows Auth User, when in C# Model? ](https://github.com/aspnet/AspNetCore.Docs/issues/15145)

**Comment by mkArtakMSFT** [comment]
Thanks for helping out @kevingates , @guardrex.
This looks like a great question for the [StackOverflow](https://stackoverflow.com) forum.
