### ISSUE TITLE
Missing descriptions for items in ASP.NET Core 3.0

### ISSUE THREAD

**Issue by BenWestbrook** [aspnet/AspNetCore.Docs#15142]
Missing  description for "Individual User Accounts"
Missing description for "Work or School Accounts"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0676a8c8-8009-8a7e-72ac-7cde0013fb97
* Version Independent ID: e35e8811-07d1-ca9b-d6e7-e28c1d4b1853
* Content: [Articles based on ASP.NET Core projects created with individual user accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/individual.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/individual.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
| Option | Type of authentication |
 | ----------------- | ------------ | 
| None            |  No authentication |
| Individual      |  Individual authentication |
| IndividualB2C   |  Individual authentication with Azure AD B2C |
| SingleOrg       |  Organizational authentication for a single tenant |
| MultiOrg        |  Organizational authentication for multiple tenants |
| Windows         |  Windows authentication |
