### ISSUE TITLE
MapRazorPages required for Identity UI

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#15144]
I've seen a couple of people get caught out by the Identity UI requiring a call to `MapRazorPages`. The need for `MapRazorPages` is covered [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#razor-pages), but it might not be obvious that this is needed if RP is _only_ being used for the Identity UI.

Should a note be added to this migration guide to point this out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#razor-pages)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> but it might not be obvious that this is needed if RP is only being used for the Identity UI.

For example, MVC app not using RP (Razor Pages).

I think that's a good idea.

**Comment by serpent5** [comment]
Awesome. I'll PR something at the weekend if this hasn't been tackled before then.

**Comment by serpent5** [comment]
Should there be a new section on the page with an e.g. "Identity UI" heading, which covers:

- Adding `MapRazorPages` if it's not already been done.
- Calling out that the NuGet package `Microsoft.AspNetCore.Identity.UI` needs to be installed. This is covered in [Add package references for removed assemblies](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies), but perhaps it could also go into this new heading. This would be similar to how "Opt in to runtime compilation" has both a section and a mention in the section I linked above.
- Instructions describing how to handle `AddDefaultUI` no longer taking a `UIFramework` option.

If no to the section thing, how should the requirement for `AddRazorPages` be called out?

**Comment by Rick-Anderson** [comment]
New section makes sense. An H2 (`##`) will get good SEO.
