### ISSUE TITLE
Unable to define Host in the Program.cs file 

### ISSUE THREAD

**Issue by kryp17** [aspnet/AspNetCore.Docs#15159]
Hi, I am not able to resolve the definition of Host in Program.cs. kindly take a look and explain/define the Host variable in:

 public static IHostBuilder CreateHostBuilder(string[] args) =&gt;
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =&gt;
                {
                    webBuilder.UseStartup&lt;Startup&gt;();
                });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by TeeKKar** [comment]
Me neither actually. I kept getting "The type or namespace name 'Startup' could not be found (are you missing a using directive or an assembly reference?) (CS0246) [mvcmovie]" error. Not sure where I went wrong.

**Comment by SigmaSolutionUsers** [comment]
I received the same error with .NET Core version 2.2. 

This tutorial however requires .NET Core 3.0+, change to .NET Core 3.0+ will resolve the issue.

**Comment by rudipapa** [comment]
I had the same problem. Edit Startup to mvc.Startup solved successfully.
