### ISSUE TITLE
Link does not have Claims transformation examples

### ISSUE THREAD

**Issue by hari2m** [aspnet/AspNetCore.Docs#15150]
The link provided at the end of the claims transformations section does not have any valid examples of claims transformation implementation. It is just taking to the page that shows how the asp.net core modules are implemented in IIS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hari2m ... Your document version selector is on the wrong version of the topic. Set it to 3.0 to see that content ...

<img width="275" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/67002368-5cde8a80-f0a1-11e9-9aca-af6cfbecd236.PNG">

It shows up for versions >=2.1.
