### ISSUE TITLE
It's all in 3.0

### ISSUE THREAD

**Issue by KyleAdo** [aspnet/AspNetCore.Docs#15166]
I'm currently doing 2.2 for University work but this tutorial page has recently changed to 3.0 completely, even when I scroll to different versions on the left-hand side, it's all the same tutorial for 3.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KyleAdo  sorry about that. We should be able to restore the 2.x version  in a few hours.

**Comment by Rick-Anderson** [comment]
@KyleAdo  thanks for bringing this to our attention. I've restored the 2.2 version. It should be live in about 10 minutes.

**Comment by KyleAdo** [comment]
Thank you very much Rick!
