### ISSUE TITLE
Social login provider tokens+claims for Blazor auth

### ISSUE THREAD

**Issue by hfaran** [aspnet/AspNetCore.Docs#15160]
From what I can tell, the `AuthenticationProperties` has been removed from ASP.NET Core 3.0, however, it is still referenced several times in this page.

Moreover, if `SaveTokens` is set to `true` in options for third-party providers, where are these tokens now *actually* saved? And how can I access them? I am trying to make a call using HttpClient from the theoretically saved token, but over the last three hours of scouring the internet, have been unable to discover how to make this work in aspnetcore3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hfaran ... `AuthenticationProperties` wasn't removed ...

https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Http/Authentication.Abstractions/src/AuthenticationProperties.cs

According to engineering, the updates for 3.0 are correct ...

https://github.com/aspnet/AspNetCore.Docs/pull/14745

The sample app worked when I upgraded it to 3.0 and tested it with Google.

> And how can I access them?

The sample app shows how to get the tokens when the ticket is created ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Startup.cs#L52

It also shows how to get the claims and auth props ...

* https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Pages/Index.cshtml.cs
* https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Pages/MyClaims.cshtml
* https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Pages/MyClaims.cshtml.cs

**Comment by hfaran** [comment]
Thanks for the quick reply. 

My bad, I didn't realize AuthenticationProperties had moved (I was looking at this page on the docs and it no longer exists in this assembly: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.authentication.authenticationproperties?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0).

To clarify my scenario, what I have is a freshly created app using the new server-side Blazor template, and to that, I have simply added a third-party authentication ([Fitbit](https://www.nuget.org/packages/AspNet.Security.OAuth.Fitbit/) in particular). I would like to save this token/associate it with the currently logged in User, however, I have not seen a clear way using existing documentation to make that happen.
Following the sample code above, even if I save the tokens using this snippet:

```csharp
var fitbitOCT = fitbitOptions.Events.OnCreatingTicket;
                    fitbitOptions.Events.OnCreatingTicket = ctx => {
                        fitbitOCT(ctx);
                        List<AuthenticationToken> tokens =      ctx.Properties.GetTokens().ToList();

                        tokens.Add(new AuthenticationToken()
                        {
                            Name = "TicketCreated",
                            Value = DateTime.UtcNow.ToString()
                        });

                        ctx.Properties.StoreTokens(tokens);

                        return Task.CompletedTask;
                    };
```

...I don't seem to be able to access the "access_token" from Fitbit later on when I want to make a call to the Fitbit API. Is there something I'm missing? It would be nice to have some sort of sample in the docs addressing the scenario of **"how to use an access token received from a third-party provider to make a call later"**.

**Comment by hfaran** [comment]
To be clear, the actual authentication with Fitbit is working just fine - I'm just struggling to figure out how to pass through the received access_token in such a way that I can access it later (within the same session of the currently logged in user so I can make a request to the third-party API on their behalf).

**Comment by guardrex** [comment]
> I didn't realize AuthenticationProperties had moved

They haven't updated the API docs yet. We don't have an ETA on when they'll have that finished. AFAIK, they're working on it right now. After they do that, it should show up with the correct namespace and assembly over at https://docs.microsoft.com/en-us/dotnet/api/.

> how to use an access token received from a third-party provider to make a call later (using HttpClient) by providing the access_token as the Authorization header for the client

> access the "access_token" from Fitbit later on when I want to make a call to the Fitbit API

In that case, forget about `OnCreatingTicket`, since you aren't trying to use it when the ticket is created. It's an authentication property (`.Token.access_token`) ...

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0#sample-app-output

Try it the way that the sample does it in the *MyClaims.cshtml.cs* file ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Pages/MyClaims.cshtml.cs#L12-L18

... in your code where you need the token to make the 3rd party call.

**Comment by guardrex** [comment]
For the HttpClient part to make your call, I don't think that `IHttpContextAccessor` is recommended any longer.

See ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0

Note that I'm leaving for a while and responses will be delayed.

**Comment by guardrex** [comment]
🤔 https://docs.microsoft.com/en-us/aspnet/core/security/blazor/index?view=aspnetcore-3.0&tabs=visual-studio

... and we show getting claims but not auth props. I'll take a look at that when I get back in a few hours. It would be nice if we show that, too, there.

**Comment by guardrex** [comment]
Well ... I worked it out in a Razor component. :smile: ....

```cshtml
@page "/"
@using Microsoft.AspNetCore.Components.Authorization
@inject AuthenticationStateProvider AuthenticationStateProvider
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Authentication;

<h1>Auth Testing</h1>

Username: @_username

<h2>Authentication Properties</h2>

<dl>
    @foreach (var prop in _authProperties)
    {
        <dt>@prop.Key</dt>
        <dd>@prop.Value</dd>
    }
</dl>

@code {
    private string _username;

    private IDictionary<string, string> _authProperties = new Dictionary<string, string>();

    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        var user = authState.User;

        var authResult = await HttpContextAccessor.HttpContext.AuthenticateAsync();

        if (authResult?.Properties?.Items != null)
        {
            _authProperties = authResult.Properties.Items;
        }
        
        _username = user.Identity.Name;
    }
}
```

I do have to run 🏃 ...... take it from there and see if you can get your class to pull the token along those lines.

Anyway ... besides what we're talking about in class ... I think this (or something like it that engineering says isn't another *RexHack!*:tm: :smile:) should be in the Blazor security topic. I'll update the issue labels and get this scheduled.

**Comment by hfaran** [comment]
Thank you for all the help thus far!

So, actually, using the way you've done it above with AuthenticateAsync doesn't work for me because for some reason, I only get the two following properties ☹️ :

```csharp
var authResult = await HttpContext.AuthenticateAsync();
var AuthProperties = authResult.Properties.Items;
```
```
// Immediate Window
AuthProperties
Count = 2
    [0]: {[.issued, Thu, 17 Oct 2019 13:26:57 GMT]}
    [1]: {[.expires, Thu, 31 Oct 2019 13:26:57 GMT]}
```

I don't know why that happens.

**Comment by hfaran** [comment]
One thing I did try was actually saving the access token in `HttpContext.Session`, like this:

```csharp
fitbitOptions.Events.OnCreatingTicket = ctx => {
    ...
    ctx.HttpContext.Session.SetString("fitbit_access_token", tokens.Where(x => x.Name == "access_token").Single().Value);
    ...
};
```

And then just accessing it later using `var fitbit_token = HttpContext.Session.GetString("fitbit_access_token");`, **however**, this also only works the first time you log in using Fitbit. Let's say you run the app, login w/ Fitbit, close it, and open it again. You are still logged in from last time **but**, it isn't the same session I guess so the fitbit_access_token you saved from before is no longer there. I'm assuming this is more to do with the DefaultIdentitySetup of the basic Blazor template that I'm using.

```csharp
            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
```

I think the **real** solution here, would probably be to save **all** of the following from the Fitbit OAuth response to a customized version of `IdentityUser`'s profile:
* access_token
* refresh_token
* expires_at

With that high-level goal in mind, I guess it would be really nice if an example of this existed somewhere 😄 . For example, once I create a custom user model with FitbitAccessToken, FitbitRefreshToken properties etc.:
* How do I manipulate the user instance to add this information to the user's profile from inside of `AddFitbit` or `AddGoogle` or whatever?
* Is that even the right approach here?
* Does the Identity framework already handle some part of all of this in some smart way?

**Comment by guardrex** [comment]
I took a look ... I agree with you. Our ASP.NET Core social docs don't apply to this scenario in Blazor. Sticking the tokens (and indeed claims from the social service) into a database and pulling them later where needed seems to be the way to go.

It could work with tokens/claims 🤔 by overriding `GetAuthenticationStateAsync`, such as is shown in the [Blazing Pizza sample](https://github.com/dotnet-presentations/blazor-workshop/blob/master/save-points/06-add-authentication/BlazingPizza.Client/ServerAuthenticationStateProvider.cs). The Blazor Server template (with the Identity option enabled) has a replacement `AuthenticationStateProvider` sitting right there (`RevalidatingIdentityAuthenticationStateProvider`) to accept such an override. When the claims are made there, they should populate for every auth request, thus the token/claim should be available anywhere in the app (*in theory* 🤞).

In passing while looking at engineering issues, I saw one that pertained to refresh tokens. They said that the dev has to take care of the logic to do that. I would paste the issue link in here, but I lost it. 🙈 The Blazor Server template has revalidation ... not token renewal. I'm not currently aware of any example on that (yet anyway), but I would guess that *some* dev *somewhere* has worked out a solution.
Leave this open ... I would like to float some additional guidance on the approach. Probably should call out in strategic spots that our social docs don't apply to Blazor. Engineering will put an :eye: on it and help on the PR. I'll ping u when I put that in, and I'll probably work on it today or this weekend.

btw -

**Comment by hfaran** [comment]
Thanks a lot! I'll give that a look soon. For now, I've set up a hacky rube goldberg machine of a solution, which is to do the following:
1) Set up a custom user as per the documentation here (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.0&tabs=visual-studio#add-custom-user-data-to-the-identity-db) to allow saving custom properties (such as FitbitAccessToken in my case) to the DB.
1) When the user initially signs in with the third-party OAuth, inside of `OnCreatingTicket` save the acquired third-party token to `HttpContext.Session`.
2) When the user navigates to a relevant page, invoke an action on page load to save the token that is stored in the `HttpContext.Session` to the custom user's profile in the DB. This is done using `UserManager` to get and update the user.
    * Unfortunately, I cannot save the token inside of the `OnCreatingTicket` method since the user technically exist at that point 🤕 (or at least, `HttpContext.User` isn't associated with the actual identity at that point).

Based on the above, the **key problem is putting the received third-party tokens somewhere until we can save them to the DB**.  Hopefully overriding the `AuthenticationStateProvider` as you mentioned above may help here (by stuffing them into claims).

I do find it strange that there is no example for the thing I'm trying to do... I would have thought actually **using** the tokens to make calls to third-parties would be a common scenario, but it seems like the [docs ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.0)only cover how to **sign in** using third-party identity providers, and not how to do anything with the received tokens after that. 😛

**Comment by guardrex** [comment]
Ah ... yes ... the 👹 *FrankenApp*:tm: 👹 ... I've built a few. 🙈 

I have an idea on how to compose it ...

> how to get this into the DB

> since the user [doesn't] technically exist at that point

We know the user via it's social username in both spots, so keying on that is a simple option to temporarily associate the data with the user until after the identity is established. Then, the app should be able to just take the claim(s) for whatever it needs thereafter.

Too bad the approach in the social docs doesn't work. When I was playing with this yesterday, I **did** scaffold the *ExternalLogin.cshtml*/*ExternalLogin.cshtml.cs* into the app and try to save tokens/claims there ... no 🎲🎲 ... didn't work.

> session state is ephemeral and could be lost whenever, meaning it's possible the token might never end up being saved to the DB.

It seems that engineering isn't leaning that way. Javier said in the state management doc to go with the dB for server-side state management.

I had a passing thought to go with server-side caching, but caching could exhaust resources under high demand. If a dev wants to use caching, they can work that out easily enough for this approach once they see how `OnCreatingTicket` and `RevalidatingIdentityAuthenticationStateProvider.GetAuthenticationStateAsync` are being used.

>  docs only cover how to sign in using third-party identity providers, and not how to do anything with the received tokens after that

I agree. I didn't think to ask about it when we put up the Blazor authn/authz topic ... I really thought that our ASP.NET Core social doc would work. I'll generate the PR and then engineering will take a look. I'll ping u on the PR. Let me know if you have any further thoughts in the meantime.

**Comment by guardrex** [comment]
*WOOT!* :tada: I think I figured it out. Will post my *RexHacks*:tm: *soon!*

**Comment by guardrex** [comment]
@SteveSandersonMS @danroth27 You can TL;DR the whole discussion on this issue, but could you run an :eye: over this comment and provide feedback?

### The Ask

Get social login provider tokens and claims into Razor components via `AuthenticationStateProvider` using as much existing Identity infrastructure as possible.

### The Problem

Our [ASP.NET Core social auth with additional claims+tokens](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims) topic guidance just **doesn't work** for this scenario.

@hfaran and I tried several approaches ... that topic and other ideas ... but it all ended in *tears* 😢.

I came up with an approach that (apparently) works ok :point_down:.

@hfaran has an alternative that uses session, but you seem to suggest not using session for server-side state management scenarios (according to that Blazor doc).

### Let's see some *RexHacks!*:tm: 🙈 ...

*.csproj*:

```xml
<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="3.0.0" />
```

*appSettings.json*:

```json
"GitHub": {
  "ClientId": "xxxxxxxxxxx",
  "ClientSecret": "xxxxxxxxxxx"
}
```

`Startup.ConfigureServices`:

```csharp
services.AddAuthentication()
    .AddGoogle(options =>
    {
        options.ClientId = Configuration["GitHub:ClientId"];
        options.ClientSecret = Configuration["GitHub:ClientSecret"];

        // Must have this to populate the tokens ...
        options.SaveTokens = true;

        // When mapped, Google properties become claims. For example ...
        options.ClaimActions.MapJsonKey("urn:google:picture", "picture", "url");

        options.Events.OnCreatingTicket = context =>
        {
            var scopeFactory = 
                context.HttpContext.RequestServices.GetRequiredService<IServiceScopeFactory>();

            using (var scope = scopeFactory.CreateScope())
            {
                var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

                // Get Google's providerKey for this user
                var providerKey = context.Principal.Claims
                    .FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;

                // Use Google's providerKey and the LoginProvider of "Google" to
                // get this user's Identity PK
                var userId = db.UserLogins.FirstOrDefault(u => u.ProviderKey == providerKey &&
                    u.LoginProvider == "Google").UserId;

                foreach (var claim in context.Principal.Claims)
                {
                    var userClaim = db.UserClaims
                        .FirstOrDefault(c => c.ClaimType == claim.Type && c.UserId == userId);

                    if (userClaim != null)
                    {
                        userClaim.ClaimValue = claim.Value;
                    }
                    else
                    {
                        db.UserClaims.Add(new IdentityUserClaim<string>
                            {
                                UserId = userId,
                                ClaimType = claim.Type,
                                ClaimValue = claim.Value,
                            });
                    }
                }

                foreach (var token in context.Properties.GetTokens())
                {
                    var userClaim = db.UserClaims
                        .FirstOrDefault(c => c.ClaimType == token.Name && c.UserId == userId);

                    if (userClaim != null)
                    {
                        userClaim.ClaimValue = token.Value;
                    }
                    else
                    {
                        db.UserClaims.Add(new IdentityUserClaim<string>
                            {
                                UserId = userId,
                                ClaimType = token.Name,
                                ClaimValue = token.Value,
                            });
                    }
                }

                db.SaveChanges();
            }

            return Task.CompletedTask;
        };
    });
```

*Index.razor*:

```cshtml
@page "/"
@using Microsoft.AspNetCore.Components.Authorization
@inject AuthenticationStateProvider AuthenticationStateProvider
@using System.Security.Claims

<h1>Auth Testing</h1>

Username: @_user.Identity.Name

<h2>All Claims</h2>

<ul>
    @foreach (var claim in _user.Claims)
    {
        <li>@claim.Type &ndash; @claim.Value</li>
    }
</ul>

<h2>Explicit Claims</h2>

<ul>
    @if (_user.Identity.IsAuthenticated)
    {
        <li>@_user.FindFirst(c => c.Type == ClaimTypes.NameIdentifier)?.Value</li>
        <li>@_user.FindFirst(c => c.Type == ClaimTypes.Name)?.Value</li>
        <li>@_user.FindFirst(c => c.Type == ClaimTypes.GivenName)?.Value</li>
        <li>@_user.FindFirst(c => c.Type == ClaimTypes.Surname)?.Value</li>
        <li>@_user.FindFirst(c => c.Type == ClaimTypes.Email)?.Value</li>
        <li>@_user.FindFirst(c => c.Type == "urn:google:picture")?.Value</li>
    }
</ul>

@code {
    private ClaimsPrincipal _user;

    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        _user = authState.User;
    }
}
```

### Notes

* The app is based on the stock `blazorserver` 3.1 template. Nothing else added besides what I just showed :point_up:.
* This example hasn't been generalized out to other providers, but that could be done.
* Repetitive code for updating/adding claims can be reduced.
* The tokens can be loaded into Identity (`AspNetUserTokens` table of the Identity dB), but there doesn't seem any way to get them out. `ClaimsPrincipal.Properties` only ever has `.issued` and `.expires`. The tokens don't seem present anywhere from `AuthenticationStateProvider`; therefore, the options were either of ...
  * Customize the `AuthenticationStateProvider` ... decided not to mess with it because of the **_BONUS!_** (explained below).
  * Just load the tokens into claims.
* Although dup claims are ok and useful in some scenarios, I work with unique claims in the example here.
* **_BONUS!_** Turns out that this approach does *NOT* require replacing `GetAuthenticationStateAsync`. It ✨ *Just Works!*:tm: ✨ ... the claims are on `authState.User.Claims`.
* As noted by an engineering issue (that I lost the link to 🙈), renewing tokens are up to the dev to work out.

Even if this approach isn't good for [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/), is it a decent *workaround* until framework bits help with social login provider claims+tokens (if so, we can point devs to this comment)?

**Comment by danroth27** [comment]
@blowdart Can you also take a look at what @guardrex is proposing here?

**Comment by Tratcher** [comment]
`OnCreatingTicket` doesn't look like the right place for this. How does SignalR solve this? @BrennanConroy

**Comment by guardrex** [comment]
Will be opened for engineering.

**Comment by javiercn** [comment]
@danroth27 [This](https://github.com/javiercn/blazor-server-aad-sample) is the way to do/pass tokens to a blazor app
