### ISSUE TITLE
Solution caused a new problem. Funny!

### ISSUE THREAD

**Issue by henryjones000** [aspnet/AspNetCore.Docs#15179]
LOL. Now the top says "Select Web Application(Model-View-Controller), and then select Create." while the picture below says "Web Application". Please correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett

**Comment by wadepickett** [comment]
That's embarrassing I missed that.  @henryjones000, thanks for the heads up, appreciated, will fix.

**Comment by wadepickett** [comment]
@henryjones000 , updated and merged.  Thanks.
