### ISSUE TITLE
Add no-loc: [Blazor] 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15172]
See https://github.com/aspnet/AspNetCore.Docs/pull/15171 and https://github.com/dotnet/docs/issues/15141
`no-loc: [Blazor]`

**Comment by guardrex** [comment]
@CeciAc The use of `no-loc: [Blazor]` in the test topic *almost* worked.

The word "éblouissant" still shows up in ...

* The IMPORTANT note at the top of the doc.
* In a cross-linked topic title (link text).

https://docs.microsoft.com/fr-fr/aspnet/core/blazor/routing?view=aspnetcore-3.0

I'm going to go ahead and add this now to the rest of the Blazor docs, but I just wanted to let you know about those.
