### ISSUE TITLE
Rewrite DetailsModel model to use Forbid 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15174]
See #6418

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#update-details)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  is this something you could do? cc @joeaudette  is the original author, but I think he's too busy in his new job.

**Comment by serpent5** [comment]
Sure. I can sort this one.

**Comment by Rick-Anderson** [comment]
I think it's just a matter of changing all the ` return new ChallengeResult();` to `return new ForbidResult();`

Then making a Details2 page with `[allowAnon]`  and copy the following code

```
public async Task<IActionResult> OnGetAsync(Guid documentId)
{
    Document = _documentRepository.Find(documentId);

    if (Document == null)
    {
        return new NotFoundResult();
    }

    var authorizationResult = await _authorizationService
            .AuthorizeAsync(User, Document, Operations.Read);

    if (authorizationResult.Succeeded)
    {
        return Page();
    }
    else if (User.Identity.IsAuthenticated)
    {
        return new ForbidResult();
    }
    else
    {
        return new ChallengeResult();
    }
}
```

**Comment by Rick-Anderson** [comment]
The Details2 page  is just to explain what was requested in #6418

**Comment by serpent5** [comment]
Yeah, that looks right to me. We can just use `return Forbid()`, `return Challenge()` and `return NotFound()` in the newer versions to make it slightly simpler too. 

Should there be a new section in this docs page that references the `Details2` code with an explanation?

**Comment by Rick-Anderson** [comment]
> Should there be a new section in this docs page that references the Details2 code with an explanation?

Yes, I can write that - something like

## Differences between Challenge vs Forbid 

This app sets the default policy to `[require authenticated users](#require-authenticated-users)`. The following code allows anonymous users. Anonymous users are allowed to  show the differences between Challenge vs Forbid.

code here

In the preceding code:

* when the user is **not** authenticated, `ChallengeResult` is returned. When `ChallengeResult` is returned, the user is redirected to the sign-in page.
* when the user is authenticated, but not authorized, `ForbidResult` is returned. `ForbidResult` ...

**Comment by serpent5** [comment]
It looks you've pretty much done all the work in this issue's comments. Do you want me to just PR all the required code changes (which I'll run and test first)?

**Comment by Rick-Anderson** [comment]
Yes, that would be great

**Comment by serpent5** [comment]
I’m planning to do this tonight. Can I remove the pre 2.2 samples rather than update those?

**Comment by Rick-Anderson** [comment]
Keep the 2.2 samples, but don't update them. Apply the changes to the 3.0 version only.

**Comment by serpent5** [comment]
Ok, I’ll leave the 2.2 sample and update only 3.0. There are also samples for 1.0 and 2.0 in there, and the 2.2 sample is in a folder with a 2.1 suffix. Let me know if you’d like me to:

* Rename the 2.1 folders to 2.2
* Remove the 1.0 and 2.0 versions

I’ll take a thumbs up as a yes to both and radio silence as a no for both. 😄

**Comment by Rick-Anderson** [comment]
Only do this:

> Remove the 1.0 and 2.0 versions

The 2.2 code is pretty close to the 2.1 code.
