### ISSUE TITLE
What if my app is a REST API only?

### ISSUE THREAD

**Issue by Paul-Dempsey** [aspnet/AspNetCore.Docs#15177]
All the content on this page ()and pretty much the whole Net Core docs) presumes you are generating UI pages.  My app is a pure REST API with no UI.  How do a wire up error handling so that my result json is like what is described in https://tools.ietf.org/html/rfc7807 or https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#7102-error-condition-responses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you see this one :point_right: https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.0

**Comment by Paul-Dempsey** [comment]
Ha! Obviously not. I landed in the other area by web search (like everyone enters the docs).

Can we please add cross references (See Also) so we can get to the right place?

Thanks!
:- Paul

**Comment by Paul-Dempsey** [comment]
Actually, I was in the Fundamentals section, were I would expect to see information relevant for both Web apps and API apps, so the defect stands:  Fundamentals should cover both uses case, or point to the specialized Error Handling topics .The Fundamentals page has no cross references to indicate that there is more specific related information.

Thanks,
:- Paul

From: Paul Dempsey
Sent: Thursday, October 17, 2019 6:10 PM
To: aspnet/AspNetCore.Docs <reply@reply.github.com>; aspnet/AspNetCore.Docs <AspNetCore.Docs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [aspnet/AspNetCore.Docs] What if my app is a REST API only? (#15177)

Ha! Obviously not. I landed in the other area by web search (like everyone enters the docs).

Can we please add cross references (See Also) so we can get to the right place?

Thanks!
:- Paul
