### ISSUE TITLE
Route Constraint not working

### ISSUE THREAD

**Issue by Alienroid** [aspnet/AspNetCore.Docs#15185]
This example:

@page "/Users/{Id:int}"

&lt;h1&gt;The user Id is @Id!&lt;/h1&gt;

@code {
    [Parameter]
    public int Id { get; set; }
}

doesn't work on /Users?id=1
if I remove parameter and use just /Users and configure some default value for Id like public int Id { get; set; } = 2; , then the route works. Just whenever use the parameter, it fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's a query string. Do this .......

```
/Users/1
```

**Comment by guardrex** [comment]
I found an issue in engineering that says they'll probably work on making working with query strings easier ...

https://github.com/aspnet/AspNetCore/issues/11977

Feel free to comment on that issue if you want to give them additional feedback.

I also see some devs talking about it here ...

https://stackoverflow.com/questions/53786347/multiple-query-string-parameters-in-blazor-routing

**Comment by Alienroid** [comment]
Oops, you are correct. I was porting a razor page to blazor and I forgot the routing convention change from ?id=1 to /1

By the way, I think few others online also missed this. Their solution is using Microsoft.AspNet.Core.WebUtilities for querystring. Some references: https://www.mikesdotnetting.com/article/340/working-with-query-strings-in-blazor

Probably good to mention the routing convention change somewhere. I recall it was mentioned in one of the preview updates before 3.0

Thanks again!
