### ISSUE TITLE
ReceiveBufferSize may need more detail

### ISSUE THREAD

**Issue by MichaelMitchellM** [aspnet/AspNetCore.Docs#15184]
It seems unclear what `WebSocketOptions.ReceiveBufferSize` does.
This doc states that it's for performance tuning, but doesn't give any guidance on how to reason about its impact or if it will raise errors if the received message exceeds that size.

Viewing the docs for [WebSocketOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.websocketoptions.receivebuffersize?view=aspnetcore-3.0#Microsoft_AspNetCore_Builder_WebSocketOptions_ReceiveBufferSize) also doesn't give much insight into its use.

I also found a PR that seems to suggest that `ReceiveBufferSize` has been deprecated behind the scenes and is entirely ignored.
https://github.com/aspnet/WebSockets/pull/232

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.websocketoptions.receivebuffersize
Gets or sets the size of the protocol buffer used to receive and parse frames. The default is 4kb.

aspnet/WebSockets#232 removes setting it in *src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs* and uses the default.
