### ISSUE TITLE
Missing example for auto-expiration using CancellationTokenSource.CancelAfter

### ISSUE THREAD

**Issue by joaopgrassi** [aspnet/AspNetCore.Docs#15187]
You can find in the docs under the "Additional notes" section:

> Expiration doesn't happen in the background. There is no timer that actively scans the cache for expired items. Any activity on the cache (Get, Set, Remove) can trigger a background scan for expired items. A timer on the CancellationTokenSource (CancelAfter) would also remove the entry and trigger a scan for expired items. For example, rather than using SetAbsoluteExpiration(TimeSpan.FromHours(1)), use CancellationTokenSource.CancelAfter(TimeSpan.FromHours(1)) for the registered token. When this token fires it removes the entry immediately and fires the eviction callbacks. For more information, see this GitHub issue.

The GitHub linked issue is quite old (2016) and doesn't actually tell how to do it. There's a comment stating that one should use `CancellationTokenSource (CancelAfter) ` but no concrete examples are shown. 

I think this is a good use case and it should be part of the examples in the docs, not in some old GitHub issue.

I guess something like this? (following the existing samples)

```
public IActionResult CacheTryGetValueSet()
{
	DateTime cacheEntry;

	// Look for cache key.
	if (!_cache.TryGetValue(CacheKeys.Entry, out cacheEntry))
	{
		// Key not in cache, so get data.
		cacheEntry = DateTime.Now;

		// create the cancellation token source with a timer of 10 seconds
		var cts = new CancellationTokenSource();
		cts.CancelAfter(TimeSpan.FromSeconds(10));

		// Set the cache options with the expiration token.
		// When the cts fires, the entry will be removed from the cache and eviction callbacks are triggered.
		var cacheEntryOptions = new MemoryCacheEntryOptions()
			.AddExpirationToken(new CancellationChangeToken(cts.Token));

		// Save data in cache.
		_cache.Set(CacheKeys.Entry, cacheEntry, cacheEntryOptions);
	}

	return View("Cache", cacheEntry);
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.0)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by anurse** [comment]
That sample looks pretty good. I think it would work fine.

> ```csharp
> var cts = new CancellationTokenSource();
> cts.CancelAfter(TimeSpan.FromSeconds(10));
> ```

You could even simplify this since CancellationTokenSource has a constructor that takes a TimeSpan:

```csharp
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
```

**Comment by Rick-Anderson** [comment]
@joaopgrassi  much appreciated. You suggestion will be live in an hour. This was very helpful, keep them coming.

**Comment by Rick-Anderson** [comment]
@joaopgrassi  BTW, I removed comments because they aren't translated.

**Comment by joaopgrassi** [comment]
@Rick-Anderson awesome! thanks for adding it :)
