### ISSUE TITLE
Check MySql support on .net core 3.0

### ISSUE THREAD

**Issue by meriturva** [aspnet/AspNetCore.Docs#15186]
With version 8.0.18: https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0-18.html
seems that .net core 3 is supported now!

But I have to say I will for sure test compatibility next weeks!

Source link: https://github.com/aspnet/AspNetCore.Docs/blob/live/aspnetcore/migration/22-to-30.md

ref: https://github.com/aspnet/AspNetCore.Docs.it-it/issues/41

**Comment by guardrex** [comment]
Please use the **This Page** feedback button at the bottom of the topic to open a new issue. It adds metadata and automatically pings the author. No worries ... I'll paste it in here ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
