### ISSUE TITLE
 Razor file compilation doesn't work for changes in referenced razor libraries.

### ISSUE THREAD

**Issue by jjamid** [aspnet/AspNetCore.Docs#15181]
Is there a way to make it work  ?

It also doesn't work when the debugger is attached (at least in Blazor server app).
I think it's worth mentioning in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I wouldn't expect it to work in referenced libs.

**Comment by cesee** [comment]
What ?! 
This is not an external library. This is my library which is part of the solution (of course I am not talking about a referenced package or dll....).
Of course you would expect it to work also there.

I would appreciate it if you re-open the issue.

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  please respond

**Comment by pranavkm** [comment]
We have a sample that shows making RuntimeCompilation work across projects here: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/runtimecompilation.

**Comment by cesee** [comment]
> We have a sample that shows making RuntimeCompilation work across projects here: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/runtimecompilation.

1. The sample code doesn't work. A runtime error is thrown while trying to use the Error component.

`The type or namespace name 'ErrorViewModel' could not be found (are you missing a using directive or an assembly reference?)`

It is because there is no using statement in the generated class
```namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
```

It seems the imports inside the component library_ViewImports.cshtml are not respected.
`@using MyClassLib.Models`

Adding the using statement to the app project's _ViewImports fixes the issue.
```
@using MyApp   
@using MyClassLib.Models <-
```

This looks like a bug to me.

2. I already tried the approach suggested but I can't make it work in my Blazor server application.
```
 builder.AddRazorRuntimeCompilation(options =>
 {
                    var libraryPath = Path.GetFullPath(Path.Combine(env.ContentRootPath, "..", "MyClassLib"));
                    options.FileProviders.Add(new PhysicalFileProvider(libraryPath));
});
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
