### ISSUE TITLE
Note that Configuration.GetValue<T> doesn't support scenarios where T is an array

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore.Docs#15182]
Example `appsettings.json`:

```json
{
  "MySettings": {
    "Domains": [
      "https://www.example.com",
      "https://www.github.com"
    ]
  }
}
```

Attempting to read this setting in the following way does not work:

```csharp
var myDomains = Configuration.GetValue<string[]>("MySettings:Domains"); // myDomains is null
```

The documentation should be updated to reflect this, as it's not obvious that this will not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#json-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @IanKemp ... Yes, it doesn't work with any collection. Two added words will fix this ... "value" to "single value" and "type" to "noncollection type." Thanks for calling it out.
