### ISSUE TITLE
Continue to use AddAuthorization + ref PolicyDLL unless you don't want to use Policy DLL, then use AddAuthorizationCore

### ISSUE THREAD

**Issue by wstaelens** [aspnet/AspNetCore.Docs#15189]
for .net core 3.0:
according to https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio we need to use AddAuthorizationCore instead of AddAuthorization. but this example uses AddAuthorization.

Also the examples on other documentation pages don't show that we should add ".AddRoles&lt;…&gt;()" 
This works without .AddRoles (it it required?).

Also in the migration 2.2 to 3.0 docs tells us to "Replace UseMvc or UseSignalR with UseEndpoints." but this example still uses .UseMvc …

all these differences are very confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  if you can outline the changes needed for the 3.0 version I'll get someone to update this doc.

**Comment by blowdart** [comment]
Oh it's in the AddRoleServices section? @Haok

**Comment by HaoK** [comment]
I think the migration guide might be slightly misleading, people should continue to be using AddAuthorization, they just might need to reference the Policy dll.  Its only if for some reason they really don't want the Policy dll, that they would switch to using AddAuthorizationCore.

The AddRoles call is needed for to get identity to add the role claim, depending on how the app is setup before, it might not be needed.  The default AddDefaultIdentity does not setup roles which is what this doc might be targetting I think

**Comment by HaoK** [comment]
I guess the migration guide states this clearly enough, so I think its fine, just slightly confusing I guess
