### ISSUE TITLE
info missing about scaffolded Identity and areas

### ISSUE THREAD

**Issue by wstaelens** [aspnet/AspNetCore.Docs#15188]
I had scaffolded Identity. 
My add had an Admin area where the HomeController of the Admin area contains a [Authorize] attribute using a custom policy.

Each time I want to site.com/Admin I saw a redirection to /Identity/Account/Login?ReturnUrl=%2Fadmin
but the content of the scaffolded Identity page was empty.

When I tested with allowanonymousattribute instead of the autorize, my area routing was working. 

Turns out you need to add "app.UseEndpoints(endpoints =&gt; { endpoints.MapRazorPages(); });".
The endpoints.MapRazorPages() is required to get the authorization working, but documentation is not very clear on this.
There is also no info if scaffolded identity pages need updates or not.

It is also not clear if we need to use services.AddAuthorization or if we need to use services.AddAuthorizationCore  (difference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> There is also no info if scaffolded identity pages need updates or not.

We only provide a list of what has changed, not what has **not** changed.

> It is also not clear if we need to use services.AddAuthorization or if we need to use services.AddAuthorizationCore (difference?)

See [AddAuthorization moved to a different assembly](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#addauthorization-moved-to-a-different-assembly)
