### ISSUE TITLE
AutoValidateAntiforgeryTokenAttribute for Razor Pages

### ISSUE THREAD

**Issue by yzorg** [aspnet/AspNetCore.Docs#15202]
My Razor Pages app doesn't use `AddMvc(..)`.  Would `AutoValidateAntiforgeryTokenAttribute` filter work for Razor Pages app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.0#)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @yzorg ... It should. This topic is very MVC-ish. :smile:

@Rick-Anderson will determine if it should (at least) have a Razor Pages example. In addition to the attribute on a page model (`[ValidateAntiForgeryToken]`), we could also show the convention, which I think goes like this ...

```csharp
services.AddRazorPages(options =>
{
    options.Conventions.ConfigureFilter(new AutoValidateAntiforgeryTokenAttribute());
});
```

Test that tho ........ I may have just *made that up!* :smile:

**Comment by guardrex** [comment]
btw @Rick-Anderson ... I need to hit https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions. I updated the sample app but missed a few spots in the topic itself. I'll open an issue and knock that out quickly.

I think the same perhaps applies to https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-3.0 ... I'll leave that for you/the team tho.

**Comment by Rick-Anderson** [comment]
Yes,the update needs RP samples. See #13394

**Comment by serpent5** [comment]
Razor Pages are automatically protected from CSRF.

**Comment by guardrex** [comment]
https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.RazorPages/src/DependencyInjection/MvcRazorPagesMvcCoreBuilderExtensions.cs#L105-L106

**Comment by guardrex** [comment]
There's already a NOTE in the XSRF/CSRF topic ...

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.0#aspnet-core-antiforgery-configuration

... and there's this section in the RP topic ...

https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index?view=aspnetcore-3.0&tabs=visual-studio#xsrfcsrf-and-razor-pages

... so that point seems fairly well covered.

**Comment by serpent5** [comment]
@guardrex Yes, I agree. I may have misunderstood but the original question here seemed to be about adding the filter for RP but I was just pointing out that it isn’t needed.

**Comment by guardrex** [comment]
I think we're on the same page ... I recall now what u were saying about it being ✨.

I recommend closing this given that the coverage is there, and we have new issues for the 3.0 pass on both topics.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/67149046-4e7ba480-f242-11e9-94dc-cad1e3a89ff7.png)
