### ISSUE TITLE
Guard against multiple dispatches example

### ISSUE THREAD

**Issue by JDBarndt** [aspnet/AspNetCore.Docs#15205]
When testing this, the button never is disabled in my project. Using VS 2019 16.3.5 (non-preview). Created a fresh Blazor Server project from File -&gt; New Project and updated the FetchData page with the example code provided.

I found a workaround by adding "await Task.Delay(1)" after isLoading = true line, then the button is disabled properly while the updated forecast data is retrieved.

Why is this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a9f84a-feaa-d2b0-409a-01f75f9101a0
* Version Independent ID: aeec639f-a9d6-2f00-b61f-2c316ef6afb6
* Content: [Secure ASP.NET Core Blazor Server apps](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/blazor/server.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JDBarndt ... That sounds like a framework bug 🐞 ... open an issue for the engineers on their repo 👉 https://github.com/aspnet/AspNetCore/issues.

**Comment by emumanu** [comment]
It seems like it is not a bug:

https://github.com/aspnet/AspNetCore/issues/15170

Please update the documentation.

**Comment by guardrex** [comment]
Ok ... thx ... I’ll put an 👁 on it ASAP.

**Comment by guardrex** [comment]
I reviewed the engineering issue. It looks like they decided not to make changes to the template. We most definitely need to call out more clearly ...

> The pattern specifically works if work's being done asynchronously. 

I'll ping u on the PR.

**Comment by emumanu** [comment]
Yeah, if it does not work synchronously it should be clearly specified, because even if the async virus is spreading through the classes a lot of people prefer using synchronous calls. 

Also, explaining the underlying reason for that behaviour would be nice. And If there is a workaround, it should also be documented.
