### ISSUE TITLE
Need document about how to use Razor Page and WebApi in one project

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#15210]
It is useful When I create a Razor page that using ajax to do some http requst

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your suggestion. See the articles under **Single Page Apps** like https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular

**Comment by TangMonk** [comment]
I do not need Angular or React, The Razor Page is fine, I do not want change. 

So there is no way to use both WebApi and Razor Page?

**Comment by Rick-Anderson** [comment]
Yes, follow https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start and add the RP code
