### ISSUE TITLE
Exactly what is a Shared cache?

### ISSUE THREAD

**Issue by Serexx** [aspnet/AspNetCore.Docs#15214]
The massive warning about "Using a /shared/ memory cache from Dependency Injection" is appreciated, but nowhere can I find a definition of exactly what that is, whether its is by definition anything instantiated via DI or simply a cache not given a specific name. I'll figure it out by fiddling and/or reading elsewhere but shouldn't have to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by TheEcMan** [comment]
Agreed. If you figured out it means, please let us know
