### ISSUE TITLE
Browser SameSite changes

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#15223]
@Rick-Anderson to triage.

* https://github.com/aspnet/Announcements/issues/390
* https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

There are a number of topics that might require attention besides this one (*Cookie auth w/o Identity*) :

* Migration (for 3.1)
* Other security topics (e.g., Identity, OpenIdConnect)
* App state topic: Session options `SessionDefaults.SameSite`
* GDPR `CookiePolicyOptions`
* `options.MinimumSameSitePolicy` appears in about 59 sample apps

cc: @blowdart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Closing since this is covered.
