### ISSUE TITLE
add `add nuget package Microsoft.Extensions.Caching.StackExchangeRedis` to doc

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#15226]
Otherwise, we will confuse about import this package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.0#distributed-redis-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's covered in the *Prerequisites* section of the topic ...

https://docs.microsoft.com/aspnet/core/performance/caching/distributed#prerequisites
