### ISSUE TITLE
Formatter for Google.Protobuf

### ISSUE THREAD

**Issue by lkishor** [aspnet/AspNetCore.Docs#15235]
**First-Party support for Protobuf Formatter**

- I am looking for First-Party support for Protobuf Formatter within .Net Core Web API.

- Using Protobuf with Web API's should be a possible option, while still maintaining shared Contract as .proto files.
- This can be added as an Example at [https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-3.0](url)
- Or can be Provided as a Separate Nuget Package

While it is great to see gRPC support in .Net Core 3.0, Though support on Mobile Platform is still very limited. Protocol Buffers with Web API can provide a second-option to do contract-based data access.

**Comment by Rick-Anderson** [comment]
Can you open this issue in https://github.com/aspnet/AspNetCore/issues
