### ISSUE TITLE
Confirm/update WS topic for Worker SDK

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#15230]
From @caioproiete ...

> Update the sample code linked to Host ASP.NET Core in a Windows Service to use the new Microsoft.NET.Sdk.Worker project SDK introduced with .NET Core 3.0

&dagger;`needs-more-info` &ndash; In addition to updating the SDK, take a look at the added MS Build props from the [3.0 PR](https://github.com/aspnet/AspNetCore.Docs/pull/12449). Confirm publish/run behaviors. The 3.0 template produces ...

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
  </ItemGroup>
</Project>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher This is a good time to ask: Should the topic's sample shed all of its **_web app_** characteristics and just become a UI-less background processor service? If so, two options are:

* Add a section at the end of the topic that explains what to add to a worker template-based app that will allow the service to serve pages.
* Have two sample apps: one based directly on the worker service template and one like the current sample (a *web app*-capable service).

**Comment by caioproiete** [comment]
IMHO: It would be nice to have separate sample apps demonstrating how to build Windows Services using .NET Core 3.0 - all of them using the new `Microsoft.NET.Sdk.Worker` project SDK: 

* Windows Service with background workers only (no dependency on AspNetCore)
* Windows Service hosting an ASP .NET Core app (examples using Kestrel & HttpSys)
* Windows Service hosting an ASP .NET Web API (examples using Kestrel & HttpSys)

**Comment by Tratcher** [comment]
Having two makes some sense, one with and one without web components. @caioproiete I don't know why you'd want a separate sample for a Web API, that's not any different at the hosting layer.

**Comment by caioproiete** [comment]
@Tratcher A project hosting a couple of Web API endpoints (_only_) ends up being much simpler and cleaner to follow... Less code on `Startup`, no Razor views, no `wwwroot` with CSS and JS files, etc...

I'd say it's particularly useful for devs coming from other stacks who are used to spinning up a quick webserver project with some REST endpoints say, in Python + Flask, and would like to try it in .NET Core.

At the same time, I think having a full web app hosted in a Windows Service *without IIS* is the _holy grail_ for existing .NET developers and too valuable not to to have as a sample app.

**Comment by Tratcher** [comment]
But the relevant parts of the sample for a Windows Service are in Program.cs and are exactly the same. It doesn't matter what's in Startup.cs. There are plenty of other samples to demonstrate the difference between the various application models controlled in Startup.
