### ISSUE TITLE
This feature should added default with using dotnet new mvc/web 

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#15234]
This feature should added default with using dotnet new mvc/web 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @TangMonk ... that's product unit feedback. We only work on the docs here. Check for an open (or closed) issue on the engineering repo. If you don't find an existing issue to comment on, then open a new issue with them.

https://github.com/aspnet/AspNetCore/issues
