### ISSUE TITLE
You can't stop the signal

### ISSUE THREAD

**Issue by jrummell** [aspnet/AspNetCore.Docs#15236]
I just want to say that I appreciate the Serenity quotes. Keep it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#custom-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback. Yeah ... you'll find a fair number of Star Wars, Star Trek, Serenity, and Dr. Who examples in topics that I worked on. :smile: ... Well, they *didn't stop me on review!* :smile: lol

...... and I'm sad that we didn't get a sequel to that movie. :cry: *Serenity* is such a great film.
