### ISSUE TITLE
Social authentication without Identity

### ISSUE THREAD

**Issue by ricardoromaobr** [aspnet/AspNetCore.Docs#15246]
How I read the providers  to show in my login page?
When I'm using Identity I use SignInManager.GetExternalAuthenticationSchemesAsync(). 
But SignInManager  is part of Idnetity? I'm right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9d7ad5-47d6-80bf-88fe-fac3a74151a3
* Version Independent ID: e64816f4-3391-5aab-31c2-ab4f915bc7f6
* Content: [Facebook, Google, and external provider authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/social/social-without-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/social-without-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`SignInManager` is used in the authentication templates.  See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity
to generate all the code and look for `SignInManager`

**Comment by ricardoromaobr** [comment]
But in this case I want to use without the identity. Like the intention of the title of the documentation
[Use social sign-in provider authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.0). If I use SignInManager it will use the Identity. Would you complete this example  to be more clear, please.

**Comment by ricardoromaobr** [comment]
The [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.0) is fantastic example, Make an example like this would be great!I can dowaloaded and run and change to learn with example. :)
