### ISSUE TITLE
Asp.net core 3.0 swagger throws error

### ISSUE THREAD

**Issue by praveenlearns** [aspnet/AspNetCore.Docs#15240]
I am using asp.net core 3.0 on .net core 3.0 api project. I have installed preview version '5.0.0-rc4 of Swashbuckle.AspNetCore. 

Added this code
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();          
        
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
            });       

        }
```
and this
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseStaticFiles();

            #region swagger middleware

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
                c.RoutePrefix = string.Empty;
            });
            #endregion
         // more code .............
}
```

it just throws this error with no other clues. Could you please help?

Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll but was not handled in user code

Screenshot of error.

![image](https://user-images.githubusercontent.com/40520335/67232449-04233f00-f45f-11e9-9d1c-077275ab58e0.png)

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
