### ISSUE TITLE
SQLServer Distributed Session State times out

### ISSUE THREAD

**Issue by ndenkha** [aspnet/AspNetCore.Docs#15255]
Hi,

I've opened this StackOverflow issue yesterday and want to share it here too for any help possible.
https://stackoverflow.com/questions/1553645/pros-and-cons-of-sticky-session-session-affinity-load-blancing-strategy

The issues I'm facing are:

1. The session times out in a web farm environment.
2. The SessionState table doesn't clear when calling session.Clear() or session.Remove(..)
3. The ID column in the SessionState holds a GUID that doesn't match the session.Id value, so what is this GUID? and how do I get it so I can call cache.Remove(id)?

I've followed all of your instructions yet the session continues to timeout, so please help point me in the right direction.

Thanks,

Ninos

**Comment by guardrex** [comment]
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Note @ndenkha that it's best to open this using the **This Page** feedback button/form at the bottom of the topic. It adds the metadata and pings the author. No worries ... I added it ☝️.

**Comment by Rick-Anderson** [comment]
. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
> The session times out in a web farm environment.

Per the article
The app retains a session for a limited time after the last request. The app either sets the session timeout or uses the default value of 20 minutes.

> The SessionState table doesn't clear when calling session.Clear() or session.Remove(..)

Per the article

Session data is deleted either when the ISession.Clear implementation is called or when the session expires.

**Comment by ndenkha** [comment]
Thanks, @guardrex for adding the feedback. But, I don't see any feedback section anywhere.

@Rick-Anderson please read my StackOverflow question. The app times out after a few seconds. 
And like I stated, I AM calling ISession.Clear but no data gets deleted.

**Comment by Rick-Anderson** [comment]
>  But, I don't see any feedback section anywhere.

Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by guardrex** [comment]
It's at the bottom of the topic .... it should be anyway ...

<img width="372" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/67329762-ebf40400-f4e0-11e9-9b1b-81fede51f2b2.PNG">

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson please read my StackOverflow question. The app times out after a few seconds.
And like I stated, I AM calling ISession.Clear but no data gets deleted.

Create the simplest possible sample that reproduces this problem and submit a product bug.  I know lots of customers are successfully using session and clear in web farms (with affinity).

**Comment by guardrex** [comment]
Submit to ... https://github.com/aspnet/AspNetCore/issues
