### ISSUE TITLE
Unintentional reference to deprecated IHostingEnvironment

### ISSUE THREAD

**Issue by IGx89** [aspnet/AspNetCore.Docs#15257]
Hello! The following documentation note about HostBuilder says it injects IHostingEnvironment into Startup's constructor, which is deprecated. I'm guessing you meant to say IWebHostEnvironment instead?

> The most significant change from WebHostBuilder to HostBuilder is in dependency injection (DI). When using HostBuilder, you can only inject IConfiguration and IHostingEnvironment into Startup's constructor. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-startupconfigure)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by guardrex** [comment]
It should be both ... `IHostEnvironment` and `IWebHostEnvironment` are ok, along with `IConfiguration`. 

https://github.com/aspnet/Announcements/issues/353

I'll fix it as soon as I'm done *beating Azure AD with certs* into submission. :smile: Thanks for the report @IGx89.
