### ISSUE TITLE
Incorrect link in TOC for JavaScript API Reference

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore.Docs#15261]
The following link:

![image](https://user-images.githubusercontent.com/14079228/67327235-9d953400-f4e5-11e9-91a1-73d043a1d377.png)

Is pointing to: https://docs.microsoft.com/en-us/javascript/api/?view=aspnetcore-3.0

But I went to edit https://github.com/aspnet/AspNetCore.Docs/edit/master/aspnetcore/toc.yml it has the correct value

![image](https://user-images.githubusercontent.com/14079228/67327353-cc130f00-f4e5-11e9-9069-0cd68fe6bc9e.png)

Correct link (I think): https://docs.microsoft.com/en-us/javascript/api/?view=signalr-js-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by spottedmahn** [comment]
Hi @scottaddie - I didn't know where to open an issue related to the TOC so I opened it here.  Thoughts?

**Comment by guardrex** [comment]
The link is correct ... the problem is that 3.0 API topics aren't available yet. Therefore, nothing (no namespaces) load. This will be resolved when the 3.0 API is available. They're working on it right now, so I think it will be fairly *soon-ish-maybe-if-they-don't-hit-big-probs*.

**Comment by spottedmahn** [comment]
>the problem is that 3.0 API topics aren't available yet

oh, ok, thanks for reviewing @guardrex 👍

>I think it will be fairly soon-ish-maybe-if-they-don't-hit-big-probs.

😂, I like that, you should trademark that 😊

**Comment by scottaddie** [comment]
@spottedmahn Thank you for the heads up. I've started an internal discussion to get the updated APIs published.
