### ISSUE TITLE
Great tutorial, but LocalDB is a dead end for Azure

### ISSUE THREAD

**Issue by keylimesoda** [aspnet/AspNetCore.Docs#15260]
Would be great to have this tutorial updated in a way that you could eventually deploy your app to Azure.

As is, the localDB doesn't migrate with the application leaving it in a broken state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Just change the connection string. There are plenty of deploy to azure tutorials and we don't want to duplicate content.
