### ISSUE TITLE
AuthorizationFilterContext no longer relevant in .NET Core 3.0

### ISSUE THREAD

**Issue by IGx89** [aspnet/AspNetCore.Docs#15263]
The last section in these docs talks about using AuthorizationFilterContext in HandleRequirementAsync, but context.Resource doesn't appear to be AuthorizationFilterContext anymore in .NET Core 3.  See https://github.com/aspnet/AspNetCore/issues/11075. I would love to see updated documentation for .NET Core 3 showing specifically how to access RouteData -- currently migrating a 2.2 webapp to 3.0 and that's one of the issues that came up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  I thought we updated this but must have been another doc.

**Comment by Rick-Anderson** [comment]
@IGx89 Was this addressed in https://github.com/aspnet/AspNetCore.Docs/pull/15103/files - which got brought over to #15120
cc @damienbod

**Comment by IGx89** [comment]
Not that I could see

**Comment by serpent5** [comment]
This is being discussed in https://github.com/aspnet/AspNetCore.Docs/issues/12564. There's some sample code in a _draft_ PR against that issue, but it's awaiting feedback on whether or not that is the recommended approach.

**Comment by Rick-Anderson** [comment]
Draft PR being #15218

**Comment by IGx89** [comment]
Thanks! I'll add a comment on that PR with an example. So far from playing with its code, it doesn't appear to demonstrate a way to access RouteData yet.

**Comment by Rick-Anderson** [comment]
Moved to #16191
