### ISSUE TITLE
Does not seem to add ProductResponseType(typeof(...), StatusCodes200OK)

### ISSUE THREAD

**Issue by jawn** [aspnet/AspNetCore.Docs#15269]
Is this supposed to add suggestions for Status code 2xx with their return types?

It does not seem to add ProductResponseType(typeof(...), StatusCodes200OK))

E.g. when I modify the example to the version below, I would expect a suggestion to add the commented line again.
```
// GET api/contacts/{guid}
[HttpGet("{id}", Name = "GetById")]
// [ProducesResponseType(typeof(Contact), StatusCodes.Status200OK)] --&gt; commented this line
public IActionResult Get(string id)
{
    var contact = _contacts.Get(id);

    if (contact == null)
    {
        return NotFound();
    }

    return Ok(contact);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
@jawn  are you saying the MVC analyzers package should flag that?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/67431339-c538da80-f57f-11e9-99f3-4618c906b0da.png)

**Comment by jawn** [comment]
Yes.

Motivation:
- The existing functionality is good to start. 
- However, flagging the happy flow 200 return type is what is really completes the picture. This type will typically differ between web apis.

**Comment by Rick-Anderson** [comment]
@jawn  that's not a doc bug, that's a product bug.  See https://github.com/aspnet/AspNetCore/blob/master/CONTRIBUTING.md to open a product bug.
