### ISSUE TITLE
HTTP/2 TLS on MAC and Windows 7

### ISSUE THREAD

**Issue by dichaos** [aspnet/AspNetCore.Docs#15274]
Is this something you are looking to support in the future ?

Turning off all security to make this work is not a workaround.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
Hello @dichaos ... This is a question for the product unit (we only handle docs here), so open it over on their repo. Before you open an issue there, search open **and closed** issues first given that it might already be something under discussion.

https://github.com/aspnet/AspNetCore/issues

**Comment by JamesNK** [comment]
ASP.NET Core uses the operating system for HTTP/2 TLS support. macOS may support hosting servers with HTTP/2 TLS in the future, Windows 7 will not.
