### ISSUE TITLE
Is there a recommendation for disposing KeyVaultClient?

### ISSUE THREAD

**Issue by biltongza** [aspnet/AspNetCore.Docs#15278]
KeyVaultClient implements IDisposable. Our code analysis is warning us to ensure that it gets disposed. Is there a recommended way to do this? I figure it doesn't actually matter in this instance but I wanted to ask to be sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @biltongza ... the AKV provider will dispose of any objects that it creates on its own (for example HTTP clients for interacting with the KV REST API behind-the-scenes). So no ... if you use the provider OOB as described in the topic (possibly with the `KeyVaultClient` that's available depending on what you're doing), you shouldn't need to worry about object disposal. But having said that, let's ask if there are any caveats that the topic should call out (or corrections to what I just said). @anurse

**Comment by anurse** [comment]
We don't dispose of the client, but I would agree with @guardrex that it's not necessary here unless you're seeing *specific problems* relating to the client sticking around in memory. We need to keep using it to reload config, so it can't be disposed until the app shuts down.

If you do want to discuss adding logic to dispose the KeyVaultClient, I'd suggest filing that here: https://github.com/aspnet/Extensions/issues

**Comment by guardrex** [comment]
Thanks @anurse.

@biltongza ... We'll keep an :ear: open for additional asks about this and probably react if we get more pings.
