### ISSUE TITLE
Is it a good practice to add comments in appsettings.json

### ISSUE THREAD

**Issue by eurojulien** [aspnet/AspNetCore.Docs#15276]
JSON doesn't support comments .
But comments can be added to appsettings.json file without a problem

Base on this thred, https://github.com/aspnet/AspNetCore.Docs/issues/11114, 
json parser in .NET Core  3.0 will support comments.

As in .NET Core 2.0 and higher versions, is it a good practice to do so?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Not supported last I heard, but that was a while ago. @JamesNK surely has the latest scoop on this.

**Comment by guardrex** [comment]
@eurojulien He might be unavailable right now. Last I heard (given the spec), comments in JSON files aren't supported. Therefore, not recommended ... even if the framework doesn't :boom: with their presence.
