### ISSUE TITLE
Move GetNextUserGeneratePW inside loop

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15286]
See  `GetNextUserGeneratePW` [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#additional-resources)

```
public static async Task Initialize(IServiceProvider serviceProvider, string userList)
{
    using (var context = new ApplicationDbContext(
        serviceProvider.GetRequiredService<DbContextOptions<ApplicationDbContext>>()))
    {
        var userPW = GetNextUserGeneratePW(userList);   // MOVE INSIDE LOOP
        while (userPW.user != null)
        {
            var userID = await EnsureUser(serviceProvider, userPW.password, userPW.user);
            NotifyUser(userPW);
            userPW = GetNextUserGeneratePW(userList);   // FIX ME
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#additional-resources)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  are you interested in PRing this to move `GetNextUserGeneratePW` inside the loop so it's not used twice. That seems more elegant.

**Comment by serpent5** [comment]
Sure. `userList` is a `string` rather than a `List<string>`. If we change that, it could be used with a `foreach` rather than a `while`. There's a few other things I think could be improved, too.

How would you like me to proceed?:

1. List the suggestions here.
2. Make a PR with the suggestions.
3. Make a PR with minimal changes to get the `while` loop to work.

**Comment by Rick-Anderson** [comment]
Make a PR with minimal changes to get the while loop to work.
