### ISSUE TITLE
Integration testing when using Windows Authentication and the [Authorize] attribute?

### ISSUE THREAD

**Issue by dfoulk** [aspnet/AspNetCore.Docs#15285]
We are trying to use the information in this documentation to setup integration testing in our project. We are using the baked-in Windows Authentication in our .NET Core API (Kerberos, Negotiate, etc.). There is no mention in this document on how to make the above work when using this authentication.

We would love some explanation on how to enable the functionality of the tests above when using windows authentication :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#test-app-organization)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
For a tip see :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/14592

**Comment by dfoulk** [comment]
@guardrex 🍻 thanks! That kinda resembles how we mock Identity in our unit tests- I love it!

**Comment by guardrex** [comment]
Since this will be covered by #14592, let's close this as a dup. I should (*hope* 🤞) to get to that issue this weekend (10/26-10/27).
