### ISSUE TITLE
Documentation for DI and static classes

### ISSUE THREAD

**Issue by Vijay-Nirmal** [aspnet/AspNetCore.Docs#15282]
There is no official documentation for logging in a static class. Documentation about logging in static class is much appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This doesn't really pertain to logging ... it's more of a general DI question (I updated the title and metadata.) Your best bet is just to shoot the service into the method ...

```csharp
public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        MyStaticClass.MyMethod(_logger);
    }
}

public static class MyStaticClass
{
    public static void MyMethod(ILogger logger)
    {
        logger.LogInformation("Logged from MyMethod!");
    }
}
```

**Comment by anurse** [comment]
It's really risky to access DI from static classes like that. If the DI container is disposed, so are all the services.

If you want to log from static classes, either pass a logger in like @guardrex showed, or create a static `LoggerFactory`. Be aware: if you use a static `LoggerFactory`, those loggers are in a completely different world and won't participate in any of the configuration you have.

In general, the DI/Logging/etc. infrastructure are designed to avoid static classes. I'd be curious **why** you have a static class here. If you're using the normal DI/Logging system, a Singleton service is a more appropriate way to have a "static" like this.

**Comment by guardrex** [comment]
Thanks, I'll see if I can wordsmith that into a new section in the DI topic in November.

**Comment by Vijay-Nirmal** [comment]
We have some static helper class that we can't make it as a singleton service via DI. Currently, we configure logger in `WebHostBuilder` using `ConfigureLogging()` and assigning the `LoggerFactory` instance to a static Logger class.

```csharp
public Startup(IConfiguration configuration, ILoggerFactory loggerFactory)
{
    _configuration = configuration;
    Logger.LoggerFactory = loggerFactory;
}
```

But in 3.0 we can't get `LoggerFactory` instance in constructor of startup class

**Comment by anurse** [comment]
You could move the initialization a little later, if the static class is isn't needed immediately. We removed injection of arbitrary types into the `Startup` class (because that required two containers which was confusing to users) but we still inject arbitrary types into the `Configure` method itself (*not* `ConfigureServices`, since the DI container isn't set up yet). Or you can register an `IHostedService` instance in DI that receives the logger and stores it on a static.

I'd definitely strongly encourage you to consider refactoring so that you *can* use a singleton service. A static class accessing logging like this introduces global state that can be difficult to reason about. Is there a particular reason it can't be a singleton service?

**Comment by Vijay-Nirmal** [comment]
I will check with the team for "**Why**"

Will you recommend below method? 

```csharp
public void ConfigureServices(IServiceCollection services)
{
    var configuration = services.FirstOrDefault(x => x.ServiceType == typeof(IConfiguration));

    var serviceCollection = new ServiceCollection();
    serviceCollection.Add(configuration);
    serviceCollection.AddLogging(); // Custom Logger
    var serviceProvider = serviceCollection.BuildServiceProvider();
    StaticLogger.LoggerFactory = serviceProvider.GetService<ILoggerFactory>();

    // Configure other services
}
```

**Comment by anurse** [comment]
That will create a completely separate set of loggers, but it would likely work.
