### ISSUE TITLE
Migration issue after scafolding. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

### ISSUE THREAD

**Issue by ggraur** [aspnet/AspNetCore.Docs#15283]
HI, I'm new in MVC, Razor Pages(CRUD).
Trying to fallow up the  example https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio.
 after scaffolding, when i'm trying to execute the both commands 
 
Add-Migration InitialCreate
Update-Database

i get an error:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

the error is with sql connection, i already configured tcp protocols, allowed the tcp ports trough firewall, but with no success till now.
All suggestions are welcome ...
thanks,

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Rick-Anderson** [comment]
Next time create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by ggraur** [comment]
Hi Rick Anderson.
Thanks for you reply
