### ISSUE TITLE
Code snippet link is broken

### ISSUE THREAD

**Issue by Lauyea** [aspnet/AspNetCore.Docs#15295]
In [this](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-3.0&tabs=visual-studio#apply-the-migration) chapter, the following code snippet is missing.

![code snippet missing](https://user-images.githubusercontent.com/51250275/67447791-9d14ae80-f647-11e9-9f51-72a9e4877341.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-3.0&tabs=visual-studio#fix-the-foreign-key-constraints)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for notifying us. The fix should be live in 24-48 hours.
