### ISSUE TITLE
Add more information on the new endpoint routing

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15298]
Need expanded coverage of endpointing routing changes to 3.0 - how they work, how they differ from 2.1 and previous routing.

currently have

An endpoint defines a delegate to process requests and a collection of arbitrary metadata. The metadata is used to implement cross-cutting concerns based on policies and configuration attached to each endpoint.
Add to that

For example, an Authorization Middleware can interrogate the endpoint's metadata collection for an `[authorization policy](xref:security/authorization/policies#applying-policies-to-mvc-controllers)`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ShaneCourtrille** [comment]
Especially important as https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#routing-startup-code is pointing at this documentation for how to go from 2.2 to 3.0 :)

**Comment by bobbyrowe22** [comment]
Im not sure where the section ends> "Endpoint routing differences from earlier versions of routing"
From the standpoint of someone learning routing from scratch this section probably just confuses the subject. Do i skip this section?

**Comment by webczat** [comment]
well endpoint routing seems to be the new thing that should be used for all routing, but most examples are for 2.2 and earlier, mvc documentation still uses UsemVC etc etc. confusing
