### ISSUE TITLE
JavaScript scheduler framework is not being displayed in a page.

### ISSUE THREAD

**Issue by jhunexjun** [aspnet/AspNetCore.Docs#15299]
There's no scheduler written in Blazor as of the moment that satisfy my requirement and open source or free of use. So I decided to use Syncfusion scheduler (JavaScript Essential 1) written in JavaScript.  So now, when I load a certain Blazor component it doesn't load. However, if this is placed inside the _Host.cshtml

`<div style="float: left" id="Schedule1"></div>`

It just load everything. I know this is Blazor intended for Single Page Application and this JS scheduler is not for SPA. But is there a way a can still load or call the Scheduler when the component is loaded?

**Comment by guardrex** [comment]
Hello @jhunexjun ... this sounds more like an issue for the product unit to address. Open it on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues ...**but** be sure to search open **and closed** issues before you open a new issue to make sure that someone else hasn't already asked.
