### ISSUE TITLE
asp-append-version is not only available for img tag

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#15297]
it also available for script and style link, please note

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09866f1-f286-b98c-1073-e402a10f35d3
* Version Independent ID: 18653de6-49b6-3f75-0392-b5eba55145ad
* Content: [Image Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/image-tag-helper?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper for scripts
