### ISSUE TITLE
Does AddKeyPerFile Need to Call SetBasePath?

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore.Docs#15300]
The JSON configuration provider also uses a physical file provider and it is not required to call `SetBasePath` as far as I can see (`CreateDefaultBuilder` does not call it). However, when looking at the documentation for `AddKeyPerFile`, this sample code is given:

```c#
.ConfigureAppConfiguration((hostingContext, config) =&gt;
{
    config.SetBasePath(Directory.GetCurrentDirectory());
    var path = Path.Combine(
        Directory.GetCurrentDirectory(), "path/to/files");
    config.AddKeyPerFile(directoryPath: path, optional: true);
})
```

Is `SetBasePath` really required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
https://github.com/aspnet/Extensions/blob/d656c4f7e22d1c0b84cab1b453c50ce73c89a071/src/Hosting/Hosting/src/HostBuilder.cs#L191

Seems to be just an inadvertent holdover from a prior version of the sample code (before there was any such thing as `ConfigureAppConfiguration`).
