### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by allan-poblete** [aspnet/AspNetCore.Docs#15309]
I installed SDK 3.1.100-preview1-014459 but when running "dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview1.19508.20" I'm getting errors that site is not enabled. How to solve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't recognize that exception. Open this for the product unit on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues.
