### ISSUE TITLE
reference-a-partial-view section

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15316]
Why are we talking about Razor Pages in a MVC section?

Is the following related to Razor Pages or MVC or both?:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.0#reference-a-partial-view

```
public IActionResult OnGetPartial() =>
    new PartialViewResult
    {
        ViewName = "_AuthorPartialRP",
        ViewData = ViewData,
    };
```

I would kick out all Razor Pages stuff into Razor Pages, in this case:
`Razor Pages --> Partial Views`

If it's MVC then I want to read about MVC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.0#reference-a-partial-view)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Razor Pages is part of MVC.

**Comment by Legends** [comment]
Where is the `Controller` in Razor Pages if it's part of MVC? :-)
RP is the successor of `WebForms`, there is no MVC.

I see, you're stressed. I know you have a lot to do and I am not trying to annoy you by opening this kind of issues.
