### ISSUE TITLE
Update to generate Open API doc

### ISSUE THREAD

**Issue by Leon99** [aspnet/AspNetCore.Docs#15313]
`AddSwaggerDocument()` should be replaced with `AddOpenApiDocument()`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by robv8r** [comment]
I agree, with the exception that both `AddSwaggerDocument()` and `AddOpenApiDocument()` should be documented.  For Swagger (V2), you should use `AddSwaggerDocument()`.  For OpenAPI (V3), you should use `AddOpenApiDocument()`.  

This is borrowed from the NSwag documentation: https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

**Comment by RicoSuter** [comment]
I agree, we should only promote open api v3 now

**Comment by tanwarsatya** [comment]
The example is not working for v 3.0 ASP.Net Core, Please update it.

**Comment by RicoSuter** [comment]
What is not working?

**Comment by Rick-Anderson** [comment]
Moved to Master issue, check here first. #16879
