### ISSUE TITLE
Is there a possibility to change the PasswordHasher

### ISSUE THREAD

**Issue by iwhp** [aspnet/AspNetCore.Docs#15322]
I have a ASP.NET Web Application (.NET Framework/Angular) and a ASP.NET Core Web Application (Angular). I would like to use the same Identity Database. But it seems that there are different password hasher used. Can I change ASP.NET Core Web Application (Angular) to use the same as ASP.NET Web Application (.NET Framework/Angular)?

See also: https://stackoverflow.com/questions/58569980/asp-net-authentication-net-framework-net-core-side-by-side-angular

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
See [Password Hasher options](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.0#password-hasher-options). You can configure `CompatibiltyMode` and set it to `IdentityV2`.

**Comment by iwhp** [comment]
thankx serpen5. it works! I also had to issue the following sql command:

`UPDATE dbo.AspNetUsers SET NormalizedUserName = UPPER(UserName);`

For more details, one may find some more information here https://github.com/iwhp/AspNetIdentitySideBySide
