### ISSUE TITLE
Filter and Sort do not work together

### ISSUE THREAD

**Issue by rmissier** [aspnet/AspNetCore.Docs#15331]
Section : Update the Razor page

Both links in the code below should also have 
asp-route-currentFilter="@Model.CurrentFilter"

&lt;thead&gt;
        &lt;tr&gt;
            &lt;th&gt;
                &lt;a asp-page="./Index" asp-route-sortOrder="@Model.NameSort"&gt;
                    @Html.DisplayNameFor(model =&gt; model.Students[0].LastName)
                &lt;/a&gt;
            &lt;/th&gt;
            &lt;th&gt;
                @Html.DisplayNameFor(model =&gt; model.Students[0].FirstMidName)
            &lt;/th&gt;
            &lt;th&gt;
                &lt;a asp-page="./Index" asp-route-sortOrder="@Model.DateSort"&gt;
                    @Html.DisplayNameFor(model =&gt; model.Students[0].EnrollmentDate)
                &lt;/a&gt;
            &lt;/th&gt;
            &lt;th&gt;&lt;/th&gt;
        &lt;/tr&gt;
    &lt;/thead&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-3.0)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Sort and filter and independent and aren't meant to work together.
