### ISSUE TITLE
Create a new section within docs that deals with the various configuration files ...

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore.Docs#15339]
I will admit I am a complete newbie with regard to ASP.Net Core, so I am still hacking my way through things, but I have found it rather difficult to navigate some portions of the "docs".

It would be great if the documentation had a separate section that describes in detail ALL of the various configuration files, the valid elements they can contain, and their effect (like the documentation we used to see about 30+ years ago).

For example, in my .csproj file (and within the existing docs) I find attributes such as "CopyToPublishDirectory" within the &lt;Content ...&gt; node.  However, when I edit the .csproj file Intellisense does not even list the "CopyToPublishDirectory" as a valid attribute, and when I search the ASP.NET Core 3.0 documentation I receive the following result:

> 0 results for "CopyToPublishDirectory"

So how does a reader figure out what values are valid for "CopyToPublishDirectory"? 

Again, if a separate section was dedicated to all of the various configuration files, their elements, attributes and a description of each were available (schema?) - it would help tremendously in trying to unravel what elements these configuration files may contain and their effects when used.   For Example:

**Title: Configuration Files**

**Configuration File:** web.config
**Schema:** Describe all elements, child-elements, attributes and what each does or effects.
**Generated by:** Describe how this file is generated / edited.
**Used by:** Describe the processes and/or utilities that use this file.

**Configuration File:** publish profiles (.pubxml)
**Schema:** Describe all elements, child-elements, attributes and what each does or effects.
**Generated by:** Describe how this file is generated / edited.
**Used by:** Describe the processes and/or utilities that use this file.

**Configuration File:** launchSettings.json
**Schema:** Describe all elements, child-elements, attributes and what each does or effects.
**Generated by:** Describe how this file is generated / edited.
**Used by:** Describe the processes and/or utilities that use this file.

Perhaps its a big ask, but having a resource like the above would be a great help in understanding the multitude of elements that exist within the various config files and the effect they have on a project.

Thank-you for your consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-3.0#basic-command-line-publishing)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by bdcoder2** [comment]
Good grief!! 

> We don’t have the resources to invest in this area,

Probably the most important aspect of the technology - the documentation !!

In that case, how about an to answer to a single question about what values are valid for "CopyToPublishDirectory" and what each value does (or should I post a separate request)?

Sorry - just hard to believe someone at MS cannot make available the schema for all of these config files along with a description of valid values, etc.

"Thanks" again.

**Comment by Rick-Anderson** [comment]
@vijayrkn what values are valid for "CopyToPublishDirectory" and what each value does

**Comment by Rick-Anderson** [comment]
> Configuration File: web.config

Per the docs:
ASP.NET Core no longer uses the Global.asax and web.config files that previous versions of ASP.NET utilized.

**Comment by Rick-Anderson** [comment]
https://stackoverflow.com/questions/46282720/

**Comment by guardrex** [comment]
A broader aspect of your request @bdcoder2 pertains to all of .NET Core SDKs and the project file ...

https://github.com/dotnet/docs/issues/2642

... so one idea is to have a small topic over here that **only** holds the props+targets that pertain to directly to ASP.NET Core. Idk if they would want something like that, but it's an idea to think about. 🤔

The files are covered, but not so much in a "fundamental" way (i.e., not in the *Fundamentals* node). They pertain to subsets of MS technology ... specific products. These are **_just files_** after all.

There's *some* light coverage in the *Fundamenals > Servers* topic. We won't have too much coverage there simply because they're fairly specific to a server and/or tooling.

We have quite a bit of content on those files in the *Host and deploy* node. Also, IIS and the VS product family **_have their own doc sets_**, which provide a lot of detailed coverage beyond what we have here. WRT our coverage, it's an on-going process to improve the coverage and improve the cross-linking to existing topics in other doc sets.

We could call them out better with improved descriptions and cross-links. @Rick-Anderson, if you would like me to work on that aspect in the *Fundamentals > Servers* topic, I think a few sentences here and there will do the trick. You can assign me, and I can work on it ... probably December P2 for this one.

WRT schemas for those files ... as we discussed on https://github.com/aspnet/AspNetCore.Docs/issues/15080 ... they don't exist for the most recent additions, so that's a fair ask. However, we can't produce those on the docs repo. IMO, that's a product unit request, and it should go to the engineering repo.

**Comment by Rick-Anderson** [comment]
>  @Rick-Anderson, if you would like me to work on that aspect in the Fundamentals > Servers topic, I think a few sentences here and there will do the trick. You can assign me, and I can work on it ... probably December P2 for this one.

Yes please.

**Comment by bdcoder2** [comment]
> > Configuration File: web.config
> 
> Per the docs:
> ASP.NET Core no longer uses the Global.asax and web.config files that previous versions of ASP.NET utilized.

@Rick-Anderson -  But the ASP.Net core docs contain references to web.config, for example, also per the docs:

> The ASP.NET Core Module is configured with the aspNetCore section of the system.webServer node in the site's web.config file.

[https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#configuration-with-webconfig](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#configuration-with-webconfig)

... Just trying to illustrate how this adds to the conflicting / confusing information found (for newbies like myself).   One section of the docs state that web.config is no longer used, and others state that it must be used (to accomplish certain tasks)!

Had the docs contained a single article / section with regard to web.config -- it might include information as to what project types web.config can be used in or why - from there, I could decide if it is required in my particular project (and sparred you all from having to answer my newbie questions!) :)

Just trying to provide some useful feedback -- as stated in the original post -- I am a very wet behind the ears when it comes to ASP.Net Core; so I am trying to post questions that others new to the environment might also face.

@guardrex - Thanks for the comments as well -- The config file schemas (along with descriptions) is a **MUST HAVE.**   Once documented, (certainly my) questions regarding configuration and the values available for use will likely start dropping.   

40+ years of programming -- I cut my teeth in the VAX/VMS world and their documentation set covered every function and configuration possible -- back then, if you had a question, the typical answer was: RTFM (Read The F***king Manual) -- because the answer was always there -- not so much these days (unfortunately).

Thanks again.
