### ISSUE TITLE
Stream was too long - Stream a file with AJAX to a controller endpoint (physical)

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15337]
Trying to upload a file (2,7GB), but I get an `Stream was too long` exception caused by the code below:

```
using (var memoryStream = new MemoryStream())
                {
                    await section.Body.CopyToAsync(memoryStream);
```
Which of course copies the whole file into a in-memory stream.

**Which setting determines if a stream is too long?**

**Overall memory consumption:**
Before upload-start I have ~10GB of free RAM available. SO memory is not a problem.

![image](https://user-images.githubusercontent.com/966368/67634021-63e27580-f8b7-11e9-9df3-ddb2477065cb.png)

**Memory consumption IISExpress.exe:**

![image](https://user-images.githubusercontent.com/966368/67634030-6e9d0a80-f8b7-11e9-9359-e0768b75810c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0#server-and-app-configuration)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Probably due to the size limit of a `MemoryStream` is `int.MaxValue`. I suppose 🤔 that taking the  `section.Body` as they come in and directly sending them to the `targetStream` instead of accumulating in the `MemoryStream` would be better. It would only be a code reorganization to make that work I think.

I'm going to be 🏃😅 for a bit, so I'm going to mark this for November, but it might slip back to December depending on the November workload.

**Comment by Legends** [comment]
> Probably due to the size limit of a `MemoryStream` is `int.MaxValue`. I suppose 🤔 that taking the `section.Body` as they come in and directly sending them to the `targetStream` instead of accumulating in the `MemoryStream` would be better. It would only be a code reorganization to make that work I think.
> 
> I'm going to be 🏃😅 for a bit, so I'm going to mark this for November, but it might slip back to December depending on the November workload.

I know that this works: ` await section.Body.CopyToAsync(targetStream);` as it does not create a complete buffer serverside.

Ah yeah, looking at its `Capacity` datatype would have helped.
So it's a limitation of the `MemoryStream` class itself.


Thanks!

**Comment by guardrex** [comment]
Leave this open because if a simple code reorg eliminates the `MemoryStream` and thus eliminates the problem, I'd like to perhaps take the topic+sample in that direction. Even if we don't go that far, the topic should **_at least_** call this limitation out.

**Comment by Donistivanov** [comment]
@guardrex I WIP'd something up some time ago. I would have shared it sooner but I thought there was going to be a discussion on the issue and the email came in today that a PR came through.
Anyway, I am not sure if it is the best code and if it works, but maybe you can find some things in it to give the issue a go again, if you wish.
