### ISSUE TITLE
3.0 update: Use AspNetCore.JsonPatch

### ISSUE THREAD

**Issue by Paul-Dempsey** [aspnet/AspNetCore.Docs#15332]
Great, but should also (or instead) document use of Microsoft's own implementation in Microsoft.AspNetCore.JsonPatch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  here's an easy one if you're interested.

**Comment by serpent5** [comment]
`Microsoft.AspNetCore.JsonPatch` _is_ being used in the samples; it's just indirect. The [`Microsoft.AspNetCore.Mvc.NewtonsoftJson`](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson) NuGet package has a dependency on `Microsoft.AspNetCore.JsonPatch`.

For reference, `Microsoft.AspNetCore.JsonPatch` provides `JsonPatchDocument` and the associated "patching" logic. `Microsoft.AspNetCore.Mvc.NewtonsoftJson` includes a Json.NET-based input formatter that converts a JSON Patch request body to a `JsonPatchDocument`. `Microsoft.AspNetCore.JsonPatch` is also dependent on Json.NET.

https://github.com/aspnet/AspNetCore/issues/14035 shows a request for `System.Text.Json`-based JSON Patch support but:

> This is not something we plan to do in the near future.

Following that issue through, there's an example of how to use Json.NET only for the JSON Patch side of things, but I don't know whether that's something the team would like to document as a suggested approach (it's a bit "hacky"). Having said that, it looks like the only option if you really want to use `System.Text.Json` for all non-JSON Patch requests.

@Rick-Anderson:

1. What should we do about this? It looks like changes in [this section](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.0#jsonpatch-in-aspnet-core) would be a good start. Although the migration docs don't show it in the list, I don't think the following is true for 3.0:

   > The package is included in the Microsoft.AspnetCore.App metapackage.

   I checked the contents of the 2.2 version and it's there but it's not in the 3.0 version.

2. There's no 3.x sample for this topic. Should I create one?

**Comment by Paul-Dempsey** [comment]
I really appreciate the followup.

The key point in aspnet/AspNetCore#14035<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fissues%2F14035&data=02%7C01%7CPaul.Dempsey%40microsoft.com%7C55b2047e8b2d458abd3e08d75cc02d0c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637079852773826125&sdata=8%2FQDxhWPFwbmAtSWB9efZ1cOlPEfqeW8BBHqP9lMsGA%3D&reserved=0> is this:

“Yes, we can simply add AddNewtonsoftJson() on the service collection instance, but it replaces the default System.Text.Json formatter for all JSON which is very unfortunate and defeat the purpose of moving away from using Newtonsoft.JSON.”

Which is disappointing. I’m hoping there are coherent plans to move to a full utf-8 string / json stack and avoid much of the transcoding and allocation in the pipeline (see Utf8Json benchmarks).

:- P

**Comment by Rick-Anderson** [comment]
@Paul-Dempsey  can you respond in GitHub and not via email? Can you edit your last response?

**Comment by Rick-Anderson** [comment]
@pranavkm  please review and provide an outline to resolve this issue.

**Comment by Rick-Anderson** [comment]
@serpent5  I took care of The package is included in the Microsoft.AspnetCore.App metapackage.

The MD is divided into 

```
::: moniker range=">= aspnetcore-3.0"
// Copy exiting MDF file here, I fixed the package included
::: moniker-end

::: moniker range="< aspnetcore-3.0"
// Original file here
::: moniker-end
```

**Comment by pranavkm** [comment]
How about this: https://github.com/aspnet/AspNetCore.Docs/pull/15400?

**Comment by RehanSaeed** [comment]
Is there a mistake in the docs? The code sample for using `System.Text.Json` and setting up `Newtonsoft.Json` just for `JsonPatchDocument<T>` is:

```c#
public void ConfigureServices(IServiceCollection services)
{
    var jsonPatchServices = new ServiceCollection();

    jsonPatchServices.AddLogging()
        .AddMvc()
        .AddNewtonsoftJson();

    var jsonPatchServiceProvider = jsonPatchServices.BuildServiceProvider();

    var jsonPatchOptions = jsonPatchServiceProvider.GetRequiredService<IOptions<MvcOptions>>().Value;
    var jsonPatchInputFormatter = jsonPatchOptions.InputFormatters.OfType<NewtonsoftJsonPatchInputFormatter>().First();

    services.AddControllersWithViews(options => jsonPatchOptions.InputFormatters.Insert(0, jsonPatchInputFormatter));
}
```

Shouldn't the last line be this?

```c#
services.AddControllersWithViews(options => options.InputFormatters.Insert(0, jsonPatchInputFormatter));
```

**Comment by Rick-Anderson** [comment]
@serpent5  do you want to fix this?

**Comment by serpent5** [comment]
Yeah, sure. PR incoming.
