### ISSUE TITLE
The property receiving the RenderFragment content must be named ChildContent by convention.

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore.Docs#15344]
[EDIT by guardrex to add the metadata]

In dotnet 3.1.100-preview1-014459, this restriction is removed. The following syntax is running fine.

![image](https://user-images.githubusercontent.com/2770401/67647362-ef7f0380-f996-11e9-91bc-710c99103f07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jingzheshan - Thanks. I'll ping engineering to check on that. Please use the **This page** feedback button/form at the bottom of the topic. It adds the metadata and automatically pings the author. No worries tho ... I just added it :point_up:.

**Comment by guardrex** [comment]
ping @mkArtakMSFT @danroth27

**Comment by danroth27** [comment]
While it's true you can have multiple component parameters of type `RenderFragment` with arbitrary names, if you want your component to support child content, where the entire content of the component is captured as a single parameter, then you need to name the parameter `ChildContent`.

**Comment by jingzheshan** [comment]
Thanks for the clarification.
