### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by toorani** [aspnet/AspNetCore.Docs#15347]
The link is specified for Cierge is incorrect and it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a218cc00-a5c0-717e-5b42-5efd6caf8abb
* Version Independent ID: 69bded75-ba42-d3ff-f27b-f7e715f6d2f8
* Content: [Community OSS authentication options for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community?view=aspnetcore-3.0#oss-authentication-providers)
* Content Source: [aspnetcore/security/authentication/community.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/community.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think it's gone. I'll take care of it. Thanks for the report @toorani.
