### ISSUE TITLE
3.0 update: dotnet aspnet-codegenerator command

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15359]
Update docs using my experience:

Just tried to scaffold an area using the above command, which does not work ootb.
If you execute the command without having added the below deps the user will get exceptions.

Steps that need to be done upfront:

```
install-package Microsoft.VisualStudio.Web.CodeGeneration.Design
install-package Microsoft.VisualStudio.Web.CodeGeneration.Utils
dotnet build // nuget restore
dotnet aspnet-codegenerator area AreaNameToGenerate
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
Actually, I should open an issue in the ASP.NET Core repo.

Depending what kind of resource you want to generate it requires different dependencies and for example `identity` you get:

`dotnet aspnet-codegenerator identity`

> Building project ...
> Finding the generator 'identity'...
> Running the generator 'identity'...
> **Please install the following packages to your project for scaffolding identity**: Microsoft.AspNetCore.Identity.UI,Microsoft.EntityFrameworkCore.Design,Microsoft.EntityFrameworkCore.SqlServer
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

Why does the scaffolding not install the deps by itself, like it's the case when using `npm` packages for example...

**Comment by Rick-Anderson** [comment]
@Legends  open it in https://github.com/aspnet/Scaffolding/issues and link to this issue.
