### ISSUE TITLE
Include some common optional middleware in the order section

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#15353]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#order

It would be good to go through our list of provided middleware and specify on the order section where they should go relative to other middleware.

See this issue as a reference for a case where there's a confusion in the middleware order:
https://github.com/aspnet/AspNetCore/issues/16584

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#order)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There’s that type of info in the table ... does it require more middlewares and/or more detail?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#built-in-middleware

**Comment by guardrex** [comment]
... and perhaps the section on *Built-in middleware* should be closer in the topic to the *Order* section. Either move *Order* down, move *Built-in middleware* up, or **_both_**.

**Comment by javiercn** [comment]
@guardrex Thanks, I see the table now. I think it would be much more visual if we just made a "Startup" with all the middlewares in it, and we simply commented out the ones not included by default. Something like this:

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseStaticFiles();
    app.UseCookiePolicy();
    app.UseRouting();
    // app.UseLocalization();
    // app.UseCors();
    app.UseAuthentication();
    app.UseAuthorization();
    app.UseSession();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapRazorPages();
    });
}
```

I can at least remember 2 or 3 issues where the customer simply didn't know the right middleware order. I think the table is nice, but a code snippet like the one above is more visual. I understand that there is not a strict order relationship between all middleware, in that case we can add an additional comment to the snippet mentioning whatever group of middleware might go in whatever order.

@danroth27 Thoughts?

**Comment by Rick-Anderson** [comment]
I agree with @javiercn , however, you'll need to duplicate the comments in the text - comments don't localize (Although I've asked for that feature).

**Comment by Rick-Anderson** [comment]
@serpent5  this and #15497 look like fun.

**Comment by serpent5** [comment]
@Rick-Anderson Both of those look like a good challenge. I'll see if I can get to them at the weekend.
