### ISSUE TITLE
Please provide some documentation on the best approach for using third-party Ioc containers.

### ISSUE THREAD

**Issue by AlexisColes** [aspnet/AspNetCore.Docs#15369]
Would be good if you could show a rough outline for what needs the be extended/replaced to use another container.

Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#replacing-the-default-services-container)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AlexisColes ... Thanks for the suggestion, but we don't have the staffing to do that. We list the container providers in the [Default service container replacement](https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection#default-service-container-replacement) section, and they *should* have their own docs on how to do it.

For example, the Autofac link goes right to their doc page on using Autofac with .NET Core ... 

https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html

Note how we would likely be updating not just for every major version of .NET but also for major releases of Autofac itself. We can't really maintain **_all_** of that for **_most/many_** of them.
