### ISSUE TITLE
PMerr:ScriptHalted

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15363]
The comment below was machine translated 

@sunmakets commented on [Sun Oct 27 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/212)

Microsoft.EntityFrameworkCore.Tools is installed

In the PMC, no matter how you enter the command about migration, it is ScriptHalted.

What is the reason for this?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [将模型添加到 ASP.NET Core MVC 应用](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sun Oct 27 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/212#issuecomment-546695831)

Hello, @sunmakets
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
