### ISSUE TITLE
Remove 1.0, 1.1, 2.0 version selectors

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15362]
Why can I read about `PageModel` = Razor Pages after I have switched to Docs v1.1 ?
AFAIK RP exists from v2.0, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-1.1)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie  can we remove the version selectors we don't support?

Remove 1.0, 1.1, 2.0 version selectors

**Comment by Legends** [comment]
this doesn't answer my question, but ok...

**Comment by Rick-Anderson** [comment]
We don't have meta-data to exclude  1.0, 1.1, 2.0 on every doc

**Comment by scottaddie** [comment]
@Legends You're correct that Razor Pages was introduced in ASP.NET Core 2.0. We're working on an improved versioning strategy for our docs, at which point this problem will be addressed.

**Comment by Rick-Anderson** [comment]
>No, the docs for these older versions should stay, just like we still have download links for these versions on the dot.net site. We can add a banner to these docs though to let folks know these versions are out of support.

We only have 3 download docs for 1.1, we have nothing for 1.0 and 2.0. It's false advertising  AND the version selector is becoming too bulky.  As far as we can tell, we have zero traffic and zero demand for these unsupported versions.

**Comment by Rick-Anderson** [comment]
@danroth27  unless you can give me a good reason to remove this false advertising, I'm going to remove the version selector for 1.0, 1.1 and 2.0

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/68695422-16a10d80-051f-11ea-97ea-d2827eeeeeb6.png)

**Comment by Rick-Anderson** [comment]
@danroth27  for the 3  1.1 docs we  have, we can add
To download the 1.1 version of this doc, use this link.

But I removing them in 48 hours unless you provide a good reason not to.

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by Rick-Anderson** [comment]
@scottaddie  we have approval to remove all of these. Let me know if you can get this done by EOY.

**Comment by scottaddie** [comment]
@Rick-Anderson I won't have time to remove this by EOY. A significant amount of work is required before the versions can be removed from the selector.

**Comment by Rick-Anderson** [comment]
@scottaddie what needs to be done? We just want to remove `1.0, 1.1, 2.0` from the selector. Can you outline the steps for me or wade?

**Comment by Rick-Anderson** [comment]
Moved to Model Binding master issue #16316
