### ISSUE TITLE
ASP.NET Core 3 MVC Custom User Profile Page

### ISSUE THREAD

**Issue by tony-long** [aspnet/AspNetCore.Docs#15379]
Is it possible that you can add a change diagram to pin-point the changes needed in each file? Create a one page graphic ?    Need for troubleshoot and check-list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by tony-long** [comment]
Okay,  Thanks Rick.  Can someone verify that they page content/steps are working in Core 3.0 then?
Maybe something is missing or to ensure data is saved because this line- await _signInManager.RefreshSignInAsync(user);
Never refreshes with the data entered.

________________________________

**Comment by Rick-Anderson** [comment]
#13232
