### ISSUE TITLE
differences between different types of certs and their uses

### ISSUE THREAD

**Issue by lonewolfnsp** [aspnet/AspNetCore.Docs#15385]
I'm getting utterly confused by the different types of certificates.. especially with regards to grpc-dotnet in the new .net core 3. in grpc.Core, the SSL certs are in the form of pem files (1 private key kept in server, 1 certificate file given to client). The new grpc-dotnet in core 3 uses only pfx file for server, but I can't find any example on how to load the certificate pem file on client side for connection to server. I know pfx is a kind of "container" that combines the private key and certificate into a single binary encrypted file, thus the need for password. 

Referring to the grpc-dotnet, they said there is this client certificate authentication, X509 etc.. I'm confused.. because I don't see them loading any pem file.. so what is that? 

Is there an example somewhere showing how to load pfx on server, load the cert pem on client for connection? 

the grpc.Core was way easier to use as it was completely independent of .net core types, so the way to instantiate server and client is the same, regardless of whether it's on asp.net web app, console app or WPF.. with this new grpc-dotnet which ties to kestrel it actually becomes very confusing.. becaue I can't see how I can use grpc server in a console or WPF app which has no built in kestrel server.. I also can't see how I can use grpc server in asp.net web app with a different port, different SSL pfx file. could you please advice me on this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #15387
