### ISSUE TITLE
Where do Roles come from?

### ISSUE THREAD

**Issue by rhires** [aspnet/AspNetCore.Docs#15380]
The first sentence: "When an identity is created it may belong to one or more roles." - could you include a link to creating an identity with roles? Or give an explanation of how that's done? Also, if I'm using Windows Authentication, where do I configure or find the roles? I see that below in the closed comments you include some additional information regarding roles, so thank you, but I think it should be in the doc, too. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by Perustaja** [comment]
I think it's a little odd to include so much quality content for how to handle roles and authorization, but not the foundation of creating and assigning them? Hoping this gets added in eventually, thank you!
