### ISSUE TITLE
UseWebpackDevMiddleware is Obsolete

### ISSUE THREAD

**Issue by mrumaiz** [aspnet/AspNetCore.Docs#15384]
In this page section Webpack Dev Middleware and HMR using app.UseWebpackDevMiddleware. But this method is Obsolete. Please give an example to convert this to ASP .NET core 3.0 compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.0)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Dup of #13245
