### ISSUE TITLE
Paging: Page number and Count.

### ISSUE THREAD

**Issue by Daniel-OriginalsUnleashed** [aspnet/AspNetCore.Docs#15390]
It would be great if the Page Number and Page Count was displayed below the table when paging is added, something like I added below?

In Students/Index.cshtml

```
<p>Page @model.Students.PageIndex of @model.Students.TotalPages</p>

@{
var prevDisabled = !Model.Students.HasPreviousPage ? "disabled" : "";
var nextDisabled = !Model.Students.HasNextPage ? "disabled" : "";
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's left for the reader. This isn't meant to be a production app and there are countless improvements like this you could make. The tutorial is long as it is.
