### ISSUE TITLE
How do we host WebAPI as a windows service using same mechanism?

### ISSUE THREAD

**Issue by undecided2013** [aspnet/AspNetCore.Docs#15391]
My project was originally created with VS2019 WebApi Template

What I am starting to do is replace 
 services.AddHostedService&lt;ServiceA&gt;();
with 
 services.AddControllers();

and added 

 app.UseEndpoints(endpoints =&gt;
            {
                endpoints.MapControllers();
            });

in the Configure method of Startup.

Am I in the right path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes ... and you see that we're going to go with a Razor Pages sample. We'll likely add a non-web sample, but we probably won't have **_three_** to include an MVC version. The latest guidance for MVC is in the MVC node of the Web apps topic, and you can see the latest changes for 3.0 in the migration topic ... https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

**Comment by undecided2013** [comment]
Thank you, it's tricky when there are so many pieces of the framework changing. We need all of them to work in harmony to produce apps.
