### ISSUE TITLE
Lazy Loading - Example

### ISSUE THREAD

**Issue by Daniel-OriginalsUnleashed** [aspnet/AspNetCore.Docs#15397]
There was a change to the text around Lazy loading as it is now supported. Is it possible to get an example.

I tried to add Lazy&lt;&gt; around different elements of the Models but kept running into issues. For example Models.Course.Department, I used the .Value property i.e. .Department.Value or .Department.Value.Name... to access the data when called on the UI. An error was presented saying that there were two potential keys to use and I would need to define a specific key.

I looked at making the collection in CourseAssigment.cs Lazy as below but the value is needed for the Explicit loading.

```
//public Course Course { get; set; }
public Lazy<Course> Course { get; set; }
```

I think I need to create a IQueryable query that is returned, then use the .Value property on the Lazy objects later on, but I am not sure exactly where to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See the  link in the article.
