### ISSUE TITLE
sqlite hard coded into the app?

### ISSUE THREAD

**Issue by gregveres** [aspnet/AspNetCore.Docs#15410]
I have been doing some investigation into how to do .Net Core / EF Core development on a Mac with Visual Studio for Mac. The ultimate deployment target is Azure with Azure SQLServer. 

The code on this page seems to hard code the target of sqlite:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();

    services.AddDbContext<RazorPagesMovieContext>(options =>
        options.UseSqlite(Configuration.GetConnectionString("MovieContext")));
}
```

When I read that part of the code, I couldn't stop wondering how this works when it is deployed to Azure. We aren't going to run our production site off of sqlite, so why does sqlite get hard coded into the production code?

It is probably worth mentioning here, or later in the series about deploying to a production environment. If it is mentioned somewhere, a link from here to that somewhere would be good so that I can stop worrying about it as I continue reading. 

This then led me to look at the differences in the code between VS for Windows and VS for Mac. I was actually quite surprised to see that they diverge. Does this imply that you can't have a team work on the same product where some developers work on Windows and some on the Mac?  That seems strange. Maybe some explanation of that would be useful at the beginning of the article series. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  this is what I'd like to do, but  **The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection.**

```
public void ConfigureServices(IServiceCollection services, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {

        services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlite(
            Configuration.GetConnectionString("DefaultConnection")));
    }
    else
    {
        // Add     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
        services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    }

    services.AddRazorPages();
}
```

So is the only option `#define LOCAL` ?

cc @guardrex @scottaddie

**Comment by Rick-Anderson** [comment]
@gregveres  I know some folks use Azure with Azure SQLServer in dev mode.

cc @tdykstra

**Comment by guardrex** [comment]
Check the last example in this section ....

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0#the-startup-class

**Comment by guardrex** [comment]
... and maybe `IHostEnvironment` would be better. If so, we might want to update that example I mentioned.

**Comment by Rick-Anderson** [comment]
No, the answer is multiple startups

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0#multiple-startup

**Comment by guardrex** [comment]
I don't like that pattern for small amounts of code ... too much *stuff* ... too much. :smile:

**Comment by Rick-Anderson** [comment]
Copy _Startup.cs_ to _StartupProd.cs_

```
public class StartupProd
{
    public StartupProd(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        // Add     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
        services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));

        services.AddRazorPages();
    }
```

**Comment by Tratcher** [comment]
IWebHostEnvironment can be injected into the Startup constructor.

**Comment by Tratcher** [comment]
@Rick-Anderson a separate Startup works but is usually overkill if you only need to vary a few lines. The normal template checks the hosting environment.

**Comment by Rick-Anderson** [comment]
We'll go with `IHostEnvironment` and mention alt startup as another option.

**Comment by gregveres** [comment]
@Rick-Anderson If you are going to document using IHostEnvironment, I suggest that you try to work in the example of different developers on different OSes. All the examples that were pointed to show different startups for different types of deployments: dev, production, I assume you could do one for testing. 

But what about those shops with a mixture of developers working on Windows, Linux and Mac computers? 

But thanks for all the reaction. This has been helpful to clarify a topic I found confusing.

**Comment by Tratcher** [comment]
@gregveres most AspNet Core components are written to handle cross platform issues internally. What kind of OS tweaks did you have in mind for Startup?

**Comment by gregveres** [comment]
@Tratcher This started because I was looking for information on how to do .Net Core dev on Mac OS with a database. The stuff I was pointed to that started this thread has two different versions of the code, one for Windows that uses the SqlServer provider and one for linux/MacOS that uses the Sqlite provider and these were hard coded into the startup code. Here is the code that was included in the mac version:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();

    services.AddDbContext<RazorPagesMovieContext>(options =>
        options.UseSqlite(Configuration.GetConnectionString("MovieContext")));
}

```
This led me to ask the question about hard coding the use of Sqlite into the app. What about production? what about the devs that use windows and will instead use SqlServer?

Now I understand that you should have multiple startups and that those startups should do different things based on the environment that you are running on. 

In general, I understand the desire to provide windows specific instructions and mac specific instructions, but that isn't how the production life works for the developers, we produce one code base that is destined to run on azure (or another hosting platform) and our local development environments. So I found the examples to be confusing as I was trying to learn how to build that one code base that can be run on Windows or linux or macOS or azure.

**Comment by Tratcher** [comment]
Fair. What is the local EF dev story for Mac?

You could create DevelopmentMac and DevelopmentWindows environments. Or you could use RuntimeInformation if you only need to vary a few lines.
https://github.com/aspnet/AspNetCore/blob/c1cc1684415f2aab86471230346856e8e09dcd43/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvConstants.cs#L28-L39

Again, having separate startups works but it is overkill if you only need to change a few parts.

**Comment by gregveres** [comment]
> Fair. What is the local EF dev story for Mac?

And that is the question that sent me on the hunt through the documentation. I don't think that is really well documented, or if it is, it isn't really easy to find. 

And that story needs to include what we are talking about here. What is the officially recommended way to setup your code base so you can:

- do development on a windows machine
- do development on a mac
- do development on a linux machine
- deploy the solution to Azure

all with a single code base. 

Is this documented somewhere? Is it pointed to by all the other "how to learn .Net Core" docs? It doesn't seem to be. 

I really don't care which mechanism is documented as the recommended way to do this, but I really think it should be documented and you know that once you do and make it available, it will get copied into every project going forward that is developed by developers on multiple machine types.

> 
> You could create DevelopmentMac and DevelopmentWindows environments. Or you could use RuntimeInformation if you only need to vary a few lines.
> https://github.com/aspnet/AspNetCore/blob/c1cc1684415f2aab86471230346856e8e09dcd43/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvConstants.cs#L28-L39
> 

Thanks for the pointer to that example. Combined with all the rest of the links in this thread I can see how you need to setup Startup now to handle the different environments.

**Comment by Rick-Anderson** [comment]
The only place I know where there's a difference is SQL Express or SQLite. Mac, many windows folks, and Linux all use SQLite.

We'll update this with an example that uses `IHostEnvironment` so you have a single code base.

In 3 years we've never had an issue on this.

**Comment by Rick-Anderson** [comment]
@guardrex  I'll provide a complete sample
