### ISSUE TITLE
Default resx files are extremely useful

### ISSUE THREAD

**Issue by zhughes** [aspnet/AspNetCore.Docs#15423]
"We anticipate that many developers won't create a default language resource file"

I have two use cases, both reasons I always create default resource files.  

- I always move resx files into a separate assembly on their own to cut down on build time
- Sometimes I need to emit error messages to the UI (ie a database save failed in an api call so I need to send a friendly error message to the client). By having the public properties (generated file) I can unit test that my method threw an exception and reported the correct messaging. I can assert a string compare with static typing now instead of magic strings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  should I add this to the doc? Something like:

We anticipate that many developers won't create a default language resource file. You might want to create a default language resource file to:

* move resx files into a separate assembly on their own to cut down on build time
*  other reason above

**Comment by zhughes** [comment]
I just wanted to note that there are definitely good use cases for default/public resx files.
I learned these techniques from people much smarter than me, so I can only assume there are a lot of folks out there using them :)

It might not hurt to add one or both in some way. I'm sure the second bulleted item could be subject to developer philosophy arguments so that may be better served to live in the comments section as is.
I don't think there's any questioning that build times improve when you move them to another assembly that rarely get recompiled (because it only contains resx files). So if you want to add that bullet I can certainly see pointing it out as an example of a valid use case.

**Comment by ryanbrandenburg** [comment]
Rather than going into depth about why it is or isn't useful to have a default language resource file why not just omit the line `We anticipate that many developers won't create a default language resource file.`. It's not clear to me what value it adds, and it suggests that we're trying to dissuade people from using them, rather than simply noting a VS behavior which isn't always conducive to their use.

Along that vein we might also remove ` That's usually not what you want with ASP.NET Core. You typically don't have a default .resx resource file (a .resx file without the culture name).`.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  Much better.. This issue will be discoverable from the closed tab on that doc if people want to read about this stuff.

**Comment by zhughes** [comment]
I agree completely that makes much more sense. You're right, I remember interpreting that when I read it as dissuading. I thought ok, well I wonder what they're going to dump it and replace it with in the future.

Thanks Rick!
