### ISSUE TITLE
CreateDefaultBuilder and UseKestrel

### ISSUE THREAD

**Issue by erichillah** [aspnet/AspNetCore.Docs#15424]
it is mention on this page (in this section above https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#how-to-use-kestrel-in-aspnet-core-apps) that calling CreateDefaultBuilder method on the Host will call UseKestrel behind the scene, but looking the code here its not the case. UseKestrel is only called when the ConfigureWebHostDefaults is used. So in the case of a simpled Hosted service for a windows service for example UseKestrel will not be called unless ConfigureWebHostDefaults  is used. Can that be reflected in the document here as this can be confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#kestrel-options)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Correct ... it's just leftover from an earlier age before the Generic Host took over the main show. I'll patch that right up. Thanks for calling out out.

https://github.com/aspnet/AspNetCore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L217

**Comment by guardrex** [comment]
Note in passing that we're going to leave the web app-based Windows Service example on updates to that topic on https://github.com/aspnet/AspNetCore.Docs/pull/15402. We're not going to talk about it in the topic ... we'll just let that sample app show it and explicitly call that sample out in the text.
