### ISSUE TITLE
Typo in scaffolding command line instruction 'Pages\Movies'

### ISSUE THREAD

**Issue by nkev** [aspnet/AspNetCore.Docs#15434]
(VSCode on Windows) In the scaffolding instructions, the `Pages\Movies` part in the command 
`dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries`
is incorrect.
Instead of creating a subfolder inside `Pages`, it creates a folder called `PagesMovies` **parallel** to the `Pages` folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett can you verify this? If that's correct, 3.0 fixes the bug where windows needed a different command than MacOS/Linux. We can get rid of the two instructions.

**Comment by RDanneskjold** [comment]
nkev, thank you!
verifying.

**Comment by Rick-Anderson** [comment]
also need to add 
Microsoft.VisualStudio.Web.CodeGeneration.Utils
