### ISSUE TITLE
fire-and-forget-3

### ISSUE THREAD

**Issue by philip-reed** [aspnet/AspNetCore.Docs#15439]
In previous versions on ASP.NET, it was my understanding that using fire and forget code to run something in a background thread was a bad idea, because IIS would not wait for that thread to complete before recycling an application pool for example.

Do the fire and forget examples above suggest that this is no longer the case?

https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2#do-not-capture-the-httpcontext-in-background-threads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2#do-not-capture-the-httpcontext-in-background-threads)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik should I add the following caveat?

background tasks should be implemented as hosted services. For more information, see [Background tasks with hosted services](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio)

**Comment by jkotalik** [comment]
@davidfowl

**Comment by davidfowl** [comment]
@Rick-Anderson yes add it 😄

**Comment by jkotalik** [comment]
The code example specifically shows why doing a fire and forget when capturing the HttpContext is a bad idea, so if you are going to fire and forget, don't capture the HttpContext. A similar problem existed with ASP.NET and IIS, but I believe it was more extreme there.
