### ISSUE TITLE
Could not find GetJsonAsync in HttpClient class

### ISSUE THREAD

**Issue by sarathlalsaseendran** [aspnet/AspNetCore.Docs#15430]
Hi, I am using Blazor Server version which is shipped with ASP.NET Core 3.0. I could not find the "GetJsonAsync" method inside HttpClient class. Is there any work around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Probably missing the package in your project file ...

```xml
<PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0" />
```

**Comment by scottaddie** [comment]
@guardrex We should make that package requirement more visible in the doc. I also missed that detail when I was trying to do this.

**Comment by guardrex** [comment]
I'll go with a normal "Package" section like we often do.

**Comment by sarathlalsaseendran** [comment]
@guardrex I can get all other methods like GetAsync, PostAsync from same HttpClient. Only GetJsonAsync and PostJsonAsyc and other Json methods missing. Didn't you include in json serialization in Blazor server?

**Comment by sarathlalsaseendran** [comment]
I have created a CRUD blazor server app with manually convert to StringContent (using Newtonsoft) in PostAsync and also converted from HttpResponse to object using same Newtonsoft Deserializer.

**Comment by guardrex** [comment]
Sorry .... sorry ... you've caught me at the very **end** of the day. I'm brain-fried for the day ... been up since 5am! *Yikes!*.

These bits only work for Blazor WebAssembly. For Blazor Server, engineering says to use [IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0), and I think those bits use `System.Text.Json` and there's a `JsonSerializer`. Check that doc ... I think it explains it all out.

**Comment by sarathlalsaseendran** [comment]
I have just checked "Microsoft.AspNetCore.Blazor.HttpClient" and found that this is still an experimental and preview only. Is that correct?

**Comment by guardrex** [comment]
Leave this issue open tho ...... I **_do_** want to add a section for the package here. This issue will automatically close when the PR merges.

**Comment by guardrex** [comment]
Yes, that's correct. All of Blazor WebAssembly is in preview.

**Comment by scottaddie** [comment]
@sarathlalsaseendran You'll need to install the following package to gain access to methods like `PostAsJsonAsync`:

```xml
<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
```

In 3.0, Json.NET (Newtonsoft) was removed from the shared framework. As a result, the Web API client package was removed too. It had a dependency on Json.NET (Newtonsoft). The default JSON serializer in 3.0 is System.Text.Json.

**Comment by guardrex** [comment]
Thanks @scottaddie ... we have the cross-link in this Blazor topic; but when I go to add the *Package* section, I'll double-check and work on the visibility of the text/link for Blazor server. *Tomorrow tho!* I'm 😵 at this point.

**Comment by sarathlalsaseendran** [comment]
Hi @scottaddie, Thanks for the suggestion. I have added the "Microsoft.AspNet.WebApi.Client" package as per your suggestion. But still not getting GetJsonAsync method in HttpCleint. I am getting "PostAsAsync" and "PutAsAsycn" methods. Can you please tell me is there any work around to get GetAsAsync method in HttpClient.

**Comment by pranavkm** [comment]
Did you mean `ReadAsAsync`? That should be on the response content.

**Comment by sarathlalsaseendran** [comment]
Hi @pranavkm, I am asking about "GetAsJsonAsync" method in HttpClient class. In previous  versions of Blazor (prior to .NET Core 3.0) it was there. Now after I added "Microsoft.AspNet.WebApi.Client" package (as per @scottaddie ) I could see "PostAsAsync" and "PutAsAsync" methods. Do you have any update?

**Comment by GlobeProgger** [comment]
Hi. Just wanted to bump this issue. 2 weeks later and I too am unable to use the GetJsonAsync<T> method as described in the article. Any updates or workarounds?

**Comment by pranavkm** [comment]
`GetAsJsonAsync` is an API specific to the experimental package. You can use `HttpContent.ReadAsAsync<T>`  as a substitute: https://stackoverflow.com/a/24052147.

**Comment by vamsea2002** [comment]
adding these resolved 
Install-Package Microsoft.AspNetCore.Components -Version 5.0.5
Install-Package Microsoft.AspNetCore.Blazor.HttpClient -Version 3.2.0-preview3.20168.3
using System.Net.Http;
using Microsoft.AspNetCore.Components;
