### ISSUE TITLE
UpdateOne instead of ReplaceOne

### ISSUE THREAD

**Issue by reggaeguitar** [aspnet/AspNetCore.Docs#15450]
It seems like ReplaceOne is a much slower way to update a document than UpdateOne. Regardless of performance it would be nice to have an example of using UpdateOne also. It's been difficult finding out how to even create a FilterDefinition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
You could be right. Let's see if this gets any traction.
