### ISSUE TITLE
How does Razor file compilation work when using .NET Framework

### ISSUE THREAD

**Issue by MikeChristensen** [aspnet/AspNetCore.Docs#15454]
When using .NET Framework 4.6.1 with ASP.NET Core 2.2, how do cshtml files get compiled?  Does this happen at runtime, or is there something that needs to happen during build process?  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation appears to be .NET Core only, so I don't think that's the trick.  I'm unable to find any examples anywhere of ASP.NET Core 2.2 MVC working under .NET Framework (non-core).

https://stackoverflow.com/questions/58667252/is-it-possible-to-use-asp-net-core-2-x-mvc-on-net-framework-4-6-1-console-appli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Create a asp.net core 2.2 mvc app targeting .NET Framework and it displays the views. Have you tried that?

**Comment by MikeChristensen** [comment]
I found an answer (See the StackOverflow link above) that works.  I'll try creating an app with the VS wizard, then re-targeting to .NET Framework to see how that works.  I'll post back here with any further questions..

**Comment by MikeChristensen** [comment]
One possible solution:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <Target Name="CustomPrecompileViews" AfterTargets="Build">
      <CallTarget Targets="MvcRazorPrecompile" />
      <Copy SourceFiles="$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\$(TargetName).PrecompiledViews.dll"        
            DestinationFolder="$(OutputPath)" />
  </Target>     
</Project>
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
