### ISSUE TITLE
How to tell it which root CA to trust?

### ISSUE THREAD

**Issue by jnxxx** [aspnet/AspNetCore.Docs#15456]
This is working on-prem where I can add my internal CA to the machines trusted root store, but I doubt I can do that on an App Service in Azure.
Can I somehow give it a public certificate for my CA in code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
That'd be a question for Azure, but it's doubtful. There's a [PR](https://github.com/aspnet/AspNetCore/pull/15029) coming for 5.0 to make it easier, so you can have an alternate root store in code.

**Comment by guardrex** [comment]
@jnxxx I'll close as answered because we won't make a topic update for this at this time.
