### ISSUE TITLE
[FromBody] requires Newtonsoft

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/AspNetCore.Docs#15469]
My POSTs stopped working after upgrading to 3.0. I need to keep Newtonsoft in order to get http-post with [FromBody] to work. Luckily, I found https://medium.com/cloudnimble/switching-to-system-text-json-in-net-core-3-0-not-so-fast-4c577a21298b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mattiasw2 ... What's your ask? It's already covered in the topic ...

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support

**Comment by mattiasw2** [comment]
Sorry, but when I search from FromBody on the page, I do not see it. But, of course, if it is there, everything is fine.
