### ISSUE TITLE
Import style file at Layout level

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore.Docs#15460]
At layout level, do we have or could we have a convenient way to import a/multiple css file(s)? I know we can put those style inside the &lt;style&gt; tag; or dynamically use JS interop to achieve this however either way feels not so great. Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-nz/aspnet/core/blazor/layouts?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jingzheshan ... Product feedback has to go to the product unit, as we only handle documentation here. https://github.com/aspnet/AspNetCore/issues
