### ISSUE TITLE
namespace could not be found

### ISSUE THREAD

**Issue by Aaronmeade92** [aspnet/AspNetCore.Docs#15468]
# Before you open an issue

If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page.

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

Startup.cs(30,35): error CS0246: The type or namespace name 'RazorPagesMovieContext' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Aaron Meade\dotnet-practice\RazorPagesMovie\RazorPagesMovie.csproj]

The build failed. Fix the build errors and run again.

Tried redoing the tutorial but ran into the same problem
Also tried dotnet restore but have not yet found a solution to this error

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by guardrex** [comment]
Hello @Aaronmeade92 ... It's best to use the **This Page** feedback button+form at the bottom of the topic to open an issue. It will automatically ping the author and add metadata to your issue. Recommend you close this and re-open the issue using that form.
