### ISSUE TITLE
namespace could not be found

### ISSUE THREAD

**Issue by Aaronmeade92** [aspnet/AspNetCore.Docs#15474]
Startup.cs(30,35): error CS0246: The type or namespace name 'RazorPagesMovieContext' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Aaron Meade\dotnet-practice\RazorPagesMovie\RazorPagesMovie.csproj]

The build failed. Fix the build errors and run again.

tried rewriting the tutorial but still ran into the same issues
Tried running dotnet restore but not really sure where I went wrong. Any feedback would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Rick-Anderson** [comment]
Good error message.
