### ISSUE TITLE
`author` is null

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15470]
In your sample app `author` is null, means doesn't get bound.
Shouldn't it get bound?

Calling: `http://localhost:xxxx/api/boundAuthors/get/1`
`author` is null:
```
// GET: api/boundauthors/get/1
        #region demo2
        [HttpGet("get/{authorId}")]
        public IActionResult Get(Author author)
        {
            return Ok(author);
        }
        #endregion

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson On a broader point, this sample is one of the lingering **_1.0 sample apps_** remaining 🤦‍♂. It's on the list ... https://github.com/aspnet/AspNetCore.Docs/issues/5495.

**Comment by guardrex** [comment]
I'm not sure if this is something that can be addressed using the existing sample. *Yes,* let's leave it open just in case the behavior can be addressed without updating the sample.

If it turns out that this can't be addressed, then we can close this as a dup of the sample update tracking issue (#5495).

**Comment by Legends** [comment]
This one is a dup of  https://github.com/aspnet/AspNetCore.Docs/issues/10341

**Comment by guardrex** [comment]
Oh ... ok. I'll relink the sample tracking issue to that one.

I presume that it's a P2 doc bug because it's one of the topics that doesn't receive nearly as much traffic as the others, and we're 🏃😅 right now with high priority work.
