### ISSUE TITLE
Is this up to date with ASP.NET Core 3.0?

### ISSUE THREAD

**Issue by lol768** [aspnet/AspNetCore.Docs#15473]
It suggests we:

> Add a package reference to the Microsoft.AspNetCore.Diagnostics.HealthChecks package. To perform health checks using Entity Framework Core, add a package reference to the Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore package.

But the sample repo's [project file](https://github.com/aspnet/AspNetCore.Docs/blob/f0e7d8e39f902c184da54a04c57f74dcf48162d5/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj#L8-L13) does no such thing? There is no `Microsoft.AspNetCore.Diagnostics.HealthChecks` reference

https://github.com/aspnet/AspNetCore.Docs/blob/f0e7d8e39f902c184da54a04c57f74dcf48162d5/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj#L8-L13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Typo ... it should be `Microsoft.Extensions.Diagnostics.HealthChecks`.

I'll patch it. Thanks for calling it out.

**Comment by guardrex** [comment]
Well .... it **_was_** a thing ...

https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.HealthChecks

... possibly 2.x. I'll take a closer look.

**Comment by guardrex** [comment]
So the deal on this one is that the `Microsoft.AspNetCore.Diagnostics.HealthChecks` package is in the `Microsoft.AspNetCore.App` package for 2.2, and it references the `Microsoft.Extensions.Diagnostics.HealthChecks` package. For 2.x, it should say that if the app doesn't use the `App` package to place a reference to it.

For 3.x, the package is implicit in the framework.

I'll put an update in now to fix it up.

**Comment by lol768** [comment]
I also noticed the  `WriteResponse` implementation provided relies on `Newtonsoft.Json`. Is it appropriate to rewrite this to use `System.Text.Json` things?

**Comment by guardrex** [comment]
It wasn't according to engineering at the time of the 3.0 update. I'll keep that in mind for the next doc update, which will be for 3.1. I'll put a note now on the sample tracking issue that we're using.

**Comment by lol768** [comment]
>It wasn't according to engineering at the time of the 3.0 update

Ah no, you're quite right. The sample works fine in 3.0 currently, which saves me rewriting it (for the minute at least!).

Thanks for making a note, though!
