### ISSUE TITLE
HttpResponse class missing WriteAsync() method ...

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore.Docs#15481]
# Issue description

Document Page:
[https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse?view=aspnetcore-3.0](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse?view=aspnetcore-3.0)

Is the  WriteAsync( String ) method missing from the docs?   Other WriteAsync() methods with different signatures are present, but WriteAsync( String ) is not shown in the Methods list.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

-  .NET Core 3.0

**Comment by guardrex** [comment]
The API docs are generated directly from the API itself.

https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Http/Http.Abstractions/src/Extensions/HttpResponseWritingExtensions.cs

Questions about what's in the API must go to the product unit.
