### ISSUE TITLE
Does Not Address Web.config, IIS, Azure Aspects of ASP.NET Core Configuration

### ISSUE THREAD

**Issue by michaelbunney** [aspnet/AspNetCore.Docs#15482]
This page makes no mention of Web.config or where to put IIS configuration.  While app settings and connection strings have been moved to JSON, where has all the rest of the configuration gone?  I see many Microsoft articles saying to add settings to Web.config under ASP.NET Core, but this file no longer exists by default, and I don't see any information on where you would put it ASP.NET Core.

When a page entitled "Configuration in ASP.NET Core" makes no mention that Web.config is even a thing any more, this is a big gap that's very confusing for developers coming over from pre-Core versions of ASP.NET.

At the same time, many are moving from on-premise IIS to Azure Web Apps, which have "application configuration" that has a relationship to Web.config and perhaps also to the JSON configuration, but this too is not addressed.  I realize that this page is not about Azure, but given Microsoft's pushing of Azure as the preferred hosting option, this really needs to be addressed in an integrated, comprehensive way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?tabs=basicconfiguration&view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @michaelbunney ... Configuration is different in ASP.NET Core than in .NET Framework. The *web.config* file isn't used to store app configuration any longer. Use the guidance in this topic to maintain your app's configuration.

IIS, the ASP.NET Core Module, and *web.config* are covered in the topics in the *Host and Deploy* node. The coverage starts with the *Overview* ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0

To understand more about the process of moving from the .NET Framework to ASP.NET Core, see the migration topics that start with this *Overview* ...

https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-3.0

With regard to Azure, several of our topics pertain to using ASP.NET Core with Azure, and we cross-link in many places to the Azure documentation. For Azure hosting, see the *Host and Deploy* > *Azure App Service* coverage node that starts with this *Overview* ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.0&tabs=visual-studio

**Comment by guardrex** [comment]
Hum ... I thought that we had a *Migration* node cross-link in the Introduction. *We don't!*

No worries ... I'll surface it now.
