### ISSUE TITLE
OpenApiInfo,OpenApiContact ,OpenApiLicense classes not found in Asp.Net Core 2.2 

### ISSUE THREAD

**Issue by vignesh-nethaji** [aspnet/AspNetCore.Docs#15486]
Hello Microsoft team,

 I couldn't find this classes Swashbuckle.AspNetCore.Swagger.OpenApiInfo , Swashbuckle.AspNetCore.Swagger.OpenApiContact and Swashbuckle.AspNetCore.Swagger.OpenApiLicense  in asp.net Core 2.2 Framework . 

Please update the class as like below.
OpenApiInfo  = Info
OpenApiContact  = Contact
OpenApiLicense  = License  

// Register the Swagger generator, defining 1 or more Swagger documents
```
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new Info
    {
        Version = "v1",
        Title = "ToDo API",
        Description = "A simple example ASP.NET Core Web API",
        TermsOfService = "https://example.com/terms",
        Contact = new OpenApiContact
        {
            Name = "Shayne Boyer",
            Email = string.Empty,
            Url = "https://twitter.com/spboyer",
        },
        License = new License
        {
            Name = "Use under LICX",
            Url = "https://example.com/license",
        }
    });
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by MaxMex007** [comment]
OpenApiInfo only exists in Swashbuckle.AspNetCore v5.0.0-rc4 which means you need to install a PRE-release version, if you are using the Visual Studio Nuget Manager, then you need to check the "Include prerelease" checkbox.
That's why on the beginning of the post they mention to use the PackageManagerConsole and execute the following line:
Install-Package Swashbuckle.AspNetCore -Version 5.0.0-rc4
which would force to install the specific version

"new License" should be "new OpenApiLicense"

I hope this helps.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
