### ISSUE TITLE
Remarks about Regex Validation

### ISSUE THREAD

**Issue by SheepRock** [aspnet/AspNetCore.Docs#15488]
It appears that RegularExpression always validate as full string, there are no difference between the pattern @"d" and @"^d$". Documentation should specify that or the implementation should be fixed, as this seems more like a bug. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)

Include steps to reproduce the bug and the version you're using `dotnet --version`
