### ISSUE TITLE
lacking useful example

### ISSUE THREAD

**Issue by m-pollack** [aspnet/AspNetCore.Docs#15495]
Migrating module code to middleware shows an existing http module right after is an example of middleware
the issue here is IT IS NOT THE CONVERSION OF THE EXAMPLE OF SHOWN BEFORE IT
INSTEAD IT IS The preceding middleware template was taken from the section on writing middleware.

WHO THOUGHT THIS WAS USEFUL?  As usual the documentation is verbose but says very little 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f81f11-5621-b581-69f5-60093946b8ed
* Version Independent ID: 886858c7-29eb-714a-22ff-c30973d889e1
* Content: [Migrate HTTP handlers and modules to ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules?view=aspnetcore-3.0)
* Content Source: [aspnetcore/migration/http-modules.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/http-modules.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
