### ISSUE TITLE
Overload of UseHsts Doesn't Seem To Exist

### ISSUE THREAD

**Issue by TheHokieCoder** [aspnet/AspNetCore.Docs#15494]
The example under the section "HTTP Strict Transport Security Protocol (HSTS)" where the `UseHsts()` method is using an overload to provide an anonymous instance of `HstsOptions` does not seem to be possible using the "ASP.NET Core Web App" (`dotnet new webapp`) template (.NET Core v3.0 in my case). No overload of `UseHsts()` that takes more than 1 argument cannot be found. I've searched through the source code of the AspNetCore repository and no such overload exists. Where do I find this extension method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#http-strict-transport-security-protocol-hsts)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> the `UseHsts()` method is using an overload to provide an anonymous instance of `HstsOptions`

No overloaded  `UseHsts()` method  is used on this page.

**Comment by TheHokieCoder** [comment]
My apologies Rick. I believe that I was too close to the problem yesterday and was confusing the examples thinking that `UseHsts()` was used in both code samples under the "HTTP Strict Transport Security Protocol (HSTS)" section. However, `UseHsts()` is only used in the `Configure()` method (first code sample) while `AddHsts()` is used in the `ConfigureServices()` method (second code sample). It is `AddHsts()` that accepts an instance of `HstsOptions`. Appreciate the nudge in the right direction!
