### ISSUE TITLE
Use, Run, and Map - differentiate them

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15497]
[Use, Run, and Map](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#use-run-and-map)

Does a poor job differentiating them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#use-run-and-map)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I've been giving this one some thought tonight.

I think the page covers `Use` well in the "Create a middleware pipeline with IApplicationBuilder" section, but that section doesn't differentiate too well between `Use` and `Run`. Here's a proposal for changes:

1. Use line highlighting for the `Use` example in the last snippet of the "Create a middleware pipeline with IApplicationBuilder" section. This is the part that gets explained, with the `Run` call being somewhat ignored.
2. Continue on to call out the `Run` example (again, with highlighting) from that same snippet. Be a bit more explicit about the call being terminal and how it differs to the previous `Use` call.
3. Remove the first paragraph from "Use, Run, and Map", which is then already covered in "Create a middleware pipeline with IApplicationBuilder".
4. Change "Use, Run, and Map" to "Branching". Keep the `Map` and `MapWhen` coverage as it, but also mention `UseWhen` and how that differs from `MapWhen`.

What do you think about this as a general approach?

**Comment by Rick-Anderson** [comment]
> What do you think about this as a general approach?

Much better!
