### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by DrumAce** [aspnet/AspNetCore.Docs#15496]
I followed all steps and the example simply doesn't work (Visual Studio for Mac v8.3.6).
Please review and fix it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by DrumAce** [comment]
I reviewed the steps several times and didn't miss any.
Have you tried it in Visual Studio for Mac?
