### ISSUE TITLE
Input radio

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#15508]
Not sure what the right place for this is, but provide a description of how to work with input type=radio based on the comment in this bug https://github.com/aspnet/AspNetCore/issues/5579#issuecomment-548061223

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by aaronhudon-ts** [comment]
To get it going right now, see this workaround.  It works fine.
https://github.com/aspnet/AspNetCore/issues/5579#issuecomment-548061223
