### ISSUE TITLE
Code download triggers antivirus alert

### ISSUE THREAD

**Issue by clovisrod** [aspnet/AspNetCore.Docs#15509]
[EDIT by guardrex to move the content from the title into the opening comment]

> Virus: when I download code my antivirus give me an alert - HEUR/AGEN.1029580. What is this ?

**Comment by guardrex** [comment]
> I download code

What did you try to download?

**Comment by clovisrod** [comment]
I' downloaded - AspNetCore.Docs-master.zip

The virus was detected in the upload of files sample, version 3.x

Thanks

[image: image.png]

[image: image.png]

**Comment by guardrex** [comment]
Heuristic scanning just looks for patterns in files. It's probably just that and not an actual virus, but that's just my guess. It looks ok from here.

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp

@blowdart Do we need to take any further action on a report of a virus in one of our samples when it doesn't look like anything is amiss and the hit was only heuristically based?

btw -- Can't see your images. You have to drag the image file into the GH comment box to upload it for your remark.

**Comment by guardrex** [comment]
Closing for lack of response.
