### ISSUE TITLE
MS load testing to be decommissioned

### ISSUE THREAD

**Issue by jzoran05** [aspnet/AspNetCore.Docs#15506]
Documentation should reflect the fact that both Visual Studio and Azure DevOps load testing are going to be decommissioned - DevOps quite soon I believe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce92350f-25e5-63bc-c815-a8a41b2253c3
* Version Independent ID: e8f9ec21-4e0a-054e-b9ba-fd27e71e31a0
* Content: [ASP.NET Core load/stress testing](https://docs.microsoft.com/en-us/aspnet/core/test/load-tests?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/test/load-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/load-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Jeremy-Meng
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Changes to load test functionality in Visual Studio and cloud load testing in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops)

There are dozens of web load testing tools. I think we should retire this doc.

Please respond @jeremymeng @mjrousos
