### ISSUE TITLE
Need to set up a link in a specific topic...

### ISSUE THREAD

**Issue by MustakimAlamMoon** [aspnet/AspNetCore.Docs#15510]
In this page, the topic of "Add route template" & "Review concurrency exception handling" parts contain a line where it is saying that "Set a breakpoint on..." But there is no details about how to set a breakpoint in visual studio. I knew it before that is why it is clear to me. But for the fresher students who are not familiar with breakpoint, maybe confused what to do in this section. Some of them maybe search in google for "how to set a breakpoint in vs 2019" and could be find the answer. But I think, if the breakpoint word here could contain a link and it redirects the page to another details page about the specific breakpoint topic then that would be more clear to a newbie student. Otherwise, this page can explain about the breakpoints shortly. Maybe, it'll save a student's time and also helps to make it sense easily...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
VS isn't the only tooling ... ASP.NET Core is cross-tooling just like it's cross-platform. If it links to VS, what about for other users on other tooling? It's not really feasible to cross-link so much. Devs probably need to check the docs for whatever tooling that they're using for many of these tooling-related concepts.

**Comment by MustakimAlamMoon** [comment]
Thank you very much for the clarification...
