### ISSUE TITLE
Best practice for registering ClaimsPrincipal as a service is not listed

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [aspnet/AspNetCore.Docs#15523]
This page is frustratingly vague. It mentions using IHttpContextAccessor in a static variable as a workaround for migration when DI isn't being used, but if DI is being used then there is no reference to what the developer *should* be doing to take advantage of it.

From reading independent blog posts it looks like this is the answer. If so can it be added?

```csharp
services.AddHttpContextAccessor();
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddScoped<ClaimsPrincipal>(p => p.GetRequiredService<IHttpContextAccessor>().HttpContext?.User);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-3.0)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Possibly solved by a cross-link?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.0

```
<xref:fundamentals/httpcontext>
```

**Comment by rellis-of-rhindleton** [comment]
That would close the gap. That page doesn't come up in a search for e.g. "asp.net core claimsprincipal services", but this page (the migration page) does, so it makes a path to the right place.
