### ISSUE TITLE
.net core 3.1: does not contain a definition for ApplyCurrentCultureToResponseHeaders

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15521]
```
    new RequestLocalizationOptions // does not contain a definition for ApplyCurrentCultureToResponseHeaders
     {
           ApplyCurrentCultureToResponseHeaders = true
     };
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#cookierequestcultureprovider)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #15412 
Please look at open issues before creating new ones.

**Comment by Rick-Anderson** [comment]
Dup of #15412 
Please look at open issues before creating new ones.

**Comment by Rick-Anderson** [comment]
Dup of #15412 
Please look at open issues before creating new ones.

**Comment by Legends** [comment]
Yes, but I am referring to v3.1 not 3.0.
