### ISSUE TITLE
AddRedis when using Microsoft.AspNetCore.SignalR.Redis

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore.Docs#15528]
>In the Startup.ConfigureServices method, call AddStackExchangeRedis after AddSignalR:

Apparently `AddRedis` is the method when using `Microsoft.AspNetCore.SignalR.Redis`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
> Apparently `AddRedis` is the method when using Microsoft.AspNetCore.SignalR.Redis

That isn't true anymore. In 3.0 there is no Microsoft.AspNetCore.SignalR.Redis package.

If you're referring to the 2.2 versioned docs then that is true, and we could update the doc to mention that. Although I'm not sure what the status on 2.2 docs is these days as it will be out of support soon.

**Comment by Rick-Anderson** [comment]
`AddRedis` is in the 2.1 and 2.2 version.

**Comment by spottedmahn** [comment]
>If you're referring to the 2.2 versioned docs

Hi @BrennanConroy - nope, I was referring to the v3 page.

---

![image](https://user-images.githubusercontent.com/14079228/68399756-e46d6580-0144-11ea-86ff-6e0eaf41088f.png)

The above has a reference to the old package `Microsoft.AspNetCore.SignalR.Redis` but only has the code snippet for the new package `Microsoft.AspNetCore.SignalR.StackExchangeRedis`

**Comment by spottedmahn** [comment]
It would see that

>Microsoft.AspNetCore.SignalR.Redis - Depends on StackExchange.Redis 1.X.X. This package will not be shipping in ASP.NET Core 3.0.

**shouldn't** be in the v3 doc page, thoughts? 💭

**Comment by BrennanConroy** [comment]
Good eye, missed that reference.



> **shouldn't** be in the v3 doc page

We should remove that reference in the 3.0 docs. 👍

**Comment by spottedmahn** [comment]
>We should remove that reference in the 3.0 docs. 

Not only that but when reading the 2.2 documentation if I use `Microsoft.AspNetCore.SignalR.Redis` I need to call `AddRedis` not `AddStackExchangeRedis`.  I went to submit a PR but I wasn't sure what is the best way to document that.

I guess it would be best if I submit my PR and go from there?

**Comment by spottedmahn** [comment]
You guys rock! 🤝

Thanks for getting this resolved 🥳.  Thanks the speed ⚡.

**Comment by Rick-Anderson** [comment]
@spottedmahn  thanks for the PR
