### ISSUE TITLE
Errors with download - Windows 7 issue?

### ISSUE THREAD

**Issue by BrennyAlbany** [aspnet/AspNetCore.Docs#15540]
A few download issues - error during download, error when attempting to run app - is this because I'm trying to run this with Windows 7?  I believe Windows 7 can't handle long file names/subfolders.  One error - Skipping file: unable to create a sensible filename out of - c:...\Documents\Microsoft Tutorial ASPNetCoreDocs\AspNe...\StartupDiagnostics.deps.json - I know where I work will be converting to Windows 10 soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Probably a long file name issue.
