### ISSUE TITLE
Unexpected end of Stream, the content may have already been read by another component.

### ISSUE THREAD

**Issue by TheGreenAirplane** [aspnet/AspNetCore.Docs#15545]
I have implemented a file upload method according to this page:
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0

I get an exception when trying to read the request body: 
```
var reader = new MultipartReader(boundary, HttpContext.Request.Body);
var section = await reader.ReadNextSectionAsync();
```

The exception:

> Unexpected end of Stream, the content may have already been read by another component.

Stack trace:

> "   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.<ReadAsync>d__36.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.<DrainAsync>d__3.MoveNext()\r\n  
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   
>   at Microsoft.AspNetCore.WebUtilities.MultipartReader.<ReadNextSectionAsync>d__20.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n  
>  at ...Controllers.UploadController.<UploadFile>d__15.MoveNext()
>  in C:\\prj\\...\\UploadController.cs:line 290"

I found this question on StackOverflow:
https://stackoverflow.com/questions/49867343/unexpected-end-of-stream-the-content-may-have-already-been-read-by-another-comp

I tried to implement the suggested solution (adding a DisableFormValueModelBinding attribute). It didn't help. 

The application is targeting .NET Core 3.0.

On the UI side I'm using UIKit File Upload component in vue.js.

**Comment by guardrex** [comment]
Hello @TheGreenAirplane ...

Passing note on opening issues: Please use the **This Page** feedback button/form at the bottom of the topic.

WRT `DisableFormValueModelBindingAttribute`: That's covered in the topic.

We don't have the staffing to troubleshoot individual developer apps. We can only work doc issues that principally use the scenarios covered by the topic. Your use of *vue.js* might be a contributing factor, and we have no way to troubleshoot such a scenario. 

You did the right thing ... SO is a great resource. You'll probably get some good advice there. You can also talk to devs on chat ...

* [Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet)
