### ISSUE TITLE
Roles with spaces in them?

### ISSUE THREAD

**Issue by bdaniel7** [aspnet/AspNetCore.Docs#15547]
I am astonished to discover that role names with spaces cannot be used. And no exception is thrown. The authorization just doesn't work. And try debugging for hours, to find out why...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by bdaniel7** [comment]
Hmm, apparently, the claims must be registered with keys from System.Security.Claims.ClaimTypes.Role, instead of "role".

**Comment by Rick-Anderson** [comment]
The doc uses `Role` from the start `[Authorize(Roles = "Administrator")]`
