### ISSUE TITLE
Add a section mentioning the usage of app.UseBasePath

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#15546]
[EDIT by guardrex to remind myself to add the no-loc metadata: `no-loc: [Blazor]`]

It might be necessary on the server deployment to configure the server base path. We should include a section here about setting the base path on the asp.net core host with `app.UseBasePath`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 120edc19-68d5-5a86-0638-59e53ee2275e
* Version Independent ID: 85e547e0-8e56-19e5-7059-c59c4930bb50
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/index?view=aspnetcore-3.0&tabs=visual-studio#app-base-path)
* Content Source: [aspnetcore/host-and-deploy/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
https://github.com/aspnet/AspNetCore/issues/16849

**Comment by guardrex** [comment]
Seems like it should be `UsePathBase`.
