### ISSUE TITLE
Create project in vscode and run it in visual studio and vice versa

### ISSUE THREAD

**Issue by Fungungun** [aspnet/AspNetCore.Docs#15543]
Could you instruct how to do it or if it's doable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Fungungun** [comment]
okay solved. 

Project A: Create and Run in VSCode
Project B: Create and Run in Visual Studio

Modify the file "launch.json" in Project B following the same file in project A
Remember to change the .dll filename

**Comment by Rick-Anderson** [comment]
Create a  project with either approach. In VSC, dotnet run, in VS - ^F
