### ISSUE TITLE
Only integers in Price field

### ISSUE THREAD

**Issue by Flodgar** [aspnet/AspNetCore.Docs#15551]
I can only type integers in Price field. If i use dot as it is in the picture, I get "The value '1.19' is not valid for Price." warning. Anyway, "Edit" fills the form with two decimal places using comma ('20,00'), which can't be saved. All this is pretty consufing for me. Note under the picture says you can't use decimal commas but says nothing about the dots.
And as a bonus, I found out you can type float number with decimal comma, but it works only if there are 3 digits after the comma. For example '13,356' will be saved as '13,36'... Inputs like '13,35' or '13,3568' will give "The field Price must be a number." warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See note at end of that page
