### ISSUE TITLE
When publish creates Identity folder in wwwroot

### ISSUE THREAD

**Issue by Thraka** [aspnet/AspNetCore.Docs#15556]
_From @RetsamSoft on Wednesday, November 6, 2019 3:32:43 AM_

Hello, sorry for my bad English, when I publish my project I create a folder called "Identity" in the wwwroot folder.
I use my own layout in /Areas/Identity/Pages/_ViewStart.cshtml

```
@ {
    Layout = "/Views/Shared/_MyLayout.cshtml";
}
```

I don't want the "Identity" folder to be created automatically at wwwroot, thx.

- .NET Core 3.0

_Copied from original issue: dotnet/docs#15716_

**Comment by Thraka** [comment]
_From @Thraka on Wednesday, November 6, 2019 3:46:37 PM_

Hello, I think this question is better suited for the ASP.NET Core team.

**Comment by guardrex** [comment]
Hello @Thraka ...

See :point_right: https://github.com/dotnet/cli/issues/5934

Yes, let me take a look at our coverage on this. We *might* want to cover it where we introduce *wwwroot* (web root) concepts or where we describe the Web SDK publishing. I'll take a look, but I'm going to put this back in December. We're 🏃😅 right now on high-priority issues.

**Comment by Thraka** [comment]
@guardrex Hi there. @RetsamSoft is the real author, I just moved the issue from the .NET Docs repo.

**Comment by guardrex** [comment]
That's ok. That might be the right place to open the issue. We're *very compartmentalized* here ... we don't work on their docs, and they don't work on ours.

For this issue tho, we *do* cover some content pertaining to publishing. I'd like to take a closer look at this for our doc set. I'll take a look in December, when I hope to have more time.

**Comment by guardrex** [comment]
For their doc set, use the **This Page** feedback form at the bottom of their topic. That will ping their author with your feedback on the topic.

... but leave this issue open here. I'll get back to it later.
