### ISSUE TITLE
Cosmos Identity Custom storage provider

### ISSUE THREAD

**Issue by allan-mobley-jr** [aspnet/AspNetCore.Docs#15550]
I was hoping the ASP.NET Core Identity team would check out an open-source storage provider using Cosmos DB that I recently published. I followed your open source library very closely. Any feedback would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by allan-mobley-jr** [comment]
Guess it would help to leave a url to the repo: https://github.com/Mobsites/AspNetCore.Identity.Cosmos.

**Comment by Rick-Anderson** [comment]
@allan-mobley-jr  I marked this as a discussion issue.  Hopefully we can get some feedback.

**Comment by blowdart** [comment]
We don't do this in docs, we do it in the identity repo where you can see other examples.

https://github.com/aspnet/AspNetCore/tree/master/src/Identity

Create a PR with your link there.

**Comment by allan-mobley-jr** [comment]
Okay, thank you for responding.
