### ISSUE TITLE
UIFramework Does Not Exist in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by Jeramu** [aspnet/AspNetCore.Docs#15559]
In the #configure-identity-services-1 section .AddDefaultUI(UIFramework.Bootstrap4) is shown in the C# code example. UIFramework was not added until ASP.NET Core 2.2. This example should likely either be adjusted to .AddDefaultUI() or this method call simply removed from the example for ASP.NET Core 2.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Jeramu  thanks for bringing this to our attention.

**Comment by Rick-Anderson** [comment]
Moved to #16230
