### ISSUE TITLE
NSwag HTTP client generation - Command Line

### ISSUE THREAD

**Issue by TheMagnificent11** [aspnet/AspNetCore.Docs#15565]
The page suggests that there are several ways to generate an HTTP client but then only goes into detail about using NSwag Studio.

Ideally, I think most people would like the HTTP client to be generated when ASP.Net Core Web API project compiles.

It is my understanding that NSwag Studio uses the `nswag.exe` or `nswag.cmd` under the hood and thus you can use these commands and your NSwag configuration file to automatically generate your HTTP client.

So documentation about `NSwag.MSBuild` or the command-line options would be ideal.

Also, it is my understanding that NSwag Studio can generate the HTTP client from the ASP.Net Core Web API DLL and doesn't have to point that the Swagger document endpoint.  I think it would be good to include this example in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by RicoSuter** [comment]
I dont think we should repeat all documentation from the project wiki here. Otherwise it will be very hard to keep all the docs updated.

**Comment by RicoSuter** [comment]
But yes, you can create the configuration with NSwagStudio and the execute it with one of the command line tools (eg nseag.msbuild, or the nswag npm package).

**Comment by TheMagnificent11** [comment]
It's hard to find all the various CLI options in the wiki. Perhaps MS Docs should have more links NSwag wiki.

**Comment by TheMagnificent11** [comment]
Actually, I see that NSwag wiki hasbeen updated recently to be more comprehensive.

**Comment by StingyJack** [comment]
For anyone needing the link, its https://github.com/RicoSuter/NSwag/wiki/CommandLine
