### ISSUE TITLE
Warning shown when adding BuildServiceProvider in 3.0

### ISSUE THREAD

**Issue by NoahStahl** [aspnet/AspNetCore.Docs#15566]
As described, I added the new jsonPatchServices  ServiceCollection section to avoid using Newtonsoft.Json gloablly. When doing this, VS 2019 complains with this warning:

"Warning	ASP0000	Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created."

Is there any better option to achieve this without triggering such warning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm should we add a warning about `    var jsonPatchServices = new ServiceCollection();`

**Comment by NoahStahl** [comment]
Also, the provided example uses the patch-specific input formatter which only accepts the narrower content type "application/json-patch+json", rather than the typical default (and arguably better because flexible) "application/json". Leaving the default content type results in the same error and misled me for a good while.

So, here's a working example with warning suppressed and allowing multiple content types for a ASP.NET Core 3.0 Web API project:

var jsonPatchServices = new ServiceCollection().AddLogging().AddMvc().AddNewtonsoftJson();
#pragma warning disable ASP0000 // Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'
var jsonPatchServiceProvider = jsonPatchServices.BuildServiceProvider();
#pragma warning restore ASP0000 // Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'
var jsonPatchOptions = jsonPatchServiceProvider.GetRequiredService<IOptions<MvcOptions>>().Value;
var jsonPatchInputFormatter = jsonPatchOptions.InputFormatters.First(formatter => formatter.GetType().Name == "NewtonsoftJsonInputFormatter");

// Web API controllers
services.AddControllers(options => options.InputFormatters.Insert(0, jsonPatchInputFormatter));

**Comment by pranavkm** [comment]
How about this https://github.com/aspnet/AspNetCore.Docs/pull/15658?
