### ISSUE TITLE
UseStaticFiles still needed with UseFileServer for wwwroot

### ISSUE THREAD

**Issue by motohead400** [aspnet/AspNetCore.Docs#15578]
The documentation says UseFileServer is like calling UseStaticFiles, UseDefaultFiles, and UseDirectoryBrowser.  This is not the behavior I encountered with .net core 2.2 (Web API application).  I had to add a call to `UseStaticFiles ` in order for files to be served from the _wwwroot_ directory.  I wasted over an hour on this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not correct. See https://stackoverflow.com/a/50381816/502537

**Comment by motohead400** [comment]
I understand that's what it's SUPPOSED to do.  I read the documentation, as was obvious in my post.  However that is NOT the behavior I experienced.  Without app.UseStaticFiles() in my code below, static files in the wwwroot do not get served.  Maybe it has something to do with me adding an additional file provider?
![image](https://user-images.githubusercontent.com/23037268/68415000-5488e500-015f-11ea-8cbf-d6669aca12d9.png)

**Comment by Rick-Anderson** [comment]
If you check the source you'll see it calls `UseStaticFiles`

**Comment by Rick-Anderson** [comment]
Try to repo the problem without the file provider.

**Comment by motohead400** [comment]
I did as you suggested and if I just call app.UseFileServer() without passing the FileServerOptions into it I'm able to remove the call to app.UseStaticFiles() and still have files served from the wwwroot directory as would be expected.  So there seems to be a bug with using a file provider causing UseFileServer() to not allow files from the wwwroot directory to be served.

**Comment by Rick-Anderson** [comment]
@Tratcher is this expected? SHould we document this?

**Comment by Tratcher** [comment]
Yes, that's expected. UseStaticFiles/UseFileServer defaults to the file provider pointing at wwwroot. You can provide additional instances of UseStaticFiles/UseFileServer with other file providers to serve files from other locations.
