### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by bgilner** [aspnet/AspNetCore.Docs#15575]
The Generic Host restricts dependency injection with a breaking change over the existing Web Host: https://github.com/dotnet/docs/issues/14900

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  I thought that got added?

**Comment by Rick-Anderson** [comment]
@bgilner  that's documented [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#hostbuilder-replaces-webhostbuilder)

**Comment by guardrex** [comment]
Yes ... it's done. However, we cover breaking changes in the *Migration* topic set, not here (unless you want to). The problem with migration changes in the reference topics is that they muddy the topics badly over time.
