### ISSUE TITLE
IgnoreBody and IgnoreSection

### ISSUE THREAD

**Issue by xenophilios** [aspnet/AspNetCore.Docs#15573]
It would be nice if you could provide some examples to show how to use these two commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
