### ISSUE TITLE
Tag Helpers in Pages/Index.cshtml : Security Concerns

### ISSUE THREAD

**Issue by xenophilios** [aspnet/AspNetCore.Docs#15585]
The use of the tag helper "asp-route-id" leads to the ID being displayed in the query string. This seems to me to be an open invitation to hackers to mess with a site. Could you please explain how to get the same results without displaying any IDs to the user? Thank you for your trouble.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's only passed as a QS if the target page doesn't directive to make it route data `@page "{id}"`
Route data is just as easy to hack as QS.

**Comment by xenophilios** [comment]
Rick, Thank you for your fast response. Could you please clarify your first sentence with an example? Thank you for your trouble.
