### ISSUE TITLE
What is StringToByteArray?

### ISSUE THREAD

**Issue by yshahin** [aspnet/AspNetCore.Docs#15601]
StringToByteArray is not a C# function, it is not defined in the docs.
It should be replaced with `Convert.FromBase64String(headerValue)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0#configure-your-host-to-require-certificates)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
@Damienbod

**Comment by damienbod** [comment]
It's actually required.  Will add it.

´´´
private static byte[] StringToByteArray(string hex)
        {
            int NumberChars = hex.Length;
            byte[] bytes = new byte[NumberChars / 2];
            for (int i = 0; i < NumberChars; i += 2)
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            return bytes;
        }
´´´

Convert.FromBase64String(headerValue) would not work as it's not a base 64 string.

**Comment by damienbod** [comment]
Added a PR for this.

**Comment by guardrex** [comment]
Fixed by #15608

**Comment by vit100** [comment]
something wrong with StringToByArray()
For example, this is my sample certificate which Azure set in header:
`MIIB8zCCAWCgAwIBAgIQct6X6LxriYxOa3wCiYTikzAJBgUrDgMCHQUAMBgxFjAUBgNVBAMTDXN0ZWFtdWwta2lvc2swHhcNMjAwNDA1MjIwNzUxWhcNMzkxMjMxMjM1OTU5WjARMQ8wDQYDVQQDEwZraW9zazEwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMXbmbvIH8ZN7ZLjD6GyFyoE5lOfI+XjOwViQNdNLkR1cQXCE2HOi+phiULGKgePL3HpOsDsAVnpDi1KDMZotH0R/UIIrG1aHYWP82mCECwFywQjyXmY9EJxNJdoxsn/vnGrnscov1Uu6XIM3rLlkL+joGNuTk2Nr+ydkj2bHdxJAgMBAAGjTTBLMEkGA1UdAQRCMECAEFg+kLWROJ57iepJgKVqnuGhGjAYMRYwFAYDVQQDEw1zdGVhbXVsLWtpb3NrghDO46IgcEhEpEIAiaDdGxCwMAkGBSsOAwIdBQADgYEAUtDT2kleFvN6sx5h11XiUE7CIBO6VKVSA4aPOUXgKcSJEnsAV8Q1bedgS/NoPRNwx8KSwUYhNm3WnXCY1dzWHCKHcQ5gAyRyx0nhdQQyTgDGtmLXGcAWfgdRmNwecu+gNCRcYOJysfnUUORV6l+akpXUv/Sdtu8OqiAwUAaqCSU=
`
And this is error in this function:
`System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)`

**Comment by damienbod** [comment]
@vit100 depends how the client sends the data. In Azure, type of yes, you don't need any forwarding for Azure to work, this works per default, so  you shouldn't need to configure the forwarding in ASP.NET Core, but yes base64 is used.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#use-certificate-authentication-in-azure-web-apps

**Comment by vit100** [comment]
Ok. Let me then be more specific in PR which I created for this.
Point is that people most likely will use it with Azure - at least I hope, Azure is first choice -)).

**Comment by damienbod** [comment]
correct, and Azure requires no forwarding so you never need to implement the AddCertificateForwarding if you use Azure

**Comment by vit100** [comment]
Pls look at this PR
https://github.com/dotnet/AspNetCore.Docs/pull/17657

I mentioned explicitly that Azure does require some config: header -> X-ARR-ClientCert

**Comment by damienbod** [comment]
I will comment on the PR, good?

I think the base64 solution is better, what you suggested because this is more common. But AddCertificateForwarding should not be required either for Azure. It should just work. The example linked above works in Azure.
