### ISSUE TITLE
Remove empty comment

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore.Docs#15606]
Empty comment in

```
&lt;!--  --&gt;
&lt;script&gt;
  window.setElementText = (element, text) =&gt; element.innerText = text;
&lt;/script&gt;
```

Want a pr as it will only take a few secs for me to sort?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Matthew-Bonner** [comment]
Also, off topic sorry, but how do I copy and paste code without it being double encoded?

**Comment by guardrex** [comment]
That's strange! Yes, *please* on the PR. Very helpful. We're 🏃😅.

 > copy and paste code without it being double encoded

You can't when using the feedback form on the topics. You have to edit the opening comment after the issue opens and fix it up (or re-paste it over what it took; or just add it for the first time). The feedback form *always* encodes.

**Comment by guardrex** [comment]
Better hold off for a sec. I think that might be a doc build system bug 🐞. I'm looking now. brb

**Comment by guardrex** [comment]
Oh ... ok ... yeah ... I see it now.

https://github.com/aspnet/AspNetCore.Docs/pull/15143/files#diff-ba09a6728aaba51215c9f92ba679a035

Yes, please do fix that if you want.

**Comment by guardrex** [comment]
I was looking at the doc in the metadata here (JS interop), but it's actually in the includes file.

**Comment by guardrex** [comment]
@Matthew-Bonner ... do u still want to take care of this, or should I go ahead and knock it out?

**Comment by guardrex** [comment]
I'll get it ..... I have a minute here.
