### ISSUE TITLE
 self-signed cert error

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore.Docs#15605]
The certificates still give an error that they are not trusted because they are self-signed, anyone trying this article coming into this from a background of developing locally over http will likely need additional instructions on how to get around the certificate error. Is it worth linking out to somewhere in the docs where a list of instructions can be found on how to install a self signed certificate in browsers so that they consider the certificate to be trusted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Matthew-Bonner** [comment]
I guess this is somewhat related to https://github.com/aspnet/AspNetCore.Docs/issues/14756 rather than just saying it isn't supported, linking out to some instructions on how to fix will help.

**Comment by guardrex** [comment]
It's addressed, but not necessarily fully covered (e.g., Firefox explicitly), in ...

https://docs.microsoft.com/aspnet/core/security/enforcing-ssl

**Comment by guardrex** [comment]
Duplication, too, of https://github.com/aspnet/AspNetCore.Docs/issues/13005.

Might need to move your remark here for the SignalR doc over to a comment on that issue and then close this one.

**Comment by Rick-Anderson** [comment]
Closing because dup.
