### ISSUE TITLE
Recommended pattern for direct DOM manipulation in Blazor

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#15603]
[EDIT by guardrex to add the metadata for the *Components* topic]

Normally we just tell people not to do it because it's unsafe, but if your goal is to integrate with some 3rd-party JS library that produces DOM output, then we'd like to be able to describe what kind of thing is legit to do.

For example, we could elaborate on [this comment](https://github.com/aspnet/AspNetCore.Docs/issues/12020#issuecomment-485552533) and put it in docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#cookies)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's *very* briefly mentioned in *Components* ...

> `OnAfterRenderAsync` and `OnAfterRender` ... Use this stage to perform additional initialization steps using the rendered content, such as activating third-party JavaScript libraries that operate on the rendered DOM elements.

... and the "unsafe" advice that you mentioned under *Capture references to elements* in the JS interop topic ...

> Do **not** use captured element references as a way of populating the DOM. Doing so may interfere with the declarative rendering model.

... but then (next sentence) it *vaguely* states ...

> `ElementReference` ... the JavaScript-side code receives an `HTMLElement` instance, which it can use with normal DOM APIs.

I'll improve the content using your language/example.
