### ISSUE TITLE
Confusion about whether 2.2 behaviour produces ProblemDetails or ValidationProblemDetails

### ISSUE THREAD

**Issue by Dave-Lowndes** [aspnet/AspNetCore.Docs#15602]
In the section headed "Default BadRequest response", it says:
"With a compatibility version of 2.2 or later, the default response type for an HTTP 400 response is ValidationProblemDetails."

However, under the heading "Problem details for error status codes", it says:
"When the compatibility version is 2.2 or later, MVC transforms an error result (a result with status code 400 or higher) to a result with ProblemDetails."

Is there some subtle difference in circumstance here that I'm not seeing, or is one of those statements wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#disable-automatic-400)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by pranavkm** [comment]
Consider:

```
public IActionResult Post(MyModel model)
{
   var storedModel = store.Find(model.Id);
   if (storedModel == null) return NotFound();
   ....
}
```

When model validation fails when deserializing the `model` instance, MVC returns a 400 response with `ValidationProblemDetails`. 

> "With a compatibility version of 2.2 or later, the default response type for an HTTP 400 response is ValidationProblemDetails."

^ This statement clarifies this behavior and is part of this section https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses. 

For the `return NotFound()` in the action, MVC will transform it to a `ProblemDetails` response. The latter statement is talking about this.

Does this help?

**Comment by Dave-Lowndes** [comment]
> Does this help?

I'm afraid not.

My situation...
We've a REST API that's annotated:
`        [ProducesResponseType(StatusCodes.Status400BadRequest)]`
with a parameter (that's a member of a class that's passed to the API) that has a StringLength annotation.

If our client (a PowerShell cmdlet) passes too long a string then it rightly fails the validation.

However the nswag generated code produces an ApiException<ProblemDetails>.

If I change our annotation to specify the type:
`        [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]`
the nswag generated code produces an ApiException<ValidationProblemDetails> - which is what I'd expected by default from the initial documentation reference - until I encountered the second reference and got totally confused!

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Dave-Lowndes** [comment]
@Rick-Anderson I'd already replied that the reply from @pranavkm didn't help, so I fail to see why you've closed this as answered. The answer may make sense to you from the inside, but it's still inconsistent from my perspective.
