### ISSUE TITLE
SameSite doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15615]
* Create doc under aspnet/core/security/ (or should it be under aspnet/core/security/ authentication
* Doc based on https://github.com/aspnet/Announcements/issues/390 
* Publish doc (so it’s localized).
* Start adding links to the doc where needed.

related: #15223

**Comment by Rick-Anderson** [comment]
@Tratcher @blowdart  please review. Should I borrow heavily from aspnet/Announcements#390 ?

**Comment by Tratcher** [comment]
> Should I borrow heavily from [aspnet/Announcements#390](https://github.com/aspnet/Announcements/issues/390) ?

Yes.
