### ISSUE TITLE
Explain how to use the HtmlAttributeName attribute

### ISSUE THREAD

**Issue by lol768** [aspnet/AspNetCore.Docs#15626]
Unless I've missed it, I don't think it's covered. I'd like a simple example, something like:

```csharp
[HtmlTargetElement("div")]
public class MyTagHelper : TagHelper
{
    [HtmlAttributeName("asp-do-thing")]
    public bool? DoThing { get; set; }

    public override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        // some logic querying value of DoThing
    }
}
```

I appreciate the doc already covers passing a model object instance via a TagHelper, but from what I understand Razor is just looking to see that the property and attributes names match up. So it would be useful to show how to override this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by lol768** [comment]
@Rick-Anderson Will you review a PR that adds it?

**Comment by Rick-Anderson** [comment]
@NTaylorMullen ?

**Comment by NTaylorMullen** [comment]
I'd review it

**Comment by Rick-Anderson** [comment]
@lol768 ping me when your ready to PR this and I'll open the issue.
