### ISSUE TITLE
show example using HttpClientFactory

### ISSUE THREAD

**Issue by AliNazar1991** [aspnet/AspNetCore.Docs#15621]
Instead of using a static reference to httpClient, show an example using the HttpClientFactory in asp net core applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9e2f78-9caf-3b88-05a6-537e031ecddf
* Version Independent ID: 06ca8420-5ca0-24ae-3584-9a4c486d3ebe
* Content: [Memory management and patterns in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/performance/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AliNazar1991 ... The topic cross-links to that coverage, so there doesn't seem to be a need for an example of it here. At the end of the section that pertains to `HttpClient`, the text states ...

> See the following for a better way to handle the lifetime of an HttpClient instance:
>
> * HttpClient and lifetime management
> * HTTPClient factory blog

The first bullet links off to the [HTTP requests topic](https://docs.microsoft.com/aspnet/core/fundamentals/http-requests).

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
