### ISSUE TITLE
Static files publicly available

### ISSUE THREAD

**Issue by vankampenp** [aspnet/AspNetCore.Docs#15622]
When using a default policy
 services.AddAuthorization(options =&gt;
            {
              options.FallbackPolicy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
           }
Static files that are not found do not return a not found error, but a page not unauthorized error. Any idea why that is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Show your `Startup.Configure` in case this is a middleware ordering issue.

**Comment by Rick-Anderson** [comment]
> Static files that are not found do not return a not found error

Either way, it's an error
