### ISSUE TITLE
bugfix

### ISSUE THREAD

**Issue by leftmostlane** [aspnet/AspNetCore.Docs#15631]
For 3.1 Preview, this:
    &lt;InputText id="name" @bind-Value="@exampleModel.Name" /&gt;
should be:
    &lt;InputText id="name" @bind-Value="exampleModel.Name" /&gt;
(remove that second @ sign).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, that's right ... thanks for spotting that. I'll patch it right now.
