### ISSUE TITLE
Use Component Section Code Shows Compile and Runtime Errors but app still works

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#15633]
I replicated the ChildComponent (Components Folder) and ParentComponent code (Pages Folder) as they appear in this page.
However at the following parameters: 
&lt;div class="panel-heading"&gt;@Title&lt;/div&gt;
    &lt;div class="panel-body"&gt;@ChildContent&lt;/div&gt;

    &lt;button class="btn btn-primary" @onclick="OnClick"&gt;
In the above lines, @Title, @ChildContent and @onclick show squiggly lines (doesn't exist in the context)
also @code section and [Parameter} indicates don't exist in the context
However the code builds and runs to show everything working. 
Can someone replicate and tell me the reason please?
I am using VS 2019 Community (16.3.8)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @krchome ... We only handle documentation issues here. Report that behavior to the VS team by using the **Report a problem** process from within VS.
