### ISSUE TITLE
Documentation is repeated

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/AspNetCore.Docs#15644]
Documentation content is duplicated:
![image](https://user-images.githubusercontent.com/1784452/68549838-4e467300-03c2-11ea-8cef-45f67cda8469.png).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @MisinformedDNA ... probably just a broken versioning setup. I'll fix it up right now.
