### ISSUE TITLE
Ought to mention solutions

### ISSUE THREAD

**Issue by david-rachwalik** [aspnet/AspNetCore.Docs#15643]
Please add steps for 'dotnet new sln'.  You could mention it's optional or perhaps link to another page with more details.  As it is now just making a directory and jumping right to the project is super confusing for anyone who'd like to learn dotnet scripting and is comparing results to something VS creates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
