### ISSUE TITLE
3.0 update:  : Configure ASP.NET Core Data Protection

### ISSUE THREAD

**Issue by aszalacinski** [aspnet/AspNetCore.Docs#15641]
At the top of the various options, it needs to be called out which packages need to be installed to enable the dataprotection extensions. I had to install

Microsoft.AspNetCore.DataProtection.AzureStorage
Microsoft.AspNetCore.DataProtection.AzureKeyVault

just to get things to compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Requires 3.0 update:
Reference the same shared framework version via the Microsoft.AspNetCore.App metapackage.
