### ISSUE TITLE
Catch-all routing not supported

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore.Docs#15652]
Update the "Route Parameters" section to note that asterisk catch-all routes are not supported.

See https://github.com/aspnet/AspNetCore/issues/16953

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#route-parameters)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The content that addresses this is over in the Blazor Routing topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#routing-with-urls-that-contain-dots

Which was added on ...

https://github.com/aspnet/AspNetCore.Docs/pull/13971/files

... and it was added for a Razor file (*_Host.cshtml*), not a Razor Component, as you found out.

I'll make a couple of changes here probably ...

* Let's call out the Razor Components scenario with catch-all.
* Perhaps, the section organization needs a little work: The catch-all is described in a section about dot notation, which are distinct concepts.

Thanks for opening this issue. I'm 🏃 at the moment and will try to get to this next week or the week after.

**Comment by chaojian-zhang** [comment]
Is there any workaround to this? 
I tried to use a controller for the same routing except the controller has a catch-all, but the controller will always take precedence over the Blazor component, making it no way to handle such scenarios.

**Comment by guardrex** [comment]
@chaojian-zhang In the future, please open a new issue using the **This page** feedback button and form at the bottom of any topic and then cross-link the closed issue/PR. We don't work closed issues and PRs.

To answer your question tho: I don't have any further information from engineering on it. You would need to open a new issue with engineering :point_right: https://github.com/dotnet/aspnetcore/issues ... but note that they've already been asked and (apparently) decided not to support it (https://github.com/dotnet/aspnetcore/issues/16953).
