### ISSUE TITLE
Entity Framework Core example should also include AddDbContext code

### ISSUE THREAD

**Issue by caihongxu** [aspnet/AspNetCore.Docs#15659]
Need something like the following line to make it work:
services.AddDbContext(MyKeyContext&gt;(options =&gt;
        options.UseSqlServer(
            Configuration.GetConnectionString("MyKeyDbConnection"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you saying the following doesn't work?

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));

    // using Microsoft.AspNetCore.DataProtection;
    services.AddDataProtection()
        .PersistKeysToDbContext<MyKeysContext>();

    services.AddDefaultIdentity<IdentityUser>()
        .AddDefaultUI(UIFramework.Bootstrap4)
        .AddEntityFrameworkStores<ApplicationDbContext>();
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

**Comment by ianfoster99** [comment]
caihongxu is correct. This worked for me
               _services.AddDbContext<DPKeysContext>(_options =>
                {
                    _options.UseSqlServer(Configuration.GetValue<string>("ConfigSqlConnectionLive:DefaultSqlConnection")
                        , sqlServerOptionsAction: _sqlOptions =>
                        {
                            _sqlOptions.EnableRetryOnFailure(maxRetryCount: 10, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null)
                            .UseNetTopologySuite();
                        })
                    //.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning)); // https://docs.microsoft.com/en-us/ef/core/querying/client-eval
                    ;
                }, ServiceLifetime.Scoped
                );

**Comment by caihongxu** [comment]
Correct. Without AddDbContext the context is not properly set up to connect to the data base.

**Comment by pranavkm** [comment]
@ajcvickers could you have someone take a look at this?

**Comment by ajcvickers** [comment]
@pranavkm The content indicates at the end that `MyKeyContext` is used, but it isn't mentioned anywhere else in the page, so I would say this is valid feedback.

**Comment by ajcvickers** [comment]
@pranavkm Not sure why you assigned this to me. This isn't EF content; I would expect someone on the ASP.NET team to fix this.

**Comment by pranavkm** [comment]
You're right @ajcvickers, I based it on the title. @mkArtakMSFT could you re-assign this?

**Comment by mkArtakMSFT** [comment]
Thanks @ajcvickers and @pranavkm. This is indeed data protection related. @anurse who would be the best person to review this?

**Comment by anurse** [comment]
I don't have anyone who could review it right now. I'll take a look myself and see what I can find out. It looks like a straightforward bit of missing configuration.

**Comment by anurse** [comment]
Opened https://github.com/aspnet/AspNetCore.Docs/pull/15681 to fix this.
