### ISSUE TITLE
Add clarification to note "It's not possible to configure JSON serialization in the JavaScript client at this time."

### ISSUE THREAD

**Issue by politigf** [aspnet/AspNetCore.Docs#15657]
In the "Switch to Newtonsoft.Json" section, there is a note that states "It's not possible to configure JSON serialization in the JavaScript client at this time.". If that means that one cannot use the javascript SignalR client with Newtonsoft.Json it should specifically state it, otherwise it should list what is needed to accomplish this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-3.0&tabs=dotnet#feedback)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
I think the note was accidentally moved when we added the "Switch to Newtonsoft.Json" section. It should be moved to the previous section.

**Comment by Rick-Anderson** [comment]
@BrennanConroy  @anurse @bradygaster  This doc is a mess. We don't version doc's like this, it leads to this type of problem. It's difficult to reason about the topic and difficult to update and maintain. This is how we do versioning:

```
::: moniker range=">= aspnetcore-3.0"
// Copy exiting MDF file here, and update to 3.0
::: moniker-end

::: moniker range="< aspnetcore-3.0"
// Original file here
::: moniker-end
```

So each version has a complete copy. Although this leads to duplication of content, we've found it to be much more robust and productive. Another tip that you should consider when adding a new version to to create a prepared PR that has the new version, but no new/updated content. For example:

```
::: moniker range=">= aspnetcore-3.0"
// Copy exiting MDF file here, no changes except the following
Warning: This content has not been updated to 3.0 yet.
::: moniker-end

::: moniker range="< aspnetcore-3.0"
// Original file here
::: moniker-end
```

Merge the preceding PR. Then when you upgrade the content, the GitHub diff is very productive to see what has changed.
