### ISSUE TITLE
ContextID 32 should have been in the ID-to-project file mapping but wasn't!

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15661]
@TopGuo commented on [Mon Nov 11 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/216)

ContextID 32 should have been in the ID-to-project file mapping but wasn't!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [ASP.NET Core 中的捆绑和缩小静态资产](https://docs.microsoft.com/zh-cn/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

---

@srvbpigh commented on [Mon Nov 11 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/216#issuecomment-552346425)

Hello, @TopGuo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
What is `ContextID` 32?

**Comment by Rick-Anderson** [comment]
Closing due to no response from @TopGuo
