### ISSUE TITLE
app.UseRouting() should be after UseAuthentication and UseAuthorization?

### ISSUE THREAD

**Issue by yetanotherchris** [aspnet/AspNetCore.Docs#15669]
**.NET 3.0 documentation**

```
If the app uses authentication/authorization features such as AuthorizePage or [Authorize], 
place the call to UseAuthentication and UseAuthorization: after, UseRouting and UseCors, 
but before UseEndpoints:
```

This doesn't appear to be correct for an API project? However I have a few other Middleware extensions being used: Swagger,  ForwardedHeaders, JsonExceptions.

The variations I've tried:

#### Working
```
app.UseAuthentication();
app.UseAuthorization();
app.UseRouting();
```

```
app.UseAuthorization();
app.UseAuthentication();
app.UseRouting();
```

#### Not working

(Putting UseRouting first)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Can you share a complete `Configure` method?

**Comment by yetanotherchris** [comment]
```
// You can add these parameters to this method: IHostingEnvironment env, ILoggerFactory loggerFactory
		public override void Configure(IApplicationBuilder app)
		{
			app.UseAuthentication();
			app.UseAuthorization();

			app.UseSwaggerWithReverseProxySupport();
			app.UseRouting();

			app.UseEndpoints(endPoints =>
			{
				endPoints.MapControllers();
			});

			app.UseJsonExceptionHandler(_hostingEnvironment);
			app.UseForwardedHeaders(new ForwardedHeadersOptions
			{
				ForwardedHeaders = ForwardedHeaders.All
			});
			app.UseJsonHealthChecks();
		}
```

**Comment by yetanotherchris** [comment]
The version that _doesn't_ work puts UseRouting first

**Comment by serpent5** [comment]
I see a few quirks in the setup you've got. Does the following work?

```csharp
app.UseRouting();
app.UseAuthentication();
// app.UseAuthorization();
app.UseEndpoints(...);
```

**Comment by yetanotherchris** [comment]
> I see a few quirks in the setup you've got. Does the following work?
> 
> ```cs
> app.UseRouting();
> app.UseAuthentication();
> // app.UseAuthorization();
> app.UseEndpoints(...);
> ```

No it needs Authorization, or the Controller I am testing (which just creates a user) has this error:

```
Failed on thread 48. Endpoint Roadkill.Api.Controllers.UsersController.CreateEditor (Roadkill.Api) contains authorization metadata, but a middleware was not found that supports authorization.
```

**Comment by guardrex** [comment]
I'm not a "Swagger guy" but just curious @yetanotherchris if you tried to set the middlewares in the following order ...

```csharp
public override void Configure(IApplicationBuilder app)
{
    app.UseSwaggerWithReverseProxySupport();
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    ...
}
```

**Comment by serpent5** [comment]
How confident are you that you're providing a token and that it's valid, etc? If you do what you're doing with the authz stuff before `UseRouting`, it looks like you're really just _disabling_ authz in a roundabout fashion. Have you tried calling the endpoint when it works, but without providing a token?

**Comment by yetanotherchris** [comment]
The code (actually a soak test, calling the controller 50 times concurrently to test ASP.NET Identity on Marten with Postgres) works prior to the .NET 3.0 upgrade. I haven't delved into the internals of the authz and authentication middleware, so I'm not sure if this is from another Middleware interfering - but from what I can tell it could only be Swagger.

I'll try removing Swagger from the project and see if the order matters then - but I think Swagger (NSwag) is a fairly common use case for a web api project.

**Comment by yetanotherchris** [comment]
Just for the record:

```
public static IApplicationBuilder UseSwaggerWithReverseProxySupport(this IApplicationBuilder app)
{
    app.UseSwagger(config => config.PostProcess = (document, request) =>
    {
        string pathBase = request.Headers["X-Forwarded-PathBase"].FirstOrDefault();
        document.BasePath = pathBase;
        document.Host = request.Headers["X-Forwarded-Host"].FirstOrDefault();
    });

    app.UseSwaggerUi3(settings =>
    {
        settings.TransformToExternalPath = (route, request) =>
        {
            string pathBase = request.Headers["X-Forwarded-PathBase"].FirstOrDefault();

            if (!string.IsNullOrEmpty(pathBase))
                return $"{pathBase}{route}";

            return route;
        };
    });

    return app;
}
```

**Comment by yetanotherchris** [comment]
I tried Startup.cs with `//app.UseSwaggerWithReverseProxySupport();` and the same error persists.

**Comment by serpent5** [comment]
With the correct middleware ordering, your JWT (or whatever) is being rejected (it's either invalid or perhaps there's a missing role). When you reorder the middleware as described, I doubt that the token is even being checked, so the request flows through to the endpoint _unauthenticated_.

This isn't an issue with the docs page.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by yetanotherchris** [comment]
Thank you all for your help, it was indeed some bad being sent, and also being interpreted which a custom `IAuthorizationRequirement` solved (really good docs can be found [here](https://www.red-gate.com/simple-talk/dotnet/c-programming/policy-based-authorization-in-asp-net-core-a-deep-dive/) on the subject).

I realise it's not a docs-related issue, but if `app.UseAuthentication();app.UseAuthorization();` had a way of knowing if EndPointRoutingMiddleware was registered, and throw that would be a nice addition - i'll possibly suggest it in a different PR or issue.

**Comment by serpent5** [comment]
> had a way of knowing if EndPointRoutingMiddleware was registered, and throw

It does, there's just a very unfortunate bug in the current 3.0 that only catches a completely missing `UseAuthorization` call. It's [been fixed](https://github.com/aspnet/AspNetCore/pull/14893) but hasn't been released yet.
