### ISSUE TITLE
Does AuthorizeFolder not apply to sub-folders?

### ISSUE THREAD

**Issue by tb-mtg** [aspnet/AspNetCore.Docs#15677]
Does AuthorizeFolder only apply to the specified folder and not sub-folders?

If not, how can the AuthorizeFilter to be added all of the pages in a under a specified folder including sub-folders?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tb-mtg ...

Engineering approved the following ...

> to all of the pages in a folder at the specified path:

... did you find that sub-folders weren't covered by a path to a given folder?

**Comment by tb-mtg** [comment]
Yes only the specified folder was required Authorization.
```
var mvcBuilder = services.AddRazorPages(razorPageOptions => {
  razorPageOptions.Conventions.AuthorizeFolder("/");
  razorPageOptions.Conventions.AuthorizeFolder("/it");
  razorPageOptions.Conventions.AllowAnonymousToPage("/index");
  razorPageOptions.Conventions.AllowAnonymousToPage("/error");
  razorPageOptions.Conventions.AllowAnonymousToPage("/privacy");
});
```
I initially wanted all folders requiring Authorization by default (using **.AuthorizeFolder("/")**) except for a pages listed above but that didn't work.

So I tested with **.AuthorizeFolder("/it")** and:
* /it required Authorization 
* /it/test does not require Authorization

**Comment by guardrex** [comment]
@pranavkm ... the behavior isn't consistent with the doc ... should this be moved to the engineering repo for investigation? ... or should we say that 'every folder requires auth' (i.e., `AuthorizeFolder("/it/test");` is required in this scenario)?

**Comment by tb-mtg** [comment]
Sorry, I just wokred out that [AllowAnonymous] attribute on PageModel overrides RazorPagesOptions.Conventions.

So it is working now on sub-folders.
