### ISSUE TITLE
Improve documentation for mismatch between assembly name + root namespace + localization

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#15673]
We should clarify the kinds of errors that can occur when assembly name and root namespace differ (for localization) and provide examples of cases that cause this (non-C#-identifiers as project names). This is a common source of mistakes, and the docs don't really explain it well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.* OK, I won't

* ID: bcfc7f38-7c0f-cc95-92c4-e99e0ad1812e
* Version Independent ID: 9a1dccda-d7bf-1eb5-e5e3-8aba4aeb444f
* Content: [Troubleshoot ASP.NET Core Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/troubleshoot-aspnet-core-localization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @hishamco
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
@rynowak i think we already described this in troubleshooting article

/cc @Rick-Anderson
