### ISSUE TITLE
Document Blazor's MonoLinkerI18NAssemblies build option

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#15679]
This is to help with customer scenarios like https://github.com/mono/mono/issues/17363

By default, Blazor's linker config strips out all internationalization information except for locales explicitly requested. This is to minimize the app size, since the data is quite large.

We have a build setting to control this, e.g.:

```xml
<PropertyGroup>
    <MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>
</PropertyGroup>
```

The default value of `MonoLinkerI18NAssemblies` is `none`. Other available options are (according to [this](https://github.com/mono/linker/tree/master/src/linker#mono-specific-options)) are `none`, `all`, `cjk`, `mideast`, `other`, `rare` or `west`. They can be comma-separated (e.g., `cjk,west`).

**Comment by catlan** [comment]
Is it possible that `<MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>` is not taking into account when the linker is disabled? For development builds this seems to be the default since 3.2.0 Preview 2.

This is working for me:
```
  <PropertyGroup>
    <BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>
    <MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>
  </PropertyGroup>
```

**Comment by guardrex** [comment]
@catlan ... Please open a new issue from the bottom of the topic. Use the **This page** feedback button+form. We have trouble tracking on closed issues and PRs.
