### ISSUE TITLE
can't create .mdf file because it is missing a \ divider

### ISSUE THREAD

**Issue by gregveres** [aspnet/AspNetCore.Docs#15680]
I have followed along with this tutorial. I am on windows. I note that this page says we will be using sqlite, but when I create the migration, it says that it is "using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None".
When I try to run the Update-Database command, I get an error that access is denied while attempting to open or create the physical file `C:\Users\gregvRazorPagesMovieContext-53b8cccb-6e84-4a19-8c01-d086db07b19c.mdf'.
Notice the lack of a '\' between gregv and 'RazarPagesMovie...`. 
You may want to point people to where to fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by torpederos** [comment]
To fix this issue you must install Cumulative Update for SQL Server 2017. Latest version is available on https://support.microsoft.com/en-ca/help/4515579/cumulative-update-17-for-sql-server-2017

**Comment by gregveres** [comment]
That did fix it BTW.

**Comment by Rick-Anderson** [comment]
@tdykstra  this comes up every month. I'll ping you when I need to find it again.
