### ISSUE TITLE
This doesn't say why Razor file compilation is now an opt-in feature in .NET Core 3.0

### ISSUE THREAD

**Issue by xantari** [aspnet/AspNetCore.Docs#15690]
Is it due to performance? What kind of performance gains can we expect? Other reasons?

@Rick-Anderson  edit: See https://github.com/aspnet/Announcements/issues/343 and https://github.com/aspnet/Announcements/issues/312

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Rick-Anderson  @pranavkm what's the primary reasons for Razor file compilation now opt-in?

**Comment by pranavkm** [comment]
Primarily this - https://github.com/aspnet/Announcements/issues/325. But in general build time compilation is much faster compared to runtime compilation. In previous releases, JITing Roslyn's binaries took up a bulk of the time in cold start performance.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Announcements/issues/343

**Comment by Rick-Anderson** [comment]
This will be documented in this issue.
