### ISSUE TITLE
Update log level at runtime without app restart?

### ISSUE THREAD

**Issue by SidShetye** [aspnet/AspNetCore.Docs#15698]
This document is missing how to update the loglevel at runtime without restarting the application. Example: the default logLevel is `warning` but when we have an issue in production for a component like `root.level1.component1`, we'd like to change that to `information` without restarting the application (and losing packets) to observe what's going on.

The `appsettings.json` equivalent would be 

```
"logging": 
    "logLevel": {
      "default": "warning",
      "root.level1.component1": "information"
    }
  }
```

**How** the user provides the component namespace and new loglevel can be outside the scope but it's unclear what APIs in logging support changing the log levels at runtime. 

Please document that here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by guardrex** [comment]
Engineering to comment on this one: It wasn't a design scenario AFAIK. Let's backlog it until one of them gets a chance to look.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#sources-and-providers

Configuration providers that implement change detection have the ability to reload configuration when an underlying setting is changed. For example, the File Configuration Provider (described later in this topic) and the Azure Key Vault Configuration Provider implement change detection.

**Comment by davidfowl** [comment]
Works fine.

**Comment by guardrex** [comment]
I misread this ... thought it was more about performing this via the Logging API ... the answer is much simpler than that. (I need some 💤🛌💤 ... been up since 5am.)

Do you want me to check the logging doc to see how it handles/cross-links to log config reloading?

**Comment by SidShetye** [comment]
It's great that `ILoggingBuilder.AddConfiguration` automatically updates logLevels for change detecting configuration providers. However, our workflow is to change site global parameters from our admin console (vs remoting into every instance to modify the `appsettings.json`), so we're looking for some API into Logging that can be explicitly called from our admin console saying "use these updated settings". 

Short of writing a custom configuration provider that supports reloading/polling to fit into the `ILoggingBuilder.AddConfiguration` model, is there any way in logging to support the above?

**Comment by guardrex** [comment]
> so we're looking for some API into Logging that can be explicitly called from our admin console

Ah, so my initial (and half-asleep 💤) reading was correct about your scenario.

Since we know now that logging picks up it's log levels on-the-fly from configuration, can you have a secure (perhaps internal) endpoint on each app that changes the configuration value(s) for logging? Just set a new log level value for a logging configuration key, such as `Logging:LogLevel:Default`. It should immediately take effect. I plan to play with this scenario when I get to work on this issue, but it sounds like that will work.

**Comment by SidShetye** [comment]
Yeah, basically a `ConfigurationProvider` at one end (for `ILoggingBuilder.AddConfiguration`) but some extra logic at the other end. A rest endpoint won't work because it'll ping only a single instance's configuration. What's needed is something shared across all instances like the database or a publisher-subscriber bus. 

Extending your already documented [database configuration provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#custom-configuration-provider) for polling async would actually work.

On a related note, I suggest that example be tweaked something along the lines (verbose for clarity)
```
builder.ConfigureAppConfiguration((hostingContext, config) =>
{
  config.AddJsonFile($"appsettings.json", optional: true, reloadOnChange: true);
  config.AddEnvironmentVariables();
  
  var configSoFar = config.Build();
  var connStr = configSoFar.GetSection("appSettings:connectionString").Value;
  config.AddEFConfiguration(opt => 
  {
    opt.UseSqlServer(connStr);
  });
})
```
That minor tweak for the connection string makes the example *far* more useful by using a real database, without hard coding strings and using any production-ready config provider till that point. All without really distracting from the illustrative goal of that example.

I'll close this ticket for now since the question about existence of APIs was implicitly answered.

**Comment by davidfowl** [comment]
> Short of writing a custom configuration provider that supports reloading/polling to fit into the ILoggingBuilder.AddConfiguration model, is there any way in logging to support the above?

There's no logging API to refresh levels. Today our logger providers implementations use configuration to reload when changes happen. You'd need to write a custom configuration provider that changed whenever those values were provided via an HTTP request (assuming that's what you wanted to do).

**Comment by davidfowl** [comment]
Assuming you can update the configuration source (maybe via an HTTP call or by some other means). You can also force a reload by calling `IConfigurationRoot.Reload`.

**Comment by guardrex** [comment]
Let's leave this open ... I haven't had time to see where the topic stands on this subject.
