### ISSUE TITLE
How to get all strings that need translation?

### ISSUE THREAD

**Issue by qvisionsa** [aspnet/AspNetCore.Docs#15693]
I'm using the approach mentioned in this doc that says "You can leave the default language literal strings in the app and wrap them in the localizer, so that you can focus on developing the app."

I need also to use a database for localization strings, because I have to export the English text and forward this text to a translation service office, to translate it in different languages. I need to do this, because there are technical terms that must be accurate.

I tried to follow sample code from Github that uses EFStringLocalizer, but this implementation (if I understand well)  assume that the strings for translation are already in the database.

Now that I've finished my multi project application, what is the method to take all these strings (from different assemblies)  and  write them in a table?
Can I use a method in the startup of the application to do it, or is there another method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0&source=docs#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Related issue #15583

**Comment by hishamco** [comment]
As I mentioned earlier `GetAllStrings()` will return all the localized strings and their values, so you can iterate through the collection and insert the resource names into the database

**Comment by qvisionsa** [comment]
@hishamco This is the implementation from EF Localization sample. GetAllStrings returns resources that are already in the database. 

public IEnumerable<LocalizedString> GetAllStrings(bool includeAncestorCultures)

        {

            return _db.Resources

                .Include(r => r.Culture)

                .Where(r => r.Culture.Name == CultureInfo.CurrentCulture.Name)

                .Select(r => new LocalizedString(r.Key, r.Value, true));

        }

**Comment by hishamco** [comment]
I mean to use the `GetAllStrings()` from `ResourceManagerStringLocalizer` :smile:
