### ISSUE TITLE
no authentication scheme is specified when default is not specified

### ISSUE THREAD

**Issue by rameshjanjyam** [aspnet/AspNetCore.Docs#15695]
doc says we can have parameterless `AddAuthentication()` but for me it's running to no default specified error. 
```
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultAuthenticateScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action&lt;AuthenticationOptions&gt; configureOptions).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The first sample is parameterless
```
public void ConfigureServices(IServiceCollection services)
{
    // Code omitted for brevity

    services.AddAuthentication()
        .AddCookie(options => {
            options.LoginPath = "/Account/Unauthorized/";
            options.AccessDeniedPath = "/Account/Forbidden/";
        })
        .AddJwtBearer(options => {
            options.Audience = "http://localhost:5001/";
            options.Authority = "http://localhost:5000/";
        });
```

**Comment by Rick-Anderson** [comment]
Specifying the default scheme results in the `HttpContext.User` property being set to that identity. If that behavior isn't desired, disable it by invoking the **parameterless** form of `AddAuthentication`.

**Comment by rameshjanjyam** [comment]
when it is left parameters I am running into this error  I have mentioned in the question 
```
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultAuthenticateScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action&lt;AuthenticationOptions&gt; configureOptions).
```

do you have a working sample that I can run to verify it?

**Comment by saeidjoker** [comment]
I'm also having this problem. Any Ideas?

**Comment by Rick-Anderson** [comment]
Moved to Master issue for: Authorize with a specific scheme #16190

**Comment by HaoK** [comment]
If you don't specify a default authentication scheme, you cannot have an [Authorize] attribute that doesn't specfiy a scheme.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Talha-Farrukh** [comment]
I'm going through this issue can you help me

**Comment by Sollace** [comment]
Having the same problem here. I don't know what it expects from me
```CSharp
        builder.Services.AddOpenIddict(options => {
            options.AddCore();
            options.AddServer(builder => {
                builder.AllowClientCredentialsFlow();
                builder.SetTokenEndpointUris("v1/token");
                builder.SetAccessTokenLifetime(TimeSpan.FromMinutes(60));
                builder.AddDevelopmentEncryptionCertificate();
                builder.AddDevelopmentSigningCertificate();
                builder.UseAspNetCore().EnableTokenEndpointPassthrough();
            });
            options.AddValidation();
        });
        builder.Services.AddAuthentication(options => {
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        });
        builder.Services.AddAuthenticationCore(options => {
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        });

        builder.Services.AddMvc();
```
