### ISSUE TITLE
Add a section that shows how to customize the model bound using [FromBody] and System.Text.Json

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore.Docs#15705]
This is common enough that it should have an explanatory section.

Use this code-snippet as a starting point
```csharp
    [ApiController]
    [Route("[controller]")]
    public class CustomJsonController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post([FromBody] DataModel model) => Ok(model);

    }

    public sealed class DataModel
    {
        [Required]
        public ObjectId ObjectId { get; set; }
    }

    [JsonConverter(typeof(ObjectIdConverter))]
    public struct ObjectId
    {
        public ObjectId(int id) => Id = id;

        public int Id { get; }
    }

    internal class ObjectIdConverter : JsonConverter<ObjectId>
    {
        public override ObjectId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => new ObjectId(JsonSerializer.Deserialize<int>(ref reader, options));

        public override void Write(Utf8JsonWriter writer, ObjectId value, JsonSerializerOptions options) => writer.WriteNumberValue(value.Id);
    }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#frombody-attribute)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
@javiercn Can you also please elaborate on [section manual-model-binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#manual-model-binding) please.

**Comment by Rick-Anderson** [comment]
@serpent5  this looks a like an interesting issue, let me know if you're interested at some point.

**Comment by javiercn** [comment]
@Legends I'm not sure what you are talking about or how that relates to anything in this issue. Could you file a separate issue with a detailed ask for what your suggestion is so that the team can evaluate it separately?

As I said, I'm a bit confused because I really don't know what you are asking/want.

**Comment by Legends** [comment]
@javiercn What I meant to say is, the section mentioned above makes not much sense to me, if you could further clarify it, enrich the section with more information about it.

It's completely unrelated to this section.

**Comment by javiercn** [comment]
@Legends Thanks for the clarification.

In that case file a separate issue so that it can be triaged independently, this helps distribute the load between the team and makes sure the right person gets to look at it. I'm knowledgeable in the area but I'm not the subject matter expert on the team.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.0#tryupdatemodelasync

**Comment by Legends** [comment]
This makes it clear, thanks!

**Comment by Rick-Anderson** [comment]
@serpent5  this is yours if you want it.

**Comment by serpent5** [comment]
@Rick-Anderson The new content is specific to 3.0, but this topic hasn't been updated yet. Do you want me to do a 3.0 update first?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson The new content is specific to 3.0, but this topic hasn't been updated yet. Do you want me to do a 3.0 update first?

Yes.
