### ISSUE TITLE
two backgroundService waiting another?

### ISSUE THREAD

**Issue by bobbydog** [aspnet/AspNetCore.Docs#15701]
I have two backgroundService like example QueuedHostedService,  the second service's BackgroundProcessing method would not execute until the first one's BackgroundProcessing's while content  run the first time , what's wrong?  I had to change the " await BackgroundProcessing(stoppingToken); " to "Task.Factory.StartNew(() =&gt; { BackgroundProcessing(stoppingToken); }, TaskCreationOptions.LongRunning);"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Your question/scenario might be a candidate for explanation in the topic.

@Tratcher ... and let me know if you think your answer to this one should be part of the topic, or should we call it an advanced scenario (beyond the scope of the topic)?

**Comment by Tratcher** [comment]
@bobbydog Take a look at https://github.com/aspnet/Extensions/issues/2149 and see if that answers your question.

**Comment by guardrex** [comment]
Given that the behavior is currently by-design and that engineering is considering changing the behavior in a future release, I'd like to surface the engineering issue in the topic's *Additional Resources* for the time being.

**Comment by bobbydog** [comment]
When I saw the source code https://github.com/aspnet/Extensions/blob/master/src/Hosting/Abstractions/src/BackgroundService.cs#L33 , I thought that the ExecuteAsync Method just ask me to return a task but do not to help me to start it, I should make the task start in the ExecuteAsync method, am I right?
