### ISSUE TITLE
Less common example

### ISSUE THREAD

**Issue by aedwill** [aspnet/AspNetCore.Docs#15712]
Would be nice to see a way to add controllers at runtime.  As an example if I have a modular UI and I'm allowing internal developers to upload new controllers at runtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e3baf6-6cba-aee0-9a8d-1e1fced2b690
* Version Independent ID: 74b76258-36a3-17de-6648-292da0a9e400
* Content: [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
