### ISSUE TITLE
"long-running"

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/AspNetCore.Docs#15710]
Instruction the users to call [long-running operations APIs asynchronously](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md#L39) usually leads the users to use `Task.Run`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We should discourage or at least warn against long running tasks.

**Comment by paulomorgado** [comment]
And explain that it returns the thread to the thread pool, schedules another one and, when finished, returns that thread to the thread pool and schedules another one.

**Comment by Rick-Anderson** [comment]
Fixed by  #15780
