### ISSUE TITLE
Not Deployable on IIS

### ISSUE THREAD

**Issue by kwakuduahc1** [aspnet/AspNetCore.Docs#15717]
I am worried there is no documentation that demonstrates how to deploy the app on IIS. After you create a new app, you cannot deploy to IIS for it to work straight away. It will be helpful if you could demonstrate how to run the IdentityServer without Azure but on IIS because there are intranets applications too

**Comment by guardrex** [comment]
Hello @kwakuduahc1 ... We have a lot of general coverage for IIS in the *Host and Deploy* node of the docs starting with ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/

... and we have one set up as a tutorial for step-by-step coverage (for an app) ...

https://docs.microsoft.com/aspnet/core/tutorials/publish-to-iis

... is that what you're looking for?

> run the IdentityServer without Azure but on IIS

That one is beyond the scope of our coverage. We would leave that to the IdentityServer folks ... https://identityserver.io/

**Comment by guardrex** [comment]
I'll close as answered, but you can add a further comment if that coverage isn't what you're looking for.

**Comment by kwakuduahc1** [comment]
@guardrex , thank you, I will look into those documents. Thanks once again.
