### ISSUE TITLE
Horizontal scrolling for code snippets with highlights

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#15715]
Whenever I see a code snippet in a docs page that has a highlight, it has a very wide horizontal scroll. Here's a full screenshot from Chrome:

![Screenshot](https://user-images.githubusercontent.com/6025110/68981229-a7ffd080-07fa-11ea-8c63-80fde3a58424.png)

It seems like this would be a known issue, but I can't find anything that already exists. I've seen it on a couple of different machines I've used and it's present in at least the latest Chrome and Firefox.

**Comment by guardrex** [comment]
*Yep* ... that's a new regression.

Do you want to open it over at https://github.com/MicrosoftDocs/feedback/issues, or do you want me to open it?

**Comment by serpent5** [comment]
@guardrex Can you do that? I'm sure that green dinosaur is gonna carry a lot more weight than a green shell :laughing:. You've got inside connections too, right?

I am very happy to do it though, if you prefer that.

**Comment by guardrex** [comment]
Yes, no, and not really. :smile:

I'll take care of it.

**Comment by guardrex** [comment]
Moved to MicrosoftDocs/feedback.

**Comment by serpent5** [comment]
@guardrex Thanks. :star2:
