### ISSUE TITLE
SignalR Docs Feedback - Help Mitigate Current Pitfalls

### ISSUE THREAD

**Issue by DogFive** [aspnet/AspNetCore.Docs#15726]
### **Useless Forethought:**

Let me start out by saying that SignalR is pretty awesome I probably abuse it a little more than I should. Recently I've jumped on the .Net Core bandwagon, I've felt the cross platform abilities alone justify the switch (even though the guys over at Mono make amazing stuff I didn't always use it).

### **Real Question/Problem:**

Anyways onto the juice, I get over to the docs and I want to know what my limitations are gonna be for the switch and I hit this brick wall.

> **_Automatic reconnects aren't supported in ASP.NET Core SignalR_**

I feel like this is expressed nonchalantly as if it's not a major problem with the framework. 

> If the client is disconnected, the user must explicitly start a new connection if they want to reconnect.

Here's what I think when I see this: In most applications today we face many different types of clients from many different types of connections (think cellular, wifi, ethernet, etc). Some of these clients can connection hop from one type of connection to another and do this often for bandwidth, powersaving, etc. This means clients could be technically disconnecting a lot.

I don't want to waste my time testing to see how much of an obstacle this is going to be, I feel as if this should be discussed a little bit more -or provide some sort of background on how to mitigate this issue.

Anyways just my 2𝇍

**Comment by BrennanConroy** [comment]
Could you point to the docs that say "Automatic reconnects aren't supported in ASP.NET Core SignalR"?

In 3.0 we added automatic reconnect so that text shouldn't exist anymore, and in the 2.1/2.2 docs we showed how to add your own reconnect logic.

**Comment by DogFive** [comment]
> in the 2.1/2.2 docs we showed how to add your own reconnect logic.

Okay awesome, this is why I thought the situation was weird and I saw the pull requests for functionality in 3.0 but it says this doc was just updated on 11/11/2019:

https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.0#automatic-reconnects

**Comment by BrennanConroy** [comment]
Ah, looks like we missed a spot! Thanks, we'll fix that up.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/AspNetCore.Docs/pull/15703
