### ISSUE TITLE
Does not convey routing or patterns well enough. 

### ISSUE THREAD

**Issue by bobbyrowe22** [aspnet/AspNetCore.Docs#15720]
I don't feel i could even formulate a question to help me understand other than "where is the specification for patterns?" 
I'm horribly confused about how to take a request and point the values at a some controller&gt; action&gt; args. 

Some conceptual understanding of routing is needed here. This has a rough example but does not cover the fundamentals well enough to allow anything but troubleshooting after a few reads. Specifically, I'm working with AspNetCore 3 MVC web apps.  UseEndpoints is used by default with MapControllerRoute and with no previous routing knowledge this article and many others left me puzzled. In code, there are no comments either just a parameter of "pattern" which is of type string. 

Reading this the first time I thought the pattern was what the user typed(the HTTP request) and the defaults: new{} was where you put the mapping to the controller and action with parameters. After a bit of brute force and debugging i've got something working but am more confused than ever. 

What's missing: pattern syntax, pattern parameters, and expectations. A better explanation of what's happening on the back end or how the pattern is breaking down the string or "mapping a request to the route" and in what priority.  The article has mention of some of these things but does not follow through on each subject. I believe the article should be rewritten to be shorter with less abstract examples. I'm mostly confused about the pattern string syntax, which seems like the most important thing.  Below is my current understanding 2 weeks after reading the internet and this article a few times.

-pattern parameters are separated by /
-pattern parameters are either a custom verbatim string, custom parameter with an optional default value, keyword with an optional default value, or route data with constraints.
-defaults: new {} can redirect requests from a pattern

-I don't understand how the pattern connects with the request. is it by the number of parameters?
-although I've only added "id?" at the end of a pattern of 4 segments, I can magically still except other route parameters in my action methods. how is that possible when I've only defined patterns with x amount of parameters?

It seems like every time I add a new map it breaks another.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc
This document covers low-level ASP.NET Core routing. For information on ASP.NET Core MVC routing, see Routing to controller actions in ASP.NET Core. For information on routing conventions in Razor Pages, see Razor Pages route and app conventions in ASP.NET Core.

**Comment by bobbyrowe22** [comment]
I didn't see anything on there that looked similar to the default generated code. I'll check the comments.
