### ISSUE TITLE
Not in index

### ISSUE THREAD

**Issue by richardcox13** [aspnet/AspNetCore.Docs#15724]
This page appears to not have an entry in the index (along with a few of the other inbuilt tag helper's pages).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90104e1-65b1-0007-e56d-0dffef4b1a44
* Version Independent ID: 5c95e5dc-dc10-8658-91fd-1d55d3959c37
* Content: [Script Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-US/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @richardcox13 ... I'll take care of that right now.
