### ISSUE TITLE
How HttpContext Has Use.Identity

### ISSUE THREAD

**Issue by mrumaiz** [aspnet/AspNetCore.Docs#15733]
Hi, 

I am using IdentityServer4 and I have normal user logins as well as client and secret for server to server communication. When I use client_credentials from another server and call the API HttpContext.User.Identity.Name is null. I just want to know is where is the place setting Identity.Name? and Why Name is not set when it access only from client_credentials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You might ask at http://docs.identityserver.io/en/latest/

**Comment by weitzhandler** [comment]
Make sure you're operating under the same authentication policy between IdentityServer and what's the policy in the `[Authorize(policyName)]` attribute.
