### ISSUE TITLE
Getting the logged in user name

### ISSUE THREAD

**Issue by owlyowl** [aspnet/AspNetCore.Docs#15746]
Try as I might on the server side I can't seem to get the current application user name of the logged in user.
The best I've been able to do is UserId.
Just wondering if anyone else has had this issue and how they've managed to pull it out without another db hit?

Below is the method I'm using to try:
 string IGetCurrentApplicationUserName.GetCurrentApplicationUserName()
        {
            var email = contextAccessor.HttpContext?.User?.Claims?.FirstOrDefault(c =&gt; c.Type == "sub")?.Value;
            var userId = contextAccessor.HttpContext?.User?.FindFirst(ClaimTypes.NameIdentifier).Value;
            return contextAccessor.HttpContext?.User?.Identity?.Name;
        }

The only line that populates anything is the userId var - I've debugged and explored the objects as well and can't find it either.

My startup.cs identity config is like so:
```
services.AddDefaultIdentity<ApplicationUser>()
.AddEntityFrameworkStores<ApplicationDbContext>();
services.AddIdentityServer()
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
services.AddAuthentication()
.AddIdentityServerJwt();
```
Cheers :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Check out *Pages\Shared\_LoginPartial.cshtml*

`User.Identity.Name`

**Comment by owlyowl** [comment]
> 
> 
> Check out _Pages\Shared_LoginPartial.cshtml_
> 
> `User.Identity.Name`

Hi Rick,
I'm trying to get it as part of an injected service using an IHttpContextAccessor:

```namespace PregnancyStudy.Web.Services
{
    public class GetCurrentApplicationUserName : IGetCurrentApplicationUserName
    {
        readonly IHttpContextAccessor contextAccessor;

        public GetCurrentApplicationUserName(IHttpContextAccessor contextAccessor)
        {
            this.contextAccessor = contextAccessor;
        }

        string IGetCurrentApplicationUserName.GetCurrentApplicationUserName()
        {
            var email = contextAccessor.HttpContext?.User?.Claims?.FirstOrDefault(c => c.Type == "sub")?.Value;
            var userId = contextAccessor.HttpContext?.User?.FindFirst(ClaimTypes.NameIdentifier).Value;
            return contextAccessor.HttpContext?.User?.Identity?.Name;
        }
    }
}```

You'll notice my last line ```contextAccessor.HttpContext?.User?.Identity?.Name``` - Name is null

![image](https://user-images.githubusercontent.com/1916426/69128691-fb2a9980-0b00-11ea-8a8f-c9cda59ff3d6.png)

**Comment by owlyowl** [comment]
@Rick-Anderson sorry that doesn't seem to work
