### ISSUE TITLE
Reverseproxy example is slightly wrong.

### ISSUE THREAD

**Issue by AnorZaken** [aspnet/AspNetCore.Docs#15755]
It says:
"If using directories with IIS or a reverse proxy, set the Swagger endpoint to a relative path using the ./ prefix. For example, ./swagger/v1/swagger.json."
This is wrong since "/swagger" is the current directory, so it should be "./v1/swagger.json", otherwise you are trying to access "swagger/swagger/v1/swagger.json".
The dot and backslash is unnecessary too, you can just write "v1/swagger.json" - not having a starting backslash is all you need to do to make it relative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@ssemyan  please review.

**Comment by ssemyan** [comment]
Are you sure you have the right Scott?

**Comment by Rick-Anderson** [comment]
Moved to #16195
