### ISSUE TITLE
"Render stateful interactive components from Razor pages and views" guidance is severely lacking details

### ISSUE THREAD

**Issue by smadgerano** [aspnet/AspNetCore.Docs#15759]
The section in your docs suggest that all you need to do is use "await Html.RenderComponentAsync...." tags.

In reality you also need to add extra using statements into your _Imports.razor file (that  are only apparent after going through the downloadable samples), an extra tag into the Head of the page, extra extra endpoints and services in to your Startup.cs (which to be fair I did pick up from other parts of the doc).

I've been using components in this way for the last 6 months in various preview versions, and having to put "extra" using statements in the _Imports.razor file was the last thing I thought of - taken me 2 hours to work this out, could have taken 5 minutes if there was a proper document for this hybrid style of usage rather than a single paragraph that was mixed up in the middle of the other two hosting scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Correct, we haven't had **_how to convert_** or **_hybrid_** coverage to date.

This seems like an extension of your earlier remarks on https://github.com/aspnet/AspNetCore.Docs/issues/13546. I've moved your remarks here over to that issue, which is awaiting triage by engineering. They'll get to it soon enough. Stand-by for their response.

**Comment by smadgerano** [comment]
Thanks for the feedback, understood. Apologies for my rant, I was just frustrated the time it took to get to the bottom of it, which I thought would have been covered in the docs for the final release, but we're all busy people so it's cool :)

**Comment by guardrex** [comment]
One of the background problems is the degree of churn. Engineering is still cranking away on framework scenarios. I agree we need the coverage, but it might be that 3.1's release is a good time to address this problem. The 3.1 release is **coming soon**. Preview 3 just landed. It won't be long now. Your issue is on the list, and they will see it and triage it shortly. To get a sense of everything we're doing, take a look at the Blazor.Docs project ... you'll see what I mean. 🏃🏃😅 

https://github.com/aspnet/AspNetCore.Docs/projects/35
