### ISSUE TITLE
Missing Checkbox section

### ISSUE THREAD

**Issue by tony-long** [aspnet/AspNetCore.Docs#15761]
Missing Checkbox section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@tony-long Can you please add more details on what you expect to see?

**Comment by tony-long** [comment]
Here’s what I think:

  1.  Since there are other input types in the doc, why not include the Checkbox since that is very commonly used;
  2.  Point out how to use them, especially where the use case requires a nullable boolean (bool?)
  3.  When you have a nullable bool the scaffolding for a view results in a inbox – which makes no sense.  Searches found many others having the same need.
  4.  The workarounds are more like hacks so I ended up going back to regular not-nullable bool. But, this there is a simply way then that should be included too.
Make sense?
Thanks for you quick response.


________________________________

**Comment by Rick-Anderson** [comment]
There are several blogs on this. https://www.learnrazorpages.com/razor-pages/forms/checkboxes is good.

We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
