### ISSUE TITLE
SQL Server CU must be installed to fix broken path

### ISSUE THREAD

**Issue by surfmuggle** [aspnet/AspNetCore.Docs#15777]
While going through the tutorial i encountered

> CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file '

I noticed that the path was missing a backslash. The [bug report 384](https://github.com/aspnet/EntityFramework6/issues/384) did contain the same problem. The advice was to update to the latest [SQL Server® 2017 for Microsoft® Windows Latest Cumulative Update ](https://www.microsoft.com/en-us/download/details.aspx?id=56128). This fixed the problem.

Suggestion: add a note to the tutorial to install the latest updates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #15680 

![image](https://user-images.githubusercontent.com/3605364/69197291-0e277480-0ad5-11ea-9b35-a9064811d5bb.png)
