### ISSUE TITLE
No mention of view model validation

### ISSUE THREAD

**Issue by tony-long** [aspnet/AspNetCore.Docs#15778]
No mention of view model validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
View models are just models.

**Comment by tony-long** [comment]
Thanks for the quick response.   You should probably mention this because people on StackOverFlowingBadly are putting out bad info on view models and client side validation.   I  count on Microsoft to provide a complete and truthful documentation on this stuff.


________________________________

**Comment by Rick-Anderson** [comment]
This is not a validation doc, it's just part of an intro tutorial. You should be reading https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0

**Comment by tony-long** [comment]
Thanks Rick – one other thing that would be great to have docs on.

I have a few bootstrap modals that I use for pop-up record add/edit using JavaScript to call controller action for a partial view w/form and stuff that into the modal body, make visible.  How to enable form validation in this use case I’m clueless on.  Perhaps jquery validation and unobtrusive  support.   But, with Blazor here and hopefully will get very powerful for forms,  client side validation,  I would prefer to go in a new direction and avoid jquery.

Any pointers on that would be very welcome.


________________________________
