### ISSUE TITLE
Correction request

### ISSUE THREAD

**Issue by wildcatgerry** [aspnet/AspNetCore.Docs#15782]
500.35 seems to be a copy of 500.34.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @wildcatgerry ... I’m just off to 🛌, so I’ll take a look and get back to you in the morning.

**Comment by guardrex** [comment]
Good :eye: @wildcatgerry ... *yes* ... I think it should say "multiple in-process applications" for 500.35. I'll fix that up and then ping engineering on the PR to confirm the change. Thanks for calling this out.
