### ISSUE TITLE
Steps are not happening according to the guide after "Apply Migration"

### ISSUE THREAD

**Issue by quakeulf** [aspnet/AspNetCore.Docs#15785]
"Internal Server Error: A database operation failed while processing the request. SQL exception: Cannot open the database. Applying existing migrations for Application DB context may resolve this issue."

This does not appear, and when I try to login again using the e-mail address I get "Invalid login attempt".

![image](https://user-images.githubusercontent.com/3605364/69262236-352e8680-0b67-11ea-9639-18a34b08d029.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's how the app works. You need to run migrations. The DB doesn't deploy.
