### ISSUE TITLE
Config files used during Build, Deploy and Launch ...

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore.Docs#15781]
I have started my "deep dive" into ASP.Net Core by creating an EMPTY web app (website) project that serves only static files - no MVC, no Razor, nothing fancy.   I use COMMAND line tools (msbuild) to compile (build) the project, and to deploy it to a local test or production directory.  I then use the "dotnet" command to launch the website.  (Using command line tools makes documentation easier than trying to grab screen snapshots of GUI tools that seem to change each year).

My specific questions are posted on StackOverflow at:
https://stackoverflow.com/questions/58940101/asp-net-core-launch-website-via-visual-studio-vs-command-line

In my opinion, the best way to tackle the various configuration files is by showing a complete cycle for a specific platform and hosting environment, for example:

WINDOWS SPECIFIC:

BUILD, DEPLOY AND RUN A WEBSITE LOCALLY USING IIS EXPRESS.
- Show command(s) and config files needed to build the website
- Show command(s) and config files needed to deploy the website
- Show command(s) and config files need to launch the website

BUILD, DEPLOY AND RUN A WEBSITE USING AZURE APP SERVICES
- Show command(s) and config files needed to build the website
- Show command(s) and config files needed to deploy the website
- Show command(s) and config files need to launch the website

BUILD, DEPLOY AND RUN A WEBSITE USING AZURE VIRTUAL MACHINE (IIS)
- Show command(s) and config files needed to build the website
- Show command(s) and config files needed to deploy the website
- Show command(s) and config files need to launch the website

LINUX SPECIFIC:
(as above)

As icing on the cake, please provide a link that describes the various options / nodes available in each of the config files -- currently, trying to find what options and values are even allowed in the various config files has consumed a large amount of time; and in most cases, I have been finding the answers via StackOverflow rather than in the official documentation -- which is very disappointing.

Thank-you for your consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback and questions @bdcoder2. I’m just off to 🛌, so I’ll get back to you on this in the morning.

**Comment by guardrex** [comment]
We're collecting feedback on how configuration files are covered. There have been a few inquiries on the subject, but not many to my knowledge from watching the issues come in.

Today, there are **_many_** configuration "files" for aspects of configuration:

* App
* Host
* Server/service
* Tooling

Thus far, we've adopted the strategy of covering configuration files (in the broadest sense) *with the technology to which they apply*. This makes sense owing to the fact that ASP.NET Core/.NET Core is cross-platform and cross-tooling ... there are many platforms and many tools now, thus many *files*.

To get a full handle on configuration files, one should access the documentation areas where those files apply. For example, *web.config* is covered in the IIS/ANCM section. App configuration files are covered in this topic. *launchSettings.json* is covered where VS is addressed (i.e., many places throughout the docs).

We'll continue to collect feedback, and perhaps management will one day ask for some sort of explicit coverage of most configuration file types in one spot.

You asked two specific questions ...

> I cannot find the port numbers in any configuration file (.json or web.config) within the published directory - so where are these port numbers coming from?

Ports 5000 and 5001 are the defaults for the Generic Host URLs and covered in [.NET Generic Host: URLs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#urls).

> How can I configure / control which ports are used when the website is published to either a test or production environment (using command line tools)? - is this done via a .pubxml file? If so, what node(s) must be included within the .pubxml file? ... Or is this done via some other config file when the website is launched, i.e.: web.config?

This is where configuration depends on the scenario, and you didn't describe your environment/approach completely. You seem to be deploying to IIS for a local development experience. Ordinarily, I'd point you to [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.0), but you said "command-line tools." Therefore, take a look at the [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.0&tabs=netcore-cli) tutorial. You'll see there that the port is set in the binding in IIS as usual. There's nothing for you to set for the app in the base/default scenario.

When using the *in-process hosting model* (the default), the IIS binding is the app's port. When using the *out-of-process hosting model*, the ANCM (ASP.NET Core Module) forwards requests from IIS (again, with the port determined by the app's binding in IIS) to the app **_on a random port_**, which you obviously don't interact with. For more info on the hosting models, see [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0#hosting-models).

I'm going to close as answered, but we'll keep an :ear: open for more feedback on configuration.

**Comment by bdcoder2** [comment]
@guardrex - Thank-you.  I very much appreciate the time you have taken to explain things; and your patience with a newbie such as myself.

As an engineer, let me illustrate the difference between documentation of years gone by compared to today.  Lets pretend 30+ years ago (I know, hard to imagine), ASP.NET Core was released, and I just cracked open the manual entitled "ASP.NET Core 3.0 - Windows" (note the clarification; this particular manual would be **Windows specific**).   Others might crack open a manual entitled "ASP.NET Core 3.0 - Linux" or "ASP.NET Core 3.0 - iOS" -- the point being, right from the top, the docs should be platform specific.

Moving forward in the **Windows specific** manual, I find an an "Introduction".  I probably would have found another section entitled "Configuration Files", One of the files described would be "launchsettings.json".  The manual would describe the following:

1.  What launchsettings.json does.
2. The process(es) or tools that read launchsettings.json
3. The valid sections and values that launchsettings.json may contain.

Nice, simple, done.

Fast forward to the here and now, and I have to jump around docs.microsoft.com, stackoverflow.com and about a dozen other blogs and articles to piece together the above; in addition to reading about other platforms or settings that do not even apply to my environment.

For example, I have yet to find a complete schema for the launchsettings.json file - instead I keep finding code examples that make use of various "sections" of the launchsettings.json file.  A typical search scenario goes as follows:

`Google: Site:docs.microsoft.com launchsettings.json schema`
**Result:**
[https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019)

The article describes a “Docker” section; great, but I am not using Docker ...  lets try ...

`Google: Site:docs.microsoft.com launchsettings.json logging section`
**Result:**
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#configuration)

Logging section described! - great, now how about a section for controlling the port numbers?

... off I go to Google, StackOverflow, blog, etc.

Had a single article described the various sections that are available in launchsettings.json I would have been able to answer every question I have when it comes to configuration.

Please understand, I am not trying to belittle the good work you are doing -- I am just saying that better ways have existed when it comes to technical documentation and I hope Microsoft might consider adopting some of those tried and true methods.    In the end, I think it would save everyone a LOT of time.

Thanks again!
