### ISSUE TITLE
Select Tag Helper

### ISSUE THREAD

**Issue by tony-long** [aspnet/AspNetCore.Docs#15792]
Need more complete example of using the select within the full CRUD lifecycle - Adding new record with a field using a Select List.   Update example of setting the value of the previous selected value of the current(recent add) record.   The Client Side behaviour for changing the value and any associated onchange event handling in javascript or Blazor.    Does anything exist for this?  Any working examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by tony-long** [comment]
Thanks Rick,  Please share this with the upper management team and I will follow-up with them next week.   MSFT needs to invest into having better documentation.  They are not investing enough and it’s always been a case of minimal effort going back to the 1990’s.
Cheers!

________________________________
