### ISSUE TITLE
Install nuget

### ISSUE THREAD

**Issue by JohnTraDolta** [aspnet/AspNetCore.Docs#15808]
Maybe tell the user to install the nuget package 
Microsoft.AspNetCore.Authentication.Facebook

@Rick-Anderson  edit:
![image](https://user-images.githubusercontent.com/3605364/69359217-4b524a80-0c2c-11ea-9dd2-e7a3d8d9d6e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
All of the social auth topics don't call out their packages. @Rick-Anderson, I'll have some time after the next round of Blazor PRs. If ur busy, I can take this one ... assign me if u want.

**Comment by Rick-Anderson** [comment]
@guardrex  Thanks for the offer. @wadepickett will be updating all of these.

**Comment by wadepickett** [comment]
I updated Google, the OAuth overview and working on Facebook right now.  Facebook Developer registration changed, updating those steps and screenshots as well, plus updating the code examples to address default change to Bootstrap4 and we no longer use .AddIdentityUI() to set it otherwise.

**Comment by wadepickett** [comment]
Fixed with PR #15838
