### ISSUE TITLE
Improve CSAT

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15817]
Currently pretty good, but historically it's been low

![image](https://user-images.githubusercontent.com/3605364/69362774-4349d900-0c33-11ea-9fe8-8afccbcc1c95.png)

[Internal tracking bug](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1617784)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ardalis @guardrex  Part of the reason for bad ratings is there's no readme.txt with instructions for getting this working. It needs the following

* A solution file that integrates the two. SLN are OK to check in when needed, just use `force` to override *.gitignore*
* Instructions on how to run tests

Is this SLN correct:

![image](https://user-images.githubusercontent.com/3605364/69384899-c5e98d00-0c61-11ea-998f-40b765ce55d2.png)

How do you run the tests?

**Comment by Rick-Anderson** [comment]
**Test** > **Test Explorer** > **Run All Tests**

**Comment by guardrex** [comment]
They're run the usual way ... `dotnet test` ... but yeah ... if the topic doesn't say that, it could be a pain point for readers.

IIRC, most of my attention to this was just to keep the sample updated. I don't recall ever getting into the guts of the text.

**Comment by Rick-Anderson** [comment]
When I try to run the project download - web site, not test, I get the following
![image](https://user-images.githubusercontent.com/3605364/69392119-0a345780-0c79-11ea-9e81-f2a428bbe7db.png)

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot resolve scoped service 'TestingControllersSample.Core.Interfaces.IBrainstormSessionRepository' from root provider.
  Source=Microsoft.Extensions.DependencyInjection
  ```

**Comment by Rick-Anderson** [comment]
This fixed it

```
public void Configure(IApplicationBuilder app,
    IWebHostEnvironment env,
    IServiceProvider serviceProvidery)
{
    if (env.IsDevelopment())
    {
        //var repository = app.ApplicationServices.GetService<IBrainstormSessionRepository>();

        var repository = serviceProvidery.GetRequiredService<IBrainstormSessionRepository>();

        InitializeDatabaseAsync(repository).Wait();
    }
```

LOL, all the tests pass but the web site can't start.

**Comment by guardrex** [comment]
Ah, yes, I see how this slipped thru the cracks.

When I did the upgrade ... I ran the app to make sure that the 3.0 updates worked ... **_and the app ran fine_**.

# **_BUT_** ...

I test ran the app in the **Production environment**. 🤦‍♂😄 This line wasn't hit, so the app ran ok. I didn't give it any further thought. 🏃

Well, no biggie probably .... no community dev discovered/reported it.

**Comment by guardrex** [comment]
> all the tests pass but the web site can't start.

... and **in Production** the tests would be **_RIGHT!_** :smile:
