### ISSUE TITLE
"Remove obsolete package references" section is confusing 

### ISSUE THREAD

**Issue by laura-rodriguez** [aspnet/AspNetCore.Docs#15815]
In this section, it is explained that ASP.NET Core no longer produces a large number of NuGet packages features, and some of the package references should be removed from the project file. Then, there is a list of packages that are no longer produced, for example, `Microsoft.AspNetCore.Authentication.JwtBearer` or `Microsoft.AspNetCore.Authentication.OpenIdConnect` among others. This gives you the impression that package references should be removed from the project file for any of the listed packages. However, in this section:  https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies, it is described that some of these packages should be used by adding a package reference to the version 3.0.0, for example, `Microsoft.AspNetCore.Authentication.JwtBearer`, which is available on NuGet. 
Both sections are contradictory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#update-the-project-file)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@laura-rodriguez Thank you for pointing this out. I'll see what I can do to clarify in the doc.

Here's one way to visualize things. Compare the 2.2 and 3.0 shared frameworks on your development machine:

![image](https://user-images.githubusercontent.com/10702007/69378232-9a6f9e00-0c73-11ea-92da-cb0d34b1b633.png)

In this screenshot, you see that the `Microsoft.AspNetCore.Authentication.JwtBearer` assembly doesn't exist in the 3.0 shared framework. It does, however, exist in the 2.2 shared framework. This is a situation in which you'd need to install the assembly from the NuGet package (https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer).

**Comment by laura-rodriguez** [comment]
@scottaddie thanks for sharing that screenshot, which is super helpful :). This information should be definitely included in the docs. This is relevant information for those who have to support multiple .NET versions. Thanks!
