### ISSUE TITLE
Mention IAsyncDisposable

### ISSUE THREAD

**Issue by mv10-work** [aspnet/AspNetCore.Docs#15828]
Components can implement IAsyncDisposable instead of IDisposable. Probably worth a mention in the Component disposal section. (I just replaced somebody's Task.WhenAll in a Dispose because they weren't aware DisposeAsync exists...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mv10-work ... Engineering didn't specify `IAsyncDisposable` for coverage when the content was written or reviewed at 3.0 GA, but it may have just been an oversight. They'll triage this, and we'll see what they say.

**Comment by mkArtakMSFT** [comment]
Components don't support `IAsyncDisposable` at the moment. So nothing will happen, if you implement it. We will be fixing this for the .NET 5 release.
