### ISSUE TITLE
Add-Migration does not work

### ISSUE THREAD

**Issue by henryjones000** [aspnet/AspNetCore.Docs#15825]
An unhandled exception occurred while processing the request.
SqlException: Invalid column name 'Rating'.
Microsoft.Data.SqlClient.SqlCommand+&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__164_0(Task&lt;SqlDataReader&gt; result)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by henryjones000** [comment]
I think Update-Database is the problem. It says this: 
Applying migration '20191119023842_InitialCreate'.
Applying migration '20191119023842_InitialCreate'.

t does not Create the Table with Ratings in it.

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by henryjones000** [comment]
When I ran Update-Database, it executed the InitialCreate.cs I made in the "Add a model" section. It DID NOT run the Rating.cs I just made. Will it work if I delete InitialCreate.cs?

**Comment by Rick-Anderson** [comment]
probably

**Comment by henryjones000** [comment]
lol.
When I right-click 20191119023842_InitialCreate.cs, the option "Exclude from Project" is available.
What will happen if I click that? Will InitialCreate.cs be prevented from running?

**Comment by firatkazak** [comment]
I solve this problem today when i work this tutorial.

<div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>

Add this div in Edit.cshtml
You add just Create.cshtml, not in Edit.cshtml probably.
