### ISSUE TITLE
Preserve current culture in all doc links

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore.Docs#15834]
The problem is described well in this issue https://github.com/MicrosoftDocs/feedback/issues/1498. The whole Microsoft Doc system is broken and as you can see in the comments it annoys all people around the globe. Unfortunately this issue is ignored by Microsoft. Personally I'm interested in ASP.NET Core and especially in Blazor so I'm writing here in hope that all these great people who work on ASP.NET can help. Doc is displayed in the browser and everybody in this team knows what redirection or cookie is.

Imagine that your browser is setup for different language than English, for example Spanish, French, Polish, Italian, etc. Open this page https://docs.microsoft.com/en-us/aspnet/ and try to click on any link. Notice that you are on a page which has `en-us` culture in the address. Unfortunately all links on this page are cultureless (is it a correct word?). After clicking on any link you are redirected to culture specific page which is _usually_ translated by Bing. This culture is taken from Accept-Language header. My English is far from perfect and maybe you will find some errors in this text, but I hope you can understand everything. Garbage created by Bing Translator is not acceptable. **If I want to read something I have to manually edit page address in address bar after every navigation to a page which has a link without culture.** There are a lot of links without culture, for example **all** links to reference documentation. Open this page https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.0#new-json-serialization and click on `System.Text.Json` link in the first sentence. 

Now imagine that you have to manually edit page address after each navigation. Annoying?

There are two solution.
1. Add culture to every link to Microsoft Doc.
2. Remember culture in cookie and then use culture from cookie and not from Accept-Language header to make the redirection.

I think that especially the second solution is trivial to implement.

**Comment by guardrex** [comment]
Hello @Andrzej-W ... This isn't something that we can address at our level. It has to be handled in a general way for all MS docs, and the MicrosoftDocs repo (such as in the feedback issue that you cross-linked) is the right spot to address it to management and doc system engineers.

**Comment by Andrzej-W** [comment]
hope dies last :(

**Comment by guardrex** [comment]
I wish we could help, but that has to be taken on by that team ... the managers and engineers that control the whole show.

The good news there is that they assigned a PM to look into it ... they didn't just close it. That's a good sign that they'll work on it.
