### ISSUE TITLE
Example for CreateAuthenticatedChannel contains wrong information

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15831]
@christopheblin commented on [Fri Nov 22 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/237)

In the doc, there is:
// SslCredentials is used here because this channel is using TLS.
// Channels that aren't using TLS should use ChannelCredentials.Insecure instead.

As I investigated in https://stackoverflow.com/a/58990584/1545567, ChannelCredentials.Insecure is not allowed to be combiend with CallCredentials

So the comment should be

//SslCredentials is required here, GRPC standard does not allow to send CallCredentials over insecured channel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 363b40bb-4e20-e4b3-4456-5eb8fe6b30fb
* Version Independent ID: 8a7e85b0-5c1c-969d-9748-5e5e2dc45cce
* Content: [Authentication and authorization in gRPC for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/grpc/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

@christopheblin commented on [Fri Nov 22 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/237#issuecomment-557449017)

Note that this is not fr-fr specifically

---

@srvbpigh commented on [Fri Nov 22 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/237#issuecomment-557456560)

Hello, @christopheblin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@JamesNK  if this is correct, I can fix it.

```
// SslCredentials is used here because this channel is using TLS.
    // Channels that aren't using TLS should use ChannelCredentials.Insecure instead.
    var channel = GrpcChannel.ForAddress(address, new GrpcChannelOptions
    {
        Credentials = ChannelCredentials.Create(new SslCredentials(), credentials)
    });
    return channel;
```

**Comment by christopheblin** [comment]
Any progress on this ? 

One of my colleague encountered the exact same problem yesterday due to the exact same situation and he lost some time to investigate because the error message "Supplied channel credentials do not allow composition" is pretty obscure (filled a bug directly in gRPC .NET for that : https://github.com/grpc/grpc-dotnet/issues/679)

**Comment by JamesNK** [comment]
PR to improve the doc sample - https://github.com/aspnet/AspNetCore.Docs/pull/16029
