### ISSUE TITLE
Error in "Register the database context" step

### ISSUE THREAD

**Issue by JohnStraumann66** [aspnet/AspNetCore.Docs#15844]
This line: services.AddDbContext&lt;TodoContext&gt;(opt =&gt; opt.UseInMemoryDatabase("TodoList")); is giving me an error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase' and no accessible extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)	TodoApi	C:\Users\JohnStraumann\Documents\Visual Studio 2019\Projects\TodoApi\Startup.cs	30	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio&source=docs#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
