### ISSUE TITLE
HttpClient Factory docs should talk about CookieContainer

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#15848]
See: https://github.com/aspnet/Extensions/issues/872

The HttpClient Factory docs don't mention how an instance of `CookieContainer` will be shared across `HttpClient` instances. We should recommend some options about how to use cookies with the client factory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@rynowak can you provide a draft?

**Comment by rynowak** [comment]
I sent a PR 😁

**Comment by ATLSAPI** [comment]
@rynowak @Rick-Anderson Thanks for adding this to the docs. We think we are experiencing this issue. In your update to the docs, as an example of how to disable automatic cookie handling, you specified the below:

```csharp
 services.AddHttpClient("configured-disable-automatic-cookies")
	.ConfigurePrimaryHttpMessageHandler(() =>
	{
		return new SocketsHttpClientHandler()
		{
			UseCookies = false,
		};
         });
```

Did you mean `return new SocketsHttpHandler()`? As SocketsHttpClientHandler does not exist on `System.Net.Http`. 

Also, it seems that `SocketsHttpHandler` is only available in NET Core 2.1 so netstandard libraries cant use it? Should this be reflected in the docs? 

I'm happy to raise a new issue/pr with your guidance if that's preferable.

**Comment by rynowak** [comment]
yes that's right! this was mistake. It would be helpful if you could send a PR

**Comment by ATLSAPI** [comment]
Cool, I'll do that @rynowak. Besides correcting `SocketsHttpClientHandler`, do we want to include any information about the compatibility of `System.Net.Http.SocketsHttpHandler` with certain NET Core versions (>=2.1) as it's currently displayed on all versions of the docs?

**Comment by angelaki** [comment]
Reusing this closed issue hoping that it still gets updated. Just noticed this behavior of `HttpClient`, `HttpClientFactory` etc. asking myself: who the hell wants this behavior? Isn't 99% of all use-cases: one `CookieContainer` per HttpClient? Using the FactoryPattern, what is quite neat, I can decide between: _don't use Cookies at all_ or _share them between all my instances, not being able to reset them at except the get reset automatically at some point I even can't controll_? Am I mistaken? Or is this just a horrible concept?

**Comment by LuohuaRain** [comment]
> Reusing this closed issue hoping that it still gets updated. Just noticed this behavior of `HttpClient`, `HttpClientFactory` etc. asking myself: who the hell wants this behavior? Isn't 99% of all use-cases: one `CookieContainer` per HttpClient? Using the FactoryPattern, what is quite neat, I can decide between: _don't use Cookies at all_ or _share them between all my instances, not being able to reset them at all except they get reset automatically at some point I even can't controll_? Am I mistaken? Or is this just a horrible concept?

yeeeeeeeeees! Really horrible concept😢

**Comment by LuohuaRain** [comment]
> Reusing this closed issue hoping that it still gets updated. Just noticed this behavior of `HttpClient`, `HttpClientFactory` etc. asking myself: who the hell wants this behavior? Isn't 99% of all use-cases: one `CookieContainer` per HttpClient? Using the FactoryPattern, what is quite neat, I can decide between: _don't use Cookies at all_ or _share them between all my instances, not being able to reset them at all except they get reset automatically at some point I even can't controll_? Am I mistaken? Or is this just a horrible concept?

![image](https://user-images.githubusercontent.com/37979368/134303650-d55f7d12-f9f7-413e-a965-31c6bdf7ed4c.png)

**Comment by LuohuaRain** [comment]
@angelaki I'm going to try Flurl

**Comment by angelaki** [comment]
Thank you for your suggestions!
