### ISSUE TITLE
Alignment on underscores in Blazor examples

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#15853]
It looks like we won't have complete alignment between engineering and docs on explicit use of the `private` access modifier. Templates do it now, but engineering samples often (perhaps usually) don't. It's consistently in use now in the docs.

Next question is on underscores for private fields:

https://github.com/aspnet/AspNetCore/wiki/Engineering-guidelines#coding-style-guidelines--general

* Engineering:
  * No underscore for private fields in the `@code` block root. Slight inconsistencies tho: Templates have `_stopPropagation` but `currentCount`, `forecasts`, and `collapseNavMenu`.
  * The underscore is used for a private field **inside of a class** in the `@code` block in engineering samples.
* Docs: Commonly using underscores for private fields. There are many that still need a touch of work if we're going to use them everywhere in docs.

How would you like the underscore used with private fields across the doc examples?

* Always
* Inside classes only, not for fields at the root of `@code` blocks
* Nowhere

btw - I plan to put an engineering PR in to standardize the approach in templates, if needed ... plz 🛑 me if you prefer that I not do that.

**Comment by guardrex** [comment]
@danroth27 Need your ruling on this one in order to work it. :point_up:

**Comment by guardrex** [comment]
@danroth27 

**_Just ONE more!_** (*yeah, right!* :smile:)

Just need a decision on this one to work it. *Underscores on fields!* ... we're a bit 😵 at the moment. :point_up:

**Comment by danroth27** [comment]
Private fields in Razor components are still just private fields in a class, so they should follow the standard coding guidelines of both using the explicit access modifier and the leading underscore on the field name.

And if I fail to follow the guidelines it's just my own personal rebellion and not an endorsement of a different coding style :smiley:.

**Comment by guardrex** [comment]
Cool ... I'll take care of this quickly because the inconsistency bothers me.

⚔️ **_Hear 'ye! Hear 'ye! Join Dan's Rebellion!_** ⚔️
