### ISSUE TITLE
EventSource vs EventLog

### ISSUE THREAD

**Issue by philip-reed** [aspnet/AspNetCore.Docs#15852]
This page states that calling CreateDefaultBuilder will add EventSource & EventLog, but the documentation for CreateDefaultBuilder states that only EventSource is added.

I cant get my app writing to the event log unless I explicitly call .AddEventLog() :

    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();            
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
               webBuilder.UseStartup<Startup>();
            }).ConfigureLogging(logging => logging.AddEventLog());

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#add-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @philip-reed ... On Windows for the Generic Host, it's added ...

https://github.com/aspnet/Extensions/blob/ef5d488c054c3aa850c29c10d851fcdc8a004eed/src/Hosting/Hosting/src/Host.cs#L113

However, with the Web Host, it's not added ...

https://github.com/aspnet/AspNetCore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L155-L206

When you set the topic version selector back to 2.2, the topic drops the mention of the Event Log ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#add-providers

I take it that you're using the Web Host? If so, you're good ... add it. If you're using the Generic Host and having to **_re-add it_**, that would be a 🐞 if true.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
