### ISSUE TITLE
One page query

### ISSUE THREAD

**Issue by aureole82** [aspnet/AspNetCore.Docs#15851]
Paging at SQL databases is almost like this:
```cs
var count = await source.CountAsync();
var items = await source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
```
Both statements result in database queries. Depending on the query (including `JOIN`s, `WHERE`s, ...) both database queries may last very long.
*What if EntityFramework Core introduces a `PaginatedList<T>` construct which will be populated by a single database query?*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by aureole82** [comment]
On SQL Server I reduced the execution time from 3+8 seconds (`COUNT` and `SELECT ...` statements) to 7 seconds using [common table expression](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql):
```sql
;WITH Query AS (
SELECT *
FROM (
	SELECT 
	    p.Id,
		p.IsActive,
		v.Title, 
		v.Body,
		...
	FROM Versions v
	INNER JOIN Posts AS p ON p.Id = v.PostId
	WHERE v.LastUpdated = (
		SELECT TOP(1) LastUpdated
		FROM Versions
		WHERE PostId = v.PostId
		ORDER BY LastUpdated DESC
	)
) x
WHERE
  IsActive = 1
  AND (Title LIKE '%filter%' 
    OR Body LIKE '%filter%' 
	OR ...
  )
)

SELECT *
FROM Query
CROSS JOIN (SELECT COUNT(*) AS Total FROM Query) x
ORDER BY [Id]
OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY
```

**Comment by Rick-Anderson** [comment]
@tdykstra would should consider cutting sorting, filtering, and paging - 

That's pure EF and not a core area for ASP.NET Core to document.

@aureole82  we're a doc team for ASP.NET Core. You'd probably have better luck at StackOverflow.
