### ISSUE TITLE
no support for jsonconstructor

### ISSUE THREAD

**Issue by jwisener** [aspnet/AspNetCore.Docs#15869]
currently the swagger cannot be generated for immutable objects that are utilizing [jsonconstructor] attribute

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@jwisener Is this just a comment for discussion or is there something wrong with the doc?

**Comment by jwisener** [comment]
Hi @Rick-Anderson 

Thanks for responding, greatly appreciated.

I feel the doc should clarify and state there is no current support for people trying to use this for swagger generation using [jsonconstructor].   Even though json.net has this feature and it works properly in deseralization for a given api/.net core project. The Swagger generation of the models for operations involving a request parameter/parameters will be generated incorrectly, as it just reading public properties of a given class (note: json ignore attributes do work). This is assuming an anaemic type design where all properties are public for both gets and sets. Had I known, when I read thru this documentation, there was no support for this, I would have not wasted time trying to use it, to only arrive at conclusion it just will not work without a huge amount rework to override the generation of the swagger( e.g. idocument processor for all parameters) of the schema. 

I am just asking to clarify this fact in the documentation.

**Comment by Rick-Anderson** [comment]
@scottaddie do you want to update this?

**Comment by jwisener** [comment]
@Rick-Anderson I'll take that as a no.

**Comment by jwisener** [comment]
Closing this due to no response
