### ISSUE TITLE
Static resource handling

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15877]
Hi team, 
I moved this from here: https://github.com/aspnet/AspNetCore.Docs.pl-pl/issues/19

@it-xtech-dev commented 3 hours ago
For core 3.0 there are some mentions about serving static assets - here i cannot find any. Can you provide some examples how to solve this issue?

I have used this approach: https://stackoverflow.com/questions/51610513/can-razor-class-library-pack-static-files-js-css-etc-too

This works fine when RCL is referenced as project but fails for nuget packaged library (resources not found except those provided by host app).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  quick question.

**Comment by pranavkm** [comment]
I'd expect this to work - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets for packages produced from Razor Class Libraries. If you don't see this happening, please file an issue in https://github.com/dotnet/aspnetcore/issues with a minimal project that reproduces the problem.
