### ISSUE TITLE
Emphasis on SharedResource class definition

### ISSUE THREAD

**Issue by Errors4l** [aspnet/AspNetCore.Docs#15871]
This might just be a me problem, but I had a hard time getting data annotations to work using the DataAnnotationLocalizerProvider option. The factory requires a type definition and I was trying to use the backing resources class (`Data.resx` & `Data.Designer.cs`) for this. None of my data attributes were getting localized: the resulting value was simply the value of the Name attribute.

I later had a thorough look at the documentation and it states the example app uses an **empty** `SharedResources` class.
It made more sense to me to use the generated backing class for the resources file, because that actually has a reference to the resources. Right now it seems that the sole purpose of the empty class is to map the resources file by name (the same job a string would do).
_Edit2: it seems to use both the name and the assembly, not just the name._

After getting the mapping to work with the empty class I found this related issue: https://github.com/aspnet/AspNetCore.Docs/issues/6830
So the issue seems to lie in the location of the class. It shouldn't be in `/Resources`, yet that's the place generated resources classes will be in.

I feel like it'd be good to mention something in the official documentation.

_Edit: typo_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#dataannotations-localization)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco  should we add a comment? It's clearly an empty class

```
// Dummy class to group shared resources

namespace Localization
{
    public class SharedResource
    {
    }
}
```

**Comment by hishamco** [comment]
Good idea, also we should mention that in the docs if it's not there yet, that the purpose to group the shared resources. IMHO a note block is preferred here

**Comment by Rick-Anderson** [comment]
@hishamco  would you like to PR this?

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
@Rick-Anderson I think it's already mentioned in the docs

**Comment by Errors4l** [comment]
Thank you for your quick replies. @Rick-Anderson, I do feel like this issue was closed too soon, as I think there still seems to be something lacking in the documentation.

@hishamc I think the section you're referring to is [Resource file name](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#resource-file-naming). It describes that a resource file name and location should match the class namespace and name in order to be detected.
Once you put the resources **class** in the `Resources folder` (just like the example app), you easily run into a naming conflict due to the fact that ASP.NET Core uses `/Resources` as the root for locating resource files.

---

Let's take a look at the following location and namespaces for a resource file located at `/Resources/SharedResource.resx` with different namespaces:

| Class | Namespace | Lookup path |
|---|---|---|
| `/Resources/SharedResource.cs` | `LocalizationWebsite.Web.Resources` | `/Resources/Resources/SharedResource.resx` |
| `/Resources/SharedResource.cs` | `LocalizationWebsite.Web` | `/Resources/SharedResource.resx` |

Here, only the latter option works because the namespace of the dummy class has been changed to fix the otherwise incorrect the lookup path.

---

Furthermore, the example app has two different methods of instantiating the localizer in the `TestController`. These behave slightly differently and the more common use case seems more restrictive:

![image](https://user-images.githubusercontent.com/2056697/69712160-a5f31700-1102-11ea-818a-b8c88dbcef1d.png)

The first option uses the `Type.FullName` whereas the second option only uses the `Type.Name`. This difference leads to the second option working even with the correct namespace for the `SharedResource` file, while the first option does not.

After changing the namespace of `Localization/Resources/SharedResource.cs` to `Localization.Resources`:

```cs
// Does not work.
_localizer = factory.Create(typeof(SharedResource));
// Does work.
var assemblyName = new AssemblyName(type.GetTypeInfo().Assembly.FullName);
_localizer2 = factory.Create("SharedResource", assemblyName.Name);
```

---

Do you feel like it's not worth at least a mention? This seems like a very easy mistake to make, especially considering the example app has the files in the same location _but with a changed namespace_. ReSharper will even suggest to correct the namespace based on the location of the file:
![image](https://user-images.githubusercontent.com/2056697/69711173-e487d200-1100-11ea-8484-8b5c2765ccaa.png)

**Comment by hishamco** [comment]
> I think the section you're referring to is Resource file name. It describes that a resource file name and location should match the class namespace and name in order to be detected.

No, there's paragraph mentioned that the `SharedResource` is a dummy class ..

At the end if the namespace is wrong - which is possible - I will have a final look today

**Comment by Errors4l** [comment]
@hishamco Any news on that last part?

**Comment by hishamco** [comment]
Sorry I was sick last few days, if you talk about the name space issue you can make a PR for that

I already checked the docs and it covers the info about the `SharedResource`

**Comment by Errors4l** [comment]
No problem. I hope you're feeling better.

Correcting the namespace of the `SharedResource` class would break the reference to the resource file (which was the issue I initially faced), so I'm not going to PR that.

The information is there. It's just very easy to overlook the fact that the file `Localization/Resources/SharedResource.cs` has the full type name `Localization.SharedResource` rather than `Localization.Resources.SharedResource`. But I will considering it an oversight on my part and leave things be.

Thank you for your time.

**Comment by lvmajor** [comment]
Personally, I have the same feeling as @Errors4l , I already knew about this issue so it's not a problem for me, but I think the documentation is still not clear for newcomers regarding the `sharedResources` namespace.

I think it wouldn't hurt to simply add another comment in the example, something like:
```
// Dummy class to group shared resources
// To be noted that the `SharedResource` namespace should be the root namespace even if it is located in the /Resources folder,
// This goes against Visual Studio normal namespacing rules, but is mandatory for it to work.
namespace Localization
{
    public class SharedResource
    {
    }
}
```
