### ISSUE TITLE
Awaitable Extension of partial method of Html helper 

### ISSUE THREAD

**Issue by Tariq12010** [aspnet/AspNetCore.Docs#15870]
[Enter feedback here]
when we mouse hover over the method of HTML.RenderpartialAsync .  why  it say that  awaitable? as we can't use await with that method ,like we do for PartialAsync method. i think render partial dosn't return anything. its void.  but here what mean awaitable ? 
 
 @{
        @await Html.PartialAsync("_FirstPartialView")
    }
    @Html.RenderPartialAsync("_FirstPartialView");
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
The `RenderPartialAsync` method returns a `Task`, and you can use it as follows:

```cshtml
@{
    await Html.RenderPartialAsync("_PartialView.cshtml", item); 
}
```

Here are some related resources:

* API ref page: https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.rendering.htmlhelperpartialextensions.renderpartialasync
* Asynchronous HTML Helper docs: 
https://docs.microsoft.com/aspnet/core/mvc/views/partial?view=aspnetcore-3.0#asynchronous-html-helper
* Source code: https://github.com/aspnet/AspNetCore/blob/620a827d9b657f626ba9c5fc243e7eb67fc9afcc/src/Mvc/Mvc.ViewFeatures/src/Rendering/HtmlHelperPartialExtensions.cs#L284-L370
