### ISSUE TITLE
Please discuss authentication schemes and logging/debugging problems

### ISSUE THREAD

**Issue by lukepuplett** [aspnet/AspNetCore.Docs#15872]
Thanks for this article, its really welcome.

In total I've spent weeks "fighting" with the Identity framework and have found it much easier in past years to write the OAuth middleware myself, from scratch. Sadly on this project I've sunk cost into ASP.NET Core Identity.

 - I think setting DefaultChallengeScheme is confusing because most people will be supporting more than one social login IDP, which immediately begets the question of what to set this to when using Google and Facebook login?

 - I think this article should cover or link to information on what named schemes even are.

But today, my problem is that after adding a new Yahoo login (I have Google and MS), which I am convinced I've done correctly, I get a null from `SignInManager.GetExternalLoginInfoAsync`. My issue is that there is nothing in the logs to describe the OAuth dance that has taken place, confirming at least what parts of the conversation between middleware and Yahoo have worked and what part is failing and causing a null to be returned - I have moaned separately, months back, about the dubious design decision to return a null from an API and the lack of logging within that code.

 - Today I just want to know how to flip a switch to have the middleware write verbose logging so I stand half a chance of working out why Yahoo login is failing.

My worry is that the code authors have chosen not to log detail for fear of externalising sensitive information. Fair, but perhaps demonstrates that it is often best to teach people to fish and provide a line and a hook - write their own middleware that they can step through in a debugger - than it is to build a huge framework that becomes an obstacle.

All the best, thank you for listening!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9d7ad5-47d6-80bf-88fe-fac3a74151a3
* Version Independent ID: e64816f4-3391-5aab-31c2-ab4f915bc7f6
* Content: [Facebook, Google, and external provider authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/social/social-without-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/social-without-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  @guardrex  can you respond?

> I just want to know how to flip a switch to have the middleware write verbose logging so I stand half a chance of working out why Yahoo login is failing.

**Comment by guardrex** [comment]
Are you saying that ordinary logging wasn't helpful enough? I just ran the Social Auth Additional Claims sample with this in the *appsettings.Development.json* file ...

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Error",
      "System": "Error",
      "Microsoft": "Error",
      "Microsoft.AspNetCore.Authentication": "Trace"
    }
  }
}
```

`Error` for everything else to suppress most of the chatter from the app. I ran the app and went to do a Google sign in. I did get a lot of good info logged out (the ASP.NET Core side of the *OAuth dance*. 💃

For the things on the social auth provider side, I would expect their console to provide more info (e.g., why a sign on attempt was denied).

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by lukepuplett** [comment]
Thanks for the helpful logging config snippet. I'm not able to see anything useful.

```
"Microsoft.AspNetCore.Authentication": "Trace"
```

I don't really see a great deal more than usual, tbh.

My logs read like so from the moment of handling the redirect back from the Yahoo IDP to the moment my call to `GetExternalLoginInfoAsync()` returns `null`.

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:44340/oauth2/yahoo?code=redacted&state=giant-encrypted-value
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: Identity.External signed in.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 628.1336ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:44340/Account/ExternalLoginCallback?returnUrl=%2F&trackingCode=standard-login-signup-page
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[9]
      AuthenticationScheme: Identity.Application was not authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Co.Brand.Features.AccountManagement.AccountController.ExternalLoginCallback (Co.Brand.Web.Application)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Route matched with {action = "ExternalLoginCallback", controller = "Account"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] ExternalLoginCallback(System.String, System.String, System.String) on controller Co.Brand.Features.AccountManagement.AccountController (Co.Brand.Web.Application).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Co.Brand.Features.AccountManagement.AccountController.ExternalLoginCallback (Co.Brand.Web.Application) - Validation state: Valid
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: Identity.External was successfully authenticated.
```

It might be worth calling out this issue. I'm still on 2.2 so either my logging config still isn't right, or I'm hitting the issue with the lack of logging.

https://github.com/aspnet/AspNetCore/issues/11146

**Comment by lukepuplett** [comment]
To be honest, I wasn't looking to take advantage of you to get support. I was really feeding back about the docs failing me ...in my time of need ;)

I can just post on SO or perhaps even compile my own auth DLL and step through.
