### ISSUE TITLE
Poweshell Snipet to download and install dotnet-hosting

### ISSUE THREAD

**Issue by StefanSchoof** [aspnet/AspNetCore.Docs#15873]
In this documentation is only the way to download and install the dotnet-hosting with many manual step explained. Is there any Powershell snippet that download and installs a dotnet hosting on a windows server? Trying this is seems unnecessary hard. The real download URL is hidden on a webpage, the installer is not waiting until the installation is finished. I assumed there would be an easier way, but the documentation mention no. So is there really no easy way to automate the dotnet-hosting installation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StefanSchoof ... It was discussed on https://github.com/aspnet/AspNetCore.Docs/issues/14520, and the verdict from engineering is to use the Custom Script Extension with Azure VMs. Of course, that's an Azure thing, so it's not going to help everyone. That's as far as engineering would like to go at this time with the official docs, but I'm sure that they're keeping an :ear: open for more feedback. In the future, they might decide to work up a PS script or some other approach.

For the time being, you can write your own script and/or search out blogs, etc. for guidance/tips/scripts. You can try SO, and you can reach out to the devs on Slack or Gitter, where you'll probably get some great tips:

* [Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Gitter](https://gitter.im/aspnet/Home)

**Comment by StefanSchoof** [comment]
Thanks, for the quick reply and to clearly that there is no support for a official script.
I am on azure and like to use the Custom Script Extension, but simple say, write your own script it is not what I expect in the highly automation focus world. And I a little disappointed that the installer does not wait. This are unnecessary barriers. 
(I understand your point of view, but I needed to express my dissatisfaction)

**Comment by guardrex** [comment]
> the installer is not waiting until the installation is finished

@joeloff ... a report here that the hosting bundle installer script isn't behaving as @StefanSchoof expects. @StefanSchoof, you'll probably need to elaborate on what you mean by "is not waiting until the installation is finished." Explain in details what the behavior is.

**Comment by StefanSchoof** [comment]
I have this script:
```powershell
Invoke-WebRequest -Uri https://download.visualstudio.microsoft.com/download/pr/32b71802-0b4d-4064-a7e6-083b5155d3b1/080cf60a5c06be4ed27e2eac6c693f2f/dotnet-hosting-3.0.1-win.exe -OutFile dotnet-hosting-3.0.1-win.exe
./dotnet-hosting-3.0.1-win.exe /passive
#Start-Sleep -Seconds 300
net stop was /y
net start w3svc
```
And if I do not have the Start-Sleep in there the `net stop was /y` will executed right after the installation starts and not wait until the installer has finished.

**Comment by guardrex** [comment]
Oh ... I see what you mean. Nevermind @joeloff ... this is a custom solution issue.

@StefanSchoof, ask on SO or chat. I'm not familiar with running (and then waiting on) an installer like that (never had to do it before). I'm sure that on chat or SO that you'll find a PS guru (*or several*) who can help.

**Comment by StefanSchoof** [comment]
You are right this was simple. With fresh start I got:
```powershell
Invoke-WebRequest -Uri https://download.visualstudio.microsoft.com/download/pr/32b71802-0b4d-4064-a7e6-083b5155d3b1/080cf60a5c06be4ed27e2eac6c693f2f/dotnet-hosting-3.0.1-win.exe -OutFile dotnet-hosting-3.0.1-win.exe
Start-Process -FilePath ./dotnet-hosting-3.0.1-win.exe -Wait -ArgumentList /passive
net stop was /y
net start w3svc
```

Thanks for your help and sorry to bother you with this.

**Comment by guardrex** [comment]
No worries. You definitely aren't the first person to ask about this ... you're like the ~6 person to ask me over the past few years. If the engineers/managers get more feedback that something formal should be done (especially with the installer itself), I'm sure they'll take that up at some point.
