### ISSUE TITLE
Select All Checkboxes

### ISSUE THREAD

**Issue by rleath82** [aspnet/AspNetCore.Docs#15874]
Is there a way to use a "select all" checkbox for a list of checkboxes using C# instead of JavaScript?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
As you see today, only  a single checkbox has framework support with the `InputCheckbox` component.

Explore blog posts, SO, chat, etc. to see if you can find an example.

If you wish to provide product feedback directly to the engineers, you can open an issue on their repo :point_right: https://github.com/aspnet/AspNetCore/issues
