### ISSUE TITLE
Complete Code for ListView Templated Components

### ISSUE THREAD

**Issue by krchome** [aspnet/AspNetCore.Docs#15882]
Here is my completed working solution to above:
Following on Templated components, I created,
ListViewTemplate.razor:
@typeparam TItem

&lt;ul&gt;
    @foreach (var item in Items)
    {
        @ItemTemplate(item)
    }
&lt;/ul&gt;

@code {
    [Parameter]
    public RenderFragment&lt;TItem&gt; ItemTemplate { get; set; }

    [Parameter]
    public IReadOnlyList&lt;TItem&gt; Items { get; set; }
}

In the ListViewTemplateUser.razor Component (Using the template):
&lt;h3&gt;ListViewTemplateUser&lt;/h3&gt;
@page "/LVTU"

&lt;div&gt;

    &lt;ListViewTemplate Items="pets"  TItem="Pet"&gt;
        &lt;ItemTemplate Context="pet"&gt;
            &lt;li&gt;@pet.Name&lt;/li&gt;
        &lt;/ItemTemplate&gt;
    &lt;/ListViewTemplate&gt;
&lt;/div&gt;
@code {

    [Parameter]

    public IReadOnlyList&lt;Pet&gt; pets { get; set; } = new List&lt;Pet&gt;() { new Pet(1, "Burfy"),
                                                                    new Pet(2, "Sandy"),
                                                                    new Pet(3, "Lara"),
                                                                    new Pet(4, "Bhojua")
    
                                                                };

     }

Finally  the model class:
    namespace GetStartedBlazor
   {
    public class Pet
    {
        public int ID { get; set; }
        public string Name { get; set; }

        
        public Pet(int id, string name)
        {
            ID = id;
            Name = name; 
        }

    }
  }

I hope the code helps someone like me who is stuck trying to implement this. 

  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @krchome.
