### ISSUE TITLE
Add SLN file to download

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15886]
So VS opens them and allows testing from VS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-3.0)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It does it all by itself ... there's no need for this.
