### ISSUE TITLE
Speak about dotnet core update

### ISSUE THREAD

**Issue by vletoux** [aspnet/AspNetCore.Docs#15893]
When the dotnet core is updated with minor version and if the service has not been restarted and if a new dll of the framework is loaded, an exception can occur: System.IO.FileNotFoundException 
The cause is that the application (in memory) tries to load a dll of the previous dotnet core version. which does not exists anymore

A service (the one you configure it) restart fixes the problem.

Why am I reporting here ?
Because nothing is told at the configuration level here, that a minor update should trigger a restart of all the service configured here. Either manually (that I'm doing it) or either automatically (not good enough to know what needs to be done)

Im able to reproduce it.
Setup an application in an older framework version. Update it. Go to a special page and you will see the exception.
My special page is an API page which uses bearer authentication instead of a classic cookie authentication. The dll that tried to be loaded is the OpenID dll and then it fails.

The problem should be the same with the Nginx chapter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **shboyer**

**Comment by guardrex** [comment]
@shirhatti Should we say in the *Additional Suggestions* section to restart the server whenever the runtime is updated? It's a rather common server scenario tho ... restarts are usually required (in my experience) in server scenarios with updated software of any kind.

**Comment by shirhatti** [comment]
Before we make any changes to the document I want to understand the scenario and currently I don't follow the issue filed.

@vletoux Can you please elaborate or more provide more detailed repro steps?

What version did you upgrade from? And what version did you upgrade to?
Additionally, what was the assembly that failed to load? Is it part of the shared framework?

**Comment by shirhatti** [comment]
I see what's happening now. I assume you updated from 3.0.0 to 3.0.1?

**Comment by vletoux** [comment]
Not at all
I ran apt upgrade to update from 2.1.x to the latest 2.1.x
Then I didn’t restart the application.
A while later I tried to call the API.
It was not working.
I looked at the log and found the file not found exception that I can reproduce.
Then restarted the application which fixed the problem.
I can copy paste the whole exception but this has nothing with the root cause.

**Comment by shirhatti** [comment]
It was pointed out to me that I missed the fact that you're on Linux.

Yes, what you've observed can happen if your application attempts to load assemblies in a shared framework. Unfortunately, the only foolproof way of ensuring this doesn't occur is restarting any dotnet application that might have relied on the prior shared framework.

@guardrex You don't require a system reboot. Just need to restart your application.
While this issue has always been the case in Linux (if you install through package managers), as of 3.x and newer it impacts Windows as well. Just a heads-up in case you see more of these issues filed.
