### ISSUE TITLE
Component parameters: is "MouseEventArgs e" recommended.

### ISSUE THREAD

**Issue by DrGriff** [aspnet/AspNetCore.Docs#15894]
In the section on Component Parameters, you show the button click event handler having the signature:

private void ShowMessage(MouseEventArgs e)
    {
        messageText = "Blaze a new trail with Blazor!";
    }

My question is whether `MouseEventArgs e` recommended?  I've found it works without any parameters `private void ShowMessage()`.  In the example you've show, you're not consuming `e` and so would get the code-analysis warnings for unused parameters.  However, I want to stick with Microsoft's recommended "best practice".

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-parameters 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-parameters)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by DrGriff** [comment]
Ah: "If access to one of these event types isn't necessary, it isn't required in the method call."  Guess that answes that...

**Comment by guardrex** [comment]
That's reasonable, but I lean in the direction of using `e` there. It demos a concept coming up later in the page for these event argument types (which you just saw :point_up:).

I'll make a change for this ... probably use `e`. If not tho, then I'll 🔪 that there as unnecessary to make this concept (parameters) clear.

Thanks for asking. No need to close this ... this issue will automatically close when the PR merges.
