### ISSUE TITLE
Implementing AddApiAuthorization with database for IdentityServer4 objects

### ISSUE THREAD

**Issue by yakeer** [aspnet/AspNetCore.Docs#15896]
Hey,
I've tried to implement the AddApiAuthorization extension alongside with saving the IdentityServer4 objects, but with no luck.

Is it even possible?
It seems like it's always taking the Resources (and other objects) from the InMemory storage.

Would appreciate any reference for this.

**Comment by Rick-Anderson** [comment]
I'd ask the IdentityServer4  folks
