### ISSUE TITLE
A step-by-step tutorial with deployment to Azure App service

### ISSUE THREAD

**Issue by DevOpsFounder** [aspnet/AspNetCore.Docs#15909]
**I created this video as step-by-step with animated workflow, it can help many people**
This video will show step-by-step ASP.NET Core development with Deployment to Azure
https://www.youtube.com/watch?v=1QVRe7UHaro
![ASP NET And Entity Framework With Azure](https://user-images.githubusercontent.com/14263956/69832613-3dea2100-1227-11ea-9575-64aab6f03466.gif)

**Comment by Rick-Anderson** [comment]
What tutorial should this be surfaced from?
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
