### ISSUE TITLE
How to configure Plain text Input formatter in Razor Pages 3.0?

### ISSUE THREAD

**Issue by alvipeo** [aspnet/AspNetCore.Docs#15906]
I have a plain text formatter, but how do I configure Razor pages? Or should I just use MVC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This topic is for Web API's, not UI.

**Comment by alvipeo** [comment]
I added formatter with the old Core 2 code:
```
services.AddMvc(options =>
            {
                options.InputFormatters.Add(new TextPlainInputFormatter());
                options.OutputFormatters.Add(new TextPlainOutputFormatter());
            });
```

I couldn't find any other way. But I had to remove `AddRazorPages()` and use `AddMvc()`.

Not sure this is optimal way.

**Comment by Rick-Anderson** [comment]
No need to remove  `AddRazorPages()`
