### ISSUE TITLE
Edit a Razor Page

### ISSUE THREAD

**Issue by manonash** [aspnet/AspNetCore.Docs#15908]
The instruction says to "save the page with the following highlighted markup" -- but I have no idea where to *put* said markup. I see nothing on the existing page that matches the code surrounding the line to be pasted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.0&tabs=windows#feedback)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by santarede** [comment]
Simple add the line before </div>.

**Comment by Rick-Anderson** [comment]
Thanks @santarede
