### ISSUE TITLE
Not updated to VS 2019 & 3.0

### ISSUE THREAD

**Issue by Gobbeldygook** [aspnet/AspNetCore.Docs#15902]
Nobody has done their homework here. It's just assume the VS 2017 instructions! With VS 2019 it has a "Get Started" page which isn't like VS 2017! The choices you have started are "Clone or check out code", "Open a project or solution", "Open a local folder" or "Create new project". THEREFORE, the steps you have at the start cannot go in that order! These instructions should be redone & validated, which they obviously are not valid!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/69767672-730c4b80-1121-11ea-99b6-e59ea3592811.png)
