### ISSUE TITLE
Why is Microsoft telling me to install an unsigned app and give it admin priveleges?

### ISSUE THREAD

**Issue by randyramig** [aspnet/AspNetCore.Docs#15910]
This app requires admin to install and is not signed.  Let's fix that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
What unsigned app? What's the instructions?

**Comment by randyramig** [comment]
Hi Rick, the link to install NSwagStudio:
https://github.com/RicoSuter/NSwag/wiki/NSwagStudio
On this page:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.0&tabs=visual-studio

**Comment by jwisener** [comment]
Does Microsoft officially support/offer this? Or is this just a 3rd party windows form application created by independent software developer?

**Comment by dougbu** [comment]
The application is a 3rd party application. Our documents mention its use but Microsoft does not support it.

@RicoSuter can speak to why it's not signed.

**Comment by Rick-Anderson** [comment]
@danroth27 please review. Seriously, you need to review this.

**Comment by RicoSuter** [comment]
On the release page you can also download an xcopy version which can be started without installation and admin privileges. But  I agree that the app should be signed or provided via app store (better).

**Comment by danroth27** [comment]
@glennc

**Comment by Rick-Anderson** [comment]
> On the NSwag releases page you can also download an xcopy version which can be started without installation and admin privileges.

Thanks @RicoSuter  I'll add that to this doc and close the issue.
