### ISSUE TITLE
JS client don't add token to query string with accessTokenFactory

### ISSUE THREAD

**Issue by wangxin12** [aspnet/AspNetCore.Docs#15911]
"In standard web APIs, bearer tokens are sent in an HTTP header. However, SignalR is unable to set these headers in browsers when using some transports. When using WebSockets and Server-Sent Events, the token is transmitted as a query string parameter."

Describe the bug
token is not transmitted as a query parameter to the backend. I am using @aspnet/signalr 1.1.4

To Reproduce
this.connection = new signalR.HubConnectionBuilder()
.withUrl("/chathub", { accessTokenFactory: () =&gt; this.loginToken })
.build();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
@wangxin12 could you provide a repro app that shows the token not being sent to the server?

**Comment by wangxin12** [comment]
Sorry, my bad. Signalr js client is all good. I found that the cause is about the order of  middlewares in my .net core app. In my case, putting app.UseRouting() after app.UseAuthorization() works, not as the order recommended by this doc https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0 . I am new to .net core and I will dive deep it.

I will close this issue.  Sorry for the inconvenience caused.

**Comment by yakeer** [comment]
God bless you.
Moving the app.UseRouting() after app.UseAuthorization() indeed works!
I'm on this issue for 20 hours now!

I'm just suspecting it's going to make something else not work...

**Comment by yakeer** [comment]
Well I was happy too soon..
If does remove the error, but the user is not identified... :/

**Comment by wangxin12** [comment]
I haven't found it makes anything else not work till now. And for the user not identified issue, maybe you did not check the token you got in a right way.
