### ISSUE TITLE
Combining multiple providers from seperate libraries

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#15917]
The approach shown in this documentation doesn't show you how you might combine multiple providers, say from seperate nuget packages, into one singleton composite provider.

For anyone looking to do that, I created: https://github.com/dazinator/Dazinator.AspNetCore.Authorization - and have opened this github issue as I think that would be a good thing to have in the framework by default: https://github.com/aspnet/AspNetCore/issues/17493

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by dazinator** [comment]
- I think a better example of how to write a custom policy provider is the one I have documented here: https://github.com/dazinator/Dazinator.AspNetCore.Authorization/blob/develop/README.md#note-to-provider-authors
It would be interesting to know if the asp.net core team agree with me and if you'd therefore update this documentation with this in mind?

**Comment by Rick-Anderson** [comment]
@blowdart  let me know if you're interested in documenting this. I think this is out of the scope of the docs so closing for now.
