### ISSUE TITLE
Can't use SignInManager.PasswordSignInAsync in Blazor

### ISSUE THREAD

**Issue by sarathlalsaseendran** [aspnet/AspNetCore.Docs#15919]
Currently Blazor supports ASP.NET Core MVC authentication by default. Hence, I tried to create my own register and login with Blazor components. I could register a new user using "UserManager.CreateAsync". But while trying "SignInManager.PasswordSignInAsync", it is showing below error message.

System.InvalidOperationException: The response headers cannot be modified because the response has 
already started.

Do you have any work around for it? So that I can complete my Login component with Blazor itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn can you please look into this? Thanks!

**Comment by idchlife** [comment]
Guys, what's the official way for signing in users in Blazor using Identity Core? I have the same problem as @sarathlalsaseendran

**Comment by javiercn** [comment]
You can't sign in users in server-side Blazor using `SignInManager`. Server-side Blazor uses SignalR under the hood and the underlying transport might not have an HttpContext available.

The right way to Sign in Blazor users is to redirect them to a plain old server-side rendered page (like it does by default) and then redirect them to the Blazor app to re-establish the connection.

Otherwise, there's no way for Identity to setup the cookie that is required for tracking the authentication state.

**Comment by javiercn** [comment]
@SteveSandersonMS Do you have any further thoughts given you did all the work here?

**Comment by guardrex** [comment]
For a few workarounds (or at least one by [Christian Sparre](https://github.com/christiansparre) at [SignIn.razor](https://github.com/christiansparre/BlazorAuthenticationSample/blob/master/src/BlazorAuthenticationSample.Client/Features/Account/Pages/SignIn.razor)) for right now, I suggested that we cross-link Awesome Blazor's *Authentication* section on https://github.com/aspnet/AspNetCore.Docs/pull/16816 in the *Additional Resources* section.

**Comment by idchlife** [comment]
@javiercn I might add, that just to be safe, there should be double-action when signing in. Good-ole sign out, then redirect to sign in, then redirect to "/".

I experienced several times bizarre bug when after restarting PC ASP.NET thought that user is not logged in despite browser using cookies from before PC restart. So naturally our blazor app suggested for user to sign in. User signed in, on server side verything cool, but for some reason cookie was not replaced with new one, and blazor still did not know that user should be already authenticated, no matter redirects or page reloads. Endless "please login" limbo with redirects to "please login" popup.

Solved it by always signing out after login form submit then redirecting to empty page (to remove old cookies or something), which redirects to sign in controller action which redirects to "/" with new cookies. All redirects took with them protected token of course, so the final part will successfully login user..

**Comment by javiercn** [comment]
@idchlife I'm not sure what you are trying to accomplish, but essentially server-side Blazor is a stateful connection under the hood and the user identity is established when the client connects to the server for the first time.

ASP.NET Core Identity is designed to work with traditional server-side rendered applications and for that matter the entry point to a server-side Blazor application is a traditional server-side rendered application. 

For that reason, the SignInManager and other abstractions will in principle not work once the server-side Blazor application has started.

The recommended way to perform authentication in such scenarios is with a form post + redirect, the way the default UI in ASP.NET Core Identity does.

Hope this helps.

I'm closing this issue as this is not a docs issue per se.

**Comment by idchlife** [comment]
@javiercn just for future developers who will stumble upon this issue. I'm using ASP.NET Mvc Identity Core authentication with Blazor server, since it's the only working way for blazor server for authentication(as we already learned here). It just there is weird bug when using approach https://github.com/christiansparre/BlazorAuthenticationSample/blob/master/src/BlazorAuthenticationSample.Client/Features/Account/Pages/SignIn.razor that sometimes user can be caught in forever login, because old cookies for some reason stay and new cookies are not being written if user is not force-sign-out before sign-in.

Just leaving comment so anyone who is trying to use Blazor server in production will know the sort of resolution.

**Comment by Freshmintyy** [comment]
> @javiercn just for future developers who will stumble upon this issue. I'm using ASP.NET Mvc Identity Core authentication with Blazor server, since it's the only working way for blazor server for authentication(as we already learned here). It just there is weird bug when using approach https://github.com/christiansparre/BlazorAuthenticationSample/blob/master/src/BlazorAuthenticationSample.Client/Features/Account/Pages/SignIn.razor that sometimes user can be caught in forever login, because old cookies for some reason stay and new cookies are not being written if user is not force-sign-out before sign-in.
> 
> Just leaving comment so anyone who is trying to use Blazor server in production will know the sort of resolution.

If you have changed IdentityUser to a custom implementation remember to update 

UserManager<ApplicationUser> userManager
and
SignInManager<ApplicationUser> signInManager

**Comment by ParadiseFallen** [comment]
Is there any progress on this issue?

**Comment by domizacz** [comment]
Do we have any updates on this topic?
