### ISSUE TITLE
machine account password (in linux steps)

### ISSUE THREAD

**Issue by HelicalSyncromesh** [aspnet/AspNetCore.Docs#15923]
"Use ktpass to generate a keytab file:
    ktpass -princ HTTP/mywebservice.mydomain.com@MYDOMAIN.COM -pass myKeyTabFilePassword -mapuser MYDOMAIN\mymachine$ -pType KRB5_NT_PRINCIPAL -out c:\temp\mymachine.HTTP.keytab -crypto AES256-SHA1"

When I run this command I get prompted if I want to reset the password of the machine account:
"WARNING: Account ip-10-0-243-22$ is not a user account (uacflags=0x11001).
WARNING: Resetting ip-10-0-243-22$'s password may cause authentication problems if ip-10-0-243-22$ is being used as a server.

Reset ip-10-0-243-22$'s password [y/n]?"

Won't resetting the machine account password break the realm join that was done in prior steps?

Also, I think you should update the code snippet because "-pass myKeyTabFilePassword" is misleading if this command is actually updating the machine account password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Moved to #15922.
