### ISSUE TITLE
Questions about Windows auth & Linux

### ISSUE THREAD

**Issue by HelicalSyncromesh** [aspnet/AspNetCore.Docs#15922]
"On the domain controller, add new web service SPNs to the machine account:
    setspn -S HTTP/mywebservice.mydomain.com mymachine
    setspn -S HTTP/mywebservice@MYDOMAIN.COM mymachine"
Why are the HTTP SPNs needed in addition to the default HOST SPNs?  Playing with this in a lab environment I'm seemingly able to get this working (hosted from linux, accessed with a windows domain machine, currently signed in user can access without a password prompt) while totally skipping the SPN/ktpass steps.  So what is the point of them?

[EDIT by guardrex to include followup question from #15923]

### machine account password (in linux steps)

"Use ktpass to generate a keytab file:
    ktpass -princ HTTP/mywebservice.mydomain.com@MYDOMAIN.COM -pass myKeyTabFilePassword -mapuser MYDOMAIN\mymachine$ -pType KRB5_NT_PRINCIPAL -out c:\temp\mymachine.HTTP.keytab -crypto AES256-SHA1"

When I run this command I get prompted if I want to reset the password of the machine account:
"WARNING: Account ip-10-0-243-22$ is not a user account (uacflags=0x11001).
WARNING: Resetting ip-10-0-243-22$'s password may cause authentication problems if ip-10-0-243-22$ is being used as a server.

Reset ip-10-0-243-22$'s password [y/n]?"

Won't resetting the machine account password break the realm join that was done in prior steps?

Also, I think you should update the code snippet because "-pass myKeyTabFilePassword" is misleading if this command is actually updating the machine account password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @HelicalSyncromesh Let's wait until we're past this holiday weekend. I'll ping the author to comment.

**Comment by guardrex** [comment]
@HelicalSyncromesh ... Need to wait a bit longer. All teams are 🏃😅 for 3.1 work. I'll call for engineering clarification after 3.1 releases.

**Comment by guardrex** [comment]
@Tratcher ... a question on Windows Auth and Linux. I waited until after 3.1 to ping. 🏃😅

Whatever the answer, also let me know which bits should be covered from your response, if anything.

**Comment by Tratcher** [comment]
> @HelicalSyncromesh ... Need to wait a bit longer. All teams are 🏃😅 for 3.1 work. I'll call for engineering clarification after 3.1 releases.

@guardrex we finished 3.1 weeks ago 😁.

> Why are the HTTP SPNs needed in addition to the default HOST SPNs?

That's odd, the HTTP SPNs are required for a Windows server. I recall my Linux server not working without them, but I didn't try many variations. Which client are you using?

> When I run this command I get prompted if I want to reset the password of the machine account:

Curious, I never saw that warning.

@davidsh, any insights on these?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by HelicalSyncromesh** [comment]
> Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

Um no, this absolutely hasn't been answered.  Please reopen and explain what the SPNs are required for and what function they perform.  You guys also merged my other question about machine password resets and have provided no information about that either.  Come on team, give me something better than a collective shoulder shrug.

**Comment by guardrex** [comment]
> collective shoulder shrug

Not my call @HelicalSyncromesh. Management handles this decision.

**Comment by HelicalSyncromesh** [comment]
> > @HelicalSyncromesh ... Need to wait a bit longer. All teams are 🏃😅 for 3.1 work. I'll call for engineering clarification after 3.1 releases.
> 
> @guardrex we finished 3.1 weeks ago 😁.
> 
> > Why are the HTTP SPNs needed in addition to the default HOST SPNs?
> 
> That's odd, the HTTP SPNs are required for a Windows server. I recall my Linux server not working without them, but I didn't try many variations. Which client are you using?
>
> 
> Curious, I never saw that warning.

Clients I've been using is newest IE.

As far as password reset warning I'm getting that warning repeatably as are other team members in their own environments.  We've never been able to get the steps to work without getting that warning.



> > @HelicalSyncromesh ... Need to wait a bit longer. All teams are 🏃😅 for 3.1 work. I'll call for engineering clarification after 3.1 releases.
> 
> @guardrex we finished 3.1 weeks ago 😁.
> 
> > Why are the HTTP SPNs needed in addition to the default HOST SPNs?
> 
> That's odd, the HTTP SPNs are required for a Windows server. I recall my Linux server not working without them, but I didn't try many variations. Which client are you using?
> 
> > When I run this command I get prompted if I want to reset the password of the machine account:
> 
> Curious, I never saw that warning.
> 
> @davidsh, any insights on these?

Sorry I got no email about this particular reply.  Client used was IE, latest.  The machine password reset was observed repeatably by myself and two other dev team members.  Any insights on the potential long term impact of forcibly resetting?

**Comment by Tratcher** [comment]
> Any insights on the potential long term impact of forcibly resetting?

Sorry, no, this scenario is new for us and we haven't experienced any long term side-effects yet.

**Comment by undecided2013** [comment]
OK, so, Kerberos Auth works for us against Windows AD in asp.net core 3.1 running on Linux. What we can't figure out is how to make the Authorize Attributes work with AD roles. It seems that the identity retrieved after the kerberos authentication has no claims associated with it. What do we need to configure to fetch the roles from AD?

**Comment by Tratcher** [comment]
@undecided2013 That's work we're considering for 5.x and is tracked by https://github.com/aspnet/AspNetCore/issues/12938.

**Comment by undecided2013** [comment]
> 
> 
> @undecided2013 That's work we're considering for 5.x and is tracked by [aspnet/AspNetCore#12938](https://github.com/aspnet/AspNetCore/issues/12938).

That makes sense, thank you. As a side-question, in the meantime, if we wanted to handle the fetching of claims ourselves using LDAP api, is there an injection point in the pipeline that would allow us to do that after the user has been authenticated but before the Authorize attribute is checked ? ([Authorize (Roles="")] ). We could then populate the claims onto the Identity ourselves. Thx

**Comment by Tratcher** [comment]
@undecided2013 check out NegotiateOptions.Events.OnAuthenticated.
https://github.com/aspnet/AspNetCore/blob/94b44141ce0437541fc1ff6b5fd8b48140548f66/src/Security/Authentication/Negotiate/test/Negotiate.Test/EventTests.cs#L280-L290

Beware that this runs on every request, even if the kerberos credentials don't change. You'll want to do some caching.

**Comment by undecided2013** [comment]
> @undecided2013 check out NegotiateOptions.Events.OnAuthenticated.
> https://github.com/aspnet/AspNetCore/blob/94b44141ce0437541fc1ff6b5fd8b48140548f66/src/Security/Authentication/Negotiate/test/Negotiate.Test/EventTests.cs#L280-L290
> Beware that this runs on every request, even if the kerberos credentials don't change. You'll want to do some caching.

Hi Tratcher, I tried 2 approaches. One was to add the NegotiateEvent OnAuthenticated  in the ConfigureServices like this:

services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate(options =>
            {
                options.Events = new NegotiateEvents()
                {
                    OnAuthenticated = context =>
                    {
                        context.Success();
                        return Task.CompletedTask;
                    }
                };
            });

I never saw the event being called though.

As a separate approach I created an IClaimsTransformation that took the username and went to LDAP directly to pull the claims. 
I injected that using 
services.AddSingleton<IClaimsTransformation, LDAPRoleAuthorizationTransform>();

That works for the most part as in my Controller the Identity has the claims I manually add to the ClaimsPrincipal in the TransformAsync methos of the IClaimsTransformation implementation.

What still does NOT work is the [Authorize (Roles="")].

It seems that the Authorize Attribute is unaware of all of the above work that I did.  It just throws a 401 everytime I add a Role for it to check.

**Comment by undecided2013** [comment]
> @undecided2013 check out NegotiateOptions.Events.OnAuthenticated.
> https://github.com/aspnet/AspNetCore/blob/94b44141ce0437541fc1ff6b5fd8b48140548f66/src/Security/Authentication/Negotiate/test/Negotiate.Test/EventTests.cs#L280-L290
> Beware that this runs on every request, even if the kerberos credentials don't change. You'll want to do some caching.

OK, some more info:

In ConfigureServices I added this policy

 services.AddAuthorization(options =>
            {
              options.AddPolicy("CanView", policy => policy.RequireClaim(@"role", new string[] { "ViewRole" }));
}


In the    IClaimsTransformation
 TransformAsync(ClaimsPrincipal principal)
I create a new ClaimsIdentity with RoleClaimType 'role'.



In my BaseController derived controller I added an Authorize attribute with no policy, put a breakpoint in there and I can see the user is populated with 
the claims I populate in my ClaimsTransformation and the claims have the correct RoleClaimType of 'role'.


BUT when I change the [Authorize] to [Authorize(Policy ="CanView")] I get a 403.
Is there a place I can put a break point to see what is happening?

**Comment by undecided2013** [comment]
> @undecided2013 check out NegotiateOptions.Events.OnAuthenticated.
> https://github.com/aspnet/AspNetCore/blob/94b44141ce0437541fc1ff6b5fd8b48140548f66/src/Security/Authentication/Negotiate/test/Negotiate.Test/EventTests.cs#L280-L290
> Beware that this runs on every request, even if the kerberos credentials don't change. You'll want to do some caching.

Update, everything works now. I created an IClaimsTransformation to go to LDAP and I store the claims in a singleton InMemoryCache. Thanks for the help.
