### ISSUE TITLE
Named options: list of names

### ISSUE THREAD

**Issue by rcollina** [aspnet/AspNetCore.Docs#15925]
Could you please include any guidance on how to retrieve all the names with which an option type has been registered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rcollina ... AFAIK, the Options Manager doesn't make the names public. If you want to make a feature request, open an issue on the engineering repo :point_right: https://github.com/aspnet/AspNetCore/issues
