### ISSUE TITLE
httprepl nice idea, but why are error messages like fail to connect shown as stacktraces?

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/AspNetCore.Docs#15936]
For example, instead of "No connection ...." I get this

http://localhost:5000/&gt; options
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---&gt; System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
:
:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16842b60-b268-a322-8078-c0b27c57fa7d
* Version Independent ID: d63c12f3-220e-9067-ead5-90e644c06591
* Content: [Test web APIs with the HTTP REPL](https://docs.microsoft.com/en-us/aspnet/core/web-api/http-repl?view=aspnetcore-3.0&tabs=windows)
* Content Source: [aspnetcore/web-api/http-repl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/http-repl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/dotnet/HttpRepl/issues/304, where the engineering team can take a look.
