### ISSUE TITLE
Enabling detailed logs for SignalR's server-side logging

### ISSUE THREAD

**Issue by adiessl** [aspnet/AspNetCore.Docs#15935]
The documentation for the server-side logging says that one has to set the log level to `Debug` for the logger categories `Microsoft.AspNetCore.SignalR` and `Microsoft.AspNetCore.Http.Connections` to enable detailed logging. During my tests, however, I could only enable detailed logging when setting the log level to `Trace`.

https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#server-side-logging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef32cc5-6a1f-25c9-0d89-a984a3f68851
* Version Independent ID: 3e302985-8504-d333-3222-ab8da8902da2
* Content: [Logging and diagnostics in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#server-side-logging)
* Content Source: [aspnetcore/signalr/diagnostics.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @anurse
* Microsoft Alias: **anurse**

**Comment by Rick-Anderson** [comment]
Can you post the simplest possible repo on a public GitHub?

**Comment by adiessl** [comment]
Unfortunately I can't. I've been trying to, but in the simple sample that I set up it works as intended ...

The real question then is: why does it not work in our production app?! I think I'll have to investigate further. In the meantime I will close this issue.

**Comment by adiessl** [comment]
I found the reason: we are using Serilog and have a custom event filter active that filters log messages for log level `Debug`. Only for `Debug` though, not for `Trace`. That is why setting the log level to `Trace` led to an output while `Debug` did not.
