### ISSUE TITLE
It's said SQLite but SQL Server is used

### ISSUE THREAD

**Issue by mrmowji** [aspnet/AspNetCore.Docs#15933]
I went through this tutorial. I'm using VS Community 2019 (removed 2017 and installed 2019). At the beginning of the document, it's mentioned that we will use SQLite, but when I finished the steps, I ended up with a SQL Server DB (.mdf). Couldn't find SQLite on later tutorials either. Is there something missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio#scaffold-the-movie-model)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
VS uses SQL Express.
