### ISSUE TITLE
AddNewtonsoftJson() not defined

### ISSUE THREAD

**Issue by KevinBurton** [aspnet/AspNetCore.Docs#15930]
I installed Microsoft.AspNetCore.Mvc.NewtonsoftJson but AddNewtonsoftJson() is not defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
After restoring the project, you should be able to get it with ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting/3.0sample/StartupNewtonsoftJson.cs#L4

**Comment by guardrex** [comment]
I'll close as answered. If you end up with strange package behavior, nuke your package cache and try again ...

```dotnetcli
dotnet nuget locals all --clear
```
