### ISSUE TITLE
Publish React ASP.NET Core 3 Template 

### ISSUE THREAD

**Issue by windson** [aspnet/AspNetCore.Docs#15934]
These steps didn't work for React ASP.NET Core 3 Template that comes with visual studio 2019.
Pleaes provide detailed step by step documentation.

I Created S1 linux plan and tried to deploy the asp.net core 3 react template. but it didn't succeed. Still shows the default homepage that comes with app service plan.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This tutorial doesn't use React.

**Comment by windson** [comment]
Can you point me to react asp.net core 3 publish steps documentation?
