### ISSUE TITLE
DI - Views - Sample out of date

### ISSUE THREAD

**Issue by Rich-Lang** [aspnet/AspNetCore.Docs#15939]
Project still uses XProj and VS unable to migrate and run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Dependency injection into views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-3.0#configuration-injection)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Rich-Lang ... thanks for writing in. Yes, this is tracked by our sample update tracking issue :point_right:. We don't have an ETA on it being addressed, but it is being tracked for that work.
