### ISSUE TITLE
Command update-database failed

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15946]
@PanQiWei commented on [Mon Dec 02 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/222)

After excute Add-Migration InitialCreate correctly,the command Update-Database failed with the following error:
Error Number:5123,State:1,Class:16
CREATE FILE encountered operating system error 5(拒绝访问。) while attempting to open or create the physical file 'C:\Users\59455RazorPagesMovieContext-b2dc6870-9632-49c3-a351-68dc42444044.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
Can masters help me!!!

---

@PanQiWei commented on [Mon Dec 02 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/222#issuecomment-560392529)

Is that I need to redirect the folder path to create the database?

---

@PanQiWei commented on [Mon Dec 02 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/222#issuecomment-560392868)

It seems there is no web.config file for me to redirect path...

---

@srvbpigh commented on [Mon Dec 02 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/222#issuecomment-560396163)

Hello, @PanQiWei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by PanQiWei** [comment]
I still not deal with the error of Update-Database command,but I use Script-Migration to build a .sql file and create the database by hand and this works.But I still wonder how should I fix the problem when using the Update-Database command? It seems that there is a bug in default directory path.

**Comment by Rick-Anderson** [comment]
The tutorial works. ASP.NET Core doesn't use web.config.
