### ISSUE TITLE
3.1: Partial class support for Razor components

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15953]
See https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-1/

Add a section for **Partial class support for Razor components** That I can point to in the what's new in 3.1 guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  any chance you could get this done by noon your time tomorrow?

**Comment by guardrex** [comment]
This one? ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#partial-class-support

**Comment by guardrex** [comment]
I'm pretty sure that I can get that done by noon tomorrow. :smile: lol

**Comment by Rick-Anderson** [comment]
That was fast!

**Comment by Rick-Anderson** [comment]
@guardrex  can you provide a link for 
Pass parameters to top-level components
Blazor Server apps can now pass parameters to top-level components during the initial render. Previously you could only pass parameters to a top-level component with RenderMode.Static. With this release, both RenderMode.Server and RenderModel.ServerPrerendered are now supported. Any specified parameter values are serialized as JSON and included in the initial response.

For example, you could prerender a Counter component with a specific current count like this:

@(await Html.RenderComponentAsync<Counter>(RenderMode.ServerPrerendered, new { Cur

**Comment by guardrex** [comment]
Use this one (version is important, so link to 3.1) ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#integrate-components-into-razor-pages-and-mvc-apps

... there's an existing PR for the components topic. I'd like to make the call out more explicit than what the example there shows. However, it's fairly obvious that the param is passed there as it is.

**Comment by guardrex** [comment]
I added a line to that section to surface it a bit more. That will merge shortly. You can go ahead with that link :point_up: versioned for 3.1.

**Comment by Rick-Anderson** [comment]
3.1 becomes the default tomorrow.
Thanks.
