### ISSUE TITLE
2.1 reference included in page

### ISSUE THREAD

**Issue by Allann** [aspnet/AspNetCore.Docs#15967]
CompatibilityVersion.Version_2_1 is reference in the page even though I had 3.0 selected

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Allann ... Yes, it's because the topic hasn't been updated for 3.x. It looks like that's the only change, so I'll do a quick patch to version that content and provide the 3.x approach. Thanks for calling it out.
