### ISSUE TITLE
[BindRequired] attribute description unclear

### ISSUE THREAD

**Issue by kustox** [aspnet/AspNetCore.Docs#15972]
Description states "Can only be applied to model properties, not to method parameters. ", 
but the source code allows the attribute on parameters 
`([AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Parameter, AllowMultiple = false, Inherited = true)]`
from https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/BindRequiredAttribute.cs ) 
Can you please clarify this contradiction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It has other restrictions

Note that this `[BindRequired] ` behavior applies to model binding from posted form data, not to JSON or XML data in a request body. Request body data is handled by input formatters.

**Comment by vernou** [comment]
The doc notice [BindRequired] don't work with method's parameter :

> [BindRequired] attribute
> Can only be applied to model properties, not to method parameters. Causes model binding to add a model state error if binding cannot occur for a model's property. Here's an example:

But when I try, [BindRequired] appear to work correctly with method's parameter.

Example :
```csharp
[ApiController]
[Route("data")]
public class DataController : ControllerBase
{
    [HttpGet]
    public IActionResult Post([BindRequired] int id, [BindRequired] string label)
    {
        return Ok(new { id, label });
    }
}
```
When I call `http://localhost:5005/data`, this return this :
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-a5d0607e3ac60f44b47639f45e77fd6a-bedbe77983591349-00",
    "errors": {
        "id": [
            "A value for the 'id' parameter or property was not provided."
        ],
        "label": [
            "A value for the 'label' parameter or property was not provided."
        ]
    }
}
```

Is the doc incorrect?
Or method's parameter mean other thing?
