### ISSUE TITLE
Visual Studio 2019 v16.4.0 Publish Profiles

### ISSUE THREAD

**Issue by NXTwoThou** [aspnet/AspNetCore.Docs#15986]
Note, you'll also need to hand edit your .pubxml files to change from netcoreapp3.0 to netcoreapp3.1.  If you use the Edit button inside of Publish, under Settings and Target Framework, it will say netcoreapp3.1, but after hitting save, it doesn't update the pubxml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b7135b-b7a0-2fba-b846-530480aeb415
* Version Independent ID: 69e5b8fb-04e0-817e-434f-72cf6ba12923
* Content: [Migrate from ASP.NET Core 3.0 to 3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/30-to-31.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/30-to-31.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Surprising! I We would expect it to honor the selection. We're a bit outside of the Visual Studio processes here. We only handle ASP.NET Core doc issues here, so we can't address this problem directly. I recommend that you open this with the VS team using the **Help** > **Send Feedback** > **Report a Problem** process from within Visual Studio.

**Comment by NXTwoThou** [comment]
> Surprising! We would expect it to honor the selection. We're a bit outside of the Visual Studio processes here. We only handle ASP.NET Core doc issues here, so we can't address this problem directly. I recommend that you open this with the VS team using the Help > Send Feedback > Report a Problem process from within Visual Studio. Truly ... it opens an issue directly with that team. It won't vaporize on you. 😄 They will see it and react. They work off an internal issue processing system.

Not so much unfortunately.  I went through the steps to report the problem(went to publish, hit edit, showed dropdown, saved, brought up the .pubxml, tried it on two other publish profiles to demonstrate the same thing) and after I recorded the steps it said "preparing" and I finally killed the process after 40+ minutes of doing nothing.

I mostly replied to the docs because you are hopefully about to have a flood of people go there to get their sites migrated to 3.1.  If any of them are using VS to publish, they'll run into the same "There's no other option beyond netappcore3.1 in the drop down, yet I'm getting an error when I publish" and might not know where to look to track down what they need to hand edit.  In the scope of things, it's relatively minor but it's not documented as a possible step that needs to be done.

**Comment by guardrex** [comment]
The only thing that jumps to mind is the version. Are you on the just-released 16.4 version (**not preview**) that came out today?

**Comment by guardrex** [comment]
I don't want to keep this open given the issue load. @NXTwoThou, try the latest VS that just came out today ... 16.4. See if that's still an issue with this version that just released. If so, let the VS team know via the *Report a Problem* process. I assure u ... it isn't a *black hole* ⚫️. :smile: Human :eyes: will see your issue filed that way.

**Comment by NXTwoThou** [comment]
> The only thing that jumps to mind is the version. Are you on the just-released 16.4 version (not preview) that came out today?

Correct, 16.4.0.  I saw the blog post about 3.1 being released, checked for VS update, installed, rebooted, loaded up vs, changed my project target to 3.1, updated extensions/GitHub, compiled, ran in debug, tested everything, switched to release, tested everything, installed 3.1 hosting bundle on all servers, went to publish, got an error about not being able to find 3.0, double checked my publish properties, did a search in my project for 3.0, got frustrated, eventually grepped the folder and found the .pubxml files that still said netappcore3.0 as the target.  Rebooted, checked for vs updates again, loaded up my project, double checked for any component/extension/library updates, went to publish and made sure the target was netappcore3.1 and hit save, tried to publish, same error.  Hand edited .pubxml file for netappcore3.1, published fine, worked fine on server.  Selected my second publish profile and had the same 3.0 error, compared IDE settings and both said netappcore3.1(no selection for 3.0 available), did the report a problem option in help, detailed what was going on, started recording, demoed the above steps on the second publish profile and that hitting save didn't change the target, stopped the recording, it came up that it was working(don't recall the exact message), let it sit for 30 minutes, closed the vs window while allowing the report a problem screen to continue with it's infinite progress bar, did some work else where for 10 minutes, it was still doing it's thing, loaded up another vs instance, hand edited my .pubxml's, published to the other two servers.

**Comment by guardrex** [comment]
Unfortunately, I don't have a contact on the VS team to receive a problem that the **Report a Problem** process can't accept. We're working off of https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019, and teans are highly compartmentalized. That's how they recommend to users to get in touch with them. We only handle ASP.NET Core docs here, so we don't have much direct contact with them.

**Comment by robinwilson16** [comment]
I reported this issue when migrating .NET Core 2.2 projects to 3.0 in October (AspNetCore/issues/14842) and was able to easily replicate it with each project I migrated but the issue was closed and seems it is not fixed.

**Comment by guardrex** [comment]
It has to be addressed by engineering/VS team. We only maintain the ASP.NET Core doc set here. Open a new issue with engineering to let them know that the issue isn't fixed and cross-link that engineering issue.
