### ISSUE TITLE
Disable registration 'Remove the code and links from the cshtml file.'

### ISSUE THREAD

**Issue by pwen090** [aspnet/AspNetCore.Docs#15994]
Hello, upgrading a project to 3.1 and love the new detailed documentation steps to disable registration. One point of clarification on the last step you mention "Remove the code and links from the cshtml file." 

Did you mean to essentially comment out everything below the &lt;h1&gt;@ViewData["Title"]&lt;/h1&gt; line in the RegistrationConfirmation.cshtml file? 

Like this: 
![image](https://user-images.githubusercontent.com/19834208/70102258-69388b80-15ec-11ea-9692-60168d42441b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes
