### ISSUE TITLE
Using a different environment when running integration tests

### ISSUE THREAD

**Issue by hamdarsi** [aspnet/AspNetCore.Docs#16002]
Some integration tests may need to use a custom or non-default hosting environment. This document provides a sample on how to do this, but unfortunately the `Set the environment` section does not match well with ASP.Net Core version 2.1 and 2.2 (I only checked these two specific versions)

I made it work using these steps:
1. Create a custom appsettings.[environment].json file
2. Create a custom WebApplicationFactory&lt;StartupClass&gt;
3. Write integration tests using the custom factory:

```
    public class IntegrationTestingFactory : WebApplicationFactory&lt;Startup&gt;
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.UseEnvironment("[Evnironment name]");
        }
    }

    public class SomeIntegrationTests : IClassFixture&lt;IntegrationTestingFactory&gt;
    {
        private readonly IntegrationTestingFactory _factory;

        public AccountControllerTests(IntegrationTestingFactory factory)
        {
            _factory = factory;
        }

        [Fact]
        public TestScenario()
        {

        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#customize-webapplicationfactory-1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hamdarsi ... Yes, there are a few ways to do it. The approach shown in the topic today is what engineering approved after discussing it when other developers wrote in to ask. We'll maintain it this way ... at least for now ... we'll keep and :ear: open for more feedback like yours and probably react if many devs write in about it. There's a discussion on it (and the approach that you settled on) at :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/12303, and you can check the linked issues there for more information.
