### ISSUE TITLE
Minor - "Host" missing in sample code

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore.Docs#16005]
For the sample code at the start of the "Create logs in the Program class" section, `CreateDefaultBuilder(args)` should be `Host.CreateDefaultBuilder(args)` -- the `Host` portion is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MV10 ... Referring to the first example? It's ok ... it's calling `CreateHostBuilder`, which returns an `IHostBuilder`. It could add a little boilerplate, but that might be overkill.

```csharp
... existing code for "public static void Main(string[] args)" ...

public static IHostBuilder CreateHostBuilder(string[] args)
{
    ...
}
```

**Comment by MV10** [comment]
It won't compile that way, `Host.` is missing:

![image](https://user-images.githubusercontent.com/794270/70153735-6c2f8c80-167d-11ea-9e85-950eb255788a.png)

It should be:

```csharp
public static void Main(string[] args)
{
    var host = Host.CreateHostBuilder(args).Build();
...etc.
```

**Comment by MV10** [comment]
![image](https://user-images.githubusercontent.com/794270/70154018-ce888d00-167d-11ea-8ee4-22981ba71d34.png)

**Comment by guardrex** [comment]
It’s not the complete example. The `CreateHostBuilder` method calls `Host.CreateDefaultBuilder` and returns an `IHostBuilder`. It can show the code I suggested. See the next example in this section. I’m at the 🏋 gym 💪 on the treadmill ... hard to type a little more context for what I’m proposing.

**Comment by guardrex** [comment]
*BACK!* :smile: ... that treadmill nearly 💀 me! 🏃🏃🏃😅 

It's best if we show the recommended approach that calls `CreateHostBuilder`. So, here's a more fleshed-out example of what I propose for that example ...

```csharp
public static void Main(string[] args)
{
    var host = CreateHostBuilder(args).Build();

    var todoRepository = host.Services.GetRequiredService<ITodoRepository>();
    todoRepository.Add(new Core.Model.TodoItem() { Name = "Feed the dog" });
    todoRepository.Add(new Core.Model.TodoItem() { Name = "Walk the dog" });

    var logger = host.Services.GetRequiredService<ILogger<Program>>();
    logger.LogInformation("Seeded the database.");

    IMyService myService = host.Services.GetRequiredService<IMyService>();
    myService.WriteLog("Logged from MyService.");

    host.Run();
}

public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

**Comment by MV10** [comment]
Doh! Can't believe I overlooked that. (I'm not a fan of the `CreateHostBuilder` approach since it doesn't work well for larger, real-world apps, so I'd forgotten MS does that everywhere.)
