### ISSUE TITLE
3.1 update: Filters

### ISSUE THREAD

**Issue by t-hart** [aspnet/AspNetCore.Docs#16006]
It's not quite clear from the docs whether you can use filters with routing that isn't based on MVC. For instance, I'm working on upgrading an app from 2.2 to 3.1 now, and where we previously used MVC routing, we now want to use Routing/Endpoint as per the recommendations. Also, because it's a web API using endpoint option's `MapControllers` makes getting the routes trivial. However, we previously set filters on the MvcOptions object (including AuthorizeFilter and a few custom ones), but this isn't available when using Routing. Can you still add filters even if you don't use MVC? If so: how? Either showing how you would do it, or explicitly calling out that you can't would make things easier, I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think you need to edit your question and change MVC to Controllers and Views. It's all MVC.

Is the real question how do I use filtering with a 3.1 API project that changes
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
```
to 
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }
```

And in `Configure` 3.1 uses

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
```

Rather than

`app.UseMvc();`

**Comment by JamesNK** [comment]
> However, we previously set filters on the MvcOptions object (including AuthorizeFilter and a few custom ones), but this isn't available when using Routing.

MvcOptions isn't related to routing. You can still do this in Startup.cs:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers(options =>
    {
         // configure MVC filters here
    });
}
```

**Comment by t-hart** [comment]
Aha, that does  it! Thanks @JamesNK; where to apply the  filters was what I was looking for and couldn't find any documentation on. 

The first part (controllers and endpoints) was pretty easy to find in the documentation and the upgrade guide, but I couldn't find anything on where to put the filters after being told to replace `AddMvc`, so yes, the question could be reframed to how do I add filters when moving away from `AddMvc`.

Thanks again!
