### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by lhemkendreis** [aspnet/AspNetCore.Docs#16004]
It says:
&gt; "For example, an authorization policy can specify by name which authorization scheme (or schemes) should be used to authenticate the user."

Shouldn't it be "[..]which authentication scheme [..] to authenticate the user" ? If it is not a mistake - i.e. if I am just failing to understand it - then it would be helpful to add an explanatory sentence in there to prevent this sort of confusion for future readers. Thx. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Slight change to the wording should work ...

> For example, a named authorization policy can specify which authorization scheme (or schemes) should be used to authenticate the user.

I'll patch that up right now. Thanks for writing in on it.

**Comment by mjrousos** [comment]
Yep, good catch, @lhemkendreis. Thanks!
