### ISSUE TITLE
Directionally this page is problematic

### ISSUE THREAD

**Issue by garethj-msft** [aspnet/AspNetCore.Docs#16001]
Leaving aside this page's fixation with the outdated swagger terminology, it focuses on a generative approach to OAS descriptions of services.

The API community on the whole is probably about 60/40 in the direction of design-first rather than code-first OAS usage. 

Thus, OAS is a hand-crafted artifact produced before code for services is written and used to lead and validate the design and evolution of services.   In this case, tools like swashbuckle and nswag are anti-patterns, leading as they do to incoherent OAS with minimal reuse and poor human readability and reviewability, and certainly to an inability to compare effectively with human-originated specs.

This pages assertion that a "swagger file is generated by a tool chain" is very much from the code-first school of thought, but the article does not make that clear or discuss the two prevailing approaches, their pros or cons or the API community's current direction.  It's a very poor steer for our customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core Web API help pages with Swagger / OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@spboyer  please review.

**Comment by spboyer** [comment]
@garethj-msft - thanks for the feedback here. Perhaps some dialog with @glennc and the team on messaging would help.

cc: @scottaddie @bradygaster

**Comment by dougbu** [comment]
The discussion of code- versus design-first doesn't fit in documentation of how to use the code-first features NSwag and Swagger produce. We may eventually document use of NSwag's ability to generate a controller from an OpenAPI description and maybe then it would make sense to mention design-first options.

/cc @bradygaster in case he wants to do something in the short term.

**Comment by bradygaster** [comment]
Though I agree @garethj-msft on the "design versus code-first" approaches, I also concur with @dougbu that design-first doesn't really fit into this documentation. This doc's goal is, explicitly, to introduce the notion of Open API/Swagger insomuch as Swashbuckle and NSwag are designed to enable the code-first approach. So, if you'd be interested in submitting a PR that would shore up this document's out-of-date terminology that you referenced, we'd be open to reviewing it. In terms of changing the direction of this document to guide folks to do API design first; that's orthogonal. 

Again - I agree that developers should be designing their APIs first, but many can't/won't. For those scenarios, tools like Swashbuckle and NSwag exist to generate the document from the code. This is that scenario, so I don't think we need to change this document whole-hog. I do support adding another document that discusses the need for proper API design, but that's not an ASP.NET doc item, it's more an architectural guidance doc item.

**Comment by garethj-msft** [comment]
Thanks for the conversation - I think maybe the primary point here is not to guide people to do one or the other but to acknowledge that there is a wider universe and that these are tools that live within one segment. Then its easy to link to well-chosen external reference material that discusses the choices rather than to explain the two inline here.   

That would lessen the tone of assertion that this use case is what OAS is for as opposed to one thing it is for.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
