### ISSUE TITLE
Violation of the principles of MVC

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#16014]
The comment below was machine translated

@aford9880 commented on [Wed Dec 04 2019](https://github.com/aspnet/AspNetCore.Docs.ru-ru/issues/65)

The expression "var movieGenreVM = new MovieGenreViewModel" in the controller does not violate the principles of MVC, creating a rigid binding of the controller action method to the model? Correct. please if i'm wrong. Thanks)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Добавление поиска в приложение MVC ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Wed Dec 04 2019](https://github.com/aspnet/AspNetCore.Docs.ru-ru/issues/65#issuecomment-561522311)

Hello, @aford9880
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The code is fine.
