### ISSUE TITLE
BlazorServer sample is missing minified bootstrap files.

### ISSUE THREAD

**Issue by anthcool** [aspnet/AspNetCore.Docs#16015]
@guardrex 

The BlazorServerSample located at aspnetcore/blazor/common/samples/3.x/ does not work correctly due to missing a dependency on Bootstrap for styling.  I get the following error in my dev tools in Chrome due to such.  Please add these into the sample when time permits.  Thanks!

![image](https://user-images.githubusercontent.com/5133304/70164206-fd066800-167d-11ea-8db9-277945835ab3.png)

**Comment by guardrex** [comment]
Hello @anthcool ... sure thing ... I'll take a look at that right now.

**Comment by guardrex** [comment]
Oh, yeah ... I see where things went badly. This is a relatively new sample, and it was built directly from the template. We want to try and avoid the whole repo becoming *gigantic* with styles, so the styles for the app were moved from the WebAssembly sample app (*site.css*) here. The link to the minified styles should be dropped here. I'll get this sorted out *right now*. I'll kill that link and confirm that *site.css* has all of the styles that the app requires. Thanks for catching this @anthcool! :rocket:

**Comment by anthcool** [comment]
Sweet deal!  Thank you!  You rock!  Appreciate your hard work and time.

**Comment by guardrex** [comment]
Reversing what I just said. 🤦‍♂ ... I see the **_real problem now!_** Looks like I'll need to explicitly allow the bootstrap file because we have a repo-wide gitignore rule to kill off minified assets. No worries ... I'll get that squared away.

**Comment by guardrex** [comment]
☝️ What I said earlier **does** apply to **most** of our samples. I often embed styles into sample apps into a `<style>` tag to avoid making samples big.
