### ISSUE TITLE
Needs More Info (Publish Includes Many Microsoft.CodeAnalysis.resources.dll)

### ISSUE THREAD

**Issue by cgountanis** [aspnet/AspNetCore.Docs#16028]
https://github.com/dotnet/core/issues/3895

**Comment by scottaddie** [comment]
I suspect this feature is working as designed. Roslyn assemblies (those prefixed with Microsoft.CodeAnalysis.*) were removed from the shared framework as of 3.0. Those assemblies are needed to support runtime view compilation.

Have you already tried adding a `Condition` to your package ref? For example:

```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.0" Condition="'$(Configuration)' == 'Debug'" />
```

/cc: @pranavkm

**Comment by cgountanis** [comment]
I will give that a try but it would be nice if it would automatically in Release mode not include those since there are no CSHTML changing on a production machine.

**Comment by scottaddie** [comment]
@pranavkm Do you have any other ideas?

**Comment by pranavkm** [comment]
> I will give that a try but it would be nice if it would automatically in Release mode not include those since there are no CSHTML changing on a production machine.

Conditionally referencing the package based on Configuration is the best option there is now.

**Comment by cgountanis** [comment]
Cool, trying it out. Do I have to do anything with the builder in the example or does it just work by adding properties to it? e.g. builder.AddRazorRuntimeCompilation();

**Comment by scottaddie** [comment]
I'm working on updating the doc right now. Here's a more complete example in the meantime: https://github.com/scottaddie/ContosoLending/blob/master/src/ContosoLending.Ui/Startup.cs#L31

**Comment by cgountanis** [comment]
Just a heads up before you gothrough all that work. I added Condition="'$(Configuration)' == 'Debug'" and the Startpp AddRazorRuntimeCompilation() still seems to be working in Release mode.

**Comment by scottaddie** [comment]
@cgountanis Did you also add the `Startup.ConfigureServices` change I mentioned above? That should prevent `AddRazorRuntimeCompilation` from executing in Release mode.

**Comment by cgountanis** [comment]
Will do just wanted to test it it parts.

**Comment by cgountanis** [comment]
Ahhh, once I cleared out the /BIN folder it did give me the expected error ''IMvcBuilder' does not contain a definition for 'AddRazorRuntimeCompilation'". Just had those old files in there fooling me :)

**Comment by cgountanis** [comment]
I am currently using AddControllersWithViews() not AddRazorPages(), assuming I can just add the  DEBUG logic for the AddRazorRuntimeCompilation() or should I change the way I am setting up. This is a basic MVC with EndPoints on Core 3.1, pretty much converted everything but I am still leaning on Razor pages for my CSHTML Views.

BTW, thanks for the help on this!

**Comment by cgountanis** [comment]
Maybe add both, jsut never needed AddRazorPages() before. Good practice to add all?

![image](https://user-images.githubusercontent.com/14899817/70259472-ddda0a00-1753-11ea-84f4-e6c5b1147531.png)

**Comment by scottaddie** [comment]
It sounds like there's no need for you to call `services.AddRazorPages();`. Call `services.AddControllersWithViews();` instead. You would only need the `AddRazorPages` method call if you have Razor Pages files (those *.cshtml files which are most often stored in a *Pages* directory and that contain an `@page` directive as the first line in the file).

**Comment by cgountanis** [comment]
OK, seems to be working, in the end I ended up with this:

```
        public void ConfigureServices(IServiceCollection services)
        {
            IMvcBuilder builder = services.AddControllersWithViews();

#if DEBUG
            builder.AddRazorRuntimeCompilation();
#endif
...
```

I did not include the `if (Env.IsDevelopment())` as I did not want to deal with the global Env injection/variable. Not really needed for what I am doing.

**Comment by cgountanis** [comment]
I can confirm with the settings above, might be slightly different for various setups, MVC/Pages/Blazor but overall the Publish - Configuration: Release, now does NOT include all those debug files in the published file output.

I still think there has to be an easier way down the road but for now, this does work.

Thank you!
