### ISSUE TITLE
EventLog

### ISSUE THREAD

**Issue by dcp12345678** [aspnet/AspNetCore.Docs#16021]
In your first code example, you provide an example of logging using AddEventLog, but you never indicate *where* in the event log the message gets written.  I've yet to be able to find the message in the event log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's described in the provider section :point_right: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#windows-eventlog-provider

**Comment by dcp12345678** [comment]
I found the message.  Thanks.  It might be good to just add a sentence to this doc saying that by default, the message goes to the "Application" section of Windows Logs, along with a screenshot.

**Comment by guardrex** [comment]
I don't think that we can guarantee that ...

https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.EventLog/src/WindowsEventLog.cs#L18

... `logName` isn't set in stone.

**Comment by guardrex** [comment]
Yeah ...

https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.EventLog/src/EventLogSettings.cs#L16

... we could say "default" ... that's cool. @Rick-Anderson, I'm chill'in waiting for Blazor reviews, so you can assign me if you want.

**Comment by guardrex** [comment]
... and call out the defaults for `SourceName` and `MachineName` as well!

**Comment by guardrex** [comment]
I'm going to go ahead ..... I've already worked up the PR. :smile:
