### ISSUE TITLE
override app configuration using azure leaves some things ambiguous

### ISSUE THREAD

**Issue by drdamour** [aspnet/AspNetCore.Docs#16025]
in this section it says "When an app uses the Generic Host, environment variables aren't loaded into an app's configuration by default and the configuration provider must be added by the developer."

but in which cases IS the vars loaded into the app's configuration by default?

changing this sentence to indicate the cases they are auto loaded would make it clearer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-3.1&tabs=visual-studio#override-app-configuration-using-the-azure-portal)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @drdamour ... That section of text is antiquated. I think it goes back to before 3.0 GA. That's before the formal release of the Generic Host. Back in those days (2.2), the Generic Host didn't have a `CreateDefaultBuilder` method to call for building out a default host and adding providers for you, such as the Environment Variable Configuration provider ...

https://github.com/aspnet/Extensions/blob/ef5d488c054c3aa850c29c10d851fcdc8a004eed/src/Hosting/Hosting/src/Host.cs#L86

... back in those days, you really did have to add the providers yourself in dev code.

@bradygaster, if ur busy and want me to take this one, you can assign me, and I'll ping u for review on the PR.
