### ISSUE TITLE
C# language version

### ISSUE THREAD

**Issue by tasop-rsconnect** [aspnet/AspNetCore.Docs#16047]
I found that changing TargetFramework to netcoreapp3.1 somehow downgraded the C# version. I got several errors about features not available in C# 7.3.
Adding the below in .csproj fixed that:

  &lt;PropertyGroup&gt;
    &lt;LangVersion&gt;8.0&lt;/LangVersion&gt;
  &lt;/PropertyGroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b7135b-b7a0-2fba-b846-530480aeb415
* Version Independent ID: 69e5b8fb-04e0-817e-434f-72cf6ba12923
* Content: [Migrate from ASP.NET Core 3.0 to 3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/30-to-31.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/30-to-31.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Aetheria** [comment]
Got the same error. It's strange that you have to set this explicitly.

**Comment by Rick-Anderson** [comment]
@tasop-rsconnect  @Aetheria provide the smallest project that reproduces this issue, preferable on GitHub. I'm not able to reproduce this problem.

[.NET Core 3.0 adds support for C# 8.0.](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0) and 3.1 hasn't changed that.

cc @BillWagner @scottaddie

**Comment by tasop-rsconnect** [comment]
It turns out that this was a result of VS not being the latest version (16.4). I was mistaken about having upgraded to it.
