### ISSUE TITLE
Needs the step for the Microsoft.AspNetCore.Authentication.Twitter Nuget Package

### ISSUE THREAD

**Issue by enkodellc** [aspnet/AspNetCore.Docs#16052]
At the top of this document you should put the step that people need to include the Nuget Package. You do this on the Facebook documentation but not on Twitter.

> Add the Microsoft.AspNetCore.Authentication.Twitter NuGet package to the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external sign-in setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #13300

**Comment by Rick-Anderson** [comment]
@wadepickett  can you get that added today? You don't need to do  #13300 today.

**Comment by wadepickett** [comment]
OK, I will get this done today, thanks.  I am also assigned to get getting over 11K SEO issues sorted out for all .NET areas at the moment so have been jumping back and forth a bit, sorry.  Let me get this Twitter one though, I want to finish it, thanks.

**Comment by Rick-Anderson** [comment]
@wadepickett  early next week is OK.

**Comment by wadepickett** [comment]
Updating for 3.0 twitter auth Nuget package right now so it matches the 3.0 overview and starter project, publishing, then updating to 3.1 for overview and rest of social auth afterwards.   The RTW 3.1 Twitter package just released requires ASP.NET Core 3.1
