### ISSUE TITLE
global change

### ISSUE THREAD

**Issue by guanghuawu** [aspnet/AspNetCore.Docs#16066]
Where and how to make a global change across the whole project of _context.Student to _context.Students.?There are 8 occurrences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That was only necessary in a previous version. What version are you following. YOu make the change with any editor.

**Comment by guanghuawu** [comment]
Thank you so much for your quick response. I use Visual Studio version3.1.0, the latest version. I have tried this tutorial for several times and all failed.

**Comment by Rick-Anderson** [comment]
>Where and how to make a global change across the whole project of _context.Student to _context.Students.?There are 8 occurrences.

Where does the 3.1 version say to do that?

**Comment by prbrowne** [comment]
Since an entity set contains multiple entities, the DBSet properties should be plural names. Since the scaffolding tool created aStudent DBSet, this step changes it to plural Students.

To make the Razor Pages code match the new DBSet name, make a global change across the whole project of _context.Student to _context.Students. There are 8 occurrences.


SO WHERE ARE THE 8 CHANGES NEEDED????

**Comment by Rick-Anderson** [comment]
@guanghuawu  that was fixed several versions ago.
