### ISSUE TITLE
Complete list of validation attributes

### ISSUE THREAD

**Issue by xenophilios** [aspnet/AspNetCore.Docs#16068]
In the section "Built-in attributes" the article says that "A complete list of validation attributes can be found in the System.ComponentModel.DataAnnotations namespace". I followed the link, but couldn't find the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/70378188-bd2fc280-18c1-11ea-8c3c-ea20d44ff087.png)
