### ISSUE TITLE
Scaffolding a controller on Mac

### ISSUE THREAD

**Issue by williamnoble** [aspnet/AspNetCore.Docs#16077]
In order for my scaffold to succeed on Mac I had to remove the Nuget Package Microsoft.VisualStudio.Web.CodeGeneration.Design (version 3.1.0) and then re-install as version 3.0.0, in case anyone else has issues. Prior to this, it would fail with error 'Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Web.CodeGeneration.Utils, Version=3.1.0.0, Culture=neutral'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Try this just to make sure that cached packages aren't to blame:

1. Reset the version of that package to `3.1.0`.
2. Clear the package cache by executing [dotnet nuget locals all --clear](https://docs.microsoft.com/dotnet/core/tools/dotnet-nuget-locals) in a Terminal console.
3. Restore and build the project again.

If you still get the same exception, open an issue over at https://github.com/aspnet/Scaffolding/issues.

**Comment by krbrennan** [comment]
I also had issues with VS2019 on my mac. I was unable to create a project with framework 3.1, so I built one using framework 3.0. When the project was created I right-clicked on the TodoApi file in the tree, then Tools, then Edit File. In the file I simply modified the line:

<TargetFramework>netcoreapp3.0</TargetFramework>

TO:

<TargetFramework>netcoreapp3.1</TargetFramework>

and I stopped running into weird compatibility issues when the rest of the project used 3.1 dependencies.

**Comment by Rick-Anderson** [comment]
> I was unable to create a project with framework 3.1, 

Can you create one from the command line?

```
dotnet new webapi -o TodoApi
cd TodoApi
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet add package Microsoft.EntityFrameworkCore.InMemory
```

If you can repro this problem from VS Mac

**Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)

**Comment by krbrennan** [comment]
Rick-Anderson -- I confirmed through use of the commands you supplied that my inability to create a project using 3.1 is limited to creating a project with the VS2019 GUI, and I submitted feedback as you suggested. Thank you for the help.
