### ISSUE TITLE
Add note for Swagger 2.0 versus OpenAPI 3.0.x

### ISSUE THREAD

**Issue by mprabhu11** [aspnet/AspNetCore.Docs#16070]
The steps as described above will generate the API spec in OpenAPI version 3.0.x format. 
This will not work if the consuming tools do not yet support that format (e.g., PowerApps/Flows custom connector setup). 
The following code can be used to generate Swagger 2.0 instead of OpenAPI 3.0 metadata:
            //use this instead of just app.UseSwagger() in Configure() above...
            app.UseSwagger(c =&gt;
            {
                c.SerializeAsV2 = true;
            });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16195
