### ISSUE TITLE
Does not work on MAC

### ISSUE THREAD

**Issue by jjxtra** [aspnet/AspNetCore.Docs#16079]
Not sure if this was tested on MAC, but I just get a blank Loading... screen, this is latest MAC with latest VS 2019 and .NET core SDK 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by jjxtra** [comment]
It works if I dotnet build and then dotnet run from terminal. If I try to run from within visual studio, I get an error that the .exe file is not found, weird because I'm on a MAC...

**Comment by guardrex** [comment]
Which hosting model are you using? Blazor Server should work. Blazor WebAssembly isn't supported in VS4Mac yet.

**Comment by jjxtra** [comment]
Just FYI I can run the client only Blazor on MAC from terminal using dotnet run.
