### ISSUE TITLE
Link .NET Core 3.0 SDK or later must point to the latest download

### ISSUE THREAD

**Issue by ionyshch** [aspnet/AspNetCore.Docs#16088]
Link ".NET Core 3.0 SDK or later" is https://dotnet.microsoft.com/download/dotnet-core/3.0 that has 3.0.1 version while the latest is 3.1 which is correctly pointed to in output of "dotnet --info" and is
https://dotnet.microsoft.com/download - has 3.1.
This is important, because having 3.0.1 then leads to failure install EF framework on the next step of tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> This is important, because having 3.0.1 then leads to failure install EF framework on the next step of tutorial.

It works fine with `3.0.100`

**Comment by ionyshch** [comment]
I couldn't make it work with 3.0.101 as "dotnet tool install --global dotnet-ef" attempted installing EF version 3.1 (the latest version available) which failed complaining about incompatibility with 3.0.101 SDK.
