### ISSUE TITLE
SharedResources on ASP.NET Core 3.0 Project not working after updating Visual Studio to v16.4.0

### ISSUE THREAD

**Issue by pocki** [aspnet/AspNetCore.Docs#16083]
Since updating Visual Studio to v16.4.0 the SharedResources Keys are not found anymore in  ```IHtmlLocalizer<SharedResource>``` my ASP.NET Core 3.0 MVC WebApp. When the ASP.NET Core 3.0 App gets compiled with Azure Pipeline Hostest Windows-2019 Agent (actual running Visual Studio v16.9.x) it is running and working as expected.

I use CookieRequestCultureProvider, and Cookies are set und read correctly.

**What I tried after Visual Studio Update without success:**
* Reinstall .NET Core SDK v3.0.101 (which gets uninstalled at Visual Studio update)
* Create global.json with: 
```
{
  "sdk": {
    "version": "3.0.100"
  }
}
```
* Clean and Rebuild multiple times, manually deleting /bin and /obj folders
* Cleared cookies and Browser Caches
* Restarting Windows and restarting Visual Studio multiple times

**Expected Behavior**:
SharedResource Keys are found with ```IHtmlLocalizer<SharedResource>``` and localization is used. It also works with Azure Pipeline and Hosted Agent Windows-2019 Image

**Actual Behavior**:
SharedResource Keys are not found with ```IHtmlLocalizer<SharedResource>```

```
@inject IHtmlLocalizer<SharedResource> Localizer
Localizer["ExistingResourceKey"].IsResourceNotFound // is true
```

**Version Used**: 
OS: Windows Server 2016 x64 (all Updates installed)

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Microsoft Visual Studio Enterprise 2019
Version 16.4.0
VisualStudio.16.Release/16.4.0+29519.181
Microsoft .NET Framework
Version 4.8.03761

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)

Include steps to reproduce the bug

**Comment by pocki** [comment]
Correct, is a bug somewhere else:  dotnet/sdk#4033
