### ISSUE TITLE
Incorrect namespace in RazorPageMovieContext.cs

### ISSUE THREAD

**Issue by ionyshch** [aspnet/AspNetCore.Docs#16090]
Example says 
namespace RazorPagesMovie.Models
which leads to an error when adding
using RazorPagesMovie.Data to Startup.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/70462011-17658a80-1a5e-11ea-818c-1e76ad4a35c7.png)

cc @imba-tjd

**Comment by CGrijalva90** [comment]
I have the same issue, I was able to scaffold the model but when updating `Startup.cs` there is a missing namespace name for MovieContext. In my RazorPagesMovieContext.cs file, am I supposed to change the namespace there? I'm not following your picture, could you clarify a little more? 

Thanks
