### ISSUE TITLE
Example for client side vaidation

### ISSUE THREAD

**Issue by wksub** [aspnet/AspNetCore.Docs#16115]
I'm missing an example for implementing jqurey unobtrusive validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's covered over at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#client-side-validation ... and in the sections that follow.
