### ISSUE TITLE
Update for .NET Core 3.1

### ISSUE THREAD

**Issue by jawn** [aspnet/AspNetCore.Docs#16114]
E.g. section "Deploy ASP.NET Core 3.0 to Azure App Service" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.1&tabs=visual-studio#deploy-aspnet-core-30-to-azure-app-service)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by jawn** [comment]
See https://github.com/Azure/app-service-announcements/issues/217

**Comment by guardrex** [comment]
@bradygaster This is a fairly minor one, and I can work it as well if you like ... assign me if you want. I think we mostly need to make a handful of remarks generic wrt the version (e.g., say "3.x" over "3.0" or even better, speak to versions generally such that the content will apply even further out than 3.1 ... to 5.0 and beyond).
