### ISSUE TITLE
Consider cleaning up the "How CORS works" section

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore.Docs#16113]
It makes sense to start a document about CORS with an explanation of what it is and how it works, it makes sense to move "How CORS works" to be the first section in the page.

On the other hand, this page is about configuring and testing CORS in ASP.NET Core, so perhaps it would be better to move the explanation to a separate page and just link to that one from here.

On someone else's hand, this page already links to the MDN explanation of CORS; is there any value in duplicating that information here?

Depending on what's decided, you should also consider removing some of the bullet points in the opening paragraph, as they are duplicated in "How CORS works".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#how-cors-works)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, we'll review this on the next doc sweep. We don't have the resources to invest in it now.
