### ISSUE TITLE
Combining conventions with explicit use of ProducesResponseType

### ISSUE THREAD

**Issue by Leon99** [aspnet/AspNetCore.Docs#16136]
Conventions is a great idea and want to use it, but I still want to specify ProducesResponseType on the controller class to cater for methods not included in the conventions. When I do it, conventions don't seem to apply. How do I combine both? There surely must be a way, conventions unlikely to be used as the sole source of the metadata.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Per the doc:
Web API conventions are a substitute for decorating **individual actions** with `[ProducesResponseType]`.

**Comment by Leon99** [comment]
Per my question:
I still want to specify ProducesResponseType on the **controller class** to cater for methods not included in the conventions

Is it possible to define class-level conventions, or is there another way to get the same functionality as I get by applying `[ProducesResponseType]` on a class while using conventions for individual methods?
