### ISSUE TITLE
Blazor Windows Authentication on Kestrel works locally only

### ISSUE THREAD

**Issue by nkw** [aspnet/AspNetCore.Docs#16138]
# Blazor Windows Authentication on Kestrel works locally only

https://stackoverflow.com/questions/59204346/blazor-windows-authentication-on-kestrel-works-locally-only-an-anonymous-reques

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
V3.0
V3.1
```
</details>

**Comment by guardrex** [comment]
Hello @nkw ... I see a few issues for WinAuth that they're investigating ...

* https://github.com/aspnet/AspNetCore/issues/17025
* https://github.com/aspnet/AspNetCore/issues/17467

Recommend opening an issue with them. Post the full content tho (i.e., don't cross-link to SO) perhaps with a repro project on GH cross-linked for them to look at.

If you/they work out critical advice that differs from our WinAuth guidance, open a new issue using the **This Page** feedback button+form at the bottom of the Blazor Authentication and Authorization topic. We can add a section that calls out anything specific to Blazor.
