### ISSUE TITLE
Step Install-Package "Microsoft.EntityFrameworkCore.Design" was required

### ISSUE THREAD

**Issue by surfmuggle** [aspnet/AspNetCore.Docs#16130]
In the step "New Scaffolded Item" i got an error that "Microsoft.EntityFrameworkCore.Design" was missing. Adding it with the package manager console: "Install-Package Microsoft.EntityFrameworkCore.Design -Version 3.1.0" fixed the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you doing the VS or VSC instructions? VS should add that for you. If not, it's a VS bug. The VSC instructions have you add that.
