### ISSUE TITLE
Regarding supported platforms

### ISSUE THREAD

**Issue by DrGriff** [aspnet/AspNetCore.Docs#16141]
From the section https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.1#supported-platforms

"Deploy a 32-bit app with a 32-bit (x86) .NET Core SDK unless the app....."

Does this suggest that 32 bit is preferred over 64 bit for performance?  I know that Visual Studio is 32 bit for this reason (https://blogs.msdn.microsoft.com/ricom/2015/12/29/revisiting-64-bit-ness-in-visual-studio-and-elsewhere/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.1#supported-platforms)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DrGriff ... No, just for the reasons listed there. This question came up, so I asked, and that's what they said. They didn't indicate anything about perf.
