### ISSUE TITLE
Explain what "IE padding means"

### ISSUE THREAD

**Issue by jeremyVignelles** [aspnet/AspNetCore.Docs#16144]
In the Exception handler lambda example, there is this line:

```cs
await context.Response.WriteAsync(new string(' ', 512)); // IE padding
```

Is it needed? What does it do? Does it still make sense in 2019 (almost 2020)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-lambda)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Not needed. Author used it to get what he considered better output.

**Comment by jeremyVignelles** [comment]
I've found this : https://perishablepress.com/important-note-for-your-custom-error-pages/

Apparently, it's a trick to make IE show the page you send it, rather than a default error page made by IE.

Would it make sense to document that for those who were wondering?

**Comment by Rick-Anderson** [comment]
Good idea. Although IE usage is low and getting lower.

**Comment by Rick-Anderson** [comment]
@jeremyVignelles  thanks for posting that link.

**Comment by jeremyVignelles** [comment]
Since this issue is linked to the documentation page, I'm adding [that other link]( https://core.trac.wordpress.org/ticket/8942) I found from wordpress about that very issue. It seems that the size below which the issue is triggered is expressed in bytes after compression ( I mean that if you have a total of 512 plain text bytes, once encrypted, you will likely have less bytes)
