### ISSUE TITLE
Multiple Cookie authentication

### ISSUE THREAD

**Issue by Frankofoedu** [aspnet/AspNetCore.Docs#16156]
I edited the sample page to add another cookie which is supposed to redirect to a second login page. 

It keeps going back to the VS generated Index page.

 ```
services.AddAuthentication()
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie("Admin", o =>
                {
                    o.Cookie.HttpOnly = true;
                    o.ExpireTimeSpan = TimeSpan.FromMinutes(15);
                    o.LoginPath = "/Account/TestLogin";
                    o.SlidingExpiration = true;
                    o.Cookie.IsEssential = true;
                });
  services.AddAuthorization(options =>
            {
                var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(CookieAuthenticationDefaults.AuthenticationScheme,"Admin");
                defaultAuthorizationPolicyBuilder =
                    defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
                options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
            });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you phrase this as what's wrong with the doc and what needs to be fixed?

**Comment by Rick-Anderson** [comment]
moved to Master issue for: Authorize with a specific scheme #16190

**Comment by HaoK** [comment]
There's not enough info here to see exactly what's going on but generally this is most likely due to the challenge going to the normal cookie, you would need to challenge("Admin") to see a redirect to the admin login

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
