### ISSUE TITLE
Example for ApiConventionNameMatchBehavior.Any?

### ISSUE THREAD

**Issue by Leon99** [aspnet/AspNetCore.Docs#16152]
An example of using ApiConventionNameMatchBehavior.Any would be good. Simply doing 
```
[ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
public static void Any(params object[] _) { }
```
doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/AspNetCore.Docs/issues/10954
`ApiConventionNameMatchBehavior.Any` only makes sense on params, not methods.

**Comment by Leon99** [comment]
That sounds contradictory to the documentation for `ApiConventionNameMatchBehavior.Any`:

_Matches any name. Use this if the parameter or **method name** does not need to be matched._

Should the documentation be amended?

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/DefaultApiConventions.cs#L37-#L39

**Comment by Rick-Anderson** [comment]
> Should the documentation be amended?

API changes are only made to source code /// comments.

**Comment by Rick-Anderson** [comment]
@pranavkm

Matches any name. Use this if the parameter ~or method name~ does not need to be matched.
This doesn't work on methods does it?

Should I do a PR on https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ApiExplorer/ApiConventionNameMatchBehavior.cs#L12

**Comment by VictorioBerra** [comment]
I do not think it works on methods:

IE:

```csharp
    public static class CustomApiConventions
    {
        [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
        [ProducesResponseType(418)]
        public static void ABCTEST()
        {
            
        }
```

Would NOT get applied to:

```csharp
        [HttpPost(Name = "CreateProduct")]
        public Product Create([FromBody, Required]Product product)
        {
            return product;
        }
```

Also, I think you CCed the wrong person @Rick-Anderson but I checked anyway.

**Comment by Rick-Anderson** [comment]
@VictorioBerra  I cc'd you from #10954 :)
