### ISSUE TITLE
This is not valid for Core 3.0 "MVC passes an instance of AuthorizationFilterContext in the Resource property"

### ISSUE THREAD

**Issue by yahorsi** [aspnet/AspNetCore.Docs#16155]
Hi, since .NET Core 3.0 this is not valid anymore:

For example, MVC passes an instance of AuthorizationFilterContext in the Resource property. This property provides access to HttpContext, RouteData, and everything else provided by MVC and Razor Pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#accessing-mvc-request-context-in-handlers)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by damienbod** [comment]
I did a blog about how to do this now in 3.0 onwards. This might help maybe

https://damienbod.com/2019/12/02/using-http-request-routes-request-body-and-query-string-parameters-for-authorization-in-asp-net-core/

Greetings Damien

**Comment by serpent5** [comment]
This looks like #12564 and #15263. There’s some discussion in #15218.

**Comment by Rick-Anderson** [comment]
Moved to #16191
