### ISSUE TITLE
Please update the document as per .net core 3.1

### ISSUE THREAD

**Issue by KamranShahid** [aspnet/AspNetCore.Docs#16161]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows should be updated as per .net core 3.1

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
@KamranShahid  this is a dup of  #13877

**Comment by KamranShahid** [comment]
> @KamranShahid this is a dup of #13877

Thanks @Rick-Anderson for letting me know that this is already highlighted. 
But it is seem to be marked for **2020 sometime**
https://github.com/aspnet/AspNetCore.Docs/projects/54#card-30503512
I thought it is quite misguiding. e.g i have read somewhere that  
services.AddMvc()   and app.UseMvc(); are not recommended in .net core 3.1

Please correct me if i am wrong about that

**Comment by Rick-Anderson** [comment]
Yes
