### ISSUE TITLE
JsonResult missing?

### ISSUE THREAD

**Issue by andrepiresrep** [aspnet/AspNetCore.Docs#16176]
Hello, in the Add Newtonsoft.Json-based JSON format support section of this page, it is mentioned that we should use JsonResult on the following code, where it says: Output serialization options, on a per-action basis, can be configured using JsonResult. For example:
public IActionResult Get()
{
    return Json(model, new JsonSerializerSettings
    {
        options.Formatting = Formatting.Indented,
    });
}
Shouldn't it be JsonResult instead of return Json in the code?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Json is a method that creates a JsonResult https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller.json?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_Controller_Json_System_Object_System_Object_
