### ISSUE TITLE
Blazor doc node should not show up for 2.2

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#16181]
![image](https://user-images.githubusercontent.com/1874516/70824866-fff90b00-1d97-11ea-9a33-795a118916cb.png)

**Comment by guardrex** [comment]
@scottaddie This seems to be caused by ...

```
- name: Samples
  href: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor
```

What's the solution? Given that the sample apps are well cross-linked in the Blazor topics, we could remove that "Samples" link to solve this. 🤞 Is that the right fix?

**Comment by Rick-Anderson** [comment]
@guardrex  I think it's a good idea to remove the samples link even without this problem.

**Comment by guardrex** [comment]
Scott added it on https://github.com/aspnet/AspNetCore.Docs/pull/14499.

... idk if he has a way around the problem or if he felt it was super important. He may have a ✨ *DocTrick*:tm: ✨ to fix it.
