### ISSUE TITLE
Confusing Obsoleting Package - Microsoft.AspNetCore.Mvc.Razor

### ISSUE THREAD

**Issue by rebelweb** [aspnet/AspNetCore.Docs#16187]
I use the Microsoft.AspNetCore.Mvc.Razor package for the IRazorViewEngine interface. This document states the package is no longer being produced, but document at https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.irazorviewengine?view=aspnetcore-3.1, says it is available in asp.net core 3.0 & asp.net core 3.1. I can include the package Microsoft.AspNetCore.Mvc.Razor at the 2.2 version and seems to build okay is this correct, or have these APIs moved elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Right, it's not a NuGet package. You get it from the Framework.

**Comment by rebelweb** [comment]
If I remove the package, it no longer finds the interface was it renamed?

**Comment by Rick-Anderson** [comment]
No it was not. What version of ASP.NET Core are you using? I'm asking because you mentioned 2.2

**Comment by rebelweb** [comment]
I am upgrading to 3.0. I figured out my issue, The project SDK was pointed at Microsoft.NET.Sdk.Razor instead of Microsoft.NET.Sdk.Web. Thank You for your help.
