### ISSUE TITLE
RCL docs should explain information about components

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#16189]
[EDIT by guardrex to update the metadata]

The RCL doc says a lot about Razor Pages and Razor Views for MVC.

It doesn't say a whole lot about adding components. We should have a section here that explains that you can use RCL for components, and what exactly is required (project file, `@using Microsoft.AspNetCore.Components.Web`). This is feedback from https://github.com/aspnet/AspNetCore/issues/17809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b02665-c8ab-bd91-8057-3b07b4e238d3
* Version Independent ID: e4f176f5-0b94-d532-53d5-cffce437961a
* Content: [Razor components class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/class-libraries.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@rynowak We have a topic in the Blazor TOC for it (and the original comment came in from that, so the reader was looking in the right spot for help) ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&tabs=visual-studio 

I'll modify the metadata to point to that one for these updates.
