### ISSUE TITLE
This doesn't work at all

### ISSUE THREAD

**Issue by dave0783** [aspnet/AspNetCore.Docs#16188]
Registering 2 authentication schemes and passing 2 different bearer tokens always yields the default scheme being called

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Looks like a dup of #16156  and #12177

**Comment by dave0783** [comment]
@Rick-Anderson so is there no fix for this?

**Comment by Rick-Anderson** [comment]
@dave0783  I've ping the engineering team in the master issue.
