### ISSUE TITLE
Clean way to guard routing

### ISSUE THREAD

**Issue by hoksource** [aspnet/AspNetCore.Docs#16192]
Is there a clean way to guard specific events when user goes to a specified route. I want to be able to prevent users from accessing a set of page or redirect users to another page if a condition is met. I'm looking for something like
- angular routing guards
- or razor pages filters
- or page component base class that triggers onRoutingToPage
- or onRoutingToLayout (this applies for all pages under it)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/aspnetcore#18425
