### ISSUE TITLE
How to set affinity configuration

### ISSUE THREAD

**Issue by alefcarlos** [aspnet/AspNetCore.Docs#16197]
I didn't see any information about how do we configure affinity. Should we use cookie? If so, which cookie name should I use? Or should we use header ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
See https://blogs.msdn.microsoft.com/benjaminperkins/2016/06/03/setting-application-request-routing-arr-affinity-for-your-azure-app-service/

**Comment by alefcarlos** [comment]
@Rick-Anderson , when I'm not using Azure signalR, how could I setup. I'm deploying it in k8s using Istio. And I need to know which header/cookie name I need to setup.
