### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by ihorbond** [aspnet/AspNetCore.Docs#16208]
Followed tutorial step by step but when pasted code for client into Program.cs it seems the build process didn't generate types based on .proto so line 
var client = new Greeter.GreeterClient(channel);
breaks saying Greeter is could not be found. Same with HelloRequest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by hjy1210** [comment]
@ihorbond

I ran into the same problem.

After inspect the GrpcGreeterClient.csproj, I found a strange node as follows:
```
<ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
</ItemGroup>
```
After delete it, rebuild the project, the problem is gone.

**Comment by ihorbond** [comment]
> @ihorbond
> 
> I ran into the same problem.
> 
> After inspect the GrpcGreeterClient.csproj, I found a strange node as follows:
> 
> ```
> <ItemGroup>
>     <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
> </ItemGroup>
> ```
> 
> After delete it, rebuild the project, the problem is gone.

Thanks but I think you actually need it. GrpcServices value must equal “Client” on the client side though. My problem was I accidentally added it twice in server and none on the client so was totally my fault

**Comment by hjy1210** [comment]
@ihorbond
Yes, I do have
```
  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
  </ItemGroup>
```
on Client side.

**Comment by mawaru29** [comment]
I ran into the same issue as well. Has anyone else seen this?
