### ISSUE TITLE
Namespace update

### ISSUE THREAD

**Issue by ihorbond** [aspnet/AspNetCore.Docs#16207]
Shouldn't it say GrcpGreeterClient namespace ? 
Create the Greeter client
Build the project to create the types in the GrpcGreeter namespace. The GrpcGreeter types are generated automatically by the build process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
The namespace is correct.

**Comment by ihorbond** [comment]
Right, it is because we pasted .proto from server project where namespace was GrpcGreeter. In client project the namespace is GrpcGreeterClient though so in my opinion it'd make sense to update option csharp_namespace to GrpcGreeterClient in client's .proto
