### ISSUE TITLE
register AuthorizationHandler with EF and use it in AddPolicy

### ISSUE THREAD

**Issue by alexey-formalmethods** [aspnet/AspNetCore.Docs#16205]
Can you provide any example of registering the AuthorizationHandler and using it in AddPolicy() method?

You also mention, that "Handlers that use Entity Framework shouldn't be registered as singletons.". I have the exact case, how to work with it?

Here is my handler, where I want to inject HttpContextAccessor:
```
public class CustomRequirement : AuthorizationHandler<CustomRequirement>, IAuthorizationRequirement
    {
        private readonly IHttpContextAccessor httpContextAccessor;
        public CustomRequirement(IHttpContextAccessor httpContextAccessor)
        {
            this.httpContextAccessor = httpContextAccessor;
        }
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, CustomRequirement requirement)
        {
            //my code using Entity Framework here
        }
    }
```
Here is my ConfigureServices. So how to add there Authorization with Policy, using my AuthorizationHandler?
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpContextAccessor();
            services.AddAuthorization(options =>
            {
                options.AddPolicy("Custom",
                    policy => policy.Requirements.Add([ How to add here the instance of my handler??? ]));
            });
            services.AddControllers();
        }
```

**Comment by guardrex** [comment]
Hello @alexey-formalmethods ... You'll get a faster response (a little bit faster), if you close this and re-open it using the **This page** feedback button+form at the bottom of the topic. It will open an issue with metadata that automatically pings the author.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
