### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Google -Version 3.1.0

### ISSUE THREAD

**Issue by anandnandagiri** [aspnet/AspNetCore.Docs#16203]
[Enter feedback here]

Install-Package Microsoft.AspNetCore.Authentication.Google -Version 3.1.0
Steps mentioned is not working with ASP.NET Core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try `Install-Package Microsoft.AspNetCore.Authentication.Google`

**Comment by micro-belgium-application** [comment]
https://www.nuget.org/packages/Google.Apis.Auth.AspNetCore3/1.43.0-beta01
