### ISSUE TITLE
SignalR User specific hub.

### ISSUE THREAD

**Issue by arsalan0312** [aspnet/AspNetCore.Docs#16218]
This is an example Regarding signalR ,It has no explanation of these fuctions "Clients.User(user).SendAsync("ReceiveMessage", message)"
and yet no implementation as well ,just only three features were implemented ,
The purpose of an example project like this is to showcase the all the availible functions
Please add the implementation of the user specific notification.

URL of project is given below.

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/groups/sample

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
