### ISSUE TITLE
ValidateModelAttribute example typo error

### ISSUE THREAD

**Issue by ozkank** [aspnet/AspNetCore.Docs#16215]
[There is a typo end of the ValidateModelAttribute example on the ASP.NET CORE 3.0 doc page. You should add one more square bracket.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ozkank ...  I don't see what you're referring to. Could you screenshot it for us? Drag the image file right into a comment on this issue.

**Comment by ozkank** [comment]
Hi @guardrex 
You can find here. 
![image](https://user-images.githubusercontent.com/5203386/70905864-10b6b480-2016-11ea-8b3e-cbab7158e159.png)
Url : https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.0

**Comment by guardrex** [comment]
**_OH!_** lol :smile: ... you said "bracket," so the brace didn't register. I was just saying on another issue that I need to brew some ☕️!!! I'll do that.

Ok ... I'll fix this up right now. Thanks for calling it out.

**Comment by guardrex** [comment]
That was done on purpose to show two code snippets from the same source without using in-text code blocks. Code snippet named `snippet` ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters/sample/FiltersSample/Filters/ValidateModelAttribute.cs

Thanks for mentioning it tho. Always best to take a look and confirm.
