### ISSUE TITLE
The code sample in the Basic usage requires some adjustment...

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore.Docs#16213]
Calling JsonSerializer.DeserializeAsync with only one parameter is not enough. The code is executed, but the result is wrong. You should provide a second parameter:  JsonSerializerOptions . The following works for me: 
` await JsonSerializer.DeserializeAsync
                                 &lt;WeatherForecast[]&gt;(responseStream, 
                                 new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase }); 
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @enetstudio ... by "result is wrong" you just mean that camel case isn't used, correct?

The fix is probably to cross-link the topic that covers it at ...

https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to

**Comment by guardrex** [comment]
I see. We did an update recently on samples to 3.1 without manually checking due to 🏃😅 being crazy busy. It's likely that the API changed there. I'll *try again!* 🤦‍♂

**Comment by guardrex** [comment]
@enetstudio ... I'm not having a problem here. Seems ok ...

<img width="239" alt="Capture" src="https://user-images.githubusercontent.com/1622880/70937166-76e90a80-2009-11ea-8fa8-5c0cc3f0eeb4.PNG">

**Comment by guardrex** [comment]
You passed an array and not an interface. I think the overload is different. We don't document all of them for every scenario supported. As long as the sample runs as shown for the scenario shown and the overload that you need works in your scenario, we're ok here. All of the overloads are actually documented in the API docs ...

https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer

**Comment by enetstudio** [comment]
OK, I understand, thank you...
