### ISSUE TITLE
register AuthorizationHandler with HttpContextAccessor and EF and use it in AddPolicy

### ISSUE THREAD

**Issue by alexey-formalmethods** [aspnet/AspNetCore.Docs#16211]
Can you provide any example of registering the AuthorizationHandler with HttpContextAccessor and using it in AddPolicy() method?

You also mention, that "Handlers that use Entity Framework shouldn't be registered as singletons.". I have the exact case, how to work with it?

Here is my handler, where I want to inject HttpContextAccessor:

```
public class CustomRequirement : AuthorizationHandler<CustomRequirement>, IAuthorizationRequirement
    {
        private readonly IHttpContextAccessor httpContextAccessor;
        public CustomRequirement(IHttpContextAccessor httpContextAccessor)
        {
            this.httpContextAccessor = httpContextAccessor;
        }
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, CustomRequirement requirement)
        {
            //my code using Entity Framework here
        }
    }
```
Here is my ConfigureServices. So how to add there Authorization with Policy, using my AuthorizationHandler?

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpContextAccessor();
            services.AddAuthorization(options =>
            {
                options.AddPolicy("Custom",
                    policy => policy.Requirements.Add([ How to add here the instance of my handler??? ]));
            });
            services.AddControllers();
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcab4fd-00de-6e6f-0552-30c07ffc4086
* Version Independent ID: 5c2b0d48-ef1a-5875-35d1-865cb022fa71
* Content: [Dependency injection in requirement handlers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/dependencyinjection?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authorization/dependencyinjection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/dependencyinjection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Mds92** [comment]
I have the same problem.

**Comment by Kant8** [comment]
Just don't mix IAuthorizationRequirement and IAuthrizationHandler in one class. Requirement is just simple marker and holder of parameters (if any). Handler is separate object that is called by Authorization Middleware, where it's constructor is resolved by DI. And only then middleware calls HandleRequirementAsync for all requirements that have type of CustomRequirement. Or even you can just register generic IAuthrizationHandler that handles any types of requirements it wants.

In your case create separate
```
public class CustomRequirementHandler : AuthorizationHandler<CustomRequirement>
{
    public CustomRequirement(IHttpContextAccessor httpContextAccessor, YourDbContext context)
    { ... }
}
```

and register it as `services.AddScoped<IAuthorizationHandler, CustomRequirementHandler>();`

So you won't have problem with constructing CustomRequirement to pass it to `policy.Requirements.Add()`

**Comment by jdege** [comment]
I'm not seeing it.

I'm working an ASP.NET CORE 3.1, and policy.Requirements.Add() expects an IAuthorizationRequirement. How do I construct one, within Startup.ConfigureServices()?

**Comment by Kant8** [comment]
Just with new? Again, Requirement is simple class with or without properties, it doesn't have any logic and doesn't have any dependencies. They may only need configuration for constructor parameters.
Docs already have decent example https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies#requirements

You can even add requirements dynamically with custom `IAuthorizationPolicyProvider`, where you can inject anything you want https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider#custom-iauthorizationpolicyprovider

**Comment by alexey-formalmethods** [comment]
@Kant8 , your answer isn't clear.

Your class is CustomRequirementHandler  
and constructor there is CustomRequirement, si what is it eventually? 

> So you won't have problem with constructing CustomRequirement to pass it to policy.Requirements.Add()

Can you provide an example with using separate Requirement, Handler, their registration in Startup and "Authorize" attribute in controller ([Authorize(Policy = "Custom")])

**Comment by Kant8** [comment]
Sorry about that, copypasted from question and forgot to add 'Handler' to constructor.
Full example with separate handler, requirement and policy registration is available via first link in my previous comment.

**Comment by alexey-formalmethods** [comment]
It's clear now, thank you.
I have to create 
CustomRequirement : IAuthorizationRequirement
CustomAuthorizationHandler : AuthorizationHandler<CustomRequirement>, overriding HandleRequirementAsync()

and in Startup.cs:
services.AddAuthorization(options =>
            {
                options.AddPolicy("Custom", policy =>
                    policy.Requirements.Add(new CustomRequirement()));
            });
and services.AddSingleton<IAuthorizationHandler, CustomAuthorizationHandler>(); or  services.AddScoped<IAuthorizationHandler, CustomAuthorizationHandler>() or
