### ISSUE TITLE
dotnet tools missing / database migration fails

### ISSUE THREAD

**Issue by JAusD** [aspnet/AspNetCore.Docs#16229]
With just a fresh core 3.1 installation, dotnet tools were missing for me and needed manual installation:
dotnet tool install --global dotnet-aspnet-codegenerator --version 3.1.0
dotnet tool install --global dotnet-ef --version 3.1.0

Afterwards, "dotnet ef" commands end up with  build failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
