### ISSUE TITLE
Can't directly inject json content into static properties

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#16226]
The comment below was machine translated

@1257960069 commented on [Sat Dec 14 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/225)

If the Option1 property of the class MyOptions is a static property, I want to directly use the property's static class MyOptions.Option1 to get the value after using the services.Configure <MyOptions> () method, but after I try, the value of MyOptions.Option1 is null

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [ASP.NET Core 中的选项模式](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sat Dec 14 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/225#issuecomment-565716892)

Hello, @1257960069
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
> If the Option1 property of the class `MyOptions` is a static property, I want to use the static class `MyOptions.Option1` of the property to take the value directly after using the `services.Configure <MyOptions>()` method, but after I try, the value of `MyOptions.Option1` is `null`.

**Comment by guardrex** [comment]
I have a feeling that this is *by-design*. Can you confirm @HaoK?

**Comment by guardrex** [comment]
@1257960069 ...

Can you provide an example? Show your code.

你能举个例子吗？显示您的代码。

Nǐ néng jǔ gè lìzi ma? Xiǎnshì nín de dàimǎ.

**Comment by guardrex** [comment]
I think the general advice from engineering is not to use static classes with dependency injection. I know that you can't use a static type when calling `Configure` to configure options. I'm less sure about using a static property, but it does present problems. For example, I just made `Option1` a static property, and it led to problems like this ...

> Member 'MyOptions.Option1' cannot be accessed with an instance reference

**Comment by 1257960069** [comment]
otherwise,How to get a Instance from a Injected Container？SomeTimes，I just use some Class like Statice Class。Is this？
![image](https://user-images.githubusercontent.com/31265244/71143592-1c90b980-2256-11ea-92c8-9ce72801d8e1.png)
![image](https://user-images.githubusercontent.com/31265244/71143618-35996a80-2256-11ea-8df0-3cf8f6b86240.png)
