### ISSUE TITLE
.net core 30 :static  file   http404  on Linux Centos7

### ISSUE THREAD

**Issue by AKA285066112** [aspnet/AspNetCore.Docs#16235]
when  run   dotnet xxxx.dll

Content root path  always reset to  path: /root
webroot  reset  too!!

Microsoft.AspNetCore.Hosting.Diagnostics[2]
Request finished in 0.8585ms 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)

Include steps to reproduce the bug and the version you're using `dotnet --version`

Why aren't you using .NET Core 3.1?

**Comment by AKA285066112** [comment]
yum&nbsp; didnot&nbsp; have&nbsp;.NET Core 3.1

I don't need to update the dotnet every day, in the test phase.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rick Anderson"<notifications@github.com&gt;; 
发送时间: 2019年12月17日(星期二) 中午11:50
收件人: "aspnet/AspNetCore.Docs"<AspNetCore.Docs@noreply.github.com&gt;; 
抄送: "☆ALONG☆"<285066112@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aspnet/AspNetCore.Docs] .net core 30 :static  file   http404  on Linux Centos7 (#16235)




If you think this is a product bug, create the simplest possible sample that reproduces the problem and open an issue at GitHub ASP.NET Core
 
Include steps to reproduce the bug and the version you're using dotnet --version
 
Why aren't you using .NET Core 3.1?
