### ISSUE TITLE
Add section on Microsoft.Extensions.Caching.Redis being removed

### ISSUE THREAD

**Issue by divinebovine** [aspnet/AspNetCore.Docs#16247]
There's been some questions regarding the lack of Microsoft.Extensions.Caching since the release of ASPNET.Core 3.0. I did a little research and it looks like it was removed on purpose, but I can't find any information on the breaking change.

https://stackoverflow.com/questions/59292159/does-redis-cache-in-net-core-3-requires-the-usage-of-the-stack-exchange-package/59313344#59313344

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The announcement is here ...

https://github.com/aspnet/Announcements/issues/322

We cover it in the Distributed Caching topic (it's versioned content) ...

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache

AFAIK, it's not covered in our *Migration* doc set.

**Comment by divinebovine** [comment]
I was aware of the Distributed Caching topic, but there was no explanation, so it left me unsure if it was intentional or not.

Doing announcements in Github issues does raise the question of discoverability, especially when you consider the number of Github repositories that will need monitoring. If you don't feel like things like this are worthwhile to add to the migration document, I guess its your call. It just increases our risk as we try to plan out our sprints.

**Comment by divinebovine** [comment]
I take back what I said about the number of repos to monitor, I didn't realize it was an announcements repository.

**Comment by guardrex** [comment]
Yes, we just version the content. In many cases, you'd have to flip the topic's version selector over to the earlier version to see the difference. We try to document the current version only in a given version of the topic. Changes are called out in the *Migration* topic set.

Most of the announcement content makes it into the *Migration* topics. This was an oddball one that didn't find its way in there. *It looks like it was just an oversight.* Sorry about that.

**Comment by divinebovine** [comment]
Completely understandable. Thanks for your time!
