### ISSUE TITLE
The type or namespace name 'MovieContext' could not be found

### ISSUE THREAD

**Issue by CGrijalva90** [aspnet/AspNetCore.Docs#16249]
After scaffolding, I tried to inject IWebHostEnvironment into `Startup.cs` using the code provided but I got the following error: `The type or namespace name 'MovieContext' could not be found`. the `MovieContext` is found in the `ConfigureServices` method.

I'm using .NET Core 3.1, and Visual Studio Code. I'm unsure if the docs got messed up somewhere or if the issue is on my end. 

`Data/RazorPagesMovieContext.cs`:

```csharp
using Microsoft.EntityFrameworkCore;

namespace RazorPagesMovie.Data
{
    public class RazorPagesMovieContext : DbContext
    {
        public RazorPagesMovieContext (
            DbContextOptions<RazorPagesMovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorPagesMovie.Models.Movie> Movie { get; set; }
    }
}
```

`Models/Movie.cs`

```csharp
using System;
using System.ComponentModel.DataAnnotations;

namespace RazorPagesMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}
```

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by CGrijalva90** [comment]
@Rick-Anderson Is there a final version on github for the completed tutorial that I can reference?
