### ISSUE TITLE
Documentation needed to clarify how route precedence works in .Net Core 3+.

### ISSUE THREAD

**Issue by Coderrob** [aspnet/AspNetCore.Docs#16245]
In previous versions of Asp.Net MVC when using the router's `MapRoute` it used to be documented the order you should define routes. I believe the previous guidance was to enter the routes from the "most restrictive" route to the default route.

Ex:
```
            app
                .UseStaticFiles()
                .UseMvc(builder =&gt;
                {
                    builder
                        .MapRoute("Api", "api/{controller=Home}/{id?}")
                        .MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
                })
```

Now it seems that the reverse is true. Looks like the router must define the default route first then the more restrictive routes. 

```
            app
                .UseStaticFiles()
                .UseMvc(builder =&gt;
                {
                    builder
                        .MapRoute("default", "{controller=Home}/{action=Index}/{id?}")
                        .MapRoute("Api", "api/{controller=Home}/{id?}");
                })
```

It would be helpful to include a snippet that includes a route other than what could be accomplished with the `MapDefaultControllerRoute` function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rybkov** [comment]
It is a breaking change! Now need to reverse all routings.

**Comment by Rick-Anderson** [comment]
Moved to Routing master issue #16501
