### ISSUE TITLE
The type or namespace name 'MovieContext' could not be found

### ISSUE THREAD

**Issue by CGrijalva90** [aspnet/AspNetCore.Docs#16253]
After running the scaffold, right under "Use SQLite for development, SQL Server for production", I try to update the ConfigureServices method in Startup.cs but the reference of "MovieContext" cannot be found in the following line:

```
services.AddDbContext&lt;MovieContext&gt;(options =&gt;
            options.UseSqlite(
                Configuration.GetConnectionString("MovieContext")));
```

 I've followed the tutorial step by step numerous times, and can't seem to find where the namespace is missing or the missing reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/71045327-a450b980-20d8-11ea-89fb-32c366a834c5.png)

**Comment by CGrijalva90** [comment]
In the previous lesson where we create the class in the `Data` folder, you name it: `RazorPagesMovieContext` not `MovieContext`

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/71196284-d62a6300-2233-11ea-995c-878f519c8f50.png)
