### ISSUE TITLE
Create logs in the Program class

### ISSUE THREAD

**Issue by dansward** [aspnet/AspNetCore.Docs#16266]
var logger = host.Services.GetRequiredService&lt;ILogger&lt;Program&gt;&gt;();
Won't compile.
Error -&gt; 'Program': static types cannot be used as type arguments
Suggest using following instead.
var logger = host.Services.GetRequiredService&lt;ILogger&lt;Startup&gt;&gt;();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's used twice:

## Create logs in the Program class

To write logs in the `Program ` class of an ASP.NET Core app, get an `ILogger ` instance from DI after building the host:

`    var logger = host.Services.GetRequiredService<ILogger<Program>>();`

It's not writing logs in the  `Program ` class,  it's writing logs with the name Program -right @guardrex ?

**Comment by serpent5** [comment]
It's writing logs from within the `Program` class. That will log the `Program` type name as a _category_ in the log messages.

The `Program` class in the topic isn't `static`:

>     public class Program

The error message being reported here will be because @dansward is using a `static` `Program` class:

>     public static class Program

Drop the `static` and it should work.

**Comment by guardrex** [comment]
They're all static `Main`s in the topic ... maybe a half-dozen examples set up a logger like that. I also haven't ever had a problem with that code construct IIRC. @dansward can you paste in your full *Program.cs* file here for us to see?

**Comment by guardrex** [comment]
Oh ... lol ... **class**. Gotcha ... I'm doing like three things here at once.

**Comment by guardrex** [comment]
@Rick-Anderson You should be able to just close this. The topic doesn't show a static `Program` class.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
