### ISSUE TITLE
Improve StartUp sample with Kestrel

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#16265]
https://github.com/aspnet/AspNetCore/issues/17928#issuecomment-566666011

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Actually, this isn't a "doc-bug," nor does it apply to the sample. Let's call it an "enhancement" for the text. It's just that the example is a little sparse because it doesn't show the injection of config and it doesn't cross-link exactly to where we show it in another doc. A little more info in the in-text example will help flesh it out.

**Comment by Ricardoaraujo00** [comment]
Thanks @guardrex 

If you could had a simple explanation on how to get out of the localhost block and expose the service to the outside would be great. Even if just for development proposes. Another good thing to explain is on how to run a aspnet core grpc server as a windows(and linux) service and have it exposed to the outside also(an application to just click and run). A compreensive manual on how to make the deployment into a local linux server, ubuntu or derived, would be also great. Despite these being my needs i think they are also the needs of other developers. Thanks
