### ISSUE TITLE
Useful

### ISSUE THREAD

**Issue by alvinchesaro** [aspnet/AspNetCore.Docs#16277]
Very well crafted and precise saved me a lot of research time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @alvinchesaro ... this one had a [major overhaul](https://github.com/aspnet/AspNetCore.Docs/pull/12344) that took over a week 😅, but **_it was worth it_** to address many feedback items on https://github.com/aspnet/AspNetCore.Docs/issues/10214#issuecomment-491382346. We have a collection of additional tasks to work on https://github.com/aspnet/AspNetCore.Docs/issues/12285, so you can comment there if you think of anything else.
