### ISSUE TITLE
"Blazor" localization issue

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16273]
From @vintzl at https://github.com/dotnet/docs/issues/15141#issuecomment-567191041 ...

> Hi everyone.
> You still have some bad outputs…
> try this in Bing or Google:
>
>     blazor site:docs.microsoft.com éblouissant
>
> here a sample:
>
>     https://docs.microsoft.com/fr-fr/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
In spite of having `no-loc: [Blazor, SignalR]` in metadata, "éblouissant" is still showing up in ...

* The IMPORTANT and WARNING notes.
* Emphasis text (e.g., `*blazor.webassembly.js*` appearing as `éblouissant. webassembly. js`).
* An unclear translation issue:

  > While a Blazor Server app is prerendering, certain actions, such as calling into JavaScript, aren't possible because a connection with the browser hasn't been established.`

  > Bien qu’une application de serveur éblouissante soit prérendue, certaines actions, telles que l’appel en JavaScript, ne sont pas possibles, car une connexion avec le navigateur n’a pas été établie.

* In parentheses (e.g., `(Blazor WebAssembly)` appearing as `(éblouissante webassembly)` and `(Blazor Server)` appearing as `(serveur éblouissant)`).

**Comment by JasonCard** [comment]
@guardrex Thank you for the summary of issues. I found there are mainly two root causes for these over-localization issues and need your help to address them. 

1. The `no-loc` metadata will not work for content referenced from INCLUDES files, so can you please help to use the [no-loc md syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) for the "Blazor" terms directly in the two INCLUDES files below?
 - [blazorwasm-preview-notice.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/blazorwasm-preview-notice.md)  
 - [blazor-prerendering.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/blazor-prerendering.md)  

2. The `no-loc` metadata for [Blazor] will not work for *blazor.webassembly.js* as it's treated as different word. So could you please try to add "blazor.webassembly.js" in the `no-loc` metadata? 
no-loc: [Blazor, SignalR, blazor.webassembly.js]

**Comment by guardrex** [comment]
Thanks ... I'll work on this today.

> use the no-loc md syntax for the "Blazor" terms directly in the two INCLUDES files below

I can't see the content under the link that you posted. I assume it's ok to use the metadata in an INCLUDES as usual. Is that correct? ...

```
---
no-loc: [Blazor, SignalR]
---
........... INCLUDES CONTENT HERE ...........
```

**Comment by JasonCard** [comment]
@guardrex Thank you for your help on this. I asked, but it seems that we have not yet tested to see if the no-loc metadata will actually work in INCLUDES files. We're also currently not able to test the no-loc metadata in our playground, so we will just have to try it live and see.

**Comment by guardrex** [comment]
@JasonCard Most of the updates are on the following PR with the INCLUDES file changes ...

https://github.com/aspnet/AspNetCore.Docs/pull/16272

There's a little 🐞 *bug* in the build system somewhere, so all PRs aren't fully building right now. A work item has been opened internally on it. As soon as that's resolved and we get that PR reviewed+merged+live, I'll ping you to let you know if the INCLUDES file attempt worked.
