### ISSUE TITLE
How to expose to the outside?

### ISSUE THREAD

**Issue by Ricardoaraujo00** [aspnet/AspNetCore.Docs#16278]
I think there is missing an important, and key aspect, in this explanation, wich is on how to expose the service to the outside and not being stuck on localhost. Being on localhost is useless. We need that. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
It's no different than any other web app except that  [gRPC not supported on Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1#grpc-not-supported-on-azure-app-service)
