### ISSUE TITLE
Please specify whether or not we should use  stringBuilder.Clear()

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore.Docs#16288]
And why/ why not, in the example, it is not used. Why don't we have to clear it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075aad4c-9e53-92c1-8405-70bd5ed54baa
* Version Independent ID: fa535bff-449d-ac12-ea5b-8a975b0682f6
* Content: [Object reuse with ObjectPool in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/objectpool?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/ObjectPool.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/ObjectPool.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, because the ObjectPool manages  it.

`            var stringBuilder = builderPool.Get();`
