### ISSUE TITLE
How do I include this analyzer for .NET Core 2.2?

### ISSUE THREAD

**Issue by udlose** [aspnet/AspNetCore.Docs#16282]
How do I include the web api analyzers for .NET Core 2.2?  I tried adding `<PropertyGroup>
 <IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
</PropertyGroup>` to my .csproj file but I don't get any warnings/suggestions (and I know I'm missing this attribute in many places).  I have also included the `ApiController` attribute on all of my controllers.

Does it need to be downloaded separately as a Nuget package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
`Install-Package Microsoft.AspNetCore.Mvc.Api.Analyzers`

Select the 2.2 version of the doc
