### ISSUE TITLE
Ambiguity bettween class names StudentController and StudentsController

### ISSUE THREAD

**Issue by LayersOfAbstraction** [aspnet/AspNetCore.Docs#16285]
Hi, 
You guys keep saying StudentsController and then StudentController. I assume you meant StudentController minus the plural. I saw you write StudentsController in the previous page of this tutorial. Regardless, great tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll try to get it straight in the next refresh.
