### ISSUE TITLE
Error compiling on Windows 10. The system cannot find the file specified.

### ISSUE THREAD

**Issue by Seamus3131** [aspnet/AspNetCore.Docs#16295]
Following the tutorial I ended with a VSCode or VS2019 project version with compilation error:
--grpc_out: The system cannot find the file specified.

.Net core is 3.0.100
Grpc.AspNetCore is 2.26
Grpc.Core is 2.26
Grpc.Tools is 2.26

base path is c:\sources\grpcgreeter

Any hints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Seamus3131** [comment]
Not saying tutorial does not work, saying I face a problem wondering if someone already got it.

Anyway, Protobuf compilation of .proto file uses the protoc.exe, it seems compilation chain does not support certain characters in protoc.exe path. That is my case due to my firstname.

Moving all %userprofile%/.nuget to a simple path and defining the NUGET_PACKAGES environment variable did the work for me.
