### ISSUE TITLE
Spelling error: PhysicaFileProvider 

### ISSUE THREAD

**Issue by StevenRasmussen** [aspnet/AspNetCore.Docs#16290]
The hyperlinked text "PhysicaFileProvider" about half way through the document should be "PhysicalFileProvider"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9e2f78-9caf-3b88-05a6-537e031ecddf
* Version Independent ID: 06ca8420-5ca0-24ae-3584-9a4c486d3ebe
* Content: [Memory management and patterns in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
