### ISSUE TITLE
Does Order property take precedence over scope?

### ISSUE THREAD

**Issue by reponemec** [aspnet/AspNetCore.Docs#16298]
Documentation says:
IOrderedFilter exposes the Order property that **takes precedence over scope** to determine the order of execution.
But it looks Order property **does not** takes precedence over scope.

**Comment by guardrex** [comment]
@reponemec Would you mind re-opening this from the bottom of the topic? Use the **This page** feedback button+form. It will add metadata and ping the author automatically.

... and btw -- We're all out on vacation for the ⛄️ holidays 🎁, so you might not get an answer for a while, possibly even after Jan. 1.
