### ISSUE TITLE
Missing using statements and packages

### ISSUE THREAD

**Issue by JAusD** [aspnet/AspNetCore.Docs#16296]
I have just installes core 3.1 with nothing else. Trying to get these sample running (latest VSCode) needs some additional steps for me:
1.Startup.cs needs addidional using statements
```
using RazorPagesMovie.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
```

Otherwise SameSiteMode.None, &lt;RazorPagesMovieContext&gt; and CompatibilityVersion are not recognized.

2. Tools missing
tool aspnet-codegenerator and ef are missing.
```
dotnet tool install --global dotnet-aspnet-codegenerator --version 3.1.0
dotnet tool install --global dotnet-ef --version 3.1.0
```

3. SqlServer package missing
Need to execute 
`dotnet add package Microsoft.EntityFrameworkCore.SqlServer`
Otherwise  dotnet aspnet-codegenerator... fails with 

> Building project ...
> Finding the generator 'razorpage'...
> Running the generator 'razorpage'...
> To scaffold controllers and views using models please install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design, Microsoft.EntityFrameworkCore.SqlServer
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.&lt;BuildCommandLine&gt;b__6_0() 
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)     
>    at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)   

 4. Wrong path for Pages/Movies
`dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries`
Created PagesMovies instead of Pages/Movies
Moved everything manually there and then it worked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> 1. Startup.cs needs addidional using statements

It has all the using.

All these directions are there if you use the VSC tab
