### ISSUE TITLE
Shouldn't UseMvc be a UseEndpoints?

### ISSUE THREAD

**Issue by Hakej** [aspnet/AspNetCore.Docs#16306]
I'm not really sure, cause this is all new to me, but I've been going through this tutorial and suddenly this page recalls to app.UseMvc in Startup.cs file, while I have app.UseEndpoints instead. It doesn't seem like a big of a deal for now, but confused me a bit nonetheless. I went through the tutorial up to this point briefly and haven't found any mention of changing UseEndpoints to UseMvc. I have no clue if I missed something, but that's definitely possible, I'd be thankful for explanation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Hakej  thanks for notifying us. Fix will be live in a couple days.
