### ISSUE TITLE
Issue with globalization asp.net core 3,1 not getting value just key

### ISSUE THREAD

**Issue by davidbuckleyni** [aspnet/AspNetCore.Docs#16312]
I have setup globalization as per the documents here but something must be wrong cause I am only getting the value of the key not the value of the resource.

The following is my code which i have more or less copied from the doument link above.

    // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLocalization(opts => { opts.ResourcesPath = "Resources"; });

            services.Configure<RequestLocalizationOptions>(opts =>
            {
                var supportedCultures = new List<CultureInfo> { new CultureInfo("en-GB"), new CultureInfo("fr-FR"), };

                opts.DefaultRequestCulture = new RequestCulture("en-GB");

                // Formatting numbers, dates, etc.
                opts.SupportedCultures = supportedCultures;
                // UI strings that we have localized.
                opts.SupportedUICultures = supportedCultures;
            });
            // Add framework services.
            services.AddControllersWithViews()
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
                // Maintain property names during serialization. See:
                // https://github.com/aspnet/Announcements/issues/194
                .AddNewtonsoftJson(options =>
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver())
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix,
                    opts => { opts.ResourcesPath = "Resources"; })
                .AddDataAnnotationsLocalization();
            services.Configure<ConnectionStringConfig>(Configuration);
            //lets inject the connection string to the data layer 
            //but we should be using the api layer for any heavy lifting.
            services.AddHttpClient("externalservice", c =>
            {
                // Assume this is an "external" service which requires an API KEY
                c.BaseAddress = new Uri("https://localhost:5001/");
            });
        
            // Add Kendo UI services to the services container
                        services.AddKendo();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            SetUpLocalization(app);

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            var options = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
        
            app.UseRequestLocalization(options.Value);
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}/{id?}");
            });

        }
        private static void SetUpLocalization(IApplicationBuilder app)
        {
            var supportedCultures = new[]
            {
                new CultureInfo("en-US"),
                new CultureInfo("pl-PL"),
                new CultureInfo("pl")
            };

            var options = new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("en-GB", "en-GB"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures,
             
            };
            options.AddInitialRequestCultureProvider(new CustomRequestCultureProvider(async context =>
            {
                // My custom request culture logic
                return new ProviderCultureResult("en");
            }));

            // Find the cookie provider with LINQ
            var cookieProvider = options.RequestCultureProviders
                .OfType<CookieRequestCultureProvider>()
                .First();
            // Set the new cookie name
            cookieProvider.CookieName = "UserCulture";

            // Configure the Localization middleware
            app.UseRequestLocalization(options);

        }
This is my controller where I am accessing the resouce file key 

    public class StockController : Controller
    {
        private  readonly IStringLocalizer<StockController> _localizer;
        
        RoundTableAPIClient apiClient = new RoundTableAPIClient();
        // GET

        public StockController(IStringLocalizer<StockController> localizer)
        {
          
            _localizer = localizer;
            
        }
        public IActionResult Index()  
        {
            var test = _localizer[ResourceKeys.StockPageTitle].Value;
            

            ViewBag.Title = _localizer["StockPageTitle"].Value;

            return View();
        }
     }
But I am not getting the value that is in my resource file I am just getting the text StockPageTItle which is incorrect also how does one give the en-GB as default in asp.net core routes that is not explained in the docs.` enter code here`
 ![enter image description here](https://i.imgur.com/m7oGY1r.png)

**Comment by davidbuckleyni** [comment]
I placed it in the docs as I feel its an issue with the docs not explaining properly

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

Try the sample download. Create the simplest possible sample that fetches resources, then start adding complexity.

**Comment by davidbuckleyni** [comment]
I havent missed any step this was working 3.0 I have been working 0 years and this seemd to have been skimmed over in typical microsoft support style
