### ISSUE TITLE
How do I register custom converters globally rather than via annotations?

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/AspNetCore.Docs#16315]
How do I register a custom converter globally rather than having to use annotations to trigger their behaviour?

(The type I need to convert for lives outside of my assembly.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Model Binding master issue #16316

**Comment by Rick-Anderson** [comment]
Per #16316

@atrauzzi 

This is covered in [How to write custom converters for JSON serialization in .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to) (linked from the topic). It's under the section [Register a custom converter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#register-a-custom-converter). I wouldn't repeat that in this topic, but a hint towards using `AddJsonOptions` in `ConfigureServices` to get access to `JsonSerializerOptions` might be useful.
