### ISSUE TITLE
How do I specify a binder for a type outside of my project?

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/AspNetCore.Docs#16314]
I don't have the ability to annotate the type I want hydrated from the request. Is there any way to register model binders/custom converters globally for the types I wish to convert from the request body?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #16319

**Comment by Rick-Anderson** [comment]
@atrauzzi  per #16319 

This one is already covered in the section [Implementing a ModelBinderProvider](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#implementing-a-modelbinderprovider).
