### ISSUE TITLE
Better migration removal idea

### ISSUE THREAD

**Issue by LayersOfAbstraction** [aspnet/AspNetCore.Docs#16311]
So I practised removing migrations and found I could not do this so I went to SO and found using the -v option allowed me to see the error being generated which said I...

 "cannot access the file ... ContosoUniversity.dll because it is being used by another process." Accidently via (Ctrl + F5).

Instead of `dotnet ef migrations remove`, you should consider `dotnet ef migrations remove -v` so user can see the error and is saved a trip to SO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [Tutorial: Using the migrations feature - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@LayersOfAbstraction  good suggestion thanks. I made a similar change in https://github.com/aspnet/EntityFramework.Docs/pull/2011
