### ISSUE TITLE
Tutorial Migration transfers data into new DB? 

### ISSUE THREAD

**Issue by LayersOfAbstraction** [aspnet/AspNetCore.Docs#16310]
Hi guys,

I have done as instructed. And have successfully created a new database with the same tables and columns. I am confused as to if the intent of this tutorial was to migrate data to new DB as per this image. 
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations/_static/students-index.png?view=aspnetcore-2.2

I am not able to do that upon completing instructions. The DB has no data except what is in the table "dbo.__EFMigrationsHistory". Were the instructions to allow us to migrate data to new DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [Tutorial: Using the migrations feature - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by LayersOfAbstraction** [comment]
OK all good. It just confused me a bit when the tutorial shows a screenshot of the same data in the new database because you are applying the migrations to create a new database with the same schema without copying data across from the previous database. Unless I misunderstood something.
