### ISSUE TITLE
Specify guideline for integration tests in terms of what to mock and what should not be mocked

### ISSUE THREAD

**Issue by tekbyts** [aspnet/AspNetCore.Docs#16320]
# Issue description

The documentation on Integration tests does not provide a guideline as to what can be mocked and what should not be mocked. 

For example: while doing integration tests, can i mock the dependencies (i.e. business logic, repository etc..) I think mocks are useful for unit tests. There should be some guideline that states what can be mocked and what should not be mocked 

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core specifically ASP.Net Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
