### ISSUE TITLE
Specify guideline for integration tests in terms of what to mock and what should not be mocked 

### ISSUE THREAD

**Issue by tekbyts** [aspnet/AspNetCore.Docs#16321]
The documentation on Integration tests does not provide a guideline as to what can be mocked and what should not be mocked.

For example: while doing integration tests, can i mock the dependencies (i.e. business logic, repository etc..) I think mocks are useful for unit tests. There should be some guideline that states what can be mocked and what should not be mocked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
