### ISSUE TITLE
How is a handler that handles multiple requirements invoked?

### ISSUE THREAD

**Issue by bathetrade** [aspnet/AspNetCore.Docs#16333]
This page clearly states how to create a handler that handles multiple requirements, but it does not say how such a handler is registered or invoked. For single-requirement handlers, you add the requirement to a policy, and the framework will resolve the handler based on the requirement. How do you add a multiple-requirement handler to a policy (perhaps through the authentication scheme)? Also, it's not clear in what order requirements will be resolved if you mix single-requirement and multiple-requirement handlers together, which could be relevant when dealing with the PendingRequirements property. More information would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #16191
