### ISSUE TITLE
DI for RP Filters is a little confusing

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#16331]
In the opening section, this topic states that RP filters:

> * Have access to the following services:
>   * `IConfiguration`
>   * `IHostEnvironment`
>   * `IWebHostEnvironment`
> * Can **not** access services other than the preceding by Dependency Injection (DI). The `TypeFilterAttribute` and `ServiceFilterAttribute` can access the services registered in the DI container. For more information, see ServiceFilterAttribute and TypeFilterAttribute.

These services aren't provided to the filter via DI. They're just passed in to the filter's constructor when added in `Startup`. The only DI here is into the `Startup` constructor, but that's not related to RP filters and how DI works for those. I don't think there's anything wrong with passing e.g. `IConfiguration` this way, but it's not DI and RP filters don't have special access to these. I think this makes the explanation a bit confusing.

I think I'd remove the first bullet and update the second to just indicate that DI can be used and link as it already does.

At a higher level, I'd like to see this page merged into the existing filters page. I realise that might not be practical, but it's just a thought given how closely related the two topics are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-3.1)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I've edited in the content (I guess you don't get notifications for that).

**Comment by Rick-Anderson** [comment]
Good idea. Can you PR this?

**Comment by serpent5** [comment]
> Can you PR this?

The DI changes or a merger?

**Comment by Rick-Anderson** [comment]
DI changes.

Maybe we can patch the merger with cross linking for now.
