### ISSUE TITLE
gRPC from F# — docs are missing

### ISSUE THREAD

**Issue by haf** [aspnet/AspNetCore.Docs#16349]
Hello,

This page (see below) is completely missing docs on how to do gRPC from F#. Could you please add it?

Thanks! 😋

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
Hello @haf ... F# examples/samples aren't covered in the ASP.NET Core docs (nor VB). We only provide C# examples/samples. If there's an industry shift to F# (and/or VB), then I'm sure management will consider also providing coverage in F# (and/or VB).

**Comment by haf** [comment]
It’s insulting that you compare F# to a bearded dinosaur like VB.
