### ISSUE TITLE
ValidationState not being set correctly

### ISSUE THREAD

**Issue by jvert** [aspnet/AspNetCore.Docs#16356]
I believe there is a bug in the sample code and it should be 
    `bindingContext.ValidationState[newBindingContext.Result.Model] = new ValidationStateEntry`
not 
    `bindingContext.ValidationState[newBindingContext.Result] = new ValidationStateEntry`

Otherwise the validation of the derived class does not run correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by serpent5** [comment]
> Otherwise the validation of the derived class does not run correctly.

@jvert Can you elaborate on this a little? What problem do you see?

**Comment by ddvk** [comment]
the ModelState.IsValid == false if not done like shown above, happens if the model is a IList<abstracttype>

**Comment by Cal279** [comment]
@Rick-Anderson - This still appears to be a problem. The current example for polymorphic model binding results in derived types having properties which are marked as `Unvalidated` (so `ModelState.IsValid` is false). The original suggestion by @jvert to use the below line resolves this problem.

`bindingContext.ValidationState[newBindingContext.Result.Model] = new ValidationStateEntry`
