### ISSUE TITLE
Downloading samples

### ISSUE THREAD

**Issue by Youssef1313** [aspnet/AspNetCore.Docs#16362]
Many articles links to samples on GitHub. Example is [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1).

In the "How to download" link, it suggests to download the whole repo, which isn't a good solution. It would be much much better to migrate these samples to the [samples browser](https://docs.microsoft.com/en-us/samples/browse/), so it allows to download ONLY the required sample.

The process of migration isn't too difficult, it only requires a README.md with special metadata.

An example of a PR that migrated a sample to the samples browser is #13808

**Note:** The PR was missing a required metadata, ('urlFragment'), which was added later. So, if someone will work on this, don't take the metadata section as is without adding the urlFragment.

**Note 2:** I don't know if there is already an issue open for the same task. If there is one already, you can close this one.

**Comment by guardrex** [comment]
Hello @Youssef1313 ... Yes, we're aware. We haven't had the call from management yet here to do the work. I don't have an ETA at this time. This work may or may not be tied to a new issue. We keep a sample update tracking issue, so we might use that one for this work. Indeed, some of the sample moves might include versioning work as well, so it might make sense to track using that one :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/5495
