### ISSUE TITLE
Add a new tutorial for .NET Core with Couchbase

### ISSUE THREAD

**Issue by mgroves** [aspnet/AspNetCore.Docs#16373]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs: I searched (with Bing) for "ASP.NET Core Couchbase Getting Started"
- Tell us what docs you found that didn't address your concern: There is a Mongo version, but there is not Couchbase equivalent, and the first Docs result is https://docs.microsoft.com/en-us/aspnet/core/getting-started/ (which doesn't reference any database)

**Describe the new topic**

- Explain why this topic is needed: There is no tutorial present for beginners to understand how dotnet core can work with Couchbase.
- Suggest a location in the Table of Contents: Docs/tree/master/aspnetcore/tutorials
- Write an abstract. In one **short** paragraph, describe what this topic will cover: Creating a Web API using ASP.NET Core to perform CRUD operations on a Couchbase bucket.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic:

1. Setting up Couchbase
2. Creating Dotnet Core web API Application in Visual Studio
3. Adding required packages (with NuGet)
4. Adding Data Model classes
5. Writing repository for CRUD Operations
6. Making Controller
7. Building and running the application

I'm basing this request on #8859, which is a tutorial featuring Mongo. I am willing to write the first draft of this tutorial, assuming you approve the above outline.

**Comment by Rick-Anderson** [comment]
My vote is this is something better blogged outside the official docs. 
[Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio) requires alot of effort each version. Mongo is much higher requested than Couchbase.

@danroth27  and @scottaddie  might convince me it's worth it.

**Comment by scottaddie** [comment]
While I'd love to see a Couchbase tutorial in our docs, the reality is that we're not staffed to maintain it.
