### ISSUE TITLE
API conventions not being applied

### ISSUE THREAD

**Issue by t-hart** [aspnet/AspNetCore.Docs#16388]
Hi! I was having some trouble with the API Conventions and struggled to make it work for an hour or two before I finally found the solution. I'm opening this issue to let you know what I struggled with so that you can improve it if you think it's necessary.

# Solution
As per the issue below, I couldn't get API Conventions to work at all, no matter what I tried. In the  end, the solution was pretty simple: I had to add the `[ApiController]` attribute to the controller class or to the assembly.

However, this was not obvious to me in any way. It may be due to inexperience with the framework and conventions, but it took me a long time to figure out, and it doesn't seem to be called out explicitly anywhere (at least not where I found), including in the [docs for the `ApiController` attribute](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1). I'd suggest calling this out explicitly somewhere if I haven't just missed it.

Cheers.

-----

# Original issue.

I came here from the [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/samples/aspnet/aspnetcore.docs/getstarted-swashbuckle-aspnetcore/?tabs=visual-studio-code), hoping to use API conventions for documenting controllers project-wide (WebAPI project, .NET Core 3.1, using Swashbuckle). I've tried to follow the docs on how to apply API conventions, but I don't seem to be having any luck .

Given the following controller, I'd expect to see more than just 200 show up as status codes, but that's all I get:
```csharp
    [Produces("application/json")]
    [Route("api/[controller]")]
    public class TestController : ControllerBase
    {
        [HttpPut("{id}")]
        [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Put))]
        public ActionResult Update(int id, object _)
        {
            System.Console.WriteLine(id);
            return Ok();
        }
    }
```

I originally wanted to apply a set of custom conventions, but couldn't get it to work. Seeing as even `DefaultApiConventions` don't seem to work, I'm inclined to think that it's something I've forgotten to do elsewhere, in setting up Swagger or the like.

Another option is that API conventions doesn't work with Swagger out of the box, but being taken here from the swashbuckle page, I'd expect it to be straightforward.
Manually annotating endpoints works just fine, so it seems likely to me that it's related to API conventions setup somehow.

Appreciate any help and would be happy to give more info if necessary. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1#create-web-api-conventions)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
> I had to add the `[ApiController]` attribute to the controller class or to the assembly.

That should be required should it @scottaddie

**Comment by pranavkm** [comment]
> That should be required 

There's a way for API conventions to apply to non-ApiController instances using https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ApplicationModels/ApiConventionApplicationModelConvention.cs, but in general, we'd recommend using `ApiControllerAttribute`. It's the most cohesive experience for conventions.

**Comment by Rick-Anderson** [comment]
@t-hart  There's no indication in the article you don't need `ApiControllerAttribute`:

* It's used in the sample, and shown on this page
* The API templates use it.

We'll monitor this issue and see if others are tripped up by this.

**Comment by t-hart** [comment]
> It's used in the sample, and shown on this page

What is 'this page' you're referring to?

And indeed, there's no indication you don't need the attribute, but it's a pretty small detail in the one code sample that does have it, and it's very easy to miss if you don't know you're looking for it. 

> The API templates use it.

What are the API templates you're talking about? It may be part of the `dotnet new webapi` generated content, but it seems that it may have been lost (or not added to new controllers) when developing the project on our end. 

And yeah, I'm happy for you to close the issue; just thought I'd flag it so that you are aware of it (and maybe help someone else if they run into the same one) :)

**Comment by MCatapang** [comment]
@thomasheartman it seems like it's been a couple years since this. I've also just started trying to implement Open API and I'm encountering the same issue, but with certain nuances. 
<hr>

> Manually annotating endpoints works just fine, so it seems likely to me that it's related to API conventions setup somehow.

Likewise. Annotating controller methods themselves with either `[ProducesResponseType]` or `[ApiConventionMethod]` seems to update the Swagger documentation.
<hr>

> the solution was pretty simple: I had to add the [ApiController] attribute to the controller class or to the assembly.

The solution you encountered doesn't seem to work for me. I already had `[ApiController]` decorated above the controller <i>class</i>. I then added `[ApiConventionType(typeof(CustomAPIConvention))]` - but the Swagger documentation did not produce the response types I specified under `CustomAPIConvention`.
<hr>

Were you able to get more insight on this during the past couple of years by any chance?

**Comment by thomasheartman** [comment]
@MCatapang Sorry, I haven't really worked on .NET code since about when I posted this issue, so I'm not gonna be of much help, I'm afraid.

**Comment by MCatapang** [comment]
@thomasheartman All good no worries! I forgot to place a follow-up here but I did end up finding the culprit. Posting the following for anyone's reference in the future.

<hr>

Microsoft docs weren't too specific on this, but creating a convention method like the one below
```csharp
// Original Version
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status404NotFound)]
[ApiConventionNameMatch(ApiConventionNameMatchBehavior.Prefix)]
public static void Find( )
{ 
    // A convention method that matches "Find[...]" controller methods
}
```
only matches controller methods that have **no parameters** - contrary to how people may assume that it matches controller methods with any parameters because parameters are not specified in the convention method. If you actually want to apply this convention method to controller methods that have parameters (e.g., services, etc.), you need to write your convention method in the following way:
```csharp
// Adjusted Version
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status404NotFound)]
[ApiConventionNameMatch(ApiConventionNameMatchBehavior.Prefix)]
public static void Find( 
    [ApiConventionTypeMatch(ApiConventionTypeMatchBehavior.Any)] params object[] p 
)
{ 
    // A convention method that matches "Find[...]" controller methods
}
```

**Comment by AbdAlazim-dev** [comment]
its 12/27/2023 
And im facing the same issue i have applied the ApiConvension on Controller level it worked on some actions like POST but when its Get with paramater or not it dose not work the only potintial status code i see is 200OK which not accurate,
even when i apply the : [ApiConventionType(typeof(CustomConventions))] on controller level it dose not work only when i apply it on action level it worked it seems like some attribute is override these attribute 

```
namespace Library.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [ApiConventionType(typeof(CustomConventions))]
    public class ConventionTestsController : ControllerBase
    {

        // GET: api/<ConventionTestsController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
}
```

Thank you and happy new year
