### ISSUE TITLE
MapGrpcService link needed

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#16384]
`MapGrpcService` should be linked but it can't be found in API docs

@scottaddie  why can't I find it? Need it in other docs too.

https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.1&term=MapGrpcService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by scottaddie** [comment]
@Rick-Anderson The method comes from the following NuGet package: https://www.nuget.org/packages/Grpc.AspNetCore/.
