### ISSUE TITLE
Example: Deploy to Azure Websites Linux Support?

### ISSUE THREAD

**Issue by Pyrobolser** [aspnet/AspNetCore.Docs#16392]
Hello,

It looks like this part of the documentation is not working for a __Linux App Service__
I suffer from the exact same issue as described [here](https://github.com/aspnet/AspNetCore/issues/15366), the only feedback suggest to use Windows instead of Linux, which is not possible right now with .NET Core 3.1.
Can you suggest a working workaround in the documentation?

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406
