### ISSUE TITLE
Cookie code samples

### ISSUE THREAD

**Issue by Daniel15** [aspnet/AspNetCore.Docs#16396]
It would be good to add some code samples demonstrating how to use cookies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#cookies)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
