### ISSUE TITLE
Suggestions for some clarifications

### ISSUE THREAD

**Issue by vlttnv** [aspnet/AspNetCore.Docs#16394]
I was following the tutorial with the VS code examples and a couple of things caught me off guard and potentially might discourage more inexperienced people.
1. The "Add database context class" section has a code snippet which when pasted in the editor when following along produces a lot of errors. I thought that there might be a typo or something but noticed that a library was missing and started searching for what to install. Later I noticed that a few paragraphs below the needed dependencies are installed. Perhaps you should move this section as the first step of this page as a prerequisite to add a model, before any code is written.

2. In the section "Scaffold the movie model" there is a duplicate command to install `dotnet-aspnet-codegenerator`. Also, the subsequent command that runs the code generator will not work without a shell restart as the global is not in the PATH variable. It would be good to add a note that the shell needs to be restarted for the command to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Also, the subsequent command that runs the code generator will not work without a shell restart as the global is not in the PATH variable. It would be good to add a note that the shell needs to be restarted for the command to work.

It's a global tool and doesn't require a shell restart.
