### ISSUE TITLE
Error when installing aspnet codegenerator

### ISSUE THREAD

**Issue by joshcv2112** [aspnet/AspNetCore.Docs#16408]
In the steps under "Scaffold a Controller", running the command "dotnet tool install --global dotnet-aspnet-codegenerator" returns the error:
error NU1202: Package dotnet-aspnet-codegenerator 3.1.0 is not compatible with netcoreapp3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by joshcv2112** [comment]
I resolved this issue by installing the dotnet-aspnet-codegenerator tool with a version flag as 3.0.0:
dotnet tool install --global dotnet-aspnet-codegenerator --version 3.0.0

**Comment by erik-sandoval** [comment]
I solved this by updating my .NET Core SDK to 3.1, I was using 3.0. Then I updated TodoApi.csproj  to be: <TargetFramework>netcoreapp3.1</TargetFramework>

**Comment by Rick-Anderson** [comment]
> I solved this by updating my .NET Core SDK to 3.1, I was using 3.0. Then I updated TodoApi.csproj to be: netcoreapp3.1

That't the right solution. Thanks for posting.
