### ISSUE TITLE
Ctor injection in components

### ISSUE THREAD

**Issue by RedDeathGitHub** [aspnet/AspNetCore.Docs#16409]
Will there be an ability to use constructor injection for components/pages?
At least when you have the "code behind" .cs file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RedDeathGitHub, Add your :+1: to the engineering issue so that the engineers can see the interest in this. **_I'll add one, too! :smile:_**

https://github.com/aspnet/AspNetCore/issues/18088

**Comment by RedDeathGitHub** [comment]
Thanks, added!
