### ISSUE TITLE
Code Line highlighting isn´t working properly in Chrome

### ISSUE THREAD

**Issue by tomfrenzel** [aspnet/AspNetCore.Docs#16411]
[EDIT by guardrex to add the metadata. @tomfrenzel ... If you use the **This page** feedback button+form at the bottom of any topic, it will add the metadata automatically and ping the author of the topic automatically.]

Highlighted code lines are all shifted down. This issue happens to be with Google Chrome only. 

![Screenshot](https://user-images.githubusercontent.com/40773830/71810792-7e815980-3073-11ea-9069-9d7fdb24b4d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
These are generally referred to the docs feedback at ...

https://github.com/MicrosoftDocs/feedback/issues

It might be related to having a zoom set, and there's an existing issue for that at ...

https://github.com/MicrosoftDocs/feedback/issues/1887

I see the same artifacts in Chrome tho ...

<img width="377" alt="Capture" src="https://user-images.githubusercontent.com/1622880/71820215-25ee9400-3054-11ea-90ab-f1ca6990de0d.PNG">

If you note that it is zoom, then add a :+1: to that existing docs engineering issue. If it looks to be something else causing it, open a new issue there for them to take a look at.
