### ISSUE TITLE
UseSignalR is deprecated

### ISSUE THREAD

**Issue by jefffhaynes** [aspnet/AspNetCore.Docs#16419]
Please update to use UseEndpoints instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Are you looking at the 2.2 or 2.1 versioned docs? As far as I can see the 3.0 and 3.1 docs are using `UseEndpoints`.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Rick-Anderson** [comment]
The meta-data shows he was looking at  `?view=aspnetcore-3.1`

**Comment by jefffhaynes** [comment]
Not sure where you're seeing that.  I'm on the 3.1 docs and they still say UseSignalR.

**Comment by Rick-Anderson** [comment]
> Not sure where you're seeing that. I'm on the 3.1 docs and they still say UseSignalR.

Where?

**Comment by jefffhaynes** [comment]
Ugh, sorry.  I was confounding AddSignalR and UseSignalR.  No more coding with a head cold.
