### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by abaljeu** [aspnet/AspNetCore.Docs#16438]
If you Ctrl+ to zoom in the page in Chrome, the highlighting no longer is precisely over the code it's supposed to highlight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abaljeu ... It's a known issue. Add your :+1: to their issue at ...

https://github.com/MicrosoftDocs/feedback/issues/1887
