### ISSUE TITLE
a little problem with understanding

### ISSUE THREAD

**Issue by fori96** [aspnet/AspNetCore.Docs#16431]
At the use another app to add users part i dont get two thing:
- what is the SeedDate? throwing me error.
- where does the second section of code go? I think it is related to my first problem but cant find out.

**Comment by guardrex** [comment]
Hello @fori96 ... Please re-open this issue using the **This page** feedback button+form at the bottom of the topic. When an issue is opened using that form, the issue will contain metadata that identifies the issue, and the author of the topic is automatically notified.
