### ISSUE TITLE
Link to incorrect article?

### ISSUE THREAD

**Issue by nathanscottdaniels** [aspnet/AspNetCore.Docs#16445]
In the second paragraph of this article is the following sentence:
`For information about how to use the Generic Host in non-web console apps, see [Hosted services]`

However, the link provided sends you to the "Background tasks with hosted services in ASP.NET Core" article.  This article does not explain how to use Generic Host in a non-ASP.NET application.

Is there really such an article anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It should probably say **_'for an example see'_** rather than the current text.

**Comment by guardrex** [comment]
@Rick-Anderson Assign me if you'd like me to touch-up that line. I'd plan to go with 'for an example, see the sample app for'-type of lingo.

**Comment by guardrex** [comment]
@Rick-Anderson Should I work this from the Generic Host topic ... create a console app example there, or should I just touch-up this line so that it says 'for an example see ...' and keep the Hosted Services cross-link?
