### ISSUE TITLE
Prerequisites link

### ISSUE THREAD

**Issue by kitkatsim** [aspnet/AspNetCore.Docs#16450]
Prerequisites links to .net core 3.0 sdk instead of 3.1.

with .net core 3.0 end of support approaching on march 2020, linking to 3.1 would be better especially to the people who are unaware of 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows#feedback)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
A possible good target ...

https://dotnet.microsoft.com/download/dotnet-core
