### ISSUE TITLE
Changing the validation message so its suitable for humans.

### ISSUE THREAD

**Issue by brent-p** [aspnet/AspNetCore.Docs#16459]
Is there a way to specify a custom validation message? 
"The field Genre must match the regular expression '^[A-Z]+[a-zA-Z"'\s-]*$'."  is not a helpful message to the user. Most programmers struggle reading regular expressions, normal humans would have no idea what this means. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, keep reading.
