### ISSUE TITLE
DbSet.Any() is marked as an internal API not meant for public use.

### ISSUE THREAD

**Issue by arnavb** [aspnet/AspNetCore.Docs#16452]
When building the code in this tutorial, I get this warning when building:

```
  SeedData.cs(16, 31): [EF1001] Microsoft.EntityFrameworkCore.Internal.EnumerableExtensions is an internal API that supports the Entity Framework Core infrastructure and not subject to the same compatibility standards as public APIs. It may be changed or removed without notice in any release.
```

I checked the api docs for EF Core 3.1, and don't see an `Any()` method. Is there some alternative way of checking whether a `DbSet` is empty?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you talking about `if (context.Movie.Any())`?

That compiles without warning.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.any

**Comment by arnavb** [comment]
That's so weird! I'm using Jetbrains Rider, and I'm seeing this warning:

<img width="883" alt="Screen Shot 2020-01-08 at 5 48 52 PM" src="https://user-images.githubusercontent.com/30810402/72022779-4af32a80-323f-11ea-9212-b7b9f6249cc3.png">

Maybe it's a Rider issue and not EF Core. I'm using the latest version of all packages. Sorry that I didn't research that DbSet is an `IQueryable`, I'm new to C# and am not aware of all the relationships between library classes.

**Comment by Leviasan** [comment]
Need to add directive "`using System.Linq`". that will allow you to use the System.Linq.Queryable.Any (...) method and there will be no such notification. Without this directive, he tries to use Microsoft.EntityFrameworkCore.Internal.EnumerableExtensions.Any (...) which is internal to EfCore.
