### ISSUE TITLE
GrpcChannel thread safety

### ISSUE THREAD

**Issue by Daniel15** [aspnet/AspNetCore.Docs#16469]
This document says:

&gt; A channel represents a long-lived connection to a gRPC service. When a channel is created it is configured with options related to calling a service. For example, the HttpClient used to make calls, the maximum send and receive message size, and logging can be specified on GrpcChannelOptions and used with GrpcChannel.ForAddress. For a complete list of options, see client configuration options.
&gt;
&gt; Creating a channel can be an expensive operation and reusing a channel for gRPC calls offers performance benefits. Multiple concrete gRPC clients can be created from a channel, including different types of clients. Concrete gRPC client types are lightweight objects and can be created when needed.

Can the same GrpcChannel be reused in multiple threads at the same time? The docs say that it can be reused across multiple requests, but does not say if this allows multiple **concurrent** requests, or just multiple sequential requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7ec3c3-918c-6ffd-1ac0-4f88b89d9295
* Version Independent ID: 1c1f72f1-3d5d-3397-c17d-1889dbae6fee
* Content: [Call gRPC services with the .NET client](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
It is thread-safe.
