### ISSUE TITLE
Add migration steps for Microsoft.Extensions.Caching.Redis

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/AspNetCore.Docs#16476]
It appears that the Redis caching extension package has been made obsolete. The last version was 2.2.0.

Link: https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#update-the-project-file)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Side note: We would only need to add something here AFAIK (migration for 3.0) because we made the update in the topics that cover caching.

**Comment by Rick-Anderson** [comment]
@guardrex  I don't see anything in https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed about this being obsoleted.

**Comment by guardrex** [comment]
I just meant that we had PRs in the past that call out the new Redis package in the topics where it applies. We didn't have a call out here in the migration topic ... if that's desirable.
