### ISSUE TITLE
Nice guide, but i suggest to change the order of Sections

### ISSUE THREAD

**Issue by ducphamhoang** [aspnet/AspNetCore.Docs#16475]
Thank for detail guide. May i suggest to change the order of sections in this guide, like:
1. IAuthorizationService
2. Requirements
3. Authorization handlers
4. What should a handler return?
5. Why would i want multiple handlers for a requirements?
6. Using a func to fulfill a policy
7. Applying policies to MVC Controllers
8. Applying policies to Razor Pages
9. Accessing MVC request context in handlers

I think it's more make sense for any new dev, or devs come here from another language. First we make Policy, then apply that policy to Controllers, and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#iauthorizationservice)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Policy-based authorization #16191
