### ISSUE TITLE
anyone got issue w/ blazor wasm please read this: https://github.com/dotnet/aspnetcore/issues/17754

### ISSUE THREAD

**Issue by zhou-xb** [aspnet/AspNetCore.Docs#16477]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zhou-xb ... They resolved the issue for the upcoming 3.2 release with https://github.com/dotnet/aspnetcore/pull/18207. We don't document every bug fix. We only usually call out bugs/fixes/workarounds when they affect many users.
