### ISSUE TITLE
Provide troubleshooting guidance in WS topic

### ISSUE THREAD

**Issue by mdddev** [aspnet/AspNetCore.Docs#16481]
The user I am using as context has log-on as service rights, however, when I try to start the service via the services.msc GUI there is the following error:

The server runs Windows 2012 R2. I compiled the .Net Core 3.1 version with both the win81-x64 runtime identifier (as was suggested for that OS by docs, https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) and also with RID win10-x64. Same result.

"Windows could not start the NAME service on Local Computer. Error 1053: The service did not respond to the start or control request in a timely fashion."

When trying to start the service via Powershell's      start-service -name "NAME"

The error is "Service NAME cannot be started due to the following error: Cannot start service NAME on computer `.`

Any help with this is greatly appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mdddev ... `NAME` should be the name of your service ... that's a placeholder.

**Comment by guardrex** [comment]
I'll use this issue to track an update to the topic that states explicitly that the dev should use their service name.

Even if you get it running ok, leave this issue open. It will close automatically when the PR merges later.

**Comment by mdddev** [comment]
Hi
Yes it's a place holder, the service name is too long to type and I deemed it unimportant to the issue at hand.
Cheers

**Comment by guardrex** [comment]
Oh, I see. Devs do sometimes take our commands too literally; and when I saw your error message with "NAME," too, I thought that was what happened.

You don't see any kind of detailed service startup error in the Event Viewer?

**Comment by mdddev** [comment]
There is.

1 entry referencing the same error message, and 1 about a timeout exceeding 30000ms. The starting of the service rellay takes long (initially that is, subsequent attempts to start it fail quicker with the same error). 

However, when I start the exe manually, it's up and running in 1-2 seconds, so I don't expect this to be an issue.

I am commuting right now, so I cannot access the machine. I will post the exact entries shortly. 

Best regards

**Comment by guardrex** [comment]
I have a feel'in that you'll be headed towards having to analyze a crash dump. The bugs/configurations where the app runs at a command prompt but fails when started by any kind of service (IIS, in Azure, as a WS, etc.) can be a pain to sort out. It's soooo much nicer when the app just fails in the Development environment on the hosting platform and spits out a reason! :smile:

In passing, I need to point out that we're not really MS Support here. We just handle the docs, and we have a huge workload. We don't have the staffing to provide product support. I'm not really happy tho with our lack of troubleshooting guidance for services. We have good coverage for IIS/Azure Apps. I think I'm going to change the focus here to provide more troubleshooting advice in this scenario. (I'll fix up the placeholder nit, too, while I'm at it.)

It sounds like you're not testing with a stock OOB template app, too. Is that correct? If that's the case, I recommend seeing if a basic worker service template app will run properly. You can use the sample app that goes with the topic (or the web app sample) or knock one up with a `dotnet new worker` command and modify as described in the topic. If that runs but your custom app doesn't, then something is obviously choking under the Service Control Manager startup. That would at least narrow it down. Also, consider lowering your logging level to `Debug` (quick-'n-dirty hack is to run the app in the Development environment ...

```csharp
Host.CreateDefaultBuilder(args)
    .UseEnvironment("Development")
    .UseWindowsService()
    ...
```

See if the additional logging provides a clue where it's choking.

**Comment by mdddev** [comment]
Thanks for your detailled comments! As you suggested, I took another look at the event viewer and luckily found the culprit! It's working now. 

The problem was, that in the code I used relative path references (base path was NAME.exe) to set-up https (path to a cusotm certificate). When running it manually, everything went fine. But when running as a service, the application event logs told me, that the referenced file could not be found. That is, because the base path apparently switched to c:\Windows\System32 which explained the error.

After putting the absolute path values into the appsettings.json and referencing them that way the problem went away and I was able to start the service with no issues at all.

Thank you for that tip!

**Comment by guardrex** [comment]
Cool ... glad you were able to solve it.

I suspect that I'll add a new *Troubleshoot* section to the topic calling out three approaches:

* Application Event Log
* Lower the logging level if running in Production environment or run the app locally in the Development environment.
* Crash dump

I suspect that a *Common Errors* section could hold the note on paths. I'll search old issues to see what else has cropped up and might go into this section.

I'll ping you on the PR. What I'd like to confirm with you is that the added text would have saved you in this scenario.

This issue will automatically close when the PR merges.
