### ISSUE TITLE
Not clear that AddHttpClient replaces AddScoped, AddTransient, etc

### ISSUE THREAD

**Issue by metoule** [aspnet/AspNetCore.Docs#16498]
It's not clear that `AddHttpClient` also registers the provided service, and that it's not necessary (and harmful!) to call `AddTransient` afterwards. For example, if you do this:

    services.AddHttpClient<GitHubService>();
    services.AddTransient<GitHubService>();

then no `HttpClient` is injected when constructing `GitHubService`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#consumption-patterns)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by bbarry** [comment]
The documentation should also mention the lifetime of the registered service (and options if applicable).

**Comment by serpent5** [comment]
@bbarry The topic already states the following:

> The typed client is registered as transient with DI.

This isn't something that can be changed (see the [source](https://github.com/dotnet/extensions/blob/release/3.1/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L328-L335)).

@Rick-Anderson Would you be interested in a PR to address @metoule's concern here, or is this with PU to determine whether or not it _should_ be addressed?

**Comment by Rick-Anderson** [comment]
@pranavkm  can you approve this proposed work. 45 second review needed.

**Comment by Rick-Anderson** [comment]
@pranavkm can you approve this proposed work. 45 second review needed.

**Comment by Rick-Anderson** [comment]
Moved to master issue: Make HTTP requests using IHttpClientFactory #16641

**Comment by Rick-Anderson** [comment]
@rynowak  Please approve or reject customers proposal.

**Comment by rynowak** [comment]
I think it's reasonable that we can make this more explicit in the docs.

**Comment by Rick-Anderson** [comment]
@serpent5  it's all yours.
