### ISSUE TITLE
Memo about how to get access token for Facebook API 

### ISSUE THREAD

**Issue by osamum** [aspnet/AspNetCore.Docs#16491]
This document does not provided information about how the application accesses authenticated user information.
Therefore, the application does not even know the name of the user who logged in with Facebook authentication.

At a minimum, it would be helpful to show you how to get an access token to use the Facebook API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
