### ISSUE TITLE
Alternatives for non-SPA login/signup pages

### ISSUE THREAD

**Issue by oatsoda** [aspnet/AspNetCore.Docs#16493]
This article is aimed at authentication for Single Page Apps.  Is there more detail on why the template requires non-SPA pages for login/signup etc? I understand that these default login/signup pages are provided by the Identity package - and that you can scaffold them out automatically if you wish to then customise/alter them - but these are still then hosted as Razor pages.  I would like to know what options there are for actually implementing this within a SPA - and if not, why is that the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406

**Comment by baselbj** [comment]
I was thinking in the same point and I think you can build you own pages.
