### ISSUE TITLE
Howto definine globally accessible BackgroundSocketProcessor?

### ISSUE THREAD

**Issue by karezza** [aspnet/AspNetCore.Docs#16490]
Given that a server-side implementation is described, a common next step would be to implement some sort of ClientManager in order to later message connected clients.  In the case where SignalR is not a natural fit, it would be helpful to describe a way to instantiate a ClientManager in such a way as to be globally accessible.  As in, accessible outside of 'Configure'.  An answer more than "use services.AddSingleton would be helpful.".  I believe I've found a way using services.AddSingleton to share a 'ClientManager' throughout the webapp but the solution does not appear to be accessible within 'Configure'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by karezza** [comment]
The answer can be found here:
https://stackoverflow.com/questions/39005861/asp-net-core-initialize-singleton-after-configuring-di

**Comment by Rick-Anderson** [comment]
@karezza  Thanks for the info.
