### ISSUE TITLE
What are query strings?

### ISSUE THREAD

**Issue by mrmowji** [aspnet/AspNetCore.Docs#16509]
I think this page needs a modification. We don't have **query strings** in a URL; we have one query string. Am I right? Each query string could have multiple query parameters separated by `&`. This is based on Wikipedia. Please let me know if I misunderstood and if Wikipedia page needs any modification.

> In the image above, the URL segment (Parameters) isn't used, the name and numTimes parameters are passed as query strings. The ? (question mark) in the above URL is a separator, and the query strings follow. The & character separates query strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for bringing this to our attention. Fixed
