### ISSUE TITLE
WsFederation Support for multiple Identity Providers?

### ISSUE THREAD

**Issue by j3fflan3** [aspnet/AspNetCore.Docs#16507]
Is there a way to integrate more than one Identity Provider at a time using AddWsFederation in .NET Core? For example, if I want to provide the option to authenticate via WsFederation with ADFS as well as Azure Active Directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks @j3fflan3, hopefully the engineering team will respond soon.
Moved to master issue: WS-Federation #16508

**Comment by blowdart** [comment]
You'd probably treat it as just another "social" login. You can add multiple providers, just not with our templates, because that's not a common scenario.  How you'd do it depends on your requirements and that's really application specific and probably outside the scope of documentation.
