### ISSUE TITLE
WsFederation Support for multiple Identity Providers?

### ISSUE THREAD

**Issue by j3fflan3** [aspnet/AspNetCore.Docs#16505]
Is there a way to integrate more than one Identity Provider using AddWsFederation in .NET Core?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
