### ISSUE TITLE
order of processing @attributes 

### ISSUE THREAD

**Issue by zhou-xb** [aspnet/AspNetCore.Docs#16518]
I got confused w/ these two explanation , please help me to understand:

(i) from https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-7/ :

Using the @attributes directive the contents of the Attribute property get “splatted” onto the input element. If this results in duplicate attributes, then evaluation of attributes occurs from left to right. In the above example if Attributes also contained a value for class it would supersede class="form-field". If Attributes contained a value for type then that would be superseded by type="text".

(ii) from this page, section Attribute splatting and arbitrary parameters:
  
The position of @attributes relative to the position of element attributes is important. When @attributes are splatted on the element, the attributes are processed from right to left (last to first). Consider the following example of a component that consumes a Child component:

ParentComponent.razor:
     &lt;ChildComponent extra="10" /&gt;

ChildComponent.razor:
     &lt;div @attributes="AdditionalAttributes" extra="5" /&gt;
     [Parameter(CaptureUnmatchedValues = true)]
     public IDictionary&lt;string, object&gt; AdditionalAttributes { get; set; }

The Child component's extra attribute is set to the right of @attributes . The Parent component's rendered
&lt;div&gt; contains extra="5" when passed through the additional attribute because the attributes are processed
right to left (last to first):  
     &lt;div extra="5" /&gt;

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zhou-xb ... I'm not sure what to add to the existing explanations and examples to further clarify. I would just be restating what's already there. I recommend that you run your own local tests of the scenarios to see the behaviors in action.

**Comment by zhou-xb** [comment]
Hi Luke,

Referring the below:

The position of @attributes relative to the position of element attributes
is important. When @attributes are splatted on the element, the attributes
are processed from right to left (last to first). Consider the following
example of a component that consumes a Child component:

ParentComponent.razor:
<ChildComponent extra="10" />

ChildComponent.razor:
<div @attributes="AdditionalAttributes" extra="5" />
[Parameter(CaptureUnmatchedValues = true)]
public IDictionary<string, object> AdditionalAttributes { get; set; }

The Child component's extra attribute is set to the right of @attributes .
The Parent component's rendered
<div> contains extra="5" when passed through the additional attribute
because the attributes are processed
right to left (last to first):
<div extra="5" />


Please inform me... "* the attributes are processed from right to left
(last to first)*" .. means the rightest or the leftest will be the result?
Thank you.

Yours sincerely,
Zhou XB

**Comment by guardrex** [comment]
They're processed **_from the right_** ...

The parent component is ...

```cshtml
<ChildComponent extra="10" />
```

If the order in the Child component is ...

```cshtml
<div @attributes="AdditionalAttributes" extra="5" />
```

... then the result is ...

```html
<div extra="5" />
```

If the order in the Child component is ...

```cshtml
<div extra="5" @attributes="AdditionalAttributes" />
```

... then the result is ...

```html
<div extra="10" />
```

That's what the example shows. Run the example locally. That's the result you will get if you set up a test app there and run this scenario.

**Comment by zhou-xb** [comment]
So, can I conclude that processing is from right and will ignore the same attribute to the left?

**Comment by guardrex** [comment]
Yes

**Comment by zhou-xb** [comment]
Thank you very much. Still, I think some will consider this is processing from left to right, because the last rightmost among same name attributes witll come out as the result. Or, I suggest you add ".. from right to left and only take the first occurance of same name attributes ..". Sorry to be "talkative"

**Comment by guardrex** [comment]
The framework has to know about the right-most attribute **_first_** in order to use it as it checks each attribute moving to the left. Therefore, it is processing from right-to-left. Besides, the example makes it clear.
