### ISSUE TITLE
Configuration enhancements

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16515]
Took a look at Configuration topic remarks for default configuration (`CreateDefaultBuilder`) for app settings files after @nicksav left a remark at https://github.com/aspnet/AspNetCore.Docs/issues/11224#issuecomment-573399264. Not sure what you're asking for there, @nicksav, but I see a couple of items for improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by nicksav** [comment]
Hey Thank you for you reply.
I am struggling to get Windows Service to locate app.settings.json. This is what docs are saying:
![image](https://user-images.githubusercontent.com/9266365/72227307-a67a3b00-35e6-11ea-8e1a-885a23c52ea5.png)

Many examples for Web App, but none for console app (or Windows Service).
![image](https://user-images.githubusercontent.com/9266365/72227320-c9a4ea80-35e6-11ea-982d-c5769c53a86f.png)

**Comment by guardrex** [comment]
I haven't checked that exact scenario myself. Can you set the `SetBasePath` with an **absolute path** as we called out in the instruction and see if that works? Use the path right to the folder where the *appsettings.json* file is in the deployment.

```csharp
var builder = new ConfigurationBuilder()
    .SetBasePath("c:\myapp")
    .AddJsonFile("appsetting.json");
```

I'm curious to know what it thinks the `ContentRootPath` is ... you might want to log that out and see what it thinks that is. The reason it probably isn't working is that `ContentRootPath` isn't the path to where the config file is ... *guessing* 🤔. Log that out ...

```csharp
var logger = host.Services.GetRequiredService<ILogger<Program>>();
logger.LogInformation("ContentRootPath: {ContentRootPath}", env.ContentRootPath);
```

... you'll need the built `host` for that ... https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-logs-in-the-program-class

**Comment by nicksav** [comment]
All parameters from env. are null. Setting absolute path will work, but I
am after a generic solution, as during instalation users might decide to
change the default instalation path.

**Comment by guardrex** [comment]
Ah ... yeah ... not populated until the `HostBuilder` is created. If you go this way ...

```csharp
var host = CreateHostBuilder(args).Build();

// ... other code

host.Run();
```

... you should get it populated in there. Or, just create a new `HostBuilder` directly if you're trying to avoid the `CreateHostBuilder` method approach ... you can probably go the `var host = new HostBuilder().Build();` route.

**Comment by guardrex** [comment]
It's true ... we're rather **_web-ish_** and **_Kestrel/IIS-ish_** around here. As more feedback comes in, we address the rough spots with other scenarios. I might need to add something for this ... as you suggest an example for that section of the topic. I'll look closer on Monday.

**Comment by guardrex** [comment]
Since `CreateDefaultBuilder` is probably going to return the *system32* directory based on `GetCurrentDirectory`, the example we'd probably show is using `CreateHostBuilder` with `Host.ConfigureAppConfiguration` that sets the base path to the app's deployment folder (i.e., do what you did, but do it inside of `Host.ConfigureAppConfiguration`).

Yeah ... I'll take a look in the morning and add a bit for this scenario with example code. It probably won't be a console app example, but it will be better than what we have now ... which is *nothing*.

**Comment by nicksav** [comment]
Ok, better will wait for sample.

**Comment by guardrex** [comment]
Will probably go something like this ...

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .UseWindowsService()
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                config.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath);
                config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            })
            .ConfigureServices((hostContext, services) =>
            {
                services.AddHostedService<Worker>();
            });
}
```

... if it will work. 🤞🍀

It assumes that we get a good `ContentRootPath` there ... **_not_** to *system32*.

**Comment by nicksav** [comment]
Sorry to be a pain:) but what if we use old style Windows Service deployment?
![image](https://user-images.githubusercontent.com/9266365/72231823-29ac8880-3609-11ea-9032-a79660269ae3.png)
Do you recon we better move to new Worker model?

**Comment by guardrex** [comment]
* The *appsettings.json* and *appsettings.{Environment}.json* files are properly consumed by `CreateDefaultBuilder`.
* `ContentRootPath` is correct in `ConfigureAppConfiguration`. The call to `SetBasePath` is not required for any **new** app settings files. If there were some other settings file to consume, say *anothersettingsfile.json*, it can be consumed in `ConfigureAppConfiguration`.

  ```csharp
  public class Program
  {
      public static void Main(string[] args)
      {
          CreateHostBuilder(args).Build().Run();
      }

      public static IHostBuilder CreateHostBuilder(string[] args) =>
          Host.CreateDefaultBuilder(args)
              .UseWindowsService()
              .ConfigureAppConfiguration((hostingContext, config) =>
              {
                  config.AddJsonFile("anothersettingsfile.json");
              })
              .ConfigureServices((hostContext, services) =>
              {
                  services.AddHostedService<Worker>();
              });
  }
  ```

The pattern is the same as for non-service apps, so there's nothing special to document in the recommended scenario.

WRT the path information the topic, I'll take a further look at that shortly. We surely don't want that content to confuse anyone into thinking that they need to take special action in the most common use cases (i.e., an app based on the worker server or web app templates following the guidance in the WS and Configuration topics).

WRT your last remark, you can see how `ServiceBase` is used by the framework by searching the engineering repo for it: https://github.com/dotnet/aspnetcore/

**Comment by nicksav** [comment]
Perfect!
Works fine now!
