### ISSUE TITLE
Scaffolded Razor Pages

### ISSUE THREAD

**Issue by LorenMayhew** [aspnet/AspNetCore.Docs#16517]
I did not understand: test the app by clicking on the RpMovie link. 
Test the other links (Home, RpMovie, Create, Edit, and Delete). 
I clicked on RpMovie in the code and nothing happened. Could not find any of the other links. Do not know what they are or what they are supposed to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by LorenMayhew** [comment]
Dear Rick:

I think maybe I am having a terminology problem. I have gone back through the tutorial and rechecked everything and all is as instructed in the tutorial up to “Update the Layout” on the Scaffolded Razor Pages tutorial.

Until I run into the instruction: Save your changes, and test the app by clicking on the RpMovie link. I understand “Save your changes.” But I am totally befuddled by “test the app by clicking on the RpMovie link” What exactly is the RpMovie link, where is it and what is supposed to happen if I click on it?

Ditto for “Test the other links (Home, RpMovie, Create, Edit, and Delete). What exactly are these links and where do I find them?

[cid:image003.png@01D2E416.AF264520]Loren Mayhew
Mail: PO Box 69654 ● Oro Valley AZ 85737-0019 ● USA
Email: Biz@Mayhews.us<mailto:Biz@Mayhews.us>
Telephone: +1 (520) 289-0700; Skype/WhatsAPP: Loren Mayhew

**Comment by Rick-Anderson** [comment]
Keep going through the tutorial, you'll figure it out.
