### ISSUE TITLE
Reusable UI relies on MVC

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#16527]
The comments below were machine-translated  

@qinqoushui commented on [Mon Jan 13 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/236)

In CORE3.1, UseEndpoints is used by default, which will cause the Razor class library to not work properly. You need to disable UseEndpoints and re-enable MVC.
services.AddMvc (r => r.EnableEndpointRouting = false);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

@srvbpigh commented on [Mon Jan 13 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/236#issuecomment-573509117)

Hello, @qinqoushui
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@qinqoushui  that's not true. Create a new  3.1  web app with authorization. The auth system uses the RCL.

Having said that, this doc needs to be updated for 3.1. I'll schedule that for the next sprint.
