### ISSUE TITLE
Work with a database and ASP.Net Core

### ISSUE THREAD

**Issue by LorenMayhew** [aspnet/AspNetCore.Docs#16525]
SQL Server Object Explorer does not show Movie-1&gt;Tables&gt;dbo.Movie as in your picture. I don't even have Movie-1. So I guess this is as far as I can go with this tutorial. Darn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there and not important for the tutorial.
