### ISSUE TITLE
"The instructions volume mount certificates into containers" is a confusing sentence: what is really meant?

### ISSUE THREAD

**Issue by jnpwly** [aspnet/AspNetCore.Docs#16538]
I wonder whether something along the lines of the following is actually what is actually meant?

> You _*could*_ add certificates into container images with a COPY command in a Dockerfile, _*but*_ copying certificates into an image isn't recommended for the following reasons:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CrispyBaguette** [comment]
I think this means that the instructions in the following sections make use of Docker volume mounts (-v flag). I agree that this sentence can be a bit confusing.
