### ISSUE TITLE
Serialisation of objects in Session

### ISSUE THREAD

**Issue by KalpeshPopat** [aspnet/AspNetCore.Docs#16539]
Hi,

Referring to this document
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1

I have found there are many issues with serialising objects and storing them in sessions, i have highlighted my points [here](https://github.com/dotnet/aspnetcore/issues/18159) and have provided an alternate approach [here](https://technologymythbuster.blogspot.com/2020/01/storing-objects-in-session-in-aspnet.html).

In the documentations - i feel you should either remove the suggestion to use serialisation as a workaround to store objects in session or should add a warning "this solution should be implemented with care and recommended only when the serialised objects in the session are readonly".

The sample code also should have that warning.

Cheers,
Kalpesh

**Comment by KalpeshPopat** [comment]
Even this document should highlight the key difference in session behaviour for those like me who are planning to migrate from Asp.Net Framework to Asp.Net Core

https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-3.1

**Comment by guardrex** [comment]
@KalpeshPopat It's best if you close this and re-open using the this page feedback button+form at the bottom of the topic. It will ping the author automatically.
