### ISSUE TITLE
Slight mistake in sample `RandomRetryPolicy` implementation

### ISSUE THREAD

**Issue by stanimirsellercloud** [aspnet/AspNetCore.Docs#16533]
The sample code uses the expression `_random.Next() * 10` to generate a random number between 0 and 10 but the range of integers is much larger.

Can you change this to `_random.NextDouble() * 10`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Sure, PRs are welcome if you're interested in contributing.

**Comment by Rick-Anderson** [comment]
@stanimirsellercloud  this is just a sample. Use whatever range you like.

**Comment by stanimirsellercloud** [comment]
> @stanimirsellercloud this is just a sample. Use whatever range you like.

Rick, a lot of developers will follow the official SignalR + .NET client page which references the sample code (I did) -- the problem is that the code does not do what it is intended to.

I had to debug it before I realised it was wrong - it's not generating the range of seconds it's supposed to.

**Comment by Rick-Anderson** [comment]
@stanimirsellercloud 

Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
Lots of problems with this tutorial. 

* Need to add link to https://docs.microsoft.com/en-us/javascript/api/@microsoft/signalr/iretrypolicy

**Comment by wadepickett** [comment]
@Rick-Anderson , adding the link and moving the code comments in the code snippet in the doc back out into the text so it gets localized in the PR I currently have open, and tested the code.

**Comment by wadepickett** [comment]
Correction, just saw you closed my PR AFTER I already entered my last comment...
