### ISSUE TITLE
Chained bind example: characters get out of order

### ISSUE THREAD

**Issue by mfluehr** [aspnet/AspNetCore.Docs#16531]
There's a problem with the "chained bind" (`PasswordField` component) example. When I type something into the field, and then rapidly type some characters into the middle of the field, the caret will suddenly jump to the end, resulting in the text getting out of order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mfluehr ... The product unit should take a look at this. Open an issue for the engineers at :point_right: https://github.com/dotnet/aspnetcore/issues.
