### ISSUE TITLE
Session changes

### ISSUE THREAD

**Issue by KalpeshPopat** [aspnet/AspNetCore.Docs#16543]
Session is one of the key instrument to manage state of an application and those migrating from asp.net framework need to know that they won't be able to store objects in the session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@KalpeshPopat You can use session. We have a topic to cover it and other ways to preserve state ...

https://docs.microsoft.com/aspnet/core/fundamentals/app-state

... it's just that session has/is rapidly falling out of favor in a lot of circles. You'll probably be seeing it less and less in samples/tutorials here and around the Net.
