### ISSUE TITLE
Clarify for Server vs. WebAssembly

### ISSUE THREAD

**Issue by RedDeathGitHub** [aspnet/AspNetCore.Docs#16544]
I was thinking, as I'm reading through all the docs here :)...
and it would be so much easier to to read it if you could just have separate documentation for Server and WebAssembly.
I know there are often remarks to the side about it, but there is no clear way just to filter out info about Server, if I'm only interested in WebAssembly.

Like in this article we start with "Blazor Server is a stateful framework" - does that mean these is nothing here about WebAssembly error handling? I have to search for "WebAssembly" or scroll thought the whole thing to get an idea.

So my take on how to solve it:
- a tab at the top of the page to select one or the other, and when selected you only see relevant information - a different version of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.0&source=docs#feedback)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@RedDeathGitHub It was an early decision when Blazor Server first hit the scene. Management decided that they share enough scenarios that it would create a large amount of duplicated content to write and maintain separate topics for each hosting model.

WRT tabs, that's not a supported scenario. The docs management wouldn't permit that doc format with the tab control. Tabs are mostly used for languages and tooling. We typically would address the scenario with separate topics.

Usually, we state explicitly when something applies to one hosting model or the other ...

**_Except here!_** 🙈 ... *Yikes! Missed a spot!*

I'll address this topic shortly on this point and clarify it. Thanks for commenting.

**Comment by RedDeathGitHub** [comment]
OK, thanks for the answer!
