### ISSUE TITLE
Error while calling services.AddRazorPages()

### ISSUE THREAD

**Issue by rsganta** [aspnet/AspNetCore.Docs#16552]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'IServiceCollection' does not contain a definition for 'AddRazorPages' and the best extension method overload 'MvcRazorPagesMvcCoreBuilderExtensions.AddRazorPages(IMvcCoreBuilder)' requires a receiver of type 'IMvcCoreBuilder'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
