### ISSUE TITLE
When using endpoint routing, how do you enable cors with the default policy?

### ISSUE THREAD

**Issue by bbarry** [aspnet/AspNetCore.Docs#16569]
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-endpoint-routing

1. do you not need `app.UseCors();` anymore?
2. do you not need `services.AddCors(...);` if you use the overload that configures a policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-endpoint-routing)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I believe `app.UseCors();` enables the default policy for all endpoints. At any rate this is a dup of #13423
@pranavkm  can you confirm and give me an ETA on when we can update this article? You just need to make a quick pass through it, I'll finish it up.
