### ISSUE TITLE
"C++ client" link points to obsolete repository

### ISSUE THREAD

**Issue by mmarinchenko** [aspnet/AspNetCore.Docs#16567]
The link should point to https://github.com/aspnet/SignalR-Client-Cpp

See https://github.com/dotnet/aspnetcore/issues/5301#issuecomment-499985458 for reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Thanks @mmarinchenko ... I'll patch that up right now.
