### ISSUE TITLE
Is Worker service project type supported on Azure AppService?

### ISSUE THREAD

**Issue by PiotrPerak** [aspnet/AspNetCore.Docs#16579]
If it is how it should be deployed from Azure Release Pipelines? It seems that it is not. Once deployed using Azure App Service deploy task it just doesn't start. More info also in my question here - https://stackoverflow.com/questions/59770756/workerservice-deployed-to-azure-app-service-is-not-starting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @PiotrPerak, *Indeed,* "warming" **_WEB_** apps in Azure Apps (and IIS) has been an occasional question on the repo. We normally recommend the [Application Initialization Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#application-initialization-module) for that scenario. *That's not suitable tho in this case.*

I checked their docs, too, for this scenario, and I couldn't find anything specific for a background worker outside of perhaps using the `StartupCommand` to run the app post deployment. Did you try passing `dotnet Worker.dll` as the `StartupCommand`?
I'm not familiar with Azure Release Pipelines deployments. SO is a good spot to ask. For immediate feedback, you can also hit up the devs in support chats, such as [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/) and [ASP.NET Gitter](https://gitter.im/aspnet/Home). You could also try asking at the bottom of the [Azure App Service Deploy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment) topic. If you don't get an answer there, close the issue and open a new one at the bottom of [Build, test, and deploy .NET Core apps](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#package-and-deliver-your-code).



I like the idea of adding something to this topic to cover this given that it's not immediately evident.

**Comment by guardrex** [comment]
@Tratcher TL;DR ... a `worker` template background services app deployed via Azure Pipelines apparently doesn't start automatically. Do you know if passing `dotnet {assembly}.dll` in the `StartupCommand` parameter of the pipeline task will fire up the app after the deployment? I could test ... I'd be willing to test, but I'm 🏃😅 at the moment, so it would get pushed off for weeks/months if I have to go that far to find out. Alternatively, I could try to reach an Azure pipelines engineer.

**Comment by Tratcher** [comment]
As far as I know App Service is only for IIS based websites (or linux & Kestrel), it's not clear that worker services make sense in that environment. @shirhatti @glennc

**Comment by guardrex** [comment]
@Tratcher Ur question got stuck. If you feel good about not surfacing anything for this scenario, then I'll close this issue and keep an :ear: open for similar feedback/questions.

**Comment by PiotrPerak** [comment]
In the mean time I switched to ASP MVC Core app. Later I got answer here. You need to create special folder structure for this to work - https://stackoverflow.com/a/59787146/679340. I don't like it, it's not documented anywhere and sometime it just might stop working.

**Comment by guardrex** [comment]
@PiotrPerak Did you try passing `dotnet {assembly}.dll` in the `StartupCommand`?

**Comment by PiotrPerak** [comment]
No I didn't. I switched to other app kind before I received response here.

**Comment by guardrex** [comment]
I'd test it to see if it works, but I just don't have 🕐 these days. 🏃🏃🏃🏃🏃🏃🏃🏃🏃🏃😅

**Comment by guardrex** [comment]
Looks like the best we can do here is cross-link the WebJob coverage in the *Additional Resources* section of the Background Tasks/hosted services topic. I'll do that now.
