### ISSUE TITLE
Add React Authorization Examples

### ISSUE THREAD

**Issue by cambo2015** [aspnet/AspNetCore.Docs#16582]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
1. Asp.net React Authorization

- Tell us what docs you found that didn't address your concern.

Asp.net simple authorization
**Describe the new topic**

Explains how to to Authorization in asp.net with React

- Explain why this topic is needed.

Asp.net is used to build apis fast and React js is used by many in the industry to create SPA web applications. I would like to create an admin page but I am unsure how to go about it. I need a tutorial or documentation for react authorization.

- Suggest a location in the Table of Contents.

* Set Up an Admin Account via VS or CLI
* Simple React Authorization
* React Role Baised Authorization
* Create an Admin page

- Write an abstract. In one **short** paragraph, describe what this topic will cover.

     The topic will cover how to impliment React baised authorization with ASP.NET Core 3+ and walk the user through on how to create a very simple admin page. 

- Create an outline for the new topic. 
We'll help review the outline and approve it before anyone writes a topic.

 * Set Up an Admin Account via VS or CLI
* Simple React Authorization
* React Role Baised Authorization
* Create an admin page

Thank You!

**Comment by Rick-Anderson** [comment]
All we have is [Authentication and authorization for SPAs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1) and we have no plans to add React specific tutorials.
