### ISSUE TITLE
Aren't WebHostBuilder used in .net core 3.1?

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#16584]
@JingLi-kooboo commented on [Thu Jan 16 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/239)

Aren't WebHostBuilder used in .net core 3.1? Don't you need to replace it with IHostBuilder？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [ASP.NET Core 中的集成测试](https://docs.microsoft.com/zh-cn/aspnet/core/test/integration-tests?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Fri Jan 17 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/239#issuecomment-575445379)

Hello, @JingLi-kooboo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
Yes, `IHostBuilder` is used. Look at the 3.1 version of the sample app.

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/src/RazorPagesProject/Program.cs#L41
