### ISSUE TITLE
Does the example code violate "Don't inject a scoped service via constructor injection"?

### ISSUE THREAD

**Issue by ytingyeu** [aspnet/AspNetCore.Docs#16586]
This page has this warning in section **Service lifetimes**

> When using a scoped service in a middleware, inject the service into the Invoke or InvokeAsync method. Don't inject via constructor injection because it forces the service to behave like a singleton.

However the last example code in section **Overview of dependency injection** injects some scoped objects into `IndexModel` via constructor. 

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    
    services.AddScoped<IMyDependency, MyDependency>();
    services.AddScoped<IOperationScoped, Operation>();
    
    ...
}
```

```
public class IndexModel : PageModel
{
    private readonly IMyDependency _myDependency;

    public IndexModel(
        IMyDependency myDependency,         
        IOperationScoped scopedOperation,
        ... )
    {
        _myDependency = myDependency;
        ScopedOperation = scopedOperation;
        ...

    }
```

Doesn't this injection violate the warning above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#overview-of-dependency-injection)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ytingyeu ... that's not a [**_middleware_**](https://docs.microsoft.com/aspnet/core/fundamentals/middleware/). It's fine to inject a scoped service into a controller or page model **_class_**.
