### ISSUE TITLE
Microsoft.AspNetCore.DataProtection is v3 not compatible with azure functions anymore

### ISSUE THREAD

**Issue by petrce** [aspnet/AspNetCore.Docs#16581]
according to this: https://github.com/Azure/azure-functions-host/issues/5447
DataProtection since version 3 is not compatible with Azure Functions anymore (v2 is fine), I think the documentation should mention it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7425f4e-80fe-7972-7e7f-83948811c078
* Version Independent ID: ec6921d2-b16c-d1af-1267-388e08599a89
* Content: [Compatibility in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/compatibility/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/compatibility/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@petrce  doesn't [Data Protection: DataProtection.AzureStorage uses new Azure Storage APIs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#data-protection-dataprotectionazurestorage-uses-new-azure-storage-apis) explain it?

**Comment by Leon99** [comment]
@Rick-Anderson could you clarify how your link is related to the issue @petrce referenced?

**Comment by Rick-Anderson** [comment]
@Leon99  My link states what @petrce  want's documented. It's already documented.

**Comment by Leon99** [comment]
Hmm @Rick-Anderson I'm confused. Your link states that "DataProtection.AzureStorage uses new Azure Storage APIs" and nothing about Microsoft.AspNetCore.DataProtection being incompatible with AF v3.

**Comment by hiranamarasinghe** [comment]
> Hmm @Rick-Anderson I'm confused. Your link states that "DataProtection.AzureStorage uses new Azure Storage APIs" and nothing about Microsoft.AspNetCore.DataProtection being incompatible with AF v3.



> according to this: [Azure/azure-functions-host#5447](https://github.com/Azure/azure-functions-host/issues/5447)
> DataProtection since version 3 is not compatible with Azure Functions anymore (v2 is fine), I think the documentation should mention it...
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: e7425f4e-80fe-7972-7e7f-83948811c078
> * Version Independent ID: ec6921d2-b16c-d1af-1267-388e08599a89
> * Content: [Compatibility in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/?view=aspnetcore-3.1)
> * Content Source: [aspnetcore/security/data-protection/compatibility/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/compatibility/index.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-security**
> * GitHub Login: @Rick-Anderson
> * Microsoft Alias: **riande**

I was able fix this issue while using IWebJobsStartup instead of FunctionsStartup. The issue seems to be IFunctionsHostBuilder DI container
