### ISSUE TITLE
gRPC-Web

### ISSUE THREAD

**Issue by cveld** [aspnet/AspNetCore.Docs#16598]
During .NET Conf: Focus on Blazor, Steve Sanderson showed us a setup with gRPC-Web. His sample solution can be found here: https://github.com/SteveSandersonMS/presentation-2020-01-DotNetConf/blob/master/samples/aspnetcore/blazor/FlightFinder
Strangely I can't find any documentation on the .NET package he used: Grpc.AspNetCore.Web. Is this something that will be added to this page or section? The interesting thing about gRPC-Web is that it provides an http 1.1 implementation of the gRPC transport. I wonder whether the gRPC-Web endpoint is provided next to the regular gRPC endpoint? I like the fact that there is no extra proxy required compared to other gRPC-Web setups I have seen mostly based on a nodejs stack, e.g. https://grpc.io/docs/tutorials/basic/web/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
Hello @cveld ... It's *pre-preview* at this time, so official docs will come later. You may already have these links, but I'll put the cross-references here to the blog post and PR ...

* https://blog.stevensanderson.com/2020/01/15/2020-01-15-grpc-web-in-blazor-webassembly/
* https://github.com/grpc/grpc-dotnet/pull/695

Specifically to your question, the blog states ...

> First, since the gRPC-Web packages haven’t been published to NuGet.org yet, for now you’ll need to add a couple of temporary package feeds to get the nightly previews.

... and the post goes into all of the current implementation steps.

@Rick-Anderson will determine if this issue should track the work. If not tho, @cveld, a new issue will be opened to track it later.

**Comment by Rick-Anderson** [comment]
Closing as this hasn't been released yet.

**Comment by guardrex** [comment]
We have a PR for this issue now ... in the general case, not directly for Blazor.

**Comment by wadepickett** [comment]
Verified package available now.  Moved the new topic to publish per @JamesNK approval.  It will be available soon once the publishing system gets it there.

**Comment by wadepickett** [comment]
Published here:  [gRPC in browser apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1)
