### ISSUE TITLE
Step 3-6 "...execute dotnet run from the app's project folder" results in error

### ISSUE THREAD

**Issue by gituser227** [aspnet/AspNetCore.Docs#16601]
Following the getting started steps, when reaching 3-6 "If using a Blazor WebAssembly app, execute dotnet run from the app's project folder." results in several errors, including  
/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003: The specified task executable "dotnet" could not be run. System.ComponentModel.Win32Exception (2): No such file or directory  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@gituser227 Open an issue with the product unit for that one ...

https://github.com/dotnet/aspnetcore/issues

... include your system details.
