### ISSUE TITLE
Code Behind: add examples inheriting from ComponentBase

### ISSUE THREAD

**Issue by neil-rubens** [aspnet/AspNetCore.Docs#16606]
in https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#partial-class-support

there are no examples that show classes inheriting from ComponentBase
I though it is a best practice; e.g.: https://www.telerik.com/blogs/using-a-code-behind-approach-to-blazor-components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#partial-class-support)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @neil-rubens ... For 3.0, *yes*, but now we have partial class support (>=3.1) ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0#partial-class-support

**Comment by neil-rubens** [comment]
@guardrex thanks a lot for a quick reply
p.s. it's one of the reasons why am starting to use Azure more often than AWS
