### ISSUE TITLE
Duplicate content in RP introduction.

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#16603]
In the "Custom routes section", there's the following explanation:

> You can change the query string `?handler=JoinList` in the URL to a route segment `/JoinList` by specifying the route template `@page "{handler?}"`.
>
> If you don't like the query string `?handler=JoinList` in the URL, you can change the route to put the handler name in the path portion of the URL. You can customize the route by adding a route template enclosed in double quotes after the `@page` directive.

I think that first line could be removed, as it appears to be restated in the following line. The code snippet that follows shows and highlights the `@page "{handler?}"` change too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio#custom-routes)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Agreed. We like to remove `you` when it doesn't add to clarity. How about

If you don't like the query string `?handler=JoinList` in the URL,  change the route to put the handler name in the path portion of the URL.  The route can be customized by adding a route template enclosed in double quotes after the `@page` directive.

**Comment by serpent5** [comment]
Yeah, looks good to me.
