### ISSUE TITLE
The mvc tutorial used to be amazing back in the day.. this is nonsense

### ISSUE THREAD

**Issue by Seabizkit** [aspnet/AspNetCore.Docs#16626]
starting from scratch core - Web Application with user individual user auth, how the hell do i see where the account/login goes... they really need to fix this! i believe it been like this since like v 2x but for crying out loud... i have scaffolded the views... and for the life of me i can not connect the dots. Where is the controller which manages the login view. (Identity/Pages/Login.cshtml) i mean honestly this is really bad. We need more 101 on how things had change. this is what on the page    &lt;form id="account" method="post"&gt; how do i see where this goes.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio

**Comment by Seabizkit** [comment]
FYI, the main sentence missing which should be in bold or something is the previous controllers type files , " are now in code be hide files. aka they are now in code behind for the views... expand the view file in visual studio to see the code which is binding to the view."

**Comment by Seabizkit** [comment]
> See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio

thanks looks gd so far
