### ISSUE TITLE
Manual conversion of X-ARR-ClientCert in example is broken

### ISSUE THREAD

**Issue by mkreidenweis** [aspnet/AspNetCore.Docs#16621]
The `StringToByteArray` doesn't actually work with Azure Web Apps. 
According to https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth#access-client-certificate the `X-ARR-ClientCert` header is base64 encoded. That's also what the ASP.NET Core tests check for: https://github.com/dotnet/aspnetcore/blob/116799fa709ff003781368b578e4efe2fa32e937/src/Security/Authentication/test/CertificateTests.cs#L304

The complete `HeaderConverter` code should be removed from the example. Then it works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by damienbod** [comment]
Hi @mkreidenweis 

I have this fixed in this PR

https://github.com/aspnet/AspNetCore.Docs/pull/16354/files#diff-3806bd9578403020f5bba44e09aa31e7R243

waiting for the approval

Greetings Damien

**Comment by blowdart** [comment]
Is there a reason you can't use the helper function in cert auth itself?

**Comment by damienbod** [comment]
@blowdart Not sure I understand your question, but I could completely remove the HeaderConverter or comment this out as this is the default.

```csharp
services.AddCertificateForwarding(options =>
{
	options.CertificateHeader = "X-ARR-ClientCert";
	//options.HeaderConverter = (headerValue) =>
	//{
		
	//    X509Certificate2 clientCertificate = null;
	//    if (!string.IsNullOrWhiteSpace(headerValue))
	//    {
	//        byte[] bytes = Convert.FromBase64String(headerValue); 
	//        clientCertificate = new X509Certificate2(bytes);
	//    }

	//    return clientCertificate;
	//};
});
```

**Comment by blowdart** [comment]
We have mdidleware :) https://github.com/dotnet/aspnetcore/blob/b75b892eac51be8b2f0eb9dc9b47537fc02001c9/src/Middleware/HttpOverrides/src/CertificateForwardingMiddleware.cs

**Comment by mkreidenweis** [comment]
Cool you already have a PR open, esp. because it also fixes the client part of the documentation. :-)

> Not sure I understand your question, but I could completely remove the HeaderConverter or comment this out as this is the default.

Yes, I'd prefer you remove the `HeaderConverter` part completely from the example. After all the example is explicitly referring to Azure Web Apps, where there's no custom HeaderConverter necessary, as base64 decoding is the default.
https://github.com/aspnet/AspNetCore.Docs/pull/16354/files#diff-3806bd9578403020f5bba44e09aa31e7L229
https://github.com/dotnet/aspnetcore/blob/b75b892eac51be8b2f0eb9dc9b47537fc02001c9/src/Middleware/HttpOverrides/src/CertificateForwardingOptions.cs#L28

**Comment by damienbod** [comment]
@blowdart oh... Thanks. So we need nothing for Azure deployments then, it already works. I will remove this for the Azure exmaple and add back the custom forwarding in a separate paragraph for non Azure deployments

**Comment by damienbod** [comment]
fixed with this, I think we can close this now

https://github.com/aspnet/AspNetCore.Docs/pull/16354
