### ISSUE TITLE
Where is the controller?

### ISSUE THREAD

**Issue by DanJ210** [aspnet/AspNetCore.Docs#16630]
Everything is scaffolded. I already had a DB context and I have a DAL library but didn't know how to use my current data context so now I have two of them... Not sure what will happen yet. All seems to be in place, I have the area with the views, I have a second startup file which is strange and I'm not sure how that is called and used, but running the app and trying the "Register" and "Login" links just refresh the page. Why? I'm assuming that there's no AccountController.cs anywhere. Am I supposed to add that when I have no documentation on it? Or am I mis-understanding something? I thought this was supposed to tell me what to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc:

The generated project provides ASP.NET Core Identity as a Razor Class Library. 

See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio

**Comment by DanJ210** [comment]
@Rick-Anderson could you elaborate a bit please? Are you saying it provides everything EXCEPT the controller? I can scaffold out all of the pages that's not an issue. It's that I've followed the docs and have everything added but when I click "Register" or "Login" the page simply refreshes, nothing happens. Is the `AccountController.cs` hidden in the class library? If so then why is it not being used? I'd like to think that docs cater to beginners as much as it does to the advanced user.

So I'm asking what I'm missing from the doc if I've followed it yet "Register" and "Login" doesn't go to any of the pages.
