### ISSUE TITLE
Problem details for error status codes

### ISSUE THREAD

**Issue by ByteDev** [aspnet/AspNetCore.Docs#16631]
Isn't there supposed to be a "Problem details for error status codes" section? Seems to be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
That wasn't planned. We'll look at this again in the next doc sweep and also review customer interest.

**Comment by scottaddie** [comment]
@ByteDev The section you mention only applies to ASP.NET Core 2.2 or later. That section's link (within the **ApiController attribute** section) is currently bring displayed for 2.1 as well, which is a problem. I'll take care of that problem right now.
