### ISSUE TITLE
How to create named clients at runtime / after Startup

### ISSUE THREAD

**Issue by cmbankester** [aspnet/AspNetCore.Docs#16638]
The examples all show how to create a single named client for use during the lifetime of the application, but is there a recommended solution for using HttpClientFactory with separate instances of a named client, having different URLs (e.g. with the user of the application entering a URL for a named client)? For example, if the application needs to be able to access N different instances of an API, is there a way to use a dependency-injected HttpClientFactory to manage those as named clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Make HTTP requests using IHttpClientFactory #16641
