### ISSUE TITLE
RCL static web content from dynamically loaded dll (not pre referenced by consuming application)

### ISSUE THREAD

**Issue by RobertAcksel** [aspnet/AspNetCore.Docs#16632]
To me it is unclear how i can make static web content available to an application which does not references during build time. 
I am instead loading the RCL as an plugin at runtime.
The documentation is missing steps to configure an application to consume the library when loaded in such a way.

The documentation says 'When the RCL is built, a manifest is produced that describes the static web asset locations. The consuming app reads the manifest at runtime to consume the assets from referenced projects and packages.'
It does not say what manifest this is. Is it the 'MyApp.StaticWebAssets.xml' xml file produced by the consuming app in which the static asset paths are mapped to the absolut source paths? The behavior is different when publishing and when debugging.
When the consuming app is producing this map file at build time. 
How is loading the library as a plugin with static webasset locations mapped even possible than? 
It says 'When the RCL is built'. Which manifest is it? Is it embedded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Master issue: Create reusable UI using the RCL project #16639

**Comment by tbebekis** [comment]
This issue, of using static files (js, css) from a dynamically loaded RCL, is not yet resolved and should remain open.

I can imagine a number of reasons as to why someone wants to use razor libraries in a solution.

But the most valuable case is when a library is loaded dynamically, as a plugin. Lets say an e-Commerce solution providing a number of Tax or Shipping Charges calculation plugins or Payment plugins, for the administrator to choose from.

By resolving this issue the platform will gain a lot.

**Comment by tbebekis** [comment]
Anyway, here is my solution to the problem of [dynamically loaded RCLs with static files support](https://github.com/tbebekis/AspNetCore-3x-RCL-plugins) in case anyone wants to look at it.
