### ISSUE TITLE
Route Name use is unclear

### ISSUE THREAD

**Issue by Leon99** [aspnet/AspNetCore.Docs#16646]
What exactly is the role of Http[Verb]Attribute.Name? From reading the note

&gt; Contrast this with the conventional default route, which defines the id parameter as optional ({id?}). This ability to precisely specify APIs has advantages, such as allowing /products and /products/5 to be dispatched to different actions.

I suspect that it's only used by the routing subsystem to give a unique name to different method overloads. But surely that unique name could be generated automatically behind the scenes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#attribute-routing)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc:
Route names can be used to generate a URL based on a specific route. Route names have no impact on the URL matching behavior of routing and are only used for URL generation.

**Comment by Leon99** [comment]
@Rick-Anderson so what does "Route names can be used to generate a URL based on a specific route" mean? What role do they play in the URL generation? What will change if Name is specified vs. if it's not specified?

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#url-generation

However, that doc is in PR now.

**Comment by Leon99** [comment]
Aha, so it's to be referenced by `Url.RouteUrl`? It'd be nice then to have 

> generate a URL based on a specific route

hyperlink to https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#generating-urls-by-route, otherwise, it's hard to understand what it's about.
