### ISSUE TITLE
Most services are not available until the Configure method is called. 

### ISSUE THREAD

**Issue by abdooay** [aspnet/AspNetCore.Docs#16649]
There is a line in the docs that says 'Most services are not available until the Configure method is called.'
I think you mean when ConfigureServices method is called

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Services are configured in `ConfigureServices` but not available in `ConfigureServices`. Doc is correct.
