### ISSUE TITLE
No ASP.NET Core 3.1 samples

### ISSUE THREAD

**Issue by ata18** [aspnet/AspNetCore.Docs#16645]
The examples are all for asp.net core ~3.1~ 2.x versions. Please provide an example of how to use Azure AD with ASP.NET Core 3.1 webapp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdae773-368b-a0c1-64d0-2a7b8c8fb134
* Version Independent ID: 2816eb27-7fc5-19e6-7f79-7e81a388647f
* Content: [Azure Active Directory with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-active-directory/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-active-directory/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ata18  

* check my edit of your issues. The links are all to 2.x samples - right?
* We don't own those doc's. You need to open issues at the doc repository they reside in.


@CamSoper  please advice and reopen as appropriate.
