### ISSUE TITLE
IApplicationBuilder does not contain UseDataBaseErrorPage() method

### ISSUE THREAD

**Issue by Anastac1o** [aspnet/AspNetCore.Docs#16651]
I am using ASP.NET Core 3.1 and it looks like the UseDataBaseErrorPage method is not in the IApplicationBuilder class.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.iapplicationbuilder?view=aspnetcore-3.1

Any alternative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Add a package reference for ...

```xml
<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.0" />
```

... and the namespace for EF ...

```csharp
using Microsoft.EntityFrameworkCore;
```

... and then sacrifice *two Microsoft ergonomic keyboards* to the :pray: *server gods* 🙏. :smile:

**Comment by Rick-Anderson** [comment]
If you follow the VS instructions, VS adds that for you.
