### ISSUE TITLE
Now UseMvc is not recommended - where does UseResponseCompression fit in?

### ISSUE THREAD

**Issue by johnnyreilly** [aspnet/AspNetCore.Docs#16653]
Thanks for your amazing docs 🤗  

I have a question: now that the following `UseMvc` is effectively deprecated with .NET Core 3+ ( see https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/. ), should this piece of advice be updated:

&gt; app.UseResponseCompression must be called before app.UseMvc

And if so, in what way?  I'm asking as I've just noticed that UseResponseCompression doesn't seem to be working on my .NET Core 3.1 app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good :eye: @johnnyreilly ... I'll fix that up. The advice is the same: Use the compression middleware before any other middleware that you'd like compressed responses from. Generally, place it early in the pipeline. See the very last paragraph and example at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order.

**Comment by johnnyreilly** [comment]
Awesome - thanks! It's not working on my machine but at least I'm doing the correct thing. Will have to investigate!

**Comment by guardrex** [comment]
Yeah ... happens quite a bit. Make sure you follow https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1#troubleshooting ... especially the part about using a tool to test and not a browser.
