### ISSUE TITLE
Doesn't work on Azure App Service yet

### ISSUE THREAD

**Issue by andifandrich** [aspnet/AspNetCore.Docs#16659]
Net Core 3.1 doesn't work on Azure App Service yet (on Jan, 22nd 2020) so don't bother trying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b7135b-b7a0-2fba-b846-530480aeb415
* Version Independent ID: 69e5b8fb-04e0-817e-434f-72cf6ba12923
* Content: [Migrate from ASP.NET Core 3.0 to 3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/30-to-31.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/30-to-31.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
According to the [dashboard](https://aspnetcoreon.azurewebsites.net/), the rollout is complete. Try following the troubleshooting guidance at https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1.

**Comment by andifandrich** [comment]
Well I just tried in West Europe and it failed to start with the dreaded Could not load file or assembly Microsoft.AspNetCore... error. Rolled back to 3.0 and it worked again.

**Comment by guardrex** [comment]
I don't have any further information. According to the dashboard, the framework is present.

Paste the full error in here. This still feels like some sort of an app migration issue.

**Comment by andifandrich** [comment]
I really appreciate your offer to help and not to forget your very quick response. Thank you very much!
Though I don't think this is the right place to discuss a problem that looks like I'm the only one having it. I will dig further into it when I have a little bit more time.

**Comment by andifandrich** [comment]
If someone stumbles across this, here is the solution:
the currently latest version 3.1.1 of Microsoft.AspNetCore.Authentication.AzureAd.UI seems to be buggy (nothing new for anybody using MS Auth). A rollback to 3.1.0 fixed it.

**Comment by guardrex** [comment]
Thanks @andifandrich ... I'm glad to hear that you were able to narrow that down. I hope the package works better for you on their next release. Best wishes with it! 🍀🤞
