### ISSUE TITLE
1st tutorial did not work for me .. # 239

### ISSUE THREAD

**Issue by ticianaciminari** [aspnet/AspNetCore.Docs#16665]
Hi team, please check this issue from user below:

@Alama32 commented on [Tue Jan 21 2020](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/239)

I followed this tutorial to the letter and I had errors, at the end of the tutorial, I copied pasted all the code of the page / todo and it still did not work ..
Here is the result of the console:
_______________________________________

'BlazorApp1.dll' (CLR v4.0.30319: DefaultDomain): Loaded 'C: \ WINDOWS \ Microsoft.Net \ assembly \ GAC_64 \ mscorlib \ v4.0_4.0.0.0__b77a5c561934e089 \ mscorlib.dll'. Loading symbols ignored. The module is optimized and the debugger option 'Only my code' is activated.
'BlazorApp1.dll' (CLR v4.0.30319: DefaultDomain): Loaded 'C: \ Users \ alama \ source \ repos \ BlazorApp1 \ bin \ Debug \ netcoreapp3.1 \ BlazorApp1.dll'. The symbols have been loaded.
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown module.
Unable to load file or assembly 'System.Runtime, Version = 4.2.2.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a' or one of its dependencies. The specified file can not be found.

The program '[13268] BlazorApp1.dll' stopped with the code -1073741510 (0xc000013a).
_______________________________________

Here .. I don't know where my error is ..

https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/239
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Créer votre première Blazor application](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ticianaciminari and @Alama32 ...

I'll place this on the Blazor.Docs project for triage. They might move it to the engineering repo later. They should be here to take a look on Friday. Stand-by until they get a chance to review this.

**Comment by ticianaciminari** [comment]
Hi @guardrex, I've just noticed that @Alama32 has created another [issue ](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/240) as a continuation of this one. Here's the translation: Continuation and correction of yesterday's message .. # 240

Today I still have errors, but the program has compiled anyway and seems to be working fine.

mistakes:

Severity Code Description Project File Line Deletion status
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ Pages \ Todo.razor 9 Active
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- is it missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ obj \ Debug \ netcoreapp3.1 \ Razor \ Pages \ Todo.razor.g.cs 119 Active
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- is it missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ obj \ Debug \ netcoreapp3.1 \ Razor \ Pages \ Todo.razor.g.cs 119 Active
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ Pages \ Todo.razor 1 Active
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ Pages \ Todo.razor 1 Active
Error CS1061 'TodoItem' does not contain a definition for 'IsDone' and no accessible extension method 'IsDone' accepting a first argument of type 'TodoItem' was not found (a using directive or an assembly reference is- missing?) BlazorApp1 C: \ Users \ alama \ source \ repos \ BlazorApp1 \ Pages \ Todo.razor 3 Active

**Comment by guardrex** [comment]
> mistakes:

Not sure looking at those errors. The class (shown in the tutorial) contains `IsDone` ...

```csharp
public class TodoItem
{
    public string Title { get; set; }
    public bool IsDone { get; set; }
}
```

... I'd need further clarification to proceed. AFAIK, it should work. However, I admit that it's been a little while since I've manually walked the steps. I might need to do that just to be sure that everything is good.

**Comment by guardrex** [comment]
@ticianaciminari, is there any further information from the community member? I'm not sure what to address at this point.

**Comment by Alama32** [comment]
@ticianaciminari , Hello, i'm this member :) i'm Belgian Freanch speaking. I try to follow this training to learn C # and Razor in order to see if this language would suit me. Or maybe TypeScript if it can be compiled in machine language and WASM, because I bet that in the future, all applications will stay online and run on the client.

**Comment by guardrex** [comment]
Hello @Alama32 ... Some of the docs (and parts of docs I think) are translated manually by the localization team and many are machine translated. I don't know very much about the process. It's best for me to let them comment on translations.

With regard to Blazor native compilation, there's no Blazor .NET Native (compiled directly to run on a device) ... **_YET!_** ... that is something that management and engineering are thinking about. For an update, see Dan Roth's recent .NET Conf presentation at ...

https://www.youtube.com/watch?v=KlngrOF6RPw&list=PLdo4fOcmZ0oWlP1Qpzg7Dwzxr298ewdUQ

With regard to what you reported, I don't know if I need to change anything in the topic. As far as I know, the tutorial is correct. If so, then we can close this issue.

**Comment by guardrex** [comment]
I'll go ahead and close. They're going to triage issues today, and I don't want this to slow them down. If you have further documentation concerns, please open issues with the **This Page** feedback button and form at the bottom of any topic on the `en-us` (English) repo if you want to contact us directly.
