### ISSUE TITLE
1er tuto n'a pas fonctionné pour moi..

### ISSUE THREAD

**Issue by ticianaciminari** [aspnet/AspNetCore.Docs#16666]
@Alama32 commented on [Tue Jan 21 2020](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/239)

J'ai suivi ce tuto à la lettre et j'ai eu des erreurs, à la fin du tuto, j'ai copier collé tout le code de la page /todo et ça n'a toujours pas fonctionné..
Voici le résultat de la console:
_______________________________________

'BlazorApp1.dll' (CLR v4.0.30319: DefaultDomain) : Chargé 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Chargement des symboles ignoré. Le module est optimisé et l'option du débogueur 'Uniquement mon code' est activée.
'BlazorApp1.dll' (CLR v4.0.30319: DefaultDomain) : Chargé 'C:\Users\alama\source\repos\BlazorApp1\bin\Debug\netcoreapp3.1\BlazorApp1.dll'. Les symboles ont été chargés.
Une exception non gérée du type 'System.IO.FileNotFoundException' s'est produite dans Module inconnu.
Impossible de charger le fichier ou l'assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.

Le programme '[13268] BlazorApp1.dll' s'est arrêté avec le code -1073741510 (0xc000013a).
_______________________________________

Voilà.. j'ignore où est mon erreur..

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Créer votre première Blazor application](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Tue Jan 21 2020](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/239#issuecomment-576888552)

Hello, @Alama32
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
Will track on https://github.com/aspnet/AspNetCore.Docs/issues/16665.
