### ISSUE TITLE
Some additional explanation is required for 3.0+

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore.Docs#16677]
* *Why* is `SetCompatibilityVersion` a no-op as of 3.0? In other words, briefly explain what it was used for in 2.x, why it was necessary, and why it no longer is.
* Why is there no `CompatibilityVersion.Version_3_1`?
* Will `SetCompatibilityVersion` be deprecated at some stage in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcb541d-c695-99f6-dde7-f01d0d9307d5
* Version Independent ID: 9585545a-9047-85ff-6117-ddd07ef6ee46
* Content: [Compatibility version for ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/compatibility-version.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/compatibility-version.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
* not needed.
* not needed.
* Possibly.
