### ISSUE TITLE
Application Initialization does not work

### ISSUE THREAD

**Issue by unionthugface** [aspnet/AspNetCore.Docs#16675]
The settings above are not sufficient for application initialization to warm-up the app.  Doing a "hard" recycle of the app pool (as opposed to the app pool recycling on its own every so often) stops the app, and it does not start back up again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#application-initialization-module-and-idle-timeout)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti Thoughts?

**Comment by guardrex** [comment]
@unionthugface, He might be OOF/vacation/traveling (a conference for example). Open your issue on the engineering repo, where it will get better visibility/tracking.

https://github.com/dotnet/aspnetcore/issues

Please add a "cc: @guardrex" to the bottom of your opening comment so that I can track the discussion.

**Comment by unionthugface** [comment]
@guardrex I suspect this may be the same issue: [https://github.com/dotnet/aspnetcore/issues/3849](https://github.com/dotnet/aspnetcore/issues/3849)

**Comment by guardrex** [comment]
Ok, thanks. I'll add a short note cross-linking this to that explicitly (beyond just a GH cross-link).
