### ISSUE TITLE
Where to deploy gRPC solutions?

### ISSUE THREAD

**Issue by suarezhar** [aspnet/AspNetCore.Docs#16686]
Since IIS, Azure App Service doesn't support HTTP/2 at this moment. I cannot deploy gRPC server using those approaches. A solution can be docker?
Thank you before hand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetCore/issues/9020
