### ISSUE TITLE
Avoid memory leaks when invoking .NET instance methods

### ISSUE THREAD

**Issue by partyelite** [aspnet/AspNetCore.Docs#16680]
There is nothing in the docs about avoiding memory leaks. I dug through the MS docs and found this link

https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference-1?view=aspnetcore-3.1 

It says here that in order to avoid leaking memory, the DotNetObjectReference (used for invoking .NET instance methods from JavaScript) must later be disposed by JS code or by .NET code.

What is the best practice for disposing DotNetObjectReferences?

**Comment by guardrex** [comment]
Hello @partyelite ... Please use the **This Page** feedback button+form at the bottom of our topics. It adds metadata and pings the author automatically.

Moved to https://github.com/aspnet/AspNetCore.Docs/issues/16682.
