### ISSUE TITLE
Super, but complex to understand because no comments in the code.

### ISSUE THREAD

**Issue by ticianaciminari** [aspnet/AspNetCore.Docs#16683]
@Alama32 commented on [Thu Jan 23 2020](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/241)

Hello, having tutorials is great, but we would understand better if each line of code was commented. The work would be longer, but much more efficient for the students. ;)
Or maybe C # is too complicated for me. I come from AS3 at the base ..
(sorry for my English)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Pages Razor obtenues par génération de modèles automatique dans ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio#the-create-delete-details-and-edit-pages)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Thu Jan 23 2020](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/241#issuecomment-577732562)

Hello, @Alama32
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team, can you please check user's comment? Thanks in advance!

**Comment by guardrex** [comment]
Hello again @Alama32 ... We can't add very many code comments because they aren't machine translated. They would stay in English for everyone forever. We try to keep all of the remarks about the code in the text.

**Comment by Rick-Anderson** [comment]
@Alama32  if you would like localized comments, leave feedback in #16455
