### ISSUE TITLE
Filter category "All" not working?

### ISSUE THREAD

**Issue by pjfmast** [aspnet/AspNetCore.Docs#16695]
Nice example! 
It seems there needs to be some additional code to filter correctly on category "All" - or I missed something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by pjfmast** [comment]
Ignore comment, I indeed missed something

**Comment by Jero327** [comment]
Hi pjfmast. My "ALL" doesn't work as well. Could you please share what you missed? Thanks.
