### ISSUE TITLE
Application startup completed trigger

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16699]
Moved from @theezak at https://github.com/aspnet/AspNetCore.Docs/issues/16697.

In the health checks sample the start of a hosted service is used as an indicator for service readiness. Would it be more appropriate to use IHostApplicationLifetime ApplicationStarted/ApplicationStopping for toggling the readiness indicator on the readiness health check?

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs

Something similar to:

```

    internal class StartupHostedService : IHostedService, IDisposable
    {
        private readonly ILogger _logger;
        private readonly StartupHostedServiceHealthCheck _startupHostedServiceHealthCheck;

       public StartupHostedService(ILogger&lt;StartupHostedService&gt; logger,
            StartupHostedServiceHealthCheck startupHostedServiceHealthCheck,
            IHostApplicationLifetime hostApplicationLifetime)
        {
            _logger = logger;
            _startupHostedServiceHealthCheck = startupHostedServiceHealthCheck;
            hostApplicationLifetime.ApplicationStarted.Register(() =&gt;
            {
                _startupHostedServiceHealthCheck.IsReady = true;
            });
            hostApplicationLifetime.ApplicationStopping.Register(() =&gt;
            {
                _startupHostedServiceHealthCheck.IsReady = false;
            });
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogDebug("Startup Background Health Service is starting.");
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogDebug("Startup Background Health Service is stopping.");
            _startupHostedServiceHealthCheck.IsReady = false;
            return Task.CompletedTask;
        }

        public void Dispose()
        {
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @theezak ... I don't think that that's guaranteed. For the hosted service base class ...

> No further services are started until ExecuteAsync becomes asynchronous, such as by calling await.

So, it does block app startup until it hits an `await`. Once it hits an `await`, the app may go ahead and start while the background service is still trying to get started. Therefore, it wouldn't be good to base knowledge of the service starting on the app starting.

We need @rynowak to confirm tho. I'm just a *silly green dinosaur!* 🐲

**Comment by theezak** [comment]
Fair enough. My concern was that completing the start of StartupHostedService  was not a good indicator for all hosted services having started. There might still be other hosted services queued up or awaited (?)

**Comment by guardrex** [comment]
Yes, I think the idea from engineering is that you'd need to check each one ... it's an atomic check for a single hosted service in the example.

> appeared that IHostApplicationLifetime does not fire application started until all hosted services have completed their startup

Key word there ... **_appeared_**. If `awaits` are hit in `ExecuteAsync`, they shouldn't block the app from starting. At that point, we're dealing with parallel running code that isn't directly blocking each other. That's my current understanding.

I'll close ... Ryan may come on and add/subtract (and 👊 me 😄) if I went sideways. If I'm incorrect tho, what we'll really end up doing is not making changes here (probably) but actually addressing it further in the background services topic.
