### ISSUE TITLE
Chained bind should use the "Year" parent/child example

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/AspNetCore.Docs#16693]
Despite the improved documentation, bindings are still challenging to learn. I just spent a few hours looking at the parent/child component "Year" example, trying to figure out why changing `Year: @Year` to `Year: <input value="@Year" />` didn't enable child-to-parent updates.

One suggestion is to use the "Year" example in the Chained Binding section. It would allow the reader to focus on what has changed vs a whole new example. It is also counter-intuitive that when we use Chained Binding, we also have to stop using the `bind` attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @MisinformedDNA for that feedback ... I'll take a look.
