### ISSUE TITLE
how do you sign in the user ?

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetCore.Docs#16696]
can't find anyware in these docs how do you sign in the user,
something like:
auth.SignIn(name, roles[], remember);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The generated code from  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity shows how to do it.

**Comment by omuleanu** [comment]
actually I don't use Identity/membership,
and I think I found what I was looking for, and it is here: 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#create-an-authentication-cookie
