### ISSUE TITLE
Application startup completed trigger

### ISSUE THREAD

**Issue by theezak** [aspnet/AspNetCore.Docs#16697]
In the health checks sample the start of a hosted service is used as an indicator for service readiness. Would it be more appropriate to use IHostApplicationLifetime ApplicationStarted/ApplicationStopping for toggling the readiness indicator on the readiness health check?

[https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs]

Something similar to:

` 

    internal class StartupHostedService : IHostedService, IDisposable
    {
        private readonly ILogger _logger;
        private readonly StartupHostedServiceHealthCheck _startupHostedServiceHealthCheck;

       public StartupHostedService(ILogger<StartupHostedService> logger,
            StartupHostedServiceHealthCheck startupHostedServiceHealthCheck,
            IHostApplicationLifetime hostApplicationLifetime)
        {
            _logger = logger;
            _startupHostedServiceHealthCheck = startupHostedServiceHealthCheck;
            hostApplicationLifetime.ApplicationStarted.Register(() =>
            {
                _startupHostedServiceHealthCheck.IsReady = true;
            });
            hostApplicationLifetime.ApplicationStopping.Register(() =>
            {
                _startupHostedServiceHealthCheck.IsReady = false;
            });
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogDebug("Startup Background Health Service is starting.");
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogDebug("Startup Background Health Service is stopping.");
            _startupHostedServiceHealthCheck.IsReady = false;
            return Task.CompletedTask;
        }

        public void Dispose()
        {
        }
    }
'

**Comment by guardrex** [comment]
Hello @theezak ... Please use the **This Page** feedback button+form at the bottom of any topic. It adds metadata and pings the author automatically.

No worries ... I moved it to https://github.com/aspnet/AspNetCore.Docs/issues/16699.
