### ISSUE TITLE
Update-Database yields "Login failed for user"

### ISSUE THREAD

**Issue by npruehs** [aspnet/AspNetCore.Docs#16694]
Hey everyone,

when trying to run Update-Database in the package manager console, the following output is generated:

```
Build started...
Build succeeded.
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'xxx\xxxxxx'.
```

(user name and domain replaced). I can't seem to recall having issues with setting up the project in earlier attempts - could it be due to the fact that my machine has been recently added to a domain?

EDIT: It looks like there's a mismatch between sqllocaldb and what Visual Studio is trying to achieve. When I run sqllocaldb from the command line, it creates/updates instances in the folder `C:\Users\{MyOldUserName}\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances` and the folder `C:\Users\{MyNewDomainUserName}\AppData\Local\Microsoft` never contains any SQLite data. At the same time, the package manager console complains about not being able to login to the database. Any advice?

Thanks for your help,
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You've missed a step and I call out this error.

**Comment by npruehs** [comment]
Umm, would you mind sharing which step I've been missing?
