### ISSUE TITLE
struggling with stylesheet href within RCL pages

### ISSUE THREAD

**Issue by adamosoftware** [aspnet/AspNetCore.Docs#16708]
I'm using Core 3.1. My RCL pages share a stylesheet specific to the RCL, but I can't figure out how to reference it within my RCL pages. I created a wwwroot folder at the root of the class library, then added to it /css/styles.css. In my RCL pages, I've tried several hrefs: ~/css/styles.css, /css/styles.css, then css/styles.css. All 404 in the consuming app. I looked at this issue https://github.com/aspnet/AspNetCore.Docs/issues/7662, but I'm not seeing something straightforward that answers my question. I'm looking at the instructions above that say simply to create a wwwroot folder. I've read several blogs about this that seem a bit complicated, and aimed at Core 2 I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by adamosoftware** [comment]
Here's some more info....
- style link in RCL page is [here](https://github.com/adamosoftware/AzureLogger.ExceptionDashboard/blob/master/AzureLogger.ExceptionDashboard/Areas/ExceptionLog/Pages/Shared/_Layout.cshtml#L7)
- stylesheet itself is [here](https://github.com/adamosoftware/AzureLogger.ExceptionDashboard/blob/master/AzureLogger.ExceptionDashboard/wwwroot/css/styles.css)

**Comment by guardrex** [comment]
Did you try the pattern in the first sentence of ...

https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#consume-content-from-a-referenced-rcl

```
_content/{LIBRARY NAME}/css/styles.css
```

**Comment by adamosoftware** [comment]
I saw that, read that several times, but wasn't sure what to make of that. I want the RCL to use/consume its own content. I don't need to reference that stylesheet outside the RCL, so I felt that paragraph you're referring to didn't apply. Anyway, that advice differed from the supposedly working example [here](https://github.com/dodyg/practical-aspnetcore/blob/master/projects/mvc/razor-class-library-with-static-files/src/RazorClassLibrary1/Areas/Module1/Pages/Index.cshtml#L13) -- referenced in comment thread in #7662.

I tried it just now, and this works:
![image](https://user-images.githubusercontent.com/4549398/73122967-7f155d80-3f58-11ea-8ad0-6d5bf746c2db.png)

but I don't know how to get this working from the RCL's point of view:

![image](https://user-images.githubusercontent.com/4549398/73123010-f9de7880-3f58-11ea-85a5-1a28975f10cc.png)

**Comment by guardrex** [comment]
> reference that stylesheet outside the RCL,

... I think the idea is that **_it is outside the RCL_** from the point of view of the consuming app. The resource is still in the RCL no matter how it's requested from that point of view ... a page in the app or a page in the RCL.

WRT the issue you cite: I think 🤔 that pertains to a period before work was done by engineering to resolve this. Early on, there were some issues with getting static assets to link cleanly.

Ok ... leave this open. I'll see about clarifying on that point. Thanks for writing in on it.
