### ISSUE TITLE
dist output bundling

### ISSUE THREAD

**Issue by hanabi1224** [aspnet/AspNetCore.Docs#16709]
It's not clear how to turn on output (dll) file bundling. If I host the static output on CDN, i need bundled output files in [name].[hash].dll format otherwise it cannot handle app updates.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hanabi1224 ... Can you clarify what you mean by ...

> cannot handle app updates

... is your purpose cache-busting?

**Comment by hanabi1224** [comment]
@guardrex Yes, exactly.  I'd like to make those dll files immutable with max-age header so I need the fingerprint as part of file names, does that make sense?

**Comment by guardrex** [comment]
I'll mark this for triage, and we'll get some feedback from engineering. Thus far, there isn't any specifically-designed Blazor approach outside of setting headers. They usually triage these issues on Fridays. Stand-by until next Friday (1/31) to see what they suggest.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is going to be covered as part of https://github.com/dotnet/aspnetcore/issues/17036
