### ISSUE TITLE
services.AddDbContext<MovieContext> should be RazorPagesMovieContext

### ISSUE THREAD

**Issue by Bob1904** [aspnet/AspNetCore.Docs#16720]
In the code sample for Visual Studio Code, under "Scaffold the movie model", "Use SQLite for development, SQL Server for production", the two lines for AddDbContext should be changed from:

services.AddDbContext<**MovieContext**>(options =>

to:

services.AddDbContext<**RazorPagesMovieContext**>(options =>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Add a model to a Razor Pages app : Master Issue #15941
and dup of #15729
