### ISSUE TITLE
Framework-dependent executable is missing from list

### ISSUE THREAD

**Issue by TomVeltmeijer** [aspnet/AspNetCore.Docs#16722]
The list of files generated by `dotnet publish` for an FDD is missing the executable:
[framework-dependent executable is the default for the .NET Core SDK 3.x CLI](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#framework-dependent-executable).

Because the filename extension of an executable is platform-dependent, it wouldn't fit neatly in the current format of

> {ASSEMBLY NAME}.{EXTENSION}

It could potentially use parentheses or a double dagger to mention this and also refer to the FDE section I linked above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566f8ed0-217e-5125-b0f7-6d93c3a145c1
* Version Independent ID: 9fa94395-eff8-3b12-c2d5-c1c6d4142378
* Content: [ASP.NET Core directory structure](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/directory-structure.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/directory-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @TomVeltmeijer ... I'll update that right now. IIRC, the extension is *.exe* xplat for FDE. I'll call for engineering review, so they'll let me know if that's incorrect on the PR.
