### ISSUE TITLE
WebAppPart The view 'Index' was not found

### ISSUE THREAD

**Issue by thanhnntq** [aspnet/AspNetCore.Docs#16728]
![image](https://user-images.githubusercontent.com/30698814/73177846-9ca61b00-4142-11ea-8db8-c52e7377a323.png)
Run doc WebAppParts can't find view in reference project (MyShared).

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by thanhnntq** [comment]
I downloaded the docs and ran it and received an error like that. I didn't change anything.
