### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by brikken** [aspnet/AspNetCore.Docs#16721]
This would be a good place to mention that the .NET client does not work in Blazor WebAssembly

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: c888abac-0b7a-6529-e3a9-dc43ca14ffce
* Version Independent ID: 08a0cb80-db1e-0ca5-abd7-9bfc3a28b01e
* Content: [SignalR client features](https://docs.microsoft.com/da-dk/aspnet/core/signalr/client-features?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/client-features.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/client-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by BrennanConroy** [comment]
I'm not sure what the policy of documenting "not working on a not shipped product" is. But this does work in the [first preview](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/) of Blazor WebAssembly.

**Comment by guardrex** [comment]
I'll be taking this up tomorrow on a different issue. It's ok to close this. 

@brikken, keep an :eye: out for the doc updates coming within 24 hours.
