### ISSUE TITLE
dotnet dev-certs https --trust Does not work for Microsoft Edge Chromium based

### ISSUE THREAD

**Issue by josuemb** [aspnet/AspNetCore.Docs#16737]
When I run:

`dotnet dev-certs https --trust`

The command does not work for **Microsoft Edge Chromium based** (even when it works for Google Chrome).

Please add support for this Browser.

**Comment by josuemb** [comment]
I already checked the current code for dev-certs tool. It looks simple. If you guide me a little I can help to fix it.

**Comment by josuemb** [comment]
After applying: 

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems

And close/reopen the browser the problem has gone.

Thanks.

**Comment by abjoseph** [comment]
> After applying:
> 
> [docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems)
> 
> And close/reopen the browser the problem has gone.
> 
> Thanks.

@josuemb, can you share the specific steps or section you followed in that link to resolve the issue with MS edge browser? Also, were you running the project directly on windows or via docker-compose project (using docker desktop)?

**Comment by rahadur** [comment]
[All platforms - certificate not trusted](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio%2Clinux-sles#all-platforms---certificate-not-trusted-1)

```bash
dotnet dev-certs https --clean
dotnet dev-certs https --trust
```

**Comment by gotmoo** [comment]
> [All platforms - certificate not trusted](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio%2Clinux-sles#all-platforms---certificate-not-trusted-1)
> 
> dotnet dev-certs https --clean
> dotnet dev-certs https --trust

In case someone else comes across this: If the certificate is still not trusted after this (could happen when running dotnet under a different user context)
1. Export the untrusted cert (Export will be on the Details tab of the Edge Certificate Viewer):

<img width="410" height="192" alt="Image" src="https://github.com/user-attachments/assets/0d7ec01f-1df2-4361-855f-0877ac41f1c0" />

<img width="406" height="139" alt="Image" src="https://github.com/user-attachments/assets/a2eb75dd-f54c-4cdd-86b4-124f5e2714db" />

2. Open `certmgr.msc` and import the certificate into the **Trusted Root Certification Authorities** store for the current user
3. Restart Edge by typing `edge://restart` in the address bar
