### ISSUE TITLE
Unable to find package Microsoft.AspNetCore.Blazor.Templates

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16730]
From @FANMixco on https://github.com/aspnet/AspNetCore.Docs/issues/16729 ...

> It seems the Blazor version is incorrect:
>
> > Unable to find package Microsoft.AspNetCore.Blazor.Templates with version (&gt;= 3.1.0-preview4.19579.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates/3.1.0-preview4.19579.2

You may have a *nuget.config* file somewhere in the directory tree above the project that's changing the NuGet feed.

**Comment by FANMixco** [comment]
> https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates/3.1.0-preview4.19579.2
> 
> You may have a _nuget.config_ file somewhere in the directory tree above the project that's changing the NuGet feed.

Hi @guardrex, could you explain me? Maybe I don't understand well your viewpoint. I'm running it from the console, I'm not in any specific folder. I tried with Admin rights too.

![VSCommand](https://user-images.githubusercontent.com/1666156/73181087-e11bc180-4116-11ea-8c6a-73dec08ecec6.jpg)

Also, I followed this instructions:

> Optionally install the Blazor WebAssembly template:
> 
> Install the .NET Core 3.1 or later (Preview) SDK.
> Run the following command in a command shell. The Microsoft.AspNetCore.Blazor.Templates package has a preview version while Blazor WebAssembly is in preview.
> .NET Core CLI
> 
> Copy
> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2

From here:

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio

And I have confirmed that I have the SDK 3.1 installed. Thanks.

**Comment by guardrex** [comment]
I think you have a NuGet feeds problem of some sort.

Try re-running the command with an explicit source for nuget.org ...

```dotnetcli
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2 --nuget-source https://api.nuget.org/v3/index.json
```

**Comment by FANMixco** [comment]
> I think you have a NuGet feeds problem of some sort.
> 
> Try re-running the command with an explicit source for nuget.org ...
> 
> ```
> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2 --nuget-source https://api.nuget.org/v3/index.json
> ```

Indeed, your solution worked, _don't you think this could be added as a workaround or suggestion in the documentation?_ I'd say I might not be the only one who could face this issue, especially in corporate environments.

**Comment by guardrex** [comment]
Very few issues (only one or two over the past year) have been opened for this scenario. Usually, developers having NuGet feed/source issues in corporate environments are aware of their circumstances, so they generally seem to know how to address it. I'll keep an :ear: open for more feedback. If devs ping on this more frequently, then *yes* ... I'll add something to the topic about it.
