### ISSUE TITLE
Blazor rendering

### ISSUE THREAD

**Issue by Ricardoaraujo00** [aspnet/AspNetCore.Docs#16735]
Why not make Blazor to first load the code section and then do the rendering? I have to make a lot of conditions like "if variable not null" to go through a foreach to render page elements. And sometimes i get the error that the variable is not instantiated, or that the key in the dictionary is null. Sometimes i get the first error, other times the second, in the same condition!!!. This looks like a mess, really... Blazor should load code first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ricardoaraujo00 ... We only handle documentation issues here. Open your product feedback on the engineering repo at ...

https://github.com/dotnet/aspnetcore/issues
