### ISSUE TITLE
Content has to be improved

### ISSUE THREAD

**Issue by Locomotion77** [aspnet/AspNetCore.Docs#16741]
I am confused with so many configuration files such as launchSettings.json, appSettings.json, and web.config. This article should emphasizes that the launchSettings.json is used in Visual Studio or local development ONLY, but has nothing to do with deployment. It takes hours for me to try to digest and relate all the concepts until I find the similar discussion at stakeoverflow (https://stackoverflow.com/questions/46955538/launchsettings-json-and-appsettings-json-and-web-config).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Locomotion77 ... These files are described in the topics where each applies:

* *launchSettings.json* is a tooling configuration file for the Development environment, described in this topic's *Development* section and where it pertains to tooling across the docs.
* *appsettings.json*/*appsettings.{Environment}.json* is an app configuration file, described in the configuration and hosting topics and the topics where settings for various scenarios appear across the docs.
* *web.config* is a server configuration file, described in the IIS and ASP.NET Core Module topic in the *Host and deploy* node and elsewhere when it applies to server config across the docs.

> This article should emphasizes that the launchSettings.json is used in Visual Studio or local development ONLY

It says that ... in the topic's *Development* section ...

> The environment for local machine development can be set in the *Properties\launchSettings.json* file of the project.

We could briefly list and cross-link the various configuration files in the highest-level overview section that we have on the subject of configuration in the doc set, over in *Fundamentals* > *Overview* ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows#configuration

@Rick-Anderson If you like that idea and are busy 🏃, you can assign me if you want. I'll have time within the next week to do this. I envision a short bullet list with a few cross-links that wouldn't take long to whip up.
