### ISSUE TITLE
Scaffolding TodoItem Controller

### ISSUE THREAD

**Issue by jawaharrajan** [aspnet/AspNetCore.Docs#16748]
I am trying to Scaffold a Controller based on Model TodoItem and DBContext  TodoContext with this command Line :

`dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers`

but I get this error:
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
A type with the name TodoItem does not exist
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.93

How do we specify the location of the Model it is assumed to be in a folder called Models ?
I am following the example from :
[https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio](url)
using VS Code

**Comment by Rick-Anderson** [comment]
Try using the FQN (fully qualified name)

**Comment by jawaharrajan** [comment]
Thanks Rick,
The mistake was mine, I keep forgetting to save the new file I had generated for the TodoItem.

Once I saved the file the command ran with no issues
Thanks
