### ISSUE TITLE
Common error handler

### ISSUE THREAD

**Issue by JandosKh** [aspnet/AspNetCore.Docs#16758]
Please provide information on common error handler which intercepts all errors. Index html contains &lt;div id="blazor-error-ui"&gt; tag, but how it is used internally is unclear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JandosKh ... What do you mean by "internally"?

**Comment by JandosKh** [comment]
@guardrex , I see that '#blazor-error-ui' is hard-coded, which is okay with me. What I really want is to know where to intercept all errors. For example, when I receive HTTP 401, I'd like to redirect to login page, or do something else.

**Comment by guardrex** [comment]
See the auth topic for that ... https://docs.microsoft.com/en-us/aspnet/core/security/blazor/ ... there's an `AuthorizeRouteView` component and a following section that pertains to procedural logic for auth.

For unhandled errors in a Blazor app, you'll need to follow the guidance in this *Handle errors* topic and trap them yourself.

**Comment by guardrex** [comment]
I'll go ahead and close since what you're asking about isn't an "error" but more of an "authn/authz failure" scenario covered by the other topic.
