### ISSUE TITLE
Clarify configuration provider capabilities for Kestrel options

### ISSUE THREAD

**Issue by javs-ctr** [aspnet/AspNetCore.Docs#16759]
Question regarding the statement above under the [Kestrel options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#kestrel-options) section:

>Kestrel options, which are configured in C# code in the following examples, can also be set using a configuration provider. For example, the File Configuration Provider can load Kestrel configuration from an appsettings.json or appsettings.{Environment}.json file:

In reading the statement above, I am curious if it is possible to set the `ClientCertificateMode` from the `HttpsConnectionAdapterOptions` class [HttpsConnectionAdapterOptions.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs) from an _appsettings.json_ file.

I have tried:

```json
  1 {
  2   "Kestrel": {
  3     "HttpsDefaults": {
  4       "ClientCertificateMode": "AllowCertificate"
  5     }
  6 }
```
in an _appsettings.json_ file to no avail.

Yet, I am able to configure the `ClientCertificateMode` Kestrel option from C# code as follows (in `Program.cs`):

```csharp
hostBuilder.ConfigureWebHostDefaults(webBuilder =&gt;
{
  webBuilder.UseStartup&lt;Startup&gt;();
  webBuilder.ConfigureKestrel(o =&gt;
  {
    o.ConfigureHttpsDefaults(o =&gt;
      o.ClientCertificateMode =
        ClientCertificateMode.AllowCertificate);
  });
});
```

I did observe in the [Endpoint configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#endpoint-configuration) section above that there is an _appsettings.json_ file example configuring the `EndpointDefaults` property of the `KestrelServerOptions` class, which is a sibling property of the `HttpsDefaults` property, and I inferred that it should also be possible to configure the `HttpsDefaults` property from an _appsettings.json_ file.

Thank you in advance for any information you are able to provide.

Thank you for the detailed documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @javs-ctr ... *Indeed,* there isn't exact parity between the naming of properties that you can set in code and the keys used in the configuration file. I don't think that one is available ...

https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs

However, it's best to ask. Even if it isn't available, your feedback is important to them for framework design. Open a new issue with exactly what you posted :point_up: at ...

https://github.com/dotnet/aspnetcore/issues

Please add a "cc: @guardrex" to the bottom of your opening comment so that I can see what they say.

**Comment by javs-ctr** [comment]
My thanks to you guardrex for the rapid response. I created an [issue](https://github.com/dotnet/aspnetcore/issues/18660) earlier based on your recommendation.

The [ConfigurationReader.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs) class reference was quite helpful.

**Comment by guardrex** [comment]
See: https://github.com/dotnet/aspnetcore/issues/18660#issuecomment-579945890
