### ISSUE TITLE
Provide an example for switching to Azure KeyVaults when deployed

### ISSUE THREAD

**Issue by ata18** [aspnet/AspNetCore.Docs#16767]
I have deployed an asp.net core webapp and configured the ConnectionStrings__Default in the app settings page. It reads the connection string from an azure key vault. 

![image](https://user-images.githubusercontent.com/6476128/73395714-ea329d00-4294-11ea-914c-fc1d9bf843f5.png)

In the startup.cs file, I access it as below and it works fine.
```
services.AddDbContext<CentralDBContext>(c =>;
                c.UseSqlServer(Configuration.GetConnectionString("Default"), builder =>;
                    builder
                        .EnableRetryOnFailure()
                        .CommandTimeout(120))
                );
```
Today when developing locally, instead of having the connection string in appSettings.Development.json, I wanted to use user-secrets. 
```
dotnet user-secrets set "ConnectionStrings__Default" "<connection string>"
```

Made the following change in startup.cs in order to be able to access it:
```
services.AddDbContext<CentralDBContext>(c =>;
                c.UseSqlServer(Configuration["ConnectionStrings__Default"], builder =>;
                    builder
                        .EnableRetryOnFailure()
                        .CommandTimeout(120))
                );
```
This works in dev environment. However, it fails when deployed.  How to use user-secrets in dev environment and switch to Azure KeyVaults when deployed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
`Configuration.GetConnectionString("DefaultConnection")));` in production doesn't use secret manager. No need to change your code. Read any doc on deployment or the configuration doc.

**Comment by Rick-Anderson** [comment]
Per the article:

Consider an ASP.NET Core web app in which **Individual User Accounts** security is enabled. A default database connection string is included in the project's *appsettings.json* file with the key `DefaultConnection`. The default connection string is for LocalDB, which runs in user mode and doesn't require a password. During app deployment, the `DefaultConnection` key value can be overridden with an environment variable's value. The environment variable may store the complete connection string with sensitive credentials

**Comment by ata18** [comment]
This doesn't help much. Keeping `Configuration.GetConnectionString("DefaultConnection")));` in production would work. This is what I previously had. But, this doesn't read the user-secrets when in dev environment.

**Comment by Rick-Anderson** [comment]
You're doing something wrong if it doesn't work in both environments.

**Comment by ata18** [comment]
@Rick-Anderson I am trying to understand where I went wrong. In [this](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=linux) doc example, it doesn't use `Configuration.GetConnectionString(..)`.

Instead it uses `Configuration[..]` syntax which only works in development environment.
```
 public void ConfigureServices(IServiceCollection services)
    {
        _moviesApiKey = Configuration["Movies:ServiceApiKey"]; 
    }
```
Could you point me to the doc where you see that `Configuration.GetConnectionString(..)` should work for both environments?

**Comment by ata18** [comment]
Setting the secret as below works with the existing code without changing the syntax.

`dotnet user-secrets set "**ConnectionStrings:Default**" "<connection string>"`

```
services.AddDbContext<CentralDBContext>(c =>;
                c.UseSqlServer(Configuration.GetConnectionString("Default"), builder =>;
                    builder
                        .EnableRetryOnFailure()
                        .CommandTimeout(120))
                );
```

![image](https://user-images.githubusercontent.com/6476128/73404644-d1cb7e00-42a6-11ea-8bd2-97f35b8e40e5.png)
