### ISSUE TITLE
Split advanced configuration content out of Blazor Hosting Models topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16764]
For discussion/triage: The *Hosting Models* topic goes into advanced configuration details that might be better off in another topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Holding the .NET SignalR Client content for Blazor WebAssembly for 3.2p1 until we determine if it can go into the SignalR doc/tutorial with a cross-link from either Blazor's *Hosting Models* topic or wherever we go with config content ...

Blazor WebAssembly supports the [.NET SignalR client](xref:signalr/dotnet-client). To use SignalR in a Blazor WebAssembly app:

1. Create an ASP.NET Core hosted Blazor WebAssembly app:

   ```dotnetcli
   dotnet new blazorwasm --hosted --output BlazorSignalRApp
   ```

1. Add the ASP.NET Core SignalR Client package to the Client project:

   ```dotnetcli
   cd BlazorSignalRApp
   dotnet add Client package Microsoft.AspNetCore.SignalR.Client
   ```

1. In the Server project, add the following `ChatHub` class (*Hub/ChatHub.cs*):

   ```csharp
   using System.Threading.Tasks;
   using Microsoft.AspNetCore.SignalR;

   namespace BlazorSignalRApp.Server.Hubs
   {
       public class ChatHub : Hub
       {
           public async Task SendMessage(string user, string message)
           {
               await Clients.All.SendAsync("ReceiveMessage", user, message);
           }
       }
   }
   ```

1. In the Server project, add the SignalR services in the `Startup.ConfigureServices` method:

   ```csharp
   services.AddSignalR();
   ```

1. In the Server project, add an endpoint for the `ChatHub` in `Startup.Configure`:

   ```csharp
   .UseEndpoints(endpoints =>
   {
       endpoints.MapDefaultControllerRoute();
       endpoints.MapHub<ChatHub>("/chatHub");
       endpoints.MapFallbackToClientSideBlazor<Client.Program>("index.html");
   });
   ```

1. Update *Pages/Index.razor* in the Client project with the following markup:

   ```razor
   @page "/"
   @using Microsoft.AspNetCore.SignalR.Client
   @inject NavigationManager NavigationManager

   <div>
       <label for="userInput">User:</label>
       <input id="userInput" @bind="_userInput" />
   </div>
   <div class="form-group">
       <label for="messageInput">Message:</label>
       <input id="messageInput" @bind="_messageInput" />
   </div>
   <button @onclick="Send" disabled="@(!IsConnected)">Send Message</button>

   <hr>

   <ul id="messagesList">
       @foreach (var message in _messages)
       {
           <li>@message</li>
       }
   </ul>

   @code {
       private HubConnection _hubConnection;
       private List<string> _messages = new List<string>();
       private string _userInput;
       private string _messageInput;

       protected override async Task OnInitializedAsync()
       {
           _hubConnection = new HubConnectionBuilder()
               .WithUrl(NavigationManager.ToAbsoluteUri("/chatHub"))
               .Build();

           _hubConnection.On<string, string>("ReceiveMessage", (user, message) =>
           {
               var encodedMsg = user + " says " + message;
               _messages.Add(encodedMsg);
               StateHasChanged();
           });

           await _hubConnection.StartAsync();
       }

       Task Send() => 
           _hubConnection.SendAsync("SendMessage", _userInput, _messageInput);

       public bool IsConnected => 
           _hubConnection.State == HubConnectionState.Connected;
   }
   ```

1. Build and run the Server project:

   ```dotnetcli
   cd Server
   dotnet run
   ```

1. Open the app in two separate browser tabs to chat in real time over SignalR.

**Comment by danroth27** [comment]
SignalR content will get covered by https://github.com/aspnet/AspNetCore.Docs/issues/16771
