### ISSUE TITLE
The description of the IdentityServer json is in reversed order

### ISSUE THREAD

**Issue by Log234** [aspnet/AspNetCore.Docs#16768]
These three lines should be reversed, as they would then match the order of the lines they are describing in the json snippet.

The name property on certificate corresponds with the distinguished subject for the certificate.
The store location represents where to load the certificate from (CurrentUser or LocalMachine).
The store name represents the name of the certificate store where the certificate is stored. In this case, it points to the personal user store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

In the mean time,  moved to master issue: Authentication and authorization for SPAs #16406
