### ISSUE TITLE
meaning not clear

### ISSUE THREAD

**Issue by alex737876** [aspnet/AspNetCore.Docs#16762]
In 2.d in this doc there is "Confirm that the setProfileEnvironment attribute isn't present, which defaults the value to *true* , or explicitly set the attribute's value to *true*."
--&gt; I guess the firs "true" has to be a "false" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945c28b7-6cc7-d4ed-3b96-a401eef42f59
* Version Independent ID: eb45fbf9-29fb-c67b-2f50-454380a502dd
* Content: [Data Protection key management and lifetime in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/data-protection/configuration/default-settings.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/default-settings.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think it's correct.

The app pool's `setProfileEnvironment `attribute must also be enabled. The default value of setProfileEnvironment is `true`. In some scenarios (for example, Windows OS), `setProfileEnvironment `is set to `false`. If keys aren't stored in the user profile directory
