### ISSUE TITLE
Over-engineered

### ISSUE THREAD

**Issue by Tommigun1980** [aspnet/AspNetCore.Docs#16772]
I think this product is taking far too much a stance on programming patterns and conventions. It's good to have recommended practices, but I think those should be left as an optional addendum. As it stands now, in order to just access some configuration variables requires you to wade through tons of convention documentation and it comes off as grossly over-engineered. The entire product is going in a direction that forces the patterns on your, and things that should be trivial become a nuisance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Tommigun1980 ... We only handle documentation on this repo. You can leave product feedback on the engineering repo ...

https://github.com/dotnet/aspnetcore/issues
