### ISSUE TITLE
You are using wrong method in StudentsController.Details().

### ISSUE THREAD

**Issue by LayersOfAbstraction** [aspnet/AspNetCore.Docs#16776]
Hi, 

Great tutorials so far, thanks! You write for us to use `FirstOrDefaultAsync` but further down I can't see the (TOP(2)) from the Person table. I think the first code snippet should be changed to include the `SingleOrDefaultAsync` and not `FirstOrDefaultAsync`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's ` Details(int? id)` and uses the unique ID.
