### ISSUE TITLE
What is the purpose of NormalizedX columns in Identity tables?

### ISSUE THREAD

**Issue by dehghani-mehdi** [aspnet/AspNetCore.Docs#16774]
Hi,

EF create tables for identity, in some tables there are `NormalizedX` columns, e.g: `NormalizedName` in `AspNetRoles` table.

1. What is the purpose of this kind of columns?
2. How EF normalize data for this columns?

I didn't find any documentation about this topic.

**Comment by Rick-Anderson** [comment]
Good question. I'll try to get an answer. In the mean time, moved to Master issue: Introduction to Identity #16230

**Comment by Rick-Anderson** [comment]
@HaoK  What is the purpose of NormalizedX columns in Identity tables? 

> EF create tables for identity, in some tables there are `NormalizedX` columns, e.g: `NormalizedName` in `AspNetRoles` table.

1. What is the purpose of this kind of columns?
2. How EF normalize data for this columns?

**Comment by HaoK** [comment]
The normalized fields are what we do comparisons against for lookups, the regular columns are what you can think of as the display names, so the casing is preserved.

**Comment by dehghani-mehdi** [comment]
@HaoK what about second question?

**Comment by HaoK** [comment]
EF doesn't normalize the column at all, the user manager uses the `ILookupNormalizer` interface that by default just calls to upper invariant I believe
