### ISSUE TITLE
Error CS0229 Ambiguity between 'CreateModel._context' and 'CreateModel._context'

### ISSUE THREAD

**Issue by ekalyvio** [aspnet/AspNetCore.Docs#16779]
Apparently, there is a known problem with scaffolding in VS that is not yet fixed by MS (neither given any solution).
[https://forums.asp.net/t/2162302.aspx?Namespace+problem+when+generating+Razor+Pages+in+VS+2019](url)

Briefly:
Trying to scaffold a new 'Reviews' class generates the following error message.
Error CS0229 Ambiguity between 'CreateModel._context' and 'CreateModel._context'
More details on:
https://stackoverflow.com/questions/59987881/error-cs0229-ambiguity-between-createmodel-context-and-createmodel-context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Great error message. You must have forgotten to select data context.

If you can reproduce the problem from scratch:

* Create the simplest possible app the reproduces the problem.
* List all the steps to reproduce the problem.
* Put the app on a public GItHub
* Open an issue at https://github.com/aspnet/Scaffolding with the preceding
