### ISSUE TITLE
Why use an extension method?

### ISSUE THREAD

**Issue by tompi** [aspnet/AspNetCore.Docs#16775]
Why not just call UseMiddleware&lt;RequestCultureMiddleware&gt;(); directly on the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  does that work?

**Comment by serpent5** [comment]
Yeah, the extension method is just a wrapper around that call, so both options work.

Using an extension method is a convention that's adopted by the built-in middleware components. Consider a typical middleware pipeline setup for adding endpoints:

```csharp
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseEndpoints(...);
````

Consider that same configuration without the extension methods:

```csharp
app.UseMiddleware<EndpointRoutingMiddleware>();
app.UseMiddleware<AuthenticationMiddleware>();
app.UseMiddleware<AuthorizationMiddleware>();
app.UseMiddleware<EndpointMiddleware>(...);
```

There's a lot of noise in that second example, especially around the repeated `Middleware`. An extension method also allows additional configuration and checks, too. Some of those `Use` extensions shown above do extra work, such as adding more configuration and verifying that services have been registered.

You certainly don't have to use an extension method, if you don't like the convention and don't have additional configuration needs, etc.

**Comment by Rick-Anderson** [comment]
Good question and fantastic answer.
