### ISSUE TITLE
Custom exception filter for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#16780]
I'm trying to implement the example exception filter in a ASP.NET Core 3.1 Blazor (server-side) application however the exception is never caught or fired at all. I've used the standard Blazor website template to test this outside of my project code which is also exhibiting the same issue. Could someone please tell me if and how you can implement the exception filter in a Blazor website/application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#next-actions)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jasonshave** [comment]
A quick update on my troubleshooting progress. I've downloaded the samples from the GH repo and the filter works fine on a `Controller` class when you decorate it with the `TypeFilter` attribute. I tried testing it on a basic .NET console application but also can't get it to trigger the filter at all.

So does the example of using the `TypeFilter` attribute only work on a `Controller` class? If so, are there alternatives to getting this to work when you need a custom global exception filter?

Here is my console application code for reference:

##Program.cs
`    [TypeFilter(typeof(ExceptionFilter))]
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            throw new Exception("Testing");
        }
    }`

##ExceptionFilter.cs
`    public class ExceptionFilter : IExceptionFilter
    {
        public void OnException(ExceptionContext context)
        {
            throw new NotImplementedException();
        }
    }`

I've also tried adding a constructor to the filter just in case it's necessary but that didn't seem to make a difference. I set a breakpoint on the `throw new NotImplementedException();` but it never breaks/hits it.

**Comment by guardrex** [comment]
@jasonshave ... I suspect that the filter isn't implemented for Blazor apps. Ask on the engineering repo. They might be planning work in this area.

If you think to do so, would you please add a "cc: @guardrex" to the end of your question about this? I'll follow along with the discussion if I get the pings from GH.

https://github.com/dotnet/aspnetcore/issues

**Comment by jasonshave** [comment]
@guardrex I don't think this is a Blazor issue at all. As I mentioned above, I can't even get the Exception Filter to work in a Console application. So perhaps I'll restate my question...

Are there any restrictions on how you can use an Exception Filter or said another way, what are the supported project types for Exception Filters in .NET Core? The docs article doesn't seem to give any guidance on how to apply the filter and what isn't supported.

**Comment by Rick-Anderson** [comment]
Per the doc

**Filters run within the ASP.NET Core action invocation pipeline, sometimes referred to as the filter pipeline**

This is not .NET Core, this is ASP.NET Core.

**Comment by jasonshave** [comment]
Right, thanks for that clarification. The question remains though...

**Comment by Rick-Anderson** [comment]
You need an ASP.NET Core action invocation pipeline. Console apps don't have an ASP.NET Core action invocation pipeline.

**Comment by jasonshave** [comment]
**Are there any restrictions on how you can use an Exception Filter or said another way, what are the supported project types for Exception Filters in ASP.NET Core?**

**Comment by Rick-Anderson** [comment]
Requires the ASP.NET Core action invocation pipeline,

**Comment by jasonshave** [comment]
Officially not supported is the answer to this one for anyone else's reference: https://github.com/dotnet/aspnetcore/issues/18761

**Comment by Rick-Anderson** [comment]
@guardrex  is it worth adding a link to https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1 in this doc?

**Comment by guardrex** [comment]
Except that they are supported when the component is embedded in a Razor Page that uses the filter. I'll float a PR that seeks to clear it up.
