### ISSUE TITLE
Missing dependencies / using statements

### ISSUE THREAD

**Issue by rgamage** [aspnet/AspNetCore.Docs#16789]
This article, like nearly every other MS doc article, is missing the all-important using statements required to use the example code.  Any example anywhere should start with the requirements/dependencies, it's just common sense.  Without these, a whole lot of time is wasted trying to figure out which references to add to your project, and which using statements to add.  It's not always obvious, especially when they are extension methods.  Please consider adding these incredibly useful bits of info.  You don't need to show all of them that would be at the top of the startup.cs, just the one or two that, if missing, will make your example snippet useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't show them in advanced topics like this one. You can always check the sample project. See https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authorization/policies/samples/3.0PoliciesAuthApp1
