### ISSUE TITLE
Where is the "Web App Service Sample" that this doc mentions

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore.Docs#16781]
I want to run a web api as a windows service. 
.UseWindowsService() overload is only available on IHostBuilder not IWebHostBuilder.
The worker service template can be used to run a background service, but not seemingly a web api.
So the mentioned sample would be very useful..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Linked under the *Download* remark at the top of the topic ...

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/host-and-deploy/windows-service/samples/3.x/WebAppServiceSample

**Comment by dazinator** [comment]
Ah I see! Sorry I overlooked that.
