### ISSUE TITLE
Doesn't work on Microsoft Edge

### ISSUE THREAD

**Issue by mjboggs** [aspnet/AspNetCore.Docs#16790]
Do you realize the first part of the code in this tutorial does NOT work in Microsoft Edge? The code works perfectly fine using Google Chrome but causes an error in Microsoft Edge.  As you ARE Microsoft, it may be a good practice to test your published code in your OWN products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mjboggs Yes, we know. TextDecoder made for a nice example of something that one could do client-side for this example, and the example was signed off by engineering with full knowledge of this situation. When we put this example up IIRC, the Edge team was working on getting TextDecoder working in Edge. Let me check on their progress and see where they're at with it. If they're going to roll that support out soon, then I'd like to keep that example. I like the way that it explains the concepts here. I'll get back with u next week.

**Comment by guardrex** [comment]
@mjboggs Can you check your version of Edge. Looks like they landed it **two weeks ago**. :tada: That's a little longer than I hoped, but better late than never! :smile:

**Comment by Rick-Anderson** [comment]
I recommend you add a note to the doc saying  something like this is a sample and not supported. It's known that it doesn't currently work with Edge.

**Comment by guardrex** [comment]
It works with Edge ... now ... as of two weeks ago. Let me hear back from @mjboggs on browser version. I'm open to changing the example, but I'd prefer not to unless necessary. I like that example.

**Comment by guardrex** [comment]
After lengthy discussion of what versions of browsers are supported for Blazor, we go with **_Current_** ...

https://docs.microsoft.com/aspnet/core/blazor/supported-platforms

... so technically we're good, even if that's not very satisfying.

**Comment by guardrex** [comment]
@mjboggs I'm going to close as answered. Let me know if you're using Edge latest and it doesn't work. If that's the case, I'll repro it here, re-open this issue, and change the example. Thanks for writing in about it.
