### ISSUE TITLE
A little shout of appreciation...

### ISSUE THREAD

**Issue by Mike-EEE** [aspnet/AspNetCore.Docs#16797]
These pages around are incredibly wonderful and impressive.  Very nice work over there putting these together. 👍

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
Thanks
