### ISSUE TITLE
Improve documentation for updating component state externally

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#16801]
[EDIT by guardrex to add the metadata]

_From @SayusiAndo on Thursday, January 30, 2020 7:21:33 PM_

I'm not sure this ticket should be filed here. If it is not the right project, please let me know and I'll move it, or feel free to relocate it.

The documentation about how to update component state from external source the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state) shows two code snippets. The snippets are good and usable, or at least they give some hints what to do. Unfortunately, the documentation doesn't mention that the Notification service must be injected as singleton. If it is injected as transparent (new instance for every request), then the Notify property will be null.

Fortunately, this issue was discussed on [Stackoverflow](https://stackoverflow.com/questions/59857650/blazor-event-sent-from-service-to-component-is-null). In my opinion, it would be great to provide a more detailed example to help the community to utilize easier this functionality. 

Thanks!

_Copied from original issue: dotnet/aspnetcore#18693_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0#data-binding)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mkArtakMSFT Is the "area-blazor" for PU use? On the docs side, we use the "Blazor" label. I can work this issue, so I'm also checking if you want me to take it.

**Comment by mkArtakMSFT** [comment]
@guardrex feel free to ignore the `area-` labels. Those are just for me. We're using these labels consistently in the `dotnet/aspnetcore` repo, but not a requirement for here.
