### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by Sm1le291** [aspnet/AspNetCore.Docs#16806]
Hi! I have a question about wwwroot\index.html. You wrote that "When any page of the app is initially requested, this page is rendered and returned in the response."
I tried to reproduce this behavior. I added console.log message to index.html and it prints message only when application loads, when I am going to another page nothing happens. How to understand the statement "When any page of the app is initially requested, this page is rendered and returned in the response." in light of it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab93ded4-34f4-eddc-d967-96b2326fce9c
* Version Independent ID: 4ee1d242-ec4f-c760-d1ce-26d31e3d2f49
* Content: [ASP.NET Core Blazor templates](https://docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/blazor/templates.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/templates.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sm1le291 ... It means for a request that **_reaches the server_**. For requests within the app, the Blazor client-side router handles the request on the client.

If you reload the page, you should end up sending a new request to the server ... in that case the *index.html* file will be sent again.
