### ISSUE TITLE
Please provide the package for the .AddConsole and .AddDebug.

### ISSUE THREAD

**Issue by floppydisken** [aspnet/AspNetCore.Docs#16811]
It's a general problem in docs that a package is not referred to in the docs. I usually have to find some sample project to locate what package is used.

Am I missing something here or does everyone do the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @floppydisken ... Use the API docs at :point_right: https://docs.microsoft.com/en-us/dotnet/api/
