### ISSUE TITLE
Header Propagation Middleware missing from Build-in middleware list.

### ISSUE THREAD

**Issue by hannahchan** [aspnet/AspNetCore.Docs#16815]
I thought this page ought to mention something about the Header Propagation Middleware which is somewhat documented here; https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#header-propagation-middleware.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-au/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @hannahchan ... I'll knock that out real quick.
