### ISSUE TITLE
Example doesn't return context.Succeed

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore.Docs#16839]
First example in section "Create owner, manager, and administrator authorization handlers" never returns context.Succeed() but only executes it even though the description under it says it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1#create-owner-manager-and-administrator-authorization-handlers)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc:

The ContactIsOwnerAuthorizationHandler calls context.Succeed **if the current authenticated user is the contact owner.**

**Comment by wrkettlitz** [comment]
The ContactIsOwnerAuthorizationHandler calls context.Succeed if the current authenticated user is the contact owner. Authorization handlers generally:

**Return** context.Succeed when the requirements are met.

**Comment by Rick-Anderson** [comment]
That's sound correct.

**Comment by Rick-Anderson** [comment]
The following is correct:

```
 if (resource.OwnerID == _userManager.GetUserId(context.User))
            {
                context.Succeed(requirement);
            }
```
