### ISSUE TITLE
Adding ASP.NET Core Identity to WebAPI

### ISSUE THREAD

**Issue by karezza** [aspnet/AspNetCore.Docs#16849]
I have an existing WebAPI currently configured to use JWT bearer tokens & ADFS.  The plan is to be able to spin up a copy in the cloud for others to access.  It seems like I want ASP.NET Core Identity and its ability to create tables, add users, etc...  It seems the next steps for me are to add ASP.NET Core Identity to my webapi but the documentation always indicates adding via a new project.  This documentation is also redirecting me to use IdentityServer instead.  Later though, I probably will have a website that will access the same user accounts.  I'm not sure how moving to IdentityServer from ADFS will help move things forward for me.  I know the focus of Identity is to provide the user interface, but it seems there is so much of benefit that it would be good for me to use.  I've found this site:  https://bitoftech.net/2015/01/21/asp-net-identity-2-with-asp-net-web-api-2-accounts-management/comment-page-2/?unapproved=146863&moderation-hash=0c5f02dbfecc62776e913483b115d58f#comment-146863, which is a bit dated but looks like what I need.  However, it does seem to be a lot of work and so I'm not sure if it's what I should be doing.  I don't want to reinvent the wheel if there exists a solution to make things simpler.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by karezza** [comment]
Note, if what you were intending to say was to use IdentityServer (which can optionally use the tables used by ASP.NET Core Identity as the identity database), maybe mention that more explicitly.  Still though, how to install to an existing project would be helpful (even if the directions are to open a new project, add per instructions & copy over your code to the new project).  Possibly relevant link at IdentityServer site:  http://docs.identityserver.io/en/latest/reference/aspnet_identity.html

**Comment by Rick-Anderson** [comment]
Per the doc:

ASP.NET Core Identity adds user interface (UI) login functionality to ASP.NET Core web apps. To secure web APIs and SPAs, use one of the following:

Azure Active Directory
Azure Active Directory B2C (Azure AD B2C)]
IdentityServer4

**Comment by karezza** [comment]
Is it possible to add ASP.NET Core Identity to an existing project or is the only way to create a new project?
