### ISSUE TITLE
Example of sending messages via SignalR other than from Controller / middleware?

### ISSUE THREAD

**Issue by andrei-traktatovich** [aspnet/AspNetCore.Docs#16846]
Is it possible to send outgoing SignalR messages other than from Controller / Middlerware? e.g. could an example be provided of accessing IHubContext to send messages from a service (a service not being used in the context of a controller?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
> Is it possible to send outgoing SignalR messages other than from Controller / Middlerware?

Yes, wherever you can inject services via DI you can get an `IHubContext<THub>` injected.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
