### ISSUE TITLE
Event log

### ISSUE THREAD

**Issue by ssteiner** [aspnet/AspNetCore.Docs#16843]
This page explains that the UseWindowsService() extension method enables logging to the event log. But, when I debug the app, I get zero entries in the event log. When I run the app as a service (using local system - so it has the necessary admin rights to create a new event source), nothing is logged to the event source either. So, what am I missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by ssteiner** [comment]
Oh, I see now.. as the default event log source config is to log only messages with warning or higher, the info messages I dumped never made it.

**Comment by guardrex** [comment]
@ssteiner Leave this open. I'd like to note that in the topic. This issue will close when the PR merges. Thanks for commenting on this.
