### ISSUE TITLE
Model XML comments are not shown in the schema tab

### ISSUE THREAD

**Issue by jzalmanovich** [aspnet/AspNetCore.Docs#16856]
The documentation shows only XML comments added on the controller method, how to make the model XML comments show on the schema tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Master issue, check here first. #16879

**Comment by RicoSuter** [comment]
XML Docs are also read in DTO schema generation. What exactly is your problem?
