### ISSUE TITLE
Is it possible to add ASP.NET Core Identity to an existing project or is the only way to create a new project?

### ISSUE THREAD

**Issue by karezza** [aspnet/AspNetCore.Docs#16853]
Documentation includes a way to add ASP.NET Core Identity to a new project, what about to an existing project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes

**Comment by klausenlie** [comment]
Hi. 
This is probably answerable in the same way as above, but I just want to be sure.
I have a project supported with a mysql database, where I haven`t implemented any authentication/authorization yet. I would like to use a user-table in my database containing the users and their roles for handling this. Is the documentation you have here, the right way to go? Point me in the right direction if there is a good starting pont. BTW, great  job you have done on documentation. It helps me a lot.
