### ISSUE TITLE
Clean up calls to string.ToLower / ToUpper throughout codebase 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#16855]
See https://github.com/dotnet/aspnetcore/issues/18774

cc @guardrex  @scottaddie

**Comment by serpent5** [comment]
Is this something I can look at?

**Comment by Rick-Anderson** [comment]
Yes. Open up the repo in VS code and do a global search replace - then review the changes.

**Comment by guardrex** [comment]
@serpent5 ...

Be careful with the `SlugifyParameterTransformer` in the RP conventions and Routing topics, since that code was supplied directly by engineering. They may have intended it to be `.ToLower` in that case.

**Comment by Rick-Anderson** [comment]
> Be careful with the `SlugifyParameterTransformer` in the RP conventions and Routing topics, since that code was supplied directly by engineering. They may have intended it to be `.ToLower` in those cases.

Leave that out of your PR and we'll do that in a separate PR. That one is probably more important to fix, but we can bring them in for review.

**Comment by guardrex** [comment]
See how they did it this way ......

https://github.com/dotnet/aspnetcore/blob/321327f84b2b22dcff2e9beb06a9a64236c5cced/src/Mvc/test/WebSites/RoutingWebSite/TestParameterTransformer.cs#L15

**Comment by guardrex** [comment]
I have a feel'in that it was on purpose: culture-aware is fine AFAICT from their code.

**Comment by Rick-Anderson** [comment]
Looks wrong to me, Slugs dependant on the server culture.

**Comment by serpent5** [comment]
Ok, thanks for the heads up. I'll leave that out for now then and report back once I know the extent of the changes involved for the other topics.
