### ISSUE TITLE
Setup doesn't work with ms-vscode.csharp 1.21.10, you must downgrade.

### ISSUE THREAD

**Issue by lessteward** [aspnet/AspNetCore.Docs#16857]
After opening the folder in this step (https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vscode?view=aspnetcore-3.1#through-visual-studio-code-interface), the OmniSharp log showed failures. These steps don't work with ms-vscode.csharp 1.21.10 and VSCode 1.41.1 on Mac 10.15.2. See https://github.com/OmniSharp/omnisharp-roslyn/issues/1693
Downgrading to 1.21.9 appears to be a workaround.

Please make sure the ms-vscode.csharp Quality Assurance team is aware of these issues. This is a very poor first interaction with VSCode and Azure.

Les Steward

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb0803d-d8d8-721e-75fc-6acb72edb85e
* Version Independent ID: 65d4eb31-3924-8fb0-3256-e033033e3260
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vscode?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vscode.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vscode.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ricardoserradas
* Microsoft Alias: **riserrad**

**Comment by Rick-Anderson** [comment]
We have no connection to the OmniSharp team. Can you open a bug with them?

**Comment by filipw** [comment]
we have already resolved the issue in the pre-release 1.21.11 
https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.11
