### ISSUE TITLE
Errant space breaks xref

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore.Docs#16865]
There's an errant space in the following:

> [Angular](xref: client-side/spa/angular)

Because of this, the text above is being shown in the rendered output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson Do you want a PR for this? I doubt it saves you much time given its just removing a space, so it's up to you.

**Comment by Rick-Anderson** [comment]
PR it please.
