### ISSUE TITLE
Explanation needed

### ISSUE THREAD

**Issue by Ricardoaraujo00** [aspnet/AspNetCore.Docs#16863]
Where does the IDataAccess comes from?

public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton&lt;IDataAccess, DataAccess&gt;();
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ricardoaraujo00 ... Let's defer that over to the ASP.NET Core DI topic, which goes into great detail and includes complete examples. This topic already links to that topic in the first sentence (introduction) and in the *Additional Resources* section at the bottom.

https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection
