### ISSUE TITLE
How to remove an user from all groups in signalr core 2.2?

### ISSUE THREAD

**Issue by asimus90** [aspnet/AspNetCore.Docs#16862]
Hey, i send group names by javascript signalr lib. And each requests send new groups list for user so i should remove past group subscribes. 
I couldn't find any example in google. So i am asking here.

How to remove all subscribed groups in one request and add new subscribes of group list? I don't know when i send new groups list to signalr server that user has already in other groups or not.

Please show me some examples about managing or mapping groups with connection ids or user names.

Groups: over 20k for now and it will be more (maybe over 50k)
So i need scalable solutions.
Thanks in advice!!

**Comment by guardrex** [comment]
@asimus90 If this issue is related to content in one of the topics, please close this and re-open using the **This Page** feedback button+form at the bottom of the topic. It will add metadata to track the issue and automatically ping the author of that topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
