### ISSUE TITLE
Signalr .net core Central exception handling.

### ISSUE THREAD

**Issue by sumanrajpura** [aspnet/AspNetCore.Docs#16861]
I want to handle exception from any method of Hub onto one single location as we can do that via app.UseExceptionHandler in webapi. Is there any way to do this in signalr.
I tried with GlobalHost.HubPipeline.AddModule(new ErrorHandlingPipelineModule()); but via this also exception is not getting handled.

**Comment by guardrex** [comment]
Hello @sumanrajpura ... Can you please close this issue and re-open it using the **This Page** feedback button+form at the bottom of the topic that you're looking at? It will add metadata for tracking the issue and automatically ping the author.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
