### ISSUE TITLE
Debug in Linux

### ISSUE THREAD

**Issue by Sm1le291** [aspnet/AspNetCore.Docs#16874]
Hi! What about instructions for Linux?
I found mentions of Linux in github but when I am trying to debug, I see this message: Unknown OS platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sm1le291 ... that's a point-in-time problem I believe that was also raised by another reader. I'll see if I can track down that issue for you. Stand-by for a few minutes while I look. :eyes:

**Comment by guardrex** [comment]
Ok ... back ... here it is ... track on this one ...

https://github.com/dotnet/aspnetcore/issues/12970

**Comment by guardrex** [comment]
btw - The source of that particular engineering issue for this problem was from DR at https://github.com/aspnet/AspNetCore.Docs/pull/16123#issuecomment-575384275 ... that PR is where it was discussed. If you scan the PR comments, you'll see us discussing it before DR provided the engineering reference.

**Comment by Sm1le291** [comment]
Hi @guardrex !Thanks for fast answer)
