### ISSUE TITLE
requestTimeout does apply to InProcess hosting model

### ISSUE THREAD

**Issue by eparizzi** [aspnet/AspNetCore.Docs#16870]
I have a ASP.NET Core 2.2 web app that was timing out after 2 minutes on a long request. It's running on the default InProcess model. I've added the requestTimeout attribute to the aspnetcore element in the web.config as mentioned in the following tip and it worked.
https://microsoft.github.io/AzureTipsAndTricks/blog/tip132.html

This page says that this attribute doesn't apply to InProcess hosting model, but the facts prove that it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The default hosting model for 2.2 was *out-of-process* unless you set it. Can you paste your project file (*.csproj*) in here?

**Comment by eparizzi** [comment]
Oh sorry, my mistake then.

So for a NET Core 3.1, with the default InProcess model, there shouldn't be a default timeout of 2 minutes?

**Comment by guardrex** [comment]
Yes, that's correct. The ANCM just *keeps on wait'in*.

**Comment by guardrex** [comment]
You can make your 2.2 app use in-proc ...

```xml
<PropertyGroup>
  <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
</PropertyGroup>
```

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#in-process-hosting-model-1

**Comment by guardrex** [comment]
I think we're good here. I checked the two versions of the doc, and it seems to compose correctly for 2.2 vs. 3.0 on the hosting model default. I'll close now.
