### ISSUE TITLE
Razor page convention SampleApp projects have the wrong handler method names

### ISSUE THREAD

**Issue by davecanderson** [aspnet/AspNetCore.Docs#16875]
The razor page handler methods need to be renamed in the [2.x and 3.x SampleApp](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/razor-pages/razor-pages-conventions/samples) projects.

Currently they are `Get()` but need to be `OnGet()` for the samples to work as indicated in the documentation. Only the `*Async()` handlers on the Index page currently work as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c32c8-ec27-1771-bb62-71d6aa55b1d6
* Version Independent ID: 99dc76fb-8762-20a6-d7b1-df3ce6e6fc4d
* Content: [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-3.1)
* Content Source: [aspnetcore/razor-pages/razor-pages-conventions.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by davecanderson** [comment]
NP @guardrex, you are fast with the fix, I was going to attempt the PR (my first) but you beat me to it.

BTW You also need to update the About and Contact pages #16876 only modifies the `OtherPages/`

**Comment by guardrex** [comment]
Yeah ... bugs 🐞 bother me. If I left it to tomorrow, I wouldn't sleep easy! :smile:
