### ISSUE TITLE
TaghelperComponents registration for taghelpers

### ISSUE THREAD

**Issue by LyonBlecher** [aspnet/AspNetCore.Docs#16882]
[EDIT by guardrex to add the metadata. @LyonBlecher, please use the **This Page** feedback button+form at the bottom of any topic to open an issue. It adds the metadata automatically and pings the author.]

I think it could be beneficial to include in the documentation that TaghelperComponents can be registered directly in a related TagHelper using ITagHelperComponentManager.  This will allow for encapsulation of a script or css script being included for a TagHelper without having to register it either in a razor page, controller or ConfigureServices Method.  It also indicates how to have it load only once even if there are multiple of the same TagHelpers on the same page.

Below is an example of how I achieved this:

```csharp
[HtmlTargetElement(TagName, TagStructure = TagStructure.NormalOrSelfClosing)]
    public class TestTaghelper : TagHelper
    {
        public const string TagName = "test";
        private readonly ITagHelperComponentManager _tagHelperComponentManager;

        public TestTaghelper(ITagHelperComponentManager tagHelperComponentManager)
        {
            _tagHelperComponentManager = tagHelperComponentManager;
        }

        public override void Init(TagHelperContext context)
        {
            if (!_tagHelperComponentManager.Components
                    .OfType<JavasScriptHeadTaghelperComponent>()
                        .Any(c => c.Script.Equals(filePath, System.StringComparison.InvariantCultureIgnoreCase)))
            {
                _tagHelperComponentManager.Components.Add(new JavasScriptHeadTaghelperComponent(filePath));
            }

            base.Init(context);
        }

        public async override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            output.PostElement.AppendHtml(@"<script type=""text/javascript"">test();</script>");

            await base.ProcessAsync(context, output);
        }
    }

   public class JavasScriptHeadTaghelperComponent : TagHelperComponent
    {
        public string Script { get; }

        public JavasScriptHeadTaghelperComponent(string script)
        {
            Script = script;
        }

        public override int Order => 1;

        public override Task ProcessAsync(TagHelperContext context,
                                          TagHelperOutput output)
        {
            if (string.Equals(context.TagName, "head",
                              StringComparison.OrdinalIgnoreCase))
            {
                output.PostContent.AppendHtml(@$"<script src=""{Script}""></script>");
            }

            return Task.CompletedTask;
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  please review sample and if we should add this to the doc.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen please review sample and if we should add this to the doc.

It's a nice idea but adding a component in another TagHelper is not something I'd typically recommend (there are definitely scenarios for it, but more often it's not the best idea). The more common recommended process is a bit more involved and given the minimal amount of asks for the feature I'm hesitant to add all the doc noise on how to do it. If this issue garners enough attention I'd be willing to reconsider that viewpoint.


@LyonBlecher the recommended approach would be to always register the ITagHelperComponent at the services layer or at the controller action level and then have your TagHelper put a stateful entry in either the view state, the TagHelper context items or have a separate stateful scoped service to track state. Your TagHelperComponent would act on that stateful entry.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
