### ISSUE TITLE
Link to "Angular documentation" is broken

### ISSUE THREAD

**Issue by luuktap** [aspnet/AspNetCore.Docs#16884]
https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#add-pages-images-styles-modules-etc

The link in to "Angular documentation" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#add-pages-images-styles-modules-etc)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by guardrex** [comment]
Thanks @luuktap ... I'll fix that up right now.

**Comment by guardrex** [comment]
It was just a cut-'n-paste issue ... a double "https:" on the link to `https://angular.io`.

**Comment by luuktap** [comment]
You're welcome. Thanks!
