### ISSUE TITLE
Provide examples for localization using Razor Pages

### ISSUE THREAD

**Issue by rm-code** [aspnet/AspNetCore.Docs#16881]
The guide focuses on MVC and should get a section for setting up localization properly when one uses ASP.Net Core Razor Pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
There's no significant differences. Should we get enough requests on this issue, we'll reconsider.

**Comment by hansly1985** [comment]
Can you provide a guide for ASP.Net Core Razor Pages. Because many things are differents.

**Comment by zwcloud** [comment]
Please provide a guide for ASP.Net Core Razor Pages.

**Comment by tonineumann** [comment]
ASP.net core razor pages. Tutorials on how to configure the server to serve up localized pages that contain numbers from the ViewModel so that they are localized in the user's requested culture. Changes needed to address server-side validation to interpret the localized numbers correctly.
