### ISSUE TITLE
Add control mapping to event argument types table

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#16887]
[EDIT by guardrex to add the metadata]

At the moment it's not easily discoverable what are all the UI interaction events and what arguments each one have. For example, I was looking for the event `keypressed` event for an `input` tag and found the docs in some third-party article. Would be nice to have a page, where we can list the following:

----
| Control | Event | Arguments|
| ------ | --- | ---|
| inptut type="text" | onkeypressed | KeyboardEventArgs |
--- 

The `KeyboardEWventArgs` in this case would be a link to the API docs for that type.

/cc @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-parameters)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We (almost) have that here :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#event-argument-types

We don't have the "control" bit.

**Comment by mkArtak** [comment]
Yes, the control mapping is quite important. Let's make sure we add that info too.
Also, we need to split this `Components` article into multiple smaller ones. For example, this section should be a separate topic on its own: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#event-handling

**Comment by guardrex** [comment]
There's a discussion wrt to breaking it up starting here :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/14353#issuecomment-532190780 TL;DR ... we'll just split out into new topics directly under the current *Components* topic.

We'll have to be careful because when later sections of the *Components* doc depend on earlier sections and that earlier coverage is pulled out dropped into new topics later in the TOC, it breaks the logical flow of coverage.

The issue [Improve Blazor component lifecycle page](https://github.com/aspnet/AspNetCore.Docs/issues/14353) was marked for the PU, but we've resolved several of the listed issues there. I'll close that one and open one or two new issues with ...
* What's left to be done from that issue.
* The goal of breaking up the *Components* topic. I can work this as soon as the [current batch of Blazor PRs merge](https://github.com/aspnet/AspNetCore.Docs/pulls/guardrex).

**Comment by guardrex** [comment]
@mkArtak *Done!* :+1: ... see https://github.com/aspnet/AspNetCore.Docs/issues/14353#issuecomment-583397031.

I'll work on splitting *Components* (at least the *Event Handling* section) after open PRs are merged. It would be 😈 *Merge Conflict Hell* 🔥 to try that right now.

On this issue, I'll work on getting those control elements into the argument types coverage.

**Comment by mkArtak** [comment]
This sounds good, @guardrex.
As for `how to split` the topics`, let me think a bit more about [this](https://github.com/aspnet/AspNetCore.Docs/issues/14353#issuecomment-532219598) and get back to you.

**Comment by mkArtakMSFT** [comment]
@guardrex I agree with @SteveSandersonMS 's comment here: https://github.com/aspnet/AspNetCore.Docs/issues/14353#issuecomment-532230456
As long as content is easy to find, we're good. Flat-level under Blazor is fine. Please make sure also to have an `Event handling` as a topic under root level too (Blazor/)

**Comment by guardrex** [comment]
@mkArtak Will do on *Event Handling*, and flat sounds great to me.

**Comment by guardrex** [comment]
@mkArtakMSFT Adding controls ... i.e., *elements* ... is going to be *very challenging/nearly impossible* without creating a mess of content to maintain.

It probably can't be covered in a table like the one that we have. The table holds DOM events that apply wildly to elements *in the same table cell*. It will hose the table trying to add all of the elements where each pertains.

Another problem is that many of these apply *theoretically* to all elements under HTML5 with caveats and gotchas. Trying to cover the caveats and gotchas is an additional challenge.

I recommend that developers go to the HTML spec (https://www.w3.org/TR/uievents/) (or any of many external sources that mirror it) for any given DOM event to see what it can apply to. Do you think that we can name a good 3rd party reference, perhaps something easily searchable, or just link the HTML event spec.
