### ISSUE TITLE
namespace RazorPagesMovie.Pages.Movies

### ISSUE THREAD

**Issue by Spock1024** [aspnet/AspNetCore.Docs#16893]
I've been following the tutorial from the start and the Pages/Movies/Index.cshtml.cs Page Model using Visual Studio Community 2019 Version 16.4.4 shows 'namespace RazorPagesMovie' instead of 'namespace RazorPagesMovie.Pages.Movies'. This cascades from the first reference on the page to multiple references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What OS and `dotnet --version` ?

**Comment by Rick-Anderson** [comment]
That's from running the wrong command
![image](https://user-images.githubusercontent.com/3605364/73976023-8b3fda00-48cb-11ea-895d-ed96b03d38af.png)

**Comment by Spock1024** [comment]
My operating system is Windows 10 Pro. The target framework I find on the projects properties tab is .NET Core 3.1. I could not run the command from your second comment as the picture cut off part of the command.

**Comment by Rick-Anderson** [comment]
That image is from the doc. You must have run the wrong command.
