### ISSUE TITLE
Doesn't mention Database First approach

### ISSUE THREAD

**Issue by ChuckBevitt** [aspnet/AspNetCore.Docs#16897]
This article only explains Razor with EntityFrameworkCore using the Code First approach which assumes that you're creating a new database or tables for the application. It ignores the Database First approach where you're creating an application for an existing database. While EntityFrameworkCore doesn't implement all of the wizards that .Net EntityFramework does, it is possible to generate the data models from an existing database. See the article at: https://www.entityframeworktutorial.net/efcore/create-model-for-existing-database-in-ef-core.aspx. Substitute this for the portion of the article that manually creates the data classes (to follow this example you'll have to manually create the SQL Server database / tables instead), then just continue on with the scaffolding. Of course, change the database connect string in the appsettings.json file to point to your database (to match this example, the database name has to be 'SchoolContext'). Works fine and avoids having manually create a bunch of matching data models for a preexisting, possible complex, database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See also the EF Core documentation: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext and https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold
