### ISSUE TITLE
Can’t connect securely to this page

### ISSUE THREAD

**Issue by pamparker** [aspnet/AspNetCore.Docs#16899]
Can’t connect securely to this page

This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What browser? FF is not supported.

**Comment by Rick-Anderson** [comment]
``

**Comment by pamparker** [comment]
Rick
Thanks for looking into this!
Please see the attached images if that helps.
As I enjoy your tutorials I have tried few in the past and I never had a
problem.
Not sure what I am doing wrong this time around.
Visual Studio community 2019 v 16.4.4 is up to date
Win 10 is the latest too
Tried all IE11, Edge, Chrome 79....
Strange why nobody else mention this problem?
Thanks again
PP

**Comment by Rick-Anderson** [comment]
@pamparker  you can't reply by email and attach images. It's better to enter information on GitHub and not use email.

You may need to reinstall VS. See https://github.com/dotnet/aspnetcore/issues/16892

Try running the Web app from the command line with `dotnet run`
