### ISSUE TITLE
can .net client connect to .net core server?

### ISSUE THREAD

**Issue by paytonli2013** [aspnet/AspNetCore.Docs#16906]
can a wpf client (fx452) connect to a hub host in aspnet core server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by godrage** [comment]
sadly not.

also encountering the problem that I have a .net core web api, but a .net framework client.
in theory .net framework can install the asp.net.core signalr client, but it's dll hell :(

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
