### ISSUE TITLE
Split Razor Components topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#16904]
Discussion ...

* https://github.com/aspnet/AspNetCore.Docs/issues/14353#issuecomment-532190780
* https://github.com/aspnet/AspNetCore.Docs/issues/16887#issuecomment-583245467

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by scottkuhl** [comment]
This section is way too large and covers too many topics.  Breaking it up will be easier to reference and will probably lead to more detail on each topic over time.

**Comment by guardrex** [comment]
It's been under discussion (offline) for year. We were waiting for a *critical mass* of content. 💣 We've reached that point now. 💥 After the current batch of open Blazor PRs merge, I'll work this issue.
