### ISSUE TITLE
Dead urls to other manuall pages

### ISSUE THREAD

**Issue by quarion** [aspnet/AspNetCore.Docs#16900]
Url to "Developing ASP.NET Core Applications with Docker over HTTPS" (https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https-development.md) is dead.

There is similar issues also on other docs.microsoft.com pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I'll pick this one up over the weekend, if there are no objections.

**Comment by serpent5** [comment]
> There is similar issues also on other docs.microsoft.com pages

@quarion: I was unable to find any other broken references to the `dotnet-docker` repo in here. Would you mind pointing out where you spotted these similar issues?
