### ISSUE TITLE
Incomplete statement | That gRPC is hosted on ASP.NET Core under logging section.

### ISSUE THREAD

**Issue by Dheeraj-GL** [aspnet/AspNetCore.Docs#16917]
Under **Logging** section it say "_gRPC services and the gRPC client write logs using .NET Core logging._ " & "_Since gRPC services are hosted on ASP.NET Core_"
This implies gRPC can not be used with .NET 4.X framework, which is not true. And because that is not true this means this document is incomplete and need more content to complete spl. case where it show how one can implement it with .NET 4.X framework.
# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [Yes] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @Dheeraj-GL ... It's best if you close this and re-open the issue using the **This Page** feedback button and form at the bottom of the topic. That will add metadata and automatically ping the author of the topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Dheeraj-GL** [comment]
Thanks @Rick-Anderson , i just did that :-)

**Comment by Dheeraj-GL** [comment]
> Hello @Dheeraj-GL ... It's best if you close this and re-open the issue using the **This Page** feedback button and form at the bottom of the topic. That will add metadata and automatically ping the author of the topic.

yes , i just did that. Thanks  :-)
