### ISSUE TITLE
AllowSynchronousIO default value

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore.Docs#16910]
The document currently says the following :
Call the UseHttpSys extension method when building the host, specifying any required HttpSysOptions. The following example sets options to their default values:

but the example shows:
options.AllowSynchronousIO = true;

Then below the example it says the default value for AllowSynchronousIO is false.

These contradict.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StevenTCramer ... Probably just an oversight when the default changed. I'll fix it on Monday. Thanks for calling it out.

**Comment by guardrex** [comment]
Yeah ... the example should change. If you flip the version selector on the topic you can see that the default changed.

It's just a quick fix that I'll do it right now.

**Comment by StevenTCramer** [comment]
@guardrex Ask and you shall receive.  Can't be any faster than that.  You ROCK!!!
