### ISSUE TITLE
The link above to view source code points at diff's and not source.  

### ISSUE THREAD

**Issue by pkellner** [aspnet/AspNetCore.Docs#16919]
This link:
https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/file-providers/samples

points to a diff and not actual source. I was hoping I'd find a simple example of how to get a list of resources in a console app.  I posted that question to SO hoping someone else knows.  

https://stackoverflow.com/questions/60128660/problem-reading-embedded-resource-with-asp-net-core-3-1-in-console-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @pkellner ... That link isn't supposed to point to "reference source" if you mean framework ref source. It points to sample apps ... and not "diff" in the GH sense of things.

You took the right approach going to SO, and I know ur aware of Gitter and Slack channels. AFAIK, there aren't resources to provide further content for this topic at this time, but I defer to management to decide that. I'm just guessing based on the workload.  :running_man: :sweat_smile:
