### ISSUE TITLE
Proxy over unix sockets

### ISSUE THREAD

**Issue by gbjbaanb** [aspnet/AspNetCore.Docs#16918]
This needs a bit more info to get it working.

The configuration of the Kestrel listener is unclear if it has to be made in code, or if it can be done in config.  (in fact the whole endpoints configuration section needs a little more clarity in this regard).

the unix side of things needs the nginx proxy conf as well. It should be:

edit the nginx conf file, within the location block change the proxy_pass entry from the usual "http:://localhost:5000;" to "http://unix:/tmp/xyz.sock:/;" (the http: and colon at the end are very important) and ensure that the socket is writeable by nginx, eg "chmod go+w /tmp/xyz.sock". Where xyz.sock is the name of the socket used in ListenUnixSocket().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#endpoint-configuration)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @gbjbaanb ... I'm OOF most of the weekend, but did you see the Nginx topic in the Host and Deploy node of the docs?
