### ISSUE TITLE
A more common usage scenario

### ISSUE THREAD

**Issue by billyjim** [aspnet/AspNetCore.Docs#16921]
The example app is really good at illustrating how to implement authorization.
However, it would also be useful to have an example of how to implement the more common requirement of administering roles (rather than contacts).
Many applications require administration pages for adding and editing users with roles and I'm pretty sure people who are looking for help with Authorization would like to see how to implement that scenario.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-ca/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What do you mean by administering roles (rather than contacts).

Contacts is arbitrary. Replace contacts with any resource you want to protect. 

The sample shows manager and admin authorization handlers.

**Comment by billyjim** [comment]
Hi Rick.
It's a scenario I encounter fairly often. The administrator of an app needs
to be able to add new users and assign them roles (typically, other
administrators, managers and users, but there can be many other roles). One
option is to have a user log in to the app (using, say, organization
credentials) and request to be added. Since they are authenticated, they
would be added with a role that has no permissions; the administrator can
then assign them a role appropriate to their usage requirements for the
app. Alternatively, the user would have to request to be added via some
other communication channel and the administrator would both add the new
user and assign them a role. Ideally, the user would be notified by email
that they have been added and their role would be confirmed.
This scenario is very similar to but a bit simpler than the example since
it doesn't need the authorization handlers. It can rely on declarative
authorization checks to control which pages of the app the user can access.
Regards,
Bill

**Comment by Rick-Anderson** [comment]
The seed method does that.

**Comment by billyjim** [comment]
The seed method initializes the Administrator and Manager roles, but there
is no way to add or maintain additional people and roles once the database
has been initialized.
It seemed a worthwhile suggestion for a worked example since it is such a
common requirement.
