### ISSUE TITLE
3.1 update: authorization conventions

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#16924]
.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did I miss something for 3.1?

**Comment by Rick-Anderson** [comment]
Opps, somehow it was on the 2.2 version selector

**Comment by guardrex** [comment]
No worries ... AFAIK, I have the ones I wrote at 3.1, but a *Sneaky Topic*:tm: certainly can get by me! :smile:

**Comment by Rick-Anderson** [comment]
> The concepts and examples shown in this topic apply equally to apps that use ASP.NET Core Identity. To use ASP.NET Core Identity, follow the guidance in

Why wasn't Identity used?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/74093952-77d47080-4a7d-11ea-9d91-de9925f5b594.png)

**Comment by guardrex** [comment]
I don't recall ... it's been so long since this one went up. Generally, I don't do *random*, so it might have been that in discussion with engineering that we decided to go with *KISS* on this ... it's certainly simple. Do you want me to try and research back to find out why? ... Otherwise, I don't have the cycles to change it given the Blazor workload. If someone is free to change it, I can review the updates.

**Comment by guardrex** [comment]
All of the conventions apply exactly as described either way. It would be pretty much *window dressing* to change it over.

**Comment by Rick-Anderson** [comment]
We've got bigger fish to fry.

**Comment by guardrex** [comment]
I think so. I know I'm 🏃😅 as far as the :eye: can see right now.
