### ISSUE TITLE
Surface enabling WebSockets for Blazor on IIS

### ISSUE THREAD

**Issue by 3strategy** [aspnet/AspNetCore.Docs#16937]
I posted a question with details here:
https://stackoverflow.com/questions/60148492/client-cannot-connect-to-signalr-hub-of-a-blazor-webassembly-app-running-on-iis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#create-a-hosted-blazor-webassembly-app-project)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Let me know if Quango's answer works ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#enabling-websockets-on-iis

In the meantime, I'll mark this for triage on the Blazor.Docs project for engineering to take a look at.

**Comment by guardrex** [comment]
I also recall ...

> When using IIS, sticky sessions are enabled with Application Request Routing. For more information, see HTTP Load Balancing using Application Request Routing.

... from ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#reconnection-to-the-same-server
