### ISSUE TITLE
Testing for a HttpContext session causes an exception

### ISSUE THREAD

**Issue by PeterPann23** [aspnet/AspNetCore.Docs#16936]
One should be able to test if session is available, however if not configuring session and simply testing is session is null will cause an exception. The documentation states that testing ISession.IsAvailable can test if session is loaded however
a test on  HttpContext.Session == null || !HttpContext.Session.IsAvailable will crash middleware, simplified code below should show the issue

public Task InvokeAsync(HttpContext context)
{
    if (context.Session == null || !context.Session.IsAvailable)
   {
   }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`context?.Session?.IsAvailable`
