### ISSUE TITLE
Kestrel only supports Get and Post by default

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#16947]
The comment was machine-translated

@dotnba commented on [Sun Feb 09 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/241)

How to support Put / Delete and other HTTP methods

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [ASP.NET Core 中的 Kestrel Web 服务器实现](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x&view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sun Feb 09 2020](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/241#issuecomment-583809052)

Hello, @dotnba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
The server doesn't directly pertain to the app's behavior for HTTP verbs (e.g., PUT, DELETE, etc.).

Using Razor Pages, you can find information here ...

https://docs.microsoft.com/zh-cn/aspnet/core/razor-pages/

For MVC, here ...

https://docs.microsoft.com/zh-cn/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#attribute-routing-with-httpverb-attributes
