### ISSUE TITLE
Outdated info about ExpireTimeSpan

### ISSUE THREAD

**Issue by ygoe** [aspnet/AspNetCore.Docs#16960]
This page contains a link to the ExpireTimeSpan property which isn't available for the current ASP.NET Core version (only 1.x). This information is outdated. Also, it would be helpful to know how I should set the auth+cookie expiration time so that it works in current and future versions of ASP.NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x&view=aspnetcore-3.1#absolute-cookie-expiration-1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ygoe ... Looks like it just needs a cross-link update to ....

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.expiretimespan?view=aspnetcore-3.1#Microsoft_AspNetCore_Authentication_Cookies_CookieAuthenticationOptions_ExpireTimeSpan
