### ISSUE TITLE
Bidirectional communication

### ISSUE THREAD

**Issue by cowwoc** [aspnet/AspNetCore.Docs#16963]
**Describe the new topic**

Please provide an example showing bi-directional communication where the server sends information to the client, and the client acknowledges receipt based on a message id.

**Justification**: SignalR does not guarantee message delivery. This design pattern can be used to detect dropped messages.

**Comment by guardrex** [comment]
Hello @cowwoc ... Suggest that you close this and re-open it using the **This Page** feedback button+form at the bottom of the topic that it pertains to. It will automatically add topic metadata to the issue and automatically ping the author of the topic.
