### ISSUE TITLE
Environment example not rendering properly

### ISSUE THREAD

**Issue by MikeCheel** [aspnet/AspNetCore.Docs#16962]
Looks like:

entity open and closed brackets are being displayed as html entities

`&lt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MikeCheel ... Can you be more specific. You mean in the sample app?

**Comment by guardrex** [comment]
If you're referring to the Environment Tag Helper example, that's by-design. One doesn't want the browser to interpret those as tags. We want the browser to display which tag is being rendered. Perhaps, it would be better (less confusing) to just **_Say It!_**:tm:

```html
<div>The environment is Development.</div>
```

... instead of the current ...

```html
<div>&lt;environment include="Development"&gt;</div>
```

**Comment by guardrex** [comment]
🤔 I like the last one actually. I'll go ahead on the assumption that this is what you're inquiring about. I have a minute here. ............but only *a minute!* 🏃😅
