### ISSUE TITLE
Does validation run everytime a new IOptionsSnapshot<> instance is created

### ISSUE THREAD

**Issue by ling1726** [aspnet/AspNetCore.Docs#16976]
`Options validation doesn't guard against options modifications after the options are initially configured and validated.`

Does this apply for IOptionsSnapshot ? since that instance is scoped per request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ling1726, *yes* ... that's my understanding. After initial config and initial validation, options are **_not validated again_** as the statement says.

**Comment by ling1726** [comment]
Is it possible to do a more thorough check please, I'm reading the source code and it seems that the OptionsCache caches the factory create, which should run the the validations again.

https://github.com/dotnet/extensions/blob/730c5d93b2e3f2dc0f045c90e79ad9443ea169da/src/Options/Options/src/OptionsCache.cs

**Comment by guardrex** [comment]
Sure, let's ask @HaoK ... he developed that code and approved the doc remark, so we can ask him.

**Comment by ling1726** [comment]
Just an addedndum, I might have been wrong with my previous comment, but it seems that IOptionsSnapshot is created with a scoped instance of OptionsManager which includes a private instance cache. Therefore each not IOptionsSnapshot should begin with a fresh cache.

@guardrex  thanks for forwarding this on to the author. If validation could be run on each IOptionsSnapshot<> it would be a great feature to sell :)

**Comment by HaoK** [comment]
Options are validated by the options factory when instances are created.  So it depends on the lifetime.  IOptionsSnapshots are created once per request so they are validated the first time they are requested for each request.

**Comment by guardrex** [comment]
Thanks @HaoK ... I'll get this updated.

**Comment by ling1726** [comment]
Thanks @HaoK, this is quite an important point for use cases that involve refresh/override of settings in IConfiguration during runtime
