### ISSUE TITLE
Links to storage SDK methods are outdated

### ISSUE THREAD

**Issue by kaerm** [aspnet/AspNetCore.Docs#16970]
Links to the storage sdk methods lead to a legacy SDK. They should be referring to the new, v12 SDK version.

The links are listed here: "The topic demonstrates UploadFromFileAsync, but UploadFromStreamAsync"

The links should point to the newest library https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares?view=azure-dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @kaerm!
