### ISSUE TITLE
Article suggests unit test shouldn't pass an invalid model to an action method

### ISSUE THREAD

**Issue by escalonn** [aspnet/AspNetCore.Docs#16993]
Article includes this bizarre claim, with code to match.

&gt;The test doesn't attempt to pass in an invalid model. Passing an invalid model isn't a valid approach, since model binding isn't running (although an integration test does use model binding).

Maybe I'm missing something but that doesn't make any sense. If the method is supposed to behave in a certain way when its parameter meets a certain condition, why would that not be a candidate for unit testing? Sure, when the app runs, those values come from model binding, but that has no relevance to the unit test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
I think the point was that yes you can pass in an invalid model but it won’t be seen as such because model validation doesn’t take place if you’re just calling the method directly as in a unit test. Using an integration/functional test, you do get model binding and model validation, which is why it’s often better to test controller actions using these kinds of tests.

**Comment by escalonn** [comment]
OK, if "invalid" is restricted to refer to the validation that runs before the action method, and not coded in it, then I see the sense in that.
