### ISSUE TITLE
Configuring MemoryCache when out of the box enabled

### ISSUE THREAD

**Issue by eholman** [aspnet/AspNetCore.Docs#16992]
Like the documentation states that for most apps IMemoryCache is enabled it also should mention how to be able to configure it.

In my case I want to configure SizeLimit of the MemoryCache, because it's advised to do so.

Finally I found it's possible to do it in the ConfigureServices override:

    public override void ConfigureServices(IServiceCollection services)
    {
      services.Configure<MemoryCacheOptions>(options => { options.SizeLimit = 1000; });
    }

Created Doc request in order to help others who are looking for this because searching for in on the internet didn't brought me much!

I don't know how to link it to the documentation page, but it's about this page: https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1

**Comment by guardrex** [comment]
Hello @eholman ...

> I don't know how to link it to the documentation page

Close this issue and re-open using the **This Page** feedback button and form at the bottom of the topic.
