### ISSUE TITLE
Reference to MvcMovie.db in Razor Pages example

### ISSUE THREAD

**Issue by shimst3r** [aspnet/AspNetCore.Docs#17008]
In the `Visual Studio Code` tab of [add a database connection string](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-a-database-connection-string), the property `ConnectionStrings.MovieContext` points to a `MvcMovie.db`.

In the context of a Razor Pages app tutorial, it might be more suitable to call the database `RazorPagesMovie.db` or similar.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-a-database-connection-string)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not the convention. Check out the other connection string.
