### ISSUE TITLE
URLs/Ports cannot be specified using Configuration as documented

### ISSUE THREAD

**Issue by bcrosnier** [aspnet/AspNetCore.Docs#17009]
In the *Endpoint Configuration section*, on how to configure Kestrel endpoints, the page mentions:
"*Specify URLs using the: urls host configuration key.*"

This information is misleading and implies that the Configuration key `urls` works as intended, which is definitely not the case (https://github.com/aspnet/Hosting/issues/1299)

Funnily enough, one supported way to setup endpoints from configuration, to my knowledge, is used in the `appsettings.json` example later on in the section (with the `IConfiguration` key being `Kestrel:Endpoints:Http:Url` for a HTTP endpoint), but:

1. ~No explanation whatsoever is offered on how the `Kestrel:Endpoints` section works,~
2. ~The `Endpoint` property does *not actually exist* in `KestrelServerOptions` (I suppose there's a Configuration binder somewhere),~
3. ~Unlike other means of configuration like the `ASPNETCORE_URLS` env. var, the `UseUrls()` method, and the `--urls` program argument, the `Kestrel:Endpoints:Http:Url` key only supports a single endpoint, meaning I can't use `http://127.0.0.1:12345;http://::1:12345` to listen on both IPv4 and IPv6, to the best of my knowledge.~

I just wanted a `Urls` property somewhere in my `IConfiguration`. Have I been missing something?

Cheers!

---
## Erratum 1

All three points are addressed in the `Schema notes:` section, and a valid configuration for the use case mentioned above looks something like this:

```json
{
  "Kestrel": {
    "Endpoints": {
      "MyHttpV4": {
        "Url": "http://127.0.0.1:12345"
      },
      "MyHttpV6": {
        "Url": "http://[::1]:12345"
      }
    }
  }
}
```

I propose the *urls host configuration key* could be modified to explicit this behavior. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bcrosnier ...

> I propose the urls host configuration key could be modified to explicit this behavior.

That's product feedback, and we only work on documentation on this repo. You can provide that feedback to the product unit on the engineering repo at https://github.com/dotnet/aspnetcore/issues.

There's in-design/in-progress work in this area, some of the issues are ...

* https://github.com/dotnet/aspnetcore/issues/18660 &ndash; Working on certification configuration via appsettings file.
* https://github.com/dotnet/aspnetcore/issues/2867 &ndash; JSON schema for appsettings.
* https://github.com/dotnet/aspnetcore/issues/4765 &ndash; Additional KestrelServerOptions from config.
