### ISSUE TITLE
value of input field is changed inn inspector but not in browser window.

### ISSUE THREAD

**Issue by NareshBisht** [aspnet/AspNetCore.Docs#17012]
When back button is pressed in chrome the value of input field is changed in inspector but not in browser window.
![Untitled](https://user-images.githubusercontent.com/48261653/74536898-030ea400-4f5f-11ea-87d8-3d54ba63e0df.png)

**Comment by NareshBisht** [comment]
Here is the code. The code is very simple. The same code works properly in edge but does not work in chrome or opera.

![Screenshot (99)](https://user-images.githubusercontent.com/48261653/74538326-fdff2400-4f61-11ea-9d91-9fa221402819.png)
![Screenshot (100)](https://user-images.githubusercontent.com/48261653/74538328-ffc8e780-4f61-11ea-8768-fb0a229f66a4.png)

**Comment by guardrex** [comment]
Hello @NareshBisht ... is this associated with an example (or guidance) in a specific topic? If so, close this issue and re-open it using the **This Page** feedback button and form at the bottom of the topic. It will attach metadata to the issue and ping the author automatically. If this isn't related to a specific topic but more of a bug report for engineering, then close here and re-open it on the engineering repo for the product unit to take a look at it :point_right: https://github.com/dotnet/aspnetcore/issues.
