### ISSUE TITLE
C# (Xamarin) client unable to receive SignalR (Core) event with custom object

### ISSUE THREAD

**Issue by VictorK1902** [aspnet/AspNetCore.Docs#17014]
# Issue description 

My web (JS) client has no issue receiving the event with custom object but my Xamarin (C#) one does.

Eventually I had to go back and list all the properties on the server hub and config the client accordingly to read and parse these.

So given the type:

    NewMessageResponse {
        public string Message{ get; set; }
        public Guid ID { get; set; }
    }

The following doesnt work:

    ServerHub:
        Clients.Clients(stringIds).NewMessage(new NewMessageResponse (){
            Message = "Test", ID = Guid.Empty
        });
    C#/Xamarin client:
        hubConnection.On<NewMessageResponse>("NewMessage", (response) =>{
            // print message
        });
        hubConnection.On<string, Guid>("NewMessage", (Message, ID) =>{
            // print message
        });

The following approach works:

    ServerHub:
        Clients.Clients(stringIds).NewMessage("Test", Guid.Empty);
    C#/Xamarin client:
        hubConnection.On<string, Guid>("NewMessage", (Message, ID) =>{
            // print message
        });

    

# Software versions

Server: NET Core 3.1
Client: Xamarin Forms 4.4.0.991640, NET Standard 2.0
Microsoft.AspNetCore.SignalR.Client 3.1.1

**Comment by guardrex** [comment]
@VictorK1902 ... does this relate to a specific topic? If so, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the topic. It will add metadata that cross-links the topic and automatically pings the author.
