### ISSUE TITLE
What does "Your ASP.NET Core project needs to reference .NET framework..." mean in the article that links to this repo?

### ISSUE THREAD

**Issue by matthewkrieger** [aspnet/AspNetCore.Docs#17016]
At https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1 it says:

> Your ASP.NET Core project needs to reference .NET framework and EF6. For example, the .csproj file of your ASP.NET Core project will look similar to the following example (only relevant parts of the file are shown).

What does "...needs to reference .NET Framework..." mean?  The article and sample project seem to be showing that the ASP.NET Core application needs to *target* (not reference, but target) the .NET Framework.  But what is further confusing is that in the sample project the ASP.NET Core application is not targeting Core at all but is *only* targeting the full Framework.  So I am not clear what is the scenario as I thought the doc was about how to reference regular non-core EF 6 from ASP.NET Core projects.

**Comment by guardrex** [comment]
@matthewkrieger ... For a faster response (*maybe* lol) ... close this issue and re-open it using the **This Page** feedback button+form at the bottom of the topic. It will add metadata that cross-links the topic and automatically pings the author.

**Comment by matthewkrieger** [comment]
@guardrex Thanks for the tip will do.  Reposted here https://github.com/aspnet/AspNetCore.Docs/issues/17019.
