### ISSUE TITLE
Grunt Functionality is useless outside of Visual Studio, no details on how to automate

### ISSUE THREAD

**Issue by ExcaliburVT** [aspnet/AspNetCore.Docs#17018]
Applies to: https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt?view=aspnetcore-3.1

# Issue description

I have implemented Grunt as described in this article but once you start trying to use the build functionality in Azure DevOps Pipelines the entire process falls apart since apparently there is nothing in the csproj file that actually EXECUTES grunt, it seems that the functionality is hard baked into Visual Studio?  This is compounded by the fact that by using LibMan (which is properly restored during build by a nuget package) I cannot simply pre-run a grunt command in the build pipeline BEFORE the build/publish command because the javascript libraries i'm trying to bundle dont exist yet.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core 3.1

**Comment by guardrex** [comment]
@ExcaliburVT ... For a faster response (*maybe* :smile:) ... close this issue and re-open it using the **This Page** feedback button+form at the bottom of the topic. It will add metadata that cross-links the topic and automatically pings the author.

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/17025.
