### ISSUE TITLE
Registration Confirmation and Email Confirmation Pages

### ISSUE THREAD

**Issue by rhires** [aspnet/AspNetCore.Docs#17015]
With 3.1, the registration confirmation and email confirmation pages aren't automatically in the project anymore, they are compiled into it. Is that correct? If so, do I need to decompile the sources if I want to modify the Identity/Account/RegisterConfirmation and Identity/Account/ConfirmEmail pages? Is there some guidance or documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rhires** [comment]
Ok - I figured it out. The bottom of this page should have a link to the scaffolding page and specific heading that relates to the idea that you can customize the two pages I mention above - and on that page you should make it clear that there is "without authorization" but for the reverse case, it should say "with authorization enabled (or configured)". (Saying it a different way) On this page you should say you can override the precompiled pages by using the Identity Scaffolding which will allow you to add specific pages so that you can then customized them. The way it appears on the Scaffolding page, it looks like you're going to wipe out everything that already exists, which is a scary prospect. You should make it clear that this is only to add specific certain pages that you choose to override from the precompiled sources. Thanks!

**Comment by Rick-Anderson** [comment]
That's in the scaffold doc:

Generated code takes precedence over the same code in the Identity RCL.
