### ISSUE TITLE
Example not encoded properly

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore.Docs#17011]
The 2nd code example under: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#environments

the Code says:
```
&lt;environment include="Development"&gt;
    &lt;div&gt;&lt;environment include="Development"&gt;&lt;/div&gt;
&lt;/environment&gt;
&lt;environment exclude="Development"&gt;
    &lt;div&gt;&lt;environment exclude="Development"&gt;&lt;/div&gt;
&lt;/environment&gt;
&lt;environment include="Staging,Development,Staging_2"&gt;
    &lt;div&gt;
        &lt;environment include="Staging,Development,Staging_2"&gt;
    &lt;/div&gt;
&lt;/environment&gt;
```
However with the use of `&lt;` and `&gt;`, I presume the example was incomplete or erroneously entered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#environments)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kevingates ... The markup is correct. The plan there is that the contents of the `<div>` elements should merely be rendered ... we don't want those encoded angle brackets to be considered **tags** by the browser.

I made a change to an example on https://github.com/aspnet/AspNetCore.Docs/pull/16965, but it looks like it wasn't the file in use at that point. I'll put another PR in to fix this example. Thanks for calling it out (*again!* 🙈).
