### ISSUE TITLE
What does "Your ASP.NET Core project needs to reference .NET framework..." mean in the article that links to this repo?

### ISSUE THREAD

**Issue by matthewkrieger** [aspnet/AspNetCore.Docs#17019]
At https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1 it says:

"Your ASP.NET Core project needs to reference .NET framework and EF6. For example, the .csproj file of your ASP.NET Core project will look similar to the following example (only relevant parts of the file are shown)."

What does "...needs to reference .NET Framework..." mean? The article and sample project seem to be showing that the ASP.NET Core application needs to target (not reference, but target) the .NET Framework. But what is further confusing is that in the sample project the ASP.NET Core application is not targeting Core at all but is only targeting the full Framework. So I am not clear what is the scenario as I thought the doc was about how to reference regular non-core EF 6 from ASP.NET Core projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [Get Started with ASP.NET Core and Entity Framework 6](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It should probably say target. And yest, it must target the full framework.

**Comment by matthewkrieger** [comment]
So it must target *both* asp.net core *and* the .net framework?  Because the premise here was that the web project was ASP.NET *Core*.

**Comment by Rick-Anderson** [comment]
You can only target one framework.

**Comment by matthewkrieger** [comment]
Then I am fundamentally confused.  If the next step is for me to RTFM please feel free to tell me.  Because again I thought the web project was ASP.NET Core by definition, so how would it target the full .net framework?  What am I missing?

**Comment by matthewkrieger** [comment]
Understood - thank you.
