### ISSUE TITLE
Grunt Functionality is useless outside of Visual Studio

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#17025]
*Opened by @ExcaliburVT at https://github.com/aspnet/AspNetCore.Docs/issues/17018.*

> no details on how to automate
>
> I have implemented Grunt as described in this article but once you start trying to use the build functionality in Azure DevOps Pipelines the entire process falls apart since apparently there is nothing in the csproj file that actually EXECUTES grunt, it seems that the functionality is hard baked into Visual Studio? This is compounded by the fact that by using LibMan (which is properly restored during build by a nuget package) I cannot simply pre-run a grunt command in the build pipeline BEFORE the build/publish command because the javascript libraries i'm trying to bundle dont exist yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3b23da-ff3d-daf6-c56a-2b8ddf79f805
* Version Independent ID: 5ea39e72-fcfc-ddbe-2f4d-f4166dfbe5a8
* Content: [Use Grunt in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/using-grunt.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/using-grunt.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
My bad :point_up: ... thought I was labeling another issue.

**Comment by Rick-Anderson** [comment]
> I have implemented Grunt as described in this article but once you start trying to use the build functionality in Azure DevOps Pipelines the entire process falls apart since apparently there is nothing in the csproj file that actually EXECUTES grunt, it seems that the functionality is hard baked into Visual Studio

The doc doesn't have anything on  Grunt in Azure DevOps Pipelines  and we have no plans to support that.
