### ISSUE TITLE
ASP.NET Core 3.1 API template does not install wwwroot page like in repo or video

### ISSUE THREAD

**Issue by bunda3d** [aspnet/AspNetCore.Docs#17034]
Good tutorial, but ASP.NET Core 3.1 API template doesn't seem to install wwwroot page like in the code github code repo attached to this page, or the youtube video linked. Is this why my endpoints are returning 400 via HTTP? (resolves to WeatherForecast class/controller URLs still). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by bunda3d** [comment]
You're correct, the tutorial works well. --I was originally confused on the routing that defaults Visual Studio's IISexpress to display the "https://localhost:5001/WeatherForecast" endpoint. 

How does this work? It seems some of it comes from the project properties settings, which updates the development env. "launch.json" file settings... I read several of your pages on routing for ASP.NET Core API endpoints, but don't quite get the ins and outs of the newer API template with WeatherForecast demo, specifically how to set up default dev env routing so that on project launch (CTRL+F5), a browser launches to the API endpoints URL of my choosing?
