### ISSUE TITLE
How to enable Rewind when using the Pipeline API?

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/AspNetCore.Docs#17039]
As the docs says "Pipelines are recommended over streams", people now are trying the new Pipes API.  I notice there's a  [dev blog](https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/#user-content-partial-reads):

> the other core pipelines feature is the ability to peek at data in the Pipe without actually consuming it.

But how could we read the HTTP Request Body without actually consuming it? I thought if we don't invoke `pipeReader.AdvanceTo(s,e)`, the body won't be consumed. So I tried create a middleware like this:
```
async Task IMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next)
    {
        if(httpContext.Request.Method != HttpMethods.Post){
            return;
        }
        PipeReader bodyReader = httpContext.Request.BodyReader;
        ReadResult readResult;
        while(true){
            readResult = await bodyReader.ReadAsync();
            if(readResult.IsCompleted)
            {
                break;
            }
        }
        Process(readResult.Buffer);  // process the read only sequence
        // we don't invoke the bodyReader.AdvanceTo(s,e) method here
        bodyReader.Complete();     //  with this line , or without this line, both doesn't work
    }
```

But it doesn't work. Is there any guide for this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b15fd3-39b5-3ad9-8c4e-b8160360dee9
* Version Independent ID: c33981af-93ce-d4be-a265-5d4696666c7a
* Content: [Request and Response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/request-response.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/request-response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by jkotalik** [comment]
You can call `PipeReader.Advance(readResult.Buffer.Start, readResult.Buffer.End);` By passing in readResult.Buffer.Start for consumed, you are saying that you haven't consumed any of the ReadResult. By passing in readResult.Buffer.End, you are saying you _have_ examined everything, which tells the Pipe to not free any buffers and the next time ReadAsync returns, more data would be in the buffer.

As a general rule as well, each call to ReadAsync must be paired with a call to Advance.

```c#
async Task IMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next)
    {
        if(httpContext.Request.Method != HttpMethods.Post){
            return;
        }
        PipeReader bodyReader = httpContext.Request.BodyReader;
        ReadResult readResult;
        while(true){
            readResult = await bodyReader.ReadAsync();
            if(readResult.IsCompleted)
            {
                break;
            }
            bodyReader.Advance(readResult.Buffer.Start, readResult.Buffer.End);
        }
        Process(readResult.Buffer);  // process the read only sequence
        bodyReader.Complete();     //  with this line , or without this line, both doesn't work
    }
```

**Comment by Rick-Anderson** [comment]
@newbienewbie  that's all covered in https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines

**Comment by newbienewbie** [comment]
@jkotalik @Rick-Anderson Thanks so much for your detailed explanation!
