### ISSUE TITLE
How to customize JSON serialization settings

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#241]
Some documentation of the available hooks for customizing JSON serialization would be useful.
- Default input and output JSON formatter settings with MvcOptions.JsonSerializerSettings
- Per action ouput JSON formatter settings with Controller.Json(value, JsonSerializerSettings)
- Serializing inside a view settings with Json.Serialize(value, JsonSerializerSettings)

**Comment by Rick-Anderson** [comment]
@MikeWasson  please comment.

**Comment by Rick-Anderson** [comment]
@JamesNK 	if you can provide a first draft we can finish it off.

**Comment by JamesNK** [comment]
I think this can be put on hold until the JSON story in ASP.NET Core 3 is sorted out. I'd hate to add something that is almost immediately removed 😬
