### ISSUE TITLE
 Localization: add troubleshooting section

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#3166]
See https://forums.asp.net/t/2117531.aspx?Localization+using+vs+2017

https://forums.asp.net/t/2118898.aspx?Localization

**Comment by hishamco** [comment]
Can you elaborate what should be written in this section?

**Comment by Rick-Anderson** [comment]
@hishamco can you PR the first draft of this doc? Let me know how I can help. I could create a PR with the TOC (table of content) update and an article stub if that would help.

**Comment by hishamco** [comment]
Sure, let me start on this before the localization extensibility one, but one more thing shall I do it as FAQ or is there a guidance which I don't know about troubleshooting docs

**Comment by Rick-Anderson** [comment]
You could create it as a new issue FAQ. I'll mark it as a discussion issue.

**Comment by hishamco** [comment]
@Rick-Anderson seems you forgot to close this one
