### ISSUE TITLE
document aspnet-codegenerator 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#3208]
Document the options `aspnet-codegenerator` in https://github.com/dotnet/docs/issues/10100

```
dotnet aspnet-codegenerator -h
Command Line: -h

Usage: Code Generation [options]

Options:
  -h|--help                Show help information
  -p|--project             Path to project.json
  -n|--nuget-package-dir   Path to check for Nuget packages
  -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
  -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net451)
  -b|--build-base-path
  --no-dispatch
  --no-build
```

@prafullbhosale  should I create this article?

**Comment by Rick-Anderson** [comment]
@prafullbhosale  the following command is missing client side validation:

```
dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout
```

How do I get the views to have the following:
```
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
```

Once I get that magic flag I think I'll have identical scaffolding to the VS scaffolder. That's my goal, to have the same code from VS Code and VS 2017.

**Comment by prafullbhosale** [comment]
`--referenceScriptLibraries` should add that section.

**Comment by Rick-Anderson** [comment]
@prafullbhosale if you can provide me with a rough draft i'll write the article. See https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model and search for The following table details the ASP.NET Core code generators` parameters:
