### ISSUE TITLE
2.0 Range requests in MVC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#3657]
Near the end of the planning video - ask Dan Roth for more details.

**Comment by guardrex** [comment]
References:

* https://github.com/aspnet/Mvc/issues/3702
* https://github.com/aspnet/StaticFiles/pull/185
* https://github.com/aspnet/Mvc/issues/3702
* https://github.com/aspnet/Mvc/pull/6150

**Comment by guardrex** [comment]
@scottaddie @Rick-Anderson @rachelappel Before I self-assign and put this on the list, I haven't directly used range requests over the years. I've done a bit of video with some libs that used range requests, but I haven't used range requests directly.

If we all have about the same experience with directly making range requests (zero 😁 in my case), then it won't matter which one of us takes this, and I may as well add it to the list. I'd see if Jass will help me with it ... outline ... sample.

**Comment by scottaddie** [comment]
@guardrex I've never used this feature before.

**Comment by guardrex** [comment]
Ok, I'll give it a go. I'm sure Jass will help me out *when* I get stuck. :smile:

**Comment by Rick-Anderson** [comment]
@tdykstra  see [this](https://github.com/aspnet/Mvc/issues/6780#issuecomment-332348611) comment.
