### ISSUE TITLE
Update 2.0 uploading large files with streaming

### ISSUE THREAD

**Issue by chikien276** [aspnet/AspNetCore.Docs#3989]
[Current](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md) document uses `MultipartRequestHelper` with `MediaTypeHeaderValue` from package `Microsoft.Net.Http.Headers` which is incompatible with current ASP.NET Core 2.0 because it uses `MediaTypeHeaderValue` from package `System.Net.Http.Headers`

https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads

**Comment by Rick-Anderson** [comment]
Update mvc/models/file-uploads.md to 2.0
Archive 1.x version, don't use tabs and two samples. Point to archive and 1.1 code.

**Comment by Rick-Anderson** [comment]
@chikien276  any chance you could submit a PR with the updates for 2.0?

**Comment by chikien276** [comment]
I have a working version of it which uses both `Microsoft.Net.Http.Headers` and `System.Net.Http.Headers`. I am not sure it is right way to do this.

**Comment by Rick-Anderson** [comment]
@chikien276 `Microsoft.Net.Http.Headers`  is the one to use for  ASP.NET Core.
@jbagga  can you confirm?

**Comment by rynowak** [comment]
`Microsoft.Net.Http.Headers` is corect

**Comment by chikien276** [comment]
@Rick-Anderson I'm sorry. ASP.NET Core does use `Microsoft.Net.Http.Headers`. I mean I still have trouble in getting `Encoding` out of `MultipartSection` due to lacking of `Encoding` property in `Microsoft.Net.Http.Headers.MediaTypeHeaderValue` parsed from "MultipartSection.ContentType". Due to the urgency of my project, I ignored it and return to UTF-8 by default and haven't tried to resolve it since then.

**Comment by Rick-Anderson** [comment]
Doc needs UE pass.

**Comment by Rick-Anderson** [comment]
@guardrex  see customer comments:
![image](https://user-images.githubusercontent.com/3605364/35306817-d5d1c2fe-0043-11e8-9f87-e5322045df4f.png)

**Comment by guardrex** [comment]
These two related issues didn't cross reference ... until now that is. :smile: https://github.com/aspnet/Docs/issues/4777

**Comment by chikien276** [comment]
I wrote a working helper [here](https://github.com/chikien276/MultipartHelper/blob/master/ChiKien276.AspNetCore.MultipartHelper/FileUploadHelper.cs). This helper simplify the process as you can see [here](https://github.com/chikien276/MultipartHelper/blob/master/readme.md#usage). We've been using this for our internal product for a while. Hope it's helpful in someway.

**Comment by scottaddie** [comment]
@guardrex @Rick-Anderson I'll take care of this one. I'm already working on a related issue.

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
