### ISSUE TITLE
Debugging .NET Core and ASP.NET Core sources

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#4155]
In Visual Studio 2017 (15.3.5 and later)
 
* Un-check  **Enable Just  My Code**  in **Tools -> Options -> Debugging -> General**

![image](https://user-images.githubusercontent.com/3605364/31796868-22accaba-b4c7-11e7-8d8c-cb37ef5e8879.png)

* Verify **Enable Source Link support**  is checked.

![image](https://user-images.githubusercontent.com/3605364/31796932-691d53a2-b4c7-11e7-81f1-15ece80c67d0.png)

* Enable **Microsoft Symbol Servers** in **Tool -> Options -> Debugging -> Symbols**

![image](https://user-images.githubusercontent.com/3605364/31797007-b753bb92-b4c7-11e7-982e-530608d8aa04.png)
 
You can step into any ASP.NET Core code and Visual Studio will show you the source code.  For example:

* Set a break point in ` OnGet`  in *Pages\About.cshtml.cs *
* Double click on a line in the **Call Stack**.

![image](https://user-images.githubusercontent.com/3605364/31798032-38eb5a52-b4cd-11e7-9073-cb12414c860a.png)

If you step into CoreFX or CoreCLR code, you will be prompted to find the location of the source code (It has good PDBs, but not sourcelink information).  
 
Note that if you have debugged a .NET Core 2.0 application before you should delete your %TEMP%\SymbolCache directory as it can have old PDBs that are not as good as the new ones.  

See dotnet/core#897 for more details.

**Comment by vancem** [comment]
See https://github.com/dotnet/core/issues/897 for more details.  

The instructions above referring to clrmain only work if you have access to clrmain (you are inside Microsoft's domain).

**Comment by vancem** [comment]
I have updated https://github.com/dotnet/core/issues/897 but I will repeat it here.   We have published the symbolic information for ASP.NET DLLs including SourceLink information, which means that if you follow the instructions above  (or in https://github.com/dotnet/core/issues/897 ) you should be able to step into ASP.NET DLLs and it should 'just work'.     Non-ASP.NET parts of the framework (e.g.  System.*), has PDBs but not SourceLink but you can step into the source by following the instructions in https://github.com/dotnet/core/issues/897 .

**Comment by leslieharland** [comment]
Where can I find this setting on Visual Studio for Mac?

**Comment by seanmars** [comment]
Can use VS Code?

**Comment by vancem** [comment]
@seanmars,

Yes you can debug through the framework with VSCode.

See https://github.com/OmniSharp/omnisharp-vscode/wiki/Debugging-into-the-.NET-Framework-itself

I have used these instructions myself and they work (with V2.1). 

@leslieharland - did you get an answer?   I would have expected the normal (Windows) instructions for Visual Studio to work, but I can't try this experiment myself.   @gregg-miskelly  can you answer the question?

**Comment by DavidKarlas** [comment]
Unfortunately VS for Mac doesn't support symbol server yet. But we do plan to add it in future.

**Comment by Sergey-Nosov-GH** [comment]
Works great, thank you. Question: is there a way to enable browsing (i.e."Go To Definition" etc)  to the same source code displayed while debugging rather than metadata or decompiled sources?

**Comment by Sebazzz** [comment]
In addition, how can locally built debug builds be used? In .NET Core 1.x it was as simple as simply referencing the project in the same solution.

The release binaries are too much optimized to properly debug sometimes (because of inlining for instance). Are there debug binaries provided or otherwise means to use locally built debug builds? I can't find any docs about that.

**Comment by Legends** [comment]
@Rick-Anderson 

I want to debug the `SignOutAsync` method of `SignInManager` and this works partly until I reach to this line of code:

`Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(Microsoft.AspNetCore.Http.HttpContext, string, Microsoft.AspNetCore.Authentication.AuthenticationProperties)`

Pressing `F11` shows:

![image](https://user-images.githubusercontent.com/966368/68761411-4a119400-0614-11ea-9256-536185d7c55c.png)

**Comment by Legends** [comment]
It looks like it cannot find the `pdb` file:

**Search locations:**

> C:\Program Files\IIS Express\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\WINDOWS\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\WINDOWS\symbols\dll\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\WINDOWS\dll\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> 
> C:\Users\Admin\AppData\Local\Temp\SymbolCache\Microsoft.AspNetCore.Authentication.Cookies.pdb\735fe3d3438a4cd897d49b62fbfc46b3ffffffff\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\Users\Admin\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\Microsoft.AspNetCore.Authentication.Cookies.pdb\735fe3d3438a4cd897d49b62fbfc46b3ffffffff\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\Users\Admin\AppData\Local\Temp\SymbolCache\Microsoft.AspNetCore.Authentication.Cookies.pdb\735fe3d3438a4cd897d49b62fbfc46b31\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.
> C:\Users\Admin\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\Microsoft.AspNetCore.Authentication.Cookies.pdb\735fe3d3438a4cd897d49b62fbfc46b31\Microsoft.AspNetCore.Authentication.Cookies.pdb: Cannot find or open the PDB file.

<hr/>

**SYMSRV:  BYINDEX: 0x80A**
         c:\symbols*https://msdl.microsoft.com/download/symbols
         Microsoft.AspNetCore.Authentication.Cookies.pdb
         735FE3D3438A4CD897D49B62FBFC46B3ffffffff


**SYMSRV:  PATH:** c:\symbols\Microsoft.AspNetCore.Authentication.Cookies.pdb\735FE3D3438A4CD897D49B62FBFC46B3ffffffff\Microsoft.AspNetCore.Authentication.Cookies.pdb


**SYMSRV:  RESULT: 0x00000000**


srv*c:\symbols*https://msdl.microsoft.com/download/symbols: Symbols downloaded from symbol server.
c:\symbols\Microsoft.AspNetCore.Authentication.Cookies.pdb\735FE3D3438A4CD897D49B62FBFC46B3ffffffff\Microsoft.AspNetCore.Authentication.Cookies.pdb: Symbols loaded.

**Comment by Legends** [comment]
I managed to get it done _but not ootb_ as it should be, by setting a couple of breakpoints manually.

**Comment by Legends** [comment]
Hm, Now it doesn't work again.
Local symbol cache folder is empty, why is that?
