### ISSUE TITLE
2.0 update of File Uploads doc

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#5331]
16K PV/m 61% CSAT

https://docs.microsoft.com/aspnet/core/mvc/models/file-uploads

- [ ] Provide 2.0 code samples (address https://github.com/aspnet/Docs/pull/5217)
- [ ] UE edit (improve CSAT and use MVC style of writing)
- [ ] Address https://github.com/aspnet/Docs/issues/3989
- [x] Address https://github.com/aspnet/Docs/issues/4777
- [x] Address https://github.com/aspnet/Docs/issues/4964
- [ ] Address #6247
- [ ] Address #6349
- [ ] Address #6927
- [ ] Address #7702
- [x] Address #7742
- [ ] Address #8039
- [ ] Address #8100
- [x] Address #8298
- [ ] Address #8797
- [x] Address #9116
- [ ] Address #9327
- [ ] See #9473 for a possible enhancement opportunity.
- [x] Address #10161
- [ ] Address #11898 &ndash; Perhaps just a remark to process files in the background (i.e., [Background tasks with hosted services](https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services)).

Will fix #6609, #6610, #6611

See #6962 for a Q&A on the 65535 file limit of `GetTempFileName` mentioned in the topic and in a code comment. This subject has just come up again on #10161.

**Comment by MacGenius** [comment]
First, I'm new to visual studio enterprise. I'm trying to build the RazorPagesMovie app in five minutes but I'm already stuck at "add a model - scaffold the movie model". I'm not sure where to run "dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries" I have run this in my pc cmd console, in the Package Manager Console, and in Visual Studio code Terminal, the VSC terminal actually ran this command. But I am unable to successfully test the app  in the step "Test the app
Run the app and append /Movies to the URL in the browser (http://localhost:port/movies)." This gives me a 404 error.  I did notice the "if" in the Movie class example posted here but the tutorial makes no mention of this line...again I am new to Visual Studio I apologize if this is basic stuff, but Ive used netbeans and eclipse, and android studio successfully. Any suggestions for a rookie to VSE so I can complete this 5 minute app?
![doh](https://user-images.githubusercontent.com/29048190/40341641-8372b0f6-5d43-11e8-840f-d0705da3d801.PNG)
![doh1](https://user-images.githubusercontent.com/29048190/40341644-891a8862-5d43-11e8-89c7-35ec06198c0e.PNG)
![doh2](https://user-images.githubusercontent.com/29048190/40341646-8d50240a-5d43-11e8-9df9-6b1f3895722a.PNG)
![doh3](https://user-images.githubusercontent.com/29048190/40341743-15bd07cc-5d44-11e8-882a-8df8b7b7ea25.PNG)

**Comment by scottaddie** [comment]
@MacGenius Would you mind creating an issue for this by clicking the **Content feedback** button at the bottom of the doc giving you trouble? This allows us to better track issues.

**Comment by guardrex** [comment]
From @user135711 ...

> General feedback for the sample, not the pull request: I think the sample should actually save the uploaded image to a public folder or even better a database and then display it in the view in ProfileController.cs Line63 mainly because I want to learn how to do something similar with pdfs and books. I checked out this branch and it ran fine on my machine. Here's how I fixed the errors 2 weeks ago for [comparison](https://github.com/user135711/Docs/tree/FileUploadMigration/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample) (kindof worthless without diffs but I used .value on all partial number types whereas this used toString on a different datatype. I don't know which is more typesafe.)

**Comment by mattferderer** [comment]
In regards to #6247 the article on uploading files to Razor Pages shows a Utility file being created to solve some of these issues. The code has good comments that explain why things are being done - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/upload-files?view=aspnetcore-2.1#add-a-helper-method-to-upload-files

It also links to additional information about input validation & unrestricted file uploads.

It sounds like this article is receiving a re-write but in the meantime does it make sense for a pull request that links to the Razor article helper method for more information on file name validation?

On another note, I'm curious if this whole thing could be simplified with a suggested Nuget package to make it easier for developers to write secure code without having to think about all these potential issues.

**Comment by guardrex** [comment]
> make sense for a pull request that links to the Razor article helper method for more information on file name validation?

Seems like a good idea to me. Perhaps, just linking that whole topic would be good (as opposed to only linking part of it or its sample). It could be linked near the top temporarily (perhaps in a NOTE), since I think this sample is actually *broken* ... well ... we've had some reports that it's broken ... idk for sure. At a minimum, that topic should be linked down in *Additional resources*. @scottaddie will know what's best.

> a suggested Nuget package to make it easier for developers to write secure code

Perhaps so, but I recommend placing the request/suggestion on UserVoice or the [aspnet/Home issues](https://github.com/aspnet/Home/issues). The idea probably won't be seen here.

> The code has good comments

*TY* btw. We get a fair number of 💀 *death threats* 💀 :smile: lol, so it's nice to get a pat on the head every once and a while.

**Comment by Rick-Anderson** [comment]
@guardrex 	can you clean this up?

**Comment by guardrex** [comment]
> clean this up

The issue ... or the topic? :smile:

I'm not particularly knowledgeable in this area. My pro experience required very few file uploads and vanilla controls (e.g., AjaxControlToolkit) with simple config (e.g., extending `maxRequestLength` a bit), and I've never built from scratch with streaming. Yes, I can rewrite the topic, but it will take a chunk of time to get up on the learning curve on this one, especially the security angle.

**Comment by guardrex** [comment]
Will be tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214.
