### ISSUE TITLE
Web API: Document access protected endpoints in web api

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#6063]
See [Cookie authentication: unable to disable automatic challenge](https://github.com/aspnet/Security/issues/1394)

**Comment by Rick-Anderson** [comment]
@severisv can you provide a draft for these instructions? Should the instructions be added to [Content Negotiation](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.1#content-negotiation) ?

I could link to that section in [Build web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.2)

**Comment by Rick-Anderson** [comment]
@John0King  would you be able to provide the draft instructions?

**Comment by Rick-Anderson** [comment]
@serpent5  is this something you could do?

**Comment by John0King** [comment]
@Rick-Anderson I try to do this last night but fail on clone the project from GitHub.  GitHub is too slow for my region (China) :(

**Comment by Rick-Anderson** [comment]
@John0King  you do the work in this issue.

**Comment by Rick-Anderson** [comment]
@John0King  you can edit in browser https://github.com/aspnet/AspNetCore.Docs/blob/cookie/auth/ra/aspnetcore/security/authentication/disable-cookie.md

**Comment by Rick-Anderson** [comment]
Fix via an include - for example see (Add authentication support to a web API)[https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#add-authentication-support-to-a-web-api]
