### ISSUE TITLE
Migration: concept mapping

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#620]
We should provide a document that helps existing ASP.NET developers map existing ASP.NET concepts to the ASP.NET 5 world (ex handlers -> middleware, no synchronization context, etc).

**Comment by Rick-Anderson** [comment]
We sort of have this in the series at https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/

cc @scottaddie
