### ISSUE TITLE
AAD new azure portal UX 

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/AspNetCore.Docs#6239]
## Issues with Existing Topics
Content of the post is out-of-date, because management of an aad on classic port no longer possible. Document should reference portal.azure.com UX for AAD.
https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/developing-aspnet-apps-with-windows-azure-active-directory

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@SychevIgor  thanks for reporting this.
@CamSoper  could you update this? Should this be moved to the Azure repo?

**Comment by CamSoper** [comment]
@Rick-Anderson it's probably one where we've got a lot of crossover with existing content. Maybe we should redirect this article to one of those?

**Comment by Rick-Anderson** [comment]
@CamSoper  I agree. Whats the redirect target and I'll do that.

**Comment by Rick-Anderson** [comment]
@CamSoper  that would be great - thanks.

**Comment by Rick-Anderson** [comment]
@CamSoper 	hopefully this quarter.

**Comment by CamSoper** [comment]
@Rick-Anderson I put it on the quarterly planner thing we just did

**Comment by CamSoper** [comment]
@Rick-Anderson I'm starting on this. Two questions:

1. Thoughts on using Cloud Shell instead of Portal (where possible -- I'm not even completely sure how much can be done in Cloud Shell)?  I think I'd prefer to do it that way because there'll be fewer screenshots to maintain.

2. You want me to redirect this old one in the ASP.NET docset to the new one in ASP.NET Core?

**Comment by Rick-Anderson** [comment]
Cloud Shell would be my pref. Except for on-boarding apps, we usually provide only CLI instructions - and sometimes CLI + VS instructions with no screen shots.

> You want me to redirect this old one in the ASP.NET docset to the new one in ASP.NET Core?

That makes sense I think.

**Comment by SychevIgor** [comment]
11 without visible progress.
