### ISSUE TITLE
What is the "CacheKeys"?

### ISSUE THREAD

**Issue by rybomar** [aspnet/AspNetCore.Docs#6299]
It is hard to understand what is the "CacheKeys". Of course the search engine on GitHub helped me to find the answer but examples should to be more precisely (shuld be able to compile the code).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@rybomar Thanks for commenting. I'll let @Rick-Anderson respond to the "CacheKeys" part of your question. I just wanted to mention that the old sample that's there is due for an upgrade after 2.1 releases. We're tracking it on a samples update issue: https://github.com/aspnet/Docs/issues/5495

**Comment by Rick-Anderson** [comment]
fixed in #7792
