### ISSUE TITLE
Confusing Article - Uploading large files with streaming

### ISSUE THREAD

**Issue by rswetnam** [aspnet/AspNetCore.Docs#6349]
I found this article very confusing - and ultimately useless.  It starts off with the instruction "The initial action loads the form and saves an antiforgery token in a cookie (via the GenerateAntiforgeryTokenCookieForAjax attribute):"  - I take it that is is related to the previous article - but there is no context into the type of project is being created, type of page etc.  Unlike the article on the top of the page, there is also no sample project on github - there article is just a series of code snippets that you paste into some random files.

@Rick-Anderson 	edit: 16.4 K PV, 65% CSAT
customer comment: cancellationToken cannot be `null`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#uploading-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @rswetnam! Yes, that one is due for an overhaul. We're going to track the work on https://github.com/aspnet/Docs/issues/5331.

I'll add this issue to the list so that your feedback will be taken into account when the work is done. Thanks again for commenting.

**Comment by harmonicradius** [comment]
Is this article just a free association piece? My favourite part was when that introduction said "The following example demonstrates using JavaScript/Angular to stream to a controller action." Yet there was no javascript or angular in the remaining three paragraphs. I would like the time I have spent reading, and re-reading this article back please.

**Comment by harmonicradius** [comment]
What are we supposed to do with this code? I guess this wasn't intended for use in a `real app`. Can we provide useful information here, or delete it please? This was worse than being neutral, it was actively unhelpful. I am now further back than I was before reading this and more confused than ever.

**Comment by guardrex** [comment]
@harmonicradius We're discussing it now.

Until we have a plan to address this topic (i.e., **_OVERHAUL THIS_ :skull: _PIT OF DEATH_ 💀**), take a look at the RP topic for guidance. It's for RP, but the implementation for MVC would be similar.

https://docs.microsoft.com/aspnet/core/razor-pages/upload-files

I'll let u know what we're going to do shortly. We're chatting about it now.

**Comment by guardrex** [comment]
@harmonicradius ... **_GO! for throttle UP!_** :rocket: I'm going to overhaul this topic within the next week or two. A sister version to the RP topic is probably best. Not that I want to avoid the streaming coverage ... that's great, and I'll try to keep it. If it all goes well, I'll **_add_** the streaming coverage back over to the RP topic, too.

I'm going to check out the issues that are listed in the new tracking issue ... https://github.com/aspnet/AspNetCore.Docs/issues/10214 ... and close the old one (#5331) now. I'm going to close the prior issues (the list on the tracking issues), but I will look at and try to address the good ones on the updates.
