### ISSUE TITLE
Update docs to clarify differences between Challenge vs Forbid scenarios

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#6418]
_From @mkArtakMSFT on January 24, 2018 22:24_

The current documentation doesn't provide details about how exactly the challenge and forbid action results get processed internally and how those are different.
Please run the updated documents with @danroth27.

_Copied from original issue: aspnet/Mvc#7292_

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  If you can assign someone to draft out the document I'll get it published ASAP.

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT If you can assign someone to draft out the document I'll get it published ASAP.

**Comment by Tratcher** [comment]
@mkArtakMSFT @Rick-Anderson 

I found this https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased
> If authorization succeeds, the page for viewing the document is returned. If authorization fails but the user is authenticated, returning ForbidResult informs any authentication middleware that authorization failed. A ChallengeResult is returned when authentication must be performed. For interactive browser clients, it may be appropriate to redirect the user to a login page.

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT @Tratcher  what's action here?

* Make that paragraph more discoverable? IE, update the verbage before the code to
   * The following example:
       * determines whether the authenticated user is permitted to view the provided document.
       *  shows how to challenge and forbid action results get processed internally and how those are different
* Copy that section to another doc and add a H2 or H3 with how to challenge and forbid action results get processed internally and how those are different

**Comment by Tratcher** [comment]
It is a bit buried. At least giving it an h3 header would help.

The only other doc that mentions challenge result is https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data and it doesn't cover Forbid at all. There are a few samples in there that should probably be using forbid rather than challenge like DetailsModel.
