### ISSUE TITLE
Xml Serializer Donn't Works in .net core 2.0

### ISSUE THREAD

**Issue by yangganboy** [aspnet/AspNetCore.Docs#6438]
need add code
`options.FormatterMappings.SetMediaTypeMappingForFormat("xml", "text/xml");`
in services.addMvc

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/zh-cn/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 any reason XML would not work?

**Comment by Rick-Anderson** [comment]
@serpent5 - I think he's saying you need to enable XML via `options.FormatterMappings.SetMediaTypeMappingForFormat("xml", "text/xml");`

**Comment by yangganboy** [comment]
I commented on doc website.I don't say in detail. It's xml format url mapping problem without default config,and that without explain in doc.
I'm sorry about that.

**Comment by serpent5** [comment]
Both `AddXmlSerializerFormatters` and `AddXmlDataContractSerializerFormatters` add an XML mapping, but they add `application/xml` instead of `text/xml`. This shouldn't cause any issues under normal circumstances.

@yangganboy Are you using one of these methods to add the XML serializers? Do you have a specific need for `text/xml` instead of `application/xml`?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
