### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore.Docs#6476]
Should we mention ignoring bundled/minified assets from source control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minifiy static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.0&tabs=visual-studio%2Caspnetcore2x#use-the-bundler--minifier-extension)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by jmhongithub** [comment]
Was bundling and minification removed or replaced from ASP.NET Core MVC 2.1 RC1? When you create a new project it now longer creates a bundleconfig.json file.

**Comment by Rick-Anderson** [comment]
That's a decision the repo owner makes.
