### ISSUE TITLE
IHostingStartup with the Generic Host

### ISSUE THREAD

**Issue by rcollina** [aspnet/AspNetCore.Docs#6701]
Any chance we can get host enhancement as in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/platform-specific-configuration?view=aspnetcore-2.1 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
ping @Tratcher

**Comment by Tratcher** [comment]
No, we don't have any plans for IHostedStartup in the Generic Host yet. I expect we'll revisit this in 3.0.

**Comment by guardrex** [comment]
Thanks for asking @rcollina. We'll leave this issue open and revisit for 3.0.

**Comment by rcollina** [comment]
@guardrex, no problem - thank you for your time.
Thought I’d add my 2c on the matter. 

I am glad you introduced a generic host, since I pretty much did the same on my own some months ago. All I did was to strip any http/server-related code from your WebHost sources.

IHostingStartup is a great mechanism to plug in cross-cutting concerns, so I am a bit puzzled as to why it was left out.

Right now the best course of action for me would be to keep using a Web Host, as I need to standardize infrastructural dependencies across a variety of applications.

**Comment by Tratcher** [comment]
The .NET Core additional deps injection model keeps giving us trouble, we didn't want to bake it into generic host until we sorted that out.

**Comment by rcollina** [comment]
I need to delegate picking logging and some other implementations to the teams that performs app maintenance.

I do not necessarily want to recompile if things change on their end.

IHostingStartup seemed like a good fit.

**Comment by davidfowl** [comment]
Can you show how you are configuring those in your application?

**Comment by mesuttalebi** [comment]
How is it possible to run GenericHost as Windows Service, like what is in 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

**Comment by Tratcher** [comment]
@mesuttalebi https://github.com/aspnet/Hosting/pull/1492#issuecomment-405298223

**Comment by williamrschmidt** [comment]
Luke, I have taken the generic host sample, containing TimedHostedService.cs, and published it to Azure. I enabled diagnostic logging there and web logging but do not see the logs created periodically by TimedHostedService in the log stream there. What is required to get an IHost hosted service to log out to Azure in a way that can be easily viewed? I should note that I am not very experienced with Azure app service, so is it possible to concoct an example or tutorial for deploying these examples to Azure? Thanks.

**Comment by guardrex** [comment]
@williamrschmidt If you run the app in the Kudu console ( https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot#run-the-app-in-the-kudu-console ), you'll see the output. If you use the ASP.NET Core Module stdout logging, you can see the output. These are certainly for **_learning, testing, and troubleshooting_** and not for production apps.

The real answer tho is implementing one of the 3rd party logging providers, such as Serilog. This saves an app from eating itself with rolling logs and log size limits (among other things).

It does come down to, as you say, what's "easy." I think when one is just playing with a sample and they plan to shut the app down and disable it immediately after use, that either the Kudu console or the stdout logging approaches are fine.

WRT documenting, we cover the approaches, but there is such concern about devs using them generally (e.g., in production apps) that I don't think we want to say more than what we currently say. We leave the logging topic to cover what devs should do to see output logged from apps (console logging; log levels) ... again ... it's a pitch to use one of the robust 3rd party logging providers.

There *was* (maybe still is) a plan for MS to offer an in-the-box logging implementation, but I think that's on the back-burner as a lower priority goal at the moment. If that ever did happen, the nice things about it would be (a) it would probably be simple (a few lines of code) to wire up and get running with safe defaults, (b) be part of the `App` package, so everyone would get it for doing nothing other than the config.

**Comment by toryb** [comment]
@davidfowl 
> @rcollina those cross cutting concerns can be extension methods on the builder. Is there a specific reason you're using IHostingStartup?

I just wanted to register our desire to have IHostingStartup available for GenericHost also. We use IHostigStartup to allow our clients to use configuration to add their own custom behavior to our ASP.NET Core application without building our app. We want to provide the same functionality for an on-prem server solution running as a service.

**Comment by guardrex** [comment]
Superseded by https://github.com/aspnet/AspNetCore.Docs/issues/12574, which will include Generic Host updates.
