### ISSUE TITLE
New doc:  use static assets that are part of a RCL project 

### ISSUE THREAD

**Issue by jvaneikeren** [aspnet/AspNetCore.Docs#6838]
I created a Razor Class Library this weekend. I was able to encapsulate Razor Views and associated Models + a Controller in a Razor Class Library and accompanying NuGet package. However, I would also like to encapsulate a collection of files under a Razor Class Library "wwwroot" folder that would be copied over to the "wwwroot" folder of the referencing ASP.NET Core web application upon package installation. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92ffa7c-fd65-7dc3-194e-6a67a8a7f176
* Version Independent ID: 2df11a37-d64e-6353-bd92-0b7729070c3e
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/ui-class.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm can you comment

**Comment by pranavkm** [comment]
We have an item tracking experiences around static class libraries + Razor Sdk here - https://github.com/aspnet/Razor/issues/2322. In the meanwhile, our recommendation is to follow what's done in IdentityUI. I'll highlight the relevant pieces of code:

* https://github.com/aspnet/Identity/blob/dev/src/UI/Microsoft.AspNetCore.Identity.UI.csproj#L9
* https://github.com/aspnet/Identity/blob/dev/src/UI/Microsoft.AspNetCore.Identity.UI.csproj#L14
* https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityDefaultUIConfigureOptions.cs#L50-L67

**Comment by mmillican** [comment]
@pranavkm Would you recommend using Identity UI as an example for making a RCL with MVC instead of Razor Pages? I have a very similar need with static assets so this is super interesting.

**Comment by pranavkm** [comment]
IdentityUI uses Razor Pages - https://github.com/aspnet/Identity/tree/dev/src/UI/Areas/Identity/Pages. That said, Controllers with Views and Razor Pages are two flavors of MVC the framework. We think Razor Pages has fewer ceremony for browser based applications, but either (or both) should be fine to share UI in class libraries.

**Comment by yanshengjie** [comment]
[RPL.Demo](https://github.com/yanshengjie/RPL.Demo) 
This is my demo to use wwwroot as a part of a RCL project.
I hope it will help someone who are looking for this.

**Comment by jeremyVignelles** [comment]
@pranavkm : Your links are broken, can you update them please?

**Comment by svallis** [comment]
@jeremyVignelles Looks like the code in question is now here:

https://github.com/aspnet/Identity/blob/master/src/UI/

It looks like some of the link numbers have changed from those referenced above. I believe the following is what was originally being pointed at:

- https://github.com/aspnet/Identity/blob/master/src/UI/Microsoft.AspNetCore.Identity.UI.csproj#L9
- https://github.com/aspnet/Identity/blob/master/src/UI/Microsoft.AspNetCore.Identity.UI.csproj#L18
- https://github.com/aspnet/Identity/blob/master/src/UI/IdentityDefaultUIConfigureOptions.cs#L56-L73

@pranavkm I'm getting the following error when trying to replicate the simple setup the docs state here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.1#manifestembeddedfileprovider

My Razor Class Library `csproj` file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot/**/*" />
  </ItemGroup>
  
</Project>
```

And the main application does this:

```
services.AddMvc().AddRazorOptions(options => options.FileProviders.Add(
    new ManifestEmbeddedFileProvider(assembly, "wwwroot")
)).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

Which gives the following error:

```
InvalidOperationException: Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'Library'.
```

Not really sure what should be happening under the hood here regarding the manifest. I'm referencing the library via its `nupkg` file after performing a pack on the Library - would that make any difference?

**Comment by sfmskywalker** [comment]
A critical detail that wasn't obvious to me initially is the following package reference:

`<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="2.1.0" />`

Without it, the application will compile but fail at runtime with:

```
Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'RPL.Demo'.
```

when running:

`var filesProvider = new ManifestEmbeddedFileProvider(GetType().Assembly, basePath);`

Thanks @sheng-jie for the details walkthrough!

**Comment by AdrienTorris** [comment]
The first answer explains how to do this. It's work I just try: https://stackoverflow.com/questions/51610513/can-razor-class-library-pack-static-files-js-css-etc-too

**Comment by mttkrb** [comment]
> 
> 
> The first answer explains how to do this. It's work I just try: https://stackoverflow.com/questions/51610513/can-razor-class-library-pack-static-files-js-css-etc-too

This doesn't work if there multiple resourceFiles for different languages. (Resources.resx and Resources.en.resx)
If these files in the project available and the solution of the stackoverflow thread applied the following error occurs:
`Error	MSB4018	The "GenerateEmbeddedResourcesManifest" task failed unexpectedly.
System.InvalidOperationException: An item with the name '' already exists.
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.Internal.Entry.AddChild(Entry child)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.Manifest.AddElement(String originalPath, String assemblyResourceName)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.GenerateEmbeddedResourcesManifest.BuildManifest(EmbeddedItem[] processedItems)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.GenerateEmbeddedResourcesManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	RCLProject	C:\Users\developer\.nuget\packages\microsoft.extensions.fileproviders.embedded\2.2.0\build\netstandard2.0\Microsoft.Extensions.FileProviders.Embedded.targets	65	
`

**Comment by Rick-Anderson** [comment]
> @pranavkm : Your links are broken, can you update them please?

I fixed the links but the file numbers are off.  @pranavkm can you edit the line numbers and review new comments?

**Comment by pranavkm** [comment]
🆙 📅 the links

**Comment by Dennis-Petrov** [comment]
@mttkrb See #8121 for workaround:

https://github.com/aspnet/Mvc/issues/8121#issuecomment-410327701
