### ISSUE TITLE
How to create authenticated request?

### ISSUE THREAD

**Issue by search8** [aspnet/AspNetCore.Docs#6882]
Hi,
Can you possibly provide an example of how I would go about authenticating a request? Most of my controllers require a user to be authenticated prior to having access to a controller's actions. What's the best way to go about it using WebApplicationFactory? Prior I had used the TestServer and added a Test Middleware where I set the appropriate Header attributes. This however required me to overwrite the Startup class of my WebApplication. I'd prefer if I didn't have to do that anymore but I fail to see how I can achieve something similar using WebApplicationFactory.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's there ... are you asking for additional coverage?

https://docs.microsoft.com/aspnet/core/test/integration-tests?view=aspnetcore-2.1#test-a-secure-endpoint

**Comment by search8** [comment]
Just noticed your edit. That is exactly what I'm trying to achieve. I would like to 'mock' a request as being authenticated and check whether the executed action of my secure resource returns what I expect.

**Comment by guardrex** [comment]
Great idea. We're still working on 2.1 updates and have some other priority issues to address, but I'll get to this asap.

I'm new to AngleSharp. It was the engineering team's choice. It should make it easy for you to submit credentials to your sign-on page, and then test navigation to the secure endpoint once the user has been authenticated. Since I'm new to AngleSharp, I can't advise you further on *exactly* how to pull it off. I suggest searching for some examples.

**Comment by search8** [comment]
Ok, cool, thank you. 

I have never used AngleSharp before but I'll have a look.

**Comment by scottsauber** [comment]
@search8 - I'd recommend checking out the samples they've done to test the new IdentityUI.

Your specific example of wanting to send the login details is here: https://github.com/aspnet/Identity/blob/ae9aa9ebec4de42d2c0ab8c68f1b2bccd7b1c5f8/test/Identity.FunctionalTests/Pages/Account/Login.cs#L53

But you can navigate around the Identity.FunctionalTests folder for some examples.  It was a little hard for me to follow just reading through it on GitHub, since a lot of complexity is stashed away in methods.  So it helped me to clone the repo and step through it.

Hope that helps.

**Comment by IronMania** [comment]
Ok i figured it out. When you have a test that uses your CustomWebApplication factory, just add a filter attribute to allow anonymous requests:
services.AddMvc(opts => { opts.Filters.Add(new AllowAnonymousFilter()); });

**Comment by anetschka** [comment]
I actually achieved automated cookie authentication for my requests by adding a test authentication handler that logs the user in (by providing a cookie) whenever authentication is needed ... Not easy, but it seems to work.

**Comment by KollarM** [comment]
I achieved this by using 2 WebHosts in my xUnit test. One for hosting web which we are testing and another for running IdentityServer (or any other Security Token Service you like) on different port. IdentityServer has a nice in memory configuration for Clients, Resources, Users,... . Sample solution on Github can be found here https://github.com/KollarM/WebAPIWithIdentityServerIntegrationTest

**Comment by VictorioBerra** [comment]
Would love to see this implemented in a way we can use via the `WebApplicationFactory`.

Logging in a test user to test endpoints and policies should be as easy as adding auth via `            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)`.

It seems like right now only complex middleware is able to allow this. I will see what I can do with AngleSharp but I do not like the idea of being tied to my IdentityServer/SSO Portal for running tests.

**Comment by VictorioBerra** [comment]
As I think about it more id expect to maybe see something like this:

```csharp
[Fact]
public async Task Get_()
{
    await _factory.Server.AuthenticateAsync("Jim", claims);

    // Arrange
    var client = _factory.CreateClient();

     await client.GetAsync("/Home/Secure");

}
```

**Comment by VictorioBerra** [comment]
@InDieTasten do you want to voice why you reacted to my suggestion with a thumbs down and a confusion face? It might help to have an actual discussion on this issue.

We need a way to set and remove an authenticated user and their claims when hitting endpoints with the client.

**Comment by InDieTasten** [comment]
@VictorioBerra 
I totally agree, that there needs to be documentation on how to achieve this.

Your comment doesn't belong the the documentation repo. It's relatively off-topic, as you are not talking about guiding readers towards a common solution, but creating extra framework functionality that would cover this, which would then still need documentation.

The next part will be off-topic as well as kind of a feedback to what I believe you are trying to express in your proposed interface:

The interface you provided for accomplishing that is not covering all scenarios. The SUT still needs to be "aware" of integration tests happening, since the proposed interface would need to make serious changes to what's happening inside the authentication middleware to allow for your behavior.

For what I know, there are 3 approaches to make your request go to a protected resource:

1. Make the protected resource unprotected eg. global "AllowAnonymousAttribute" in MVC apps (not feasible when the resource makes decisions based on the details of authenticated users)
2. Registering a test authentication scheme, that can be controlled from inside the integration test code (not feasible when the application is not using the default authentication middleware or is relying on specific characteristics of a real authentication scheme (eg. looking for authentication cookies)). This to me sounds like a good fit and to my knowledge is already possible with the WebApplicationHostFactory. It's just not built-in, as it would be slightly depending on how the authentication schemes are set up in the application. It's also the closest to what you are suggesting. Maybe that's what you meant to say, so that's what the confused emote was for.
3. Consider authentication as part of your SUT. Eg. earn your session cookie by making "legit" requests to your login page, redirecting to identity providers through oauth and what not. Having helpers and extensions for accomplishing this for the most common authentication schemes would be very helpful, as this can be very tedious code to write. (Based on how much automation is tolerated at external systems this might not work, or entire external systems need to be faked)

The last one is obviously comes closest to the real thing, but is also be most difficult to set up.

**Comment by VictorioBerra** [comment]
I suppose it's just frustrating for devs using the `WebApplicationFactory` gets you 90% there. As soon as you `.AddAuthentication` then you need to add a bunch of boilerplate like you mentioned whether it be a ton of AngleSharp code, or stripping the auth using the `WebApplicationFactory` stuff, or registering fake schemes that way, or **building an entire `IdentityServer` in the `WebApplicationFactory`**. Which I personally hate that the best solution is currently to do just that.

From where I am sitting as a developer writing tests for my app I want to be able to toggle my users/impersonate all as a part of my arrange section of my test. You can consider my code confusing psudocode if you like, but it doesn't change the fact that we need to be able to toggle our claims, roles, user subjects, etc and test all our controllers and actions as different identity roles.

It would be really cool to set my user, create my client, test my endpoint without this headache.

**Comment by VictorioBerra** [comment]
Another quick and dirty solution that I was working on is to add a controller to your integration project, and then have an authentication action which logs in a user of your choice. Add it to the SUT like so:

```csharp
public class CustomConfigurationWebApplicationFactory<TStartup> : WebApplicationFactory<MyApp.Startup>
{

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {

             // ...

             var mvcBuilder = services.AddMvcCore();
             mvcBuilder.AddApplicationPart(this.GetType().Assembly);

              // ...

```

**Comment by InDieTasten** [comment]
@VictorioBerra That looks like a nice solution. I don't see anything wrong with this pattern, so might as well be documented like this IMO.

**Comment by jelster** [comment]
AIUI, you could make this work with JwtBearer tokens by exchanging the cookie authentication ticket for a Bearer token with code like this:

        [Fact]
        public async Task Test1Async()
        {
            // Arrange
            var authResult = await _client.GetAsync("/api/Impersonation?subjectId=Bob");        
            var token = await httpContext.HttpContext.GetTokenAsync("access_token");

            if (!string.IsNullOrWhiteSpace(token))
            {
                  _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }
            // ...
        }

**Comment by APIWT** [comment]
We are currently achieving this by adding two filters inside ConfigureTestServices.

```csharp
this.factory.WithWebHostBuilder(builder => builder.ConfigureTestServices(
    services => services.AddMvc(
        options =>
        {
            options.Filters.Add(new AllowAnonymousFilter());
            options.Filters.Add(new FakeUserFilter());
        }))).CreateClient();
```

Then we have our FakeUserFilter defined as:
```csharp
private class FakeUserFilter : IAsyncActionFilter
{
    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        context.HttpContext.User = new ClaimsPrincipal(new ClaimsIdentity(new List<Claim>
        {
            new Claim(ClaimTypes.NameIdentifier, "12345678-1234-1234-1234-123456789012"),
            new Claim(ClaimTypes.Name, "TestUser"),
            new Claim(ClaimTypes.Email, "test.user@example.com"), // add as many claims as you need
        }));

        await next();
    }
}
```

**Comment by guardrex** [comment]
For those tracking on this issue, I just made some remarks regarding my thoughts on when the little batch of authn/authz issues for testing *might be* addressed. See my remarks at https://github.com/aspnet/Docs/issues/9957#issuecomment-446331425 ... and keep in mind that I'm guessing a bit on timing except for where I'm describing the 3.0 doc issues. Those will be of *highest priority* as 3.0 gets close.

**Comment by mehmetilker** [comment]
I was using impersonate user model previously (adding "if environment is integration test then"... to the startup class) but with the new WebApplicationFactory things are more simple. No need to change flow in the pipeline...

Request login page and extract verification token from the content.
Then add it to the header of "login post request". Response will carry authentication cookie. Therefore all next request with http client will send authentication cookie as well.

The only thing needs to added is removing antiforgery/verification token from default header for every test run.

```C#
[Theory(DisplayName = "D_Login"), TestPriority(14)]
        [InlineData("/Member/Account/Login")]
        public async Task C_Login(string url)
        {
            var verificationToken = _testHostFixture.GetVerificationToken(url);
            LoginModel.InputModel inputModel = new LoginModel.InputModel
            {
                Email = UserTestData.UserName,
                Password = UserTestData.Password,
                RememberMe = false
            };
            var contentToSend = new FormUrlEncodedContent(inputModel.ToKeyValuePair());
            _client.DefaultRequestHeaders.Add(AppEnvironment.AntiForgeryHeaderName, verificationToken);

            HttpResponseMessage response = await _client.PostAsync(url, contentToSend);

            // Assert
            Assert.Equal(HttpStatusCode.Found, response.StatusCode);
            Assert.Equal("/Member", response.Headers.Location.OriginalString);
        }
```



```C#
 public string GetVerificationToken(string url)
        {
            HttpResponseMessage response = Client.GetAsync(url).Result;
            var verificationToken = response.Content.ReadAsStringAsync().Result;
            if (verificationToken != null && verificationToken.Length > 0)
            {
                verificationToken = verificationToken.Substring(verificationToken.IndexOf("__RequestVerificationToken"));
                verificationToken = verificationToken.Substring(verificationToken.IndexOf("value=\"") + 7);
                verificationToken = verificationToken.Substring(0, verificationToken.IndexOf("\""));
            }
            return verificationToken;
        }
```


```C#
   public void Dispose()
        {
            //Remove AntiForgeryHeader token for every test. So that next test can create fresh one.
            _client.DefaultRequestHeaders.Remove(AppEnvironment.AntiForgeryHeaderName);
        }
```

**Comment by jabbera** [comment]
For those interested I build a package that makes this simple without having to host a separate identity server: https://github.com/jabbera/aspnetcore-testing-role-handler

Feedback welcomed.

**Comment by jelster** [comment]
I took a slightly different approach by implementing a test authentication scheme and middleware, then using the `.ConfigureTestServices()` method of a custom `WebApplicationFactory<T>` class to specify my test authentication scheme as the default scheme. [Here's a gist demonstrating it](https://gist.github.com/jelster/6b850d567acef343e59fad70cb20455a)

**Comment by jelster** [comment]
The most direct route to using this is to configure your web application factory with the test authentication scheme is like this:

            _factory = (TestWebApplicationFactory<MyWebApi.Startup>)factory.WithWebHostBuilder(
              builder => {
                builder.ConfigureServices(services =>
                {
                    services.AddAuthentication(o =>
                    {
                        o.DefaultScheme = "TestAuthenticationScheme";
                    })
                    .AddTestAuthentication("TestAuthenticationScheme", "Test Auth", o => { });
                });
          });

**Comment by VictorioBerra** [comment]
Thanks a lot everyone for throwing ideas and solutions into the ring. This thread will help a lot of people out there searching for a solution.

Maybe Microsoft will prioritize this a little higher since they are really putting effort into testing infrastructure and there is clear interest in out of the box solutions for testing apps that require auth.

**Comment by jabbera** [comment]
That’s easy too. I needed a way to test aribitrary claims (roles) per test as my API behaves differently depending on the claims you have. Hence sending them over in the auth header.

**Comment by VictorioBerra** [comment]
@jabbera Same. As a user of [PolicyServer](https://github.com/PolicyServer/PolicyServer.Local/) identity role claims are mapped to policies automatically. So claims are the most important part to me as well.

It looks like if you use his `AddTestAuthentication` you are able to set the claims in his `TestAuthenticationOptions` so maybe that would still work for you. He also shows how you can modify the factory `WithWebHostBuilder` inside of one of your test classes so you can tweak this on a per test basis I think.

**Comment by VictorioBerra** [comment]
@guardrex This is off topic but do you have a second keyboard purely dedicated to emojiis? 😛

**Comment by guardrex** [comment]
Note to Microsoft management: Add **_Speech-to-emoji_** technology in Win10. 😁

**Comment by jelster** [comment]
> It looks like if you use his AddTestAuthentication you are able to set the claims in his TestAuthenticationOptions

That's correct. The gist shows a static set of claims being generated, but there's no reason you couldn't have an individual test create its' own set of claims, modifying the logic in the `TestAuthenticationHandler` to be more dynamic in the claims it generates (e.g., read from custom header, config file, etc...). 

Now that I think of it, it is pretty easy to implement that on a per-test basis -- I've updated the Gist to show how to do this (`ClaimsTests.cs`)

**Comment by VictorioBerra** [comment]
Thanks for the update!

**Comment by guardrex** [comment]
Latest guidance from engineering is that they will triage this issue for the Integration Testing topic along with the rest on the [Integration Testing Project](https://github.com/aspnet/Docs/projects/31) here. If they decide that this one makes the cut, we'll get it on a sprint for work.

**Comment by LockTar** [comment]
@guardrex I like the multiple samples in this discussion. I know for sure one of these samples work. I'm facing slightly a different problem. I have an authorized Controller that is calling another authorized controller (different project) or external api (like Microsoft Graph). Both apis are authenticated against the Azure AD. In all the controller actions we need the authenticated user. 
We can get in the first api by getting a token based on the username and password (grant_type=password). When we continue to the second api, it breaks because of an interactive login prompt. Normally, the user authenticates with open id connection, we then have the authentication code and get the accesstoken + refresh token. With the refresh token we can get an access token for the second api.

**Comment by guardrex** [comment]
They haven't pulled the trigger on further updates to the topic yet. Thanks for that info. I (or someone on the team who works on the doc further) will appreciate all of the community tips and code provided here when the time comes to work further on the topic.

**Comment by blalonde** [comment]
I had a customPolicyProvider to resolve my policy and even though I enabled AllowAnonymous filter, the authFilter needed to resolve the bypassed policy by name. Here's my fix :

```
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureTestServices(
                services =>
                {
                    services.AddMvc(options => options.Filters.Add(new AllowAnonymousFilter()));

                    var unusedPolicyStub = new AuthorizationPolicyBuilder(Array.Empty<string>())
                        .AddRequirements(Mock.Of<IAuthorizationRequirement>())
                        .Build();

                    var policyProviderMock = new Mock<IAuthorizationPolicyProvider>();
                    policyProviderMock.Setup(x => x.GetPolicyAsync(ClientCertificatesPolicyProvider.PolicyName)).ReturnsAsync(unusedPolicyStub);

                    services.AddSingleton(policyProviderMock.Object);
                });
        }
```

**Comment by VictorioBerra** [comment]
@blalonde Odd that you use `AllowAnonymousFilter` and you still needed to do this. I use PolicyServer.io and didn't have any issues.

**Comment by uvn85** [comment]
// this code work for me - avoid windows authentication

```
using System.Net.Http;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using WebService;
using Xunit;

namespace Test.WebServiceTests.IntegrationTest
{
    public class WebServiceIntegrationTest : IClassFixture<WebApplicationFactory<Startup>>
    {
        private readonly WebApplicationFactory<Startup> _factory;

        public WebServiceIntegrationTest(WebApplicationFactory<Startup> factory)
        {
            _factory = factory;
        }

        [Fact]
        public void GetProject()
        {
            using (HttpClient client = BuildAnonymousClient())
            {
                var response = client.GetAsync("/api/admin/project/101").Result;
                Assert.True(response.IsSuccessStatusCode);
            }
        }

        private HttpClient BuildAnonymousClient()
        {
            return _factory.WithWebHostBuilder(c => 
                c.ConfigureTestServices(s => s.AddMvcCore(o => o.Filters.Add(new AllowAnonymousFilter())))).CreateClient();
        }
    }
}


```

**Comment by boaterdan** [comment]
In case anyone finds it useful...  it seems to me that many of the solutions of adding Middleware or mocking the claims verification is missing the point of integration testing.  I want to confirm that my app works the way I expect when it comes to authentication and authorization - that means logging in with a user and trying to go to a page with as close to the normal process as possible.  I've got tons of unit tests for testing actions of pages, so this is a different animal.

I found that AngleSharp makes it pretty easy, as it's going to track the anti-forgery cookie and validation cookie.  It's just a matter of submitting the login page and then using the same client to do your additional testing.  I'm using the following code.  The way it's currently set up, the response from the login submit is a redirect to "/", which is what is confirmed by the first test I wrote.

`       private async Task<HttpResponseMessage> LoginUser()
        {
            var loginPage = await _client.GetAsync("/Identity/Account/Login");
            loginPage.EnsureSuccessStatusCode();
            var loginContent = await HtmlHelpers.GetDocumentAsync(loginPage);

            // ***** Act *****
            var form = (IHtmlFormElement)loginContent.QuerySelector("form[id='account']");

            var (userEmail, userPassword) = TestDatabaseSeeder.UsersData.First();
            var formValues = new Dictionary<string, string>
            {
                {"Input_Email", userEmail},
                {"Input_Password", userPassword},
                {"Input_RememberMe", "false" }
            };

            return await _client.SendAsync(form, formValues);
        }`

**Comment by guardrex** [comment]
@boaterdan Use triple-backticks above and below your code example.

**Comment by VictorioBerra** [comment]
@uvn85 I am not a big fan of modifying the host. Especially turning off MVC features like auth just for testing.

Ideally, we would have a way provided by Microsoft to tweak the client and provide a set of claims.

**Comment by dhhunter** [comment]
How do I use Windows Authentication with the WebApplicationFactory?  Allowing Anonymous access is not an option as my Service keeps an Audit Log of every Write request made to the system and will (by intention) throw an Exception if the Identity is not valid.  For the purposes of Integration Testing I would expect that the Windows Identity of the User running the Tests be sent to the Web Service with the Http Requests.  Please help, this is a very critical and urgent blocking issue for us.  Thank you in advance!

**Comment by vanillajonathan** [comment]
I tried a few solutions mentioned in this and other threads but was unable to get anything to work. Perhaps some things have changed and no longer work with ASP.NET Core 3.0. I solved it by creating a fake `AuthenticationHandler`.

```cs
public class UnitTest1 : IClassFixture<WebApplicationFactory<Startup>>
{
    private readonly WebApplicationFactory<Startup> _factory;

    public UnitTest1(WebApplicationFactory<Startup> factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task GetWeatherForecast()
    {
        using (var client = BuildAuthenticatedClient())
        {
            var response = await client.GetAsync("/WeatherForecast");
            Assert.True(response.IsSuccessStatusCode);
        }
    }

    private HttpClient BuildAuthenticatedClient()
    {
        return _factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureTestServices(services =>
            {
                services.AddAuthentication("TestAuthentication")
                    .AddScheme<AuthenticationSchemeOptions, TestAuthenticationHandler>("TestAuthentication", null);
            });
        }).CreateClient();
    }
}
```

I create a fake `AuthenticationHandler`.

```cs
public class TestAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public TestAuthenticationHandler(IOptionsMonitor<AuthenticationSchemeOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) : base(options, logger, encoder, clock)
    {
    }

    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var claims = new[] {
            new Claim(ClaimTypes.NameIdentifier, "test"),
            new Claim(ClaimTypes.Name, "test")
        };
        var identity = new ClaimsIdentity(claims, Scheme.Name);
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, Scheme.Name);

        return await Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
```

**Comment by vanillajonathan** [comment]
I tried a few solutions mentioned in this and other threads but was unable to get anything to work. Perhaps some things have changed and no longer work with ASP.NET Core 3.0. I solved it by creating a fake `AuthenticationHandler`.

```cs
public class UnitTest1 : IClassFixture<WebApplicationFactory<Startup>>
{
    private readonly WebApplicationFactory<Startup> _factory;

    public UnitTest1(WebApplicationFactory<Startup> factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task GetWeatherForecast()
    {
        using (var client = BuildAuthenticatedClient())
        {
            var response = await client.GetAsync("/WeatherForecast");
            Assert.True(response.IsSuccessStatusCode);
        }
    }

    private HttpClient BuildAuthenticatedClient()
    {
        return _factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureTestServices(services =>
            {
                services.AddAuthentication("TestAuthentication")
                    .AddScheme<AuthenticationSchemeOptions, TestAuthenticationHandler>("TestAuthentication", null);
            });
        }).CreateClient();
    }
}
```

This is my fake `AuthenticationHandler`.

```cs
public class TestAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public TestAuthenticationHandler(IOptionsMonitor<AuthenticationSchemeOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) : base(options, logger, encoder, clock)
    {
    }

    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var claims = new[] {
            new Claim(ClaimTypes.NameIdentifier, "test"),
            new Claim(ClaimTypes.Name, "test")
        };
        var identity = new ClaimsIdentity(claims, Scheme.Name);
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, Scheme.Name);

        return await Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
```

**Comment by boaterdan** [comment]
When I was trying to make this work I found various variations of replacing middleware parts, along the lines of @vanillajonathan solution.  To me this is just not what I'm after, as I'm specifically trying to do integration testing of the authentication process.  If I visit a secured page anonymously I should receive a redirect to the login page, for example.  Or testing visiting a secured page with two authenticated users, one authorized for that page and one not.  Part of what I want to test is that I've correctly secured the page, so mocking the success or deny is completely defeating that.

In the end I was able to get something working with the real stack, but only against a physical DB and not in-memory, which makes the tests quite expensive to run and exacerbates test concurrency problems.

**Comment by VictorioBerra** [comment]
I am really surprised they didn't improve the extensibility of all this in Core 3. This is obviously a massive shortcoming of the TestServer/Host.

**Comment by vanillajonathan** [comment]
@boaterdan, the AuthenticationHandler only gets inserted on the unit tests that call the private `BuildAuthenticatedClient` method. So you have your unit tests consist of a mix of methods are authenticated and non-authenticated in order to test redirects and such.

**Comment by boaterdan** [comment]
Yes @vanillajonathan I can test that I get a redirect when I'm supposed to - meaning when access is declined.  But my point is that doesn't test that access is declined when it's supposed to.  A couple of unit tests can confirm the mechanism for the first part works, but every page must be tested "for real" for the second one, so the authentication/authorization stack used live has to be intact.  Of course, those are not even unit tests at that point - it's those full integration tests I finally got working only against a physical database.

**Comment by overcomer79** [comment]
I had this issue when I migrated to .NET Core 3.0 (from 2.2)
Finally I found the solution for my integration tests.

I Use a base class for all the tests for that category
- **In Memory DB** does not work with ConfigureTestServices extension
- **Skipping Authentication** does not work anymore with ConfigureTest

Skypping authorization example (not working anymore):
 ```
services.AddControllers( setupAction => {
                            setupAction.Filters.Add( new AllowAnonymousFilter() );
                            setupAction.Filters.Add( new Factory.MVC.FiltersFactory.FakeUserFilter() );
} );
 ```

This is the solution (Hybrid configuration, using both).
- Memory DB from my specific test have to be disposable. But is not always needed: it depends from the test requirements.

The base class:
 ```
public class SkipAuthMemoryDbIntegrationTest : IDisposable {
        protected readonly HttpClient TestClient;
        private readonly IServiceProvider _serviceProvider;

        protected SkipAuthMemoryDbIntegrationTest() {

            var appFactoryNoAuthMemoryDB = new WebApplicationFactory<BPER_API.Startup>()
                .WithWebHostBuilder( builder => {
                    builder.ConfigureServices( services => {
                        services.RemoveAll( typeof( DataContext ) );
                        services.AddDbContext<DataContext>( options => { options.UseInMemoryDatabase( "TestDb" ); } );
                    } )
                    .ConfigureTestServices( services => {
                        services
                          .AddAuthentication( "TestAuthentication" )
                          .AddScheme<AuthenticationSchemeOptions, TestAuthenticationHandler>( "TestAuthentication", null );
                    } );
                } );
                
            this._serviceProvider = appFactoryNoAuthMemoryDB.Services;
            this.TestClient = appFactoryNoAuthMemoryDB.CreateClient();
        }

        public void Dispose() {
            using var serviceScope = this._serviceProvider.CreateScope();
            var context = serviceScope.ServiceProvider.GetService<DataContext>();
            context.Database.EnsureDeleted();
        }
    }
```
The Handler

```
 public class TestAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions> {
        public TestAuthenticationHandler( IOptionsMonitor<AuthenticationSchemeOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock ) : base( options, logger, encoder, clock ) {
        }

        protected override async Task<AuthenticateResult> HandleAuthenticateAsync() {
            var claims = Factory.Security.ClaimsFactory.GetMockClaimsFromUser(Factory.Domain.UsersFactory.GetMockAuthenticatedUser());
            var identity = new ClaimsIdentity( claims, this.Scheme.Name );
            var principal = new ClaimsPrincipal( identity );
            var ticket = new AuthenticationTicket( principal, this.Scheme.Name );

            return await Task.FromResult( AuthenticateResult.Success( ticket ) );
        }
    }
```
The Mocks:
 ```
internal static User GetMockAuthenticatedUser() {
            return new User {
                Username = "TestUser",
                Email = "test.user@example.com",
                IdSts = 2020
            };
        }
```
```
internal static List<Claim> GetMockClaimsFromUser(User user) {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim("sub", user.IdSts.ToString())
                };
        }
```
And an **example integration test** extending the base test
```
public class TransactionsControllerTest : SkipAuthMemoryDbIntegrationTest {

        [Fact]
        public async Task GetAll_WithoutAnyTransactions_ReturnsEmptyDataResponse() {
            //  Arrange

            //  Act
            var response = await this.TestClient.GetAsync( ApiRoutes.Transactions.GetAll );

            //  Assert
            response.StatusCode.Should().Be( HttpStatusCode.OK );
            (await response.Content.ReadAsAsync<PagedResponse<TransactionResponse>>()).Data.Should().BeEmpty();
        }
}
```
![Annotazione 2019-10-11 161421](https://user-images.githubusercontent.com/17455841/66658715-50da6f00-ec42-11e9-9aec-807a7e028369.png)

**Comment by InDieTasten** [comment]
Hello everyone. There are already many helpful solutions here, which almost all seem to work for the most of us. But today I have something to share with you.

Whilst all our current solutions here are trying to mock the authentication middleware in some way or another, I have just completed creating a way of actually signing into **ASP.NET Core Identity** with actual seeded credentials. This is of course much more work to setup, but it will allow you to include the entire authentication setup to be tested as part of your tests. As it should be, in an _integration_ test.

The sample code of a minimal solution can be found here: https://github.com/InDieTasten/Authenticated-Integration-Testing

It's heavily inspired by the current docs, but going the extra step to GET the login page, POST the credentials to the login page, and then GETting an endpoint secured by [Authenticate].

The code is obviously a bit dirty, and things can be rearranged for easier usage, but for a prototype and understanding the the underlying workings, it should suffice.

The linked sample is on ASP.NET Core 3.0.


I'm hoping, that somebody will have the courage to extend the current documentation with this functionality, because this seems to be the first big issue most developers face, once they decided to give integration testing a shot. If there are further questions about the code, feel free to ask by creating an issue on the linked repo.

Good luck

**Comment by guardrex** [comment]
Although there are many variations discussed here for auth+testing, we're going to start with https://github.com/aspnet/AspNetCore.Docs/pull/15340. That will go in today and go live within 24 hours. We'll continue to take feedback on authn/authz as we go ... but let's start with that, which covers the basics of what engineering would like to show **_intinally_**. We'll keep an :eye: out and an :ear: open for more feedback.

**Comment by sadiqkhoja** [comment]
I had to do following to get it work:

```
services.AddAuthentication(x =>
{
  x.DefaultAuthenticateScheme = "Test";
  x.DefaultChallengeScheme = "Test";
})
.AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(
   "Test", options => { });
```

**Comment by jelster** [comment]
Hi @guardrex -- 
Thanks for all the effort you've put into this! 🙇 
I like the approach you've taken, and not just because it's similar to the pattern I laid out in my [comment](https://github.com/aspnet/AspNetCore.Docs/issues/6882#issuecomment-452388897) and the linked [gist](https://gist.github.com/jelster/6b850d567acef343e59fad70cb20455a) 😄 

Something I think that was in my gist that I didn't see in your implementation was my update to support per-fixture testing of arbitrary claims - was that an oversight or on purpose because you didn't want to complicate things further by including claims?

**Comment by guardrex** [comment]
Thanks, but that wasn't my pattern ... it was from engineering. I just got the commas in there. :smile:

Open a new issue using the **This Page** feedback button/form at the bottom of the topic. We can't work closed issues/PRs. Include the cross-link to your comment and gist.
