### ISSUE TITLE
RP tutorial links to MVC streaming file upload, which is not compatible with RP

### ISSUE THREAD

**Issue by nburkitt** [aspnet/AspNetCore.Docs#6927]
The RP tutorial page [Upload files to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?view=aspnetcore-2.1) includes a link to [Uploading large files with streaming](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#uploading-large-files-with-streaming). Beyond the fact that the linked document resembles a box from Ikea that's missing its assembly instructions, the referenced code is not even compatible with RP - it relies heavily on method-level filter attributes, which are not available in RP.

**Comment by guardrex** [comment]
It's due for an overhaul on https://github.com/aspnet/Docs/issues/5331.

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
