### ISSUE TITLE
Update topics that use "Shared Framework"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#7124]
* Add brief definition and link to Nate's blog on first use of the term "shared framework".
* Fix incorrect/confusing/misleading usage of the term.

In each of the following docs -- 
* metapackage.md
* metapackage-app.md
* troubleshoot.md 
* 2.0 to 2.1 migration 
* 2.2 to 3.0 migration 

Create new issue to change the links when https://github.com/dotnet/docs/issues/5009 is completed and there's a doc to link to.

**Comment by tdykstra** [comment]
As a stop-gap until the https://github.com/dotnet/docs/issues/5009 article is written I'll update these and link to Nate's blog.

**Comment by tdykstra** [comment]
There are a few other docs that mention shared framework and could use some clarification or a least links.  Here then are all of the docs I think we should hit : 
* metapackage.md
* metapackage-app.md
* troubleshoot.md 
* 2.0 to 2.1 migration 
* 2.2 to 3.0 migration 

In each -- 
* Add brief definition and link to Nate's blog on first use of the term "shared framework"
* Fix incorrect/confusing/misleading usage of the term and how it's used

@Rick-Anderson LMK if this is what you had in mind.
