### ISSUE TITLE
How to trust HTTPS cert from WSL Ubuntu on Windows?

### ISSUE THREAD

**Issue by AArnott** [aspnet/AspNetCore.Docs#7166]
I'm using Windows Subsystem for Linux (Ubuntu) to host my ASP.NET Core web app. It has generated its own HTTPS self-signed cert. How do I configure my Windows cert store to trust that cert so that my Windows browser will navigate to it and trust it? 
Note I've tried the command above, but it only trusts the Windows-generated cert. I need Windows to trust the Linux cert.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2191c25-85c0-80b3-6e0e-f54aaf087150
* Version Independent ID: 5e0ec5a6-a0d1-b78f-b5cc-209f63a66c51
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started?view=aspnetcore-2.1&tabs=linux)
* Content Source: [aspnetcore/getting-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by AArnott** [comment]
[This](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md) helped out. I followed the instructions to export my Windows-generated cert:

```
dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p crypticpassword
```

Then in my WSL window I ran:
```
ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/c/Users/andarno/.aspnet/https/aspnetapp.pfx dotnet watch run
```

That effectively set the environment variables so that linux would use the Windows generated-and-trusted cert. Then my Windows browser was happy to access it. :)

**Comment by Rick-Anderson** [comment]
@guardrex  where is the right place to surface this info? I'm thinking in another doc, but link to it here.

**Comment by Rick-Anderson** [comment]
@scottaddie  isn't this related to #3310 ?

**Comment by Rick-Anderson** [comment]
Make sure this page has a link showing how to set it up a cert for Ubuntu
