### ISSUE TITLE
Update GULP topic to use VS/CLI tabs

### ISSUE THREAD

**Issue by grimley517** [aspnet/AspNetCore.Docs#7299]
This article seems to assume that the developer is using visual studio in a windows environment.  The cross-platform nature of ASP.NET core makes this a poor assumption.

There should be a reference to this assumption in the introduction, as visual studio for mac does not seem to support gulp in the same manner.  CLI usage is also missing - and again may be different in different environments.

@Rick-Anderson 	edit: 4.7 KPV, 100% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb34beb-733d-ad1e-37a7-cbe045ee9f15
* Version Independent ID: 02319a95-6eb9-59cd-f5fc-747c61e90123
* Content: [Use Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-gulp.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie  what's the plan for this tutorial? 
We should only feature VS in a few onboarding tutorials.

**Comment by scottaddie** [comment]
@Rick-Anderson Let's use this issue as a tracker for updating the doc. It shouldn't be tied to a specific OS or IDE/editor.

**Comment by Rick-Anderson** [comment]
Close per #10798
