### ISSUE TITLE
Application Insights example

### ISSUE THREAD

**Issue by hiraldesai** [aspnet/AspNetCore.Docs#7316]
Can this include the example for Application Insights for folks who didn't want to take dependency on third party providers. I remember it used to be `loggerFactory.AddApplicationInsights()` in the `Configure` method before along with `loggerFactory.AddDebug()`. But dotnet core 2.1 has the `Debug` and `Console` loggers moved inside the `WebHost.CreateDefaultBuilder`. Now I'm not sure what the right way of doing this for Application Insights is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#third-party-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @hiraldesai Thanks for commenting. Yes, this is something we should consider. It may take a while to get to it in a formal way with a section added to the topic; but in the meantime, let's consider adding an additional resource link to ...

https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging

@Rick-Anderson @scottaddie Sound good for the time being? I'll circle around to this issue later and do a proper job on documenting this aspect of logging.

**Comment by Rick-Anderson** [comment]
@guardrex 	ping @jeremymeng - he's the AI contact and is very helpful.

**Comment by Rick-Anderson** [comment]
@guardrex 	see stopgap issue #10511

**Comment by guardrex** [comment]
@Rick-Anderson Very good. I was hoping (*am hoping*) that it can merely be linked to an existing AI topic. If not, this becomes a section in the Logging topic.

After we have an answer from the AI folks and decide that we'll need to work this issue, do you still want me to do this given that @tdykstra did the last major overhaul to the topic?

**Comment by Rick-Anderson** [comment]
@guardrex 	we got an answer in https://github.com/aspnet/Docs/issues/10511
@tdykstra 	can do it.
