### ISSUE TITLE
Need emphasis on the "identical parameter names" for the file data

### ISSUE THREAD

**Issue by heapwalker** [aspnet/AspNetCore.Docs#7702]
To whom it may concern, the `name` specified at the submitted data MUST match exactly with the name of the argument at the controller's action.

i.e. if you have a `<input>` with such name:
```html
<input type="file" name="deathStarPlans" multiple />
```

or if you use `FormData` instead (no matter plain javascript or typescript):
```javascript
const formData = new FormData();
for (var file in $event.target.files) {
	formData.append('deathStarPlans', file, file.name);
}
```

Then you MUST name your argument on c# controller's action in exactly same name:
```csharp
public async Task<IActionResult> Post(List<IFormFile> deathStarPlans)
```

May the author of this article add a emphasis on this requirement?

---

### Background story:
I was (wrongly) assuming that `List<IFormFile>` would contain ALL the uploaded files (as conveniently as `Request.Form.Files`) and we could get (recognize) the original field name via `IFormFile#Name`. I thought the names used during submission was not important.
To be specific, I was using plainly `formData.append('files', file, file.name);` at my angular app. At the same time I wrote `public async Task<IActionResult> Post(List<IFormFile> formFiles)` at my c# controller, just to make the argument name looks, hopefully, like its type.
Apparently the different parameter names leads to failure.

This small mistake took me more than a day ._. trying different combinations of ajax headers / trying coding with `Request.Form.Files`...
Until I read https://devblog.dymel.pl/2016/09/02/upload-file-image-angular2-aspnetcore/ that we should have identical names at both client side and server side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @heapwalker. This topic will be receiving an overhaul on #5331. I'll add this issue to the list there; so when it's worked over, your remarks will be taken into account.

**Comment by MisinformedDNA** [comment]
@heapwalker Thank you! I thought I was losing my mind!

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
