### ISSUE TITLE
OnModelCreation highlighting is incorrect

### ISSUE THREAD

**Issue by RyanTaite** [aspnet/AspNetCore.Docs#7709]
I noticed that the highlighting when updating the [OnModelCreating method](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio#update-the-db-context) indicates that the method was created earlier in the walk-through, but going back through the previous four articles makes no mention of it. Should not the entire method be highlighted?

<hr/>

Probably related is that the existing DbSets, `Course(s)` and `Student`, also have some very small discrepancies leading up to this point too:

- In the [Get started](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#examine-the-schoolcontext-db-context) article, `public DbSet<Course> Course {get; set; }` (singular) is seen, but back in [OnModelCreating method](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio#update-the-db-context) it's `Courses` (plural)
- `_context.Students` (plural) is mentioned once in the text here in [Sort, filter, page, and group](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1#add-filtering-functionality-to-the-index-method), seems to be the only mention of it in plural.

My final, kinda nit-picky, question that I have is that if in the `OnModelCreating` method, all of the new DbSets being created (`Departments`, `Instructors`, `OfficeAssignments`, and `CourseAssignments`) are plural and then converted to a non-pluralized table name, shouldn't `Course`, `Enrollment`, and `Student` also start off pluralized and then be converted? Or just simply left out of the method altogether since they are created non-pluralized already? (expect for maybe `Courses`? See first bullet point earlier)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by RyanTaite** [comment]
Okay, if you would like, I can try to go through and update the articles so all the `_context.(Student|Course|Enrollments)` references in the code and text are plural, but I'm not sure I'll be able to do that until Monday.

**Comment by Rick-Anderson** [comment]
@RyanTaite Thanks for the offer. I think we'll leave this for @tdykstra to do when he does the next document update. We'll keep this issue open to track the work.

**Comment by RyanTaite** [comment]
Sounds good!

**Comment by Rick-Anderson** [comment]
@tdykstra  when you update this series can you ask @RyanTaite  for a review?

**Comment by tdykstra** [comment]
@Rick-Anderson Will do!

**Comment by Rick-Anderson** [comment]
@RyanTaite 	there's lots of other issues we'd appreciate your help on. Almost every issue is available, even if it's assigned to someone.

**Comment by RyanTaite** [comment]
@Rick-Anderson I'm not sure how much time I can put towards it, but I'm happy to help where I can. I'll check out the issues and see if there is anything I understand well enough to contribute to.
