### ISSUE TITLE
Update auto-generated ApplicationUser.cs

### ISSUE THREAD

**Issue by karlbaker02** [aspnet/AspNetCore.Docs#7722]
Upgrading from ASP.NET Core 1.1.2 to 2.0, I followed this guide for migrating authentication and identity. One of the missing pieces that it does not cover is that the `ApplicationUser` model needs to use `Microsoft.AspNetCore.Identity` and not `Microsoft.AspNetCore.Identity.EntityFrameworkCore` - without this change, the project won't build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@karlbaker02  that sounds right.

**Comment by Rick-Anderson** [comment]
@karlbaker02  any chance you could create a PR to address this?
