### ISSUE TITLE
Incorrect updates to SchoolContext class

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/AspNetCore.Docs#7726]
In the [Update the DB Context](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=netcore-cli#update-the-db-context) section, you show a few updates that are required in the SchoolContext class; however, the only other work done on the SchoolContext class in this tutorial was in [part 1](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#examine-the-schoolcontext-db-context), and in this part of the tutorial there are changes that are not highlighted as new (and therefore that will likely be missed by someone not paying attention and just copying the highlighted portions of the code). The changes that were made in this part that are not highlighted are as follows:

- Course property was renamed as Courses (question: shouldn't each of these DbSet properties use plural for their names, since all of the ones being added here do?)
- The OnModelCreating method did not exist at all before this step in this part of the tutorial, yet highlighting seems to indicate that it should have been there with modelBuilder.Entity&lt;&gt;.ToTable invocations for Course, Enrollment, and Student.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=netcore-cli#update-the-db-context)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by bill1109** [comment]
I ran into the same issue...

**Comment by regal60740** [comment]
I had to rename Courses to Course in "context.Course.Add(c);" to get error to disappear. Hopefully moving forward, everything will work.

**Comment by ianpano** [comment]
ditto.

**Comment by tdykstra** [comment]
Fixed by #13422 (3.0 version of the tutorial)
