### ISSUE TITLE
Document unit testing with IHttpClientFactory

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#7847]
There's a partial example at https://github.com/aspnet/HttpClientFactory/wiki/Consumption-Patterns#unit-testing. This content needs to be added to Docs.

See the xUnit & Moq sample at https://github.com/glennc/httpclientfactorysample/tree/master/test/WebUI.Tests.

**Comment by scottaddie** [comment]
@glennc @rynowak Do either of you have a sample app I can use for this? The Wiki section (linked above) is incomplete with a TODO comment.

**Comment by jphellemons** [comment]
FYI: The first url redirects to https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1

**Comment by scottaddie** [comment]
@jphellemons Thanks for pointing this out. All of the content on that Wiki page, except for the unit testing, was moved to Docs.

**Comment by jphellemons** [comment]
@scottaddie the unit testing part was exactly what I was looking for.

**Comment by scottaddie** [comment]
@jphellemons Here's a screenshot of what that Wiki page used to contain for unit testing:

![image](https://user-images.githubusercontent.com/10702007/45433244-5c3f1d80-b671-11e8-889c-028e26ec91e6.png)

See also the link above to the xUnit & Moq sample.

**Comment by Rick-Anderson** [comment]
@guardrex 	please suggest a doc this issue should be attached to.

**Comment by guardrex** [comment]
@Rick-Anderson Perhaps none because we only keep two unit tests topics ([Razor Pages tests](https://docs.microsoft.com/aspnet/core/test/razor-pages-tests) & [Test controllers](https://docs.microsoft.com/aspnet/core/mvc/controllers/testing)), and this doesn't look like it fits neatly into either of them. I think Scott's plan was to make a new topic for this under the *Test, debug, and troubleshoot* node.

**Comment by Rick-Anderson** [comment]
@scottaddie  we don't have the resources to maintain our current testing docs, so I'm closing this issue.

**Comment by lloydjatkinson** [comment]
This is still a valid request as real world code is unit tested.

**Comment by martincostello** [comment]
I wrote up a blog post for a helper library for this sort of thing a few years ago if it's of any help to you: https://tech.justeattakeaway.com/2017/10/02/reliably-testing-http-integrations-in-a-dotnet-application/
