### ISSUE TITLE
How to properly use IHttpClientFactory in a console app

### ISSUE THREAD

**Issue by suchoss** [aspnet/AspNetCore.Docs#7967]
I am missing information about how to use `IHttpClientFactory` in console application. Or should I still register some service `services.AddHttpClient();`? and then create client when needed.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Initiate HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by TheBeardedLlama** [comment]
I'm using it with a cmd app.

I had to find a way in via DI. In my case (webjob), I had to `ConfigureServices` using the `IServiceCollection` that `IWebJobsBuilder` exposed.

**Comment by stevejgordon** [comment]
I'm also using this successfully in non-webserver based console apps. My preferred approach is to use the [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1#configureservices) which allows for the Microsoft DI container to be registered in ConfigureServices, in a similar way to the WebHost.

**Comment by guardrex** [comment]
@Rick-Anderson Ok to work this in early June? If so, I'll wait for a "June 2019" project to schedule it (or I can create a June project if you want me to ... let me know).

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama  @stevejgordon  can either of you provide a sample app we can use?

**Comment by guardrex** [comment]
@Rick-Anderson The code is already on the PR #13434. Do you want me to turn that into a sample app?

**Comment by TheBeardedLlama** [comment]
@Rick-Anderson I don't have one, but could provide one if you like

let me know if/when and I could sort something out

although @guardrex's looks ok to me

either way, happy to help if required

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama   as long as you're OK with @guardrex sample we should be good. Thanks for the quick feedback.
