### ISSUE TITLE
Document how to setup server side rendering with Angular Template

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#7971]
_From @dominikfoldi on June 29, 2018 19:19_

It would be awesome to have an AppModule that we can use to add only browser supported modules if SSR enabled. The idea is to have a shared AppModule that the server AppModule and the browser AppModule use. The browser one only bootstrapped in the browser not on the server.

You can find a great example in @MarkPieszak's repo: https://github.com/MarkPieszak/aspnetcore-angular2-universal

_Copied from original issue: aspnet/Templating#597_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dominikfoldi.
@danroth27 what are your thoughts regarding this?

**Comment by mkArtakMSFT** [comment]
_From @danroth27 on August 3, 2018 23:50_

@SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
_From @SteveSandersonMS on August 6, 2018 10:5_

The goal for the template is to be as close to Angular CLI defaults as possible, and doesn't have SSR enabled by default. Hence I'd suggest it would make more sense for an `AppModule` or similar to be provided in the form of a blog post or wiki so that people who want to go in that direction can add it.

**Comment by mkArtakMSFT** [comment]
_From @dominikfoldi on August 6, 2018 10:12_

@SteveSandersonMS okay this makes sense. I think the best place for it would be in the Angular project template documentation at Microsoft Docs: https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio

**Comment by ryanbrandenburg** [comment]
As per https://github.com/aspnet/AspNetCore.Docs/issues/8139#issuecomment-467613547 we don't want to make recommendations about Angular SSR.
