### ISSUE TITLE
Defining Attributes in Metadata Classes Doc for ASP.NET Core

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetCore.Docs#8003]
## Requests for new Topics
Explain how [`ModelMetadataType`](https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/ModelMetadataTypeAttribute.cs) works.

Put the documentation in https://docs.microsoft.com/en-us/aspnet/core/index, pages titled
   - Model validation in ASP.NET Core MVC
   - Add validation to an ASP.NET Core MVC app

Almost copy and past [from this page](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff664465(v=pandp.50)).

**Adapt the code for NETCore:**
```
public class ProductMetadata
{
  [Required(ErrorMessage = "ID is required.")]
  [RegularExpression("[A-Z]{2}[0-9]{4}", 
          ErrorMessage = "Product ID must be 2 capital letters and 4 numbers.")]
  public object ID { get; set; };

  [StringLength(100, ErrorMessage = "Description must be less than 100 chars.")]
  public object Description { get; set; } ;
}
```

**Comment by Rick-Anderson** [comment]
@dougbu  see [Defining Attributes in Metadata Classes](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff664465(v=pandp.50))

Do we need an ASP.NET Core version of that doc?

**Comment by dougbu** [comment]
@Rick-Anderson good idea.

Because `[MetadataType]` is available only in .NET Framework, ASP.NET Core Mvc instead supports `[ModelMetadataType]` (in the `Microsoft.AspNetCore.Mvc` namespace).

Separately, as far as I can tell, there's no requirement `[ModelMetadataType]` be applied to a `partial` class.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
