### ISSUE TITLE
IFormFile interface has incorrect method signature

### ISSUE THREAD

**Issue by ShreyanshDaga** [aspnet/AspNetCore.Docs#8039]
From the code metadata:
    //
    // Summary:
    //     Represents a file sent with the HttpRequest.
    public interface IFormFile
    {
        //
        // Summary:
        //     Gets the raw Content-Type header of the uploaded file.
        string ContentType { get; }
        //
        // Summary:
        //     Gets the raw Content-Disposition header of the uploaded file.
        string ContentDisposition { get; }
        //
        // Summary:
        //     Gets the header dictionary of the uploaded file.
        IHeaderDictionary Headers { get; }
        //
        // Summary:
        //     Gets the file length in bytes.
        long Length { get; }
        //
        // Summary:
        //     Gets the form field name from the Content-Disposition header.
        string Name { get; }
        //
        // Summary:
        //     Gets the file name from the Content-Disposition header.
        string FileName { get; }

        //
        // Summary:
        //     Copies the contents of the uploaded file to the target stream.
        //
        // Parameters:
        //   target:
        //     The stream to copy the file contents to.
        void CopyTo(Stream target);
        //
        // Summary:
        //     Asynchronously copies the contents of the uploaded file to the target stream.
        //
        // Parameters:
        //   target:
        //     The stream to copy the file contents to.
        //
        //   cancellationToken:
        Task CopyToAsync(Stream target, CancellationToken cancellationToken = default);
        //
        // Summary:
        //     Opens the request stream for reading the uploaded file.
        Stream OpenReadStream();
    }

Your article has the method
        Task CopyToAsync(Stream target, CancellationToken cancellationToken = null);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ShreyanshDaga ... The topic is due for an overhaul on #5331. I'll add this issue to the list.

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
