### ISSUE TITLE
Code bug with model validation fails

### ISSUE THREAD

**Issue by eyadraschad** [aspnet/AspNetCore.Docs#8049]
I think that the `return Page();` which is being used if the model is not valid when creating or editing (a course or an instructor) is missing a key point at server side which is that the select menu and the checkboxes list will become empty when any of the OnPost actions is called. 

Currently, the line `return Page();` will result in a "NullReferenceException" because the populated fields (for example the DepartmentNameSL which is being populated by PopulateDepartmentsDropDownList at OnGet) are not longer populated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1#add-course-assignments-to-the-instructor-edit-page)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@eyadraschad  thanks, we'll fix this in the next doc update.

**Comment by edikaufmann** [comment]
Is there a workaround for this issue ?

**Comment by eyadraschad** [comment]
@edikaufmann yes, the workaround would be to call the methods that populate the select list and the list of checkboxes again `OnPost` (when the validation of the model fails) just like you did originally with `OnGet`. Because in this case this would be the same as making a new Get request.

**Comment by AlbertoPa** [comment]
The method is indeed already called, but the argument would seem to be incorrect. In the Create page, when saving to the DB fails, the code is:

PopulateAssignedCourseData(_context, newInstructor);

however, shouldn't newInstructor be replaced with Instructor, which is the model bound to the view? Similarly for Edit with instructorToUpdate, assuming my reasoning is correct.
