### ISSUE TITLE
Generic Class and Localization blog

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#8244]
See [Localization & Generics](http://www.hishambinateya.com/localization-and-generics)

and https://github.com/aspnet/Home/issues/3422

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
FYI I wrote a blog post last month about [Localization & Generics](http://www.hishambinateya.com/localization-and-generics) hope it helps. I think we need to mention into the docs how to deal with generic classes because this confusing 😄

**Comment by hishamco** [comment]
What's the action needed on this?

**Comment by hishamco** [comment]
@Rick-Anderson any update on this?

**Comment by Rick-Anderson** [comment]
@hishamco 	I made this a discussion issue and changed the title/added link at the top. This should make it discoverable in the article.

**Comment by hishamco** [comment]
What's the action needed on this on?

**Comment by Rick-Anderson** [comment]
No action needed. It's a `discussion` issue. I could close it, but it's more discoverable when it's open.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/58982199-9d331100-876f-11e9-8a6e-220e9b461677.png)

**Comment by hishamco** [comment]
I already point out to a blog post that I wrote, so it can't be open forever, but we could point out in the docs or write a small section for this one

**Comment by programatix** [comment]
It this ```UseGenericResources``` property part of ASP.NET Core? It's not available for me to use.

**Comment by hishamco** [comment]
Nope

**Comment by codelovercc** [comment]
Hi, I created a class to solve Generic class localization resources naming. I hope this could help some one who need this. 

```C#

using System.Globalization;
using System.Reflection;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace My.Localization;

public class GenericTypeSupportResourceManagerStringLocalizerFactory : ResourceManagerStringLocalizerFactory
{
    public GenericTypeSupportResourceManagerStringLocalizerFactory(IOptions<LocalizationOptions> localizationOptions,
        ILoggerFactory loggerFactory) : base(localizationOptions, loggerFactory)
    {
    }

    protected override string GetResourcePrefix(TypeInfo typeInfo, string? baseNamespace, string? resourcesRelativePath)
    {
        if (typeInfo == null)
        {
            throw new ArgumentNullException(nameof(typeInfo));
        }

        if (string.IsNullOrEmpty(baseNamespace))
        {
            throw new ArgumentNullException(nameof(baseNamespace));
        }

        if (string.IsNullOrEmpty(typeInfo.FullName))
        {
            throw new ArgumentException(string.Format(CultureInfo.CurrentCulture,
                "Type '{0}' must have a non-null type name.", typeInfo));
        }

        if (string.IsNullOrEmpty(resourcesRelativePath))
        {
            return typeInfo.FullName;
        }
        
        // Convert the full type name
        // MyClass<T,T1> is MyClass`2 to MyClass_2
        // MyClass<int, double> is MyClass`2[Int,Double] to MyClass_2
        // MyClass<T, T1>.MySubClass<TS, TS1> is MyClass`2+MySubClass2`2 to MyClass_2.MySubClass2_2
        var fullName = ConvertGenericFullName(typeInfo);

        return baseNamespace + "." + resourcesRelativePath + TrimPrefix(fullName, baseNamespace + ".");
    }

    private static string ConvertGenericFullName(Type typeInfo)
    {
        if (string.IsNullOrEmpty(typeInfo.FullName))
        {
            throw new ArgumentException(string.Format(CultureInfo.CurrentCulture,
                "Type '{0}' must have a non-null type name.", typeInfo));
        }

        string fullName;
        if (typeInfo.IsGenericType)
        {
            fullName = typeInfo.FullName.AsSpan(0, typeInfo.FullName.IndexOf('[')).ToString().Replace('`', '_')
                .Replace('+', '.');
        }
        else
        {
            fullName = typeInfo.FullName;
        }

        return fullName;
    }

    private static string TrimPrefix(string name, string prefix)
    {
        return name.StartsWith(prefix, StringComparison.Ordinal) ? name[prefix.Length..] : name;
    }
}

```

Extension method:

```C#
public static class LocalizationServiceCollectionExtensions
{
    public static IServiceCollection AddGenericTypeSupportStringLocalizerFactory(this IServiceCollection collection)
    {
        return collection.Replace(ServiceDescriptor.Singleton<IStringLocalizerFactory, 
            GenericTypeSupportResourceManagerStringLocalizerFactory>());
    }
}
```

**Comment by hishamco** [comment]
@codelovercc do you have a repo for it, so I can have a look?

**Comment by codelovercc** [comment]
@hishamco I would create a repo if that helps :)

**Comment by codelovercc** [comment]
@hishamco Here is the repo [GenericClassLocalization](https://github.com/codelovercc/GenericClassLocalization)
