### ISSUE TITLE
YouTube version

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#8526]
[YouTube version](https://www.youtube.com/watch?v=F0SP7Ry4flQ&feature=youtu.be)
by @krchome 
see #8522

If you find this video helpful, leave a comment or 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@Rick-Anderson if there's no more to be done on this, can it be closed?

**Comment by Rick-Anderson** [comment]
@tdykstra 	I keep these open and marked as discussion (milestone) so it's more discoverable and folks can comment on the youtube.

**Comment by ryanbrandenburg** [comment]
Can we condense these 17 issues into one issue with a list of the videos and their topics? Currently they all have the same name, and it looks like 17 duplicate issues.

**Comment by Rick-Anderson** [comment]
We like these visible on the page they go with. You can see them at the bottom of the page.

You can filter them out via -label:Discussion or -milestone:discussion

label:PU is for the Product unit, label:SignalR is self explanatory. You shouldn't be looking at P3 issues.

Try is:issue is:open  -label:P4 -label:P3 -label:P2 -label:SignalR  -milestone:discussions -label:"Razor Components" 

![image](https://user-images.githubusercontent.com/3605364/53517251-4633e680-3a72-11e9-87e1-12f90706ac0c.png)

**Comment by tdykstra** [comment]
@Rick-Anderson Why not put the links in the docs in an Additional resources section? I'd prefer not to hold issues open just to provide links.

**Comment by Rick-Anderson** [comment]
Good idea. Do you want to two issues to do that and I'll split the work with you.

**Comment by tdykstra** [comment]
Deal

**Comment by donhuvy** [comment]
show remove these content 

Additional resources
Youtube version of this tutorial
Youtube version of this tutorial (Turkish)

the quality of video tutorial is very bad, out of date, none meaning.

**Comment by Rick-Anderson** [comment]
@donhuvy  thanks for bringing this to our attention.
