### ISSUE TITLE
Blog on revoking cookie consent after consent has been accepted

### ISSUE THREAD

**Issue by joeaudette** [aspnet/AspNetCore.Docs#8544]
http://www.joeaudette.com/blog/2018/08/28/gdpr---adding-a-revoke-consent-button-in-aspnet-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mochr** [comment]
Will be closed by #13849.

**Comment by wadepickett** [comment]
@Rick-Anderson, should this one be closed?  Not clear to me if #13849 that was merged closes this issue or not.

**Comment by Elvis254** [comment]
Hello @Rick-Anderson,
The link: [http://www.joeaudette.com/blog/2018/08/28/gdpr---adding-a-revoke-consent-button-in-aspnet-core](http://www.joeaudette.com/blog/2018/08/28/gdpr---adding-a-revoke-consent-button-in-aspnet-core) isn't available.
Elvis.
