### ISSUE TITLE
Update sample with latest templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#8596]
Update sample with latest templates

2.9 K PV 100% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScriptServices to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Also note that this sample is on the sample update tracking issue #5495. Whoever takes it, please update #5495 or ping us to update that issue.

**Comment by RyanLilla** [comment]
@Rick-Anderson Is this issue still open? Could you tell me more about what exactly needs to be done, if so?

**Comment by guardrex** [comment]
The sample isn't directly linked into the topic, but you can see it here ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/client-side/spa-services/sample/SpaServicesSampleApp

It's 1.1-era. It should actually still run ok in this form. However, it would need a bit of work to take it all the way to 2.1. You can follow the migration topics to do it.

1. [Migrate from ASP.NET Core 1.x to 2.0](https://docs.microsoft.com/aspnet/core/migration/1x-to-2x)
1. [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/aspnet/core/migration/20_21)

**Comment by Rick-Anderson** [comment]
Yes, it's open. 
The code under https://github.com/aspnet/Docs/tree/master/aspnetcore/client-side/spa-services/sample/SpaServicesSampleApp needs to be updated to what the current templates generate.

**Comment by Rick-Anderson** [comment]
Moved to #13245
