### ISSUE TITLE
Supporting Third Party Clients using OAuth 2.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore.Docs#86]
ASP.NET 5 -> Security -> Supporting Third Party Clients using OAuth 2.0

[Edit Tom Dykstra] [commit with deleted article stub](https://github.com/aspnet/Docs/commit/e4940fb39e40b4af7973e0709c004c6a6cc62f21)

[Edit Rick-Anderson]

 per `@Tratcher`

- [ ] A walk-through for Google, MicrosoftAccount, and Twitter that highlights some of their eccentricities.
- [ ] A reference to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for additional providers
- [ ] Requesting more data with Scopes (general oauth) and Fields (Facebook specific).
- [ ] Using the OnCreatingTicket event or ClaimsActions to map additional data into claims (#5106)
- [ ] How to map provider claims into the Identity database (#3744)

**Comment by voltagex** [comment]
Ended up here after looking at https://github.com/aspnet/Security/blob/1a59b385a012ac0873fb599fbe6c648b10088fd5/samples/SocialSample/Startup.cs - how can I help?

**Comment by voltagex** [comment]
http://www.jerriepelser.com/blog/introduction-to-aspnet5-generic-oauth-provider is good but appears to be out of date (ExternalAuthenticationOptions doesn't exist)

**Comment by tedzhao** [comment]
How to implement the OAuth 2 server in ASP.NET Core web application(.net core)? any suggestion or comments.

**Comment by nikitadmitry** [comment]
What if I don't want to use DbContext on presentation layer but use business services? How to seup separate project for security?

**Comment by Tratcher** [comment]
https://docs.asp.net/en/latest/security/authentication/sociallogins.html

**Comment by Tratcher** [comment]
The social logins writeup is a good start for Facebook. Here are some things we should add to this or related docs:
- A walk-through for Google, MicrosoftAccount, and Twitter that highlights some if their eccentricities.
- A reference to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for additional providers
- Requesting more data with Scopes (general oauth) and Fields (Facebook specific).
- Using the OnCreatingTicket event to map additional data into claims
- How to map provider claims into the Identity database

**Comment by markadrake** [comment]
Hi @Tratcher - is there any documentation in the works? I've actually managed to stumble through creating my own middleware by using multiple examples I've found online. But one of the last things I need to do is go from identity.AddClaim (which stores claims in a cookie) and change it to store this information in the database. 

Thanks for all the hard work everyone's put into asp.net and it's documentation!

Mark

**Comment by Tratcher** [comment]
@HaoK @blowdart ?

**Comment by Tratcher** [comment]
@rustd ?

**Comment by HaoK** [comment]
@Rick-Anderson might know

**Comment by Rick-Anderson** [comment]
We don't have anything scheduled. If one of you guys wants to write it (in word, notpad or anything I can read), I'll get it published.

**Comment by Rick-Anderson** [comment]
#1470 copied @Tratcher issues

**Comment by tmm360** [comment]
Is this scenario actually supported? Because I'm having issues configuring a login with FB from my app. See aspnet/home#1871

**Comment by danroth27** [comment]
We don't have built-in support for building an authorization server with ASP.NET Core, but you can integrate with an existing service like [Azure AD B2C](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/) or use a community package like [IdentityServer4](https://identityserver4.readthedocs.io/en/release/)

**Comment by danroth27** [comment]
@tmm360 Note, to specifically configure login with FB see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins.

**Comment by tmm360** [comment]
Thank you @danroth27, I'm trying to explore the OAuth world, but it's a bit complex. Anyway I should have found a solution to my problem...
I don't need an OAuth server, but I need to pass through an initialization call on my service for generate the state parameter, and so go to FB for login. I was directly pointing to Facebook from app, and on redirect to my server I was missing the state parameter.

**Comment by Ponant** [comment]
@Tratcher , I think your bullet points will be a great addition. I had to switch back and forth between a @rustd video on youtube and Adam Tulliper on MVA to see how you can add scope to retrieve stuff (friends pictures etc) to your app or db. But these videos go back to a few years ago and they were using a FacebookClient with using statements whereas we could go through DI to fit the .Net Core design.
It will be great to have a working prototype going beyond to @danroth27's link above.

**Comment by Rick-Anderson** [comment]
@voltagex would you be able to work on this doc?

**Comment by isaac2004** [comment]
@Rick-Anderson @danroth27 is this still valid? From what I gather is that the original request was how to build an OWIN middleware to use OAuth2, is that correct?

**Comment by Rick-Anderson** [comment]
@isaac2004  look at what `@Tratcher` posted.

**Comment by isaac2004** [comment]
@Rick-Anderson @Tratcher it seems like some of this checklist is done, so is this what is needed

- [x] A walk-through for Google, MicrosoftAccount, and Twitter that highlights some of their eccentricities.
- [x] A reference to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for additional providers
- [ ] Requesting more data with Scopes (general oauth) and Fields (Facebook specific).
- [ ] Using the OnCreatingTicket event or ClaimsActions to map additional data into claims (#5106)
- [ ] How to map provider claims into the Identity database (#3744)

Does that seem right? Plus it seems like the issues for this got moved into #1470, so is this still needed?

**Comment by Rick-Anderson** [comment]
Moved to #1470
