### ISSUE TITLE
Update for RP

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#8622]
Needs rewrite, update, UE pass.
Doc needs alot of work. RP is a minor part of that work.
16K PV, 56% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#custom-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by daveabrock** [comment]
I can take this RP update as well.

**Comment by Rick-Anderson** [comment]
Sounds great.

**Comment by henrikrxn** [comment]
Sample code still uses 2.0

**Comment by daveabrock** [comment]
Thanks @henrikrxn. This is on my radar in the next few weeks and will be using fresh 2.2 examples.

**Comment by henrikrxn** [comment]
@daveabrock Would you like some help updating the Github example?

But I have no idea which branches to make the PRs for 2.1 and 2.2 repectively

**Comment by Rick-Anderson** [comment]
> But I have no idea which branches to make the PRs for 2.1 and 2.2 respectively

@henrikrxn 	update all to 2.2 and use master.

**Comment by daveabrock** [comment]
@Rick-Anderson 	Is it okay to still reference `MVC`? To note a few examples from the document:

- "This is a great feature of MVC..."
- "MVC will try to bind request data..."
- "In MVC, simple types are..."

Both Model-View-Controller and Razor Pages run on MVC, but saying MVC might confuse some customers who think it only relates to Model-View-Controller.

Should these references just be changed to something like "in ASP.NET Core..."?

**Comment by Rick-Anderson** [comment]
@danroth27 	@DamianEdwards 	@rynowak @tdykstra 	@scottaddie 	
To avoid the ambiguity between ASP.NET Core MVC and MVC with controllers and view vs Razor Pages - in this article on model binding (and similar articles) where we've written MVC will, In MVC, ....
What language do you prefer to remove the ambiguity?
