### ISSUE TITLE
Changing the Edit page

### ISSUE THREAD

**Issue by LouBH** [aspnet/AspNetCore.Docs#8660]
In the section "Update the Edit Page," I assume we are editing Pages/Students/Edit.cshtml.cs but my page is very different from the one in the tutorial.  Here is the code I find in OnPostAsync so I am confused as to how to proceed:

```
public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Student).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(Student.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@LouBH 	 looks like you're right - it needs more highlighting. The changes are similar to those you made previously in the create page. 

Use the code provided. We'll fix this in the next update.

**Comment by kylesalstrom** [comment]
This is the merge I ended up with combining the two. You do need to drop the _context.Attach(Student)

public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var studentToUpdate = await _context.Students.FindAsync(id);

            if(await TryUpdateModelAsync<Student>(
                studentToUpdate,
                "Student",
                s => s.FirstMidName, s => s.LastName, s => s.EnrollmentDate))
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (StudentExists(Student.ID))
                    {
                        throw;
                    }
                    
                }
                
                return RedirectToPage("./Index");
            }
            
            return Page();
        }
