### ISSUE TITLE
Regarding the Concurrency Error Issues for Update the Delete Page Portion

### ISSUE THREAD

**Issue by chaos520** [aspnet/AspNetCore.Docs#8708]
Hi, Microsoft

I had tested the code based on 2.0 cu-part8, it works well with scenario that mentioned in the documentation.

However my development environment is working on 2.1 and when I tried to create and edit in the browser A and deleted in browser B, it does not display the error message as 2.0 code base do. 

Please note that this exception is works great.
                ConcurrencyErrorMessage = "The record you attempted to delete "
                  + "was modified by another user after you selected delete. "
                  + "The delete operation was canceled and the current values in the "
                  + "database have been displayed. If you still want to delete this "
                  + "record, click the Delete button again.";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by chaos520** [comment]
![dotnetcore2 0](https://user-images.githubusercontent.com/9786501/46056340-b74d3600-c182-11e8-9647-36318a5e1546.PNG)

This error does not show on 2.1 code base

**Comment by chaos520** [comment]
![dotnetcore2 1](https://user-images.githubusercontent.com/9786501/46056380-ef547900-c182-11e8-95b8-2566902138b1.PNG)

It throws this error instead

**Comment by Rick-Anderson** [comment]
Thanks for the report. We'll look into it when we can.

**Comment by tdykstra** [comment]
@chaos520 I am unable to reproduce the error. Do you see the same error if you download and run the completed project?
