### ISSUE TITLE
Add and Configure Swashbuckle Middleware issue

### ISSUE THREAD

**Issue by kozigh01** [aspnet/AspNetCore.Docs#8722]
Needed to change documentations "c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");" line to: "c.SwaggerEndpoint("v1/swagger.json", "My API V1");".  The original line gave an error "Fetch errorundefined /swagger/v1/swagger.json".  Was using Microsoft.AspNetCore.App 2.1.4, Microsoft.NETCoreApp 2.1.4 and Swashbuckle.AspNetCore 3.0.0.

@Rick-Anderson 	edit: 25.4 K PV - 70% CSAT
comments: 

- Obsolete UseSwaggerUI.
- None of the steps are up to date.
- the code example does not seem to be working..
- o basic info on what swagger actually is and does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by mmillican** [comment]
I can try to tackle this one as I use Swagger quite a bit.

**Comment by scottaddie** [comment]
@mmillican Go ahead. It's all yours.

**Comment by crgarcia12** [comment]
This works fine for WebApi controllers... If you are using MVC controllers and .netcore21 then you have to add to your controllers:
        [HttpGet]
        [Route("/questions/Active")]
        [ProducesResponseType(typeof(Answer), 200)]

**Comment by Joshua-romil** [comment]
Yupp, still not working for me either. 

```
app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("v1/swagger.json", "My API V1");
                //c.RoutePrefix = string.Empty;
            });
```

**Comment by mmillican** [comment]
@Joshua-romil What part is not working for you?

**Comment by Joshua-romil** [comment]
@mmillican I still get the
```
Fetch error undefined /swagger/v1/swagger.json
´´´

**Comment by mmillican** [comment]
@Joshua-romil Can we please see your `Startup.cs`?

**Comment by Joshua-romil** [comment]
@mmillican
````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using TodoApi.Models;
using Swashbuckle.AspNetCore.Swagger;

namespace TodoApi
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<TodoContext>(opt => opt.UseInMemoryDatabase("TodoList"));
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            
            app.UseSwagger();

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("v1/swagger.json", "My API V1");
                //c.RoutePrefix = string.Empty;
            });

            app.UseMvc();
        }
    }
}
´´´´

**Comment by Joshua-romil** [comment]
@mmillican I tried the Endpoint in different ways, eg:

c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1")

When I try to debug, 

services.AddSwagger(c => {c.SwaggerDoc("v1", new Info {Title = "My API", Version = "v1"});}); 

won't run. I started suspecting It had to do with read/write access, but I'm not sure.

**Comment by mmillican** [comment]
@Joshua-romil 

This is what I'm using for mine:

**ConfigureServices**

```c#

services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
});

```

**Configure**

```c#

app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    c.RoutePrefix = ""; // serves Swagger at the root
});

```

**Comment by spboyer** [comment]
Using the downloaded sample for 2.1 - https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle

The application builds, runs as described in the document. Swagger UI is available at `/swagger` without the mentioned `c.RoutePrefix = ""`

![image](https://user-images.githubusercontent.com/7681382/63027967-e85a5600-be7b-11e9-915e-2f581f813979.png)

@Rick-Anderson @scottaddie - not reproducible
