### ISSUE TITLE
Performing a query on the extended custom user data

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#8746]
I've followed these (great) instructions and have added a custom field to my database. A common ask for people using this example might be: "How can I perform a lookup in the database to make sure my custom field is unique?". For example, if I have "DomainName" as a custom user data property in my registration, I don't want another user registering their unique data with another user's DomainName entity. Just like you can't create two users with the same email address; you get 'username is already taken'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK 	can you suggest?

**Comment by Rick-Anderson** [comment]
@HaoK can you suggest?

**Comment by HaoK** [comment]
You can always just use linq on the Users IQueryable on the UserManager, i.e. userManager.Users.Where(u => o.DomainName == "whatever") and throw a similar error if more than one is found

**Comment by Rick-Anderson** [comment]
@jasonshave  Any chance you could PR this fix? At the top right of the article, select the pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
