### ISSUE TITLE
IEnumerable<IFormFile> model binding works only from version 2.2.0-preview1 up

### ISSUE THREAD

**Issue by meixger** [aspnet/AspNetCore.Docs#8797]
IEnumerable&lt;IFormFile&gt; model binding works only from version 2.2.0-preview1 up: https://github.com/aspnet/Mvc/issues/7770

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @meixger ... I'll add this to the tracking issue for updates to this topic. #5331

**Comment by sgf** [comment]
the same for me,
https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2

the flowlly classes all not works for me 
IFormFileCollection,IEnumerable<IFormFile>,IList<IFormFile>,List<IFormFile>....

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
