### ISSUE TITLE
Contributing topic follow-up

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#8814]
Follow-up to https://github.com/aspnet/Docs/pull/8808.

Let's take a follow-up look at the CONTRIBUTING.md topic. I think there are some additional content opportunities for things that aren't covered *anywhere* (i.e., our unpublished repo rules).

Let's do this **_later_**. We're 🏃🏃🏃🏃🏃😅 at the moment.

**Comment by Rick-Anderson** [comment]
Closing for now. We can revisit when we have time.
