### ISSUE TITLE
Document Localization Extensibility 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#8870]
Copy of #8867
Explain the extensibility points in localization APIs, including:
    - Create a custom `RequestCultureProvider`.
     - Create a custom `StringLocalizer`.

/cc @Rick-Anderson @ryanbrandenburg

----------------------------------------------------
@hishamco did you want this in docs.microsoft.com/en-us/aspnet/core/fundamentals/localization ?

Can you provide code samples for those?

---------------------------------------------

Yep they should go there, by adding a new section after PO Localization section

Can you provide code samples for those?

I already have many sample such as My.Extensions.Localization.Json, My.AspNetCore.Localization.Json, My.AspNetCore.Localization.Session

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
CC @eriawan in case you're interested in helping out on this one.

**Comment by hishamco** [comment]
@Rick-Anderson I'm interested on this one

**Comment by eriawan** [comment]
@Rick-Anderson 
Yes, I'd love to work on this one, but I think I will finish the client side (user agent) culture handling article first. 
I'll wait for @hishamco to do the Document Localization Extensibility first 🙂

**Comment by hishamco** [comment]
No problem we can work together on this :smile:

**Comment by eriawan** [comment]
@hishamco thanks! 👍

**Comment by hishamco** [comment]
**Abstract**

- Describe localization extensibility
- Describe the extensibility points in request culture provider in ASP.NET Core (with sample code)
- Describe the extensibility points in underlying provider for localization resources in ASP.NET Core (with sample code)

**Items to track**

- [ ] Introduction to localization extensibility
- [ ] Create custom `RequestCultureProvider` with sample code
- [ ] Create custom `StringLocalizer` with sample code

Please if there 's anything need to be added let me know /cc @Rick-Anderson @ryanbrandenburg also hope to here from the community folks @damienbod @Bartmax

**Comment by LucaGabi** [comment]
How dose IStringLocalizer chooses which types are localized?

**Comment by ryanbrandenburg** [comment]
This is valuable stuff, but I really don't want talk about implementing your own `RequestCultureProvider` and `IStringLocalizer` included on the main Localization doc page as the document details here seem to imply. That page is already massive and covers a ton of topics, including something as advanced and niche as writing your own extensibility is likely to cause more confusion than it solves.

If we're thinking of this as a separate page or blog post then I have no problems.

**Comment by Rick-Anderson** [comment]
> If we're thinking of this as a separate page or blog post then I have no problems.

Or create it as a discussion issue. I'd be happy to edit/help.

**Comment by hishamco** [comment]
@lucaGabi I think you need to check the README.md file of the [localization repo](https://github.com/aspnet/localization) which contains examples for both custom `RequestCultureProvider` and `IStringLocalizer`

> This is valuable stuff, but I really don't want talk about implementing your own RequestCultureProvider and IStringLocalizer included on the main Localization doc page as the document details here seem to imply. 

My intend is to separate this into another page, which I think don't have any problem with you 😄

**Comment by rodoch** [comment]
Having recently written (and continuing to maintain) a reasonably comprehensive piece of [request localization middleware](https://github.com/gaois/Gaois.Localizer) that extends the framework's native tools I would be very interested to read docs on this topic!

**Comment by Rick-Anderson** [comment]
@hishamco 	let me know if I can help you get started on this.

**Comment by hishamco** [comment]
Sorry I was sick after that too busy, let me start on this week, of course I will let you know when I need your help .. thanks

**Comment by hishamco** [comment]
I think it's the time to start to finalize this ..

**Comment by eriawan** [comment]
guys, I'm sorry I could not finish this sooner.
big apologize...

I'm quite busy this last 4 months with main jobs.

@hishamco I would like to help you to test the doc you have submitted as PR

**Comment by hishamco** [comment]
@eriwan I'd like to help you on you in your other PR if you submitted 😊

**Comment by hishamco** [comment]
@Rick-Anderson this is takes so long because my ankle was broken since 3-4 months ago, hope to push some updates ASAP

**Comment by Rick-Anderson** [comment]
@hishamco  sorry to hear that. Hope you're feeling better. No hurry.

**Comment by hishamco** [comment]
Thanks Rick .. hope to work on this in the next few days ..
