### ISSUE TITLE
Add more details about Custom Authorize filter attribute

### ISSUE THREAD

**Issue by himalayagarg** [aspnet/AspNetCore.Docs#9094]
Add more details about Custom Authorize filter attribute that accept multiple parameters and can filter based on them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1#ifa)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@himalayagarg 	thanks for the suggestion. We'll evaluate this at the next doc sweep.

**Comment by himalayagarg** [comment]
How can we create Filter Attribute on handler, not on Page?

**Comment by DragonMastery** [comment]
This convention is out dated:  
services.AddMvc(options =>
    {
        options.Filters.Add(new SamplePageFilter(_logger));
    });

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
