### ISSUE TITLE
Examples do not show how to configure authentication from appsettings / similar

### ISSUE THREAD

**Issue by mattiasflodin** [aspnet/AspNetCore.Docs#9096]
Hi, not sure if this specific page should cover this but it should at least be somewhere around this section. I find the examples to be unrealistic in that all URLs and similar are hard-coded in source, and I'm frustrated that I can't find any documentation that covers how to do this properly. For example, in the AddJwtBearer callback I might need to access another DI service to obtain client certificates for the back channel http handler, or obtain endpoint URLs from appsettings.json. But since no IServiceProvider is passed into the callback, I'm at a loss how to get this working. All your examples are taking the easy way out by hard-coding values and are unhelpful in the real world.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart 	please respond.

**Comment by blowdart** [comment]
This should be covered in the configuration pages, not in feature specific pages, otherwise you'd have to do it everywhere on every feature that needs configuration.

**Comment by danroth27** [comment]
It sounds like both scenarios being asked about here are really about how to get access to services through DI when setting up options. I agree it would be best to document this in one place that other docs can reference. Filed https://github.com/aspnet/Docs/issues/10553 to track.

**Comment by jlchavez** [comment]
Or Add a Link to the Specific Page that will allow developers to Configure this Cases

**Comment by Rick-Anderson** [comment]
Closing since moved to #10553 to track.
