### ISSUE TITLE
Incorporate metapackage articles into migrate articles

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#9107]
Per decision made at ToC review meeting on 10/16, eliminate the metapackage articles and incorporate their content into the migrate docs:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage 
goes into
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app
goes into
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app shouldn't be moved to migration as it's got critical info that applies to 2.2, 3.0, etc - like [how to update it](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1#update-aspnet-core)

Even the rest of it needs to be in **other topics**.

cc @scottaddie 	@danroth27

**Comment by tdykstra** [comment]
@rick-anderson As you noted, these docs have a mix of information that belongs in different places.  If we go ahead with this, here's where I think the various parts should go.  LMK your thoughts:

* AspNetCore.All metapackage doc
  * Initial note recommending .App for 2.1+ --> Migrate 2.0 to 2.1 doc
  * Initial text that describes what the metapackage is and contains --> What's New in 2.0 doc
  * Implicit versioning h2 section --> Migrate 2.0 to 2.1 doc
  * Migrating .All to .App h2 section --> Migrate 2.0 to 2.1 doc
* AspNetCore.App metapackage doc
  * Initial text that describes what the metapackage is and contains --> What's New in 2.1 doc
  * Implicit versioning section (mostly duplicates text in the .All doc) --> Migrate 2.0 to 2.1 doc
  * Update ASP.NET Core h2 section --> include file for Migrate 2.0 to 2.1 and Migrate 2.1 to 2.2 docs

Redirects of metapackage doc URLs would go to the metapackage sections of the What's New docs (.All to 2.0, .App to 2.1), which in turn link to the migrate docs

**Comment by tdykstra** [comment]
In offline discussion with RickAnderson, we decided that moving this content around isn't worth the amount of time that would be invested in it.
