### ISSUE TITLE
Remove wwwroot assets (CSS/JavaScript/images/lib) from samples that don't need them

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#9186]
Only the following on boarding tutorial samples will contain wwwroot assets:

- Create a Web API 
- Create a Razor Pages web app 
- Create a web app with ASP.NET Core MVC 
- Tutorial: Get started with ASP.NET Core SignalR
- EF/RP intro

The remaining samples will contain *README.ME* explaining how to acquire the assets.

@danroth27 	will be mentioned on all PRs

**Comment by Rick-Anderson** [comment]
@danroth27 	mentioned today it would be really bad if someone had to get the wwwroot contents for a sample. I don't think it's that problematic compared to rewriting the tutorials so they don't depend on wwwroot. You could use the following instructions.

- Generate wwwroot assets: `dotnet new webapp -o ContosoUniversity`
- copy wwwroot folder to sample.

@danroth27 	please respond.

**Comment by danroth27** [comment]
> The remaining samples will contain README.ME explaining how to acquire the assets.

I would recommend something different. For many samples you really don't need much for the UI. For example, if you're demonstrating config or options or DI you can just use some raw HTML. It doesn't have to be pixel pretty. My suggestion is to dramatically simplify samples to focus on the feature they are trying to demonstrate.

**Comment by Rick-Anderson** [comment]
@danroth27 	OK, that will be the new policy. When topics/samples are updated we'll remove the dependency on wwwroot assets. That means we won't make non-trivial progress on removing wwwroot assests in the next 6 months.

**Comment by tdykstra** [comment]
I don't follow what you mean by a style tag paste-in.

**Comment by tdykstra** [comment]
> My suggestion is to dramatically simplify samples to focus on the feature they are trying to demonstrate.

This should be a project by project process; git-ignoring the entire wwwroot folder seems like it might create more problems than it will solve.

**Comment by guardrex** [comment]
\<style> ... styles to make the page look like it wasn't built in *1995!* :smile: lol ... \</style>

**Comment by tdykstra** [comment]
If you just mean a snippet of HTML markup that we can copy and paste, I'd say go ahead and if it's something we'd use in many samples we could store it in https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md

**Comment by danroth27** [comment]
@guardrex Having some *simple* styles that we can use in samples without bringing in all of bootstrap and jquery sounds like a reasonable idea.

**Comment by guardrex** [comment]
kk ... here's an I-dear.

The following styles would have us perform the following for any `dotnet new` template sample ...

1. Kill the navbar (if the sample requires links, put them at the top of the layout).
1. Kill the footer.
1. Drop rows and columns from pages. (Leave the panels alone.)
1. Add the `<style>` tag to the `<head>` of the *_Layout.cshtml* file.

The doc author might need to make a few minor adjustments for any MIA Bootstrap styles that they call for.

### Example for Distributed Caching Sample

*Hey! That looks just like Bootstrap!*

![image](https://user-images.githubusercontent.com/1622880/47455236-f4fba980-d796-11e8-839a-898ab69bf34f.png)

### The Tag

Could prob use a little more work, but just spitball'in here.

> \<style>body{margin:0;padding-bottom:20px;font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-size:14px;line-height:1.42857143;color:#333;background-color:#fff;}h1{font-size:24px;margin:.67em 0;}pre{overflow:auto;}code,pre{font-family:monospace, monospace;font-size:1em;}button,input{margin:0;font:inherit;color:inherit;}button{overflow:visible;}button{text-transform:none;}input{line-height:normal;}*{box-sizing:border-box;}*:before,*:after{box-sizing:border-box;}input,button{font-family:inherit;font-size:inherit;line-height:inherit;}a{color:#337ab7;text-decoration:none;}h1,h2,h3,h4{font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;}h3{font-size:16px;}h4{font-size:18px;}p{margin:0 0 10px;}ol{margin-top:0;margin-bottom:10px;}code,pre{font-family:Menlo, Monaco, Consolas, "Courier New", monospace;}code{padding:2px 4px;font-size:90%;color:#c7254e;background-color:#f9f2f4;border-radius:4px;}pre{display:block;padding:9.5px;margin:0 0 10px;font-size:13px;line-height:1.42857143;color:#333;word-break:break-all;word-wrap:break-word;background-color:#f5f5f5;border:1px solid #ccc;-radius:4px;}pre code{padding:0;font-size:inherit;color:inherit;white-space:pre-wrap;background-color:transparent;border-radius:0;}.container{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;}.container{width:800px;}.btn{display:inline-block;padding:6px 12px;margin-bottom:0;font-size:14px;font-weight:normal;line-height:1.42857143;text-align:center;white-space:nowrap;vertical-align:middle;background-image:none;border:1px solid transparent;border-radius:4px;;color:#fff;background-color:green;border-color:gray;float:right}.panel{margin-bottom:20px;background-color:#fff;border:1px solid transparent;border-radius:4px;box-shadow:0 1px 1px rgba(0, 0, 0, .05);}.panel-body{padding:15px;}.panel-heading{padding:10px 15px;border-bottom:1px solid transparent;border-top-left-radius:3px;border-top-right-radius:3px;}.panel-title{margin-top:0;margin-bottom:0;font-size:16px;color:inherit;}.panel-default{border-color:#ddd;}.panel-default > .panel-heading{color:#333;background-color:#f5f5f5;border-color:#ddd;}.clearfix:before,.clearfix:after,.container:before,.container:after,.panel-body:before,.panel-body:after{display:table;content:" ";}.clearfix:after,.container:after,.panel-body:after{clear:both;}.body-content{padding-left:15px;padding-right:15px;}.panel-body{font-size:16px;}\</style>

**Comment by danroth27** [comment]
For what it's worth, LGTM :smile:

**Comment by guardrex** [comment]
I'll test each time to make sure this works. We might (or **_probably_**) need to tweak it. It looks soooooooo much better than raw HTML tho. 😀

**Comment by danroth27** [comment]
and it's soooooooo much smaller! :tada:

**Comment by guardrex** [comment]
Note to self (i.e. You've heard of *Hello World!* ... this is more like *World Ignore Me!*):

```html
<style>body{margin:0;padding-bottom:20px;font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-size:18px;color:#333}h1{font-size:36px;margin-top:20px;margin-bottom:15px;font-weight:500}h2{font-weight:500}:before,*:after{box-sizing:border-box;}p{margin:0 0 10px;}.container{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;width:800px;}.container:before,.container:after{display:table;content:" ";}.container:after{clear:both;}.body-content{padding-left:15px;padding-right:15px;}</style>
```

**Comment by guardrex** [comment]
Let's pick back up our chat over here.

> Just use .gitignore. That's our standard. The debug assets are trivial.
> If you use .gitignore, the only problem is non-development.

I don't grok that. On the dev's machine ...

* In dev environment, the app uses un-minifed static resources, which aren't present unless .gitignore forces them into the repo.
* In prod environment, the app uses CDN resources or falls back to minified static resources.

So, if .gitignore is used to force static assets into the app, **ok** ... I'm with u there, but that defeats the goal of slimming down the repo. There's another way ... better way imo ...

What I've been doing is *totally removing static assets* for samples that don't need them and dropping in a line of styles that make the app look great. It provides the following advantages:

* Super-slim app ... slim repo eventually as more-and-more samps get this treatment.
* App looks great no matter if the dev is online or offline or running it in dev or prod environments.

That's what I thought we worked out here earlier.

WRT forcing in with .gitignore, ok ... I may have just misunderstood what was being said. I'm not doing that tho unless I have to (e.g., the auth samples, which really need their full static assets to look good everywhere).

**Comment by Rick-Anderson** [comment]
Solved offline. 
The policy is to depend on .gitignore to prevent production assets into the rep.
