### ISSUE TITLE
Suggestion to use EF 2.1 Seed feature on MvcMovieContext instead

### ISSUE THREAD

**Issue by dannevesdantas** [aspnet/AspNetCore.Docs#9205]
EF Core 2.1 brings back seed support by overriding the OnModelCreating method of a database Context class, same way as the "old" EF does. So it’s not required anymore to create a separate Initialize class and call it on Program.cs as the current tutorial does, the MvcMovieContext is now able to seed data (the same way as the old MVC 5 tutorials does). Moreover, I personally believe it would reduce the amount of code necessary to reach the goal of seeding data and consequently will decrease the complexity to beginners. I believe Introducing EF 2.1 seed capability on the tutorial would also be didactic. 

What about updating the "Seed the database" section to seed data through MvcMovieContext database context class by overriding the OnModelCreating method? 

Thanks so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL Server LocalDB in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-2.1&tabs=aspnetcore2x#seed-the-database)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@divega what's the best practice to seed the DB from an ASP.NET Core app?

**Comment by dannevesdantas** [comment]
In order to update the [Create an MVC web app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.1) tutorial to use EF 2.1 Seed feature in the MvcMovieContext instead of a separate SeedData class, some updates in the tutorial's code should be made. Instructions in the [Work with SQL Server LocalDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-2.1&tabs=aspnetcore2x) and [Add a new field](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-2.1) sections are also required.

By using EF 2.1 Seed feature on MvcMovieContext class, the MvcMovieContext.cs would be:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MvcMovie.Models
{
    public class MvcMovieContext : DbContext
    {
        public MvcMovieContext (DbContextOptions<MvcMovieContext> options)
            : base(options)
        {
        }

        public DbSet<MvcMovie.Models.Movie> Movie { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>().HasData(
                new Movie
                {
                    ID = 1,
                    Title = "When Harry Met Sally",
                    ReleaseDate = DateTime.Parse("1989-1-11"),
                    Genre = "Romantic Comedy",
                    Price = 7.99M
                },

                new Movie
                {
                    ID = 2,
                    Title = "Ghostbusters ",
                    ReleaseDate = DateTime.Parse("1984-3-13"),
                    Genre = "Comedy",
                    Price = 8.99M
                },

                new Movie
                {
                    ID = 3,
                    Title = "Ghostbusters 2",
                    ReleaseDate = DateTime.Parse("1986-2-23"),
                    Genre = "Comedy",
                    Price = 9.99M
                },

                new Movie
                {
                    ID = 4,
                    Title = "Rio Bravo",
                    ReleaseDate = DateTime.Parse("1959-4-15"),
                    Genre = "Western",
                    Price = 3.99M
                }
            );
        }
    }
}
```

The Program.cs file would also change for its initial implementation:

```csharp
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Models;
using MvcMovie;

namespace MvcMovie
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
```

It also requires a new Migration to be generated and applied in order to insert the seed data in the db.

**Comment by Rick-Anderson** [comment]
@dannevesdantas 	great idea. We'll take this approach in the next upgrade (soon). cc @tdykstra

**Comment by dannevesdantas** [comment]
cool @Rick-Anderson! I'm glad to be able to help.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @tdykstra Since the scenario ...

> requires a new Migration to be generated and applied in order to insert the seed data in the db.

We don't want to do this in sample apps/topics where migrations aren't in use. It adds a layer of tedious complexity to our normal ✨ *Just Run It!*:tm: ✨ samples.

**Comment by Rick-Anderson** [comment]
@divega 	should we use `protected override void OnModelCreating(ModelBuilder modelBuilder)` (as shown in the previous code) and migrations to seed the DB?

**Comment by shadinamrouti** [comment]
@dannevesdantas thanks for your suggestion, it worked very well. 
I have two notes:
1. The ID field inside OnModelCreating() method should be rewritten as "Id" according to Movie.cs in the tutorial.
2. There is no way to check for any existing data while creating the model, thus, the tutorial should either use SSOX to empty the table or drop-database MPC command.
3. What I liked about OnModelCreating for seeding is avoiding the modification to Program.cs file, which makes the code much simpler. Thank you.

**Comment by divega** [comment]
@Rick-Anderson sorry I missed it when you mentioned me before. I don't know/remember in detail how the tutorial uses the seed data. I think using model data seeding feature would be a good idea as long as:

1. The usage of the data in the tutorial doesn't fall into any of the scenarios described in https://docs.microsoft.com/ef/core/modeling/data-seeding#limitations-of-model-seed-data. 
2. The tutorial doesn't show how to apply the data programmatically (in general, a pit of failure) but rather using migration commands or through generating and deploying a SQL script.

**Comment by Rick-Anderson** [comment]
We've decided to keep the current approach for simplicity.
