### ISSUE TITLE
How to  implement Authorization using Azure AD application roles & role claims?

### ISSUE THREAD

**Issue by adravi** [aspnet/AspNetCore.Docs#9344]
I haven't been able to find documentation such as this: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-roleclaims/ for ASP.NET Core + React template. 
I want to have an Application registered on a Azure Tenant and perform authentication and authorization based on the given roles to the users. 
Any guidance will be highly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@adravi 	thanks for the suggestion.

**Comment by adravi** [comment]
I'm actually about to figure it out. I'm using .NET Core 2.1 (using API Template) and a React 16.6.0 client (create-react-app template) using react-adal (https://github.com/salvoravida/react-adal) and Azure App Registration. I can upload the code. Perhaps it can serve as reference. I'll update this thread when it's finished.

**Comment by Rick-Anderson** [comment]
@adravi 	how's the sample coming?

**Comment by ahaija-dev** [comment]
Any updates on this?

**Comment by Rick-Anderson** [comment]
Moved to #16209
