### ISSUE TITLE
New doc: Safe storage of app secrets in production

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#9410]
This could be a overview page with links docs on securing test/production secrets.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration
 
Security
Adopt the following best practices:
•         Never store passwords or other sensitive data in configuration provider code or in plain text configuration files.
•         Don't use production secrets in development or test environments.
•         Specify secrets outside of the project so that they can't be accidentally committed to a source code repository.
Learn more about how to use multiple environments and managing the safe storage of app secrets in development with the Secret Manager (includes advice on using environment variables to store sensitive data). The Secret Manager uses the File Configuration Provider to store user secrets in a JSON file on the local system. The File Configuration Provider is described later in this topic.
Azure Key Vault is one option for the safe storage of app secrets. For more information, see Azure Key Vault configuration provider in ASP.NET Core.

#12428 has sample code

**Comment by weifenluo** [comment]
#12428

**Comment by kabuguad** [comment]
i am hosting a web in smarterasp.net  how will i configure the secrets, or will azure key vault work for websites hosted elsewhere

**Comment by scottaddie** [comment]
@kabuguad Your app doesn't have to be hosted in Azure to use Key Vault. We have some documentation available at https://docs.microsoft.com/aspnet/core/security/key-vault-configuration. See also the official Key Vault docs at https://docs.microsoft.com/azure/key-vault/.

**Comment by Rick-Anderson** [comment]
Closing as we'll never have the resources to do this and AKV is a viable solution.
