### ISSUE TITLE
Filename from Content-Disposition

### ISSUE THREAD

**Issue by devbrsa** [aspnet/AspNetCore.Docs#9473]
Resolved.
`
ContentDispositionHeaderValue.TryParse(section.ContentDisposition, out var contentDisposition);
`
//

I don't know if is the correct place to ask, but how can I get the file name from Content-Disposition following "Uploading large files with streaming"? ty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by gmareater** [comment]
it's really a must have option here, i dont know how other work with file, but filename is necessary.

**Comment by guardrex** [comment]
Tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. Closing here, but this issue will be assessed for the updates when working the tracking issue.
