### ISSUE TITLE
InstructorCoursesPageModel.cshtml.cs base class shouldn't have .cshtml

### ISSUE THREAD

**Issue by LouBH** [aspnet/AspNetCore.Docs#9523]
Should this sentence:  
Create the Pages/Instructors/InstructorCoursesPageModel.cshtml.cs base class:

read like this?:
Create the Pages/Instructors/InstructorCoursesPageModel.cs base class:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1#update-the-instructor-pages)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@LouBH 	That would be a nice improvement since the base class doesn't have an associated view/razor page. I'll make that change when I update this.

Thanks for the suggestion.

**Comment by Rick-Anderson** [comment]
@LouBH 	I can't make that change without changing the sample.

Create the *Pages/Instructors/InstructorCoursesPageModel.cshtml.cs* base class:

`[!code-csharp[](intro/samples/cu/Pages/Instructors/InstructorCoursesPageModel.cshtml.cs)]`

**Comment by tonypitwood** [comment]
Hi there, I tried changing DepartmentNamePageModel.cs to 
DepartmentNamePageModel.cshtml.cs but it didn't seem to make any difference.
My problem is that the object inherited  from the base class
compiles OK but click on CreateNew throws an Error Object reference not set - asp-items="@Model.DepartmentNameSL">  in Courses/Create.cshtml
Holding my mouse over @Model.DepartmentNameSL shows
Select DepartmentNameModel.DepartmentNameSL { get; set; } so why would it be saying Object reference not set?
I have copied/pasted the three files, Create.cshtml and cshtml.cs and DepartmentNamePageModel.cs from Github, but still hit the error
Please help!   Pitters

**Comment by Toby9876** [comment]
I ran into this problem as well due to a validation bug of mine (see reported #9523). When the tutorial is updated to take care of this validation problem it would be nice with a solution that don't clear the validation errors. Simply repopulating the model and return seem to not render the error message that caused the validation problem (does not state the error message on the page). Or?
