### ISSUE TITLE
Create a page in docs to explain how we can localize Identity in general

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/AspNetCore.Docs#9572]
Create a page in docs to explain how we can localize Identity in general

1. Errors from identity system
2. Identity UI

https://github.com/aspnet/Identity/issues/991

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Localizing IdentityUI is not any different than localizing any other page. Simply scaffold the IdentityUI pages into your project and then us [standard localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2) techniques to localize them.
