### ISSUE TITLE
Extending PartialTagHelper

### ISSUE THREAD

**Issue by reZach** [aspnet/AspNetCore.Docs#9683]
Is it possible to extend existing tag helper classes? I am specifically trying to update the TagHelperContext in a class derived from PartialTagHelper to change the name of the view the partial is loading.

Why?
I have minified .cshtml views that I want my partial to load without changing the name property of all my &lt;partial&gt; tag helpers. I have tried to create a new TagHelperContext by overriding the Init function as well as trying to call .Reinitialize in the ProcessAsync method but that doesn't seem to be the extension point I'm looking for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1#get-started-with-tag-helpers)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@NTaylorMullen Any recommendations on how to proceed?

**Comment by reZach** [comment]
@scottaddie You can disregard this, I found out how to extend to change the view the tag helper loads. A sample file of this can be found here: https://github.com/reZach/minifynetcore/blob/master/MinifyNETCore/MinifyNETCore/TagHelpers/MPartialTagHelper.cs

**Comment by scottaddie** [comment]
@reZach Thank you for following up. I'll modify the document to discuss how to accomplish this.

**Comment by geh24** [comment]
Hello reZach,

your example code MPartialTagHelper.cs from Nov. 26 2018 helped me a lot,
but with the current net7.0 framework the Annotation
[HtmlTargetElement("partial", TagStructure = TagStructure.WithoutEndTag)]
is needed, to make the custom-class work.

best regards
Gerhard
