### ISSUE TITLE
Windows Service topic+sample update for 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#9696]
* For 3.0, there will be an inferred default runtime identifier for WS apps. See: https://github.com/aspnet/Docs/issues/9214#issuecomment-441723840
* Update the topic+sample for 3.0 (can be worked at Preview 4 release).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
It wasn't clear from the coverage to @sertunc on comment at https://github.com/aspnet/AspNetCore.Docs/pull/9988#issuecomment-492242493 why there are two `if` blocks checking for a service-based run instead of a console-based run. I think we should say why on the update here. Thanks @sertunc for calling it out.

**Comment by guardrex** [comment]
@Tratcher Working this now ... can u give me a tip on service events?

I tried it this way ...

```csharp
internal class CustomHostService : ServiceBase
{
    private ILogger _logger;

    public CustomHostService(IHost host) : base()
    { _logger = ... }

    protected override void OnStart(string[] args) { ... }
    protected override void OnShutdown() { ... }
    protected override void OnStop() { ... }
}
```

```csharp
public static void RunAsCustomService(this IHost host)
{
    var hostService = new CustomHostService(host);
    ServiceBase.Run(hostService);
}
```

```csharp
public static void Main(string[] args)
{
    var builder = CreateHostBuilder(args);

    if (ServiceHelpers.IsWindowsService())
    {
        builder.UseWindowsService();

        var host = builder.Build();
        host.RunAsCustomService();
        
        // For not using the custom service (this works)
        // builder.Build().RunAsync();
    }
    else
    {
        var host = builder.Build();
        host.RunAsync();
    }
}
```

It looks like it starts the service (e.g., I see `OnStart` in Event Viewer), but nothing runs ... no app responses, no background services running.

**Comment by Tratcher** [comment]
Do we really need the custom service example? It's given a strange level of prominence in the doc.

The 1st class story is much cleaner:
```
public static async Task Main(string[] args)
{
    var builder = CreateHostBuilder(args)
        .UseWindowsService(); // Move inside CreateHostBuilder

        var host = builder.Build();
        await host.RunAsync();
}
```

Also RunAsync needs to be `await`'d.

**Comment by guardrex** [comment]
Sounds good to me. I'll have it in tomorrow.

**Comment by guardrex** [comment]
Ah ... I see what you mean.

> .UseWindowsService(); // Move inside CreateHostBuilder

It no-ops if it isn't running as a service. Gotcha.
