### ISSUE TITLE
Add documentation for OData

### ISSUE THREAD

**Issue by boppbo** [aspnet/AspNetCore.Docs#9740]
I only found a blog post, no official documentation: https://blogs.msdn.microsoft.com/odatateam/2018/07/03/asp-net-core-odata-now-available/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@danroth27 	 should we migrate [ASP.NET Core OData now Available](https://blogs.msdn.microsoft.com/odatateam/2018/07/03/asp-net-core-odata-now-available/) to our docs?

**Comment by Rick-Anderson** [comment]
moved to #4556

**Comment by Rick-Anderson** [comment]
@danroth27 	who's the ODATA contact?

Per @danroth27

> I’m open to considering having OData docs in our docs as long as it’s the OData team that writes them.

**Comment by danroth27** [comment]
@mikepizzo Where are the ASP.NET Core OData docs published and managed?

**Comment by boppbo** [comment]
There is content in the aspnet docs: https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/
The documentation linked in the odata repository is http://odata.github.io/WebApi/
(for the lower-level api http://odata.github.io/odata.net/)

But as these are pretty extensive and partly dated ("This is the first version of this document written in April, 2015" Source: http://odata.github.io/WebApi/ ) there should be at least some kind of quick start tutorial in the aspnetcore docs. Better move all the odata-webapi content for aspnetcore  into this repo here. This is an official verified **Microsoft.AspNetCore. ...** [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.OData
) package after all.

There are even tutorials for external developed packages like [Swashbuckle ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle) and [NSwag](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag), so why not for an standard/package developed by Microsoft?
