### ISSUE TITLE
Document usage of ProducesResponseTypeAttribute

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#9789]
See #6440

@Rick-Anderson edit: 25.4 K PV - 70% CSAT
comments:

Obsolete UseSwaggerUI.
None of the steps are up to date.
the code example does not seem to be working..
o basic info on what swagger actually is and does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by tarikguney** [comment]
I have just tried the steps above, and it works fine.

**Comment by EasternBaron** [comment]
True, works for me as well... Though keep in mind that article was updated on 04/04/2019.

**Comment by spboyer** [comment]
@Rick-Anderson - it is noted now
```
In ASP.NET Core 2.2 or later, conventions can be used as an alternative to explicitly decorating individual actions with [ProducesResponseType]. For more information, see [Use web API conventions.](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2)
```
Close?
