### ISSUE TITLE
SEO updates

### ISSUE THREAD

**Issue by tdykstra** [aspnet/AspNetCore.Docs#9866]
Folders:

azure -- @CamSoper 
client-side - mikeblome
data - mikeblome
fundamentals - tdykstra
getting-started
host-and-deploy
migration	
mobile	
mvc - tdykstra	
performance
razor-pages - @CamSoper 
release-notes
security -- @CamSoper
signalr - tdykstra
test	
tutorials - tdykstra

**Comment by mikeblome** [comment]
@tdykstra I'll take client-side and data. (I don't have edit permissions on your comment)

**Comment by tdykstra** [comment]
Leave as-is.  There are almost none that are unbranded.

**Comment by tdykstra** [comment]
Closing, as this was created for the December, 2018 SEO hackathon.
